BUG: GH13629 Binned groupby median function calculates median on empt…
pandas-dev/pandas pull request #14225
Opened 2016-09-15 01:57 UTC by paul-mannino

- [ x] closes #13629
 - [ x] tests added / passed
 - [ x] passes ``git diff upstream/master | flake8 --diff``
 - [x ] whatsnew entry

2016-09-17 13:07 UTC, chris-b1 commented on pandas/core/groupby.py
> +        keys, counts = _hash.value_count_int64(codes, False)
Rather than adjusting the hash table value counts, I think you could use `np.bincount` here? - see  `Categorical.value_counts`

2016-09-17 13:12 UTC, chris-b1 commented on pandas/tests/test_groupby.py
> +            expected = df.groupby(pd.cut(df[0], grps)).agg(targop)
Because `agg` intercepts methods (i.e. `np.median` is interpreted as `'median'`), this wouldn't fail on master - wrap the targop in a lambda.

2016-09-17 13:13 UTC, chris-b1 commented on pandas/tests/test_groupby.py
> +            expected = df.groupby(pd.cut(df[0], grps)).agg(targop)
Can you also add a test that hits the public api (e.g. `df.groupby(...).median()`)?

2016-09-17 13:16 UTC, chris-b1 requested changes
...

2016-09-18 14:23 UTC, paul-mannino commented on pandas/core/groupby.py
> +        keys, counts = _hash.value_count_int64(codes, False)
Per your suggestion, I borrowed some of the logic from Categorical.value_counts. The mask.all() check seemed to make the code run slower in this case, so I left it out.

2016-09-18 15:47 UTC, chris-b1 approved these changes

2016-09-18 15:48 UTC, chris-b1 commented
lgtm, @jreback?

2016-09-18 15:54 UTC, jreback approved these changes

2016-09-18 15:54 UTC, jreback commented
lgtm

merge away

2016-09-18 15:57 UTC, merged

2016-09-18 22:36 UTC, paul-mannino commented on pandas/core/groupby.py
> +        if not counts.size == values.categories.size:
The _algos.groupby_indices function expects a counts array that is the same length as the categories. If one of the categories has no values in it (empty bins), the _hash.value_count_int64 function would just return a shorter count array (with no 0 entries for empty categories/bins). My initial approach was to pad the array with 0s in the right places, but per chris-b1's suggestion, I used np.bincount instead.