ENH: Allow usecols to accept callable (GH14154)
pandas-dev/pandas pull request #14234
Opened 2016-09-16 04:08 UTC by WillAyd

- [ X] closes #14154 
- [ X] tests added / passed
- [ X] passes `git diff upstream/master | flake8 --diff`
- [X ] whatsnew entry
  <img width="1515" alt="asv_bench" src="https://cloud.githubusercontent.com/assets/609873/18575075/942a9240-7ba1-11e6-9dca-bab8b9987f31.png">

2016-09-16 10:28 UTC, jreback commented on pandas/io/parsers.py
> +            return usecols
you can just in-line ``_evaluate_usecols`` here, then change ``_vaidate_usecols`` to return the usecols and set it

2016-09-16 10:28 UTC, jreback requested changes

2016-09-16 10:29 UTC, jreback commented on pandas/io/parsers.py
>      inferred from the document header row(s). For example, a valid `usecols`
can you add a mini-example of a callable

2016-09-16 10:29 UTC, jreback requested changes

2016-09-16 22:27 UTC, WillAyd commented on pandas/io/parsers.py
> +            return usecols
Took a look but don't think that would work.  The problem seems to be the names argument that's a requirement for `_evaluate_usecols`.  

Unless I'm missing something I think I'd have to modify `_validate_usecols` to accept names as an argument, but it's currently being called before the names are even set (unless explicitly passed as an argument to the `read` function)

2016-11-25 14:37 UTC, jreback commented
can you rebase, move whatsnew notes to 0.20.0, and add an example as indicated

2016-11-25 22:45 UTC, WillAyd commented
Requested changes should have been made - let me know if there's anything else you would like to tweak for this enhancement

2016-11-25 22:48 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- The ``usecols`` argument now accepts a callable function as a value  (:issue:`14154`)
The ``usecols`` argument in ``pd.read_csv``

2016-11-25 22:49 UTC, jreback commented on pandas/io/parsers.py
> +    else:
just return is fine here (no else)

2016-11-25 22:51 UTC, jreback commented on pandas/io/tests/parser/usecols.py
> +               "all integers or callable")
same

2016-11-25 22:51 UTC, jreback commented on pandas/io/tests/parser/usecols.py
> +        s = '''AaA,bBb,CCC,ddd
can you add the issue number as a comment

2016-11-25 22:54 UTC, jreback commented on pandas/parser.pyx
> +                self.callable_usecols = 1
I would not use this additional variable and instead just do a ``callable(self.usecalls)`` I think its more obvious

2016-11-25 22:54 UTC, jreback commented
@WillAyd thanks. couple more pretty minor comments. otherwise lgtm.

2016-11-27 17:51 UTC, WillAyd commented
All of your requested changes should be accounted for.  Let me know if anything else comes to mind.

2016-11-28 09:38 UTC, jorisvandenbossche reviewed
Apart from the docstring and whatsnew, can you also update the IO docs in two places:

- overview of keywords: http://pandas.pydata.org/pandas-docs/stable/io.html#column-and-index-locations-and-names
- section on usecols: http://pandas.pydata.org/pandas-docs/stable/io.html#filtering-columns-usecols (I would add an example of a callable there)

2016-11-28 09:38 UTC, jorisvandenbossche commented on pandas/io/parsers.py
> +    parsing time and lower memory usage.
Can you add before the example some explanation how the callable is used? (I suppose it is called on each individual column name and should return True or False?)

And maybe also use ``` `` ``` around the code example to better indicate that the "in ['AAA', 'BBB', 'DDD']" still belongs with the "lambda x: x.upper()"

2016-11-28 09:38 UTC, jorisvandenbossche commented on pandas/io/parsers.py
> +                    if com._apply_if_callable(usecols, name)])
I think the `com._apply_if_callable` is not needed anymore as you already did `if callable(usecols)`? (apply_if_callable does exactly the same under the hood)

2016-11-28 09:38 UTC, jorisvandenbossche commented on pandas/io/tests/parser/usecols.py
> +        tm.assert_frame_equal(df, expected)
Can you add a test that `lambda x: False` return an empty frame? (similar to the test_empty_usecols above)

2016-11-28 09:38 UTC, jorisvandenbossche commented on pandas/parser.pyx
> +                    if com._apply_if_callable(self.usecols, name):
same here, `com._apply_if_callable` is not needed I think

2016-11-30 00:02 UTC, WillAyd commented
I noticed that the Travis-CI build failed for OS X.  I didn't see anything useful in the log and checking their website it appears that the failure may have stemmed from issues on their end and not necessarily from the code.  Do you have a preferred method to restart that build?  Should I close / re-open the PR or do you have another way you'd like to restart that test?

<img width="868" alt="screen shot 2016-11-29 at 7 01 45 pm" src="https://cloud.githubusercontent.com/assets/609873/20734278/66c770c0-b666-11e6-9525-e87de7899461.png">

2016-11-30 00:04 UTC, jreback commented
I restarted the job.

2016-12-04 23:46 UTC, jreback commented on doc/source/io.rst
> +  `usecols` parameter would be [0, 1, 2] or ['foo', 'bar', 'baz']. If callable,
since this is docs, you can format this to read easier. (use an ipython block), blank line

2016-12-04 23:47 UTC, jreback commented on pandas/io/parsers.py
> +    returning names where the callable function evaluates to True. An example
you can't format this (like you can an .rst), but maybe a blank line or some bullet points?

2016-12-04 23:47 UTC, jreback commented on pandas/io/parsers.py
> +    if callable(usecols):
can you give a mini-doc string here

2016-12-04 23:49 UTC, jreback commented
@WillAyd just a couple of minor comments. ping when green.

2016-12-04 23:49 UTC, jreback approved these changes

2016-12-06 04:56 UTC, WillAyd commented
@jreback pushed some edits to cover your latest comments.  Let me know if there's anything else you'd like on this

2016-12-06 11:03 UTC, jorisvandenbossche approved these changes

2016-12-06 11:29 UTC, jreback commented
lgtm. ping on green.

2016-12-06 11:38 UTC, merged

2016-12-06 11:38 UTC, jorisvandenbossche commented
@WillAyd Thanks!