BUG: fix alignment in series ops (GH14227)
pandas-dev/pandas pull request #14230
Opened 2016-09-15 17:55 UTC by jorisvandenbossche

- [x] closes #14227
 - [x] tests added / passed
 - [ ] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

2016-09-15 21:47 UTC, jreback commented on pandas/core/ops.py
> +            if is_datetime64tz_dtype(left.index):
should be inside ``.join`` not here

2016-09-15 21:47 UTC, jreback requested changes

2016-09-15 21:48 UTC, jorisvandenbossche commented on pandas/core/ops.py
> +            if is_datetime64tz_dtype(left.index):
Do you mean in `align` ?

2016-09-15 21:50 UTC, jreback commented on pandas/core/ops.py
> +            if is_datetime64tz_dtype(left.index):
yes, that's what I mean

2016-09-20 10:31 UTC, jreback commented
@jorisvandenbossche can you update

2016-09-30 10:31 UTC, jorisvandenbossche commented
@jreback I moved this to align (and therefore also fixing the bug in align), but it is still not yet that clean ... 
So the problem for tz aware indexes is that `Index.join` does not returns indexers when the result does not need to be reindexed (although in case of tz aware indexes the actual indexes can be different and have to be adapted), and based on that the index of the result is adapted in `align` or not. So I still have to check for this specific case. I tried to solve it in `Index.join` itself, but that caused other errors.

2016-09-30 13:02 UTC, jreback commented
if this works (and you want to push in 0.19.0), ok.. maybe just add a TODO / issue to fix/clean later.

2016-09-30 21:22 UTC, jorisvandenbossche commented
Well, it was a hack before, and it is still the exact same hack now, only moved down the stack into align (fixing the behaviour of align as well), so merging for now.

2016-09-30 21:23 UTC, merged