BUG: float truncation in eval with py 2
pandas-dev/pandas pull request #14255
Opened 2016-09-20 00:43 UTC by chris-b1

- [x] closes #14241
 - [ ] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew entry

Python 2 only - apparently `str()` rounds shorter than `repr()`

```
In [1]: f = 1000000000.006

In [2]: str(f)
Out[2]: '1000000000.01'

In [3]: repr(f)
Out[3]: '1000000000.006'
```

2016-09-20 10:19 UTC, jreback commented on pandas/computation/ops.py
> +        return repr(self.name)
I bet this is a similar problem when selecting from pytables, can you add a test for that?

2016-09-20 10:19 UTC, jreback requested changes

2016-09-21 01:46 UTC, chris-b1 commented on pandas/computation/ops.py
> +        return repr(self.name)
Added a test/fix for this

2016-09-21 10:10 UTC, jreback commented
can you change the pytables test to add 3 values, then have the scalar select the middle one select and having it return empty doesn't prove it works, more like proves it doesn't not work :>

2016-09-21 22:33 UTC, jreback commented on pandas/computation/tests/test_eval.py
> +        result = df.query('A == %.4f' % exact)
oh I didn't mean for this last one to be ``==``, it *might* work but I wouldn't guarantee it (as float equality esp when you store may not be guaranteed )

2016-09-21 22:33 UTC, jreback requested changes

2016-09-21 22:44 UTC, chris-b1 commented on pandas/computation/tests/test_eval.py
> +        result = df.query('A == %.4f' % exact)
I know float precision is thorny generally, but shouldn't this be guaranteed with HDF5?

2016-09-21 23:01 UTC, jreback commented
i don't know how equality of floats works in numexpr / HDF5

it might test well for us but fail on some platforms (just a guess) - so include if passes

2016-09-22 10:20 UTC, closed without merging

2016-09-22 10:20 UTC, jreback commented
thanks!