BUG: Fix concat key name
pandas-dev/pandas pull request #14292
Opened 2016-09-23 19:44 UTC by bkandel

- [x] closes #14252
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew entry

Fixes a bug where `pd.concat` didn't propagate the names of keys used to create
a hierarchical index.

2016-09-23 19:46 UTC, jreback commented on pandas/tests/frame/test_combine_concat.py
> +        assert_equal(concatted.index.names, FrozenList(['baz', None]))
always use assert_frame_equal and construct and expected frame

2016-09-23 19:47 UTC, jreback commented on pandas/tools/merge.py
> +            self.names = names
names or getattr(keys, 'names', None)

2016-09-23 19:48 UTC, jreback requested changes

2016-09-23 20:02 UTC, bkandel commented on pandas/tests/frame/test_combine_concat.py
> +        assert_equal(concatted.index.names, FrozenList(['baz', None]))
fixed

2016-09-23 20:02 UTC, bkandel commented on pandas/tools/merge.py
> +            self.names = names
fixed

2016-09-23 22:43 UTC, bkandel commented on pandas/tests/frame/test_combine_concat.py
> +        assert_equal(concatted.index.names, FrozenList(['baz', None]))
I'm not sure that `assert_frame_equal` checks for names of indices here.

2016-09-23 22:47 UTC, jreback commented on pandas/tests/frame/test_combine_concat.py
> +        assert_equal(concatted.index.names, FrozenList(['baz', None]))
sure it does
see doc string

2016-09-25 02:57 UTC, bkandel commented on pandas/tests/frame/test_combine_concat.py
> +        assert_equal(concatted.index.names, FrozenList(['baz', None]))
I see -- fixed now. Also added a couple extra test cases.

2016-09-27 22:15 UTC, jreback commented on pandas/tools/merge.py
> +            clean_keys_index = Index(clean_keys_list)
use ``_ensure_index``

2016-09-27 22:16 UTC, jreback commented on pandas/tools/merge.py
> +            if isinstance(keys, Index):
this logic seems convoluted, can you simplify?

2016-09-28 12:58 UTC, TomAugspurger commented on pandas/tools/merge.py
> +            if isinstance(keys, Index):
Seems like you should be able to change the name of `clean_keys_list` back to `clean_keys` and

```python
if isinstance(keys, Index):
    keys = Index(clean_keys, name=keys.name)
```

2016-09-30 17:38 UTC, bkandel commented on pandas/tools/merge.py
> +            clean_keys_index = Index(clean_keys_list)
Fixed.

2016-09-30 17:38 UTC, bkandel commented on pandas/tools/merge.py
> +            if isinstance(keys, Index):
Fixed.

2016-10-02 00:26 UTC, bkandel commented
@jreback I think all comments are addressed now.

2016-10-07 20:04 UTC, bkandel commented
@jreback Changed whatsnew entry to 0.19.1. Is there anything left to do before merging?

2016-10-08 14:46 UTC, jreback commented on pandas/tools/merge.py
> +            keys = _ensure_index(Index(clean_keys))
hmm I don't think you need the ``_ensure_index`` if you are forcing the index

2016-10-09 12:27 UTC, bkandel commented on pandas/tools/merge.py
> +            keys = _ensure_index(Index(clean_keys))
yes appears that is correct: https://github.com/pydata/pandas/pull/14292/commits/cdc76f6f0e2fd5e307f3a335afc23385d1e8234f looks fine.

2016-10-09 17:38 UTC, closed without merging

2016-10-09 17:38 UTC, jreback commented
thanks @bkandel