Enforce boolean types
pandas-dev/pandas pull request #14318
Opened 2016-09-29 06:10 UTC by rforgione

- [ x ] closes #14189
 - [ x ] tests added / passed
 - [ ] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

This PR only addresses the `inplace` argument, though there was a comment on #14189 that identifies the issue as being with the `copy` argument as well. I can build this out further to account for all of the frequently occurring boolean arguments.

I also wrote tests for the common function `_enforce_bool_type`, but didn't write individual tests for every method with an `inplace` argument. This is something I can add if it makes sense. I wanted to get something reviewed sooner rather than later to get feedback and ensure that I'm on the right track. Feedback is much appreciated -- thanks!

2016-09-29 09:21 UTC, jreback requested changes

2016-09-29 09:21 UTC, jreback commented on pandas/computation/eval.py
> -        in a future version, will default to False.  Use inplace=True
don't change this

2016-09-29 10:42 UTC, jreback commented on pandas/computation/eval.py
> -        in a future version, will default to False.  Use inplace=True
this will be an explict decision to remove.

2016-09-29 10:47 UTC, jreback commented
call this ``_validate_bool_type``, should accept ``None`` as valid. (just ignore)

use ``pandas.types.common.is_bool`` (for consistency with other routines)

put this in ``pandas.types.validate`` (make a new module). add tests in ``pandas.tests.types.test_validate``. Need to cover each routine that is covered (just a smoke test, IOW, just loop thru a couple of invalid values and make sure it raises)

2016-10-01 02:12 UTC, rforgione commented
thanks for the feedback @jreback, will work on these!

2016-10-06 10:40 UTC, jreback commented on pandas/computation/eval.py
> +         target=None, inplace=False):
don't change this

2016-10-06 10:40 UTC, jreback commented on pandas/computation/eval.py
> +    inplace : bool, default False
nor this

2016-10-27 14:13 UTC, jorisvandenbossche commented
@rforgione Do you have time to update this?

2016-10-28 20:43 UTC, rforgione commented
@jorisvandenbossche yeah, apologies. Things have been a little crazy with my day job of late. I'll dig into this over the weekend.

2016-10-29 13:19 UTC, jorisvandenbossche commented
@rforgione No problem, just ping here when you updated it

2016-12-02 08:10 UTC, rforgione commented
hey @jorisvandenbossche / @jreback -- sorry for the delay on this. I think I knocked out more-or-less all of the feedback items listed by @jreback above. I struggled a little with some of the tests for internals.py, namely for the putmask method on the NonConsolidatableMixIn class, and the _replace_single method on the ObjectBlock class (I had trouble instantiating the appropriate classes to run tests on). I'd be happy to write tests for those if you wouldn't mind pointing me in the right direction. Any other thoughts/feedback are appreciated. Thanks!

2016-12-04 18:03 UTC, jreback commented on pandas/computation/eval.py
> +from pandas.core import common as com
this will fail linting (as not used)

2016-12-04 18:04 UTC, jreback commented on pandas/core/frame.py
> +    def eval(self, expr, inplace=True, **kwargs):
leave this alone

2016-12-04 18:05 UTC, jreback commented on pandas/types/validate.py
> +    if not com.is_bool(value) and not value is None:
``not (is_bool(value) or value is None))``

2016-12-04 18:05 UTC, jreback commented on pandas/types/validate.py
> +from pandas.types import common as com
``from pandas.types.common import is_bool``

2016-12-04 18:09 UTC, jreback commented
@rforgione looks pretty good. just a few more comments.

2016-12-04 18:09 UTC, jreback commented
pls add a whatsnew for 0.20.0.

2016-12-04 19:17 UTC, rforgione commented on pandas/core/frame.py
> +    def eval(self, expr, inplace=True, **kwargs):
missed this one when reverting all of my original changes, thanks for pointing out!

2016-12-04 19:26 UTC, rforgione commented on pandas/tests/types/test_validate.py
> +from unittest import TestCase
@jreback how should we handle tests unrelated to the series and the dataframe, for instance the `Categorical` class? Should we add an additional test_validate file in the tests/ directory to account for those that don't fit under series and frame? Similarly I'd assume we could place put the `eval` tests inside computation/tests/test_validate or something like that. Thanks!

2016-12-04 19:28 UTC, jreback commented on pandas/tests/types/test_validate.py
> +from unittest import TestCase
you can put the categorical tests in tests_categorical. iow, these tests go with the type that they are testing.

2016-12-04 20:04 UTC, rforgione commented on pandas/tests/types/test_validate.py
> +from unittest import TestCase
Got it, thanks @jreback

2016-12-04 21:36 UTC, jorisvandenbossche commented
One concern about this PR I have is that if you now call a method with argument with a wrong type (eg like `df.where(lambda x: x > 4, lambda x: x + 10, 'fail')` as the original example in the issue), you simply get the error message "ValueError: Expected type bool, received type str". From this it is not clear at all that it is about the inplace keyword. 
So I think you should either make this validation function specific for `inplace` and add that to the error message, or either pass in the keyword name we are checking to the `_validate_bool_type` function (to include it in the error message) in all places.

2016-12-04 21:48 UTC, rforgione commented
@jorisvandenbossche I like the second suggestion. I can add a second argument to the `_validate_bool_type` function and pass the argument name as a string in each instance throughout the code base (so if I'm testing the `inplace` argument, I can call `_validate_bool_type(inplace, 'inplace')` where `_validate_bool_type` will use the string to create a more specific error message). Is that what you had in mind @jorisvandenbossche ?

2016-12-05 02:23 UTC, rforgione commented
@jreback @jorisvandenbossche I pushed the discussed changes, feel free to take a look. Any additional feedback is appreciated!

2016-12-05 11:07 UTC, jreback requested changes

2016-12-05 11:07 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +
thrown -> raised

2016-12-05 11:07 UTC, jreback commented on pandas/sparse/tests/test_list.py
> +        for value in invalid_values:
this is deprecated so need to assert_produces_warning as well

2016-12-05 11:07 UTC, jreback commented on pandas/tests/frame/test_validate.py
> +    df = DataFrame({'a':[1,2], 'b':[3,4]})
1 line comment on what this is checking

2016-12-05 11:07 UTC, jreback commented on pandas/tests/series/test_validate.py
> +
same here

2016-12-05 11:07 UTC, jreback commented on pandas/tests/test_categorical.py
> +        invalid_values = [1, "True", [1,2,3], 5.0]
same

2016-12-05 11:07 UTC, jreback commented on pandas/tests/test_categorical.py
> +        invalid_values = [1, "True", [1,2,3], 5.0]
nvm this one is descriptive enough

2016-12-05 11:07 UTC, jreback commented on pandas/tests/test_internals.py
> +        invalid_values = [1, "True", [1,2,3], 5.0]
internals shouldn't have tests for this at all (or even check)

you can assert if u want

2016-12-05 11:07 UTC, jreback commented on pandas/tests/types/test_validate.py
> +        for value in invalid_values:
add tests that are valid, iow True, False, None

2016-12-06 22:31 UTC, jorisvandenbossche commented on pandas/core/categorical.py
> +        return self.set_ordered(True, inplace=_validate_bool_type(inplace, 'inplace'))
This line is too long (PEP8, that is the reason travis is failing). You can put the validation of inplace on its own line

2016-12-06 22:31 UTC, jorisvandenbossche commented on pandas/core/categorical.py
> +        return self.set_ordered(False, inplace=_validate_bool_type(inplace, 'inplace'))
same here

2016-12-06 22:31 UTC, jorisvandenbossche commented on pandas/sparse/tests/test_list.py
> +        for value in invalid_values:
or just leave out this test, since its deprecated it's not that important to test this

2016-12-06 22:31 UTC, jorisvandenbossche commented on pandas/tests/series/test_validate.py
> +    s = Series([1,2,3,4,5])
missing spaces after commas (PEP8). You can see on travis what is all failing: https://travis-ci.org/pandas-dev/pandas/jobs/181229873 (scroll down, at the bottom there is a list of failures)

2016-12-06 22:31 UTC, jorisvandenbossche commented on pandas/types/validate.py
> +        raise ValueError('For argument %s expected type bool, received type %s.' %\
Can you insert quotes around `%s`? (make it clearer that is the arg name), like `"Argument '%s' exp ..."`

2016-12-06 22:34 UTC, jorisvandenbossche commented on pandas/types/validate.py
> +def _validate_bool_type(value, arg_name):
I would maybe call this `_validate_bool_kwarg` to make it clearer that it is specifically to validate a keyword

2016-12-07 03:46 UTC, rforgione commented on pandas/types/validate.py
> +def _validate_bool_type(value, arg_name):
@jorisvandenbossche would you recommend making the validation function itself accept a keyworded variable-length argument? or leave as is and just rename?

2016-12-07 22:29 UTC, rforgione commented
just a couple of more changes to pass the Travis tests, will work on these tonight

2016-12-08 12:19 UTC, jreback commented on pandas/types/validate.py
> +def _validate_bool_kwarg(value, arg_name):
move this to: https://github.com/pandas-dev/pandas/blob/master/pandas/util/validators.py

had forgotten that we put input validations here

2016-12-08 12:20 UTC, jreback commented on pandas/tests/types/test_validate.py
> +                _validate_bool_kwarg(value, name)
move this to pandas/util/tests where other validation tests are)

2016-12-11 22:49 UTC, jreback commented on pandas/core/series.py
> +            kwargs['inplace'] = validate_bool_kwarg(kwargs['inplace'], 'inplace')
``kwargs['inplace'] = validate_bool_kwarg(kwargs.get('inplace', False), 'inplace')``
works?

2016-12-11 22:50 UTC, jreback commented on pandas/util/validators.py
> +    if not (is_bool(value) or value is None):
can you add a doc-string here

2016-12-11 22:50 UTC, jreback approved these changes

2016-12-11 22:51 UTC, jreback commented
just some very minor comments.

ping on green.

2016-12-14 11:25 UTC, jorisvandenbossche commented on pandas/util/validators.py
> +        raise ValueError('For argument "%s" expected type bool, ' % arg_name +\
the `\` is not needed here

2016-12-30 21:24 UTC, jreback commented
can you rebase

2017-01-05 14:46 UTC, rforgione commented
@jreback @jorisvandenbossche it's not immediately clear to me why the first set of tests is failing. I looked at the output in Travis but not seeing anything (literally blank output). Any idea what's going on? Was about to rebase but wanted to check in on this first.

2017-01-06 04:55 UTC, rforgione commented
@jreback @jorisvandenbossche figured it out -- I needed to re-build after I rebased against the upstream changes. All checks are on green, I think we are good to go!

2017-01-06 12:33 UTC, merged

2017-01-06 12:33 UTC, jorisvandenbossche commented
@rforgione Thanks!