TST: #14345 fixes TestDatetimeIndexOps test_nat AssertionErors
pandas-dev/pandas pull request #14347
Opened 2016-10-05 00:01 UTC by MattRijk

- [ ] closes #14345 
       all tests now pass on 32bit linux install.

2016-10-05 00:16 UTC, jreback requested changes

2016-10-05 00:16 UTC, jreback commented on pandas/tseries/tests/test_base.py
> +    #     self.assertIs(pd.TimedeltaIndex._na_value, pd.NaT)
what the heck are you commenting out a test?

2016-10-05 00:16 UTC, jreback commented on pandas/tseries/tests/test_base.py
> +    #     self.assertIs(pd.TimedeltaIndex._na_value, pd.NaT)
if it's incorrect it should be deleted (but it's not)
it can be skipped on paticular platforms if needed
but this should work on 32bit

2016-10-05 00:16 UTC, jreback commented on pandas/tseries/tests/test_base.py
> +
pls don't change the formatting unless it's germane (this line is too long anyhow)

2016-10-05 00:16 UTC, jreback commented on pandas/tseries/tests/test_base.py
> -        self.assertTrue(idx._can_hold_na)
same here

2016-10-05 00:40 UTC, MattRijk commented on pandas/tseries/tests/test_base.py
> -        self.assertTrue(idx._can_hold_na)
Sorry about that forgot i commented those out when i was figuring out the error. 
I installed pandas on 32bit ubuntu, ran all the nosetests and keep getting that AssertionError.
Should i change it to intp or leave it?

2016-10-05 00:41 UTC, jreback commented on pandas/tseries/tests/test_base.py
> -        self.assertTrue(idx._can_hold_na)
the intp is correct

2016-10-05 11:44 UTC, jreback commented on pandas/tseries/tests/test_base.py
> +        self.assertIs(pd.DatetimeIndex._na_value, pd.NaT)
pls revert whitespace changes.

2016-10-05 11:44 UTC, jreback commented on pandas/tseries/tests/test_base.py
> +
same

2016-10-05 11:44 UTC, jreback commented on pandas/tseries/tests/test_base.py
> +            tm.assert_numpy_array_equal(idx._nan_idxs,
you seem to be adding whitespace at the end of the line

2016-10-05 11:44 UTC, jreback commented on pandas/tseries/tests/test_base.py
> +
same (and below)

2016-10-05 16:05 UTC, jorisvandenbossche commented on pandas/tseries/tests/test_base.py
> +
@MattRijk If you look at the log of the failing travis build, at the bottom you will see the output of the linter:

```
pandas/tseries/tests/test_base.py:860:58: W291 trailing whitespace
pandas/tseries/tests/test_base.py:862:1: W293 blank line contains whitespace
pandas/tseries/tests/test_base.py:866:1: W293 blank line contains whitespace
pandas/tseries/tests/test_base.py:869:55: W291 trailing whitespace
pandas/tseries/tests/test_base.py:871:1: W293 blank line contains whitespace
pandas/tseries/tests/test_base.py:877:55: W291 trailing whitespace
pandas/tseries/tests/test_base.py:1713:1: W293 blank line contains whitespace
pandas/tseries/tests/test_base.py:1716:1: W293 blank line contains whitespace
pandas/tseries/tests/test_base.py:1721:1: W293 blank line contains whitespace
pandas/tseries/tests/test_base.py:1724:1: W293 blank line contains whitespace
pandas/tseries/tests/test_base.py:2710:1: W293 blank line contains whitespace
pandas/tseries/tests/test_base.py:2713:1: W293 blank line contains whitespace
pandas/tseries/tests/test_base.py:2718:1: W293 blank line contains whitespace
pandas/tseries/tests/test_base.py:2721:1: W293 blank line contains whitespace
```

You can normally set your editor to automatically remove trailing white space, then you would normally have less of such issues.

2016-10-06 10:21 UTC, jreback approved these changes

2016-10-06 10:22 UTC, jreback commented
thanks @MattRijk lgtm.

2016-10-06 10:23 UTC, closed without merging