Frequency empty series fix
pandas-dev/pandas pull request #14340
Opened 2016-10-03 22:57 UTC by sahildua2305

- [x] closes #14320 
 - [x] tests added / passed
 - [ ] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

2016-10-03 22:59 UTC, jreback requested changes
add a release note in 0.20

2016-10-03 22:59 UTC, jreback commented on pandas/tests/frame/test_timeseries.py
> +        self.assertEqual(s.index.freq, 'H')
construct an expected series and test against that

2016-10-04 22:10 UTC, sahildua2305 commented on pandas/tests/frame/test_timeseries.py
> +        self.assertEqual(s.index.freq, 'H')
Done! Please check.

2016-10-06 10:48 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- Bug in ``asfreq``, where frequency wasn't set for empty series (:issue:`14320`)
series -> ``Series``

2016-10-06 10:48 UTC, jreback commented on pandas/tests/frame/test_timeseries.py
> +        empty_series = Series(index=pd.DatetimeIndex([]), data=[]).asfreq('H')
add the issue number as a comment

2016-10-06 10:49 UTC, jreback commented on pandas/tests/frame/test_timeseries.py
> +        normal_series = Series(index=pd.DatetimeIndex(["2016-09-29 11:00"]),
expected =

2016-10-06 10:49 UTC, jreback commented on pandas/tests/frame/test_timeseries.py
> +        self.assertEqual(empty_series.index.freq, normal_series.index.freq)
use ``tm.assert_series_equal``

2016-10-13 16:41 UTC, sahildua2305 commented on pandas/tests/frame/test_timeseries.py
> +        self.assertEqual(empty_series.index.freq, normal_series.index.freq)
@jreback But we actually want to compare the frequency of the index not the complete series. Also, if we have one empty and one non-empty series, how can we use `assert_series_equal` method?

2016-10-19 12:30 UTC, jreback commented
@sahildua2305 you need to rebase on master

``git rebase -i origin/master``

2016-10-19 12:46 UTC, sahildua2305 commented
Oops! Last time I rebased this branch it was fine. I will do that again.

2016-10-19 12:50 UTC, jreback commented
if that doesn't work, then close and open a new PR. We had shifted the url of the repo.

2016-10-19 12:53 UTC, sahildua2305 commented
Sure!

2016-10-19 23:26 UTC, closed without merging