PERF: period factorization
pandas-dev/pandas pull request #14348
Opened 2016-10-05 02:15 UTC by chris-b1

- [x] closes #xxxx
 - [ ] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

asv (reversed)
```
   before     after       ratio
  [c41c6511] [96b364a4]
+   47.50ms      2.39s     50.37  groupby.groupby_period.time_groupby_sum
```

cc @sinhrks , @bmoscon

2016-10-05 11:35 UTC, jreback requested changes

2016-10-05 11:35 UTC, jreback commented on asv_bench/benchmarks/groupby.py
> +    def setup(self):
can you add similar benches for dti and dti w/tz

2016-10-05 11:36 UTC, jreback commented on asv_bench/benchmarks/groupby.py
> +    def setup(self):
ideally inherit from a common class

2016-10-05 11:37 UTC, jreback commented on pandas/core/algorithms.py
> +        vals = values.view(np.int64)
use ``values.asi8``

2016-10-05 11:37 UTC, jreback commented on pandas/core/algorithms.py
> +    if is_period_dtype(values):
make an elif

2016-10-05 11:38 UTC, jreback commented on pandas/core/algorithms.py
> +    if is_period_dtype(values):
maybe add a comment here about what is going on (helpful to future readers)

2016-10-05 12:06 UTC, bmoscon commented
thanks for taking care of this. It looks like this  is targeted for 0.19.1; any rough idea when that will be released?

2016-10-06 09:14 UTC, jorisvandenbossche commented
Looks good to me. We only should include a whatsnew notice, depending on the outcome of https://github.com/pydata/pandas/issues/14352

2016-10-13 20:01 UTC, jorisvandenbossche commented
Looks good to me! @jreback

2016-10-13 20:13 UTC, closed without merging

2016-10-13 20:14 UTC, jorisvandenbossche commented
@chris-b1 whoops, sorry, closed this and I don't see a reopen button ..

2016-10-13 20:16 UTC, chris-b1 commented
Strange, I can't reopen either, will just make a new PR

2016-10-13 20:17 UTC, chris-b1 commented
#14419

2016-10-13 20:18 UTC, jorisvandenbossche commented
Possibly some glitches due to the repo transfer. Older PRs are also stuck on "Checking for ability to merge automatically…" (that was the reason I wanted to close/reopen this one to retrigger it)