Convert float freqstrs to ints at finer resolution
pandas-dev/pandas pull request #14378
Opened 2016-10-08 16:32 UTC by jisantuc

- [x] closes #8419 
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

Passing `'0.5min'` as a frequency string should generate 30 second
intervals, rather than five minute intervals. By recursively increasing
resolution until one is found for which the frequency is an integer,
this commit ensures that that's the case for resolutions from days to
microsecond

2016-10-08 18:02 UTC, jreback requested changes

2016-10-08 18:02 UTC, jreback commented on pandas/tseries/tests/test_frequencies.py
> +        self.assertEqual(Reso.bump_to_int(62.4, 'T'), (3744, 'S'))
can u exercise some more fail cases
and systematically cover cases that should succeed

2016-10-08 23:46 UTC, sinhrks commented on pandas/tseries/frequencies.py
> +                raise ValueError(_CANNOT_CONVERT_TO_INT)
pls move error message here, because the message is used only once.

2016-10-08 23:46 UTC, sinhrks commented on pandas/tseries/frequencies.py
> +        'U': None
Pls add Nanosecond.

2016-10-08 23:46 UTC, sinhrks commented on pandas/tseries/tests/test_frequencies.py
> +        self.assertEqual(Reso.bump_to_int(62.4, 'T'), (3744, 'S'))
Pls also add some failure cases with invalid str, such as ``1.5.0S``, ``1.S``.

2016-10-08 23:46 UTC, sinhrks commented on pandas/tseries/tests/test_frequencies.py
> -            frequencies.to_offset('.5S')
Can you change it to compare with 500 milisec.

2016-10-08 23:46 UTC, sinhrks commented on doc/source/whatsnew/v0.19.1.txt
> +- Bug in date range treating e.g. 0.5s as 5s (:issue:`8419`)
can you add occurrence condition, like

- Bug in multiple offset aliases with decimal points is regarded as int (e.g. 0.5s as 5s).

2016-10-08 23:46 UTC, sinhrks commented on pandas/tseries/frequencies.py
> +    def bump_to_int(cls, value, freq):
can the method name be clearler, like``get_stride_from_decimal``

2016-10-08 23:46 UTC, sinhrks commented on pandas/tseries/frequencies.py
> +        Increase resolution an integer value is available to create an
Convert freq with decimal stride to higher freq with integer stride.

2016-10-08 23:46 UTC, sinhrks commented on pandas/tseries/tests/test_frequencies.py
> -            frequencies.to_offset('.5S')
Also pls add some tests whether this works with combined offset, like ``.5H.5S``.

2016-10-09 15:49 UTC, jisantuc commented on pandas/tseries/tests/test_frequencies.py
> -            frequencies.to_offset('.5S')
`1.S` is valid now, parsed as `1 second`. Should it not be?

2016-10-09 17:22 UTC, jreback commented on pandas/tseries/frequencies.py
> +NS_RESO = 0
so would be nice to clean this up. This is essentially an Enum, but that only exists in 3.5 (maybe we could add the backport of https://pypi.python.org/pypi/enum34 as an in-inline package), not sure this is worth it though.

In any event just put these in a list and ``enumerate`` if needed.

2016-10-11 00:46 UTC, sinhrks commented on pandas/tseries/tests/test_frequencies.py
> -            frequencies.to_offset('.5S')
You're right. should be 1 sec like ``float("1.")`` is valid.

2016-10-11 01:44 UTC, jisantuc commented on pandas/tseries/frequencies.py
> +NS_RESO = 0
Just learned they need to be available at the module level for some of the c imports, but inside the class they can live in a list, so I did that.

2016-10-27 14:09 UTC, jorisvandenbossche reviewed
Can you rebase and update?

2016-10-27 14:09 UTC, jorisvandenbossche commented on doc/source/whatsnew/v0.19.1.txt
> +- Bug in multiple offset aliases with decimal points regarded as ints (e.g. 0.5s as 5s) (:issue:`8419`)
Can you move this to v0.20.0 file and add it to the enhancements section? It was a bug that is was parsed incorrectly and did not error, but supporting fractional resolutions is an enhancement that can be listed in the enhancement section

2016-10-27 14:09 UTC, jorisvandenbossche commented on pandas/tseries/frequencies.py
> +    RESOS = [RESO_NS, RESO_US, RESO_MS, RESO_SEC, RESO_MIN, RESO_HR, RESO_DAY]
is this used somewhere?

2016-10-27 14:30 UTC, jisantuc commented on pandas/tseries/frequencies.py
> +    RESOS = [RESO_NS, RESO_US, RESO_MS, RESO_SEC, RESO_MIN, RESO_HR, RESO_DAY]
Nope, will destruct.

2016-10-27 14:59 UTC, jisantuc commented on pandas/tseries/frequencies.py
> +NS_RESO = 0
They're used in some of the `@classmethod`s it turns out so need to stay for now

2016-12-06 21:32 UTC, jreback commented
can you rebase

2016-12-14 13:49 UTC, jreback commented on pandas/tseries/tests/test_frequencies.py
> +        Reso = frequencies.Resolution
can you add the issue number here as as comment

2016-12-14 13:50 UTC, jreback commented on pandas/tseries/frequencies.py
> +        Convert freq with decimal stride into a higher freq with integer stride
can you add Parameters/Returns section to detail the args

2016-12-14 13:50 UTC, jreback commented
just a little docs, otherwise lgtm.

2016-12-14 16:08 UTC, merged

2016-12-14 16:08 UTC, jorisvandenbossche commented
Made the latest changes quickly myself. @jisantuc Thanks a lot for this nice contribution!