BUG: underflow on Timestamp creation
pandas-dev/pandas pull request #14433
Opened 2016-10-16 12:03 UTC by chris-b1

- [x] closes #14415
 - [ ] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew entry

2016-10-16 12:29 UTC, jreback requested changes

2016-10-16 12:29 UTC, jreback commented on pandas/tslib.pyx
> +
shouldn't these be imported from the numpy headers? for consistency

2016-10-16 12:29 UTC, jreback commented on pandas/tslib.pyx
> +cdef int64_t _NS_LOWER_BOUND = INT64_MIN + 1
why change this?
iirc some platforms don't play nice with this definition

2016-10-16 12:31 UTC, chris-b1 commented on pandas/tslib.pyx
> +
This is how we do it in `lib.pyx`, but agreed it probably makes more sense to pull it from the numpy headers.

2016-10-16 12:33 UTC, jreback commented on pandas/tslib.pyx
> +
ok no big deal 
ideally should be consistent across the code 
maybe just import into util.pxd and use from there?

2016-10-16 12:36 UTC, jreback commented on pandas/tslib.pyx
> +cdef int64_t _NS_LOWER_BOUND = INT64_MIN + 1
it's fine
i don't know why these were hard coded in the first place

2016-10-16 19:56 UTC, chris-b1 commented on pandas/tslib.pyx
> +cdef int64_t _NS_LOWER_BOUND = INT64_MIN + 1
On further look, I'll change the lower bound back - in our compat with python datetime we assume in several places that the min value has a 0 nanosecond unit - I think it _could_ be worked around, but fairly invasive for another 800 ns of span.

2016-10-19 12:40 UTC, jreback commented
lgtm. Push again though (you might need to ``git commmit --all --amend -C amend`` to generate a new has. Want to make sure that appveyor is working. I just turned it back on (was set to old pydata/pandas repo)

2016-10-20 11:01 UTC, jreback commented
lgtm. rebase and merge.

2016-10-20 13:46 UTC, merged