Type levels as list in _make_concat_multiindex (fixes #14438)
pandas-dev/pandas pull request #14449
Opened 2016-10-19 06:20 UTC by dubourg

- [ OK ] closes #14438
 - [ OK ] tests added / passed
 - [ OK ] passes ``git diff upstream/master | flake8 --diff``
 - [ OK ] whatsnew entry

2016-10-19 09:11 UTC, jreback requested changes

2016-10-19 09:11 UTC, jreback commented on pandas/tools/merge.py
>          if levels is None:
change this in factorize_from_iterable instead

2016-10-19 11:58 UTC, jreback commented
minor change, ping when green.

2016-10-19 12:01 UTC, dubourg commented
yep, will do!

2016-10-20 04:36 UTC, dubourg commented
@jreback done!

2016-10-20 10:25 UTC, jreback approved these changes

2016-10-20 10:25 UTC, merged

2016-10-20 10:25 UTC, jreback commented
thanks @dubourg