GH #14499 Panel.ffill ignores axis parameter and fill along axis=1
pandas-dev/pandas pull request #14528
Opened 2016-10-28 16:06 UTC by Tux1

- [X] closes #14499 
 - [X] tests added / passed
 - [X] passes ``git diff upstream/master | flake8 --diff``
 - [X] whatsnew entry

2016-10-28 16:08 UTC, jreback requested changes

2016-10-28 16:08 UTC, jreback commented on pandas/core/generic.py
> +                    def test_ffill_bfill_axis(self):
?

2016-10-28 16:13 UTC, Tux1 commented on pandas/core/generic.py
> +                    def test_ffill_bfill_axis(self):
fixed

2016-11-02 13:58 UTC, Tux1 commented
handle case where `axis=0`, tests added for every case and passed, whatsnew added

2016-11-03 13:40 UTC, Tux1 commented
@jreback you're okay with this pr ?

2016-11-11 09:21 UTC, jorisvandenbossche commented on doc/source/whatsnew/v0.19.1.txt
> +- Bug in ``pd.Panel.ffill`` where ``axis`` was not propagated (:issue:`14499`)
Can you move this to the 0.20.0 file? (0.19.1 is released in the meantime)

2016-11-11 09:21 UTC, jorisvandenbossche commented on pandas/tests/test_panel.py
> +        print(panel)
left over

2016-11-11 09:21 UTC, jorisvandenbossche commented on pandas/core/generic.py
> +                    frame = self.swapaxes(0, 1)
Question (not too familiar with Panels): swapping the axes here can potentially cause dtypes to change? (ints upcast to float, or numeric upcast to object when you have mixed dtypes)

2016-11-12 14:27 UTC, Tux1 commented on pandas/core/generic.py
> +                    frame = self.swapaxes(0, 1)
Good point. Let me check

2016-11-12 14:27 UTC, Tux1 commented on doc/source/whatsnew/v0.19.1.txt
> +- Bug in ``pd.Panel.ffill`` where ``axis`` was not propagated (:issue:`14499`)
done.

2016-12-21 23:09 UTC, jreback commented
@Tux1 can you rebase / update

2016-12-22 13:49 UTC, Tux1 commented
Done

> On 22 Dec 2016, at 07:09, Jeff Reback <notifications@github.com> wrote:
> 
> @Tux1 <https://github.com/Tux1> can you rebase / update
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/pandas-dev/pandas/pull/14528#issuecomment-268668173>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AGWku4E3Ck1ncZf0bkgZaE4sGggfblb0ks5rKbGpgaJpZM4KjmbC>.
>

2017-01-21 22:29 UTC, jreback requested changes

2017-01-21 22:29 UTC, jreback commented on pandas/core/generic.py
> -            axis = 0
``axis = self._stat_axis_number`` give the correct default

2017-01-21 22:29 UTC, jreback commented on pandas/core/generic.py
> +                    axis2d = axis - 1
``axis == 2``?

2017-01-21 22:29 UTC, jreback commented on pandas/core/generic.py
> +                        raise NotImplementedError()
add a message to the ``NotImplementedError``

2017-01-21 22:29 UTC, jreback commented on pandas/tests/test_panel.py
> +        a['a'].loc[1, 1] = np.nan
set using full ``.loc``, not chained indexing, e.g. ``f0.loc['a', 1, 1] = np.nan``

2017-01-21 22:29 UTC, jreback commented on pandas/tests/test_panel.py
> +        assert_panel_equal(a.ffill(axis=0), f0)
make these expected before each statement, e.g.

```
result = a.ffill(axis=0)
expected = ......
assert_panel_equal(result, expected)
```

2017-01-21 22:29 UTC, jreback commented on pandas/tests/test_panel.py
> +
ideally also tests with a panel that has a non-numeric type as well (IOW, add a string to the above example); this should be a separate set of tests.

2017-03-20 13:41 UTC, jreback commented
pls comment if youd like to update / rebase and continue

2017-03-20 13:41 UTC, closed without merging