BUG: fixes #12405 by eliding values index by NaT in MPLPlot._get_xticks
pandas-dev/pandas pull request #14540
Opened 2016-10-30 14:16 UTC by tsdlovell

- [ ] closes #12405
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

Proposed solution: elide rows where x value would be `NaT` in [MPLPlot._get_xticks](https://github.com/pandas-dev/pandas/blob/7f5a45c1b388b3f7f309f82bfa0733b7b9980c3a/pandas/tools/plotting.py#L1328) (which seems like a minor misnomer: its getting x values, not what will ultimately be ticks).

Reordering occurs in MPLPlot._get_xticks and it has a block that is conditional on `use_index` and `is_datetype`, so seems like a reasonable place to elide the values.  Mutation of `self.data` already occurs there (reordering) and a read through suggests nothing has saved info related to `self.data`'s shape before this point.

2016-10-30 14:20 UTC, tsdlovell commented
Will add a test in [test_datetimelike.py](https://github.com/pandas-dev/pandas/blob/7f5a45c1b388b3f7f309f82bfa0733b7b9980c3a/pandas/tests/plotting/test_datetimelike.py) but it will probably just repeat the sorting and eliding that occurs in the `use_index`/`is_datetype` branch of _get_xticks.  Alternatively, could check that all the xvalues are within the nan{min,max} bounds of the original index.

2016-10-30 15:39 UTC, jreback commented
i would add some edge cases
e.g. all nans, single nan first, and single nan last

2016-10-30 22:28 UTC, tsdlovell commented
@jreback , I think all NaTs should be a failure:  `pd.Series().plot()` (data is all NaTs and we use the elide NaTs methodology) results in `TypeError: Empty 'DataFrame': no numeric data to plot`.  Perhaps we should alert that we've elided values and that's why there is no data left.

Otherwise, all cases are the same since `sort_values()` results in the same series regardless of number of non-NaTs, barring all NaTs.

2016-10-30 22:31 UTC, tsdlovell commented
incidentally, re @jorisvandenbossche's comment in the orignal bug report, matplotlib complains if you try to plot with `NaT` as an xvalue in a new plot.  But once you're plotting on an axis that has already plotted with a datetime on the index, it accepts NaT values (as the min datetime value).

2016-10-31 12:26 UTC, jreback commented on pandas/tests/plotting/test_datetimelike.py
> +        s = (tm.makeTimeSeries()
this is overly complicated, can you simplify the creation?

2016-10-31 12:27 UTC, jreback commented on pandas/tests/plotting/test_datetimelike.py
> +        xdata = ax.get_lines()[0].get_xdata()
add a ``_check_plot_works`` call

2016-10-31 12:27 UTC, jreback commented
pls add a release note, 0.19.1 bug fixes is fine.

2016-10-31 16:34 UTC, jorisvandenbossche commented
The way matplotlib deals with missing values (for numerical data) is to leave a gap in the line. So matplotlib can actually deal with nan values. So therefore, we could also opt for this behaviour, rather than just removing those NaN values from the data before plotting.

2016-10-31 16:38 UTC, tsdlovell commented
@jorisvandenbossche , we [sort the index](https://github.com/pandas-dev/pandas/blob/v0.19.0/pandas/tools/plotting.py#L1328) before we plot the data.  Where would we insert the `NaT` index value?

2016-12-16 23:54 UTC, jreback commented on doc/source/whatsnew/v0.19.1.txt
> +- Bug in ``plot`` where ``NaT`` in ``DatetimeIndex`` results in ``Timestamp.min`` (:issue: `12405`)
can you move to 0.20.0

2016-12-16 23:54 UTC, jreback commented
@tsdlovell can you rebase / update

2017-01-21 23:16 UTC, jreback commented
status of this?

2017-01-28 22:25 UTC, dlovell commented on doc/source/whatsnew/v0.19.1.txt
> +- Bug in ``plot`` where ``NaT`` in ``DatetimeIndex`` results in ``Timestamp.min`` (:issue: `12405`)
moved

2017-03-14 13:50 UTC, jreback commented
@tsdlovell ping!

2017-04-18 22:38 UTC, jreback commented
@tsdlovell can you rebase?

2017-04-21 17:26 UTC, tsdlovell commented
@jreback , I had some issues rebase'ing onto master.  I ended up just applying the changes manually to the current head and creating a new branch: [fix-gh12405-2](https://github.com/tsdlovell/pandas/tree/fix-gh12405-2).

Can I just push that to the original fork branch for this PR or will that mess something up?

2017-04-21 22:31 UTC, jreback commented
yes i think u can just force push it and will work

2017-05-13 21:38 UTC, jreback commented
@TomAugspurger how does this look?

2017-05-13 21:38 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- Bug in ``plot`` where ``NaT`` in ``DatetimeIndex`` results in ``Timestamp.min`` (:issue: `12405`)
can you move to 0.20.2

2017-05-15 18:14 UTC, TomAugspurger requested changes
Just a few changes @tsdlovell and can you move the release note to 0.20.2? Thanks!

2017-05-15 18:14 UTC, TomAugspurger commented on pandas/tests/plotting/test_datetimelike.py
> +        import matplotlib.pyplot as plt  # noqa
You can remove this import and use `self.plt`, which comes from the base class

2017-05-15 18:14 UTC, TomAugspurger commented on pandas/tests/plotting/test_datetimelike.py
> +        fig = plt.gcf()
Is this necessary for the test to work? Our base class should take care of closing all the figures, so there shouldn't be any hanging around from a previous test.

2017-05-15 18:14 UTC, TomAugspurger commented on pandas/tests/plotting/test_datetimelike.py
> +        self.assertLessEqual(s.index.min(), Series(xdata).min())
We just switched over to pytest, so this can be `assert s.index.min() <= Series(xdata).min()`. Same thing with the next line.

2017-05-15 18:14 UTC, TomAugspurger commented on pandas/tests/plotting/test_datetimelike.py
> +        _check_plot_works(s.plot)
I think you can remove this line. It's just calling `s.plot()` again.

2017-05-20 20:59 UTC, tsdlovell commented
@TomAugspurger , let me know if there's something I still need to do.

2017-05-20 21:58 UTC, TomAugspurger approved these changes

2017-05-20 21:59 UTC, merged

2017-05-20 21:59 UTC, TomAugspurger commented
Thanks!