Fix parse empty df
pandas-dev/pandas pull request #14596
Opened 2016-11-06 02:13 UTC by bkandel

- [x] closes #14515 
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew entry

2016-11-06 02:16 UTC, jreback requested changes

2016-11-06 02:16 UTC, jreback commented on doc/source/whatsnew/v0.19.1.txt
> +- Bug in ``pd.read_csv`` where reading files fails if the number of headers is equal to the number of lines in the file (:issue:`14515`)
0.20

2016-11-06 02:16 UTC, jreback commented on pandas/io/tests/parser/common.py
> +        tm.assert_frame_equal(df, expected)
use the same styling as above
e.g. expected

2016-11-06 02:16 UTC, jreback commented on pandas/parser.pyx
> +                    and not isinstance(self.orig_header, list)) or (
this is really odd what r u trying to do

2016-11-06 02:20 UTC, bkandel commented on pandas/parser.pyx
> +                    and not isinstance(self.orig_header, list)) or (
Counteract the extension to the header added in: https://github.com/pandas-dev/pandas/blob/master/pandas/parser.pyx#L519 The issue is that if the header is passed in as a list, it's extended to enable reading in the index name line (I think that's what it's for if I interpreted that comment correctly) but not accounted for when checking if the file is too short. So this checks if the header has been artificially extended and doesn't complain about the file being too short if the header was extended beyond the length of the file.

2016-11-11 09:05 UTC, jorisvandenbossche commented
@bkandel You have several tests that are failing now (I think also the one you added)

2016-11-11 14:32 UTC, bkandel commented
@jorisvandenbossche Sorry for the delay in fixing this -- there was more complexity here than I realized. I think it's getting there.

2016-11-12 16:40 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- Bug in ``pd.read_csv`` where reading files fails if the number of headers is equal to the number of lines in the file (:issue:`14515`)
can move to 0.19.2

2016-11-12 16:43 UTC, jreback commented on pandas/io/tests/parser/common.py
> +        expected = DataFrame(columns=[('a',), ('b',)])
I would expect these to resolve to an ``Index`` actually (we don't have a single level MI)

```
In [6]: pd.MultiIndex.from_tuples([('a',), ('b',)])
Out[6]: Index(['a', 'b'], dtype='object')
```

2016-11-12 16:43 UTC, jreback commented on pandas/io/tests/parser/common.py
> +        tm.assert_frame_equal(df2, expected2)
then this works nicely

```
In [7]: pd.MultiIndex.from_tuples([('a','c'), ('b', 'd')])
Out[7]: 
MultiIndex(levels=[['a', 'b'], ['c', 'd']],
           labels=[[0, 1], [0, 1]])
```

2016-11-13 13:30 UTC, bkandel commented on pandas/io/tests/parser/common.py
> +        expected = DataFrame(columns=[('a',), ('b',)])
That's what I thought too, but I got dtype matching errors when I did that. I'll try to figure out what's going on.

2016-11-15 19:40 UTC, jreback commented
@bkandel looks pretty good. ping when all green.

2016-11-15 21:19 UTC, bkandel commented
@jreback all green. Should be ready for final review now.

2016-11-22 01:49 UTC, bkandel commented
@jreback just rebased and should be good to go now.

2016-11-22 11:24 UTC, jreback commented
thanks!

2016-11-22 11:24 UTC, closed without merging