ENH: Explicit range checking when writing Stata
pandas-dev/pandas pull request #14637
Opened 2016-11-10 22:51 UTC by bashtage

- [X] closes #14618
 - [X] tests added / passed
 - [X] passes ``git diff upstream/master | flake8 --diff``
 - [X] whatsnew entry

Add explicit error checking for out-of-range doubles when writing Stata files

closes #14618

2016-11-10 22:59 UTC, jreback requested changes

2016-11-10 22:59 UTC, jreback commented on pandas/io/stata.py
> +            value = data[col].max()
use pandas.types.common.is_floating_dtype (or float_dtype) forgot

2016-11-10 23:27 UTC, bashtage commented
@jreback That doesn't work since it is `True` for `np.float32`.

2016-11-10 23:50 UTC, bashtage commented
Changed the approach and also added check for `float32` column range with upcast if needed.

2016-11-15 11:38 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- Explicit check in ``to_stata`` and ````StataWriter `` for out-of-range values when writing doubles (:issue:`14618`)
move to 0.19.2; too many quotes on StataWriter

2016-11-15 11:40 UTC, jreback commented on pandas/io/tests/test_stata.py
> +        df = DataFrame({'ColumnOk': [0.0,
can u throw some infs (and -infs) in here as well (unless that screws up the test)

2016-11-15 11:56 UTC, bashtage commented
Need to check behavior of infs/-inf, as well as NaN in Stata.  It might support these values.

2016-11-15 19:45 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +
you can move to 0.19.2

2016-11-17 12:42 UTC, jreback approved these changes

2016-11-17 12:42 UTC, jreback commented
so infs are not allowed in state at all?

2016-11-17 12:49 UTC, bashtage commented
`+inf` is a missing value, appears in Stata the same as `NaN` (denoted with a `.`). Basically Stata always uses the largest representable numbers as missing values, and everything above the upper cutoff for a double is a missing value.  I think users who with to express a missing value in Stata should be forced to use `NaN` which exports fine.

`-inf` is allowed

2016-11-17 12:50 UTC, jreback commented
ok, that's fine then.

2016-11-17 12:54 UTC, closed without merging

2016-11-17 12:54 UTC, jreback commented
thanks!