BUG: resampling with NaT in TimedeltaIndex (#13223)
pandas-dev/pandas pull request #14649
Opened 2016-11-14 01:46 UTC by liuguangyu0220

- [ ] closes #13223 
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

2016-11-15 11:35 UTC, jreback commented on pandas/tseries/resample.py
> +            n_NaT = sum([ax_i is tslib.NaT for ax_i in ax])
``n_NaT = ax.isnull().sum()``

2016-11-15 11:37 UTC, jreback commented on pandas/tseries/resample.py
> +        if ax.hasnans:
though we actually need to ignore the nans, doesn't this actually create a NaT group? this is inconcistent with grouping.

2016-11-15 11:38 UTC, jreback commented on pandas/tseries/tests/test_resample.py
> +        index = pd.to_timedelta(['0s', pd.NaT, '2s'])
test with an all NaT index

2016-11-17 05:11 UTC, liuguangyu0220 commented on pandas/tseries/resample.py
> +            n_NaT = sum([ax_i is tslib.NaT for ax_i in ax])
Will change. Thanks

2016-11-17 05:18 UTC, liuguangyu0220 commented on pandas/tseries/resample.py
> +        if ax.hasnans:
NaT group will be ignored in aggregation. It is handled the same way as in function `_get_time_bins`.

2016-12-26 21:45 UTC, jreback commented on pandas/tseries/resample.py
> +        if len(ax) > 0 and all(ax._isnan):
I would give a better error message here. Is this consistent with how we handle all-nan grouping?

2017-01-02 06:10 UTC, liuguangyu0220 commented on pandas/tseries/resample.py
> +        if len(ax) > 0 and all(ax._isnan):
All-nan grouping doesn't seem to be handled elsewhere. Any suggestions?

2017-01-02 16:01 UTC, jreback commented on pandas/tseries/resample.py
> +        if len(ax) > 0 and all(ax._isnan):
we currently ignore all nan groups, that's why I think it is there, so this is consistent, maybe a comment is worth it here.

2017-01-02 16:02 UTC, jreback commented on pandas/tseries/resample.py
> +        if len(ax) > 0 and all(ax._isnan):
so this is *all* data is nan. Hmm, I would just give a better error message then.

2017-01-02 16:06 UTC, jreback commented on pandas/tseries/tests/test_resample.py
> +        self.assertRaises(DataError, series.resample('1s').mean)
This is probably the right idea (e.g. raising a nice message),

e.g. we do this for all-nan groups (which is unfriendly)

```
In [8]: s = Series([1,2,3],[np.nan,np.nan,np.nan])

In [9]: s.groupby(s.index).sum()
TypeError: unhashable type: 'Float64Index'
```

2017-02-01 04:04 UTC, liuguangyu0220 commented
Rebased

2017-02-01 14:17 UTC, jreback requested changes
looks pretty good. some doc fixups

pls add a whatsnew entry in bug fixes (0.20.0).

ping on green.

2017-02-01 14:17 UTC, jreback commented on pandas/tseries/resample.py
> +        if len(ax) > 0 and all(ax._isnan):
use ``ax.hasnans``

2017-02-01 14:17 UTC, jreback commented on pandas/tseries/resample.py
> +        if ax.hasnans:
add a comment here on what you are doing

2017-02-01 14:17 UTC, jreback commented on pandas/tseries/resample.py
> +        # Addresses GH #13223
add a comment on what you are doing here (and why not just selecting start/end)

2017-03-28 18:02 UTC, jreback commented
can you rebase / upate

2017-04-07 03:15 UTC, liuguangyu0220 commented
rebased

2017-04-07 12:22 UTC, jreback commented
when you rebase you should end up with a small number of commits.

try

```
git rebase -i yourbranchname origin/master
git push yourremote yourbranchname
```

2017-05-07 14:12 UTC, jreback commented
closing. this needs a new PR with a cherry-pick on top of master.

2017-05-07 14:12 UTC, closed without merging