DOC: Explain pivot vs. pivot_table (#6950)
pandas-dev/pandas pull request #14650
Opened 2016-11-14 05:19 UTC by mroeschke

- [x] closes #6950

2016-11-14 11:52 UTC, jreback requested changes

2016-11-14 11:52 UTC, jreback commented on doc/source/reshaping.rst
> +function for pivoting with aggregation of numeric data (see the
i would love this down to the first paragraph in the pivot section

2016-11-14 18:03 UTC, mroeschke commented on pandas/tools/pivot.py
> +        non-numeric data
The `pivot` docstring already references `pivot_table` ([here](https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L3908))

2016-11-14 18:07 UTC, mroeschke commented on doc/source/reshaping.rst
> +function for pivoting with aggregation of numeric data (see the
Sounds good @jreback. I'll push the change later tonight.

2016-11-15 08:18 UTC, jorisvandenbossche commented on pandas/tools/pivot.py
> +        non-numeric data
Ah, yes, that's good. But not yet the `pd.pivot` one, and that is apparently located here: https://github.com/pandas-dev/pandas/blob/master/pandas/core/reshape.py#L339

2016-11-15 17:36 UTC, mroeschke commented on pandas/tools/pivot.py
> +        non-numeric data
Ah, thank you for bringing that to my attention. I'll push that change later tonight.

2016-11-16 07:14 UTC, mroeschke commented
@jorisvandenbossche @jreback  Thanks for the feedback. Implemented the changes you guys suggested.

2016-11-16 09:06 UTC, merged

2016-11-16 09:06 UTC, jorisvandenbossche commented
@mroeschke Thanks a lot! (feel free to do more PRs with doc improvements :-))