[WIP]API: CategoricalType for specifying categoricals
pandas-dev/pandas pull request #14698
Opened 2016-11-20 02:47 UTC by TomAugspurger

closes #14676 

This adds a new top-level class `pd.CategoricalType` for representing the *type* information on a `Categorical`, *without the values*. Users can pass this anywhere they would previously pass `'category'` if they need to specify non-default values for `categories` or `ordered` (you can still use `'category'` of course):

```python
In [1]: from pandas import *

In [2]: paste
    >>> t = CategoricalType(categories=['b', 'a'], ordered=True)
    >>> s = Series(['a', 'a', 'b', 'b', 'a'])
    >>> c = s.astype(t)
    >>> c

## -- End pasted text --
Out[2]:
0    a
1    a
2    b
3    b
4    a
dtype: category
Categories (2, object): [b < a]
```

This is the simplest possible change for now. A bigger change would be to make `c.dtype` return a `CategoricalType` instead of '`category`'. We could probably do that in a way that's backwards compatible, but I'll need to think on it a bit.

Other places this should work

- `select_dtypes` (currently returns all categoricals; should just be ones with same `CategoricalType`?)
- `read_csv`: need to implement, see https://github.com/pandas-dev/pandas/issues/14503
probably others.

Implementation-wise I need to document, more tests, clean up some things like the repr. But I wanted to get this out there for discussion. @janschulz you might be interested.

2016-11-20 02:52 UTC, jreback requested changes

2016-11-20 02:52 UTC, jreback commented on pandas/core/categorical.py
> +    """
this should be in with the rest of the dtypes

to be honest i wouldn't create this; just add it optionally into the existing

2016-11-20 03:00 UTC, TomAugspurger commented on pandas/core/categorical.py
> +    """
Is that OK with the caching and stuff that is done on `CategoricalDType`? This is on `CategoricalyDtype`:

```python
    def __new__(cls):

        try:
            return cls._cache[cls.name]
        except KeyError:
            c = object.__new__(cls)
            cls._cache[cls.name] = c
            return c
```

I haven't messed with extension types much. We could make the keys of that internal dict reflect the categories and ordered attributes.

2016-11-20 03:01 UTC, jreback commented on pandas/core/categorical.py
> +    """
yes you would had optional attributes and cache based on them

2016-11-20 03:39 UTC, TomAugspurger commented on pandas/core/categorical.py
> +    """
K, this seems to be working. Just have to convert the categories to a tuple so that they're hashable. Thanks.

2016-11-20 12:47 UTC, TomAugspurger commented
What would the ideal `__repr__` of `CategoricalDtype` be? Currently it's just `category`. For places like `DataFrame.info` it's probably best to keep that as is, but that's not as useful if you're inpsecing `CategoricalDtype` itself.

Also, for equality semantics, this is what I have right now

```python
    An instance of ``CategoricalDtype`` compares equal with any other
    instance of ``CategoricalDtype``, regardless of categories or ordered.
    In addition they compare equal to the string ``'category'``.
    To check whether two instances of a ``CategoricalDtype`` match,
    use the ``is`` operator.

    >>> t1 = CategoricalDtype(['a', 'b'], ordered=True)
    >>> t2 = CategoricalDtype(['a', 'c'], ordered=False)
    >>> t1 == t2
    True
    >>> t1 == 'category'
    True
    >>> t1 is t2
    False
    >>> t1 is CategoricalDtype(['a', 'b'], ordered=True)
    True
```

though I don't expect people to be working with these objects that much.

2016-11-21 11:29 UTC, jreback commented on pandas/types/dtypes.py
> +    .. versionadded:: 0.20.0
this has been around for quite some time, you are adding parameter support in 0.20.0

2016-11-21 11:30 UTC, jreback commented on pandas/types/dtypes.py
> +    categories : list or None
list-like, use similar to whats in Categorical now

2016-11-21 11:31 UTC, jreback commented on pandas/types/dtypes.py
> +    >>> t = CategoricalDtype(categories=['b', 'a'], ordered=True)
these examples are not relevant. This should be not include Series. This is a self-contained type.

2016-11-21 11:32 UTC, jreback commented on pandas/types/dtypes.py
> +        categories_ = categories if categories is None else tuple(categories)
this needs all of the validation logic (from Categorical). on the actual categories.

2016-11-21 11:34 UTC, jreback commented
you need to move over the repr (of the categories) and the validation logic on the categories to this class.

Further Categorical should use this internally for storage of categories / ordered. 

This is a fairly invasive change and needs some thought.

2016-11-21 11:35 UTC, jreback commented
I would split off the actual issue change and make that a follow up PR. Just putting in place the correct infrastructure can be the scope of this PR>

2016-11-21 13:06 UTC, TomAugspurger commented
> This is a fairly invasive change and needs some thought.

Yep. I had hoped to do the minimal change of just providing a new API, but let's do it right the first time. I'll spend some time on this the next couple weeks and ping when I have something.

2016-11-22 14:10 UTC, TomAugspurger commented
Closing for now. Will reopen a new PR on top of a PR fixing https://github.com/pandas-dev/pandas/issues/14711

2016-11-22 14:10 UTC, closed without merging