BUG: Fixes GH14554
pandas-dev/pandas pull request #14700
Opened 2016-11-20 13:50 UTC by clham

- [x] closes #14554 
 - [x] tests added / passed: updated test_indexing.py
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

Errors in indexing no longer forced into KeyError

2016-11-21 11:26 UTC, jreback commented on pandas/tests/indexing/test_indexing.py
> -                          fails=KeyError)
this is a major API change, pls revert

2016-11-21 11:26 UTC, jreback commented
needs the test from the issue

2016-11-22 11:16 UTC, jreback requested changes
please make the changes as indicated

2016-11-22 12:32 UTC, clham commented
I'm struggling with the intent of what's going on then.   

Indexing errors and key errors should be converted to key error,  everything else (like the bug reports recursion error) shouldbubble up?  Thanks for the understanding,   This is one of my first non doc PRs.

2016-11-22 23:43 UTC, jreback commented
> Indexing errors and key errors should be converted to key error, everything else (like the bug reports recursion error) shouldbubble up? Thanks for the understanding, This is one of my first non doc PRs.

no they should be converted to the ``_exception``. you can try just catching ``IndexError/TypeError`` where where the bare exceptions are now.

Its very important that the exceptions that are related to indexing are consistent (think from a user perspective). and so we don't/can't change them. However we may have an implementation that actually does positional type things (e.g. ``.take``), which may raise an error for something not found, but (in this case) are doing label indexing so a ``KeyError`` is correct, but the same code block may *also* handle positional indexing (the subclasses define _exception), so the ``_exception`` is then ``IndexError`` (again for consistency).

2016-12-05 23:49 UTC, jreback commented on pandas/core/indexing.py
> +        except:
you don't need an except here (it will default to raising).

you also don't need to catch ``self._exception``

2016-12-05 23:49 UTC, jreback commented on pandas/tests/indexing/test_indexing.py
> +        #GH14554
you need a space after the comments

2016-12-05 23:49 UTC, jreback commented on pandas/tests/indexing/test_indexing.py
> +    def recursive_indexing_function(self, a):
can we define this *inside* of the test function?

2016-12-15 02:40 UTC, clham commented
@jreback What's the best course of action here? Some of the builds are failing, but for conflicting reasons. 3.4 is blowing the stack, 3.5 is failing because it because the recursion limit is being set to low.  I've reached an impasse in googling.  Something doesn't smell right in artificially setting the `setrecursionlimit`, but I can't think of another way to ensure the stack doesn't actually overflow before the exception it thrown?

2016-12-15 11:17 UTC, jreback commented on pandas/tests/indexing/test_indexing.py
> +        oldVal=sys.getrecursionlimit()
why are you changing the recursion limit at all?
just let the assert happen naturally.

2016-12-16 02:45 UTC, clham commented on pandas/tests/indexing/test_indexing.py
> +        oldVal=sys.getrecursionlimit()
If I exclude it, when I run the tests, my stack just blows up, and the exception doesn't bubble up.

2016-12-16 23:19 UTC, jreback commented on pandas/tests/indexing/test_indexing.py
> +        oldVal=sys.getrecursionlimit()
yeah this seems kind of extreme. why don't you just remove this test and leave your change. pls add a whatsnew note (for 0.20.0), and we'll call it a day :> 

of course give it a manual test that things work

2016-12-17 02:25 UTC, clham commented
@jreback Updated and squashed.

2016-12-17 14:39 UTC, jreback approved these changes

2016-12-17 14:39 UTC, jreback commented
can you rebase and push again. like to see this all green.

2016-12-17 23:50 UTC, clham commented
My git-foo was all jacked up. I have no idea what happened. Please let me know if current push works.

2016-12-17 23:54 UTC, jorisvandenbossche commented
@clham Can you push again? For some reason, the tests didn't run

2016-12-18 00:00 UTC, clham commented
Done.  Still seems not to be triggering.  Should I try adding a commit?

2016-12-18 00:03 UTC, jorisvandenbossche commented
Can you fix the merge conflict and in the whatsnew file, and push that?

2016-12-18 00:39 UTC, clham commented
made a change and repushed:  still doesn't appear to be getting pulled into Travis or AppVeyor.  Conflict was also resolved.  it is only a few small changes.  does it make sens to nuke the branch and submit a fresh PR?

2016-12-18 21:41 UTC, clham commented
resubmitted as PR14192.  Jsut starting fresh to make the pain stop.

2016-12-19 11:49 UTC, closed without merging