BUG: Respect the dtype parameter for empty CSV
pandas-dev/pandas pull request #14717
Opened 2016-11-22 21:01 UTC by gfyoung

Title is self-explanatory.  Closes #14712.

Should be merged in before #14295 because the bug could also exist for the Python parser.

2016-11-22 23:38 UTC, jreback commented on pandas/io/parsers.py
> +                     np.empty(0, dtype=dtype[col_name]))
this too

2016-11-22 23:38 UTC, jreback requested changes

2016-11-22 23:38 UTC, jreback commented on pandas/io/tests/parser/c_parser_only.py
> +        expected = pd.DataFrame(columns=['a', 'b'])
for completeness, can you tests with timedelta/datetime/category as well.

2016-11-23 04:36 UTC, gfyoung commented on pandas/io/tests/parser/c_parser_only.py
> +        expected = pd.DataFrame(columns=['a', 'b'])
Yep, done.

2016-11-23 04:36 UTC, gfyoung commented on pandas/io/parsers.py
> +        index = [np.empty(0, dtype=dtype[index_name])
Fixed.

2016-11-23 04:36 UTC, gfyoung commented on pandas/io/parsers.py
> +                     np.empty(0, dtype=dtype[col_name]))
Fixed.

2016-11-23 09:04 UTC, jorisvandenbossche approved these changes

2016-11-23 11:01 UTC, jreback approved these changes

2016-11-23 11:03 UTC, jreback commented
lgtm. I restarted appveyor. If that doesn't pass, then pls have a look @gfyoung 
ping when passed / fixed.

2016-11-23 11:04 UTC, jreback commented
I would be fine with this for 0.19.2 a well. @jorisvandenbossche up to you.

2016-11-23 17:13 UTC, gfyoung commented
@jreback , @jorisvandenbossche : I see a lot of green and no red.  Ready to merge if there are no other concerns.

2016-11-24 21:18 UTC, merged

2016-11-24 21:18 UTC, jorisvandenbossche commented
@gfyoung Thanks. Moved to 0.19.2