BUG: Corrects stopping logic when nrows argument is supplied (#7626)
pandas-dev/pandas pull request #14747
Opened 2016-11-25 19:44 UTC by jeffcarey

- closes #7626 - Subsets of tabular files with different "shapes" will now load when a valid skiprows/nrows is given as an argument
 - [x] tests added / passed - No new tests added, nosetests suite passed successfully.
 - [x] passes ``git diff upstream/master | flake8 --diff``

Issue summary: The function "tokenize_bytes" in tokenizer.c can be called multiple times when reading in a file. When nrows is supplied, a check is done at the end of each line read:

self->lines == start_lines + line_limit

The problem is that previously, on each consecutive run of tokenize_bytes, start_lines was set to be the current position, i.e. the beginning of the current segment being parsed rather than the beginning the user requested. This behavior actually always happened when nrows was supplied, causing extra rows to be read, and then discarded. It only caused a crash when it encountered a row with a different number of columns.

2016-11-25 19:50 UTC, jreback commented
can i create a small test that replicates the issue and fails on master (and passes here)?

2016-11-25 20:00 UTC, jeffcarey commented
Are you asking me to create the test or asking if it's OK for you to? If the latter, sure.

It's hard for me to say how large the file needs to be to create a crash but the bug can be reproduced at will using the file and row numbers jzwinck posted on the issue: https://gist.githubusercontent.com/jzwinck/838882fbc07f7c3a53992696ef364f66

2016-11-25 20:27 UTC, jreback commented
@jeffcarey I am asking you to. The point is to have a regression test so future changes don't break this.

2016-11-25 20:28 UTC, jreback commented
The issue / example is a last case resort. We much prefer to have a code based test (you can simply generate the appropriate data in memory; the size doesn't really matter). I just don't want to include external files like this. But if its impossible / hard, then you would need to include this test file.

2016-11-26 09:31 UTC, jeffcarey commented
@jreback I've created a test case that does not rely on any external files, including the example. Where do you think the best place for it is in the test suite? I figured somewhere in the frame directory since it relates to creating a DataFrame, but I don't see anything about input. Let me know if you think it fits best into something that already exists or if it deserves to be in its own file.

2016-11-26 12:16 UTC, jreback commented
https://github.com/pandas-dev/pandas/tree/master/pandas/io/tests/parser

has extensive tests for the parser

2016-11-26 21:58 UTC, jeffcarey commented
@jreback I've added a test and updated the comment here about the root cause. Please take a look.

2016-12-01 19:30 UTC, jeffcarey commented
@jreback Anything else needed here? I've fixed my test so that it complies with linting, all checks are green.

2016-12-01 22:32 UTC, jreback commented on pandas/io/tests/parser/common.py
> +        df = self.read_table(StringIO(test_input), nrows=1010)
use ``self.read_csv`` here.

I think this tests should be in c_parser only as well.

2016-12-01 22:32 UTC, jreback commented
pls add a whatsnew note in 0.19.2.

2016-12-05 02:15 UTC, jeffcarey commented
Requested changes made, all green again. Please review.

2016-12-05 11:09 UTC, jreback requested changes

2016-12-05 11:09 UTC, jreback commented on pandas/io/tests/parser/common.py
> +        header_narrow = '\t'.join(['COL_HEADER_' + str(i)
this is duplicating the above test in c_parser_only

2016-12-05 11:10 UTC, jreback requested changes
minor change - ping on green

2016-12-05 23:13 UTC, jreback approved these changes

2016-12-05 23:13 UTC, jreback commented
@jeffcarey lgtm. ping on green.

2016-12-06 01:36 UTC, jeffcarey commented
@jreback All green

2016-12-06 01:48 UTC, closed without merging

2016-12-06 01:48 UTC, jreback commented
thanks @jeffcarey