TST:Same return values in drop_duplicates for Series and DataFrames(#…
pandas-dev/pandas pull request #14754
Opened 2016-11-27 00:49 UTC by mroeschke

- [x] closes #14192
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``

…14192)

2016-12-01 12:11 UTC, sinhrks requested changes

2016-12-01 12:11 UTC, sinhrks commented on pandas/tests/test_base.py
> +                           'c': [3, 3, np.nan, np.nan, 'three']
can u also add ``int`` and ``datetime64(with NaT)`` columns to be comprehensive?

2016-12-01 12:12 UTC, sinhrks requested changes

2016-12-01 12:12 UTC, sinhrks commented on pandas/tests/test_base.py
> +            dropped_frame = df[[column]].drop_duplicates()
pls loop with ``keep`` patterns also.

2016-12-01 15:53 UTC, mroeschke commented on pandas/tests/test_base.py
> +                           'c': [3, 3, np.nan, np.nan, 'three']
Sure thing. Will add those columns tonight.

2016-12-01 15:54 UTC, mroeschke commented on pandas/tests/test_base.py
> +            dropped_frame = df[[column]].drop_duplicates()
By `keep` patterns, do you mean with `loc`?

2016-12-01 16:36 UTC, mroeschke commented on pandas/tests/test_base.py
> +            dropped_frame = df[[column]].drop_duplicates()
Ah, I understand now. The keep keyword argument.

2016-12-03 17:44 UTC, mroeschke commented
Added the `keep` kwarg and added `int` and `datetime64` columns @sinhrks

2016-12-04 23:36 UTC, sinhrks approved these changes

2016-12-15 09:02 UTC, merged

2016-12-15 09:02 UTC, jorisvandenbossche commented
@mroeschke Thanks!