added timedelta as valid type for conversion to integer
pandas-dev/pandas pull request #14799
Opened 2016-12-05 00:24 UTC by aileronajay

- [ ] closes #xxxx
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

2016-12-05 00:26 UTC, aileronajay commented
this PR is currently a WIP, tests have not been added yet. This iteration is for initial reviews

2016-12-05 01:33 UTC, aileronajay commented
@TomAugspurger the change that is currently in this PR will support timedelta as part of the index and the case presented in the issue

pd.DataFrame({'v':[1,np.nan,5]},index=pd.to_timedelta([1,2,3], unit="d")).interpolate(method="time")

will work

>>> pd.DataFrame({'v':[1,np.nan,5]},index=pd.to_timedelta([1,2,3], unit="d")).interpolate(method="time")
          v
1 days  1.0
2 days  3.0
3 days  5.0

Though i think what we expect here is that interpolate should work if the passed data is of type datetime or timedelta, something like this (below) should work (like how cut was enhanced). Is this the expectation?

>>> pd.DataFrame({'v':[np.datetime64('2012-01-01'),np.nan,np.datetime64('2012-01-03')]},index=[1,2,3]).interpolate()
           v
1 2012-01-01
2        NaT
3 2012-01-03

2016-12-05 21:28 UTC, aileronajay commented
@jreback @jorisvandenbossche @TomAugspurger need pointers about expected functionality. I have added support for time delta as index when interpolating. Should we also be able to interpolate between input time data?

2016-12-05 22:31 UTC, TomAugspurger commented
@aileronajay IIRC the original issue https://github.com/pandas-dev/pandas/issues/6424 was about interpolating when the index was timedeltas. We can support interpolating time delta data like in your second example as well. That's fine either in this PR or a separate one.

2016-12-05 22:48 UTC, aileronajay commented
@TomAugspurger i will then add support for timedelta as index in this PR and create a separate PR for interpolating time data

2016-12-07 01:04 UTC, aileronajay commented
are there other changes required in this PR? (like more tests?) @sinhrks @jreback @TomAugspurger @jorisvandenbossche

2016-12-07 01:18 UTC, jreback requested changes

2016-12-07 01:18 UTC, jreback commented on pandas/core/missing.py
> +                    issubclass(inds.dtype.type, np.timedelta64)):
this should use the is_datetime64_dtype functions instead

2016-12-07 01:18 UTC, jreback commented on pandas/core/missing.py
> +                    issubclass(inds.dtype.type, np.timedelta64)):
or better yet the needs_i8_conversion function

2016-12-07 01:27 UTC, aileronajay commented on pandas/core/missing.py
> +                    issubclass(inds.dtype.type, np.timedelta64)):
@jreback I have made this change now

2016-12-07 18:05 UTC, aileronajay commented
@jreback i have made the change requested in the review, are there other changes that need to be taken care of?

2016-12-07 22:38 UTC, jorisvandenbossche reviewed
Can you add a small notice in the v0.20.0.txt whatsnew file (in the 'other enhancements' section)

2016-12-07 22:38 UTC, jorisvandenbossche commented on pandas/tests/series/test_missing.py
> +        tm._skip_if_no_scipy()
Is scipy needed for this interpolate method?

2016-12-07 22:45 UTC, TomAugspurger commented on pandas/core/missing.py
> +            if (needs_i8_conversion(inds.dtype.type)):
You can remove the redundant outer pair of parenthesis.

2016-12-07 22:46 UTC, TomAugspurger commented on pandas/tests/series/test_missing.py
> +        tm._skip_if_no_scipy()
It shouldn't be.

2016-12-07 22:46 UTC, aileronajay commented on pandas/tests/series/test_missing.py
> +        tm._skip_if_no_scipy()
the interpolate method being used over here is 'time', i dont think it requires scipy, i just had this notion that we ignore the interpolation tests if scipy is absent, on a more thorough check i found that is not the case

2016-12-07 22:52 UTC, aileronajay commented on pandas/tests/series/test_missing.py
> +    def test_interp_timedelta64(self):
sure, would it be better if i add it as one more in the existing test or as a new test?

2016-12-07 23:05 UTC, aileronajay commented on pandas/tests/series/test_missing.py
> +    def test_interp_timedelta64(self):
@TomAugspurger i have added non uniform spacing as a test case now

2016-12-07 23:05 UTC, aileronajay commented on pandas/core/missing.py
> +            if (needs_i8_conversion(inds.dtype.type)):
@TomAugspurger i have addressed this review comment

2016-12-07 23:06 UTC, aileronajay commented on pandas/tests/series/test_missing.py
> +        tm._skip_if_no_scipy()
I have removed the skip if no scipy statement

2016-12-09 17:32 UTC, aileronajay commented
@jreback I have made the suggested changes

2016-12-09 19:31 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +-  The ``pd.Series.interpolate`` now supports timedelta as index type(:issue:`6424`)
with ``method='time'`` (also space before ``(:issue:...``

2016-12-09 19:31 UTC, jreback approved these changes

2016-12-09 19:31 UTC, jreback commented
minor doc change. ping on green.

2016-12-09 21:50 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +-  The ``pd.Series.interpolate`` now supports timedelta as index type with method=`time` (:issue:`6424`)
small edit, but I can do on merge:

remove the leading ``The`` and ``method='time'`` needs to be in double backticks.

``timedelta as *an* index type`` (add an)

2016-12-09 21:54 UTC, aileronajay commented on doc/source/whatsnew/v0.20.0.txt
> +-  The ``pd.Series.interpolate`` now supports timedelta as index type with method=`time` (:issue:`6424`)
@jreback should i make these changes or will be able to do that during merge?

2016-12-10 03:06 UTC, aileronajay commented
@jreback there was a clean run in travis, appveyor failed after running for an hour, there appears to be a problem with appveyor

2016-12-10 11:19 UTC, merged

2016-12-10 11:19 UTC, jorisvandenbossche commented
@aileronajay Thanks!