fixed kde plot to ignore the missing values
pandas-dev/pandas pull request #14820
Opened 2016-12-08 01:38 UTC by keshavramaswamy

- [ ] closes #xxxx
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

2016-12-08 15:42 UTC, TomAugspurger commented
Can you add a test and a release notes in whatsnew/0.19.2?

2016-12-08 15:43 UTC, keshavramaswamy commented
Yes, I can do that

2016-12-10 15:33 UTC, jreback commented
can you rebase, problem with appeveyor which i just fixed

2016-12-10 15:34 UTC, keshavramaswamy commented
Sure, I'll do that!

On Sat, Dec 10, 2016 at 10:33 AM Jeff Reback <notifications@github.com>
wrote:

> can you rebase, problem with appeveyor which i just fixed
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/14820#issuecomment-266216306>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGg1E01seEPTO65FIZGUbq1__9zCTGicks5rGsZfgaJpZM4LHV8J>
> .
>

2016-12-11 12:46 UTC, TomAugspurger requested changes
Still need a test too.  That can go in pandas/tests/plotting/test_series.py There's already a test in there with missing values `test_kde_missing_vals`, apparently not the right mix of missing values though.

Put a comment with a link to this issue when you make the new test. Thanks!

2016-12-11 12:46 UTC, TomAugspurger commented on doc/source/whatsnew/v0.19.2.txt
> +<<<<<<< HEAD
You can remove the git conflict markers.

2016-12-11 15:57 UTC, keshavramaswamy commented on doc/source/whatsnew/v0.19.2.txt
> +<<<<<<< HEAD
yes, I noticed that - will add the required test too asap!

2016-12-12 18:50 UTC, keshavramaswamy commented
@jreback - Is there a problem with the Travis CI?

2016-12-12 19:08 UTC, jreback commented
you need to rebase on current master, I fixed this yesterday.

2016-12-14 06:33 UTC, keshavramaswamy commented
Thanks @jreback - have rebased now.

2016-12-14 12:50 UTC, TomAugspurger commented on pandas/tests/plotting/test_series.py
> +        self.assertTrue(any(~np.isnan(axes.lines[0]._xorig)),
Can you replace the `._xorig` with `.get_xdata()`? Better to not use matplotlib's internal APIs.

2016-12-14 12:53 UTC, TomAugspurger commented
One small change, then we should be good! We're aware of that travis failure on the 3.4 build.

2016-12-14 20:39 UTC, TomAugspurger approved these changes

2016-12-15 15:40 UTC, merged

2016-12-15 15:40 UTC, TomAugspurger commented
@keshavramaswamy thanks!