BUG: addresses #14855 by fixing color kwarg conflict
pandas-dev/pandas pull request #14871
Opened 2016-12-13 00:34 UTC by alexandercbooth

- [x] closes #14855 
 - [x] tests passed
 - [x] passes ``git diff upstream/master | flake8 --diff``

2016-12-13 11:14 UTC, jreback commented on pandas/tools/plotting.py
> +    else:
``kwds.setdefault('c', kwdgs.pop('color', plt.rcParams['patch.facecolor']))`` is a big more idiomatic

2016-12-13 11:14 UTC, jreback commented
pls add a whatsnew note (for 0.19.2 is fine)

2016-12-13 11:15 UTC, jreback commented on pandas/tools/plotting.py
> +    else:
nvm, I see that these kwards are *slightly* different. Can you update / add to the comment (and reference the issue).

2016-12-13 11:15 UTC, jreback commented
pls add a test

2016-12-14 09:56 UTC, sinhrks requested changes

2016-12-14 09:56 UTC, sinhrks commented on pandas/tools/plotting.py
> +    if 'color' in kwds:
shouldn't overwrite if any of ‘c’, ‘color’ and ‘facecolor’.

2016-12-16 01:13 UTC, alexandercbooth commented on pandas/tools/plotting.py
> +    if 'color' in kwds:
I'm sorry, I don't quite understand. Could you explain a little bit more?

2016-12-16 01:15 UTC, alexandercbooth commented
Sorry for the slow response, long week at work. Thank you both for the feedback, let me know if there's something else I can change.

2016-12-16 03:44 UTC, sinhrks commented on pandas/tools/plotting.py
> +    if 'color' in kwds:
I meant, ``plt.scatter(..., facecolor='red')`` and ``plt.scatter(..., c='red')`` both draws points in red. So ``scatter_matrix(..., facecolor='red')`` and ``scatter_matrix(..., c='red')`` should be the same.

2016-12-16 06:44 UTC, alexandercbooth commented on pandas/tools/plotting.py
> +    if 'color' in kwds:
Ahh gotcha. Thanks!
So one of the problems turned out that difference between `c` and `color` was an edge border on the markers. We can take care of that by setting the default to `'none'`. After making the changes here is the current behavior:
![image](https://cloud.githubusercontent.com/assets/15242567/21254074/c93c54f6-c317-11e6-9587-bc2e9d10bf06.png)
![image](https://cloud.githubusercontent.com/assets/15242567/21254080/d0d495ac-c317-11e6-819d-0a9091355157.png)
![image](https://cloud.githubusercontent.com/assets/15242567/21254083/d618af76-c317-11e6-9de2-3d98dbd887cd.png)
All are now the same.

2016-12-16 17:50 UTC, alexandercbooth commented
I also notice that this exact same bug is present in scatter_plot. It can be fixed in exactly the same way as I have done above:

![image](https://cloud.githubusercontent.com/assets/15242567/21272466/3dccec7a-c374-11e6-8256-981e7b16f7ce.png)
![image](https://cloud.githubusercontent.com/assets/15242567/21272470/425303ce-c374-11e6-957e-c2666805dd64.png)
![image](https://cloud.githubusercontent.com/assets/15242567/21272452/2ef99fb8-c374-11e6-9459-0ccd473cf09e.png)

I would be happy to fix it as well. I could just tack it on here or open another PR, whichever is best.

2016-12-16 18:05 UTC, tacaswell requested changes

2016-12-16 18:05 UTC, tacaswell commented on pandas/tools/plotting.py
> +        kwds.setdefault('c', plt.rcParams['patch.facecolor'])
I do not understand this, if `'c'` is in kwds, then `setdefault` is a no-op.

You probably also want to version guard this, mpl 2.0 scatter respects the color cycle
http://matplotlib.org/2.0.0rc1/users/dflt_style_changes.html#scatter

2016-12-16 23:10 UTC, alexandercbooth commented on pandas/tools/plotting.py
> +        kwds.setdefault('c', plt.rcParams['patch.facecolor'])
Good thinking, @tacaswell! I investigated it a bit further and it turns out we can resolve this issue and the same issue for scatter_plot by removing the old bug fix, removing the new changes and adding in the edgecolor='none' as default. With this, we still get the identical behavior with `c`, `color` or `facecolor` set and no error.

2016-12-17 21:52 UTC, tacaswell commented
The change to the default value of `c` went in via https://github.com/matplotlib/matplotlib/pull/4079 which is in mpl >=1.5.0.  pandas will need to do some version checking to correctly support older versions of mpl.  I thought back to 1.3.1 is currently supported?

2016-12-30 21:39 UTC, jreback commented
status of this?

2017-01-02 11:19 UTC, jorisvandenbossche reviewed
This seems to work (I don't fully understand how passing facecolor solves the color cs c conflict). 
The only thing is that this slightly changes the plot appearance. As previously `c` only changed the facecolor, while it now also seems to change the edgecolor.

2017-01-02 11:19 UTC, jorisvandenbossche commented on pandas/tests/plotting/test_misc.py
> +            _check_plot_works(scat, color='rgb')
Is there a reason you pass here 'rgb' and not just 'r'? As passing multiple colors seems a bit odd for a single scatter plot (I think now the points just get the [r, g, b, r, g, b, r, g, b, ...] colors sequentially?)

2017-01-03 11:15 UTC, sinhrks approved these changes

2017-01-21 23:09 UTC, jreback commented
status on this? @sinhrks @jorisvandenbossche @TomAugspurger

2017-01-22 01:38 UTC, alexandercbooth commented
Thanks Jeff and everyone else for your patience on this; it's been a really hectic month at work. I appreciate all the feedback from everyone. I will try to address all concerns I can tomorrow and report back.
Thanks!

2017-01-24 18:54 UTC, alexandercbooth commented on pandas/tests/plotting/test_misc.py
> +            _check_plot_works(scat, color='rgb')
Purely for aesthetic purposes. I have trouble seeing some colors and wanted to visually confirm these changes rendered the same objects.

2017-01-24 19:19 UTC, alexandercbooth commented
I squashed and rebased since the PR was stale, but it's my first time doing that so I apologize if I made a mistake.

2017-03-23 13:19 UTC, jreback commented
@alexandercbooth can you rebase

@TomAugspurger ok on this?

2017-03-23 22:55 UTC, jreback commented
lgtm. @TomAugspurger ok? (don't merge yet)

2017-03-25 16:05 UTC, jreback commented
@TomAugspurger ?

2017-04-05 21:16 UTC, TomAugspurger commented
Sorry for the delay, +1 on this.

@jreback, when you merge PRs that need a rebase (conflicts in whatsnew), you use the `merge-pr.py` script, right? I can do it, just want to double check first. Don't want to make @alexandercbooth rebase again.

2017-04-05 21:19 UTC, jreback commented
@TomAugspurger yes you can use the script. it will stop when it can't auto rebase (it will squash), you then fix the conflicts, ``git add``, then continue the script. Then I stop again (its now rebased), just to make sure the commits message and everything is ok. Then have it push upstream.

2017-04-05 21:47 UTC, closed without merging

2017-04-05 21:48 UTC, TomAugspurger commented
@alexandercbooth thanks!

2017-04-05 21:57 UTC, alexandercbooth commented
My pleasure!