Add new optional "separator" argument to json_normalize
pandas-dev/pandas pull request #14891
Opened 2016-12-16 00:23 UTC by jowens

- [x] closes #14883
 - [x] tests added / passed (added test `test_shallow_nested_with_separator`)
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew entry (v0.20.0)

2016-12-16 01:34 UTC, TomAugspurger requested changes

2016-12-16 01:34 UTC, TomAugspurger commented on pandas/io/json.py
> +    separator : string, default '.'
Can you add a [`.. versionadded::`](http://www.sphinx-doc.org/en/1.4.9/markup/para.html#directive-versionadded) directive here.

Also, might be better to make `separator` the last keyword argument. That way it won't break people using all positional arguments.

2016-12-16 01:34 UTC, TomAugspurger commented on pandas/io/tests/json/test_json_norm.py
> +    def test_shallow_nested_with_separator(self):
I think this test can be simplified a lot. Could you do something like

```python
result = json_normalize({"A": {"A": 1, "B": 2}}, separator='_')
expected = pd.DataFrame([[1, 2]], columns={"A_A", "A_B"})
assert_frame_equal(result, expected)
```

That way you're directly testing your change.

2016-12-16 01:34 UTC, TomAugspurger commented on pandas/io/tests/json/test_json_norm.py
> +    def test_shallow_nested_with_separator(self):
Also add test with the default separator, and ensure that the columns are `A.A, A.B`.

2016-12-16 02:00 UTC, jreback commented on pandas/io/json.py
> +    separator : string, default '.'
call it sep

add a version added tag

2016-12-16 03:48 UTC, sinhrks requested changes

2016-12-16 03:48 UTC, sinhrks commented on doc/source/whatsnew/v0.20.0.txt
> +- ``pandas.io.json.json_normalize()`` gained the option ``separator=string``; the default is ``separator='.'`` which is backward compatible. (:issue:`14883`)
How about, ...gained ``separator`` option which accepts ``str``, default is ``"."``

2016-12-16 03:48 UTC, sinhrks commented on pandas/io/json.py
> +    meta_keys = [separator.join(val) for val in meta]
validate whether ``separator`` is ``compat.string_types``

2016-12-16 03:48 UTC, sinhrks commented on pandas/io/tests/json/test_json_norm.py
> +        ex_data = {'name': ['Dade', 'Broward', 'Palm Beach', 'Summit',
can u also add unicode tests?

2016-12-16 05:32 UTC, jowens commented
I appreciate all of these comments, and implemented them. And then I found my code doesn't even work. I am doing something clearly wrong here—I thought it was to simply substitute

```python
    meta_keys = [sep.join(val) for val in meta]
```

for

```python
    meta_keys = ['.'.join(val) for val in meta]
```

It's not. That doesn't work. Happy to take any suggestions.

2016-12-16 10:05 UTC, jorisvandenbossche commented
> And then I found my code doesn't even work.

I am not sure that is the reason, but in your last version, it is still `separator.join` instead of `sep.join`

2016-12-21 23:41 UTC, jowens commented
Thanks for the comments, which I've incorporated into a new pull request https://github.com/pandas-dev/pandas/pull/14949. However, despite y'all pointing out some issues with my code, I am baffled why the simple replace-`.`-with-`sep` doesn't work, happy to take suggestions.

(Feel free to close this pull request whenever it's appropriate to do so; it's supplanted by the new one.)

2016-12-22 00:06 UTC, closed without merging