PR for Pandas issue #14872 / fillna() TZ datetime64 rounded
pandas-dev/pandas pull request #14905
Opened 2016-12-17 20:43 UTC by RodolfoRFR

Hi Jeff,

The change adds a "datetime64[ns, UTC]" object to the _DATELIKE_DTYPES set in pandas/types/common.py. 

No such object existed in this set and that is the reason the wrong method was executed on the inputs.

Object is created with DatetimeTZDtype.__new__

Thanks,
Rodolfo

 - [X] closes #14872
 - [ X] tests added / passed
 - [ X] passes ``git diff upstream/master | flake8 --diff`` (returns the same number of skips, errors and failures before changes)
 - [ ] whatsnew entry

2016-12-17 20:51 UTC, jreback commented
this goes way overboard 

see the pull request which closed the original issue

2016-12-17 22:44 UTC, RodolfoRFR commented
The changes in request #6587  added "dtype in _DATELIKE_DTYPES" to the method selection in the backfill_2d function (now in missing.py), 
```
-        _method = getattr(algos, 'backfill_2d_inplace_%s' % dtype, None)
-    elif is_datetime64_dtype(values):
+        _method = getattr(algos, 'backfill_2d_inplace_%s' % dtype.name, None)
+    elif dtype in _DATELIKE_DTYPES or is_datetime64_dtype(values):
```
I initially tried adding an extra is_datetime64tz_dtype() to this line with no success. After tracing the process with pdb I found that the values are already coerced to integers in pandas/core/internals.py,

```
    def _interpolate_with_fill(self, method='pad', axis=0, inplace=False,
                               limit=None, fill_value=None, coerce=False,
                               downcast=None, mgr=None):
        """ fillna but using the interpolate machinery """
        .
        .
        .
        values, _, fill_value, _ = self._try_coerce_args(values, fill_value)
```
before being passed to /pandas/missing/missing.interpolate_2d and then to backfill_2d. The dtype information is passed as dtype=datetime64[ns, UTC]. When it gets to these lines in the backfill_2d function,
```
elif dtype in _DATELIKE_DTYPES or is_datetime64_dtype(values):
      method = _backfill_2d_datetime
```
the return is always false because datetime64[ns, UTC] is not in _DATELIKE_DTYPES and the 'values' are integers.

Another way would be to either replace datetime64[ns, UTC] with datetime64[ns] before we get to this line or skip the coercion somehow. Unless I am missing something.

2016-12-17 22:59 UTC, jreback commented
so this should simply be changed to pass the actual value (and not coerced ones) when this is called and drop al of the _DATELIKE_DTYPES that is really old code

use the is_datetime64_dtype and is_datetime64tz_dtype

2016-12-17 23:24 UTC, jreback commented
actually you just need to check the dtype instead (of the values)

e.g.
```
(Pdb) p is_datetime64tz_dtype(dtype)
True
```

2016-12-18 00:22 UTC, RodolfoRFR commented
Done! I was indeed missing something. Thank you for the feedback!

2016-12-18 00:25 UTC, jreback requested changes
pls add a whatsnew entry (0.19.2) ok if u can make these changes in next day or so

2016-12-18 00:25 UTC, jreback commented on pandas/tests/test_dtype_utc.py
> +    expected = pd.Series([datetime.datetime(2016, 12, 12, 22, 24, 6, 100001,
this test needs to go in test_missing (search and out it with other similar tests)

2016-12-18 13:16 UTC, jreback requested changes

2016-12-18 13:16 UTC, jreback commented on pandas/tests/series/test_missing.py
> +    def test_dtype_utc():
needs to take self

2016-12-18 19:42 UTC, closed without merging

2016-12-18 19:42 UTC, jreback commented
thanks!