BUG: Prevent uint64 overflow in Series.unique
pandas-dev/pandas pull request #14915
Opened 2016-12-19 05:43 UTC by gfyoung

Introduces a `UInt64HashTable` class to hash `uint64` elements and prevent overflow in functions like `Series.unique`.

Closes #14721.

2016-12-19 10:22 UTC, jreback requested changes

2016-12-19 10:22 UTC, jreback commented on pandas/tests/test_base.py
> +        s = pd.Series([1, 2, 2**63, 2**63], dtype=np.uint64)
i think needs a bit more testing
most test are in algos for things like this

2016-12-19 11:32 UTC, jreback commented
you will need to rebase after #14919. I moved a couple of things, and added a HashTable testing section.

Though what I would really like is to systematically add unit64 to as many places as we test other dtypes and see what breaks / falls out (can do in another PR). Then create issues for incompat places.

2016-12-19 16:30 UTC, gfyoung commented on pandas/tests/test_base.py
> +        s = pd.Series([1, 2, 2**63, 2**63], dtype=np.uint64)
"Needs a bit more testing" is vague.  What sort of cases are you thinking of?  Secondly, the affected function has no relation to `algos`.  The code path is completely different.

However, you did catch a bug in `pd.unique`, which does travel through `algorithms.py` and can now benefit from my hashtable. :smile:

2016-12-19 17:01 UTC, jreback commented on pandas/tests/test_base.py
> +        s = pd.Series([1, 2, 2**63, 2**63], dtype=np.uint64)
not on the hashtable itself. ideally you should add uint64 to lots of places that we test int64 (construction type things). IOW, to actually exercise this code. I know this is vague. happy to merge this and to do a followup with more tests (and potentially breaking things). later.

2016-12-19 17:02 UTC, gfyoung commented on pandas/tests/test_base.py
> +        s = pd.Series([1, 2, 2**63, 2**63], dtype=np.uint64)
Okay, well that's a larger issue beyond this PR.  However, let's not merge until I patch `pd.unique`, which suffers from a similar issue as `Series.unique`.

2016-12-19 20:19 UTC, jreback approved these changes

2016-12-19 20:19 UTC, jreback commented
what was the bug (from before I moved unique)?

2016-12-19 20:21 UTC, gfyoung commented
@jreback : The <a href="https://github.com/pandas-dev/pandas/pull/14915/files#diff-fafd7700903bc35b7e73b5e1fa65b6daR133">diff</a> explains it all.  We were smashing all integer types together into one hashtable.

2016-12-19 20:27 UTC, jreback commented
ok, lgtm. ping on green.

2016-12-19 20:42 UTC, gfyoung commented
@jreback : I changed my mind about changing `pd.unique` in this PR.  `core.algorithms` is riddled with `uint64` bugs that need to be checked.  I'll tackle in a follow-up.

2016-12-19 20:55 UTC, jreback commented
> @jreback : Sounds good. I changed my mind about changing pd.unique in this PR. core.algorithms is riddled with uint64 bugs that need to be checked. I'll tackle in a follow-up.

totally fine. we can make a master issue of these if that is helpful.

2016-12-20 09:16 UTC, gfyoung commented
@jreback : Everything is green, so ready to merge if there are no other concerns.

2016-12-20 13:46 UTC, closed without merging

2016-12-20 13:46 UTC, jreback commented
thanks!

as I said, ideally have an issue which greatly expands test coverage for uint64 (and just mark the tests that are failing (e.g. assert that they are failing or comment out)).

Then can come back around and fix.