BUG: Patch rank() uint64 behavior
pandas-dev/pandas pull request #14935
Opened 2016-12-21 04:25 UTC by gfyoung

Adds `uint64` ranking functions to `algos.pyx` to allow for proper ranking with `uint64`.

Also introduces partial patch for `factorize()` by adding `uint64` hashtables and vectors for
usage. However, this patch is only partial because the larger bug of non-support for `uint64`
in `Index` has not been fixed:
~~~python
>>> from pandas import Index, np
>>> Index(np.array([2**63], dtype=np.uint64))
Int64Index([-9223372036854775808], dtype='int64')
~~~

Also removes `uint8` from testing in `test_merge.py` because `DataFrame.sort_values()`
incorrectly sorts when handling uint's on multiple columns:
~~~python
>>> from pandas import DataFrame, np
>>>
>>> col2 = ['a', 'a', 'a', 'b', 'b', 'b']
>>> col = np.array([2, 0, 1, 1, 2, 0], dtype=np.uint64)
>>> col_b = np.array([2, 0, 1, 1, 2, 0], dtype=np.int64)
>>>
>>> df = DataFrame({'a': col, 'b': col2})
>>> df_b = DataFrame({'a': col_b, 'b': col2})
>>>
>>> df.sort_values(['a'])  # Right (uint64)
   a  b
1  0  a
5  0  b
2  1  a
3  1  b
0  2  a
4  2  b
>>> df_b.sort_values(['a'])  # Right (int64)
   a  b
1  0  a
5  0  b
2  1  a
3  1  b
0  2  a
4  2  b
>>>
>>> df.sort_values(['a', 'b'])  # Wrong (uint64)
   a  b
2  1  a
3  1  b
0  2  a
4  2  b
1  0  a
5  0  b
>>> df2.sort_values(['a', 'b'])  # Right (uint64)
   a  b
1  0  a
5  0  b
2  1  a
3  1  b
0  2  a
4  2  b
~~~

2016-12-21 11:37 UTC, jreback commented on pandas/algos.pyx
> +cdef _take_2d_uint64(ndarray[uint64_t, ndim=2] values,
not sure why float64/int64/object are here either, they should also be in algos_take_helper.pxi.in

can you move there (could be in same PR or another ok)

2016-12-21 11:38 UTC, jreback commented on pandas/algos.pyx
> +def rank_1d_uint64(object in_arr, ties_method='average', ascending=True,
same we need to create a algos_rank_helper.pxi.in and move all of the rank routines (and then add uint64). prob easiest to move, then add (in another PR), but up to you.

2016-12-21 16:53 UTC, gfyoung commented on pandas/core/algorithms.py
> +    Parameters
👍 : can't really patch if you don't know what you're patching 😄

2016-12-22 05:46 UTC, gfyoung commented on pandas/core/algorithms.py
> +        raise TypeError("Array with ndim > 2 are not supported.")
There is now.

2016-12-22 05:46 UTC, gfyoung commented on pandas/algos.pyx
> +def rank_1d_uint64(object in_arr, ties_method='average', ascending=True,
Indeed.  Done.

2016-12-22 05:46 UTC, gfyoung commented on pandas/algos.pyx
> +cdef _take_2d_uint64(ndarray[uint64_t, ndim=2] values,
Makes sense.  Done.

2016-12-22 07:31 UTC, gfyoung commented
@jreback : Addressed all comments, and everything is green and passing. Ready to merge if there are no other concerns.

2016-12-23 17:53 UTC, gfyoung commented
@jreback : With #14934 merged, this is ready to be merged now.

2016-12-23 17:59 UTC, jreback requested changes

2016-12-23 17:59 UTC, jreback commented on pandas/src/algos_rank_helper.pxi.in
> +
prob could just have the same signature for object (and just ignore that arg no?)

2016-12-23 17:59 UTC, jreback commented on pandas/src/algos_rank_helper.pxi.in
> +    # py2.5/win32 hack, can't pass i8
remove this comment

2016-12-23 17:59 UTC, jreback commented on pandas/src/algos_rank_helper.pxi.in
> +        {{else}}
this could be nogil

2016-12-23 21:17 UTC, jreback commented on pandas/src/algos_rank_helper.pxi.in
> +
nvm, this is fine.

2016-12-24 08:35 UTC, gfyoung commented on pandas/src/algos_rank_helper.pxi.in
> +    # py2.5/win32 hack, can't pass i8
Done.

2016-12-24 08:35 UTC, gfyoung commented on pandas/src/algos_rank_helper.pxi.in
> +        {{else}}
Only for non-`object` but agreed.  Done.

2016-12-24 10:23 UTC, gfyoung commented
@jreback : Addressed all comments, and both Appveyor and Travis are passing.  Ready to merge if there are no other concerns.

2016-12-24 14:55 UTC, jreback commented on pandas/core/algorithms.py
> +        # once constructor has been fixed.
meaning where is the issue?

2016-12-24 14:57 UTC, jreback commented on pandas/src/algos_rank_helper.pxi.in
> +    {{if name == 'generic'}}
maybe change generic -> object so this is not necessary? (in a higher level definition)

2016-12-24 14:57 UTC, jreback commented on pandas/src/algos_rank_helper.pxi.in
> +dtypes = [('generic', 'object', 'Infinity()', 'NegInfinity()'),
here I mean, I don't think we use generic generically (and instead use object) nomenclature

2016-12-24 18:38 UTC, gfyoung commented on pandas/core/algorithms.py
> +        # once constructor has been fixed.
@jreback : I'm handling that TODO right now in #14937.  I'm literally tackling all of these problems simultaneously.

2016-12-24 18:39 UTC, gfyoung commented on pandas/src/algos_rank_helper.pxi.in
> +    {{if name == 'generic'}}
Yeah...that makes sense.  I haven't been giving too much thought to changing things, but as Travis and Appveyor are happy right now, it couldn't hurt to try.

2016-12-24 20:14 UTC, gfyoung commented on pandas/src/algos_rank_helper.pxi.in
> +dtypes = [('generic', 'object', 'Infinity()', 'NegInfinity()'),
Yep, done.

2016-12-24 20:41 UTC, jreback commented on pandas/core/algorithms.py
> +        # once constructor has been fixed.
ok sure

2016-12-24 20:43 UTC, jreback approved these changes

2016-12-24 20:43 UTC, jreback commented
lgtm. ping on green.

2016-12-24 21:24 UTC, gfyoung commented
@jreback : Everything is green now.  Ready to merge if there are no other concerns.

2016-12-24 22:04 UTC, closed without merging

2016-12-24 22:04 UTC, jreback commented
thanks!