API: allow list-like to DataFrame rename
pandas-dev/pandas pull request #15029
Opened 2017-01-01 15:20 UTC by chris-b1

- [x] closes #14829
 - [ ] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew entry

2017-01-01 15:31 UTC, jreback requested changes

2017-01-01 15:31 UTC, jreback commented on pandas/tests/test_generic.py
> +        result.rename(columns=['J', 'K'], index=['a', 'b'], inplace=True)
test with ndarray and with an Index
a scalar should error yes?

2017-01-01 16:47 UTC, jreback commented
this is also now an alternative to the ``.index =`` API (which is fine I think). So can you put some references in the doc-string and update the docs (where .set_index is).

2017-01-01 17:12 UTC, chris-b1 commented
I added a couple doc references, but I might be missing something - wasn't sure if there is a canonical spot for the `.index/.columns=` api?

2017-01-01 17:20 UTC, jreback commented
http://pandas.pydata.org/pandas-docs/stable/indexing.html#set-reset-index

ad-hoc indexing. This would be expanded in any event (and *maybe* moved to http://pandas.pydata.org/pandas-docs/stable/basics.html#renaming-mapping-labels) as these are the same idea.

2017-01-11 01:22 UTC, chris-b1 commented
Closing in favor of #15104

2017-01-11 01:22 UTC, closed without merging