Add quantile shortcut
pandas-dev/pandas pull request #15032
Opened 2017-01-01 19:15 UTC by srinivasreddy

- [ ] closes #15023 
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

2017-01-01 19:58 UTC, jreback commented
tests!

2017-01-01 20:00 UTC, jreback requested changes
look at how .mean is implemented

2017-01-02 15:36 UTC, jreback commented on pandas/core/groupby.py
> +    def quantile(self, *args, **kwargs):
not sure what you are doing here, this doesn't affect ``.resample``.

but more importantly w/o tests it is impossible to tell.

2017-02-27 16:02 UTC, jreback commented
can you rebase / update

2017-03-28 18:01 UTC, jreback commented
if you'd like to add tests and finish this up, pls ping.

2017-03-28 18:01 UTC, closed without merging

2017-04-28 16:10 UTC, pwaller commented
Ping @srinivasreddy. Would have used this :)