BUG: Indexing MultiIndex with Series failed.
pandas-dev/pandas pull request #15041
Opened 2017-01-03 01:38 UTC by bkandel

Previously, accessing elements of a MultiIndex-indexed DataFrame with a Series
failed. This changes that behavior so that it is possible to use a Series to
access elements from a MultiIndex-indexed DataFrame, just as one would use
a list.

 - [x] closes #14730
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew entry

2017-01-03 01:47 UTC, jreback requested changes

2017-01-03 01:47 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        y = Series([1, 3])
put this is tests/test_multilevel or test_indexing

find a very similar test (iow indexing a mi with list/ndarray) and put after

2017-01-03 01:47 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        tm.assert_series_equal(expected, actual_from_series)
result = ...
expected = ....
assert_series_equal(result, expected)

2017-01-03 01:47 UTC, jreback commented on pandas/tests/indexes/test_multi.py
>          # GH13854
check empty series as well

2017-01-03 01:47 UTC, jreback commented on pandas/core/indexing.py
> +                        # GH 14730
you can prob just

list(key)

2017-01-03 15:13 UTC, bkandel commented on pandas/core/indexing.py
> +                        # GH 14730
I thought taking the `.values` was more explicit, but `list` is probably more familiar. Changed.

2017-01-03 16:18 UTC, jreback commented on pandas/core/indexing.py
> +                        # GH 14730
no ``.values`` is fraught with issues as it converts dtypes, we don't use it internally if at all possible.

2017-01-04 00:00 UTC, closed without merging

2017-01-04 00:00 UTC, jreback commented
thanks @bkandel (I moved the tests to the appropriate location)