BUG: GH14233 resample().median() failed if duplicate column names wer…
pandas-dev/pandas pull request #15202
Opened 2017-01-23 22:48 UTC by Dr-Irv

Simple fix for  median issue.  Should use cython implementation.

 - [X] closes #14233
 - [X] tests added / passed
 - [X ] passes ``git diff upstream/master | flake8 --diff``
 - [X] whatsnew entry

2017-01-23 22:53 UTC, jreback commented on pandas/core/groupby.py
> -    _cython_functions['aggregate'].pop('median')
hmm, I remember something was failing because of this.......

2017-01-23 22:55 UTC, jreback requested changes

2017-01-23 22:55 UTC, jreback commented on pandas/tseries/tests/test_resample.py
> +        df = pd.DataFrame(np.array([[i + j for i in range(20)]
can you use the repro from the original issue?

2017-01-23 22:57 UTC, Dr-Irv commented on pandas/tseries/tests/test_resample.py
> +        df = pd.DataFrame(np.array([[i + j for i in range(20)]
Only difference is using `np.random.randn()` versus the sequence I put in there, which makes it easier to debug.  I can put the `randn()` if you want.

2017-01-23 22:58 UTC, Dr-Irv commented on pandas/core/groupby.py
> -    _cython_functions['aggregate'].pop('median')
I ran nosetests locally, and it works.  I looked back at old versions, and I think it is a legacy issue of how the cython stuff was implemented over time.

2017-01-24 16:29 UTC, jreback approved these changes

2017-01-24 16:30 UTC, jreback commented
lgtm. ping on green.

2017-01-24 18:46 UTC, closed without merging

2017-01-24 18:46 UTC, jreback commented
thanks!