BUG: TimedeltaIndex raising ValueError when boolean indexing (#14946)
pandas-dev/pandas pull request #15221
Opened 2017-01-25 06:21 UTC by mroeschke

- [x] closes #14946
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew entry

Implementing patch suggested by @jreback [here](https://github.com/pandas-dev/pandas/issues/14946#issuecomment-268666453) that prevents raising a `ValueError` when boolean indexing with a `TimedeltaIndex`

2017-01-25 12:48 UTC, jreback requested changes

2017-01-25 12:48 UTC, jreback commented on pandas/tseries/tests/test_timedeltas.py
> +        # GH 14946
put this in pandas/tests/indexing

create a new class for TimedeltaIndex

might be some other timedelta indexing routines you can group with it

2017-01-26 07:12 UTC, mroeschke commented
Moved the tests to `pandas/tests/indexing/test_indexing.py`, created class for TimedeltaIndex, and all green. I didn't find any tests here that tested TimedeltaIndex exclusively, so I didn't group any more under this class.

2017-01-26 14:57 UTC, jreback approved these changes

2017-01-26 15:01 UTC, closed without merging

2017-01-26 15:01 UTC, jreback commented
thanks @mroeschke keep em coming!