Do not cast .transform() output back to input dtype (closes #10972)
pandas-dev/pandas pull request #15256
Opened 2017-01-29 13:45 UTC by nbonnotte

- [x] closes #10972
 - [ ] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew entry

Maybe need more tests, and check performance?

2017-01-29 13:48 UTC, jreback reviewed
this needs perf  (just run the asv for groupby) and see

2017-01-29 16:34 UTC, nbonnotte commented
Well, each time I run asv, I get different results, but after closing everything and leaving my computer alone, here is what I get:
```
   before     after       ratio
  [3853fe6d] [2bc47491]
+   19.84ms    22.47ms      1.13  groupby.GroupBySuite.time_diff('float', 100)
+   12.45ms    13.92ms      1.12  groupby.FirstLast.time_groupby_nth_none('float64')
-    1.97ms     1.78ms      0.90  groupby.GroupBySuite.time_size('int', 10000)
-   27.05ms    24.28ms      0.90  groupby.GroupBySuite.time_rank('float', 100)
-   19.79ms    17.21ms      0.87  groupby.FirstLast.time_groupby_nth_none('object')
-   18.12ms    15.64ms      0.86  groupby.FirstLast.time_groupby_nth_none('datetime')
-   10.96ms     9.37ms      0.86  groupby.FirstLast.time_groupby_last('datetime')
```

2017-01-29 16:37 UTC, jreback commented
those are not the transform asv

2017-01-29 17:11 UTC, nbonnotte commented
I run `asv continuous -f 1.1 -E virtualenv upstream/master HEAD -b ^groupby`, but it's the first time I do perf, so I may have missed something :)

Is there something else I should do for this PR?

2017-01-29 17:31 UTC, nbonnotte commented
I think Appveyor is complaining about int being int32 on windows instead of int64. Is there a way to cast them to int64 instead?

2017-01-29 18:26 UTC, jreback requested changes
don't change any tests; you have to maintain the existing unless their is a really good reason

tests breaking generally means something is wrong in your code 

i suspect your changes are not propagating dtypes correctly 

add the tests from the issue

2017-01-29 18:26 UTC, jreback commented on pandas/tseries/tests/test_resample.py
>              exp = df.asfreq('T')
why r u changing tests like this?

2017-01-29 18:26 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +            result = getattr(df.groupby(labels), op)()
don't change tests

your changes are not robust

2017-01-29 20:17 UTC, nbonnotte commented
@jreback Hum, this is more complex than I thought

The initial problem is: `.transform` cast output dtypes back to input dtype, so `.size` for instance produce timestamps if the initial data was timestamps

If I keep the output type as it is, then `Series.mean`, for instance, will produce `float`. So if the original data is `float32`,  performing `.groupby().apply(lambda g: g.mean())`  might thus result in `float64` output, but `.groupby().mean()` will stay in `float32`.

Am I missing something obvious? How to proceed from there?

2017-01-29 20:19 UTC, jreback commented
you need to selectively cast

all lost every function should be cast except for things that produce ints (like size)

2017-01-29 20:27 UTC, nbonnotte commented
So `.groupby().agg(lambda : float(len(x)))` should keep producing timestamps if input is timestamps?

(That's how I stumbled on this issue when working on my PR #12607)

2017-01-29 20:35 UTC, jreback commented
@nbonnotte of course not, that's the point of this issue!

you simply need to infer based on the return values, not automatically cast it.

you *might* be able to simply stick it into a Series and it will work, BUT, you will still need to cast if its a numeric type (IOW a float) to the original type flavor.

2017-01-30 20:05 UTC, nbonnotte commented
Ok. I'm going to take it slow, starting with datetime input

2017-03-02 23:19 UTC, jreback commented
this was fixed by https://github.com/pandas-dev/pandas/commit/251826f0861159160bd1d51eafadb6e0b4161f77

2017-03-02 23:19 UTC, closed without merging

2017-03-03 07:56 UTC, nbonnotte commented
It looks so simple once you see the solution... Thanks @jreback for your feedback and your patience, sorry I couldn't get that through