TST: groupby.describe levels don't appear as column (#4792)
pandas-dev/pandas pull request #15260
Opened 2017-01-30 07:12 UTC by mroeschke

- [x] closes #4792
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``

Doesn't look like this was address in a PR in 0.20, but the original issue works on master.

2017-01-30 11:33 UTC, jreback requested changes

2017-01-30 11:33 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +                                               ['count', 'mean', 'std',
instead of constructing this way

use concat with keys on the subframes

2017-01-30 14:20 UTC, jreback commented
Actually I think the bug is still present. The issue that you want this

```
In [10]: df.groupby('PRICE').VOLUME.describe().unstack(1)
Out[10]: 
       count          mean           std           min           25%           50%           75%           max
PRICE                                                                                                         
24990    1.0  1.500000e+09           NaN  1.500000e+09  1.500000e+09  1.500000e+09  1.500000e+09  1.500000e+09
25499    2.0  2.550000e+09  3.464823e+09  1.000000e+08  1.325000e+09  2.550000e+09  3.775000e+09  5.000000e+09
```

rather than this
```
In [9]: df.groupby('PRICE').VOLUME.describe()
Out[9]: 
PRICE       
24990  count    1.000000e+00
       mean     1.500000e+09
       std               NaN
       min      1.500000e+09
       25%      1.500000e+09
       50%      1.500000e+09
       75%      1.500000e+09
       max      1.500000e+09
25499  count    2.000000e+00
       mean     2.550000e+09
       std      3.464823e+09
       min      1.000000e+08
       25%      1.325000e+09
       50%      2.550000e+09
       75%      3.775000e+09
       max      5.000000e+09
Name: VOLUME, dtype: float64
```

we do a similar unstack already with ``.ohlc``. 
```
In [8]: df.groupby('PRICE').VOLUME.ohlc()
Out[8]: 
             open        high         low       close
PRICE                                                
24990  1500000000  1500000000  1500000000  1500000000
25499  5000000000  5000000000   100000000   100000000
```

So each group gets a single row, while multi-columns are present for multiple aggregations.
multi-index are present for *multiple* groupers.

2017-01-30 21:36 UTC, mroeschke commented
Ah that makes sense. Thanks for clarifying the expected output!

I've been poking into the code, and since each group goes through `apply()` and `describe()` returns the metrics labeled on the index, it tries to vertically concat the `describe()` results for each group:

```
(Pdb) values
[             VOLUME
count  1.000000e+00
mean   1.500000e+09
std             NaN
min    1.500000e+09
25%    1.500000e+09
50%    1.500000e+09
75%    1.500000e+09
max    1.500000e+09,              
              VOLUME
count  2.000000e+00
mean   2.550000e+09
std    3.464823e+09
min    1.000000e+08
25%    1.325000e+09
50%    2.550000e+09
75%    3.775000e+09
max    5.000000e+09]
```

I could add some logic saying if the indexes for each group are the same, concat on the index and transpose to the columns, but I think that'd be a pretty big change since it will probably affect all `groupby.apply()` functions. Or should we make a special case for `describe()`? Thoughts @jreback?

2017-01-30 21:48 UTC, jreback commented
so you *do* just need to define ``.describe`` as a method on ``DataFrameGroupby`` and ``SeriesGroupby``, then you can do the ``.apply`` (followed by the unstack).

Right now we automagically just do any whitelisted function (including .describe) and they go thru the standard reshaping things. If you can figure out a generic way to do this great, but otherwise defining a method is fine.

2017-02-01 07:39 UTC, mroeschke commented
Cool, thanks for the insight. 

I defined a new method for `groupby.describe()` and noticed in the process if `groupby(...,axis=1).describe()` is called, the transposing returns the desired results instead of unstacking. I also had to subsequently change a lot of the existing tests since the output has changed. Most notably the test for #14848 changed a lot.

2017-02-01 14:13 UTC, jreback requested changes

2017-02-01 14:13 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> + - ``groupby.describe()`` now labels the `describe()` metrics in the column instead of the index (:issue:`4792`)
I think move this to a sub-section and show previous and current behavior.

2017-02-01 14:13 UTC, jreback commented on pandas/core/groupby.py
> +        Provide summary statistics for each group, excluding NaN values
pls add a full doc-string, with named arguments. You might be able to simply add Series.describe and DataFrame.describe in the Notes section.

2017-02-01 14:13 UTC, jreback commented on pandas/core/groupby.py
> +        Provide summary statistics for each group, excluding NaN values
or as you do below just use the DataFrame doc-string

2017-02-03 07:17 UTC, mroeschke commented
Added previous/current behavior in whatsnew, documentation to describe with `DataFrame.describe.__doc__`, and fixed other failing tests.

2017-02-03 13:59 UTC, jreback requested changes

2017-02-03 13:59 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +This format is consistent with ``groupby.ohlc()`` (:issue:`4792`)
more to the point its consistent with how ``.agg()`` works.

2017-02-03 13:59 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +This format is consistent with ``groupby.ohlc()`` (:issue:`4792`)
most people prob don't know about ``.ohlc()`` :>

2017-02-03 13:59 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +.. code-block:: ipython
use an ipython-block here (so the code executes)

2017-02-03 13:59 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +                                            .to_frame()
This seems like lots of reshapings (this is current master)

```
In [6]: df
Out[6]: 
   A    B    C
0  1  2.0  foo
1  1  NaN  bar
2  3  NaN  baz

In [7]: df.groupby('A').describe()
Out[7]: 
           B
A           
1 count  1.0
  mean   2.0
  std    NaN
  min    2.0
  25%    2.0
  50%    2.0
  75%    2.0
  max    2.0
3 count  0.0
  mean   NaN
  std    NaN
  min    NaN
  25%    NaN
  50%    NaN
  75%    NaN
  max    NaN

In [8]: df.groupby('A').describe().unstack()
Out[8]: 
      B                                  
  count mean std  min  25%  50%  75%  max
A                                        
1   1.0  2.0 NaN  2.0  2.0  2.0  2.0  2.0
3   0.0  NaN NaN  NaN  NaN  NaN  NaN  NaN
```

2017-02-06 20:27 UTC, mroeschke commented on pandas/tests/groupby/test_groupby.py
> +                                            .to_frame()
In this test, the `result = df.groupby('A').describe().unstack()` after `unstack()` was added to `groupby.describe()`. Shouldn't `expected` follow an independent path to the `result`?

2017-02-06 20:35 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +                                            .to_frame()
yes, but you can simply directly construct this result (as its 'simple' enough), just ``pd.DataFrame(.....)``

2017-02-06 22:12 UTC, mroeschke commented on pandas/tests/groupby/test_groupby.py
> +                                            .to_frame()
Ah I see thanks! Agreed that my it my first edit probably included too much reshaping.

2017-02-07 06:23 UTC, mroeschke commented
Replaced API example using `groupby.agg()` instead of `groupby.ohlc()`, fixed the code block, and simplified `expected` in `test_non_cython_api`

2017-02-07 15:31 UTC, jreback approved these changes

2017-02-07 15:34 UTC, jreback commented
hmm, something is wrong here. Its including the grouper.
```
In [1]: df = pd.DataFrame({'A': [1, 1, 2, 2], 'B': [1, 2, 3, 4]})

In [2]: df.groupby('A').describe()
Out[2]: 
      A                                        B                                          
  count mean  std  min  25%  50%  75%  max count mean       std  min   25%  50%   75%  max
A                                                                                         
1   2.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0   2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0
2   2.0  2.0  0.0  2.0  2.0  2.0  2.0  2.0   2.0  3.5  0.707107  3.0  3.25  3.5  3.75  4.0

In [3]: df.groupby('A').agg(['mean', 'std'])
Out[3]: 
     B          
  mean       std
A               
1  1.5  0.707107
2  3.5  0.707107
```

2017-02-07 19:39 UTC, mroeschke commented
It looks like the grouper is included when using `groupby.apply()`:

```
In [4]: pd.__version__
Out[4]: u'0.19.2' #not current master

In [5]: df.groupby('A').apply(lambda x: x.describe()) 
Out[5]:
           A         B
A
1 count  2.0  2.000000
  mean   1.0  1.500000
  std    0.0  0.707107
  min    1.0  1.000000
  25%    1.0  1.250000
  50%    1.0  1.500000
  75%    1.0  1.750000
  max    1.0  2.000000
2 count  2.0  2.000000
  mean   2.0  3.500000
  std    0.0  0.707107
  min    2.0  3.000000
  25%    2.0  3.250000
  50%    2.0  3.500000
  75%    2.0  3.750000
  max    2.0  4.000000

```

Can be seen with other functions as well:

```
In [11]: df.groupby('A').apply(np.mean) #not idiomatic but should be similar to  df.groupby('A').mean()
Out[11]:
     A    B
A
1  1.0  1.5
2  2.0  3.5
```

Is this a known issue?

2017-02-07 19:48 UTC, jreback commented
@mroeschke so by-definition this is what apply does.

you can use ``._set_group_selection()`` to avoid this problem.

2017-02-07 19:52 UTC, mroeschke commented
Ah thanks for clarifying that @jreback. Will edit to use `._set_group_selection()` tonight.

2017-02-10 00:06 UTC, mroeschke commented
Added `_set_group_selection()` to prevent the grouper from being included and resolved conflict with whatsnew

2017-02-10 00:19 UTC, closed without merging

2017-02-10 00:19 UTC, jreback commented
thanks!

keep em coming!