ENH: Added ability to freeze panes from DataFrame.to_excel() (#15160)
pandas-dev/pandas pull request #15291
Opened 2017-02-02 05:28 UTC by jeffcarey

- [X ] closes #15160
 - [ ] tests passed- Pending- see below 
 - [X] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry- Pending - see below.

The ability to freeze panes has been added to the to_excel() method on data frames. The parameter is a tuple of 2 integers, representing the bottom-most row and right-most column to freeze, respectively. (This is the same format xlsxwriter uses). The default value is None, resulting in no freezing.

Example usage: 
df.to_excel(writer, sheet_name='Sheet1', freeze_panes=(1,1))

The following engines are supported:
xlsxwriter
xlwt
openpyxl22

The parameter exists for openpyxl20 and openpyxl1 but it has no effect, in anticipation of support for these versions being dropped (#15184).

Can one of the maintainers confirm this approach for engine support is adequate, or suggest an alternative? Once that is settled I can write a test to create a workbook using each engine and then try reading it back in using openpyxl.

2017-02-02 13:43 UTC, jreback commented
seems reasonable to me. yeah I wouldn't worry about supporting older version of openpyxl.

not sure how to test this (except for a smoke test I think).

2017-02-02 13:43 UTC, jreback requested changes

2017-02-02 13:43 UTC, jreback commented on pandas/io/excel.py
> +            wks.freeze_panes = wks.cell(row=freeze_panes[0] + 1,
vaidate that its a len 2 tuples

2017-02-02 13:43 UTC, jreback commented on pandas/io/excel.py
> +            wks.set_panes_frozen(True)
same here

2017-02-02 13:43 UTC, jreback commented on pandas/io/excel.py
> +            wks.freeze_panes(*(freeze_panes))
same (you may want to make a general validation for this somewhere)

2017-02-02 13:44 UTC, jreback commented
pls add a whatsnew note, update docs in io.rst (maybe put a small section on 'Style'), IOW things that you can do. (we don't really support much readl styling yet (other issues about that), though things like float_format could be included).

2017-02-03 15:35 UTC, chris-b1 commented on pandas/core/frame.py
> +                 freeze_panes=None):
Add `freeze_panes` to the docstring here, which this function uses
https://github.com/pandas-dev/pandas/blob/9ddba8dc811184c49d9bc4df5dc97d505345ec23/pandas/core/generic.py#L1021

2017-02-04 22:52 UTC, jeffcarey commented
@jreback @chris-b1 Requested changes made, please review. 

Also, I can look at supporting autofilter as well, as was mentioned in the original issue. Shall I open a separate issue for that? Sounds cleaner to me.

2017-02-04 23:13 UTC, jreback commented
@jeffcarey that's fine to open a new issue.

One thing to thing about is do we just keep adding kwargs to ``.to_excel``? or a better API?

@chris-b1

2017-02-04 23:35 UTC, jreback commented on pandas/core/generic.py
> +        is to be frozen
add a versionadded tag here

2017-02-04 23:36 UTC, jreback commented on pandas/io/excel.py
> +            freeze_panes is not None and
maybe make this a validation function

``
freeze_panes = _validate_freeze_panes(freeze_panes)
if freeze_panes:
    ....
```

2017-02-04 23:37 UTC, jreback commented
can you add a smoke test to write & then read back a simple frame.

2017-02-04 23:47 UTC, chris-b1 commented
@jreback - not sure on the API, for now probably easiest as a kwarg.

I guess could see having some kind of template / styler like api?

```
df.to_excel('tmp.xlsx') # default, template=ExcelTemplate

my_template =  pd.ExcelTemplate.freeze_panes().autofilter()

df.to_excel('tmp2.xlsx', template=my_template)
```

2017-02-04 23:52 UTC, jreback commented
@chris-b1 yeah, I guess if only a couple of other options then kwargs is the way to go.

2017-02-07 16:31 UTC, jreback commented on doc/source/io.rst
> +Style and Formatting
you can add a ref-tag here: io.excel.style

2017-02-07 16:32 UTC, jreback commented on pandas/core/frame.py
> +            else:
don't need the else

2017-02-07 16:33 UTC, jreback commented on pandas/io/tests/test_excel.py
> +    # GH15160
put the comment inside the function

2017-02-07 16:34 UTC, jreback commented
minor comments, some flake issues (use ``git diff master | flake8 --diff`` to see).

lgtm. ping on green.

2017-02-08 17:03 UTC, jeffcarey commented
@jreback Checks are green. Do you want me to fix the conflict that came up in the whatsnew or is that something you can do?

2017-02-08 17:17 UTC, jreback commented
@jorisvandenbossche comments?

@jeffcarey can fix it on merge.

2017-02-14 23:08 UTC, jreback commented
can you rebase

2017-02-15 16:29 UTC, jreback commented
@jeffcarey can you rebase and push one more time. sorry had asome issues with the ci.

2017-02-16 17:47 UTC, closed without merging

2017-02-16 17:47 UTC, jreback commented
thanks!

keem em coming!

2017-02-16 22:52 UTC, jorisvandenbossche reviewed
@jeffcarey a bit late feedback for the PR, but if you would like to do a small follow-up PR for this, always welcome!

2017-02-16 22:52 UTC, jorisvandenbossche commented on doc/source/io.rst
> +freeze the first row and first column (default None)
this line will not be formatted nicely in the html docs (it needs two spaces at the start to have it indented in the list)

2017-02-16 22:52 UTC, jorisvandenbossche commented on pandas/core/generic.py
> +        is to be frozen
Does this start at zero or one?

2017-03-04 23:50 UTC, jreback commented
@jeffcarey I just realized that https://github.com/pandas-dev/pandas/blame/master/pandas/core/frame.py#L1441 was defined in ``core/frame.py``. This should *only* be in ``io/excel.py``. We want to make code ``core/frame.py`` as simple as possible, and this is completely extraneous.

Can you do a PR to remove (and simply put it in ``.write_cells``, where I think it is already validated anyhow).