Numexpr 2.4.6
pandas-dev/pandas pull request #15383
Opened 2017-02-13 10:52 UTC by FrancescAlted

- [x ] closes #15382 
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew entry

This addresses #15213.  Actually, the recommended version for me is 2.6.2, but I understand that this is too recent still.

2017-02-13 11:21 UTC, jorisvandenbossche commented
@FrancescAlted we have a few occurences of numpexpr pinned at older versions in ci/requirement files (I think the 2.7_COMPAT.run and 3.4_SLOW.run ones). Best to change those versions to 2.4.6 then.

2017-02-13 11:40 UTC, jreback requested changes

2017-02-13 11:40 UTC, jreback commented on doc/source/install.rst
> +  If installed, must be Version 2.4.6 or higher.  Numexpr 2.6.2 or higher is strongly recommended.
you don't need the recommended part

2017-02-13 11:40 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +   Due to important fixes and performance improvements, ``numexpr`` version is now required to be >= 2.4.6 and it will not be used at all if this requisite is not fullfilled (:issue:`15213`).
i would just move this to the other api changes section; just say 2.4.6 is now required

2017-02-13 11:40 UTC, jreback commented on pandas/computation/__init__.py
> -        warnings.warn(
there is a test for this i think

2017-02-13 11:45 UTC, FrancescAlted commented on doc/source/install.rst
> +  If installed, must be Version 2.4.6 or higher.  Numexpr 2.6.2 or higher is strongly recommended.
Well, IMO the improvements in https://github.com/pydata/numexpr/blob/master/RELEASE_NOTES.rst#changes-from-261-to-262 are worth a recommendation, but I can remove it if you insist.

2017-02-13 11:48 UTC, FrancescAlted commented on doc/source/whatsnew/v0.20.0.txt
> +   Due to important fixes and performance improvements, ``numexpr`` version is now required to be >= 2.4.6 and it will not be used at all if this requisite is not fullfilled (:issue:`15213`).
You probably mean "Other enhancements" section (numexpr does not introduce any API change).

2017-02-13 11:57 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +   Due to important fixes and performance improvements, ``numexpr`` version is now required to be >= 2.4.6 and it will not be used at all if this requisite is not fullfilled (:issue:`15213`).
it's an API change for pandas meaning if u has a version that is no longer supported then things will change - its also something to be aware of when upgrading

2017-02-13 11:58 UTC, jreback commented on doc/source/install.rst
> +  If installed, must be Version 2.4.6 or higher.  Numexpr 2.6.2 or higher is strongly recommended.
it may be but back compat is more important

2017-02-13 18:01 UTC, FrancescAlted commented on pandas/computation/__init__.py
> -        warnings.warn(
Yep.  Addressed in https://github.com/pandas-dev/pandas/pull/15383/commits/f22559876b130891e7c834cf269d1289307e3fa3.

2017-02-13 18:10 UTC, FrancescAlted commented on pandas/computation/__init__.py
> -        warnings.warn(
and fixed a typo in https://github.com/pandas-dev/pandas/pull/15383/commits/7a275ce974fbd85cbbf65f2feda32b06ea836917

2017-02-13 19:24 UTC, FrancescAlted commented
There are a couple of ["allowed failures" in TravisCI](https://travis-ci.org/pandas-dev/pandas/builds/201215599).  Any hint on what's going on there?

2017-02-13 22:55 UTC, jorisvandenbossche commented
For the MacOSX one, I see 

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - numexpr 2.4.6
  - pytables 3.0.0 -> numexpr 2.2*
```

2017-02-14 09:13 UTC, FrancescAlted commented
Uh, I see the Mac OSX build that completed just fine.  Also, the AppVeyor failure seems like a transitory failure during conda packages access:

```
conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: HTTPError: 502 Server Error: Bad Gateway for url: https://repo.continuum.io/pkgs/free/win-64/xlsxwriter-0.9.6-py35_0.tar.bz2: https://repo.continuum.io/pkgs/free/win-64/xlsxwriter-0.9.6-py35_0.tar.bz2
```

But I am still unsure on the level of importance of the ["allowed failures" in TravisCI](https://travis-ci.org/pandas-dev/pandas/builds/201215599).

2017-02-14 09:28 UTC, jorisvandenbossche commented
Sorry, I mislooked, not the MacOSX build of course, build number 6 with the old versions (2.7_COMPAT), the error now is:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - numexpr 2.4.6 -> numpy 1.10*
  - numpy 1.7.1
Use "conda info <package>" to see the dependencies for each package.
```

We want to keep the numpy 1.7 there for now (although there is an issue to bump that requirement as well), so I would just keep the older numexpr in this build (then it is a test that you get the correct error for that).

> But I am still unsure on the level of importance of the "allowed failures" in TravisCI.

They are not 'allowed' to fail in principle (only for specific things, eg compat issue with numpy master that is not yet fixed). I think it is like that to get quicker feedback from travis.

There is still a lint error:

```
pandas/computation/__init__.py:18:17: E128 continuation line under-indented for visual indent
```

The appveyor issue indeed does not seem to be related to this PR.

2017-02-14 10:18 UTC, jorisvandenbossche commented
@FrancescAlted Was it needed to also revert the version change in the 3.4_SLOW build? As this one was not failing I think.

2017-02-14 10:35 UTC, FrancescAlted commented
Yes, it was: https://travis-ci.org/pandas-dev/pandas/builds/201238220.  I am not familiar with the convention to run different configurations, but I'd say that stems from: https://github.com/pandas-dev/pandas/blob/master/.travis.yml#L131.  I just reverted the numexpr versions existing in this two scenarios.  My intention is to look at the possible errors after the revert and try to fix them.

2017-02-14 13:28 UTC, jreback commented
i would change this version to 2.4.6, otherwise lgtm. https://github.com/pandas-dev/pandas/blob/master/ci/requirements-3.4_SLOW.run

ping on green.

2017-02-14 13:28 UTC, jreback approved these changes

2017-02-14 15:29 UTC, FrancescAlted commented
I think we will still have a remaining error [here](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/computation/test_compat.py#L29).  But the assert will not raise the error as such, and we would need something like `from pandas.computation import __NUMEXPR_INSTALLED`.  However, there is a line at the beginning saying `from pandas.computation import _MIN_NUMEXPR_VERSION` which already raises the warning, and hence the error is not re-raised.  Not sure how to cope with that.  Opinions?

2017-02-14 15:47 UTC, jorisvandenbossche commented
So probably that test never worked .. What you could do is move the import inside the test and in a "catch warnings" context, and then check that a warning is raised in the specific case and not otherwise (https://docs.python.org/3.5/library/warnings.html#testing-warnings)?

2017-02-14 16:33 UTC, jreback commented
no it worked but the import process is changed by this PR
it needs to be protected

2017-02-14 19:38 UTC, FrancescAlted commented
I have been looking at the original code, and I don't think it worked because `assert not _NUMEXPR_INSTALLED` cannot possibly raise a Warning; can it?

2017-02-14 21:11 UTC, jreback commented
so I think with the changed up order of tests, this ``test_compat`` that is failing (on 2.7_COMPAT) is not able to assert the warning as its already been produced (you can see in the output actually).

So I guess just change the test then.

2017-02-15 09:07 UTC, FrancescAlted commented
Ok, I think that I have found the issue and fixed it in e1b34a9.  Basically, one needs to force the `reload()` of `pandas.computation` module to trigger the `UserWarning` in import time.  Hopefully we should see all green after this one.

2017-02-15 10:54 UTC, FrancescAlted commented
Well, it turns out that `reload()` is tricky and it still cannot raise the `UserWarning` in Python 2.7 (although 3.4 seems to work well).  After googling a bit, I have read that [`reload()` is very tricky to get right](http://stackoverflow.com/a/684229/3095325), so my vote is to remove this `UserWarning` test completely (unless you have a better proposition).

2017-02-15 13:14 UTC, jreback commented
@FrancescAlted I would just remove the check for the warning (leave the test just don't assert that it produces)

2017-02-15 13:15 UTC, jreback commented on pandas/tests/computation/test_compat.py
> +# Get reload for Python 3.4 and on, if not, use internal reload()
too complicated, don't reload

2017-02-15 13:15 UTC, jreback commented on pandas/tests/computation/test_compat.py
>              with tm.assert_produces_warning(UserWarning,
just remove this ``assert_produces_warning``

2017-02-15 13:15 UTC, jreback commented on pandas/tests/computation/test_compat.py
> +                reload(pd.computation)
too complicated

2017-02-15 13:34 UTC, jreback commented
lgtm. ping on green.

2017-02-15 13:35 UTC, FrancescAlted commented
Done.  Hopefully this will give us all green (bar some temporary failures that apparently are usual in TravisCI).

2017-02-15 13:38 UTC, jreback commented
@FrancescAlted well there have been some flakiness with some gbq tests; I turned them off for now. We *should* have all green. 

FYI we just have the fail fast to make the results appear quicker. We have LOTS of configurations to test. So allowed failures are really NOT allowed :>

2017-02-15 13:40 UTC, jreback commented
one more FYI. every push on a PR generates a new travis run (which can take hours). So generally like to bunch them up if possible. This PR of course is a case that its necessary to test little changes so no big deal.

2017-02-15 15:21 UTC, jreback commented
thanks @FrancescAlted

2017-02-15 15:21 UTC, closed without merging