BUG: Concat with inner join and empty DataFrame
pandas-dev/pandas pull request #15397
Opened 2017-02-14 17:19 UTC by abaldenko

- [ ] closes #15328
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

2017-02-14 21:48 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
>  - Bug in ``.eval()`` which caused multiline evals to fail with local variables not on the first line (:issue:`15342`)
just an FYI, if you put changes in whatsnew NOT at the end (but in empty space that is left), then you won't get conflicts.

2017-02-14 21:52 UTC, jreback requested changes

2017-02-14 21:52 UTC, jreback commented on pandas/tests/tools/test_concat.py
> +        df_empty = pd.DataFrame()
put a comment here for the issue number (rather than in the test name) (try to be descriptive with that if possible)

2017-02-14 21:52 UTC, jreback commented on pandas/tests/tools/test_concat.py
> +        self.assertTrue(result.empty)
construct the result frame and use assert_frame_equal

2017-02-14 21:52 UTC, jreback commented on pandas/tests/tools/test_concat.py
> +        self.assertTrue(result.empty)
same

2017-02-14 21:52 UTC, jreback commented on pandas/tests/tools/test_concat.py
>      def test_concat_series_axis1_same_names_ignore_index(self):
can you systematically tests the how=* here? (for the empty cases)

2017-02-14 21:52 UTC, jreback commented on pandas/tests/tools/test_merge.py
> +        self.assertTrue(result.empty)
same as above

2017-02-14 23:11 UTC, abaldenko commented on doc/source/whatsnew/v0.20.0.txt
>  - Bug in ``.eval()`` which caused multiline evals to fail with local variables not on the first line (:issue:`15342`)
ah i see. makes sense. thanks!

2017-02-14 23:11 UTC, abaldenko commented on pandas/tests/tools/test_concat.py
>      def test_concat_series_axis1_same_names_ignore_index(self):
sorry i'm not clear on what you mean here. could you clarify our point to something similar ?

2017-02-14 23:17 UTC, jreback commented on pandas/tests/tools/test_concat.py
>      def test_concat_series_axis1_same_names_ignore_index(self):
what I mean is something like:

```
for how, expected in [('inner', df_empty), ('outer', df_a), ('left', df_a), ('right', df_empty)]:
    result = pd.concat([df_a, df_empty, axis=1, join=how)
    assert_frame_equal(result, expected)
```
```

(now obviously the concat results are different for these)

2017-02-16 17:31 UTC, abaldenko commented on pandas/tests/tools/test_concat.py
>      def test_concat_series_axis1_same_names_ignore_index(self):
oh haha. got it. thanks!

2017-02-16 17:38 UTC, jreback commented on pandas/tests/tools/test_concat.py
> +        for how, expected in [('inner', df_expected), ('outer', df_a)]:
right forgot this only accepts outer & inner

2017-02-16 17:41 UTC, jreback commented
thanks @abaldenko !

2017-02-16 17:41 UTC, closed without merging