BUG: GH15426 timezone lost in groupby-agg with cython functions
pandas-dev/pandas pull request #15433
Opened 2017-02-16 23:19 UTC by stephenrauch

- [x] closes #15426
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew entry

2017-02-17 14:50 UTC, jreback requested changes

2017-02-17 14:50 UTC, jreback commented on pandas/tests/groupby/test_aggregate.py
> +        ts = pd.Timestamp("2016-01-01 12:00:00", tz='US/Pacific')
add the issue number as a comment

2017-02-17 14:50 UTC, jreback commented on pandas/tests/groupby/test_aggregate.py
> +        result1 = df.groupby('a')['b'].agg(np.min).iloc[0]
compare with ``.min()`` as well

2017-02-17 14:50 UTC, jreback commented on pandas/types/cast.py
> +                    result = to_datetime(result).tz_localize('utc')
can add addtl tests in ``pandas/tests/types/test_cast.py`` fit them in as appropriate. take out this fix temporarily to validate your test cases, then add back to make sure they work.

2017-02-17 14:51 UTC, jreback commented
add examples from https://github.com/pandas-dev/pandas/issues/10668 as well. (and you can list list issue in the whatsnew too)

2017-02-23 13:26 UTC, jreback commented
can you update

2017-02-24 14:18 UTC, stephenrauch commented
I will take care of this this weekend...

On Thu, Feb 23, 2017 at 5:27 AM, Jeff Reback <notifications@github.com>
wrote:

> can you update
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/15433#issuecomment-281990871>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AJ7NeshkvzXo2tuiRjqZ-4PTvtkl-iCHks5rfYkmgaJpZM4MDrH->
> .
>

2017-02-27 15:46 UTC, closed without merging

2017-02-27 15:46 UTC, jreback commented
thanks!