fast non-unique indexing
pandas-dev/pandas pull request #15468
Opened 2017-02-21 10:15 UTC by Horta

This is essentially the same pull request as https://github.com/pandas-dev/pandas/pull/15372 but now from a proper branch.

2017-02-21 13:01 UTC, jreback requested changes

2017-02-21 13:01 UTC, jreback commented on pandas/indexes/base.py
> +
this is quite messy, what are you trying to do here?

2017-02-21 13:01 UTC, jreback commented on pandas/index.pyx
> +                                         int64_t[:] idx1):
this is a massive amount of added code, what exactly are you doing?

2017-02-22 12:21 UTC, Horta commented on pandas/indexes/base.py
> +
Agreed! Just factorised that.

2017-02-22 16:18 UTC, jreback commented on pandas/indexes/base.py
> +
you are adding much more code. Where exactly does this routine fail? The only scenario I could see is with actual mixed types (which I am happy to raise on when you have a non-unique index). 

Further it looks like you are duplicating lots of functionailty that already exists, see pandas/core/algorithms.py w.r.t. counting / sorting / factorizing.

2017-02-24 16:24 UTC, Horta commented on pandas/indexes/base.py
> +
I didn't find routines un pandas/core/algorithms.py that I could use. I have now described the functions in index.pyx so I hope it is now clearer.

Yes, I was having problem with mixed types. For example,

```python
v = np.array([1, 'danilo'], object)
v[0] < v[1]
```
raises a `TypeError` exception.

2017-02-24 16:26 UTC, Horta commented on pandas/index.pyx
> +                                         int64_t[:] idx1):
Notice that I have removed the code regarding lists. Most of the code consists in two functions: `_count` and `_map`. They implement two very specific algorithms that I couldn't find in the above-mentioned file.

2017-02-24 18:38 UTC, Horta commented
Benchmark:

```python
import numpy as np
import pandas as pd
from time import time
from pandas import Index

n = 10000
r = 100


for j in range(1, 11):
    i = Index(list(range(j*n)) * r)
    slic = i[0:j*n]
    start = time()
    i.get_indexer_non_unique(slic)
    print(time() - start)
```

Elapsed time in seconds:

```
Previous | New
---------------
    0.92 | 0.18
    3.03 | 0.37
    6.25 | 0.64
   10.90 | 0.79
   17.82 | 1.00
   25.07 | 1.16
   31.49 | 1.33
   40.97 | 1.53
   51.54 | 2.03
   60.64 | 2.18
```

2017-02-24 20:24 UTC, jreback commented on pandas/index.pyx
> +
this is exactly value_counts

2017-02-24 20:26 UTC, jreback commented
@Horta you are adding more and more code. I want LESS code. you are rewriting the world here.

2017-02-24 20:30 UTC, jreback commented
pls add an asv.

2017-02-24 20:30 UTC, jreback requested changes

2017-02-24 20:30 UTC, jreback commented on pandas/index.pyx
> +            int64_t[:] mapping, int64_t[:] missing):
this signature is WAY too complicated.

2017-02-24 20:30 UTC, jreback commented on pandas/index.pyx
> +
this looks like a take, but really not sure what you are doing

2017-02-24 20:30 UTC, jreback commented on pandas/index.pyx
> +
you can add 1 function in cython, anything else is WAY too complicated.

2017-02-24 20:30 UTC, jreback commented on pandas/indexes/base.py
> +        (orderable, idx0, idx1) = _order_them(is_mono0, src_values, is_mono1,
if you insist on ordering, then simply order an unordered index, get the results and take the original. this is so much complexity.

2017-02-24 20:30 UTC, jreback commented on pandas/indexes/base.py
> +    return (True, indices)
do ALL of this in the cython function. you are needlessly splitting things up.

2017-02-25 00:38 UTC, Horta commented
@jreback You are such an ass. Closing here as I'm not helping it anymore.

2017-02-25 00:38 UTC, closed without merging

2017-02-25 00:40 UTC, jreback commented on pandas/indexes/base.py
> +        (orderable, idx0, idx1) = _order_them(is_mono0, src_values, is_mono1,
@Horta we don't tolerate that type of language

2017-02-25 00:41 UTC, jreback commented
@Horta we don't tolerate that type of language