BUG: GH #12223, GH #15262. Allow ints for names in MultiIndex
pandas-dev/pandas pull request #15478
Opened 2017-02-22 22:25 UTC by Dr-Irv

- [X] closes #12223 and #15262
 - [X] tests added / passed
  - `pandas/tests/frame/test_combine_concat.py::TestDataFrameConcatCommon::test_concat_numerical_names`
 - [X] passes ``git diff upstream/master | flake8 --diff``
 - [X] whatsnew entry

See discussion in #10461 .  Now if we internally know we need to call `get_level_values` for a specific level number, there is an internal function for doing that, which should allow better support for when people create indices with names that are integers.

2017-02-23 01:54 UTC, jreback commented
did u mean to close?
this looks pretty reasonable

2017-02-23 14:28 UTC, Dr-Irv commented
@jreback yes.  The conflicts indicated you had made a change that was incompatible with what I did, so I need to fix that.  Will create a new pull request when ready.

2017-02-23 14:41 UTC, jreback commented
@Dr-Irv you don't need to close a PR to fix that though. simply rebase and force push. you *never* need to open a new PR for the same exact issue.

2017-02-23 14:43 UTC, Dr-Irv commented
@jreback OK, didn't know that.  Should I reopen this one when I'm ready?

2017-02-23 14:43 UTC, jreback commented
sure

2017-02-23 14:44 UTC, jreback commented
see more detail here: http://pandas.pydata.org/pandas-docs/stable/contributing.html#contributing-your-changes-to-pandas

2017-02-23 15:04 UTC, jorisvandenbossche commented
@Dr-Irv Already reopened it, because if you push again while the PR is closed, you cannot reopen it anymore.

2017-02-23 17:13 UTC, jreback requested changes

2017-02-23 17:13 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- ``Series/DataFrame.squeeze()`` have gained the ``axis`` parameter. (:issue:`15339`)<<<<<<< f4edb053e17e51e8c2bed7c16755c4f7f3222117
merge residual :>

2017-02-23 17:13 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- Using numerical names in ``MultiIndex`` causes less errors. (:issue:`12223`) (:issue:`15262`)
say instead about the bug report about output formatting with a MI under certain conditions.

2017-02-23 17:13 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- Using numerical names in ``MultiIndex`` causes less errors. (:issue:`12223`) (:issue:`15262`)
``(:issue:`12223`, :issue:`15262`)``

2017-02-23 17:13 UTC, jreback commented on pandas/indexes/base.py
> +        # Used to mirror implementation for MultiIndex
better to add an actual doc-string

2017-02-23 17:13 UTC, jreback commented on pandas/indexes/multi.py
> +        copy  : bool whether copy of results should be done
why are you adding this? this is a whole different ball game.

2017-02-23 19:20 UTC, Dr-Irv commented on pandas/indexes/multi.py
> +        copy  : bool whether copy of results should be done
@jreback What I needed `_get_level_values()` to do is have the same behavior as the public `get_level_values()`,  with the assumption of the int argument, so the `copy` argument makes that happen by doing the shallow copy there.

When I first looked at this, there was no `_get_level_values()`, but that got introduced within the past 2 weeks, so I then had to make everything compatible.

2017-02-23 19:26 UTC, jreback commented on pandas/indexes/multi.py
> +        copy  : bool whether copy of results should be done
still its not clear why you would actually be making this change, it just adds too much complexity.

show an example of why you think you need it (or simply take it out)

2017-02-23 19:43 UTC, Dr-Irv commented on pandas/indexes/multi.py
> +        copy  : bool whether copy of results should be done
@jreback I'll try an alternate implementation and let you review that.

2017-02-24 14:08 UTC, Dr-Irv commented
@jreback the last commit I did should have addressed the changes you requested, and we're all green, so let me know if there is more to do

2017-02-24 20:18 UTC, closed without merging

2017-02-24 20:19 UTC, jreback commented
thanks @Dr-Irv

2017-02-24 23:08 UTC, jorisvandenbossche commented
@Dr-Irv Thanks!