msgpack supports CategoricalIndex
pandas-dev/pandas pull request #15493
Opened 2017-02-23 21:33 UTC by abast

- [x] closes #15487
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

This allows `read_msgpack`  to read DataFrames with a categorical index. I'd assume that my testcase needs some improvement. Where can I find some information where and how to add the "whatsnew entry"?

2017-02-23 21:37 UTC, jreback requested changes
you edit ``pandas/doc/source/whatsnew/v0.20.0.txt`` for this Bug Fix

2017-02-23 21:37 UTC, jreback commented on pandas/tests/msgpack/test_unpack.py
> +    def test_unpack_categorical_index(self):
the tests are all in ``pandas/tests/io/test_packers.py`` (this section is for the c-code that implements msgpack itself).

2017-02-23 21:37 UTC, jreback commented on pandas/tests/msgpack/test_unpack.py
> +    def test_unpack_categorical_index(self):
just follow examples there for style

2017-02-23 22:53 UTC, abast commented on pandas/tests/msgpack/test_unpack.py
> +    def test_unpack_categorical_index(self):
Thanks, I tried to change the it accordingly. Do you get a notification if I push new commits? Or should I comment?

2017-02-23 22:56 UTC, jreback approved these changes
small comments ping when all green

2017-02-23 22:56 UTC, jreback commented on pandas/tests/io/test_packers.py
> +        df2 = df.astype({0: 'category'}).set_index(0)
make a new test function
add the issue number as a comment

2017-02-23 22:56 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- Bug in ``DataFrame.read_msgpack`` which did not allow to load DataFrames with a CategoricalIndex (:issue:`15487`)
pd.read_msgpack

2017-02-24 20:41 UTC, jreback commented
thanks!

2017-02-24 20:41 UTC, closed without merging