DEPR: rename to _consolidate and create deprecation warning
pandas-dev/pandas pull request #15501
Opened 2017-02-25 04:51 UTC by GuessWhoSamFoo

- [x] closes #15483 
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew entry

Test output:
```
running: pytest --skip-slow --skip-network pandas
============================= test session starts ==============================
platform linux2 -- Python 2.7.13, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /home/sfoo/pandas, inifile: setup.cfg
collected 11882 items / 4 skipped

 10147 passed, 1662 skipped, 77 xfailed, 2084 pytest-warnings in 407.18 seconds  
```

2017-02-25 10:51 UTC, jorisvandenbossche commented
@GuessWhoSamFoo We would like to have it the other way around. Have the deprecation warning in `consolidate` and not in `_consolidate` (so this last one can be used internally without warning). So you can leave the existing `consolidate` intact like it is now, apart from renaming it to `_consolidate`, and then add a new `consolidate` that has the deprecation warning and just calls `_consolidate` (not adding a new `_consolidate` like you did now). 
Further, you will also have to replace internal usage in the pandas codebase of `consolidate` to `_consolidate` to avoid raising the deprecation warning (that is the reason for the test failures).

2017-02-26 14:32 UTC, GuessWhoSamFoo commented
```running: pytest --skip-slow --skip-network pandas
==================================== test session starts =====================================
platform linux2 -- Python 2.7.13, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /home/sfoo/pandas, inifile: setup.cfg
collected 11882 items / 4 skipped 

======= 10147 passed, 1662 skipped, 77 xfailed, 2084 pytest-warnings in 419.22 seconds =======
```
The original consolidate has been left intact except for a line taken out of the docstring. Then I've changed instances of `consolidate` to `_consolidate` (even in tests) but still have the same number of failed tests/warnings. Am I missing something here?

2017-02-26 14:55 UTC, jorisvandenbossche commented on pandas/io/pytables.py
> +            data = data._consolidate()
Here, `data` is not a DataFrame, but a BlockManager, so this should be left as `consolidate`

2017-02-27 00:00 UTC, jreback requested changes

2017-02-27 00:00 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- ``DataFrame.consolidate()`` has been deprecated. (:issue:`15483`)
say ``Series/DataFrame/Panel.consolidate()`` it affects everything

say has been deprecated as a public method as

2017-02-27 00:00 UTC, jreback commented on pandas/core/generic.py
> +        DEPRECATED:
this is not deprecated though.

can you add a doc-string

2017-02-27 00:00 UTC, jreback commented on pandas/core/generic.py
> +        # 15483
here is where the DEPRECATED goes (in the doc-string)

2017-02-27 00:00 UTC, jreback commented on pandas/tests/frame/test_block_internals.py
>      def test_consolidate(self):
can you add a single test (test_consolidate_deprecation), which uses ``assert_produces_warning(FutureWarning)``

2017-02-27 00:00 UTC, jreback commented on pandas/core/generic.py
> +                      "future release.", DeprecationWarning)
use FutureWarning

2017-02-27 23:37 UTC, GuessWhoSamFoo commented
Squashed the last two commits with the changes from the feedback. Thank you for the guidance!

2017-02-28 10:43 UTC, merged

2017-02-28 10:43 UTC, jorisvandenbossche commented
@GuessWhoSamFoo Thank you!