Added FrozenList subtraction
pandas-dev/pandas pull request #15506
Opened 2017-02-25 20:52 UTC by bthayer2365

- [x] closes #15475
 - [x] tests added / passed
 - [ ] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

2017-02-25 21:02 UTC, jreback requested changes

2017-02-25 21:02 UTC, jreback commented on pandas/indexes/frozen.py
> +        return self.__class__(temp)
add isub as well (and a test)

2017-02-25 21:02 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- Added subtraction from FrozenLists (:issue:`15475`)
this is called difference 

i think might be nice to add an example to th docs as well

2017-02-25 22:57 UTC, jreback commented on doc/source/groupby.rst
> +but the specified columns
add a versionadded tag here

2017-02-25 22:57 UTC, jreback commented on pandas/tests/indexes/test_frozen.py
>      def test_inplace(self):
can you rename this to make consistent

2017-02-26 00:51 UTC, jorisvandenbossche commented
I want to raise some concern regarding adding this feature (without wanting to dismiss your effort @bthayer2365 !). I think we should think about this some more. 

Adding this would introduce a discrepancy between index level names and column names, while we actually try to lessen the gap (eg by being able to specify an index level name in places where you can specify a column name). This is actually a feature we *removed* from column names, in favor of the `difference` method. 
So that is maybe also an alternative? Putting this in a method instead of overloading subtraction? (although I certainly agree what we try to obtain here is useful, and as a method it is more verbose)

2017-02-26 02:29 UTC, jreback commented
no conceptual problem with making these real setops, e.g. ``.union``, ``.difference`` as @jorisvandenbossche suggests. Publicly these are *only* used for names of levels anyhow.

2017-02-26 02:49 UTC, bthayer2365 commented
Would you like me to change `__add__` to `union` as well?

2017-02-26 02:52 UTC, jreback commented
yes; u will have to deprecate the add though

2017-02-26 02:54 UTC, bthayer2365 commented
To do that, do I just decorate it with `@deprecated`, or is there more?

2017-02-26 03:01 UTC, jreback commented
that should work (and add in whatsnew as well)
iadd too

2017-02-27 15:53 UTC, jreback commented on doc/source/groupby.rst
> +   df.set_index(['A', 'B'])
this won't work as it returns a new object, instead something like

```
df2 = df.set_index(['A', 'B'])
grouped = df2.groupby(level=....)
```

2017-02-27 15:54 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- Added difference from FrozenLists (:issue:`15475`)
``.difference()`` method for ``FrozenList``

2017-02-27 15:54 UTC, jreback commented on pandas/indexes/frozen.py
>          if isinstance(other, tuple):
```
return self.union(other)
```

2017-02-27 15:54 UTC, jreback commented on pandas/indexes/frozen.py
> +        if isinstance(other, tuple):
can you add a doc-string

2017-02-27 15:54 UTC, jreback commented on pandas/indexes/frozen.py
> +        other = set(other)
same here

2017-02-27 15:56 UTC, jreback commented on pandas/indexes/frozen.py
> +        return self.__class__(super(FrozenList, self).__add__(other))
I *think* ``__iadd__`` is also defined? if so, deprecate that as well.

2017-03-01 01:55 UTC, bthayer2365 commented
I tried resolving the conflicts and merging manually, but the check failed, so I reverted back to before I resolved the conflict. Am I supposed to resolve the merge conflicts and merge master?

2017-03-01 01:59 UTC, cpcloud commented
@bthayer2365 Yep, you need to resolve conflicts on your local branch. You should do:

```
git pull upstream master --rebase --tags
```
And resolve the conflicts one by one, doing `git rebase --continue` once each one has been resolved. Then push to your fork.

2017-03-01 01:59 UTC, jreback commented
yes the idea is to rebase on master. But don't worry about that as much as passing tests (of course I think travis / amazon is having issues atm).

2017-03-01 02:13 UTC, bthayer2365 commented
Okay, should we just wait a bit to see if the tests work when everything
starts working again? Everything worked on the command line

On Feb 28, 2017 7:59 PM, "Jeff Reback" <notifications@github.com> wrote:

> yes the idea is to rebase on master. But don't worry about that as much as
> passing tests (of course I think travis / amazon is having issues atm).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/15506#issuecomment-283221620>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AF0RY4QdddVNhcFqKprMdBJcVTc45us2ks5rhNEegaJpZM4MMIo2>
> .
>

2017-03-01 02:26 UTC, bthayer2365 commented
I'll leave it like this and see if it passes

2017-03-01 19:24 UTC, jreback commented
you'll want to rebase on master as travis was having some issues

2017-03-01 19:56 UTC, jreback requested changes

2017-03-01 19:56 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- ``FrozenList.__add__`` has been depricated in favor of ``FrozenList.union`` (:issue: `15475`)
deprecated. Add for ``__iadd__`` here as well

2017-03-01 19:56 UTC, jreback commented on pandas/indexes/frozen.py
> +        return self.union(other)
this is technically wrong; its an in-place modify, and doesn't return anything. Can you add a test for validate this?

*maybe*

```
def __iadd__(self, other):
    warnings(.....)
     if isinstance(other, tuple):
            other = list(other)
    super(FrozenList, self).__iadd__(other)
```

might work

2017-03-02 05:45 UTC, bthayer2365 commented
Anything else? All tests passed 👍

2017-03-02 13:25 UTC, closed without merging

2017-03-02 13:25 UTC, jreback commented
thanks @bthayer2365

2017-03-02 20:36 UTC, cpcloud commented
@bthayer2365 Great job! Thanks for your contribution.

2017-03-03 01:57 UTC, bthayer2365 commented
Glad I could help!