Fix nansum overflow on Windows with bottleneck
pandas-dev/pandas pull request #15507
Opened 2017-02-25 21:28 UTC by JaviSorribes

- [x] closes #15453 
 - [x] tests added / passed
 - [ ] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

2017-02-26 19:26 UTC, jreback requested changes
The biggest issue here is this semantically changes things. IOW, now since we are *always* using pandas nansum (rather than bottleneck nansum if installed), we will *always* yield ``Series([np.nan]).sum()`` -> ``np.nan`` (rather than 0 if bottleneck is installed). So I think we actually have to change this for *all* platforms or then this becomes even more confusing.

2017-02-26 19:26 UTC, jreback commented on pandas/core/nanops.py
> +            elif os.name == 'nt':  # bottleneck has overflow issue in Windows
use ``pandas.compat.is_platform_windows()``

2017-02-26 19:26 UTC, jreback commented on pandas/tests/test_nanops.py
> +        s = Series([2**31])
needs testing both with and w/o bottleneck (to yield the same results), see other tests for how to do this.

2017-02-26 19:27 UTC, jreback commented
@jorisvandenbossche @shoyer 

w.r.t. #9422 I think we need to simply change this (in effect what this PR does), but for all platforms (and not just windows).

2017-02-27 20:57 UTC, cpcloud commented
@JaviSorribes Looking at @jreback's comments, it looks like we should just disable `nansum` bottleneck calls altogether.

2017-02-28 07:50 UTC, JaviSorribes commented
So I understand @jreback and @cpcloud that we should not use bottleneck at all for nansum? Checkout the image attached for what I think this would look like.

Also, what about all the other nan operations? Should we consider possible overflow in any of them?

![image](https://cloud.githubusercontent.com/assets/15252789/23396198/3420769c-fd58-11e6-85bd-4c9001dd032d.png)

2017-03-01 21:09 UTC, jreback commented
xref #15542

2017-03-01 22:10 UTC, jorisvandenbossche commented
We indeed just need to take a decision on #9422, as we have left this lingering too long. 
But, I am not necessarily convinced that we should change everything to the native pandas way (returning NaN), instead of changing pandas to return 0 to align with numpy/bottleneck (and also R, matlab, ..). 
I don't think there was really agreement on this in #9422 (several have argued for both positions), but I also don't know how to best proceed on taking a decision.

2017-05-07 13:59 UTC, jreback commented
The fixes are related to fixing #9422 are a bit bigger in scope than this. That said If you want to rebase / add some additional tests could take this as a precurser.

2017-08-20 18:12 UTC, jreback commented
closing this. as #9422 needs resolution.

2017-08-20 18:12 UTC, closed without merging