!B [pandas-dev/pandas#15549] resample with tz-aware: Values falls after last bin
pandas-dev/pandas pull request #15555
Opened 2017-03-02 21:01 UTC by ahcub

- [ ] closes #xxxx
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

2017-03-02 21:02 UTC, ahcub commented
jreback, would you like me to add tests for this change ?

2017-03-02 21:08 UTC, jreback commented
tests!

2017-03-03 10:06 UTC, ahcub commented
committed a test and wrote a whatsnew note.
please let me know if the format of whatsnew is correct, I'm not sure if there is any standard form I should follow.

2017-03-03 18:23 UTC, ahcub commented
I understand why the checks failed, I will commit a fix

2017-03-04 09:36 UTC, ahcub commented
@jreback is it ok to change current tests in order to make my change pass them ?

2017-03-04 12:13 UTC, jreback commented
you need to prove that a current test is wrong in order to change it

2017-03-04 21:28 UTC, jreback requested changes
I am not so sure I buy the rationale for the change here. The binning MUST be in the local tz, and NOT UTC, otherwise that is VERY confusing (IOW you would have really odd breakpoints which have nothing to do with the data, but the timezone). T

2017-03-04 21:28 UTC, jreback commented on pandas/tests/tseries/test_resample.py
> +        df.resample('12h', closed='right', label='right').last().ffill()
```
result = df.resample(.......)
expected = ....
tm.assert_frame_equal(result, expected)
```

add a comment with the issue number as a comment (and not in the test name)

2017-03-04 21:28 UTC, jreback commented on pandas/tests/tseries/test_resample.py
> +        index = pd.DatetimeIndex([1450137600000000000, 1474059600000000000], tz='UTC').tz_convert('America/Chicago')
this line is going to be too long for linting.

2017-03-04 21:33 UTC, jreback commented
I think you need to compute the range edges *with* the tz intact. I think it is mishandling when it has an ambiguous datetime.

Then constructing the tz should be ok.

2017-03-06 01:11 UTC, ahcub commented on pandas/tests/tseries/test_resample.py
> +        index = pd.DatetimeIndex([1450137600000000000, 1474059600000000000], tz='UTC').tz_convert('America/Chicago')
understood, I will change it

2017-03-06 01:11 UTC, ahcub commented
got it, let me try to use your approach

2017-03-06 01:13 UTC, ahcub commented on pandas/tests/tseries/test_resample.py
> +        df.resample('12h', closed='right', label='right').last().ffill()
agree, I will fix it. I just used the same notation as in the test above. thought it's a common thing

2017-03-06 14:39 UTC, jreback commented
@ahcub yeah this seemingly trivial change is actually hard. there have been lots of fixes (for various reasons) thru the years. good news is the test suite is quite comprehensive here :>

2017-03-28 18:03 UTC, jreback commented
can you rebase / update

2017-03-28 18:26 UTC, ahcub commented
I will close it for now and restore it when I get back to it

2017-03-28 18:26 UTC, closed without merging

2017-03-28 18:58 UTC, jreback commented
@ahcub ok sure. though pls come back when you can! thanks!