Subclassed reshape
pandas-dev/pandas pull request #15564
Opened 2017-03-04 01:21 UTC by delgadom

- [x] closes #15563
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

Reshape operations in pandas/core/reshape.py modified to use `obj._constructor`, `obj._constructor_sliced`, and `obj._constructor_expanddim` for Series and DataFrame. This preserves a subclass family on `stack`, `unstack`, and `pivot` operations.

2017-03-04 14:42 UTC, jreback commented
can you also have a look over: http://pandas-docs.github.io/pandas-docs-travis/internals.html#subclassing-pandas-data-structures

and see if anything needs amendment

2017-03-04 14:42 UTC, jreback commented on doc/source/whatsnew/v0.9.1.txt
> +  - `stack`, `unstack`, and `pivot` operations now preserve subclass family
move to 0.20.0

2017-03-04 14:45 UTC, jreback requested changes

2017-03-04 14:45 UTC, jreback commented on pandas/core/reshape.py
> +        else:
hmm I think this should be done *inside* the ``.stack`` and ``_unstack_frame`` functions no?

2017-03-04 14:45 UTC, jreback commented on pandas/core/reshape.py
> +
same here, this now has logic in 2 places, the creation itself of the unstacked result, then the return class. should be a part of ``get_result`` (it certainly could be another method that is *called* by ``get_result``) though

2017-03-04 14:45 UTC, jreback commented on pandas/core/reshape.py
> +    return frame._constructor_sliced(new_values, index=new_index)
so this is good

2017-03-04 14:45 UTC, jreback commented on pandas/tests/frame/test_subclass.py
> +        df = tm.SubclassedDataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]],
can you add the issue number as a comment

2017-03-04 14:46 UTC, jreback commented
thanks @delgadom 

reshape could certainly use some tlc!

2017-03-08 03:47 UTC, delgadom commented
Thanks @jreback - I'm working on your suggestions.

Keeping this clean is a bit tough, especially because unstacking is sometimes handled by `_unstack_multiple` and sometimes by `_Unstacker`. I'd modify `_unstack_multiple` and `_Unstacker`, except `_Unstacker` accepts a numpy array and returns a `DataArray`, so there's no way to access the `_constructor*` properties from within this class.

To me this class seems really nasty and should be handled by functions rather than a class (would you ever use `_Unstacker` except to get an unstacked object?) but originally was tentative in making changes. Do you think this should be re-written? At the very least it seems as though `_Unstacker` should be able to handle `DataFrame` arguments.

Happy to take a stab if you agree.

2017-03-08 13:45 UTC, jreback commented
@delgadom the reshaping code is certainly in need of refactoring to make things easier :>

certainly take a stab at it. Yes the ``_Unstacker`` class is merely a helper class, so you can change things if you need (not public).

You *might* want to do a refactor *before* this PR to make it easier to test / debug. Though if its relatively simple go ahead here.

2017-03-08 23:05 UTC, delgadom commented
Yeah I think I'll refactor and then create a new PR. Thanks for the help!

2017-03-08 23:05 UTC, closed without merging

2017-03-08 23:08 UTC, jreback commented
ok!