Added exception for invalid dtypes per issue #15520
pandas-dev/pandas pull request #15574
Opened 2017-03-05 04:15 UTC by trevorpburke

- [ ] closes #xxxx
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

2017-03-05 04:28 UTC, jreback commented
tests!

2017-03-05 04:29 UTC, jreback requested changes

2017-03-05 04:29 UTC, jreback commented on pandas/core/series.py
> +                else:
you would change this in the _validate_dtype method

2017-03-05 04:37 UTC, trevorpburke commented on pandas/core/series.py
> +                else:
oh! pandas/pandas/indexes/range.py, right?

2017-03-05 04:43 UTC, jreback commented on pandas/core/series.py
> +                else:
this is in generic.py

2017-03-05 14:45 UTC, jreback commented
tests!

2017-03-10 12:08 UTC, jreback commented
if you'd like to add some tests, ping and can reopen

2017-03-10 12:08 UTC, closed without merging