ENH: Allow parameters method and min_periods in DataFrame.corrwith()
pandas-dev/pandas pull request #15573
Opened 2017-03-04 23:18 UTC by anthonyho

Added new keyword parameters for DataFrame.corrwith(), which allows methods other than Pearson to be used. See #9490.

 - [x] closes #9490
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew entry

2017-03-04 23:28 UTC, jreback requested changes

2017-03-04 23:28 UTC, jreback commented on doc/source/computation.rst
> +   df2.corrwith(df1, axis=1, method='kendall')
add versionsddes tag (and small comment here)

2017-03-04 23:28 UTC, jreback commented on pandas/core/frame.py
> +                                             right[col].values,
this is going to be very slow

we need to rework nancorr to do this instead

2017-03-05 01:08 UTC, anthonyho commented on pandas/core/frame.py
> +                                             right[col].values,
I think the new implementation (which calls nancorr which calls numpy/scipy correlation functions) is actually significantly faster than the current implementation (manually computing Pearson correlation using `DataFrame.mean()`, `DataFrame.sum()`, and `DataFrame.std()`)

For example:

Current implementation:
```python
>>> import pandas as pd; import timeit
>>> pd.__version__
u'0.19.2'
>>> iris = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
>>> timeit.timeit(lambda: iris.corrwith(iris), number=10000)
50.891642808914185
>>> timeit.timeit(lambda: iris.T.corrwith(iris.T), number=10000)
42.0677649974823
```

New implementation:
```python
>>> import pandas as pd; import timeit
>>> pd.__version__
'0.19.0+539.g0b77680.dirty'
>>> iris = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
>>> timeit.timeit(lambda: iris.corrwith(iris, method='pearson'), number=10000)
28.622286081314087
>>> timeit.timeit(lambda: iris.T.corrwith(iris.T, method='pearson'), number=10000)
21.898916959762573
```

I'm pretty new to this, so please let me know if I'm missing anything here.

2017-03-05 04:26 UTC, jreback commented on pandas/core/frame.py
> +                                             right[col].values,
look thru the benchmarks and pls add some asv as appropriate

include wide and talk data

on wide data this will be slower

2017-04-03 15:15 UTC, jreback commented
can you update

2017-06-10 19:05 UTC, jreback commented
can you rebase and update?

2017-08-17 10:29 UTC, jreback commented
closing as stale

2017-08-17 10:29 UTC, closed without merging