Raising for invalid dtype issue #15520
pandas-dev/pandas pull request #15576
Opened 2017-03-05 14:06 UTC by petioptrv

2017-03-05 14:45 UTC, jreback requested changes
first thing to always do are tests

2017-03-05 14:45 UTC, jreback commented on pandas/core/generic.py
> +            # check if coerced dtype is of type object
use ``pandas.types.common.pandas_dtype``

2017-03-05 15:10 UTC, petioptrv commented
Are you saying I should raise within the pandas_dtype method?

2017-03-05 15:22 UTC, jreback commented
yes ``pandas_dtype`` will raise if an invalid string is passed, but not an invalid object

```
In [1]: pandas.types.common.pandas_dtype(pd.Timestamp)
Out[1]: dtype('O')

In [2]: pandas.types.common.pandas_dtype('foo')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-07647ef910a7> in <module>()
----> 1 pandas.types.common.pandas_dtype('foo')

/Users/jreback/pandas/pandas/types/common.py in pandas_dtype(dtype)
    491         return dtype
    492 
--> 493     return np.dtype(dtype)

TypeError: data type "foo" not understood

```

2017-03-10 12:08 UTC, jreback commented
if you want to add some tests ping and will reopen

2017-03-10 12:08 UTC, closed without merging