BUG: Group-by numeric type-coericion with datetime
pandas-dev/pandas pull request #15680
Opened 2017-03-14 10:57 UTC by gwpdt

GH Bug #14423

During a group-by/apply on a DataFrame, in the presence of one or more
DateTime-like columns, Pandas would incorrectly coerce the type of all
other columns to numeric.  E.g. a String column would be coerced to
numeric, producing NaNs.

Fix the issue, and add a test.

 - [ ] closes #xxxx
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

2017-03-14 12:09 UTC, jreback requested changes
lgtm couple of comments
pls add a whatsnew note in bug fixes
ping when green or need review

2017-03-14 12:09 UTC, jreback commented on pandas/core/groupby.py
> +                        lambda x: pd.to_numeric(x, errors='ignore'))
don't import pd
import to_numeric from pandas.util.misc (inside the function)

2017-03-14 12:09 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +        # GH 14423
there are a couple of issues marked duplicate can u add there tests here as well (inside this test is ok)

2017-03-14 12:09 UTC, jreback commented on pandas/core/groupby.py
> +                        lambda x: pd.to_numeric(x, errors='ignore'))
or u can import pd inside the function is ok too

2017-03-14 12:20 UTC, jreback commented
pls add tests from these two

xref #14873 (boolean casts)
xref #14849 (datetime)

if this change doesn't fix these, pls lmk.

2017-03-14 18:03 UTC, gwpdt commented
I tried adding the test for #14873 - my fix does not resolve this issue.  It's similar, but unrelated.   It seems to be this line in _python_agg_general:

`output[name] = self._try_cast(result, obj, numeric_only=True)`

that seems to favour converting the result of the apply back to the same type as the original series.

2017-03-14 18:16 UTC, jreback commented
@gwpdt ok, we can treat that issue independently.

2017-03-14 18:23 UTC, gwpdt commented
I also tried adding the test for #14849 - my fix does not resolve this issue either.

The issue with that test is that it is testing for preservation of dtype="object" for a column whose values are all numeric (and therefore the "soft coercion" to numeric type succeeds).

In this instance (in the absence of any non-numeric values in the series), even with my fix, it will still convert the dtype of the column from "object" to numeric.

I tried removing the conversion altogether.  That fixes #14849, but breaks another test (test_time_field_bug / #11324), so I will not commit that change.

I still think it is worth contributing my fix, since it improves upon the current situation.  A series with string values will not be converted to NaNs when doing groupby/apply on a DF with one or more datetime columns.

I will address other review feedback (re: "pd" import) and update the PR.

2017-03-14 20:47 UTC, jreback commented
AFAICT this *only* resolved #15421 (w/o breaking anything else). so thats good.

2017-03-14 20:48 UTC, jreback commented
#14423 I think *should* be fixable as well. want to give that a shot? (the example is not very good though).

2017-03-14 20:49 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +        # GH 14423
add a 1-liner explaining this (maybe also make the test name a bit more descriptive)

2017-03-16 11:24 UTC, gwpdt commented
Agreed - #15670 #15421 and #14423 are all fixed.

2017-03-16 11:55 UTC, jreback approved these changes

2017-03-16 11:56 UTC, jreback commented
lgtm. merging shortly.

2017-03-16 12:08 UTC, jreback commented
thanks!

2017-03-16 12:08 UTC, closed without merging