BUG: Check that values for "nrows" and "chunksize" are valid
pandas-dev/pandas pull request #15774
Opened 2017-03-21 22:29 UTC by toobaz

- [x] closes #15767
 - [x] tests added / passed
 - [x] passes ``git diff master --name-only -- '*.py' | flake8 --diff``
 - [x] whatsnew entry

2017-03-21 22:38 UTC, jreback requested changes
some minor comments

2017-03-21 22:38 UTC, jreback commented on pandas/io/parsers.py
> +    msg = "'%s' must be an integer >=%s" % (name, min_val)
can you use "{}".format(...) string formatting, ideally with named parameters

2017-03-21 22:38 UTC, jreback commented on pandas/io/parsers.py
>      """
can you add a Parameters section to the doc-string.

2017-03-21 22:38 UTC, jreback commented on pandas/tests/io/parser/common.py
> +        # with invalid chunksize value:
is there a test for nrows that is negative? and same for chunsize?

2017-03-21 22:40 UTC, jorisvandenbossche commented
Looks good!

Currently, `chunksize=0` also 'works' (it was only negatives and floats between 0 and 1 that caused the infinite loop, chunksize=0 is somehow checked for), but just directly returning the full dataframe. I suppose because the 0 was just interpreted as 'False'. 
I don't think we need to keep supporting this, however, as this is rather strange?

2017-03-21 22:44 UTC, toobaz commented on pandas/tests/io/parser/common.py
> +        # with invalid chunksize value:
Well, there is a test for ``nrows=-1`` and one for ``chunksize=0``... which is already "too negative". So yes, there are tests for the positivity check.

2017-03-21 23:14 UTC, jreback approved these changes

2017-03-21 23:15 UTC, jreback commented
lgtm. I agree with @jorisvandenbossche point, that ``chunksize==0`` is an error as well.

2017-03-22 08:03 UTC, merged

2017-03-22 08:03 UTC, jorisvandenbossche commented
@toobaz Thanks!

2017-03-22 08:33 UTC, toobaz commented
You're welcome!