Rolling window endpoints inclusion
pandas-dev/pandas pull request #15795
Opened 2017-03-23 22:29 UTC by carlosdanielcsantos

- [x] closes #13965 
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

2017-03-23 22:32 UTC, carlosdanielcsantos commented on pandas/core/window.pyx
> +                   object index, str closed, bint is_max):
Not sure about the behavior of str here...

2017-03-23 22:37 UTC, carlosdanielcsantos commented on pandas/core/window.pyx
> +                   object index, str closed, bint is_max):
Not sure about the behavior of str here (cdef)

2017-03-23 22:44 UTC, carlosdanielcsantos commented
Here is a quick example of what this feature looks like

```
df = pd.DataFrame({'x': [1]*5},
....:                 index = [pd.Timestamp('20130101 09:00:01'),
....:                          pd.Timestamp('20130101 09:00:02'),
....:                          pd.Timestamp('20130101 09:00:03'),
....:                          pd.Timestamp('20130101 09:00:04'),
....:                          pd.Timestamp('20130101 09:00:06')])

df["right"] = df.rolling('2s', closed='right').x.sum()   # current behavior
df["both"] = df.rolling('2s', closed='both').x.sum()
df["left"] = df.rolling('2s', closed='left').x.sum()
df["open"] = df.rolling('2s', closed='none').x.sum()

print(df)
                     x  right  both  left  open
2013-01-01 09:00:01  1    1.0   1.0   NaN   NaN
2013-01-01 09:00:02  1    2.0   2.0   1.0   1.0
2013-01-01 09:00:03  1    2.0   3.0   2.0   1.0
2013-01-01 09:00:04  1    2.0   3.0   2.0   1.0
2013-01-01 09:00:06  1    1.0   2.0   1.0   NaN
```

2017-03-23 22:45 UTC, jreback requested changes
mostly minor points
- add a whatsnew entry (Other Enhancements) in whatsnew (0.20.0), with a link to the computation.rst docs (where you have a new section showing the use of closed; you can use your test examples, e.g. showing all 4 cases).

2017-03-23 22:45 UTC, jreback commented on pandas/core/window.py
> +        if self.closed not in ['right', 'both', 'left', 'neither']:
testing this?

2017-03-23 22:45 UTC, jreback commented on pandas/core/window.pyx
> +                 bint l_closed=False, bint r_closed=True):
if you have a chance, can you add a mini-doc strings to things.

2017-03-23 22:45 UTC, jreback commented on pandas/core/window.pyx
>          code path with all of the indexers.
can you augment the doc-string here (with closed)

2017-03-23 22:45 UTC, jreback commented on pandas/core/window.pyx
> +    if closed not in ['right', 'left', 'both', 'neither']:
you can just do an assert here (this is an internal routine that has certain guarantees)

2017-03-23 22:45 UTC, jreback commented on pandas/core/window.pyx
> +               object index, closed='right'):
just make this required

``object closed``

2017-03-23 22:45 UTC, jreback commented on pandas/core/window.pyx
> +              object index, str closed):
``object closed``

2017-03-23 22:45 UTC, jreback commented on pandas/core/window.pyx
> +             object index, str closed):
same for the rest of these: str-> object

2017-03-23 22:45 UTC, jreback commented on pandas/core/window.pyx
> +                   object index, str closed, bint is_max):
same

2017-03-23 22:45 UTC, jreback commented on pandas/tests/test_window.py
> +        df = DataFrame({'A': [1]*5},
add this issue number as a comment

2017-03-23 22:45 UTC, jreback commented on pandas/tests/test_window.py
> +                                 pd.Timestamp('20130101 09:00:03'),
test passing invalid closed

2017-03-23 22:45 UTC, jreback commented on pandas/tests/test_window.py
> +
@chrisaycock how do these tests look? what corners do we need to test here

2017-03-23 22:46 UTC, jreback commented
@carlosdanielcsantos https://github.com/pandas-dev/pandas/pull/15795#issuecomment-288883027 are basically the docs (with a bit of prose) and nice formatting. Laying out the possibilities (in a sub-section of computation.rst). Note you also might want to have a 'real-world' uses case sentence for some of these.

2017-03-23 22:54 UTC, jreback commented
you can see pep errors: http://pandas-docs.github.io/pandas-docs-travis/contributing.html#python-pep8

use ``git diff master | flake8 --diff``

2017-03-24 01:34 UTC, chrisaycock commented on pandas/tests/test_window.py
> +
What happens if the DataFrame is empty?

2017-03-27 14:05 UTC, carlosdanielcsantos commented on pandas/tests/test_window.py
> +
If the DataFrame is empty, the behavior is exactly the same as in the current implementation. For time-based windows, it throws "ValueError: window must be an integer".  Note that this feature only affects the window indexer's start and end vectors. In fixed windows, empty DataFrames always return empty (the result is constructed as np.empty(N) where N is the length of the input)

2017-03-27 14:12 UTC, jreback commented on pandas/tests/test_window.py
> +
separately I think [4] should just return an empty frame for consistency.

```
In [4]: DataFrame().rolling('1s').sum()
ValueError: window must be an integer

In [5]: DataFrame().rolling(1).sum()
Out[5]: 
Empty DataFrame
Columns: []
Index: []
```

@chrisaycock ?

2017-03-27 15:02 UTC, carlosdanielcsantos commented
@jreback How should I add this to computations.rst? A new section inside Window Functions or just add the examples inside the existing Window Functions -> Rolling Windows?

2017-03-27 15:03 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- ``DataFrame.rolling()`` now accepts the parameter ``closed='right'|'left'|'both'|'neither'`` to choose the rolling window endpoint closedness. (:issue:`13965`)
is that a word?

2017-03-27 15:04 UTC, jreback commented on pandas/core/window.py
> +    closed : 'right', 'left', 'both', 'neither'
add the default setting (right)

2017-03-27 15:04 UTC, jreback commented on pandas/core/window.py
> +    closed : 'right', 'left', 'both', 'neither'
I would do this with a bulleted list

2017-03-27 15:05 UTC, jreback commented on pandas/core/window.pyx
> +        left endpoint closedness
I would write these out ``l_closed`` -> ``left_closed`` easier to read

2017-03-27 15:05 UTC, jreback commented on pandas/core/window.pyx
> +        left endpoint closedness
can add a bit of explication here (1 line), just for future readers

2017-03-27 15:06 UTC, jreback commented on pandas/core/window.pyx
> +
put the comments above the code

```
if r_closed:
    # .....
    end[0] = 1
else:
    # ....
    end[0]  0
```

2017-03-27 15:06 UTC, jreback commented on pandas/core/window.pyx
> +                if l_closed:  # left endpoint is closed
same

2017-03-27 15:07 UTC, jreback commented on pandas/core/window.pyx
> +                if l_closed:  # left endpoint is closed
of can do (I use this if only an if statement)
```
# left endpoint ....
if left_closed:
    ....
```

2017-03-27 15:07 UTC, jreback commented on pandas/core/window.pyx
> +                # right endpoint is open
yep excatly like this one

2017-03-27 15:07 UTC, jreback commented on pandas/core/window.pyx
> +    closed: 'right', 'left', 'both', 'neither'
```
closed: string, default 'right'
        {'right',......}
```

2017-03-27 15:08 UTC, jreback commented
@carlosdanielcsantos lgtm. some more doc-string nitpicks.

2017-03-27 15:08 UTC, jreback approved these changes

2017-03-27 15:08 UTC, jreback commented
ping when all green.

2017-03-27 15:17 UTC, carlosdanielcsantos commented
@jreback I was going to start writing tests for the FixedWindowIndexer but there are no explicit rolling computing test going on in TestRolling (they are done in TestMoments, I think). Where should I add these new tests?

2017-03-27 15:19 UTC, carlosdanielcsantos commented on doc/source/whatsnew/v0.20.0.txt
> +- ``DataFrame.rolling()`` now accepts the parameter ``closed='right'|'left'|'both'|'neither'`` to choose the rolling window endpoint closedness. (:issue:`13965`)
There is some discussion going on about that online, but its a useful word to reference the property of being closed. But I am open to suggestions, no pun intended :)

2017-03-27 15:22 UTC, jreback commented
> @jreback How should I add this to computations.rst? A new section inside Window Functions or just add the examples inside the existing Window Functions -> Rolling Windows?

exactly, a new sub-section that pretty much shows the example with all 4 closed. maybe right before Centering Windows?

2017-03-27 15:24 UTC, jreback commented
> @jreback I was going to start writing tests for the FixedWindowIndexer but there are no explicit rolling computing test going on in TestRolling (they are done in TestMoments, I think). Where should I add these new tests?

We don't have explicit tests for the cython routines, these are covered by the integration tests (top-level routines). Though certainly could add them if you want / can. 

You could add a new class in test_windows that explicity exercises these.

2017-03-27 15:27 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- ``DataFrame.rolling()`` now accepts the parameter ``closed='right'|'left'|'both'|'neither'`` to choose the rolling window endpoint closedness. (:issue:`13965`)
hahah yep that is fine

2017-03-27 15:28 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- ``DataFrame.rolling()`` now accepts the parameter ``closed='right'|'left'|'both'|'neither'`` to choose the rolling window endpoint closedness. (:issue:`13965`)
maybe ``closed-ness``? (though I don't think *that* is actually a word)

2017-03-27 17:32 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- ``DataFrame.rolling()`` now accepts the parameter ``closed='right'|'left'|'both'|'neither'`` to choose the rolling window endpoint closedness. (:issue:`13965`)
also add a ``:ref:`` to the new sub-section that you are creating in computation.rst

2017-03-28 12:47 UTC, carlosdanielcsantos commented
@jreback @chrisaycock 
Thinking deeper about the fixed window case, it seems that, intuitively, the default behavior right now better resembles the closed='both' case. Notice that when you use rolling(3).apply(f), the result for index i will be the result of f applied to `[i-2, i-1, i]`, not `]i-2, i-1, i]` (ISO 31-11 math set notation). One could argue that this is equivalent to having closed='right' with f applied to `]i-3, i-2, i-1, i]`. Indeed, but this probably adulterates the meaning of the window size.

2017-03-28 12:52 UTC, jreback commented
> @jreback @chrisaycock
Thinking deeper about the fixed window case, it seems that, intuitively, the default behavior right now better resembles the closed='both' case. Notice that when you use rolling(3).apply(f), the result for index i will be the result of f applied to [i-2, i-1, i], not ]i-2, i-1, i] (ISO 31-11 math set notation). One could argue that this is equivalent to having closed='right' with f applied to ]i-3, i-2, i-1, i]. Indeed, but this probably adulterates the meaning of the window size.

@carlosdanielcsantos can you show a comparison of these 2, to show more what you mean?

2017-03-28 17:00 UTC, jreback commented
> Nonetheless, I think that the possibility of ignoring the current index in computations is valuable (that was my initial problem, after all). Some solutions for this are:

This a bit orthogonal though. We *always* want to actually use the index. Since using a fixed window size, it *looks* like we are ignoring the index :>.

So a possiblity is to actually check the index whether its equiv to a RangeIndex. e.g.

```
In [5]: df1 = pd.DataFrame([1] * 5)

In [6]: df1.rolling(3, min_periods=1).sum()
Out[6]: 
     0
0  1.0
1  2.0
2  3.0
3  3.0
4  3.0

In [8]: df2 = pd.DataFrame([1] * 5, index=[0, 1, 3, 4, 5])

In [9]: df2.rolling(3, min_periods=1).sum()
Out[9]: 
     0
0  1.0
1  2.0
3  3.0
4  3.0
5  3.0
```

```
In [11]: (np.diff(df1.index)==1).all()
Out[11]: True

In [12]: (np.diff(df2.index)==1).all()
Out[12]: False

```

Let's deal with this in a separate issue. 

A way to disambiguate on this ATM is to allow ``closed=None`` to be the default parameter. Then it cannot be anything but that for a FixedWindow. For Variable, if we see ``closed=None`` -> ``closed='right'`` IOW the default is the same. And then allow the rest of the closed intervals.

I think *we* should fix this for Fixed intervals, but I agree this is a problem because we essentially have ``closed='both'`` as the default now (its implicit though) (as you stated above).

2017-03-29 19:37 UTC, jreback commented
@carlosdanielcsantos if you can update would be great (docs and such), ignoring the issue about fixed windows for the moment.

2017-04-03 16:18 UTC, carlosdanielcsantos commented
I'll do that in the next hours. Should I just leave the fixed-window as it is?

2017-04-03 16:29 UTC, jreback commented
I think make the ``closed=None`` the default, and document the possibilities (and default) for the variable sized window (and validate left,right,both,neither). For the fixed window document as well (you can say its closed='both', but ATM only allow None). and then open a new issue where we can deal with this.

We have to fix this, but this PR merely opens up the possibilities of change here. So I think ok to merge this.

2017-04-09 14:01 UTC, jreback commented
@carlosdanielcsantos can you update

2017-04-10 00:30 UTC, carlosdanielcsantos commented
@jreback made some corrections but circleci is not passing in test_append_index - pandas.tests.test_multilevel.TestMultiLevel, but passing locally. Any thoughts?

2017-04-10 00:52 UTC, jreback commented
try pushing again (make a modification)
looks like a fluke

2017-04-11 08:27 UTC, carlosdanielcsantos commented
@jreback Still not passing. Could I have broken this with the changes in window?

2017-04-11 10:22 UTC, jreback commented
@carlosdanielcsantos I rebased you against current master. This should pass cleanly. If you'd make those other changes and ping.

2017-04-12 08:23 UTC, carlosdanielcsantos commented
@jreback what changes? I believe I updated everything that you requested. Can you take a look at AppVeyor build that failed?

2017-04-12 10:38 UTC, jreback approved these changes
minor comments.

2017-04-12 10:38 UTC, jreback commented on doc/source/computation.rst
> +~~~~~~~~~~~~~~~~~~
make this Rolling Window Endpoints

2017-04-12 10:38 UTC, jreback commented on doc/source/computation.rst
> +  - ``right`` : close right endpoint (default for time-based windows)
can you make this a csv-table (3 columns: ``closed``, ``description``, ``default``) or something like that

2017-04-12 10:38 UTC, jreback commented on doc/source/computation.rst
> +Currently, this feature is only implemented for time-based windows.
expand this a touch to say that *only* ``closed='both'`` is accepted for fixed windows.

2017-04-12 10:38 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- ``DataFrame.rolling()`` now accepts the parameter ``closed='right'|'left'|'both'|'neither'`` to choose the rolling window endpoint closedness. See :ref:`documentation <stats.rolling_window.endpoint
See ``:ref:`the documentation ....``

2017-04-12 10:38 UTC, jreback commented on pandas/core/window.py
> +            raise ValueError("closed must be 'right', 'left', 'both' or "
is there validation for a fixed window when closed is NOT both?

2017-04-12 22:47 UTC, carlosdanielcsantos commented on doc/source/computation.rst
> +Currently, this feature is only implemented for time-based windows.
I am only accepting closed=None for fixed windows, as previously requested by you

> For the fixed window document as well (you can say its closed='both', but ATM only allow None)

2017-04-12 22:49 UTC, jreback commented on doc/source/computation.rst
> +Currently, this feature is only implemented for time-based windows.
that's what i mean just make sure the docs are clear on that ; e.g. None -> 'both' for fixed (and assert that as well )

2017-04-12 22:51 UTC, carlosdanielcsantos commented on pandas/core/window.py
> +            raise ValueError("closed must be 'right', 'left', 'both' or "
Again, there is a validation for when closed is not None in Rolling.validate()

2017-04-13 09:29 UTC, carlosdanielcsantos commented on pandas/tests/test_window.py
> +    def test_closed(self):
@jreback here is the piece that tests that closed must be None for fixed-window. Well, actually it only tests that it should not be 'neither', but I do not think replication is necessary.

2017-04-13 09:31 UTC, carlosdanielcsantos commented on pandas/core/window.py
> +        if not self.is_datetimelike and self.closed is not None:
@jreback here we enforce that `closed` must be `None` for windows that are not datetimelike

2017-04-13 11:39 UTC, closed without merging

2017-04-13 11:39 UTC, jreback commented
thanks @carlosdanielcsantos nice PR. as you can see, the code changes are the 'easy' part, its the docs & testing that are the details.!

keem em coming!