BUG: SparseDataFrame construction with lists not coercing to dtype  (GH 15682)
pandas-dev/pandas pull request #15834
Opened 2017-03-29 08:38 UTC by ucals

- [x] closes #15682
 - [x] tests added / passed
 - [ ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [x] whatsnew entry

2017-03-29 12:18 UTC, jreback requested changes

2017-03-29 12:18 UTC, jreback commented on pandas/sparse/frame.py
> +            sdict[k] = v.astype(np.dtype(dtype)) if dtype is not None else v
you would do this in ``sp_maker``, also don't use if/else on a single line (hard to read)

2017-03-29 12:18 UTC, jreback commented on pandas/tests/sparse/test_frame.py
> -        renamed = self.frame.rename(columns=lambda x: '%s%d' % (x, len(x)))  # noqa
can you compare these results (as no tests before).

2017-03-29 12:18 UTC, jreback commented on pandas/tests/sparse/test_frame.py
> -
try to turn off this removing blank lines like this

2017-03-29 12:18 UTC, jreback commented on pandas/tests/sparse/test_frame.py
> +        result = df.dtypes[0]
create the result and use ``assert_sp_frame_equal``

2017-03-29 12:20 UTC, jreback requested changes

2017-03-29 12:20 UTC, jreback commented on pandas/tests/sparse/test_frame.py
> +        result = df.dtypes[0]
you can use the comparison from the issue (IOW construct both ways and compare)

2017-03-29 12:20 UTC, jreback commented on pandas/tests/sparse/test_frame.py
> +        result = df.dtypes[0]
move this test where other ``test_constructor`` tests are

2017-03-29 17:47 UTC, ucals commented on pandas/tests/sparse/test_frame.py
> +        result = df.dtypes[0]
done

2017-03-29 17:47 UTC, ucals commented on pandas/sparse/frame.py
> +            sdict[k] = v.astype(np.dtype(dtype)) if dtype is not None else v
done

2017-03-29 17:58 UTC, ucals commented on pandas/tests/sparse/test_frame.py
> -        renamed = self.frame.rename(columns=lambda x: '%s%d' % (x, len(x)))  # noqa
didn't understand

2017-03-29 17:59 UTC, ucals commented on pandas/tests/sparse/test_frame.py
> -
just put it back, sorry

2017-03-30 01:05 UTC, ucals commented on pandas/tests/sparse/test_frame.py
> -        renamed = self.frame.rename(columns=lambda x: '%s%d' % (x, len(x)))  # noqa
ok, just figured it out, added the right test on my last commit! :)

2017-03-30 12:19 UTC, closed without merging