na_position doesn't work for sort_index() with MultiIndex
pandas-dev/pandas pull request #15845
Opened 2017-03-30 06:57 UTC by linebp

- [X] closes #14784 
 - [X] tests added / passed
 - [X] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

2017-03-30 12:02 UTC, jreback commented
@linebp I'd prefer if you did something like I illustrated here: https://github.com/pandas-dev/pandas/issues/14784#issuecomment-287362444

Put these tests (and on Series as well) in ``test_multilevel.py`` where these types of things live. Further Ideally we'd do a lower-level test in ``pandas/tests/indexes/tests/test_multi.py`` and/or ``pandas/tests/tests_sorting.py``

2017-03-31 06:47 UTC, linebp commented
I am not sure what I am missing, I tried to do as suggested. These are my steps figuring out what to do:
* I looked for a function called `_lexsort_indexer` and didn't manage to locate it. 
* I figured what you meant was the function `lexsort_indexer`, which made sense to me, as this function is called while sorting the index.
* The `lexsort_indexer` is called directly from `sort_index`, no code in MultiIndex is called(?)
* I put the fix in `sort_index` as that is the function calling `lexsort_indexer`. This made good sense to me, as `lexsort_indexer` is not actually broken, but the data passed to it is. 

Where and how did I go wrong?

I'll move the tests to a more appropriate location! ... and test the Series sorting too.

2017-03-31 13:04 UTC, jreback requested changes
this needs testing for Series (which won't work as you have changed the code)

2017-03-31 13:04 UTC, jreback commented on pandas/core/frame.py
> -            indexer = lexsort_indexer(labels.labels, orders=ascending,
as I said, you can simply create a method on ``MultiIndex``, called ``_lexsort_indexer`` (let's make it private), that returns the correct indexer.

2017-04-04 13:16 UTC, jreback requested changes

2017-04-04 13:16 UTC, jreback commented on pandas/core/frame.py
> -            # if not we need to reconstruct to get the correct indexer
so leave the ``is_lexsorted`` check in here; this is fixed in #15694 w/o this subtle things will break.

2017-04-04 13:16 UTC, jreback commented on pandas/core/frame.py
> +            indexer = labels._lexsort_indexer(orders=ascending,
just do

```
indexer = lexsort_indexer(labels._get_labels_for_sorting(), orders=ascending,
                                      na_position=na_position)
```

so IOW rename ``pandas.indexes.multi._lexsort_indexer`` (your new routines) to ``_get_labels_for_sorting``

2017-04-04 13:16 UTC, jreback commented on pandas/core/series.py
> -            from pandas.core.sorting import lexsort_indexer
make the same change as above

2017-04-04 13:16 UTC, jreback commented on pandas/indexes/multi.py
> +        keys = []
rename to ``_get_labels_for_sorting()``

add a doc-string.

rename ``keys`` -> ``labels``

2017-04-05 06:55 UTC, linebp commented
so, add the `is_lexsorted` check to both series and frames `sort_index` right before call to `_lexsort_indexer`? What is the reason for not adding the check to the `_lexsort_indexer` function?

Panels seems to have a function similar to `sort_index` on frames and series, is that in the scope of this bug?

If you use the `level` option when calling `sort_index`, the `na_position` option is ignored.  Should this be fixed to?

2017-04-05 11:21 UTC, jreback commented
@linebp this needs to be very targeted. don't touch Panel and don't worry about level.

instead of a``labels.labels``, call ``labels._get_labels_for_sorting()``

it is *very* easy to break things w/o very specific patches.

2017-04-06 13:37 UTC, jreback commented
@linebp maybe I wasn't clear. These ALL the existing code, except for

``indexer = lexsort_indexer(index._get_labels_for_sorting(), orders=ascending)``

where ``_get_labels_for_sorting()`` is the routine that you added ``_lexsort_indexer``

so you are adding 1 function to MultiIndex, and changing 1 line in series & 1 line in frame.py thats it.

2017-04-07 08:54 UTC, linebp commented
I am still a bit confused about what to do, but this adds 1 function and only changes 1 line in series and frame each. No comments on the tests, so I let those stay as is.

2017-04-07 17:09 UTC, jreback commented
ok, pls rebase this as I pushed in a bunch of fixes for sorting (generally)

2017-04-16 18:25 UTC, linebp commented
I made an effort to rebase, how is it looking now?

2017-04-16 18:40 UTC, jreback commented
@linebp code looks good. pls add a whatsnew (bug fix). make sure you rebase on origin (there are still conflicts showing)

```
git rebase -i thisbranch origin/master
```

then push with ``-f`` to update.

2017-04-16 18:40 UTC, jreback approved these changes

2017-04-19 08:05 UTC, linebp commented
It fails when `Categorical.from_codes()` is called on an index where some rows are removed, for example with `dropna()`. The index is not relabelled and so the labels may be outside the -1 to len(categories) range. Example:
 
```
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'date': pd.to_datetime([
        '20121002', '20121007', '20130130', '20130202', '20130305',
        '20121002', '20121207', '20130130', '20130202', '20130305',
        '20130202', '20130305'
    ]),
    'user_id': [1, 1, 1, 1, 1, 3, 3, 3, 5, 5, 5, 5],
    'whole_cost': [1790, np.nan, 280, 259, np.nan, 623, 90, 312, np.nan, 301,
                   359, 801],
    'cost': [12, 15, 10, 24, 39, 1, 0, np.nan, 45, 34, 1, 12]
}).set_index(['date', 'user_id'])

df.dropna().sort_index()

```

2017-04-19 10:40 UTC, jreback commented
@linebp I pushed a fix to your branch. can you add the above as an additional tests. ping on green.

2017-04-19 22:29 UTC, closed without merging