DOC: timeseries.rst floating point precision (#15817)
pandas-dev/pandas pull request #15919
Opened 2017-04-06 09:48 UTC by mchwalisz

- [x] closes #15817

2017-04-06 11:55 UTC, jreback requested changes

2017-04-06 11:55 UTC, jreback commented on pandas/tseries/tools.py
> +        unexpected behavior use a fixed-width exact type.
this is true only for ns (make that clear); i would put this in the Notes section

2017-04-06 11:55 UTC, jreback commented on doc/source/timeseries.rst
> +Conversion of float epoch times can lead to inaccurate and unexpected results.
i would make this a note

also units are rounded to the unit precision so the first example is misleading

2017-04-06 12:02 UTC, mchwalisz commented on pandas/tseries/tools.py
> +        unexpected behavior use a fixed-width exact type.
If you mean for `unit='ns'` I don't agree. You can use `unit='s'` and have result saved up to mili seconds with rounding error from float. as in timeseries example

2017-04-06 12:18 UTC, mchwalisz commented on doc/source/timeseries.rst
> +Conversion of float epoch times can lead to inaccurate and unexpected results.
you mean the line as note or the whole section?

also unit is taken as the base but precision is taken from float. First example is exactly the problem I've had at the beginning.

```
In [36]: pd.to_datetime(1490195805.433502912, unit='s')
Out[36]: Timestamp('2017-03-22 15:16:45.433503')
```
It neither `s` nor `ns` in the example.

2017-04-06 13:24 UTC, jreback commented on doc/source/timeseries.rst
> +Conversion of float epoch times can lead to inaccurate and unexpected results.
right, that was the example, ok then.

2017-04-06 13:25 UTC, jreback commented on doc/source/timeseries.rst
> +Conversion of float epoch times can lead to inaccurate and unexpected results.
I mean this whole section  you added to make a note (or could do a warning).

2017-04-06 13:25 UTC, jreback commented on doc/source/timeseries.rst
>  These *work*, but the results may be unexpected.
you may have to adjust this line after

2017-04-06 13:26 UTC, jreback commented on pandas/tseries/tools.py
> +        unexpected behavior use a fixed-width exact type.
right. ok in any even still put it in the Notes section.

2017-04-06 15:10 UTC, mchwalisz commented
I've moved the warning in `to_datetime` to examples and rearranged sections in `timeseries.rst` to make it more logical (IMO).

2017-04-06 16:14 UTC, jreback commented
lgtm. @jorisvandenbossche

2017-04-06 21:44 UTC, jorisvandenbossche reviewed
Some small comments about the wording (to make sure everything is clear to the reader!)

2017-04-06 21:44 UTC, jorisvandenbossche commented on doc/source/timeseries.rst
> +   Python floats are unbounded precision, with about 15 significant digits (depends on
What do you mean with "unbounded precision"? that seems to contradict a bit with "15 digits"

2017-04-06 21:44 UTC, jorisvandenbossche commented on doc/source/timeseries.rst
> +   operating system). Rounding in conversion from to high precision ``Timestamp`` is
There seems to be something wrong in the "in conversion from to high precision ``Timestamp``" part (it doesn't read fluent to me)

2017-04-07 10:14 UTC, mchwalisz commented on doc/source/timeseries.rst
> +   operating system). Rounding in conversion from to high precision ``Timestamp`` is
flaot is missing. will correct it in a sec.

2017-04-07 12:15 UTC, jreback commented on doc/source/timeseries.rst
> +   operating system). Rounding in conversion from to high precision ``Timestamp`` is
pls emphasize that this is only on input of *very* high precision float data.

2017-04-07 12:17 UTC, jreback commented on doc/source/timeseries.rst
> +   These *work*, but the results may be unexpected.
this part is now hanging, so add something like. numeric input is in referece to the ``epoch`` time (actually may want to move this mini-example (just this last part here) to the 'origin' section.)

2017-04-08 21:54 UTC, closed without merging

2017-04-08 21:54 UTC, jreback commented
thanks!