ENH: Minor change to parallel_coordinates (#15908)
pandas-dev/pandas pull request #15935
Opened 2017-04-07 05:17 UTC by stangirala

Add option to sort class lables, add to test

 - [x] closes #15908
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

2017-04-07 12:11 UTC, jreback requested changes

2017-04-07 12:11 UTC, jreback commented on pandas/tests/plotting/test_misc.py
> +        df = DataFrame({"feat": [i for i in range(30)],
make this a separate named test

2017-04-07 12:11 UTC, jreback commented on pandas/tests/plotting/test_misc.py
> +        df = DataFrame({"feat": [i for i in range(30)],
add the issue number as a comment

2017-04-07 12:11 UTC, jreback commented on pandas/tools/plotting.py
> +        Sort class_column labels, useful when assigning colours
add a versionadded tag here, add the default (False) instead of optional

2017-04-07 12:11 UTC, jreback commented
pls add a whatsnew entry, in Other Enhancements.

2017-04-07 19:45 UTC, stangirala commented on pandas/tests/plotting/test_misc.py
> +        df = DataFrame({"feat": [i for i in range(30)],
Done

2017-04-11 11:52 UTC, TomAugspurger commented
@stangirala could you rebase and push one more time? Looks like our CI services were having trouble last time you pushed.

2017-04-11 18:49 UTC, stangirala commented
@TomAugspurger @jreback Looks like the CI builds are passing.

2017-04-11 20:10 UTC, stangirala commented
@TomAugspurger I'm actually not sure why the code coverage tool is reporting a decrease in coverage.

2017-04-11 20:11 UTC, TomAugspurger commented
Yeah, I took a glance and couldn't figure it out either. I'm guessing it's just a fluke, but I'll take a closer look later and merge.

2017-04-11 20:23 UTC, stangirala commented
Thanks!

2017-04-11 21:04 UTC, jreback commented
if your master is not up to date code coverage doesn't make much sense

2017-04-11 21:46 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- ``pd.read_csv()`` will now raise a ``csv.Error`` error whenever an end-of-file character is encountered in the middle of a data row (:issue:`15913`)
this line is duped

2017-04-11 21:46 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- ``parallel_coordinates()`` now has a ``sort_labels`` keyword arg that sorts class labels and the colours assigned to them (:issue:`15908`)
``has gained a ``

2017-04-11 21:47 UTC, jreback commented on pandas/tests/plotting/test_misc.py
> +        from pandas.tools.plotting import parallel_coordinates
you may need a mpl skip here? @TomAugspurger ?

2017-04-11 21:48 UTC, jreback commented on pandas/tools/plotting.py
> +    if sort_labels is True:
``if sort_labels`` is enough

2017-04-11 21:49 UTC, jreback commented
lgtm. minor comment.

2017-04-11 21:56 UTC, TomAugspurger commented on pandas/tests/plotting/test_misc.py
> +        from pandas.tools.plotting import parallel_coordinates
Done on the class.

2017-04-14 09:21 UTC, stangirala commented on doc/source/whatsnew/v0.20.0.txt
> +- ``pd.read_csv()`` will now raise a ``csv.Error`` error whenever an end-of-file character is encountered in the middle of a data row (:issue:`15913`)
I don't see this duped on my copy, can you double check?

2017-04-14 09:21 UTC, stangirala commented on doc/source/whatsnew/v0.20.0.txt
> +- ``parallel_coordinates()`` now has a ``sort_labels`` keyword arg that sorts class labels and the colours assigned to them (:issue:`15908`)
Fixed.

2017-04-14 09:22 UTC, stangirala commented on pandas/tools/plotting.py
> +    if sort_labels is True:
I mirrored an if expression from the lines above, but fixed.

2017-04-14 13:30 UTC, closed without merging

2017-04-14 13:30 UTC, jreback commented
thanks @stangirala