BUG: Fix Empty DataFrame.style.render raises IndexError
pandas-dev/pandas pull request #15971
Opened 2017-04-10 21:07 UTC by sandipchatterjee

Fix attempt for Issue #15953

Handles DataFrames and Series with no rows or columns
using `pd.DataFrame().empty` or `pd.Series().empty`

```python
In [1]: import pandas as pd

In [2]: pd.DataFrame().style.render()
Out[2]: '\n        <style  type="text/css" >\n        \n        \n        </style>\n\n        <table id="T_de3b3e8c_1e30_11e7_9abb_a8667f1b25b4" None>\n        \n\n        <thead>\n            \n        </thead>\n        <tbody>\n            \n        </tbody>\n        </table>\n        '
```

 - [ ] closes #15953 
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

2017-04-10 21:26 UTC, TomAugspurger requested changes
Thanks! One comment on the fix. Could you also add tests and a release note in doc/source/whatsnew/v0.20.0.txt?

2017-04-10 21:26 UTC, TomAugspurger commented on pandas/formats/style.py
> +        n_rlvls = 0 if self.data.empty else self.data.index.nlevels
I think you'll have to change this around a bit. `DataFrame.empty` is True if either the index or columns is empty. So you get

```python
pd.DataFrame([], index=[1, 2]).empty  #  True
pd.DataFrame([], columns=['A', 'B']).empty  # True
```

2017-04-10 21:27 UTC, TomAugspurger commented
I think our desired output is the same as the notebook 

![screen shot 2017-04-10 at 4 25 09 pm](https://cloud.githubusercontent.com/assets/1312546/24883449/91580a3c-1e0a-11e7-91ba-b525dd0a0a67.png)

2017-05-07 14:13 UTC, jreback commented
pls rebase / update according to the comments. Needs a tests.

2017-05-08 15:21 UTC, TomAugspurger commented
whatsnew notes should go in `whatsnew/0.20.1.txt` now.

2017-05-30 21:42 UTC, TomAugspurger commented
Looks like https://github.com/pandas-dev/pandas/pull/16441 fixed this in the meantime. Thanks anyways @sandipchatterjee, sorry about the duplicated effort.

2017-05-30 21:42 UTC, closed without merging