ENH: Crosstab support for setting the margins name #15972
pandas-dev/pandas pull request #15973
Opened 2017-04-11 11:23 UTC by slide333333

closes #15972

2017-04-11 11:34 UTC, TomAugspurger commented on pandas/tools/pivot.py
> +    margins_name : string, default 'All'
Can you add a ` ..versionadded:: 0.20.0` for this parameter?

2017-04-11 11:35 UTC, TomAugspurger requested changes
Thanks.

One comment on the docstring.

Can you also add a note in the whatsnew file, and a couple tests (one with the default, one with a user-specified argument).

2017-05-07 13:35 UTC, jreback commented
needs a rebase and tests

2017-05-30 21:44 UTC, TomAugspurger commented
Looks like https://github.com/pandas-dev/pandas/pull/16489 fixed this in the meantime. Sorry @slide333333 , but thanks anyways for the PR.

2017-05-30 21:44 UTC, closed without merging