BUG: Fix length 1 .loc slicing with datetime string GH16071
pandas-dev/pandas pull request #16072
Opened 2017-04-20 14:53 UTC by cpaulik

- [x] closes #16071 
 - [ ] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [x] whatsnew entry

2017-04-20 19:16 UTC, TomAugspurger reviewed
I think since you aren't using any of the advanced pytest features like fixtures, it'd be better to include this test with other similar ones on the class.

2017-04-20 19:16 UTC, TomAugspurger commented on pandas/tests/indexing/test_loc.py
> +    df = pd.DataFrame(columns=['1'],
This is the same `df` right? Shouldn't need to re-create it (unless I'm missing something).

2017-04-20 19:16 UTC, TomAugspurger commented on pandas/tests/indexing/test_loc.py
> +    """
You can replace this docstring with the github issue number

2017-04-20 22:40 UTC, jreback requested changes

2017-04-20 22:40 UTC, jreback commented on pandas/tests/indexing/test_loc.py
> +    from datetime import datetime
datetime should already be imported (if not add at the very top)

2017-04-20 22:40 UTC, jreback commented on pandas/tests/indexing/test_loc.py
> +    df_sliced_dt = df.loc[datetime(2016, 10, 1):]
```
result = ....
tm.assert_frame_equal(result, df)
```

2017-04-20 22:40 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- ``loc`` indexer with datetime strings now works correctly for length 1 DataFrames and is consistent with the behaviour of using a ``datetime.datetime`` object (:issue:`16071')
move to Bug / Conversion section

just say: ``Bug in indexing with partial string indexing with a len-1 ``DataFrame`` ``

2017-04-20 22:40 UTC, jreback commented on pandas/tests/indexing/test_loc.py
> +
move this test to : ``pandas/tests/indexes/datetimes/test_partial_slcing.py ``

2017-04-21 09:28 UTC, cpaulik commented
Thank you for the feedback. I made the requested changes.

2017-04-21 10:21 UTC, jreback approved these changes

2017-04-21 10:28 UTC, closed without merging