Unary plus operator (Issue #16073)
pandas-dev/pandas pull request #16106
Opened 2017-04-24 07:27 UTC by wuisawesome

- [x] closes #16073
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [x] whatsnew entry

Continuation from https://github.com/pandas-dev/pandas/pull/16103.

2017-04-24 10:24 UTC, jreback requested changes

2017-04-24 10:24 UTC, jreback commented on pandas/tests/series/test_operators.py
> +       assert_series_equal(+self.series, 1 * self.series)  #Ensures no rounding issues
comment is not necessary

2017-04-24 10:24 UTC, jreback commented on pandas/tests/series/test_operators.py
> +
add a couple of raise assertion on strings

2017-04-24 10:24 UTC, jreback commented on pandas/tests/series/test_operators.py
> +
this would technically work on datetimes, but I think we should disallow this (pls add tests for ``__neg__`` as well).

2017-04-24 10:24 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> +- `Series` and `DataFrame` now have unary plus operators (:issue:`16073`). The plus operator behaves consistently with the unary minus operator.
use double backticks here around Series, DataFrame. Put the issue reference at the end.

2017-04-24 10:24 UTC, jreback commented on doc/source/whatsnew/v0.20.0.txt
> -.. ipython:: python
don't change other things in the file

2017-04-24 10:24 UTC, jreback commented on pandas/tests/series/test_operators.py
> +
e.g. 

```
In [9]: -Series(list('abc'))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-93660e79330e> in <module>()
----> 1 -Series(list('abc'))

/Users/jreback/pandas/pandas/core/generic.py in __neg__(self)
    865             arr = operator.inv(values)
    866         else:
--> 867             arr = operator.neg(values)
    868         return self.__array_wrap__(arr)
    869 

TypeError: bad operand type for unary -: 'str'
```

2017-04-24 10:24 UTC, jreback commented on pandas/tests/series/test_operators.py
> +
```
In [10]: Series(pd.date_range('20130101', periods=3))
Out[10]: 
0   2013-01-01
1   2013-01-02
2   2013-01-03
dtype: datetime64[ns]

In [11]: -Series(pd.date_range('20130101', periods=3))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-23bfb90f61eb> in <module>()
----> 1 -Series(pd.date_range('20130101', periods=3))

/Users/jreback/pandas/pandas/core/generic.py in __neg__(self)
    865             arr = operator.inv(values)
    866         else:
--> 867             arr = operator.neg(values)
    868         return self.__array_wrap__(arr)
    869 

TypeError: ufunc 'negative' did not contain a loop with signature matching types dtype('<M8[ns]') dtype('<M8[ns]')

In [12]: +Series(pd.date_range('20130101', periods=3))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-b72a11ca274c> in <module>()
----> 1 +Series(pd.date_range('20130101', periods=3))

TypeError: bad operand type for unary +: 'Series'

```

I want [12] still to raise after this change.

2017-04-24 18:41 UTC, wuisawesome commented on doc/source/whatsnew/v0.20.0.txt
> -.. ipython:: python
I'm not certain why this happened. The rest of the diff shows that the same identical line is added again, thus making no actual changes to the file

2017-04-24 21:58 UTC, wuisawesome commented
Hopefully I've addressed all your concerns and rebased.

2017-04-25 02:28 UTC, jreback requested changes

2017-04-25 02:28 UTC, jreback commented on pandas/tests/frame/test_operators.py
> +            assert_frame_equal(+self.frame, self.frame.apply(lambda x: +self.frame))
dont' test like this. instead use a couple of sample frames that have singular dtypes (can be a single column). test the valid ones via ``assert_frame_equal(-frame, -1 * frame)``. The invalid ones should raise.

2017-04-25 02:28 UTC, jreback commented on pandas/tests/series/test_operators.py
> +           if not (len(self.frame) > 0 and isinstance(self.frame[0], pd.Timestampe)):
same

2017-04-25 02:28 UTC, jreback commented on pandas/core/generic.py
> +        if values.dtype == np.bool_:
something like:
```
if is_bool_dtype(values):
   ...
elif not (is_numeric_dtype(values) or is_timedelta64_dtype(values)):
   raise
```

2017-04-25 02:28 UTC, jreback commented on pandas/core/generic.py
> +        if values.dtype == np.bool_:
add the same logic to ``__neg__``

2017-05-13 21:40 UTC, jreback commented
can you rebase / update

2017-05-19 01:11 UTC, jreback commented
can you move whatsnew & rebase / update

2017-08-01 22:57 UTC, jreback commented
closing as stale. if you want to re-visit, pls comment and we can re-open.

2017-08-01 22:57 UTC, closed without merging