Unblock supported compression libs in pytables
pandas-dev/pandas pull request #16196
Opened 2017-05-02 08:36 UTC by linebp

- [x] closes #14478
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

2017-05-02 10:30 UTC, jreback commented on pandas/tests/io/test_pytables.py
> +        data = [{'ID': '7082-GTZ-572490',
don't specify data like this, just use ``tm.makeDataFrame``

2017-05-02 10:36 UTC, jreback requested changes

2017-05-02 10:36 UTC, jreback commented on pandas/tests/io/test_pytables.py
> +            with ensure_clean_store(self.path, complib=lib,
I would rather you use ``.to_hdf`` and ``.read_hdf`` here

2017-05-02 10:36 UTC, jreback commented
this is going to need a release note for 0.20.1 (but doesn't exist as of yet, soon).

2017-05-03 10:22 UTC, jreback commented on pandas/tests/io/test_pytables.py
> +
can you add a test that validates that ``complevel=0`` turns off compression?

2017-05-03 10:22 UTC, jreback commented on pandas/tests/io/test_pytables.py
> +        df = tm.makeDataFrame()
add a comment referencing the issue

2017-05-03 10:23 UTC, jreback commented on pandas/tests/io/test_pytables.py
>              pytest.raises(ValueError, df.to_hdf, path,
this needs to have be

```
with pytest.raises(ValueError):
   ...
```

2017-05-04 07:54 UTC, linebp commented on pandas/tests/io/test_pytables.py
> +
How do I best do that? There is the h5dump utility that can tell me if its compressed or I can compare the size of the files perhaps?

2017-05-04 11:24 UTC, jreback commented on pandas/tests/io/test_pytables.py
> +
look in the meta data of the file
lots of _ attributes that define things like this
pytables docs might be helpful

2017-05-11 09:58 UTC, linebp commented
It turned out that not all configurations has lzo compression available, so I removed those tests for those scenarios. 

Is this looking good? The whatsnew file for 20.1 is still not in existence?

2017-05-11 11:32 UTC, jreback approved these changes

2017-05-11 11:33 UTC, jreback commented
@linebp put this in 0.20.2 Enhancements (0.20.1 doesn't exist and was a combine release with 0.20.0).

ping on green.

2017-05-11 11:34 UTC, jreback commented on pandas/core/generic.py
> +            compressor specified: 'blosc:blosclz'):
add as of 0.20.2 these addtional compressors are available.

2017-05-11 11:34 UTC, jreback commented on pandas/io/pytables.py
> +            compressor specified: 'blosc:blosclz'):
same here

2017-05-11 18:32 UTC, linebp commented
Its all green now.

2017-05-11 22:55 UTC, merged

2017-05-11 22:55 UTC, jreback commented
thanks!