rolling.quantile returns an interpolated result
pandas-dev/pandas pull request #16216
Opened 2017-05-03 12:00 UTC by guillemborrell

- [x] closes #16211 
 - [x] tests added / passed
 - [ ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

2017-05-03 12:34 UTC, jreback requested changes
pls add a release note (0.20.1), call a bug fix is fine. 
pls add the example from the issue as an additional tests; add a comment to reference the issue

2017-05-03 12:34 UTC, jreback commented on pandas/tests/test_window.py
> +                retval = vlow + (vhig - vlow)*(per - qlow)/(qhig - qlow)
this will cause some lint issues

2017-05-03 12:35 UTC, jreback commented
add the examples as tests from #9413

2017-05-03 13:14 UTC, guillemborrell commented
In my last master. The linter passed OK, and I have created a whatsnew entry in the Numeric section.

2017-05-03 13:30 UTC, guillemborrell commented
@jreback  I think that I have implemented all the requested improvements.

2017-05-04 10:46 UTC, guillemborrell commented
@jreback. Tests passed and changes implemented.

2017-05-05 06:44 UTC, closed without merging

2017-05-05 06:53 UTC, guillemborrell commented
@jreback I closed this a created a clean PR: #16247

2017-05-05 10:09 UTC, jreback commented
pls don't open new pr's for the same issue, you simply push to the same PR. ok on this one.

2017-05-05 10:31 UTC, guillemborrell commented
Sorry. Just trying to make things right.