ENH: add optional ddof param to DataFrame.cov()
pandas-dev/pandas pull request #16227
Opened 2017-05-04 09:23 UTC by edhalter

- [ ] closes #xxxx (searched, didn't see any issues on this topic)
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [x] whatsnew entry

Noticed that the .cov() methods on DataFrame and Series assume the user wants to calculate sample variance and normalize by N-1. In contrast, the .var() and .std() methods on DataFrame, Series, DataFrameGroupBy, and SeriesGroupBy take a ddof parameter. Its default value is 1, calculating the sample std/var, but the user can specify ddof=0 to calculate the population std/var.

Simply added a ddof param (default value 1) to the .cov() methods. The value is then passed into other method calls as required. Did have to modify 1 bit of Cython code in algos.pyx, the nancorr() function.

2017-05-04 11:59 UTC, jreback approved these changes
lgtm.

2017-05-04 11:59 UTC, jreback commented on pandas/core/frame.py
> +            is ``N - ddof``, where ``N`` represents the number of elements.
versionadded tag

2017-05-04 11:59 UTC, jreback commented on pandas/core/series.py
same

2017-05-04 11:59 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- The ``.cov()`` methods for DataFrame and Series now accept the parameter
add this PR number here

2017-05-04 11:59 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- The ``.cov()`` methods for DataFrame and Series now accept the parameter
accept -> accepts

2017-05-04 12:21 UTC, TomAugspurger commented on pandas/core/frame.py
> +        Normalized by N-1 by default. This can be changed using the ddof argument"
I don't think this line is needed (as it's have it in the Notes section)

2017-05-04 12:21 UTC, TomAugspurger commented on pandas/core/frame.py
> +        The covariance is normalized by N-ddof -- for the default ddof value of
Double backticks around `N-ddof` and `ddof`.

2017-05-04 12:21 UTC, TomAugspurger commented on pandas/core/series.py
> +        Normalized by N-1 by default. This can be changed using the ddof argument"
Can probably make this a new Notes section, and combine with the note that's currently in the Returns section.

2017-06-10 19:04 UTC, jreback commented
can you rebase and update?

2017-06-13 14:27 UTC, edhalter commented
Made changes to docstrings, etc. based on comments. Rebased and updated.

2017-06-13 14:38 UTC, TomAugspurger commented
@edhalter did you push your changes? There seems to be a conflict in the whatsnew file. You may need to force push to your branch.

2017-06-14 13:56 UTC, edhalter commented
Already pushed -- the conflicting file has my most recent changes. Someone just needs to edit it and append my new line to the other new lines under "Other Enhancements".

2017-06-14 23:10 UTC, jreback commented
@edhalter pls rebase on master. this will present a conflict which you fix, then push.

2017-06-15 03:23 UTC, edhalter commented
Rebased on master.

2017-06-15 10:20 UTC, jreback requested changes

2017-06-15 10:20 UTC, jreback commented on pandas/core/frame.py
> +            .. versionadded:: 0.21.0
move the versionadded tag below the expl.

2017-06-15 10:20 UTC, jreback commented on pandas/core/frame.py
> +        The covariance is normalized by ``N-ddof`` -- for the default ``ddof``
just start a new sentence, I don't think '--' works here.

2017-06-15 10:20 UTC, jreback commented on pandas/core/series.py
> +            .. versionadded:: 0.21.0
same as above

2017-06-15 10:20 UTC, jreback commented on pandas/core/series.py
> +        The returned covariance is normalized by ``N-ddof`` -- for the default
same as above

2017-06-15 10:20 UTC, jreback commented on pandas/_libs/algos.pyx
> -                    divisor = (nobs - 1.0) if cov else sqrt(sumxx * sumyy)
what about ddofv >= nobs case? can you add a test for this. looks like divisor == 0 is handled, but what about ddofv > nobs?

2017-06-16 04:01 UTC, edhalter commented
Added some checks in DataFrame.cov() and the nancov() func called by Series.cov():

- sanity check on input ddof
- warn when N - ddof <= 0

For the latter, alternatively, could throw an Exception, or just silently return nan. The warning seemed better -- that's what numpy's cov() does:

`warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)`

However, the Cython nancorr() func called by DataFrame.cov() does just silently return nan.

2017-06-16 10:58 UTC, jreback approved these changes

2017-06-16 10:59 UTC, jreback commented
> warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)

can you change UserWarning -> RuntimeWarning to be consistent

> However, the Cython nancorr() func called by DataFrame.cov() does just silently return nan.

can you change (and test) this as well?

2017-07-07 10:36 UTC, jreback commented
if you can rebase and update

2017-08-17 10:36 UTC, jreback commented
can you rebase

2017-08-21 08:30 UTC, pep8speaks commented
Hello @edhalter! Thanks for updating the PR.







 - In the file [`pandas/tests/frame/test_analytics.py`](https://github.com/pandas-dev/pandas/blob/7cb4b0b62b942fd39d933e99df75d0c37f18d546/pandas/tests/frame/test_analytics.py), following are the PEP8 issues :

> [Line 137:30](https://github.com/pandas-dev/pandas/blob/7cb4b0b62b942fd39d933e99df75d0c37f18d546/pandas/tests/frame/test_analytics.py#L137): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 139:80](https://github.com/pandas-dev/pandas/blob/7cb4b0b62b942fd39d933e99df75d0c37f18d546/pandas/tests/frame/test_analytics.py#L139): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 146:80](https://github.com/pandas-dev/pandas/blob/7cb4b0b62b942fd39d933e99df75d0c37f18d546/pandas/tests/frame/test_analytics.py#L146): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)

2017-08-21 10:29 UTC, edhalter commented
Returning to this.... Changed warning type to RuntimeWarning, and added a single warning that will throw in cython from nancorr() if at least 1 result in the matrix is set to NaN due to N - ddof <= 0.

Manual tests looked good. Also added some more automated tests in DataFrame's test_cov().

2017-08-22 12:50 UTC, jreback requested changes

2017-09-23 20:12 UTC, jreback commented on pandas/core/frame.py
> +                fill_nan = True
can you explain whats going on here

2017-09-23 20:12 UTC, jreback commented on pandas/tests/frame/test_analytics.py
> +        for ddof in [0, 1]:
can you do this

2017-09-23 20:12 UTC, jreback requested changes
pls rebase and update according to comments

2017-10-29 23:20 UTC, jreback commented
closing as stale, but if you'd like to continue work, pls rebase and ping.

2017-10-29 23:20 UTC, closed without merging