BUG: Incorrect handling of rolling.cov with offset window
pandas-dev/pandas pull request #16244
Opened 2017-05-04 22:33 UTC by keitakurita

- [x] closes #16058
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

2017-05-04 23:28 UTC, jreback commented on pandas/tests/test_window.py
> +
comment with the issue

2017-05-05 00:36 UTC, keitakurita commented on pandas/tests/test_window.py
> +
fixed!

2017-05-06 23:18 UTC, jreback requested changes
add the test from the issue. I would prefer that instead of comparing the results, you construct the correct results for each case.

add a whatsnew note in 0.20.2 bug fixes / rolling section

2017-05-06 23:18 UTC, jreback commented on pandas/core/window.py
> +        if self.is_freq_type:
you can do this in ``_get_window`` itself i think.

2017-05-08 01:40 UTC, keitakurita commented on pandas/core/window.py
> +        if self.is_freq_type:
I tried changing `_get_window`, but a lot of methods (such as `var`, `median`, and `sum`) require an integer window and seem to be working fine right now. If this issue is not a problem in methods other than `cov`, changing the code only for `cov` seems to make more sense.

2017-05-08 05:57 UTC, keitakurita commented on pandas/core/window.py
> +        if self.is_freq_type:
test for issue and whatsnew note added

2017-05-19 01:06 UTC, jreback commented on pandas/core/window.py
> +        if self.is_freq_type:
can you add a comment here (1-line) about this

2017-05-19 01:08 UTC, jreback commented on pandas/tests/test_window.py
> +        result = ss.rolling('2h').cov()
also test again using ``ss.rolling(2).cov()`` (will be the same for this case).

I don't know if we have any tests for a non-regular date range (Iow where freq='2' and freq='2h' are actually different.

2017-05-20 00:25 UTC, keitakurita commented on pandas/tests/test_window.py
> +        result = ss.rolling('2h').cov()
test added

2017-05-30 21:41 UTC, TomAugspurger commented
Rebased. @jreback I think everything was addressed, if you want to verify?

2017-05-30 23:12 UTC, jreback approved these changes

2017-05-30 23:12 UTC, merged

2017-05-30 23:12 UTC, jreback commented
thanks!