Adding 'protocol' parameter to 'to_pickle'.
pandas-dev/pandas pull request #16252
Opened 2017-05-05 12:40 UTC by jbschiratti

This PR aims at adding an optional `protocol` parameter to the function `to_pickle`. 
Closes #14488. If needed, I can update the corresponding test (`pandas/tests/io/test_pickle.py`).

2017-05-05 12:49 UTC, jreback commented
tests are the first thing you should write.

2017-05-06 22:25 UTC, jreback requested changes
needs some tests. with valid & invalid protocol passed.

2017-05-06 22:25 UTC, jreback commented on pandas/core/generic.py
> +from pandas.compat import cPickle as pkl
move to the previous line

2017-05-06 22:25 UTC, jreback commented on pandas/core/generic.py
> +            default HIGHEST_PROTOCOL (Pickle module).
version added tag (the compression one goes above this), your tag should read 0.21.0

2017-05-06 22:25 UTC, jreback commented on pandas/io/pickle.py
> +    protocol : int
same

2017-05-06 22:26 UTC, jreback commented
also add a whatsnew in enhancements for 0.21.0

2017-05-11 16:16 UTC, jbschiratti commented
I am facing an issue when writing the tests.
I Installed a pandas-dev environment as suggested in http://pandas.pydata.org/pandas-docs/stable/contributing.html. When I try to run `pytests` on `pandas/tests/io/test_pickle.py`, I get the following error :

```
 % pytest test_pickle.py                                                                                                                                                                                             ~/pandas/pandas/tests/io
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /cal/homes/jbschiratti/pandas, inifile: setup.cfg
plugins: cov-2.3.1
collected 42 items 

test_pickle.py ..........................................Traceback (most recent call last):
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/bin/pytest", line 6, in <module>
    sys.exit(pytest.main())
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/config.py", line 57, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/main.py", line 127, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/main.py", line 122, in wrap_session
    exitstatus=session.exitstatus)
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/terminal.py", line 358, in pytest_sessionfinish
    outcome.get_result()
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/cacheprovider.py", line 152, in pytest_sessionfinish
    prev_failed = config.cache.get("cache/lastfailed", None) is not None
  File "/cal/homes/jbschiratti/anaconda3/envs/pandas_dev/lib/python3.6/site-packages/_pytest/cacheprovider.py", line 57, in get
    return json.load(f)
AttributeError: module 'json' has no attribute 'load'
```
Is it because it indirectly calls the wrong `json` module ?

2017-05-11 16:50 UTC, TomAugspurger commented
Try changing to the root of the git repo and running `pandas/tests/io/test_pickle.py`

2017-05-11 16:54 UTC, jbschiratti commented
@TomAugspurger It solved my problem. Thanks!

2017-05-11 22:58 UTC, jreback commented
this needs some tests.

2017-05-11 23:02 UTC, jbschiratti commented
I'm on it. I'll make a new commit, very soon, with the necessary tests.

2017-05-12 13:54 UTC, jbschiratti commented
@jreback I added some tests for valid and invalid values of the `protocol` parameter. Please, have a look and tell me if more tests are needed or if there is a problem with the code.

2017-05-17 09:09 UTC, jbschiratti commented
@jreback : Do you think that more tests are needed ?

2017-05-17 12:24 UTC, jreback approved these changes
lgtm.

2017-05-17 12:24 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +Pickle file I/O protocol parameter
I don't think we need this section. Can just add a single line with the issue refernce.

2017-05-17 12:25 UTC, jreback commented
small linting failure.

2017-05-17 12:36 UTC, jbschiratti commented on doc/source/whatsnew/v0.21.0.txt
> +Pickle file I/O protocol parameter
I changed the 'whatsnew' file accordingly.

2017-05-17 12:43 UTC, jbschiratti commented
If I understand correctly, the failure comes from `cpplint` because the code in some file violates style requirements (it is not compliant with Google's C++ style guide). How could I fix this ?

2017-05-17 23:23 UTC, jreback reviewed
lgtm. minor comments. ping on green.

2017-05-17 23:23 UTC, jreback commented on pandas/core/generic.py
> +            protocol parameter is equivalent to setting its value to
can you add a link to the pickle docs where this is defined.

2017-05-17 23:23 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Added protocol parameter to :func:`to_pickle`. The 'protocol' parameter defaults to HIGHEST_PROTOCOL. (:issue:`16252`)
:func:`to_pickle` has gained a protocol parameter.....

2017-05-17 23:23 UTC, jreback commented on pandas/io/pickle.py
> +        possible values are 0, 1, 2. For Python>=3.0, 3 is a valid value.
same

2017-05-18 08:10 UTC, jbschiratti commented on pandas/core/generic.py
> +            protocol parameter is equivalent to setting its value to
done, I added the url.

2017-05-18 09:46 UTC, jbschiratti commented
With my previous commit, all tests were successful. After modifying docstrings and the whatsnew file, `test_clipboard` is failing, according to Travis. Is there something wrong with my recent changes ?

2017-05-18 10:06 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +this parameter is set to HIGHEST_PROTOCOL (see https://docs.python.org/3/library/pickle.html, 12.1.2).
does this render? e.g. we normally use `HIGHEST_PROTOCOL <url....>`__

2017-05-18 10:07 UTC, jreback commented
I restarted that CI job. sometimes that tests fails :<

minor comment on docs. just ping when pushed.

2017-05-18 10:22 UTC, jbschiratti commented
@jreback : I pushed the changes.

2017-05-18 10:30 UTC, jreback commented
thanks!

2017-05-18 10:30 UTC, closed without merging

2017-05-18 10:31 UTC, jreback commented
keem em coming!