BUG: pathlib.Path in io
pandas-dev/pandas pull request #16292
Opened 2017-05-09 00:43 UTC by chris-b1

- [x] closes #16291
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [x] whatsnew entry

2017-05-09 00:46 UTC, jreback requested changes

2017-05-09 00:46 UTC, jreback commented on pandas/tests/io/test_pickle.py
> +    tm._skip_if_no_pathlib()
instead of making a specific test can u add a general routine like we have for round_trip_pickle

2017-05-09 00:46 UTC, jreback commented on pandas/tests/io/test_pickle.py
> +    tm._skip_if_no_pathlib()
and then use it here

ideally add tests for all of the io functions (and xfail id they don't work)

and test for localpath as well

2017-05-09 01:00 UTC, chris-b1 commented on pandas/tests/io/test_pickle.py
> +    tm._skip_if_no_pathlib()
Good point, let me know if what I just pushed is what you had in mind and I'll add to other io functions

2017-05-09 01:08 UTC, jreback commented on pandas/tests/io/test_pickle.py
> +    tm._skip_if_no_localpath()
I would move the skip routines to the actual test functions themselves (in util/testing)

2017-05-09 01:09 UTC, jreback commented on pandas/util/testing.py
> +    from py.path import local as LocalPath
e.g. here. 

and you need an pytimportor.skip here (for both of these).

2017-05-09 01:09 UTC, jreback commented on pandas/tests/io/test_pickle.py
> +    tm._skip_if_no_localpath()
ignore this, you can just use a skip importer below.

2017-05-09 01:10 UTC, jreback commented on pandas/tests/io/test_pickle.py
> +    tm._skip_if_no_pathlib()
yep exactly like this!

maybe put a little docs in the testing file above these 3 tests routines.

2017-05-09 02:08 UTC, jreback approved these changes
fantastic. thanks! (tiny comments). merge when ready.

2017-05-09 02:08 UTC, jreback commented on pandas/io/common.py
> +    # Convert pathlib.Path/py.path.local or string
can you add a blank line

2017-05-09 02:08 UTC, jreback commented on doc/source/whatsnew/v0.20.2.txt
> +- Bug in using ``pathlib.Path`` object with io functions (:issue:`16291`)
localpath too?

2017-05-09 07:49 UTC, jorisvandenbossche commented on pandas/tests/io/parser/common.py
> +        result = tm.round_trip_pathlib(df.to_csv,
round_trip_localpath ?

2017-05-09 10:15 UTC, jreback commented
for those ones which xfail this, can you create an issue (put all in issue). Though might be one that just needs updating.

2017-05-09 10:16 UTC, jreback commented on pandas/tests/io/sas/test_sas7bdat.py
> +    def test_path_pathlib(self):
looks like needs xfailing here

2017-05-10 11:26 UTC, jreback commented
can you add tests for feather-format as well (it should work I think, not sure)

2017-05-10 13:50 UTC, jorisvandenbossche approved these changes

2017-05-12 12:37 UTC, chris-b1 commented
@jreback - this should be good now, looks like most of the xfails will be fixed by #16301

2017-05-12 13:17 UTC, TomAugspurger commented
There was a failure in one job: https://travis-ci.org/pandas-dev/pandas/jobs/231516184#L2140 but that looks unrelated.

2017-05-12 13:30 UTC, merged

2017-05-12 13:30 UTC, jreback commented
thanks!