BUG: reshape fix for maybe_infer_to_datetimelike()
pandas-dev/pandas pull request #16395
Opened 2017-05-20 04:14 UTC by RobinFiveWords

- [x] closes #16362
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

2017-05-20 14:59 UTC, jreback commented
tests should *always* be included. generally I write them *first* to ensure that they are picking up the bug. you can push to this PR itself.

2017-05-24 04:51 UTC, RobinFiveWords commented
@jreback I might need some guidance...I might not have needed to touch this -- the branch had a new conflict, I imagine because of other merged PRs, but only with whatsnew. Now I'm not sure how to fix it back to a state where tests pass.

2017-05-24 12:29 UTC, jreback requested changes
rebase on master

```
git pull origin/master
git rebase -i origin/master
```

then when pushing
```
git push yourupstream yourbranch -f
```

2017-05-24 12:29 UTC, jreback commented on pandas/tests/dtypes/test_cast.py
> +
add the issue number here

2017-05-24 12:29 UTC, jreback commented on pandas/tests/dtypes/test_cast.py
> +        result = DataFrame(np.array([[NaT, 'a', 'b', 0],
use both examples from here:  https://github.com/pandas-dev/pandas/issues/16362#issuecomment-301581166

and assert the result to an expected result == 8

2017-05-24 12:30 UTC, jreback commented
pls add a whatsnew note in 0.20.2 (bug fixes, reshaping section)

2017-05-24 15:20 UTC, TomAugspurger commented
Does https://github.com/pandas-dev/pandas/commit/cd11b497608d216dbd4276ddc119f52dc0588a70 look like the full set of changes, aside from the whatsnew?

2017-05-24 15:33 UTC, TomAugspurger commented
It looks like you lost some changes, but you should be able to recover them with your git reflog, assuming you haven't cleared it manually. Or maybe even a `git reset --soft cd11b49`. If you ping me on gitter I can walk you through the recover steps.

2017-05-24 17:21 UTC, RobinFiveWords commented
@TomAugspurger thanks, didn't have much time today and thankfully this is such a small change so I just redid the changes. I did add one more test assertion this morning upon Jeff's recommendation, and that's included here as well.

2017-05-24 23:21 UTC, closed without merging

2017-05-24 23:21 UTC, jreback commented
thanks @RobinFiveWords