Error with .drop([]) on non-unique index
pandas-dev/pandas pull request #16428
Opened 2017-05-22 19:10 UTC by lloydkirk

Wraps the labels array in `_ensure_object`. The labels array is being cast to a float by default, causing the error raised in #16398.

 - [X] closes #16398 
 - [X] tests added / passed
 - [X] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

2017-05-22 19:14 UTC, lloydkirk commented
Where does the `whatsnew` entry go for this PR?

2017-05-22 19:15 UTC, TomAugspurger commented
This can be 0.20.1 since it's a bugfix

2017-05-22 19:20 UTC, lloydkirk commented
Done, plz let me know if you need anything else on my end

2017-05-22 22:36 UTC, jreback commented on doc/source/whatsnew/v0.20.2.txt
> +- Fix ``pd.drop([])`` for dataframes with non-unique indices (:issue:`16270`)
Bug in ``df.drop([])`` for DataFrame with non-unique indices

2017-05-23 00:33 UTC, jreback requested changes
pls add the test from the issue.

2017-05-23 19:30 UTC, TomAugspurger commented
@lloydkirk can you update with a test and fix the note in the whatsnew? The test can go in `pandas/tests/frame/test_axis_select_reindex.py`

2017-05-23 22:20 UTC, lloydkirk commented
Done, added a test to ``test_drop``, and to ``test_drop_names``, and fixed the whatsnew language

2017-05-24 23:23 UTC, jreback approved these changes

2017-05-24 23:24 UTC, merged

2017-05-24 23:24 UTC, jreback commented
thanks!