ENH: Add the decimal.Decimal type to infer_dtypes (#15690)
pandas-dev/pandas pull request #16426
Opened 2017-05-22 18:55 UTC by margaret

- [x] closes #15690 
 - [x] tests added / passed
 - [ ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

Currently figuring out the `git diff` step. I've set the upstream to the pandas-dev/pandas repo, but it's returning `fatal: bad revision 'upstream/master'.

2017-05-22 19:12 UTC, TomAugspurger commented on pandas/tests/dtypes/test_inference.py
> +        arr = np.array([Decimal(1), Decimal(2), Decimal(3)])
Can you add a comment with a link to the github issue? (#15690)

2017-05-22 19:24 UTC, TomAugspurger commented on pandas/tests/dtypes/test_inference.py
> +
Sorry, could you add a test with a mix of Decimal and non-decimal (like floats) and make sure that the return is `mixed`? Or search through and see if we have a test that already covers this. Other than that, this looks great.

2017-05-22 20:00 UTC, jorisvandenbossche commented
What I am wondering is what are potential consequences of this change. As there are quite some places in the codebase where we wheck if the inferred type is 'mixed', which could lead to potential changes in behaviour for objects with Decimals with this change. 
But don't know if those cases in the code would be relevant for Decimal objects.

2017-05-22 20:47 UTC, margaret commented
https://travis-ci.org/pandas-dev/pandas/jobs/234948322#L1392 failed one of the vector resizing tests (`Test for memory errors after internal vector reallocations`), but only on the Python 3.6 run. Any ideas on how that would be related to this? The parameter it failed on seems to just be int64.

2017-05-22 21:04 UTC, TomAugspurger commented
@jorisvandenbossche are there places where we explicitly check `== 'mixed'`? I haven't been able to find in just grepping (other than tests).

@margaret I'm not able to reproduce that. I'll restart that worker.

2017-05-22 21:09 UTC, jorisvandenbossche commented
According to my pycharm search, there are 13 occurrences of 'mixed' (usage as a string constant)

2017-05-22 22:16 UTC, jreback requested changes

2017-05-22 22:16 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- ``lib.infer_dtype`` now infers decimals. (:issue: `15690`)
``:func:`api.types.infer_dtype` ``

2017-05-22 22:16 UTC, jreback commented on pandas/_libs/src/inference.pyx
>      """
pls update the doc-string & add an example

2017-05-22 22:18 UTC, jreback commented
If the suite passes this is prob ok. The times when we infer are: 

1) construction (IOW we have something like ``Series([Decimal(..), Decimal(..)])``, but since ``decimal`` is an object dtype this won't matter (IOW, we don't specially handle it so it will fall thru as object anyhow).

2) indexing, with an *Index* of decimals. but again its the same as above, we don't do anything special. so I think ok for now.

2017-05-22 22:26 UTC, jorisvandenbossche commented
One further thought: would we like to call this `"mixed-decimal"` ? (or "object-decimal", but we seem to use 'mixed' as general indicator for object dtyped columns) 
This is more explicit in the fact that it is still object dtype (since we don't have a decimal dtype, nor do we plan to have one), but lets you specifically check for decimals, and also let's you more easily test for object dtypes in general (`"mixed" in inferred_dtype`, instead of `inferred_dtype` in ['decimal', 'mixed', 'mixed-..', ..]`)

2017-05-22 22:29 UTC, margaret commented on pandas/_libs/src/inference.pyx
>      """
https://github.com/pandas-dev/pandas/pull/16426/commits/6f158cb23cbfc51b35f9109a65e2929721f1e9a2

2017-05-22 22:47 UTC, jreback commented
i think decimal is just fine ; don't need to get more complicated

2017-05-23 00:18 UTC, jreback approved these changes

2017-05-23 00:18 UTC, jreback commented
lgtm. ping on green.

2017-05-23 10:56 UTC, merged

2017-05-23 10:56 UTC, jreback commented
thanks!