BUG: adding numpy errstate to dataframe/series broadcasting (GH16378)
pandas-dev/pandas pull request #16433
Opened 2017-05-22 19:48 UTC by AndrewArcher

TST: test for fix of GH16378

 - [x] closes GH16378
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [x] whatsnew entry

2017-05-22 20:18 UTC, chris-b1 commented
Looks like this may also close #16306 - could you add some confirming tests?

2017-05-22 20:23 UTC, chris-b1 commented on pandas/tests/frame/test_convert_to.py
> +        df.clip_lower(s, axis=0)
you can use `with tm.assert_produces_warning(None):` around this to assert no warning raised rather than reading stderr

2017-05-22 20:24 UTC, TomAugspurger commented on pandas/tests/frame/test_convert_to.py
> +        df.clip_lower(s, axis=0)
Could you write this as

```
with warnings.catch_warnings(record=True) as w:
    df.clip_lower(s, axis=0)

assert len(w) == 0
```

2017-05-22 20:24 UTC, TomAugspurger commented on pandas/tests/frame/test_convert_to.py
> +    def test_to_series(self, capsys):
Could you move this to `pandas/tests/frame/test_analytics.py`

2017-05-22 20:24 UTC, TomAugspurger commented on pandas/tests/frame/test_convert_to.py
> +        df.clip_lower(s, axis=0)
And you shouldnt need the `capsys` then (may have to import warnings).

2017-05-22 20:25 UTC, TomAugspurger commented on pandas/tests/frame/test_convert_to.py
> +        df.clip_lower(s, axis=0)
nvm, do what @chris-b1 said, that's shorter than catching and asserting 😄

2017-05-22 22:32 UTC, jreback commented on doc/source/whatsnew/v0.20.2.txt
> +- Bug when broadcasting dataframe to series silencing numpy warning messages in common use case (:issue:`16378`)
Silence numpy warnings when broadcasting DataFrame to Series with comparison ops.

2017-05-22 22:33 UTC, jreback commented on pandas/tests/frame/test_analytics.py
> +        df = DataFrame({'A': [np.nan, 2.0, np.nan]})
can you add the issue number as a comment here. (and a 1-line comment that this is a smoke test for numpy warnings)

2017-05-22 22:33 UTC, jreback approved these changes
minor doc comments. ping on green.

2017-05-22 22:34 UTC, jreback commented on doc/source/whatsnew/v0.20.2.txt
> +- Bug when broadcasting dataframe to series silencing numpy warning messages in common use case (:issue:`16378`)
add 16306 as well

2017-05-23 02:03 UTC, TomAugspurger commented
@AndrewArcher small lint failure here: https://travis-ci.org/pandas-dev/pandas/jobs/235018875#L1380 Mind removing the extra newline at the end of the file? Then we can get it merged.

2017-05-23 10:38 UTC, jreback requested changes

2017-05-23 10:38 UTC, jreback commented on pandas/tests/frame/test_analytics.py
> +            df.gt(s, axis=0)
``pd.DataFrame([0,0]).gt(pd.Series([0, np.nan]), axis=0)``

can you also add this test (the Series has the nan)

maybe just loop over these e.g.

```
for op in ['lt', 'le', 'ge', 'lt', 'eq', 'ne']:
     getattr(df, op)(s, axis=0)
```

2017-05-23 19:56 UTC, TomAugspurger commented on pandas/tests/frame/test_analytics.py
> +                getattr(df, op)(s_nan, axis=0)
Hah, now we'll have opposite problem.

```
pandas/tests/frame/test_analytics.py:2088:47: W292 no newline at end of file
```

Basically line 2088 should end with a newline, but there shouldn't be a line 2089 that's just a newline. Want me to push a fix for this, or do you want to take care of it?

2017-05-23 21:27 UTC, AndrewArcher commented on pandas/tests/frame/test_analytics.py
> +                getattr(df, op)(s_nan, axis=0)
I think I updated it correctly this time - if not, could you please push the correct fix?

2017-05-23 21:42 UTC, TomAugspurger commented on pandas/tests/frame/test_analytics.py
> +                getattr(df, op)(s_nan, axis=0)
I think that looks good.

2017-05-24 23:24 UTC, jreback approved these changes

2017-05-25 02:08 UTC, TomAugspurger commented
Merging (the Appveyor failure was fixed in master this morning).

Thanks @AndrewArcher!

2017-05-25 02:09 UTC, merged