BUG: Handle np strings in index.name in HDF #13492 (Work in Progress)
pandas-dev/pandas pull request #16444
Opened 2017-05-23 00:11 UTC by makmanalp

Work in progress!
 - [ ] closes #13492
 - [ ] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

2017-05-23 00:17 UTC, makmanalp commented
I found that pytables is returning a numpy.str_ as the index name for both indices. I don't think this has to do with how we write it, and pytables just chooses to write / read it that way. So we can handle this on the read side. There is some trickiness around numpy types in py2/3 and python string types in py2/3. So I decided to split the problem in two steps:

1) Handle converting numpy to python string types
2) Handle converting byte types to unicode codepoints.

The latter is done by _ensure_decoded, so for the former I added an _ensure_python_type. This way we should cover most situations.

2017-05-23 00:17 UTC, makmanalp commented
The numpy type situation is complicated across py2/3 and string types, but luckily they have a function that handles all that: https://github.com/numpy/numpy/blob/v1.12.1/numpy/core/numerictypes.py#L74

2017-05-23 00:23 UTC, jreback commented
as an additional test, try using a unicode index names as well :>

2017-05-23 00:25 UTC, jreback commented
```
In [14]: s = np.str_('foo')

In [15]: type(s)
Out[15]: numpy.str_

In [16]: type(s.item())
Out[16]: str

In [17]: type(str(s))
Out[17]: str
```

I prefer [17] for the conversion I think.

2017-05-23 00:29 UTC, makmanalp commented
@jreback so that was the original plan (and it works on my python 3.6 install) but the worry is that the behavior for what the heck happens with bytes vs strings (is it always going to return str_?) or py2/py3 (where in py2 np.str_ means bytes and in py3 np.str_ means unicode), and then how that interacts with .decode("utf-8") in the _ensure_decoded? If you're confident the above approach will work, more than happy to change.

Will add the test!

2017-05-23 00:32 UTC, jreback commented
@makmanalp 

So all string data is stored as bytes in PyTables. I think we encode to utf-8 (and decode the same). Though this is really just for table format. I dont' really remember what happens for fixed format for meta data. You might want to trace it and see.

2017-05-23 13:05 UTC, TomAugspurger commented
@makmanalp it seems like all the tests passed, so that's good.

Would you mind including the example from

```python
import pandas as pd
import numpy as np
import datetime

idx = pd.Index(pd.to_datetime([datetime.date(2000, 1, 1), datetime.date(2000, 1, 2)]), name='cols')
idx1 = pd.Index(pd.to_datetime([datetime.date(2010, 1, 1), datetime.date(2010, 1, 2)]), name='rows')
s = pd.DataFrame(np.arange(4).reshape(2,2), columns=idx, index=idx1)

with pd.HDFStore("test.h5", "w") as store:
    store.put("test", s, "fixed")

with pd.HDFStore("test.h5", "r") as store:
    s1 = store["test"]
```

and ensure that `type(s1.index.name)` is indeed a str. And maybe use a unicode name that isn't encodable as ASCII?

2017-05-23 13:10 UTC, makmanalp commented
@jreback OK, if it's bytes only then that should simplify things a bit.
@TomAugspurger will do!

2017-05-30 21:37 UTC, TomAugspurger commented
@makmanalp will you have a chance to update this in the next day or so? We're releasing 0.20.2 by the end of the week. Not a big deal to push.

2017-05-30 23:15 UTC, jreback requested changes
needs a test and a whatsnew entry.

2017-05-31 04:26 UTC, makmanalp commented
@TomAugspurger sorry for dropping the ball on this. I'm going to give it a shot tomorrow during the day. The test and whatsnew is easy, but double checking how things work in fixed format is a bit harder for me. Feel free to push it off the release if so.

2017-06-01 03:18 UTC, makmanalp commented
OK, oddly enough, in the test cases, I can't seem to use the ensure_clean_store() helper, perhaps there is something about the closing / opening of the file that changes things? I'm removing the bugfix that I made, and expecting the test to fail:

```python
    with ensure_clean_store(self.path) as store:
        store.put('frame', df, format='fixed')
        recons = store['frame']

        tm.assert_frame_equal(recons, df)

        assert type(df.index.name) == str
        assert type(df.columns.name) == str
        # Won't fail (surprising)

    with pd.HDFStore("test.h5", "w") as store:
        store.put("test", df, "fixed")

    with pd.HDFStore("test.h5", "r") as store:
        df2 = store["test"]
        assert type(df2.index.name) == str
        assert type(df2.columns.name) == str
        # Will fail! (which is what I want)
```

I thought of using `self._check_roundtrip` but then I don't have access to the dataframe to be able to assert the assertions about the name types. Any pointers on the right way to do this?

2017-06-01 15:43 UTC, makmanalp commented
OK so I fixed the issue with ensure_clean_store because I found ensure_clean_path. Re: picking a unicode index name for the test, how are we going to make this work for py2/py3 again? Do we want a `u"blah"` string? Do we need a `# coding=utf-8` on top of the file?

2017-06-01 15:57 UTC, makmanalp commented
Ah, OK, so I found the `compat` module and `u_safe` and `text_type`, will give a shot at those.

2017-06-01 15:57 UTC, TomAugspurger commented
I think the `# coding` is only required if you use non-ascii characters in the source.

2017-06-01 16:01 UTC, makmanalp commented
@TomAugspurger yeah - I've now realized we don't need to care about because I can use the u_safe thing helps because you can use the `\u05d0` style notation. Thank you!

2017-06-01 17:57 UTC, makmanalp commented
Just for posterity, conversation on numpy strings / bytestrings / unicode in numpy gitter channel:

```

Mehmet Ali "Mali" Akmanalp @makmanalp May 22 19:12
Hi, does anyone know the difference between numpy.str and numpy.string (i.e. numpy.bytes_) and how to handle them in different python versions?
I'm trying to do a pull request for pandas where pytables is creating a np.str_ object that we need to decode into a regular ol' string

Julian Taylor @juliantaylor May 23 04:52
np.str_ is the equivalent to python str and maps to bytes in python2 and unicode in python3
np.string is always bytes and should not be used
the only real string type numpy has is np.unicode
that works in both python2 and 3

Mehmet Ali "Mali" Akmanalp @makmanalp May 23 09:27
@juliantaylor and how do conversions within those numpy types and/or from those to python types work?
(and thank you for the clarification)
My current understanding is that .item() does the right thing in terms of numpy->python, regardless of python version

Julian Taylor @juliantaylor May 23 11:31
@makmanalp no, item will return bytes in python3, which happens to be string in python2
the 'S' dtype is flat out broken, if you need actual bytes you are better of using int8 arrays, if you need strings you need to use unicode
the 'S' type has no concept of encoding, so even putting encoded data into it is troublesome as it strips trailing nulls

```

2017-06-01 18:23 UTC, makmanalp commented
So I don't think the types converted / encoded / decoded at all for index names in fixed format, at least not within pandas:

https://github.com/pandas-dev/pandas/blob/fb47ee56d95ff1d5fcdff5dc589491c63a238bac/pandas/io/pytables.py#L2485

and also

https://github.com/pandas-dev/pandas/blob/fb47ee56d95ff1d5fcdff5dc589491c63a238bac/pandas/io/pytables.py#L2529

But I may not be understanding this code fully.

2017-06-01 19:06 UTC, TomAugspurger commented on pandas/tests/io/test_pytables.py
> +            assert type(df2.index.name) == str
And then replace `str` here and below with `compat.text_type`. But I would also add an assert that the exact string matches.

2017-06-01 19:06 UTC, TomAugspurger commented on pandas/tests/io/test_pytables.py
> +            df.to_hdf(path, 'df', format='table')
You can parametrize `format` I think

@pytest.mark.parametrized('format', ['table', 'fixed'])
def test_store_index_name_numpy_str(self, format):
    ...

```

2017-06-01 19:06 UTC, TomAugspurger commented on pandas/io/pytables.py
> +            name = _ensure_decoded(_ensure_python_type(node._v_attrs.name))
You shouldn't need the `_ensure_python_type` stuff then.

2017-06-01 19:13 UTC, TomAugspurger commented on pandas/io/pytables.py
> +            name = _ensure_decoded(_ensure_python_type(node._v_attrs.name))
I guess you can't just do this unconditionally, as the name could be something like `None` or the literal `10` (not a string). So it'll be something like

```python
name = node._v_attrs.name
if isinstance(name, compat.string_types):
    name = compat.text_type(name)
```

2017-06-01 19:38 UTC, makmanalp commented
Thanks a bunch @TomAugspurger! The latest push should handle all your comments correctly, and pass the 2.7 test this time!

2017-06-01 19:43 UTC, TomAugspurger commented on pandas/tests/io/test_pytables.py
> +            assert df2.index.name == u('rows\u05d0')
Oh, I guess this is unnecessary since you have the `assert_frame_equal` up above. Oh well.

2017-06-01 19:43 UTC, TomAugspurger approved these changes

2017-06-01 19:52 UTC, makmanalp commented on pandas/tests/io/test_pytables.py
> +            assert df2.index.name == u('rows\u05d0')
Fixed this too!

2017-06-01 20:53 UTC, makmanalp commented
(last push fixes a minor lint error that escaped me after the latest changes: `pandas/tests/io/test_pytables.py:2931:24: E128 continuation line under-indented for visual indent`)

2017-06-02 00:30 UTC, jreback commented on doc/source/whatsnew/v0.20.2.txt
> +- Bug where ``pd.read_hdf()`` returns numpy strings for index names (:issue:`13492`)
specify this is for ``format='fixed'``

2017-06-02 00:30 UTC, jreback commented on doc/source/whatsnew/v0.20.2.txt
> +- Bug where ``pd.read_hdf()`` returns numpy strings for index names (:issue:`13492`)
where numpy strings were returned, rather than python strings for a named Index.

2017-06-02 00:31 UTC, jreback commented on pandas/io/pytables.py
> +            if isinstance(name, compat.string_types):
write this as ``_ensure_str`` (like ``_ensure_decoded``) and use it here.

2017-06-02 00:32 UTC, jreback commented on pandas/io/pytables.py
> +            if isinstance(name, compat.string_types):
add a comment (and issue reference) of why this is needed

2017-06-02 00:33 UTC, jreback approved these changes
minor code change. ping on green.

2017-06-02 22:31 UTC, jreback commented
@makmanalp can you update

2017-06-04 00:59 UTC, TomAugspurger commented
Got it, merging on green and will cherry pick for 0.20.2;

2017-06-04 10:44 UTC, merged

2017-06-04 10:44 UTC, TomAugspurger commented
Thanks @makmanalp