BUG: Allow non-callable attributes in aggregate function. Fixes GH16405
pandas-dev/pandas pull request #16458
Opened 2017-05-23 16:07 UTC by pvomelveny

- [x ] closes #16405
 - [ ] tests added / passed
 - [x ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

2017-05-23 17:38 UTC, TomAugspurger commented
Can you add the test from the original issue here? It can go in `pandas/tests/frame/test_apply.py`

Also could use a release note in `doc/source/whatsnew/v0.20.2.txt`, under the bugfix section.

2017-05-23 21:16 UTC, pvomelveny commented
I may have gone a bit overboard with the tests...

2017-05-24 12:18 UTC, jreback requested changes

2017-05-24 12:18 UTC, jreback commented on pandas/core/base.py
> +        - try to find an attribute on ourselves
function (or attribute)

2017-05-24 12:18 UTC, jreback commented on doc/source/whatsnew/v0.20.2.txt
> +- Bug in ``DataFrame.agg`` and ``Series.agg`` with aggregating on non-callable attributes (:issue:`16404`)
I *think* this only affects ``.size``, so say that

2017-05-24 12:18 UTC, jreback commented on pandas/core/base.py
> +            # people may try to aggregate on a non-callable attribute
blank line

2017-05-24 12:18 UTC, jreback commented on pandas/tests/frame/test_apply.py
> +        assert_frame_equal(result1.reindex_like(expected),
you can pass ``check_like=True`` to do this reindex comparisons.

2017-05-24 12:18 UTC, jreback commented on pandas/tests/frame/test_apply.py
> +        # Just functional string arg is same as calling df.arg()
can you add a minimal tests to ``series/test_apply.py``

2017-05-24 12:18 UTC, jreback commented on pandas/tests/frame/test_apply.py
> +        # which we explicitly forbid
this actually should work, what are the args/kwargs that are actually there? (ithere *maybe* internal ones that need to be remove FYI, e.g. ``_level`` or something)

2017-05-24 18:40 UTC, pvomelveny commented on doc/source/whatsnew/v0.20.2.txt
> +- Bug in ``DataFrame.agg`` and ``Series.agg`` with aggregating on non-callable attributes (:issue:`16404`)
As it works right now, you really can use *any* attribute in the aggregation, so something like:
```python
In [20]: df
Out[20]:
     A    B     C
0  NaN  1.0   foo
1  2.0  NaN  None
2  3.0  3.0   bar

In [21]: df.agg({'A': ['count', 'size', 'name'],
    ...:         'B': ['count', 'size', 'name', 'data'],
    ...:         'C': 'size'})
    ...:
Out[21]:
         A                B    C
count    2                2  NaN
data   NaN  [1.0, nan, 3.0]  NaN
name     A                B  NaN
size     3                3  3.0
```
works. 

If it should only affect size, we could change the check in base.py to just see if the arg passed is `'size'`.

2017-05-25 17:49 UTC, pvomelveny commented on doc/source/whatsnew/v0.20.2.txt
> +- Bug in ``DataFrame.agg`` and ``Series.agg`` with aggregating on non-callable attributes (:issue:`16404`)
This one's not actually outdated. I just messed up the bug # and had to fix it. The question of this only affecting size is still open

2017-05-30 21:36 UTC, TomAugspurger commented
@jreback are you OK with this? I believe the discussion was whether we could have a simpler implementation by special-casing `'size'`?

2017-05-30 22:22 UTC, jreback commented
can't change size as it's already defined as a property (for numpy compat)

2017-05-30 23:08 UTC, jreback approved these changes
very small doc change. ping on green.

2017-05-30 23:08 UTC, jreback commented on doc/source/whatsnew/v0.20.2.txt
> +- Bug in ``DataFrame.agg`` and ``Series.agg`` with aggregating on non-callable attributes (:issue:`16405`)
``DataFrame.agg()`` and ``Series.agg()``

2017-05-30 23:08 UTC, jreback commented on pandas/tests/frame/test_apply.py
> +
can you add a comment of ``.size`` here (and how its a property of Series/DataFrame and hence we allow this)

2017-06-01 10:35 UTC, merged

2017-06-01 10:35 UTC, jreback commented
thanks!