Fix correct warning with c engine when skipping lines
pandas-dev/pandas pull request #16455
Opened 2017-05-23 14:40 UTC by pankajp

Fixed bug where c engine would not print warnings for lines
it skipped in case the skipped line had an inline comment.
Also, its accounting of number of fields in such lines would
be off by one.

 - [ ] closes #xxxx
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

2017-05-23 15:48 UTC, TomAugspurger requested changes
Thanks. Can you also add a release note in `doc/source/whatsnew/0.20.2.txt` in the bug fixes section.

2017-05-23 15:48 UTC, TomAugspurger commented on pandas/tests/io/parser/comment.py
> +    def test_comment_whitespace_delimited(self):
You can use the `tm.capture_stderr` decorator from `pandas/util/testing.py` so you don't have to do the patching yourself. See https://github.com/pandas-dev/pandas/blob/6614e266bca32771c761e904367eff10dd4c8979/pandas/tests/io/parser/test_textreader.py#L146 for an example.

2017-05-23 23:49 UTC, jreback commented
does this have an issue number?

2017-05-24 08:10 UTC, pankajp commented
@TomAugspurger I have added the whatsnew bug entry and replaced `sys.stderr` patching with `tm.capture_stderr`, and also moved the test to `CParserTests` since it is only applicable to the `c` engine.
The CI tests seem to fail on some pyarrow/feather code.

@jreback Added an issue for this: https://github.com/pandas-dev/pandas/issues/16472

2017-05-24 10:38 UTC, jreback commented
can you rebase on master, CI has been fixed

2017-05-24 12:10 UTC, jreback approved these changes
lgtm, minor comment.

2017-05-24 12:10 UTC, jreback commented on doc/source/whatsnew/v0.20.2.txt
> +- Bug in skipping error lines with inline comments in space delimited text files (:issue:`16472`)
something like this: Bug in ``pd.read_csv()`` when ``comment`` is passed in space deliminted text files.

2017-05-24 12:10 UTC, jreback commented
@gfyoung if you can have a look

2017-05-24 13:16 UTC, TomAugspurger approved these changes

2017-05-24 16:27 UTC, gfyoung commented
LGTM!

2017-05-24 17:36 UTC, merged

2017-05-24 17:36 UTC, TomAugspurger commented
Thanks @pankajp!