BUG: fixed wrong order of ordered labels in pd.cut()
pandas-dev/pandas pull request #16466
Opened 2017-05-23 22:51 UTC by economy

- [x] closes #16459 
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

Changes to how `cut` instantiates `Categorical` when a list of labels are passed to it, and the `test_cut_pass_labels` test for it. If labels are passed in as a `Categorical` already, behavior isn't altered at all, but if the user specifies a list of labels, the rank ordering of those labels is preserved in `cut`.

2017-05-23 23:36 UTC, jreback requested changes
can you add:

- a whatsnew note (0.20.2 reshaping bug fix)
- the test from the original issue

2017-05-23 23:40 UTC, economy commented
@jreback happy to do  that, can you tell me how/where to add the what's new, and what you're looking for in terms of the original test? all i know is it passes.

2017-05-23 23:42 UTC, jreback commented
doc/source/whatsnew/v0.20.2.txt

you copy the test from the original issue and assert that it is correct now (you construct the expected) and compare vs running ``pd.cut``. it should fail w/o this fix and pass with it.

2017-05-23 23:45 UTC, economy commented
Ok, the what's new is straightforward, in terms of the test, do you just want me to include the output in the original issue? or an actual test in `test_tile.py`? The test that was failing no longer fails.

2017-05-23 23:48 UTC, jreback commented
> in the original issue? or an actual test in test_tile.py? The test that was failing no longer fails.

that's exactly the point. the test should succeed now! and failed before the fix.

2017-05-23 23:54 UTC, economy commented
Pre-fix:
```
In [2]: labels = ['okay', 'good', 'bad']
In [3]: pd.cut([.2, .4, .6, 1, 2, 3, 5], 3, labels=labels)

Out [3]:
[okay, okay, okay, okay, good, good, bad]
Categories (3, object): [bad < good < okay]
In [50]:


```

Post-fix:
```
In [4]: labels = ['okay', 'good', 'bad']
In [5]: pd.cut([.2, .4, .6, 1, 2, 3, 5], 3, labels=labels)

Out [5]:
[okay, okay, okay, okay, good, good, bad]
Categories (3, object): [okay < good < bad]
```

```pytest reshape/test_tile.py
=========================================================================================== test session starts ============================================================================================
platform darwin -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /Users/economy/Documents/pycon-2017/pandas/pandas, inifile: setup.cfg
collected 35 items

reshape/test_tile.py ...................................

======================================================================================== 35 passed in 0.58 seconds =========================================================================================
```

2017-05-23 23:59 UTC, jreback commented
@economy so make a test out of that.

2017-05-23 23:59 UTC, economy commented
Gotcha, sorry for the confusion.

2017-05-24 12:24 UTC, jreback commented on doc/source/whatsnew/v0.20.2.txt
> +- Bug in ``pd.cut`` when ``labels`` are set (:issue:`16459`)
Bug in ``pd.cut`` does not preserve label ordering when ``labels`` are passed

2017-05-24 12:24 UTC, jreback commented on pandas/tests/reshape/test_tile.py
> +			  categories=labels,
this causes a lint error

2017-05-24 12:24 UTC, jreback approved these changes
lgtm. minor comments. rebase on master, ping when green.

2017-05-26 18:04 UTC, economy commented
@jreback finally had a chance to get to this. should be green now

2017-05-27 01:08 UTC, TomAugspurger commented
@economy looks like a conflict in the whatsnew file. Can you rebase?

2017-05-30 23:01 UTC, jreback approved these changes
minor doc comments.

2017-05-30 23:01 UTC, jreback commented on doc/source/whatsnew/v0.20.2.txt
> +- Bug in ``pd.cut`` when ``labels`` are set (:issue:`16459`)
maybe add incorrect ordering resulted

2017-05-30 23:01 UTC, jreback commented on pandas/tests/reshape/test_tile.py
> +        labels = ['Good', 'Medium', 'Bad']
add issue reference here

2017-06-01 10:57 UTC, closed without merging

2017-06-01 10:57 UTC, jreback commented
thanks!