Gh 14671
pandas-dev/pandas pull request #16460
Opened 2017-05-23 18:09 UTC by bpraggastis

- [ ] closes #14671
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] Bug fix: In parser.py added check that usecols option in read_csv raises an error if it contains strings not in the names option. 'test_raise_on_usecols_names_mismatch' added to tests/io/parser/usecols.py

2017-05-23 19:10 UTC, TomAugspurger commented
There will be some warnings from our style checker:

```
pandas/tests/io/parser/usecols.py:481:9: E266 too many leading '#' for block comment
pandas/tests/io/parser/usecols.py:483:45: E262 inline comment should start with '# '
pandas/tests/io/parser/usecols.py:484:32: E261 at least two spaces before inline comment
pandas/tests/io/parser/usecols.py:484:33: E262 inline comment should start with '# '
pandas/tests/io/parser/usecols.py:486:23: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:486:27: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:486:31: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:488:38: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:488:50: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:488:62: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:488:74: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:491:23: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:491:27: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:491:31: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:495:23: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:495:27: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:496:80: E501 line too long (91 > 79 characters)
pandas/tests/io/parser/usecols.py:502:38: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:502:50: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:502:62: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:502:74: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:506:80: E501 line too long (84 > 79 characters)
pandas/tests/io/parser/usecols.py:511:80: E501 line too long (84 > 79 characters)
pandas/tests/io/parser/usecols.py:516:9: E303 too many blank lines (2)
pandas/tests/io/parser/usecols.py:516:23: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:516:27: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:516:31: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:517:80: E501 line too long (91 > 79 characters)
pandas/tests/io/parser/usecols.py:518:80: E501 line too long (81 > 79 characters)
pandas/tests/io/parser/usecols.py:519:23: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:519:27: E231 missing whitespace after ','
pandas/tests/io/parser/usecols.py:520:80: E501 line too long (91 > 79 characters)
```

you can get the warnings with `flake8 pandas/tests/io/parser/usecols.py` (may have to `pip install flake8`)

Could you also add a release note to `doc/source/whatsnew/v0.20.2.txt` under the bug fixes seciton?

2017-05-24 12:33 UTC, jreback commented on pandas/io/parsers.py
> +            #gh-14671
@gfyoung is there a reason *some* of these checks for usecols are *outside* ``_evaluate_usecols``?

(e.g. the one after this one could be inside if ``self.names`` were passed)

2017-05-24 12:33 UTC, jreback commented on pandas/tests/io/parser/usecols.py
> +        # usecols = ['A','C']
commented out?

2017-05-24 12:34 UTC, jreback commented
can you add a whatsnew entry for 0.20.2 (IO section)

2017-05-24 16:22 UTC, gfyoung commented on pandas/tests/io/parser/usecols.py
> +        # usecols = ['A','C']
Yes, those failures are related to #16469.  Should put a TODO there I think.

2017-05-24 16:24 UTC, gfyoung commented on pandas/tests/io/parser/usecols.py
> +        msg = 'Usecols do not match names'  ## from parsers.py CParserWrapper()
Condition the message on `self.engine` i.e.:
~~~
msg = <first-message> if self.engine == 'c' else <second-message>
~~~
That way you don't need that massive regex (and can remove the `re` import)

2017-05-24 16:25 UTC, gfyoung commented on pandas/io/parsers.py
> +            #gh-14671
`_evaluate_usecols` is purely for evaluation.  I don't think it was meant to have validation like this inside its implementation as well.

2017-05-30 21:34 UTC, TomAugspurger commented
@bpraggastis do you have time to update this today or tomorrow? We're releasing 0.20.2 by the end of the week.

2017-05-30 23:03 UTC, jreback commented on pandas/io/parsers.py
> +            #gh-14671
k that's fine, maybe think about making this an actual ``_validate_usecols`` (if it reduces code and is more clear).

2017-05-30 23:04 UTC, jreback requested changes
if you can address @gfyoung changes we can get this in .

2017-05-30 23:04 UTC, jreback submitted a review, later dismissed
pls add a whatsnew note as well (0.20.2) in IO for bug fixes.

2017-05-31 16:52 UTC, gfyoung commented
@TomAugspurger @jreback : If @bpraggastis does not respond by tomorrow, just ping me.  I can pull this branch down and finish it off.

2017-06-02 09:55 UTC, jreback commented
@gfyoung if you are interested

2017-06-02 17:40 UTC, bpraggastis commented
@TomAugspurger @jreback Just now had a chance to check back in. Have you fixed all of the things you wanted changed or should I review your comments and respond?

2017-06-02 22:32 UTC, jreback commented on pandas/tests/io/parser/usecols.py
> +        # usecols = ['A','C']
@bpraggastis I think add a TODO here with the issue above.

2017-06-02 22:32 UTC, jreback commented on pandas/tests/io/parser/usecols.py
> +        msg = 'Usecols do not match names'  ## from parsers.py CParserWrapper()
do this one as well

2017-06-02 22:33 UTC, jreback commented
@bpraggastis couple of comments, pls do those
add a whatsnew entry for 0.20.2
needs to pass CI

2017-06-04 01:16 UTC, TomAugspurger commented
I pushed an update addressing the comments.

2017-06-04 10:47 UTC, merged

2017-06-04 15:55 UTC, bpraggastis commented
@TomAugspurger Thank you for closing this.

2017-06-04 16:00 UTC, TomAugspurger commented
Thank you for the contribution @bpraggastis!

2017-06-04 17:51 UTC, bpraggastis commented
@TomAugspurger Thank You for the assistance! I sent you an email with a couple of questions. Looking forward to hearing from you.