ENH: Add to_latex() method to Series (#16180)
pandas-dev/pandas pull request #16465
Opened 2017-05-23 22:41 UTC by bsweger

This changeset adds _repr_latex_ to the Series class and moves
the to_latex() method from the DataFrame class to the NDFrame
class.

 - [ ] closes #16180
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

2017-05-24 21:51 UTC, TomAugspurger requested changes
Sorry I missed this yesterday. A couple of comments.

Could you also add some tests for `Series.to_latex` directly (keep the one testing `_repr_latex_` though. They can go in `pandas/tests/io/formats/test_to_latex.py`

Thanks!

2017-05-24 21:51 UTC, TomAugspurger commented on pandas/core/generic.py
> +        # Get defaults from the pandas config
I think you'll need to start this with

```python
if self.ndim == 1:
    self = self.to_frame()
```

then the rest of it should be ok.

2017-05-24 21:51 UTC, TomAugspurger commented on pandas/core/series.py
> +    def _repr_latex_(self):
Can you actually remove this and move the `_repr_latex_` from `pandas/core/frame.py` and to `NDFrame` in `pandas/core/generic.py`?

2017-05-26 03:52 UTC, bsweger commented on pandas/core/generic.py
> +        # Get defaults from the pandas config
Thanks for this suggestion--doing the check here rather than invoking `to_frame()` in the Series _repr_latex method makes a lot of sense.

2017-05-26 03:56 UTC, bsweger commented
@TomAugspurger Thanks for the review! Moved things around per your suggestions and added a test explicitly for `Series.to_latex()`. It's a very simple test to make sure the function works; wasn't sure if the entire suite of dataframe-related latex test options was worth repeating for a series. Happy to add more if you think it's helpful.

2017-05-26 11:46 UTC, TomAugspurger commented
@bsweger this looks fantastic. I'm pushing a tiny doc change that I forgot to ask for (adding a note that it was added to series in 0.20.2), then merging.

2017-05-26 11:46 UTC, TomAugspurger approved these changes

2017-05-26 11:47 UTC, merged