ENH: inconsistent naming convention for read_excel column selection (#4988)
pandas-dev/pandas pull request #16488
Opened 2017-05-24 21:58 UTC by abarber4gh

- update API to use ‘usecols’ instead of ‘parse_cols’.  still functionally the same as ‘parse_col’,
- added test cases for ‘usecols’, added assert_produces_warning(FutureWarning) to other test
cases that use ‘parse_cols’.
- refactor column use column parsing to only occur once per sheet.
- updated whats new with deprecated parse_col argument and other enhancements
to usecols functionality.
- update documentation to show new usecols functionality in read_excel().

 - [X] closes #4988 
 - [X] tests added / passed
 - [X] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [X] whatsnew entry
 - [X] packers.* BENCHMARKS NOT SIGNIFICANTLY CHANGED.

2017-05-24 22:47 UTC, chris-b1 commented
FYI, just discussing a bug related to usecols #15316, might be easiest to work that change into your refactoring, or can be separate, cc @stanleyguan

2017-05-24 22:53 UTC, jreback requested changes

2017-05-24 22:53 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- :func:`read_excel` now allows a column character list (E.G. ['A', 'C', 'D']) with the ``usecols`` parameter (:issue:`4988`).
we are listed this in deprecations so this is unecessary

2017-05-24 22:53 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- :func:`read_excel()` has deprecated ``parse_cols`` in favor of ``usecols`` for consistency with other read_ functions (:issue:`4988`).
``pd.read_*`` functions

2017-05-24 22:53 UTC, jreback commented on pandas/io/excel.py
> +    .. deprecated:: 0.21.0
hmm, didn't know sphinx had this deprecated tag. @TomAugspurger @jorisvandenbossche should maybe change other deprecations to use this if it looks nice.

2017-05-24 22:53 UTC, jreback commented on pandas/tests/io/test_excel.py
> +        df2 = self.get_exceldf('test1', 'Sheet2', skiprows=[1], index_col=0,
so you need to change ALL tests to use the new one (usecols), except for a single test to actually hit the deprecation.

2017-05-24 22:53 UTC, jreback commented on pandas/tests/io/test_excel.py
> +
are these new tests?

2017-05-24 23:29 UTC, abarber4gh commented on pandas/io/excel.py
> +    .. deprecated:: 0.21.0
appears as:
> **parse_cols** _: int or list, default None_
> _Deprecated since version 0.21.0:_ Use _usecols_ instead

2017-05-24 23:53 UTC, TomAugspurger commented on pandas/io/excel.py
> +    .. deprecated:: 0.21.0
http://pandas-docs.github.io/pandas-docs-travis/generated/pandas.read_excel.html Has an example from sheetname. Looks ok

2017-05-25 21:06 UTC, jreback requested changes

2017-05-25 21:06 UTC, jreback commented on pandas/io/excel.py
> +    .. deprecated:: 0.21.0
@TomAugspurger if we like this (and lgtm), let's make an issue to updated all DEPRECATED in codebase with this directive

2017-05-25 21:06 UTC, jreback commented on pandas/io/excel.py
> -                return reduce(lambda s, a: s * 26 + ord(a) - ord('A') + 1,
is there a reason you are changing this code? does this involve the deprecation somehow? if you are cleaning/fixing, pls do in another PR.

2017-05-25 21:06 UTC, jreback commented on pandas/tests/io/test_excel.py
> -    def test_parse_cols_str(self):
leave the original tests structure (sure you can change the name to conform), but don't change the tests (in THIS PR).

2017-05-25 21:33 UTC, abarber4gh commented on pandas/io/excel.py
> -                return reduce(lambda s, a: s * 26 + ord(a) - ord('A') + 1,
code changed to allow passing list of strings, similar to other `read_*` functions, and keep the `read_excel` "superpower" to pass a string that is parsed as mentioned in the original issue (#4988, point 3).

2017-05-25 21:47 UTC, abarber4gh commented on pandas/tests/io/test_excel.py
> +
yes, new tests for the new functionality.

2017-05-25 22:13 UTC, jreback commented on pandas/io/excel.py
> -                return reduce(lambda s, a: s * 26 + ord(a) - ord('A') + 1,
and that's fine, but needs to be in a separate PR from the deprecation change.

2017-05-25 22:29 UTC, abarber4gh commented on pandas/io/excel.py
> -                return reduce(lambda s, a: s * 26 + ord(a) - ord('A') + 1,
ok, opened #16510 for this functionality.  will re-submit with only the argument change (parse_cols -> usecols).

2017-05-26 14:27 UTC, TomAugspurger commented
@abarber4gh can you rebase, now that the excel tests are running?

2017-06-10 05:24 UTC, abarber4gh commented on pandas/tests/io/test_excel.py
> -    def test_parse_cols_str(self):
tests are back to original but with changed function & kwarg names.

2017-07-19 10:36 UTC, jreback commented
can you rebase / update according to comments

2017-09-10 14:49 UTC, jreback commented
closing as stale. pls ping to reopen if you want to continue.

2017-09-10 14:49 UTC, closed without merging