DOC: added string processing comparison with SAS
pandas-dev/pandas pull request #16497
Opened 2017-05-25 17:12 UTC by natethedrummer

#13229 

Added string processing section to comparison_with_sas DOC.  Used info from http://blog.dominodatalab.com/using-r-and-python-for-common-sas-functions.  

This completes half of the issue.  Working on R next.

2017-05-25 20:01 UTC, chris-b1 requested changes
One comment, overall this looks great!

2017-05-25 20:01 UTC, chris-b1 commented on doc/source/comparison_with_sas.rst
> +.. code-block:: none
Can you make all the python code segments ipython blocks (like elsewhere in the doc) so the output will show?

2017-05-25 21:08 UTC, jreback requested changes

2017-05-25 21:08 UTC, jreback commented on doc/source/comparison_with_sas.rst
can you add a directive here (and other sub-sections if you can), for references e.g. ``_compare_with_sas.string``

2017-08-07 12:56 UTC, merged

2017-08-07 12:57 UTC, jorisvandenbossche commented
@natethedrummer Thanks!