optimized median func when bottleneck not present
pandas-dev/pandas pull request #16509
Opened 2017-05-25 22:10 UTC by rohanp

Uses np.nanmedian to compute median instead of internal algos.median when bottleneck is not present/turned off. Has order of magnitude performance benefits

`df = pd.DataFrame(np.random.randn(10000, 2), columns=list('AB'))`

Before
```
>>> pd.set_option('use_bottleneck', False)
>>> %timeit df.median(1)
318 ms ± 8.56 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

>>> %timeit pd.Series(np.nanmedian(df.values, axis=1), index=df.index)
1.83 ms ± 123 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

>>> pd.set_option('use_bottleneck', True)
>>> %timeit df.median(1)
239 µs ± 2.23 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

After
```
>>> pd.set_option('use_bottleneck', False)
>>> %timeit df.median(1)
1.89 ms ± 53.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

>>> pd.set_option('use_bottleneck', True)
>>> %timeit df.median(1)
227 µs ± 11 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

2017-05-25 22:11 UTC, jreback commented on pandas/core/nanops.py
> -    def get_median(x):
and this will break in numpy < 1.9, you need to do this conditionally.

2017-05-25 22:11 UTC, jreback commented
needs an asv (run with and w/o bottleneck)

2017-05-25 22:36 UTC, rohanp commented
Do i need to run all the tests or can i get away with a subset?

2017-05-25 22:37 UTC, rohanp commented
Also do I have to manually turn bottleneck on and off for the tests?

2017-05-25 22:39 UTC, jreback commented
> Also do I have to manually turn bottleneck on and off for the tests?

have 2 tests, 1 with it forced on, 1 with forced off

> Do i need to run all the tests or can i get away with a subset?

just the median tests :>

2017-05-25 22:40 UTC, jreback commented
actually I don't think bottleneck is in our asv config. (separate issue is it should be)

2017-05-25 23:13 UTC, rohanp commented
> just the median tests :\>

does that just entail `test_nanops.py`?

2017-05-26 12:37 UTC, TomAugspurger commented
@rohanp `asv continuous -f 1.1 upstream/master HEAD -b median` should work. See http://pandas.pydata.org/pandas-docs/stable/contributing.html#running-the-performance-test-suite

2017-05-27 20:55 UTC, rohanp commented
I don't understand why the tests are failing. How do I see the test cases that failed?

2017-05-27 22:35 UTC, jreback commented
click on the red x

2017-05-29 02:24 UTC, rohanp commented
I'm not quite sure what you mean. I figured out how to see the details of the tests that failed; for example on circleci I can see

```
self = <pandas.tests.test_nanops.TestnanopsDataFrame object at 0x7f67d2d65c88>

    def test_nanmedian(self):
        with warnings.catch_warnings(record=True):
            self.check_funs(nanops.nanmedian, np.median, allow_complex=False,
                            allow_str=False, allow_date=False,
>                           allow_tdelta=True, allow_obj='convert')

pandas/tests/test_nanops.py:374: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pandas/tests/test_nanops.py:245: in check_funs
    **kwargs)
pandas/tests/test_nanops.py:234: in check_fun
    targarnanval, **kwargs)
pandas/tests/test_nanops.py:193: in check_fun_data
    check_dtype=check_dtype)
pandas/tests/test_nanops.py:146: in check_results
    tm.assert_almost_equal(targ, res, check_dtype=check_dtype)
pandas/util/testing.py:234: in assert_almost_equal
    **kwargs)
pandas/_libs/testing.pyx:59: in pandas._libs.testing.assert_almost_equal (pandas/_libs/testing.c:4156)
    cpdef assert_almost_equal(a, b,
pandas/_libs/testing.pyx:173: in pandas._libs.testing.assert_almost_equal (pandas/_libs/testing.c:3274)
    raise_assert_detail(obj, msg, lobj, robj)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

obj = 'numpy array', message = 'numpy array values are different (20.0 %)'
left = '[[nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan]]'
right = '[[0.0511871111488, -0.458724351947, -0.0208572588354, 0.00471620824214, -0.487450340243], [0.254176310551, -0.0309721..., -0.2722898607, 0.174928469595], [-0.431481894512, 0.245270844279, 0.140055994353, -0.0727601005076, 0.238682362073]]'
```

But what I do not understand is how to find the input that caused the test to fail. I checked the `test_nanops.py` file and while it has the tests it does not seem to have the test cases.

2017-05-30 15:15 UTC, TomAugspurger commented
@rohanp these tests have several layers of indirection (to allow more code reuse). I would try `pytest pandsa/tests/test_nanops.py -k test_nanmedian --pdb` to drop into a debugger on failure so you can inspect what's going on. But the basic idea is `test_nanmedian` -> `check_funs` -> `check_fun` -> `check_fun_data` -> `check_results`, which is failing for one of the input array.

The actual arrays will be something like `self.arr_float` or `arr_float_nan` and are accessed with `getattr`.

2017-06-10 19:08 UTC, jreback commented
can you rebase and update?

2017-07-07 10:37 UTC, jreback commented
can you rebase and update

2017-07-19 10:35 UTC, jreback commented
can you rebase / update according to comments

2017-08-08 07:05 UTC, pep8speaks commented
Hello @rohanp! Thanks for updating the PR.

 - In the file [`pandas/core/nanops.py`](https://github.com/pandas-dev/pandas/blob/fa0bb249b04d3d9b3a9b88cb107602dd0074dc3d/pandas/core/nanops.py), following are the PEP8 issues :

> [Line 335:5](https://github.com/pandas-dev/pandas/blob/fa0bb249b04d3d9b3a9b88cb107602dd0074dc3d/pandas/core/nanops.py#L335): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 337:80](https://github.com/pandas-dev/pandas/blob/fa0bb249b04d3d9b3a9b88cb107602dd0074dc3d/pandas/core/nanops.py#L337): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 338:5](https://github.com/pandas-dev/pandas/blob/fa0bb249b04d3d9b3a9b88cb107602dd0074dc3d/pandas/core/nanops.py#L338): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 339:5](https://github.com/pandas-dev/pandas/blob/fa0bb249b04d3d9b3a9b88cb107602dd0074dc3d/pandas/core/nanops.py#L339): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 380:80](https://github.com/pandas-dev/pandas/blob/fa0bb249b04d3d9b3a9b88cb107602dd0074dc3d/pandas/core/nanops.py#L380): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

2017-08-08 07:15 UTC, rohanp commented
Hi, sorry for the delay. I think I figured out the bug. Thanks @TomAugspurger for the debugging command. How do I rebase and update?

2017-08-08 07:41 UTC, jorisvandenbossche commented
@rohanp you can do the following (assuming that pandas-dev/pandas remote repo is called 'upstream')

```
git fetch upstream
git checkout rohanp
git merge upstream/master # after this you can fix merge conflicts, and do 'git commit' to continue
git push origin rohanp
```

2017-08-08 07:45 UTC, jorisvandenbossche commented on pandas/core/nanops.py
> +
you can remove this blank line? (in general, please try to avoid such changes on lines that you are not changing for this PR)

2017-08-08 07:45 UTC, jorisvandenbossche commented on pandas/core/nanops.py
> +        return np.median(values, axis=axis)
Is this special case needed? As `np.nanmedian` is almost as fast as `np.median`, also when there are no NaNs.

2017-08-08 11:07 UTC, jreback requested changes
need a whatsnew note in performance section.

2017-08-08 11:07 UTC, jreback commented on pandas/core/nanops.py
>      values, mask, dtype, dtype_max = _get_values(values, skipna)
use ``_np_version_under1p19`` which are already defined

2017-08-08 11:07 UTC, jreback commented on pandas/core/nanops.py
> +        return np.median(values, axis=axis)
this is not needed

2017-08-08 11:07 UTC, jreback commented on pandas/core/nanops.py
>      values, mask, dtype, dtype_max = _get_values(values, skipna)
then define

```
if _np_under_version1p19:
       agg1d = get_median
       aggaxis = lambda values, axis: np.apply_along_axis(get_median, axis, values)
else:
      agg1d = np.nanmedian
      aggaxis = lambda values, axis: np.nanmedian(values, axis)
```

then the code is almost the same as before, just replace with ``agg1d`` and ``aggaxis``

2017-08-09 11:31 UTC, jorisvandenbossche reviewed
update looks good, please have a look at the remaining comment

Further:
- can you add a whatsnew note? (in performance improvements section)

2017-08-09 11:31 UTC, jorisvandenbossche commented on pandas/core/nanops.py
> +        return np.median(values, axis=axis)
@rohanp Can you deal with this comment? (remove or give some explanation on why you think it is needed)

BTW, `isnull` was recently be renamed to `isna` in this file, that is the reason all tests are failing now.

2017-08-09 11:31 UTC, jorisvandenbossche commented on pandas/tests/test_nanops.py
> +                    #    import pdb; pdb.set_trace()
leftover to remove

2017-08-09 15:02 UTC, rohanp commented
Hi @jorisvandenbossche, my changes are causing the tests to fail. I'm still looking into why. I'll remove that once I get to the bottom of what the problem is.

2017-08-10 08:35 UTC, jorisvandenbossche commented
> my changes are causing the tests to fail. I'm still looking into why

see my comment above, isnull was recently be renamed to isna in this file, that is the reason all tests are failing now (but, we also asked to remove the part that uses isnull (or explain why it is needed))

2017-08-12 18:00 UTC, jreback requested changes
couple of things to remove. pls add a whatsnew note (in perf). ping on green.

2017-08-12 18:00 UTC, jreback commented on pandas/core/nanops.py
> +    #if False and not skipna and isna(np.sum(values)):
remove

2017-08-12 18:02 UTC, rohanp commented
Hi, I had put that in because the tests were failing and I thought that would fix it (but apparently not). The tests are still failing without it.

2017-08-14 10:39 UTC, jreback commented on pandas/tests/test_nanops.py
> +
revert this file; the whitespace is causing an issue

2017-08-15 10:37 UTC, jreback commented
needs a rebase. ping on green.

2017-08-16 12:38 UTC, jorisvandenbossche commented
@rohanp you have some failing tests

2017-08-17 04:23 UTC, rohanp commented
I don't understand—all the errors seem to be in tests unrelated to nanmedian.

```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

self = <pandas.tests.series.test_operators.TestSeriesOperators object at 0x113abe278>
test_input = 0    foo
1    bar
2    baz
dtype: object, error_type = <class 'TypeError'>

    @pytest.mark.parametrize(
        "test_input,error_type",
        [
            (pd.Series([]), ValueError),
    
            # For strings, or any Series with dtype 'O'
            (pd.Series(['foo', 'bar', 'baz']), TypeError),
            (pd.Series([(1,), (2,)]), TypeError),
    
            # For mixed data types
            (
                pd.Series(['foo', 'foo', 'bar', 'bar', None, np.nan, 'baz']),
                TypeError
            ),
        ]
    )
    def test_assert_argminmax_raises(self, test_input, error_type):
        """
            Cases where ``Series.argmax`` and related should raise an exception
            """
        with pytest.raises(error_type):
>           test_input.argmin()

pandas/tests/series/test_operators.py:1882: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pandas/core/series.py:1310: in idxmin
    i = nanops.nanargmin(_values_from_object(self), skipna=skipna)
pandas/core/nanops.py:513: in nanargmin
    isfinite=True)
pandas/core/nanops.py:212: in _get_values
    mask = _isfinite(values)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

values = array(['foo', 'bar', 'baz'], dtype=object)

    def _isfinite(values):
        if is_datetime_or_timedelta_dtype(values):
            return isna(values)
        if (is_complex_dtype(values) or is_float_dtype(values) or
                is_integer_dtype(values) or is_bool_dtype(values)):
            return ~np.isfinite(values)
>       return ~np.isfinite(values.astype('float64'))
E       ValueError: could not convert string to float: 'baz'

pandas/core/nanops.py:255: ValueError
```

2017-08-17 10:09 UTC, jreback commented
you need to rebase on master and build the extensions, this was a recent change.

2017-08-18 05:40 UTC, rohanp commented
The same tests seem to be failing

2017-08-18 08:49 UTC, jorisvandenbossche commented
@rohanp There went something wrong when merging upstream master (when solving the conflicts, you removed some code). See the diff now includes changes in the argmin/argmax methods. If you undo those changes, the tests will pass.

2017-08-19 05:18 UTC, rohanp commented
@jorisvandenbossche thank you for that catch! I've now double checked that nothing in the diff has changed except for the contents of `nanmedian`, and the tests are passing on my local computer, but some of the same errors are popping up on the CI tests. 

pandas/util/testing.py:1105: AssertionError
___________________________ TestPanel4d.test_median ____________________________

self = <pandas.tests.test_panel4d.TestPanel4d object at 0x7f3358785e50>

    def test_median(self):
        def wrapper(x):
            if isna(x).any():
                return np.nan
            return np.median(x)
    
>       self._check_stat_op('median', wrapper)

pandas/tests/test_panel4d.py:54:

2017-08-19 17:24 UTC, jreback commented on pandas/core/nanops.py
> +    if not skipna:
why are you adding this?

2017-08-19 17:35 UTC, rohanp commented on pandas/core/nanops.py
> +    if not skipna:
The tests compare nanmedian to numpy's median function. If this special case were not there, this function would return a non-null result for input with null values and skipna turned off. Here is a debug log demonstrating this: https://gist.github.com/rohanp/1082ad5a5e199f6b1cb8ade965c4519f

2017-08-19 17:43 UTC, jreback commented on pandas/core/nanops.py
> +    if not skipna:
so fix the test to do the correct comparison

2017-08-19 17:46 UTC, rohanp commented on pandas/core/nanops.py
> +    if not skipna:
Isn't the desired behavior for nanmedian to be like median when skipna is turned off though? If not, then what is the skipna flag supposed to do?

2017-08-20 13:59 UTC, jreback commented on pandas/core/nanops.py
> +    if not skipna:
yes, so use the ``skipna`` flag as a switch when generating which function to use.

2017-08-22 07:29 UTC, rohanp commented
It looks like the tests are passing on when I run `pytest pandas` locally as well as on AppVeyor, but failing on Travis CI and CircleCI.

Could someone please explain how I can replicate the environment for CircleCI on my local computer so that I can debug? I tried looking in the [ci folder](https://github.com/rohanp/pandas/tree/master/ci) but am not sure what I should be looking for (a conda environment.yml?)

2017-08-22 07:35 UTC, gfyoung commented
The Travis failures are style-checking errors, which you can see here:

https://travis-ci.org/pandas-dev/pandas/jobs/267057585#L1937

Address those lint issues, and you should get a green-light from Travis.

The Circle failures are coming from Python 2.7.  Are you using Python 3.x to test your changes?  If so, then you should create a Python 2.x environment (either with `virtualenv` or `conda`) in which you should install your changes and test.

2017-08-23 11:25 UTC, jorisvandenbossche commented
@rohanp The `skipna_switch` feels very complex to me. It is not possible to achieve the same by doing some switch within the `nanmedian` function?

You still have failing median tests on Circle CI. Are you able to reproduce that locally?

2017-08-23 12:05 UTC, jreback commented
@rohanp yeah I would go back to the previous iteration. This needs to use the version detection as well (you had previously)

2017-08-23 12:11 UTC, jorisvandenbossche commented
> This needs to use the version detection as well (you had previously)

why? it was for numpy < 1.9, which we just removed?

2017-08-23 12:15 UTC, rohanp commented
I am not able to reproduce the Circle CI bugs locally, even after making a Python 2.7 environment. Here is the conda environment I am using:

```
apipkg                    1.4                       <pip>
dateutil                  2.4.1                    py27_0  
execnet                   1.4.1                     <pip>
joblib                    0.11                      <pip>
lxml                      3.8.0                     <pip>
mkl                       2017.0.3                      0  
numpy                     1.13.1                   py27_0  
openssl                   1.0.2k                        2  
pip                       9.0.1                    py27_1  
py                        1.4.34                    <pip>
pytest                    3.2.1                     <pip>
pytest-forked             0.2                       <pip>
pytest-xdist              1.20.0                    <pip>
python                    2.7.13                        0  
pytz                      2017.2                   py27_0  
readline                  6.2                           2  
setuptools                27.2.0                   py27_0  
six                       1.10.0                   py27_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
zlib                      1.2.8                         3 
```

2017-09-22 13:51 UTC, jreback commented
can you rebase / update

2017-10-28 00:37 UTC, jreback commented
pls rebase

2017-11-12 19:46 UTC, jreback commented
can you rebase

2017-12-11 00:24 UTC, jreback commented
master
```
In [1]:  pd.set_option('use_bottleneck', False)

In [2]: np.random.seed(1234); df = pd.DataFrame(np.random.randn(100000, 4))

In [3]: %timeit df.median(1)
2.86 s ± 14.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

PR
```
In [1]:  pd.set_option('use_bottleneck', False)

In [2]: np.random.seed(1234); df = pd.DataFrame(np.random.randn(100000, 4))

In [3]: %timeit df.median(1)
21.7 ms ± 470 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

2018-01-21 18:42 UTC, jreback approved these changes

2018-01-22 11:11 UTC, merged