Add inplace support for rename_axis
pandas-dev/pandas pull request #16505
Opened 2017-05-25 21:14 UTC by HndrkMkt

- [x] closes #15704 
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``

2017-05-26 12:41 UTC, jreback requested changes

2017-05-26 12:41 UTC, jreback commented on pandas/core/generic.py
> +            whether to modify `self` directly or return a copy
versionadded tag

2017-05-26 12:41 UTC, jreback commented on pandas/core/generic.py
> +        renamed = self if inplace else self.copy(deep=True)
deep=True is the default so can remove that

2017-05-31 20:43 UTC, HndrkMkt commented on pandas/core/generic.py
> +            whether to modify `self` directly or return a copy
Which version should I specify?

2017-06-01 09:52 UTC, HndrkMkt commented on pandas/core/generic.py
> +            whether to modify `self` directly or return a copy
Specified 0.20.2

2017-06-01 10:29 UTC, jreback approved these changes

2017-06-01 10:29 UTC, jreback commented on pandas/core/generic.py
> +            whether to modify `self` directly or return a copy
move to 0.21.0

2017-06-01 10:29 UTC, jreback commented on pandas/tests/frame/test_alter_axes.py
> +        renamed = self.frame.rename_axis('foo')
add the issue number as a comment

2017-06-01 10:29 UTC, jreback commented on pandas/tests/frame/test_alter_axes.py
> +    def test_rename_axis(self):
test_rename_axis_inplace

2017-06-01 10:29 UTC, jreback commented on pandas/tests/frame/test_alter_axes.py
> +        assert_frame_equal(renamed, renamed2)
make this read

``assert_frame_equal(result, expected)`` (rename things)

2017-06-01 20:40 UTC, jorisvandenbossche commented on pandas/core/generic.py
> +        renamed = self if inplace else self.copy()
Is there a reason you removed the `deep=True` ?

2017-06-01 21:33 UTC, HndrkMkt commented on pandas/core/generic.py
> +        renamed = self if inplace else self.copy()
It's the default and can thus be removed (as of @jreback's request that disappeared after my rebase).
https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py#L3523

2017-06-01 21:35 UTC, jorisvandenbossche commented on pandas/core/generic.py
> +        renamed = self if inplace else self.copy()
OK, perfect! (I looked for a comment about it, but didn't find one :-))

2017-06-01 21:35 UTC, jorisvandenbossche approved these changes

2017-06-01 22:21 UTC, jreback requested changes
pls add a whatnews note in other enhancements for 0.21.0. ping on green.

2017-06-01 22:22 UTC, jreback commented on pandas/tests/frame/test_alter_axes.py
> +    def test_rename_axis_inplace(self):
can you also add a similar test in series/test_alter_axes.py

and tests this with axis=1 as well.

2017-06-10 17:29 UTC, HndrkMkt commented on doc/source/whatsnew/v0.21.0.txt
> +- ``Series.rename_axis()`` and ``DataFrame.rename_axis()`` with ``inplace=True`` now return None while renaming the axis inplace. (:issue:`15704`)
@jreback - added

2017-06-13 23:06 UTC, jreback approved these changes

2017-06-13 23:07 UTC, merged

2017-06-13 23:07 UTC, jreback commented
thanks @HndrkMkt