DOC: added string processing comparison with R
pandas-dev/pandas pull request #16502
Opened 2017-05-25 19:06 UTC by natethedrummer

#13229

Added string processing section to comparison_with_r DOC. Used info from http://blog.dominodatalab.com/using-r-and-python-for-common-sas-functions.

This completes the issue.

2017-05-25 21:00 UTC, jreback requested changes

2017-05-25 21:00 UTC, jreback commented on doc/source/comparison_with_r.rst
add a section tag here, like: ``_compare_with_r.string`` (actually if you can add them some of the sub-sections would be great). you put right *after* the sub-section label.

2017-05-25 21:00 UTC, jreback commented on doc/source/comparison_with_r.rst
> +.. code-block:: none
is there a R highlter?

2017-05-25 21:00 UTC, jreback commented on doc/source/comparison_with_r.rst
> +.. code-block:: none
-> ipython:: python (and for all running pandas code)

2017-05-25 21:00 UTC, jreback commented on doc/source/comparison_with_r.rst
> +   nchar(trimws(as.character(df$color)))
would be nice to show output here (IOW run the R code and show the output too if you can)

2017-05-25 21:08 UTC, TomAugspurger commented on doc/source/comparison_with_r.rst
> +.. code-block:: none
http://pygments.org/docs/lexers/#lexers-for-the-r-s-languages

`r` or `rconsole` should work.

2017-05-25 21:09 UTC, jreback commented on doc/source/comparison_with_r.rst
> +.. code-block:: none
yeah I realize that these produce the same output, so we don't actually show the output (I think) elsewhere, so maybe that is ok (though obviously the code formatting would be nice)

2017-05-26 14:29 UTC, TomAugspurger commented on doc/source/comparison_with_r.rst
If you aren't familiar with sphinx, you need to start the line with a `..` http://www.sphinx-doc.org/en/stable/markup/inline.html#cross-referencing-arbitrary-locations

2017-07-19 10:35 UTC, jreback commented
@gfyoung can you review

2017-07-19 15:10 UTC, gfyoung commented on doc/source/comparison_with_r.rst
> +R indexes are 1 based.
Simpler: "Keep in mind that Python 0-indexes, whereas R 1-indexes"

2017-07-19 15:10 UTC, gfyoung commented on doc/source/comparison_with_r.rst
> +indexes are zero-based.
Slightly simpler: "Keep in mind that Python 0-indexes"

2017-07-19 15:12 UTC, gfyoung commented on doc/source/comparison_with_r.rst
> +.. code-block:: none
Same comment <a href="https://github.com/pandas-dev/pandas/pull/16502#discussion_r118583818">above</a>

2017-09-10 14:50 UTC, jreback commented
can you rebase / update

2017-09-23 20:11 UTC, jreback commented
can you update according to comments

2017-11-10 20:18 UTC, jreback commented
closing as stale. if you'd like to continue working, pls ping.

2017-11-10 20:18 UTC, closed without merging