Issue16503
pandas-dev/pandas pull request #16514
Opened 2017-05-26 15:58 UTC by Kiv

HDFStore __unicode__ now only returns file path info. New info() method has the previous behavior of __unicode__.

 - [x] closes #16503
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [x] whatsnew entry

2017-05-26 19:08 UTC, jreback commented on pandas/io/pytables.py
> +        """return detailed information on the store"""
add a versionadded tag.

2017-05-26 19:08 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- :class:`pandas.HDFStore`'s string representation is now faster and less detailed. For the previous behavior, use ``pandas.HDFStore.info()``. (:issue:`16503`).
move to API breaking changes

2017-05-26 19:08 UTC, jreback commented on pandas/io/pytables.py
> +        if self.is_open:
add this to api.rst

2017-05-26 19:09 UTC, jreback approved these changes
lgtm, with some minor comment.

2017-05-26 19:10 UTC, jreback commented
ping when fixed / green.

2017-05-28 10:09 UTC, gfyoung commented
1) Got a small linting error in `pytables.py` (hence the Travis failure)

2) Can you provide some timing info in the PR given that this is a performance change?

2017-05-28 19:17 UTC, Kiv commented
@jreback I think this is ready to go?

2017-05-28 19:39 UTC, jreback requested changes

2017-05-28 19:39 UTC, jreback commented on pandas/tests/io/test_pytables.py
> +            assert 'CLOSED' not in store.info()
so you should also test str(store) a bit (u changed all of these to .info())

2017-05-28 21:34 UTC, Kiv commented on pandas/tests/io/test_pytables.py
> +            assert 'CLOSED' not in store.info()
I added a test that str(store) prints the filename, is that what you mean? There's not much behavior in there anymore to test...

2017-05-28 21:41 UTC, jreback commented on pandas/tests/io/test_pytables.py
> +            assert 'CLOSED' not in store.info()
point to it it's not clear where it is

2017-05-28 22:28 UTC, Kiv commented on pandas/tests/io/test_pytables.py
> +            assert 'CLOSED' not in store.info()
https://github.com/pandas-dev/pandas/pull/16514/commits/6faa5a66c005343c71b1ce623bb3ff89affd72b1#diff-5066b062c892df33c29b37a8c1c75f75R422

2017-05-29 22:20 UTC, gfyoung commented
@Kiv Some timing info in the PR would be useful for future reference.  Plus a benchmark test would be good here.

2017-06-01 22:32 UTC, jreback approved these changes

2017-06-01 22:33 UTC, jreback commented
@Kiv lgtm. if you would add an asv would be great (you can use your original example, just not as long, maybe 20 nodes or something would be fine).

2017-06-10 19:09 UTC, jreback commented
can you add an asv?

2017-06-11 11:14 UTC, closed without merging

2017-06-11 11:35 UTC, Kiv commented
My git branch got out of date and I don't know how to update it properly. New version with ASV bench is here:

https://github.com/pandas-dev/pandas/pull/16666

2017-06-11 15:17 UTC, jreback commented
in the future see: http://pandas.pydata.org/pandas-docs/stable/contributing.html#combining-commits

you just needed to do:

```
git rebase -i upstream/master
git push yourremove yourbranch -f
```