TST: Skip test_database_uri_string if pg8000 importable
pandas-dev/pandas pull request #16528
Opened 2017-05-28 20:02 UTC by neirbowj

- [x] closes #16527
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

2017-05-29 16:04 UTC, jreback commented on pandas/tests/io/test_sql.py
>          # in sqlalchemy.create_engine -> test passing of this error to user
you would need to do

```
pg8000 = pytest.pyimportskip('pg8000')  # noqa
```

you need to explicitly install this though in the requirements-2.7.pip (and other ones if needed)

cc @jorisvandenbossche

2017-05-29 16:06 UTC, jreback requested changes
actually how did this come up? reading the comments suggest that we *don't* want to have this driver installed at all (we are testing an error when sqlalchemy is installed but not a specific driver).

2017-05-29 16:24 UTC, jreback commented on pandas/tests/io/test_sql.py
>          # in sqlalchemy.create_engine -> test passing of this error to user
@neirbowj ahh I see what you posted on the issue. ok then your fix is fine (just need the noqa), and put an explanation of what is going on here.

2017-05-31 23:12 UTC, jreback approved these changes

2017-05-31 23:12 UTC, jreback commented
@jorisvandenbossche ok?

2017-06-01 19:50 UTC, TomAugspurger commented
This looks good, thanks.

2017-06-01 19:50 UTC, merged

2017-06-01 20:00 UTC, jorisvandenbossche commented
Yes, perfect! Thanks @neirbowj