bug fix #16524
pandas-dev/pandas pull request #16557
Opened 2017-05-31 18:08 UTC by preddy5

Patch to bug fix #16524

2017-05-31 18:11 UTC, preddy5 commented
@jreback this fixes the issue, could you review the PR and let me know if am doing it wrong.

2017-05-31 23:08 UTC, jreback commented
pls add tests. in fact you want to write the tests first to make sure that they fail, then your fix makes it pass. also add a whatsnew entry (0.20.2) is fine.

2017-06-01 18:01 UTC, TomAugspurger commented on pandas/tests/series/test_dtypes.py
> +        expected = Categorical(['a', 'b', 'c'])
I think you can mak this `expected = Series(['a', 'b', 'c'], dtype='category')`

and then you can use `tm.assert_series_equal(categorical_series, expected)`.

2017-06-02 05:11 UTC, preddy5 commented
@TomAugspurger  can you retrigger the travis build?

2017-06-03 07:55 UTC, preddy5 commented
could you retrigger circleci build as well please. Thank you.

2017-06-05 09:19 UTC, preddy5 commented
@jreback @TomAugspurger Could you review the PR please, Thank you.

2017-06-05 10:30 UTC, jreback requested changes

2017-06-05 10:30 UTC, jreback commented on doc/source/whatsnew/v0.20.2.txt
> +- Bug in ``Series`` with dtype='category' (:issue:`16524`)
Bug in ``Series`` construction with ``dtype='category'``

2017-06-05 10:30 UTC, jreback commented on pandas/tests/series/test_dtypes.py
> +        series = Series(['a', 'b', 'c'])
add comment for the issue number

2017-06-05 10:30 UTC, jreback commented on pandas/tests/series/test_dtypes.py
> +        categorical_series = Series(series, dtype='category')
result =

2017-06-05 10:30 UTC, jreback commented on pandas/tests/series/test_dtypes.py
> +        tm.assert_series_equal(categorical_series, expected)
categorical_series -> result

2017-06-05 10:30 UTC, jreback commented on pandas/core/categorical.py
> +    def __init__(self, values, categories=None, ordered=False, fastpath=False,
this fix should not be here.

instead in core/internals.py/Block/_astype.py

``raise_one_error`` can be a named argument in the signature and not passed to the constructor

2017-06-05 12:24 UTC, preddy5 commented
@jreback I have made the changes according to your comments.

2017-06-06 14:43 UTC, preddy5 commented
@jreback hey I have made changes according to your previous comments, could you review the changes once. Thank You.

2017-06-07 21:32 UTC, TomAugspurger commented
@preddy5 I rebased and moved the release note to 0.20.3 (releasing in a couple weeks).

I'll let Jeff comment on the changes, but I think we're good.

2017-06-08 12:04 UTC, jreback commented on doc/source/whatsnew/v0.20.3.txt
> +- Bug in ``Series`` with ``dtype='category'`` (:issue:`16524`)
be a bit more descriptive.

``Bug in Series construction when passing type=category``

2017-06-08 12:05 UTC, jreback approved these changes
tiny change. ping on green.

2017-06-09 15:51 UTC, merged

2017-06-09 15:51 UTC, jorisvandenbossche commented
@preddy5 Thanks!