BUG: IntervalIndex is_non_overlapping_monotonic is incorrect when endpoints are closed on both sides
pandas-dev/pandas pull request #16588
Opened 2017-06-02 23:20 UTC by alysivji

- [x] closes #16560
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

2017-06-05 10:16 UTC, jreback requested changes
some changes. add a whatsnew note. 0.21.0 conversion bug fixes

2017-06-05 10:16 UTC, jreback commented on pandas/core/indexes/interval.py
> +        else:
don't use the else here

add a comment on these cases (left/right).

neighter case? (short circuit to False)

2017-06-05 10:16 UTC, jreback commented on pandas/tests/indexes/test_interval.py
> +        assert index.is_non_overlapping_monotonic == True
use is True

2017-06-05 10:16 UTC, jreback commented on pandas/tests/indexes/test_interval.py
> +        assert index.is_non_overlapping_monotonic == False
use is False

2017-06-09 22:53 UTC, alysivji commented on pandas/core/indexes/interval.py
> +        else:
Working on this now. Why would the neither case short circuit to False? Can't we have intervals [(0, 1), (1, 2)] where it is non-overlapping and also cases where it is overlapping [(0, 1), (.5, 3)]

Thanks!

2017-06-11 16:36 UTC, jreback commented on pandas/core/indexes/interval.py
> +        else:
this is checking monotonicity as well. so you can do the same for neither.

2017-06-11 19:41 UTC, alysivji commented
Fixed the issues from the review, except for changing ```==``` to ```is``` in the asserts. Using ```is``` resulted in assert errors so I kept it the way it was originally.

Added additional tests and updated the whatsnew section in the docs. Thanks.

2017-09-09 05:43 UTC, jschendel commented
ping @jreback : This can be closed, as the issue was resolved by #17238

2017-09-09 07:18 UTC, gfyoung commented
@jschendel : Confirmed and closing.

2017-09-09 07:18 UTC, closed without merging