SparseSeries accepts scipy.sparse.spmatrix in constructor
pandas-dev/pandas pull request #16617
Opened 2017-06-06 20:22 UTC by kernc

- [X] closes #15634
 - [X] tests added / passed
 - [X] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [X] whatsnew entry

2017-06-06 22:21 UTC, jreback requested changes
just a quick look. this is probably going to be tricky to make work.

2017-06-06 22:21 UTC, jreback commented on doc/source/whatsnew/v0.20.2.txt
> +- ``SparseSeries`` and ``SparseArray`` now support 1d ``scipy.sparse.spmatrix`` in constructor. Additionally, ``SparseDataFrame`` can be assigned columns of ``scipy.sparse.spmatrix``; see :ref:`here
will be for 0.21.0

2017-06-06 22:21 UTC, jreback commented on pandas/core/sparse/frame.py
> +        super().__setitem__(key, value)
use the fully qualified call

2017-06-06 22:21 UTC, jreback commented on pandas/core/sparse/series.py
> +        unstack it, then use .to_coo() on the resulting SparseDataFrame.
use the deprecated sphinx directive (I think we are changing these all over)

2017-06-06 22:21 UTC, jreback commented on pandas/core/sparse/series.py
> +        SparseSeries constructor, and 2d into SparseDataFrame constructor.
same

2017-06-06 23:48 UTC, kernc commented
> this is probably going to be tricky to make work.

Why do you think so? I does seem to work for the moment. 😃

2017-06-08 10:55 UTC, jreback requested changes
looks pretty good. a couple of comments.

2017-06-08 10:55 UTC, jreback commented on doc/source/sparse.rst
> +Below interface is deprecated.
say that this is deprecated in 0.21.0

2017-06-08 10:55 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- ``SparseSeries`` and ``SparseArray`` now support 1d ``scipy.sparse.spmatrix`` in constructor.
in the constructor

2017-06-08 10:55 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +  Additionally, ``SparseDataFrame`` can be assigned columns of ``scipy.sparse.spmatrix``;
make this 2nd sentence a separate bullet point (you can use same issue on both of them, or 2nd one should be the PR number maybe)

2017-06-08 10:55 UTC, jreback commented on pandas/core/sparse/frame.py
> +                value = list(value.tocsc().T)
does this materialize?

2017-06-08 10:55 UTC, jreback commented on pandas/tests/sparse/test_frame.py
> +
this comparision on the scipy side is fine, but also let's compare with assert_sparse_series/frame_equal

2017-06-08 10:55 UTC, jreback commented on pandas/tests/sparse/test_frame.py
> +        idx = np.zeros(sdf.shape[0], dtype=bool)
can you test with ``.loc/.iloc`` as well (might already be another issue about this, if not and its too complicated for here, then create a new issue)

2017-07-19 10:32 UTC, jreback commented
can you rebase / update

2017-09-10 14:48 UTC, jreback commented
@kernc if you have time can you rebase / update

2017-09-10 17:11 UTC, kernc commented
For some reason (probably `assert_raises` in `test_setitem_spmatrix()`), I had a while ago decided to first implement `setitem` on `SparseSeries` that I have 80% done waiting in a feature branch somewhere. If you insist, I can push this first, however.

2017-09-10 17:21 UTC, jreback commented
oh we can do the other first 
was just looking thru open prs 

what was that number?

2017-10-04 16:45 UTC, kernc commented
Right, it's https://github.com/pandas-dev/pandas/pull/17785.

2018-01-21 18:20 UTC, jreback commented
closing as stale. if you want to continue working, pls ping.

2018-01-21 18:20 UTC, closed without merging