BUG: TimedeltaIndex raising ValueError when slice indexing (#16637)
pandas-dev/pandas pull request #16638
Opened 2017-06-08 13:48 UTC by jdeschenes

Before accepting this Pull request is there any other kind of usage of loc that might fail using deltatimeindex that I am not aware of? I could take some time to fix it once and for all.

closes #16637

 - [ x ] closes #16637
 - [ x ] tests added / passed
 - [ x ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ x ] whatsnew entry

2017-06-08 13:58 UTC, jreback commented
https://github.com/pandas-dev/pandas/issues?q=is%3Aopen+is%3Aissue+label%3ATimedelta+label%3AIndexing

are the only timedelta / indexing issues AFAICT (aside from new  one)

2017-06-08 13:59 UTC, jreback commented on pandas/tests/indexing/test_timedelta.py
> +
just make sure test is near other slicing testsing (may not actually be many).

2017-06-08 14:00 UTC, jreback commented
lgtm (just a comment to check location of test). ping on green.

2017-06-08 18:05 UTC, jorisvandenbossche commented on pandas/tests/indexing/test_timedelta.py
> +    def test_slice_indexing(self):
this is not slice indexing, but list-indexing with another index, if I am correct ? 
If so, I would update the name (and also whatsnew file)

2017-06-08 18:05 UTC, jorisvandenbossche commented on pandas/tests/indexing/test_timedelta.py
> +            result = df.assign(x=df.mask(cond, 10).astype(df['x'].dtype))
Is this change related to the PR?

2017-06-08 18:57 UTC, jdeschenes commented on pandas/tests/indexing/test_timedelta.py
> +            result = df.assign(x=df.mask(cond, 10).astype(df['x'].dtype))
Not at all. The circle CI unit test fails on a 32 bit machine.

2017-06-08 18:58 UTC, jdeschenes commented on pandas/tests/indexing/test_timedelta.py
> +    def test_slice_indexing(self):
It was meant to convey that you take a slice off the index.

2017-06-08 19:28 UTC, jdeschenes commented on pandas/tests/indexing/test_timedelta.py
> +            result = df.assign(x=df.mask(cond, 10).astype(df['x'].dtype))
It still fails even with that attempted fix. Travis-CI builds is giving me error entirely unrelated to the change I have done.

2017-06-09 10:11 UTC, jreback commented on pandas/tests/indexing/test_timedelta.py
> +    def test_slice_indexing(self):
slice is actual slicing; here you are passing a boolean mask that is the same shape (and aligned) with the input); mark this as a separate case

2017-06-09 14:33 UTC, jreback commented
do u have a repo for isnull or is_timeselta64_dtype raising?

2017-06-09 14:38 UTC, jdeschenes commented
Yeah... I am not sure about this change for the is_timedelta64_dtype. On one hand the behavior to me is bogus(Either a value is of a type or it's not). On the other hand, other projects may rely on this behavior(Why? I have no idea). I ran the test against the pandas suite and nothing broke.

I can make the change locally in get_loc, but I would rather fix the issue directly in the function. Let me know what you think.

2017-06-09 14:40 UTC, jdeschenes commented on pandas/tests/indexing/test_timedelta.py
> +    def test_slice_indexing(self):
Hi, in the new case we are not passing a boolean mask. Would you agree if I renamed the test to `test_list_like_indexing`?

2017-06-09 14:45 UTC, jorisvandenbossche commented on pandas/tests/indexing/test_timedelta.py
> +    def test_slice_indexing(self):
yep, that is better

2017-06-09 14:47 UTC, jreback commented on pandas/core/dtypes/common.py
> +    except ValueError:
this is fine
but need tests that hit this

2017-06-09 19:06 UTC, jdeschenes commented
@jreback @jorisvandenbossche Both failures are unrelated to the code I changed. I think it's ready to be merged at this point.

2017-06-09 22:50 UTC, jreback commented on pandas/tests/indexing/test_timedelta.py
> +
might be slightly more clear as a parametrized test

e.g.

```
@pytest.mark.parametrize("indexer, exp", [(0, ....), (slice(4, 8), ...), ([3, 5], ...)]
def test_list_like(self, indexer, exp):
    ....
```

2017-06-09 22:50 UTC, jreback commented on pandas/tests/dtypes/test_common.py
> +    assert not com.is_timedelta64_dtype("0 days 00:00:00")
didn't you have 2 cases that trigger the exception? if so pls add the other one.

2017-06-09 22:51 UTC, jreback commented on doc/source/whatsnew/v0.20.3.txt
> +- Bug in ``TimedeltaIndex`` raising a ``ValueError`` when slice indexing with ``loc`` (:issue:`16637`)
Bug in a DataFrame/Series with a TimedeltaIndex when slice indexing

2017-06-09 22:52 UTC, jreback commented
lgtm. pls rebase and push again (had some ci failures unrelated).

2017-06-09 23:00 UTC, jdeschenes commented on pandas/tests/indexing/test_timedelta.py
> +
Ok, I am not familiar with this... I will take a look.

2017-06-09 23:08 UTC, jreback commented
http://pandas.pydata.org/pandas-docs/stable/contributing.html#using-pytest

2017-06-09 23:10 UTC, jdeschenes commented on pandas/tests/dtypes/test_common.py
> +    assert not com.is_timedelta64_dtype("0 days 00:00:00")
No that I am aware of. There is a separate issue I think were isnull would trigger an exception in the get_loc function. I don't see how that condition could be hit in the future.

2017-06-09 23:24 UTC, jdeschenes commented
Hi,

I have noticed another issue closely related to this.

```python
df.loc[[0, 3], 'x'] = 20
```

This will fail with the ValueError. Instead, it should do `KeyError: 'None of [[0, 3]] are in the [index]'`

I will take a second look a bit later and see if I can fix this.

2017-06-09 23:30 UTC, jreback commented
you can address that other error in another PR (or here) up 2 u

2017-06-10 00:42 UTC, jdeschenes commented
I Will do it in a separate PR

On Jun 9, 2017 7:30 PM, "Jeff Reback" <notifications@github.com> wrote:

> you can address that other error in another PR (or here) up 2 u
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/16638#issuecomment-307523934>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AJfOkHsSqoNiRUy1nTRZw-_h-wRaAgUyks5sCdWhgaJpZM4N0GMz>
> .
>

2017-06-10 01:37 UTC, jreback commented
@jdeschenes ok great. if you can create an issue would be great.

FYI travis is fixed, working on circle now. pytest-xdist new version broke some things.

2017-06-30 20:48 UTC, jreback requested changes
if you can add a few tests on the is_timedelta64_dtype (in tests/dtypes/test_common.py)

otherwise lgtm.

2017-06-30 20:48 UTC, jreback commented on doc/source/whatsnew/v0.20.3.txt
> +- Bug in a DataFrame/Series with a TimedeltaIndex when slice indexing (:issue:`16637`)
use double-backticks on TimedeltaIndex

2017-07-03 13:45 UTC, TomAugspurger commented
@jdeschenes can you update? (some linting failures too I believe)

2017-07-03 15:09 UTC, jdeschenes commented
I have added the backticks to the what's new.

For the test, I have added an extra case. I can more if you want, if you have a better idea of what you want to see there, let me know.

2017-07-03 17:23 UTC, TomAugspurger commented
@jdeschenes that's what failed this build: https://travis-ci.org/pandas-dev/pandas/jobs/249668871#L1779

2017-07-04 14:20 UTC, jreback commented
can you rebase

2017-07-05 14:50 UTC, jdeschenes commented
Let me know if you need anything else!

2017-07-06 12:23 UTC, jreback approved these changes

2017-07-06 12:23 UTC, merged

2017-07-06 12:23 UTC, jreback commented
thanks!