Read excel nrows
pandas-dev/pandas pull request #16672
Opened 2017-06-11 22:21 UTC by alysivji

- [x] closes #16645
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [x] whatsnew entry

2017-06-11 23:08 UTC, gfyoung commented on doc/source/whatsnew/v0.21.0.txt
> +- ``pd.read_excel()`` has a ``nrows`` parameter (:issue:`16645`)
How about:

`pd.read_excel()` has gained the `nrows` parameter (...)

2017-06-11 23:09 UTC, jreback commented on pandas/io/excel.py
> +               skip_footer=0, index_col=None, names=None, parse_cols=None,
we normally don't like to shuffle parameters around in kwargs. Please align the ordering of these params as much as possible with how read_csv does it (obviously only include the current parameters).

2017-06-11 23:11 UTC, jreback commented on pandas/tests/io/test_excel.py
> +        with pytest.raises(ValueError):
@gfyoung don't we have an issue about ``nrows`` validation in the parser?

2017-06-11 23:11 UTC, jreback commented on pandas/tests/io/test_excel.py
> +        tm.assert_frame_equal(actual, expected)
try to pull *more* rows than exist in the file as well.

2017-06-11 23:14 UTC, gfyoung commented on pandas/io/parsers.py
> +            nrows = _validate_integer('nrows', nrows)
I think this is unnecessary.  This already gets validated the moment you call `read_excel`.

2017-06-11 23:15 UTC, gfyoung commented on pandas/tests/io/test_excel.py
> +        with pytest.raises(ValueError):
1) We have an entire test suite for this in `common.py` (under `io/parsers`)

2) This already gets validated.  Thus, this test is somewhat unnecessary.

2017-06-11 23:22 UTC, gfyoung commented on pandas/tests/io/test_excel.py
> +        with pytest.raises(ValueError):
@alysivji : Put this as a separate test, and use `tm.assert_raises_regex` to check the specific error message raised in the `ValueError` (we want it to be that validation failed).

2017-06-11 23:28 UTC, alysivji commented on pandas/io/parsers.py
> +            nrows = _validate_integer('nrows', nrows)
I originally didn't have this line there, but then I was getting the following error:
```TypeError: '>=' not supported between instances of 'int' and 'str'``` vs
```ValueError: 'nrows' must be an integer >=0```

2017-06-11 23:32 UTC, alysivji commented on pandas/io/excel.py
> +               skip_footer=0, index_col=None, names=None, parse_cols=None,
Sure, not a problem. I was using read_csv as a guide and saw that ```nrows``` was directly after ```skiprows```, hence the change.

I will go ahead and line up the read_excel kwargs as close as possible to the read_csv kwargs. I see 3or4 out of order with just a quick glance.

2017-06-11 23:40 UTC, jreback commented on pandas/io/excel.py
> +               skip_footer=0, index_col=None, names=None, parse_cols=None,
ok great. prob need a slightly expanded whatsnew note to tell about this

2017-06-13 02:14 UTC, alysivji commented on pandas/io/excel.py
> +               skip_footer=0, index_col=None, names=None, parse_cols=None,
I rearranged the kwargs and also updated docstrings to match parameter order (one of the things that always bugs me). Should I also update all internal function kwargs in ```excel.py``` to match the external API?

I'm adding the following note to the Other Enhancements section (just wanted to make sure it was the right spot...):
```- Rearranged the order of keyword arguments in :func:`read_excel()` to align with :func:`read_csv()` ```

Thanks!

2017-06-14 10:37 UTC, jreback requested changes

2017-06-14 10:37 UTC, jreback commented on pandas/io/excel.py
> +    Number of rows to parse
versionadded 0.21.0 tag

2017-06-14 10:37 UTC, jreback commented on pandas/io/excel.py
> +               skip_footer=0, index_col=None, names=None, parse_cols=None,
yes I would have the internal API match the external

2017-06-14 10:37 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- ``pd.read_excel()`` has a ``nrows`` parameter (:issue:`16645`)
you can make another entry (with this PR number), in api_breaking section that the kwargs are re-aranged to match pd.read_csv

use ``:func:`read_excel` ``

2017-06-14 10:37 UTC, jreback commented on pandas/io/parsers.py
> +            nrows = _validate_integer('nrows', nrows)
yes this change should be done in the parser itself. See if you can come up with an example that ONLY used pd.read_csv directly.

2017-06-14 13:23 UTC, alysivji commented on pandas/io/parsers.py
> +            nrows = _validate_integer('nrows', nrows)
Where should I put this test? There are a bunch in `tests/io/parser', but nothing for read_csv directly.

2017-07-19 10:31 UTC, jreback commented
can you rebase/update

2017-07-19 12:52 UTC, pep8speaks commented
Hello @alysivji! Thanks for updating the PR.

 - In the file [`pandas/io/excel.py`](https://github.com/pandas-dev/pandas/blob/f1a6740208ecf8f292aa18c43faf13abf96de592/pandas/io/excel.py), following are the PEP8 issues :

> [Line 333:58](https://github.com/pandas-dev/pandas/blob/f1a6740208ecf8f292aa18c43faf13abf96de592/pandas/io/excel.py#L333): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

 - In the file [`pandas/io/parsers.py`](https://github.com/pandas-dev/pandas/blob/f1a6740208ecf8f292aa18c43faf13abf96de592/pandas/io/parsers.py), following are the PEP8 issues :

> [Line 1002:1](https://github.com/pandas-dev/pandas/blob/f1a6740208ecf8f292aa18c43faf13abf96de592/pandas/io/parsers.py#L1002): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2017-09-10 14:49 UTC, jreback commented
can you rebase / update

2017-09-11 01:32 UTC, alysivji commented
Sure, I got some time this week. Will take a look at it.

2017-09-23 20:10 UTC, jreback commented
pls rebase

2017-11-10 20:18 UTC, jreback commented
closing as stale. if you'd like to continue, pls ping.

2017-11-10 20:18 UTC, closed without merging

2017-11-26 18:33 UTC, alysivji commented
I got some time. Picked this back up. Sent another PR (18507)

Thanks.