BUG: fix infer frequency for business daily
pandas-dev/pandas pull request #16683
Opened 2017-06-12 13:32 UTC by AdamGleave

Closes #16624 

Had to update a couple of tests, test_timedelta and test_business_daily, which appear to rely on the old incorrect behaviour. Added a new regression test, test_business_daily_look_alike, for the bug.

Modest performance impact: for 50,000-long business daily index, infer_freq goes from 2.54 ms to 3.91 ms. There should be no performance impact in most cases for non-business daily index, as the initial day_deltas check will throw out most of these cases.

2017-06-12 13:42 UTC, jreback requested changes
can you add an asv for this?

2017-06-12 13:42 UTC, jreback commented on pandas/tseries/frequencies.py
> +    WORKING_DAY_SHIFTS = set([(0, 1), (1, 2), (2, 3), (3, 4), (4, 0)])
what is this for?

2017-06-12 13:53 UTC, AdamGleave commented on pandas/tseries/frequencies.py
> +    WORKING_DAY_SHIFTS = set([(0, 1), (1, 2), (2, 3), (3, 4), (4, 0)])
Unused code from a previous iteration, removed in latest commit

2017-06-12 16:17 UTC, AdamGleave commented
ASV report 
[attached](https://github.com/pandas-dev/pandas/files/1068792/asv_report.txt), indicates that no benchmarks are significantly changed.

2017-06-30 18:54 UTC, TomAugspurger commented
@jreback are you OK with the changes here? LGTM on a quick skim.

2017-06-30 19:05 UTC, jreback approved these changes
small test comment
might be worth it to add an asv

2017-06-30 19:05 UTC, jreback commented on pandas/tests/indexes/timedeltas/test_timedelta.py
> +        index = date_range('1/1/2000', periods=50, freq='D')
can u also test with B

2017-07-04 14:19 UTC, jreback commented
can you update

2017-07-06 22:45 UTC, jreback requested changes
ping on green.

2017-07-06 22:45 UTC, jreback commented on doc/source/whatsnew/v0.20.3.txt
> +- Bug in ``infer_freq`` causing indices with 2-day gaps during the working week to be wrongly inferred as business daily (:issue:`16624`)
move to 0.21.0

2017-07-06 22:45 UTC, jreback commented on pandas/tests/indexes/timedeltas/test_timedelta.py
> +        for freq in ['D', 'B']:
instead of doing a loop, use parametrize

2017-07-06 22:45 UTC, jreback commented on pandas/tests/tseries/test_frequencies.py
> +        # 'weekend' (2-day gap) in wrong place
add the issue number as a comment

2017-07-06 22:45 UTC, jreback commented on pandas/tseries/frequencies.py
> +        if self.day_deltas != [1, 3]:  # quick check: cannot be business daily
put the comment on the line above (causes lint failure as line too long)

2017-07-06 22:45 UTC, jreback commented on pandas/tseries/frequencies.py
> +        # probably business daily, but need to confirm
add blank line before comment

2017-07-06 22:45 UTC, jreback commented on pandas/tseries/frequencies.py
> +        shifts = np.diff(np.asarray(self.index).view('i8'))
use ``np.diff(self.index.asi8)``

2017-07-07 10:20 UTC, jreback commented
looks like a tiny lint error.

2017-07-07 10:31 UTC, jreback approved these changes

2017-07-07 13:11 UTC, merged

2017-07-07 13:11 UTC, jreback commented
thanks!