BUG: fix to_latex bold_rows option
pandas-dev/pandas pull request #16708
Opened 2017-06-15 18:48 UTC by kdebrab

- [x] closes #16707
 - [x] tests added / passed
 - [ ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

2017-06-15 23:00 UTC, jreback requested changes
looks reasonable. pls add a bug fix whatsnew entry (in IO) for 0.20.3

2017-06-15 23:00 UTC, jreback commented on pandas/io/formats/format.py
> +            if self.fmt.kwds.get('bold_rows', True) and self.fmt.index:
in the constructor do a ``self.bold_rows = self.fmt.kwd.get('bold_rows', True)``; see ``HTMLFormatter``. 

Then just use this here

2017-06-16 07:18 UTC, kdebrab commented
I had to adapt  the expected result of all existing tests where. to_latex() was used, as the default behaviour changed. I'm not so sure though whether it's a good idea to set bold_rows to True by default. I guess the reason for this documented  default is the analogy with. to_html(), but in that output also the column headers are bold. In addition, bold row and/or column headers do not seem very common in latex community examples.

2017-06-16 12:08 UTC, chris-b1 commented
Could you show an example what the before/after output looks like rendered?  I'm inclined to agree that changing the default isn't a good idea.

2017-06-16 15:36 UTC, kdebrab commented
With `bold_rows=False` (i.e. 'before' output):
![image](https://user-images.githubusercontent.com/1150402/27233171-daa1846a-52b8-11e7-9fdb-d9abb439e3b5.png)
With `bold_rows=True` (would be 'after' default output):
![image](https://user-images.githubusercontent.com/1150402/27233205-02a8be88-52b9-11e7-8c93-90b033b67907.png)

It's a matter of taste, but I don't like the latter one that much...

I'm in favor of keeping the default output the same as before, and correcting the signature (and docstring) of .to_latex() accordingly.

2017-06-16 15:45 UTC, TomAugspurger commented
> I'm in favor of keeping the default output the same as before, and correcting the signature (and docstring) of .to_latex() accordingly.

+1

2017-06-19 14:28 UTC, kdebrab commented
@jreback: As proposed, I made sure to have the same default behaviour as before (i.e. `bold_rows=False`) and corrected the `.to_latex()` signature accordingly.

I also added and updated a whatsnew entry as you asked, so I guess this is ready to be merged.

2017-06-19 23:38 UTC, jreback commented
lgtm. can you rebase. ping on green. @TomAugspurger

2017-06-28 14:42 UTC, TomAugspurger approved these changes
Looks good, small suggestion to clarify the whatsnew that you can change as you rebase.

2017-06-28 14:42 UTC, TomAugspurger commented on doc/source/whatsnew/v0.20.3.txt
> +- Bug in ``.to_latex()`` where ``bold_rows`` was wrongly specified to be True by default, whereas in reality row labels remained non-bold whatever parameter provided. (:issue:`16707`)
Maybe just say here that the default behavior is the same (not bold), but can now be overridden correctly.

2017-06-30 20:34 UTC, jreback approved these changes

2017-06-30 20:34 UTC, merged

2017-06-30 20:34 UTC, jreback commented
thanks!