BUG: Fix Series doesn't work in pd.astype(). Now treat Series as dict.
pandas-dev/pandas pull request #16725
Opened 2017-06-19 09:31 UTC by BranYang

- [ ] closes #16717 
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [x] whatsnew entry

2017-06-19 10:22 UTC, jreback requested changes

2017-06-19 10:22 UTC, jreback commented on pandas/tests/frame/test_dtypes.py
> +        # GH16717
I would instead modify the previous the test and use parametrize

2017-06-19 10:22 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Fix a bug when pd.astype() receive Series as `dtype` paramter, no action is taken. Now Series
``Bug in :func:`DataFarme.astype` where a passed Series as a dtype mapping would be ignored``

2017-06-19 10:22 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Fix a bug when pd.astype() receive Series as `dtype` paramter, no action is taken. Now Series
Add the issue number as well

2017-06-19 10:22 UTC, jreback commented on pandas/tests/frame/test_dtypes.py
> +        # GH16717
then just add the issue number as an additional comment

2017-06-20 10:12 UTC, jreback approved these changes

2017-06-20 10:12 UTC, jreback commented on pandas/tests/frame/test_dtypes.py
> +        dt7 = dtype_class({})
add issue number as a comment
use result = 
rather than equiv

2017-06-20 10:12 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +works the same as a `dict` when passed to `dtype`. (:issue:`16717`).
reword to be less verbose

2017-06-20 10:29 UTC, jreback commented on pandas/core/generic.py
> +                new_type = dtype.get(self.name)
``new_type = dtype[self.name]`` is ok here now

2017-06-20 10:30 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +works the same as a `dict` when passed to `dtype`. (:issue:`16717`).
you can put this in 0.20.3

2017-06-28 05:36 UTC, jreback approved these changes
just a whatsnew fix. ping on green.

2017-06-28 05:36 UTC, jreback commented on doc/source/whatsnew/v0.20.3.txt
> +- Bug in pd.astype() when passing `Series` as `dtype`. (:issue:`16717`).
Bug in ``.astype()`` when passing a ``Series`` to ``dtype`` (use double backticks)

2017-06-28 12:59 UTC, BranYang commented
@jreback Done as your suggestion.

2017-06-30 20:11 UTC, merged

2017-06-30 20:11 UTC, jreback commented
thanks!