ENH: simple patch for read_json compression
pandas-dev/pandas pull request #16750
Opened 2017-06-21 17:40 UTC by colinhiggins

Addresses GH15644

 - [x] closes #15644
 - [x] tests added / passed
 - [ ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

The latest comment on https://github.com/pandas-dev/pandas/issues/15644 from March suggest just adding compression to read_json. This does that.

Not sure what kind of tests should be added since its using pre-existing code. It works when I tested it manually, and test_fast.sh returned with:
>9880 passed, 1280 skipped, 6 xfailed in 145.52 seconds

This is my first contribution, and I'm a bit confused about the whatsnew entry. I'm not sure which version the changes should be recorded in.

In that vein,``git diff upstream/master --name-only -- '*.py' | flake8 --diff`` fails with:
>fatal: bad revision 'upstream/master'

2017-06-21 17:44 UTC, TomAugspurger commented
> I'm not sure which version the changes should be recorded in.

New feature, so it can go in `whatsnew/v0.21.0.txt`

> In that vein,git diff upstream/master --name-only -- '*.py' | flake8 --diff fails with:

What's the output of `git remote -v`? That should include a couple lines like

```
upstream	https://github.com/pandas-dev/pandas (fetch)
upstream	https://github.com/pandas-dev/pandas (push)
```

but it may be named differently.

2017-06-21 18:37 UTC, colinhiggins commented
@TomAugspurger:

>What's the output of git remote -v? That should include a couple lines like
```
$ git remote -v
origin	git@github.com:colinhiggins/pandas.git (fetch)
origin	git@github.com:colinhiggins/pandas.git (push)
```
I tried a few different forms, all failed with the same error, including:
https://github.com/pandas-dev/pandas
git@github.com:pandas-dev/pandas.git
git://github.com/pandas-dev/pandas

2017-06-21 18:41 UTC, TomAugspurger commented
git remote add upstream https://github.com/pandas-dev/pandas should; then
you'll need to `git fetch upstream` before it'll work.

On Wed, Jun 21, 2017 at 1:37 PM, colinhiggins <notifications@github.com>
wrote:

> @TomAugspurger <https://github.com/tomaugspurger>:
>
> What's the output of git remote -v? That should include a couple lines like
>
> $ git remote -v
> origin	git@github.com:colinhiggins/pandas.git (fetch)
> origin	git@github.com:colinhiggins/pandas.git (push)
>
> I tried a few different forms, all failed with the same error, including:
> https://github.com/pandas-dev/pandas
> git@github.com:pandas-dev/pandas.git
> git://github.com/pandas-dev/pandas
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/16750#issuecomment-310168065>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABQHIv9Xdh2gkVItDlLIY8ibza7-MsO0ks5sGWMAgaJpZM4OBSwm>
> .
>

2017-06-21 18:49 UTC, colinhiggins commented
Ah, right, duh. It ran with no output. Is that a pass?

Also, upon looking at my changes, I realized that I failed to update the documentation, and there was one change I wanted to ask about. In read_csv, the first positional argument is `filepath_or_buffer`, but read_json uses `path_or_buf`. In my edit of `read_json`, I changed it to `filepath_or_buffer` since the read_csv method is a lot more developed and I assume the nomenclature is preferred. Let me know if I should revert that and stick with `path_or_buf` so that read_json is backward compatible vs. leaving it as is so that the API is more consistent between csv and json.

2017-06-21 22:29 UTC, colinhiggins commented
Reverted back to the `path_or_buf` API to maintain backward compatibility, added the whatsnew blurb, and fixed an indentation PEP8 violation.

2017-06-22 14:24 UTC, TomAugspurger commented
Changes look good, but we'll need tests for the new behavior.

You can compress https://github.com/pandas-dev/pandas/blob/master/pandas/tests/io/json/data/tsframe_iso_v012.json and add it to the repo, and then ensure we have basic coverage on this. We should also have a jsonlines version too probably.

2017-06-22 14:32 UTC, jreback commented
see https://github.com/pandas-dev/pandas/pull/13317 for how to do tests on this.

This needs similar types of testing.

2017-06-22 14:34 UTC, jreback requested changes
need to add to ``.to_json`` as well. then tests become much easier.

2017-06-22 14:34 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- The ``read_json`` method now supports a ``compression`` keyword, which allows you to read compressed json directly. The behavior of this is identical to the ``read_csv`` keyword and defaults to ``i
needs a new doc section in io.json (again see how the io.pickle compression section is done).

2017-06-22 14:34 UTC, jreback commented on pandas/io/json/json.py
> +    For on-the-fly decompression of on-disk data. If 'infer', then use gzip,
needs version added. also needs to be indendted as this won't render I think.

2017-06-22 14:34 UTC, jreback commented on pandas/io/json/json.py
> +    For on-the-fly decompression of on-disk data. If 'infer', then use gzip,
see ``pd.read_pickle`` doc-string as well.

2017-06-22 15:38 UTC, colinhiggins commented
Got it. I can take a crack at the to_json and tests, but it will have to wait for the weekend.

2017-07-08 10:37 UTC, bashtage commented on pandas/io/json/json.py
> +    '.zip', or 'xz', respectively, and no decompression otherwise. If using
Missing a . Before xz

2017-07-19 10:29 UTC, jreback commented
closing this. it needs comprehensive tests as indicated above. pls comment if you'd like to reopen.

2017-07-19 10:29 UTC, closed without merging