DOC: Updated cookbook to show usage of Grouper instead of TimeGrouper…
pandas-dev/pandas pull request #16794
Opened 2017-06-29 04:44 UTC by manikbhandari

Added links to show usage of Grouper and removed SO links to TimeGrouper- #16747

 - [ ] closes #xxxx
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

2017-06-29 11:19 UTC, jorisvandenbossche commented on doc/source/cookbook.rst
> -<http://stackoverflow.com/questions/15297053/how-can-i-divide-single-values-of-a-dataframe-by-monthly-averages>`__
I would paybe try to update the stackoverflow post?

In any case, the Grouper docs in itself are not a good reference for "Using Grouper to group values across time"

2017-06-29 16:43 UTC, manikbhandari commented on doc/source/cookbook.rst
> -<http://stackoverflow.com/questions/15297053/how-can-i-divide-single-values-of-a-dataframe-by-monthly-averages>`__
@jorisvandenbossche thank you for reviewing. I'm sorry I'm new to this, it'll be great if you could guide me on this.

I'll definitely try and update the stackoverflow post. 

> In any case, the Grouper docs in itself are not a good reference for "Using Grouper to group values across time"

Should I instead include some examples to show the usage of Grouper to group values across time?

2017-07-06 12:30 UTC, jreback requested changes

2017-07-06 12:30 UTC, jreback commented on doc/source/cookbook.rst
> +`Using Grouper instead of TimeGrouper
you can still say ``time grouping`` here.

2017-07-06 12:30 UTC, jreback commented on doc/source/cookbook.rst
> +`Grouper#2
can you give a more informative title (and again you can say 'time grouping')

2017-07-06 12:30 UTC, jreback commented on doc/source/cookbook.rst
> +`Grouping using multiindex
Grouping using a MultiIndex

2017-07-07 10:18 UTC, jreback approved these changes

2017-07-07 10:18 UTC, merged

2017-07-07 10:18 UTC, jreback commented
thanks!