Bugfix groupby multiindex levels equals rows
pandas-dev/pandas pull request #16859
Opened 2017-07-07 22:49 UTC by P-Tillmann

Fix for GH16843 where groubpy gives wrong result when number of
groupedby index+columns is equal to length of axis

 closes #16843
 tests added
 passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff`` (On Windows, ``git diff upstream/master -u -- "*.py" | flake8 --diff`` might work as an alternative.)
 - [ ] whatsnew entry

2017-07-10 10:32 UTC, jreback requested changes
lgtm. pls add a whatsnew note (0.21.0 / groupby section)

2017-07-10 10:32 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +            # GH16843
can you add a 1-liner about what this is testing

2017-07-11 19:17 UTC, P-Tillmann commented
Ok, lots red warnings now. I hope you have everything from me now for the PR.

2017-07-19 10:29 UTC, jreback commented
can you rebase and update for small comments.

2017-07-27 10:16 UTC, pep8speaks commented
Hello @P-Tillmann! Thanks for updating the PR.



 - In the file [`pandas/tests/groupby/test_groupby.py`](https://github.com/pandas-dev/pandas/blob/9404a00109b6b886d75ccb1fd48fdd4ffac7f982/pandas/tests/groupby/test_groupby.py), following are the PEP8 issues :

> [Line 3896:13](https://github.com/pandas-dev/pandas/blob/9404a00109b6b886d75ccb1fd48fdd4ffac7f982/pandas/tests/groupby/test_groupby.py#L3896): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 3896:78](https://github.com/pandas-dev/pandas/blob/9404a00109b6b886d75ccb1fd48fdd4ffac7f982/pandas/tests/groupby/test_groupby.py#L3896): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 3897:13](https://github.com/pandas-dev/pandas/blob/9404a00109b6b886d75ccb1fd48fdd4ffac7f982/pandas/tests/groupby/test_groupby.py#L3897): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

2017-07-27 22:55 UTC, jreback approved these changes

2017-07-27 22:56 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +            df.set_index(['first', 'second'], inplace=True)
can you change to 

``df = df.set_index(..)``

more idiomatic

2017-07-27 22:56 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> -- Bug in ``.isin()`` in which checking membership in empty ``Series`` objects raised an error (:issue:`16991`)
what changed on this line?

2017-07-27 22:57 UTC, jreback approved these changes
minor comment. ping when pushed / green.

2017-07-27 23:01 UTC, gfyoung commented on pandas/tests/groupby/test_groupby.py
> +            df.set_index(['first', 'second'], inplace=True)
Also, don't pass in `inplace=True`

2017-07-28 09:07 UTC, P-Tillmann commented
@jreback ping ;-)

Would you discourage the use of inplace option in general in favor of assigning back to the df?

2017-07-28 15:02 UTC, gfyoung commented
> Would you discourage the use of inplace option in general in favor of assigning back to the df?

Yes, see #16529.

2017-07-28 15:03 UTC, gfyoung commented on doc/source/whatsnew/v0.21.0.txt
> +- Bug in ``DataFrame.groupby`` when called with index or index + column key numbers equal to the axis length of the groupby (:issue:`16859`)
Your description underneath your test I think is clearer about the bug than this description is.  Try incorporating some of your test description into here.

2017-07-29 16:44 UTC, jreback commented
small changes suggest by @gfyoung look fine. otherwise lgtm.

2017-08-21 08:31 UTC, gfyoung commented
@jreback @jorisvandenbossche : Addressed my own comments.  PTAL.

2017-08-24 09:48 UTC, gfyoung commented
@jreback @jorisvandenbossche : Addressed my own comments.  PTAL.

2017-08-24 10:38 UTC, merged

2017-08-24 10:38 UTC, jreback commented
thanks!