Bug16639 fix
pandas-dev/pandas pull request #16858
Opened 2017-07-07 21:30 UTC by aviolov

- closes #16639 
 - [1 ] tests added / passed
 - ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff`` (On Windows, ``git diff upstream/master -u -- "*.py" | flake8 --diff`` might work as an alternative.)
 - [check ] whatsnew entry

2017-07-07 21:36 UTC, jreback requested changes
pretty good. some stylistic comments.

2017-07-07 21:36 UTC, jreback commented on pandas/core/algorithms.py
> -    ABCSeries, ABCIndex,
is there a reason you moved the imports around?

2017-07-07 21:36 UTC, jreback commented on pandas/tests/test_categorical.py
> +
make this a new test, move it to ``test_algos.py`` (near the other isin tests)

2017-07-07 21:36 UTC, jreback commented on pandas/tests/test_categorical.py
> +        select_ids = D['id'].isin(T['id']);
use result=
the expected= is below and use
``tm.assert_numpy_array_equal``

2017-07-07 21:36 UTC, jreback commented on pandas/tests/test_categorical.py
> +        D = pd.DataFrame({'id': pd.Series(pd.Categorical(1).from_codes(vals, cats))});
you have some linting errors, these lines are too long

2017-07-07 21:36 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Bug in ``Series.isin()`` when called for categoricals (:issue`16639`)
use :func:`Series.isin()`

when called with a categorical

2017-07-07 21:47 UTC, aviolov commented on pandas/core/algorithms.py
> -    ABCSeries, ABCIndex,
NOne, that was accidental, possibly due to Pydev or some other fluke, Ive tried to fix to baseline

2017-07-08 13:37 UTC, aviolov commented
I"m not sure I understand the Travis CI build failure. Is there something I need to do/change

2017-07-08 14:02 UTC, jreback commented
linting is failing

git diff upstream/master --name-only -- '*.py' | flake8 --diff

2017-07-08 18:54 UTC, aviolov commented
Hm... I must be missing something, on my local copy I get 
``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
with no output, which i take to mean that all is well. 
Also 
`` $ git status
On branch bug16639-fix
nothing to commit, working directory clean``

Do I need to make another pull request for my minor fixes to the review

2017-07-08 18:56 UTC, jreback commented
> Do I need to make another pull request for my minor fixes to the review

NO

simply update and push

2017-07-08 19:10 UTC, aviolov commented
From my local 
```$ git pull origin bug16639-fix 
From http://github.com/aviolov/pandas
 * branch            bug16639-fix -> FETCH_HEAD
Already up-to-date.
 $ git push origin bug16639-fix 
Everything up-to-date
`` 

Do I need to apply the 'force' flag?
`` git push -f ``

2017-07-08 19:11 UTC, jreback commented
you don't need to force push unless the existing fails. but you are failing linting.

http://pandas.pydata.org/pandas-docs/stable/contributing.html

2017-07-08 19:26 UTC, aviolov commented
I got it, I needed to run the 'comprehensive' flakes command

``` 
git diff master --name-only -- '*.py' | grep 'pandas/' | xargs -r flake8
```

Ok, hopefully fixed those

2017-07-11 10:40 UTC, jreback approved these changes

2017-07-11 10:40 UTC, merged

2017-07-11 10:40 UTC, jreback commented
thanks!

2017-07-12 16:43 UTC, aviolov commented
anytime, thanks for reviewing