ENH - Modify Dataframe.select_dtypes to accept scalar values
pandas-dev/pandas pull request #16860
Opened 2017-07-08 14:52 UTC by Ffisegydd

This commit relates to GH16855. It allows the Dataframe.select_dtypes
function to accept scalar values as well as list-like values. As such,
it should maintain backwards compatibility.

 - [x ] closes #16855
 - [x ] tests added / passed
 - [x ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff`` (On Windows, ``git diff upstream/master -u -- "*.py" | flake8 --diff`` might work as an alternative.)
 - [x ] whatsnew entry

2017-07-08 15:16 UTC, jreback requested changes
pretty good. some comments.

2017-07-08 15:16 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
>  - :func:`read_feather` has gained the ``nthreads`` parameter for multi-threaded operations (:issue:`16359`)
a reason you changed style.ipynb?

2017-07-08 15:16 UTC, jreback commented on pandas/core/frame.py
> +        # GH16855 - If either include or exclude is a non-None scalar then
comment not needed

2017-07-08 15:16 UTC, jreback commented on pandas/core/frame.py
> +        if not is_list_like(include):
use

```
 if include is not None and not is_list_like(include):
    include = [include]
```
and similar

2017-07-08 15:16 UTC, jreback commented on pandas/tests/frame/test_dtypes.py
add as a separate test, try both with include and exclude as scalaras (separately)

2017-07-08 15:16 UTC, jreback commented on pandas/tests/frame/test_dtypes.py
> +        re = df.select_dtypes(exclude=np.number)
add this test in there

2017-07-08 15:17 UTC, Ffisegydd commented on doc/source/whatsnew/v0.21.0.txt
>  - :func:`read_feather` has gained the ``nthreads`` parameter for multi-threaded operations (:issue:`16359`)
It got changed automatically by something as part of trying to build docs. I found it actually got deleted at some point and so reverted it from previous commits but the space was different for some reason.

2017-07-08 15:24 UTC, Ffisegydd commented on pandas/core/frame.py
> +        if not is_list_like(include):
Using this logic doesn't cover the case when `include` is `None` as it then gets passed through as `None`, not `[None]`, and causes a `TypeError` later on.

2017-07-08 15:55 UTC, Ffisegydd commented
As discussed in commit message. Implemented all changes apart from the logic change as it misses a necessary edge case. Happy to discuss it though.

2017-07-10 10:35 UTC, jreback approved these changes

2017-07-10 10:36 UTC, merged

2017-07-10 10:36 UTC, jreback commented
nice PR!

keep em coming!