Test  dtype
pandas-dev/pandas pull request #16887
Opened 2017-07-11 22:00 UTC by topper-123

- [ x] closes #16817
 - [x ] tests added / passed
 - [x ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff`` (On Windows, ``git diff upstream/master -u -- "*.py" | flake8 --diff`` might work as an alternative.)
 - [ ] whatsnew entry

Makes ``_get_dtype`` accept ``Categorical``s and ``CategoricalIndex``. Also passes relevant tests in ``test_common.py``.

See also discussion in #16845. Is there a manual for checking performance (can't imagine this affects performance, though)?

2017-07-11 22:44 UTC, jreback commented
> See also discussion in #16845. Is there a manual for checking performance (can't imagine this affects performance, though)?

This is in a critical path for lots of things. This absolutely needs checking.

http://pandas.pydata.org/pandas-docs/stable/contributing.html#running-the-performance-test-suite

2017-07-12 12:56 UTC, topper-123 commented
Alright, I've run asv. It took 2 hours, and the results are all over the place, from ratios of over 3 down to 0.01.  I assume this is not normal.

I tried selectively running the worst offenders individually, and then the results were now within limits (``BENCHMARKS NOT SIGNIFICANTLY CHANGED``). Do I need to take special precautions when running the whole suite, to avoid affecting the results?

2017-07-12 13:25 UTC, jreback requested changes
add a whatsnew note in bug fix conversion section

2017-07-12 13:25 UTC, jreback commented on pandas/tests/dtypes/test_common.py
> +    (str, np.dtype(str)),
what fixed this one?

2017-07-12 13:33 UTC, topper-123 commented on pandas/tests/dtypes/test_common.py
> +    (str, np.dtype(str)),
On both my system (Windows) and at try.jupyter.org (sys.platform is 'linux', ``_get_dtype(str)`` returns ``np.dtype('<U')``. In the jenkins/appvoyeur,  it returns ``np.dtype('S')``. 

To me it looks like a difference of how numpy is handled on different system and not a pandas issue. I therefore relax that test, to make it only check that ``_get_dtype(str) == np.dtype(str)``, which passes both locally and in the CI system.

2017-07-12 13:35 UTC, jreback commented on pandas/tests/dtypes/test_common.py
> +    (str, np.dtype(str)),
hmm, that looks like a py2/py3 thing. ok then. (you can maybe add a comment for that particular case)

2017-07-12 15:50 UTC, jreback commented
ok on the asv. thanks for running that. just needs a whatsnew note. ping on green.

2017-07-12 23:42 UTC, jreback approved these changes

2017-07-12 23:44 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- :func:`dtypes.common._get_dtype` now accepts ``Categorical``s and
no need for an external note here; this is an internal function

2017-07-13 20:01 UTC, topper-123 commented on doc/source/whatsnew/v0.21.0.txt
> +- :func:`dtypes.common._get_dtype` now accepts ``Categorical``s and
I don't quite understand. Above you say

> just needs a whatsnew note

Are you thinking of a different location for the note?

2017-07-13 20:05 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- :func:`dtypes.common._get_dtype` now accepts ``Categorical``s and
not this doesn't need a note at all. This is not a user relevant change as ``_get_dtype`` is not user facing.

2017-07-13 20:35 UTC, merged

2017-07-13 20:35 UTC, jreback commented
thanks @topper-123