fix for #16889 along with test
pandas-dev/pandas pull request #16897
Opened 2017-07-12 16:59 UTC by hhuuggoo

- [ ] closes #xxxx
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff`` (On Windows, ``git diff upstream/master -u -- "*.py" | flake8 --diff`` might work as an alternative.)
 - [ ] whatsnew entry

2017-07-12 21:30 UTC, jreback commented on pandas/tests/indexing/test_datetime.py
> +        mask = np.array([True, False, True, False])
add a comment with the issue number

can you also add the working example as well (from your issue)

2017-07-12 21:31 UTC, jreback requested changes
lgtm. pls add a whatnew note in indexing bug fixes.

2017-07-12 21:32 UTC, jreback commented on pandas/tests/indexing/test_datetime.py
> +        mask = np.array([True, False, True, False])
as well as the case of 

``testf.loc[mask] = df.loc[mask]``

2017-07-12 21:33 UTC, jreback commented on pandas/tests/indexing/test_datetime.py
> +        test = df.copy()
call this ``result`` rather than ``test``

2017-07-12 22:27 UTC, hhuuggoo commented on pandas/tests/indexing/test_datetime.py
> +        test = df.copy()
will do - thanks

2017-07-12 23:22 UTC, jreback commented on pandas/tests/indexing/test_datetime.py
> +    def test_tuple_setitem_with_datetime_tz(self):
sorry I meant put these cases in a single test (obviously with several sub-sections, and avoid duplicated code within reason)

2017-07-12 23:22 UTC, hhuuggoo commented on pandas/tests/indexing/test_datetime.py
> +    def test_tuple_setitem_with_datetime_tz(self):
Oh yea no problem

2017-07-13 14:06 UTC, jreback commented on pandas/tests/indexing/test_datetime.py
> +    def test_tuple_setitem_with_datetime_tz(self):
great

2017-07-13 14:06 UTC, jreback requested changes
lgtm. just need a whatsnew note. ping on green. (but fix section, indexing is fine) for 0.21.0

2017-07-14 14:59 UTC, jreback requested changes
doc changes

2017-07-14 14:59 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Fixes `__setitem__` with a tuple for dataframes with a tz-aware `DatetimeIndex` (:issue: `16889`)
this is not correct:

``DataFrame.loc`` for setting wth alignment and a tz-aware DatetimeIndex (use double-back ticks around DTI)

2017-07-14 14:59 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Fixes `__setitem__` with a tuple for dataframes with a tz-aware `DatetimeIndex` (:issue: `16889`)
no space between `` :issue:`16889` ``

2017-07-14 14:59 UTC, jreback commented on pandas/tests/indexing/test_datetime.py
> +        # support setitem with datetimeindex with tz
``.loc`` with alignment

2017-07-19 10:26 UTC, jreback commented
can you rebase and update

2017-07-19 13:42 UTC, hhuuggoo commented
will do later today

2017-07-21 11:00 UTC, jreback approved these changes

2017-07-21 11:01 UTC, merged

2017-07-21 11:01 UTC, jreback commented
thanks!