API: add infer_objects for soft conversions
pandas-dev/pandas pull request #16915
Opened 2017-07-13 23:39 UTC by chris-b1

- [x] closes #11221  (more or less)
 - [ ] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff`` (On Windows, ``git diff upstream/master -u -- "*.py" | flake8 --diff`` might work as an alternative.)
 - [x] whatsnew entry

Need to add more tests cases still

2017-07-13 23:40 UTC, gfyoung commented on doc/source/whatsnew/v0.21.0.txt
> +to native types, but not any coercive conversions.  For example
python --> Python
for example --> For example:

2017-07-13 23:41 UTC, gfyoung commented on pandas/core/generic.py
> +
The beginning of the docstring should be a single line.

2017-07-13 23:42 UTC, gfyoung commented on pandas/core/generic.py
> +        converted : same as input object
Not quite, though, as the dtypes could have been changed, right?

2017-07-13 23:43 UTC, gfyoung commented on pandas/tests/frame/test_block_internals.py
> +        tm.assert_frame_equal(df.reset_index(drop=True), expected)
What is the purpose of this part of the test?

2017-07-13 23:44 UTC, gfyoung commented on pandas/tests/series/test_dtypes.py
> +        assert actual.dtype == 'object'
Perhaps a comment above that block of code explaining why this is the case would be useful.

2017-07-13 23:45 UTC, gfyoung commented on pandas/tests/series/test_dtypes.py
> +        assert actual.dtype == 'object'
Also, why isn't there a similar test for `DataFrame` ?

2017-07-14 10:14 UTC, bashtage commented on pandas/core/generic.py
> +        See Also
Maybe a note that this is the same as the inference used when a DataFrame is constructed?

2017-07-14 14:19 UTC, jreback requested changes

2017-07-14 14:19 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +
add a sub-section reference

2017-07-14 14:19 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +on object columns, replacing some of the functionality of the deprecated ``convert_objects``
maybe want to make these `` :func:`Series.infer_objects` `` (and the like), but needs rewording to do that

2017-07-14 14:19 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +to native types, but not any coercive conversions.  For example
python scalars -> python objects

2017-07-14 14:19 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +to native types, but not any coercive conversions.  For example
use colon after For example

2017-07-14 14:19 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +   df.dtypes
sould have this same example in the docs (in basics.rst) and a ref to that.

2017-07-14 14:19 UTC, jreback commented on pandas/core/generic.py
> +        Only attempts soft conversions
add a version added tag

2017-07-17 22:48 UTC, chris-b1 commented on pandas/tests/frame/test_block_internals.py
> +        tm.assert_frame_equal(df.reset_index(drop=True), expected)
This enforces that the inference rules I'm checking against are the same as `DataFrame` constructor

2017-07-17 22:51 UTC, gfyoung commented on pandas/tests/frame/test_block_internals.py
> +        tm.assert_frame_equal(df.reset_index(drop=True), expected)
Ah, I see.  Perhaps a comment above `expected` might be useful, since it wasn't immediately clear (at least to me why this was done).

2017-07-17 23:11 UTC, gfyoung commented on pandas/core/generic.py
> +        Attempt to infer better dtypes for object columns
Nit: add a period at the end.

2017-07-17 23:11 UTC, gfyoung commented on pandas/core/generic.py
> +        Attempts soft conversion of object dtyped
Nit: "object dtyped" --> "object-dtyped"

2017-07-17 23:12 UTC, gfyoung commented on pandas/tests/series/test_dtypes.py
> +        assert actual.dtype == 'object'
Nit: add newline between "expected =" and "assert " (for readability)

2017-07-18 01:19 UTC, jreback approved these changes
lgtm. minor doc comments. merge on green (after fix)

2017-07-18 01:19 UTC, jreback commented on doc/source/basics.rst
> +     df.infer_objects().dtypes
make this a separate ipython block (to break up the code)

2017-07-18 01:19 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +The `:meth:`~DataFrame.infer_objects` and :meth:`~Series.infer_objects`
add a ref to the basics section above.

2017-07-18 01:19 UTC, jreback commented on pandas/core/generic.py
> +        >>> df.infer_objects().dtypes
I like blank lines between these sections of code

2017-07-18 11:26 UTC, merged

2017-07-18 11:26 UTC, chris-b1 commented
thanks @gfyoung @jreback @bashtage

2017-07-19 01:17 UTC, jreback commented
@chris-b1 when you have a chance: http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#infer-objects-type-conversion

``.dtype`` -> ``.dtypes``

I don't know why ``:meth:`` doesn't work, I use ``:func:`` which seems to....