DOC: behavior when slicing with missing bounds
pandas-dev/pandas pull request #16932
Opened 2017-07-14 21:54 UTC by toobaz

- [x] closes #16917
 - [ ] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff`` (On Windows, ``git diff upstream/master -u -- "*.py" | flake8 --diff`` might work as an alternative.)
 - [ ] whatsnew entry

This documents the behavior discussed in #16917. I don't have time now to produce tests (and I suspect some already exist), so feel free to not close that issue, or to open a new one for tests only.

2017-07-14 21:55 UTC, gfyoung commented
@toobaz : you will need to test this too!

2017-07-14 21:57 UTC, toobaz commented
> @toobaz : you will need to test this too!

Are you jocking?! Did you read above?

2017-07-14 22:09 UTC, jreback commented
Maybe adding a note box instead would be more clear, showing a situation where this could work and where it doesn't work. 

Putting this in the headline docs is a non-starter.

2017-07-15 00:11 UTC, gfyoung commented
> Are you jocking?! Did you read above?

It's been a long day, man.  I did not see that. :smile:

2017-07-15 00:12 UTC, gfyoung commented
@toobaz : I would prefer to merge only if there were tests.  As you don't have time to do this, I will go ahead and write tests for it unless @tdpetrou wants to jump in.

2017-07-15 06:38 UTC, gfyoung commented
BTW, I should add that the doc changes look pretty reasonable.  As I said before, adding tests (if you have time) would make this merge-able.  Otherwise, we can take care of that.

2017-07-15 07:16 UTC, toobaz commented
> BTW, I should add that the doc changes look pretty reasonable.

Cool, thanks. I did put writing those tests (and, first, searching for existing ones) in my pandas TODO list, but frankly speaking it's not very high.

2017-07-15 07:26 UTC, gfyoung commented
@toobaz : I presume you have allowed edits by maintainers, so I think what we can do is add the missing tests to your branch if you don't have the time.  Then, we can merge this.  How does that sound?

2017-07-15 07:39 UTC, toobaz commented
> @toobaz : I presume you have allowed edits by maintainers, so I think what we can do is add the missing tests to your branch if you don't have the time. Then, we can merge this. How does that sound?

Sure, that would be great!

2017-07-15 12:30 UTC, jreback requested changes

2017-07-15 12:30 UTC, jreback commented on doc/source/indexing.rst
> +    sorted (and can be compared against start and stop labels), then slicing
as indicated in my comments 
pull these out to a separate note and put in the label section

2017-07-15 12:30 UTC, jreback commented on doc/source/indexing.rst
> +**At least 1** of the labels for which you ask, must be in the index or a ``KeyError`` will be raised! When slicing, both the start bound **AND** the stop bound are *included*, if present in the inde
same

2017-07-15 13:49 UTC, toobaz commented on doc/source/indexing.rst
> +**At least 1** of the labels for which you ask, must be in the index or a ``KeyError`` will be raised! When slicing, both the start bound **AND** the stop bound are *included*, if present in the inde
I moved the main discussion in a box, but if I remove the clarification "if present in the index", then the above is actually false. Should I remove all the sentence?

2017-07-15 13:51 UTC, toobaz commented
> what we can do is add the missing tests to your branch

Notice the feature I'm describing is actually already tested at several places, including:
https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexing/test_floats.py#L387
https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexing/test_floats.py#L502
https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexing/test_floats.py#L553
https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexing/test_floats.py#L593
https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexing/test_loc.py#L307
with floats, ints and datetimes - but possibly never with strings, which were the main concern in #16917.

2017-07-15 13:59 UTC, jreback commented on doc/source/indexing.rst
> +**At least 1** of the labels for which you ask, must be in the index or a ``KeyError`` will be raised! When slicing, both the start bound **AND** the stop bound are *included*, if present in the inde
no that is ok

2017-07-15 14:01 UTC, jreback commented on doc/source/indexing.rst
> +   against start and stop labels), then slicing will still work, by selecting
ok, I think we need a mini-example here, this text is pretty dense. can you make a sub-section with a couple of examples. 

This is just not obvious to new users (whom we presume read the documentation). want to make it really clear what is going on. The examples from the issue are pretty good and show the situation.

2017-07-15 15:50 UTC, jreback approved these changes
some nitpicky comments. you can just ping when pushed.

2017-07-15 15:50 UTC, jreback commented on doc/source/indexing.rst
> +Accessing via label slices (also see :ref:`Slicing with labels <indexing.slicing_with_labels>`)
I wouldn't add this reference on this one (maybe in text some where, but not the section head)

2017-07-15 15:50 UTC, jreback commented on doc/source/indexing.rst
> +   s = pd.Series(np.random.random(5), index=[0,3,2,5,4])
can you do with with 

```
s = pd.Series(list('abcde'), index=[0, 3, 2, 5, 4])
```

instead. I think a bit more clear on what is getting selected.

2017-07-15 15:50 UTC, jreback commented on doc/source/indexing.rst
> +If at least one of the two is absent but the index is sorted (and can be
comma after absent.

2017-07-15 15:50 UTC, jreback commented on doc/source/indexing.rst
> +   s.sort_index().loc[1:6]
show

```
s.sort_index()
s.sort_index().loc[1:6]
```

to make this really clear

2017-07-15 15:50 UTC, jreback commented on doc/source/indexing.rst
> +as well as potentially ambiguous for mixed type indexes). So for instance in
For instance, in the above example,

2017-07-15 15:50 UTC, jreback commented on doc/source/indexing.rst
> +
this raises ``KeyError`` not ``IndexError``

2017-07-15 15:50 UTC, jreback commented on doc/source/indexing.rst
> +If at least one of the two is absent but the index is sorted (and can be
comma after sorted, you don't need the parens around (and can be compared....)

2017-07-15 15:58 UTC, jreback commented
ignore pep failure I just fixed

2017-07-16 08:24 UTC, toobaz commented
> some nitpicky comments. you can just ping when pushed.

@jreback ping

2017-07-16 08:43 UTC, gfyoung commented
I think given the issue you're addressing, an example like what @tdpetrou provided might be useful.

@jreback : I was thinking that we should add tests before merging this?

2017-07-16 15:23 UTC, merged

2017-07-16 15:24 UTC, jreback commented
thansks @toobaz 

this is tested in several. Separate issue is whether we want to try show a warning on non-sorted selections.

2017-07-16 17:16 UTC, gfyoung commented
> this is tested in several places.

But with partial strings though?  That's what I wasn't sure about.