DEPR #16747: deprecate pd.TimeGrouper
pandas-dev/pandas pull request #16942
Opened 2017-07-15 10:18 UTC by stevemontana1980

- [x] closes #16747
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master -u -- "*.py" | flake8 --diff``
 - [ ] whatsnew entry -> Should I do this for a future

2017-07-15 10:18 UTC, pep8speaks commented
Hello @stevemontana1980! Thanks for submitting the PR.

 - In the file [`pandas/core/resample.py`](https://github.com/pandas-dev/pandas/blob/8d9fd112f4f4271b7ea15539a32635bba255a46d/pandas/core/resample.py), following are the PEP8 issues :

> [Line 1118:9](https://github.com/pandas-dev/pandas/blob/8d9fd112f4f4271b7ea15539a32635bba255a46d/pandas/core/resample.py#L1118): [E741](https://duckduckgo.com/?q=pep8%20E741) ambiguous variable name 'l'



 - In the file [`pandas/tests/test_resample.py`](https://github.com/pandas-dev/pandas/blob/8d9fd112f4f4271b7ea15539a32635bba255a46d/pandas/tests/test_resample.py), following are the PEP8 issues :

> [Line 857:5](https://github.com/pandas-dev/pandas/blob/8d9fd112f4f4271b7ea15539a32635bba255a46d/pandas/tests/test_resample.py#L857): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def
> [Line 1558:9](https://github.com/pandas-dev/pandas/blob/8d9fd112f4f4271b7ea15539a32635bba255a46d/pandas/tests/test_resample.py#L1558): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def
> [Line 2197:5](https://github.com/pandas-dev/pandas/blob/8d9fd112f4f4271b7ea15539a32635bba255a46d/pandas/tests/test_resample.py#L2197): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def
> [Line 2799:5](https://github.com/pandas-dev/pandas/blob/8d9fd112f4f4271b7ea15539a32635bba255a46d/pandas/tests/test_resample.py#L2799): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def
> [Line 2870:9](https://github.com/pandas-dev/pandas/blob/8d9fd112f4f4271b7ea15539a32635bba255a46d/pandas/tests/test_resample.py#L2870): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def
> [Line 2881:9](https://github.com/pandas-dev/pandas/blob/8d9fd112f4f4271b7ea15539a32635bba255a46d/pandas/tests/test_resample.py#L2881): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def
> [Line 3043:9](https://github.com/pandas-dev/pandas/blob/8d9fd112f4f4271b7ea15539a32635bba255a46d/pandas/tests/test_resample.py#L3043): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def
> [Line 3085:9](https://github.com/pandas-dev/pandas/blob/8d9fd112f4f4271b7ea15539a32635bba255a46d/pandas/tests/test_resample.py#L3085): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def

2017-07-15 10:27 UTC, imih commented
#16747

2017-07-15 12:27 UTC, TomAugspurger commented on pandas/tests/api/test_api.py
> +    deprecated_classes_in_future = ['Panel', 'TimeGrouper']
I think `TimeGrouper` should go in the `deprecated_classes` list.

2017-07-15 12:27 UTC, TomAugspurger commented on pandas/tests/test_resample.py
> +        # deprecation TimeGrouper, #16747
Usually we write these as # GH #16747

2017-07-15 12:44 UTC, stevemontana1980 commented on pandas/tests/test_resample.py
> +        # deprecation TimeGrouper, #16747
Thank, changes committed. I'm new at this, so thanks for your patience.

2017-07-15 13:20 UTC, jreback requested changes
- pls add a line in whatsnew (deprecations sections).
- run tests where this appears locally (e.g. the resample / groupby tests). we need to suppress this error where it is used now. so you need to change any instances of use of ``TimeGrouper`` to use ``Grouper`` (there are a few). but of course leave the tests on the deprecated one.

2017-08-18 00:57 UTC, jreback commented
can you rebase and update according to comments.

2017-09-23 20:55 UTC, jreback commented
can you rebase / update

2017-09-28 10:28 UTC, jreback commented
closing in favor of #17703

2017-09-28 10:28 UTC, closed without merging