Clarify whitespace behavior in read_fwf documentation (#16772)
pandas-dev/pandas pull request #16950
Opened 2017-07-15 16:24 UTC by lphk92

- [x] closes #16772 
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master -u -- "*.py" | flake8 --diff``
 - [ ] whatsnew entry

2017-07-15 16:24 UTC, pep8speaks commented
Hello @lphk92! Thanks for submitting the PR.

 - In the file [`pandas/io/parsers.py`](https://github.com/pandas-dev/pandas/blob/f4aef5e16376d464e317bea9056222da114141f0/pandas/io/parsers.py), following are the PEP8 issues :

> [Line 1698:9](https://github.com/pandas-dev/pandas/blob/f4aef5e16376d464e317bea9056222da114141f0/pandas/io/parsers.py#L1698): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'
> [Line 2937:13](https://github.com/pandas-dev/pandas/blob/f4aef5e16376d464e317bea9056222da114141f0/pandas/io/parsers.py#L2937): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'
> [Line 3152:9](https://github.com/pandas-dev/pandas/blob/f4aef5e16376d464e317bea9056222da114141f0/pandas/io/parsers.py#L3152): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'
> [Line 3173:9](https://github.com/pandas-dev/pandas/blob/f4aef5e16376d464e317bea9056222da114141f0/pandas/io/parsers.py#L3173): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'
> [Line 3177:9](https://github.com/pandas-dev/pandas/blob/f4aef5e16376d464e317bea9056222da114141f0/pandas/io/parsers.py#L3177): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'

2017-07-15 16:29 UTC, jreback commented on pandas/io/parsers.py
> +    delimiters are prone to ignoring quoted data. Regex example: ``'\r\t'``
you *may* need to update ``docs/source/io.rst`` as well

2017-07-15 16:30 UTC, jreback commented on pandas/tests/io/parser/test_read_fwf.py
> +        data_expected = """ a ,bbb
can you add the issue number as a comment

2017-07-15 16:31 UTC, jreback commented
cc @chris-b1 

hmm so we are updating the docs? was there a resolution on the issue?

2017-07-15 17:04 UTC, lphk92 commented on pandas/io/parsers.py
> +    delimiters are prone to ignoring quoted data. Regex example: ``'\r\t'``
This is done now.

2017-07-15 17:06 UTC, jreback commented on doc/source/io.rst
> +well as a behavioral change in the ``delimiter`` parameter:
what does this addition mean?

2017-07-15 17:07 UTC, lphk92 commented on doc/source/io.rst
> +well as a behavioral change in the ``delimiter`` parameter:
That the delimiter parameter behaves differently in read_fwf than it does in read_csv (as specified in the new documentation)

2017-07-16 08:15 UTC, gfyoung commented on pandas/io/parsers.py
Why was this moved in the first place?

2017-07-16 08:18 UTC, gfyoung commented on doc/source/io.rst
> +well as a behavioral change in the ``delimiter`` parameter:
I would reword as : "and a different usage of the ``delimiter`` parameter" instead of "as well as...parameter"

2017-07-16 08:18 UTC, gfyoung commented
@jreback : AFAICT, I think @chris-b1 was thinking we should better surface and document the `delimiter` parameter, which I agree with and is what this PR does.

2017-07-16 14:10 UTC, lphk92 commented on doc/source/io.rst
> +well as a behavioral change in the ``delimiter`` parameter:
Done.

2017-07-16 15:22 UTC, jreback requested changes

2017-07-16 15:22 UTC, jreback commented on pandas/tests/io/parser/test_read_fwf.py
> +        test_data = """ a bbb
can you also add an example using ``\t`` (the default)

2017-07-16 15:22 UTC, jreback commented on pandas/tests/io/parser/test_read_fwf.py
> +        df = read_fwf(StringIO(test_data), widths=[3, 3],
result =

2017-07-17 19:26 UTC, chris-b1 commented on pandas/io/parsers.py
> +delimiter: str, default ``\t ``
Wrap default value in quotes - at a glance it's kind of trick to see that whitespace is included maybe write as `'\t' + ' '`

2017-07-17 19:27 UTC, chris-b1 commented
This looks good to me, except for doc notes.  I didn't know the delimiter kw worked this way on `read_fwf`, so not what I had in mind, but is the right solution!

2017-07-17 23:12 UTC, lphk92 commented on pandas/tests/io/parser/test_read_fwf.py
> +        test_data = """ a bbb
Done

2017-07-17 23:12 UTC, lphk92 commented on pandas/io/parsers.py
> +delimiter: str, default ``\t ``
Done

2017-07-17 23:12 UTC, lphk92 commented on pandas/tests/io/parser/test_read_fwf.py
> +        df = read_fwf(StringIO(test_data), widths=[3, 3],
Not entirely sure what you're asking for. Do you just want me to rename 'df' to 'result'?

2017-07-17 23:13 UTC, gfyoung commented on pandas/tests/io/parser/test_read_fwf.py
> +        df = read_fwf(StringIO(test_data), widths=[3, 3],
Yes, that is correct.

2017-07-17 23:38 UTC, jreback approved these changes

2017-07-17 23:38 UTC, jreback commented
lgtm. merge on green.

2017-07-17 23:45 UTC, gfyoung commented
@lphk92 : If you could address my question <a href="https://github.com/pandas-dev/pandas/pull/16950#discussion_r127601576">above</a> before merging this, that would be great!

2017-07-17 23:52 UTC, lphk92 commented on pandas/io/parsers.py
I'm not sure why this was originally moved out of `_sep_doc`, however I've put it back as this particular documentation of the `delimiter` parameter only applies to `read_csv` and `read_table`, both of which use `_sep_doc` in their documentation.

2017-07-17 23:53 UTC, lphk92 commented
@gfyoung I've just responded to your question as best I can. Let me know if I can provide more clarification.

2017-07-17 23:58 UTC, gfyoung commented on pandas/io/parsers.py
Awesome.  Thanks!

2017-07-18 05:00 UTC, gfyoung commented
Alright, everything looks good now.  Merging.

2017-07-18 05:01 UTC, merged

2017-07-18 05:01 UTC, gfyoung commented
Thanks @lphk92 !