ENH: Add warning when setting into nonexistent attribute
pandas-dev/pandas pull request #16951
Opened 2017-07-15 16:52 UTC by deniederhut

- [ ] closes #7175
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master -u -- "*.py" | flake8 --diff``
 - [ ] whatsnew entry

2017-07-15 16:52 UTC, pep8speaks commented
Hello @deniederhut! Thanks for submitting the PR.

 - In the file [`pandas/core/generic.py`](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py), following are the PEP8 issues :

> [Line 351:13](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py#L351): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'
> [Line 364:13](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py#L364): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'
> [Line 581:9](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py#L581): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'
> [Line 864:9](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py#L864): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'
> [Line 1758:17](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py#L1758): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'
> [Line 1867:13](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py#L1867): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'
> [Line 1875:13](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py#L1875): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'
> [Line 2636:13](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py#L2636): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'
> [Line 2845:13](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py#L2845): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def
> [Line 3289:13](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py#L3289): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def
> [Line 3304:9](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py#L3304): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def
> [Line 3309:9](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py#L3309): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def
> [Line 3314:9](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py#L3314): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def
> [Line 3327:17](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py#L3327): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'
> [Line 5369:25](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py#L5369): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'
> [Line 5409:29](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py#L5409): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'
> [Line 6253:9](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/core/generic.py#L6253): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def

 - In the file [`pandas/tests/dtypes/test_generic.py`](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/tests/dtypes/test_generic.py), following are the PEP8 issues :

> [Line 45:31](https://github.com/pandas-dev/pandas/blob/eb4668694a2a4a0e9f2ab7d08b5e211c1dea1029/pandas/tests/dtypes/test_generic.py#L45): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment

2017-07-15 16:59 UTC, jreback commented on doc/source/indexing.rst
> +if you try to use attribute access to create a new column, it issues a `UserWarning` and creates a new attribute rather than a
use double-backticks around ``UserWarning``

2017-07-15 17:01 UTC, jreback requested changes

2017-07-15 17:01 UTC, jreback commented on pandas/core/generic.py
> +                                  "https://pandas.pydata.org/pandas-docs/"
you need a stacklevel=2 (or maybe higher here)

2017-07-15 17:01 UTC, jreback commented on pandas/tests/dtypes/test_generic.py
> +        with pytest.warns(UserWarning):
use ``tm.assert_raises_warning``

2017-07-15 17:01 UTC, jreback commented on pandas/tests/dtypes/test_generic.py
> +        with catch_warnings(record=True) as w:
what are you testing here?

2017-07-15 17:01 UTC, jreback commented on pandas/tests/dtypes/test_generic.py
> +            assert len(w) == 0 # fail if false warning on Series
move this to a new test add the issue number as a comment

2017-07-15 17:03 UTC, jreback commented
Replicate this test from the original issue (and assert each of these things).

```
d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
     'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)

# this adds a column to df
df['three'] = df.two + 1

# this successfully modifies an existing column
df.one += 1

# this seems to work but does not add a column to df
df.four = df.two + 2

print df.three
print df.four
print df
```

I would be ok with this raising
```
# this seems to work but does not add a column to df
df.four = df.two + 2
```

2017-07-15 17:04 UTC, jreback commented
also would love to warn on this: https://github.com/pandas-dev/pandas/issues/5904 as well.

2017-07-15 17:04 UTC, deniederhut commented
Wilco. Still in `test_generic.py`?

2017-07-15 17:25 UTC, jreback commented
> Wilco. Still in test_generic.py?

yeah that seems reasonable

2017-07-15 17:34 UTC, jreback commented on doc/source/indexing.rst
> +if you try to use attribute access to create a new column, it issues a ```UserWarning`` and creates a new attribute rather than a
maybe add a: starting in 0.21.0

2017-07-15 18:53 UTC, jreback requested changes

2017-07-15 18:53 UTC, jreback commented on pandas/core/generic.py
> +                          "columns whose names collide with methods",
i would say that this is a collision

we actually DO allow it (maybe should raise but let's start with a warning)

2017-07-15 18:53 UTC, jreback commented on pandas/tests/dtypes/test_generic.py
> +    series = pd.Series([1, 2, 3])
u can remove this

2017-07-15 18:53 UTC, jreback commented on pandas/tests/dtypes/test_generic.py
> +class TestABCWarnings(object):
u don't need a class here
u can just do this as a function (more pytest idiomatic)

2017-07-15 18:53 UTC, jreback commented on pandas/tests/dtypes/test_generic.py
> +        with catch_warnings(record=True) as w:
put blank lines in between these

2017-07-15 18:53 UTC, jreback commented on pandas/tests/dtypes/test_generic.py
> +            self.df['sum'] = self.df.two
test with self.df.sum as well

2017-07-15 19:05 UTC, deniederhut commented on pandas/tests/dtypes/test_generic.py
> +class TestABCWarnings(object):
I didn't see anything in the contributing guide about test style, so I was following the style of the code nearby.

2017-07-15 19:09 UTC, deniederhut commented on pandas/core/generic.py
> +                          "columns whose names collide with methods",
The warning says that attribute-like access is not allowed. E.g.

```python
df = pd.DataFrame({'a': [1, 2]})
df['sum'] = [3, 4]
print(df.sum)
```

```
<bound method DataFrame.sum of    a  sum
0  1    3
1  2    4>
```

2017-07-15 19:12 UTC, jreback commented on pandas/tests/dtypes/test_generic.py
> +class TestABCWarnings(object):
http://pandas.pydata.org/pandas-docs/stable/contributing.html#test-driven-development-code-writing

pytest section -

2017-07-15 19:15 UTC, jreback commented on pandas/core/generic.py
> +                          "columns whose names collide with methods",
i just want to see a more verbose message that this is not recommended
we could also raise but that's a bit harsh

2017-07-15 19:19 UTC, deniederhut commented on pandas/core/generic.py
> +                          "columns whose names collide with methods",
Okay... how about something like:

> Column name '{key}' collides with a built-in method, which will cause unexpected attribute behavior

2017-07-15 19:20 UTC, jreback commented on pandas/core/generic.py
> +                          "columns whose names collide with methods",
sure

2017-07-15 19:40 UTC, deniederhut commented on pandas/core/generic.py
> +                                  "https://pandas.pydata.org/pandas-docs/"
This has been fixed -- not sure why GH isn't picking it up

2017-07-16 01:15 UTC, jreback commented on pandas/core/generic.py
> +        if callable(getattr(self, str(key), None)):
check if its a string first, e.g. 

```
if isinstance(key, compat.text_types) and callable(getattr(self, key, None))):
 ......
```

2017-07-16 01:16 UTC, jreback commented on pandas/core/generic.py
> +                                  "https://pandas.pydata.org/pandas-docs/"
use ``if isinstance(self, ABCDataFrame) and is_list_like(value):``

2017-07-16 01:17 UTC, jreback commented on pandas/tests/dtypes/test_generic.py
> +    with catch_warnings(record=True) as w:
this should NOT show a warning, right?

2017-07-16 01:17 UTC, jreback commented on pandas/tests/dtypes/test_generic.py
> +    with catch_warnings(record=True) as w:
nor this one

2017-07-16 01:18 UTC, jreback commented on pandas/tests/dtypes/test_generic.py
> +        # successfully add new column
add a statement that the first 3 should NOT be showing warnigns (I know you are checking which is fine)

2017-07-16 01:19 UTC, jreback commented
@deniederhut looks pretty good. rebase on master, some changes and you prob need to force push.

2017-07-16 01:20 UTC, jreback commented
also needs a whatsnew note; put this in the api-breaking changes section. I *think* we may need a full on example to highlite this.

2017-07-19 00:18 UTC, deniederhut commented
Wilco. 

And I might be missing something, but we are just issuing warnings, right? This shouldn't break any clients unless they are configured to raise warnings as exceptions?

2017-07-19 00:36 UTC, jreback commented
yeah isn't it just a warning then no big deal

however I think we may want to consider making this an error in the future (so can make an issue for that)

2017-07-19 00:49 UTC, deniederhut commented
Would you like me to add to the whatsnew that these warnings are subject to escalation in future releases?

2017-07-19 00:52 UTC, jreback commented
no but pls open an issue to re-evaluate in the future

2017-07-19 01:28 UTC, jreback approved these changes
docs look good! some small changes.

2017-07-19 01:28 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +which does not raise any obvious exceptions, but also does not create a new column:
which -> This

2017-07-19 01:28 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +and creating a column whose name collides with a method or attribute already in the instance
Creating a column (use sentences if possible here).

2017-07-19 01:28 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +  UserWarning: Pandas doesn't allow Series to be assigned into nonexistent columns - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
Can you put this whole section in indexing.rst (below the attribute access section). Put a reference to it from the whatsnew (you can leave some of it here as well; usually we make the whatsnew a smaller version of what we put in the docs proper).

2017-07-19 01:28 UTC, jreback commented on pandas/core/generic.py
> +                                  "https://pandas.pydata.org/pandas-docs/"
this change here

2017-07-19 12:11 UTC, deniederhut commented
Okay, I _think_ I've gotten the docs correct

2017-07-29 19:13 UTC, jbrockmendel commented on pandas/core/generic.py
>      def _set_item(self, key, value):
Is this a single-point-of-contact that all (most?  many?) setter methods go through?  i.e. will the various `loc.__setitem__` paths eventually wind through here?

2017-07-29 19:14 UTC, gfyoung commented on pandas/core/generic.py
>      def _set_item(self, key, value):
Yes, I believe that is correct.

2017-07-29 20:29 UTC, deniederhut commented on pandas/core/generic.py
>      def _set_item(self, key, value):
That is my understanding, yes. Here is an example of setting while using `.loc`:

```python
import pandas as pd
df = pd.DataFrame({'one': [0, 1, 2]})
df.loc[:, 'sum'] = df.one.sum()
```

```
UserWarning: Column name 'sum' collides with a built-in method, which will cause unexpected attribute behavior
  self._set_item(key, value)

```

2017-07-31 23:19 UTC, jreback commented on pandas/core/generic.py
>      def _set_item(self, key, value):
this point is *only* for ``[]`` setting, e.g. setting a column on a DF or an element on a Series. ``.loc/.iloc`` are handled in core/indexing.py

2017-07-31 23:31 UTC, jreback requested changes
some doc comments. lgtm. ping on green for a final look.

2017-07-31 23:31 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
the underline length must match the title.

2017-07-31 23:31 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +Both of these now raise a ``UserWarning`` about the potential for unexpected behavior. See `Attribute Access <https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access>`__.
use `` :ref:`Attribute Access <indexing.attribute_access>` ``

2017-07-31 23:31 UTC, jreback commented on pandas/core/generic.py
> +        if isinstance(key, str) and callable(getattr(self, key, None)):
use compat.string_types rather than ``str`` here

2017-07-31 23:31 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +.. _whatsnew_0210.enhancements.column-creation:
call this ``attribute_access`` (rather than ``column-creation``)

2017-07-31 23:31 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +Both of these now raise a ``UserWarning`` about the potential for unexpected behavior. See `Attribute Access <https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access>`__.
the section in indexing.rst

2017-08-03 12:40 UTC, deniederhut commented on pandas/core/generic.py
> +        if isinstance(key, str) and callable(getattr(self, key, None)):
Using `string_types` causes failures in Python2 when creating columns that have unicode characters in their names. See c90aa2266137d78f4786b85ff3a5cd08ff0c39fd.

2017-08-04 13:32 UTC, deniederhut commented
@jreback I think we might be ready for the final check

2017-08-07 11:05 UTC, jreback approved these changes

2017-08-07 11:05 UTC, merged

2017-08-07 11:06 UTC, jreback commented
thanks @deniederhut nice changes!

2017-08-08 13:12 UTC, jreback commented
@deniederhut 
see https://travis-ci.org/MacPython/pandas-wheels/jobs/262048673

this is a 32-bit python 2.7 build; there are some warnings at the end. See if you can repro (you can try using a 64-bit python 2.7 build)

2017-08-08 14:24 UTC, jorisvandenbossche commented
I have some general comments on this PR (sorry for being late with this feedback):

* I like that you now get a warning when trying to create a new column with `df.col_name = [..]` (which silently fails at creating a new column), that's very useful! However, the case when the name you try to set is a builtin, eg `df.mean = [...]` doesn't raise a warning. 
  I think it would be nice to add a warning then as well (as it is actually a more harmful case, it is not only silently failing, but also overwriting your `mean()` method)

* IMO the warning when setting a new column with `df['new_col'] = ..` which has the same name as a builtin method is a bit overkill. I understand it is confusing from time to time that the attribute access does not always work, but IMO there are many more people who use column names like `mean` without any problem that would now get warnings (one example that this is common is applying functions in groupby operations that create such warnings like `s.groupby(..).agg(['mean', 'median'])`). So I am -1 on this change. 
  See also comment above about `df.mean = ..` not raising a warning while `df['mean] = ..` does, but that's something else as it is actually overwriting the method (and this can also be easily fixed to raise I think). 
  Last, if we keep this warning, I think we should also do it for attributes and not only methods? (eg currently `df['shape'] does not raise a warning`

2017-08-08 14:27 UTC, jorisvandenbossche reviewed
and also one specific code comment

2017-08-08 14:27 UTC, jorisvandenbossche commented on pandas/core/generic.py
> +                                  "into nonexistent columns - see "
I would write this a bit more generic, as it does not only raise for Series objects (and I also find it a bit confusing, as pandas certainly allows assigning Series objects, just with another syntax). 

Maybe something like "pandas doesn't allow to add a new column using attribute access" ? (can certainly be improved further)

2017-08-12 21:15 UTC, deniederhut commented
Happy to dig into this some more - two questions:

1. What is the consensus among the maintainers about warning on name collision?
2. Should this be submitted as a separate PR?

2017-08-12 21:34 UTC, jreback commented
new PR

2017-08-12 22:04 UTC, shoyer commented
I also just saw this PR. I agree with @jorisvandenbossche we should not raise warnings when setting column names that conflict with built-in methods. This would be a major source of annoyance for users.

I think we're pretty clear that attribute style access for columns is a convenience feature, not something to be relied on for arbitrary names. In contrast, we *do* guarantee that `__getitem__` works for any valid column name.

2017-08-16 13:12 UTC, jorisvandenbossche commented
@deniederhut do you want to do a PR for this?

@jreback what do you think about the concerns of @shoyer and me? Fine with changing this part of the PR back?

2017-08-16 13:45 UTC, deniederhut commented
I'll take a look this weekend

On Wed, Aug 16, 2017, 08:13 Joris Van den Bossche <notifications@github.com>
wrote:

> @deniederhut <https://github.com/deniederhut> do you want to do a PR for
> this?
>
> @jreback <https://github.com/jreback> what do you think about the
> concerns of @shoyer <https://github.com/shoyer> and me? Fine with
> changing this part of the PR back?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/16951#issuecomment-322766464>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGjNrIJP7vd57k2d7VACiSiUdIES21mXks5sYurrgaJpZM4OZEMp>
> .
>

2017-08-16 20:41 UTC, jorisvandenbossche commented
@deniederhut cool! 
I also just opened https://github.com/pandas-dev/pandas/issues/17268 to keep track of this