DOC: document convention argument for resample()
pandas-dev/pandas pull request #16965
Opened 2017-07-15 21:51 UTC by fding253

- [ ] closes #5023 
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master -u -- "*.py" | flake8 --diff``
 - [ ] whatsnew entry

2017-07-15 23:51 UTC, jreback commented on pandas/core/generic.py
> +        >>> series_p = pd.Series([1, 2],
just call this s, your lines are too long I think as well.

2017-07-15 23:51 UTC, jreback requested changes

2017-07-15 23:51 UTC, jreback commented on pandas/core/generic.py
> +        Resample by month using 'start' ``convention``. Values are assigned to
you don't need convertion to be in double-backticks here

2017-07-16 15:55 UTC, merged

2017-07-16 15:55 UTC, TomAugspurger commented
Thanks @fding253!