ENH: Use 'Y' as an alias for end of year
pandas-dev/pandas pull request #16978
Opened 2017-07-16 10:35 UTC by gfyoung

Redo of #16958.
Closes #9313.

cc @imih

2017-07-16 12:25 UTC, jreback commented
i would have simply taken the original commit and added things in another commit; no need to tense the original away

2017-07-16 17:36 UTC, gfyoung commented
> i would have simply taken the original commit and added things in another commit; no need to rebase the original away

That's fair.  Done.

2017-07-16 22:13 UTC, jreback requested changes

2017-07-16 22:13 UTC, jreback commented on doc/source/timeseries.rst
>      "AS", "year start frequency"
YS is also accepted here

2017-07-16 22:13 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- :func:`date_range` now accepts 'Y' in addition to 'A' as an alias for end of year (:issue:`9313`)
and add mention of YS

2017-07-16 22:13 UTC, jreback commented on pandas/tests/tseries/test_frequencies.py
>      assert (frequencies._period_str_to_code('A-JAN') == 1001)
tests for YS as well (like AS)

2017-07-16 22:13 UTC, jreback commented on pandas/tseries/frequencies.py
> +_pure_alias = {
why is this necessary? why is this not added to the ``_offsset_to_period_map`` and creating new code?

2017-07-16 23:21 UTC, gfyoung commented on pandas/tests/tseries/test_frequencies.py
>      assert (frequencies._period_str_to_code('A-JAN') == 1001)
Umm...where do we actually test 'AS' in this file?

2017-07-17 01:15 UTC, gfyoung commented on pandas/tests/tseries/test_frequencies.py
>      assert (frequencies._period_str_to_code('A-JAN') == 1001)
I added tests for "AS" in `test_date_range`.

2017-07-17 03:36 UTC, gfyoung commented
@jreback : PTAL

2017-07-17 10:55 UTC, jreback requested changes

2017-07-17 10:55 UTC, jreback commented on pandas/tests/indexes/datetimes/test_date_range.py
> +    @pytest.mark.parametrize("freq", ["BA", "BY"])
move to the class for Business tests (below)

2017-07-17 10:55 UTC, jreback commented on pandas/tests/tseries/test_frequencies.py
> +    assert (frequencies._period_str_to_code('Y') == 1000)
I would add tests that validate things with 'A', 'YS', 'AS' as well here, similar to Y

2017-07-17 10:55 UTC, jreback commented on pandas/tests/tseries/test_frequencies.py
> +        assert frequencies.get_freq_group('Y-JAN') == 1000
also BYS (assume BAS is validated somewhere)

2017-07-17 10:55 UTC, jreback commented on pandas/tseries/frequencies.py
> +    "Y": 1000,
I don't think you need this, the point is the alias are mapped to here

2017-07-17 10:55 UTC, jreback commented on pandas/tseries/frequencies.py
>  # Additional aliases
say that these are yearly aliases (Y, A)

2017-07-17 15:22 UTC, gfyoung commented on pandas/tests/indexes/datetimes/test_date_range.py
> +    @pytest.mark.parametrize("freq", ["BA", "BY"])
But this is for `date_range`, not `bdate_range` though.

2017-07-17 23:20 UTC, jreback commented on pandas/tests/indexes/datetimes/test_date_range.py
> +    @pytest.mark.parametrize("freq", ["BA", "BY"])
hmm ok.

2017-07-18 04:10 UTC, gfyoung commented on pandas/tests/tseries/test_frequencies.py
> +    assert (frequencies._period_str_to_code('Y') == 1000)
Not sure what you mean here: neither `YS` nor `AS` are considered valid "period strings"

2017-07-18 04:12 UTC, gfyoung commented on pandas/tests/tseries/test_frequencies.py
> +        assert frequencies.get_freq_group('Y-JAN') == 1000
Not sure what you mean here: neither `BYS` nor `BAS` are considered valid "frequency groups"

2017-07-18 04:12 UTC, gfyoung commented on pandas/tseries/frequencies.py
>  # Additional aliases
Done.

2017-07-18 04:56 UTC, gfyoung commented on pandas/tseries/frequencies.py
> +    "Y": 1000,
Done.

2017-07-18 10:43 UTC, jreback commented on pandas/tests/tseries/test_frequencies.py
> +    assert (frequencies._period_str_to_code('Y') == 1000)
well, where is AS tested then?

2017-07-18 14:58 UTC, gfyoung commented on pandas/tests/tseries/test_frequencies.py
> +    assert (frequencies._period_str_to_code('Y') == 1000)
In `date_range` at the very least.

2017-07-19 02:38 UTC, gfyoung commented
@jreback : Everything is green.  PTAL

2017-07-19 02:41 UTC, jreback commented
lgtm

2017-07-19 02:51 UTC, merged

2017-07-19 09:47 UTC, jreback commented
http://pandas-docs.github.io/pandas-docs-travis/timeseries.html#offset-aliases

needs updates for biz start/end freq

2017-07-19 15:34 UTC, gfyoung commented
Oops.  Done.