Fix missing imports and a syntax error
pandas-dev/pandas pull request #16984
Opened 2017-07-16 19:24 UTC by cclauss

- [ ] closes #xxxx
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master -u -- "*.py" | flake8 --diff``
 - [ ] whatsnew entry

2017-07-16 19:24 UTC, pep8speaks commented
Hello @cclauss! Thanks for submitting the PR.





 - In the file [`scripts/windows_builder/check_and_build.py`](https://github.com/pandas-dev/pandas/blob/e70995aa1a1989a993145fa68dab8d69a533d11e/scripts/windows_builder/check_and_build.py), following are the PEP8 issues :

> [Line 52:9](https://github.com/pandas-dev/pandas/blob/e70995aa1a1989a993145fa68dab8d69a533d11e/scripts/windows_builder/check_and_build.py#L52): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

2017-07-16 19:45 UTC, jreback commented
instead of this would be happy with progress on https://github.com/pandas-dev/pandas/issues/13704

blow away most of these scripts

2017-07-16 23:23 UTC, gfyoung commented
> instead of this would be happy with progress on #13704

I agree with this.  Should we close then?

2017-07-17 04:51 UTC, cclauss commented
#13704 has been open almost one year.  I can look into it but that is going to require me learning much more project context to make sure that useful code is not thrown away in the process.  The contents of this pull request are targeted changes to ensure that the entire project can pass a flake8 test.  I think that gives them value even if the files that they are in are deleted next week or next month.

2017-07-17 05:09 UTC, gfyoung commented
> The contents of this pull request are targeted changes to ensure that the entire project can pass a flake8 test.

We actually don't check those files during `flake8`.

> I think that gives them value even if the files that they are in are deleted next week or next month.

That is fair.  I'm kind of indifferent given that there hasn't been much progress on this.  I'll leave it to @jreback to decide since he piloted the issue in the first place.

2017-07-17 10:50 UTC, jreback requested changes

2017-07-17 10:50 UTC, jreback commented on bench/bench_join_panel.py
> +from pandas import Panel
remove this entire directory! (bench), these are no longer used.

2017-07-17 10:50 UTC, jreback commented on scripts/windows_builder/check_and_build.py
>  username='pandas'
remove the entire directory: scripts/windows_builder as these are not longer used

2017-07-17 11:00 UTC, jreback commented
@cclauss you don't need to make these separate commits. I am going to squash this anyhow.

2017-07-17 11:43 UTC, cclauss commented
@jreback Yes, please squash!  Thanks.

2017-07-17 12:02 UTC, jreback commented
So each time a push happens the CI's are all triggered. They do fail with duplicates (IOW a new push is spun up). You can certainly have many commits, just don't push after *each* one.

2017-07-17 12:58 UTC, jreback approved these changes

2017-07-17 12:59 UTC, merged

2017-07-17 12:59 UTC, jreback commented
thanks @cclauss

2017-07-17 13:00 UTC, jreback commented
if you wanted to fix the remaining on this issue: https://github.com/pandas-dev/pandas/issues/13704

would be great.