Fix for #16836
pandas-dev/pandas pull request #16995
Opened 2017-07-17 15:40 UTC by jdeschenes

* Removed unnecessary conversion to i8
* Fixed failed test (`test_frame_column_inplace_sort_exception`)
* Added check to ensure that the test is performing its intended goal(`test_sort_nan`)

 - [x] closes #16836 
 - [ ] tests added / passed
 - [x] passes ``git diff upstream/master -u -- "*.py" | flake8 --diff``
 - [x] whatsnew entry

2017-07-17 16:30 UTC, gfyoung commented on pandas/tests/frame/test_sorting.py
> +        assert_frame_equal(df_sorted, df)
Why did this assertion statement change?

2017-07-17 16:30 UTC, gfyoung approved these changes

2017-07-17 18:27 UTC, jdeschenes commented on pandas/tests/frame/test_sorting.py
> +        assert_frame_equal(df_sorted, df)
As far as I understand, this was a bug in the test.  Previously, the two assertions implied that na_position does not have any effect on the sort, which is incorrect.

2017-07-17 18:31 UTC, gfyoung commented on pandas/tests/frame/test_sorting.py
> +        assert_frame_equal(df_sorted, df)
Okay, makes sense.

2017-07-18 01:24 UTC, jreback requested changes
couple of comments

2017-07-18 01:24 UTC, jreback commented on pandas/tests/frame/test_sorting.py
> +        # GH 16836
make this a separately naemd tests

2017-07-18 01:24 UTC, jreback commented on pandas/tests/frame/test_sorting.py
put a comment as to the issue number

2017-07-18 01:24 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Fixes regression when sorting by multiple columns on a datetime array with NaT values (:issue:`16836`)
double back-ticks around ``NaT``; say ``datetime64`` dtype (its not an array, rather a Series)

2017-07-18 10:47 UTC, jreback requested changes

2017-07-18 14:01 UTC, jdeschenes commented on pandas/tests/frame/test_sorting.py
This particular change does not have anything to do with the fix. I added it to fix the test since I saw that its goal was broken

2017-07-18 14:06 UTC, jdeschenes commented on pandas/tests/frame/test_sorting.py
> +        # GH 16836
The test is actually superfluous. The fix to `test_sort_nat_values_in_int_columns` is sufficient to cover the issue. Do you still want to keep it?

2017-07-18 23:37 UTC, jreback commented on pandas/tests/frame/test_sorting.py
> +
ok for a new issue, generally like a separate test. can you fix here. otherwise lgtm.

2017-07-19 22:32 UTC, jdeschenes commented on pandas/tests/frame/test_sorting.py
> +
The latter test starting on line 337 is actually redundant with this test. Do you want me to remove it, or move it to a separate test?

2017-07-21 10:42 UTC, jreback requested changes
some doc comments

2017-07-21 10:42 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Fixes regression when sorting by multiple columns on a ``datetime64`` dtype ``Series`` with ``NaT`` values (:issue:`16836`)
``datetime64[ns]`` dtype

2017-07-21 10:42 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Fixes regression when sorting by multiple columns on a ``datetime64`` dtype ``Series`` with ``NaT`` values (:issue:`16836`)
say bug in ``DataFrame.sort_values()``

2017-07-21 10:42 UTC, jreback commented on pandas/tests/frame/test_sorting.py
> +        df1 = df.sort_values(by='B')
use

```
expected = 

result = 
```

2017-07-21 10:42 UTC, jreback commented on pandas/tests/frame/test_sorting.py
> +        sorted_df = df.sort_values(by=['a', 'b'], )
use ``result=``

2017-08-09 00:00 UTC, jreback commented
can you rebase and update

2017-09-23 17:04 UTC, jreback commented
can you rebase / update

2017-09-28 14:18 UTC, jreback approved these changes

2017-09-28 14:18 UTC, jreback commented
looks fine, can you rebase. ping on green.

2017-09-29 10:43 UTC, jreback commented
thanks!

2017-09-29 10:43 UTC, closed without merging