BUG: fixed issue with mixed type groupby aggregate
pandas-dev/pandas pull request #17003
Opened 2017-07-18 01:44 UTC by nreeve17

Fixes issue #16916, where using aggregate on a mixed type grouping
vector fails. Added test in test_aggregate.py to ensure that the bug
is fixed.

 - [x] closes #xxxx
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master -u -- "*.py" | flake8 --diff``
 - [ ] whatsnew entry

2017-07-18 03:55 UTC, gfyoung commented
@nreeve17 : Thanks for the PR!  I think you just need a `whatsnew`, and you should be set!

2017-07-18 03:55 UTC, gfyoung commented on pandas/tests/groupby/test_aggregate.py
> +    def test_mixed_type_grouping(self):
Refer the issue number beneath the function definition.

2017-07-18 10:24 UTC, jreback requested changes

2017-07-18 10:24 UTC, jreback commented on pandas/core/groupby.py
> +                values = result
I would rather
```
# put at top
from pandas.core.agorithms

index = Index(safe_sort(result), name=self.grouper.names[0])
```

2017-07-18 10:24 UTC, jreback commented on pandas/tests/groupby/test_aggregate.py
> +        X = pd.DataFrame(data=[[[1, 1], [2, 2], [3, 3]],
expected =

2017-07-18 10:24 UTC, jreback commented on pandas/tests/groupby/test_aggregate.py
> +        S = pd.DataFrame(data=[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]],
df =

2017-07-18 10:24 UTC, jreback commented on pandas/tests/groupby/test_aggregate.py
> +        T = S.groupby('grouping').aggregate(lambda x: x.tolist())
result = df.groupby(....)

2017-07-18 10:24 UTC, jreback commented on pandas/tests/groupby/test_aggregate.py
> +        tm.assert_frame_equal(T, X)
tm.assert_frame_equal(result, expected)

2017-07-19 18:40 UTC, nreeve17 commented on pandas/core/groupby.py
> +                values = result
I tried this change and it caused 4 tests in the full test suite to fail. Those tests were TestDatetimeIndex.test_resample_categorical_data_with_timedeltaindex, TestGroupByAggregate.test_mixed_type_grouping (the test that I wrote), TestGroupBy.test_basic, and test_compressed_urls[python-explicit-gzip-.gz]
Also, I noticed that safe_sort returns all objects as strings, even if the input includes numeric types.

2017-07-20 11:04 UTC, jreback commented on pandas/core/groupby.py
> +                values = result
yeah this is an embedded issue with ``safe_sort``, fixed here: https://github.com/pandas-dev/pandas/pull/17034. you can rebase on top (or wait for me to merge this).

2017-07-21 10:39 UTC, jreback requested changes

2017-07-21 10:39 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Bug in ``infer_freq`` causing indices with 2-day gaps during the working week to be wrongly inferred as business daily (:issue:`16624`)
revert all of these changes except the this issue note

2017-07-21 10:39 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Bug in ``Grouper.aggregate()`` on using a mixed type grouping vector (:issue:`16916`)
this is not at all clear, pls revise

2017-07-28 00:38 UTC, nreeve17 commented on pandas/core/groupby.py
> +                values = result
I tried this and it resulted in the same tests failing, not sure what's going on.

2017-07-28 00:43 UTC, jreback commented on pandas/core/groupby.py
> +                values = result
did u rebase

2017-08-02 19:19 UTC, nreeve17 commented on pandas/core/groupby.py
> +                values = result
I did 'git pull upstream master'

2017-08-03 12:14 UTC, jreback requested changes

2017-08-03 12:14 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Bug in ``DataFrame.resample().size()`` where an empty ``DataFrame`` did not return a ``Series`` (:issue:`14962`)
rebase error, pls remove

2017-08-03 12:14 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> -- Bug in ``groupby.transform()`` that would coerce boolean dtypes back to float (:issue:`16875`)
also a rebase error, you removed an existing issue

2017-08-03 12:14 UTC, jreback commented on pandas/core/groupby.py
> +                values = result
you need to use ``safe_sort`` here with the latest changed.

``git pull upstream origin/master``

2017-08-04 20:55 UTC, nreeve17 commented
I have re-added the bugfix line into the whatsnew doc, and I git pulled upstream master and pushed the changes with safe_sort.

2017-08-07 11:03 UTC, jreback commented
looks like there is a ``TypeError`` raised somewhere which causes this to take an incorrect path.

2017-08-07 13:47 UTC, ElDeveloper commented
@jreback, yeah, seems like the exception is coming from [this line](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/src/inference.pyx#L363).

2017-08-07 22:00 UTC, nreeve17 commented
@jreback Is there anything you might suggest to fix this error? This error did not show up when we used the Try/Catch block

2017-08-08 23:59 UTC, jreback commented
you have to pick out the cases where its failing and see exactly how it is failing. its possible ``safe_sort`` needs another case

2017-09-23 17:03 UTC, jreback commented
can you rebase / update

2017-09-26 01:17 UTC, nreeve17 commented
Commits should be updated 👍

2017-10-29 23:23 UTC, jreback commented
can you rebase and update

2017-11-25 16:18 UTC, jreback requested changes

2017-12-18 19:48 UTC, closed without merging