# Issue 17046
pandas-dev/pandas pull request #17051
Opened 2017-07-21 23:33 UTC by ysau

#    modified: /pandas/tests/indexes/test_base.py,
#              /doc/source/whatsnew/v0.21.0.txt
#
# Include both '>' and '<' in the error message in
# TestMixedIntIndex.test_argsort and
# TestMixedIntIndex.test_numpy_argsort

 - [ ] closes #17046
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master -u -- "*.py" | flake8 --diff``
 - [ ] whatsnew entry

2017-07-21 23:42 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Fixes ``test_argsort``, ``test_numpy_argsort`` to cover both `>` and `<` in the error message (:issue:`17046`)
this doesn't need a release note

2017-07-21 23:42 UTC, jreback commented
looks good. let's see if this passes. ping on green.

2017-07-21 23:43 UTC, jreback requested changes
comment

2017-07-21 23:50 UTC, ysau commented on doc/source/whatsnew/v0.21.0.txt
> +- Fixes ``test_argsort``, ``test_numpy_argsort`` to cover both `>` and `<` in the error message (:issue:`17046`)
Ok.  What do I need to do to undo changes in the release note?  Should I check in the code again and resubmit a pull request?

2017-07-22 01:25 UTC, gfyoung commented on doc/source/whatsnew/v0.21.0.txt
> +- Fixes ``test_argsort``, ``test_numpy_argsort`` to cover both `>` and `<` in the error message (:issue:`17046`)
On your branch at the top directory, perform the following:

~~~
git checkout master doc/source/whatsnew/v0.21.0.txt
~~~

Commit these changes and push.

2017-07-22 04:23 UTC, gfyoung approved these changes

2017-07-22 04:23 UTC, gfyoung commented
@ysau : LGTM, ping when green!

2017-07-22 04:58 UTC, merged

2017-07-22 04:58 UTC, gfyoung commented
Thanks @ysau !

2017-07-22 07:08 UTC, ysau commented
@jreback, @gfyoung Thanks for the guidance!