Bugfix for multilevel columns with empty strings in Python 2
pandas-dev/pandas pull request #17099
Opened 2017-07-27 18:10 UTC by chrisjbillington

Allow unicode empty strings to be used as placeholders in multilevel column names in Python 2.

The code in `Frame._getitem_multilevel()` only treats empty strings as placeholders in multilevel columns if they are of type `str`. Since in Python 2 this means bytestrings, this means a unicode empty string is not treated as a placeholder. This is a problem for Python 2 code that is trying to be forward-compatible with Python 3 by importing `unicode_literals` from `__future__` and using empty strings in DataFrame construction - those empty strings will be unicode strings and not treated as placeholders by pandas.

This patch changes the logic to allow anything that passes an equality check with `''` to be used as a placeholder, rather than checking its type, which means that after this patch either bytestring or unicode empty strings can be used as placeholders in Python 2, and the situation is unchanged in Python 3 (unicode strings, but not bytestrings, will be treated as placeholders).

Without this patch, the following code:

```python
from __future__ import print_function
import pandas

# Unicode string placeholder in multilevel column:
df = pandas.DataFrame({(u'test', u''): [1.0, 2.0, 3.0]})
print(df['test'])
print(type(df['test']))
print()

# native string type placeholder in multilevel column:
df = pandas.DataFrame({(u'test', ''): [1.0, 2.0, 3.0]})
print(df['test'])
print(type(df['test']))

```
Results in the following in Python 2:

```
0  1.0
1  2.0
2  3.0
<class 'pandas.core.frame.DataFrame'>

0    1.0
1    2.0
2    3.0
Name: test, dtype: float64
<class 'pandas.core.series.Series'>
```
Whereas in Python 3 it results in:
```
0    1.0
1    2.0
2    3.0
Name: test, dtype: float64
<class 'pandas.core.series.Series'>

0    1.0
1    2.0
2    3.0
Name: test, dtype: float64
<class 'pandas.core.series.Series'>
```

After the patch, the Python 2 result is the same as the Python 3 result.

2017-07-27 18:20 UTC, chrisjbillington commented
Full disclosure - the bug is my fault! I've only contributed to pandas once before and it was the exact code that has this problem. I wasn't thinking about forward compatibility with Python 3 at the time.

2017-07-27 19:48 UTC, pep8speaks commented
Hello @chrisjbillington! Thanks for updating the PR.



 - In the file [`pandas/tests/test_multilevel.py`](https://github.com/pandas-dev/pandas/blob/6d8710fd5026537cff68a6c615c772626214afa1/pandas/tests/test_multilevel.py), following are the PEP8 issues :

> [Line 1699:80](https://github.com/pandas-dev/pandas/blob/6d8710fd5026537cff68a6c615c772626214afa1/pandas/tests/test_multilevel.py#L1699): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 1700:80](https://github.com/pandas-dev/pandas/blob/6d8710fd5026537cff68a6c615c772626214afa1/pandas/tests/test_multilevel.py#L1700): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)

2017-07-27 22:58 UTC, jreback requested changes
i have to look again, but pls add a whatsnew note, couple of changes.

2017-07-27 22:58 UTC, jreback commented on pandas/tests/test_multilevel.py
> +        df = DataFrame(randn(4, 6), columns=index)
use np.random.randn

2017-07-27 22:58 UTC, jreback commented on pandas/tests/test_multilevel.py
> +        # Note this is only different to test_mixed_depth_get() on Python 2
can you add the PR number for this (as no associated issue number)

2017-07-27 22:58 UTC, jreback commented on pandas/tests/test_multilevel.py
> +        tm.assert_series_equal(result, expected, check_names=False)
construct the expected to have the correct names

2017-07-27 22:59 UTC, gfyoung commented
> Note the first blank line in the output when a unicode empty string placeholder was used.

A little hard to see given that you don't have anything printed before that but understood. :smile:

2017-07-27 23:00 UTC, gfyoung commented on pandas/tests/test_multilevel.py
> +        tm.assert_series_equal(result, expected, check_names=False)
Same comment as <a href="https://github.com/pandas-dev/pandas/pull/17099#discussion_r129979113">above</a>

2017-07-28 03:48 UTC, chrisjbillington commented
Thanks for the (tentative) review!

I've made the requested changes.

2017-07-28 06:04 UTC, gfyoung approved these changes

2017-07-29 16:50 UTC, jreback requested changes

2017-07-29 16:50 UTC, jreback commented on pandas/tests/test_multilevel.py
> -        assert result.name == ('routine1', 'result1')
can you parametrize ``test_mixed_depth_get`` in that case then, rather than duping all of the code

2017-07-29 16:50 UTC, jreback commented on pandas/core/frame.py
> +                if top == '':
put a comment what is going on here.

2017-07-29 18:07 UTC, chrisjbillington commented
Thanks! I've made the further requested changes.

2017-08-02 16:34 UTC, chrisjbillington commented
Bump! Any chance of getting this into the next release? I'm in the process of porting an application to that strange dialect that is Python2.7/3.4+ and it would be great to be able to deploy my updates once this fix is in the conda repositories.

2017-08-02 16:35 UTC, gfyoung commented
@chrisjbillington : Absolutely.  This looks pretty good to merge, but I think @jreback might want to look it over just in case there is anything else to fix.

2017-08-02 16:37 UTC, chrisjbillington commented
Great, thanks!

2017-08-09 10:22 UTC, jreback requested changes

2017-08-09 10:22 UTC, jreback commented on pandas/tests/test_multilevel.py
> -    def test_mixed_depth_get(self):
use 
```
pytest.mark.parametrize('unicode_strings', [True, False])
def test_mixed_depth_get(self, unicode_strings):
 .....
```

2017-08-09 10:22 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Fixes getting a column by name when unicode empty strings are used as placeholders in multilevel columns in Python 2 (:issue:`17099`)
this is a mouthful, can you simplify a bit

2017-08-10 06:05 UTC, chrisjbillington commented
Thanks! I've simplified the whatsnew note and parametrized the test.

2017-08-10 06:10 UTC, gfyoung commented
@jreback : Thoughts?

2017-08-10 10:36 UTC, jreback approved these changes

2017-08-10 10:36 UTC, merged

2017-08-10 10:36 UTC, jreback commented
thanks!

2017-08-10 13:38 UTC, chrisjbillington commented
No worries, thank you!