BUG: #7757 Fix CSV parsing of singleton list header
pandas-dev/pandas pull request #17090
Opened 2017-07-27 04:43 UTC by threecgreen

- [ ] closes #7757
 - [ ] added ```test_singleton_header``` in ```pandas/tests/io/parser/header.py```
 - [ ] passes ``git diff upstream/master -u -- "*.py" | flake8 --diff``

I fixed an issue with CSV parsing where passing a single-row header as a list to ```pd.read_csv```
would result in a ```pd.DataFrame``` of all ```NaN``` values. I added a simple parser test of whether there are any ```NaN``` values in the ```pd.DataFrame``` returned by ```pd.read_csv``` given a header list of length one.

2017-07-27 04:44 UTC, gfyoung commented on pandas/_libs/parsers.pyx
> +                # Header list of length 1
Remove this comment.

2017-07-27 04:45 UTC, gfyoung commented on pandas/tests/io/parser/header.py
> +        assert not df.isnull().values.any()
Instead of doing this, construct the expected output.

2017-07-27 04:45 UTC, gfyoung commented on pandas/tests/io/parser/header.py
> +        data = """a,b,c\n0,1,2\n1,2,3"""
Reference the issue number above this line, e.g.: "see gh-7757"

2017-07-27 10:01 UTC, gfyoung commented on pandas/tests/io/parser/header.py
> +        expected = self.read_csv(StringIO(data), header=0)
I would explicitly construct it using the `DataFrame` constructor.  This makes the test more reliable.

2017-08-01 22:48 UTC, jreback requested changes
pls add a whatsnew note. some comments.

2017-08-01 22:48 UTC, jreback commented on pandas/_libs/parsers.pyx
> +                if len(header) > 1:
any way to make this slightly less duplicative

e.g. you can pul out
```
self.header  = header
```

after the ``if len(header) > 1:`` block (as its for both if and else.

2017-08-01 22:48 UTC, jreback commented on pandas/io/parsers.py
> +                if len(header) > 1:
```
have_mi_columns = len(header) > 1
if have_mi_columns:
    .....
```

2017-08-03 12:11 UTC, jreback approved these changes
pls address the comment by @gfyoung otherwise lgtm.

2017-08-03 15:51 UTC, gfyoung approved these changes

2017-08-03 16:37 UTC, merged

2017-08-03 16:37 UTC, gfyoung commented
Thanks @threecgreen !