Normalized index type and name of empty series
pandas-dev/pandas pull request #17149
Opened 2017-08-02 05:20 UTC by discort

- [ ] closes #14313
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master -u -- "*.py" | flake8 --diff``
 - [ ] whatsnew entry

2017-08-02 07:51 UTC, gfyoung commented on pandas/tests/test_resample.py
> +            assert_series_equal(result, expected, check_dtype=False)
Why are we not checking `dtype` ?

2017-08-02 08:07 UTC, discort commented on pandas/tests/test_resample.py
> +            assert_series_equal(result, expected, check_dtype=False)
Is there exist a way how to predict a `dtype` after [apply](https://github.com/pandas-dev/pandas/blob/master/pandas/core/resample.py#L403)?
In this example after aplying we have the next result:
```
In [1]: result
Out[1]: Series([], dtype: float64)

In [2]: result.index
Out[2]: Index([], dtype='object')
```

I decided to change the name and index type according to the issue. And we have a similar [test](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/test_resample.py#L761-L777) where we are not checking `dtype`

2017-08-02 10:27 UTC, jreback requested changes

2017-08-02 10:27 UTC, jreback commented on pandas/core/resample.py
> +        if isinstance(result, com.ABCSeries) and result.empty:
ABCSeries should already be imported (and if not, just add at the top)

2017-08-02 10:27 UTC, jreback commented on pandas/tests/test_resample.py
> +            assert_series_equal(result, expected, check_dtype=False)
yeah this is fine. ``create_series()`` returns a float, while the first apply coerces this to int. So to answer your question, no its not possible to a-priori determine the type w/o actual introspection of the udf.

2017-08-02 10:27 UTC, jreback commented on pandas/tests/test_resample.py
> +            assert result.name == expected.name
you don't need to assert the name as assert_series_equal does this by default

2017-08-02 10:27 UTC, jreback commented on pandas/core/resample.py
> +        if isinstance(result, com.ABCSeries) and result.empty:
This should go at line 437 (the other ``_wrap_result``); this is for a sub-class DatetimeIndexResampler (and it calls the other one).

2017-08-02 10:27 UTC, jreback commented on pandas/tests/test_resample.py
> +            assert result.name == expected.name
can you move this to ``Base`` instead to fully test Period/Timedelta Index (this will fail currently there as the code change is too specific)

2017-08-02 10:47 UTC, discort commented on pandas/tests/test_resample.py
> +            assert result.name == expected.name
@jreback 

I've already tried to move this to `Base`.But I got the failure on `TestPeriodIndex`
```
pandas/core/resample.py:316: in aggregate
    self._set_binner()
pandas/core/resample.py:244: in _set_binner
    self.binner, self.grouper = self._get_binner()
pandas/core/resample.py:252: in _get_binner
    binner, bins, binlabels = self._get_binner_for_time()
pandas/core/resample.py:695: in _get_binner_for_time
    return self.groupby._get_time_bins(self.ax)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pandas.core.resample.TimeGrouper object at 0x7f8ba410d860>, ax = PeriodIndex([], dtype='period[D]', freq='D')

    def _get_time_bins(self, ax):
        if not isinstance(ax, DatetimeIndex):
            raise TypeError('axis must be a DatetimeIndex, but got '
>                           'an instance of %r' % type(ax).__name__)
E           TypeError: axis must be a DatetimeIndex, but got an instance of 'PeriodIndex'
```

I didn't find in tests whether `PeriodIndex` is testing with `apply`.
Is this correct behavior? I mean the test failure on `PeriodIndex`

2017-08-02 10:58 UTC, jreback commented on pandas/tests/test_resample.py
> +            assert result.name == expected.name
its possible we aren't fully testing PI with .apply. you can have a look. If nothing, then pls add a test which xfails.

2017-08-02 15:03 UTC, discort commented
@jreback

2017-08-09 10:29 UTC, jreback approved these changes

2017-08-09 10:37 UTC, merged

2017-08-09 10:37 UTC, jreback commented
thanks!