Update window.pyx
pandas-dev/pandas pull request #17156
Opened 2017-08-02 20:29 UTC by FXocena

- [ ]  #15305
 - [ ] changing the order of 'calling roll_sum' and 'get_window_indexer' in 'roll_generic' could fix #15305 
The bug caused by the return values from get_window_indexer. It changes value of 'win', which is not supposed to be passed to roll_sum.

2017-08-02 21:08 UTC, gfyoung commented
> could fix

You can write a test to confirm your suspicion :wink:

2017-08-04 12:57 UTC, pep8speaks commented
Hello @FXocena! Thanks for updating the PR.

 - In the file [`pandas/tests/test_window.py`](https://github.com/pandas-dev/pandas/blob/0a7db15a07661ce6dcc9c7cf7310bf35cc29d01c/pandas/tests/test_window.py), following are the PEP8 issues :

> [Line 436:80](https://github.com/pandas-dev/pandas/blob/0a7db15a07661ce6dcc9c7cf7310bf35cc29d01c/pandas/tests/test_window.py#L436): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 445:1](https://github.com/pandas-dev/pandas/blob/0a7db15a07661ce6dcc9c7cf7310bf35cc29d01c/pandas/tests/test_window.py#L445): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2017-08-04 13:27 UTC, FXocena commented
@gfyoung I add a test method to class TestRolling in test_window. 
The method is called 'test_constructor_with_timedelta_window_and_minperiods', using same dataframe as 'test_constructor_with_timedelta_window'.
with old window.pyx, this test will fail since the result_roll_generic is a all-nan dataframe

2017-08-04 14:48 UTC, gfyoung commented
@FXocena : This looks pretty good.  You will need to address some style-checking errors <a href="https://travis-ci.org/pandas-dev/pandas/jobs/260999962#L1847">here</a> and add a `whatsnew` entry.  Otherwise, it looks great!

2017-08-07 11:09 UTC, jreback requested changes

2017-08-07 11:09 UTC, jreback commented on pandas/tests/test_window.py
> +            expected = pd.DataFrame({'value': expected_data},
you can put the expected_data directly in the frame.

2017-08-07 11:09 UTC, jreback commented on pandas/tests/test_window.py
> +            expected = df.rolling('3D', min_periods=2).sum()
what is this last part testing?

2017-08-08 13:07 UTC, FXocena commented on pandas/tests/test_window.py
> +            expected = df.rolling('3D', min_periods=2).sum()
This tests when window == '3D'. I'd better put it together with [timedelta(days=3), pd.Timedelta(days=3)]

2017-08-08 23:41 UTC, jreback approved these changes

2017-08-08 23:41 UTC, jreback commented
ok pushed a commit. this can be merged on green.

2017-08-10 12:32 UTC, merged

2017-08-10 12:32 UTC, jreback commented
thanks!