Make some attributes of DateOffset read-only; add tests
pandas-dev/pandas pull request #17181
Opened 2017-08-06 04:56 UTC by jbrockmendel

This PR takes over for #17137.  That PR tried to handle the general case of this issue, but ultimately doing that correctly would require a much more extreme refactoring.

This PR only used a cached version of `_params` when `kwds` is empty.  This special case covers `'M', 'D', 'H', 'min', 'sec', 'ms', 'us', 'ns'` special cases.

I plan to extend this to cover at least the Annual and Quarterly cases, but doing that carefully may take a while, so this can get the ball rolling.

 - [ ] closes #xxxx
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master -u -- "*.py" | flake8 --diff``
 - [ ] whatsnew entry

2017-08-08 23:58 UTC, jreback requested changes

2017-08-08 23:58 UTC, jreback commented on pandas/tseries/offsets.py
> +        if name in frozen and hasattr(self, name):
so this needs a deprecation cycle for n & normalize, rather than raising here.

2017-08-09 01:59 UTC, jbrockmendel commented on pandas/tseries/offsets.py
> +        if name in frozen and hasattr(self, name):
This PR is not a long-term solution.  Instead how about we have it clear the cache whenever an attribute is re-set?  That should ensure correctness without breaking backward-compatibility.

2017-08-09 02:34 UTC, pep8speaks commented
Hello @jbrockmendel! Thanks for updating the PR.

 - In the file [`pandas/tests/tseries/test_offsets.py`](https://github.com/pandas-dev/pandas/blob/a888af50e8b44855aebefea2af5625535be9e9d6/pandas/tests/tseries/test_offsets.py), following are the PEP8 issues :

> [Line 176:21](https://github.com/pandas-dev/pandas/blob/a888af50e8b44855aebefea2af5625535be9e9d6/pandas/tests/tseries/test_offsets.py#L176): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator

 - In the file [`pandas/tseries/offsets.py`](https://github.com/pandas-dev/pandas/blob/a888af50e8b44855aebefea2af5625535be9e9d6/pandas/tseries/offsets.py), following are the PEP8 issues :

> [Line 1901:1](https://github.com/pandas-dev/pandas/blob/a888af50e8b44855aebefea2af5625535be9e9d6/pandas/tseries/offsets.py#L1901): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2017-08-30 15:10 UTC, jbrockmendel commented
I've got a much better approach that can be implemented if/when #17274 is merged.  Closing this to be replaced at a later date.

2017-08-30 15:10 UTC, closed without merging