BUG: support pandas objects in iloc with old numpy versions
pandas-dev/pandas pull request #17194
Opened 2017-08-07 22:07 UTC by toobaz

- [x] closes #17193
 - [x] tests added / passed
 - [x] passes ``git diff master -u -- "*.py" | flake8 --diff``
 - [x] whatsnew entry

2017-08-07 22:08 UTC, gfyoung commented
@toobaz : I'm not sure if you saw my comment, but we intend to drop support for `numpy` < 1.9 in this upcoming release per #17002.

2017-08-07 22:09 UTC, toobaz commented
> @toobaz : I'm not sure if you saw my comment, but we intend to drop support for numpy < 1.9 in this upcoming release per #17002.

Yes, sorry, I saw it now only. Shall I rebase just leaving the new test? It makes sense regardless of numpy versions.

2017-08-07 22:12 UTC, gfyoung commented
@toobaz : No worries!  I'm a little hesitant to accept your "patch" (i.e. the change in the non-test file) if it's not necessary for newer versions of `numpy`.  However, I think we would be perfectly fine just accepting the test (though we wouldn't merge until after #17002).

2017-08-07 22:15 UTC, toobaz commented
> However, I think we would be perfectly fine just accepting the test (though we wouldn't merge until after #17002).

Sure, that's what I meant: I will then wait for #17002 (or at least for the numpy version used in circleci to change) and then rebase leaving the test only.

2017-08-07 22:15 UTC, gfyoung commented
Ah, okay.  We're on the same page here.  Absolutely.

2017-08-08 10:48 UTC, jreback requested changes
fine with this.

2017-08-08 10:48 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Fixes ``.iloc`` with numpy 1.7 or 1.8 when passed a pandas object (:issue:`17193`)
this is not very descriptive. pls revise. you can just say older numpy.

2017-08-08 10:48 UTC, jreback commented on pandas/core/internals.py
> +            indexer = getattr(indexer, 'values', indexer)
``indexer = np.asarray(indexer)`` might be better here

2017-08-08 10:48 UTC, jreback commented on pandas/tests/indexing/test_iloc.py
> +        # GH 17193
specify that this is for older numpy

2017-08-08 10:48 UTC, jreback commented on pandas/core/internals.py
> +            indexer = getattr(indexer, 'values', indexer)
you can be explcit and use _np_version_under1p19 (then this is easier to remove later). alternatively the ``np.asarray`` may work.

2017-08-08 14:39 UTC, jorisvandenbossche approved these changes

2017-08-08 21:54 UTC, toobaz commented
> you can be explcit and use _np_version_under1p19 (then this is easier to remove later).

done

> alternatively the np.asarray may work.

Unfortunately fails when ``indexer`` is a slice

2017-08-08 23:30 UTC, jreback approved these changes

2017-08-08 23:30 UTC, merged

2017-08-08 23:30 UTC, jreback commented
thanks @toobaz