REF: _get_objs_combined_axis
pandas-dev/pandas pull request #17217
Opened 2017-08-10 18:27 UTC by toobaz

- [x] tests passed
- [x] passes `git diff master -u -- "*.py" | flake8 --diff`

As proposed [here](https://github.com/pandas-dev/pandas/pull/17011#discussion_r128045375), with the addition of the ``axis`` argument.

2017-08-11 07:59 UTC, pep8speaks commented
Hello @toobaz! Thanks for updating the PR.







 - In the file [`pandas/core/reshape/concat.py`](https://github.com/pandas-dev/pandas/blob/e162de5bcde980ce47ea5eaeec80eed2ee102ee6/pandas/core/reshape/concat.py), following are the PEP8 issues :

> [Line 451:45](https://github.com/pandas-dev/pandas/blob/e162de5bcde980ce47ea5eaeec80eed2ee102ee6/pandas/core/reshape/concat.py#L451): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

2017-08-11 10:26 UTC, jreback commented on pandas/core/indexes/api.py
> +    obs_idxes = [obj._get_axis(axis) for obj in objs
why the if here? then you get a return of ``None``, rather than an empty Index?

2017-08-11 10:27 UTC, jreback commented on pandas/core/indexes/api.py
> +                 if hasattr(obj, '_get_axis')]
can you add a comment for a doc-string

2017-08-11 10:29 UTC, jreback commented on pandas/core/reshape/concat.py
> +        data_axis = 1 - i if self.objs[0].ndim == 2 else i
you can use: ``self.objs[0]._get_block_manager_axis(i)``

2017-08-11 10:30 UTC, jreback commented on pandas/core/indexes/api.py
> +    obs_idxes = [obj._get_axis(axis) for obj in objs
I c, you use this below. Then you can add a comment about what this is doing.

2017-08-11 10:30 UTC, jreback requested changes
comments, lgtm otherwise.

2017-08-11 13:25 UTC, toobaz commented
> comments

done

2017-08-12 17:33 UTC, jreback approved these changes

2017-08-12 17:33 UTC, merged

2017-08-12 17:33 UTC, jreback commented
thanks!