FIX: define `DataFrame.items` for all versions of python
pandas-dev/pandas pull request #17214
Opened 2017-08-10 15:31 UTC by tacaswell

Closes #17213

This leaves a slight semantic difference between `dict.items` and
`DateFrame.items` in python2, however there is no code currently
expecting `DataFrame.items` to return a list and in python3 there is
no `dict.iteritems`.

This eases writing 'native' python3 code that also runs under python2.

Do you want a whatsnew for this?

- [x] closes #xxxx
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-08-10 15:32 UTC, gfyoung commented on pandas/tests/frame/test_api.py
> +        df = DataFrame([[1, 2, 3], [4, 5, 6]], columns=['a', 'a', 'b'])
Reference issue number.

2017-08-10 15:33 UTC, gfyoung commented on pandas/tests/frame/test_api.py
> +            assert type(v) == Series
Do you think you could explicitly check the `Series` that you get for each iteration?

2017-08-10 15:34 UTC, tacaswell commented on pandas/tests/frame/test_api.py
> +            assert type(v) == Series
I just cargo-culted the test immediately above this that checks `compat.iteritems(df)` :smiling_imp:

2017-08-10 16:03 UTC, jreback commented
prior PR https://github.com/pandas-dev/pandas/pull/13920

2017-08-10 16:19 UTC, gfyoung commented on pandas/tests/frame/test_api.py
> +        # issue #17213
Let's reference #13918 as well here.

2017-08-10 16:24 UTC, tacaswell commented
I disagree with @jreback from a year ago that `items` should be not-lazy in python2.  We are a year closer to python2 EOL and we should not jump through hoops to maintain exactly identical behavior, but not ideal, behavior.

However I have just spent more time complaining about not wanting to do it than it would take to just implement it, so either way is fine with me.

2017-08-10 17:49 UTC, gfyoung commented
@tacaswell : I think your change is almost exactly the same as the original PR, which I think people were in agreement with back then.  This looks fine (just needs a `whatsnew`).

2017-08-10 19:53 UTC, gfyoung commented on doc/source/whatsnew/v0.21.0.txt
> +- :func:`DataFrame.items` is present in both Python 2 and 3 and is lazy in all cases.
Reference both issue numbers here.

2017-08-17 10:19 UTC, jreback commented
trivial changes. rebase and ping on green.

2017-08-17 10:22 UTC, jreback requested changes
actually can you also change Series.items and see where that breaks.

2017-08-17 10:22 UTC, jreback commented on pandas/tests/frame/test_api.py
> +            assert type(v) == Series
isinstance(v, Series0

2017-08-17 10:22 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- :func:`DataFrame.items` is present in both Python 2 and 3 and is lazy in all cases (:issue:`13918`, :issue:`17213`)
is now present.

2017-08-19 20:35 UTC, tacaswell commented
ping @jreback all green!

2017-08-19 20:36 UTC, tacaswell commented
sigh, just force-pushed a spelling correction to the docs.

2017-08-19 21:58 UTC, jreback approved these changes

2017-08-19 21:59 UTC, merged

2017-08-19 21:59 UTC, jreback commented
thanks!