COMPAT: avoid calling getsizeof() on PyPy
pandas-dev/pandas pull request #17229
Opened 2017-08-11 12:58 UTC by mattip

WIP Relates to issue #17228, this is a simple possible solution to the issue. Not sure this approach is the best, perhaps ``deep=True`` should raise on PyPy?

2017-08-11 12:58 UTC, pep8speaks commented
Hello @mattip! Thanks for submitting the PR.



 - In the file [`pandas/core/indexes/multi.py`](https://github.com/pandas-dev/pandas/blob/045a341077b73045376938080dea5c13b54ead08/pandas/core/indexes/multi.py), following are the PEP8 issues :

> [Line 470:21](https://github.com/pandas-dev/pandas/blob/045a341077b73045376938080dea5c13b54ead08/pandas/core/indexes/multi.py#L470): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment



 - In the file [`pandas/tests/frame/test_repr_info.py`](https://github.com/pandas-dev/pandas/blob/045a341077b73045376938080dea5c13b54ead08/pandas/tests/frame/test_repr_info.py), following are the PEP8 issues :

> [Line 337:80](https://github.com/pandas-dev/pandas/blob/045a341077b73045376938080dea5c13b54ead08/pandas/tests/frame/test_repr_info.py#L337): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

2017-08-11 13:08 UTC, chris-b1 commented
My first instinct would be to `raise` on PyPy with `deep=True` rather than stubbing a value, but don't feel strongly about it.

2017-08-11 13:08 UTC, chris-b1 commented on pandas/core/base.py
> +IS_PYPY = platform.python_implementation() == 'PyPy'
This can go in `pandas.compat`

2017-08-12 16:12 UTC, jreback commented
not a big fan of downstream having to deal with this. I suppose using the default argument is ok.

2017-08-12 17:40 UTC, jreback commented on pandas/util/testing.py
> +import platform
don't define this, just import from ``pandas.compat`` where you need it

2017-08-12 17:41 UTC, jreback commented
pls add a whatsnew note in bug fixes maybe conversion section. ping on green.

2017-08-12 21:02 UTC, mattip commented
@jreback ping. I added ``if PYPY`` conditional testing rather than just skipping entirely on PyPy where appropriate, those tests pass on PyPy too (PyPy latest nightly + Numpy HEAD is down to 44 failures).

2017-08-14 10:18 UTC, jreback requested changes
lgtm. some doc / testing comments.

2017-08-14 10:18 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Add a ``default`` argument to ``sys.getsizeof`` used in ``memory_usage`` to support PyPy. Objects on PyPy do not have a
spelling, remove the word guess. remove reference to ``sys.getsizeof``, this is not user visible.

2017-08-14 10:18 UTC, jreback commented on pandas/core/indexes/multi.py
> +        objsize = 24  # for implementations with no useful getsizeof (PyPy)
put comments on a separate line (and skip a line)

2017-08-14 10:18 UTC, jreback commented on pandas/core/indexes/range.py
> +        """ return the number of bytes in the underlying data
formatting, line up on the triple quote

2017-08-14 10:18 UTC, jreback commented on pandas/tests/frame/test_repr_info.py
> -            index=True).sum())
split into 2 tests, 1 for PYPY 1 for existing (skip for PYPY on existing, skip if not PYPY on other test)

2017-08-15 06:12 UTC, mattip commented
@jreback updated pull request according to the review

2017-08-15 10:31 UTC, jreback approved these changes

2017-08-15 10:32 UTC, closed without merging

2017-08-15 10:32 UTC, jreback commented
thanks @mattip

2017-08-15 14:59 UTC, mattip commented
thanks @jreback, @chris-b1. It is a pleasure to interact with such a responsive community