Make pd.Period immutable
pandas-dev/pandas pull request #17239
Opened 2017-08-13 03:05 UTC by jbrockmendel

Follows @jreback 's suggestion in #17116 to define `_Period.ordinal` and `_Period.freq` as `def readonly` attributes.  This requires massaging `__new__/__init__` a bit.

Adds a quick test that these attributes can't be changed.

Note that this doesn't fully solve the issue of Periods being immutable because `per.freq` is a `DateOffset` object which itself can be messed with.

- [ ] closes #
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-08-13 03:05 UTC, pep8speaks commented
Hello @jbrockmendel! Thanks for submitting the PR.

 - In the file [`pandas/tests/test_lib.py`](https://github.com/pandas-dev/pandas/blob/891228347688e6b311b28c2159be8ba69f7b62e2/pandas/tests/test_lib.py), following are the PEP8 issues :

> [Line 260:21](https://github.com/pandas-dev/pandas/blob/891228347688e6b311b28c2159be8ba69f7b62e2/pandas/tests/test_lib.py#L260): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator

2017-08-14 10:14 UTC, jreback requested changes
add a whatsnew note in API breaking changes.

2017-08-14 10:14 UTC, jreback commented on pandas/tests/test_lib.py
> +    per = pd.Period('2014Q1')
add the issue number here. move test to tests for period scalars.

2017-08-14 10:14 UTC, jreback commented on pandas/_libs/period.pyx
> +# this is _libs.src.datetime, not python stdlib
don't add superfluous comments

2017-08-14 18:14 UTC, jbrockmendel commented on pandas/tests/test_lib.py
> +    per = pd.Period('2014Q1')
Sure.

2017-08-14 18:16 UTC, jbrockmendel commented on pandas/_libs/period.pyx
> +# this is _libs.src.datetime, not python stdlib
Similar comments exist elsewhere e.g. in lib.pyx:

```
# this is our tseries.pxd
from datetime cimport *
```

This name overlap is an easy source of confusion.

Not worth arguing about so I'll change it.  Just sayin'.

2017-08-19 20:06 UTC, MaximilianR commented on pandas/_libs/period.pyx
> +            self = _Period.__new__(cls, ordinal, freq)
Should this be `self = cls.__new__...`?

2017-08-19 20:25 UTC, jbrockmendel commented on pandas/_libs/period.pyx
> +            self = _Period.__new__(cls, ordinal, freq)
I don't think so.  `cls._from_ordinal` gets called at the end of `Period.__new__`, so I expect it explicitly needs to be `_Period`.

2017-08-20 13:46 UTC, jreback requested changes

2017-08-20 13:46 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +pd.Period objects are now immutable
just say Period

2017-08-20 13:46 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +assign a new value to the `ordinal` or `freq` attributes.  This will allow
you dont need to provide an explanation.

2017-08-23 12:04 UTC, jreback requested changes

2017-08-23 12:04 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +=======
extra line here. IIRC I told you to make a sub-section, but let's move this back to just a single line (still in API breaking change)

2017-08-23 12:27 UTC, jorisvandenbossche commented on pandas/tests/scalar/test_period.py
> +    with pytest.raises(AttributeError, message="is not writable"):
the `message="is not writable"` is not needed here, the default assertion message of pytest is normally clear.

If you actually want to check the message of the AttributeError, it is the `match` keyword you need to use, not `message` (but I don't think it is needed to test that, it is not a custom error message we write ourselves)

2017-08-23 18:30 UTC, jbrockmendel commented on pandas/tests/scalar/test_period.py
> +    with pytest.raises(AttributeError, message="is not writable"):
Pushing change now.

2017-08-23 18:36 UTC, jbrockmendel commented on doc/source/whatsnew/v0.21.0.txt
> +=======
OK.  RST is another area where I'm figuring it out as I go.  About to push a change that _I think_ corresponds to what you're saying.

2017-08-23 23:16 UTC, jreback requested changes

2017-08-23 23:16 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +:class:`Period` will now raise an ``AttributeError`` when a user tries to assign a new value to the `ordinal` or `freq` attributes (:issue:`17116`).
no what I meant was remove this as a sub-section and just add it as a single like in other breaking changes.

2017-08-23 23:45 UTC, jbrockmendel commented on doc/source/whatsnew/v0.21.0.txt
> +:class:`Period` will now raise an ``AttributeError`` when a user tries to assign a new value to the `ordinal` or `freq` attributes (:issue:`17116`).
All the other breaking changes have a subsection like:

```
.. _whatsnew_0210.api_breaking.pandas_eval:

Improved error handling during item assignment in pd.eval
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'll keep pushing guesses until the Infinite Monkeys Theorem kicks in.

2017-08-24 08:21 UTC, jorisvandenbossche commented on doc/source/whatsnew/v0.21.0.txt
> +:class:`Period` will now raise an ``AttributeError`` when a user tries to assign a new value to the `ordinal` or `freq` attributes (:issue:`17116`).
Still not fully what he meant :-) 

The "Backwards incompatible API changes" section starts with subsections for things that we think are important enough to explain in more than a single line, and at the end there is section "other API changes" with a bunch of single entries:

https://github.com/jbrockmendel/pandas/blob/19567c8f0de212dec15e17dc918e6eada6a8c354/doc/source/whatsnew/v0.21.0.txt#L280-L295

So you can put it there.

2017-08-24 08:22 UTC, jorisvandenbossche approved these changes
apart from the small move in whatsnew, +1 to merge

2017-08-24 10:03 UTC, merged

2017-08-24 10:03 UTC, jreback commented
thanks!