BUG: Cannot use tz-aware origin in to_datetime (#16842)
pandas-dev/pandas pull request #17244
Opened 2017-08-14 08:02 UTC by step4me

- [x] closes #16842 
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2017-08-14 08:02 UTC, pep8speaks commented
Hello @step4me! Thanks for submitting the PR.

 - In the file [`pandas/core/tools/datetimes.py`](https://github.com/pandas-dev/pandas/blob/5ab75f0434a65a70d84ef693a91dd0d3d8c855dc/pandas/core/tools/datetimes.py), following are the PEP8 issues :

> [Line 494:51](https://github.com/pandas-dev/pandas/blob/5ab75f0434a65a70d84ef693a91dd0d3d8c855dc/pandas/core/tools/datetimes.py#L494): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 494:53](https://github.com/pandas-dev/pandas/blob/5ab75f0434a65a70d84ef693a91dd0d3d8c855dc/pandas/core/tools/datetimes.py#L494): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals

 - In the file [`pandas/tests/tseries/test_timezones.py`](https://github.com/pandas-dev/pandas/blob/5ab75f0434a65a70d84ef693a91dd0d3d8c855dc/pandas/tests/tseries/test_timezones.py), following are the PEP8 issues :

> [Line 210:80](https://github.com/pandas-dev/pandas/blob/5ab75f0434a65a70d84ef693a91dd0d3d8c855dc/pandas/tests/tseries/test_timezones.py#L210): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)

2017-08-14 10:20 UTC, jreback requested changes

2017-08-14 10:20 UTC, jreback commented on pandas/tests/tseries/test_timezones.py
> +    def test_timestamp_to_datetime_tzinfo(self):
tests for this are in  ``pandas/tests/indexes/datetimes/test_tools.py``

2017-08-14 10:20 UTC, jreback commented on pandas/core/tools/datetimes.py
> +            origin_ts = tslib.Timestamp(origin)
I would not do this, rather fail with a better error message.

2017-08-15 10:23 UTC, jreback requested changes

2017-08-15 10:23 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
>  - Bug in :func:`unique` where checking a tuple of strings raised a ``TypeError`` (:issue:`17108`)
``origin`` kwarg

2017-08-15 10:23 UTC, jreback commented on pandas/core/tools/datetimes.py
> +        if origin.tzinfo is not None:
this incorrectly raises on strings that are convertible to a Timestamp.

change to something like

```
# the existing try block, but move the subtraction out
try:
    offset = tslib.Timestamp(origin)
except OutOfBounds:
    ....
except ValueError:
  ...
```

then
```
if offset.tz is not None:
    raise ValueError # nice message about timezones

offset -= tslib.Timestamp(0)
```

2017-08-15 13:03 UTC, step4me commented
@jreback Thanks jreback, I edited files to reflect your comments. But I don't know why "all ci checks have failed".

2017-08-15 14:28 UTC, step4me commented
@jreback I found ci error message about <from datetime import timezone>. ImportError: cannot import name timezone in python 2.7. So, I edited "datetime(....., tzinfo=pytz.utc)"

2017-08-16 13:08 UTC, jorisvandenbossche approved these changes

2017-08-16 13:08 UTC, jorisvandenbossche commented on doc/source/whatsnew/v0.21.0.txt
> +- Bug in :func:`to_datetime` that cannot use tz-aware origin kwarg (:issue:`16842`)
I don't think this really relfects the issues, as it sounds like it will now work (while the error message was just clarified)

2017-08-17 01:17 UTC, step4me commented on doc/source/whatsnew/v0.21.0.txt
> +- Bug in :func:`to_datetime` that cannot use tz-aware origin kwarg (:issue:`16842`)
thanks, @jorisvandenbossche  I understand. I just wrote title of issue #16842. Then, should I edit like "Bug in :func:`to_datetime` that cannot use tz-aware origin kwarg raised a ``ValueError``"?

2017-08-17 22:57 UTC, jorisvandenbossche commented on doc/source/whatsnew/v0.21.0.txt
> +- Bug in :func:`to_datetime` that cannot use tz-aware origin kwarg (:issue:`16842`)
Or something like "tz-aware timestamp passed to to_datetime origin kwarg now raises correct ValueError"

2017-08-24 12:59 UTC, closed without merging

2017-08-24 12:59 UTC, jreback commented
thanks!