Issue14042
pandas-dev/pandas pull request #17255
Opened 2017-08-15 08:12 UTC by wooyekim

Root cause: When a DatetimeIndex is created by __array_wrap__,
round-trip of timezone occured

Solution: Remove the timezone of the original index when creating
a DatetimeIndex via __array_wrap__ and apply the timezone later

- [x] closes #14042
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2017-08-15 10:14 UTC, jreback requested changes

2017-08-15 10:14 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Fixes bug for ``numpy.split`` on pandas dataframe with non-utc timezone (:issue:`14042`)
bug in numpy array_wrap with a pandas Series/Index.

2017-08-15 10:14 UTC, jreback commented on pandas/core/indexes/base.py
> +        from pandas.core.indexes.datetimes import DatetimeIndex
add this

```
diff --git a/pandas/core/indexes/base.py b/pandas/core/indexes/base.py
index de6221987..865e92201 100644
--- a/pandas/core/indexes/base.py
+++ b/pandas/core/indexes/base.py
@@ -99,6 +99,9 @@ def _new_Index(cls, d):
     if issubclass(cls, ABCPeriodIndex):
         from pandas.core.indexes.period import _new_PeriodIndex
         return _new_PeriodIndex(cls, **d)
+    elif issubclass(cls, ABCDatetimeIndex):
+        from pandas.core.indexes.datetimes import _new_DatetimeIndex
+        return _new_DatetimeIndex(cls, **d)
     return cls.__new__(cls, **d)
``` 

then you can simply call
return _new_Index(result attrs)

2017-08-15 10:14 UTC, jreback commented on pandas/tests/indexes/datetimes/test_datetime.py
> +        # https://github.com/pandas-dev/pandas/issues/14042
add a 1-liner about what you are testing here

2017-08-15 10:14 UTC, jreback commented on pandas/tests/indexes/datetimes/test_datetime.py
> +        split = np.split(idx, indices_or_sections=[])
use an ``tm.assert_index_equal`` and test for each piece.

Also test using a ``Series`` (can be here is ok)

2017-08-15 10:14 UTC, jreback commented on pandas/tests/indexes/datetimes/test_datetime.py
> +        split = np.split(idx, indices_or_sections=[])
ideally we could exercise more numpy ufuncs for 1d reshaping ops here as well.

2017-08-15 14:52 UTC, wooyekim commented on pandas/tests/indexes/datetimes/test_datetime.py
> +        split = np.split(idx, indices_or_sections=[])
I found that Series does not suffer from this issue. But I'll leave the testcase.

2017-08-15 15:09 UTC, pep8speaks commented
Hello @wooyekim! Thanks for updating the PR.



 - In the file [`pandas/tests/indexes/datetimes/test_datetime.py`](https://github.com/pandas-dev/pandas/blob/d0590579f22033367e2b1be612e7490aec2e2574/pandas/tests/indexes/datetimes/test_datetime.py), following are the PEP8 issues :

> [Line 791:67](https://github.com/pandas-dev/pandas/blob/d0590579f22033367e2b1be612e7490aec2e2574/pandas/tests/indexes/datetimes/test_datetime.py#L791): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 791:69](https://github.com/pandas-dev/pandas/blob/d0590579f22033367e2b1be612e7490aec2e2574/pandas/tests/indexes/datetimes/test_datetime.py#L791): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 793:65](https://github.com/pandas-dev/pandas/blob/d0590579f22033367e2b1be612e7490aec2e2574/pandas/tests/indexes/datetimes/test_datetime.py#L793): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 793:70](https://github.com/pandas-dev/pandas/blob/d0590579f22033367e2b1be612e7490aec2e2574/pandas/tests/indexes/datetimes/test_datetime.py#L793): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 793:72](https://github.com/pandas-dev/pandas/blob/d0590579f22033367e2b1be612e7490aec2e2574/pandas/tests/indexes/datetimes/test_datetime.py#L793): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator

2017-08-18 00:43 UTC, jreback requested changes

2017-08-18 00:43 UTC, jreback commented on pandas/core/indexes/base.py
> +        from pandas.core.dtypes.generic import ABCDatetimeIndex
not sure if you saw my comment. pls move this logic to ``_new_Index`` (and the import can be at the top of the file)

2017-09-13 01:19 UTC, jreback commented
can you rebase / update

2017-10-28 15:52 UTC, jreback requested changes
can you rebase

2017-10-28 15:52 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
>  - Allow unicode empty strings as placeholders in multilevel columns in Python 2 (:issue:`17099`)
move to 0.21.1

2017-10-29 14:50 UTC, closed without merging