BUG: fillna returns frame when inplace=True if value is a dict (#16156)
pandas-dev/pandas pull request #17279
Opened 2017-08-18 09:29 UTC by ante328

- [x] closes #16156
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2017-08-18 09:29 UTC, pep8speaks commented
Hello @ante328! Thanks for submitting the PR.

 - In the file [`pandas/core/generic.py`](https://github.com/pandas-dev/pandas/blob/9af801ab668d98c84ba0da246a9041dcc62d212c/pandas/core/generic.py), following are the PEP8 issues :

> [Line 4058:1](https://github.com/pandas-dev/pandas/blob/9af801ab668d98c84ba0da246a9041dcc62d212c/pandas/core/generic.py#L4058): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

 - In the file [`pandas/tests/frame/test_missing.py`](https://github.com/pandas-dev/pandas/blob/9af801ab668d98c84ba0da246a9041dcc62d212c/pandas/tests/frame/test_missing.py), following are the PEP8 issues :

> [Line 410:38](https://github.com/pandas-dev/pandas/blob/9af801ab668d98c84ba0da246a9041dcc62d212c/pandas/tests/frame/test_missing.py#L410): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'

2017-08-18 10:02 UTC, jreback requested changes
lgtm. doc comment.

2017-08-18 10:02 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Bug in :func: `fillna` returns frame when ``inplace=True`` and ``value`` is dict (:issue:`16156`)
`` :func:`Series.fillna` ``

move to conversions.

2017-08-21 12:12 UTC, ante328 commented on doc/source/whatsnew/v0.21.0.txt
> +- Bug in :func: `fillna` returns frame when ``inplace=True`` and ``value`` is dict (:issue:`16156`)
done

2017-08-21 23:54 UTC, jreback approved these changes

2017-08-21 23:55 UTC, merged

2017-08-21 23:55 UTC, jreback commented
thanks!