Remove inline declarations in pxd files
pandas-dev/pandas pull request #17277
Opened 2017-08-18 05:46 UTC by jbrockmendel

At the moment (I think since .26, not sure) they don't do anything but cause lots of warnings during cythonizing.  Eventually they will raise errors.

https://github.com/cython/cython/issues/1706#issuecomment-302347613

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-08-18 05:48 UTC, gfyoung approved these changes

2017-08-18 09:56 UTC, jreback commented
this would need a performance check. older versions of cython may respect this directive.

2017-08-18 09:57 UTC, jreback requested changes
this likely has much worse performance in most scenarios.

2017-08-18 09:59 UTC, jreback commented on pandas/_libs/src/khash.pxd
> +    void kh_destroy_pymap(kh_pymap_t*)
these *are* c-functions

2017-08-18 09:59 UTC, jreback commented on pandas/_libs/hashtable.pxd
> -    cdef inline void _check_for_collision(self, Py_ssize_t loc, object label)
this prob should be implemented in the .pxd file; its called a lot

2017-08-18 10:00 UTC, jreback commented
The comment above only seems to apply to *cython* defintiion, NOT c definitions.

2017-08-18 19:54 UTC, jbrockmendel commented
> The comment above only seems to apply to cython defintiion, NOT c definitions.

OK, then this is moving outside my competence zone.  We can wait until it starts raising errors and fix it then.

2017-08-18 22:25 UTC, jorisvandenbossche commented on pandas/_libs/src/khash.pxd
> +    void kh_destroy_pymap(kh_pymap_t*)
But they still trigger the warning when building. So apparently that does not matter

2017-08-19 16:49 UTC, jreback commented
ok, as I said its new in cython 0.26 if you want to specifically address some things great. but will need performance checking.

2017-08-19 16:49 UTC, closed without merging

2017-08-19 17:11 UTC, jorisvandenbossche commented on pandas/_libs/hashtable.pxd
> -    cdef inline void _check_for_collision(self, Py_ssize_t loc, object label)
Is it correct that `_check_for_collisions` is only used in `hashtable.pyx` itself? (or in the included template files) 
If so, I think we can just remove it here from the pxd file altogether (it is already defined as inline in hashtable itself)

2017-08-19 17:13 UTC, jorisvandenbossche commented on pandas/_libs/src/khash.pxd
> +    void kh_destroy_pymap(kh_pymap_t*)
Based on the comment in the cython issues, I understand that those will not be inlined anyhow when used in another cython module (d57f51a707da5d9944dcb58530d44b3d842229ea)