BUG: Index._searchsorted_monotonic(..., side='right') returns the left side position for monotonic decreasing indexes
pandas-dev/pandas pull request #17272
Opened 2017-08-17 18:55 UTC by jschendel

- [X] closes #17271
- [X] closes #16417
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

I didn't add a whatsnew entry for the `Index._searchsorted_monotonic` fix, since it looks like past convention has been to not add whatsnew entries for private methods.  Happy to add a whatsnew entry if I'm mistaken though.  I did add a whatsnew entry for the downstream effect on IntervalIndex.

2017-08-17 19:00 UTC, gfyoung commented
> since it looks like past convention has been to not add whatsnew entries for private methods.

That is correct.

2017-08-18 00:41 UTC, jreback requested changes

2017-08-18 00:41 UTC, jreback commented on pandas/tests/indexes/test_base.py
> +        idx_dec = Index([4, 2, 0])
would be better to move these to ``common.py/Base`` as they be tested generically.

2017-08-18 00:41 UTC, jreback commented on pandas/tests/indexing/test_interval.py
> +        # test endpoint of non-overlapping monotonic decreasing (GH16417)
I would instead make a specific test of this (also test increasing monotonic), even better would be to parametrize over closed (bonus points)

2017-08-21 01:51 UTC, jschendel commented
Notes regarding the review changes I made:

- Removed some redundant checks from `test_loc_with_scalar` and `test_getitem_with_scalar` in `test_interval.py`, as these checks are now being handled by `test_nonoverlapping_monotonic`  (the index used in the two former tests is nonoverlapping monotonic increasing).

- Added some monotonic decreasing indexes to `setup_method` to various test classes within in order to ensure that monotonic decreasing indexes are fully tested by `common.py/test_searchsorted_monotonic` (and other tests).
   - Had to change ` tm.assert_numpy_array_equal` to `tm.equalContents` in `common.py/test_difference_base`.  Introducing a decreasing sequence led to the test failing with ` tm.assert_numpy_array_equal` due to different sorting of the result and expected answer.  If keeping ` tm.assert_numpy_array_equal` is preferable, the arrays could be sorted prior to using it.
   -  Did not add a monotonic decreasing index to `test_range`, as it currently fails `common.py/test_intersection_base`  due to the issue described in #17296 (will add when I submit a PR for this issue).

2017-08-21 01:58 UTC, jreback commented
> Had to change tm.assert_numpy_array_equal to tm.equalContents in common.py/test_difference_base. Introducing a decreasing sequence led to the test failing with tm.assert_numpy_array_equal due to different sorting of the result and expected answer. If keeping tm.assert_numpy_array_equal is preferable, the arrays could be sorted prior to using it.

yes, pls just sort them if need; we don't use ``tm.equalContents`` (actually should remove that)


> Did not add a monotonic decreasing index to test_range, as it currently fails common.py/test_intersection_base due to the issue described in #17296 (will add when I submit a PR for this issue).

simply add an xfailing test (with the issue number).

2017-08-21 02:32 UTC, jschendel commented
Okay, made those additional changes.  Any idea why codecov is saying this will decrease coverage by 50%?  I don't think I made any substantial changes that would cause that.  Just a glitch?

2017-08-23 03:31 UTC, jschendel commented
ping @jreback : made review related updates and did a rebase to resolve merge conflicts

2017-08-23 12:01 UTC, jreback requested changes

2017-08-23 12:01 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Bug in ``IntervalIndex`` where performing a scalar lookup fails for included right endpoints of non-overlapping monotonic decreasing indexes (:issue:`16417`)
can you add both issue numbers

2017-08-23 12:01 UTC, jreback commented on pandas/tests/indexes/common.py
> +                assert index._searchsorted_monotonic(value, side='left') == 0
can you test ``.searchsorted()`` as well for the various cases

2017-08-23 12:01 UTC, jreback commented on pandas/tests/indexing/test_interval.py
> +                                     ('left', 'right', 'neither', 'both')))
@zfrenchee if you'd have a look here

2017-08-25 05:22 UTC, jschendel commented
Made the requested changes.  A couple comments:

- Only tested `.searchsorted` for monotonic increasing, since that's the underlying assumption.
- Added an index with repeats to `test_base` to better test `side='right'` for `_searchsorted_monotonic` and `.searchsorted`.
   - Required a modifying `test_get_indexer_consistency` to check uniqueness in one place where uniqueness was assumed.
- Moved the xfail for `test_intersection_base` to only occur for `RangeIndex`, since that's the only type of index that should fail.

2017-08-25 11:30 UTC, jreback requested changes
minor request. lgtm. ping on green.

2017-08-25 11:30 UTC, jreback commented on pandas/tests/indexes/common.py
> +                assert indexer.dtype == np.intp
can you add what the result if not index.is_unique as well

2017-08-25 21:24 UTC, jschendel commented
ping @jreback : checks are green

Made one small additional change to the `index.is_unique` case.  Since `get_indexer` is implemented slightly differently for `CategoricalIndex` relative to other indexes, they're actually fine even if the values in the index aren't unique, so they fell into the `index.is_unique` case regardless of uniqueness.

2017-08-29 20:35 UTC, jschendel commented
ping @jreback : green again after rebasing to address the merge conflict.

2017-09-07 11:48 UTC, jreback approved these changes

2017-09-07 11:49 UTC, merged

2017-09-07 11:49 UTC, jreback commented
thanks @jschendel nice fixes! keep em coming!

2020-12-06 03:59 UTC, jbrockmendel commented on pandas/tests/indexes/common.py
> +            if index.is_unique or isinstance(index, CategoricalIndex):
@jschendel why is CategoricalIndex excluded here?