BUG: Fix strange behaviour of Series.iloc on MultiIndex Series (#17148)
pandas-dev/pandas pull request #17291
Opened 2017-08-19 15:06 UTC by ante328

- [x] closes #17148
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2017-08-19 16:52 UTC, jreback requested changes

2017-08-19 16:52 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Bug ``Series`` with ``MultiIndex`` gives surprising ``.iloc`` results when an integer indexer is used (:issue: `17148`)
needs to be a bit more explicit as this covers several cases.

2017-08-19 16:52 UTC, jreback commented on pandas/core/indexing.py
> +        if isinstance(axis, MultiIndex) and not isinstance(key, int):
use ``is_integer``

2017-08-19 16:52 UTC, jreback commented on pandas/tests/indexing/test_iloc.py
> +        df = pd.DataFrame(data=[[1, 2, 5], [1, 3, 6]], columns=['i', 'j', 'k'])
make a new test
add the issue number as a comment.

pls test all cases brought up.

2017-08-19 17:33 UTC, jreback commented on pandas/core/indexing.py
> +        if isinstance(axis, MultiIndex) and not isinstance(key, int):
also this should *only* be true if ``self.name == 'iloc'``, IOW we have a positional indexer.

2017-08-19 22:17 UTC, ante328 commented on pandas/tests/indexing/test_iloc.py
> +        df = pd.DataFrame(data=[[1, 2, 5], [1, 3, 6]], columns=['i', 'j', 'k'])
Thanks for the quick feedback! think its all fixed now

2017-08-20 07:45 UTC, ante328 commented on pandas/core/indexing.py
> +        if isinstance(axis, MultiIndex) and not isinstance(key, int):
Should I change `not is_integer(key)` to `self.name != 'iloc'`?

2017-08-20 13:42 UTC, jreback requested changes

2017-08-20 13:42 UTC, jreback commented on pandas/tests/indexing/test_iloc.py
> +        check_scenario(
parametrize this test

2017-08-20 13:42 UTC, jreback commented on pandas/core/indexing.py
> +        if isinstance(axis, MultiIndex) and not is_integer(key):
use ``self.name != 'iloc'``, and use a tests that fails this (IOW a MultiIndex with an integer first level that does not match the positions)

2017-08-20 13:42 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Bug in :func:`Series.iloc` when used with inplace addition or assignment and an int indexer on a ``MultiIndex`` ``Series`` causing the wrong indexes to be read from and written to (:issue:`17148`)
its a bug in ``.iloc`` not restricted to Series

2017-08-20 19:50 UTC, jreback requested changes
does this hit all 3 cases in the issue? (can you enumerate them in the test)

2017-08-20 19:50 UTC, jreback commented on pandas/tests/indexing/test_iloc.py
> +        df.set_index(['i', 'j'], inplace=True)
``df = df.set_index(...)``, don't use inplace in testing code.

2017-08-20 19:50 UTC, jreback commented on pandas/tests/indexing/test_iloc.py
> +        df.k = expected_k
``df['k'] = expected_k``

2017-08-20 19:50 UTC, jreback commented on pandas/tests/indexing/test_iloc.py
> +        expected = df.k.copy()
this copy is necessary?

2017-08-21 10:17 UTC, ante328 commented
I have been unable to recreate the error from the travis-ci test locally. The failed test doesn't hit the `_get_setitem_indexer` function when i run it here. Any tips on how to proceed are appreciated!

2017-08-22 14:03 UTC, ante328 commented
nvm is passes now

2017-08-22 14:31 UTC, jreback approved these changes

2017-08-22 14:31 UTC, merged

2017-08-22 14:31 UTC, jreback commented
thanks!