BUG: Set index when reading stata file
pandas-dev/pandas pull request #17328
Opened 2017-08-24 16:08 UTC by bashtage

Ensures index is set when requested when reading state dta file

closes #16342

- [x] closes #16342
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2017-08-24 16:15 UTC, gfyoung commented on pandas/io/stata.py
> +            index = self._index
Do we have tests that hit this path?

2017-08-24 16:25 UTC, bashtage commented on pandas/io/stata.py
> +            index = self._index
Added in PR

2017-08-25 15:38 UTC, TomAugspurger commented
Did we want to change the keyword from `index` to `index_col` to match `read_csv`?

2017-08-25 16:07 UTC, bashtage commented
Probably a good idea.

2017-08-25 16:08 UTC, bashtage commented
Does this need deprecation?

2017-08-25 16:08 UTC, bashtage commented
Last one, is there a pattern to follow for renaming (e.g. a decorator, *kwargs, etc)

2017-08-25 16:12 UTC, TomAugspurger commented
Yeah, there's an `@deprecate_kwarg` decorator somewhere. Honestly not sure about whether it needs a deprecation, since the old one didn't do anything, but we may as well.

2017-08-25 16:13 UTC, TomAugspurger commented
It's in `pandas/util/_decorators` btw.

2017-08-28 11:48 UTC, bashtage commented
I went ahead and did the insta-deprecate.

2017-08-29 17:06 UTC, jreback requested changes
minor comments. can you deprecate ``index`` (and direct to ``index_col``) as well.

2017-08-29 17:06 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Renamed non-functional `index` to `index_col` in :func:`read_stata` to improve API consistency (:issue:`16342`)
can you use double backticks here (around index,index_col)

2017-08-29 17:06 UTC, jreback commented on pandas/tests/io/test_stata.py
> +        df = tm.makeDataFrame()
can you add the issue number

2017-08-29 18:34 UTC, TomAugspurger commented
> minor comments. can you deprecate index (and direct to index_col) as well.

Do we need a deprecation, or can we just "break" API here. `index=...` didn't work at all earlier, so I'm OK with just changing without a deprecation cycle.

2017-09-16 11:12 UTC, bashtage commented
@jreback @TomAugspurger I think this is GTG

2017-09-16 13:40 UTC, merged

2017-09-16 13:40 UTC, TomAugspurger commented
Thanks!