Fix typo that causes several NaT methods to have incorrect docstrings
pandas-dev/pandas pull request #17327
Opened 2017-08-24 15:47 UTC by jbrockmendel

This block of code exists to make NaT raise ValueError for each of a bunch of datetime methods. This is supposed to attach the original docstring to the new function f. The typo _method_name instead of func_name means that a bunch of the docstrings are currently wrong.

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-08-24 16:01 UTC, gfyoung commented
@jbrockmendel : Just for reference, can you show us a before and after for one of those functions?

2017-08-24 16:12 UTC, jbrockmendel commented
Take `ctime` as an example

Status quo:
```
>>> pd.NaT.ctime.__doc__
'\n        Total duration of timedelta in seconds (to ns precision)\n        '
```

After:
```
>>> pd.NaT.ctime.__doc__
'Return ctime() style string.'
```

2017-08-25 11:10 UTC, jreback requested changes
can you add a test using ctime for this. And a whatsnew note.

2017-08-29 13:11 UTC, jreback approved these changes
update whatsnew, ping on green. lgtm.

2017-08-29 13:11 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Several ``NaT`` method docstrings (e.g. :func:`NaT.ctime`) were incorrect
add the PR refernce

2017-08-29 17:04 UTC, merged

2017-08-29 17:04 UTC, jreback commented
thanks!