ENH - GH:17160, DataFrame.pivot accepts a list of values
pandas-dev/pandas pull request #17339
Opened 2017-08-25 19:58 UTC by BBQHarvey

- [ ] closes #17160
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-08-28 19:29 UTC, BBQHarvey commented
I can't figure out why the test_reindexing integration test failed. Can you give some instructions on how to proceed?

2017-08-28 19:31 UTC, gfyoung commented
@BBQHarvey : Don't worry about it.  #17355 will take care of it.

2017-10-28 15:42 UTC, jreback requested changes
pls rebase

2017-10-28 15:42 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
>  - :func:`pd.read_sas()` now recognizes much more of the most frequently used date (datetime) formats in SAS7BDAT files (:issue:`15871`).
move to 0.21.1

2017-11-25 16:15 UTC, jreback commented
closing as stale

2017-11-25 16:15 UTC, closed without merging