Remove property that re-computed microsecond;
pandas-dev/pandas pull request #17331
Opened 2017-08-24 23:12 UTC by jbrockmendel

just accessing the already-existing attribute is about 10x faster than re-computing it

This accounts for the discrepancy discussed in #17234 (https://github.com/pandas-dev/pandas/pull/17297#pullrequestreview-57686247)

Per requests from @jreback, I'm refraining from moving forward with any other optimizations that this makes possible (e.g. removing the roundabout call to `convert_to_tsobject` from `Timestamp.to_pydatetime`).

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-08-24 23:22 UTC, gfyoung commented
@jbrockmendel : Could you post performance metrics in this PR just for reference?

2017-08-24 23:37 UTC, jbrockmendel commented
See update above.

2017-08-25 04:39 UTC, jbrockmendel commented
The error on Travis here is identical to the one in #17318.  I can't reproduce it locally in either branch.  Is it plausible that the issue is with Travis?

2017-08-25 11:16 UTC, jreback commented
> The error on Travis here is identical to the one in #17318. I can't reproduce it locally in either branch. Is it plausible that the issue is with Travis?

No, the issue is here: https://github.com/pandas-dev/pandas/issues/17323

2017-08-25 11:17 UTC, jreback requested changes
needs a whatsnew note and asv (and add asv for all Timestamp properties)

2017-08-25 16:43 UTC, pep8speaks commented
Hello @jbrockmendel! Thanks for updating the PR.

 - In the file [`asv_bench/benchmarks/timestamp.py`](https://github.com/pandas-dev/pandas/blob/26c0980d4401e1963b6edb1419dbadbed683db67/asv_bench/benchmarks/timestamp.py), following are the PEP8 issues :

> [Line 13:1](https://github.com/pandas-dev/pandas/blob/26c0980d4401e1963b6edb1419dbadbed683db67/asv_bench/benchmarks/timestamp.py#L13): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 61:1](https://github.com/pandas-dev/pandas/blob/26c0980d4401e1963b6edb1419dbadbed683db67/asv_bench/benchmarks/timestamp.py#L61): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2017-08-25 16:45 UTC, jbrockmendel commented
Just pushed with asv and note in whatsnew.  Two runs of asv results:

```
[100.00%] ··· Running timestamp.TimestampProperties.time_weekday_name                                                                                                                                                                                     26.8±0.9μs       before           after         ratio
     [96f92eb1]       [48a59233]
+        34.7±1μs        70.6±10μs     2.03  timestamp.TimestampProperties.time_is_quarter_end
+      34.4±0.8μs         57.4±2μs     1.67  timestamp.TimestampProperties.time_is_quarter_start
+        35.7±2μs         49.9±2μs     1.40  timestamp.TimestampProperties.time_is_year_end
+     1.18±0.02μs      1.58±0.05μs     1.35  timestamp.TimestampProperties.time_freqstr
+      31.5±0.4μs       38.8±0.3μs     1.23  timestamp.TimestampProperties.time_is_month_end
+      30.7±0.5μs         37.7±1μs     1.23  timestamp.TimestampProperties.time_days_in_month
+      33.3±0.6μs         38.8±1μs     1.17  timestamp.TimestampProperties.time_is_month_start
-      30.6±0.8μs         473±10ns     0.02  timestamp.TimestampProperties.time_microsecond
```

```
[100.00%] ··· Running timestamp.TimestampProperties.time_weekday_name                                                                                                                                                                                     30.2±0.7μs       before           after         ratio
     [96f92eb1]       [48a59233]
-        27.0±2μs       20.5±0.5μs     0.76  timestamp.TimestampProperties.time_week
-        399±20ns          301±8ns     0.75  timestamp.TimestampProperties.time_tz
-        27.8±6μs       20.6±0.4μs     0.74  timestamp.TimestampProperties.time_quarter
-        36.3±4μs       23.5±0.8μs     0.65  timestamp.TimestampProperties.time_is_year_end
-      30.2±0.7μs       15.4±0.3μs     0.51  timestamp.TimestampProperties.time_weekday_name
-      22.7±0.7μs          239±8ns     0.01  timestamp.TimestampProperties.time_microsecond
```

`microsecond` is the only one that I _should_ be changed, so it's reassuring that it is an order of magnitude bigger change than everything else.

2017-08-26 01:52 UTC, jbrockmendel commented
Looks like the Travis error is the same OSX error that is happening elsewhere.  The AppVeyor error message looked like an HTTP timeout.

2017-08-29 13:08 UTC, jreback requested changes

2017-08-29 13:08 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- `Timestamp.microsecond` no longer re-computes on attribute access.
add the PR number as the issue. we *always* want a reference to an entry in whatsnew (issue preferd, or PR if not avail).

2017-08-29 13:08 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- `Timestamp.microsecond` no longer re-computes on attribute access.
either use double-backticks, or `` :attr:`Timestamp.microsecond` `` (in general prefer the api references). I don't think this API reference will actually work ATM as ``Timestamp`` is not defined in api.rst (so separate issue to rectify that).

2017-08-29 14:26 UTC, jbrockmendel commented
What's the syntax for referencing a PR?  For an Issue I'd use ```(:issue:`17331`)```.  should I just replace "issue" with "pull" here?

2017-08-29 14:33 UTC, jreback commented
same syntax just use the pr number

2017-09-07 00:51 UTC, jreback approved these changes

2017-09-07 00:51 UTC, merged

2017-09-07 00:51 UTC, jreback commented
thanks!