BUG: Return local Timestamp.weekday_name attribute (#17354)
pandas-dev/pandas pull request #17377
Opened 2017-08-30 06:28 UTC by mroeschke

- [x] closes #17354
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

@jreback created a new method `_get_named_field` based on your [comment](https://github.com/pandas-dev/pandas/issues/17354#issuecomment-325319229) in the issue thread.

2017-08-30 10:28 UTC, jreback requested changes

2017-08-30 10:28 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Bug in ``Timestamp.weekday_name`` returning a UTC-based weekday name when localized to a timezone (:issue:`17354`)
you can do `` :func:`Timestamp.weekday_name` `` I think (might need to be attr actually)

2017-08-30 10:28 UTC, jreback commented on pandas/_libs/tslib.pyx
> +    cpdef _maybe_convert_value_to_local(self):
this can be just cdef and should return ``int64_t``

2017-08-30 10:28 UTC, jreback commented on pandas/_libs/tslib.pyx
> +        val = self._maybe_convert_value_to_local()
you can type val as ``cdef: int64_t`` (same for ``_get_named_field``)

2017-09-05 05:04 UTC, mroeschke commented
cdef'd `_maybe_convert_value_to_local` and `val` argument in related function and all green.

2017-09-05 10:22 UTC, jreback requested changes
some cdef comments. lgtm. ping when changed / pushed.

2017-09-05 10:22 UTC, jreback commented on pandas/_libs/tslib.pyx
> +        """Convert UTC i8 value to local i8 value if tz exists"""
you need to add a

```
cdef int64_t val
```

here in order to type it

2017-09-05 10:22 UTC, jreback commented on pandas/_libs/tslib.pyx
> +        cdef:
like this

2017-09-05 10:22 UTC, jreback commented on pandas/_libs/tslib.pyx
> +        val = self._maybe_convert_value_to_local()
if you can type out in these (ndarray[int32_t]) i think

2017-09-06 11:53 UTC, jreback commented on pandas/_libs/tslib.pyx
> +        date_array[0] = val
this is overkill to type the input ndarray itself

it was ``out`` which was looking to type, though not a big deal, so just remove the date_array temp. ping on green.

2017-09-07 00:46 UTC, jreback approved these changes

2017-09-07 00:46 UTC, merged

2017-09-07 00:46 UTC, jreback commented
thanks!