DOC: cleaned references to pandas v0.15 and v0.16 in docs
pandas-dev/pandas pull request #17442
Opened 2017-09-05 19:07 UTC by topper-123

Last round of cleanup of references to older pandas versions (here v0.15 and v0.16).

I'm not intending to go further up:  v0.16.2 was released in june 2015, and allowing up to 2 years old references to be seen in the docs themselves is reasonable IMO. (but other may have a different view, so if there's a "demand" I could change the cut-off point, its not so much work).

See also #17420 and #17404.

I also removed a reference to python 3.4  in the ``install.rst``. In  the same document, I also "updated" the test section to show python3.6 (just a (very) minor signal that pandas is python 3 positive).

2017-09-06 11:57 UTC, jreback requested changes
lgtm. some minor comments. ping when pushed / green.

2017-09-06 11:57 UTC, jreback commented on doc/source/io.rst
> +   pandas / ``PyTables`` >= 2.3 are fully compatible (this was the previous
you can take this out (about older PyTables)

2017-09-06 11:57 UTC, jreback commented on doc/source/install.rst
>      numpy version 1.10.2
iI would update the pandas  & numpy version here as well (you can just change the text) to something more current

2017-09-06 11:57 UTC, jreback commented on doc/source/install.rst
>      numpy version 1.10.2
actually this is from an older nose run, can you fix up to show what pytest prints.

2017-09-06 11:58 UTC, jreback commented
pls also add a whatsnew entry on Other Enhancements that docs are now updated to remove older references (and you can list the issue / PR's that were involved).

2017-09-07 00:47 UTC, topper-123 commented
ping @jreback

2017-09-07 01:00 UTC, jreback approved these changes

2017-09-07 01:00 UTC, merged

2017-09-07 01:01 UTC, jreback commented
thanks @topper-123 very nice series of changes!

when docs are built (could be a while), see http://pandas-docs.github.io/pandas-docs-travis/

and if anything needs corrections pls push a PR.

2017-09-07 02:14 UTC, topper-123 commented
Ok, I'll go look in a few days.

Yeah, these 3 commits have a net reduction in line count of ca. 330 lines, that's quite a bit of deadweight removed :-)