ENH: Add Styler.where
pandas-dev/pandas pull request #17474
Opened 2017-09-08 08:26 UTC by Licht-T

- [x] closes #16255
- [x] tests added / passed
Added `test_where_subset` in `pandas/tests/io/formats/test_style.py`.
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry
It makes the redundant style condition simple.
```python
df.style.applymap(lambda val: 'color: %s' % 'red' if val < 0 else 'black')
df.style.where(lambda val: val < 0, 'color: red', 'color: black')
```

2017-09-08 08:27 UTC, pep8speaks commented
Hello @Licht-T! Thanks for submitting the PR.



 - In the file [`pandas/tests/io/formats/test_style.py`](https://github.com/pandas-dev/pandas/blob/c3866562c49a79f6c0ca4ad8b1e25fc65723d903/pandas/tests/io/formats/test_style.py), following are the PEP8 issues :

> [Line 283:80](https://github.com/pandas-dev/pandas/blob/c3866562c49a79f6c0ca4ad8b1e25fc65723d903/pandas/tests/io/formats/test_style.py#L283): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)

2017-09-08 10:09 UTC, jreback requested changes
can you add a whatsnew note on Other Enahancements as well as use this in the notebook where appropriate

2017-09-08 10:09 UTC, jreback commented on pandas/io/formats/style.py
> +        accordance with the return value of a function.
add a versionadded tag

2017-09-08 10:09 UTC, jreback commented on pandas/io/formats/style.py
> +        """
defaults should be ``None`` not ``''``

2017-09-08 10:09 UTC, jreback commented on pandas/io/formats/style.py
> +        func : function
callable

2017-09-08 10:09 UTC, jreback commented on pandas/io/formats/style.py
> +        style1 : a style applied when ``func`` returns true
style1: str
    when applied......

2017-09-08 10:09 UTC, jreback commented on pandas/tests/io/formats/test_style.py
> +        def f(x):
add a comment with the issue number (this PR number)

2017-09-08 11:20 UTC, TomAugspurger commented on pandas/tests/io/formats/test_style.py
> +            expected = self.df.style.applymap(g, subset=slice_)._compute().ctx
These tests are fine, but could you add one test that checks the generated values directly against the dictionary?

2017-09-09 07:27 UTC, Licht-T commented
@jreback @TomAugspurger Thanks for your review. Fixed and made some new tests.

2017-09-09 16:08 UTC, Licht-T commented
Travis CI seems not work well due to its own error.
Could someone restart the Travis CI build?

2017-09-09 17:01 UTC, jreback approved these changes
this seems ok, @TomAugspurger . do we have a section in api.rst for things like this?

2017-09-09 17:01 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- :func:`Styler.where` has been implemented. It enables simple DataFrame styling on the Jupyter notebook (:issue:`17474`).
pls label this as a convenience for Styler.applymap

2017-09-09 17:01 UTC, jreback commented on pandas/io/formats/style.py
> +        func : callable
this should mimic the signature of ``DataFrame.where`` as much as possible

func -> cond
style1 -> value
style2 -> other

2017-09-10 05:00 UTC, Licht-T commented
@jreback Thanks for your suggestion. Fixed!

2017-09-10 14:26 UTC, jreback requested changes

2017-09-10 14:26 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- :func:`Styler.where` has been implemented. It is as a convenience for Styler.applymap and enables simple DataFrame styling on the Jupyter notebook (:issue:`17474`).
use ``:func:`Styler.applymap` `` as well

2017-09-10 14:26 UTC, jreback commented on pandas/io/formats/style.py
> +        self : Styler
can you add a ``See Also`` here (pointing to .applymap) and the reciprical one there

2017-09-10 14:26 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
``.where`` needs to be added to ``api.rst``

2017-09-10 14:49 UTC, Licht-T commented
@jreback Thanks. All is now fixed.

2017-09-10 15:05 UTC, TomAugspurger approved these changes

2017-09-11 00:01 UTC, jreback approved these changes

2017-09-11 00:01 UTC, merged

2017-09-11 00:02 UTC, jreback commented
thanks @Licht-T 

If you'd have a pass thru the actual documentation notebook and make a PR for anything where we should logically use ``.where`` to make the syntax more clear would be great (or indicate that it looks good).