TST: Add tests for sparse quantile/where
pandas-dev/pandas pull request #17568
Opened 2017-09-18 10:34 UTC by Licht-T

- [x] closes #xxxx
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry
This is the part of. https://github.com/pandas-dev/pandas/pull/17386.

2017-09-18 11:06 UTC, jreback commented on pandas/tests/sparse/test_frame.py
> +        # GH 17386
pls pls pls use parametrize. you are repeating way too many things

2017-09-18 12:27 UTC, Licht-T commented
@jreback Thanks for your review. Parametrized `other`.

2017-09-18 13:49 UTC, jreback requested changes

2017-09-18 13:49 UTC, jreback commented on pandas/tests/sparse/test_frame.py
> +                              '(GH 17386)')
you need to parameterize on the data itself as well

2017-09-18 14:40 UTC, Licht-T commented
@jreback Parametrized `data`.

2017-10-28 00:30 UTC, jreback commented
can you rebase

2017-10-28 14:23 UTC, Licht-T commented
@jreback Rebased.

2017-10-28 15:22 UTC, jreback commented
these tests are failing the CI, not really sure why

2017-10-29 00:35 UTC, Licht-T commented
@jreback Okay. I'll check.

2017-10-29 01:34 UTC, Licht-T commented
@jreback It seems that segfault happened in `test_where_with_bool_data_and_other`.
Marked `skip`.

2017-10-31 01:29 UTC, jreback approved these changes

2017-10-31 01:29 UTC, merged

2017-10-31 01:30 UTC, jreback commented
thanks @Licht-T 

love to have the fixes for these!