Dont check for NaTType, just NaT
pandas-dev/pandas pull request #17564
Opened 2017-09-17 20:27 UTC by jbrockmendel

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-09-17 20:31 UTC, jreback requested changes
small change, other lgtm.

2017-09-17 20:31 UTC, jreback commented on pandas/tests/scalar/test_timedelta.py
> +        assert min_td - Timedelta(1, 'ns') is NaT
use parens

2017-09-17 20:47 UTC, jreback commented on pandas/io/packers.py
> -                          np.timedelta64, NaTType)):
FYI: 

```
In [40]: np.timedelta64('nat') is pd.NaT
Out[40]: False

In [41]: pd.Timedelta(np.timedelta64('nat')) is pd.NaT
Out[41]: True
```

this is reason for the complex type checking around NaTs; numpy has a 'nat' like value embedded in np.timedelta64/np.datetime64 (however its not very useful).

2017-09-17 20:47 UTC, jreback approved these changes

2017-09-17 20:47 UTC, jreback commented
lgtm. merge on green.

2017-09-19 17:37 UTC, jbrockmendel commented
Test error is in `pyarrow`, which I haven't looked at closely.  Does it instantiate a new instance of `NaTType` for some reason?

2017-09-19 18:02 UTC, jreback commented
no just rebase

2017-09-23 19:42 UTC, merged

2017-09-23 19:42 UTC, jreback commented
thanks!