Allow for dict-like argument to Categorical.rename_categories
pandas-dev/pandas pull request #17586
Opened 2017-09-19 02:26 UTC by alanbato

- [x] closes #17336
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

`Categorical.rename_categories` can now take a dict as `new_categories` and updates the categories to those found in the mapping.
 It will only change the categories found in the dict, and leave all others the same.
The dict can be smaller or larger, and may or may not contain mappings referencing the old categories.

Have a good day/night! 🐼 🐍

2017-09-19 12:40 UTC, jreback requested changes
lgtm. some small comments. pls rebase / ping on green.

2017-09-19 12:40 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- :func:`Categorical.rename_categories` now accepts a dict-like argument as `new_categories`, and only updates the categories found in that dict. (:issue:`17336`)
can you update / add to the example in categorical.rst as well

2017-09-19 12:40 UTC, jreback commented on pandas/core/categorical.py
> +        if isinstance(new_categories, dict):
use is_dict_like, no need to do this as an if

```
if is_dict_like(new_categories):
    new_categories = [new_categories.get(item, item).....]
cat.categories = new_categories
```

2017-09-19 12:40 UTC, jreback commented on pandas/tests/test_categorical.py
> +        # Test for dicts of smaller length
blank lines between sub-tests

2017-09-19 19:17 UTC, TomAugspurger commented
Don't worry about the travis failures. They're unrelated and have been fixed. +1 once you change the `if isinstance(...)` to use `is_dict_like`.

2017-09-20 04:34 UTC, gfyoung commented on doc/source/whatsnew/v0.21.0.txt
> +- :func:`Categorical.rename_categories` now accepts a dict-like argument as `new_categories`, and only updates the categories found in that dict. (:issue:`17336`)
Nit: remove the comma before "and only updates"

2017-09-20 04:34 UTC, gfyoung commented on pandas/core/categorical.py
> +        if is_dict_like(new_categories):
Nit: newline above this one.

2017-09-20 04:34 UTC, gfyoung commented on pandas/tests/test_categorical.py
> +        # Test for inplace
Nit: newline above this one.

2017-09-20 04:35 UTC, gfyoung commented on pandas/tests/test_categorical.py
> +        # Test for dicts of smaller length
Nit: newline above this one.

2017-09-20 04:35 UTC, gfyoung commented on pandas/tests/test_categorical.py
> +        tm.assert_index_equal(cat.categories, expected)
Nit: remove newline above this one.

2017-09-20 04:35 UTC, gfyoung commented on pandas/tests/test_categorical.py
> +        # Test for dicts with bigger length
Nit: newline above this one.

2017-09-20 04:35 UTC, gfyoung commented on pandas/tests/test_categorical.py
> +        # Test for dicts with no items from old categories
Nit: newline above this one.

2017-09-20 04:35 UTC, gfyoung commented on pandas/tests/test_categorical.py
> +        expected = Index([1, 'b', 3, 'd'])
Nit: newline above this one.

2017-09-20 04:35 UTC, gfyoung commented on pandas/tests/test_categorical.py
> +        expected = Index(['a', 'b', 'c', 'd'])
Nit: newline above this one.

2017-09-20 04:36 UTC, gfyoung commented
@alanbato : LGTM as well.  Bunch of nit-picking to enhance readability is all I've got above.

2017-09-20 16:04 UTC, alanbato commented
Done @gfyoung. Do we wait for green again?

2017-09-20 16:23 UTC, gfyoung commented
@alanbato : Yes, ping us when it's green.

2017-09-20 16:23 UTC, gfyoung approved these changes

2017-09-20 22:10 UTC, alanbato commented
@TomAugspurger @gfyoung @jreback Ping! 🌵✔️

2017-09-20 22:12 UTC, gfyoung commented
Nice!  I'll let @jreback look this over and merge just to double check.

2017-09-21 13:33 UTC, jreback approved these changes
lgtm. merge away

2017-09-21 13:34 UTC, jreback requested changes

2017-09-21 13:34 UTC, jreback commented on pandas/core/categorical.py
> +            cat.categories = [new_categories.get(item, item)
actually make sure the doc string is updated here as well (maybe add a versionchanged tag)

2017-09-21 20:10 UTC, jreback commented on pandas/core/categorical.py
>             The renamed categories.
``dict-like (>=0.21.0)``

2017-09-21 22:31 UTC, alanbato commented
@jreback 🌵 ✔️

2017-09-21 22:43 UTC, jreback approved these changes

2017-09-21 22:45 UTC, merged

2017-09-21 22:45 UTC, jreback commented
thanks @alanbato nice patch!