Simplify to_pydatetime()
pandas-dev/pandas pull request #17592
Opened 2017-09-19 17:45 UTC by jbrockmendel

Up until #17331, `Timestamp.microsecond` was very slow.  So previously it was faster to go through `convert_to_tsobject` to get a new `datetime` instance than it was to just return 
 `datetime(self.year, self.month, self.day, self.hour, self.minute, self.second, self.microsecond, self.tzinfo)`

Now it is slightly faster (and much simpler) to do it this way.

Before:

```
In [2]: ts = pd.Timestamp.now()
In [3]: %timeit ts.to_pydatetime()
The slowest run took 13.88 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.44 µs per loop
```

After:
```
In [2]: ts = pd.Timestamp.now()
In [3]: %timeit ts.to_pydatetime()
The slowest run took 8.51 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.29 µs per loop
```

With a tz-aware Timestamp the speedup is much bigger:

Before:
```
In [4]: import pytz
In [5]: ts2 = ts.replace(tzinfo=pytz.timezone('US/Pacific'))
In [6]: %timeit ts2.to_pydatetime()
The slowest run took 39.71 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 68.9 µs per loop
```

After:
```
In [7]: import pytz
In [8]: ts2 = ts.replace(tzinfo=pytz.timezone('US/Pacific'))
In [9]: %timeit ts2.to_pydatetime()
The slowest run took 8.29 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.47 µs per loop
```

2017-09-20 01:48 UTC, chris-b1 commented on pandas/_libs/tslib.pyx
> +                         self.hour, self.minute, self.second,
indendation

2017-09-20 01:49 UTC, chris-b1 commented
LGTM, minus formatting nit.

2017-09-20 10:41 UTC, jreback requested changes
can you verify that there is an asv for this (and add one if not).

2017-09-20 14:44 UTC, jbrockmendel commented
There is not, just added one.

2017-09-20 14:48 UTC, pep8speaks commented
Hello @jbrockmendel! Thanks for updating the PR.

 - In the file [`asv_bench/benchmarks/timestamp.py`](https://github.com/pandas-dev/pandas/blob/ee2885911935238c4a369162aedb50204a612e97/asv_bench/benchmarks/timestamp.py), following are the PEP8 issues :

> [Line 90:1](https://github.com/pandas-dev/pandas/blob/ee2885911935238c4a369162aedb50204a612e97/asv_bench/benchmarks/timestamp.py#L90): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2017-09-20 14:49 UTC, jbrockmendel commented
Looks like someone added one overnight, will add to_pydatetime timing to it.

2017-09-20 22:40 UTC, jbrockmendel commented
Is there an error message in the circleci log that I'm missing?

2017-09-21 13:21 UTC, jreback commented
looks fine

you can click thru to circleci to see errors

2017-09-21 15:02 UTC, jbrockmendel commented
> looks fine
>
>you can click thru to circleci to see errors

I don't ask _just_ because I want to waste your time.  I'm saying I don't see any error message in the log.

2017-09-21 20:18 UTC, jreback commented
> I don't ask just because I want to waste your time. I'm saying I don't see any error message in the log.

I know, but some people don't actually realize you can click thru. yeah it prob timed out or something.

Wait till I merge #17619 and rebase

2017-09-22 13:22 UTC, jreback approved these changes

2017-09-22 13:22 UTC, merged

2017-09-22 13:22 UTC, jreback commented
thanks!