Add documentation link to SettingWithCopyWarning
pandas-dev/pandas pull request #17672
Opened 2017-09-25 19:47 UTC by gliptak

https://github.com/pandas-dev/pandas/issues/17505

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-09-26 13:31 UTC, jreback commented on doc/source/indexing.rst
> +
I would move this to the top of the section and make it a note::

2017-09-28 00:28 UTC, jreback requested changes

2017-09-28 00:28 UTC, jreback commented on doc/source/indexing.rst
> +   assignment. There may be false positives; situations where a chained assignment is inadvertently
remove the last sentence; this is actually not true. All purported false positive are actually user error (at least that have been reported)

2017-10-01 16:08 UTC, gliptak commented
@jreback Please review.

2017-10-01 16:34 UTC, jreback commented
@jorisvandenbossche ?

2017-10-28 13:56 UTC, closed without merging