BUG: GH17525 Function _get_standard_colors resets global random seed
pandas-dev/pandas pull request #17730
Opened 2017-09-30 21:33 UTC by cmazzullo

- [X] closes #17525 
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

2017-10-01 06:57 UTC, gfyoung commented on pandas/plotting/_style.py
> +                rstate = random.getstate()  # to avoid resetting the seed
Point to the issue number.

2017-10-01 06:58 UTC, gfyoung commented on pandas/plotting/_style.py
> +                rstate = random.getstate()  # to avoid resetting the seed
Also, since you're changing the behavior, let's document it.  A brief doc-string would be good here.

2017-10-01 07:00 UTC, gfyoung commented
@cmazzullo : Also, you're definitely going to need tests.

2017-10-01 15:28 UTC, pep8speaks commented
Hello @cmazzullo! Thanks for updating the PR.



 - In the file [`pandas/tests/plotting/test_misc.py`](https://github.com/pandas-dev/pandas/blob/2f3da72c2706364afd483c2cb6dfa8d4fc44813d/pandas/tests/plotting/test_misc.py), following are the PEP8 issues :

> [Line 290:36](https://github.com/pandas-dev/pandas/blob/2f3da72c2706364afd483c2cb6dfa8d4fc44813d/pandas/tests/plotting/test_misc.py#L290): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 293:41](https://github.com/pandas-dev/pandas/blob/2f3da72c2706364afd483c2cb6dfa8d4fc44813d/pandas/tests/plotting/test_misc.py#L293): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 295:41](https://github.com/pandas-dev/pandas/blob/2f3da72c2706364afd483c2cb6dfa8d4fc44813d/pandas/tests/plotting/test_misc.py#L295): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2017-10-01 15:33 UTC, cmazzullo commented
Okay, just added one.

2017-10-01 17:41 UTC, jreback requested changes

2017-10-01 17:41 UTC, jreback commented on pandas/plotting/_style.py
>              def random_color(column):
I don't think ``random`` provides a context manger, maybe do this like:

```
rstate = random.getstate()
try:
    random.seed(...)
    return = [random...... ]
finally:
    random.setstate(rstate)
```

2017-10-01 17:46 UTC, jreback commented on pandas/plotting/_style.py
>              def random_color(column):
actually just use this
```
In [20]: rs = pandas.core.common._random_state()

In [21]: rs.rand(3)
Out[21]: array([ 0.6786481 ,  0.94231001,  0.03334007])
```

2017-10-01 17:46 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Bug in ``plotting._style._get_standard_colors`` resetting the random seed when generating random colors (:issue:`17525`)
reference the user visibile issue (e.g. parallel coordinates)?

2017-10-01 20:00 UTC, gfyoung commented on pandas/tests/plotting/test_misc.py
> +        """ For #17525 """
Generally, we just add a comment above, not a docstring.

2017-10-01 23:28 UTC, jreback approved these changes
lgtm with a minor comment. have't looked why its failing. ping on green.

2017-10-01 23:28 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
> +- Bug in ``plotting._style._get_standard_colors`` causing ``plotting.parallel_coordinates`` to reset the random seed when using random colors (:issue:`17525`)
you don't need the first part, a user won't know what you are talking about.

2017-10-02 10:15 UTC, jreback commented on pandas/plotting/_style.py
> +                return rs.rand(3)
``return rs.rand(3).tolist()`` will make this work.

2017-10-02 12:42 UTC, jreback approved these changes
lgtm. ping on green.

2017-10-03 08:07 UTC, merged

2017-10-03 08:07 UTC, jorisvandenbossche commented
@cmazzullo Thanks!

2017-10-03 11:19 UTC, cmazzullo commented
Sure thing