Clarify exceptions for invalid datetimelike operations
pandas-dev/pandas pull request #17772
Opened 2017-10-03 23:45 UTC by mturzanska

closes #9631

2017-10-03 23:50 UTC, mturzanska commented
Seemed too small a change for a what's new note

2017-10-04 10:16 UTC, jreback requested changes

2017-10-04 10:16 UTC, jreback commented on pandas/tests/indexes/datetimes/test_ops.py
> +        dti = DatetimeIndex(['2011-01-01', '2011-01-02'])
add the issue number as a comment

2017-10-04 10:16 UTC, jreback commented on pandas/tests/indexes/datetimes/test_ops.py
> +        msg = 'cannot add DatetimeIndex and Timestamp'
can you combine these into a single tests and use parametrize for the args

2017-10-04 10:16 UTC, jreback commented
some comments. ping when pushed and green. skipping whatsnew is fine.

2017-10-06 09:42 UTC, mturzanska commented
@jreback addressed all comments, tests pass

2017-10-06 10:12 UTC, jreback requested changes

2017-10-06 10:12 UTC, jreback commented on pandas/tests/indexes/datetimes/test_ops.py
> -
hmm I think you removed the ``dti_tz + dti_tz`` tests (IOW a tz-aware interacting with a non-tzaware). these can be a separate test function. also add a datetime scalar addend.

2017-10-06 22:50 UTC, jreback commented on pandas/tests/indexes/datetimes/test_ops.py
> +        msg = 'cannot add DatetimeIndex and DatetimeIndex'
can u parametrize this as well

2017-10-08 16:15 UTC, jreback approved these changes

2017-10-08 16:15 UTC, merged

2017-10-08 16:15 UTC, jreback commented
thanks @mturzanska