BUG: Ignore division by 0 when merging empty dataframes (#17776)
pandas-dev/pandas pull request #17846
Opened 2017-10-11 18:57 UTC by yeemey

- [/] closes #17776
- [ ] tests added / passed
- [/] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [/] whatsnew entry

2017-10-13 11:09 UTC, jreback requested changes
pls add the test from the original issue

2017-10-13 11:09 UTC, jreback commented on pandas/core/reshape/merge.py
>      pred = lambda i: not is_int64_overflow_possible(shape[:i])
use the context manager here (and only surround the actual divide statement)

2017-10-13 21:01 UTC, yeemey reviewed
Thanks, @jreback ! I made the changes [here](https://github.com/pandas-dev/pandas/pull/17846/commits/039315ada5ea3964c46151203c055694bd7e84cc). I haven't done a review before, so I'm not entirely sure how this works.

2017-10-14 14:44 UTC, jreback commented
need you to rebase on master

```
git rebase -i upstream/master
```

then fix any conflicts

```
git push yourupstream yourbranch -f
```

2017-10-14 21:11 UTC, jreback requested changes

2017-10-14 21:11 UTC, jreback commented on pandas/core/reshape/merge.py
> +    np.seterr(divide='warn')
not necessary

2017-10-14 21:11 UTC, jreback commented on pandas/tests/reshape/test_merge.py
> +        import warnings
the test should mimic the one from the issue, except use a context manager (to avoid setting it globally)

2017-10-14 21:11 UTC, jreback commented on pandas/core/reshape/merge.py
> +    np.seterr(divide='ignore')
not needed

2017-10-16 18:37 UTC, yeemey commented
@jreback, thanks, I've made the changes. How can I address the failed AppVeyor build? This test passed when I ran `pytest pandas` on my computer:

`
================================== FAILURES ===================================
_______________________ TestDataFrameAnalytics.test_sum _______________________
[gw0] win32 -- Python 2.7.14 C:\Miniconda3_64\envs\pandas\python.exe
self = <pandas.tests.frame.test_analytics.TestDataFrameAnalytics object at 0x00000000089BB518>
    def test_sum(self):
        self._check_stat_op('sum', np.sum, has_numeric_only=True)
    
        # mixed types (with upcasting happening)
        self._check_stat_op('sum', np.sum,
                            frame=self.mixed_float.astype('float32'),
                            has_numeric_only=True, check_dtype=False,
>                           check_less_precise=True)
pandas\tests\frame\test_analytics.py:449: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pandas\tests\frame\test_analytics.py:753: in _check_stat_op
    check_less_precise=check_less_precise)
pandas\util\testing.py:1272: in assert_series_equal
    obj='{obj}'.format(obj=obj))
pandas\_libs\testing.pyx:59: in pandas._libs.testing.assert_almost_equal
    cpdef assert_almost_equal(a, b,
pandas\_libs\testing.pyx:173: in pandas._libs.testing.assert_almost_equal
    raise_assert_detail(obj, msg, lobj, robj)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
obj = 'Series', message = 'Series values are different (25.0 %)'
left = '[-13.4449, 0.13886, 9.09849, -0.00019373]'
right = '[-13.4448623657, 0.13885974884, 9.098487854, -0.000193253159523]'
diff = None
    def raise_assert_detail(obj, message, left, right, diff=None):
        if isinstance(left, np.ndarray):
            left = pprint_thing(left)
        if isinstance(right, np.ndarray):
            right = pprint_thing(right)
    
        msg = """{obj} are different
    
    {message}
    [left]:  {left}
    [right]: {right}""".format(obj=obj, message=message, left=left, right=right)
    
        if diff is not None:
            msg += "\n[diff]: {diff}".format(diff=diff)
    
>       raise AssertionError(msg)
E       AssertionError: Series are different
E       
E       Series values are different (25.0 %)
E       [left]:  [-13.4449, 0.13886, 9.09849, -0.00019373]
E       [right]: [-13.4448623657, 0.13885974884, 9.098487854, -0.000193253159523]
pandas\util\testing.py:1089: AssertionError
 1 failed, 15133 passed, 790 skipped, 13 xfailed, 1 xpassed in 517.30 seconds =
Command exited with code 1
`

2017-11-12 19:15 UTC, jreback commented
can you rebase and add a note in 0.21.1

2017-11-26 23:49 UTC, jreback approved these changes

2017-11-27 11:36 UTC, merged

2017-11-27 11:36 UTC, jreback commented
thanks @yeemey