BUG: duplicate indexing with embedded non-orderables (#17610)
pandas-dev/pandas pull request #17851
Opened 2017-10-12 08:54 UTC by gloryfromca

BUG: duplicate indexing with embedded non-orderables (#17610)

- [x] closes #xxxx
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2017-10-12 18:04 UTC, jschendel commented on pandas/tests/series/test_indexing.py
> +        s = pd.Series({1: 12, 2: [1, 2, 2, 3]})
Can you add the github issue number as a comment here?

2017-10-13 10:40 UTC, jreback requested changes

2017-10-13 10:40 UTC, jreback commented on pandas/core/series.py
> -                            result, index=[key] * len(result),
you need to do something like

```
index = self.index[self.index.get_loc(key)]
```

2017-10-28 02:32 UTC, jreback requested changes

2017-10-28 02:32 UTC, jreback commented on doc/source/whatsnew/v0.21.0.txt
>  - Bug in :func:`String.str_get` raises ``IndexError`` instead of inserting NaNs when using a negative index. (:issue:`17704`)
move to 0.21.1

2017-11-25 16:15 UTC, jreback commented
can you rebase / update

2017-12-03 12:59 UTC, closed without merging