tslib flake8 cleanup, missing declarations
pandas-dev/pandas pull request #17907
Opened 2017-10-17 19:37 UTC by jbrockmendel

replace `isinstance` checks with the faster C versions
change cpdef-->cdef for internal field-getter methods
remove get_named_field in favor of faster dict lookup (yah yah I'll show asv results in a bit)

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-10-17 22:42 UTC, jreback requested changes
looks fine. ping on green.

can you show updated benchmarks (for things that changed)

2017-10-17 22:42 UTC, jreback commented on pandas/_libs/tslib.pyx
> +        datetime dtime
call as dt (like below)

2017-10-17 23:43 UTC, jbrockmendel commented
> can you show updated benchmarks (for things that changed)

Should just be `weekday_name` property.

Old:
```
In [2]: ts = pd.Timestamp.now()
In [3]: ts2 = ts.tz_localize('Europe/Amsterdam')
In [4]: %timeit ts.weekday_name
10000 loops, best of 3: 79.5 µs per loop
In [5]: %timeit ts2.weekday_name
10000 loops, best of 3: 150 µs per loop
```

New:
```
In [2]: ts = pd.Timestamp.now()
In [3]: ts2 = ts.tz_localize('Europe/Amsterdam')
In [4]: %timeit ts.weekday_name
The slowest run took 11.97 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.92 µs per loop
In [5]: %timeit ts2.weekday_name
100000 loops, best of 3: 5.26 µs per loop
```

2017-10-17 23:56 UTC, jreback commented
since it looks like you are doing flake8 fixups, can you edit the lint.sh script to pick these things up?
if some things are currently failing, just separate those out into a separate section (in the same scripts) with a comment and we can uncomment later.

2017-10-18 00:15 UTC, jbrockmendel commented
> can you edit the lint.sh script to pick these things up?

Just added this to the TODO list.

2017-10-20 13:30 UTC, jreback approved these changes

2017-10-20 13:30 UTC, merged

2017-10-20 13:30 UTC, jreback commented
thanks @jbrockmendel