ERR: Improve error message on non-sorted input with .truncate
pandas-dev/pandas pull request #17984
Opened 2017-10-25 20:13 UTC by reidy-p

- [ ] closes #17935
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-10-25 23:04 UTC, gfyoung approved these changes

2017-10-26 17:53 UTC, TomAugspurger approved these changes

2017-10-27 10:17 UTC, jreback requested changes
can you add a note in other api changes in 0.22 (this is technially an api change, sort of a trivial one)

2017-10-27 10:17 UTC, jreback commented on pandas/tests/frame/test_timeseries.py
> +    def test_truncate_nonsortedindex(self):
can you add a test for series as well (you can also put this test generically in test_generic if its easier)

2017-10-27 10:17 UTC, jreback commented on pandas/core/generic.py
add a comment here

2017-11-12 19:45 UTC, jreback commented
can you rebase

2017-11-16 00:14 UTC, jreback requested changes
looks good, except you have lint issues, you can run ``make lint-diff`` and see

2017-11-16 00:14 UTC, jreback commented on pandas/core/generic.py
> +           not ax.is_monotonic_decreasing):
lint error

2017-11-16 00:14 UTC, jreback commented on doc/source/whatsnew/v0.22.0.txt
> +- :func:`Series.truncate` and :func:`DataFrame.truncate` will raise a ``ValueError`` if the index is not sorted (:issue:`17935`)
say, rather than a non-helpful ``KeyError``

2017-11-16 20:36 UTC, reidy-p commented
I updated the whatsnew and think I fixed the lint issue.

But since I opened this PR a new the ``test_truncate`` test has been added to ``pandas/tests/series/test_period.py`` in #17755. This new test fails on my branch because it tries to truncate on a non-sorted index. So I modified the test to sort the index before truncating and now it passes. Alternatively, I could simply check for the new error message ``ValueError: truncate requires a sorted index`` in this test.

2017-11-17 00:30 UTC, jreback approved these changes

2017-11-17 00:30 UTC, merged

2017-11-17 00:31 UTC, jreback commented
thanks @reidy-p 

changing the test for Period was just fine