CLN: replace %s syntax /w .format in _version, plotting, stats, tseries
pandas-dev/pandas pull request #18010
Opened 2017-10-28 09:18 UTC by corazzon

Progress towards #16130

- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2017-10-28 11:06 UTC, jreback commented on pandas/_version.py
>          if verbose:
revert this file it is auto generated

2017-10-28 11:08 UTC, jreback commented on pandas/_version.py
>          if verbose:
rather versioneer creates it; would rather use a newer versioneer

2017-11-08 12:06 UTC, jreback commented
can u rebase

2017-11-09 12:58 UTC, jreback requested changes

2017-11-09 12:58 UTC, jreback commented on pandas/tseries/offsets.py
> +    def __repr__(self):
remove this; its a rebase artifact

2017-11-10 20:06 UTC, jreback approved these changes

2017-11-10 20:06 UTC, merged

2017-11-10 20:06 UTC, jreback commented
thanks!

2017-11-10 22:41 UTC, corazzon commented
thanks!