to_csv now working for string arrays using ascii, still broken for utf-8
pandas-dev/pandas pull request #18013
Opened 2017-10-28 18:06 UTC by rtkaleta

WIP.

- [ ] closes #10813
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-10-31 00:59 UTC, jreback requested changes

2017-10-31 00:59 UTC, jreback commented on pandas/tests/io/formats/test_to_csv.py
> +,names
so if you make this 2 test functions, then you can xfail the non-working one (to at least get things passing)

2017-11-05 14:35 UTC, rtkaleta commented
@jreback It seems the current behaviour stems from the fact that pandas' own `UnicodeWriter` calls `pprint_thing` without `quote_strings=True` so then:

```python
>>> from pandas.io.formats.printing import pprint_thing
>>> pprint_thing([u'foo', u'bar'])
u'[foo, bar]'
```
instead of the more intuitive (at least to me):
```python
>>> pprint_thing([u'foo', u'bar'], quote_strings=True)
u"[u'foo', u'bar']"
```

A couple of questions come to my mind:
1) Why do we have our own `UnicodeWriter` [here](https://github.com/pandas-dev/pandas/blob/master/pandas/io/formats/format.py#L1642) instead of [unicodecsv.writer](https://github.com/jdunck/python-unicodecsv)?
2) Better to expose the `quote_strings` (or similar) parameter to the `to_csv` caller, or is the behaviour I expect so ubiquitously intuitive that we should be changing things under the hood?

2017-11-06 13:47 UTC, jreback commented
will have a look

2017-11-07 18:09 UTC, jreback approved these changes

2017-11-07 18:09 UTC, merged

2017-11-07 18:10 UTC, jreback commented
thanks @rtkaleta 

love for you to take a stab at fixing the xfailed unicode case!