Separate out arithmetic tests for datetimelike indexes
pandas-dev/pandas pull request #18049
Opened 2017-10-31 06:43 UTC by jbrockmendel

As discussed... somewhere.  I'll find the reference tomorrow.

This is about as close as I could get to pure cut/paste.  There are a few notes to sprinkle in about things to clean up in a follow-up.

In a couple places this wraps some string literals to make folding easier.

2017-10-31 10:36 UTC, jreback requested changes
can you show the before & after number of tests fo r the affected files (to make sure not missing any). a couple of comments.

2017-10-31 10:36 UTC, jreback commented on pandas/tests/indexes/timedeltas/test_arithmetic.py
> +# FIXME: This was moved from `test_tools`.  It belongs in scalar tests
so let's move it there

2017-10-31 10:36 UTC, jreback commented on pandas/tests/indexes/timedeltas/test_arithmetic.py
> +# FIXME: This came from `test_timedelta`, does not appear to have
the class names came from a previous round of moving tests, you can remove/rename them if it doesn't make sense (in fact I generally *don't* like classes for organizing , and much prefer separate well-named files, changing this is out of scope for this PR). This plays nicer with pytest.

2017-10-31 16:32 UTC, jbrockmendel commented
Looking at tests.indexes: 3824 under PR, 3829 under master.  Removal of duplicate Julian tests accounts for the difference

2017-10-31 16:34 UTC, jbrockmendel commented
From Travis log:

```
=================================== FAILURES ===================================
________________ TestClipboard.test_round_trip_valid_encodings _________________
self = <pandas.tests.io.test_clipboard.TestClipboard object at 0x7f8377152438>
    def test_round_trip_valid_encodings(self):
        for enc in ['UTF-8', 'utf-8', 'utf8']:
            for dt in self.data_types:
>               self.check_round_trip_frame(dt, encoding=enc)
pandas/tests/io/test_clipboard.py:136: 
[...]
>       raise AssertionError(msg)
E       AssertionError: DataFrame are different
E       
E       DataFrame shape mismatch
E       [left]:  (5, 3)
E       [right]: (2, 2)
[...]
pandas/util/testing.py:1089: AssertionError
============================ 15513 tests deselected ============================
 1 failed, 518 passed, 22 skipped, 15513 deselected, 1 xfailed in 164.49 seconds 
sys:1: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=2050, proto=0, laddr=('0.0.0.0', 0)>
[...]
..ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long'
Exception ignored in: 'pandas._libs.lib.is_bool_array'
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long'
.................ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long'
Exception ignored in: 'pandas._libs.lib.is_bool_array'
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long'
.ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long'
Exception ignored in: 'pandas._libs.lib.is_bool_array'
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long'
```

No idea if the buffer mismatches are related to the TestClipboard error.  The latter has shown up a handful of times and usually goes away with re-running the CI.

2017-11-01 01:18 UTC, jreback commented
the clipboard tests are orthogonal to this. They fail occasionally, a restart of the job usually fixes. 

However the is_bool_array is faulting somewhere in cython.

2017-11-01 01:19 UTC, jreback approved these changes

2017-11-01 01:19 UTC, merged

2017-11-01 01:19 UTC, jreback commented
thanks!