Gh 17483
pandas-dev/pandas pull request #18042
Opened 2017-10-31 01:09 UTC by cmazzullo

- [X] closes #17483

2017-10-31 01:16 UTC, jreback requested changes

2017-10-31 01:16 UTC, jreback commented on doc/source/io.rst
> +  ``header=None``. Explicitly pass ``header=0`` to be able to replace
I would put a paragraph break here, its pretty long.

2017-10-31 01:16 UTC, jreback commented on pandas/io/parsers.py
> +    ``header=None``. Explicitly pass ``header=0`` to be able to
I would also add a note in Handling Column Names, maybe a ``::note`` box would be nice.

2017-11-02 11:29 UTC, jreback commented on pandas/io/parsers.py
> +    ``header=None``. Explicitly pass ``header=0`` to be able to
can you make this note the same as above?

2017-11-02 12:53 UTC, jreback commented
@jorisvandenbossche if you'd review

2017-11-06 23:01 UTC, jorisvandenbossche reviewed
Looks good! Added two small comments

2017-11-06 23:01 UTC, jorisvandenbossche commented on doc/source/io.rst
> +  passed explicitly then the behavior is identical to
I would add: passed explicitly with the `header` keyword

2017-11-06 23:01 UTC, jorisvandenbossche commented on doc/source/io.rst
> +  names. The header can be a list of ints that specify row locations
I would make the paragraph break here at "The header can be ..." and leave the first sentence at the previou paragraph.

2017-11-25 16:22 UTC, jreback commented
can you rebase

2017-11-29 01:29 UTC, cmazzullo commented
Sure thing @jreback

2017-11-29 10:48 UTC, jorisvandenbossche commented
@cmazzullo Seems something went wrong with the rebase (many commits included on github now). In principle if you do exactly the following (assuming pandas-dev/pandas remote is called upstream):

```
git fetch upstream
git checkout gh-17483
git rebase upstream/master
git push origin gh-17483 --force
```

this should solve it.

2017-11-30 14:26 UTC, merged

2017-11-30 14:26 UTC, jorisvandenbossche commented
@cmazzullo quickly did the rebase myself. Thanks for this clarification of the docs!

2017-12-01 02:06 UTC, cmazzullo commented
Thanks!