DOC: Improve reduce docstring
pandas-dev/pandas pull request #18100
Opened 2017-11-04 01:25 UTC by reidy-p

- [ ] closes #17673
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

I have tried to separate the docstrings for series and dataframe as suggested in the original issue but can try to combine them if that works better.

As noted in the original issue, ``replace`` can do a lot things and I've tried to cover most of them with the examples but would welcome other suggestions.

2017-11-04 14:54 UTC, TomAugspurger reviewed
Haven't gone through this in detail yet, but I think it'd be cleaner to leave the implementation in `pandas/core/generic.py`, and to only overwrite the docstring in `series.py` and `frame.py`.

So in, e.g. `series.py` it'd look like

```python
    def replace(self, to_replace=None, value=None, inplace=False, limit=None,
                regex=False, method='pad', axis=None):
   """add your docstring"""
    super().replace(to_replace= to_replace, value=value...)
```

Then you don't have all the duplicated code.

2017-11-04 14:54 UTC, TomAugspurger commented on pandas/core/frame.py
> +def _single_replace(self, to_replace, method, inplace, limit):
Could define this in one place and then import it in `frame.py` and `series.py`.

Also a short docstring would still be nice, even though it's internal.

2017-11-04 14:54 UTC, TomAugspurger commented on pandas/core/frame.py
> +        :func:`DataFrame.fillna` : Fill NA/NaN values
You do't need the

   :func:`

. Just DataFrame.fillna should be enough for numpydoc.

2017-11-04 20:49 UTC, reidy-p commented
@TomAugspurger thanks for the review, made some updates.

2018-01-21 18:10 UTC, jreback commented
can you rebase

2018-01-21 19:41 UTC, jreback requested changes

2018-01-21 19:41 UTC, jreback commented on pandas/core/series.py
> +    def replace(self, to_replace=None, value=None, inplace=False, limit=None,
can we share *most* / all of this via ``_shared_docs``? otherwise end up with lots of duplication here

2018-01-29 22:42 UTC, reidy-p commented
I removed the duplication by using ``_shared_docs`` but as a result most of the examples for both the ``Series.replace`` and ``DataFrame.replace`` docstrings now use ``DataFrame``.

2018-01-30 00:27 UTC, jreback commented
@jorisvandenbossche if you'd have a look. I only glanced briefly :>

2018-01-30 00:27 UTC, jreback approved these changes

2018-01-30 12:19 UTC, TomAugspurger approved these changes

2018-01-30 12:19 UTC, TomAugspurger commented on pandas/core/generic.py
>                  - str and regex rules apply as above.
I suppose this is "str, regex, and numeric rules apply as above." now?

2018-02-04 16:32 UTC, merged

2018-02-04 16:33 UTC, jreback commented
thanks!