PERF: Vectorized Timedelta property access (#18092)
pandas-dev/pandas pull request #18225
Opened 2017-11-11 03:26 UTC by WillAyd

- [X] closes #xxxx
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

2017-11-11 04:06 UTC, jreback commented
can u post the asv results?

2017-11-11 04:49 UTC, WillAyd commented
See below. I was not able to consistently reproduce the one increase for `timeseries.ToDatetime.time_iso8601_tz_spaceformat`

    asv continuous -f 1.1 upstream/master HEAD -b timedelta -b timeseries -b indexing

    [  0.00%] · For pandas commit hash e369c1fc:
    [  0.00%] ·· Building for conda-py3.6-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-pytest-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt......................................................
    [  0.00%] ·· Benchmarking conda-py3.6-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-pytest-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt
    [  0.30%] ··· Running frame_methods.Iteration.time_iteritems_indexing                                                   15.0±0.06ms
    [  0.60%] ··· Running frame_methods.frame_assign_timeseries_index.time_frame_assign_timeseries_index                    1.70±0.04ms
    [  0.90%] ··· Running indexing.DataFrameIndexing.time_boolean_rows                                                          264±2μs
    [  1.20%] ··· Running indexing.DataFrameIndexing.time_boolean_rows_object                                                   477±6μs
    [  1.51%] ··· Running indexing.DataFrameIndexing.time_get_value                                                         3.98±0.02μs
    [  1.81%] ··· Running indexing.DataFrameIndexing.time_get_value_ix                                                       21.6±0.4μs
    [  2.11%] ··· Running indexing.DataFrameIndexing.time_getitem_scalar                                                     10.5±0.2μs
    [  2.41%] ··· Running indexing.DataFrameIndexing.time_iloc_big                                                              112±3μs
    [  2.71%] ··· Running indexing.DataFrameIndexing.time_iloc_dups                                                             188±2μs
    [  3.01%] ··· Running indexing.DataFrameIndexing.time_loc_dups                                                             995±20μs
    [  3.31%] ··· Running indexing.DatetimeIndexing.time_getitem_scalar                                                     4.05±0.03μs
    [  3.61%] ··· Running indexing.IndexerLookup.time_lookup_iloc                                                               277±5ns
    [  3.92%] ··· Running indexing.IndexerLookup.time_lookup_ix                                                             16.0±0.08μs
    [  4.22%] ··· Running indexing.IndexerLookup.time_lookup_loc                                                                290±3ns
    [  4.52%] ··· Running indexing.IndexingMethods.time_get_loc_float                                                        7.91±0.3μs
    [  4.82%] ··· Running indexing.IndexingMethods.time_take_dtindex                                                        3.90±0.04ms
    [  5.12%] ··· Running indexing.IndexingMethods.time_take_intindex                                                       3.89±0.09ms
    [  5.42%] ··· Running indexing.Int64Indexing.time_getitem_array                                                         1.10±0.01ms
    [  5.72%] ··· Running indexing.Int64Indexing.time_getitem_list_like                                                         423±5μs
    [  6.02%] ··· Running indexing.Int64Indexing.time_getitem_lists                                                          6.76±0.1ms
    [  6.33%] ··· Running indexing.Int64Indexing.time_getitem_scalar                                                         16.1±0.2μs
    [  6.63%] ··· Running indexing.Int64Indexing.time_getitem_slice                                                          45.8±0.4μs
    [  6.93%] ··· Running indexing.Int64Indexing.time_iloc_array                                                             60.4±0.3μs
    [  7.23%] ··· Running indexing.Int64Indexing.time_iloc_list_like                                                         34.3±0.4μs
    [  7.53%] ··· Running indexing.Int64Indexing.time_iloc_scalar                                                            12.1±0.1μs
    [  7.83%] ··· Running indexing.Int64Indexing.time_iloc_slice                                                             34.1±0.4μs
    [  8.13%] ··· Running indexing.Int64Indexing.time_ix_array                                                                  780±5μs
    [  8.43%] ··· Running indexing.Int64Indexing.time_ix_list_like                                                              305±4μs
    [  8.73%] ··· Running indexing.Int64Indexing.time_ix_scalar                                                              54.1±0.7μs
    [  9.04%] ··· Running indexing.Int64Indexing.time_ix_slice                                                               73.3±0.9μs
    [  9.34%] ··· Running indexing.Int64Indexing.time_loc_array                                                                 930±8μs
    [  9.64%] ··· Running indexing.Int64Indexing.time_loc_list_like                                                             355±3μs
    [  9.94%] ··· Running indexing.Int64Indexing.time_loc_scalar                                                             44.1±0.3μs
    [ 10.24%] ··· Running indexing.Int64Indexing.time_loc_slice                                                                49.0±2μs
    [ 10.54%] ··· Running indexing.IntervalIndexing.time_getitem_list                                                          95.1±2μs
    [ 10.84%] ··· Running indexing.IntervalIndexing.time_getitem_scalar                                                        43.3±4μs
    [ 11.14%] ··· Running indexing.IntervalIndexing.time_loc_list                                                              76.0±1μs
    [ 11.45%] ··· Running indexing.IntervalIndexing.time_loc_scalar                                                            67.4±2μs
    [ 11.75%] ··· Running indexing.MultiIndexing.time_frame_xs_mi_ix                                                            312±2μs
    [ 12.05%] ··· Running indexing.MultiIndexing.time_is_monotonic                                                              240±2ns
    [ 12.35%] ··· Running indexing.MultiIndexing.time_multiindex_get_indexer                                                1.96±0.04ms
    [ 12.65%] ··· Running indexing.MultiIndexing.time_multiindex_large_get_loc                                                  270±5μs
    [ 12.95%] ··· Running indexing.MultiIndexing.time_multiindex_large_get_loc_warm                                             303±3ms
    [ 13.25%] ··· Running indexing.MultiIndexing.time_multiindex_med_get_loc                                                4.39±0.02μs
    [ 13.55%] ··· Running indexing.MultiIndexing.time_multiindex_med_get_loc_warm                                           4.20±0.03ms
    [ 13.86%] ··· Running indexing.MultiIndexing.time_multiindex_slicers                                                    5.51±0.02ms
    [ 14.16%] ··· Running indexing.MultiIndexing.time_multiindex_small_get_loc_warm                                         4.10±0.05ms
    [ 14.46%] ··· Running indexing.MultiIndexing.time_multiindex_string_get_loc                                             4.19±0.03μs
    [ 14.76%] ··· Running indexing.MultiIndexing.time_remove_unused_levels                                                      386±3μs
    [ 15.06%] ··· Running indexing.MultiIndexing.time_series_xs_mi_ix                                                           273±2μs
    [ 15.36%] ··· Running indexing.PanelIndexing.time_subset                                                                   903±10μs
    [ 15.66%] ··· Running indexing.StringIndexing.time_get_value                                                                354±3ms
    [ 15.96%] ··· Running indexing.StringIndexing.time_getitem_label_slice                                                      357±3ms
    [ 16.27%] ··· Running indexing.StringIndexing.time_getitem_pos_slice                                                     49.2±0.1μs
    [ 16.57%] ··· Running inference.DtypeInfer.time_timedelta64_1  [...]

2017-11-11 10:44 UTC, jreback commented
your new asv did not appear to run

2017-11-11 12:55 UTC, jreback commented
you don't need to post the entire run, just the changed benches.

2017-11-11 13:01 UTC, jreback requested changes
looks pretty good. some comments.

2017-11-11 13:01 UTC, jreback commented on asv_bench/benchmarks/timedelta.py
> +
I think these need to have time_ leading the name

2017-11-11 13:01 UTC, jreback commented on doc/source/whatsnew/v0.22.0.txt
> +- Vectorized Timedelta property access (:issue:`18092`)
be a bit more informative here

2017-11-11 13:01 UTC, jreback commented on pandas/core/indexes/timedeltas.py
> +        result = libts.get_timedelta_field(values, alias)
import this from tslibs.timedeltas directly

2017-11-11 13:01 UTC, jreback commented on pandas/_libs/tslib.pyx
> -    build_field_sarray)
you don't need this import, see below

2017-11-11 15:07 UTC, WillAyd commented
Changes made. See below for sample benchmark run. 

As far as the increase, on some runs microseconds failed, while other runs nanoseconds failed. There always one or the other. I think it has to do with some overhead in moving the computations out of timedeltas.pyx into np_datetimes.c but will report back with what I find

    before        after         ratio
    +88±1ns          210±2ns     1.12  timedelta.TimedeltaProperties.time_timedelta_microseconds
    -658±4ms      1.65±0.05ms    0.00    timedelta.DatetimeAccessor.time_timedelta_dt_accessor_microseconds
    -695±4ms      1.63±0.05ms    0.00  timedelta.DatetimeAccessor.time_timedelta_dt_accessor_seconds
    -684±4ms      1.59±0.01ms    0.00  timedelta.DatetimeAccessor.time_timedelta_dt_accessor_nanoseconds
    -681±4ms      1.57±0.02ms    0.00  timedelta.DatetimeAccessor.time_timedelta_dt_accessor_days

2017-11-11 16:22 UTC, jbrockmendel commented
This is nice.  Is the datetime.c bit the same as the numpy version?  Can any of it be `cdef extern`ed from numpy instead of implemented directly?

2017-11-11 16:47 UTC, WillAyd commented
I didn't see any method for converting a timedelta to a timedeltastruct in  [numpy's datetime.c](https://github.com/numpy/numpy/blob/68fd82271b9ea5a9e50d4e761061dfcca851382a/numpy/core/src/multiarray/datetime.c#L673)

FWIW I noticed some of the Timedelta properties defined in timedelta.pyx (namely days, seconds and microseconds) are superfluous as they already defined in [Cython's source](https://github.com/python/cpython/blob/191e993365ac3206f46132dcf46236471ec54bfa/Lib/datetime.py#L491). Do you think it's worth removing them from pandas as part of this?

2017-11-12 16:10 UTC, jreback approved these changes

2017-11-12 16:12 UTC, jreback commented
@WillAyd 

this looks good, just rebase on master.

> FWIW I noticed some of the Timedelta properties defined in timedelta.pyx (namely days, seconds and microseconds) are superfluous as they already defined in Cython's source. Do you think it's worth removing them from pandas as part of this?

I *think* you could do this (in a followup). The reason to leave them is that we have a consistent doc-string, and then future readers are not wondering where the 'missing' methods are. It might be a slight perf boost (though not as much as @jbrockmendel got with microseconds on Timestamp). 

So if you want to attack that would be great. (but in a followup).

2017-11-12 16:26 UTC, WillAyd commented
@jreback rebased

2017-11-12 18:02 UTC, merged

2017-11-12 18:02 UTC, jreback commented
thanks @WillAyd very nice. keep em coming!

2017-11-15 16:29 UTC, jbrockmendel commented
np_datetime.c has a `can_cast_timedelta64_units` that is apparently never used.  I don't see it in the diff for this PR.  Has it always been there?

2017-11-15 22:46 UTC, WillAyd commented
I see it dating back to the start of 2012 when I believe the file was created in 098ce734