BUG: MultiIndex not raising AttributeError with a million records (#1…
pandas-dev/pandas pull request #18229
Opened 2017-11-11 18:23 UTC by WillAyd

…8165)

- [X] closes #xxxx
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

2017-11-11 18:58 UTC, gfyoung commented on pandas/tests/indexes/test_multi.py
> +                           message="'Series' object has no attribute 'foo'"):
Let's use `tm.assert_raises_regex` instead.

2017-11-11 18:59 UTC, gfyoung commented on doc/source/whatsnew/v0.22.0.txt
> +- Bug where a ``MultiIndex`` with more than a million records was not raising ``AttributeError`` as expected (:issue:`18165`)
In what context?  Add something short to the end of that sentence to clarify.

2017-11-12 16:03 UTC, jreback commented on doc/source/whatsnew/v0.22.0.txt
>  - Bug in :func:`DataFrame.groupby` where key as tuple in a ``MultiIndex`` were interpreted as a list of keys (:issue:`17979`)
I think this is ok for 0.21.1, can you move. ping on when pushed.

2017-11-12 16:04 UTC, jreback requested changes
comments

2017-11-12 16:12 UTC, WillAyd commented
@jreback moved to v0.21.1

2017-11-12 16:13 UTC, jreback approved these changes

2017-11-12 16:14 UTC, merged

2017-11-12 16:14 UTC, jreback commented
thanks!