BUG: Fix filter method so that accepts byte and unicode column names
pandas-dev/pandas pull request #18238
Opened 2017-11-12 13:41 UTC by Licht-T

- [x] closes #13101
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-11-12 14:20 UTC, jreback requested changes
pls add a whatsnew for 0.21.1

2017-11-12 14:20 UTC, jreback commented on pandas/core/generic.py
> +                    x = bytes_to_str(x)
hmm can you codify these into a function in ``pandas/compat/__init__.py``, maybe ``to_str``, and add a doc-string so its clear what it does, put it right below the ``u/u_safe`` functions

2017-11-12 14:20 UTC, jreback commented on pandas/core/generic.py
> +                    x = bytes_to_str(x)
make it clear that you are turning bytes, non-strings into strings

2017-11-12 14:21 UTC, jreback requested changes

2017-11-12 14:21 UTC, jreback commented on pandas/tests/frame/test_axis_select_reindex.py
> +    @pytest.mark.parametrize('exp', ['a', u'a'])
can you add the example from the issue, e.g. with a non-ascii character

2017-11-12 14:21 UTC, jreback commented on pandas/tests/frame/test_axis_select_reindex.py
> +    @pytest.mark.parametrize('exp', ['a', u'a'])
add the issue number as a comment on the tests

2017-11-21 16:09 UTC, pep8speaks commented
Hello @Licht-T! Thanks for updating the PR.





 - In the file [`pandas/tests/frame/test_axis_select_reindex.py`](https://github.com/pandas-dev/pandas/blob/e46bc009d5089f43ac8f65bcf6e00ac1922342cc/pandas/tests/frame/test_axis_select_reindex.py), following are the PEP8 issues :

> [Line 887:45](https://github.com/pandas-dev/pandas/blob/e46bc009d5089f43ac8f65bcf6e00ac1922342cc/pandas/tests/frame/test_axis_select_reindex.py#L887): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2017-11-21 16:26 UTC, Licht-T commented
Thanks @jreback, now fixed!

2017-11-22 02:03 UTC, jreback approved these changes

2017-11-22 02:03 UTC, merged

2017-11-22 02:03 UTC, jreback commented
thanks @Licht-T very nice!