Groupby tuples
pandas-dev/pandas pull request #18249
Opened 2017-11-12 21:24 UTC by toobaz

- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Sorry for having missed #17996, where this could have been discussed, but this said I don't think we should treat specially the case of a ``MultiIndex`` (see the test I added with tuples as labels): we should just interpret what is not a list as a label, as the docs already state (although with some incoherence, which I tried to address).

While I was at it, I fixed a typo which made a test inserted in #17996 trivial.

2017-11-12 21:29 UTC, jreback requested changes

2017-11-12 21:29 UTC, jreback commented on pandas/core/groupby.py
> +    if not isinstance(key, list):
can you add a nice comment here, explaining

2017-11-12 21:29 UTC, jreback commented on pandas/core/generic.py
> +            labels may be passed to group by the columns in ``self``.
maybe callout what a tuple does.

2017-11-13 00:50 UTC, jreback commented
linting issue

2017-11-13 08:40 UTC, toobaz commented
> linting issue

Fixed! ping @jreback

2017-11-13 11:39 UTC, closed without merging

2017-11-13 11:39 UTC, jreback commented
thanks!