CLN: Remove unnecessary uses of pd. in tests
pandas-dev/pandas pull request #18277
Opened 2017-11-14 05:12 UTC by jschendel

- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

- Mostly edits along the lines of `pd.Series` -> `Series` for things that were already imported and had redundant uses of `pd`.  
- I cleaned some of the `import` statements, but I didn't import anything new, though that could be done in the future for further cleaning. 
- Was able to shorten some multi-line statements for a net deletion of ~100 lines without changing the content of any tests.
- Only did the base level `tests` and `tests/indexing` so far.

2017-11-14 11:23 UTC, jreback requested changes
happy to take this (one small comment). Ideally we could add a linting test for these, something along the lines of (of course have to augment with things we check for, which would things like DataFrame, Index, etc.).

you could start off but explicity using just certain files / dirs for now (IOW as you do them).

you can put this after the ``np.testing`` checks
``grep -r -E --include '*.py' 'pd\.Series' pandas/tests/``

2017-11-14 11:23 UTC, jreback commented on pandas/tests/test_sorting.py
> +        if compat.PY2 and not compat.numpy._np_version_under1p10:
I would import _np_version.... directly up top

2017-11-14 11:24 UTC, jreback commented
@jschendel just that one change is fine for now. the lint checks can be in a followup (or here if you can/want).

2017-11-14 20:32 UTC, jschendel commented
@jreback : made the one change. not familiar with the lint checks, so I'll hold off until a followup.

2017-11-15 11:27 UTC, jreback approved these changes

2017-11-15 11:27 UTC, merged

2017-11-15 11:28 UTC, jreback commented
thanks @jschendel would love to come back with something that we can add to ``ci/lint.sh`` to check the codebase automatically.

2020-11-06 02:08 UTC, jbrockmendel commented on pandas/tests/test_categorical.py
> +        code = "import pandas as pd; c = Categorical([])"
@jschendel @jreback why is removing pd OK here?  We have a couple tests with this pattern that look fishy to me, but they are passing on master so im confused