BUG: Use float64 for row counter in rank() GH18271
pandas-dev/pandas pull request #18274
Opened 2017-11-14 02:17 UTC by proinsias

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

As reported in #18271, for a large `Series` `s` of `float`s,
`Series.rank(pct=True).max()` may not be `<=1` as expected.

This is due to the use of a `float` for the row counter. This updates
the counter to use a `float64`.

2017-11-14 11:39 UTC, jreback requested changes
does your test from the original issue repro the failure?

2017-11-14 11:39 UTC, jreback commented on doc/source/whatsnew/v0.22.0.txt
> +- Fixed incorrect maximum :func:`Series.rank` percentile for large arrays (:issue:`18271`)
move to 0.21.1

2017-11-14 11:39 UTC, jreback commented on doc/source/whatsnew/v0.22.0.txt
> +- Fixed incorrect maximum :func:`Series.rank` percentile for large arrays (:issue:`18271`)
move to Numeric section

2017-11-14 15:52 UTC, proinsias commented
When I rerun the same code from #18271, I get the same result in `Rank_Pct` and `Rank_Pct_Manual`:

```
                abc          Rank      Rank_Pct  Rank_Pct_Manual
count  2.000000e+07  2.000000e+07  2.000000e+07     2.000000e+07
mean   4.999223e-01  1.000000e+07  5.000000e-01     5.000000e-01
std    2.886891e-01  5.773503e+06  2.886751e-01     2.886751e-01
min    1.036192e-08  1.000000e+00  5.000000e-08     5.000000e-08
25%    2.498756e-01  5.000001e+06  2.500000e-01     2.500000e-01
50%    4.999781e-01  1.000000e+07  5.000000e-01     5.000000e-01
75%    7.499111e-01  1.500000e+07  7.500000e-01     7.500000e-01
max    1.000000e+00  2.000000e+07  1.000000e+00     1.000000e+00
```

2017-11-14 15:55 UTC, proinsias commented on doc/source/whatsnew/v0.22.0.txt
> +- Fixed incorrect maximum :func:`Series.rank` percentile for large arrays (:issue:`18271`)
Both done. Thanks!

2017-11-15 11:36 UTC, jreback commented
tests

2017-11-22 02:28 UTC, jreback commented
pls rebase and update to comments

2018-01-21 18:09 UTC, jreback commented
closing as stale. if you want to continue working, pls ping.

2018-01-21 18:09 UTC, closed without merging