BUG: Use total_tie_count to normalize dense ranking
pandas-dev/pandas pull request #18297
Opened 2017-11-15 03:33 UTC by proinsias

- [x] closes #18296
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

As reported in #18296, for a `Series` with repeated values, `Series.rank(pct=True, method='dense').max()` may not be `<=1` as expected.

This is due to the division of the ranks by the total number of elements in the `Series`, instead of the maximum rank assigned. Here we update the calculation.

2017-11-15 03:34 UTC, proinsias commented
I've confirmed that the updated code gives the expected result from the example in #18296.

2017-11-15 07:04 UTC, jreback commented
how about some tests

2017-11-15 11:13 UTC, jreback commented
see #15630 (and linked PR soln but has comments).

2017-12-28 12:37 UTC, jreback requested changes

2017-12-28 12:37 UTC, jreback commented on doc/source/whatsnew/v0.21.1.txt
> +- Fixed incorrect maximum :func:`Series.rank` percentile when using the `dense` method with repeated values (:issue:`18296`)
can you move to 0.23

2018-02-10 18:44 UTC, jreback commented
closing as stale. ping if you want to update.

2018-02-10 18:44 UTC, closed without merging