BUG: #12815 Always use np.nan for missing values of object dtypes
pandas-dev/pandas pull request #18313
Opened 2017-11-15 20:19 UTC by mattayes

- [x] closes #12815
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] ~whatsnew entry~ (N/A)

Handles the issue of unstacked object columns filling missing values with `None` instead of `np.nan` by modifying `pd.core.dtypes.cast.maybe_promote()` to use a `fill_value` of `np.nan` (or `pd.NaT`) when the original `fill_value` is `None`.

Let me know if you'd like me to clarify anything!

2017-11-15 23:57 UTC, jreback requested changes
lgtm. pls add a note in 0.22 / other api changes.

2017-11-15 23:57 UTC, jreback commented on pandas/tests/frame/test_reshape.py
> +    # Test unstacking with object
add the issue number as a comment

2017-11-19 18:35 UTC, mattayes commented
@jreback Changes made.

2017-11-19 18:53 UTC, jreback commented
trivial change. push & ping when green.

2017-11-19 18:54 UTC, jreback approved these changes

2017-11-19 18:54 UTC, jreback commented on doc/source/whatsnew/v0.22.0.txt
> +- `Dataframe.unstack()` will now default to filling with `np.nan` for ``object`` columns. (:issue:`12815`)
use double-backticks around `` np.nan ``

2017-11-19 18:55 UTC, jreback commented
note if you are interested in cleaning some things up :>

``maybe_promote`` I think will pretty much ignore its fill value for almost all dtypes. So the question is, when is it *not* ignored, can we safely remove it (or really just make the default ``fill_value=None``, and then when its not ``None`` actually do something.

Not sure of the answer here.

2017-11-20 23:10 UTC, mattayes commented
@jreback Green

2017-11-21 00:41 UTC, merged

2017-11-21 00:41 UTC, jreback commented
thanks @mattayes