BUG: Fix Index.putmask makes stack overflow with an invalid mask
pandas-dev/pandas pull request #18407
Opened 2017-11-21 12:32 UTC by Licht-T

- [x] closes #18368
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-11-22 01:43 UTC, jreback requested changes
pls add a whatsnew note (0.21.1 is ok)

2017-11-22 01:43 UTC, jreback commented on pandas/core/indexes/base.py
> +            if self.dtype == np.dtype(object):
can you use ``is_object_dtype``

2017-11-22 01:43 UTC, jreback commented on pandas/core/indexes/base.py
> +            else:
just use the return here, no else is needed

2017-11-25 14:00 UTC, Licht-T commented
@jreback Thanks! Fixed!

2017-11-25 16:19 UTC, jreback approved these changes

2017-11-25 16:19 UTC, jreback commented
lgtm. ping on green.

2017-11-25 21:01 UTC, merged

2017-11-25 21:01 UTC, jreback commented
thanks @Licht-T keep em coming!