BLD: since we already use setuptools, let's remove the optional logic…
pandas-dev/pandas pull request #18448
Opened 2017-11-23 12:57 UTC by gkonefal-reef

… in setup.py (GH18113).

- [x] closes #18113 
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2017-11-23 15:30 UTC, jreback commented on setup.py
> +setuptools_kwargs["test_suite"] = "nose.collector"
remove this, its no longer needed

2017-11-23 15:33 UTC, jreback requested changes

2017-11-23 15:33 UTC, jreback commented on setup.py
>                                                'pytz >= 2011k',
this can be a bit simpler, e.g. use a common setuptool_kwargs, leaving out datetutil, then add this separately for PY2 and 3

2017-11-24 12:16 UTC, bashtage commented on doc/source/whatsnew/v0.22.0.txt
> +- BLD: since we already use setuptools, let's remove the optional logic in setup.py (:issue:`18113`)
This isn't the usual style of a what's new entry.  Something like "Simplified setup due to explicit dependence on setuptools (:issue...)"

2017-11-28 10:57 UTC, jreback commented
can you rebase and update

2017-12-03 10:16 UTC, pep8speaks commented
Hello @gkonefal-reef! Thanks for updating the PR.

 - In the file [`setup.py`](https://github.com/pandas-dev/pandas/blob/21cbe794695bdee41527a02c01c59faa164dd467/setup.py), following are the PEP8 issues :

> [Line 47:80](https://github.com/pandas-dev/pandas/blob/21cbe794695bdee41527a02c01c59faa164dd467/setup.py#L47): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)

2017-12-03 13:59 UTC, gkonefal-reef commented
I've applied changes as it was requested.

2017-12-03 15:40 UTC, jreback approved these changes

2017-12-03 15:41 UTC, jreback commented
ok re-running on travis [here](https://github.com/jreback/pandas/commit/c6b88e11268500c8cc26e397d66c30e0853d5022) just to make sure

2017-12-03 18:04 UTC, closed without merging

2017-12-03 18:05 UTC, jreback commented
thanks @gkonefal-reef