Fix issue 18434
pandas-dev/pandas pull request #18440
Opened 2017-11-23 02:43 UTC by Xbar

MultiIndex.from_tuples accept zipped tuples in python 3. Ensures compatibility
between 2 and 3.

- [x] closes #18434 
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2017-11-23 16:01 UTC, jreback requested changes

2017-11-23 16:01 UTC, jreback commented on pandas/core/indexes/multi.py
> +        if not hasattr(tuples, '__len__'):
would just do

```
if not is_list_like(tuples):
    raise TypeError...
elif is_iterator(tuples):
    tuples = list(tuples)
```

2017-11-23 16:01 UTC, jreback commented on pandas/core/indexes/multi.py
> +                iter(tuples)  # if iterable, then it's iterator or generator
needs checking in ``from_product`` and ``from_arrays`` as well. 

needs tests that hit all 3 cases

2017-11-24 03:19 UTC, Xbar commented
Added the test cases and fix from_tuples/from_arrays/from_product

2017-11-24 17:01 UTC, jreback requested changes
some error context comments. otherwise lgtm. ping on green.

2017-11-24 17:01 UTC, jreback commented on pandas/core/indexes/multi.py
> +            raise TypeError("Inappropriate input for list of arrays.")
make a more user-friendly message, maybe

``input must be a list-like of arrays``

2017-11-24 17:01 UTC, jreback commented on pandas/core/indexes/multi.py
> +            raise TypeError('Inappropriate input for tuples.')
same (except say tuples)

2017-11-24 17:01 UTC, jreback commented on pandas/core/indexes/multi.py
> +        if not is_list_like(iterables):
same

2017-11-24 17:01 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        # iterator as input
blank line here

2017-11-24 17:01 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        # invlide iterator input
same

2017-11-24 17:01 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        # input tuples
same

2017-11-24 19:51 UTC, jreback requested changes
pls rebase as well. lgtm. ping on green.

2017-11-24 19:51 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        # iterator as input
can you make this a separate test (the added code), and do so for from_product, from_tuples, from_arrays as well, call it something like

``test_multiindex_from_product_iterable`` and add the issue number to it.

2017-11-24 19:51 UTC, jreback commented on pandas/core/indexes/multi.py
> +            raise TypeError('Input must be a list /sequence of tuple-likes.')
need a space after the ``/``

2017-11-24 19:51 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        # input tuples
same (new test)

2017-11-24 19:51 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        res1 = MultiIndex.from_tuples(((1, 2), (3, 4)), names=['a', 'b'])
use result =

2017-11-24 19:51 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        res2 = MultiIndex.from_tuples(zip([1, 3], [2, 4]), names=['a', 'b'])
same

2017-11-24 19:51 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        assert res2.equals(expected)
use ``tm.assert_index_equal(result, expected)`` for the checking

2017-11-24 19:51 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        # iterator as input
separate test

2017-11-24 19:51 UTC, jreback commented on pandas/core/indexes/multi.py
> +
looks like you picked up another commit.

2017-11-25 01:30 UTC, Xbar commented
All build passed.

2017-11-25 15:08 UTC, jreback requested changes

2017-11-25 15:08 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        assert list(result) == list(self.index)
use ``tm.assert_index_equal``, IOW construct the expected MI

2017-11-25 15:08 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        assert result.equals(expected)
use assert_index_equal

2017-11-25 15:08 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        assert expected.names == result.names
same

2017-11-25 15:08 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        assert result.equals(expected)
same

2017-11-25 15:08 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        assert expected.names == result.names
same

2017-11-25 20:56 UTC, jreback approved these changes

2017-11-25 20:56 UTC, merged

2017-11-25 20:57 UTC, jreback commented
thanks @Xbar nice patch and very responsive interactions!

2017-11-25 22:13 UTC, Xbar commented
Thanks! 👍