Improve DatetimeIndex.time performance
pandas-dev/pandas pull request #18461
Opened 2017-11-24 02:39 UTC by tmnhat2001

xref #18058 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

  Speed up DatetimeIndex.time in a similar way to DatetimeIndex.date. Not sure whether the timezone information should be passed to `ints_to_pydatetime()` or not.

2017-11-24 11:53 UTC, bashtage commented on pandas/_libs/tslib.pyx
> +    assert ((box == "datetime") or (box == "date") or (box == "timestamp")
Why not use box in ('datetime', 'date',...)?  Seems unnecessarily C-like

2017-11-24 19:55 UTC, jreback requested changes

2017-11-24 19:55 UTC, jreback commented on pandas/_libs/tslib.pyx
>          func_create = create_datetime_from_ts
alternatively, can remove the assert and make else the raise case

2017-11-24 19:55 UTC, jreback commented
can you post the result of the asv as well (IOW how well does this do)

2017-12-09 22:16 UTC, tmnhat2001 commented
@jreback @bashtage sorry for the late reply. The asv is:  
```
             before                 after     ratio
         [e6eac0b3]            [c274e8d5]
-        9.17±0.2ms           1.17±0.02ms     0.13   timeseries.DatetimeIndex.time_dti_time
```
  
should any other changes be made in addition to changing the assertion to an else block?

2017-12-09 22:22 UTC, jreback commented
can u rebase

2017-12-10 16:22 UTC, jreback approved these changes

2017-12-10 16:22 UTC, merged

2017-12-10 16:22 UTC, jreback commented
thanks @tmnhat2001

2017-12-10 19:49 UTC, tmnhat2001 commented
thanks