BUG: Fix the un-pickleable plot with DatetimeIndex
pandas-dev/pandas pull request #18486
Opened 2017-11-25 17:30 UTC by Licht-T

- [x] closes #18439
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-11-25 17:38 UTC, jreback commented
can u add a test as well

2017-11-25 17:42 UTC, Licht-T commented
@jreback Where should I add test? `pandas/tests/plotting/*`?

2017-11-25 17:48 UTC, jreback commented
sure

2017-11-25 21:16 UTC, jreback commented
0.21.1 release note as well, yes ``pandas/tests/test_plotting`` is ok (or maybe in a misc section in plotting).

2017-11-26 01:14 UTC, Licht-T commented
Thanks @jreback, fixed!

2017-11-26 01:23 UTC, jreback commented
lgtm. ping on green.

2017-11-26 14:35 UTC, Licht-T commented
CI failed because of the test. I'll check.

2017-11-26 14:51 UTC, Licht-T commented
@jreback Seems that the pickling `instancemethod` only works in Python 3.

2017-11-26 14:58 UTC, Licht-T commented
Now added the restriction to Python 3.

2017-11-26 15:06 UTC, jreback commented on pandas/tests/plotting/test_datetimelike.py
> +            with ensure_clean(return_filelike=True) as path:
could test for the round trip here, but prob overkill

2017-11-26 15:07 UTC, jreback commented on pandas/tests/plotting/test_datetimelike.py
> +        # GH18439
why is this only PY3?

add a more informative comment, not just the issue, e.g. ensure round-trip pickle compat

2017-11-26 15:26 UTC, jreback requested changes

2017-11-26 15:26 UTC, jreback commented on pandas/tests/plotting/test_datetimelike.py
> +        # GH18439
@Licht-T saw your comment, ok then, just make a comment that we are pickling instancemethods which is supported on PY3 only (hmm thought this did work on PY2)

2017-11-27 21:44 UTC, jreback commented
can you update

2017-11-27 23:23 UTC, Licht-T commented
@jreback Okay! I'll re-check the pickling issue on Python 2 and update until tomorrow.

2017-12-02 17:39 UTC, jreback commented
can you update

2017-12-05 00:21 UTC, Licht-T commented
Sorry @jreback! Now updated!

2017-12-05 00:29 UTC, jreback commented
lgtm
ping on green

2017-12-06 11:26 UTC, jreback approved these changes

2017-12-06 11:26 UTC, merged

2017-12-06 11:26 UTC, jreback commented
thanks!