Fix tzaware dates mismatch error
pandas-dev/pandas pull request #18488
Opened 2017-11-25 19:31 UTC by aschade

- [x] closes #18431
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2017-11-25 21:20 UTC, jreback requested changes

2017-11-25 21:20 UTC, jreback commented on pandas/tests/indexes/datetimes/test_date_range.py
> +        dt1_tz = pd.Timestamp('2017-01-01', tz='US/Eastern')
add the issue number here as a comment

2017-11-25 21:20 UTC, jreback commented on pandas/tests/indexes/datetimes/test_date_range.py
> +        dt2_tz = pd.Timestamp('2017-01-04', tz='US/Eastern')
can you parametrize this test (IOW pass in start, end), cases for raising include:

- one naive, one with a tz & reversed
- different timezones & reversed

I don't think we care about the freq here.

2017-11-25 23:56 UTC, aschade commented
Updated tests

2017-11-26 00:07 UTC, jreback requested changes

2017-11-26 00:07 UTC, jreback commented on pandas/tests/indexes/datetimes/test_date_range.py
> +        #issue 18488
can use parametrize: http://pandas.pydata.org/pandas-docs/stable/contributing.html#using-pytest

2017-11-26 01:24 UTC, aschade commented
Gotcha, using parametrize now

2017-11-26 01:26 UTC, jreback commented
lgtm. ping on green.

2017-11-26 15:17 UTC, aschade commented
@jreback all green :)

2017-11-26 15:19 UTC, jreback approved these changes

2017-11-26 15:19 UTC, merged

2017-11-26 15:19 UTC, jreback commented
thanks @aschade