bugfix for FY5253 case with bunched yearends
pandas-dev/pandas pull request #18550
Opened 2017-11-28 17:14 UTC by jbrockmendel

Also achieves coverage for one of the uncovered branches in `FY5253.apply`

- [x] closes #14774
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-11-28 23:56 UTC, jreback commented
cc @cancan101

2017-11-28 23:57 UTC, jreback commented
release note pls.

2017-12-03 15:24 UTC, jbrockmendel commented
Ping.

2017-12-03 16:39 UTC, jreback requested changes

2017-12-03 16:39 UTC, jreback commented on pandas/tests/tseries/offsets/test_fiscal.py
> +    assert dt - fy == Timestamp('2002-12-28')
can you add from the OP: ``fy.rollback(pd.Timestamp('2003-12-31'))`` (which I think is the same result) as well

2017-12-03 16:40 UTC, jreback commented
cc @ronif can you have a look.

2017-12-06 04:23 UTC, jbrockmendel commented
Just rebased and pushed; no new changes.

2017-12-06 11:15 UTC, jreback approved these changes

2017-12-06 11:15 UTC, merged

2017-12-06 11:15 UTC, jreback commented
thanks