BUG: Fix TimeFormatter behavior with fractional seconds
pandas-dev/pandas pull request #18552
Opened 2017-11-28 19:37 UTC by nmartensen

- [x] closes #18478
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-12-02 15:44 UTC, jreback commented
@TomAugspurger

2017-12-02 17:26 UTC, TomAugspurger approved these changes
Ping on green.

2017-12-02 17:29 UTC, jreback requested changes

2017-12-02 17:29 UTC, jreback commented on pandas/plotting/_converter.py
> -        fmt = '%H:%M:%S'
can you add a doc-string here

2017-12-02 17:29 UTC, jreback commented on pandas/tests/plotting/test_converter.py
> +        assert rs == xp
can you add a blank line before the comments

2017-12-02 17:29 UTC, jreback commented on pandas/tests/plotting/test_converter.py
> -        self.tc(90000)
add the issue number here as a comment

2017-12-02 17:29 UTC, jreback commented on pandas/tests/plotting/test_converter.py
> +        rs = self.tc(90000)
I think we need a test from the original issue, which check that the plot works

2017-12-09 13:08 UTC, nmartensen commented
Do you know why GH still says "changes requested"? I believe all comments are addressed.

2017-12-09 15:14 UTC, jreback requested changes
can you post a plot from before and after here

2017-12-09 15:14 UTC, jreback commented on doc/source/whatsnew/v0.21.1.txt
> +- Bug in :class:`TimeFormatter` when trying to display fractional seconds (:issue:`18478`).
move to 0.22.0

2017-12-09 15:15 UTC, jreback commented on doc/source/whatsnew/v0.21.1.txt
> +- Bug in :class:`TimeFormatter` when trying to display fractional seconds (:issue:`18478`).
actually this is ok

2017-12-09 15:15 UTC, jreback commented on pandas/plotting/_converter.py
> -        fmt = '%H:%M:%S'
cam you add a Parameters sections

2017-12-09 15:15 UTC, jreback commented on pandas/plotting/_converter.py
> -        fmt = '%H:%M:%S'
and a Returns

2017-12-09 15:33 UTC, nmartensen commented
Example code:
```python
ax = pandas.DataFrame({'A': 1}, index=[pydt.time(11, 2, 59, 899502), pydt.time(11, 3, 0, 123456)]).plot()
for l in ax.xaxis.get_majorticklabels():
    l.set_rotation(45)
    l.set_horizontalalignment('right')
```
Output before:
![eleven_before](https://user-images.githubusercontent.com/16715246/33796929-80e58a0e-dcfe-11e7-802e-298f6fdc1dec.png)

Output after:
![eleven_after](https://user-images.githubusercontent.com/16715246/33796931-88d898c8-dcfe-11e7-873e-a4561ae37fc0.png)

2017-12-09 15:35 UTC, jreback commented
is it standard to only show the most resolved, IOW, ``11:03`` rather than ``11:03:00``, IOW we always want to show HH:MM:SS (but not show millis unless needed).

2017-12-09 15:42 UTC, nmartensen commented
My original motivation to change the TimeFormatter was to get rid of the :SS since I was always plotting full days. But if you prefer, we can drop that commit.

I didn't discover the sub-second breakage from a real usecase, but while reading the code to figure out where I'd need to change it for the above.

2017-12-09 15:46 UTC, jreback commented
> My original motivation to change the TimeFormatter was to get rid of the :SS since I was always plotting full days. But if you prefer, we can drop that commit.

do we do a similar thing for fractional datetimes? cc @TomAugspurger @jorisvandenbossche @tacaswell

2017-12-09 15:58 UTC, nmartensen commented on pandas/plotting/_converter.py
> -        fmt = '%H:%M:%S'
done

2017-12-09 16:08 UTC, nmartensen commented
The ideal way would probably be to not show the seconds if they are zero for each tick position, and show them if they are non-zero for at least one tick position. But I don't know how to implement that.

2017-12-15 22:37 UTC, nmartensen commented
For comparison some plots illustrating tick labels with datetimes. Code:
```python
fig, axes = plt.subplots(nrows=6, ncols=1, figsize=(6, 10))
for i, ut in enumerate(['H', 'min', 'S', 'ms', 'us', 'N']):
    dti = pandas.date_range('11:02:59.889502', periods=2, freq='200'+ut)
    pandas.DataFrame({'A': 1}, index=dti).plot(ax=axes[i])
    axes[i].set_title('delta t = 200'+ut, position=(0.5, 0.6))
    axes[i].text(0.5, 0.1, str(dti.max()-dti.min()), transform=axes[i].transAxes, ha='center')

plt.tight_layout()
```
Resulting output:
![datetime_ticklabels](https://user-images.githubusercontent.com/16715246/34063141-8c29738e-e1f0-11e7-918c-7363844186e1.png)

2017-12-21 15:31 UTC, jreback commented
thanks @nmartensen

2017-12-21 15:31 UTC, closed without merging