Cleanup cimports
pandas-dev/pandas pull request #18556
Opened 2017-11-29 02:02 UTC by jbrockmendel

2017-11-29 02:06 UTC, jreback commented on pandas/_libs/tslib.pxd
> -
used in setup.py anywhere?

2017-11-29 02:07 UTC, jbrockmendel commented on pandas/_libs/tslib.pxd
> -
Nope

2017-11-29 11:40 UTC, jreback requested changes

2017-11-29 11:40 UTC, jreback commented on pandas/_libs/src/inference.pyx
> +from tslibs.conversion cimport convert_to_tsobject
need to add ``conversion.pxd`` as a dep for lib.pyx (tslib.pyd should have been there)

2017-12-03 20:05 UTC, jbrockmendel commented
ping

2017-12-03 22:57 UTC, jreback approved these changes

2017-12-03 22:57 UTC, merged

2017-12-03 22:57 UTC, jreback commented
thanks!