Fix parquet error and add HDFS reading
pandas-dev/pandas pull request #18568
Opened 2017-11-29 18:43 UTC by AbdealiJK

- Fix the parquet error message if no package is installed.
 - Add HDFS reading using `libhdfs3`

- [x] closes #18199
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2017-11-29 23:48 UTC, jreback requested changes

2017-11-29 23:48 UTC, jreback commented on pandas/io/hdfs.py
> +if compat.PY3:
these should be moved to ``pandas/compat/__init__.py`` (and same change in pandas.io.s3fs)

2017-11-29 23:48 UTC, jreback commented on pandas/io/parquet.py
> +                          "tried using: pyarrow, fastparquet\n\n"
why are you changing this? IIRC this is a separeate issue, make it a separate PR

2017-11-29 23:48 UTC, jreback commented on pandas/io/hdfs.py
> +    import hdfs3
you need to add hdfs3 on *some* builds (you can put on the same as s3fs) is fine in pandas/ci

2017-11-29 23:48 UTC, jreback commented on pandas/io/common.py
you need

``need_text_wrapping = tuple(need_text_wrapping)`` before ``handles``

2017-11-29 23:48 UTC, jreback commented on doc/source/whatsnew/v0.22.0.txt
> +- :func:`read_csv` now supports reading from hdfs by giving "hdfs:///tmp/data.csv". The hadoop configs will try to be automatically found. The configs can also be mentioned using the format "hdfs://n
add in the Other Enhancements section. Add documentionat in io.rst (where s3 docs are found)

2017-12-10 23:48 UTC, jorisvandenbossche commented
@AbdealiJK I cherry-picked your first commit (as this was an easy change) and merged that in a separate PR (https://github.com/pandas-dev/pandas/pull/18717).

Can you update the hdfs part according to the comments?

2017-12-11 07:13 UTC, AbdealiJK commented
Thanks Jeff. Modifying this is on my ToDo - a bit pre-occupied at the
moment.  Will do it soon.

On Dec 11, 2017 5:19 AM, "Joris Van den Bossche" <notifications@github.com>
wrote:

> @AbdealiJK <https://github.com/abdealijk> I cherry-picked your first
> commit (as this was an easy change) and merged that in a separate PR (
> #18717 <https://github.com/pandas-dev/pandas/pull/18717>).
>
> Can you update the hdfs part according to the comments?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/18568#issuecomment-350592114>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACGUp9qUKaEqZNXVDuVXIqtlG8nO2TAPks5s_G3-gaJpZM4QvcDi>
> .
>

2017-12-16 07:04 UTC, pep8speaks commented
Hello @AbdealiJK! Thanks for updating the PR.



 - In the file [`pandas/io/common.py`](https://github.com/pandas-dev/pandas/blob/a55e848f33ec7c738a3d4fd3f48dea53e9d8bed1/pandas/io/common.py), following are the PEP8 issues :

> [Line 106:5](https://github.com/pandas-dev/pandas/blob/a55e848f33ec7c738a3d4fd3f48dea53e9d8bed1/pandas/io/common.py#L106): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'

 - In the file [`pandas/io/hdfs.py`](https://github.com/pandas-dev/pandas/blob/a55e848f33ec7c738a3d4fd3f48dea53e9d8bed1/pandas/io/hdfs.py), following are the PEP8 issues :

> [Line 5:1](https://github.com/pandas-dev/pandas/blob/a55e848f33ec7c738a3d4fd3f48dea53e9d8bed1/pandas/io/hdfs.py#L5): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'

2017-12-16 07:15 UTC, AbdealiJK commented
For the unit test: I need some help in setting up HDFS inside Travis.
The way other orgs are doing this is by using their own dockers: [Example of hdfs3's CI](https://github.com/dask/hdfs3/blob/master/continuous_integration/Dockerfile)

Pandas does not seem to have it's own docker ... so a little confused about this.

Manually I've tested the following:
 - If hdfs3 is not installed, Throws:
```
ImportError: The hdfs3 library is required to handle hdfs files
```
 - If hdfs3 is installed but libhdfs3 is not installed, Throws:
```
ImportError: Can not find the shared library: libhdfs3.so
See installation instructions at http://hdfs3.readthedocs.io/en/latest/install.html
```
 - If hdfs3 is installed it works for the code: pd.read_csv("hdfs://localhost:9000/tmp/a.csv")
 - If hdfs3 is installed it works if export HADOOP_CONF_DIR=/usr/local/Cellar/hadoop/2.7.0/libexec/etc/hadoop/ is done and pd.read_csv("hdfs:///tmp/a.csv") is provided

2018-02-01 13:22 UTC, jreback commented
if you can rebase. this would require a testing setup similar to this:

https://github.com/dask/dask/tree/master/continuous_integration/hdfs

2018-03-16 22:07 UTC, jreback commented
closing as stale. nice idea, but we have to be able to automatically test this.

2018-03-16 22:07 UTC, closed without merging