BUG: Unwanted conversion from timedelta to float (#18493)
pandas-dev/pandas pull request #18586
Opened 2017-12-01 08:50 UTC by fjdiod

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-12-01 11:26 UTC, jreback requested changes
lgtm. mostly style comments. ping on green.

2017-12-01 11:26 UTC, jreback commented on doc/source/whatsnew/v0.22.0.txt
> +- Bug in ``TimeDeltaBlock._can_hold_element()`` where masked assignment of a timedelta series converts the series values to float64 (:issue:`18493`)
you can move to 0.21.1

don't use internal language here, these are user-level notes. So say something like

Bug in masked assignment of a ``timedelta64[ns]`` dtype ``Series`` with a ``Timedelta`` incorrectly coerced to float.

2017-12-01 11:26 UTC, jreback commented on pandas/tests/indexing/test_timedelta.py
> +from numpy import nan
don't import this, use ``np.nan``

2017-12-01 11:26 UTC, jreback commented on pandas/tests/indexing/test_timedelta.py
> +        series = pd.Series([0, 1, 2], dtype='timedelta64[ns]')
add the issue number here as a commet

2017-12-01 11:26 UTC, jreback commented on pandas/tests/indexing/test_timedelta.py
> +        [(None, [pd.NaT, 1, 2]),
you don't need to pass expected here as they are the same, just define in the body

2017-12-01 11:26 UTC, jreback commented on pandas/tests/indexing/test_timedelta.py
> +    def test_nan(self, value, expected):
name this like: test_masked_setitem

2017-12-01 11:26 UTC, jreback commented on pandas/tests/indexing/test_timedelta.py
> +        expected = pd.Series([pd.NaT, 1, 2], dtype='timedelta64[ns]')
test with ``.loc`` as well

2017-12-01 12:07 UTC, fjdiod commented
Hello, ok will fix that. Also, additional commits should be combined into one?

2017-12-01 12:16 UTC, jreback commented
you don’t need to combine you can just push more

2017-12-02 17:37 UTC, jreback approved these changes

2017-12-02 17:43 UTC, merged

2017-12-02 17:43 UTC, jreback commented
thanks @fjdiod