json_normalize: Make code more pythonic and avoid modification of meta if mutable
pandas-dev/pandas pull request #18610
Opened 2017-12-03 13:54 UTC by davidfischer-ch

- [ ] closes itself
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

- Update json_normalize to prevent modifying `meta` parameter.
- Make the code more Pythonic too.

2017-12-03 16:34 UTC, jreback requested changes
can you add a whatsnew not for 0.21.1

2017-12-03 16:34 UTC, jreback commented on pandas/tests/io/json/test_normalize.py
> +        data = [{'foo': 'hello',
can you add the issue number here

2017-12-04 11:54 UTC, davidfischer-ch commented
@jreback is it OK now? Thanks.

2017-12-04 12:55 UTC, jreback approved these changes

2017-12-04 12:55 UTC, merged

2017-12-04 12:55 UTC, jreback commented
thanks!