BUG: Fix tz-aware DatetimeIndex +/- TimedeltaIndex/timedelta64 array
pandas-dev/pandas pull request #18653
Opened 2017-12-06 01:00 UTC by jschendel

- [X] closes #17558
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

Added the whatsnew entry under 0.22.0, but could possibly go under 0.21.1.  This PR is a prereq for #18558.

2017-12-06 01:31 UTC, jreback requested changes
let's keep under 0.22

2017-12-06 01:31 UTC, jreback commented on pandas/tests/indexes/datetimes/test_arithmetic.py
> +        result = dti + tdi
also test a reverse add

2017-12-06 01:31 UTC, jreback commented on pandas/tests/indexes/datetimes/test_arithmetic.py
> +        result = dti - tdi
test that the reverse ops raise

2017-12-06 08:18 UTC, jschendel commented on pandas/tests/indexes/datetimes/test_arithmetic.py
> +        result = dti + tdi
done

2017-12-06 08:19 UTC, jschendel commented on pandas/tests/indexes/datetimes/test_arithmetic.py
> +        result = dti - tdi
done

2017-12-07 01:19 UTC, jreback approved these changes

2017-12-07 01:19 UTC, merged

2017-12-07 01:19 UTC, jreback commented
thanks @jschendel 

very nice; keep em coming!