ERR: ValueError when merging on incompatible dtypes
pandas-dev/pandas pull request #18674
Opened 2017-12-06 23:50 UTC by reidy-p

- [ ] closes #9780
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-12-06 23:50 UTC, pep8speaks commented
Hello @reidy-p! Thanks for submitting the PR.



 - In the file [`pandas/tests/reshape/merge/test_merge.py`](https://github.com/pandas-dev/pandas/blob/0773aeefaa84f4f5c9ff3e9489ca751401aaff61/pandas/tests/reshape/merge/test_merge.py), following are the PEP8 issues :

> [Line 1393:71](https://github.com/pandas-dev/pandas/blob/0773aeefaa84f4f5c9ff3e9489ca751401aaff61/pandas/tests/reshape/merge/test_merge.py#L1393): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2017-12-07 01:35 UTC, jreback requested changes

2017-12-07 01:35 UTC, jreback commented on pandas/core/reshape/merge.py
> +                msg = ("You are trying to merge on {lk_dtype} and "
can you do these as separate elif (rather than catch these on the big else, which should be just for the object type)

2017-12-07 01:35 UTC, jreback commented on pandas/tests/reshape/merge/test_merge.py
> -            result = pd.merge(left, right, on='A')
can you parameterize this test

2017-12-07 11:13 UTC, jreback commented
rebase and looks good to go.

2017-12-08 00:27 UTC, jreback approved these changes

2017-12-08 00:27 UTC, jreback commented on doc/source/whatsnew/v0.22.0.txt
> +- Building pandas for development now requires ``cython >= 0.24`` (:issue:`18613`)
hmm this moved, can you fixup

2017-12-10 15:41 UTC, merged

2017-12-10 15:41 UTC, jreback commented
thanks @reidy-p

2017-12-10 15:47 UTC, inodb commented
Thanks for the fix @reidy-p and @jreback