BUG: Pass kwargs from Index.to_series to pd.Series
pandas-dev/pandas pull request #18707
Opened 2017-12-10 00:27 UTC by alysivji

- [x] closes #18699
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Please let me know if you have any questions

2017-12-10 15:48 UTC, jreback requested changes

2017-12-10 15:48 UTC, jreback commented on pandas/core/indexes/base.py
instead of this, simply list the kwargs that we accept, ``name=None, index=None`` and pass them thru.

2017-12-10 15:48 UTC, jreback commented on pandas/core/indexes/datetimes.py
> +    def to_series(self, keep_tz=False, **kwargs):
same

2017-12-10 15:48 UTC, jreback commented on pandas/tests/indexes/common.py
> +
you can do this in 1 test

2017-12-10 15:48 UTC, jreback commented on doc/source/whatsnew/v0.22.0.txt
> +- :func:`DatetimeIndex.to_series` now allows kwargs which are passed to :class:`Series` constructor (:issue:`18699`)
just same we now only accept kwargs ``name,index`` ``:func;`Index..to_series` ``

2017-12-10 15:49 UTC, jreback commented on doc/source/whatsnew/v0.22.0.txt
> +- :func:`DatetimeIndex.to_series` now allows kwargs which are passed to :class:`Series` constructor (:issue:`18699`)
actually, make this in the bug-fix section and not here

2017-12-10 23:52 UTC, alysivji commented
Completed requested changes and rebased.

2017-12-13 04:13 UTC, alysivji commented
@jreback Changes have been made. Anything else that needs to be done?

2017-12-13 14:36 UTC, jreback approved these changes

2017-12-13 14:36 UTC, merged

2017-12-13 14:36 UTC, jreback commented
thanks!