BUG: Fix df.loc slice support
pandas-dev/pandas pull request #18703
Opened 2017-12-09 12:02 UTC by Licht-T

- [x] closes #8856
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-12-09 12:13 UTC, jreback requested changes
whatsnew 0.22

2017-12-09 12:13 UTC, jreback commented on pandas/tests/indexing/test_multiindex.py
> +        # GH8856
make separate test

2017-12-09 12:13 UTC, jreback commented on pandas/core/indexes/multi.py
> +        if isinstance(key, slice):
can u add some comments here

2017-12-09 12:13 UTC, jreback commented on pandas/tests/indexing/test_multiindex.py
> +        s = pd.Series(np.arange(10),
is this a duplicate of the other test?

2017-12-09 12:13 UTC, jreback commented on pandas/tests/indexing/test_multiindex.py
> +                      pd.MultiIndex.from_product(([0, 1], list('abcde'))))
can u add several cases using slices

also if other testing of slice u can pull to this section

2017-12-09 14:54 UTC, Licht-T commented
@jreback Oops, sorry! I overlooked another test.
The `MultiIndex` `loc` slicing work at the first level.
https://github.com/pandas-dev/pandas/blob/master/pandas/tests/test_multilevel.py#L1829
### Input:
```python
s = pd.Series(np.arange(8), pd.MultiIndex.from_product(([0, 1, 2, 3], list('ab'))))
s.loc[::2] = 200
s
```
### Output:
```
0  a    200
   b    200
1  a      2
   b      3
2  a    200
   b    200
3  a      6
   b      7
```

But, this returns the crazy result.
### Input:
```python
index = pd.MultiIndex(levels=[['foo', 'bar', 'baz', 'qux'], ['one', 'two','three']],
                      labels=[[0, 0, 0, 1, 1, 2, 2, 3, 3, 3], [0, 1, 2, 0, 1, 1, 2, 0, 1, 2]],
                      names=['first', 'second'])
frame = pd.DataFrame(np.random.randn(10, 3), index=index, columns=pd.Index(['A', 'B', 'C'], name='exp'))
frame.loc['foo':'bar':4]
```
### Output:
```
exp                  A         B         C
first second
foo   one     0.870785  1.900457 -0.907938
bar   two    -0.290714 -0.211697 -0.957994
```

2017-12-09 14:55 UTC, jreback commented
@toobaz if you'd have a look

2017-12-09 17:23 UTC, Licht-T commented
I think slicing by string is not good since `slice` seems not supporting string.

2017-12-12 17:03 UTC, toobaz commented on pandas/tests/indexing/test_multiindex.py
> +        s = pd.Series(np.arange(10),
(``.iloc`` vs. ``.loc``)

2017-12-12 17:23 UTC, toobaz commented
@Licht-T : I'm confused. Unless I'm missing anything, your changes to code are limited to ``pd.MultiIndex.get_loc``, but in up-to-date master,
- none of the problematic examples in #8856 hits ``pd.MultiIndex.get_loc``
- none of the tests you add addresses any of the problematic examples in #8856 
- none of the tests you add hits ``pd.MultiIndex.get_loc``

... ?

2018-02-10 18:43 UTC, jreback commented
closing as stale. ping if you want to update.

2018-02-10 18:43 UTC, closed without merging