DOC: read_csv usecols element order is ignored
pandas-dev/pandas pull request #18729
Opened 2017-12-11 17:30 UTC by ignamv

- [x] closes #18673
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-12-12 01:10 UTC, jreback requested changes

2017-12-12 01:10 UTC, jreback commented on pandas/io/parsers.py
> +    `usecols` parameter would be [0, 1, 2] or ['foo', 'bar', 'baz']. Element
can you also add this note to io.rst

2017-12-16 10:26 UTC, ignamv commented on pandas/io/parsers.py
> +    `usecols` parameter would be [0, 1, 2] or ['foo', 'bar', 'baz']. Element
Done.

2017-12-21 15:24 UTC, jreback approved these changes

2017-12-21 15:24 UTC, merged

2017-12-21 15:24 UTC, jreback commented
thanks @ignamv

2017-12-22 12:50 UTC, ignamv commented
No problem.