BUG: Fix IntervalIndex.to_tuples() with NA values
pandas-dev/pandas pull request #18757
Opened 2017-12-13 03:56 UTC by jschendel

- [X] closes #18756
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

2017-12-15 00:55 UTC, jreback requested changes

2017-12-15 00:55 UTC, jreback commented on pandas/core/indexes/interval.py
>          """Return an Index of tuples of the form (left, right)"""
I guess would be ok to add a kwarg ``na_tuple=False`` here to select behavior as @shoyer suggests.

2017-12-15 01:33 UTC, jschendel commented
Added the `na_tuple` kwarg.  Had to do some explicit checks of the NA value in the test, due equality issues with tuples of NA (see https://github.com/pandas-dev/pandas/issues/18756#issuecomment-351881631 for an example)

2017-12-15 11:31 UTC, jreback approved these changes

2017-12-15 11:32 UTC, merged

2017-12-15 11:32 UTC, jreback commented
thanks @jschendel

2017-12-16 18:33 UTC, shoyer commented
Indeed, thanks!