DEPR: Deprecate is_copy (#18801)
pandas-dev/pandas pull request #18812
Opened 2017-12-17 14:10 UTC by cbertinato

Not all tests for this branch on the fork are passing, but these are the same tests that fail for the clean master and appear to be unrelated to the changes.

References to is_copy in tests were changed to the internal attribute _is_copy assuming that, though is_copy is not meant to be a public attribute, checking the state of this attribute is necessary to check consistent internal behavior.

2017-12-17 21:30 UTC, gfyoung commented on pandas/core/generic.py
> +                      "version.", FutureWarning, stacklevel=2)
Say : "is deprecated and will removed..."

2017-12-17 21:30 UTC, gfyoung commented on pandas/core/generic.py
> +                      "version.", FutureWarning, stacklevel=2)
Also, add a test for this deprecation (both for getter and setter).

2017-12-18 12:21 UTC, jreback requested changes
can you add a whatsnew note in the deprecation section & a test (as @gfyoung indicates); you can put this in pandas/tests/indexing/test_chainging_and_caching.py

2017-12-18 15:27 UTC, pep8speaks commented
Hello @cbertinato! Thanks for updating the PR.









 - In the file [`pandas/tests/indexing/test_chaining_and_caching.py`](https://github.com/pandas-dev/pandas/blob/9b8f2af0cc434d1e51015ffc77b1715980e12e66/pandas/tests/indexing/test_chaining_and_caching.py), following are the PEP8 issues :

> [Line 424:9](https://github.com/pandas-dev/pandas/blob/9b8f2af0cc434d1e51015ffc77b1715980e12e66/pandas/tests/indexing/test_chaining_and_caching.py#L424): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

2017-12-18 20:04 UTC, cbertinato commented
Shall I squash these commits into one and resubmit, or can we do it on the merge?

2017-12-18 20:06 UTC, jreback commented
no need to squash

will be auto done on merge

2017-12-20 23:20 UTC, cbertinato commented
I am by no means in a rush, but just wanted to check whether this is waiting on anything else. I believe that the requested changes have been made.

2017-12-20 23:35 UTC, cbertinato commented
Roger that!

2017-12-21 15:07 UTC, jreback approved these changes

2017-12-21 15:07 UTC, merged

2017-12-21 15:07 UTC, jreback commented
thanks @cbertinato

2017-12-23 09:23 UTC, topper-123 commented
When tab-completing in iPython, the ``FutureWarning`` for ``is_copy`` pops up.

I believe that ``'is_copy'`` should be added to ``_deprecations``

2017-12-23 13:23 UTC, jreback commented
yep that is right - PR?

2017-12-23 15:58 UTC, cbertinato commented
PR #18922