CLN: ASV replace
pandas-dev/pandas pull request #18833
Opened 2017-12-19 05:21 UTC by mroeschke

- Flake8'd and removed star imports

For the `ReplaceDict` benchmark I reduced the number of samples from 10^6 to 10^5 because it was taking a significant amount of time, but 10^5 samples should still be representative of a large sample performance.

```
asv dev -b ^replace
· Discovering benchmarks
· Running 4 total benchmarks (1 commits * 1 environments * 4 benchmarks)
[  0.00%] ·· Building for existing-py_home_matt_anaconda_envs_pandas_dev_bin_python
[  0.00%] ·· Benchmarking existing-py_home_matt_anaconda_envs_pandas_dev_bin_python
[ 25.00%] ··· Running replace.Convert.time_replace                                                               ok
[ 25.00%] ···· 
               ============ =========== ===========
               --                 replace_data     
               ------------ -----------------------
                contructor   Timestamp   Timedelta 
               ============ =========== ===========
                DataFrame      411ms       409ms   
                  Series       349ms       349ms   
               ============ =========== ===========

[ 50.00%] ··· Running replace.NaN.time_fillna                                                                    ok
[ 50.00%] ···· 
               ========= ========
                inplace          
               --------- --------
                  True    6.42ms 
                 False    15.0ms 
               ========= ========

[ 75.00%] ··· Running replace.NaN.time_replace                                                                   ok
[ 75.00%] ···· 
               ========= ========
                inplace          
               --------- --------
                  True    7.09ms 
                 False    23.6ms 
               ========= ========

[100.00%] ··· Running replace.ReplaceDict.time_replace_series                                                    ok
[100.00%] ···· 
               ========= =======
                inplace         
               --------- -------
                  True    7.43s 
                 False    7.48s 
               ========= =======
```

2017-12-19 11:06 UTC, jreback requested changes

2017-12-19 11:06 UTC, jreback commented on asv_bench/benchmarks/replace.py
> +class NaN(object):
can you give this class a more informative name, maybe FillNA?

2017-12-20 07:22 UTC, mroeschke commented
Changed the class name from `NaN` to `Fillna`

2017-12-21 15:05 UTC, jreback approved these changes

2017-12-21 15:06 UTC, merged

2017-12-21 15:06 UTC, jreback commented
thanks @mroeschke