BUG: Stack/unstack do not return subclassed objects (GH15563)
pandas-dev/pandas pull request #18929
Opened 2017-12-24 14:07 UTC by rockg

- [x] closes #15563
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Basically picked from #15655 to support stack/unstack in subclassed DataFrames and Series.

2017-12-26 22:10 UTC, jreback requested changes
looks pretty good.

2017-12-26 22:10 UTC, jreback commented on doc/source/whatsnew/v0.23.0.txt
> +- Bug in :func:`DataFrame.stack`, `DataFrame.unstack`, `Series.unstack` which were not returning subclasses (:issue:`15563`)
need to have the ``:func:`` for each one

2017-12-26 22:10 UTC, jreback commented on pandas/core/reshape/reshape.py
> +    constructor : object, default DataFrame
thanks!

2017-12-26 22:10 UTC, jreback commented on pandas/core/reshape/reshape.py
> +        if constructor is None:
hmm I hate if then's like this. any better way?

2017-12-26 22:10 UTC, jreback commented on pandas/core/reshape/reshape.py
>          unstacker = _Unstacker(obj.values, obj.index, level=level,
might be a slightly bigger change, but could pass ``obj`` to ``_Unstacker`` directly and *might* be simpler.

2017-12-30 18:06 UTC, pep8speaks commented
Hello @rockg! Thanks for updating the PR.



 - In the file [`pandas/core/reshape/reshape.py`](https://github.com/pandas-dev/pandas/blob/2d3683b3257acb46f9afe7d24d2c62c7e49d0afd/pandas/core/reshape/reshape.py), following are the PEP8 issues :

> [Line 218:26](https://github.com/pandas-dev/pandas/blob/2d3683b3257acb46f9afe7d24d2c62c7e49d0afd/pandas/core/reshape/reshape.py#L218): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation

2017-12-30 18:08 UTC, rockg commented
Tried to incorporate obj into `_Unstacker`.  Take a look.  When there's a mixed frame being unstacked the underlying blocks are unstacked and so passing obj doesn't really work.

2017-12-30 18:12 UTC, jreback commented
can you revert back to what you had. that was ok for now. its not as clear this way.

2018-01-12 01:16 UTC, rockg commented
All green.

2018-01-12 11:48 UTC, jreback approved these changes

2018-01-12 11:49 UTC, merged

2018-01-12 11:49 UTC, jreback commented
thanks @rockg