Deprecation
pandas-dev/pandas pull request #18934
Opened 2017-12-25 00:17 UTC by datapythonista

- [X] closes #18928 
- [X] tests passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2017-12-25 00:18 UTC, pep8speaks commented
Hello @datapythonista! Thanks for submitting the PR.











 - In the file [`pandas/util/_decorators.py`](https://github.com/pandas-dev/pandas/blob/7e49bd466a302cf92fae4e63c03fb9dd975ad9fe/pandas/util/_decorators.py), following are the PEP8 issues :

> [Line 34:80](https://github.com/pandas-dev/pandas/blob/7e49bd466a302cf92fae4e63c03fb9dd975ad9fe/pandas/util/_decorators.py#L34): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)

2017-12-26 21:55 UTC, jreback requested changes
can you add a rule in ``ci/lint.sh`` to search for DEPRECATED (so it will fail linting). looks pretty good otherwise.

2017-12-26 21:55 UTC, jreback commented on scripts/find_deprecated.py
> +import re
can you add text describing how to use this & purpose

2017-12-26 21:55 UTC, jreback commented on scripts/api_rst_coverage.py
>          else:
can you add a note about using this?

ideally we would also add these scripts in a not in the contributing docs.

2017-12-26 21:55 UTC, jreback commented on pandas/core/frame.py
> +        """.. deprecated:: 0.20.0
can you make the first line the simple description

2017-12-26 21:55 UTC, jreback commented on pandas/core/generic.py
> +        """.. deprecated:: 0.21.0
same here

2017-12-26 21:55 UTC, jreback commented on pandas/core/generic.py
> +        """Convert the frame to its Numpy-array representation.
same here

2017-12-26 21:55 UTC, jreback commented on pandas/core/generic.py
> +        """.. deprecated:: 0.18.0
same, can also remove the TODO comment (we keep a separate list of these things)

2017-12-26 21:55 UTC, jreback commented on pandas/core/series.py
> +            Use ``astype(object) instead.
I am not 100% sure, but might need a blank line after these directives (you can build and see if they look ok)

2017-12-26 21:55 UTC, jreback commented on pandas/util/_decorators.py
> +    msg = msg or 'Use `{alt_name}` instead.'
can you add a comment on what you are doing here

2017-12-26 21:57 UTC, jreback commented
also would love some tests in contributing.rst on how to depreciate things (e.g. how to use the decorator is prob enough)

2017-12-27 01:20 UTC, datapythonista commented
Thanks for the review @jreback. I updated the pull request, addressing all your comments. Please let me know if there is anything that is not yet clear, or that can be improved.

Regarding the blank line after the directive, it doesn't make a difference for sphinx. In both cases the comment about the deprecation is shown inline.

2017-12-27 19:34 UTC, jreback requested changes
small comments. ping on green.

2017-12-27 19:34 UTC, jreback commented on pandas/core/series.py
> +        """.. deprecated:: 0.19.0
can you fix this one?

2017-12-27 19:34 UTC, jreback commented on pandas/core/series.py
> +        """.. deprecated:: 0.21.0
here as well

2017-12-27 19:34 UTC, jreback commented on ci/lint.sh
> +    grep -R --include="*.py" --include="*.pyx" DEPRECATED pandas
can you also look for Deprecated (capitalize first letter), and maybe DEPRECATE

2017-12-27 19:51 UTC, datapythonista commented
Sure, thanks for the comments @jreback .

I'm also implementing a more exhaustive version of `find_deprecated.py`. I think it makes sense to know your opinion about it before continuing.

What I think it would be useful is to have a script that detects all deprecated stuff, so it can be completely removed at the right time. That's what `find_deprecated` does, but just for methods of `Series`, `DataFrame` and `Panel`, and assuming they got the `.. deprecated::` directive in the docstring.

What I'm implementing now is a version that checks all python files in the project, looks for `FutureWarning`, and checks the docstrings of everything in the file (the module itself, classes, functions,...), and finds what has been deprecated.

This way, if when releasing pandas 0.22, everything that was deprecated before 0.19 needs to go away, it can be detected in an easy and reliable way.

Does this make sense?

2017-12-27 19:57 UTC, jreback commented
this would be fine as a double check: https://github.com/pandas-dev/pandas/pull/18934#issuecomment-354168451

We keep a nice annotated list: https://github.com/pandas-dev/pandas/issues/6581
and removals: https://github.com/pandas-dev/pandas/issues/13777

2017-12-27 20:13 UTC, datapythonista commented
Ah, thanks for pointing it out. I checked for the list in the code, didn't know it was in github.

Then, I think I'll update the pull request with your comments, removing the find_deprecated.py script. Later on I'll implement the script, probably in a repo separate from pandas (there is nothing pandas specific in it), and run it to see if there is nothing missing in these tickets.

2017-12-27 20:19 UTC, jreback commented
@datapythonista that would be great!

2017-12-27 22:12 UTC, datapythonista commented
@jreback fixed items in last review. In lint.sh I added DEPRECATE, DEPRECATED and Deprecated, but only if they finish with colon, comma or dot, as it was capturing DeprecatedModule for example.

2017-12-30 23:59 UTC, jreback requested changes
couple of comments

2017-12-30 23:59 UTC, jreback commented on scripts/api_rst_coverage.py
>          else:
can you update for this?

2017-12-30 23:59 UTC, jreback commented on pandas/core/sparse/series.py
> -
can you add the 1-liner description here (IOW the deprecated should not be the first line)

2017-12-30 23:59 UTC, jreback commented on pandas/core/series.py
> -        """DEPRECATED. Series.valid will be removed in a future version.
add the 1 liner here

2017-12-30 23:59 UTC, jreback commented on pandas/core/series.py
> +        """.. deprecated:: 0.20.0
same here

2018-01-03 00:40 UTC, datapythonista commented
@jreback, I made the requested changes. I agree that the scripts should be added to a note in the contributing documentation, but I'd do that in a separate request if you agree. That's unrelated to this PR, and some standardization of the scripts will be probably required. So I don't think it's a small change.

2018-01-04 00:37 UTC, jreback commented
just needs a rebase and looks ok.

2018-01-04 00:46 UTC, datapythonista commented
Rebased. Thanks @jreback

2018-01-04 00:48 UTC, jreback approved these changes

2018-01-04 00:48 UTC, jreback commented
lgtm. ping on green.

2018-01-04 01:02 UTC, datapythonista commented
@jreback, am I right in assuming that all the stuff deprecated in 0.19 and before can be deleted? If that's the case, I'll submit a PR leaving only the methods and functions with deprecation warning added in 0.20, 0.21 and 0.22.

2018-01-04 01:18 UTC, jreback commented
things before 0.19.0 should already be removed (except for - couple of ones)

2018-01-06 00:11 UTC, topper-123 commented
I submittet the PR's to deprecate ``as_matrix``, ``asobject`` and ``valid``. These will be deprecated in 0.23. Currently you've marked them as deprecated in 0.21.1/0.21.2.

2018-01-06 11:54 UTC, datapythonista commented
Thanks for pointing out @topper-123. It looks like I misunderstood something about the git workflow. For `as_matrix` for example, I saw it was merged to master in November 26th, and that 0.21.1 was the next next version released (on December 12), so I assumed everything in master was released, which doesn't seem right.

I'll compare all the versions I added with #6581 and with github tags, and fix the wrong ones.

Thanks for reporting this!

2018-01-06 14:07 UTC, datapythonista commented
@topper-123  I reviewed all the deprecation versions I added, with the release where the commit was introduced (checking `git tag --contains <commit>`). All them should be correct now. I added the version 0.23.0 to the ones that haven't been released. They match the ones you mentioned.

@jreback, this should be ready to be merged now.

Just to let you know, compared to the changes you already reviewed, I removed from the docstring the `Timestamp.offset` attribute in pandas/_libs/tslibs/timestamps.pyx. The attributed was removed from the code in fb95f7f305e85d474cc44283fc642abc900e0096 but not from the docstring. For the rest is the same, with updated deprecation versions.

Thanks to both!

2018-01-06 17:15 UTC, merged

2018-01-06 17:15 UTC, jreback commented
thanks @datapythonista very nice!

2018-01-11 16:31 UTC, jorisvandenbossche reviewed
@datapythonista some review after the fact. In general I am certainly +1 on making how we use things more consistent. But I personally like the "DEPRECATED" in the first one-liner for practical reasons.

2018-01-11 16:31 UTC, jorisvandenbossche commented on pandas/core/frame.py
> +            Use :func:`pandas.read_csv` instead.
For this case I actually don't find this an improvement. For deprecated methods, I find it useful that this is clear from the one-liner summary this it is deprecated, so you directly see this in the online api summary tables (on api.rst or on the DataFrame docstring page).

We could also do both?

(I know we don't do this consistently for all deprecated methods as well, but from_csv seems like a more important one)

2018-01-11 16:31 UTC, jorisvandenbossche commented on pandas/core/frame.py
> -        DEPRECATED: use :meth:`DataFrame.sort_index`
same here

2018-01-11 16:31 UTC, jorisvandenbossche commented on pandas/core/generic.py
> +        """Compute NDFrame with "consolidated" internals (data of each dtype
For future reference, please never use 'NDFrame' is user-facing docstrings. Users should not be aware what that means.

2018-01-11 16:31 UTC, jorisvandenbossche commented on pandas/core/generic.py
> -        DEPRECATED: as_matrix will be removed in a future version.
same here

2018-01-11 17:06 UTC, datapythonista commented
Thanks a lot for you comments @jorisvandenbossche, I see your point, didn't think about it.

My main motivation for standardizing the docstrings is to be able to automatically detect the deprecated methods. The `api_rst_coverage.py` and `list_future_warnings.sh` scripts benefit from it already.

I see two solutions here:
1. Given the fact that now it can easily be detected that a module is deprecated by code, check it while generating api_rst.html and the DataFrame page (I guess this needs to be done in sphinx)
2. Add the DEPRECATED word as the first word in all deprecated methods, besides the `.. deprecated::` directive (which also provides the version)

I prefer 1, as seems the "right" way to do it. Surely more complex to implement now, but looks cleaner once implemented.

What do you think?

For the `NDFrame` in the docstring summary, I think I copied that summary from the called function, and didn't think NDFrame wasn't part of the public API. I'll fix it and send a PR.

Thanks!

2018-01-11 17:15 UTC, jorisvandenbossche commented
Doing that in sphinx will probably some overkill IMO, so a pragmatic solution is to do both. I don't think that is a problem, as the `.. deprectated::` directive gives then additional information on when it is deprecated.

2018-03-14 17:54 UTC, shoyer commented
Out of curiosity, how does the `.. deprecated::` macro appear in generated docs? I hope it's highly visible in some way, e.g., a big red box?

2018-03-14 18:16 UTC, TomAugspurger commented
https://github.com/pandas-dev/pandas/issues/20349