TST: organize and cleanup pandas/tests/groupby/test_aggregate.py
pandas-dev/pandas pull request #18931
Opened 2017-12-24 19:13 UTC by alysivji

closes #18490

Module currently has tests in 2 classes (`TestGroupByAggregate` and `TestGroupByAggregateCython`). The remaining tests are not in a class.

Also made the following changes:

### TestGroupByAggregate class
#### test_agg_must_agg
* replaced `pytest.raises` with `tm.assert_raises_regex`

#### test_agg_apply_corner
* made it more readable

#### test_agg_multiple_functions_too_many_lambdas
* replaced `pytest.raises` with `tm.assert_raises_regex`

#### test_multi_function_flexible_mix
* made it more readable

### TestGroupByAggregateCython class

_all test methods that contain cython in the test name_

#### test_cython_agg_nothing_to_agg
* replaced `pytest.raises` with `tm.assert_raises_regex`

#### test_cython_agg_return_dict
* replaced `self.df` with df initialized inside function

### All Others

#### test_agg_dict_renaming_deprecation
* made it more readable

#### test_agg_nested_dicts
* replaced `pytest.raises` with `tm.assert_raises_regex`
* made it more readable

#### test_agg_item_by_item_raise_typeerror
* replaced `pytest.raises` with `tm.assert_raises_regex`

#### test_agg_structs_series
* made it more readable

2017-12-26 22:04 UTC, jreback commented
thanks @alysivji 

can you split things out to a new file (maybe just the moved tests)?

IOW each of these classes to a separate file, something like

``pandas/tests/groupby/aggregate/test_cython`` (2nd one)
``test_aggregate`` (1st class)
``test_other`` (3rd one)

just to make this even more organized.

be sure to add a ``__init__.py`` in the sub-dir

2017-12-27 18:34 UTC, alysivji commented
* Split up the files
* cleaned up the imports
* changed all assert_frame/assert_series calls to `tm.assert_*`
* more cleaning up tests to increase readability
* rebased

@jreback lemme know if anything else needs to be done.

Thanks!

2017-12-27 19:15 UTC, jreback requested changes
@alysivji looking good. some requests to parameterize. could completely eliminate the need for the setup method in aggregate/test_aggregate.py if you want to make those into fixtures instead. can do this in another PR if you want.

2017-12-27 19:15 UTC, jreback commented on pandas/tests/groupby/aggregate/test_aggregate.py
> +    def test_aggregate_str_func(self):
can you parametrize this (on by_weekday and by_mwkday)

2017-12-27 19:15 UTC, jreback commented on pandas/tests/groupby/aggregate/test_aggregate.py
> +        # API change in 0.11
can remove this commented out

2017-12-27 19:15 UTC, jreback commented on pandas/tests/groupby/aggregate/test_cython.py
> +    def test_cythonized_aggers(self):
can you parameterize this

2017-12-27 19:15 UTC, jreback commented on pandas/tests/groupby/aggregate/test_cython.py
> +        ops = [('mean', np.mean),
can you parameterize

2017-12-27 19:15 UTC, jreback commented on pandas/tests/groupby/aggregate/test_cython.py
> +    def test_cython_agg_empty_buckets(self):
same

2017-12-27 19:16 UTC, jreback commented
cc @TomAugspurger I think we have to merge #18921 (when ready) before this (and rebase this on master)?

2017-12-27 19:27 UTC, TomAugspurger commented
Yes it'd be nice to merge #18921 before this. Backporting can be tricky when files are split.

2017-12-27 19:43 UTC, jreback commented
@alysivji but go ahead and make the changes as above when you can. we will be merging @TomAugspurger soon anyhow.

2017-12-27 21:57 UTC, alysivji commented
@jreback Changes have been made. Also deleted the cython test class, not needed anymore since it's in a separate module.

I can rebase when @TomAugspurger 's changes get in.

Also started working on turning the `test_aggregate.py` setup into fixtures. Lots of moving pieces for one PR; will send a separate request once this is merged.

2017-12-27 22:06 UTC, jreback requested changes
looks good
couple of comments - will let u know when to rebase

2017-12-27 22:06 UTC, jreback commented on pandas/tests/groupby/aggregate/test_cython.py
> +
yes u can collapse testit - just move everything up

2017-12-27 22:06 UTC, jreback commented on pandas/tests/groupby/aggregate/test_cython.py
> +    except BaseException as exc:
yes u can take this try/except out
it’s helpful when not parametrized but not now

2017-12-27 22:06 UTC, jreback commented on pandas/tests/groupby/aggregate/test_aggregate.py
> +
same - collapse this function

2017-12-29 21:42 UTC, jreback commented
@alysivji if you want to rebase we can get this in.

2017-12-30 03:24 UTC, alysivji commented
@jreback all green!

Will start working on refactoring the setup method to fixtures this weekend.

2017-12-30 12:31 UTC, jreback approved these changes

2017-12-30 12:31 UTC, merged

2017-12-30 12:32 UTC, jreback commented
thanks @alysivji 

would like to remove the imports *inside* functions as well (and consolidate at the top-level) on your next PR.