DOC: greater consistency for intro docs
pandas-dev/pandas pull request #18948
Opened 2017-12-26 16:14 UTC by tommyod

I read through introductory docs, and made the following changes:

- Added missing periods, which were sometimes absent in short sentences.
- In other parts of the documentation, code examples appear to typically be introduced with a colon. This has been added in some sentences which did not end in a period nor a colon.
- Updated a reference to the Python 2 docs to Python 3.
- Restructured a few sentences slightly.

2017-12-26 21:37 UTC, jreback requested changes
looks good. thanks! some comments, mainly would love to update to use references where we have not already, e.g. ``:meth:`DataFrame.apply` `` for example rather than ``apply``.

2017-12-26 21:37 UTC, jreback commented on doc/source/basics.rst
> +We encourage you to view the source code of ``pd.DataFrame.pipe``.
can you make this a func reference

2017-12-26 21:37 UTC, jreback commented on doc/source/basics.rst
> +The ``.apply()`` method will also dispatch on a string method name.
can you make this a func reference (use DataFrame.apply is fine)

2017-12-26 21:37 UTC, jreback commented on doc/source/basics.rst
> +The ``.apply()`` method will also dispatch on a string method name.
like on line 866

2017-12-26 21:37 UTC, jreback commented on doc/source/basics.rst
> +Here ``.transform()`` received a single function; this is equivalent to a ufunc application.
can you add the refernce here

2017-12-26 21:37 UTC, jreback commented on doc/source/basics.rst
> +    important, consider writing the inner loop using for instance cython or numba.
a comma before for instance

2017-12-26 21:37 UTC, jreback commented on doc/source/basics.rst
> +   and which is generally much faster than ``iterrows``.
can you add the reference

2017-12-26 21:37 UTC, jreback commented on doc/source/overview.rst
> +   Series and DataFrame.
this same text exists in ``pandas/__init__.py`` can you update there as well.

2017-12-26 21:50 UTC, jschendel commented on doc/source/10min.rst
> +expressions <https://docs.python.org/3.5/library/re.html>`__ by default (and in
Can you use `/3/` instead of `/3.5/`?  That way it should always link to the most current version of Python 3.

2017-12-27 14:08 UTC, tommyod commented
@jreback and @jschendel : I have made the requested changes.

2017-12-27 19:29 UTC, jreback approved these changes

2017-12-27 19:30 UTC, merged

2017-12-27 19:30 UTC, jreback commented
thanks @tommyod 

built docs are: http://pandas-docs.github.io/pandas-docs-travis/ (likely take a few hours). please make sure changes are rendered ok. thanks!

2017-12-27 19:44 UTC, tommyod commented
@jreback - Great, will do.

2017-12-28 00:56 UTC, jschendel commented
@tommyod : I don't think there's really a preference in terms of the size of a PR.  Whatever works best for you should be fine.  My advice is to lean towards submitting PR's more frequently as opposed to waiting to submit a huge number of changes at once.  Waiting could lead to merge conflicts if other people are updating the same sections of the docs, which could lead to extra work resolving the conflicts. Thanks for improving the docs!