Spellcheck of docs, a few minor changes
pandas-dev/pandas pull request #18973
Opened 2017-12-28 16:54 UTC by tommyod

This PR continues my read-through of the docs, the previous PRs submitted are #18941 and  #18948.

The following edits have been made:
- Missing periods and colons added before introducing code examples.
- Increased number of function references (clickable links).
- Cleared up a few sentences which I found unclear.

Feedback is welcome.

2017-12-28 17:11 UTC, TomAugspurger reviewed
Only partway through, looks good so far.

Style question: we have quite a few places like

    The :meth:`Series.cov` method does...

I prefer just saying

    :meth:`Series.cov` does...

I think it's clear from the context that we're talking about a method.

2017-12-28 17:11 UTC, TomAugspurger commented on doc/source/advanced.rst
> +You can use ``pd.IndexSlice`` to facilitate a more natural syntax using ``:``, rather than using ``slice(None)``.
You could link to `IndexSlice` here

    :class:`IndexSlice`

I think (maybe `pandas.IndexSlice`).

2017-12-28 17:11 UTC, TomAugspurger commented on doc/source/advanced.rst
> +Slicing is **always** on the values of the index when using ``[],ix,loc``, and
Except for booleans :)

Perhaps we can rephrase this as "**primarily** on the values" and mention elsewhere (perhaps after `iloc`) that booleans are also allowed.

2017-12-28 17:11 UTC, TomAugspurger commented on doc/source/computation.rst
> +The ``Series`` object has a method :meth:`~Series.cov` to compute covariance
How about

    :meth:`Series.cov` can be used to compute covariance between series (excluding missing values)

2017-12-28 17:11 UTC, TomAugspurger commented on doc/source/computation.rst
> +Analogously, ``DataFrame`` has a method :meth:`~DataFrame.cov` to compute
And 

    Analogously, :meth:`DataFrame.cov` can be used to compute pairwise...

2017-12-28 19:30 UTC, tommyod commented
Thanks for the feedback @TomAugspurger. I have submitted a new PR addressing your comments, which were helpful. 

- I agree that "*... to compute it, use `my_method` and ...*" is more succinct and clear than "*... to compute it, use the method `my_method` and ...*".
- I am uncertain about starting a sentence with "*The `my_method` method is...*" vs. "*`my_method` is...*". The first phrasing seems to occur quite a bit in the documentation.

2017-12-29 00:38 UTC, jreback requested changes
lgtm! just some small changes. ping on green.

2017-12-29 00:38 UTC, jreback commented on doc/source/computation.rst
> +Wikipedia has articles covering the
can you make these a bulleted list?

2017-12-29 00:38 UTC, jreback commented on doc/source/indexing.rst
> +vector that is true wherever the Series elements exist in the passed list.
generally like to use double-backticks around Series, DataFrame, Index where possible.

2017-12-29 00:38 UTC, jreback commented on doc/source/indexing.rst
> -**mask**
could make mask a sub-section (of the where section).

2017-12-29 00:38 UTC, jreback commented on doc/source/indexing.rst
>  ``mask`` is the inverse boolean operation of ``where``.
you can remove the experimental from the Query section.

2017-12-29 00:38 UTC, jreback commented on doc/source/options.rst
> +**Note:** Developers can check out ``pandas/core/config.py`` for more info.
you can put this link in: https://github.com/pandas-dev/pandas/blob/master/pandas/core/config.py

2017-12-29 00:38 UTC, jreback commented on doc/source/options.rst
>  As described above, ``get_option()`` and ``set_option()`` are available from the
you can use ``:func:`get_option` `` and so on

2017-12-29 00:38 UTC, jreback commented on doc/source/text.rst
> +It's easy to expand this to return a DataFrame using ``expand``.
It is

2017-12-29 14:34 UTC, tommyod commented
@jreback I've addressed your comments. I've been noting some stylistic preferences (which I agree with), such as "*It is ...*" instead of "*It's*" and using double-backticks on objects. For now I have not addressed these globally in the docs, but I hope to do so in a future PR.

2017-12-29 14:45 UTC, jreback commented
@tommyod totally cool. updating things like this is generally, do a few docs / files at once. it becomes too hard to review otherwise.

2017-12-29 14:50 UTC, jreback requested changes
small comments.

2017-12-29 14:50 UTC, jreback commented on doc/source/indexing.rst
> +~~~~~~~~~
this needs to be the same length as the title (otherwise sphinx warns)

2017-12-29 14:50 UTC, jreback commented on doc/source/indexing.rst
> +The :meth:`~pandas.DataFrame.query` Method
same here

2017-12-29 14:50 UTC, jreback commented on doc/source/indexing.rst
> +to create a new, indexed DataFrame:
capitalize as beginning of sentence?

2017-12-29 14:50 UTC, jreback commented on doc/source/indexing.rst
> +This is the inverse operation to ``set_index``.
put a ``:func:`DataFrame.set_index` ``

2017-12-29 14:50 UTC, jreback commented on doc/source/indexing.rst
> +   The ``reset_index`` method used to be called ``delevel``, which is now
you can remove this, delevel is removed

2017-12-29 15:11 UTC, tommyod commented
@jreback :+1: . Addressed comments.

2017-12-29 21:48 UTC, jreback approved these changes

2017-12-29 21:48 UTC, merged

2017-12-29 21:49 UTC, jreback commented
thanks @tommyod