Spellcheck
pandas-dev/pandas pull request #19017
Opened 2017-12-31 16:19 UTC by tommyod

This PR is a continuation of my read-through of the docs, the earlier PRs are #18941, #18973 and #18948.

**The changes included in this PR include**
- Changed spelling of "python" to "Python" for consistency, same with "numpy" to "NumPy". This change was made globally, i.e. for most documents in `/docs/source/`.
- A review of `groupby.rst` and `missing_data.rst`
  - Added punctuation where missing.
  - Added more function references (i.e. `:meth:...`) where appropriate.
  - Rewrote a few sentences.

Feedback is very welcome.

2017-12-31 16:25 UTC, jreback commented
> Changed spelling of "python" to "Python" for consistency, same with "numpy" to "NumPy". This change was made globally, i.e. for most documents in /docs/source/.

can you add a lint rule for this (and other things that we want to check globally)
in ``ci/lint.sh``

2017-12-31 16:27 UTC, jreback commented
also can you add a note in the whats new about documentation edits (there is a section) and include these PR#'s ?
and a similar note for #18966

2018-01-01 12:16 UTC, tommyod commented
@jreback I've added a reference to this and earlier PRs in `whatsnew/v0.23.0.txt`. I don't know how to make the linting rule, since for instance ` numpy ` should be replaced with ` NumPy ` in writte documentation, but not in the accompanying code. Not sure how to enforce this.

2018-01-01 14:19 UTC, jreback commented
rebase and push again, fixed some hanging by Travis CI

2018-01-01 16:26 UTC, jreback requested changes
small comments. can you add a rule in lint.sh?

2018-01-01 16:26 UTC, jreback commented on doc/source/cookbook.rst
> +These examples are written for Python 3.4.  Minor tweaks might be necessary for earlier python
can you make this 3.6

2018-01-01 16:26 UTC, jreback commented on doc/source/cookbook.rst
> +These examples are written for Python 3.4.  Minor tweaks might be necessary for earlier python
or rather say Python 3

2018-01-01 16:26 UTC, jreback commented on doc/source/groupby.rst
> +  - A dict or Series, providing a ``label -> group name`` mapping.
can you double-backticks Series/DataFrame when you see

2018-01-02 18:12 UTC, tommyod commented
@jreback - I've addressed the review, rebased and pushed. I could not figure out good logic for a rule in `lint.sh`, will come back to this in the future if I figure it out.

2018-01-02 22:09 UTC, WillAyd commented
@tommyod the grep command below could be a starter for you. This will find any instance of ``numpy`` but subsequently exclude it if the line contains ``from`` or ``import``

It could miss some lines like ``# need to import foo from numpy`` but should realistically catch most issues

`` grep -R --include="*.py" --include="*.pyx" --include="*.rst" "numpy" $path | grep -Ev "from|import"``

2018-01-03 12:23 UTC, jreback approved these changes

2018-01-03 12:25 UTC, merged

2018-01-03 12:25 UTC, jreback commented
thanks @tommyod 

yeah a rule similar to

``grep -R --include="*.py" --include="*.pyx" --include="*.rst" "numpy" doc/ pandas/ | grep -Ev "from|import|_numpy_|\/numpy\/"``

is close, though picking up extra things so prob have to add a bit to it

would take as a followup