Fix #19057
pandas-dev/pandas pull request #19058
Opened 2018-01-03 16:57 UTC by Mofef

This fixes #19057

2018-01-04 00:03 UTC, jreback requested changes
this looks ok, but pls add your original test (both with and w/o inplace) as well as a note in the whatsnew

2018-01-04 00:04 UTC, jreback commented
cc @toobaz 

any thoughts here

2018-01-04 11:12 UTC, toobaz commented
Looks good to me. As for tests, I guess it's just a matter of understanding what went wrong in [this one](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexes/test_multi.py#L213), and fix it.

2018-01-04 11:26 UTC, Mofef commented
you probably mean https://github.com/pandas-dev/pandas/blob/93033151a8d8aaa650a81df9f41347758bf6c393/pandas/tests/indexes/test_multi.py#L287 , set_levels works correctly iirc.
The issue with the test is that self.index has the same magnitude of categories in each level. (i.e. the length is each smaller than 127).  So the missalignment dos not have an effect. Also there is no missalignment if the labels get replaced in the first n levels. 
I would like to take care of the tests later.

2018-01-04 12:39 UTC, toobaz commented
> you probably mean

yep, sorry, actually this assertion:
https://github.com/pandas-dev/pandas/blob/93033151a8d8aaa650a81df9f41347758bf6c393/pandas/tests/indexes/test_multi.py#L302

But I agree with your explanation.

2018-01-04 15:26 UTC, jreback commented
@Mofef tests need to be in the same issue as the PR fixing.

2018-01-04 17:23 UTC, Mofef commented
@jreback Sorry I don't understand, you mean i should also add tests to this PR?
In the meanwhile i looked into test_multi.py. My initial idea was to just increase the size of the minor level with something like 
```python
    def setup_method(self, method):
        major_axis = Index(['foo', 'bar', 'baz', 'qux'])
        minor_axis = Index(range(2, 128))

        major_labels = np.random.choice(range(4), 128)
        minor_labels = np.array(range(128))
...
```
However, that doesn't seem to be feasible since a lot of test methods rely on the current "reference index". So I get ~50 presumably false negative tests. 
Another option would be to create a bigger `MultiIndex` down in `test_set_labels`. On the other hand it's probably a good idea to check each operation against such an index with `levels` of different `dtype`.
What do you think?

2018-01-04 17:27 UTC, jreback commented
@Mofef yes you need a test, you can use the one that you put in the issue. you need to assert that this works (eg. construct the expected MI).

2018-01-05 10:46 UTC, Mofef commented
Done. I had to define another test method, with its own `assert_matching` function, since inside `test_set_labels` the expected labels get casted to int8. Imho this should happen outside of a function called "assert_equal"

I also stumbled upon #19092

2018-01-05 13:47 UTC, jreback requested changes

2018-01-05 13:47 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        ind_reference = pd.MultiIndex.from_tuples(
call this expected

2018-01-05 13:47 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        assert_equal(ind2, ind_reference)
call these result, then you can simply do

``assert result.equals(expected)``

for the inplace case you need to copy before

2018-01-05 13:47 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        def assert_equal(actual, expected):
see below this is not necessary

2018-01-05 14:16 UTC, Mofef commented
Cool, thanks. PTAL

2018-01-05 14:21 UTC, jreback approved these changes

2018-01-05 14:21 UTC, jreback commented
looks good. ping on green.

2018-01-05 16:08 UTC, Mofef commented
@jreback https://travis-ci.org/pandas-dev/pandas/jobs/325457802#L448
```
648.46s$ git fetch origin +refs/pull/19058/merge:
fatal: unable to access 'https://github.com/pandas-dev/pandas.git/': Failed to connect to github.com port 443: Connection timed out
```

2018-01-05 22:22 UTC, TomAugspurger commented
Sorry about the extra commits @Mofef. I fixed a merge conflict in the release notes and the CI services apparently had an issue with that. They're running again now.

2018-01-05 22:35 UTC, Mofef commented
Oh ok no problem. thank you :)

2018-01-06 17:25 UTC, merged

2018-01-06 17:25 UTC, jreback commented
thanks @Mofef