DOC: Add clear and other parameter docs to assert_produces_warning
pandas-dev/pandas pull request #19066
Opened 2018-01-03 23:22 UTC by davetlewis-van

- [GH18996 ] closes #18996
- Added information on `clear` parameter 
- Added information on other undocumented parameters (expected_warning, filter_level, check_stacklevel)

2018-01-04 00:16 UTC, jreback requested changes

2018-01-04 00:16 UTC, jreback commented on pandas/util/testing.py
> +    expected_warning : class Warning|False|None, default Warning
``{Warning, False, None}``

2018-01-04 00:16 UTC, jreback commented on pandas/util/testing.py
> +    check_stacklevel : bool, default true
true -> True

2018-01-04 00:16 UTC, jreback commented on pandas/util/testing.py
> +    ----------
make this same length as Examples

2018-01-04 00:16 UTC, jreback commented on pandas/util/testing.py
> +         "error" - turns matching warnings into exeptions
can you use * for the bullets.

2018-01-04 00:46 UTC, davetlewis-van commented
Thanks for the quick and thorough review @jreback. I've pushed your requested changes.

2018-01-04 00:47 UTC, jreback commented
can you ``git merge master`` and push again (generally we want to rebase / merge master anytime you push).

2018-01-04 00:54 UTC, davetlewis-van commented
I did `git merge master` and then `git push origin doc_clear` on my feature branch in my forked repo. Is that correct? The git messages were "Already up-to-date" and "Everything up-to-date".

2018-01-04 14:14 UTC, jreback commented
``git merge upstream`` sorry you need to pull from the upstream (this should point to the pandas-dev/master.git``

```
(pandas) bash-3.2$ git remote -v
jreback https://github.com/jreback/pandas.git (fetch)
jreback https://github.com/jreback/pandas.git (push)
upstream        https://github.com/pandas-dev/pandas.git (fetch)
upstream        https://github.com/pandas-dev/pandas.git (push)
```

2018-01-08 20:46 UTC, TomAugspurger commented
Whoops, looks like some unrelated commits got in here.  Do you want help walking through the git commands?

I think the simplest version would be

```
git reset --soft upstream/master
git commit -m "Fixed git issue"
git push -f origin
```

That'll rewrite history (which is usually not good, but OK for this PR) and hopefully clean everything up.

2018-01-08 21:00 UTC, davetlewis-van commented
@TomAugspurger Hi Tom. I ran the commands above. Are there any additional commands I need to run to deliver this change? Thanks!

2018-01-08 21:05 UTC, TomAugspurger commented
The diff looks good now, thanks. Let us know if you see that the tests all pass before we do.

2018-01-09 18:10 UTC, davetlewis-van commented
I need help with troubleshooting the travis-ci errors. I don't understand what the problem is. Thanks!

2018-01-09 21:09 UTC, TomAugspurger commented
I restarted those. I think boto (one of our dependencies) had a bad release yesterday. They've been passing today.

Ping on green :)

2018-01-10 00:25 UTC, jreback approved these changes

2018-01-10 00:26 UTC, merged

2018-01-10 00:26 UTC, jreback commented
thanks!