str.extractall with no match returns appropriate MultIndex
pandas-dev/pandas pull request #19075
Opened 2018-01-04 13:16 UTC by jsnowacki

Relates and fixes issue #19034. It's a small fix which creates empty MultiIndex instead of Index, with appropriate names, when `str.extractall` doesn't find any matches. Also, a related test in `pandas.tests.test_strings` has been updated to reflect the expected result.

2018-01-04 14:16 UTC, jreback requested changes
tests comments & can you add a whatsnew for bug fixes

2018-01-04 14:16 UTC, jreback commented on pandas/tests/test_strings.py
>      def test_extractall_no_matches(self):
can you parameterize this with both a 0-len index and a 0-len MI.

2018-01-04 23:02 UTC, TomAugspurger approved these changes

2018-01-04 23:02 UTC, TomAugspurger commented on pandas/tests/test_strings.py
> +    def test_extractall_no_matches(self, data, names):
By test comments, @jreback meant a comment with the issue number, so like `# GH-19075` just below the `def test_`

2018-01-05 09:05 UTC, jsnowacki commented
Ah, yes, sorry; didn't get this step. I've added it.

2018-01-05 13:59 UTC, jreback approved these changes
very minor comment. ping when pushed.

2018-01-05 13:59 UTC, jreback commented on pandas/tests/test_strings.py
>          # two named groups.
can you put a blank line before each comment; easier to read the tests then

2018-01-05 15:50 UTC, jsnowacki commented
@jreback I've pushed the comment newline fix.

2018-01-05 19:13 UTC, merged

2018-01-05 19:13 UTC, jreback commented
thanks @jsnowacki