DEPR: Removing previously deprecated datetools module (#6581)
pandas-dev/pandas pull request #19119
Opened 2018-01-07 15:55 UTC by datapythonista

- [X] related to #6581
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

2018-07-07 22:47 UTC, jreback requested changes

2018-07-07 22:47 UTC, jreback commented on doc/source/whatsnew/v0.23.0.txt
> +- Removal of the previously deprecated module ``pandas.core.datetools`` (:issue:`14105`, :issue:`14094`)
move to 0.24.0

2018-07-08 15:56 UTC, jreback approved these changes

2018-07-08 15:56 UTC, jreback commented
lgtm. though not running on travis for some reason.

2018-07-08 15:57 UTC, jreback commented
cc @TomAugspurger 

maybe need to login to travis and turn on pandas-dev for your fork?

2018-07-27 20:55 UTC, jbrockmendel commented
@datapythonista needs rebase, hopefully CI problem will fix itself.

2018-07-28 13:43 UTC, jreback commented
can you rebase, for some reason travis is not running either - not sure why

2018-08-02 10:45 UTC, merged

2018-08-02 10:45 UTC, jreback commented
thanks @datapythonista