DEPR: Removing previously deprecated flavor parameter from SQLiteData…
pandas-dev/pandas pull request #19121
Opened 2018-01-07 16:02 UTC by datapythonista

…base (#6581)

- [X] related to #6581
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

2018-01-07 16:05 UTC, jreback requested changes

2018-01-07 16:05 UTC, jreback commented on doc/source/whatsnew/v0.23.0.txt
> +- The ``flavor`` parameter have been removed from ``SQLiteDatabase`` and :func:`to_sql` method
just say ``to_sql``, ``SQLiteDatabase`` is not public. add the issue number and this issue.

2018-01-07 16:13 UTC, jreback commented
hmm, these are not building on travis for some reason.

2018-01-07 16:18 UTC, datapythonista commented
It's a great reason for you to take a break today, it's Sunday! ;)

2018-01-10 11:29 UTC, jreback approved these changes

2018-01-10 12:58 UTC, merged

2018-01-10 12:58 UTC, jreback commented
thanks!