Doc: Add example of merging a Series with a Dataframe
pandas-dev/pandas pull request #19160
Opened 2018-01-09 20:46 UTC by pdpark

- [X] closes #19140

2018-01-12 00:57 UTC, jreback requested changes
this isn't referenced to #19140 which is a PR. what is the associated issue?

2018-01-12 00:57 UTC, jreback commented on doc/source/merging.rst
> +To join a Series and a DataFrame, the Series has to be transformed into a DataFrame first:
use double backticks around Series & DataFrame

2018-01-13 18:25 UTC, jreback commented
you need to rebase on master and push again, don't see any changes

2018-01-14 03:14 UTC, pdpark commented
This PR can be closed - resubmitted as PR #19235.

2018-01-14 03:39 UTC, jreback commented
in he future pls just push to thme same PR with changes

2018-01-14 03:39 UTC, closed without merging

2018-01-14 03:40 UTC, pdpark commented
I see. Will do.