API: Add compression argument to Series.to_csv
pandas-dev/pandas pull request #19216
Opened 2018-01-13 00:05 UTC by reidy-p

- [ ] closes #18958
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-01-13 00:05 UTC, pep8speaks commented
Hello @reidy-p! Thanks for submitting the PR.

 - In the file [`pandas/core/series.py`](https://github.com/pandas-dev/pandas/blob/588a8f4455f08a4cefbd5e53c5afd872311fccff/pandas/core/series.py), following are the PEP8 issues :

> [Line 2914:77](https://github.com/pandas-dev/pandas/blob/588a8f4455f08a4cefbd5e53c5afd872311fccff/pandas/core/series.py#L2914): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2018-01-13 17:04 UTC, jreback requested changes
see comments

2018-01-13 20:44 UTC, reidy-p commented
@jreback did you post comments? I can't see any.

2018-01-13 21:41 UTC, jreback commented
sorry, see #19226 want to parametrize these tests

2018-01-14 16:12 UTC, jreback requested changes

2018-01-14 16:12 UTC, jreback commented on pandas/tests/series/test_io.py
> +    def decompress_file(self, src_path, compression):
can u move this function to pandas.util.testing as it’s more generally useful for testing

2018-01-15 00:28 UTC, gfyoung commented
@jreback @reidy-p : I like the `decompress` utility (it should be applied to our `DataFrame.to_csv` tests), but this patch for `Series.to_csv` is only a band-aid.  We should implement what you summarized in your comment <a href="https://github.com/pandas-dev/pandas/issues/18958#issuecomment-357449553">here</a> to close this issue.

2018-01-15 14:10 UTC, jreback commented
@gfyoung I agree, but it puts this in a central location at least for now.

2018-01-15 14:11 UTC, jreback approved these changes

2018-01-15 14:11 UTC, merged

2018-01-15 14:11 UTC, jreback commented
thanks @reidy-p ok would love to work on centralizing the compression tests!