Doc: Adds example of exploding lists into columns instead of storing in dataframe cells
pandas-dev/pandas pull request #19215
Opened 2018-01-12 23:56 UTC by pdpark

- [X] closes #17027

2018-01-13 18:28 UTC, jreback requested changes

2018-01-13 18:28 UTC, jreback commented on doc/source/gotchas.rst
> +------------------------------------------------------
needs to be the same length as the title

2018-01-13 18:28 UTC, jreback commented on doc/source/gotchas.rst
> +
make things into separate ``ipython:: python blocks``, rather than using comments (you can simply write text and not use the ``#``)

2018-01-13 18:28 UTC, jreback commented on doc/source/gotchas.rst
> +   df2 = pd.concat([df[['name','opponent']], pd.DataFrame(nearest_neighbors)], axis=1)
you don't need to keep naming the dataframes, just use 

df = ..... or whatever

2018-01-13 18:28 UTC, jreback commented on doc/source/gotchas.rst
> +Example of exploding nested lists into a DataFrame:
since you have 2 examples you can use another level of sub-section

2018-02-24 17:26 UTC, jreback commented
can you update

2018-08-02 17:33 UTC, jreback commented
can you rebase and update

2018-08-31 01:15 UTC, pdpark commented
Will do - have been absent due to starting new job, but plan to spend some time on this.

2018-10-09 04:47 UTC, datapythonista commented
Closing as discontinued. Superseded by #23041

2018-10-09 04:47 UTC, closed without merging