FIX: Raise errors when wrong string arguments are passed to `resample`
pandas-dev/pandas pull request #19307
Opened 2018-01-18 23:36 UTC by cchwala

- [ ] closes #19303
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

As a first step, the initial commit just extends the resampling tests so that they fail when a misstyped string argument, e.g. for `label`, passes silently without raising.

I have the fix for the code ready and will commit when the tests have failed once.

2018-01-18 23:54 UTC, jreback requested changes

2018-01-18 23:54 UTC, jreback commented on pandas/tests/test_resample.py
> +
can you add as a separate test.

2018-01-19 00:20 UTC, cchwala commented on pandas/tests/test_resample.py
> +
Yes. No problem.

2018-01-19 11:08 UTC, jreback commented
tests look good. pls push the fix when you can.

2018-01-19 14:08 UTC, TomAugspurger commented on pandas/core/resample.py
> +            raise AttributeError('Unsupported value %s for `label`' % label)
These should probably be `ValueError`s.

2018-01-19 14:08 UTC, TomAugspurger commented on doc/source/whatsnew/v0.23.0.txt
> +- Bug in :func:`DataFrame.resample` which silently ignored unsupported (or misstyped) options for `label`, `closed` and `convention` (:issue:`19303`)
Use double backticks for `label`, `closed` and `convention`.

2018-01-19 14:22 UTC, pep8speaks commented
Hello @cchwala! Thanks for updating the PR.

 - In the file [`pandas/core/resample.py`](https://github.com/pandas-dev/pandas/blob/24bcb9843971df2b735dd607857aa5861926f6ed/pandas/core/resample.py), following are the PEP8 issues :

> [Line 1072:34](https://github.com/pandas-dev/pandas/blob/24bcb9843971df2b735dd607857aa5861926f6ed/pandas/core/resample.py#L1072): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

2018-01-19 15:18 UTC, TomAugspurger approved these changes
Looks good @cchwala, ping us when the tests pass.

2018-01-19 21:52 UTC, jreback requested changes

2018-01-19 21:52 UTC, jreback commented on pandas/core/resample.py
> +            raise ValueError('Unsupported value %s for `convention`'
don't use '%', use ``.format()`` instead.

2018-01-19 21:52 UTC, jreback commented on pandas/tests/test_resample.py
> +        rng = date_range('1/1/2000 00:00:00', '1/1/2000 00:13:00', freq='min',
add the issue number here as a comment

2018-01-20 09:41 UTC, cchwala commented on pandas/tests/test_resample.py
> +        with pytest.raises(ValueError) as e_info:
@jreback There is also a linting error here because of the unused `e_info`. I will also remove these, okay?

2018-01-21 15:47 UTC, jreback approved these changes

2018-01-21 15:47 UTC, merged

2018-01-21 15:47 UTC, jreback commented
thanks @cchwala