REF: Change how pandas.core.common shim works
pandas-dev/pandas pull request #19304
Opened 2018-01-18 21:44 UTC by TomAugspurger

I have a PR incoming that would introduce a circular dependency
between pandas.core.arrays.categorical, pandas.api, and pandas.core.common.

This change will allow that PR to avoid hacky workarounds, since the
real problem is pandas.core importing pandas.api.types.

xref https://github.com/pandas-dev/pandas/pull/13990

2018-01-18 22:44 UTC, desasaliho commented
Hello..i have a problem in my Facebook when I login it say your account has been disabled 
By an administrator I want to know why I am Disabled please and when I can login back I 
Hope that you can help me and it thank you for
Any answer you will give it to me bye

2018-01-18 22:44 UTC, desasaliho requested changes
Hello..i have a problem in my Facebook when I login it say your account has been disabled 
By an administrator I want to know why I am Disabled please and when I can login back I 
Hope that you can help me and it thank you for
Any answer you will give it to me bye

2018-01-18 22:47 UTC, jorisvandenbossche approved these changes

2018-01-18 23:22 UTC, jreback commented
these are on the list to be removed in 0.23 anyhow( https://github.com/pandas-dev/pandas/issues/6581). would rather just take them out.

2018-01-18 23:22 UTC, jreback requested changes
see comments

2018-01-19 03:00 UTC, TomAugspurger commented
Hmm, looks like dask uses it in one place :/

Thoughts up bumping it to a FutureWarning for one more release and then removing?

2018-01-19 03:01 UTC, TomAugspurger commented
Ah, dask's usage is just compatability for older pandas (0.19.2, which isn't so long ago).

2018-01-19 04:01 UTC, jreback commented
this should go now
it’s been a while

2018-01-21 15:40 UTC, jreback commented
as I said above, just remove the core.common accessors

2018-01-30 19:08 UTC, TomAugspurger commented
I think we're undecided on what to do with deprecations slated for 0.23.0, comment from @jorisvandenbossche in https://github.com/pandas-dev/pandas/issues/6581#issuecomment-357449108. Let's resolve that in #6581 first.

2018-01-30 23:24 UTC, jreback commented
this was an already slated deprecation for removal

2018-02-19 19:37 UTC, closed without merging