TST: Clean up pickle compression tests
pandas-dev/pandas pull request #19350
Opened 2018-01-22 20:37 UTC by reidy-p

xref #19226

Move compression fixture to top-level ``conftest.py``

Clean-up compression tests in ``pandas/tests/io/test_pickle.py`` and add zip to the ``decompress_file`` testing utility

Make some minor adjustments to the json and csv compression tests to skip zip compression when it's not valid

2018-01-23 00:09 UTC, jreback requested changes

2018-01-23 00:09 UTC, jreback commented on pandas/tests/frame/test_to_csv.py
> +        if compression != "zip":
you could do

```
if compression == 'zip':
    pytest.skip("not zip compression test for to_csv")

....
```

2018-01-23 00:09 UTC, jreback commented on pandas/tests/io/json/test_compression.py
> +        with tm.ensure_clean() as path:
same here (alternatively, you can make *another* fixed w/o zip), maybe ``compression_no_zip`` is better

2018-01-24 01:07 UTC, jreback approved these changes

2018-01-24 01:08 UTC, jreback commented
lgtm. ping on green (or at least all linux builds on travis), seems mac may have some issues.

2018-01-24 09:18 UTC, reidy-p commented
@jreback it's green now, thanks!

2018-01-24 10:06 UTC, merged

2018-01-24 10:06 UTC, gfyoung commented
Thanks @reidy-p !