BUG SparseDataFrame with dense Series (#19374)
pandas-dev/pandas pull request #19377
Opened 2018-01-24 18:04 UTC by datapythonista

- [X] closes #19374
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

2018-01-24 20:03 UTC, gfyoung commented on pandas/tests/sparse/frame/test_frame.py
> +        pytest.raises(TypeError, SparseDataFrame, Unknown())
Let's check error message too.

2018-01-24 20:04 UTC, gfyoung commented on pandas/tests/sparse/frame/test_frame.py
> +    def test_constructor_from_dense_series(self):
Reference issue number under all of your added tests.

2018-01-24 20:04 UTC, gfyoung commented
@datapythonista : Looks pretty good so far.  Don't forget to add a `whatsnew` entry.

2018-01-25 01:05 UTC, jreback requested changes
pls add a whatsnew note as well.

2018-01-25 01:05 UTC, jreback commented on pandas/tests/sparse/frame/test_frame.py
> +        assert isinstance(df, SparseDataFrame)
construct an expected SDF and compare

2018-01-25 01:05 UTC, jreback commented on pandas/tests/sparse/frame/test_frame.py
> +        # No column name available
same for the rest

2018-01-25 01:05 UTC, jreback commented on pandas/core/sparse/frame.py
> +            if columns is None and data.name is None:
need a test to hit this case

2018-01-25 11:09 UTC, datapythonista commented
Thanks a lot for the comments. Sorry about the whatsnew, I added it when opening the PR, but forgot to add it to the commit.

@jreback, I didn't find a way to construct the expected `SparseDataFrame` without using the constructor that is being tested itself. But I added the comparison of the length and sum of the original series and the new `SparseDataFrame`, which I think should be enough (and it helped find a bug in my previous code).

Addressed all the other comments, let me know if you see anything else. Thanks!

2018-01-25 12:07 UTC, jreback requested changes

2018-01-25 12:07 UTC, jreback commented on pandas/core/sparse/frame.py
> +            mgr = self._init_dict(data.to_frame(columns[0]),
don't construct like this, actually make dict

2018-01-25 12:07 UTC, jreback commented on pandas/tests/sparse/frame/test_frame.py
> +        assert isinstance(df, SparseDataFrame)
construct a DataFrame and use .to_sparse() to construct an expected frame. we do not want to do all of these little checks, we already have well established comparison functions, e.g. ``tm.assert_sparse_equal`` for this

2018-01-25 12:07 UTC, jreback commented on pandas/core/sparse/frame.py
> +                                     'w/o a name or columns')
I don't think you need any of this, you can simply all ``to_manager`` with the column (in a list)

2018-01-25 13:44 UTC, datapythonista commented
Thanks for the feedback @jreback, I misunderstood what the columns argument had to do, and I was overcomplicating the code.

Now it simply creates the `DataFrame` with the `Series` name if it has one, or it uses 0 as the column if it doesn't. This seems to be consistent with the `Series` constructor and with creating a `SparseDataFrame` from a `DataFrame`, which ignores unknown columns.

I'm not 100% sure I understood what you mean by "actually contruct dic", please let me know if this new version doesn't address this too.

2018-01-26 12:30 UTC, jreback requested changes
small edits, other lgtm. ping on green.

2018-01-26 12:30 UTC, jreback commented on pandas/tests/sparse/frame/test_frame.py
> +        assert isinstance(x, Series)
you don't need this assert

2018-01-26 12:30 UTC, jreback commented on pandas/tests/sparse/frame/test_frame.py
> +        res = SparseDataFrame(x)
I prefer result and expected

2018-01-26 12:30 UTC, jreback commented on pandas/tests/sparse/frame/test_frame.py
> +        assert isinstance(res, SparseDataFrame)
you don't need the assert

2018-01-26 12:30 UTC, jreback commented on pandas/tests/sparse/frame/test_frame.py
> +        res = SparseDataFrame(x)
same w.r.t naming & asserts

2018-01-26 16:57 UTC, datapythonista commented
Thanks once again for the comments @jreback, seems that I followed the conventions of an old test. Addressed your comments, should be all right now.

2018-01-27 01:10 UTC, jreback approved these changes

2018-01-27 01:10 UTC, merged

2018-01-27 01:10 UTC, jreback commented
thanks @datapythonista