DOC: Spellcheck of categorical.rst and visualization.rst
pandas-dev/pandas pull request #19428
Opened 2018-01-28 11:29 UTC by tommyod

Minor changes to the documentation, specifically `categorical.rst` and `visualization.rst`:

* Function references as links.
* Backticks ` `` ` around Series, DataFrame.
* Minor rephrasing of sentences, spelling, etc.
* For plots such as lag plots, Andrews plot, Radviz, I added links to Wikipedia entries.

Comments very welcome.

2018-01-29 14:12 UTC, jreback requested changes

2018-01-29 14:12 UTC, jreback commented on doc/source/categorical.rst
> +<reshaping.tile.cut>`):
can you expand the ref for the cut section in the docs

2018-01-31 23:53 UTC, jreback approved these changes

2018-01-31 23:54 UTC, merged

2018-01-31 23:55 UTC, jreback commented
thanks @tommyod . these are *very* welcome PR's. If possible, can you put a PR per file (unless very little changes). Just a bit easier to review. thanks! keep em coming

2018-02-01 05:28 UTC, tommyod commented
@jreback I expanded the reference by writing a sentence about the `cut` function. I hope I understood your comment correctly. I believe this PR is good to go.