BUG: groupby with resample using on parameter errors when selecting column to apply function
pandas-dev/pandas pull request #19433
Opened 2018-01-28 16:56 UTC by discort

- [ ] closes #17813
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-01-29 18:03 UTC, discort commented
@jreback

2018-01-30 00:20 UTC, jreback commented
try with something like this. your patch is just working around the issue and not fixing it at the source. its pretty deep code, but try here.

```
diff --git a/pandas/core/groupby.py b/pandas/core/groupby.py
index 4c03f3bfa..6a2cd69eb 100644
--- a/pandas/core/groupby.py
+++ b/pandas/core/groupby.py
@@ -466,11 +466,15 @@ class Grouper(object):
                 "The Grouper cannot specify both a key and a level!")
 
         # the key must be a valid info item
-        if self.key is not None and not isinstance(obj, Series):
+        if self.key is not None:
             key = self.key
-            if key not in obj._info_axis:
-                raise KeyError("The grouper name {0} is not found".format(key))
-            ax = Index(obj[key], name=key)
+
+            if getattr(self.grouper, 'name', None) == key:
+                ax = self.grouper
+            else:
+                if key not in obj._info_axis:
+                    raise KeyError("The grouper name {0} is not found".format(key))
+                ax = Index(obj[key], name=key)
 
         else:
             ax = obj._get_axis(self.axis)
diff --git a/pandas/core/resample.py b/pandas/core/resample.py
index 03b522abc..43391061d 100644
--- a/pandas/core/resample.py
+++ b/pandas/core/resample.py
@@ -743,11 +743,6 @@ class _GroupByMixin(GroupByMixin):
 
             return x.apply(f, **kwargs)
 
-        # Patch the index in case we're applying after __getitem__. GH 17813
-        if self.groupby.key:
-            key = self.groupby.key
-            self._groupby.obj.index = Index(self.groupby.obj[key], key=key)
-
         result = self._groupby.apply(func)
         return self._wrap_result(result)
 
```

2018-01-30 08:10 UTC, discort commented
The result in this case would be:
```
In [11]: result
Out[11]:
id  date
a   2016-01-01    2
    2016-01-03    0
    2016-01-05    0
b   2016-01-01    2
    2016-01-03    1
    2016-01-05    0
Name: data, dtype: int64
```

instead of:
```
In [10]: exp
Out[10]:
id  date
a   2016-01-01    2
b   2016-01-03    2
    2016-01-05    1
Name: data, dtype: int64
```

But I got your idea. The main challenge is that `self.grouper` is overriding [here](https://github.com/pandas-dev/pandas/blob/33a1202cd3e2dbc86b9b4adc1b54152c8cd67075/pandas/core/groupby.py#L511). Could you take a look at newest solution? @jreback

2018-02-04 15:28 UTC, jreback requested changes
change looks good. some comments. ping on green.

2018-02-04 15:28 UTC, jreback commented on doc/source/whatsnew/v0.23.0.txt
> +- Bug in `DataFrame.groupby` with resample using `on` parameter when selecting column to apply function (:issue:`17813`)
passing the ``on=`` kwarg, and subsequently using ``.apply()`` (not the double backticks on both)

2018-02-04 15:28 UTC, jreback commented on pandas/core/groupby.py
> +            if getattr(self.grouper, 'name', None) == key and \
can you add a comment here about what this is doing (IOW the on is already defined).

use ``ABCSeries`` rather than ``Series``

2018-02-04 15:28 UTC, jreback commented on pandas/tests/test_resample.py
> +    def test_groupby_resample_on_api_with_getitem(self):
can you move this a bit lower down in the file (immediately after the other getitem tests)

2018-02-05 09:13 UTC, discort commented
@jreback

2018-02-05 11:13 UTC, closed without merging

2018-02-05 11:14 UTC, jreback commented
thanks @discort