BUG: Fix problem with SparseDataFrame not persisting to csv
pandas-dev/pandas pull request #19441
Opened 2018-01-29 08:03 UTC by hexgnu

- [x] closes #19384
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-01-30 00:24 UTC, jreback requested changes

2018-01-30 00:24 UTC, jreback commented on pandas/core/internals.py
> +        # values = self.values
you can remove the comment

2018-01-30 00:24 UTC, jreback commented on pandas/tests/io/formats/test_to_csv.py
> +        sdf = pd.SparseDataFrame({'a': [1, 2]})
add a comment here for the issue number. I would rather have this test in pandas/tests/sparse/frame/test_to_csv.py 

can you add several variations, e.g. using fill value and with some nulls.

2018-01-30 02:43 UTC, pep8speaks commented
Hello @hexgnu! Thanks for updating the PR.



 - In the file [`pandas/tests/sparse/frame/test_to_csv.py`](https://github.com/pandas-dev/pandas/blob/ffdcaa282f1b8712c99f4f8fe8dcfcdaedc93c32/pandas/tests/sparse/frame/test_to_csv.py), following are the PEP8 issues :

> [Line 7:1](https://github.com/pandas-dev/pandas/blob/ffdcaa282f1b8712c99f4f8fe8dcfcdaedc93c32/pandas/tests/sparse/frame/test_to_csv.py#L7): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 11:69](https://github.com/pandas-dev/pandas/blob/ffdcaa282f1b8712c99f4f8fe8dcfcdaedc93c32/pandas/tests/sparse/frame/test_to_csv.py#L11): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 11:71](https://github.com/pandas-dev/pandas/blob/ffdcaa282f1b8712c99f4f8fe8dcfcdaedc93c32/pandas/tests/sparse/frame/test_to_csv.py#L11): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 11:80](https://github.com/pandas-dev/pandas/blob/ffdcaa282f1b8712c99f4f8fe8dcfcdaedc93c32/pandas/tests/sparse/frame/test_to_csv.py#L11): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)

2018-01-30 02:46 UTC, hexgnu commented
K updated thanks @jreback

2018-01-30 15:16 UTC, TomAugspurger commented
@hexgnu do the tests you've written pass for you locally?

2018-01-30 23:54 UTC, hexgnu commented
oi sorry, should pass now.

2018-01-31 12:49 UTC, TomAugspurger commented
Still one lint failure: https://travis-ci.org/pandas-dev/pandas/jobs/335405859#L3035

I'm looking into the (unrelated) S3 failures later this morning.

2018-02-01 00:25 UTC, hexgnu commented
Ok for real this time it passed @jreback @TomAugspurger thanks 😄

2018-02-01 00:30 UTC, jreback requested changes

2018-02-01 00:30 UTC, jreback commented on pandas/tests/sparse/frame/test_to_csv.py
> +    for fill_value in fill_values:
can you parameterize

2018-02-01 00:30 UTC, jreback commented on pandas/tests/sparse/frame/test_to_csv.py
> +    fill_values = [np.nan, 0, None, 1]
can you add the issue number here as well

2018-02-01 00:31 UTC, jreback commented on doc/source/whatsnew/v0.23.0.txt
> +- Bug in :class:`SparseDataFrame.to_csv` where too many indices for values (:issue:`19384`)
move to sparse, and don't need this kind of detail, just say was raising.

2018-02-01 12:19 UTC, jreback commented
a lint error.ping when pushed and green.

2018-02-01 13:45 UTC, jreback approved these changes

2018-02-01 13:45 UTC, jreback commented
great. ping on green.

2018-02-01 19:26 UTC, merged

2018-02-01 19:26 UTC, TomAugspurger commented
Thanks @hexgnu!