Mi get loc performance
pandas-dev/pandas pull request #19464
Opened 2018-01-30 13:14 UTC by toobaz

- [x] tests passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

The second commit is related only in the sense that the docs mentioned a ``PerformanceWarning`` due to (non-)sorting, while it was actually due (non-)uniqueness.

2018-01-31 00:00 UTC, jreback requested changes
can you add any asv's that are needed and show the results (or if there is already sufficient coverage, can you show the results)

2018-01-31 00:00 UTC, jreback commented on doc/source/whatsnew/v0.23.0.txt
> +- Improved performance of :func:`MultiIndex.get_loc` for non-unique indexes, which as a consequence does not emit a ``PerformanceWarning`` any more
can you add the issue number (this PR number if no issue).

2018-02-24 17:03 UTC, jreback commented
rebase when you can and pls show perf

2018-02-24 17:18 UTC, toobaz commented
> rebase when you can and pls show perf

Unfortunately I found out that performance drops dramatically in some cases... until I'm able to fix and merge #19539.

2018-02-24 17:19 UTC, jreback commented
ok https://github.com/pandas-dev/pandas/pull/19464#issuecomment-368243824

keep open then?

2018-02-24 17:21 UTC, toobaz commented
> keep open then?

definitely... I think they are both significant improvements, I just need to understand what's wrong with Windows

2018-05-08 07:51 UTC, toobaz commented
Rebased, and #19539 did improve things significantly... but results are still not what one expects from a performance fix!

```
       before           after         ratio
     [2299693d]       [cd7fd6b1]
+         125±6ms          247±1ms     1.98  multiindex_object.Duplicated.time_duplicated_loc
-      14.4±0.3μs       11.9±0.1μs     0.82  multiindex_object.GetLoc.time_string_get_loc

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
```

I will have to investigate more.

2018-07-28 14:37 UTC, jreback commented
can you rebase

2018-11-01 01:44 UTC, jreback commented
closing as stale. if you'd like to continue pls ping.

2018-11-01 01:44 UTC, closed without merging