Use cythonize for build
pandas-dev/pandas pull request #19484
Opened 2018-02-01 01:08 UTC by jbrockmendel

Discussed back in #18089.  This builds OK locally, we'll see about the CI...

- Makes `util` a module instead of a stub.
- Renames io/sas/_sas.pyx --> io/sas/sas.pyx, otherwise a warning is produced at compile-time and an error is raised at import-time.

2018-02-01 01:26 UTC, jreback requested changes

2018-02-01 01:26 UTC, jreback commented on pandas/_libs/util.pyx
> +cdef bint is_datetime64_object(object obj) nogil:
i think these should actually be in the .pxd

2018-02-04 01:01 UTC, pep8speaks commented
Hello @jbrockmendel! Thanks for updating the PR.



 - In the file [`setup.py`](https://github.com/pandas-dev/pandas/blob/5b24944f921032b2d7281056f785abb867cc9af1/setup.py), following are the PEP8 issues :

> [Line 153:23](https://github.com/pandas-dev/pandas/blob/5b24944f921032b2d7281056f785abb867cc9af1/setup.py#L153): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 154:19](https://github.com/pandas-dev/pandas/blob/5b24944f921032b2d7281056f785abb867cc9af1/setup.py#L154): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four

2018-02-04 05:40 UTC, jbrockmendel commented
It looks like the CI errors are occurring in builds with cython pinned to 0.24.0.  The un-pinned builds are using 0.27.3 and passing.  Running locally it looks like 0.25.0 still breaks, but 0.26.0 works.

2018-02-05 17:42 UTC, jbrockmendel commented
@gfyoung any idea what the timeline is for bumping the cython specs?  This is going nowhere until that happens, so may be closable.

2018-02-05 17:46 UTC, gfyoung commented
@jbrockmendel : Not my call unfortunately.  Let's ping @jreback about this.

2018-02-06 01:06 UTC, jreback commented
we changed this dep to 0.23 in pandas 0.20.1

2018-02-06 16:03 UTC, jbrockmendel commented
It looks like implementing tslibs.util is a/the fix for the older cythons.

2018-02-06 23:52 UTC, jreback commented
looks good. going to need a perf check. might want to put the util changes in a separate PR?

2018-02-07 16:57 UTC, jbrockmendel commented
Ran the whole asv suite a few times overnight.  Usual melange.  First for just timeseries:

```
asv continuous -f 1.1 -E virtualenv master HEAD -b timeseries
[...]
    before     after       ratio
  [983d71fa] [f09bee78]
+    6.93ms    33.49ms      4.83  timeseries.Factorize.time_factorize(None)
+    6.99ms    33.09ms      4.74  timeseries.Factorize.time_factorize('Asia/Tokyo')
+    6.04ms     9.51ms      1.57  timeseries.AsOf.time_asof('DataFrame')
+  261.93μs   365.65μs      1.40  timeseries.DatetimeIndex.time_add_timedelta('dst')
+  537.02μs   706.39μs      1.32  timeseries.InferFreq.time_infer_freq(None)
+  541.84μs   711.63μs      1.31  timeseries.InferFreq.time_infer_freq('D')
+    5.97ms     7.53ms      1.26  timeseries.AsOf.time_asof_nan('DataFrame')
+  128.04ms   156.67ms      1.22  timeseries.DatetimeIndex.time_to_pydatetime('tz_aware')
+   66.47ms    79.99ms      1.20  timeseries.ToDatetimeISO8601.time_iso8601_tz_spaceformat
+  843.69μs     1.01ms      1.20  timeseries.InferFreq.time_infer_freq('B')
-   21.69ms    19.69ms      0.91  timeseries.DatetimeIndex.time_to_pydatetime('repeated')
-    3.00ms     2.71ms      0.90  timeseries.ToDatetimeCache.time_dup_seconds_and_unit(False)
-    4.82μs     4.26μs      0.88  timeseries.DatetimeIndex.time_get('dst')
-  139.72ms   123.21ms      0.88  timeseries.DatetimeIndex.time_to_time('tz_aware')
-  527.94μs   458.28μs      0.87  timeseries.ResetIndex.time_reest_datetimeindex('US/Eastern')
-    3.79ms     3.15ms      0.83  timeseries.AsOf.time_asof_nan('Series')
-    3.90ms     3.24ms      0.83  timeseries.AsOf.time_asof('Series')
-    2.80ms     1.85ms      0.66  timeseries.ResampleDataFrame.time_method('max')
-    4.92ms     3.02ms      0.61  timeseries.AsOf.time_asof_nan_single('DataFrame')
-    4.33ms     2.54ms      0.59  timeseries.ToDatetimeCache.time_dup_string_tzoffset_dates(True)

    before     after       ratio
  [983d71fa] [f09bee78]
+    1.86ms     3.10ms      1.66  timeseries.DatetimeIndex.time_add_timedelta('repeated')
+  256.82μs   358.71μs      1.40  timeseries.DatetimeIndex.time_add_timedelta('dst')
+  538.74μs   688.32μs      1.28  timeseries.InferFreq.time_infer_freq(None)
+  541.64μs   687.80μs      1.27  timeseries.InferFreq.time_infer_freq('D')
+  840.61μs     1.00ms      1.19  timeseries.InferFreq.time_infer_freq('B')
-    3.96ms     3.42ms      0.86  timeseries.AsOf.time_asof('Series')
-    3.77ms     3.14ms      0.83  timeseries.AsOf.time_asof_nan('Series')
```

And the whole suite:
```
    before     after       ratio
  [983d71fa] [f09bee78]
+   11.95ms    35.06ms      2.93  io.hdf.HDFStorePanel.time_read_store_table_panel
+   20.88ms    44.81ms      2.15  io.hdf.HDF.time_read_hdf('fixed')
+  125.70μs   211.42μs      1.68  indexing.IntervalIndexing.time_getitem_list
+   86.26ms   139.19ms      1.61  io.json.ToJSON.time_float_int_str('split')
+   21.72ms    34.26ms      1.58  offset.OffsetDatetimeIndexArithmetic.time_add_offset(<CustomBusinessDay>)
+   83.22ms   129.40ms      1.55  io.json.ToJSON.time_float_int('split')
+  304.53μs   468.58μs      1.54  stat_ops.SeriesOps.time_op('mean', 'float', False)
+  224.66μs   340.59μs      1.52  offset.OffsetDatetimeIndexArithmetic.time_add_offset(<MonthEnd>)
+  243.17μs   364.07μs      1.50  offset.OffsetDatetimeIndexArithmetic.time_add_offset(<YearEnd: month=12>)
+  224.34μs   334.48μs      1.49  offset.OffsetDatetimeIndexArithmetic.time_add_offset(<MonthBegin>)
+  237.56μs   352.31μs      1.48  offset.OffsetDatetimeIndexArithmetic.time_add_offset(<QuarterBegin: startingMonth=3>)
+    5.35ms     7.92ms      1.48  stat_ops.SeriesMultiIndexOps.time_op(0, 'sem')
+  228.48μs   337.05μs      1.48  offset.OffsetDatetimeIndexArithmetic.time_add_offset(<YearBegin: month=1>)
+  253.66μs   371.63μs      1.47  offset.OffsetDatetimeIndexArithmetic.time_add_offset(<BusinessQuarterEnd: startingMonth=3>)
+  237.63μs   347.45μs      1.46  offset.OffsetDatetimeIndexArithmetic.time_add_offset(<QuarterEnd: startingMonth=3>)
+  234.48μs   341.10μs      1.45  offset.OffsetDatetimeIndexArithmetic.time_add_offset(<BusinessMonthBegin>)
+  235.38μs   341.91μs      1.45  offset.OffsetDatetimeIndexArithmetic.time_add_offset(<Day>)
+  240.36μs   345.56μs      1.44  offset.OffsetDatetimeIndexArithmetic.time_add_offset(<BusinessYearBegin: month=1>)
+  241.32μs   346.50μs      1.44  offset.OffsetDatetimeIndexArithmetic.time_add_offset(<BusinessQuarterBegin: startingMonth=3>)
+  257.84μs   370.16μs      1.44  offset.OffsetDatetimeIndexArithmetic.time_add_offset(<BusinessMonthEnd>)
+  506.50μs   725.95μs      1.43  offset.OffsetDatetimeIndexArithmetic.time_add_offset(<DateOffset: kwds={'months': 2, 'days': 2}>)
+  259.27μs   370.45μs      1.43  timeseries.DatetimeIndex.time_add_timedelta('dst')
+    7.98ms    11.28ms      1.41  binary_ops.Ops.time_frame_add(True, 'default')
+  263.65μs   370.73μs      1.41  offset.OffsetDatetimeIndexArithmetic.time_add_offset(<BusinessYearEnd: month=12>)
+    1.50ms     2.08ms      1.39  inference.NumericInferOps.time_multiply(<type 'numpy.int32'>)
+    1.43ms     1.97ms      1.37  inference.NumericInferOps.time_subtract(<type 'numpy.float32'>)
+   11.94ms    16.09ms      1.35  frame_methods.Repr.time_repr_tall
+    1.01ms     1.33ms      1.31  inference.NumericInferOps.time_subtract(<type 'numpy.uint64'>)
+  303.84μs   396.25μs      1.30  groupby.GroupByMethods.time_method('int', 'sum')
+  108.24ms   140.14ms      1.29  io.json.ToJSON.time_delta_int_tstamp('index')
+  539.02μs   696.29μs      1.29  timeseries.InferFreq.time_infer_freq(None)
+  299.71ns   385.43ns      1.29  timestamp.TimestampProperties.time_is_year_end(<DstTzInfo 'Europe/Amsterdam' LMT+0:20:00 STD>, None)
+  537.47μs   686.67μs      1.28  timeseries.InferFreq.time_infer_freq('D')
+   16.69μs    21.12μs      1.27  offset.OffestDatetimeArithmetic.time_subtract_10(<QuarterEnd: startingMonth=3>)
+  349.34μs   441.60μs      1.26  inference.NumericInferOps.time_multiply(<type 'numpy.uint16'>)
+    3.73ms     4.68ms      1.26  timeseries.ToDatetimeCache.time_dup_seconds_and_unit(True)
+  579.46ms   724.11ms      1.25  io.json.ToJSON.time_delta_int_tstamp_lines('columns')
+  611.83ms   757.73ms      1.24  io.json.ToJSON.time_delta_int_tstamp_lines('split')
+  273.24μs   338.34μs      1.24  inference.NumericInferOps.time_subtract(<type 'numpy.int8'>)
+  415.03μs   513.02μs      1.24  offset.ApplyIndex.time_apply_index(<MonthEnd>)
+  487.02ns   598.83ns      1.23  timestamp.TimestampProperties.time_freqstr(<DstTzInfo 'Europe/Amsterdam' LMT+0:20:00 STD>, None)
+  617.10ms   756.28ms      1.23  io.json.ToJSON.time_delta_int_tstamp_lines('index')
+  857.92μs     1.05ms      1.22  offset.ApplyIndex.time_apply_index(<DateOffset: kwds={'months': 2, 'days': 2}>)
+   10.70ms    12.99ms      1.21  timeseries.Iteration.time_iter_preexit(<function period_range at 0x7fefcb4211b8>)
+  770.87ms   935.24ms      1.21  io.json.ToJSON.time_float_int_lines('columns')
+  761.82ms   923.69ms      1.21  io.json.ToJSON.time_float_int_lines('index')
+  761.20ms   922.92ms      1.21  io.json.ToJSON.time_float_int_lines('split')
+  913.65μs     1.11ms      1.21  offset.OffsetSeriesArithmetic.time_add_offset(<DateOffset: kwds={'months': 2, 'days': 2}>)
+   36.00ms    43.57ms      1.21  eval.Eval.time_chained_cmp('python', 'all')
+   37.37ms    44.94ms      1.20  eval.Eval.time_and('numexpr', 'all')
+  838.16μs     1.01ms      1.20  timeseries.InferFreq.time_infer_freq('B')
+    1.88ms     2.25ms      1.20  stat_ops.SeriesOps.time_op('sem', 'int', True)
+  879.47μs     1.05ms      1.20  binary_ops.Timeseries.time_series_timestamp_compare('US/Eastern')
+  673.02μs   802.19μs      1.19  offset.OffsetSeriesArithmetic.time_add_offset(<BusinessYearEnd: month=12>)
+    1.75ms     2.08ms      1.19  index_object.SetOperations.time_operation('datetime', 'intersection')
+  312.61μs   369.60μs      1.18  stat_ops.SeriesOps.time_op('prod', 'int', True)
+  640.26μs   756.66μs      1.18  offset.OffsetSeriesAri [...]

2018-02-07 16:58 UTC, jbrockmendel commented
Going through looking for asv entries that show up repeatedly:

`timeseries.DatetimeIndex.time_add_timedelta('dst')` is pretty consistently showing up around 1.4x

2018-02-07 21:20 UTC, closed without merging