TST: Remove dupe TimdeltaIndex tests from indexes/timedeltas/test_astype.py
pandas-dev/pandas pull request #19509
Opened 2018-02-02 15:37 UTC by jschendel

- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Both classes in `test_astype.py` and [`test_timedelta.py`](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexes/timedeltas/test_timedelta.py#L19) inherit from `Datetimelike`, which in turn [inherits from `Base`](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexes/datetimelike.py#L9), leading to 200+ dupe tests being run.

Modified `test_astype.py` to inherit from `object` instead, removed some unnecessary boilerplate, and removed some additional tests that were specified to override base class tests.

2018-02-02 15:43 UTC, jschendel commented on pandas/tests/indexes/timedeltas/test_astype.py
> -        # err8083
note that this same test is also in `test_arithmetic.py`, and is overriden in `test_timedeltas`:

https://github.com/pandas-dev/pandas/blob/69cd5fbfd8b57033b0eb280ebc6dd502652f269c/pandas/tests/indexes/timedeltas/test_timedelta.py#L35-L36

https://github.com/pandas-dev/pandas/blob/69cd5fbfd8b57033b0eb280ebc6dd502652f269c/pandas/tests/indexes/timedeltas/test_arithmetic.py#L170-L187

2018-02-02 19:49 UTC, jbrockmendel commented
+1

FWIW there are some other `astype` tests that may be in suboptimal locations:

`test_timedelta.test_freq_conversion` (and the Series cases probably belong elsewhere)
`test_ops.test_astype_object`

2018-02-04 15:52 UTC, jreback requested changes

2018-02-04 15:52 UTC, jreback commented on pandas/tests/indexes/timedeltas/test_astype.py
>      _multiprocess_can_split_ = True
remove any of these ``_multi precess_can_split``, they are really old

2018-02-04 15:54 UTC, jreback commented on pandas/tests/indexes/timedeltas/test_astype.py
>      _multiprocess_can_split_ = True
actually let's do that separately.

2018-02-04 15:54 UTC, jreback approved these changes

2018-02-04 15:54 UTC, merged

2018-02-04 15:54 UTC, jreback commented
thanks!