Remove duplicated logic from period_helper
pandas-dev/pandas pull request #19540
Opened 2018-02-05 17:27 UTC by jbrockmendel

Following on the heels of #19534, this removes a bunch of duplicate logic from period_helper and uses the implementations in np_datetime and ccalendar instead.  A handful of functions are moved directly into period, but for the most part it's deletion.

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-02-06 11:32 UTC, jreback requested changes

2018-02-06 15:18 UTC, jbrockmendel commented on pandas/_libs/src/period_helper.c
> +    int day_of_week = dayofweek(dinfo->year, dinfo->month, dinfo->day);
`DtoB` actually stays in place at least through the next two PRs in this sequence.  This PR is getting `dayofweek` from the implementation in src/datetime/np_datetime, so did remove the duplicated routine in period_helper.

2018-02-06 15:19 UTC, jbrockmendel commented on pandas/_libs/src/period_helper.h
> +int _quarter_year(npy_int64 ordinal, int freq, int *year, int *quarter);
Yah, _quarter_year is actually really redundant with get_yq, so they will be merged in the PR after next.

2018-02-06 15:22 UTC, jbrockmendel commented on pandas/_libs/tslibs/period.pyx
> +cdef int pyear(int64_t ordinal, int freq):
get_accessor_func returns pointers to these functions.  Does that affect inline-ability?

2018-02-06 23:44 UTC, jreback commented on pandas/_libs/tslibs/period.pyx
> +cdef int pyear(int64_t ordinal, int freq):
no idea. ok can you run a perf comparison on period stuff, maybe even vs 0.21.0 so we can get a good sense if anything has changed much.

2018-02-06 23:56 UTC, jbrockmendel commented on pandas/_libs/tslibs/period.pyx
> +cdef int pyear(int64_t ordinal, int freq):
The compiler didn't complain about the inlining.  Looking at timeit results the difference is indistinguishable.  Will get asv going in a few minutes.

2018-02-07 00:38 UTC, jbrockmendel commented
No change against master (running against ~0.21.0 now)

```
asv continuous -f 1.1 -E virtualenv master HEAD -b period
[...]
    before     after       ratio
  [93c86aa1] [9e88f869]
+   60.09μs    68.30μs      1.14  period.PeriodUnaryMethods.time_to_timestamp('M')
+   16.56ms    18.38ms      1.11  period.DataFramePeriodColumn.time_setitem_period_column
-   19.84μs    17.81μs      0.90  period.PeriodUnaryMethods.time_asfreq('M')
-  971.81ns   868.77ns      0.89  period.PeriodProperties.time_property('M', 'daysinmonth')
-   21.83μs    18.90μs      0.87  period.PeriodUnaryMethods.time_now('M')

  [93c86aa1] [9e88f869]
+  851.04ns   968.69ns      1.14  period.PeriodProperties.time_property('M', 'quarter')
-    1.03μs   874.42ns      0.85  period.PeriodProperties.time_property('M', 'dayofyear')

  [93c86aa1] [9e88f869]
+  110.80μs   166.18μs      1.50  period.PeriodIndexConstructor.time_from_date_range('D')

  [93c86aa1] [9e88f869]
+  151.88μs   244.22μs      1.61  period.Indexing.time_intersection
-    1.01μs   842.80ns      0.83  period.PeriodProperties.time_property('min', 'year')
```

2018-02-07 11:32 UTC, jreback commented
rebase as we merged the get_day function. lgtm otherwise.

2018-02-07 22:14 UTC, jbrockmendel commented
Once this goes in I can rebase #19550, then after that we'll get rid of date_info and just use pandas_datetimestruct directly.

2018-02-08 01:09 UTC, jreback commented on pandas/_libs/tslibs/period.pyx
> +    """
as usual want to write doc-strings for things

2018-02-08 01:09 UTC, jreback approved these changes

2018-02-08 01:09 UTC, merged

2018-02-08 01:09 UTC, jreback commented
thanks!