BUG: Fixed merge on dtype equal categories
pandas-dev/pandas pull request #19553
Opened 2018-02-06 17:37 UTC by TomAugspurger

closes #19551

2018-02-06 21:05 UTC, jorisvandenbossche approved these changes

2018-02-06 23:04 UTC, jreback requested changes

2018-02-06 23:04 UTC, jreback commented on doc/source/whatsnew/v0.23.0.txt
> +  the categories were unordered and had the same values but in a different
looks fine

maybe should elevate to a subsection to highlite this

2018-02-07 16:00 UTC, TomAugspurger commented
Found one more case hit by this (`get_indexer`). Made a warning in the docs, still under the bugfix section though.

2018-02-08 01:20 UTC, jreback approved these changes

2018-02-08 01:20 UTC, merged

2018-02-08 01:20 UTC, jreback commented
thanks! looks good @TomAugspurger, yeah way you did docs is good.