remove 1 char line terminator limit
pandas-dev/pandas pull request #19601
Opened 2018-02-08 18:47 UTC by jwdeitch

This PR closes #3501
This restriction is preventing the loading of CRLF delimited CSVs

Steps to reproduce:

```
import pandas as pd
import StringIO
pd.read_csv(StringIO.StringIO(' a,b,c\r\n'), header=None, lineterminator='\r\n')
```

while the following parses the CSV successfully: 

```
import pandas as pd
import StringIO
pd.read_csv(StringIO.StringIO(' a,b,c\r\n'), header=None)
```

2018-02-08 21:35 UTC, chris-b1 commented
It's not clear exactly what this is fixing - your second example runs before this change?  Also needs tests, thanks.

2018-02-08 21:40 UTC, jwdeitch commented
@chris-b1 
sure - will add tests
the first example explicitly specifies the CRLF lineterminator and fails - the second example does not specify the lineterminator and succeeds. This behavior does not seem desirable

2018-02-11 09:02 UTC, eromoe commented
@chris-b1 Simply, `df = pd.read_csv(doc, sep='\t',  lineterminator='\r\n')`  would fail on windows.

2018-02-11 16:25 UTC, jreback requested changes
pls add a whatsnew note. add in other enhancements section. (say taking off the restriction), use this PR number as the issue.

2018-02-11 16:25 UTC, jreback commented on pandas/tests/io/parser/c_parser_only.py
> +        data = 'a,\n,c\r\n1,2,3\r\n4,\r,6'
can you add the issue number. is this *only* c_parser? (I think yes), just confirming

2018-02-13 18:18 UTC, chris-b1 commented
As the tests are showing, this is more complicated than just removing the check - down in the c parser the line terminator can only be 1 character:
https://github.com/pandas-dev/pandas/blob/df38f66b417b754afdd2b0e17282255bbf2c769e/pandas/_libs/src/parser/tokenizer.h#L172

`'\r\n'` is special - parsing code gets tough to follow, but is effectively the default.
https://github.com/pandas-dev/pandas/blob/df38f66b417b754afdd2b0e17282255bbf2c769e/pandas/_libs/src/parser/tokenizer.c#L668

So a better workaround for #3501 may be to simply special-case it - treat `'\r\n'` as `lineterminator=None`

2018-09-25 16:06 UTC, jreback commented
closing as stale. if you are interested in fixing according to @chris-b1 comments, pls ping / submit new pr.

2018-09-25 16:06 UTC, closed without merging

2019-09-01 17:56 UTC, martin0 commented
\r\n line terminator in windows is still problematic.
even with single char line terminator, pandas displays \n in undesirable places.
I'm new to pandas and python. Do I need to debug this myself?

2019-09-01 18:42 UTC, martin0 commented
ironically, part of the issue is using debug console in visual studio code. - it displays literal \n instead of producing a new line.

2019-10-11 08:16 UTC, danjjl commented
I still cannot load a csv file with a CRLF line terminator. is their a trick to load such a file in pandas?

2020-04-25 14:32 UTC, bf commented
@danjjl unfortunately it is still a mess. I have CSV files with \r\n line terminators and some columns contain random \n's within the text. Panda breaks on this.

2021-06-26 16:43 UTC, lmatzer commented
This is still reproducible in v1.2.4.

2021-06-26 16:46 UTC, jreback commented
this a non merged PR the issue is #3501