Fix uncaught OutOfBounds in array_to_datetime
pandas-dev/pandas pull request #19612
Opened 2018-02-09 04:00 UTC by jbrockmendel

The call to convert_datetime_to_tsobject has a check_dts_bounds in it.  One of the usages in array_to_datetime gets that right, the other misses it.

2018-02-10 15:59 UTC, jreback requested changes

2018-02-10 15:59 UTC, jreback commented on pandas/tests/tslibs/test_tslib.py
> +class TestArrayToDatetime(object):
hmm this should be in ``pandas/tests/indexes/datetimes/test_tools.py``. I know you are ceating new locations is fine. but would rather move all of tools testing there (in a new PR).

2018-02-10 16:00 UTC, jreback commented
does this have a referenced issue? needs a whatsnew note

2018-02-10 18:15 UTC, jbrockmendel commented
> does this have a referenced issue? 

None that I found.

2018-02-11 14:48 UTC, jreback approved these changes

2018-02-11 14:48 UTC, merged

2018-02-11 14:48 UTC, jreback commented
thanks!