Bug: Do not round DatetimeIndex nanosecond precision when iterating
pandas-dev/pandas pull request #19628
Opened 2018-02-10 08:34 UTC by mroeschke

- [x] closes #19603
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

This issue was actually very specific to localizing a `DatetimeIndex` with `datetime.timezone.utc`

```
# On master
In [1]: import pandas as pd

In [2]: datetimeindex = pd.DatetimeIndex(["2018-02-08 15:00:00.168456358"], tz='UTC')

In [3]: list(datetimeindex)[0] == datetimeindex[0] # returned False with datetime.timezone.utc
Out[3]: True 
```

I realize our timezone support relies heavily on pytz and dateutil, but I am curious how much support we have for `datetime.timezone` objects.

2018-02-10 15:50 UTC, jreback requested changes
we would need comprehensive support for datetime.timezone in order to accept this. IOW you need to add testing in LOTS of places where we test datetutil/pytz

2018-02-10 15:50 UTC, jreback commented on pandas/_libs/tslibs/timezones.pyx
> +    if PY3:
this would be a perf issue, you can almost certainly access this in stead at the cython level

2018-02-10 15:50 UTC, jreback commented on pandas/tests/indexes/datetimes/test_datetime.py
> +    from datetime import timezone
this is not idiomatic, see comments above

2018-02-11 08:04 UTC, mroeschke commented
I updated the fix and found the real issue (edited in my description above).

2018-02-11 15:05 UTC, jreback requested changes

2018-02-11 15:05 UTC, jreback commented on pandas/_libs/tslib.pyx
> +                    # Python datetime objects do not support nanosecond
use tz_convert_tzlocal_to_utc here from conversion.pyx

2018-02-11 15:05 UTC, jreback commented on pandas/tests/indexes/datetimes/test_datetime.py
> +    from datetime import timezone
rather than put this here, make a fixture in pandas/conftest.py

called datetime_tz_utc to return this and skip if its not PY3

2018-02-11 15:05 UTC, jreback commented on pandas/tests/indexes/datetimes/test_datetime.py
> +    def test_iteration_preserves_nanoseconds(self, tz):
add a similar test for pandas/tests/scalar/test_timezones.py

2018-02-11 15:05 UTC, jreback commented on pandas/tests/indexes/datetimes/test_datetime.py
> +                                    dateutil.tz.tzoffset(None, -28800)])
move to test_timezones (in same subdir)

2018-02-11 15:06 UTC, jreback requested changes

2018-02-11 15:06 UTC, jreback commented on pandas/tests/indexes/datetimes/test_datetime.py
> +        assert list(index)[0] == index[0]
check both getitem and iteration

2018-02-11 23:52 UTC, mroeschke commented
Replaced fix with the use of `tz_convert_utc_to_tzlocal`, added `datetime_tz_utc` fixture, Also I am not sure what test I should have added to `pandas/tests/scalar/test_timezones.py` since the issue is with `DatetimeIndex.__iter__`

2018-02-14 09:02 UTC, mroeschke commented
All green

2018-02-14 11:05 UTC, jreback approved these changes

2018-02-14 11:05 UTC, merged

2018-02-14 11:07 UTC, jreback commented
thanks @mroeschke 

FYI looking to move tz to be fixtures (e.g. the strings 'UTC', 'Asia/Tokyo') etc....across the test codebase, IOW to have a 'tz' fixture (prob need several slightly different ones)

cc @jbrockmendel