fix overflows in Timestamp.tz_localize near boundaries
pandas-dev/pandas pull request #19626
Opened 2018-02-10 02:58 UTC by jbrockmendel

Flesh out docstring for localize_tsobject, add slightly stronger typing.

Closes #12677

2018-02-10 17:12 UTC, jreback requested changes
can you add a whatsnew note, small changes. ping on green.

2018-02-10 17:12 UTC, jreback commented on pandas/_libs/tslibs/conversion.pyx
> +cdef inline _check_silent_overflows(_TSObject obj):
de-privatize. by definition not public if its not in the .pxd

2018-02-10 17:12 UTC, jreback commented on pandas/_libs/tslibs/conversion.pyx
> +cdef inline void _localize_tso(_TSObject obj, tzinfo tz):
can you de-privatize

2018-02-10 17:12 UTC, jreback commented on pandas/tests/scalar/timestamp/test_timezones.py
> +from pandas._libs.tslib import OutOfBoundsDatetime
from pandas.errors

2018-02-10 18:20 UTC, jreback requested changes
more minor comment

2018-02-10 18:20 UTC, jreback commented on pandas/_libs/tslibs/conversion.pyx
> +        check_silent_overflows(obj)
rename to check_overlows

2018-02-10 18:20 UTC, jreback commented on pandas/_libs/tslibs/conversion.pyx
> +cdef inline check_silent_overflows(_TSObject obj):
rename, add doc-string (just convert your comment)

2018-02-10 18:20 UTC, jreback commented on pandas/_libs/tslibs/conversion.pyx
> +    (void)
None

2018-02-10 18:32 UTC, jreback approved these changes

2018-02-10 18:32 UTC, jreback commented
lgtm. ping ongreen.

2018-02-10 23:24 UTC, jbrockmendel commented
Ping

2018-02-11 00:04 UTC, merged

2018-02-11 00:04 UTC, jreback commented
thanks

2018-02-11 16:05 UTC, jreback commented
some warnings as a result of this change

```
pandas/tests/scalar/timestamp/test_timezones.py::TestTimestampTZOperations::()::test_tz_localize_pushes_out_of_bounds
  /home/travis/build/pandas-dev/pandas/pandas/tests/scalar/timestamp/test_timezones.py:32: RuntimeWarning: overflow encountered in long_scalars
    Timestamp.min.tz_localize('Asia/Tokyo')
  /home/travis/build/pandas-dev/pandas/pandas/tests/scalar/timestamp/test_timezones.py:39: RuntimeWarning: overflow encountered in long_scalars
    Timestamp.max.tz_localize('US/Pacific')
```

2018-03-26 01:16 UTC, jreback commented
when you have a chance can you look at the warnings above: https://github.com/pandas-dev/pandas/pull/19626#issuecomment-364762511