Gh18498
pandas-dev/pandas pull request #19735
Opened 2018-02-17 01:25 UTC by mikebarkas

- [x] closes #18498 
- [x] tests moved / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Moved test classes for pytables into sub-modules.
Moved hdf test data files needed into sub-module.

I did not change any tests, just broke up the classes into separate modules.

2018-02-17 01:25 UTC, pep8speaks commented
Hello @mikebarkas! Thanks for submitting the PR.

 - In the file [`pandas/tests/io/pytables/common.py`](https://github.com/pandas-dev/pandas/blob/65419cea814cef0b6b1cc0e35442be7ed23df383/pandas/tests/io/pytables/common.py), following are the PEP8 issues :

> [Line 28:9](https://github.com/pandas-dev/pandas/blob/65419cea814cef0b6b1cc0e35442be7ed23df383/pandas/tests/io/pytables/common.py#L28): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'
> [Line 36:5](https://github.com/pandas-dev/pandas/blob/65419cea814cef0b6b1cc0e35442be7ed23df383/pandas/tests/io/pytables/common.py#L36): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'
> [Line 94:5](https://github.com/pandas-dev/pandas/blob/65419cea814cef0b6b1cc0e35442be7ed23df383/pandas/tests/io/pytables/common.py#L94): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'

2018-02-17 01:30 UTC, mikebarkas commented
PEP8 issue for `common.py` 
`do not use bare except` This is in existing code.
This issue is for moving the tests and not changing test.

2018-02-18 15:53 UTC, jreback requested changes

2018-02-18 15:53 UTC, jreback commented on pandas/tests/io/pytables/common.py
> +tables = pytest.importorskip('tables')
if things are not used here, remove them

2018-02-18 15:53 UTC, jreback commented on pandas/tests/io/pytables/common.py
> +def safe_remove(path):
would like to tun these into fixtures, also this removes the need for the Base class entirely. ok with doing this in another pass though

2018-02-18 15:53 UTC, jreback commented on pandas/tests/io/pytables/test_hdf_complex_values.py
> +
you can just name this test_complex.py

2018-02-18 15:53 UTC, jreback commented on pandas/tests/io/pytables/test_hdf_store.py
> -    def teardown_method(self, method):
the idea is to split this out into many submodules, e.g. 

test_store (construct & instrospect a store)
test_append
test_multiindex
test_remove
test_where
test_select

basically just select similar tests (by name to start is ok) and group them into sub-modules

2018-02-18 15:53 UTC, jreback commented on pandas/tests/io/pytables/test_timezones.py
> +        from datetime import timedelta
move any imports to the top

2018-02-22 02:29 UTC, jreback commented
@mikebarkas looks great!

oddly there is 1 less tests here (174 and 1 xfail) vs 175 and 1 xfail on master.

happy to have parameterization of any tests as well.

2018-02-22 02:36 UTC, mikebarkas commented
My test build on my fork is failing because  `ImportError: No module named tables`
Looking into it.

I will look for the missing test.

2018-02-22 03:27 UTC, mikebarkas commented
This is my missing test
```
def test_longpanel(self):
    pass
```

I will add it back into `test_panel`

2018-02-22 03:30 UTC, jreback commented
oh no need to add that back then

2018-02-23 11:34 UTC, jreback requested changes
a bit too much splitting. idea is to put common files together. tests might be named inconsitenly, but still to group them together, we should end up with only about 5 ish modules here overall.

2018-02-23 11:34 UTC, jreback commented on pandas/tests/io/pytables/test_common.py
> +from pandas.tests.io.pytables.common import (ensure_clean_store, safe_close,
you can just do a

```
from .common import .....
```

(and do this generally)

2018-02-23 11:34 UTC, jreback commented on pandas/tests/io/pytables/test_common.py
> +from pandas.util.testing import (assert_panel_equal,
prefer not to import these and just reference with ``tm.``

2018-02-23 11:34 UTC, jreback commented on pandas/tests/io/pytables/test_common.py
> +from pandas.util.testing import (assert_panel_equal,
also do this generally across all files

2018-02-23 11:34 UTC, jreback commented on pandas/tests/io/pytables/test_date.py
> +from pandas import Series, DataFrame, date_range, timedelta_range, bdate_range
can you rename to test_datetime

2018-02-23 11:34 UTC, jreback commented on pandas/tests/io/pytables/test_panel.py
> +
there are may more panel tests, can you move here

2018-02-23 11:34 UTC, jreback commented on pandas/tests/io/pytables/test_path.py
> +        assert not store.is_open
these need to go with any other open/close tests, which I think you have in test_common.py now. call this file test_open_close (move this one and other tests)

2018-02-23 11:34 UTC, jreback commented on pandas/tests/io/pytables/test_read.py
> +import numpy as np
there are many more selection / query type tests that are in test_common. move here

2018-02-23 11:34 UTC, jreback commented on pandas/tests/io/pytables/test_read.py
> +import pytest
rename this to test_query

2018-02-23 11:34 UTC, jreback commented on pandas/tests/io/pytables/test_select.py
> +from pandas.tests.io.pytables.common import (ensure_clean_store,
consolidate with test_read (and call test_query)

2018-02-23 11:34 UTC, jreback commented on pandas/tests/io/pytables/test_start_stop.py
> +
move these to test_select, we don't need a separate file for this

2018-02-23 11:34 UTC, jreback commented on pandas/tests/io/pytables/test_store.py
> +                               [0, 1, 2, 0, 1, 1, 2, 0, 1, 2]],
these need to be put in the right place, not a separate file

2018-04-29 10:03 UTC, alsobay commented
Hi Mike, are you still working on this? Would be glad to help out or pick it up if you're too busy.

2018-07-28 14:36 UTC, jreback commented
closing as stale, happy to take an updated PR of this

2018-07-28 14:36 UTC, closed without merging