BUG: drop_duplicates not raising KeyError on missing key
pandas-dev/pandas pull request #19730
Opened 2018-02-16 18:14 UTC by NoahTheDuke

- [x] closes #19726 
- [ ] tests added / passed
- [x] passes git diff upstream/master -u -- "*.py" | flake8 --diff
- [ ] whatsnew entry

2018-02-18 16:19 UTC, jreback requested changes

2018-02-18 16:19 UTC, jreback commented on pandas/core/frame.py
> +        for name in subset:
can you add a comment here on what you are checking

2018-02-18 16:19 UTC, jreback commented on pandas/core/frame.py
> +        for name in subset:
you can do this
```
diff = pd.Index(subset).difference(self.columns)
if len(diff):
     raise KeyError(diff)
```

2018-02-18 16:20 UTC, jreback commented
can you also check ``.duplicated()`` (and add a test)

2018-02-21 02:03 UTC, NoahTheDuke commented
Updated!

2018-02-21 11:40 UTC, jreback approved these changes

2018-02-21 11:40 UTC, merged

2018-02-21 11:40 UTC, jreback commented
thanks!