TST: add test for numpy ops, esp. nanmin/max bug for np<1.13
pandas-dev/pandas pull request #19753
Opened 2018-02-18 22:13 UTC by topper-123

- [x] closes #8383
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

The bug in #8383 concerns np.nanmin and np.nanmax only, don't know if I'm testing too much.

2018-02-18 22:32 UTC, jreback requested changes

2018-02-18 22:32 UTC, jreback commented on pandas/tests/test_nanops.py
> +np_version113 = LooseVersion(np.__version__) >= LooseVersion('1.13')
import from pandas
we already define this

2018-02-18 22:32 UTC, jreback commented on pandas/tests/test_nanops.py
> +    # GH8383
you can just make 2 tests
1 for numpy >= 1.13 and 1 for < 1.13 which assert those functions which exist there

2018-02-18 23:23 UTC, topper-123 commented
Comments addressed. Not sure if I understood your second, but please look at changed versions.

2018-02-18 23:27 UTC, jreback approved these changes

2018-02-18 23:28 UTC, jreback commented
lgtm ping on green

2018-02-19 09:46 UTC, topper-123 commented
all green.

2018-02-19 13:50 UTC, merged