ENH: Let initialisation from dicts use insertion order for python >= 3.6 (part I)
pandas-dev/pandas pull request #19830
Opened 2018-02-21 22:04 UTC by topper-123

- [x] xref #19018
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

This PR prepares pandas to allow initialisation using insertion order for python>=3.6. E.g. ``Series({'B': 1, 'A': 2})`` will then retain order and not convert to ``Series({'A': 2, 'B': 1})``.

Letting dataframe/series initialisation from dicts preserve order for python >=3.6 is a relative simple change, just change a line each in core/frame.py and core/series.py. However, this makes some 36 tests fail, as the tests have been set up to depend on conversion to alphabetical order.

This PR makes all tests in ``pandas/tests/frame`` pass both if dict initialisation uses insertion order and alphabetical order. No test functionality is changed in this PR.

After this PR I will do 1 or 2 more similar PRs, so all tests pass independent of dict initialisation rule, and then core/frame.py and core/series.py will be changed to use insertion order for python>=3.6.

2018-02-22 01:53 UTC, jreback commented
seems fine. small comments. ping on green.

2018-02-22 06:53 UTC, topper-123 commented
Green.

2018-02-22 11:11 UTC, jreback requested changes

2018-02-22 15:01 UTC, jreback approved these changes

2018-02-22 15:01 UTC, jreback commented
lgtm ping on green

2018-02-23 01:22 UTC, merged

2018-02-23 01:22 UTC, jreback commented
thanks