Fix+test DTI/TDI/PI add/sub with ndarray[datetime64/timedelta64]
pandas-dev/pandas pull request #19847
Opened 2018-02-22 20:08 UTC by jbrockmendel

Two notes for upcoming passes:

- the tests are pretty redundant, can be parametrized more tightly once they are all OK.
- catching ndarray[datetime64] separately from DatetimeIndex is kind of weird, but for the moment necesarry.  Once #19835 goes through and re-orders the catching, we'll be able to fix this.

2018-02-23 09:12 UTC, gfyoung commented
@jbrockmendel : Good direction so far!  Looks you can parametrize now since all the CI is green.

2018-02-23 11:38 UTC, jreback requested changes

2018-02-23 11:38 UTC, jreback commented on pandas/core/indexes/datetimelike.py
> +                from pandas.core.indexes.datetimes import DatetimeIndex
since inside a function, can just import from pandas directrly

2018-02-23 11:38 UTC, jreback commented on pandas/core/indexes/datetimelike.py
> +                from pandas.core.indexes.datetimes import DatetimeIndex
atually pls change all imports that are inside functions to do this (its just shorter)

2018-02-24 15:24 UTC, jreback commented
needs a rebase. does this fix any open issue?

2018-02-24 16:31 UTC, jbrockmendel commented
> does this fix any open issue?

Not that I'm aware of.

2018-02-24 16:41 UTC, jreback requested changes
this needs a whatsnew note to show what is a bug fix  / enhancement / api change (IOW what works now that didn't work before)

2018-02-24 16:41 UTC, jreback commented on pandas/tests/indexes/datetimes/test_arithmetic.py
> +    def test_dti_add_dt64_array_raises(self, tz):
these tests don't exist already? odd

2018-02-24 23:32 UTC, jbrockmendel commented
Here too Travis error is pyarrow import

2018-02-25 16:11 UTC, jreback approved these changes

2018-02-25 16:11 UTC, merged

2018-02-25 16:11 UTC, jreback commented
thanks