Fixed issue with leftover test.json file
pandas-dev/pandas pull request #19879
Opened 2018-02-24 07:56 UTC by jjames34

- [ ] closes #19815
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-02-24 13:20 UTC, TomAugspurger commented on doc/source/whatsnew/v0.23.0.txt
> +   test_json_buf = io.StringIO()
Ideally, a user reading this doesn't have to care about any of the stuff with the IO buffer. They only care about writing and reading the dataframe.

I think it's best to leave the `df.to_json` and `new_df = ` as it was previosly.

Then we can add a new `ipython` block afterwards to remove the file.

```
.. ipython:: python
   :suppress:

   import os
   os.remove('test.json')
```

2018-02-24 14:32 UTC, jreback requested changes
pls change to using @TomAugspurger soln

2018-02-25 16:17 UTC, jreback approved these changes

2018-02-25 16:17 UTC, merged

2018-02-25 16:17 UTC, jreback commented
thanks!