Pct change fill
pandas-dev/pandas pull request #19875
Opened 2018-02-24 00:20 UTC by WillAyd

- [X] closes #19873 
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

2018-02-24 00:24 UTC, jreback commented on pandas/tests/generic/test_generic.py
> +            pytest.skip("Not testing deprecated Panel")
just add this method to the Panel section and it will skip automatically

2018-02-24 16:17 UTC, jreback requested changes

2018-02-24 16:17 UTC, jreback commented on pandas/tests/generic/test_generic.py
> +        # Convert output into Series, regardless of input type
if you rename obj above, you can simply determine the output down here, and make this a bit less convoluted, e.g.

```
if type(obj) is DataFrame:
    # compare dataframe
else:
   # compare series
```

2018-02-25 07:08 UTC, WillAyd commented
Failed Travis tests don't appear related to the change

2018-02-25 16:06 UTC, merged

2018-02-25 16:07 UTC, jreback commented
thanks @WillAyd