transition period_helper to use pandas_datetimestruct
pandas-dev/pandas pull request #19918
Opened 2018-02-26 22:07 UTC by jbrockmendel

In the last round we transitioned period.pyx to use pandas_datetimestruct instead of date_info.  This does the same thing for period_helper.

2018-02-27 01:30 UTC, jreback commented
lgtm. ping on green.

2018-02-27 01:30 UTC, jreback commented
actually, any doc-strings to update?

2018-02-27 01:43 UTC, jbrockmendel commented
> actually, any doc-strings to update?

The affected docstrings are already updated.

2018-02-28 11:24 UTC, jreback requested changes
doc-strings, can you rebase on master

2018-02-28 11:24 UTC, jreback commented on pandas/_libs/tslibs/period.pyx
> +                             int s, int us, int ps, int freq):
doc-string

2018-03-01 11:26 UTC, jreback commented
you need to rebase on master

2018-03-02 17:14 UTC, jbrockmendel commented
Ping

2018-03-04 20:00 UTC, jreback approved these changes

2018-03-04 20:00 UTC, merged

2018-03-04 20:00 UTC, jreback commented
thanks!