Adding sample datasets to be used in the documentation
pandas-dev/pandas pull request #19933
Opened 2018-02-28 00:03 UTC by datapythonista

- [X] closes #19710 
- [ ] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

2018-03-01 01:19 UTC, jreback commented
I thought we had an issue about this already, IIRC @mrocklin either made it or commented (was for a slightly different purpose though).

2018-03-01 01:20 UTC, jreback commented
We already have lots of data constructors in ``pandas.util.testing``, though these are 'nicer' ones. These would need testing (e.g. do they run), and can be de-privatized (no leading _).

2018-03-01 08:47 UTC, jorisvandenbossche commented
> I thought we had an issue about this already, IIRC @mrocklin either made it or commented (was for a slightly different purpose though).

I don't know if there is an older issue, but this is related to what is recently discussed in https://github.com/pandas-dev/pandas/issues/19710 as @datapythonista linked to.

2018-03-01 08:49 UTC, jorisvandenbossche commented
> We already have lots of data constructors in pandas.util.testing, though these are 'nicer' ones.

Indeed, I don't think the ones in util.testing are suitable for this, as the exact purpose of those are to be 'nicer' relate-able small dataframes.

2018-03-02 14:57 UTC, datapythonista commented
Any more thoughts on this? Knowing which data to use for the examples in the docstrings is the main blocker for the sprint. Any feedback on how you think we can improve this first draft is highly appreciated. Thanks!

2018-03-02 15:14 UTC, jorisvandenbossche commented
This needs to be imported in some `__init__` files, as otherwise you cannnot do `pd.io.samples. ...`. Or what would be the intended use in the docs?

2018-03-04 20:20 UTC, jreback requested changes

2018-03-04 20:20 UTC, jreback commented on pandas/io/samples.py
> +def _countries_with_penguins():
these need to be de-privatized (no leading _)

2018-03-04 20:20 UTC, jreback commented on pandas/io/samples.py
> +        ('AO', 'Angola', 'Luanda', 'AF', 1, 21.55),
these need tests

2018-03-06 00:08 UTC, datapythonista commented
For what has been discussed in #19710, seems like it probably makes more sense to simply have some ideas on data to be used, but use custom datasets as simple and illustrative as possible depending on each case. So, closing this.

2018-03-06 00:08 UTC, closed without merging