BUG: Compat for pre-0.20 TimedeltaIndex and Float64Index pickles #19939
pandas-dev/pandas pull request #19943
Opened 2018-03-01 00:36 UTC by Liam3851

- [ ] closes #19939 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Added pre-0.20 locations of TimedeltaIndex and Float64Index to pickle_compat.py.

2018-03-01 00:48 UTC, jreback commented
can you add 1 or more pickle files from a pre-0.20 version using the instructions here: https://github.com/pandas-dev/pandas/blob/master/pandas/tests/io/generate_legacy_storage_files.py

this is in effect a test, IOW w/o this patch ``pandas/tests/io/test_pickle.py ``should fail, with it they should pass.

2018-03-01 00:48 UTC, jreback requested changes
also pls add a whatsnew note

2018-03-01 18:36 UTC, Liam3851 commented
Thanks @jreback. I added timedelta, float, uint64, range, and interval indexes to the generate_legacy_storage_files script. I've generated pickles for 0.16.2 and 0.19.2 (which happen to be what I had on hand).

In running the script I realized IntervalIndex doesn't serialize on master for msgpack and neither do the date offsets. I've put these under the not supported section at generate_legacy_storage_files.py:289 so that it's green, but perhaps this is an issue that should be supported?

2018-03-01 23:16 UTC, jreback requested changes
small comments. can you open an issue for the msgpack problems. (of course feel free to PR that), but its separate. also rebase on master.

2018-03-01 23:16 UTC, jreback commented on pandas/tests/io/generate_legacy_storage_files.py
> +        if _loose_version >= '0.21':
can you make not a nested if

2018-03-04 19:58 UTC, jreback approved these changes

2018-03-04 19:58 UTC, merged

2018-03-04 19:58 UTC, jreback commented
thanks!