DOC: Add comparison with Stata page to documentation
pandas-dev/pandas pull request #19945
Opened 2018-03-01 05:10 UTC by kylebarron

- [ ] closes #####
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

I noticed that the pandas documentation has pages for [Comparison with SAS](https://pandas.pydata.org/pandas-docs/stable/comparison_with_sas.html), [Comparison with R](https://pandas.pydata.org/pandas-docs/stable/comparison_with_r.html) and [Comparison with SQL](https://pandas.pydata.org/pandas-docs/stable/comparison_with_sql.html), but nothing for newcomers from Stata.

This is heavily based off of the "Comparison with SAS" page, with all the examples and discussion fixed for Stata.

2018-03-01 05:31 UTC, kylebarron commented
When I recompile with `python make.py html`, the command line interface still asks me
> Running Sphinx v1.7.1
> I'm about to DELETE the following:
> ['comparison_with_stata.rst']
>
> WARNING: I'd like to delete those to speed up processing (yes/no)? 

Is there a configuration file somewhere that I should add this document to?

2018-03-01 11:31 UTC, jreback commented
you need to add to the ``pandas/doc/source/index.rst.template``

2018-03-01 11:32 UTC, jreback requested changes

2018-03-01 11:32 UTC, jreback commented on doc/source/comparison_with_stata.rst
> +********************
sections should be excatly underlined (otherwise you get warnings)

2018-03-01 22:57 UTC, jreback commented
can you render and post this section

2018-03-02 19:48 UTC, kylebarron commented
I rendered it with `python make.py html`, and it looks fine, but Github doesn't let me attach an html file to an issue. How should I post it?

It seems like the Travis build failed from the time limit?
> The job exceeded the maximum time limit for jobs, and has been terminated.

https://travis-ci.org/pandas-dev/pandas/jobs/347824581#L2729

2018-03-09 17:01 UTC, kylebarron commented
@jreback What can I do to get this merged?

2018-03-29 01:40 UTC, kylebarron commented
The CircleCI build is failing on two TSPlot tests, which seem to be unrelated to this PR.

2018-03-29 02:26 UTC, TomAugspurger approved these changes
This looks really nice. I merged in master, which should fix the circle CI issues. ping on green.

2018-03-29 14:26 UTC, kylebarron commented
Ping!

2018-03-29 14:39 UTC, merged