DOC/TST: add test for np.*prod to test_nanops.py + some doc cleanup
pandas-dev/pandas pull request #19968
Opened 2018-03-02 16:52 UTC by topper-123

- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Some minor stuff.

1:
In #19753 I forgot to do tests for np.prod and np.nanprod. Added here.

2:
The README.md has a link about ``DataFrame.ix``. As ``ix`` is deprecated, the link is changed to [selection-by-label](https://pandas.pydata.org/pandas-docs/stable/indexing.html#selection-by-label).

3:
In [selection-by-label](https://pandas.pydata.org/pandas-docs/stable/indexing.html#selection-by-label) a minor wall of warnings come before the reader even knows what the warning are about (because this is the section about `´loc.``...). This is very "scary" introduction.

I've moved the chanied-assignment warning to after the intro, and the rest to the end of the section, so the reader first gets a the understanding about ``loc`` and then only after that gets the warnings about the pitfalls of ``loc``.

2018-03-02 20:53 UTC, gfyoung commented
I would have preferred that you broke your in PR into two separate PR's: one for the indexing and one for your added tests.  It's a little easier to review, and helps to main the atomicity of the PR's / merges.

2018-03-05 11:34 UTC, jreback requested changes

2018-03-05 11:34 UTC, jreback commented on doc/source/indexing.rst
> +   ``.loc`` is strict when you present slicers that are not compatible (or convertible) with the index type. For example
acutallly maybe put some of this somewhere in the slicing with labels section.

2018-03-05 11:34 UTC, jreback commented on doc/source/indexing.rst
> +
this part should be left where it was

2018-05-18 18:09 UTC, closed without merging