DOC: add small guide on how to write examples that pass doctests
pandas-dev/pandas pull request #20037
Opened 2018-03-07 14:56 UTC by jorisvandenbossche

Some initial attention points for getting doctests passing (this would eventually fit in the docstring guide, putting it in contributing.rst for now, will move once the other is merged).

Anybody else thinks of typical gotcha's?

cc @datapythonista

2018-03-07 15:01 UTC, jreback requested changes

2018-03-07 15:01 UTC, jreback commented on doc/source/contributing.rst
> +
can you add sub-section refs

2018-03-07 15:07 UTC, datapythonista commented
One that comes to my mind is reading from files, like `pandas.read_csv`, that I assume it fails, as the file won't be found.

2018-03-07 19:42 UTC, jorisvandenbossche commented
> One that comes to my mind is reading from files, like pandas.read_csv, that I assume it fails, as the file won't be found.

The question is what to do in general for those IO functions. 
Do we want to show actual output? But then there needs to be an actual file to read in, as otherwise it also does not say much. 

In principle you could always create a small file to then read back in.

2018-03-08 20:09 UTC, jorisvandenbossche commented
In general, for read functions, we could do like:

```
For the example, we first create a small example csv file

>>> df = pd.DataFrame(...)
>>> df.to_csv('file.csv')

We can now read that in with read_csv:

>>> pd.read_csv('file.csv')

read with option:

>>> ...
```

for write functions that is a bit more difficult, as you don't directly see what you get. Maybe just showing the basic usage (method call) and then referring to user guide is enough for those?

2018-03-10 12:28 UTC, jreback approved these changes

2018-03-13 22:29 UTC, jorisvandenbossche commented
This was included in the merge of https://github.com/pandas-dev/pandas/pull/19704, so closing.

2018-03-13 22:29 UTC, closed without merging