Latex bugs
pandas-dev/pandas pull request #20032
Opened 2018-03-07 11:06 UTC by shangyian

- [x] closes #19981 and #18669 
- [x] tests added / passed (see `test_to_latex.py`)
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-03-07 11:09 UTC, shangyian commented on pandas/io/formats/format.py
> +    def write_result(self, buf):
I did some refactoring here and broke this method down into a couple of smaller ones. Ideally, pieces like `_rebuild_multi_index()` could also be a bit clearer, but maybe I'll tackle that while looking at some of the other Latex-related bugs.

2018-03-07 11:21 UTC, shangyian commented
Also, after going through some of the other Latex-related bugs, I found [this discussion](https://github.com/pandas-dev/pandas/issues/13203#issuecomment-219744505) about refactoring `to_latex` to use `Styler`. @TomAugspurger, do you think that still makes sense?

2018-03-07 13:03 UTC, jreback requested changes
@shangyian so if going to refactor (great idea!). Would you mind doing a pre-cursor PR to split out to separate files, csv.py, html.py, latex.py (just the CSVFormatter and like classes). into separate module. Then should be much cleaner to re-factor this (e.g. you can make module level & static functions easily)

2018-03-07 13:03 UTC, jreback commented on pandas/io/formats/format.py
> +        def null_replace(x):
can you add doc-strings to added methods

2018-03-08 09:07 UTC, tomneep commented
Hi @shangyian, 
I came across this because I've also been looking at some to_latex bugs and have a PR open: https://github.com/pandas-dev/pandas/pull/19910

As part of the discussion I also realised that what you've renamed ``_rebuild_multi_index()`` could be much cleaner. I had a go at this here https://github.com/tomneep/pandas/blob/to_latex_nan_fix_alternative/pandas/io/formats/format.py#L905 and think it really helps. I think it also addresses #19981  (as well as fixing a couple of other bugs). So maybe that is a potential option. 

I have a question about one of your new tests, ``test_to_latex_multiindex_non_string``, I'd expect the header to be `0 & 1 &    \\` but in your test you have `{} & 1 &    \\`. Am I missing something?

2018-03-08 10:27 UTC, shangyian commented
@jreback - I did a preliminary PR to move the different formatters to separate files here: https://github.com/pandas-dev/pandas/pull/20051. Let me know what you think.

2018-03-08 10:30 UTC, shangyian commented
@tomneep - Good catch on the test - not sure why I thought that made sense! As for the multi-indexing portion of the method, yeah, it makes sense to rework that to be clearer. I didn't change much from the original code when I pulled it into `_rebuild_multi_index`.

2018-03-14 11:02 UTC, jreback commented
ok let's rebase this and see where we are

2018-03-14 17:51 UTC, shangyian commented
Rebased and added some comments.

2018-03-14 22:10 UTC, shangyian commented
Not sure if best to do this here, but we discussed combining `get_level_lengths` and `_get_level_lengths` in `formats.style` and I just did that now.

2018-03-14 23:25 UTC, pep8speaks commented
Hello @shangyian! Thanks for updating the PR.



 - In the file [`pandas/io/formats/format.py`](https://github.com/pandas-dev/pandas/blob/e5546996bf4b8739bb55802f354112d6701e8069/pandas/io/formats/format.py), following are the PEP8 issues :

> [Line 1588:80](https://github.com/pandas-dev/pandas/blob/e5546996bf4b8739bb55802f354112d6701e8069/pandas/io/formats/format.py#L1588): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)





 - In the file [`pandas/io/formats/style.py`](https://github.com/pandas-dev/pandas/blob/e5546996bf4b8739bb55802f354112d6701e8069/pandas/io/formats/style.py), following are the PEP8 issues :

> [Line 203:80](https://github.com/pandas-dev/pandas/blob/e5546996bf4b8739bb55802f354112d6701e8069/pandas/io/formats/style.py#L203): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)

2018-07-28 14:39 UTC, jreback commented
can you rebase / fixup

2018-11-01 01:44 UTC, jreback commented
closing as stale. if you'd like to continue pls ping.

2018-11-01 01:44 UTC, closed without merging