Added 'displayed_only' option to 'read_html'
pandas-dev/pandas pull request #20047
Opened 2018-03-07 23:52 UTC by WillAyd

- [X] closes #20027
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

2018-03-07 23:56 UTC, WillAyd commented on pandas/tests/io/test_html.py
> +    @pytest.mark.parametrize("displayed_only,exp0,exp1", [
Blatant copy/paste of the method above. I was kind of surprise how few tests were shared between the parsers, so there's opportunity here to consolidate a lot of these tests into a base class but I figured that was better done comprehensively than trying to shimmy into this change

2018-03-08 05:52 UTC, jschendel commented on pandas/io/html.py
> +            tables = [x for x in tables if not (
Minor comment: I think you could make this a generator comprehension instead of a list comprehension.

2018-03-08 05:53 UTC, jschendel commented on pandas/io/html.py
> +                "display:none" in x.attrib.get('style', '').replace(' ', ''))]
same

2018-03-08 06:54 UTC, WillAyd commented on pandas/io/html.py
> +            tables = [x for x in tables if not (
Unfortunately I don't think that's possible (save further rework) as the `tables` variable could be iterated over more than once. This causes subsequent iterators to throw after the generator is exhausted the first time

2018-03-08 07:32 UTC, jschendel commented on pandas/io/html.py
> +            tables = [x for x in tables if not (
It looks like in this case there's just a single loop over `tables` before the newly constructed `result` list is returned, so there shouldn't be a possibility of multiple iterations here?  For the other instance of this further down in the code it looks like `tables` itself is returned, so an exhausted generator is a valid concern there.  Oops, missed that!

Probably best to just leave this as-is for consistency with the other method though, as I don't think converting to a generator will provide much of a benefit anyways.  Was more trying to be in line with some other cleaning related PRs I've noticed where the preference was to convert to generators where possible.

2018-03-08 11:45 UTC, jreback requested changes
does lxml / bs4 not have an option for this?

2018-03-08 11:45 UTC, jreback commented on pandas/io/html.py
> +                import re
import at the top

2018-03-08 16:29 UTC, WillAyd commented
I couldn't find anything on a google search, assumedly because these tools aren't concerned with rendering and don't have the concept of "displayed". LXML does have a `cssselect` statement that could potentially make this easier, but it requires `cssselect` to be installed and would break the consistency in how this is handled with the bs4 method

2018-03-08 17:13 UTC, pep8speaks commented
Hello @WillAyd! Thanks for updating the PR.

 - In the file [`pandas/io/html.py`](https://github.com/pandas-dev/pandas/blob/b1d0f91e766faa5bd916579a7a8fa081b0c60bab/pandas/io/html.py), following are the PEP8 issues :

> [Line 408:40](https://github.com/pandas-dev/pandas/blob/b1d0f91e766faa5bd916579a7a8fa081b0c60bab/pandas/io/html.py#L408): [E713](https://duckduckgo.com/?q=pep8%20E713) test for membership should be 'not in'

2018-03-09 10:59 UTC, jreback requested changes

2018-03-09 17:04 UTC, TomAugspurger commented
Changes look good. Did you open an issue for sharing tests between parsers?

2018-03-09 17:09 UTC, WillAyd commented
#20082

2018-03-10 01:53 UTC, jreback approved these changes

2018-03-10 01:53 UTC, merged

2018-03-10 01:53 UTC, jreback commented
thanks @WillAyd very nice as always! keep em coming!