TST: series/indexing tests parameterization + moving test methods
pandas-dev/pandas pull request #20059
Opened 2018-03-08 20:10 UTC by almaleksia

Parts 2 and 3 of #20014. 
- tests parameterization
- moving some tests from test_indexing.py to other files 
- test methods reordering in test_indexing.py

- [ ] closes #20014
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2018-03-09 11:18 UTC, jreback requested changes
very nice! just a couple of minor comments. ping on green.

2018-03-09 11:18 UTC, jreback commented on pandas/tests/series/indexing/test_boolean.py
> +    for arr in [np.array([item]), [item], (item,)]:
could add this to the parameterization, we typically would call this ``box: [lambda x: np.array([x]), lambda x: [x], lambda x: (x,)]``

2018-03-09 11:18 UTC, jreback commented on pandas/tests/series/indexing/test_boolean.py
> +        for arr in [np.array([item]), [item], (item,)]:
same as above, though would not be averse to testing both mask and where in the same function to make this simpler

2018-03-10 01:40 UTC, jreback approved these changes

2018-03-10 01:40 UTC, merged

2018-03-10 01:40 UTC, jreback commented
very nice @almaleksia !

2018-03-10 01:41 UTC, jreback commented
if you wanted to move the JOIN_TYPES to the top-level ``pandas/conftest.py`` (and make it a fixture),  and prob rename to join_types, would be *really* helpful. note that this will percolate to lots of other modules, mainly in pandas/tests/reshape where they are actually used.

2018-03-10 01:42 UTC, jreback commented
I *think* we have an issue about this (or at least about generally moving things like this to fixtures). Also would be great to split up pandas/tests/frame/test_indexing.py along the same lines as you did here :-D

2018-03-10 09:55 UTC, almaleksia commented
@jreback thanks! I can create separate PRs for joins and frame/test_indexing refactoring