Update the DatetimeIndex.normalize docstring
pandas-dev/pandas pull request #20094
Opened 2018-03-10 04:34 UTC by techytushar

Signed-off-by: Tushar Mittal <chiragmittal.mittal@gmail.com>

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [x] PR title is "DOC: update the <your-function-or-method> docstring"
- [x] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [x] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [x] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
################################################################################
################## Docstring (pandas.DatetimeIndex.normalize) ##################
################################################################################

Return DatetimeIndex with times converted to midnight.

When using DatetimeIndex, the time can be converted to midnight i.e.
00:00:00. This is useful in cases, when the time does not matter in
DataFrame. Length is unaltered.

Returns
-------
normalized : DatetimeIndex

See Also
--------
DatetimeIndex.floor : Floor the DatetimeIndex to the specified freq.
DatetimeIndex.ceil : Ceil the DatetimeIndex to the specified freq.
DatetimeIndex.round : Round the DatetimeIndex to the specified freq.

Examples
--------
>>> df = pd.DataFrame({'date':['2015-05-01 18:47:05.060000',
...                            '2014-05-01 18:47:05.110000']})
>>> df.date = pd.to_datetime(df.date)
>>> df.date[1]
Timestamp('2014-05-01 18:47:05.110000')
>>> df.date[1].normalize()
Timestamp('2014-05-01 00:00:00')

################################################################################
################################## Validation ##################################
################################################################################

Docstring for "pandas.DatetimeIndex.normalize" correct. :)
```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

Checklist for other PRs (remove this part if you are doing a PR for the pandas documentation sprint):

2018-03-10 09:31 UTC, IHackPy approved these changes
LGTM

2018-03-10 13:06 UTC, jreback requested changes

2018-03-10 13:06 UTC, jreback commented on pandas/core/indexes/datetimes.py
> +        00:00:00. This is useful in cases, when the time does not matter in
This useful in cases where the time does not matter (remove the in DataFrame). The length of the DatetimeIndex is unaltered.

2018-03-10 13:07 UTC, jreback requested changes

2018-03-10 13:07 UTC, jreback commented on pandas/core/indexes/datetimes.py
> +        ...                            '2014-05-01 18:47:05.110000']})
can you add another example with a tz.

2018-03-10 13:07 UTC, jreback commented on pandas/core/indexes/datetimes.py
> +        00:00:00. This is useful in cases, when the time does not matter in
maybe mention this does not affect tz's

2018-03-10 13:47 UTC, techytushar commented
@jreback required changes done, please review :grinning:

2018-03-10 14:30 UTC, jreback requested changes
small changes, otherwise lgtm.

2018-03-10 14:30 UTC, jreback commented on pandas/core/indexes/datetimes.py
> +        Length is unaltered. The timezones are unaffected. If the frequency
I would remove the last sentence. freq is actually re-inferred here, so this is misleading.

2018-03-10 14:35 UTC, marielen requested changes

2018-03-10 14:35 UTC, marielen commented on pandas/core/indexes/datetimes.py
> +        Return DatetimeIndex with times converted to midnight.
Please, make a simpler description. I suggest `Convert times to midnight`.

2018-03-10 14:40 UTC, techytushar commented
done!

2018-03-10 14:40 UTC, jreback approved these changes

2018-03-15 14:28 UTC, jorisvandenbossche approved these changes
Looks good! 

I made a few edits to make it more generic for both DatetimeIndex and Series.dt (they share the docstring)

2018-03-15 14:28 UTC, merged