FIX: add support for desc order when ranking infs with nans #19538
pandas-dev/pandas pull request #20091
Opened 2018-03-10 02:19 UTC by peterpanmj

Please include the output of the validation script below between the "```" ticks:

```
################################################################################
################ Docstring (pandas._libs.algos.rank_1d_object)  ################
################################################################################

Fast NaN-friendly version of scipy.stats.rankdata

################################################################################
################################## Validation ##################################
################################################################################

Errors found:
        Summary does not end with dot
        No extended summary found
        No returns section found
        See Also section not found
        No examples section found
(pandas_dev)

```

Checklist for other PRs (remove this part if you are doing a PR for the pandas documentation sprint):

- [x] closes #19538
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-03-10 02:19 UTC, pep8speaks commented
Hello @peterpanmj! Thanks for submitting the PR.

 - In the file [`pandas/tests/series/test_rank.py`](https://github.com/pandas-dev/pandas/blob/5eb57b03b1821bb820f8adebfd3cadc0eee85f3c/pandas/tests/series/test_rank.py), following are the PEP8 issues :

> [Line 267:80](https://github.com/pandas-dev/pandas/blob/5eb57b03b1821bb820f8adebfd3cadc0eee85f3c/pandas/tests/series/test_rank.py#L267): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 269:80](https://github.com/pandas-dev/pandas/blob/5eb57b03b1821bb820f8adebfd3cadc0eee85f3c/pandas/tests/series/test_rank.py#L269): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)

2018-03-10 13:04 UTC, jreback requested changes
can you add a whatsnew note

2018-03-10 13:04 UTC, jreback commented on pandas/tests/series/test_rank.py
> +        def _check(s, expected, method='average', na_option='keep',
can you parametrize this test

2018-03-10 13:04 UTC, jreback commented on pandas/tests/series/test_rank.py
>      def test_rank_methods_series(self):
ca you change this to use the ``@td.skip_if_no_scipy`` decorator instead

2018-03-10 13:04 UTC, jreback commented
can you add the simple example from the issue as a test as well.

2018-03-13 02:28 UTC, peterpanmj commented
> The command "ci/lint.sh" exited with 1.

The Travis CI build failed after some modification on "pandas\tests\series\test_rank.py". I have no idea what is the cause.

2018-03-13 10:29 UTC, jreback commented
somehow lots of commits go there. merge in master and push again.

2018-03-14 10:54 UTC, jreback requested changes

2018-03-14 10:54 UTC, jreback commented on pandas/tests/series/test_rank.py
> +        def _check(s, method, na_option, ascending):
can you inline these below

2018-03-14 10:54 UTC, jreback commented on pandas/tests/series/test_rank.py
> +        iseries = Series([1, np.nan, np.inf, -np.inf, 25])
can you add the issue number

2018-03-16 08:25 UTC, peterpanmj commented
lint.sh gives error. Don't know why.

2018-03-16 12:49 UTC, TomAugspurger commented on pandas/tests/series/test_rank.py
> +                    'average': ([2, 2, 2], [5, 5, 5], [8, 8, 8]),
These should start four spaces to the right of the `e` in `exp_ranks`.

2018-03-16 12:50 UTC, TomAugspurger reviewed
Added comments on the linking errors in https://travis-ci.org/pandas-dev/pandas/jobs/353646265#L3004

Run `flake8 pandas/tests/series/test_rank.py` locally before pushing to validate your fixes.

2018-03-16 12:50 UTC, TomAugspurger commented on pandas/tests/series/test_rank.py
> +                    'average': ([2, 2, 2], [5, 5, 5], [8, 8, 8]),
Likewise with each one below it.

2018-03-16 12:50 UTC, TomAugspurger commented on pandas/tests/series/test_rank.py
> +        #GH 19538
Space after `#`

2018-03-16 12:50 UTC, TomAugspurger commented on pandas/tests/series/test_rank.py
> +        #check descending ranking when mix nans and infs
Space after `#`

2018-03-25 14:01 UTC, jreback commented
@WillAyd if you'd have a look

2018-03-25 14:02 UTC, jreback approved these changes

2018-03-25 16:30 UTC, WillAyd commented
@peterpanmj nice work - does this work for GroupBy ranking the same way?

2018-03-27 12:28 UTC, peterpanmj commented
@WillAyd  As long as rank_1d_{dtype} is called, it is fine, but group by rank is still broken.
```
In [51]: df = pd.DataFrame([1, np.nan, np.inf, -np.inf, 25])

In [52]: df['key'] = 'foo'

In [53]: df.groupby("key").rank()      # not working properly for infinity
Out[53]:
     0
0  2.0
1  NaN
2  NaN
3  1.0
4  3.0

In [54]: df.rank()     # this is ok
Out[54]:
     0  key
0  2.0  3.0
1  NaN  3.0
2  4.0  3.0
3  1.0  3.0
4  3.0  3.0

In [55]: df.groupby("key").apply(lambda x:x.rank())   # this is also ok
Out[55]:
     0  key
0  2.0  3.0
1  NaN  3.0
2  4.0  3.0
3  1.0  3.0
4  3.0  3.0

```

2018-03-27 17:43 UTC, WillAyd commented
Do you want to try and tackle the groupby implementation as part of this? I've linked the relevant function below - it isn't that drastically different from the algos rank implementation

https://github.com/pandas-dev/pandas/blob/766a4800b4d9b7e847577b74b24128fcda8eeb55/pandas/_libs/groupby_helper.pxi.in#L415

2018-03-29 12:53 UTC, peterpanmj commented
I will try but it should take a lot of efforts. 
I don't under stand why _out_ has ndim=2 ? What is the dtype of _labels_ ?

2018-03-29 14:57 UTC, WillAyd commented
Labels are int64 - each unique grouping will have it's own label. out has `ndim=2` to match the other Cython call signatures, but you'll see in this that only the first dimension ever gets written to (I think this will be cleaned up in the future).

2018-03-30 20:27 UTC, jreback commented
can do the groupby fixes in another PR :> @peterpanmj or @WillAyd can you open an issue?

2018-03-30 20:35 UTC, merged

2018-03-30 20:37 UTC, jreback commented
thanks @peterpanmj