Update
pandas-dev/pandas pull request #20106
Opened 2018-03-10 10:41 UTC by radovankavicky

Update

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [ ] PR title is "DOC: update the <your-function-or-method> docstring"
- [ ] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [ ] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [ ] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
# paste output of "scripts/validate_docstrings.py <your-function-or-method>" here
# between the "```" (remove this comment, but keep the "```")

```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

Checklist for other PRs (remove this part if you are doing a PR for the pandas documentation sprint):

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-03-10 10:41 UTC, pep8speaks commented
Hello @radovankavicky! Thanks for submitting the PR.

 - In the file [`pandas/io/pickle.py`](https://github.com/pandas-dev/pandas/blob/2ffc1ecc1ee9928be00bd57d70daf04d2008cf83/pandas/io/pickle.py), following are the PEP8 issues :

> [Line 32:1](https://github.com/pandas-dev/pandas/blob/2ffc1ecc1ee9928be00bd57d70daf04d2008cf83/pandas/io/pickle.py#L32): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2018-03-10 13:37 UTC, jreback requested changes

2018-03-10 13:37 UTC, jreback commented on pandas/io/pickle.py
> +
extra whitespace

2018-03-10 13:37 UTC, jreback commented on pandas/io/pickle.py
>          .. versionadded:: 0.21.0
is there a generic link here?

2018-03-12 21:35 UTC, jorisvandenbossche commented
This is being updated by https://github.com/pandas-dev/pandas/pull/20253 as well, so therefore closing this one. @radovankavicky I hope there was no error in the docstring assignment, in that case sorry!

2018-03-12 21:35 UTC, closed without merging