"DOC" update the pandas.Series.dropna docstring by Ankara Chapter
pandas-dev/pandas pull request #20116
Opened 2018-03-10 12:39 UTC by Neuroscitechie

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [ x] PR title is "DOC: update the <your-function-or-method> docstring"
- [x ] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [ x] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ x] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [x ] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
# paste output of "scripts/validate_docstrings.py <your-function-or-method>" here
# between the "```" (remove this comment, but keep the "```")

```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

Checklist for other PRs (remove this part if you are doing a PR for the pandas documentation sprint):

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-03-10 12:39 UTC, pep8speaks commented
Hello @Neuroscitechie! Thanks for submitting the PR.

 - In the file [`pandas/core/series.py`](https://github.com/pandas-dev/pandas/blob/6d067f22a2d4bf6264ed7df0fa9b7c22afe6b043/pandas/core/series.py), following are the PEP8 issues :

> [Line 2996:80](https://github.com/pandas-dev/pandas/blob/6d067f22a2d4bf6264ed7df0fa9b7c22afe6b043/pandas/core/series.py#L2996): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

2018-03-10 12:48 UTC, TomAugspurger commented
Hmm can you check to see if your editor changed the newline mode of the document? The diff should just be the lines you changed, not the entire file.

Ping me in the chat if you need help figuring it out.

2018-03-10 13:45 UTC, Neuroscitechie commented
I collected edits from everyone and uploaded the file instead of updating the lines only

2018-03-10 14:55 UTC, jreback requested changes
something when wrong here as the whole file is changed.

2018-03-14 15:26 UTC, TomAugspurger reviewed
Pushed a commit fixing the line endings.

@Neuroscitechie there may be a setting in your editor handling line endings. We want `LF`, not `CRLF`.

https://help.github.com/articles/dealing-with-line-endings/#platform-windows

2018-03-14 15:26 UTC, TomAugspurger commented on pandas/core/series.py
> +        In case of missing data, any or all values can be used reciprocally.
Not sure what you mean by "reciprocally". I think this can section can be removed.

2018-03-14 15:26 UTC, TomAugspurger commented on pandas/core/series.py
> +            Pass tuple or list to drop on multiple axes.
This method is series-specific, so note that \`axis\`  is included for compatability with `DataFrame.dropna`.

2018-03-14 15:26 UTC, TomAugspurger commented on pandas/core/series.py
> +        kwargs : {'any', 'all'}
Format as

```
**kwargs
    For compatibility with `DataFrame.dropna`. No additional arguments are used.
```

2018-03-14 15:26 UTC, TomAugspurger commented on pandas/core/series.py
> +        core.series._sanitize_array : To understand why is array one-dimensional.
Remove this, it's a private method.

Add

```
pandas.isna : Top-level NA detection method.
Series.isna : Detect missing values.
Series.fillna : Fill missing values.
DataFrame.dropna : Same method for DataFrames.
```

2018-03-14 15:26 UTC, TomAugspurger commented on pandas/core/series.py
> +        >>> s = pd.Series([None,2,None,0,3])
PEP8: space after comma.

2018-03-14 15:26 UTC, TomAugspurger commented on pandas/core/series.py
> +        To omit these NaN values, use dropna() function
Can remove this. Just show the example.

2018-03-14 15:26 UTC, TomAugspurger commented on pandas/core/series.py
> +        >>> s.dropna(axis=0, inplace=False, how='any')
Remove False and `how='any'`. Just show the defaults.

2018-03-14 15:26 UTC, TomAugspurger commented on pandas/core/series.py
>          """
Show that `s` is unmodified and then show an example with `inplace=True` that returns None and modifies `s` inplace.

2018-03-14 19:40 UTC, jorisvandenbossche commented
We seem to have a conflicting PR: https://github.com/pandas-dev/pandas/pull/20204 (that one is doing both DataFrame and Series dropna)

2018-03-16 20:48 UTC, TomAugspurger commented
Closing in favor of #20204.

2018-03-16 20:48 UTC, closed without merging