DOC: update the MultiIndex docstring
pandas-dev/pandas pull request #20124
Opened 2018-03-10 13:12 UTC by jesrael

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [ ] PR title is "DOC: update the <your-function-or-method> docstring"
- [ ] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [ ] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [ ] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
# paste output of "scripts/validate_docstrings.py <your-function-or-method>" here
# between the "```" (remove this comment, but keep the "```")

```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

Checklist for other PRs (remove this part if you are doing a PR for the pandas documentation sprint):

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-03-10 13:12 UTC, pep8speaks commented
Hello @jesrael! Thanks for submitting the PR.

 - In the file [`pandas/core/indexes/multi.py`](https://github.com/pandas-dev/pandas/blob/0b7cbc2f6f60e3ad6263f4860d9e8f8ea63242d6/pandas/core/indexes/multi.py), following are the PEP8 issues :

> [Line 1163:29](https://github.com/pandas-dev/pandas/blob/0b7cbc2f6f60e3ad6263f4860d9e8f8ea63242d6/pandas/core/indexes/multi.py#L1163): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

2018-03-10 13:15 UTC, TomAugspurger commented
@jesrael do you need help working on this docstring?

2018-03-10 15:34 UTC, jreback requested changes
this is not going to pass linting

2018-03-15 21:11 UTC, TomAugspurger commented
@jesrael let us know if you want to continue working on this.

2018-03-15 21:11 UTC, closed without merging