DOC: update and seperate the Series.drop and Dataframe.drop docstring
pandas-dev/pandas pull request #20120
Opened 2018-03-10 12:48 UTC by JennaVergeynst

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [] PR title is "DOC: update the <your-function-or-method> docstring"
- [X] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [X] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [X] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
Errors found:
Errors in parameters section
Parameter "columns" description should finish with "."
```

This error is caused by `.. versionadded:: 0.21.0`, which needs to stay in place.

2018-03-10 12:48 UTC, pep8speaks commented
Hello @JennaVergeynst! Thanks for submitting the PR.

 - In the file [`pandas/core/frame.py`](https://github.com/pandas-dev/pandas/blob/3b5d1019796f834e2a2af1b272e880b66c13be70/pandas/core/frame.py), following are the PEP8 issues :

> [Line 3039:22](https://github.com/pandas-dev/pandas/blob/3b5d1019796f834e2a2af1b272e880b66c13be70/pandas/core/frame.py#L3039): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 3043:80](https://github.com/pandas-dev/pandas/blob/3b5d1019796f834e2a2af1b272e880b66c13be70/pandas/core/frame.py#L3043): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 3078:80](https://github.com/pandas-dev/pandas/blob/3b5d1019796f834e2a2af1b272e880b66c13be70/pandas/core/frame.py#L3078): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 3123:80](https://github.com/pandas-dev/pandas/blob/3b5d1019796f834e2a2af1b272e880b66c13be70/pandas/core/frame.py#L3123): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 3126:9](https://github.com/pandas-dev/pandas/blob/3b5d1019796f834e2a2af1b272e880b66c13be70/pandas/core/frame.py#L3126): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 3126:9](https://github.com/pandas-dev/pandas/blob/3b5d1019796f834e2a2af1b272e880b66c13be70/pandas/core/frame.py#L3126): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 3147:9](https://github.com/pandas-dev/pandas/blob/3b5d1019796f834e2a2af1b272e880b66c13be70/pandas/core/frame.py#L3147): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 3147:9](https://github.com/pandas-dev/pandas/blob/3b5d1019796f834e2a2af1b272e880b66c13be70/pandas/core/frame.py#L3147): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs

 - In the file [`pandas/core/generic.py`](https://github.com/pandas-dev/pandas/blob/3b5d1019796f834e2a2af1b272e880b66c13be70/pandas/core/generic.py), following are the PEP8 issues :

> [Line 2803:1](https://github.com/pandas-dev/pandas/blob/3b5d1019796f834e2a2af1b272e880b66c13be70/pandas/core/generic.py#L2803): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

 - In the file [`pandas/core/series.py`](https://github.com/pandas-dev/pandas/blob/3b5d1019796f834e2a2af1b272e880b66c13be70/pandas/core/series.py), following are the PEP8 issues :

> [Line 2664:17](https://github.com/pandas-dev/pandas/blob/3b5d1019796f834e2a2af1b272e880b66c13be70/pandas/core/series.py#L2664): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

2018-03-10 14:42 UTC, stijnvanhoey requested changes

2018-03-10 14:42 UTC, stijnvanhoey commented on pandas/core/frame.py
> +                     self).drop(labels=labels, axis=axis, index=index,
indendation is a bit strange here. I would set the `self` on the same line

2018-03-10 14:42 UTC, stijnvanhoey commented on pandas/core/frame.py
> +            Redundant for application on Series, but index can be used instead
As this is now in the `data.frame` section, this is probably not redundant?

2018-03-10 14:42 UTC, stijnvanhoey commented on pandas/core/frame.py
> +            Redundant for application on Series, but index can be used instead
As this is now in the `data.frame` section, this is probably not redundant?

2018-03-10 14:42 UTC, stijnvanhoey commented on pandas/core/frame.py
> +            For MultiIndex.
Is it useful to make this more detailed? e.g. `Level for which the labels will be removed`

2018-03-10 14:42 UTC, stijnvanhoey commented on pandas/core/frame.py
> +        dropped : type of caller
In the generic, this was the same as the caller, but here we know it is a dataframe

2018-03-10 14:42 UTC, stijnvanhoey commented on pandas/core/frame.py
> +        >>> df.drop(index='cow',columns='small')
missing space after `, `

2018-03-10 14:42 UTC, stijnvanhoey commented on pandas/core/frame.py
> +        >>> midx = pd.MultiIndex(levels=[['lama','cow','falcon'],
missing spaces after `,`

2018-03-10 14:42 UTC, stijnvanhoey commented on pandas/core/series.py
> +        dropped : type of caller
pandas.Series

2018-03-10 14:59 UTC, stijnvanhoey commented on pandas/core/frame.py
> +            columns (1 / 'columns').
I would write (0 or 'index') and  columns (1 or 'columns')

2018-03-10 15:04 UTC, stijnvanhoey commented on pandas/core/frame.py
> +        axis : int or axis name, default 0
cfr. gitter discussion: `axis : {0 or 'index', 1 or 'columns'}, default 0`

2018-03-10 15:06 UTC, jreback requested changes

2018-03-10 15:06 UTC, jreback commented on pandas/core/frame.py
> +            removed, optionally only considering certain columns
reference DataFrame.loc (first) as well as this is an indexing operations

2018-03-10 15:06 UTC, jreback commented on pandas/core/frame.py
> +        Drop columns and/or rows of MultiIndex
MultiIndexed DataFrame

2018-03-10 15:06 UTC, jreback commented on pandas/core/frame.py
> +        lama 	speed 	45.0 	30.0
I don't think this is layed out  correctly, a copy-paste issue?

2018-03-10 15:06 UTC, jreback commented on pandas/core/frame.py
> +        ...                              [0, 1, 2, 0, 1, 2, 0, 1, 2]])
I would make this example a bit simpler, maybe using integers for the value column (and order them, e.g. use ``np.arange(len(midx))`` to create (big/small)

2018-03-10 15:06 UTC, jreback requested changes

2018-03-10 15:06 UTC, jreback commented on pandas/core/frame.py
> +            removed, optionally only considering certain columns
also Series.drop

2018-03-12 22:01 UTC, jorisvandenbossche approved these changes

2018-03-13 16:05 UTC, merged

2018-03-13 16:06 UTC, jorisvandenbossche commented
@JennaVergeynst Thanks for the PR!