DOC: update the pandas.IntervalIndex docstring
pandas-dev/pandas pull request #20188
Opened 2018-03-10 15:54 UTC by verakai

Docstring assignated to the Buenos Aires, Argentina chapter.

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [x] PR title is "DOC: update the <your-function-or-method> docstring"
- [x] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [x] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [x] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```

################################################################################
####################### Docstring (pandas.IntervalIndex) #######################
################################################################################

Immutable Index implementing an ordered, sliceable set. IntervalIndex
represents an Index of Interval objects that are all closed on the same
side.

.. versionadded:: 0.20.0

.. warning::

   The indexing behaviors are provisional and may change in
   a future version of pandas.

Parameters
----------
data : array-Like (1-dimensional)
    Array-like containing Interval objects from which to build the
    IntervalIndex.
closed : {'left', 'right', 'both', 'neither'}, default 'right'
    Whether the intervals are closed on the left-side, right-side, both or
    neither.
dtype : dtype or None, default None
    If None, dtype will be inferred.
copy : boolean, default False
    Copy the meta-data.
name : object, optional
    Name to be stored in the index.
fastpath : boolean, default False
    Create IntervalIndex without verifying integrity.
verify_integrity : boolean, default True
    Verify that the IntervalIndex is valid.
    
    ..versionadded:: 0.23.0.

Attributes
----------
left
right
closed
mid
length
values
is_non_overlapping_monotonic

Methods
-------
from_arrays
from_tuples
from_breaks
contains

Examples
---------
A new ``IntervalIndex`` is typically constructed using
:func:`interval_range`:

>>> pd.interval_range(start=0, end=5)
IntervalIndex([(0, 1], (1, 2], (2, 3], (3, 4], (4, 5]]
              closed='right', dtype='interval[int64]')

It may also be constructed using one of the constructor
methods: :meth:`IntervalIndex.from_arrays`,
:meth:`IntervalIndex.from_breaks`, and :meth:`IntervalIndex.from_tuples`.

See further examples in the doc strings of ``interval_range`` and the
mentioned constructor methods.

Notes
------
See the `user guide
<http://pandas.pydata.org/pandas-docs/stable/advanced.html#intervalindex>`_
for more.

See Also
--------
Index : The base pandas Index type.
Interval : A bounded slice-like interval; the elements of an IntervalIndex.
qcut : Quantile-based discretization function.
cut : Return indices of half-open bins to which each value of x belongs.
interval_range : Function to create a fixed frequency IntervalIndex.

################################################################################
################################## Validation ##################################
################################################################################

Errors found:
	No returns section found
Checking `class` definition so nothing to return 
```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

2018-03-10 15:54 UTC, pep8speaks commented
Hello @verakai! Thanks for submitting the PR.

 - In the file [`pandas/core/indexes/interval.py`](https://github.com/pandas-dev/pandas/blob/7c8dcee08cb4eadb73f6842700de4242be2c0b64/pandas/core/indexes/interval.py), following are the PEP8 issues :

> [Line 161:1](https://github.com/pandas-dev/pandas/blob/7c8dcee08cb4eadb73f6842700de4242be2c0b64/pandas/core/indexes/interval.py#L161): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2018-03-10 22:30 UTC, jreback requested changes

2018-03-10 22:30 UTC, jreback commented on pandas/core/indexes/interval.py
> +    data : array-Like (1-dimensional)
array-like is correct

2018-03-10 22:30 UTC, jreback commented on pandas/core/indexes/interval.py
> +    dtype : dtype or None, default None
numpy dtype, optional

2018-03-10 22:30 UTC, jreback commented on pandas/core/indexes/interval.py
> +    copy : boolean, default False
boolean -> bool

2018-03-10 22:30 UTC, jreback commented on pandas/core/indexes/interval.py
> +        Copy the meta-data.
this refers to copying of the input data

2018-03-10 22:30 UTC, jreback commented
cc @jschendel if you'd have a look

2018-03-11 01:40 UTC, jschendel commented
Looks like these changes were also included in #20224, and there were a few related comments there.

2018-03-11 01:43 UTC, jschendel commented on pandas/core/indexes/interval.py
>      closed : {'left', 'right', 'both', 'neither'}, default 'right'
Can you swap the order of `'left'` and `'right'` here (and on the line below), so the default value appears first.  I think some of the other `Interval` related PRs from the sprint did the same thing, and it'd be nice to make this consistent.

2018-10-14 22:35 UTC, jschendel commented
Closing in favor of #23157

2018-10-14 22:35 UTC, closed without merging