DOC: Update the DatetimeIndex.floor docstring
pandas-dev/pandas pull request #20182
Opened 2018-03-10 15:42 UTC by techytushar

Signed-off-by: Tushar Mittal <chiragmittal.mittal@gmail.com>

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [x] PR title is "DOC: update the <your-function-or-method> docstring"
- [x] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [x] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [x] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
################################################################################
#################### Docstring (pandas.DatetimeIndex.floor) ####################
################################################################################

Floor the DatetimeIndex to the specified freq.

All the available freq can be found in the following link
in the offset-aliases section:
http://pandas.pydata.org/pandas-docs/stable/timeseries.html

Parameters
----------
freq : str
    Valid freq string.

Returns
-------
DatetimeIndex

See Also
--------
DatetimeIndex.ceil : Ceil the DatetimeIndex to the specified freq.
DatetimeIndex.round : Round the DatetimeIndex to the specified freq.

Examples
--------
>>> df = pd.DatetimeIndex(start='2014-08-01 09:23:41.321211',
...                       freq = 'H', periods = 3)
>>> df
DatetimeIndex(['2014-08-01 09:23:41.321211',
               '2014-08-01 10:23:41.321211',
               '2014-08-01 11:23:41.321211'],
                dtype='datetime64[ns]', freq='H')
>>> df.floor('H')
DatetimeIndex(['2014-08-01 09:00:00',
               '2014-08-01 10:00:00',
               '2014-08-01 11:00:00'],
                dtype='datetime64[ns]', freq=None)
>>> df.floor('D')
DatetimeIndex(['2014-08-01', '2014-08-01', '2014-08-01'],
               dtype='datetime64[ns]', freq=None)
>>> df.floor('min')
DatetimeIndex(['2014-08-01 09:23:00',
               '2014-08-01 10:23:00',
               '2014-08-01 11:23:00'],
               dtype='datetime64[ns]', freq=None)

################################################################################
################################## Validation ##################################
################################################################################

Docstring for "pandas.DatetimeIndex.floor" correct. :)
```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

2018-03-10 15:46 UTC, techytushar commented
IMHO, since there was a common docstring for `ceil`, `floor`, and `round`, it was quite difficult to make it descriptive so i had to separate out the docstring for `floor`, same can be done for `ceil` and `round`. :slightly_smiling_face:

2018-03-10 16:02 UTC, kynan requested changes

2018-03-10 16:02 UTC, kynan commented on pandas/core/indexes/datetimelike.py
> +        Floor the DatetimeIndex to the specified freq.
Either spell it out as frequency or mark it up as a parameter name: ```freq```

2018-03-10 16:02 UTC, kynan commented on pandas/core/indexes/datetimelike.py
> +        All the available freq can be found in the following link
frequency aliases

2018-03-10 16:02 UTC, kynan commented on pandas/core/indexes/datetimelike.py
> +        All the available freq can be found in the following link
at the following link

2018-03-10 16:02 UTC, kynan commented on pandas/core/indexes/datetimelike.py
> +    @Appender(_floor_doc)
Since you're no longer using a shared docstring, don't use the `Appender`. Instead add the docstring to the method directly.

2018-03-10 16:02 UTC, kynan commented on pandas/core/indexes/datetimelike.py
> +        http://pandas.pydata.org/pandas-docs/stable/timeseries.html
Consider using an rST reference and directly link to the section: http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases

2018-03-10 16:02 UTC, kynan commented on pandas/core/indexes/datetimelike.py
> +        freq : str
Can also be an object: https://pandas.pydata.org/pandas-docs/stable/timeseries.html#dateoffset-objects

2018-03-10 16:02 UTC, kynan commented on pandas/core/indexes/datetimelike.py
> +            Valid freq string.
String or object  specifying the frequency to round down to.

2018-03-10 16:48 UTC, pep8speaks commented
Hello @techytushar! Thanks for updating the PR.

 - In the file [`pandas/core/indexes/datetimelike.py`](https://github.com/pandas-dev/pandas/blob/c41b8764d7c949d7001d89919fdce3e54aa34448/pandas/core/indexes/datetimelike.py), following are the PEP8 issues :

> [Line 127:1](https://github.com/pandas-dev/pandas/blob/c41b8764d7c949d7001d89919fdce3e54aa34448/pandas/core/indexes/datetimelike.py#L127): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2018-03-10 16:51 UTC, techytushar commented
@kynan thank you for the review, i have made the required changes. :slightly_smiling_face:

2018-03-11 10:55 UTC, techytushar commented
@jreback please review! :slightly_smiling_face:

2018-07-08 15:58 UTC, jreback commented
@pandas-dev/pandas-core needs a rebase

2018-07-08 21:05 UTC, gfyoung commented
@jreback : Do we need this PR anymore?

https://pandas-docs.github.io/pandas-docs-travis/generated/pandas.DatetimeIndex.floor.html

2018-07-08 22:07 UTC, jreback commented
yeah the floor docs are now in pandas/core/indexes/datetimelike.py. let's close but if you think should add to those examples, pls do a PR (or pls create a new issue for that).

2018-07-08 22:07 UTC, closed without merging