DOC: update the api.types.is_number docstring
pandas-dev/pandas pull request #20196
Opened 2018-03-10 16:27 UTC by tapumar

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [X] PR title is "DOC: update the <your-function-or-method> docstring"
- [X] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [X] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [X] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
Docstring for "pandas.core.dtypes.inference.is_number" correct. :)
```

2018-03-10 17:11 UTC, jreback requested changes

2018-03-10 17:11 UTC, jreback commented on pandas/core/dtypes/inference.py
> +    Booleans are valid because they are int subclass.
can you put this in Notes

2018-03-10 17:11 UTC, jreback commented on pandas/core/dtypes/inference.py
> +    >>> pd.api.types.is_number(False)
could also add a comment here instead

2018-03-11 15:44 UTC, tapumar commented
Changes done :)

2018-03-17 12:23 UTC, jorisvandenbossche approved these changes
Looks good, thanks!

2018-03-17 12:24 UTC, merged