DOC: Update the DataFrame.join() docstring
pandas-dev/pandas pull request #20195
Opened 2018-03-10 16:16 UTC by kantologist

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [x] PR title is "DOC: update the <your-function-or-method> docstring"
- [x] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [x] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [x] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
################################################################################
###################### Docstring (pandas.DataFrame.join)  ######################
################################################################################

Join columns with other DataFrame either on index or a key
column.

Efficiently Join multiple DataFrame objects by index at once by
passing a list.

Parameters
----------
other : DataFrame, Series with name field set, or list of DataFrame
    Index should be similar to one of the columns in this one. If a
    Series is passed, its name attribute must be set, and that will be
    used as the column name in the resulting joined DataFrame.
on : name, tuple/list of names, or array-like
    Column or index level name(s) in the caller to join on the index
    in `other`, otherwise joins index-on-index. If multiple
    values given, the `other` DataFrame must have a MultiIndex. Can
    pass an array as the join key if it is not already contained in
    the calling DataFrame. Like an Excel VLOOKUP operation.
how : {'left', 'right', 'outer', 'inner'}, default: 'left'
    How to handle the operation of the two objects.

    * left: use calling frame's index (or column if on is specified).
    * right: use other frame's index.
    * outer: form union of calling frame's index (or column if on is
      specified) with other frame's index, and sort it
      lexicographically.
    * inner: form intersection of calling frame's index (or column if
      on is specified) with other frame's index, preserving the order
      of the calling's one.
lsuffix : string
    Suffix to use from left frame's overlapping columns.
rsuffix : string
    Suffix to use from right frame's overlapping columns.
sort : boolean, default False
    Order result DataFrame lexicographically by the join key. If False,
    the order of the join key depends on the join type (how keyword).

Notes
-----
The on, lsuffix, and rsuffix options are not supported when passing
a list of DataFrame objects.

Support for specifying index levels as the `on` parameter was added
in version 0.23.0.

Examples
--------
>>> caller = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3', 'A4', 'A5'],
...                      'key': ['K0', 'K1', 'K2', 'K3', 'K4', 'K5']})

>>> caller
    A key
0  A0  K0
1  A1  K1
2  A2  K2
3  A3  K3
4  A4  K4
5  A5  K5

>>> other = pd.DataFrame({'B': ['B0', 'B1', 'B2'],
...                       'key': ['K0', 'K1', 'K2']})

>>> other
    B key
0  B0  K0
1  B1  K1
2  B2  K2

Join DataFrames using their indexes.

>>> caller.join(other, lsuffix='_caller', rsuffix='_other')
    A key_caller    B key_other
0  A0         K0   B0        K0
1  A1         K1   B1        K1
2  A2         K2   B2        K2
3  A3         K3  NaN       NaN
4  A4         K4  NaN       NaN
5  A5         K5  NaN       NaN

If we want to join using the key columns, we need to set key to be
the index in both caller and other. The joined DataFrame will have
key as its index.

>>> caller.set_index('key').join(other.set_index('key'))
  A    B
key
K0   A0   B0
K1   A1   B1
K2   A2   B2
K3   A3  NaN
K4   A4  NaN
K5   A5  NaN

Another option to join using the key columns is to use the on
parameter. DataFrame.join always uses other's index but we can use any
column in the caller. This method preserves the original caller's
index in the result.

>>> caller.join(other.set_index('key'), on='key')
    A key    B
0  A0  K0   B0
1  A1  K1   B1
2  A2  K2   B2
3  A3  K3  NaN
4  A4  K4  NaN
5  A5  K5  NaN

See also
--------
DataFrame.merge : For column(s)-on-columns(s) operations

Returns
-------
joined : DataFrame

################################################################################
################################## Validation ##################################
################################################################################

Docstring for "pandas.DataFrame.join" correct. :)
```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

2018-03-10 17:01 UTC, WillAyd commented on pandas/core/frame.py
>          on : name, tuple/list of names, or array-like
The types could use a clean up here. Something like:

`str, list of str, tuple of (str,), or array-like`

2018-03-10 17:02 UTC, WillAyd commented on pandas/core/frame.py
>          other : DataFrame, Series with name field set, or list of DataFrame
Without trying to do to much, perhaps this line should just be `DataFrame, Series or list of DataFrame`. The detail around the name being set is in the comment below, and could maybe be reinforced in the `Notes` section

2018-03-10 17:03 UTC, WillAyd commented on pandas/core/frame.py
>              Column or index level name(s) in the caller to join on the index
Can you think of any better ways to word this?

2018-03-10 17:05 UTC, WillAyd commented on pandas/core/frame.py
> +            * left: use calling frame's index (or column if on is specified).
Understood why you did this, but generally you don't put periods at the end of bullet points

2018-03-10 17:07 UTC, WillAyd commented on pandas/core/frame.py
>          See also
Capitalize "Also"

2018-03-10 17:07 UTC, WillAyd requested changes
Noted a few improvements in various comments

2018-03-10 17:10 UTC, jreback requested changes

2018-03-10 17:10 UTC, jreback commented on pandas/core/frame.py
> +        Join columns with other DataFrame either on index or a key
on the index or a key column. might be too long though.

2018-03-10 17:10 UTC, jreback commented on pandas/core/frame.py
>          passing a list.
passing a list of DataFrames

2018-03-10 17:10 UTC, jreback commented on pandas/core/frame.py
> +        ...                      'key': ['K0', 'K1', 'K2', 'K3', 'K4', 'K5']})
the original formatting was ok here

2018-03-10 17:10 UTC, jreback commented on pandas/core/frame.py
> +          A    B
the column headers should be lined up

2018-03-10 17:10 UTC, jreback commented on pandas/core/frame.py
> +            A key    B
is this how it renders? I *think* there should be another space before the entire column of key

2018-03-11 13:08 UTC, jreback requested changes

2018-03-11 13:08 UTC, jreback commented on pandas/core/frame.py
> +        Join columns with other DataFrame either on a key column.
Join with other Dataframe on the index or a key column.

2018-03-11 13:08 UTC, jreback commented on pandas/core/frame.py
> +        Efficiently Join multiple DataFrame objects by index at once by
should be in the Notes section

2018-03-11 13:08 UTC, jreback commented on pandas/core/frame.py
> +        other : DataFrame, Series, or list of DataFrame
DataFrames

2018-03-11 13:08 UTC, jreback commented on pandas/core/frame.py
> +            it would be used as the name of the appended
appended -> added

2018-03-11 13:08 UTC, jreback commented on pandas/core/frame.py
> +        If a Series is used as other parameter it must be with name field set.
is must have the name attribute set.

2018-03-11 13:08 UTC, jreback commented on pandas/core/frame.py
> -        ...                        'A': ['A0', 'A1', 'A2', 'A3', 'A4', 'A5']})
was ok before

2018-03-11 13:08 UTC, jreback commented on pandas/core/frame.py
> +          key   A
was ok before

2018-03-11 13:08 UTC, jreback commented on pandas/core/frame.py
> -        2  B2  K2
same

2018-03-11 13:08 UTC, jreback commented on pandas/core/frame.py
> -            2  A2  K2   B2
leave all of these examples alone, they are fine

2018-03-14 08:17 UTC, kantologist commented
I have made the changes. Waiting for reviews.

2018-07-22 00:44 UTC, datapythonista commented
@kantologist can you please restore the original examples, as per previous review?

2018-11-03 05:40 UTC, datapythonista commented
Closing as stale.

2018-11-03 05:40 UTC, closed without merging