DOC: update the DataFrame.eval() docstring
pandas-dev/pandas pull request #20209
Opened 2018-03-10 18:03 UTC by StephenVoland

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [x ] PR title is "DOC: update the <your-function-or-method> docstring"
- [x ] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [x ] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x ] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [x ] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
################################################################################
###################### Docstring (pandas.DataFrame.eval)  ######################
################################################################################

Evaluate expression in the context of the calling DataFrame instance.

Evaluates a string describing operations on dataframe columns.  This
allows `eval` to run arbitrary code, but remember to sanitize your
inputs.

Parameters
----------
expr : str
    The expression string to evaluate.
inplace : bool, default False
    If the expression contains an assignment, whether to perform the
    operation inplace and mutate the existing DataFrame. Otherwise,
    a new DataFrame is returned.

    .. versionadded:: 0.18.0.
kwargs : dict
    See the documentation for :func:`~pandas.eval` for complete details
    on the keyword arguments accepted by
    :meth:`~pandas.DataFrame.query`.

Returns
-------
ndarray, scalar, or pandas object
    The result of the evaluation.

See Also
--------
pandas.DataFrame.query : Evaluates a boolean expression to query the
    columns of a frame.
pandas.DataFrame.assign : Can evaluate an expression or function to
    create new values for a column.
pandas.eval : Evaluate a Python expression as a string using various
    backends.

Notes
-----
For more details see the API documentation for :func:`~pandas.eval`.
For detailed examples see :ref:`enhancing performance with eval
<enhancingperf.eval>`.

Examples
--------
>>> df = pd.DataFrame({'A': range(1, 6), 'B': range(10, 0, -2)})
>>> df
   A   B
0  1  10
1  2   8
2  3   6
3  4   4
4  5   2
>>> df.eval('A + B')
0    11
1    10
2     9
3     8
4     7
dtype: int64
>>> df.eval('C = A + B')
   A   B   C
0  1  10  11
1  2   8  10
2  3   6   9
3  4   4   8
4  5   2   7
>>> df
   A   B
0  1  10
1  2   8
2  3   6
3  4   4
4  5   2
>>> df.eval('C = A + B', inplace=True)
>>> df
   A   B   C
0  1  10  11
1  2   8  10
2  3   6   9
3  4   4   8
4  5   2   7

################################################################################
################################## Validation ##################################
################################################################################

Docstring for "pandas.DataFrame.eval" correct. :)
```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

2018-03-10 18:10 UTC, joaoavf commented
There is a space here `[x ]`, there should be no space between 'x' and ']'.

2018-03-10 18:14 UTC, StephenVoland commented
Fixed.

2018-03-10 18:26 UTC, TomAugspurger commented on pandas/core/frame.py
> +        >>> df.eval('C = A + B')
Could you add a line before this saying "Assignment is allowed and by default the original DataFrame is not modiefied."

2018-03-10 18:27 UTC, TomAugspurger commented on pandas/core/frame.py
> +        >>> df.eval('C = A + B', inplace=True)
And before this, say "use `inplace=True` to modify the original DataFrame.

2018-03-10 18:31 UTC, joaoavf reviewed
Minor suggestions, very good overall.

2018-03-10 18:31 UTC, joaoavf commented on pandas/core/frame.py
> +        Evaluates a string describing operations on dataframe columns.  This
dataframe --> DataFrame

2018-03-10 18:31 UTC, joaoavf commented on pandas/core/frame.py
> +        inputs.
Might be useful to state clearly that this will not evaluate expression within elements of the DataFrame, that it will only evaluate columns.

2018-03-10 19:13 UTC, StephenVoland commented
All fixes made, thanks for comments.

2018-03-10 19:54 UTC, jreback requested changes

2018-03-10 19:54 UTC, jreback commented on pandas/core/frame.py
> +        This function calls `pandas.eval()` and is likely to be slower than
remove this, its not relevant

2018-03-10 19:54 UTC, jreback commented on pandas/core/frame.py
> +        not specific rows or elements).  This allows `eval` to run arbitrary
You can move the last sentence to the Notes section, and slightyl expand on 'sanitize' inputs.

2018-03-12 12:10 UTC, TomAugspurger commented on pandas/core/frame.py
> +        This function calls `pandas.eval()` and is likely to be slower than
Is this meaningfully slower than `pd.eval`? We don't seem to do much before handing it off, so if you're doing anything meaningfully expensive in the `eval`, there shouldn't be much overhead. I'd prefer to remove this unless there's a significant difference.

2018-03-12 12:11 UTC, TomAugspurger commented on pandas/core/frame.py
> +        pandas.DataFrame.query : Evaluates a boolean expression to query the
I believe `DataFrame.query` and `DataFrame.assign` will work. You will need `pandas` in `pandas.eval`.

2018-03-13 14:26 UTC, TomAugspurger approved these changes

2018-03-13 14:27 UTC, merged