Docstring pandas.data frame.diff
pandas-dev/pandas pull request #20227
Opened 2018-03-10 20:00 UTC by adatasetaday

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [X] PR title is "DOC: update the <your-function-or-method> docstring"
- [X] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [X] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [X] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
################################################################################
################################## Validation ##################################
################################################################################

Errors found:
	Errors in parameters section
		Parameter "axis" description should finish with "."
```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

"axis" parameter has a versionadded tag that does not end with ".".

2018-03-10 20:05 UTC, TomAugspurger commented
I think we just need a `.` at the end of this line https://github.com/pandas-dev/pandas/pull/20227/files#diff-1e79abbbdd150d4771b91ea60a4e1cc7R4739

LGTM otherwise.

2018-03-10 20:17 UTC, adatasetaday commented
I can definitely do that, but it won't be consistent with the other functions' documentation.

I'm also adding a "See Also" to DataFrame.pct_change() which I didn't realize was pretty much the same function using % instead of absolute value.

2018-03-10 20:28 UTC, adatasetaday commented
As dicsussed, the "." was added at the end of the versionadded and passed validation without any errors.

2018-03-10 21:43 UTC, jreback requested changes

2018-03-10 21:43 UTC, jreback commented on pandas/core/frame.py
> +
add DataFrame.shift

2018-03-10 21:43 UTC, jreback commented on pandas/core/frame.py
> +        >>> df.diff()
add a blank line between cases

2018-03-11 01:44 UTC, pep8speaks commented
Hello @adatasetaday! Thanks for updating the PR.

 - In the file [`pandas/core/frame.py`](https://github.com/pandas-dev/pandas/blob/736310ee49405282f7467629f14f63c9d855d1f8/pandas/core/frame.py), following are the PEP8 issues :

> [Line 4748:80](https://github.com/pandas-dev/pandas/blob/736310ee49405282f7467629f14f63c9d855d1f8/pandas/core/frame.py#L4748): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)

2018-03-11 02:01 UTC, adatasetaday reviewed
As requested added blank line between cases and added reference to DataFrame.shift in "See Also"

2018-03-11 12:36 UTC, merged

2018-03-11 12:36 UTC, TomAugspurger commented
Thanks @adatasetaday!