Series as of docstring
pandas-dev/pandas pull request #20226
Opened 2018-03-10 19:53 UTC by Lrodlima

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [ ] PR title is "DOC: update the <your-function-or-method> docstring"
- [ ] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [ ] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [ ] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
# paste output of "scripts/validate_docstrings.py <your-function-or-method>" here
# between the "```" (remove this comment, but keep the "```")

```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

Checklist for other PRs (remove this part if you are doing a PR for the pandas documentation sprint):

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-03-10 19:53 UTC, pep8speaks commented
Hello @Lrodlima! Thanks for submitting the PR.

 - In the file [`pandas/core/generic.py`](https://github.com/pandas-dev/pandas/blob/95a5298b56afd6c7ceab6cc321a25941642099ec/pandas/core/generic.py), following are the PEP8 issues :

> [Line 5404:43](https://github.com/pandas-dev/pandas/blob/95a5298b56afd6c7ceab6cc321a25941642099ec/pandas/core/generic.py#L5404): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5405:1](https://github.com/pandas-dev/pandas/blob/95a5298b56afd6c7ceab6cc321a25941642099ec/pandas/core/generic.py#L5405): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 5406:80](https://github.com/pandas-dev/pandas/blob/95a5298b56afd6c7ceab6cc321a25941642099ec/pandas/core/generic.py#L5406): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 79 characters)
> [Line 5407:80](https://github.com/pandas-dev/pandas/blob/95a5298b56afd6c7ceab6cc321a25941642099ec/pandas/core/generic.py#L5407): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (106 > 79 characters)
> [Line 5408:1](https://github.com/pandas-dev/pandas/blob/95a5298b56afd6c7ceab6cc321a25941642099ec/pandas/core/generic.py#L5408): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 5410:1](https://github.com/pandas-dev/pandas/blob/95a5298b56afd6c7ceab6cc321a25941642099ec/pandas/core/generic.py#L5410): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 5416:80](https://github.com/pandas-dev/pandas/blob/95a5298b56afd6c7ceab6cc321a25941642099ec/pandas/core/generic.py#L5416): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 79 characters)
> [Line 5434:80](https://github.com/pandas-dev/pandas/blob/95a5298b56afd6c7ceab6cc321a25941642099ec/pandas/core/generic.py#L5434): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (134 > 79 characters)
> [Line 5441:80](https://github.com/pandas-dev/pandas/blob/95a5298b56afd6c7ceab6cc321a25941642099ec/pandas/core/generic.py#L5441): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 5442:62](https://github.com/pandas-dev/pandas/blob/95a5298b56afd6c7ceab6cc321a25941642099ec/pandas/core/generic.py#L5442): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5456:1](https://github.com/pandas-dev/pandas/blob/95a5298b56afd6c7ceab6cc321a25941642099ec/pandas/core/generic.py#L5456): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2018-03-10 20:19 UTC, jorisvandenbossche commented
Can you please follow the instructions? (paste the output of the validation scripts, make sure the PEP8 check passes)

2018-03-10 20:21 UTC, jorisvandenbossche commented on pandas/core/generic.py
> +        ...          datetime.strptime('20160101', '%Y%m%d')]
you can generate some dates with `pd.date_range` (if you want a regular index), or pd.to_datetime.

2018-03-10 20:21 UTC, jorisvandenbossche commented on pandas/core/generic.py
> +        >>> mySeries = pd.Series(data=names, index=dates)
you can call the series `s`

2018-03-10 20:21 UTC, jorisvandenbossche commented on pandas/core/generic.py
> +        >>> mySeries.asof(datetime.strptime('20150102', '%Y%m%d'))
Can you use `pd.Timestamp("2015-01-02")` instead? (to use the pandas equivalent way)

2018-03-10 21:46 UTC, jreback requested changes

2018-03-10 21:46 UTC, jreback commented on pandas/core/generic.py
> +        subset : str
subset: str or list of strings
    if not None, use the columns for NaN propagation.

2018-03-10 21:46 UTC, jreback commented on pandas/core/generic.py
> +        Dates are assumed to be sorted.
can you make a Raises section and add ValueError there (if dates are not sorted)

2018-03-10 21:46 UTC, jreback commented on pandas/core/generic.py
> +        >>> import pandas as pd
don't need pandas import

2018-03-17 12:11 UTC, jorisvandenbossche commented
@Lrodlima do you have time to update the PR based on the feedback?

2018-08-22 10:27 UTC, datapythonista commented
Seems like this is duplicate work with #21034, which is a bit more complete. Closing this one. Thanks @Lrodlima for the work, and sorry about the lack of synchronization.

2018-08-22 10:27 UTC, closed without merging