Docstring pandas.series.diff
pandas-dev/pandas pull request #20238
Opened 2018-03-10 21:11 UTC by adatasetaday

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [X] PR title is "DOC: update the <your-function-or-method> docstring"
- [X] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [X] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [X] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
################################################################################
################################## Validation ##################################
################################################################################

Docstring for "pandas.Series.diff" correct. :)
```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

2018-03-10 21:14 UTC, TomAugspurger commented
@adatasetaday were you assigned both DataFrame.diff and Series.diff? OK to do as one PR, but wanted to make sure we don't conflict with someone else.

2018-03-10 21:17 UTC, TomAugspurger commented
Ah I see https://github.com/pandas-dev/pandas/pull/20227

could you remove the dataframe changes from this branch so we don't ahve merge conflicts?

2018-03-10 21:18 UTC, TomAugspurger commented
LGTM once you remove the dataframe changes.

2018-03-10 21:35 UTC, adatasetaday commented
@TomAugspurger Yes, I was assigned diff for both Series and DataFrame. I made sense since it were very similar.

I fixed the commit.

2018-03-10 21:38 UTC, jreback requested changes

2018-03-10 21:38 UTC, jreback commented on pandas/core/series.py
> +        DataFrame.diff: First discrete difference of object
add Series.shift

2018-03-11 02:17 UTC, adatasetaday reviewed
Series.shift added

2018-03-11 14:16 UTC, jreback approved these changes

2018-03-11 14:17 UTC, merged

2018-03-11 14:17 UTC, jreback commented
thanks @adatasetaday very nice!