DOC: update Series.sort_values docstring
pandas-dev/pandas pull request #20247
Opened 2018-03-10 21:36 UTC by rafarui

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [ ] PR title is "DOC: update the <your-function-or-method> docstring"
- [ ] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [ ] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [ ] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
# paste output of "scripts/validate_docstrings.py <your-function-or-method>" here
# between the "```" (remove this comment, but keep the "```")

```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

Checklist for other PRs (remove this part if you are doing a PR for the pandas documentation sprint):

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-03-10 21:37 UTC, pep8speaks commented
Hello @rafarui! Thanks for submitting the PR.

 - In the file [`pandas/core/series.py`](https://github.com/pandas-dev/pandas/blob/4aea67cf510ee3d7e330a2a1197348dcea24ab45/pandas/core/series.py), following are the PEP8 issues :

> [Line 1893:80](https://github.com/pandas-dev/pandas/blob/4aea67cf510ee3d7e330a2a1197348dcea24ab45/pandas/core/series.py#L1893): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 1904:80](https://github.com/pandas-dev/pandas/blob/4aea67cf510ee3d7e330a2a1197348dcea24ab45/pandas/core/series.py#L1904): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 79 characters)
> [Line 1907:80](https://github.com/pandas-dev/pandas/blob/4aea67cf510ee3d7e330a2a1197348dcea24ab45/pandas/core/series.py#L1907): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 1922:80](https://github.com/pandas-dev/pandas/blob/4aea67cf510ee3d7e330a2a1197348dcea24ab45/pandas/core/series.py#L1922): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)

2018-03-10 21:40 UTC, jorisvandenbossche commented
Can you follow the guidelines please: paste the output of the validation script above (you can still edit your top post). And check PEP8 as well, as you have some errors there.

2018-03-10 21:45 UTC, jorisvandenbossche commented on pandas/core/series.py
> +            Axis to direct sorting.
I would mention here that is can only be 0 for Series (accepted for compatibility with DataFrame.sort_values)

2018-03-10 21:45 UTC, jorisvandenbossche commented on pandas/core/series.py
> +            Choice of sorting algorithm. See also ndarray.np.sort [1]_ for more information. `mergesort` is the only stable
you can use `` :func:`np.sort` `` as a syntax to create this reference automatically (then you don't need the `[1]_`

2018-03-10 21:45 UTC, jorisvandenbossche commented on pandas/core/series.py
> +        Sort values ascending order
Can you add something like `(default behaviour)` ?

2018-03-10 21:45 UTC, jorisvandenbossche commented on pandas/core/series.py
> +        >>> s = pd.Series([np.nan, 1, 232, 323, 1, 2, 3, 45])
I would make this a bit shorter (try to aim at 5 elements)

2018-03-10 21:59 UTC, math-and-data commented on pandas/core/series.py
> +        """
If you find time, it would be nice to have an example that includes strings as well so that users see that sorting can apply to anything.

2018-03-10 21:59 UTC, math-and-data commented on pandas/core/series.py
> +        Sort values descending order
Quick grammar comment: Sort values *in* descending order

2018-03-10 21:59 UTC, math-and-data commented on pandas/core/series.py
> +        Sort values ascending order
Quick grammar comment: Sort values *in* ascending order

2018-03-10 23:24 UTC, jorisvandenbossche commented on pandas/core/series.py
> +        >>> s = pd.Series([np.nan, 1, 3, 5, 10])
maybe put the 5 and 10 out of order?

2018-03-11 13:47 UTC, jreback requested changes

2018-03-11 13:47 UTC, jreback commented on pandas/core/series.py
> +        Sort (or order) a Series in ascending or descending order by some
by the values.

2018-03-11 13:47 UTC, jreback commented on pandas/core/series.py
> +        Sort (or order) a Series in ascending or descending order by some
just say Sort

2018-03-11 14:03 UTC, jreback approved these changes

2018-03-11 14:03 UTC, jreback commented
lgtm. @jorisvandenbossche

2018-03-12 09:03 UTC, jorisvandenbossche reviewed
Looking good! Added a few more comments

2018-03-12 09:03 UTC, jorisvandenbossche commented on pandas/core/series.py
> +        kind : {‘quicksort’, ‘mergesort’ or ‘heapsort’}, default ‘quicksort’
it seems you are using here not the 'normal' single quote, but king of curved smart quote. Can you change this? (see the quotes in the type description of the na_position keyword, that are the good ones)

2018-03-12 14:59 UTC, jorisvandenbossche approved these changes

2018-03-12 14:59 UTC, merged

2018-03-12 15:00 UTC, jorisvandenbossche commented
@rafarui Thanks a lot!