DOC: update the DataFrame.mode method docstring
pandas-dev/pandas pull request #20241
Opened 2018-03-10 21:15 UTC by mkoo21

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [ ] PR title is "DOC: update the <your-function-or-method> docstring"
- [ ] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [ ] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [ ] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
# paste output of "scripts/validate_docstrings.py <your-function-or-method>" here
# between the "```" (remove this comment, but keep the "```")

```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

Checklist for other PRs (remove this part if you are doing a PR for the pandas documentation sprint):

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-03-10 21:15 UTC, pep8speaks commented
Hello @mkoo21! Thanks for submitting the PR.

 - In the file [`pandas/core/frame.py`](https://github.com/pandas-dev/pandas/blob/7458582b7bc8f36278f70ca0d472c282c042961c/pandas/core/frame.py), following are the PEP8 issues :

> [Line 5876:65](https://github.com/pandas-dev/pandas/blob/7458582b7bc8f36278f70ca0d472c282c042961c/pandas/core/frame.py#L5876): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5877:1](https://github.com/pandas-dev/pandas/blob/7458582b7bc8f36278f70ca0d472c282c042961c/pandas/core/frame.py#L5877): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 5884:77](https://github.com/pandas-dev/pandas/blob/7458582b7bc8f36278f70ca0d472c282c042961c/pandas/core/frame.py#L5884): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5893:46](https://github.com/pandas-dev/pandas/blob/7458582b7bc8f36278f70ca0d472c282c042961c/pandas/core/frame.py#L5893): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5894:79](https://github.com/pandas-dev/pandas/blob/7458582b7bc8f36278f70ca0d472c282c042961c/pandas/core/frame.py#L5894): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5896:73](https://github.com/pandas-dev/pandas/blob/7458582b7bc8f36278f70ca0d472c282c042961c/pandas/core/frame.py#L5896): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5897:64](https://github.com/pandas-dev/pandas/blob/7458582b7bc8f36278f70ca0d472c282c042961c/pandas/core/frame.py#L5897): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5909:70](https://github.com/pandas-dev/pandas/blob/7458582b7bc8f36278f70ca0d472c282c042961c/pandas/core/frame.py#L5909): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5910:75](https://github.com/pandas-dev/pandas/blob/7458582b7bc8f36278f70ca0d472c282c042961c/pandas/core/frame.py#L5910): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5911:60](https://github.com/pandas-dev/pandas/blob/7458582b7bc8f36278f70ca0d472c282c042961c/pandas/core/frame.py#L5911): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5916:78](https://github.com/pandas-dev/pandas/blob/7458582b7bc8f36278f70ca0d472c282c042961c/pandas/core/frame.py#L5916): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5919:36](https://github.com/pandas-dev/pandas/blob/7458582b7bc8f36278f70ca0d472c282c042961c/pandas/core/frame.py#L5919): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5920:69](https://github.com/pandas-dev/pandas/blob/7458582b7bc8f36278f70ca0d472c282c042961c/pandas/core/frame.py#L5920): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5921:65](https://github.com/pandas-dev/pandas/blob/7458582b7bc8f36278f70ca0d472c282c042961c/pandas/core/frame.py#L5921): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5953:1](https://github.com/pandas-dev/pandas/blob/7458582b7bc8f36278f70ca0d472c282c042961c/pandas/core/frame.py#L5953): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2018-03-10 21:22 UTC, jorisvandenbossche commented
@mkoo21 Can you try to follow the guidelines please? Check for PEP8, paste the output of the validation script

2018-03-10 21:25 UTC, mkoo21 commented
Sorry, I thought I ran the PEP8 check but it wasn't outputting anything earlier.
Output of validation script: 
```
################################################################################
################################## Validation ##################################
################################################################################

Docstring for "pandas.DataFrame.mode" correct. :)
```

2018-03-11 13:59 UTC, jreback requested changes

2018-03-11 13:59 UTC, jreback commented on pandas/core/frame.py
>                levels and/or column labels
try not to change unrelated things

2018-03-11 13:59 UTC, jreback commented on pandas/core/frame.py
> +        Adds a row for each mode per label, filling gaps with NaN.
can add a line explaining what mode is

2018-03-11 13:59 UTC, jreback commented on pandas/core/frame.py
> +            default behaviour).
you don't need the parens, it doesn't read well

2018-03-11 13:59 UTC, jreback commented on pandas/core/frame.py
> +        axis (when more than one item share the maximum frequency), which is
no parens, just use a comma. capitalize DataFrame.

you can leave off the impute sentence

2018-03-11 13:59 UTC, jreback commented on pandas/core/frame.py
> +        Series.value_counts : Returns a Series with all occuring values as
counts of values

2018-03-11 13:59 UTC, jreback commented on pandas/core/frame.py
> +        ``mode`` returns a DataFrame with multiple rows if there is more than
you don't need this sentence as its above

2018-03-11 13:59 UTC, jreback commented on pandas/core/frame.py
> +        75        2     2
put the mode example first

2018-03-22 18:31 UTC, mkoo21 commented
I've made the requested changes to the text. The validation and PEP8 scripts passed. I'm not sure how to address the CI failures on my end. Is there anything else I need to do?

2018-08-17 20:32 UTC, datapythonista commented
Superseded by #22404 (discontinued PR, and the source branch does not exist anymore).

2018-08-17 20:32 UTC, closed without merging