DOC: update the window.Rolling.min docstring
pandas-dev/pandas pull request #20263
Opened 2018-03-11 00:01 UTC by gojandrooo

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [ ] PR title is "DOC: update the <your-function-or-method> docstring"
- [ ] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [ ] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [ ] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
# paste output of "scripts/validate_docstrings.py <your-function-or-method>" here
# between the "```" (remove this comment, but keep the "```")

```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

Checklist for other PRs (remove this part if you are doing a PR for the pandas documentation sprint):

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-03-11 00:01 UTC, pep8speaks commented
Hello @gojandrooo! Thanks for submitting the PR.

 - In the file [`pandas/core/window.py`](https://github.com/pandas-dev/pandas/blob/81f5d97728ff4ade3d206bf5315e0d189f460f5a/pandas/core/window.py), following are the PEP8 issues :

> [Line 841:36](https://github.com/pandas-dev/pandas/blob/81f5d97728ff4ade3d206bf5315e0d189f460f5a/pandas/core/window.py#L841): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 853:1](https://github.com/pandas-dev/pandas/blob/81f5d97728ff4ade3d206bf5315e0d189f460f5a/pandas/core/window.py#L853): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 882:1](https://github.com/pandas-dev/pandas/blob/81f5d97728ff4ade3d206bf5315e0d189f460f5a/pandas/core/window.py#L882): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2018-03-11 01:02 UTC, WillAyd requested changes

2018-03-11 01:02 UTC, WillAyd commented on pandas/core/window.py
> +    >>> s
The constructor here is simple enough that you don't need to explicitly print

2018-03-11 12:17 UTC, jorisvandenbossche reviewed
Small comment + @WillAyd 's one, looks good!

2018-03-11 12:17 UTC, jorisvandenbossche commented on pandas/core/window.py
> +    >>> s = pd.Series([4,3,5,2,6])
spaces after comma for PEP8

2018-03-17 11:49 UTC, jorisvandenbossche approved these changes
Pushed a small update fixing the PEP8 issues

2018-03-17 11:49 UTC, merged

2018-03-17 11:49 UTC, jorisvandenbossche commented
@gojandrooo Thanks!