DOC: update the pandas.core.window.x.mean docstring
pandas-dev/pandas pull request #20265
Opened 2018-03-11 00:06 UTC by johnnymetz

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [X] PR title is "DOC: update the <your-function-or-method> docstring"
- [X] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [X] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [X] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
(pandas_dev) lilcrawford:pandas $ python scripts/validate_docstrings.py pandas.core.window.Window.mean

################################################################################
################## Docstring (pandas.core.window.Window.mean) ##################
################################################################################

Calculate the window mean of the values.

Parameters
----------
*args
    Under Review.
**kwargs
    Under Review.

Returns
-------
Series or DataFrame
    Returned object type is determined by the caller of the window
    calculation.

See Also
--------
Series.window : Calling object with Series data
DataFrame.window : Calling object with DataFrames
Series.mean : Equivalent method for Series
DataFrame.mean : Equivalent method for DataFrame

Examples
--------
The below example will show rolling mean calculations with window sizes of
two and three, respectively.

>>> s = pd.Series([1, 2, 3, 4])
>>> s.rolling(2).mean()
0    NaN
1    1.5
2    2.5
3    3.5
dtype: float64
>>> s.rolling(3).mean()
0    NaN
1    NaN
2    2.0
3    3.0
dtype: float64

################################################################################
################################## Validation ##################################
################################################################################

Errors found:
	No extended summary found
	Errors in parameters section
		Parameters {'args', 'kwargs'} not documented
		Unknown parameters {'**kwargs', '*args'}
		Parameter "*args" has no type
		Parameter "**kwargs" has no type

(pandas_dev) lilcrawford:pandas $ python scripts/validate_docstrings.py pandas.core.window.Rolling.mean

################################################################################
################# Docstring (pandas.core.window.Rolling.mean)  #################
################################################################################

Calculate the rolling mean of the values.

Parameters
----------
*args
    Under Review.
**kwargs
    Under Review.

Returns
-------
Series or DataFrame
    Returned object type is determined by the caller of the rolling
    calculation.

See Also
--------
Series.rolling : Calling object with Series data
DataFrame.rolling : Calling object with DataFrames
Series.mean : Equivalent method for Series
DataFrame.mean : Equivalent method for DataFrame

Examples
--------
The below example will show rolling mean calculations with window sizes of
two and three, respectively.

>>> s = pd.Series([1, 2, 3, 4])
>>> s.rolling(2).mean()
0    NaN
1    1.5
2    2.5
3    3.5
dtype: float64
>>> s.rolling(3).mean()
0    NaN
1    NaN
2    2.0
3    3.0
dtype: float64

################################################################################
################################## Validation ##################################
################################################################################

Errors found:
	No extended summary found
	Errors in parameters section
		Parameters {'args', 'kwargs'} not documented
		Unknown parameters {'**kwargs', '*args'}
		Parameter "*args" has no type
		Parameter "**kwargs" has no type

(pandas_dev) lilcrawford:pandas $ python scripts/validate_docstrings.py pandas.core.window.Expanding.mean

################################################################################
################ Docstring (pandas.core.window.Expanding.mean)  ################
################################################################################

Calculate the expanding mean of the values.

Parameters
----------
*args
    Under Review.
**kwargs
    Under Review.

Returns
-------
Series or DataFrame
    Returned object type is determined by the caller of the expanding
    calculation.

See Also
--------
Series.expanding : Calling object with Series data
DataFrame.expanding : Calling object with DataFrames
Series.mean : Equivalent method for Series
DataFrame.mean : Equivalent method for DataFrame

Examples
--------
The below example will show rolling mean calculations with window sizes of
two and three, respectively.

>>> s = pd.Series([1, 2, 3, 4])
>>> s.rolling(2).mean()
0    NaN
1    1.5
2    2.5
3    3.5
dtype: float64
>>> s.rolling(3).mean()
0    NaN
1    NaN
2    2.0
3    3.0
dtype: float64

################################################################################
################################## Validation ##################################
################################################################################

Errors found:
	No extended summary found
	Errors in parameters section
		Parameters {'args', 'kwargs'} not documented
		Unknown parameters {'**kwargs', '*args'}
		Parameter "*args" has no type
		Parameter "**kwargs" has no type
```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

2018-03-11 01:01 UTC, WillAyd commented
lgtm

2018-03-11 14:14 UTC, jreback requested changes

2018-03-11 14:14 UTC, jreback commented on pandas/core/window.py
> +    >>> s.rolling(3).mean()
can you add a blank line between cases

2018-03-12 07:24 UTC, pep8speaks commented
Hello @johnnymetz! Thanks for updating the PR.

 - In the file [`pandas/core/window.py`](https://github.com/pandas-dev/pandas/blob/a9a510c0ca232ee5ea6abae49c31679e210c5928/pandas/core/window.py), following are the PEP8 issues :

> [Line 360:1](https://github.com/pandas-dev/pandas/blob/a9a510c0ca232ee5ea6abae49c31679e210c5928/pandas/core/window.py#L360): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2018-03-12 07:33 UTC, johnnymetz commented
Blank line added!

2018-03-17 12:30 UTC, jorisvandenbossche approved these changes
Looks good, thanks!

2018-03-17 12:30 UTC, merged