API: Remove integer position args from xy for plotting
pandas-dev/pandas pull request #20371
Opened 2018-03-15 21:44 UTC by MasonGallo

- [x] closes #20056 
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [?] whatsnew entry

This is based on discussion from #20000 where we decided it was confusing to allow `df.plot` to support both labels AND positions. I wasn't sure where to put this in whatsnew, so lmk and I'll update it.

2018-03-15 23:06 UTC, jreback commented on pandas/tests/plotting/test_frame.py
> +        if self.mpl_ge_1_3_1:
@TomAugspurger we should be able to blow this code away as we > 1.4.3, yes (separate PR)

2018-03-15 23:08 UTC, jreback requested changes
can you add a sub-section in the whatsnew about this in api-breaking changes. Note we *may* want to consider deprecating this and removing in a future version @jorisvandenbossche @TomAugspurger . though I am fine with just changing it.

2018-03-15 23:08 UTC, jreback commented on pandas/tests/plotting/test_frame.py
> +    @pytest.mark.parametrize("x,y,colnames", [
can you add a test that checks the raise when passing ints and a non-int index

2018-03-16 08:53 UTC, jorisvandenbossche commented
> Note we may want to consider deprecating this and removing in a future version @jorisvandenbossche @TomAugspurger . though I am fine with just changing it.

If it worked, I think we should deprecate it. But did it actually work? Because https://github.com/pandas-dev/pandas/issues/20056 seems to indicate not? (if it didn't work, of course fine to just remove)

2018-03-16 08:58 UTC, jorisvandenbossche commented
So it seems that for `line`, `bar`, `area` it doesn't work, but for `scatter`, `pie` and `hexbin` it does?

2018-03-16 11:06 UTC, TomAugspurger commented
I don't think we should remove this. I know positional plotting gets some use, especially for exploratory analysis when you have long column names.

I'll look more at why the original issue was failiing.

2018-03-16 14:26 UTC, MasonGallo commented
> So it seems that for line, bar, area it doesn't work, but for scatter, pie and hexbin it does?

@jorisvandenbossche yes I believe this is due to the structure of the code - the index setting I mentioned in #20056 only happens to `kind` not from that set - called `_dataframe_kinds` and `_series_kinds`.

> I don't think we should remove this. I know positional plotting gets some use, especially for exploratory analysis when you have long column names.

@TomAugspurger why not ask the user to supply `data.columns[ind]` instead of us making assumptions and calculating it for them? IMO that would make the API less complex.

2018-03-16 14:33 UTC, TomAugspurger commented
IME, DataFrame.plot is most often used in exploratory analysis. For this,
speed typing becomes an API consideration.
If you have a long column name, but want to quickly plot it, `df.plot(y=0)`
is nicer than `df.plot(y='percent_return_for_foo_over_bar')`.

> instead of us making assumptions

I don't think we ever make assumptions? If there's ever an integer in the
column we don't fall back to positional indexing.
IIUC there was just a bug in how we computed the positions when both `x`
and `y` are specified.

On Fri, Mar 16, 2018 at 9:26 AM, Mason Gallo <notifications@github.com>
wrote:

> So it seems that for line, bar, area it doesn't work, but for scatter, pie
> and hexbin it does?
>
> @jorisvandenbossche <https://github.com/jorisvandenbossche> yes I believe
> this is due to the structure of the code - the index setting I mentioned in
> #20056 <https://github.com/pandas-dev/pandas/issues/20056> only happens
> to kind not from that set - called _dataframe_kinds and _series_kinds.
>
> I don't think we should remove this. I know positional plotting gets some
> use, especially for exploratory analysis when you have long column names.
>
> @TomAugspurger <https://github.com/tomaugspurger> why not ask the user to
> supply data.columns[ind] instead of us making assumptions and calculating
> it for them? IMO that would make the API less complex.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/20371#issuecomment-373729486>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABQHIpGFXfj-iGl2wL60jY-nACHpf7MNks5te8uQgaJpZM4Ss7iz>
> .
>

2018-03-16 15:20 UTC, MasonGallo commented
> IME, DataFrame.plot is most often used in exploratory analysis. For this,
speed typing becomes an API consideration.

That's fair - you have much more context than I do on usage.

> I don't think we ever make assumptions?

We make an assumption by allowing mixed types in column names - i.e. we check with `holds_integer` and then assume a given int is meant as a column name.

Seems like we don't have consensus on whether this should be removed from API. How should we proceed? I can close this and fix the integer indexing bug in #20000 ?

2018-03-16 15:29 UTC, TomAugspurger commented
> We make an assumption by allowing mixed types in column names - i.e. we check with holds_integer and then assume a given int is meant as a column name.

Perhaps it's just semantics then, but I wouldn't call that assuming :) To me the behavior is clear (but could be better documented). Specifying `x` and `y` as positions is allowed if and only if the columns holds no integers.

> I can close this and fix the integer indexing bug in #20000 ?

If you're comfortable with maybe wasting some effort, I would work around the bug in #20000. We can wait to hear what the other maintainers say before closing or working further on this issue, but I would be sad to see this go.

2018-03-16 15:58 UTC, jorisvandenbossche commented
> Perhaps it's just semantics then, but I wouldn't call that assuming :) To me the behavior is clear (but could be better documented). Specifying x and y as positions is allowed if and only if the columns holds no integers.

Although there might be some "guessing" cases (mixed integer columns), this is also behaviour that used a lot throughout the code base (eg `level` can often be specified both as integer or as name).

--

I don't have a strong feeling about this. If it is not too difficult to fix this to actually work, I am certainly fine with keeping it.

2018-03-19 16:16 UTC, MasonGallo commented
FYI: will be closing this in favor of #20000

2018-03-22 14:41 UTC, closed without merging