BUG: dropna() on single column timezone-aware values (#13407)
pandas-dev/pandas pull request #20422
Opened 2018-03-20 16:47 UTC by JQGoh

- [x] closes #13407
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

As mentioned by the title of #13407, DataFrame.values not a 2D-array when constructed from timezone-aware datetimes. Hence, ``notna(frame.values)`` raises ``ValueErorr: 'axis' entry is out of bounds`` because user tries to apply ``dropna`` on a 1D-array.

I mainly include the example mentioned by the original author of #13407. Let me know if further test examples are required for this issue. Thanks.

2018-03-23 12:32 UTC, pep8speaks commented
Hello @JQGoh! Thanks for updating the PR.



 - In the file [`pandas/tests/frame/test_missing.py`](https://github.com/pandas-dev/pandas/blob/cbe3c81a26f842e452ada96bd4e0d5a5e7532a5e/pandas/tests/frame/test_missing.py), following are the PEP8 issues :

> [Line 206:17](https://github.com/pandas-dev/pandas/blob/cbe3c81a26f842e452ada96bd4e0d5a5e7532a5e/pandas/tests/frame/test_missing.py#L206): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 211:17](https://github.com/pandas-dev/pandas/blob/cbe3c81a26f842e452ada96bd4e0d5a5e7532a5e/pandas/tests/frame/test_missing.py#L211): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

2018-03-23 23:55 UTC, JQGoh commented
@TomAugspurger In case this could be of your interest. I recall that my first commit passed all the CI tests. However, the current failure is related to the new change in pandas/tests/extension/json/test_json.py

2018-03-24 12:05 UTC, TomAugspurger commented
Sorry about that. Fixed on master.

If you fetch master and merge it into your branch things should pass. You can also fixup that pep8 issue.

2018-03-25 04:31 UTC, JQGoh commented
@TomAugspurger Thank you for the revisions. I have fixed the PEP8 issues as well, please help to review the changes if possible.

2018-03-25 14:09 UTC, jreback requested changes
lgtm. some tests comments. ping on green.

2018-03-25 14:09 UTC, jreback commented on pandas/tests/frame/test_missing.py
> +        # Example reported by GH13407
can you remove this second coment

2018-03-25 14:09 UTC, jreback commented on pandas/tests/frame/test_missing.py
> +        df2 = DataFrame({'Time': [dt1, None, np.nan, dt2]})
name this df, and use result and expected here

2018-03-25 23:08 UTC, JQGoh commented
@jreback Thank you for your suggestions. Done.

2018-03-25 23:55 UTC, jreback approved these changes

2018-03-25 23:55 UTC, merged

2018-03-25 23:55 UTC, jreback commented
thanks for the patch @JQGoh nice to have an older issue closed!