DOC: update the isna, isnull, notna and notnull docstring
pandas-dev/pandas pull request #20459
Opened 2018-03-22 21:27 UTC by Cheukting

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [X] PR title is "DOC: update the <your-function-or-method> docstring"
- [ ] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [X] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [X] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
# paste output of "scripts/validate_docstrings.py <your-function-or-method>" here
# between the "```" (remove this comment, but keep the "```")

```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

The validation script did not work on this docstring

2018-03-22 21:38 UTC, TomAugspurger commented on pandas/core/dtypes/missing.py
> +    """Detect missing values for an array
End with a `.`

2018-03-22 21:38 UTC, TomAugspurger commented on pandas/core/dtypes/missing.py
> +
Add Series.isna, DataFrame.isna, and Index.isna.

2018-03-22 21:38 UTC, TomAugspurger commented on pandas/core/dtypes/missing.py
> +
Add Series.notna, DataFrame.notna, and Index.notna

2018-03-22 21:38 UTC, TomAugspurger commented on pandas/core/dtypes/missing.py
>      """Replacement for numpy.isfinite / -numpy.isnan which is suitable for use
Can you shorten this to a single line? Can be similar to you docstring for `isna`, just flipped.

2018-03-22 21:44 UTC, TomAugspurger commented
In the Parameters section, can you change `arr` to `obj` to match the function siganture.

2018-03-26 10:25 UTC, jreback requested changes

2018-03-26 10:25 UTC, jreback commented on pandas/core/dtypes/missing.py
> +    a missing value (`NaN` in numeric arrays, `None`/`NaN` in object arrays)
NaT in datetimelike

2018-03-26 10:25 UTC, jreback commented on pandas/core/dtypes/missing.py
> +    >>> pd.isna(np.nan)
an you add blank lines between cases

2018-03-26 10:25 UTC, jreback commented on pandas/core/dtypes/missing.py
> +           [False, False,  True]])
an you show a datetimelike example (DatetimeIndex is good)

2018-03-26 10:25 UTC, jreback commented on pandas/core/dtypes/missing.py
> +    a missing.value (`NaN` in numeric arrays, `None`/`NaN` in object arrays)
same as above

2018-03-26 10:25 UTC, jreback commented on pandas/core/dtypes/missing.py
> +           [ 4.,  5., nan]])
same

2018-03-26 11:12 UTC, TomAugspurger commented on pandas/core/dtypes/missing.py
> +    array-like of bool or bool
Could you rephrase as `bool or array-like of bool`, so that it goes small to big?

2018-03-26 11:12 UTC, TomAugspurger commented on pandas/core/dtypes/missing.py
>          Array or bool indicating whether an object is null or if an array is
This wording tripped me up. Could try rephrasing it? Maybe something like, "Indicator for missing values. For a scalar, input, a scalar boolean is returned. For an array-like input, and array (of the same type?) of booleans indicating NA values element-wise is returned.

2018-03-26 16:27 UTC, TomAugspurger approved these changes

2018-03-26 20:12 UTC, merged

2018-03-26 20:12 UTC, TomAugspurger commented
Thanks @Cheukting !