Additional DOC and BUG fix related to merging with mix of columns and…
pandas-dev/pandas pull request #20475
Opened 2018-03-23 22:20 UTC by Dr-Irv

Checklist for other PRs (remove this part if you are doing a PR for the pandas documentation sprint):

- [x] closes #20452
- [x] tests added / passed
   - test_join.py 
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry
   - not needed as it fixes a bug for v0.23 and enhances the docs

This PR adds some documentation about how `MultiLevel` index levels are dropped when doing a merge that includes levels and columns.  It also fixes a small bug related to `join`.

2018-03-31 16:31 UTC, jreback requested changes

2018-03-31 16:31 UTC, jreback commented on pandas/tests/test_join.py
> +    leftindex = MultiIndex.from_product([list('abc'), list('xy'), [1, 2]],
can you add this issue number here

ideally can you use the join_type fixture here (to run this for all join types)

2018-03-31 16:34 UTC, jreback commented
you showed 3 examples in the OP, can you replicate them here

2018-04-03 13:36 UTC, Dr-Irv commented
@jreback I made the changes you asked for and it's all green

2018-11-01 01:37 UTC, jreback commented
@Dr-Irv this got a bit lost, can you rebase and update

2018-11-01 15:13 UTC, pep8speaks commented
Hello @Dr-Irv! Thanks for updating the PR.

 - There are no PEP8 issues in the file [`pandas/core/reshape/merge.py`](https://github.com/Dr-Irv/pandas/blob/0752e59de7cdcc8c23bf78a577ebcd03f49dd94a/pandas/core/reshape/merge.py) !

 - There are no PEP8 issues in the file [`pandas/tests/reshape/merge/test_join.py`](https://github.com/Dr-Irv/pandas/blob/0752e59de7cdcc8c23bf78a577ebcd03f49dd94a/pandas/tests/reshape/merge/test_join.py) !

 - There are no PEP8 issues in the file [`pandas/tests/reshape/merge/test_merge.py`](https://github.com/Dr-Irv/pandas/blob/0752e59de7cdcc8c23bf78a577ebcd03f49dd94a/pandas/tests/reshape/merge/test_merge.py) !

2018-11-01 16:11 UTC, Dr-Irv commented
@jreback merged with latest, and now all green.  I now added a line in whatsnew.

2018-11-20 14:37 UTC, datapythonista commented
@Dr-Irv sorry this wasn't merged before, can you do one more rebase please?

2018-11-26 16:43 UTC, datapythonista commented
@jreback

2018-11-26 17:04 UTC, Dr-Irv commented
@datapythonista now all green

2018-12-02 00:33 UTC, datapythonista commented
Sorry @Dr-Irv, another rebase needed.

2018-12-03 17:09 UTC, Dr-Irv commented
@datapythonista I've done the merge, but the failure is because there is something wrong on Azure.  Up to you to decide how to proceed.

2018-12-04 01:57 UTC, Dr-Irv commented
@datapythonista Current merge is now all green.

2018-12-04 02:59 UTC, jreback approved these changes

2018-12-04 02:59 UTC, jreback commented
lgtm. @Dr-Irv just pushed a commit to fix whitespace. ping on green.

2018-12-04 13:11 UTC, merged

2018-12-04 13:11 UTC, jreback commented
thanks @Dr-Irv