Fixed WOM offset when n=0
pandas-dev/pandas pull request #20549
Opened 2018-03-30 14:10 UTC by mmngreco

Checklist for other PRs (remove this part if you are doing a PR for the pandas documentation sprint):

- [x] closes #20481
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-03-30 18:16 UTC, jreback requested changes
@mmngreco can you add a whatsnew note (other enhancements section), and also a test for the ``date_range`` (both ones) as you indicated in the issue. otherwise lgtm. ping on green.

2018-03-31 08:52 UTC, mmngreco commented
Hi @jreback, I see that travis fails in https://travis-ci.org/pandas-dev/pandas/jobs/360472961, any idea whats going wrong?

2018-04-03 11:09 UTC, mmngreco commented
ping @jreback

2018-04-18 10:14 UTC, jreback requested changes
small comments, otherwise lgtm. ping on green.

2018-04-18 10:14 UTC, jreback commented on doc/source/whatsnew/v0.23.0.txt
> +- Now is possible create a :class:`WeekOfMonth` offset with `n=0` (:issue:`20517`).
re-word this something like: ``:class:`WeekOfMonth` `` constuctor will support ``n=0``

2018-04-18 10:14 UTC, jreback commented on pandas/tests/indexes/datetimes/test_date_range.py
> +        # https://github.com/pandas-dev/pandas/issues/20517
can you parametrize on periods=1, 2

2018-04-21 18:13 UTC, jreback approved these changes

2018-04-21 18:14 UTC, merged

2018-04-21 18:14 UTC, jreback commented
thanks @mmngreco