TST: test added to GH9336
pandas-dev/pandas pull request #20550
Opened 2018-03-30 14:18 UTC by jcontesti

- [X] closes #9336
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-03-30 18:03 UTC, jreback requested changes

2018-03-30 18:03 UTC, jreback commented on pandas/tests/indexing/test_loc.py
can you move this to pandas/tests/frame/test_indexing.py

make it a new test. (with _datetime in the name). can you add all of the examples in the original post?

2018-03-30 18:06 UTC, jreback commented
also add as a comment the original issue number

2018-05-20 17:20 UTC, jcontesti commented
Done, happy to contribute! Please, let me know if I must make any additional changes.

2018-05-23 11:14 UTC, jreback approved these changes

2018-05-23 11:16 UTC, jreback requested changes

2018-05-23 11:16 UTC, jreback commented on pandas/tests/frame/test_indexing.py
> +        df = pd.DataFrame(np.zeros((6, 2), dtype=int), columns=['a', 'b'])
this is failing because you are specify the dtype directly I think, just use 
``pd.DataFrame(0, columns = list('ab'), index=range(6))``

2018-05-23 11:16 UTC, jreback commented on pandas/tests/frame/test_indexing.py
> +        df.loc[[4, 5], ['a', 'b']] = A.values
can you assign with a numpy array that you construct directly

2018-05-26 18:07 UTC, jcontesti commented
Done! :-)

2018-05-29 01:34 UTC, jreback approved these changes

2018-05-29 01:34 UTC, merged

2018-05-29 01:34 UTC, jreback commented
thanks @jcontesti