CLN: Use new-style classes instead of old-style classes
pandas-dev/pandas pull request #20563
Opened 2018-03-30 23:44 UTC by jschendel

Noticed some [lgtm.com alerts](https://lgtm.com/projects/g/pydata/pandas/snapshot/f85a69a8fdaed49747c4db61f5177a296cf290eb/files/scripts/validate_docstrings.py?sort=name&dir=ASC&mode=heatmap&showExcluded=false#L108) about the [`@property` decorator not working in old-style classes](https://lgtm.com/rules/10030086/) in `scripts/validate_docstrings.py`.  I don't think this actually causes any undesired behavior in that script though.

Figured this would be a good time to enforce new-style classes throughout the codebase:
  - Converted old-style classes to new-style classes
      - Basically just inserted `(object)`.
  - Added a check to `lint.sh` for old-style classes, since `flake8` doesn't look to be catching it.
      - Maybe there's a way to enforce this in `flake8` instead?

2018-03-30 23:46 UTC, jschendel commented on ci/lint.sh
> +    grep -R --include="*.py" -E "class\s\S*[^)]:" pandas scripts
not a regex wizard, so an extra careful look here would be appreciated

2018-03-30 23:55 UTC, jreback commented
maybe we should add some extra flake8 plugins
https://pypi.python.org/pypi?%3Aaction=search&term=flake8&submit=search

would need to add to the requirements_dev and prob modify the ci slightly to install

can u make a separate issue?

2018-03-31 00:02 UTC, mroeschke commented
There's a Python package called [hacking](https://github.com/openstack-dev/hacking) that has flake8 extensions that seems to have a lint check for this:

    H238 = hacking.checks.python23:hacking_no_old_style_class

2018-03-31 15:47 UTC, jreback requested changes
lgtm. some renamings. ping on green.

2018-03-31 15:47 UTC, jreback commented on pandas/io/sas/sas_constants.py
> +class index(object):
can you rename this class (capitalize, but needs a differnt name then)

2018-03-31 15:47 UTC, jreback commented on pandas/tests/io/json/test_ujson.py
> +        class filelike(object):
can you rename this

2018-03-31 15:47 UTC, jreback commented on pandas/tests/test_resample.py
> +        class fn_class(object):
can you rename this

2018-04-03 06:11 UTC, jschendel commented
@jreback : green

2018-04-03 07:00 UTC, merged

2018-04-03 07:00 UTC, jorisvandenbossche commented
@jschendel Thanks!