[WIP] Complete offset prefix mapping
pandas-dev/pandas pull request #20562
Opened 2018-03-30 23:26 UTC by tv3141

Checklist for PRs :

- [x] closes #7985
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-04-01 14:18 UTC, jreback requested changes

2018-04-01 14:18 UTC, jreback commented on pandas/tseries/offsets.py
> +    Easter,                    # 'EASTER'
don't need Easter in this list

2018-04-02 12:00 UTC, pep8speaks commented
Hello @tv3141! Thanks for updating the PR.

 - In the file [`pandas/tseries/offsets.py`](https://github.com/pandas-dev/pandas/blob/772eda0d098ba8fdb5f8f04e2892c4e9dbba936d/pandas/tseries/offsets.py), following are the PEP8 issues :

> [Line 2456:38](https://github.com/pandas-dev/pandas/blob/772eda0d098ba8fdb5f8f04e2892c4e9dbba936d/pandas/tseries/offsets.py#L2456): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2018-08-09 04:33 UTC, jbrockmendel commented on pandas/tseries/offsets.py
> -    CustomBusinessHour,        # 'CBH'
What’s the logic behind reordering these?

2018-11-04 16:13 UTC, jreback commented
closing as stale. if you'd like to continue working, pls ping.

2018-11-04 16:13 UTC, closed without merging