BUG: Avoid splitting string with list() (#20592)
pandas-dev/pandas pull request #20615
Opened 2018-04-05 12:28 UTC by fredrik-1

Solves #20592 and I doubt that there are any cases when a key string should be split by `list()`

2018-04-05 12:42 UTC, WillAyd commented
This needs tests

2018-04-05 13:41 UTC, TomAugspurger commented
And a release note: http://pandas.pydata.org/pandas-docs/stable/contributing.html#documenting-your-code

2018-04-05 14:54 UTC, jreback requested changes

2018-04-05 14:54 UTC, jreback commented on pandas/core/series.py
>              if not isinstance(key, (list, Series, np.ndarray, Series)):
looks like extra Series listed here.

2018-04-05 14:54 UTC, jreback commented on pandas/core/series.py
> -                    key = list(key)
let's break this if up to specificy target a string e.g.

```
if isinstance(key, compat.string_types):
 ......
elif not isinstance(key, (list, Series, np.ndarray)):
    ....
```

2018-09-25 16:22 UTC, jreback commented
closing as stale, though would certainly take a PR here

2018-09-25 16:22 UTC, closed without merging