added check if categoricalDtype for issue #19278
pandas-dev/pandas pull request #20644
Opened 2018-04-10 03:35 UTC by xchoudhury

Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [ ] PR title is "DOC: update the <your-function-or-method> docstring"
- [ ] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [ ] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [ ] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
# paste output of "scripts/validate_docstrings.py <your-function-or-method>" here
# between the "```" (remove this comment, but keep the "```")

```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

Checklist for other PRs (remove this part if you are doing a PR for the pandas documentation sprint):

- [x] closes #19278
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-04-10 03:35 UTC, pep8speaks commented
Hello @xchoudhury! Thanks for submitting the PR.

 - In the file [`pandas/core/sparse/series.py`](https://github.com/pandas-dev/pandas/blob/eea3c889310333e343e346a4738e4555f34693ae/pandas/core/sparse/series.py), following are the PEP8 issues :

> [Line 139:29](https://github.com/pandas-dev/pandas/blob/eea3c889310333e343e346a4738e4555f34693ae/pandas/core/sparse/series.py#L139): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

2018-04-11 02:00 UTC, jreback requested changes
needs

- test
- whatsnew entry (bug fix)

2018-07-04 11:22 UTC, TomAugspurger commented
@xchoudhury can you update?

2018-10-11 01:51 UTC, jreback commented
closing as stale, if you want to continue working, pls ping and we can re-open. you will need to merge master.

2018-10-11 01:51 UTC, closed without merging