Fixing melt() when col_level>0 in a multi-index column
pandas-dev/pandas pull request #20646
Opened 2018-04-10 05:17 UTC by rbavishi

Example Input DataFrame -
```
import pandas as pd
x = pd.DataFrame([[0, 1], [2, 3]], columns=[list('AB'), list('CD')])
"""
   A  B
   C  D
0  0  1
1  2  3
"""
x.melt(col_level=1, id_vars=['C'], value_vars=['D'])
```

Current Output -
```
KeyError: 'C'
```

Desired Output -
```
   C variable  value
0  0        D      1
1  2        D      3
```

2018-04-10 05:17 UTC, pep8speaks commented
Hello @rbavishi! Thanks for submitting the PR.

 - In the file [`pandas/core/reshape/melt.py`](https://github.com/pandas-dev/pandas/blob/3181b870945ce0a75309b3d3f7bfaeead7d6a252/pandas/core/reshape/melt.py), following are the PEP8 issues :

> [Line 28:29](https://github.com/pandas-dev/pandas/blob/3181b870945ce0a75309b3d3f7bfaeead7d6a252/pandas/core/reshape/melt.py#L28): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 54:28](https://github.com/pandas-dev/pandas/blob/3181b870945ce0a75309b3d3f7bfaeead7d6a252/pandas/core/reshape/melt.py#L54): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment

2018-04-10 08:32 UTC, gfyoung commented
@rbavishi : Thanks for submitting this!  A couple of things:

1) Before submitting a PR, you should generally submit an issue.  The content of your PR message would have been perfect for that!

2) You'll need to add tests and an entry into our `whatsnew` file for `0.23.0`

2018-04-11 02:19 UTC, jreback requested changes
yeah this is probably broken. need some tests

2018-09-25 15:44 UTC, jreback commented
closing as stale

2018-09-25 15:44 UTC, closed without merging