ERR: Consistent errors for non-numeric ranking. (#19560)
pandas-dev/pandas pull request #20670
Opened 2018-04-12 17:21 UTC by mapehe

- [ ] closes #19560 
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

*This is only partial solution to issue #19560. 
*There were some errors with the tests, but I guess they are unrelated to these changes since I also
have them with master.
*I modified some tests so that they don't contradict with the update "don't allow objects to be ranked unless they are ordered categorials" that was suggested in #19560.

2018-04-14 12:55 UTC, jreback commented
it looks like another commit is included here. can you rebase on master.

2018-04-14 14:15 UTC, mapehe commented
Rebased and added a whatsnew entry @jreback.

2018-04-14 14:22 UTC, jreback requested changes

2018-04-16 21:27 UTC, WillAyd requested changes

2018-04-16 21:27 UTC, WillAyd commented on pandas/tests/series/test_rank.py
> +        # Ranking unordered categorials depreciated per #19560
I'd prefer to say "not supported" instead of "deprecated"

2018-04-16 21:27 UTC, WillAyd commented on pandas/tests/series/test_rank.py
> +        unordered1.rank()
Is this right? Certainly the example passes the "eye test" but if the Categorical is not ordered what semantics are we using for ranking?

2018-04-16 21:27 UTC, WillAyd commented on pandas/tests/series/test_rank.py
>      def test_rank_object_bug(self):
Name of this test can be changed to `test_rank_na_object_raises`

2018-11-23 03:28 UTC, closed without merging