BUG: Fix group key inference for CategoricalIndex
pandas-dev/pandas pull request #20777
Opened 2018-04-21 15:39 UTC by fjetter

For categorical type indices a `KeyError` is raised when the index level is used in the `by` of the `groupby`. With this fix I, the behavior of the test `test_merge_datetime_index(self, klass)` changed, though. IMHO, the behavior in this PR is more consistent since it is the same for all input types but I'm not sure what the actual behavior should be and I couldn't find a section in the documentation explaining this path.

- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-04-21 15:43 UTC, jreback commented
can u show. short example of what you are trying to do

2018-04-21 15:55 UTC, fjetter commented
The following code raises a `KeyError` if the index is of categorical type
```
import pandas as pd
left = pd.DataFrame(
    {"left_data": [1, 2]},
   index=pd.CategoricalIndex(data=["A", "B"], categories=["A", "B"])
)
right = pd.DataFrame(
      {"right_data": [1.0, 2.0]},
   index=pd.CategoricalIndex(data=["A", "B"], categories=["A", "B"])
)
result = left.merge(right, on=['index_col'])
```

2018-04-21 22:50 UTC, jreback requested changes
if you can fix up the formatting will have another look. pls add a whatsnew note as well. (reshaping bug fixes)

2018-04-21 22:50 UTC, jreback commented on pandas/tests/reshape/merge/test_merge.py
> +                         [
write like

```
@pytest.mark.parametrize(
    'index',
     [
```

so it is closer to the left margin, then each of the indexes can be writen more simply, also don't use the data kwarg
e.g.
```Index(['A', 'B'], name='index_col')``

2018-04-21 22:50 UTC, jreback commented on pandas/tests/reshape/merge/test_merge.py
> +    left = DataFrame(
should be a 1-liner

2018-05-03 06:41 UTC, fjetter commented
@jreback I fixed the formatting and added a changelog entry for the bug I fixed. Since I didn't know for sure if the other change in behavior is intended I left it out for now. Can add another entry once this is settled

2018-05-03 10:37 UTC, jreback approved these changes

2018-05-03 10:37 UTC, merged

2018-05-03 10:37 UTC, jreback commented
thanks @fjetter nice patch!