DOC: add concatenation-section to text.rst
pandas-dev/pandas pull request #20790
Opened 2018-04-23 06:01 UTC by h-vetinari

As requested by @jreback in #20347.

2018-04-23 12:43 UTC, jreback requested changes
looks good. very minor comment

2018-04-23 12:43 UTC, jreback commented
cc @jorisvandenbossche @TomAugspurger

2018-04-23 13:03 UTC, h-vetinari commented on doc/source/text.rst
> +    # manual alignment
Here's another try. As an aside, the lack of alignment *isn't* user-friendly (which is exactly the point of #20347)

2018-04-24 10:01 UTC, merged

2018-04-24 10:01 UTC, jreback commented
thanks