DEPR: Warn on empty Series dtype inference
pandas-dev/pandas pull request #20802
Opened 2018-04-23 20:44 UTC by TomAugspurger

We're changing `Series([])` to be `object` instead of `float`. This does the warning

- [x] xref https://github.com/pandas-dev/pandas/issues/17261 (leave open till we make the change)
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-04-23 20:45 UTC, TomAugspurger commented
FYI, d80e1c7dea07303c2aacef32afbd6ccfc6fd47bc has the changes. Everything else is catching / fixing warning internal to pandas. This ended up being a decent-sized change.

2018-04-24 10:26 UTC, jreback requested changes
generally looks good. looks like you have some extra commits (so rebase on master), and a couple of style changes.

2018-04-24 10:26 UTC, jreback commented on doc/source/whatsnew/v0.23.0.txt
> +- The inferred dtype for an empty Series will change from ``float`` to ``object`` (:issue:`17261`).
double-backticks on Series

2018-04-24 10:26 UTC, jreback commented on pandas/core/base.py
> +                if len(mapper) == 0:
I think this might be worthwhile to make a function in pandas.core.dtypes.cast.maybe_infer_1d_array_dtype

2018-04-24 10:26 UTC, jreback commented on pandas/core/generic.py
> +                        series_dtype = 'float'
see above

2018-04-24 10:26 UTC, jreback commented on pandas/core/indexes/base.py
> -            for all levels).  Otherwise level must be None
looks like you have some extra commits?

2018-04-24 10:26 UTC, jreback commented on pandas/tests/series/test_apply.py
> +        if len(index) == 0:
use function as above

2018-04-24 12:01 UTC, TomAugspurger commented
Sorry about the empty commits, will fix that up.

Still going through and squashing warnings. There are a few cases internally where we construct an empty series. e.g.

```python
In [1]: import pandas as pd

In [2]: pd.Series([], dtype='object').groupby([]).apply(lambda x: 1)
Out[2]: Series([], dtype: float64)
```

How should we handle that?

1. Leave as float64, specify the dtype to keep compat
2. Leave as float64, no dtype to generate a warning

The problem w/ 2 is that there's nothing the user can do to silence the warning.

2018-11-18 22:07 UTC, jreback commented
@TomAugspurger can you merge master

2018-11-19 12:18 UTC, TomAugspurger commented
There's a decent amount of work to do here to avoid the warnings
internally. Will try to make time.

On Sun, Nov 18, 2018 at 4:07 PM Jeff Reback <notifications@github.com>
wrote:

> @TomAugspurger <https://github.com/TomAugspurger> can you merge master
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/20802#issuecomment-439730129>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABQHIlxE1_nFXT33ZyVrGy5GKVNKLTv7ks5uwdopgaJpZM4Tgluf>
> .
>

2019-01-14 00:16 UTC, jreback commented
@TomAugspurger keep this one open?

2019-01-14 12:18 UTC, TomAugspurger commented
Probably not :/ I suppose we can just live with this. A little artifact of the time Series used to be an ndarray.

2019-01-14 12:18 UTC, closed without merging