Change _can_hold_na to a class attribute and document that it shouldn't be changed
pandas-dev/pandas pull request #20819
Opened 2018-04-25 16:11 UTC by Dr-Irv

- [x] closes #20761
- [x] tests added / passed
  - removed tests dependent on `_can_hold_na`
- [x ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry
  - not needed because it is part of `ExtensionArray` support new for v0.23

Replaces pull request #20815 (see discussion there for reasoning)

2018-04-25 18:12 UTC, TomAugspurger approved these changes
lgtm. Will wait a bit if @jorisvandenbossche or @jreback have thoughts.

2018-04-25 23:32 UTC, jreback requested changes

2018-04-25 23:32 UTC, jreback commented on pandas/tests/extension/base/interface.py
> +        assert data._can_hold_na  # Must be True
you can ``assert data._can_hold_na is True``, otherwise this is not strictly checking that it is an actual boolean True

2018-04-26 15:34 UTC, TomAugspurger commented
Nope, we're good. Thanks!.

2018-04-26 15:34 UTC, merged