Fix for handling duplicate column names in select_dtypes and get_dummies
pandas-dev/pandas pull request #20839
Opened 2018-04-27 07:48 UTC by kunalgosar

Functions `select_dtypes` and `get_dummies` previously failed on DataFrames with duplicate column names and had strange behavior as shown below. This PR fixes that strange behavior.

Previous behavior:

```
In [6]: df
Out[6]: 
  col1 col1
0    1    a
1    2    b

In [7]: df.select_dtypes(include=['int'])
Out[7]: 
Empty DataFrame
Columns: []
Index: [0, 1]

In [8]: pd.get_dummies(df)
Out[8]: 
   col1_('c', 'o', 'l', '1')  col1_('c', 'o', 'l', '1')
0                          1                          1
1                          1                          1
```

New behavior:

```
In [6]: df
Out[6]: 
  col1 col1
0    1    a
1    2    b

In [7]: df.select_dtypes(include=['int'])
Out[7]: 
   col1
0     1
1     2

In [8]: pd.get_dummies(df)
Out[8]: 
   col1  col1_a  col1_b
0     1       1       0
1     2       0       1
```

- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-04-27 10:43 UTC, jreback commented
does this have an open issue?

2018-04-27 10:49 UTC, jreback requested changes
looks ok, but need to have a look after you update comments

2018-04-27 10:49 UTC, jreback commented on pandas/core/reshape/reshape.py
> +            with_dummies = [data.select_dtypes(exclude=['object', 'category'])]
why did you add this?

2018-04-27 10:49 UTC, jreback commented on pandas/core/reshape/reshape.py
> +                if not len(item) == columns_to_encode.shape[1]:
are you sure this is correct?

2018-04-27 10:49 UTC, jreback commented on pandas/core/reshape/reshape.py
>              columns_to_encode = data.select_dtypes(
this is now not columns, so rename to something else

2018-04-27 10:49 UTC, jreback commented on pandas/tests/frame/test_dtypes.py
> +        df = DataFrame({'a': list('abc'),
add the PR number as a comment

2018-04-27 10:49 UTC, jreback commented on pandas/tests/frame/test_dtypes.py
> +                        'f': pd.date_range('now', periods=3).values})
this construction is actually not guaranteed under < py3.6, so use an OrderdDict

2018-04-27 10:49 UTC, jreback commented on pandas/tests/frame/test_dtypes.py
> +        e = DataFrame({'a': list(range(1, 4)),
e -> expected, r -> result

2018-04-27 10:49 UTC, jreback commented on pandas/tests/reshape/test_reshape.py
> +        df.columns = ["A", "A", "A"]
issue number

2018-05-04 10:27 UTC, jreback requested changes
looks good. some doc comments

2018-05-04 10:27 UTC, jreback commented on pandas/core/reshape/reshape.py
> +                include=['object', 'category'])
can you define these at the top of the function as they are used in 2 places

2018-05-04 10:27 UTC, jreback commented on pandas/core/reshape/reshape.py
> +            dummy = _get_dummies_1d(col[1], prefix=pre, prefix_sep=sep,
can you put a comment why are using col[1] here (IOW what is that)

2018-05-04 10:27 UTC, jreback commented on pandas/core/reshape/reshape.py
> -        if set(columns_to_encode) == set(data.columns):
can you add comments for these cases (IOW what they are for)

2018-05-04 10:28 UTC, jreback requested changes
need a whatsnew note as well, you can put in 0.23.0 (if you can update in next few days)

2018-05-04 21:36 UTC, kunalgosar commented
Thanks @jreback. I resolved comments and added the whatsnew note.

2018-05-05 01:50 UTC, kunalgosar commented
Rebased on master so checks pass now @jreback.

2018-05-05 12:58 UTC, jreback approved these changes

2018-05-05 12:59 UTC, merged

2018-05-05 12:59 UTC, jreback commented
thanks @kunalgosar nice patch!