ENH: linearly spaced date_range (GH 20808)
pandas-dev/pandas pull request #20846
Opened 2018-04-27 15:14 UTC by onnoeberhard

- [X] closes #20808
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

2018-04-27 17:02 UTC, mroeschke commented on pandas/tests/indexes/datetimes/test_date_range.py
> +    def test_date_range_convenience_periods(self):
Could you also test this with the `tz` arg specified? Would also be good to test a `tz` where there is a day light savings transition between `start` and `end`.

2018-04-27 18:36 UTC, jschendel commented on doc/source/whatsnew/v0.23.0.txt
> +- :func:`pandas.core.indexes.datetimes.date_range` now returns a linearly spaced DatetimeIndex if ``start``, ``stop``, and ``periods`` are specified, but ``freq`` is not. (:issue:`20808`)
- func:\`date_range\` should suffice here
- DatetimeIndex --> \`\`DatetimeIndex\`\`

2018-04-27 18:36 UTC, jschendel commented on pandas/core/indexes/datetimes.py
> +            and end is not None:
A little bit cleaner to use `if freq is None and com._all_not_none(periods, start, end):`

2018-04-27 18:36 UTC, jschendel commented on pandas/core/indexes/datetimes.py
> +        end = Timestamp(end)
`start` and `end` should be normalized if `normalize=True` is passed to `date_range`

2018-04-27 18:47 UTC, jschendel commented
For consistency, it seems like this behavior should also be implemented for `bdate_range`, `timedelta_range`, and `interval_range`.  Doesn't really make sense for `period_range`, since a freq is always required there, and can probably skip `cdate_range` since it's been deprecated (although not removed).

2018-04-27 22:16 UTC, pep8speaks commented
Hello @onnoeberhard! Thanks for updating the PR.



 - In the file [`pandas/tests/indexes/datetimes/test_date_range.py`](https://github.com/pandas-dev/pandas/blob/580bca2747b596e2d32e7863b0071be29ba52060/pandas/tests/indexes/datetimes/test_date_range.py), following are the PEP8 issues :

> [Line 189:10](https://github.com/pandas-dev/pandas/blob/580bca2747b596e2d32e7863b0071be29ba52060/pandas/tests/indexes/datetimes/test_date_range.py#L189): [E114](https://duckduckgo.com/?q=pep8%20E114) indentation is not a multiple of four (comment)
> [Line 189:10](https://github.com/pandas-dev/pandas/blob/580bca2747b596e2d32e7863b0071be29ba52060/pandas/tests/indexes/datetimes/test_date_range.py#L189): [E116](https://duckduckgo.com/?q=pep8%20E116) unexpected indentation (comment)
> [Line 193:14](https://github.com/pandas-dev/pandas/blob/580bca2747b596e2d32e7863b0071be29ba52060/pandas/tests/indexes/datetimes/test_date_range.py#L193): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four

2018-04-27 22:28 UTC, onnoeberhard commented
Alright, thank you for all the feedback. I have implemented almost everything mentioned, except for the implementation of a similar feature in the functions `bdate_range`, `timedelta_range` and `interval_range`, because I have not yet used these functions and don't know how to properly implement it in an intuitive way.

2018-04-30 00:07 UTC, jreback requested changes
also would be nice to add this to TDI

2018-04-30 00:07 UTC, jreback commented on pandas/core/indexes/datetimes.py
> +    # See https://github.com/pandas-dev/pandas/issues/20808
this needs to go in the DTI constructor itself. we already do some of this validation, it needs to fit in there. Further you don't need to worry about lots of other things that you are repeating, e.g. tz, which are already handled.

2018-05-01 18:08 UTC, onnoeberhard commented
I have moved everything to the DTI constructor. With that I have removed the functionality to declare kwargs to `to_datetime`, but I think it is much cleaner overall like this.

2018-05-03 10:41 UTC, jreback approved these changes

2018-05-03 10:42 UTC, merged

2018-05-03 10:42 UTC, jreback commented
thank @onnoeberhard