ENH: Add class to write da format 117 files
pandas-dev/pandas pull request #20844
Opened 2018-04-27 14:52 UTC by bashtage

Add export for dta 117 files which add support for long strings
Refactor StataWriter to simplify new writer

closes #16450

- [x] closes #16450
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-04-27 14:52 UTC, pep8speaks commented
Hello @bashtage! Thanks for submitting the PR.

 - In the file [`pandas/io/stata.py`](https://github.com/pandas-dev/pandas/blob/9717de4da43a7392e8b7096b34e0209669491efe/pandas/io/stata.py), following are the PEP8 issues :

> [Line 2110:17](https://github.com/pandas-dev/pandas/blob/9717de4da43a7392e8b7096b34e0209669491efe/pandas/io/stata.py#L2110): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare except'

2018-04-29 09:38 UTC, bashtage commented
Is it intentional that `stata.py` is not covered?  Seems a bit strange.

2018-04-29 23:59 UTC, jreback commented
> Is it intentional that stata.py is not covered? Seems a bit strange.

what does this mean? the coverage that prints on the issue is odd (and has always been that way), but you can click thru and see the actual reports.

2018-04-30 00:00 UTC, jreback requested changes

2018-04-30 00:00 UTC, jreback commented on pandas/core/frame.py
> +            format. Only available if version is 117.  Storign strings in the
Storing

2018-04-30 00:00 UTC, jreback commented on pandas/core/frame.py
> +            read by Stata 10 and later.  Version 117 can be read by Stata 13
should we just support version 117 and forward? how old are these respective versions?

2018-04-30 10:12 UTC, jreback commented on pandas/core/frame.py
> +            read by Stata 10 and later.  Version 117 can be read by Stata 13
how much simplfication do we get from only supporting new format?

2018-05-01 10:34 UTC, jreback requested changes
minor comments. Might consiser renaming StataWriter to StataWriter114 (and essentially make it private). Otherwise lgtm.

2018-05-01 10:34 UTC, jreback commented on pandas/io/stata.py
> +        assert self.nvar < 2 ** 16
maybe add a blank line before comments, easier to read

2018-05-01 10:34 UTC, jreback commented on pandas/tests/io/test_stata.py
> +from pandas._libs.tslib import NaT
import from pandas

2018-05-01 10:47 UTC, bashtage commented
> minor comments. Might consiser renaming StataWriter to StataWriter114 (and essentially make it private). Otherwise lgtm.

I think this would need a dep cycle since `StataWriter` has been public.  Can do this if you want.

2018-05-01 14:30 UTC, TomAugspurger commented on pandas/core/frame.py
> +        version : {114, 117}
Hmm, should these be strings? Is this exposed anywhere in stats itself? Do they use integers? (when I see version number, I think string).

2018-05-01 17:52 UTC, TomAugspurger commented on pandas/core/frame.py
> +        version : {114, 117}
Huh, https://www.stata.com/support/faqs/data-management/save-for-previous-version/ seems to suggest that stata uses integers? `version(13)`. OK then, let's follow that.

2018-05-01 17:59 UTC, TomAugspurger approved these changes
Couple small comments. OK to do as a followup (I'm tagging the RC momentarily.)

2018-05-01 17:59 UTC, TomAugspurger commented on pandas/core/frame.py
> +            raise ValueError('Only formats 114 and 117 supported.')
Would be nice to include the user passed `version` in the error message.

2018-05-01 17:59 UTC, TomAugspurger commented on pandas/tests/io/test_stata.py
> +        with warnings.catch_warnings(record=True) as w:  # noqa
What warnings are you catching here?

2018-05-01 18:02 UTC, TomAugspurger commented
@jreback are you OK with merging this as is? I'll fix the git conflict on merge.

2018-05-01 18:48 UTC, jreback commented
yep this is fine
if we need follow ups after RC that is fine

2018-05-01 18:55 UTC, TomAugspurger commented
K. @bashtage I'm going to fix the conflict and then merge. A followup PR would be welcome.

2018-05-01 18:57 UTC, merged