BUG: fix indexing.py to make a copy of the indices (#20852)
pandas-dev/pandas pull request #20855
Opened 2018-04-28 16:22 UTC by subhrm

- [x] closes #20852 
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

WIP. Reviewing the test cases and would add a test case to validate this fix.

2018-05-04 10:22 UTC, jreback requested changes
can you add

- whatsnew note
- tests (in tests/indexing/test_indexing.py)

2018-05-04 10:24 UTC, jreback requested changes

2018-05-07 16:55 UTC, subhrm commented on pandas/core/indexing.py
> +    else:
Thanks for your review comments. I have made the changes as suggested.

2018-05-07 16:56 UTC, subhrm commented on pandas/core/indexing.py
> +    else:
Would add new testcases for this change .

2018-06-06 13:28 UTC, jorisvandenbossche commented
@subhrm Can you update for @jreback 's questions:

* whatsnew note (a small note in v0.23.1.txt in the bug fixes section
* add a test (in tests/indexing/test_indexing.py). You can use the example in the issue, and then assert that the indexer array has not changed

2018-06-06 13:39 UTC, subhrm commented
@jorisvandenbossche sorry I could not devote any time for this. 
I would do the suggested changes and update by this weekend (10th June). 
Thanks for reminding me.

2018-07-17 06:32 UTC, subhrm commented
Implemented via PR #21867 . Closing this one.

2018-07-17 06:32 UTC, closed without merging