Fix #20744 . loffset ignored in upsample
pandas-dev/pandas pull request #20867
Opened 2018-04-29 16:21 UTC by johncant

- [X] closes #20744
- [X] 1 test updated
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

2018-04-29 23:53 UTC, jreback requested changes

2018-04-29 23:53 UTC, jreback commented on pandas/tests/test_resample.py
> +        expected_downsample = Series([s[0], s[1:6].mean(),
can you make a separate test instead

2018-04-29 23:53 UTC, jreback commented on doc/source/whatsnew/v0.23.0.txt
> +- Bug in :func:`DatetimeIndexResampler._upsample` where ``loffset`` was being ignored (:issue:`20744`)
should be a user visible note. users dont' know what ``_upsample`` is as its an internal method. pls rephrase.

2018-04-29 23:53 UTC, jreback commented on pandas/tests/test_resample.py
> +        expected_downsample = Series([s[0], s[1:6].mean(),
pls use result & expected rather than changing things

2018-04-30 06:40 UTC, johncant commented
Consider it done! I'll also rewrite the msg to include [BUG]

2018-04-30 16:40 UTC, johncant commented
Replaced by pull request #20884

2018-04-30 16:40 UTC, closed without merging