DOC: Improve the docstring of Str.contains()
pandas-dev/pandas pull request #20870
Opened 2018-04-29 19:05 UTC by Blair-Young

- [ ] closes #xxxx
- [ ] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

```############################################################################
################################## Validation ##################################
################################################################################

Errors found:
	Errors in parameters section
		Parameter "flags" description should start with capital letter
```
`Achieved through PyData 2018 pandas sprint.`

2018-04-29 19:14 UTC, Blair-Young commented
Unsure best way to phrase `flags` parameter as description starts with the ```re``` module.

2018-04-30 02:57 UTC, WillAyd requested changes
Thanks for submitting this

2018-04-30 02:57 UTC, WillAyd commented on pandas/core/strings.py
> +    Test if pattern or regex is contained within each string of a Series.
This method is used by `Index` as well which was removed here - please be sure to add that back

2018-04-30 02:57 UTC, WillAyd commented on pandas/core/strings.py
> +    Return boolean Series based on whether a given pattern or regex is
Related to comment above, this isn't always true

```python
index = pd.Index(['foo>>> index = pd.Index(['foo', 'bar', 'baz'])
>>> index.str.contains('a')
array([False,  True,  True])
```

2018-04-30 02:57 UTC, WillAyd commented on pandas/core/strings.py
>      Returns
Maybe use the Returns section from the below PR as reference

https://github.com/pandas-dev/pandas/pull/20491/files

2018-04-30 02:57 UTC, WillAyd commented on pandas/core/strings.py
> +        If True, assumes the passed-in pattern is a regular expression.\n
Rogue newline?

2018-04-30 03:10 UTC, WillAyd requested changes

2018-04-30 03:10 UTC, WillAyd commented on pandas/core/strings.py
> +        re module flags, e.g. re.IGNORECASE.
To suppress the warning just rewrite this as "Flags to pass through to the re module, e.g. re.IGNORECASE." or something similar

2018-04-30 03:10 UTC, WillAyd commented on pandas/core/strings.py
> +    >>> s.str.contains('og', na=False, regex=True)
These examples are good but some text to direct the user on what to look at preceding each would be helpful. For example here I would prepend something like:

```With the above examples, you'll note that NA values in the caller return `np.nan` by default and as a result cast the dtype of the returned object to `object`. You can control this behavior by specifying a an alternate `na` argument```

2018-04-30 03:10 UTC, WillAyd commented on pandas/core/strings.py
> +    Examples
Can you add examples for the `case` and `flags` parameters?

2018-05-03 07:09 UTC, Blair-Young commented
Hey @WillAyd I've tried to fix your correction. What's the next step?

2018-05-03 10:28 UTC, jreback approved these changes
lgtm. @TomAugspurger @jorisvandenbossche

2018-05-05 18:14 UTC, WillAyd approved these changes

2018-05-10 11:29 UTC, merged

2018-05-10 11:30 UTC, TomAugspurger commented
Thanks @Blair-Young!

2018-05-10 12:31 UTC, Blair-Young commented
Thanks @TomAugspurger looking forward to more.