Added docstring to Groupby mean
pandas-dev/pandas pull request #20910
Opened 2018-05-01 20:11 UTC by cxl923cc

Added examples of the usage and what is returned

2018-05-01 20:12 UTC, pep8speaks commented
Hello @cxl923cc! Thanks for submitting the PR.

 - In the file [`pandas/core/groupby/groupby.py`](https://github.com/pandas-dev/pandas/blob/f339b2cb795d25193d255379bbf52722b76f8b58/pandas/core/groupby/groupby.py), following are the PEP8 issues :

> [Line 1269:1](https://github.com/pandas-dev/pandas/blob/f339b2cb795d25193d255379bbf52722b76f8b58/pandas/core/groupby/groupby.py#L1269): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1280:1](https://github.com/pandas-dev/pandas/blob/f339b2cb795d25193d255379bbf52722b76f8b58/pandas/core/groupby/groupby.py#L1280): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1296:1](https://github.com/pandas-dev/pandas/blob/f339b2cb795d25193d255379bbf52722b76f8b58/pandas/core/groupby/groupby.py#L1296): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1300:80](https://github.com/pandas-dev/pandas/blob/f339b2cb795d25193d255379bbf52722b76f8b58/pandas/core/groupby/groupby.py#L1300): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 79 characters)
> [Line 1300:124](https://github.com/pandas-dev/pandas/blob/f339b2cb795d25193d255379bbf52722b76f8b58/pandas/core/groupby/groupby.py#L1300): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2018-05-01 21:35 UTC, Cheukting commented
Thanks for the PR! There is some PEP 8 problem (basically formatting issues) which needed to be fixed. Also you may want to use `git diff upstream/master -u -- "*.py" | flake8 --diff` to check if there's PEP 8 problem before pushing. Also, you may want to  use "DOC: update the pandas.core.groupby.GroupBy.mean docstring" as the PR title so developers knows exactly which method/functions you are updating the docstring.

2018-05-01 21:39 UTC, Cheukting requested changes

2018-05-01 21:39 UTC, Cheukting commented on pandas/core/groupby/groupby.py
You may want to put the Example at the end, see https://python-sprints.github.io/pandas/guide/pandas_docstring.html

2018-05-01 21:39 UTC, Cheukting commented on pandas/core/groupby/groupby.py
> +
You may want to put the Example at the end, see https://python-sprints.github.io/pandas/guide/pandas_docstring.html

2018-05-01 21:39 UTC, Cheukting commented on pandas/core/groupby/groupby.py
> +
May be you can try adding long summary and Parameters as well, see https://python-sprints.github.io/pandas/guide/pandas_docstring.html

2018-05-10 18:14 UTC, cxl923cc commented
This is my first pull request. Could someone please help to review the new commit I have made and let me know whether I should make any further change to the Docstring?

2018-05-12 13:45 UTC, jreback requested changes

2018-05-12 13:45 UTC, jreback commented on pandas/core/groupby/groupby.py
> +        Missing values are excluded in computing the mean.
blank line here for the Extended Summary

2018-05-12 13:45 UTC, jreback commented on pandas/core/groupby/groupby.py
> +        Example of groupby one column:the groups are stored as index in the result.
don't use underlines, rather use a blank line

2018-05-12 13:45 UTC, jreback commented on pandas/core/groupby/groupby.py
> +        Example of groupby one column:the groups are stored as index in the result.
make this a sentence.
Groubpy by one column. The result index are the group labels.

2018-07-07 22:41 UTC, jreback approved these changes

2018-07-07 22:42 UTC, merged

2018-07-07 22:42 UTC, jreback commented
thanks @cxl923cc and @mroeschke for the fixup!