BUG: Fix wrong khash method definition
pandas-dev/pandas pull request #20966
Opened 2018-05-06 08:01 UTC by Licht-T

- [x] closes #20722
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-05-07 10:08 UTC, jreback requested changes
can you add a whatsnew in bugs / indexing

2018-05-07 10:08 UTC, jreback commented on pandas/tests/indexing/test_loc.py
> +        assert 1 == s.loc[np.iinfo('uint64').max - 1]
can you construct the expected frame and user assert_series_equal

2018-05-07 10:08 UTC, jreback commented on pandas/tests/indexing/test_loc.py
> +        # GH20722
can you add a 1 line comment about what this is about

2018-05-07 14:01 UTC, Licht-T commented
Thanks @jreback, fixed!

2018-05-08 00:16 UTC, jreback approved these changes

2018-05-08 00:17 UTC, jreback commented
lgtm. ping on green. I pushed some cleaning of the test.

2018-05-08 10:35 UTC, merged

2018-05-08 10:35 UTC, jreback commented
thanks @Licht-T