BUG: Fix isna cannot handle ambiguous typed list
pandas-dev/pandas pull request #20971
Opened 2018-05-07 00:34 UTC by Licht-T

- [x] closes #20675
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-05-07 10:06 UTC, jreback requested changes
pls add a whatsnew note (bug fix / reshaping)

2018-05-07 10:06 UTC, jreback commented on pandas/core/dtypes/missing.py
> +    elif isinstance(obj, list):
can you make the same change in _isna_old

2018-05-07 13:38 UTC, Licht-T commented
Thanks @jreback, fixed!

2018-05-08 00:06 UTC, jreback approved these changes

2018-05-08 00:06 UTC, merged

2018-05-08 00:06 UTC, jreback commented
thanks @Licht-T