BUG: date_range linspace behavior respects tz
pandas-dev/pandas pull request #20988
Opened 2018-05-09 06:47 UTC by mroeschke

- [x] closes #20983
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry (addendum to the v0.23 whatsnew entry for this feature)

2018-05-09 07:08 UTC, jschendel commented
Beat me by a few minutes!

Can you modify the test that was originally written for this issue:

https://github.com/pandas-dev/pandas/blob/b3f07b2551b7eb40408ca28416ca5e21f8fb37b4/pandas/tests/indexes/datetimes/test_date_range.py#L165-L180

The first half looks to be redundant with your new test.  The timezone transition portion isn't being tested, as there's no `tm.assert_index_equal`.  It also looks wrong to me; periods is set to three, but the expected has 5 elements.  I think the correct expected is:

```python
DatetimeIndex(['2018-04-01 01:00:00+11:00', '2018-04-01 02:00:00+10:00',
               '2018-04-01 04:00:00+10:00'],
              dtype='datetime64[ns, Australia/Sydney]', freq=None)
```

2018-05-09 07:13 UTC, jschendel commented on pandas/tests/indexes/datetimes/test_date_range.py
> +        result = date_range(start, end, periods=3, tz='US/Eastern')
Might be beneficial to test when `start`/`end` are tz aware but not specifying the `tz` param for `date_range`, to ensure that `tz` inference from `start`/`end` is okay.

2018-05-09 10:26 UTC, jreback requested changes
lgtm. small comment by @jschendel

2018-05-09 10:26 UTC, jreback commented on pandas/core/indexes/datetimes.py
> +                # Create a linearly spaced date_range.
specifiy this is in local time

2018-05-10 10:26 UTC, jreback approved these changes

2018-05-10 10:26 UTC, merged

2018-05-10 10:26 UTC, jreback commented
thanks @mroeschke and @jschendel