DEPR: Add deprecated index attribute names to deprecation list
pandas-dev/pandas pull request #21125
Opened 2018-05-18 20:57 UTC by topper-123

In ipython, when you press tab (e.g. ``idx.<tab>`` a long list of depredations shows up:

```
C:\Users\TP\Miniconda3\envs\pandas-dev\lib\site-packages\jedi\evaluate\compiled\__init__.py:328: FutureWarning: Int64Index.base is deprecated and will be removed in a future version
  getattr(obj, name)
C:\Users\TP\Miniconda3\envs\pandas-dev\lib\site-packages\jedi\evaluate\compiled\__init__.py:328: FutureWarning: Int64Index.data is deprecated and will be removed in a future version
  getattr(obj, name)
C:\Users\TP\Miniconda3\envs\pandas-dev\lib\site-packages\jedi\evaluate\compiled\__init__.py:328: FutureWarning: Int64Index.flags is deprecated and will be removed in a future version
  getattr(obj, name)
C:\Users\TP\Miniconda3\envs\pandas-dev\lib\site-packages\jedi\evaluate\compiled\__init__.py:328: FutureWarning: Int64Index.itemsize is deprecated and will be removed in a future version
  getattr(obj, name)
C:\Users\TP\Miniconda3\envs\pandas-dev\lib\site-packages\jedi\evaluate\compiled\__init__.py:328: FutureWarning: Int64Index.strides is deprecated and will be removed in a future version
  getattr(obj, name)
```

With this PR we avoid getting that list of depredations in iPython.

I'm not sure if/where this should go in the whatsnew document.

2018-05-18 21:08 UTC, jreback requested changes
i think we have a test for exactly this but for Series (and for the main object not accessors)

can u add one here

2018-05-18 21:38 UTC, topper-123 commented
Not able to locate t. Where its name?

2018-05-18 23:16 UTC, jschendel commented
I think this is the test @jreback is referring to:
https://github.com/pandas-dev/pandas/blob/e033c0616158d3ba974456b4f84810492936b1fe/pandas/tests/series/test_api.py#L465-L474

There are also instances of this test (same name) for in `frame\test_api.py` and `categorical\test_warnings.py`

2018-05-19 09:06 UTC, topper-123 commented
test added. Is the location ok?

2018-05-19 09:47 UTC, topper-123 commented
BTW, @jschendel in line 474 in the ``test_api.py`` file you showed

https://github.com/pandas-dev/pandas/blob/e033c0616158d3ba974456b4f84810492936b1fe/pandas/tests/series/test_api.py#L472-L474

I think ``list(ip.Completer.completions('s.', 1))`` should be ``list(ip.Completer.completions('s.', 2))`` is order to produce the warnings, do you not agree? With ``1`` the tab is pressed at ``'s'`` which is too early.

2018-05-19 17:45 UTC, jreback commented
looks ok. can you add a whatsnew note

2018-05-19 21:06 UTC, topper-123 commented
green.

2018-05-21 10:44 UTC, jreback approved these changes

2018-05-21 10:44 UTC, merged

2018-05-21 10:44 UTC, jreback commented
thanks!

2018-05-28 07:20 UTC, jorisvandenbossche commented on pandas/core/accessor.py
> +        ['asobject', 'base', 'data', 'flags', 'itemsize', 'strides'])
BTW, this only adds them to Index, not to Series. 
So not sure why you did get warnings for Index, but not for Series in the first place.