BUG: Enable stata files to be written to buffers
pandas-dev/pandas pull request #21169
Opened 2018-05-22 09:02 UTC by bashtage

Enable support for general file-like objects when exporting stata files

- [x] closes #21041
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-05-23 10:42 UTC, jreback requested changes

2018-05-23 10:42 UTC, jreback commented on pandas/io/stata.py
> +            try:
can you move to a close method (or _close if needed), or is this the only place where things are needing to be closed? can you add some comments

2018-05-23 10:42 UTC, jreback commented on doc/source/whatsnew/v0.23.1.txt
> +- Bug in :meth:`DataFrame.to_stata` which prevented buffers from being directly written to (:issue:`21041`)
can you be slightly more descriptive here

2018-05-23 10:42 UTC, jreback commented on pandas/tests/io/test_stata.py
> +    @pytest.mark.parametrize('version', [114, 117])
it is worthwhile a replication of the OP?

2018-05-24 08:25 UTC, bashtage commented
@jreback I think I got them all.

2018-05-24 22:11 UTC, jreback approved these changes

2018-05-24 22:11 UTC, merged

2018-05-24 22:12 UTC, jreback commented
thanks @bashtage

always nice to have PRs from you!

2018-05-24 23:11 UTC, jreback commented
@jorisvandenbossche looks like master broke on geopandas test? https://travis-ci.org/pandas-dev/pandas/jobs/383432151

2018-05-25 12:07 UTC, jorisvandenbossche commented
> @jorisvandenbossche looks like master broke on geopandas test? https://travis-ci.org/pandas-dev/pandas/jobs/383432151

No, nothing pandas related, "just" conda forge dependency problems