Change nested_to_record to have a continue
pandas-dev/pandas pull request #21164
Opened 2018-05-22 04:39 UTC by ssikdar1

- [ ] closes #21158
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Continue after pop so you dont pop with the same key twice in a row

2018-05-22 13:11 UTC, ssikdar1 commented
>>  git diff upstream/master -u -- "*.py" | flake8 --diff
$ git diff upstream/master -u -- "*.py" | flake8 --diff
$

2018-05-22 13:30 UTC, pep8speaks commented
Hello @ssikdar1! Thanks for updating the PR.



 - In the file [`pandas/tests/io/json/test_normalize.py`](https://github.com/pandas-dev/pandas/blob/53d94dd2af8a8945d1ec048b919d2441c1fe97e6/pandas/tests/io/json/test_normalize.py), following are the PEP8 issues :

> [Line 391:27](https://github.com/pandas-dev/pandas/blob/53d94dd2af8a8945d1ec048b919d2441c1fe97e6/pandas/tests/io/json/test_normalize.py#L391): [E121](https://duckduckgo.com/?q=pep8%20E121) continuation line under-indented for hanging indent
> [Line 392:25](https://github.com/pandas-dev/pandas/blob/53d94dd2af8a8945d1ec048b919d2441c1fe97e6/pandas/tests/io/json/test_normalize.py#L392): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 393:23](https://github.com/pandas-dev/pandas/blob/53d94dd2af8a8945d1ec048b919d2441c1fe97e6/pandas/tests/io/json/test_normalize.py#L393): [E121](https://duckduckgo.com/?q=pep8%20E121) continuation line under-indented for hanging indent
> [Line 395:11](https://github.com/pandas-dev/pandas/blob/53d94dd2af8a8945d1ec048b919d2441c1fe97e6/pandas/tests/io/json/test_normalize.py#L395): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 398:78](https://github.com/pandas-dev/pandas/blob/53d94dd2af8a8945d1ec048b919d2441c1fe97e6/pandas/tests/io/json/test_normalize.py#L398): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 399:14](https://github.com/pandas-dev/pandas/blob/53d94dd2af8a8945d1ec048b919d2441c1fe97e6/pandas/tests/io/json/test_normalize.py#L399): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 399:80](https://github.com/pandas-dev/pandas/blob/53d94dd2af8a8945d1ec048b919d2441c1fe97e6/pandas/tests/io/json/test_normalize.py#L399): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 400:14](https://github.com/pandas-dev/pandas/blob/53d94dd2af8a8945d1ec048b919d2441c1fe97e6/pandas/tests/io/json/test_normalize.py#L400): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 400:80](https://github.com/pandas-dev/pandas/blob/53d94dd2af8a8945d1ec048b919d2441c1fe97e6/pandas/tests/io/json/test_normalize.py#L400): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 400:81](https://github.com/pandas-dev/pandas/blob/53d94dd2af8a8945d1ec048b919d2441c1fe97e6/pandas/tests/io/json/test_normalize.py#L400): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 401:14](https://github.com/pandas-dev/pandas/blob/53d94dd2af8a8945d1ec048b919d2441c1fe97e6/pandas/tests/io/json/test_normalize.py#L401): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 402:13](https://github.com/pandas-dev/pandas/blob/53d94dd2af8a8945d1ec048b919d2441c1fe97e6/pandas/tests/io/json/test_normalize.py#L402): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation

2018-05-22 16:26 UTC, WillAyd requested changes
Thanks for the change - you can add a whatsnew for v0.23.1

2018-05-22 16:26 UTC, WillAyd commented on pandas/io/json/normalize.py
>                  if v is None:  # pop the key if the value is None
Perhaps instead of continue this should just be `elif`?

2018-05-23 01:06 UTC, ssikdar1 commented
can you take a look at my newest commit?

2018-05-23 01:15 UTC, ssikdar1 commented
Can you check my latest commits? I changed it to not use a continue.

Also changed the whatsnew as well.

2018-05-23 02:55 UTC, WillAyd requested changes

2018-05-23 02:55 UTC, WillAyd commented on pandas/io/json/normalize.py
> +                else:
Use elif instead of a separate else and if

2018-05-23 10:35 UTC, ssikdar1 commented
kk, changed to elif

2018-05-23 10:46 UTC, jreback requested changes

2018-05-23 10:46 UTC, jreback commented on doc/source/whatsnew/v0.23.1.txt
> +- fix normalize to not except when json_normalize is fed a key with null value on inner most key (:issue:`21158`)
move to IO section, use a ref to ``json_normalize``.  see if you can describe this is more plain english.

2018-05-24 02:40 UTC, ssikdar1 commented
Moved into the I/O section in whatsnew. Changed the message hopefully its clearer.

2018-05-24 08:06 UTC, WillAyd requested changes

2018-05-24 08:06 UTC, WillAyd commented on doc/source/whatsnew/v0.23.1.txt
> +- bug in :meth:`nested_to_record` when :meth:`json_normalize` was called with certain nested jsons  (:issue:`21158`)
Perhaps better said "Bug in ... with None values in nested levels"

2018-05-24 08:06 UTC, WillAyd commented on pandas/tests/io/json/test_normalize.py
> +    def test_nonetype_inner_most_level(self):
Can you check if we have a test case to handle None values that show up in the initial level?

2018-05-24 11:15 UTC, ssikdar1 commented
@WillAyd 

>> Can you check if we have a test case to handle None values that show up in the initial level?

These test case below have a json list with a key as None in the initial level of a json.

https://github.com/pandas-dev/pandas/blob/master/pandas/tests/io/json/test_normalize.py#L354

  data = [
            {'info': None,
             'author_name':
             {'first': 'Smith', 'last_name': 'Appleseed'}
             },
            {'info':
                {'created_at': '11/08/1993', 'last_updated': '26/05/2012'},
             'author_name':
                {'first': 'Jane', 'last_name': 'Doe'}
             }
        ]

https://github.com/pandas-dev/pandas/blob/master/pandas/tests/io/json/test_normalize.py#L58

[
        {'info': None},
        {'info':
            {'created ...

2018-05-24 11:56 UTC, jreback requested changes

2018-05-24 11:56 UTC, jreback commented on doc/source/whatsnew/v0.23.1.txt
> +- bug in :meth:`nested_to_record` when :meth:`json_normalize` was called with None values in nested levels  (:issue:`21158`)
nested_to_record is not public, don't use it here

use double backticks around None

say nested levels in JSON

2018-05-24 15:31 UTC, WillAyd requested changes

2018-05-24 15:31 UTC, WillAyd commented on doc/source/whatsnew/v0.23.1.txt
> +- bug when :meth:`json_normalize` was called with `None` values in nested levels in JSON  (:issue:`21158`)
Capitalize "Bug" and as Jeff mentioned use double backticks around None, not just single

2018-05-24 15:31 UTC, WillAyd commented on pandas/tests/io/json/test_normalize.py
> +    def test_nonetype_inner_most_level(self):
Thanks for checking that we had a test to cover None at the top-most level. I suppose it makes sense to test None at the deepest level (which you have) and also somewhere in the middle, to make sure it doesn't mess up subsequent un-nesting operations.

Can you at least add a test with None in one of the middle layers? You can probably simplify the example below (doesn't need to be a direct copy/paste from the issue) and use parametrization to re-use the logic for different inputs (i.e. one with None at the deepest level, one with None somewhere in the middle).  Depending on how that looks maybe you want to even move the example with None at the top level here as well

2018-05-26 13:42 UTC, ssikdar1 commented
>> Can you at least add a test with None in one of the middle layers? 
I changed the test to be a test with None at multiple levels.

+        data = {
 +            "id": None,
 +            "location": {
 +                "id": None,
 +                "country": {
 +                    "id": None,
 +                    "state": {
 +                        "id": None,
 +                        "town.info": {
 +                            "region": None,
 +                            "x": 49.151580810546875,
 +                            "y": -33.148521423339844,
 +                            "z": 27.572303771972656}}}
 +            }
 +        }

Capitalized the b in Bug and put None in ticks

2018-05-29 00:45 UTC, jreback requested changes

2018-05-29 00:45 UTC, jreback commented on doc/source/whatsnew/v0.23.1.txt
> +- Bug when :meth:`json_normalize` was called with `None` values in nested levels in JSON  (:issue:`21158`)
this wont' render, you need pandas.io.json.json_normalize I think

2018-05-29 00:45 UTC, jreback commented on doc/source/whatsnew/v0.23.1.txt
> +- Bug when :meth:`json_normalize` was called with `None` values in nested levels in JSON  (:issue:`21158`)
use double back ticks around ``None``

2018-05-29 00:45 UTC, jreback commented on pandas/tests/io/json/test_normalize.py
> +            "id": None,
does this have the same result if id is NOT repeated (with None), just missing at various levels? e.g. try with a single id with None at the top and bottom levels (in another case, leave this one as well)

2018-05-29 00:45 UTC, jreback commented
pls rebase as well

2018-06-04 21:31 UTC, jreback approved these changes

2018-06-04 21:33 UTC, jreback commented
looks ok to me. @WillAyd pls merge when you are satisifed.

2018-06-04 21:45 UTC, WillAyd commented
@jreback somewhat conflicted on this. This PR certainly fixes the issue at hand, but what is the point of us dropping `None` values at the top level of the JSON yet maintaining it at deeper levels? Seems like it would be more consistent from an end user perspective to maintain at all levels and leave it to them to explicitly drop if they wanted.

Could probably go forward with this for 0.23.1 as the bug fix but then revisit top level `None`-handling for 0.24.0?

2018-06-04 21:52 UTC, jreback commented
@WillAyd hmm, that's a good point. shouldn't ``id`` be in the expected? why are we dropping it at all? yeah that sees wrong

2018-06-04 22:03 UTC, WillAyd commented
As @ssikdar1 points out it does stem from #20030, though in reading through that and the subsequent PR I think it is confusing what was actually being addressed. The PR would imply that automatically dropping the top-level `None` value is a feature, though I would argue that's not desirable and is in fact a bug.

2018-06-07 11:02 UTC, jreback commented
@ssikdar1 can you rebase

@WillAyd ok with this?

2018-06-07 15:58 UTC, WillAyd commented
Yep we can go with this for now. I'll open a separate issue for the top-level None parsing

2018-06-07 15:58 UTC, merged

2018-06-07 15:59 UTC, WillAyd commented
Thanks @ssikdar1 !

2018-06-07 15:59 UTC, ssikdar1 commented
No problem!