BUG: Should not raises errors in .set_names and comparison methods for MultiIndex with nlevels == 1
pandas-dev/pandas pull request #21182
Opened 2018-05-23 18:28 UTC by KalyanGokhale

- [x] closes #21149 
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-05-23 18:54 UTC, KalyanGokhale commented
@toobaz have made necessary updates for #21149 

original issue with set_names is fixed

Also, with the previous code snippet in `def cmp_method` it raised `ValueError` for comparisons of MultiIndex with nlevels == 1, which was inconsistent with behaviour for MultiIndex with nlevels > 1 - this has now been fixed

there is some conflict with file `whatsnew/v0.23.1.txt` that I was not able to resolve - and it is failing the `continuous-integration/appveyor/pr` check - please can you help resolve it?

2018-05-24 01:56 UTC, KalyanGokhale commented
Resolved the earlier conflict with `whatsnew` file

2018-05-24 05:45 UTC, KalyanGokhale commented
Will check the test failure and resubmit after necessary edits

2018-05-24 12:03 UTC, jreback requested changes
you are doing 2 different changes here which are unreleated, break this in to 2 PRs

2018-05-24 12:03 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        (pd.MultiIndex.from_product([[0, 1], [1, 0]]), pd.Series(range(4)), 4),
don't create a variable here, just put it directly in the parametrize (see how to format it from other tests)

2018-05-24 12:03 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        # GH 21149 - change in 'def cmp_method()'
this is a non-sensical comment, be more descriptive.

2018-05-24 12:03 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +    def test_multiindex_set_names(self):
put this near the other tests for set_names

2018-05-24 12:03 UTC, jreback commented on pandas/tests/indexes/test_multi.py
> +        result = pd.Series(midx == midx)
not really clear what you are testing, this is way too dense. put blank lines and a comment in between cases.

2018-05-24 18:35 UTC, KalyanGokhale commented
@jreback Thanks for the review - have split this into two PRs (#21195 and #21196). Have also made the suggested edits. Closing this PR.

2018-05-24 18:35 UTC, closed without merging