BUG: Fix handling of encoding for the StataReader #21244
pandas-dev/pandas pull request #21246
Opened 2018-05-29 13:08 UTC by adrian-castravete

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-05-30 10:46 UTC, jreback requested changes
is it possible include / and/or generate a utf-8 encoded file for testing?

2018-05-30 10:46 UTC, jreback commented on doc/source/whatsnew/v0.24.0.txt
> +  encoding.
add the issue number

2018-05-30 10:47 UTC, jreback commented
@bashtage can you have a look

2018-05-30 10:51 UTC, bashtage commented
You need to add a small Stata produce dta file that can replicate the issue and that this or fixes. Then please add a test that reads this dta file. It needs to be produced by Stata and not pandas.

2018-05-30 10:52 UTC, bashtage commented
118 does support utf8. But this needs to be tested using a real Stata file with both fixed width utf8 strings and StrL utf8 characters, and numbers.

2018-05-30 11:13 UTC, adrian-castravete commented on doc/source/whatsnew/v0.24.0.txt
> +  encoding.
Adding now.

2018-05-30 11:13 UTC, adrian-castravete commented
I see. I thought that https://github.com/pandas-dev/pandas/blob/master/pandas/tests/io/data/stata14_118.dta contains Unicode, since the test passes with unicode characters. And the `TestStata.test_read_dta18` test from https://github.com/pandas-dev/pandas/blob/master/pandas/tests/io/test_stata.py has a check for that.
Though indeed I do not know if the generated file was made by Stata or not.

Unfortunately I don't own a copy of the software and it's neither in my _field_ to work with stata files as a Scientist/Statician. :)
My use case is for a converter for a simple view of the file.

2018-05-30 11:41 UTC, bashtage commented
It possible the standard strings might be latin-1 not unicode. Are you sure
that the reader doesn't already read utf8 without passing an encoding? The
dta 118 spec says all strings are unicode and so this suggests that the
encoding is always utf8 irrespective of the one passed in. If so, then the
reader shouldn't be changed and a note should be added that encoding is
ignored for 118 files.

More generally I think reader should remove encoding and always use latin-1
for dta <118 and utf8 for 118.

On Wed, May 30, 2018, 13:14 Adrian Castravete <notifications@github.com>
wrote:

> I see. I thought that
> https://github.com/pandas-dev/pandas/blob/master/pandas/tests/io/data/stata14_118.dta
> contains Unicode, since the test passes with unicode characters. And the
> TestStata.test_read_dta18 test from
> https://github.com/pandas-dev/pandas/blob/master/pandas/tests/io/test_stata.py
> has a check for that.
> Though indeed I do not know if the generated file was made by Stata or not.
>
> Unfortunately I don't own a copy of the software and it's neither in my
> *field* to work with stata files as a Scientist/Statician. :)
> My use case is for a converter for a simple view of the file.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/21246#issuecomment-393123217>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFU5Rc-jrlC4-5xNhTVXzwoz0Zpbx14eks5t3n8KgaJpZM4URdVo>
> .
>

2018-05-30 11:49 UTC, adrian-castravete commented
When I tried `encoding` the string with unicode and then decoding it with `latin-1` the string was different, It showed two weird characters instead of the expected `Ü`.

As for the `encoding` argument: I agree if the specs say that 118 is always Unicode then it would make sense to add the necessary ifs where applicable. I've seen parts of the code where the encoding gets set to `latin-1`. 

If the encoding is to be determined via the version number, then this argument should also be removed and everything else like _documentation_ or _tests_ should be changed to reflect this.

2018-05-30 12:55 UTC, bashtage reviewed
Overall I think the encoding should be changd form settable to not settable.  This will require a deprecation in StataReader.  Users should not be encouraged to set encoding in `read_stata` since it isn't really settable (either latin-1 or utf-8)

2018-05-30 12:55 UTC, bashtage commented on pandas/io/stata.py
> +                   'iso8859-1', '8859', 'cp819', 'latin', 'latin1', 'L1',
These are not in general valid.  The set of valid depends on the reader.  For < 118 it is  

```
('ascii', 'us-ascii', 'latin-1', 'latin_1', 'iso-8859-1',
'iso8859-1', '8859', 'cp819', 'latin', 'latin1', 'L1')
```

for 118 it is `'utf-8', 'utf8'`.

2018-05-30 12:55 UTC, bashtage commented on pandas/io/stata.py
> +        return s.decode(self._encoding or self._default_encoding)
This should not be changed.

2018-05-30 12:55 UTC, bashtage commented on pandas/tests/io/test_stata.py
> +    def read_dta(self, file, encoding='latin-1'):
Should use `None` as encoding so it can be overridden by the reader depending on the dta version.

2018-05-30 12:55 UTC, bashtage commented on pandas/tests/io/test_stata.py
> +        return read_stata(file, convert_dates=True, encoding=encoding)
Same.

2018-05-30 13:10 UTC, bashtage commented
I took a look at the dta spec and it is stricter than pandas enforces. dta < 118 claim to use ASCII only although Stata internally displays and works with latin-1.  dta 118 is utf-8 only.

2018-06-06 15:51 UTC, bashtage commented
@adrian-castravete Master just got updated with a fix for this. If you have a chance could you try it out with your dta file?  It should always use the correct encoding (automatically) now. If it fails, we might need to look into your dta file.

2018-06-12 09:54 UTC, bashtage commented
I think this has been resolved in master.

2018-06-12 11:02 UTC, jreback commented
deprecated encoding by #21400 (and bug is already fixed in master)

2018-06-12 11:02 UTC, closed without merging