DOC: Fixing 'a la' confusion in series.quantile documentation
pandas-dev/pandas pull request #21293
Opened 2018-06-02 05:23 UTC by uds5501

Just stating that numpy.percentile also offers something similar to this

- [x] closes #21292
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] Just clarified quantile doc a bit

2018-06-02 23:07 UTC, WillAyd requested changes

2018-06-02 23:07 UTC, WillAyd commented on pandas/core/series.py
> +        (you can also see numpy.percentile, much similar like series.quantile).
Instead of this just add numpy.percentile to the See Also section

2018-06-04 12:05 UTC, jorisvandenbossche commented
@uds5501 general feedback: can you give the PR a more informative title? (you can still edit the title, see 'edit' button at the right of it)

2018-06-06 07:14 UTC, uds5501 commented
@WillAyd  Did the update you asked for. Now numpy.percentile is included in See also section

2018-06-06 07:31 UTC, jorisvandenbossche approved these changes

2018-06-06 07:31 UTC, merged

2018-06-06 07:31 UTC, jorisvandenbossche commented
@uds5501 Thanks a lot!