Update test_pivot.py
pandas-dev/pandas pull request #21393
Opened 2018-06-08 19:31 UTC by uds5501

BUG: Incorrect values shown by pivot_table() #21378

- [ ] closes #21378
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Just added a new test to verify the included patch in `master` branch

2018-06-08 23:31 UTC, gfyoung approved these changes
@uds5501 : This is awesome.  Thanks!

2018-06-13 11:10 UTC, jreback requested changes

2018-06-13 11:10 UTC, jreback commented on pandas/tests/reshape/test_pivot.py
> +        # gh-21133
can you just add this example into an existing test (the one below looks like a candidate).

2018-06-13 11:22 UTC, pep8speaks commented
Hello @uds5501! Thanks for updating the PR.

 - In the file [`pandas/tests/reshape/test_pivot.py`](https://github.com/pandas-dev/pandas/blob/4bab2bd1eed45593c18ff852a7aa1fc9193243ab/pandas/tests/reshape/test_pivot.py), following are the PEP8 issues :

> [Line 145:1](https://github.com/pandas-dev/pandas/blob/4bab2bd1eed45593c18ff852a7aa1fc9193243ab/pandas/tests/reshape/test_pivot.py#L145): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 164:1](https://github.com/pandas-dev/pandas/blob/4bab2bd1eed45593c18ff852a7aa1fc9193243ab/pandas/tests/reshape/test_pivot.py#L164): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2018-06-15 04:08 UTC, uds5501 commented
@jreback fixed the errors in the test. Any other improvement required?

2018-06-15 17:33 UTC, jreback approved these changes

2018-06-15 17:33 UTC, merged

2018-06-15 17:33 UTC, jreback commented
thanks @uds5501