Two tests didn't properly assert an exception was raised. Fixed.
pandas-dev/pandas pull request #21409
Opened 2018-06-10 12:28 UTC by akaihola

- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-06-10 12:47 UTC, jreback requested changes

2018-06-10 12:47 UTC, jreback commented on doc/source/whatsnew/v0.24.0.txt
> +- fixed two test cases which asserted an exception message but failed to make sure that an exception was actually raised
not necessary for test changes

2018-06-10 12:47 UTC, jreback commented on pandas/tests/io/parser/c_parser_only.py
> +            with pytest.raises(pd.errors.ParserError) as excinfo:
can u parametrize this test

2018-06-10 14:54 UTC, akaihola commented on doc/source/whatsnew/v0.24.0.txt
> +- fixed two test cases which asserted an exception message but failed to make sure that an exception was actually raised
Ok, reverted.

2018-06-10 14:54 UTC, akaihola commented on pandas/tests/io/parser/c_parser_only.py
> +            with pytest.raises(pd.errors.ParserError) as excinfo:
Parametrized in f47437e.

2018-06-10 18:10 UTC, gfyoung approved these changes
Nice catch!

cc @jreback

2018-06-12 11:37 UTC, merged

2018-06-12 11:37 UTC, jreback commented
thanks @akaihola; slight change to use pytest ids, otherwise nice catch! keep em coming!