fix DateOffset eq to depend on normalize attr
pandas-dev/pandas pull request #21404
Opened 2018-06-10 02:09 UTC by jbrockmendel

This has a bullet point in #18854 but doesn't appear to have its own issue.

Current:
```
now = pd.Timestamp.now()
off = pd.offsets.Week(n=1, normalize=False)
normed = pd.offsets.Week(n=1, normalize=True)

>>> now + off == now + normed
False
>>> off == normed  # PR changes this comparison to False
True
```

- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-06-10 02:11 UTC, jbrockmendel commented on pandas/tests/tseries/offsets/test_offsets.py
> +        assert offset != offset2
After substituting in `self._offset` for `BDay`, this test is identical to 5 others in this file.  I'm putting together a separate PR to try to de-duplicate and parametrize a bunch of things like this.

2018-06-10 05:05 UTC, gfyoung commented
> This has a bullet point in #18854 but doesn't appear to have its own issue.

@jbrockmendel : How about this one here: https://github.com/pandas-dev/pandas/issues/17689?

2018-06-10 05:07 UTC, gfyoung approved these changes
This looks good to me!

cc @jreback

2018-06-12 11:43 UTC, jreback requested changes
looks good. minor comment. ping on green.

2018-06-12 11:43 UTC, jreback commented on doc/source/whatsnew/v0.24.0.txt
> +- Fixed Bug where two :class:`DateOffset` objects with different `normalize` attributes could evaluate as equal (:issue:`21404`)
double backticks on normalize

2018-06-13 10:55 UTC, jreback commented
I merged something which now causes a conflict here. @jbrockmendel can you rebase. @gfyoung can merge on green.

2018-06-13 10:56 UTC, jreback approved these changes

2018-06-13 19:59 UTC, merged

2018-06-13 19:59 UTC, gfyoung commented
Thanks @jbrockmendel !