perf improvements in tslibs.period
pandas-dev/pandas pull request #21447
Opened 2018-06-12 16:49 UTC by jbrockmendel

Removes an unnecessary call to `frequencies.to_offset`, one of the last few non-cython dependencies in the file.

will post asv results when available.

2018-06-12 16:50 UTC, jbrockmendel commented on pandas/_libs/tslibs/period.pyx
> -            if isinstance(offset, offsets.Tick):
This along with the line above is redundant; `isinstance(offset, offsets.Tick)` if and only if `isinstance(self.freq, offsets.Tick)`.

2018-06-13 06:27 UTC, gfyoung commented
> will post asv results when available.

@jbrockmendel : `whatsnew` entry in `0.24.0` + perf test would also be good here.

2018-06-13 10:31 UTC, jreback requested changes
+ @gfyoung comments. (just see if we have an asv, you can run them and run report and significant diffs)

2018-06-13 10:31 UTC, jreback commented on pandas/_libs/tslibs/period.pyx
> +        elif getattr(other, "_typ", None) == "dateoffset":
maybe should add an is_offset_object in util.pxd

2018-06-13 23:00 UTC, jbrockmendel commented
as isn't showing much (recall it is wonky on my machine for reasons unknown)

```
taskset 6 asv continuous -f 1.1 -E virtualenv master HEAD -b period
[...]
    before     after       ratio
  [defdb34b] [daf9aaf7]
-    3.26ms     2.82ms      0.87  period.PeriodIndexConstructor.time_from_pydatetime('D')

    before     after       ratio
  [defdb34b] [daf9aaf7]
+   87.34ms   147.38ms      1.69  gil.ParallelDatetimeFields.time_datetime_to_period
+  118.47ms   133.50ms      1.13  gil.ParallelDatetimeFields.time_period_to_datetime
+   35.94ms    39.66ms      1.10  period.DataFramePeriodColumn.time_setitem_period_column
-   66.75μs    60.54μs      0.91  period.PeriodProperties.time_property('min', 'start_time')
-   75.69μs    68.21μs      0.90  period.PeriodProperties.time_property('M', 'end_time')

    before     after       ratio
  [defdb34b] [daf9aaf7]
+  884.44ns     1.00μs      1.13  period.PeriodProperties.time_property('min', 'week')
-  143.83ms   116.09ms      0.81  gil.ParallelDatetimeFields.time_period_to_datetime
-  143.24ms    93.98ms      0.66  gil.ParallelDatetimeFields.time_datetime_to_period

    before     after       ratio
  [defdb34b] [daf9aaf7]
+  123.27ms   164.93ms      1.34  gil.ParallelDatetimeFields.time_period_to_datetime
-   19.73μs    17.71μs      0.90  period.PeriodUnaryMethods.time_asfreq('M')
-    1.03μs   879.73ns      0.85  period.PeriodProperties.time_property('M', 'is_leap_year')

    before     after       ratio
  [defdb34b] [daf9aaf7]
+  112.56ms   125.62ms      1.12  gil.ParallelDatetimeFields.time_datetime_to_period
-   40.44ms    36.20ms      0.89  period.DataFramePeriodColumn.time_setitem_period_column
```

2018-06-14 10:12 UTC, jreback requested changes

2018-06-14 10:12 UTC, jreback commented on pandas/_libs/tslibs/period.pyx
> +        elif getattr(other, "_typ", None) == "dateoffset":
can you do this

2018-06-15 17:18 UTC, jreback approved these changes

2018-06-15 17:19 UTC, merged

2018-06-15 17:19 UTC, jreback commented
thanks!