BUG: Fix Index construction when given empty generator (#21470).
pandas-dev/pandas pull request #21481
Opened 2018-06-14 17:26 UTC by Liam3851

- [ ] closes #21470 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-06-14 19:00 UTC, mroeschke commented on pandas/tests/indexes/test_base.py
> +    def test_constructor_empty_list(self):
Could you combine this test with the one below with `pytest.mark.paremeterize` over `skip_index_keys` and the empty list and generator?

2018-06-14 19:13 UTC, mroeschke commented
Maybe also worthwhile to include a test for `iter([])` as well.

2018-06-14 20:10 UTC, Liam3851 commented
@mroeschke Thanks--good call on including iter([]) in tests- turns out calling CategoricalIndex on any non-generator iterator was broken.

2018-06-15 16:57 UTC, jreback requested changes
lgtm. pls add a whatsnew note. 0.23.2 is ok, bug fix in reshaping or conversions

2018-06-15 17:01 UTC, mroeschke commented
Just needs a whatsnew entry (0.23.2) otherwise LGTM.

2018-06-18 22:43 UTC, jreback approved these changes

2018-06-18 22:43 UTC, merged

2018-06-18 22:43 UTC, jreback commented
thanks @Liam3851