Tseries fixtures docstrings
pandas-dev/pandas pull request #21496
Opened 2018-06-15 12:08 UTC by ivergara

- [ ] closes #19159
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-06-15 16:26 UTC, jreback requested changes

2018-06-18 15:48 UTC, ivergara commented on pandas/tests/tseries/conftest.py
> +    """
Also will I need to change the reference to the `tz` fixture to the `tz_naive_fixture` right?

2018-06-22 23:22 UTC, jreback commented on pandas/tests/tseries/conftest.py
> +    """
yes

2018-07-05 16:39 UTC, pep8speaks commented
Hello @ivergara! Thanks for updating the PR.

 - In the file [`pandas/conftest.py`](https://github.com/pandas-dev/pandas/blob/8bd146384393e0dac70ba6b2d2a1993b8d85a3de/pandas/conftest.py), following are the PEP8 issues :

> [Line 143:80](https://github.com/pandas-dev/pandas/blob/8bd146384393e0dac70ba6b2d2a1993b8d85a3de/pandas/conftest.py#L143): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)



 - In the file [`pandas/tests/indexes/datetimes/test_ops.py`](https://github.com/pandas-dev/pandas/blob/8bd146384393e0dac70ba6b2d2a1993b8d85a3de/pandas/tests/indexes/datetimes/test_ops.py), following are the PEP8 issues :

> [Line 266:80](https://github.com/pandas-dev/pandas/blob/8bd146384393e0dac70ba6b2d2a1993b8d85a3de/pandas/tests/indexes/datetimes/test_ops.py#L266): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)

2018-07-08 16:37 UTC, jbrockmendel commented
LGTM.  Will merge this evening unless there's an objection.

2018-07-08 20:48 UTC, jreback approved these changes

2018-07-08 20:48 UTC, jreback commented
lgtm. merge away.

2018-07-08 22:03 UTC, merged

2018-07-08 22:03 UTC, jreback commented
thanks!

2018-07-09 19:34 UTC, ivergara commented
Sure! Hope to keep contributing.