BUG: Series.combine_first with datetime-tz dtype (#21469)
pandas-dev/pandas pull request #21544
Opened 2018-06-19 15:38 UTC by Liam3851

- [x ] closes #21469 
- [x ] tests added / passed
- [x ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-06-19 20:40 UTC, jreback requested changes

2018-06-19 20:40 UTC, jreback commented on pandas/core/series.py
> +        if needs_i8_conversion(this.dtype):
you can just use the in-built 

``other.where(isna(this), this)`` which already knows how to handle the dtypes

2018-06-20 10:01 UTC, jreback commented on pandas/core/series.py
> +        if needs_i8_conversion(this.dtype):
then convert using ``pd.Index`` and use ``.where``

2018-06-20 10:10 UTC, jreback commented on pandas/core/series.py
> +        if needs_i8_conversion(this.dtype):
really would prefer to fix #21546 first in any event.

2018-06-27 19:11 UTC, closed without merging

2018-06-27 19:11 UTC, Liam3851 commented
Closing this PR. Will open a new one that attempts to fix #21546 in addition to #21469,