BUG: Series dot product __rmatmul__ doesn't allow matrix vector multiplication
pandas-dev/pandas pull request #21578
Opened 2018-06-21 19:52 UTC by minggli

- [x] closes #21530 
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

the new __rmatmul__ implementation in Series seems to be missing matrix vector multiplication case as raised in the issue in question. Only inner product of two vectors was supported in __rmatmul__ method.

This PR uses the same implementation in DataFrame to add support in Series and test case.

2018-06-21 20:43 UTC, gfyoung commented
@minggli : Looks like a good start!  Can we also add a `whatsnew` too?

2018-06-21 20:43 UTC, gfyoung commented on pandas/tests/series/test_analytics.py
> +        # np.array (matrix) @ Series (__rmatmul__)
Can you reference the issue number too.

2018-06-21 22:01 UTC, minggli commented
raised an issue https://github.com/pandas-dev/pandas/issues/21581 regarding error message when `__rmatmul__` is called in dataframe and series. as dot method is implemented treating dataframe or series as left. when `__rmatmul__` is called the error message doesn't work well.

need advice. fix it in the same PR and how to do that or separately.

2018-06-22 10:23 UTC, jreback requested changes

2018-06-22 10:24 UTC, jreback requested changes

2018-06-22 12:15 UTC, minggli commented on pandas/tests/series/test_analytics.py
> +        result = operator.matmul(a.values.tolist(), a)
np.array @ Series should call `__rmatmul__`, so either list or np.array should be the same, i.e. calling `__rmatmul__`
np.array @ DataFrame however only calls `np.array.__matmul__`

actioned.

2018-06-22 22:59 UTC, jreback approved these changes

2018-06-22 22:59 UTC, merged

2018-06-22 22:59 UTC, jreback commented
thanks @minggli very nice

2018-06-23 07:34 UTC, minggli commented
Thanks @jreback and @gfyoung