ENH: pivot/groupby index with nan (GH3729)
pandas-dev/pandas pull request #21669
Opened 2018-06-29 03:17 UTC by andrewdalecramer

Adds the ability to use NaN as a grouping variable. Required allowing NA as a factorisation variable in `factorize()`.

- [x] closes #3729
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-07-03 09:39 UTC, gfyoung commented on pandas/tests/groupby/test_groupby.py
> +
Reference issue number in a comment.

2018-07-03 09:39 UTC, gfyoung commented on pandas/tests/groupby/test_groupby.py
> +
Reference issue number in a comment.

2018-07-03 09:40 UTC, gfyoung commented on pandas/core/algorithms.py
> +
Given that you're using broadcasting and `NumPy`, I don't think we should have any performance issues, but I wonder if we should still add a benchmark test anyway.

2018-07-03 15:00 UTC, jreback requested changes
needs quite a bit of tests & to parameterize existing tests to accept nan groups. i don't like the keyword at all. haven't reviewed fully.

2018-07-04 13:01 UTC, jreback commented
@andrewdalecramer 

this needs to be ``dropna=None`` as a default, with a warning if its *not* passed and a default of ``True`` for back-compat. Eventually we would want to make this False.

2018-07-12 12:34 UTC, ppallesen commented
@andrewdalecramer 
Suggestion for keyword name: allow_na_groups = False

2018-10-11 01:54 UTC, jreback commented
can you rebase this

2018-11-23 03:33 UTC, jreback commented
this is a nice feature, but needs quite a bit of work to fully test this out.

closing as stale. if you'd like to continue, pls ping.

2018-11-23 03:33 UTC, closed without merging