API: referring to duplicate level name raises ValueError
pandas-dev/pandas pull request #21678
Opened 2018-06-29 12:07 UTC by jorisvandenbossche

follow-up on: https://github.com/pandas-dev/pandas/pull/21423

But, this currently has a lot of failures, because of https://github.com/pandas-dev/pandas/issues/21677 that we first need to resolve.

2018-06-29 12:07 UTC, pep8speaks commented
Hello @jorisvandenbossche! Thanks for submitting the PR.

 - In the file [`pandas/core/indexes/multi.py`](https://github.com/pandas-dev/pandas/blob/8ea241933e8b1711bd15bea76406c8b7111d8f19/pandas/core/indexes/multi.py), following are the PEP8 issues :

> [Line 762:33](https://github.com/pandas-dev/pandas/blob/8ea241933e8b1711bd15bea76406c8b7111d8f19/pandas/core/indexes/multi.py#L762): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 773:37](https://github.com/pandas-dev/pandas/blob/8ea241933e8b1711bd15bea76406c8b7111d8f19/pandas/core/indexes/multi.py#L773): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 778:33](https://github.com/pandas-dev/pandas/blob/8ea241933e8b1711bd15bea76406c8b7111d8f19/pandas/core/indexes/multi.py#L778): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

2018-06-29 12:54 UTC, jorisvandenbossche commented
Changed the implementation a bit to keep the fallback logic for integer names, to decouple it from the discussion in #21677

2018-07-01 15:23 UTC, jreback requested changes
wow much simpler 

minor comment - pls add whatsnew note

any downsides to doing this?

2018-07-02 13:02 UTC, jorisvandenbossche commented
> wow much simpler

I don't think the code is simpler, the diff is just smaller :-)

> any downsides to doing this?

I don't think so. 
It's an api change, but only a minor one I think. In principle we could also keep it as KeyError (I don't think there is necessarily a more correct one, although KeyError is typically used for non-existing key, while here the key is existing but duplicate), but then encountering this in eg `stack` would change from ValueError to KeyError (so a api change as well).

2018-07-08 13:12 UTC, jreback requested changes
minor comment

2018-07-08 13:12 UTC, jreback commented on doc/source/whatsnew/v0.24.0.txt
> +  :meth:~MultiIndex.get_level_values) now raises a ValueError instead of
double backticks around the errors

2018-07-08 14:16 UTC, jreback approved these changes

2018-07-08 14:16 UTC, merged