BUG : Adding name in *kwargs
pandas-dev/pandas pull request #21703
Opened 2018-07-02 07:12 UTC by uds5501

- [x] closes #21697
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-07-02 08:29 UTC, pep8speaks commented
Hello @uds5501! Thanks for updating the PR.

 - In the file [`pandas/core/tools/datetimes.py`](https://github.com/pandas-dev/pandas/blob/42a207c13629e703800151c8eb277873c02da772/pandas/core/tools/datetimes.py), following are the PEP8 issues :

> [Line 102:39](https://github.com/pandas-dev/pandas/blob/42a207c13629e703800151c8eb277873c02da772/pandas/core/tools/datetimes.py#L102): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 104:47](https://github.com/pandas-dev/pandas/blob/42a207c13629e703800151c8eb277873c02da772/pandas/core/tools/datetimes.py#L104): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'

2018-07-02 16:54 UTC, mroeschke requested changes
Needs tests and whatsnew note (0.24.0.txt). Could you also modify this PR title to be a little more descriptive of the issue that this solves?

2018-07-02 17:17 UTC, uds5501 commented
@mroeschke  Sure sir, would do

2018-07-03 07:18 UTC, uds5501 commented
@mroeschke I had a quick question. I made a commit regarding the whatsnew note in another path. If I want to add the commit in this PR itself.. how do I do that?

2018-07-03 15:43 UTC, WillAyd commented
@uds5501 I am not sure if I completely follow but you could potentially merge the other branch into this branch locally or just re-do the whatsnew entry. The latter is probably easiest since we are just talking about a one-liner

2018-07-09 16:55 UTC, mroeschke commented on pandas/core/tools/datetimes.py
> +    from pandas.core.indexes.datetimes import DatetimeIndex
This block below already exists in `_convert_listlike_datetimes`

2018-07-20 13:32 UTC, jreback commented
closing as dupe of #21848 which is farther along

2018-07-20 13:32 UTC, closed without merging