move ndarray-returning functions to EA mixin classes
pandas-dev/pandas pull request #21722
Opened 2018-07-04 03:37 UTC by jbrockmendel

Orthogonal to other EAMixin PRs.

The methods this moves are unchanged.  Docstrings changed e.g. "DatetimeIndex" to "Datetime Array/Index".  I'm open to suggestions for better wording.

The error message in `PeriodArrayMixin._maybe_convert_timedelta` is changed to use `type(self).__name__` instead of hardcoding `PeriodIndex`.  Ditto the warning issued by `PeriodArrayMixin.freq.setter`.

2018-07-04 03:37 UTC, pep8speaks commented
Hello @jbrockmendel! Thanks for submitting the PR.





 - In the file [`pandas/core/arrays/period.py`](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py), following are the PEP8 issues :

> [Line 53:9](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L53): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 53:19](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L53): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 53:21](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L53): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 62:5](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L62): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 63:9](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L63): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 64:17](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L64): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 65:19](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L65): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 65:21](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L65): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 68:26](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L68): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 68:28](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L68): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 70:26](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L70): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 70:28](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L70): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 71:29](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L71): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 71:31](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L71): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 72:22](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L72): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 72:24](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L72): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 76:20](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L76): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 76:22](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L76): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 77:17](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L77): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 77:19](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L77): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 80:16](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L80): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 80:18](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L80): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 89:12](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L89): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 89:14](https://github.com/pandas-dev/pandas/blob/f556508b1e05500fcdeb4eb5524d2d87d26c3ec1/pandas/core/arrays/period.py#L89): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals

2018-07-04 12:57 UTC, jreback requested changes
looks good. doc comments

2018-07-04 12:57 UTC, jreback commented on pandas/core/arrays/period.py
> +        if isinstance(
can you add a doc-string to this one as it accepts many types

2018-07-04 18:15 UTC, jreback approved these changes

2018-07-04 18:15 UTC, jreback commented
lgtm. ping on green.

2018-07-04 20:33 UTC, jbrockmendel commented
ping

2018-07-05 10:39 UTC, merged

2018-07-05 10:39 UTC, jreback commented
thanks!