misplaced scatter/hexbin subplot colorbars
pandas-dev/pandas pull request #21728
Opened 2018-07-04 16:16 UTC by javadnoorb

- [x] closes #20455
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

NOTE: I have tested the following in Jupyter lab.

When I run:

```
%matplotlib inline
import matplotlib.pyplot as pl
import numpy as np
import pandas as pd
random_array = np.random.random((1000,3))
df = pd.DataFrame(random_array,columns=['A label','B label','C label'])

fig, axes = pl.subplots(1, 2)
df.plot.scatter('A label','B label', c='C label', ax=axes[0])
df.plot.scatter('A label','B label', c='C label', ax=axes[1])
pl.tight_layout()
```
I get:

![image](https://user-images.githubusercontent.com/26352146/42286164-eaa6ad96-7f7f-11e8-9bb5-cbe03d9820b7.png)

This PR fixes the issue with colorbars. After the PR the output is:

![image](https://user-images.githubusercontent.com/26352146/42286213-213375ba-7f80-11e8-964c-a0d4bdd79526.png)

This also fixes similar issue with hexbin plot. To explore different configurations try the following function:

```python
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

def make_multiplots(numrows=2,numcols=2,sharey=True,sharex=True, is_scatter = True):
    fig, axes = plt.subplots(numrows, numcols, sharey=sharey, sharex=sharex )
    for i in range(axes.shape[0]):
        for j in range(axes.shape[1]):
            random_array = np.random.random((1000,3))
            df = pd.DataFrame(random_array,columns=['A label','B label','C label'])
            if is_scatter:
                df.plot.scatter('A label', 'B label', c='C label', ax=axes[i,j]);
            else:
                df.plot.hexbin('A label', 'B label', gridsize=20, ax=axes[i,j]);

make_multiplots(numrows=2,numcols=3,sharey=False, sharex=False, is_scatter=False)
plt.tight_layout()
```
![image](https://user-images.githubusercontent.com/26352146/42286309-6bbba0c6-7f80-11e8-9327-b17cf31ecb07.png)

2018-07-04 16:37 UTC, jreback requested changes
can u modify the test to catch this? (if possible / if not ok)

2018-07-04 16:37 UTC, jreback commented on doc/source/whatsnew/v0.24.0.txt
> +- Bug in :func:'DataFrame.plot.scatter' and :func:'DataFrame.plot.hexbin' resulted in misplaced colorbars when subplot was used (related to :issue:`20455`)
you don’t need another entry, just add on to the previous one (just the number is ok)

2018-07-05 03:44 UTC, javadnoorb commented
Thanks @jreback. I included a test that checks if the distance between subplot parent axes is almost the same as the distance between colorbars. 

I'm not sure what `@pytest.mark.slow` does. I assumed it's for skipping tests that are slow. Do I need it?

2018-07-05 16:46 UTC, jreback approved these changes

2018-07-05 16:47 UTC, merged

2018-07-05 16:47 UTC, jreback commented
thanks @javadnoorb