Removed Need for OHLC As First Element if Used in .agg
pandas-dev/pandas pull request #21769
Opened 2018-07-06 16:13 UTC by WillAyd

- [X] closes #21716
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [] whatsnew entry

2018-07-06 16:14 UTC, WillAyd commented on pandas/core/groupby/groupby.py
> -            return list(compat.itervalues(results))[0]
There was no test coverage for this line and I can't feasibly think how this would be useful, hence the deletion

2018-07-06 16:20 UTC, jreback requested changes
lgtm. pls add a whatsnew note in 0.23.3.

2018-07-06 16:20 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +    df = pd.DataFrame([[1], [1]], columns=['foo'],
can you add the issue number as a comment

2018-07-06 16:46 UTC, jreback approved these changes

2018-07-06 16:46 UTC, jreback commented
lgtm. merge on green.

2018-07-07 13:43 UTC, WillAyd commented
CircleCI failure was a resource warning unrelated to PR

2018-07-07 13:44 UTC, merged