implement constructors for TimedeltaArray, DatetimeArray
pandas-dev/pandas pull request #21803
Opened 2018-07-07 22:29 UTC by jbrockmendel

Implements AttributesMixin since this is a pattern we might want to formalize.

The `_simple_new` that this implements for TimedeltaArray and DatetimeArray are pretty close to the "full" versions in the Index classes.  The `__new__` methods though are very much stripped down for the now.

With these in place we get to move `tz_convert` and `tz_localize`.  Could do a bunch more if I wasn't too much of a wuss to do it all in one go.

2018-07-07 22:36 UTC, jreback requested changes
minor comments

2018-07-07 22:36 UTC, jreback commented on pandas/core/arrays/datetimelike.py
> +        else:
don't need the else here

2018-07-07 22:36 UTC, jreback commented on pandas/core/arrays/datetimes.py
> +        if (freq is not None and not isinstance(freq, DateOffset) and
this condition could actually be handled to by ``to_offset`` (future PR) (except for the not-None part)

2018-07-07 23:29 UTC, jbrockmendel commented
Just updated to de-conflict changes to tz_convert/tz_localize docstrings.

2018-07-08 12:55 UTC, jreback approved these changes

2018-07-08 12:56 UTC, jreback commented on pandas/core/arrays/datetimelike.py
> +        else:
thanks!

2018-07-08 12:57 UTC, merged

2018-07-08 12:57 UTC, jreback commented
thanks @jbrockmendel