Propagate name in more cases when using `to_datetime`
pandas-dev/pandas pull request #21848
Opened 2018-07-10 23:45 UTC by eyurtsev

Closes 21697

https://github.com/pandas-dev/pandas/issues/21697

Haven't ran tests yet

2018-07-10 23:46 UTC, eyurtsev commented on pandas/core/tools/datetimes.py
> +                        tz_results = _return_parsed_timezone_results(
missing return here actually

2018-07-11 00:17 UTC, jreback commented
https://github.com/pandas-dev/pandas/pull/21703 is also proposed for this issue, though its currently failing. So happy to have you add tests.

2018-07-11 00:48 UTC, eyurtsev commented
I was trying to stick to the convention in the file, but wanted is there a reason for local imports? Is that the convention in the codebase or is it OK to float the imports to the top?

```+                            from pandas import Index
+                            return Index(tz_results, name=name)```

2018-07-12 00:25 UTC, jreback requested changes
needs tests. also you are changing some extraneous code, can you limit changes to what is needed to solve the issue.

2018-07-20 13:17 UTC, jreback requested changes
needs tests and a whatsnew note

2018-09-25 16:46 UTC, jreback commented
closing as stale. would still take this PR if updated.

2018-09-25 16:46 UTC, closed without merging