BUG: Fixing Series.str.zfill() to behave same as str.zfill() from sta…
pandas-dev/pandas pull request #21874
Opened 2018-07-12 06:20 UTC by atulagrwl

…ndard library (#20868)

- [ ] closes #20868
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Using standard library zfill method directly to handle specific characters issue

2018-07-12 06:36 UTC, atulagrwl commented
Added the validation test in last commit and added whatsnew entry too.

2018-07-12 10:31 UTC, jreback requested changes
pls add

- whatsnew note, other api changes, need a sub-section showing the previous and the new behavior
- check docs in text.rst to see if anything needs updating, if not pls add small example of usage there.

2018-07-12 10:31 UTC, jreback commented on pandas/tests/test_strings.py
>      def test_zfill(self):
the issue mentions also affecting ``rjust``, ``pad``, ``center``, can you add / update tests as needed for those as well.

2018-07-12 10:32 UTC, jreback requested changes

2018-07-12 10:32 UTC, jreback commented on doc/source/whatsnew/v0.24.0.txt
> +- :func:`Series.str.zfill()` now matches with standard string library zfill (:issue:`20868`)
see comments, make this a sub section in api breaking (yes its a bug fix, but an unexpected one)

2018-09-25 16:48 UTC, jreback commented
can you rebase

2018-11-23 03:32 UTC, jreback commented
closing as stale. if you'd like to continue, pls ping.

2018-11-23 03:32 UTC, closed without merging