TST/CLN: clean up indexes/multi/test_unique_and_duplicates
pandas-dev/pandas pull request #21900
Opened 2018-07-13 21:14 UTC by h-vetinari

Splitting up #21645

Added tests for `duplicated`, including a fixture for a `MultiIndex` with duplicates. Broke up a huge test into smaller chunks, removed a test that was for an `Index` (and exists verbatim in `tests/indexes/common.py`).

2018-07-14 03:52 UTC, jbrockmendel commented
Test failure appears unrelated.  Can you push again so it re-runs?

2018-07-14 09:50 UTC, h-vetinari commented
@jbrockmendel All green :)

2018-07-14 14:29 UTC, jreback requested changes

2018-07-14 14:29 UTC, jreback commented on pandas/tests/indexes/multi/test_names.py
> +    idx.names = ['foo', 'foo']
is there an issue number asssociated?

2018-07-14 14:29 UTC, jreback commented on pandas/tests/indexes/multi/test_unique_and_duplicates.py
> +@pytest.fixture
should go in the conftest.py

2018-07-14 14:33 UTC, h-vetinari commented on pandas/tests/indexes/multi/test_names.py
> +    idx.names = ['foo', 'foo']
Don't know, just moving tests around

2018-07-14 14:35 UTC, h-vetinari commented on pandas/tests/indexes/multi/test_names.py
> +    idx.names = ['foo', 'foo']
Came from #19029 through #21423

2018-07-16 10:56 UTC, jreback approved these changes

2018-07-16 10:57 UTC, merged

2018-07-16 10:57 UTC, jreback commented
thanks @h-vetinari