Change ._data to ._parent for accessors
pandas-dev/pandas pull request #21906
Opened 2018-07-13 22:41 UTC by jbrockmendel

The idea is to reduce the number of distinct meanings `._data` has.  With this it is down to just `Index._data` and `NDFrame._data`, I think.

2018-07-14 14:55 UTC, jreback commented
I can see changing this as ``_parent`` is more clear; is it intention to change other uses of ``_data``?

2018-07-14 15:40 UTC, jbrockmendel commented
> is it intention to change other uses of _data?

Not really.  At the sprint I brought up the idea of changing BlockManager references from _data to something more distinctive like _mgr, but the reception was luke-warm at best.

There is also #19658 but AFAIK there has been no action on that.

2018-07-20 12:58 UTC, jreback requested changes

2018-07-20 14:13 UTC, jbrockmendel commented on pandas/core/indexes/accessors.py
> -        self.values = data
>  i think that the dateitmelike accessors do something different?

CategoricalAccessor uses `self.categories`, is the outlier this PR leaves unchanged.

2018-08-05 23:37 UTC, jbrockmendel commented
The CI is having unrelated errors here much more consistently than usual.

2018-08-06 16:47 UTC, jbrockmendel commented
@mroeschke if you're comfortable with the "Take easy stuff off jreback's plate" strategy, this may qualify.

2018-08-06 17:15 UTC, jreback commented
i don’t think we should do this though

let me look a bit later

2018-08-06 17:19 UTC, jbrockmendel commented
> i don’t think we should do this though

Huh, [here](https://github.com/pandas-dev/pandas/pull/21906#issuecomment-405028499) you seemed on board.  My mistake.

> let me look a bit later

The goal was to take "easy" stuff off your plate.  This is definitely not a priority.

2018-08-07 13:24 UTC, jreback commented
@jbrockmendel hah, right I do remember that now. let me look again. my worry is that we are changing *some* things to ``._parent``, which makes sense, but now we have a dicotomy and now unclear what means what. maybe survey where we use ._data and propose a logical split?

2018-08-07 13:28 UTC, TomAugspurger commented
I think using `._parent` for accessors (and *only* for accessors) is a decent start.

Whether we we want to go down the road of changing `Index._data` or `DataFrame._data` can be pursued separately.

2018-08-07 13:29 UTC, TomAugspurger commented
> and now unclear what means what.

I think that's @jbrockmendel's reason for changing this in the first place, since `._data` can mean so many things. But with this PR when you need to deal with accessors, or you see `._parent`, you know at a glance what's going on.

2018-08-07 13:37 UTC, jreback commented
yeah I think this change is ok. Just want to document this somewhere and quickly survey other uses for comonaility.

2018-08-07 13:51 UTC, TomAugspurger commented
Sounds good. http://pandas-docs.github.io/pandas-docs-travis/internals.html#
may be a decent place for documenting these kinds of relationships between
classes and their data attributes.

On Tue, Aug 7, 2018 at 8:37 AM Jeff Reback <notifications@github.com> wrote:

> yeah I think this change is ok. Just want to document this somewhere and
> quickly survey other uses for comonaility.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/21906#issuecomment-411058777>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABQHIkvGI6sixHNSxFiTprLqi6DQjCATks5uOZgmgaJpZM4VPl_n>
> .
>

2018-08-07 16:54 UTC, jbrockmendel commented
> Just want to document this somewhere and quickly survey other uses for comonaility.

OK, if we're going down this road, should I update `CategoricalAccessor` to use `_parent` instead of `categories`?  (ATM it is the one case that doesn't use `_data`).

2018-08-07 17:05 UTC, jreback commented
yes i am ok with all non internals things changing to use _parent

2018-08-08 10:52 UTC, jreback approved these changes

2018-08-08 10:52 UTC, jreback commented
ok, can you add some docs in internals.rst about this

2018-08-08 10:52 UTC, merged