CLN: Remove PeriodIndex.tz_convert, tz_localize
pandas-dev/pandas pull request #21935
Opened 2018-07-16 17:22 UTC by jquinon

- [x] closes #21781 
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

- Removed PeriodIndex.tz_convert and PeriodIndex.tz_localize from PeriodIndex.
- Removed references to those methods in test_tz_convert_and_localize within test_timeseries
- Removed methods from the PeriodIndex class doc and updated whatsnew

test_tz_convert_and_localize also contains a TODO referencing changing the test to use PeriodIndex for a timezone test, which if it is never gaining timezone info should probably be removed. I just wanted to check that this was a good idea before doing it.

2018-07-16 17:55 UTC, jbrockmendel commented
There's a linting problem in the test file.

Other than that, assuming there's a consensus about removing these, LGTM.

2018-07-16 22:31 UTC, jquinon commented on doc/source/whatsnew/v0.24.0.txt
> +- :meth:`PeriodIndex.tz_convert` and :meth:`PeriodIndex.tz_localize` have been removed (:issue:`21781`)
Ok, gotcha

2018-07-16 22:36 UTC, jquinon commented on doc/source/whatsnew/v0.24.0.txt
> +- :meth:`PeriodIndex.tz_convert` and :meth:`PeriodIndex.tz_localize` have been removed (:issue:`21781`)
Also I tried to document the changes made in api.rst, but removing the methods caused a bunch of errors in the build. Do you know what is causing that? Do I need to build the docs?

2018-07-16 22:42 UTC, gfyoung commented on doc/source/whatsnew/v0.24.0.txt
> +- :meth:`PeriodIndex.tz_convert` and :meth:`PeriodIndex.tz_localize` have been removed (:issue:`21781`)
Not sure ATM.  If there's anything to remove in `api.rst` (or any of the `.rst` files), it would be reference to the methods that you just removed.

2018-07-16 23:52 UTC, jreback requested changes

2018-07-16 23:52 UTC, jreback commented on doc/source/whatsnew/v0.24.0.txt
> +- :meth:`PeriodIndex.tz_convert` and :meth:`PeriodIndex.tz_localize` have been removed (:issue:`21781`)
can you move to Other API canges, otherwise lgtm.

2018-07-17 12:04 UTC, jreback commented on doc/source/whatsnew/v0.24.0.txt
> +- :meth:`PeriodIndex.tz_convert` and :meth:`PeriodIndex.tz_localize` have been removed (:issue:`21781`)
ping when this is moved

2018-07-17 12:05 UTC, jreback commented on pandas/tests/frame/test_timeseries.py
>          # TODO: l1 should be a PeriodIndex for testing
remove this comment

2018-07-17 12:05 UTC, jreback commented on pandas/tests/frame/test_timeseries.py
>          # l1 = period_range('20140701', periods=5, freq='D')
this comment out as well

2018-07-17 18:56 UTC, jreback approved these changes

2018-07-18 01:00 UTC, merged

2018-07-18 01:00 UTC, gfyoung commented
@jquinon :  Everyone seems happy, so yes, indeed!  Thanks!