Raised value error on incorrect na_option
pandas-dev/pandas pull request #22037
Opened 2018-07-24 06:13 UTC by raguiar2

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Raised a ValueError for invalid values for na_option in the rank function. (Issue https://github.com/pandas-dev/pandas/issues/19499)

2018-07-24 06:14 UTC, WillAyd requested changes
Thanks for the PR. Just need test(s) to ensure the behavior. Can also add a whatsnew for 0.24

2018-07-24 06:16 UTC, WillAyd commented
Also can you make sure this works for all of `Series`, `DataFrame` and `GroupBy` objects? Behavior should be identical across all three

2018-07-25 06:53 UTC, raguiar2 commented
Not sure why travis-ci is failing. Looks unrelated/might have to do with an upstream dependency? Do I have to create a new PR or can I re-run the build somehow?

2018-07-25 07:02 UTC, WillAyd requested changes
One comment (applicable to all tests) but otherwise LGTM. Travis failures look unrelated so will see on re-push if resolved, but otherwise I don't think it's a blocker for this PR

2018-07-25 07:02 UTC, WillAyd commented on pandas/tests/frame/test_rank.py
> +        assert msg == str(excinfo.value)
Instead of doing this you can pass the expected `msg` as an argument to `tm.assert_raises_regex`

2018-07-25 15:33 UTC, raguiar2 commented
@WillAyd PTAL!

2018-07-25 17:39 UTC, WillAyd approved these changes
This lgtm - @jreback any feedback before I merge?

2018-07-25 17:42 UTC, jreback commented
lgtm

do we have an open issue for this?

2018-07-25 18:01 UTC, WillAyd commented
Updated original comment to make linkage clearer. Merging later today if no objections

2018-07-25 19:12 UTC, merged

2018-07-25 19:12 UTC, TomAugspurger commented
Thanks @raguiar2!