[POC] implement test_arithmetic.py
pandas-dev/pandas pull request #22033
Opened 2018-07-23 21:14 UTC by jbrockmendel

There are a ton of scattered arithmetic tests for Index/Series/DataFrame that _should_ be testing the same things, but in fact are haphazard.  Fixing this given the current structure would entail an enormous about of code duplication.

This PR if a proof of concept for gathering all those tests in one test_arithmetic.py file, parametrizing them, and ensuring that the relevant behavior is identical across arraylike classes.

As Datetime/Timedelta/Period EA come online, the case for de-duplication will be even stronger.

In this form it is really easy to track (via xfails) what behavior needs fixing.

2018-07-23 23:39 UTC, gfyoung commented
@jbrockmendel : So even though this is a POC, you still want to merge this, right?

2018-07-23 23:58 UTC, jbrockmendel commented
If there is consensus about this goal, yes.

2018-07-25 19:46 UTC, jbrockmendel commented
@jreback related to discussion about test refactoring.

2018-07-26 21:15 UTC, jorisvandenbossche commented
The idea would be to add the arrays as when they exist?

general idea looks good to me

2018-07-28 13:41 UTC, jreback requested changes

2018-07-28 13:41 UTC, jreback commented on pandas/tests/test_arithmetic.py
> +def assert_equal(left, right, **kwargs):
move to utils.testing

2018-07-28 13:41 UTC, jreback commented on pandas/tests/test_arithmetic.py
> +def box_expected(expected, box_cls):
maybe put in conftest.py, these are test helper functions that we don't necessarily want to publicly expose

2018-07-28 13:41 UTC, jreback commented on pandas/tests/test_arithmetic.py
> +def box_expected(expected, box_cls):
alternatively, we should put this into _test_decorators (maybe rename though)

2018-07-29 16:04 UTC, jreback approved these changes

2018-07-29 16:04 UTC, merged

2018-07-29 16:05 UTC, jreback commented
all for this!