Remove unused cimports, fix #22067
pandas-dev/pandas pull request #22087
Opened 2018-07-27 23:10 UTC by jbrockmendel

Fixes #22067

- [x] closes #22067

2018-07-27 23:11 UTC, jbrockmendel commented on pandas/_libs/tslibs/period.pyx
> +                                  int hour, int minute, int second, freq):
This is what fixed 22067.  year and month were getting an Int64Index.

2018-07-28 12:52 UTC, jreback requested changes
can you add a test for #22067 ?

2018-07-28 12:52 UTC, jreback commented on pandas/_libs/tslibs/period.pyx
> +cdef int64_t _ordinal_from_fields(int year, int month, quarter, int day,
does quarter not need a type?

2018-07-28 13:17 UTC, jreback commented
minor comments and pls rebase

2018-07-28 15:34 UTC, pep8speaks commented
Hello @jbrockmendel! Thanks for updating the PR.

 - In the file [`pandas/tests/indexes/datetimes/test_datetime.py`](https://github.com/pandas-dev/pandas/blob/9766fcd0bdcc58f7439361ee231be4c656d74a3b/pandas/tests/indexes/datetimes/test_datetime.py), following are the PEP8 issues :

> [Line 139:43](https://github.com/pandas-dev/pandas/blob/9766fcd0bdcc58f7439361ee231be4c656d74a3b/pandas/tests/indexes/datetimes/test_datetime.py#L139): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 144:24](https://github.com/pandas-dev/pandas/blob/9766fcd0bdcc58f7439361ee231be4c656d74a3b/pandas/tests/indexes/datetimes/test_datetime.py#L144): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2018-07-29 15:47 UTC, jreback requested changes
rebase & comments, lgtm. ping on green.

2018-07-29 15:47 UTC, jreback commented on pandas/tests/indexes/datetimes/test_datetime.py
> +        c = StringIO()
use ``tm.capture_stderr``

2018-07-30 01:44 UTC, jbrockmendel commented
Ping

2018-07-30 10:31 UTC, jreback approved these changes

2018-07-30 10:31 UTC, merged

2018-07-30 10:31 UTC, jreback commented
thanks!