BUG: DataFrame.replace with out of bound datetime causing RecursionError
pandas-dev/pandas pull request #22108
Opened 2018-07-28 22:47 UTC by minggli

- [ ] closes #https://github.com/pandas-dev/pandas/issues/20380
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

By default, keyword convert=True for replace method for Block and ObjectBlock. When trying to replace dataframe, blocks are operated on separately, during which conversion happens. OutOfBoundError(inherited from ValueError) raised by lib.maybe_convert_objects caused Block.replace, ObjectBlock.replace to form infinite recursive loop.

2018-07-29 15:27 UTC, jreback requested changes
lgtm. can you add a whatsnew, bug fix in 0.24.0, reshaping

2018-07-29 20:16 UTC, minggli commented on pandas/tests/frame/test_replace.py
> +         DataFrame({'datetime64': Index([datetime(2018, 7, 28)] * 3)})),
sure! 👍

2018-07-29 20:17 UTC, minggli commented on pandas/core/dtypes/cast.py
> +            pass
commented, used OutOfBoundsDatetime to be more clear on the error

2018-07-31 15:13 UTC, minggli commented
@jreback items actioned. additional feedback welcome.

2018-08-01 01:09 UTC, jreback approved these changes

2018-08-01 01:09 UTC, merged

2018-08-01 01:10 UTC, jreback commented
thanks @minggli keep me coming!