DOC: Clarify check_like behavior in assert_frame_equal
pandas-dev/pandas pull request #22106
Opened 2018-07-28 20:22 UTC by DeanLa

- [ ] closes #22052

2018-07-28 21:54 UTC, WillAyd requested changes

2018-07-28 21:54 UTC, WillAyd commented on pandas/util/testing.py
> +        If true, ignore the order of rows & columns.
Can you capitalize True?

2018-07-29 15:29 UTC, jreback requested changes

2018-07-30 20:03 UTC, DeanLa commented
Changed as requested

2018-07-30 20:40 UTC, WillAyd commented on pandas/util/testing.py
> +        Note: row labels must match their respective rows
Use `index` instead of `row`

2018-07-31 12:54 UTC, jreback approved these changes

2018-07-31 12:54 UTC, jreback commented
lgtm. @WillAyd merge when satisfied.

2018-07-31 15:44 UTC, merged

2018-07-31 15:44 UTC, WillAyd commented
Thanks @DeanLa !