BUG: make conftest._cython_table deterministic for Python<3.6
pandas-dev/pandas pull request #22157
Opened 2018-08-01 12:45 UTC by topper-123

Closes a bug for Python < 3.6 where xdist gets non-deterministic input because of random dict ordering for Python < 3.6.

and See #22156 for details.

2018-08-01 13:28 UTC, topper-123 commented
Travis failure is unrelated. Was in ``pandas/tests/plotting/test_deprecated.py:51:``

and message

``
E           AssertionError: Caused unexpected warning(s): [('RuntimeWarning', RuntimeWarning('invalid value encountered in equal',), '/home/travis/miniconda3/envs/pandas/lib/python2.7/site-packages/numpy/core/numeric.py', 2367)].
``

2018-08-02 10:14 UTC, jreback requested changes

2018-08-03 20:16 UTC, jbrockmendel commented on pandas/conftest.py
> +# manual sorting as dicts in py<3.6 have random order, which xdist doesn't like
I’m guessing it’s related to this: 
https://travis-ci.org/pandas-dev/pandas/jobs/411841573

2018-08-03 20:20 UTC, jreback commented on pandas/conftest.py
> +# manual sorting as dicts in py<3.6 have random order, which xdist doesn't like
there was another push after PR 

i have never seen this repeat

2018-08-09 16:34 UTC, topper-123 commented
hmm, I swear I saw this, but ok, I'll close this PR. If the issue (re-)appears, I can just do a PR then.

2018-08-09 16:39 UTC, topper-123 commented
Just saw the reference from #21902.

@h-vetinari, can you conform if you saw the same issue in your PR that I'm raporting in #22156?

2018-08-09 17:10 UTC, h-vetinari commented
Hey @topper-123, i definitely saw this issue at least 2-3 times in the 3.5 Travis build for several PRs. It's real. ;)

2018-08-09 17:12 UTC, h-vetinari commented
Since I rebased #21902, the Travis info is not (easily) available anymore, but I posted an extract there. It was always the same test (exactly related to this issue), so I'm confident about that.

2018-08-09 22:14 UTC, h-vetinari commented
I went through the travis log and looked for some of my old failed jobs. Here's some more occurrences (in each case, it was the only fail out of the required travis builds):
https://travis-ci.org/pandas-dev/pandas/jobs/412363050
https://travis-ci.org/pandas-dev/pandas/jobs/412369259
https://travis-ci.org/pandas-dev/pandas/jobs/413341494

All these are less than 4 days old, so in particular, after the comment from @jreback:
> there was another push after PR
i have never seen this repeat

2018-08-10 10:34 UTC, jreback requested changes

2018-08-10 10:34 UTC, jreback commented on pandas/conftest.py
> +# manual sorting as dicts in py<3.6 have random order, which xdist doesn't like
let's solve this entire problem, by just changing _cython_table (and the other _tables) to OrderedDict

2018-08-11 15:35 UTC, topper-123 commented
Ok, I've made ``_cython_table`` and ``_builtin_table`` OrderedDicts, which solves the issue. Nice solution.

2018-08-13 16:19 UTC, topper-123 commented
Is this ok?

2018-08-20 10:36 UTC, jreback approved these changes

2018-08-20 10:36 UTC, merged

2018-08-20 10:36 UTC, jreback commented
thanks @topper-123 I like this a lot better