qcut: Option to return -inf/inf as lower/upper bound
pandas-dev/pandas pull request #22185
Opened 2018-08-03 02:30 UTC by dberenbaum

- [x] closes #17282
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-08-03 02:55 UTC, gfyoung commented on pandas/core/reshape/tile.py
> +        otherwise use -inf/inf. Ignored if dtype is datetime/timedelta.
Move this below the version added, and add your own for `bounded` i.e.:

~~~
   .. versionadded:: 0.20.0
bounded: bool, optional
...
   .. versionadded:: 0.24.0
~~~

2018-08-03 02:55 UTC, gfyoung commented on pandas/core/reshape/tile.py
> +        pass
Why do we have a `pass` here?

2018-08-03 02:55 UTC, gfyoung commented on pandas/tests/reshape/test_tile.py
> +        labels = qcut(range(5), 4, bounded=False)
Reference issue number as a comment above this line.

2018-08-03 07:01 UTC, gfyoung approved these changes
LGTM!

cc @jreback

2018-09-15 15:05 UTC, dberenbaum commented
Checking in on this. How do I move this forward?

2018-09-16 05:06 UTC, gfyoung commented
@dberenbaum : So sorry!  Didn't realize this one fell through the cracks.

cc @jreback @jorisvandenbossche @TomAugspurger : This one has been ready to go IMO for over a month.  Could one of you take a look?

2018-09-18 13:14 UTC, jreback commented
I am not sure I like this, we are growing too many keywords here. Now we have 2 ways of specifying the bins. Is this really a problem to use np.inf in the bins specification?

2018-09-19 01:15 UTC, dberenbaum commented
I'm not following how there are 2 ways of specifying the bins. I only see a way to specify quantiles in `qcut` (there is a bins arg in `cut`). I'm not sure how else to return `np.inf` as a bin edge using `qcut`.

The use cases I have are very similar to the one raised by @prcastro in #17282. When I need to 1) compare distributions or 2) bin numerical values into known categories, I use `qcut` to bin by quantiles and then bin the new distribution by those categories. This is problematic when the new distribution contains out of bounds values. The best alternative I've found is to avoid using `qcut`:

```
bins = np.quantile(x, [0, 0.25, 0.5, 0.75, 1])
bins[0] = -np.inf
bins[-1] = np.inf
pd.cut(x, bins)
```

2018-12-03 01:58 UTC, jreback commented
@dberenbaum so I this for ``.cut()`` this is not needed at all as a user can just specify ``np.inf`` as a bound, for ``.qcut()`` its between 0 and 1, the quantiles. So can you give a case where this is actually useful?

2018-12-18 01:16 UTC, dberenbaum commented
Please see #17282 for an example of how this is useful. That example is very similar to the cases where I would have found this useful. Does that example clarify the intended usage?

2018-12-18 12:59 UTC, jreback commented
@dberenbaum did you see my comment. ``qcut`` is for ``quantile`` cutting, not arbitrary bounds, where ``cut`` suffices.

2018-12-19 01:49 UTC, dberenbaum commented
@jreback I saw your comment. Did you look at the example in #17282?

Let's say I use `qcut` to bin a sample of data collected into quartiles:

```
>>>q = pd.qcut([1,2,3,4,5,6,7,8,9], 4)
>>>q
[(0.999, 3.0], (0.999, 3.0], (0.999, 3.0], (3.0, 5.0], (3.0, 5.0], (5.0, 7.0], (5.0, 7.0], (7.0, 9.0], (7.0, 9.0]]
Categories (4, interval[float64]): [(0.999, 3.0] < (3.0, 5.0] < (5.0, 7.0] < (7.0, 9.0]]
```

I subsequently collect a new data sample, which contains values > 9. I want to compare the new sample to my original data using the returned quartiles. There is no quartile for the new values > 9. With the `bounded` option, I could do the following:

```
>>>q = pd.qcut([1,2,3,4,5,6,7,8,9], 4, bounded=False)
>>>q
[(-np.inf, 3.0], (0.999, 3.0], (0.999, 3.0], (3.0, 5.0], (3.0, 5.0], (5.0, 7.0], (5.0, 7.0], (7.0, 9.0], (7.0, np.inf]]
Categories (4, interval[float64]): [(-np.inf, 3.0] < (3.0, 5.0] < (5.0, 7.0] < (7.0, np.inf]]
```

Now, I have useful quartiles for any subsequent code that uses the output of `qcut`, even if I'm applying those quartiles to new data that falls outside the range of the original sample.

The `bounded` behavior might not always be desirable, but I've found it to at least be a useful option.

2019-01-14 00:15 UTC, jreback commented
@dberenbaum ok I looked at this again and it is ok, can you merge master

2019-01-16 01:46 UTC, jreback requested changes

2019-01-16 01:46 UTC, jreback commented on pandas/tests/reshape/test_qcut.py
> +def test_qcut_unbounded():
can you parametrize over bounded

2019-01-16 01:46 UTC, jreback commented on pandas/tests/reshape/test_qcut.py
> +    expected = np.array([-np.inf, 1.0, 2.0, 3.0, np.inf])
rather than use numpy arrays, can you construct the expected Index and use ``tm.assert_index_equal``

2019-02-27 23:32 UTC, WillAyd requested changes
Can you merge master?

2019-02-27 23:32 UTC, WillAyd commented on doc/source/whatsnew/v0.24.0.rst
> +- :func: qcut now accepts ``bounded`` as a keyword argument, allowing for unbounded quantiles such that the lower/upper bounds are -inf/inf (:issue:`17282`)
Move to 0.25 at this point

2019-03-01 02:18 UTC, closed without merging

2019-03-01 02:19 UTC, dberenbaum commented
Closing this PR per my comment above.