Added a decorator function to validate parameters
pandas-dev/pandas pull request #22193
Opened 2018-08-03 20:25 UTC by shantanuo

read_excel method needs to check if it has received valid parameters only. Use of **kwds allows any parameter that leads to confusion and bugs.

2018-08-03 20:25 UTC, pep8speaks commented
Hello @shantanuo! Thanks for submitting the PR.

 - In the file [`pandas/io/excel.py`](https://github.com/pandas-dev/pandas/blob/ad26c3c5b795f427aaabdb0a36baf75cde21c7a3/pandas/io/excel.py), following are the PEP8 issues :

> [Line 282:1](https://github.com/pandas-dev/pandas/blob/ad26c3c5b795f427aaabdb0a36baf75cde21c7a3/pandas/io/excel.py#L282): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

 - In the file [`pandas/util/_decorators.py`](https://github.com/pandas-dev/pandas/blob/ad26c3c5b795f427aaabdb0a36baf75cde21c7a3/pandas/util/_decorators.py), following are the PEP8 issues :

> [Line 8:1](https://github.com/pandas-dev/pandas/blob/ad26c3c5b795f427aaabdb0a36baf75cde21c7a3/pandas/util/_decorators.py#L8): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 12:26](https://github.com/pandas-dev/pandas/blob/ad26c3c5b795f427aaabdb0a36baf75cde21c7a3/pandas/util/_decorators.py#L12): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 12:46](https://github.com/pandas-dev/pandas/blob/ad26c3c5b795f427aaabdb0a36baf75cde21c7a3/pandas/util/_decorators.py#L12): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 12:80](https://github.com/pandas-dev/pandas/blob/ad26c3c5b795f427aaabdb0a36baf75cde21c7a3/pandas/util/_decorators.py#L12): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (118 > 79 characters)
> [Line 12:119](https://github.com/pandas-dev/pandas/blob/ad26c3c5b795f427aaabdb0a36baf75cde21c7a3/pandas/util/_decorators.py#L12): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 13:16](https://github.com/pandas-dev/pandas/blob/ad26c3c5b795f427aaabdb0a36baf75cde21c7a3/pandas/util/_decorators.py#L13): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 13:44](https://github.com/pandas-dev/pandas/blob/ad26c3c5b795f427aaabdb0a36baf75cde21c7a3/pandas/util/_decorators.py#L13): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 13:80](https://github.com/pandas-dev/pandas/blob/ad26c3c5b795f427aaabdb0a36baf75cde21c7a3/pandas/util/_decorators.py#L13): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (120 > 79 characters)
> [Line 14:16](https://github.com/pandas-dev/pandas/blob/ad26c3c5b795f427aaabdb0a36baf75cde21c7a3/pandas/util/_decorators.py#L14): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 14:80](https://github.com/pandas-dev/pandas/blob/ad26c3c5b795f427aaabdb0a36baf75cde21c7a3/pandas/util/_decorators.py#L14): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 16:66](https://github.com/pandas-dev/pandas/blob/ad26c3c5b795f427aaabdb0a36baf75cde21c7a3/pandas/util/_decorators.py#L16): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2018-08-03 22:01 UTC, jbrockmendel commented
Take a look at pandas.util._validators.validate_kwargs

2018-08-03 23:30 UTC, WillAyd commented
First and foremost this needs tests.

If this is only for `read_excel` then I think the decorator is overkill - would be better served directly within the function body. 

Is this in reference a particular issue #? If so can you update your post to link to it?

2018-08-04 01:16 UTC, shantanuo commented
This is not only related to "read_excel" function. All read_* methods accept *kwargs due to which non-valid parameters are allowed. 

https://github.com/pandas-dev/pandas/issues/22189

This is the only issue that is holding me back from using pandas and therefore I tried to fix it :)

2018-08-04 01:41 UTC, WillAyd requested changes
I still think the wrapper is overcomplicating things. As mentioned before tests are the most critical thing here and ideally should come before any other coding changes

2018-08-04 01:41 UTC, WillAyd commented on pandas/util/_decorators.py
> +            expected_keys=['io', 'sheet_name','header', 'names', 'index_col', 'usecols', 'squeeze', 'dtype', 'engine',
Just instantiate this as a set

2018-08-04 01:41 UTC, WillAyd commented on pandas/util/_decorators.py
> +                raise ValueError('invalid parameter found')
Would be nice to be explicit about which parameter isn't working. Also want a test

2018-08-04 13:41 UTC, TomAugspurger commented
I think we should focus our efforts on removing the need for `**kwargs` from the signature, rather than trying to work around it.

2018-08-04 14:24 UTC, shantanuo commented
sure. Decorator was my shortcut to incorporate the functionality that I needed desperately :)

2018-08-05 03:10 UTC, jbrockmendel commented
Am I missing something?  Why is the existing validate_kwargs decorator not up to the task?

2018-08-05 06:35 UTC, shantanuo commented
I checked the existing validate_kwargs decorator, but could not figure out how to use it :) 
Removing **kwargs seems to be ideal though. Any one of the two (that is practical, easy and quick) approach should be adopted.

2018-09-29 16:58 UTC, jbrockmendel commented
@shantanuo any plans to add a test to this?  I doubt this implementation will be merged, but a test could help us figure out how to use the existing decorators for this purpose.

2018-11-23 03:30 UTC, jreback commented
closing as stale. if you'd like to continue, pls ping.

2018-11-23 03:30 UTC, closed without merging