API/CLN: Have toplevel pd.pivot mirror pivot instead of pivot_simple
pandas-dev/pandas pull request #22209
Opened 2018-08-06 03:20 UTC by mroeschke

- [x] closes #22116
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

- Moved `pivot` from `pandas/core/reshape/reshape.py` to `pandas/core/reshape/pivot.py`
- Moved `pivot_simple` and `_slow_pivot` from `pandas/core/reshape/reshape.py` to `pandas/core/reshape/pivot.py` (only used by one panel test)
- Remapped top level `pd.pivot` to use `pivot` instead of `pivot_simple` 
- Added some additional tests for `pd.pivot`

2018-08-06 10:28 UTC, jreback requested changes
small comment, ping when green.

2018-08-06 10:28 UTC, jreback commented on doc/source/whatsnew/v0.24.0.txt
> +- Top level function :meth:`pandas.pivot` now maps directly to the instance method :meth:`DataFrame.pivot` (:issue:`22116`)
this is not necessary, you are cleaning internal code and its not user facing

2018-08-06 21:59 UTC, mroeschke commented
Ping @jreback. All green.

2018-08-07 12:51 UTC, jreback requested changes

2018-08-07 12:51 UTC, jreback commented on pandas/core/reshape/pivot.py
> +def _slow_pivot(index, columns, values):
I don't think we are using this *anywhere* but the ``test_panel`` test? if so I would just blow it away & remove the test

2018-08-08 06:03 UTC, mroeschke commented
@jreback removed those unused methods and test and all green.

2018-08-08 10:41 UTC, jreback approved these changes

2018-08-08 10:41 UTC, merged

2018-08-08 10:41 UTC, jreback commented
thanks @mroeschke nice clean!

2018-08-13 10:18 UTC, jorisvandenbossche commented
We cannot simply change this, as this completely breaks existing usage of `pd.pivot`. This needs to go through a deprecation cycle (or need to think how to keep supporting the old usage).

2018-08-16 14:39 UTC, jorisvandenbossche commented
That's certainly an option. 
I personally don't really know to what extent it would be useful to also keep the current behaviour of `pivot_simple` (so to not fully deprecate it). Will open an issue to not forget this.