BUG: Infer compression by default in read_fwf() (#22199)
pandas-dev/pandas pull request #22200
Opened 2018-08-05 04:06 UTC by NasaGeek

- [ ] closes #22199
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-08-05 19:14 UTC, jbrockmendel requested changes
Looks fine, needs a test.

2018-11-01 01:45 UTC, jreback commented
can you merge master and update

2018-11-04 00:11 UTC, pep8speaks commented
Hello @NasaGeek! Thanks for updating the PR.

 - There are no PEP8 issues in the file [`pandas/io/parsers.py`](https://github.com/NasaGeek/pandas/blob/b0c6c4ad84e4d5a1dccac9cd5949903c4aa7ed49/pandas/io/parsers.py) !

 - There are no PEP8 issues in the file [`pandas/tests/io/parser/test_read_fwf.py`](https://github.com/NasaGeek/pandas/blob/b0c6c4ad84e4d5a1dccac9cd5949903c4aa7ed49/pandas/tests/io/parser/test_read_fwf.py) !

2018-11-04 01:02 UTC, NasaGeek commented
Rebased and expanded a test

2018-11-04 15:28 UTC, jreback requested changes

2018-11-04 15:28 UTC, jreback commented on pandas/tests/io/parser/test_read_fwf.py
> +                    {'compression': comp_name}, {'compression': 'infer'}, {}]:
this needs to be parameterized.

@gfyoung don't we have functions to help compression testing along?

2018-11-11 23:57 UTC, jreback commented
can you merge master and update according to fixtures as pointed to by @gfyoung

2018-12-03 01:51 UTC, jreback commented
@NasaGeek can you merge master and update

2018-12-14 15:58 UTC, jreback commented
@NasaGeek can you merge master (or @gfyoung if you can)

2018-12-14 16:43 UTC, NasaGeek commented
Happy to rebase, @jreback, but unfortunately I don't yet have an approach to your parametrization request. The available fixture doesn't quite give me enough to work with by itself. It looks like pandas.util.testing.decompress_file may provide a solution if it's augmented to allow return writable file objects. The issue there is that the open function in python2's zipfile module will not give back writable files. Would you be willing to miss coverage on zipfile in python2? If so, what's the best way to skip it?

2018-12-19 09:20 UTC, gfyoung commented
@NasaGeek : You raise some good points regarding the fixtures.  I'm going to first do some refactoring on the `test_read_fwf.py` file itself first before revisiting this PR.

2018-12-20 12:12 UTC, NasaGeek commented
Just wanted to confirm you didn't need anything else from me on this PR. @gfyoung's changes look fine to me.

2018-12-23 19:25 UTC, jreback requested changes

2018-12-24 00:13 UTC, gfyoung commented on pandas/tests/io/parser/test_read_fwf.py
> +    extension = "gz" if compression == "gzip" else "bz2"
`compression_only` will pass in `gzip` for GZip files.  However, the file extension is `gz`, not `gzip`.  That's what we also follow in `_infer_compression` in `pandas/io/common`.

Thus, we have to do this.

2018-12-24 00:15 UTC, gfyoung commented on pandas/tests/io/parser/test_read_fwf.py
> +    extension = "gz" if compression == "gzip" else "bz2"
Is `gzip` considered a valid file extension for GZip files?  `gz` is generally the most common, and is what we follow in `_infer_compression` in `pandas/io/common`.

2018-12-24 00:18 UTC, gfyoung commented on pandas/tests/io/parser/test_read_fwf.py
> +            kwargs["compression"] = ("infer" if infer else compression)
Fixed.

2018-12-24 00:19 UTC, gfyoung commented on pandas/tests/io/parser/test_read_fwf.py
>  @pytest.mark.parametrize("compression", ["gzip", "bz2"])
Done.

2018-12-24 00:31 UTC, jreback approved these changes

2018-12-24 00:31 UTC, jreback commented
lgtm. ping on green. @jbrockmendel if you have comments.

2018-12-24 00:59 UTC, gfyoung commented
@jreback : Tests are all green.  PTAL.

@jbrockmendel : Any other thoughts?

2018-12-27 18:21 UTC, mroeschke approved these changes

2018-12-27 19:26 UTC, merged