BUG: raise KeyError if MultiIndex.get_loc_level is asked unused label
pandas-dev/pandas pull request #22230
Opened 2018-08-07 08:30 UTC by toobaz

- [x] closes #22221
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-08-07 12:46 UTC, jreback requested changes
small comments

2018-08-07 12:46 UTC, jreback commented on pandas/tests/indexes/multi/test_indexing.py
> +    # GH 22221: unused label
can you add the issue number here

2018-08-07 12:46 UTC, jreback commented on pandas/core/indexes/multi.py
> +                locs = np.array(labels == code, dtype=bool)
I think you can pass ``copy=False`` here

2018-08-07 12:47 UTC, jreback commented
can you also add the original OP test somewhere.

2018-08-07 16:55 UTC, toobaz commented on pandas/tests/indexes/multi/test_indexing.py
> +    # GH 22221: unused label
Do you mean repeat it below?

2018-08-08 10:31 UTC, jreback requested changes
minor comment

2018-08-08 10:31 UTC, jreback commented on pandas/core/indexes/multi.py
> +                locs = np.array(labels == code, dtype=bool)
can you do this

2018-08-08 10:31 UTC, jreback commented on pandas/tests/indexes/multi/test_indexing.py
> +    # GH 22221: unused label
this is good as written

2018-08-09 00:29 UTC, jreback approved these changes

2018-08-09 00:29 UTC, merged

2018-08-09 00:29 UTC, jreback commented
thanks @toobaz