TST: Add test of DataFrame.xs() with duplicates (#13719)
pandas-dev/pandas pull request #22294
Opened 2018-08-12 16:35 UTC by nmusolino

Added tests of DataFrame.xs() method for multilevel index containing duplicates.  The underlying bug reported in #13719 was fixed previously, but was not covered by specific unit tests.

- [ ] closes #13719
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-08-13 11:40 UTC, jreback requested changes

2018-08-13 11:40 UTC, jreback commented on pandas/tests/test_multilevel.py
> +        # DataFrame with a MultiIndex containing duplicates (#13719)
pls add as a separate test. add the gh issue number as a comment.

2018-08-17 14:03 UTC, nmusolino commented
@jreback This is ready for another look.

2018-09-15 12:37 UTC, jreback approved these changes

2018-09-15 12:37 UTC, merged

2018-09-15 12:37 UTC, jreback commented
thanks @nmusolino