CLN: remove Index.__inv__
pandas-dev/pandas pull request #22336
Opened 2018-08-14 10:01 UTC by toobaz

- [x] closes #22335
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

@jreback @jorisvandenbossche suggestions on where to put a test (``pandas/tests/test_arithmetic.py`` would seem the right place, except it only contains tests involving datetimelike) and which version to target (not sure 0.23.5 is OK)?

2018-08-14 11:15 UTC, jorisvandenbossche commented
> which version to target (not sure 0.23.5 is OK)?

In general, if something is not a (critical) bug fix, it should never be considered for a bug fix release (and certainly not something that is more an API clean-up)

2018-08-14 11:15 UTC, jorisvandenbossche commented
> something that is more an API clean-up

Speaking of which, shouldn't we rather deprecate this first before removing?

2018-08-14 11:28 UTC, jorisvandenbossche commented
> shouldn't we rather deprecate this first before removing?

OK, didn't yet read your issue, so missed that `~` is currently not working. Then it is fine removing it without deprecation.

2018-08-14 23:50 UTC, toobaz commented
@jreback @jorisvandenbossche while I was at it, given that this is going to 0.24 anyway, I thought it wouldn't harm to actually enable ``__invert__``, consistently with the case of ``Series``.

2018-08-16 10:52 UTC, jreback requested changes
can you also check that the ops are correctly defined in pandas/core/arrays/base.py (for EA arrays).

2018-08-16 10:52 UTC, jreback commented on pandas/tests/test_arithmetic.py
> +    @pytest.mark.parametrize('opname', ['neg', 'pos', 'abs', 'inv', 'invert'])
can you add this in conftest as a fixture (unary_op_fixtures)?

2018-08-16 10:52 UTC, jreback commented on pandas/tests/test_arithmetic.py
> +            pytest.raises(AttributeError, call_method)
make these if/elseif, then don't need the return (put the final clause in the else)

2018-08-16 11:30 UTC, jorisvandenbossche approved these changes
Apart from Jeff's comments, looks good

2018-08-23 10:50 UTC, jreback commented
@toobaz if you can rebase and check extension arrays

2018-08-23 20:50 UTC, toobaz commented
> @toobaz if you can rebase and check extension arrays

@jreback I'm afraid I can do that only in September, but while I'm at it:

> can you add this in conftest as a fixture (unary_op_fixtures)?

In the general ``pandas/conftest.py`` ?

> can you also check that the ops are correctly defined in pandas/core/arrays/base.py (for EA arrays).

Do you mean adding EA arrays to ``box`` fixture? Manually or in some automated way?

(In any case, if some tests fail I would defer to another PR)

2018-11-04 16:15 UTC, jreback commented
closing as stale. if you want to continue, pls merge master and re-open.

2018-11-04 16:15 UTC, closed without merging