TestPeriodIndex.test_resample_empty_dataframe is failed when I pass kwargs to Resampler._groupby_and_aggregate
pandas-dev/pandas pull request #22364
Opened 2018-08-15 09:34 UTC by discort

- [x] closes #22339
- [x] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

`test_resample.py::TestPeriodIndex::test_resample_empty_dataframe` triggers new changes

2018-08-15 09:36 UTC, discort commented
@jreback 

I investigated `test_resample.py::TestPeriodIndex::test_resample_empty_dataframe` test and found that `Grouby.var` may fail when `ddof = 1`. Other methods have `_python_agg_general` in case of exception, so I added the same behaviour for `var`.

Let me know if it's acceptable solution.

2018-08-15 16:01 UTC, WillAyd commented
This needs tests (should be created first)

2018-08-15 16:02 UTC, WillAyd requested changes
This needs tests (should be created first)

2018-08-15 16:09 UTC, discort commented
@WillAyd 

After adding `kwargs` to `_groupby_and_aggregate`, changes are triggered  this test `test_resample.py::TestPeriodIndex::test_resample_empty_dataframe`.

2018-08-15 21:28 UTC, discort commented
@WillAyd 

> Hmm not sure I completely follow - was this test failing before?

This test is failed using following changes.

```
diff --git a/pandas/core/resample.py b/pandas/core/resample.py
index 4a3625b2d..c82382f96 100644
--- a/pandas/core/resample.py
+++ b/pandas/core/resample.py
@@ -1043,7 +1043,7 @@ class PeriodIndexResampler(DatetimeIndexResampler):

         if is_subperiod(ax.freq, self.freq):
             # Downsampling
-            return self._groupby_and_aggregate(how, grouper=self.grouper)
+            return self._groupby_and_aggregate(how, grouper=self.grouper, **kwargs)
         elif is_superperiod(ax.freq, self.freq):
             if how == 'ohlc':
                 # GH #13083
@@ -1051,7 +1051,7 @@ class PeriodIndexResampler(DatetimeIndexResampler):
                 # for pure aggregating/reducing methods
                 # OHLC reduces along the time dimension, but creates multiple
                 # values for each period -> handle by _groupby_and_aggregate()
-                return self._groupby_and_aggregate(how, grouper=self.grouper)
+                return self._groupby_and_aggregate(how, grouper=self.grouper, **kwargs)
             return self.asfreq()
         elif ax.freq == self.freq:
             return self.asfreq()
```

2018-08-15 21:44 UTC, WillAyd commented
How is this visible from the end user perspective? The test case you provided works fine on master so asserting that it continues to work doesn't measure much. 

However this is visible to an end user you should set up a test case to cover that

2018-08-15 21:57 UTC, discort commented
@WillAyd

Just wanted to make sure that we are on the same page. @jreback suggested to create a new issue for this case [here](https://github.com/pandas-dev/pandas/pull/22304#discussion_r209901909). So, I created #22339 and this PR to close my original PR #22304, it's my goal at the moment.

I can make all changes within PR #22304 if it looks fine to you.

2018-08-15 22:00 UTC, WillAyd commented
A separate PR is fine. Whatever you were planning to xfail in the other PR should be included as a test here

2018-08-15 22:05 UTC, discort commented
@WillAyd 

There is already test that covers new changes: `TestPeriodIndex.test_resample_empty_dataframe`. I can create a separate test for `var`, for instance: `test_resample_empty_dataframe_var` which would duplicate the logic from `test_resample_empty_dataframe`. Are you okay with this approach?

2018-08-15 22:07 UTC, discort commented
follow up ^. It would be more explicit

2018-08-16 10:19 UTC, jreback requested changes
@discort we haven't merged that other PR yet, so you can build on top of it is probably best. IOW, in #22304 xfail the test and in this PR remove the xfail. We want to be sure things are tested.

2018-08-16 10:19 UTC, jreback commented on pandas/core/groupby/groupby.py
> +            except Exception:
can you make this exception more specific

2018-08-17 07:59 UTC, discort commented
Will fix within https://github.com/pandas-dev/pandas/pull/22304

see [here](https://github.com/pandas-dev/pandas/pull/22304#discussion_r210545908)

2018-08-17 07:59 UTC, closed without merging