BUG: Fix DataFrame.apply for string arg with additional args (#22376)
pandas-dev/pandas pull request #22377
Opened 2018-08-16 00:26 UTC by megabyde

- [x] closes #22376
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [] whatsnew entry

2018-08-16 10:15 UTC, jreback requested changes

2018-08-16 10:15 UTC, jreback commented on pandas/tests/frame/test_apply.py
> +    @pytest.mark.parametrize('kwds', [{}, {'axis': 1}, {'numeric_only': True}])
can you add a test for just std that adds both a positional arg (e.g. ddof) and a kwarg (numeric_only) for confirmation here (and other combinations if possible)

2018-08-16 10:15 UTC, jreback commented on pandas/core/apply.py
> +        if (kwds or args) and not isinstance(func, (np.ufunc,
can you format this like

```
if ((kwds or args) and
    (not isinstance.....)):
```

2018-08-16 10:16 UTC, jreback requested changes
can you also see if we have tests like this for groupby.apply

2018-08-16 19:32 UTC, megabyde commented
@jreback I checked and ``GroupBy.apply`` doesn't support string func arguments with positional args or keywords so seems like nothing to test there in this PR, see https://github.com/pandas-dev/pandas/blob/b5d81cfe43eeccfc3641aa9578097f726da9ce9d/pandas/core/groupby/groupby.py#L676

2018-08-23 10:42 UTC, jreback approved these changes

2018-08-23 10:42 UTC, merged

2018-08-23 10:42 UTC, jreback commented
thanks @megabyde