CLN: dedent else part of Series._get_with
pandas-dev/pandas pull request #22406
Opened 2018-08-17 22:16 UTC by topper-123

- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

There is a gigantic and unneeded ``else`` clause in ``Series._get_with`` and it makes the code hard to read.

This PR removes the else clause and dedents its content one level. This helps readability.

2018-08-17 23:17 UTC, jreback requested changes

2018-08-17 23:17 UTC, jreback commented on pandas/core/series.py
> +                # handle the dup indexing case (GH 4246)
you can remove this else as well

2018-08-17 23:32 UTC, topper-123 commented on pandas/core/series.py
> +                # handle the dup indexing case (GH 4246)
done.

2018-08-20 10:41 UTC, jreback approved these changes

2018-08-20 10:41 UTC, merged

2018-08-20 10:41 UTC, jreback commented
thanks