Fixing _get_standard_colors to honor num_colors arguments (#20585)
pandas-dev/pandas pull request #22439
Opened 2018-08-21 10:31 UTC by atulagrwl

- [ ] closes #20585
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-08-21 10:31 UTC, pep8speaks commented
Hello @atulagrwl! Thanks for submitting the PR.

 - In the file [`pandas/plotting/_core.py`](https://github.com/pandas-dev/pandas/blob/ac2bfb74aac251ae6ece69eb63fc30be8ce95d43/pandas/plotting/_core.py), following are the PEP8 issues :

> [Line 1240:13](https://github.com/pandas-dev/pandas/blob/ac2bfb74aac251ae6ece69eb63fc30be8ce95d43/pandas/plotting/_core.py#L1240): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'



 - In the file [`pandas/tests/plotting/test_series.py`](https://github.com/pandas-dev/pandas/blob/ac2bfb74aac251ae6ece69eb63fc30be8ce95d43/pandas/tests/plotting/test_series.py), following are the PEP8 issues :

> [Line 294:51](https://github.com/pandas-dev/pandas/blob/ac2bfb74aac251ae6ece69eb63fc30be8ce95d43/pandas/tests/plotting/test_series.py#L294): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2018-08-21 10:38 UTC, TomAugspurger reviewed
Looks good at a glance.

Could you add a release note to 0.24.0 in the bugfix section?

2018-08-21 10:38 UTC, TomAugspurger commented on pandas/tests/plotting/test_series.py
> +        s = Series([1, 2, 3, 4])
Add a reference to the original issue in a comment here.

2018-08-21 10:58 UTC, atulagrwl commented
@TomAugspurger - Thanks for quick review. Would really appreciate merging it to master soon (this would be my first contribution to get into master).

2018-08-22 10:18 UTC, jreback requested changes

2018-08-22 10:18 UTC, jreback commented on pandas/plotting/_core.py
> +        color = self.kwds.get(color_kwds)
can you add a doc-string here

2018-08-22 10:18 UTC, jreback commented on pandas/plotting/_style.py
> -    if len(colors) != num_colors:
can you add a comment here

2018-08-22 10:18 UTC, jreback commented
tests are failing as well

2018-11-02 06:31 UTC, dyoung418 commented
@atulagrwl do you plan on making the changes requested of you above?  I'd love to see this bugfix get merged.

2018-11-23 03:37 UTC, WillAyd commented
Closing as stale. Ping if you'd like to pick back up

2018-11-23 03:37 UTC, closed without merging