TEST: groupby(as_index=False, sort=False).aggregate formerly (?) gave unexpected results with a list-like function
pandas-dev/pandas pull request #22467
Opened 2018-08-22 15:08 UTC by discort

- [x] closes #18473
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2018-08-22 18:07 UTC, WillAyd commented on pandas/tests/groupby/aggregate/test_other.py
> +    result = df.groupby('A', as_index=False, sort=False)\
Is this not already tested elsewhere? No need to duplicate if so

2018-08-22 18:08 UTC, WillAyd requested changes

2018-08-22 18:08 UTC, WillAyd commented on pandas/tests/groupby/aggregate/test_other.py
> +    expected['B'] = df['B'].apply(lambda x: list(x))
Would be preferable to just manually construct the expected output here for both readability and risk mitigation. A smaller example (say `range(3)`) should suffice if it makes things easier

2018-08-23 08:38 UTC, discort commented
@WillAyd

2018-08-24 00:14 UTC, WillAyd requested changes

2018-08-24 00:14 UTC, WillAyd commented on pandas/tests/groupby/aggregate/test_other.py
> +    result = df.groupby('A', as_index=False, sort=False)\
Can you use implicit line breakage here instead?

2018-08-24 00:14 UTC, WillAyd commented
@jreback not sure nothing logically sticks out. Would have to bisect to see

2018-08-27 19:13 UTC, discort commented
@WillAyd

2018-08-28 02:26 UTC, WillAyd commented
@discort can you merge in from master to see if that fixes the CircleCI failure?

2018-08-29 05:37 UTC, WillAyd approved these changes
lgtm @jreback

2018-08-29 12:32 UTC, merged

2018-08-29 12:32 UTC, jreback commented
thanks!