BUG: resample with TimedeltaIndex, fenceposts are off
pandas-dev/pandas pull request #22488
Opened 2018-08-23 19:59 UTC by discort

- [x] closes #xxxx
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-08-23 20:28 UTC, mroeschke commented on pandas/tests/test_resample.py
> +        result = df.resample('1T').asfreq()
Instead, could you construct the expected frame and use `tm.assert_frame_equal`?

2018-08-23 20:29 UTC, mroeschke commented
Could you also add a downsampling case as noted here:

https://github.com/pandas-dev/pandas/issues/13022#issuecomment-238382933

2018-08-24 15:59 UTC, discort commented
@mroeschke 

There is test `TestTimedeltaIndex.test_asfreq` that exactly reproduces mentioned comment and it's passing.

2018-08-29 11:29 UTC, discort commented on pandas/tests/test_resample.py
> +        new_index = self.create_index(obj.index[0], obj.index[-1], freq=freq)
@mroeschke 

The case noted [here](https://github.com/pandas-dev/pandas/pull/22488#issuecomment-415560778) is covered by this test. However, it used to produce the incorrect index so tests were passing (which is incorrect). Here is the old expected index for TDI:

```
In [1]: obj.index.take(np.arange(0, len(obj.index), 2))
Out[1]: TimedeltaIndex(['1 days', '3 days', '5 days', '7 days', '9 days'], dtype='timedelta64[ns]', freq='2D')
```

2018-08-29 12:22 UTC, jreback requested changes

2018-08-29 12:31 UTC, jreback commented on pandas/tests/test_resample.py
> +        df = DataFrame(data={'value': [1, 5, 10]}, index=index)
ok, no that is fine

2018-08-29 14:00 UTC, discort commented on pandas/core/resample.py
>      def _adjust_binner_for_upsample(self, binner):
@jreback 

Could you please clarify how I should refresh the comment for DTI? What should be instead of `adjust our binner when upsampling`?

2018-09-03 08:11 UTC, discort commented on pandas/core/resample.py
>      def _adjust_binner_for_upsample(self, binner):
Just a reminder: here is why we adjust a binner https://github.com/pandas-dev/pandas/issues/10885

2018-09-03 14:54 UTC, discort commented
@jreback

2018-09-03 22:12 UTC, mroeschke commented
Travis flagged a linting error: `pandas/tests/test_resample.py:29:1: F401 'pandas.tseries.frequencies.to_offset' imported but unused`

2018-09-04 11:11 UTC, jreback requested changes
pls rebase and tiny comment

2018-09-04 11:11 UTC, jreback commented on pandas/core/resample.py
> +        # Just returning binner directly, GH 13022
can you add a bit more text here, e.g. the reason why this is true

2018-09-04 17:55 UTC, discort commented
@jreback

2018-09-05 09:59 UTC, pep8speaks commented
Hello @discort! Thanks for updating the PR.

 - There are no PEP8 issues in the file [`pandas/core/resample.py`](https://github.com/discort/pandas/blob/bd8f31a92b1e03d1fd6141fd837969caafdf1a8f/pandas/core/resample.py) !

 - There are no PEP8 issues in the file [`pandas/tests/test_resample.py`](https://github.com/discort/pandas/blob/bd8f31a92b1e03d1fd6141fd837969caafdf1a8f/pandas/tests/test_resample.py) !

2018-09-05 11:31 UTC, merged

2018-09-05 11:31 UTC, jreback commented
thanks @discort