BUG: silent overflow in DateTimeArray subtraction
pandas-dev/pandas pull request #22508
Opened 2018-08-26 01:07 UTC by shengpu1126

- [ ] closes #22492
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-08-26 01:13 UTC, shengpu1126 commented
Hi @jbrockmendel , thanks for the follow-up. 
- With the suggested change, it now throws `OverflowError: Overflow in int64 addition`. Is this desired behavior? 
- Where should I add the tests? Maybe under `tests/arrays/test_datetimelike.py`?

2018-08-26 02:05 UTC, gfyoung commented
@shengpu1126 : You should make the changes so that it gets the expected output that you reported in the original issue.  And yes, that does seem like a good place to put the test.  Don't forget a `whatsnew` entry too.

2018-08-26 23:12 UTC, jbrockmendel commented
Test will go in tests.arithmetic.test_datetime64

2018-08-28 14:05 UTC, pep8speaks commented
Hello @shengpu1126! Thanks for updating the PR.



 - In the file [`pandas/tests/arithmetic/test_datetime64.py`](https://github.com/pandas-dev/pandas/blob/e4a6927a8d88cb5aa9729dd18965d47cf68e809a/pandas/tests/arithmetic/test_datetime64.py), following are the PEP8 issues :

> [Line 1593:1](https://github.com/pandas-dev/pandas/blob/e4a6927a8d88cb5aa9729dd18965d47cf68e809a/pandas/tests/arithmetic/test_datetime64.py#L1593): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2018-08-29 12:37 UTC, jreback requested changes

2018-08-29 12:37 UTC, jreback commented on doc/source/whatsnew/v0.24.0.txt
> +- Bug in :class:`DatetimeIndex` subtraction that incorrectly failed to raise `OverflowError` (:issue:22492, :issue:22508)
can you add a little more here, e.g. when this fails to raise

2018-08-29 12:37 UTC, jreback commented on pandas/tests/arithmetic/test_datetime64.py
> +        dtimax = pd.to_datetime(['now', pd.Timestamp.max])
can you add a comment with the issue number

2018-08-30 00:00 UTC, jreback requested changes
minor comments. ping on green (or at least except for 3.6/3.5 builds are currently failing to an unrelated error). so might want to wait a little bit to rebase.

2018-08-30 15:49 UTC, shengpu1126 commented on doc/source/whatsnew/v0.24.0.txt
> +- Bug in :class:`DatetimeIndex` subtraction that incorrectly failed to raise `OverflowError` when the difference between :class:`Timestamp`s (a :class:`Timedelta` object) exceeds `int64` limit (:issu
sorry about that! 
for the record, it was mentioned [here](https://pandas.pydata.org/pandas-docs/stable/timedeltas.html#timedelta-limitations) that `pd.Timedelta`s are represented as nanoseconds using 64 bit integers, and I believe that's the source of potential overflow.

2018-08-31 10:10 UTC, merged

2018-08-31 10:11 UTC, jreback commented
thanks!