BUG: DataFrame.apply not adding a frequency if freq=None (#22150)
pandas-dev/pandas pull request #22561
Opened 2018-09-01 08:55 UTC by HannahFerch

- [x] closes #22150
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-09-01 22:06 UTC, gfyoung commented
@HannahFerch : Good start!  Will need a `whatsnew` and test(s) as well.

2018-09-04 11:24 UTC, jreback requested changes
comments

2018-09-07 16:51 UTC, mroeschke commented
@HannahFerch ideally if you could include this test https://github.com/pandas-dev/pandas/issues/22150#issuecomment-410211224 in our testing suite, that'd be great.

I think `pandas/tests/frame/test_apply.py` should be an apt location for the test.

2018-09-09 17:17 UTC, pep8speaks commented
Hello @HannahFerch! Thanks for updating the PR.

 - There are no PEP8 issues in the file [`pandas/core/indexes/datetimes.py`](https://github.com/HannahFerch/pandas/blob/827178efd7364421b03f6cc74c7d30e222e5147d/pandas/core/indexes/datetimes.py) !

 - There are no PEP8 issues in the file [`pandas/tests/frame/test_apply.py`](https://github.com/HannahFerch/pandas/blob/827178efd7364421b03f6cc74c7d30e222e5147d/pandas/tests/frame/test_apply.py) !

2018-09-14 09:45 UTC, HannahFerch commented
@mroeschke Thanks, have tried to do as you suggested

2018-09-14 17:04 UTC, mroeschke commented on doc/source/whatsnew/v0.24.0.txt
> +- Bug in :class:`DatetimeIndex` where frequency was being set if original frequency was 'None' (:issue:`22150`)
Nit pick: Could you replace the quotes around `None` with double backticks? Like how Timedelta is in the line above.

2018-09-14 17:07 UTC, mroeschke commented on pandas/tests/frame/test_apply.py
> +    def test_frequency_is_original_example(self):
I don't think you need this test anymore since it should be covered by the test above.

2018-09-16 11:32 UTC, HannahFerch commented
@mroeschke Done. Please let me know if anything else is needed from my side.

2018-09-16 15:35 UTC, mroeschke approved these changes
LGTM. @jreback

2018-09-18 12:28 UTC, jreback approved these changes

2018-09-18 12:28 UTC, merged

2018-09-18 12:29 UTC, jreback commented
thanks @HannahFerch