TST: add test for GH6131
pandas-dev/pandas pull request #22588
Opened 2018-09-04 16:00 UTC by simonjayhawkins

- [ ] closes #6131
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-09-05 16:55 UTC, gfyoung commented
@simonjayhawkins : Thanks for this!  Could you rebase onto `master` and run the CI again?

2018-09-05 16:59 UTC, pep8speaks commented
Hello @simonjayhawkins! Thanks for updating the PR.

 - There are no PEP8 issues in the file [`pandas/tests/io/formats/test_to_html.py`](https://github.com/simonjayhawkins/pandas/blob/65d65d16ca232854caafeebf23742afbfefb8f29/pandas/tests/io/formats/test_to_html.py) !

2018-09-06 21:41 UTC, simonjayhawkins commented
@gfyoung 

The rebase failed the CI checks again. I'll wait until #22597 is merged into master before trying again.

2018-09-07 01:11 UTC, WillAyd requested changes

2018-09-07 01:11 UTC, WillAyd commented on pandas/tests/io/formats/test_to_html.py
> +        result = df.pivot_table(
Rather than creating `df` and then pivoting can you simplify and just create the desired frame (i.e. the result of the pivot)?

2018-09-07 01:11 UTC, WillAyd commented on pandas/tests/io/formats/test_to_html.py
> +        # GH https://github.com/pandas-dev/pandas/issues/6131
Minor nit but don't need full link - can just do `# GH 6131`

2018-09-08 23:47 UTC, simonjayhawkins commented
@WillAyd i made a couple of additional changes to your request in the latest commit which on hindsight may not have been such a good idea.  i changed the name of the test since it no longer includes a pivot table command and secondly i took the opportunity of fixing a typo in the original problem description and so now the test does not faithfully recreate the original issue. will be happy to amend as necessary.

2018-09-09 15:37 UTC, WillAyd approved these changes
Thanks this lgtm - @mroeschke what do you think?

2018-09-09 17:04 UTC, mroeschke approved these changes
LGTM as well

2018-09-09 17:11 UTC, merged

2018-09-09 17:11 UTC, jreback commented
thanks @simonjayhawkins