BUG: Check types in Index.__contains__ (#22085)
pandas-dev/pandas pull request #22602
Opened 2018-09-05 07:07 UTC by yeojin-dev

- [x] closes #22085
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

I added is_float, is_integer_dtype in Index.__contains__.
If key is float and dtype of Index object is integer, return False.

And this is the same as #22360. I deleted the branch while rebasing it... 😅

2018-09-05 07:07 UTC, pep8speaks commented
Hello @yeojin-dev! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/tests/indexes/test_base.py`](https://github.com/yeojin-dev/pandas/blob/22dff3bfa639d3853f69c71c6256ac6170bb0bae/pandas/tests/indexes/test_base.py) !

2018-09-05 12:24 UTC, jreback requested changes

2018-09-13 00:58 UTC, yeojin-dev commented on pandas/_libs/index.pyx
> +        if (util.is_float_object(val) and isinstance(self, Int64Engine) and
Done.

2018-09-13 00:58 UTC, yeojin-dev commented on pandas/tests/indexes/test_base.py
> +    def test_contains_with_float_val(self):
Done.

2018-09-13 01:01 UTC, yeojin-dev commented
@jreback Please check. 😆

2018-09-15 12:20 UTC, jreback requested changes

2018-09-18 12:26 UTC, jreback commented on pandas/_libs/index_class_helper.pxi.in
> +    def __contains__(self, object val):
yes that is what I meant.

2018-09-18 13:49 UTC, jreback requested changes

2018-09-18 13:49 UTC, jreback commented on Pipfile
> +url = "https://pypi.org/simple"
what is this?

2018-09-18 13:49 UTC, jreback commented on pandas/core/indexes/numeric.py
> +        hash(key)
can you add a doc-string

2018-09-18 13:49 UTC, jreback commented on pandas/core/indexes/numeric.py
> +        hash(key)
can you create a IntegerIndex(NumericIndex) and put this method there, then inherit Int64Index and UInt64Index from that?

2018-09-19 10:20 UTC, yeojin-dev commented on Pipfile
> +url = "https://pypi.org/simple"
Sorry, it's my mistake.

2018-09-19 21:17 UTC, jreback approved these changes

2018-09-19 21:17 UTC, merged

2018-09-19 21:17 UTC, jreback commented
thanks @yeojin-dev sorry for the back and forth, sometimes hard to figure out where to put things

2018-09-20 04:13 UTC, yeojin-dev commented
@jreback Thanks. 😆