avoid ValueError when overriding eq
pandas-dev/pandas pull request #22611
Opened 2018-09-05 16:21 UTC by merraksh

Using pandas >= 0.22 together with module [xpress](https://pypi.org/project/xpress) that I maintain, I get a `ValueError` when calling `a.loc['foo']` on an index `a`. The reason has to do with xpress' overloading of a NumPy `eq` operation (and also `leq`, `geq`). This is done through NumPy's PyUFunc_FromFuncAndData() function, which is then passed as a value to a dictionary for key `'equal'`; the same happens with `'less_equal'` and `'greater_equal'`. 

This overloading works by replacing function pointers for an array of (operand_type, operand_type, result_type) tuples and possibly changing those types. For xpress to work, one of the two elements of the array having `NPY_OBJECT` as operand types should be changed so that the result is also `NPY_OBJECT`. The ValueError is triggered in _maybe_get_bool_indexer(), where `indexer`, an ndarray of bytes, is cython-defined and then assigned the result of the comparison. The comparison runs xpress' code, which realizes it's a comparison of non-xpress objects and just reverts to the original comparison operation, but returns an array of **objects** rather than of bytes. Assigning it to `indexer` thus returning a ValueError.

My change is to wrap the assignment around a try/except block and use a cython-defined array of objects to do the same task if a ValueError exception is raised.

I realize this is not a fix for any bug in pandas, but I believe this should make pandas compatible again with some modules that do the same sort of overloading, such as modeling modules.

All tests passed.

2018-09-05 16:58 UTC, gfyoung commented
@merraksh : Thanks for the contribution!  Could you open an issue with a reproducible example so we can better evaluate your changes / proposal (this is generally standard for this repository)?  You can then have this PR close the issue.

2018-09-05 18:30 UTC, merraksh commented
@alimcmaster1 I thought so too, but indexer is pre-declared with Cython as a byte array, while indexerObj is an object array. They are both used when creating found and they are returned in case count > 1. One would need one object to receive the comparison, but they are Cython declared and I don't think they can be declared dynamically---but I don't use Cython, so I don't know.

2018-09-05 18:31 UTC, merraksh commented
@gfyoung thanks for the prompt response. I submitted [#22612](https://github.com/pandas-dev/pandas/issues/22612) with a minimal example. The xpress module can be downloaded with `pip install xpress`.

2018-09-07 12:53 UTC, jreback commented
@merraksh not really sure what you are trying to do, this needs a lot more information, e.g. pls show the traceback. nor is this solution going to be acceptable. e.g. why is it raising?

2018-09-07 12:53 UTC, jreback requested changes
comments

2018-09-07 14:33 UTC, merraksh commented
@jreback xpress and pandas are unrelated, but when imported together they trigger the ValueError when running code on a pandas index.

The xpress module is for modeling optimization problems. It allows for creating NumPy arrays of optimization variables and constraints. Constraints use leq/geq/eq signs so xpress overloads Python's and NumPy's ==/<=/>= operators, using PyUFunc_FromFuncAndData() for NumPy. The resulting functions revert to previously defined ==/<=/>= functions when the members of the (in)equality are found not to be xpress objects.

The fix allows `_maybe_get_bool_indexer()` to evaluate a == between two NumPy vectors of PyObjects (which is the equality assigned to `indexer`) without triggering said ValueError, caused by an incompatible return value (object instead of byte). The different behavior only happens in case ValueError is raised, as it is caught. The script above works fine with this fix.

2018-09-08 02:54 UTC, jreback commented
@merraksh my point is we need a test that does not use an external package. I suspect you are actually doing something very odd here. Further where the ValueError is caught is very very odd. It need to be much higher in the stack. Please construct a dummy class that shows the same behavior.

2018-09-14 17:13 UTC, merraksh commented
@jreback I see the point of replicating the issue without external packages, and I'm trying to write an example that overrides `==` in numpy to get the same result.

The C extension uses `PyUFunc_FromFuncAndData()` to do the same, i.e. hijack the == when it's between arrays of a specific type of PyObject, but retains the pre-defined ufunc for all other PyObjects. The latter case really consists of a C call to this ufunc.

As for where to catch ValueError, it is in the assignment of `indexer` in `_libs/index.pyx:159`, where the `==` operator is used between `self._get_index_values()` and `val`. Catching that error upstream, i.e. without using the `indexerObj` I introduce in the same function, would still require comparing `self._get_index_values()` with `val`. I though resolving that `ValueError` directly there would be cleaner.

2018-09-18 15:03 UTC, merraksh commented
@jreback I can't find a way to overload `__eq__` so as to trigger the same error. The operation in `_maybe_get_bool_indexer` is effectively a `==`, so I would have to overload `numpy.equal`, but I can't see how unless a C extension is used; a newly created ufunc doesn't replace `numpy.equal`.

In the meantime, I reverted the try/except code change as there seems to be a much less invasive workaround: replace 
```
indexer = self._get_index_values() == val
```
with
```
indexer = np.array(self._get_index_values() == val, dtype = bool, copy = False)
```
I'm not sure if this this impact on performance (the commit affecting `_maybe_get_bool_indexer` was doc'd for performance), but this also fixes the issue I'm having.

2018-09-18 15:09 UTC, TomAugspurger commented
> I'm not sure if this this impact on performance

Can you check if we have a benchmark covering this and run asv over it? http://pandas-docs.github.io/pandas-docs-travis/contributing.html#running-the-performance-test-suite

2018-10-26 13:09 UTC, merraksh commented
Thanks. I tried a few weeks ago and today and I get the output below. Note that the 3.6 environment does have cython installed. Any suggestions?

```
$ asv continuous -f 1.1 master HEAD
· Creating environments
· Discovering benchmarks..
·· Uninstalling from conda-py3.6-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-pytest-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt.
·· Building 8eb427cf for conda-py3.6-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-pytest-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt.....
·· Error running /mnt/hgfs/common/pandas/asv_bench/env/83b3be1235aa7b08e8a17448e2f70790/bin/python setup.py build
   STDOUT -------->
   running build
   running build_py
   creating build
   creating build/lib.linux-x86_64-3.6
   creating build/lib.linux-x86_64-3.6/pandas
   copying pandas/conftest.py -> build/lib.linux-x86_64-3.6/pandas
   copying pandas/_version.py -> build/lib.linux-x86_64-3.6/pandas
   copying pandas/lib.py -> build/lib.linux-x86_64-3.6/pandas
   copying pandas/tslib.py -> build/lib.linux-x86_64-3.6/pandas
   copying pandas/__init__.py -> build/lib.linux-x86_64-3.6/pandas
   copying pandas/parser.py -> build/lib.linux-x86_64-3.6/pandas
   copying pandas/testing.py -> build/lib.linux-x86_64-3.6/pandas
   copying pandas/json.py -> build/lib.linux-x86_64-3.6/pandas
   creating build/lib.linux-x86_64-3.6/pandas/tools
   copying pandas/tools/merge.py -> build/lib.linux-x86_64-3.6/pandas/tools
   copying pandas/tools/plotting.py -> build/lib.linux-x86_64-3.6/pandas/tools
   copying pandas/tools/__init__.py -> build/lib.linux-x86_64-3.6/pandas/tools
   creating build/lib.linux-x86_64-3.6/pandas/compat
   copying pandas/compat/chainmap_impl.py -> build/lib.linux-x86_64-3.6/pandas/compat
   copying pandas/compat/__init__.py -> build/lib.linux-x86_64-3.6/pandas/compat
   copying pandas/compat/chainmap.py -> build/lib.linux-x86_64-3.6/pandas/compat
   copying pandas/compat/pickle_compat.py -> build/lib.linux-x86_64-3.6/pandas/compat
   creating build/lib.linux-x86_64-3.6/pandas/types
   copying pandas/types/concat.py -> build/lib.linux-x86_64-3.6/pandas/types
   copying pandas/types/__init__.py -> build/lib.linux-x86_64-3.6/pandas/types
   copying pandas/types/common.py -> build/lib.linux-x86_64-3.6/pandas/types
   creating build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/accessor.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/categorical.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/nanops.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/missing.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/algorithms.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/config.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/resample.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/window.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/index.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/config_init.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/generic.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/series.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/sorting.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/__init__.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/api.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/ops.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/common.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/frame.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/indexing.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/panel.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/base.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/strings.py -> build/lib.linux-x86_64-3.6/pandas/core
   copying pandas/core/apply.py -> build/lib.linux-x86_64-3.6/pandas/core
   creating build/lib.linux-x86_64-3.6/pandas/formats
   copying pandas/formats/style.py -> build/lib.linux-x86_64-3.6/pandas/formats
   copying pandas/formats/__init__.py -> build/lib.linux-x86_64-3.6/pandas/formats
   creating build/lib.linux-x86_64-3.6/pandas/util
   copying pandas/util/_depr_module.py -> build/lib.linux-x86_64-3.6/pandas/util
   copying pandas/util/_test_decorators.py -> build/lib.linux-x86_64-3.6/pandas/util
   copying pandas/util/_validators.py -> build/lib.linux-x86_64-3.6/pandas/util
   copying pandas/util/_print_versions.py -> build/lib.linux-x86_64-3.6/pandas/util
   copying pandas/util/__init__.py -> build/lib.linux-x86_64-3.6/pandas/util
   copying pandas/util/_decorators.py -> build/lib.linux-x86_64-3.6/pandas/util
   copying pandas/util/_doctools.py -> build/lib.linux-x86_64-3.6/pandas/util
   copying pandas/util/testing.py -> build/lib.linux-x86_64-3.6/pandas/util
   copying pandas/util/_exceptions.py -> build/lib.linux-x86_64-3.6/pandas/util
   copying pandas/util/_tester.py -> build/lib.linux-x86_64-3.6/pandas/util
   copying pandas/util/decorators.py -> build/lib.linux-x86_64-3.6/pandas/util
   creating build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/feather_format.py -> build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/parquet.py -> build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/gcs.py -> build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/pytables.py -> build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/html.py -> build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/__init__.py -> build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/clipboards.py -> build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/parsers.py -> build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/excel.py -> build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/api.py -> build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/common.py -> build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/date_converters.py -> build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/pickle.py -> build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/sql.py -> build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/s3.py -> build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/packers.py -> build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/stata.py -> build/lib.linux-x86_64-3.6/pandas/io
   copying pandas/io/gbq.py -> build/lib.linux-x86_64-3.6/pandas/io
   creating build/lib.linux-x86_64-3.6/pandas/tseries
   copying pandas/tseries/plotting.py -> build/lib.linux-x86_64-3.6/pandas/tseries
   copying pandas/tseries/converter.py -> build/lib.linux-x86_64-3.6/pandas/tseries
   copying pandas/tseries/__init__.py -> build/lib.linux-x86_64-3.6/pandas/tseries
   copying pandas/tseries/api.py -> build/lib.linux-x86_64-3.6/pandas/tseries
   copying pandas/tseries/offsets.py -> build/lib.linux-x86_64-3.6/pandas/tseries
   copying pandas/tseries/frequencies.py -> build/lib.linux-x86_64-3.6/pandas/tseries
   copying pandas/tseries/holiday.py -> build/lib.linux-x86_64-3.6/pandas/tseries
   creating build/lib.linux-x86_64-3.6/pandas/tests
   copying pandas/tests/test_expressions.py -> build/lib.linux-x86_64-3.6/pandas/tests
   copying pandas/tests/test_register_accessor.py -> build/lib.linux-x86_64-3.6/pandas/tests
   copying pandas/tests/test_common.py -> build/lib.linux-x86_64-3.6/pandas/tests
   copying pandas/tests/test_downstream.py -> build/lib.linux-x86_64-3.6/pandas/tests
   copying pandas/tests/test_errors.py -> build/lib.linux-x86_64-3.6/pandas/tests
   copying pandas/tests/test_sorting.py -> build/lib.linux-x86_64-3.6/pandas/tests
   copying pandas/tests/test_join.py -> build/lib.linux-x86_64-3.6/pandas/tests
   copying pandas/tests/test_panel.py -> build/lib.linux-x86_64-3.6/pandas/tests
   copying pandas/tests/__init__.py -> build/lib.linux-x86_64-3.6/pandas/tests
   copying pandas/tests/test_lib.py -> [...]

2018-12-03 01:46 UTC, jreback commented
this needs a test. closing, but if you can' provide the addtional details can reopen.

2018-12-03 01:46 UTC, closed without merging

2019-11-20 21:06 UTC, mhulko commented
Hi @merraksh , I discovered that I am also running into this issue. Did you ever find a solution that doesn't involve changes to pandas?
In my case I only need the xpress module for part of my code - is there a way to restore the original numpy.equal functionality after I've finished with the module?

2020-04-05 07:58 UTC, merraksh commented
Hi @mhulko, sorry for the reply. We are finally working on a fix for the issue because I couldn't run a successful test of pandas, both master and with the fix. I haven't tried this, but the free_module() function of the xpress module has a call to try and restore the old numpy loop functions. Can you try "del xpress" and see if this has any effect?

 




Sent: Wednesday, November 20, 2019 at 11:06 PM
From: "mhulko" <notifications@github.com>
To: pandas-dev/pandas <pandas@noreply.github.com>
Cc: "Pietro Belotti" <petr7b6@gmail.com>, Mention <mention@noreply.github.com>
Subject: Re: [pandas-dev/pandas] avoid ValueError when overriding eq (#22611)


Hi @merraksh , I discovered that I am also running into this issue. Did you ever find a solution that doesn't involve changes to pandas?
In my case I only need the xpress module for part of my code - is there a way to restore the original numpy.equal functionality after I've finished with the module?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-04-05 08:06 UTC, merraksh commented
Hi @mhulko, sorry for the reply. We are finally working on a fix for the issue because I couldn't run a successful test of pandas, both master and with the fix. I haven't tried this, but the free_module() function of the xpress module has a call to try and restore the old numpy loop functions. Can you try "del xpress" and see if this has any effect?

2020-04-06 18:51 UTC, mhulko commented
@merraksh - the solution we discovered was to add the line `np.set_numeric_ops(equal=np.equal)
`, which seems to restore the np.equal functionality.

2020-04-06 20:04 UTC, merraksh commented
@mhulko that's actually better than removing the xpress module. Restoring all operations would require to do something similar for `less_equal` and `greater_equal`. Note though that `np.set_numeric_ops` is now deprecated, see [https://github.com/numpy/numpy/pull/11916](https://github.com/numpy/numpy/pull/11916).