ENH: Allow tz_localize to handle nonexistent times
pandas-dev/pandas pull request #22644
Opened 2018-09-09 01:34 UTC by mroeschke

- [x] closes #8917
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Currently, users do not have any control over nonexistent datetime handling when `tz_localize`ing like they do ambiguous times. This adds a new keyword `nonexistent` to `tz_localize` so that users now can:

``'raise'``: Raise an error (default)
``'NaT'``: Replace nonexistent times with ``'NaT'``
``'shift'``: Shift nonexistent times forward to the closest existing time

2018-09-09 01:35 UTC, pep8speaks commented
Hello @mroeschke! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/arrays/datetimes.py`](https://github.com/mroeschke/pandas/blob/710014cefece3c5e67604def64ab14cbf69205f0/pandas/core/arrays/datetimes.py) !

 - There are no PEP8 issues in the file [`pandas/core/generic.py`](https://github.com/mroeschke/pandas/blob/710014cefece3c5e67604def64ab14cbf69205f0/pandas/core/generic.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexes/datetimes/test_timezones.py`](https://github.com/mroeschke/pandas/blob/710014cefece3c5e67604def64ab14cbf69205f0/pandas/tests/indexes/datetimes/test_timezones.py) !

 - There are no PEP8 issues in the file [`pandas/tests/scalar/timestamp/test_timezones.py`](https://github.com/mroeschke/pandas/blob/710014cefece3c5e67604def64ab14cbf69205f0/pandas/tests/scalar/timestamp/test_timezones.py) !

 - There are no PEP8 issues in the file [`pandas/tests/series/test_timezones.py`](https://github.com/mroeschke/pandas/blob/710014cefece3c5e67604def64ab14cbf69205f0/pandas/tests/series/test_timezones.py) !

2018-09-18 12:16 UTC, jreback requested changes

2018-09-18 12:16 UTC, jreback commented on pandas/_libs/tslibs/nattype.pyx
> +            - 'NaT' will return NaT where there are nonexistent times
add a ersionadded tag

2018-09-18 12:16 UTC, jreback commented on pandas/_libs/tslibs/timestamps.pyx
> +        nonexistent : 'shift', 'NaT', default 'raise'
hmm, this is now a bit confusing, e.g. there is overlap between errors and nonexistent. Is it possible to use errors instead here? (and not add a new keyword)?

2018-09-19 17:51 UTC, mroeschke commented
@jreback re: overlap between `errors` and `nonexistent`

1) The original issue mentions https://github.com/pandas-dev/pandas/issues/8917#issuecomment-65082306 having the ability to control over ambiguous times vs nonexistent times independently.
1a) `nonexistent` and `ambiguous` can handle their own errors independently
2) This PR has the ability to `shift` the nonexistent time to a real time (like how `ambiguous` can take `True/False`

So I would propose that eventually we can depreciate `errors` and keep both `ambiguous` and `nonexistent`

2018-09-23 17:00 UTC, jreback commented
> So I would propose that eventually we can depreciate errors and keep both ambiguous and nonexistent

can you do that in this PR?

2018-09-25 04:05 UTC, mroeschke commented
@jreback went ahead and depreciated the `errors` parameter in `tz_localize`

2018-09-25 12:17 UTC, jreback requested changes

2018-09-25 12:17 UTC, jreback commented on doc/source/timeseries.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
this is too short, needs to be same length as title

2018-09-25 12:17 UTC, jreback commented on doc/source/whatsnew/v0.24.0.txt
> +- :meth:`Timestamp.tz_localize`, :meth:`DatetimeIndex.tz_localize`, and :meth:`Series.tz_localize` have gained the ``nonexistent`` argument for alternative handling of nonexistent times (:issue:`8917
can you add a pointer to the docs

2018-09-25 12:17 UTC, jreback commented on pandas/_libs/tslibs/conversion.pyx
> +    nonexistent : str, bool, or arraylike
versionadded

2018-09-25 12:17 UTC, jreback commented on pandas/_libs/tslibs/conversion.pyx
> +    if is_coerce:
can we do the warning at a higher level? eg. not in the cython code? IOW refactor to avoid passing errors at all

2018-09-25 12:17 UTC, jreback commented on pandas/_libs/tslibs/conversion.pyx
> +                      "argument instead.", DeprecationWarning)
use FutureWarning

2018-09-25 12:17 UTC, jreback commented on pandas/tests/scalar/timestamp/test_timezones.py
> +        with tm.assert_produces_warning(DeprecationWarning):
change these to FutureWarning

2018-09-25 12:19 UTC, jreback requested changes
can you assert that all of the 3 deprecated ones are showing a FutureWarning (Timestamp, DTI, .dt)

2018-09-26 10:26 UTC, jreback requested changes

2018-09-26 22:51 UTC, mroeschke commented
Hmm good point @jorisvandenbossche. I think this was a complete oversight on my part. Thanks.

I had thought `errors` affected _any_ localization errors this entire time, but you're right, it appears to specifically target nonexistent times.

I guess the consolation this PR brings is:

1) IMO `nonexistent` is a better argument name than `errors` (demonstrated by my oversight)
2) Addition of the `shift` method (as you mentioned).
3) Brings nonexistent time handling to `Series.tz_localize` (akin to adding errors to that method)

I can only really hang my hat on 1, but I understand if its not worth the API churn. Thoughts?

2018-09-26 22:58 UTC, jreback commented
i don’t think api churn is really much of an issue here

this is a pretty niche use of the kwarg ; when u need it it’s very important but most of the time u don’t care

rather have the correct handling with rationale named things

2018-09-27 09:54 UTC, jorisvandenbossche commented
I agree `nonexistent` is a better name than `errors`, but I am not fully sure it is that much better to warrant a deprecation. This is indeed a rather niche use case, but if the parameter description clearly indicates "How to handle non-existent time errors: ...", I think that also might be sufficient.

The addition of shift and addition of the functionality to `Series.tz_localize` are good enhancements for sure. Since for `Series.tz_localize` it is a new keyword, there is no backward compatibility problem in that case of course ..

It just feels a bit stupid that we are deprecating a keyword that we only relatively recently added for the exact usecase in this PR (apart from adding the shift option of course)

> rather have the correct handling with rationale named things

The concern I raise is not about not having "correct handling" or so, apart from the additional features added here in this PR, it is a pure keyword-rename for the rest.

2018-09-27 11:53 UTC, jreback commented
> It just feels a bit stupid that we are deprecating a keyword that we only relatively recently added for the exact usecase in this PR (apart from adding the shift option of course)

sure, but would have rather have the new, descriptive keyword in a year than not. I don't think the prior deprecation period is relevant in the long term, though sure can produce churn. 

I don't see a reason not to proceed in this relatively niche case here. If it were a major impacting change (e.g. ``skiprows`` -> ``skip_rows``) or some such, then sure maybe it is more impactful, though that shoulnd't stop a good deprecation.

2018-09-30 14:04 UTC, jreback requested changes

2018-09-30 14:04 UTC, jreback commented on pandas/_libs/tslibs/conversion.pyx
> +    errors : {"raise", "coerce"}, default None
why do you actually need this arg to be passed?

2018-09-30 14:04 UTC, jreback commented on pandas/_libs/tslibs/timestamps.pyx
> +        errors : 'raise', 'coerce', default None
this is a top-level yes? (e.g. user callable)

2018-09-30 14:04 UTC, jreback commented on pandas/_libs/tslibs/timestamps.pyx
> +                raise ValueError("The errors argument must be either coerce "
is this tested?

2018-10-01 04:54 UTC, mroeschke commented
Addressed your comments @jreback

2018-10-04 11:58 UTC, jreback approved these changes
lgtm. minor comment, pls merge on green after that push.

2018-10-04 11:58 UTC, jreback commented on pandas/_libs/tslibs/conversion.pyx
> +
in theory should assert the possible values of nonexistent (e.g. what If I pass 'foo'),

2018-10-05 11:21 UTC, jorisvandenbossche reviewed
Added some doc related comments

2018-10-07 07:13 UTC, mroeschke commented
Thanks @jorisvandenbossche. Addressed your comments.

2018-10-07 22:17 UTC, jreback commented
lgtm. @jorisvandenbossche merged when satisified.

2018-10-11 15:26 UTC, jorisvandenbossche reviewed
Some minor comments on the new changes

2018-10-11 22:28 UTC, mroeschke commented on pandas/tests/indexes/datetimes/test_timezones.py
> +                                        clear=FutureWarning):
I test for another `FutureWarning` above this one, so as I understand it, I need `clear=FutureWarning` to test for another `FutureWarning` in the same test.

2018-10-14 18:12 UTC, jreback commented
lgtm @jorisvandenbossche any more comments?

2018-10-15 10:02 UTC, jorisvandenbossche commented on pandas/_libs/tslibs/nattype.pyx
>              - 'shift' will shift the nonexistent time forward to the closest
Sorry, rst formatting nitpick: there needs to be a blank line between the first sentences, and the start of this list ... (getting rst right can be annoying ..)

2018-10-15 10:03 UTC, jorisvandenbossche commented on pandas/tests/indexes/datetimes/test_timezones.py
> +                                        clear=FutureWarning):
I would expect the previous `assert_produces_warning` to take care of this to not leak this outside the context manager (but my experience is that with testing warnings expectations are often wrong .. :-)) 

Does it actually raise an error if you remove it?

2018-10-17 16:59 UTC, mroeschke commented
Thanks @jorisvandenbossche. Added those blank lines for rendering.

2018-10-18 16:02 UTC, jreback commented on pandas/tests/indexes/datetimes/test_timezones.py
> +        ['NaT', pd.NaT],
do you have tests that exericse the assertion when you pass a ``nonexistent`` keyword that is invalid?

2018-10-19 19:38 UTC, mroeschke commented
Thanks for catching that typo @jorisvandenbossche

2018-10-24 12:41 UTC, jreback commented
one more rebase and I think ok to go

2018-10-25 11:46 UTC, merged

2018-10-25 11:46 UTC, jreback commented
thanks @mroeschke