Dont include deleted rows from sas7bdat files (#15963)
pandas-dev/pandas pull request #22650
Opened 2018-09-09 16:35 UTC by troels

Sas7bdat files may contain rows which are actually deleted.
 
After reverse engineering the file format a bit, I found that   
if the page_type has bit 128 set, there is a bitmap following
the normal row data with a bit set for a given row if it has been
deleted. Use that information to not include deleted rows in
the resulting dataframe.

This PR is built on top of #22628

I've added two test-cases one from the issue  and another constructed
example, which tests parsing on different page types and across multiple sas7bdat-pages. 

The constructed example is rather large, mainly to have a test case where the data 
flows across several pages.

- [X] closes #15963
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

2018-09-09 16:35 UTC, pep8speaks commented
Hello @troels! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/io/sas/sas7bdat.py`](https://github.com/troels/pandas/blob/d7f46a303592c4d52d161f7dd6345fa543004618/pandas/io/sas/sas7bdat.py) !

 - There are no PEP8 issues in the file [`pandas/io/sas/sas_constants.py`](https://github.com/troels/pandas/blob/d7f46a303592c4d52d161f7dd6345fa543004618/pandas/io/sas/sas_constants.py) !

 - There are no PEP8 issues in the file [`pandas/tests/io/sas/test_sas7bdat.py`](https://github.com/troels/pandas/blob/d7f46a303592c4d52d161f7dd6345fa543004618/pandas/tests/io/sas/test_sas7bdat.py) !

2018-09-11 06:52 UTC, troels commented
Hi @WillAyd  I made a separate PR #22628 for the two first commits. This one I though was large enough to have its own PR, but as there was a dependency on the first two commits I continued this PR from the branch #22628 had sprung from. 
If #22628 can be merged soon, this PR will suddenly get slightly smaller (but just a bit)

2018-09-23 12:50 UTC, jreback requested changes

2018-09-23 12:50 UTC, jreback commented on pandas/io/sas/sas.pyx
> +
can you add some comments in here

2018-09-23 12:50 UTC, jreback commented on pandas/io/sas/sas.pyx
> +        cdef:
doc-string & comments

2018-11-26 03:46 UTC, WillAyd commented
Can you address comments and merge master?

2018-12-14 15:54 UTC, jreback commented
can you merge master and address comments

2019-02-06 03:31 UTC, WillAyd commented
Closing as stale. Ping if you'd like to continue

2019-02-06 03:31 UTC, closed without merging

2020-05-04 05:30 UTC, bezdomniy commented
This would be pretty useful as the issue makes read_sas unusable for a lot of sas datasets.