BUG: Fix dtype inconsistency when appending to empty DataFrame
pandas-dev/pandas pull request #22703
Opened 2018-09-13 23:01 UTC by araraonline

- [x] closes #22621
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-09-13 23:02 UTC, pep8speaks commented
Hello @araraonline! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/frame.py`](https://github.com/araraonline/pandas/blob/9c87db1e82a559692c991c402cccc8e10cf33894/pandas/core/frame.py) !

 - There are no PEP8 issues in the file [`pandas/tests/frame/test_combine_concat.py`](https://github.com/araraonline/pandas/blob/9c87db1e82a559692c991c402cccc8e10cf33894/pandas/tests/frame/test_combine_concat.py) !

2018-09-13 23:20 UTC, jreback requested changes

2018-09-14 00:08 UTC, araraonline commented on pandas/tests/frame/test_combine_concat.py
> +        assert df.append(series).dtypes['A'] == 'int64'
just did it

2018-09-14 00:08 UTC, araraonline commented on doc/source/whatsnew/v0.24.0.txt
> +- Bug in :meth:`DataFrame.append` would produce an inconsistent dtype when appending to empty DataFrame (:issue:`22621`)
and this too!

2018-09-14 16:12 UTC, araraonline commented
Got a question.

The problem ended up having a scope slightly bigger than what was mentioned in the Issue #22621

Now I'm working on a branch that fixes the dtype inconsistency when appending an array to a dframe, whether this dframe is empty or not.

Should I create a new PR?

2018-09-23 21:34 UTC, jreback commented
@araraonline no you can just update this one

2018-09-27 22:09 UTC, araraonline commented
I'm currently working on rewriting the DataFrame.append function. When it is ready, the issue related here will be resolved

2018-09-27 22:09 UTC, closed without merging