Clipboard
pandas-dev/pandas pull request #22715
Opened 2018-09-14 20:51 UTC by TomAugspurger

No idea if this will work on not.

2018-09-15 19:35 UTC, TomAugspurger commented
This failed.

Unless anyone objects, I'm going to just mock the actual clipboard layer part of things.

2018-09-15 19:42 UTC, jreback commented
yeah the clipboard tests are annoying

2018-09-15 20:12 UTC, pep8speaks commented
Hello @TomAugspurger! Thanks for updating the PR.

 - There are no PEP8 issues in the file [`pandas/tests/io/test_clipboard.py`](https://github.com/TomAugspurger/pandas/blob/2a90096b326b1d1de2bce5a2077b09e7186e179c/pandas/tests/io/test_clipboard.py) !

2018-09-16 00:13 UTC, jreback requested changes

2018-09-16 00:13 UTC, jreback commented on pandas/tests/io/test_clipboard.py
> +_mock_data = {}
it’s really odd to keep state outside of this fixture when it’s a function level

why don’t u just make it a module level?
or it seems that function level might be ok with state inside

2018-09-16 00:13 UTC, jreback commented on pandas/tests/io/test_clipboard.py
> +        _mock_data[request.node.name] = data
can u add a docstring

2018-09-16 00:13 UTC, jreback commented on pandas/tests/io/test_clipboard.py
> +    def test_mock_clipboard(self):
can’t u use monkey patch here?

2018-09-16 14:11 UTC, TomAugspurger commented
Moved the mock clipboard to be function-scope, rather than global.

2018-09-16 19:39 UTC, jreback commented
sure

2018-09-16 19:39 UTC, merged