Fixturize tests/frame/test_apply
pandas-dev/pandas pull request #22735
Opened 2018-09-17 20:29 UTC by h-vetinari

Split off from #22730 as per review from @WillAyd

2018-09-17 20:29 UTC, pep8speaks commented
Hello @h-vetinari! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/tests/frame/conftest.py`](https://github.com/h-vetinari/pandas/blob/0107e16d62c86df3567d6b8caf600f6a25263711/pandas/tests/frame/conftest.py) !

 - There are no PEP8 issues in the file [`pandas/tests/frame/test_apply.py`](https://github.com/h-vetinari/pandas/blob/0107e16d62c86df3567d6b8caf600f6a25263711/pandas/tests/frame/test_apply.py) !

2018-09-18 08:08 UTC, h-vetinari commented
@gfyoung @jreback @WillAyd 
Could someone retrigger the failed travis job? Thanks.

2018-09-20 16:05 UTC, h-vetinari commented
@WillAyd Green

2018-09-21 08:00 UTC, gfyoung approved these changes
Nice!

cc @jreback @WillAyd

2018-09-21 15:05 UTC, WillAyd requested changes
Just a few minor comments but otherwise looks good

2018-09-21 15:05 UTC, WillAyd commented on pandas/tests/frame/test_apply.py
> +        expected = DataFrame(int_frame_const_col.values,
Instead of using the DataFrame constructor can you just rename the columns to get to the same place?

2018-09-21 15:05 UTC, WillAyd commented on pandas/tests/frame/test_apply.py
> +        expected = DataFrame(int_frame_const_col.values[:, :2],
Similar comment as above - would be more idiomatic than slicing `.values` on the frame and passing to a constructor

2018-09-21 15:05 UTC, WillAyd commented on pandas/tests/frame/test_apply.py
> +        expected = DataFrame(int_frame_const_col.values[:, :2])
Same comment

2018-09-21 16:26 UTC, WillAyd approved these changes

2018-09-21 21:32 UTC, h-vetinari commented
@WillAyd @gfyoung Green :)

2018-09-21 22:25 UTC, jreback requested changes
will look soon

2018-09-23 13:01 UTC, jreback requested changes
looks fine. small change, ping on green.

2018-09-23 13:01 UTC, jreback commented on pandas/tests/frame/conftest.py
> +@pytest.fixture
so don't add this here, rather make it a fixture in test_apply.py; this conftest is for pretty common fixtures, this is not one of them (of course if could decide later to change this)

2018-09-23 13:27 UTC, jreback approved these changes

2018-09-23 13:27 UTC, jreback commented
lgtm. ping on green.

2018-09-23 17:54 UTC, h-vetinari commented
@jreback @WillAyd @gfyoung Green. :)

2018-09-23 18:28 UTC, merged

2018-09-23 18:28 UTC, gfyoung commented
@h-vetinari : Thanks!