DOC: Add cookbook entry using callable method for DataFrame.corr
pandas-dev/pandas pull request #22761
Opened 2018-09-19 11:19 UTC by dsaxton

Provides a cookbook entry using the callable method option for `DataFrame.corr` (PR #22684) to calculate a distance correlation matrix.  (Related: issue ##22402)

2018-09-19 12:36 UTC, datapythonista requested changes
Is the distance correlation you provided different from: https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.spatial.distance.correlation.html ?

While the example looks interesting, it doesn't seem enough related to pandas to be worth adding it to our cookbook.

If the function in scipy is the same as the one you implemented, it could be nice having this example (using the scipy function) in the `DataFrame.corr` docstring.

What do you think?

2018-09-19 12:36 UTC, datapythonista commented on doc/source/cookbook.rst
> +            for j in range(i+1, n):
missing spaces around `+`

2018-09-19 12:36 UTC, datapythonista commented on doc/source/cookbook.rst
> +        b = b + b.T
I think `a += a.T` is more Pythonic

2018-09-19 12:54 UTC, dsaxton commented
The function from `scipy.spatial.distance` is taking one minus the ordinary Pearson correlation, so this is a different calculation.  The cookbook entry was requested by @TomAugspurger in #22402 and I think the goal was just to show the flexibility of allowing callable methods in `DataFrame.corr` while also being somewhat interesting in itself.

2018-09-19 13:02 UTC, TomAugspurger commented
I think this will be good to have.

We'll need to wait for https://github.com/pandas-dev/pandas/pull/22684 first.

2018-09-19 13:03 UTC, datapythonista commented
Sorry @dsaxton, I didn't see the related issue (next time it may be a good idea to leave the template we have in the PR description, it makes it easier to see there is a related issue).

2018-09-23 21:59 UTC, gfyoung commented
@dsaxton : Can you rebase onto `master` to fix the build issues?

2018-09-30 11:41 UTC, datapythonista commented
@dsaxton seems like something went wrong with git, and your PR contains many unrelated changes. Can you take a look?

In general that could be fixed by performing being in the PR branch:
```
git fetch upstream
git merge upstream/master
git reset --soft upstream/master
git commit -m "PR description"
git push -f
```

Thanks!

2018-09-30 16:37 UTC, dsaxton commented
@datapythonista Sorry about that, could this has been caused by my (attempted) rebase?  I'll try the commands you're suggesting.

2018-09-30 16:51 UTC, datapythonista commented
@dsaxton it happens often to many people, but I'm not quite sure what's the cause.

2018-10-07 23:24 UTC, merged

2018-10-07 23:38 UTC, dsaxton commented
@jreback NP, happy to help