CLN GH22873 Replace base excepts in pandas/core
pandas-dev/pandas pull request #22901
Opened 2018-09-30 00:08 UTC by pambot

This cleaning fix adds specific exception classes to bare except statements to correct PEP8 linting errors. The classes were chosen by a mixture of educated guessing (i.e. if a statement gets the `length` property, it might raise an `AttributeError`), trying out functions on known edge cases (i.e. `df.droplevel(0)` if there's nothing left to drop - it turns out it's a `ValueError`), and inspecting functions in the `try` block to see what kind of errors they raise.

- [x] closes #22873
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-09-30 00:08 UTC, pep8speaks commented
Hello @pambot! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/computation/pytables.py`](https://github.com/pambot/pandas/blob/a96b271a03b4dd58bf784f43252b6814daeb336c/pandas/core/computation/pytables.py) !

 - There are no PEP8 issues in the file [`pandas/core/dtypes/common.py`](https://github.com/pambot/pandas/blob/a96b271a03b4dd58bf784f43252b6814daeb336c/pandas/core/dtypes/common.py) !

 - There are no PEP8 issues in the file [`pandas/core/dtypes/dtypes.py`](https://github.com/pambot/pandas/blob/a96b271a03b4dd58bf784f43252b6814daeb336c/pandas/core/dtypes/dtypes.py) !

 - There are no PEP8 issues in the file [`pandas/core/frame.py`](https://github.com/pambot/pandas/blob/a96b271a03b4dd58bf784f43252b6814daeb336c/pandas/core/frame.py) !

 - There are no PEP8 issues in the file [`pandas/core/indexes/frozen.py`](https://github.com/pambot/pandas/blob/a96b271a03b4dd58bf784f43252b6814daeb336c/pandas/core/indexes/frozen.py) !

 - There are no PEP8 issues in the file [`pandas/core/indexes/multi.py`](https://github.com/pambot/pandas/blob/a96b271a03b4dd58bf784f43252b6814daeb336c/pandas/core/indexes/multi.py) !

 - There are no PEP8 issues in the file [`pandas/core/indexing.py`](https://github.com/pambot/pandas/blob/a96b271a03b4dd58bf784f43252b6814daeb336c/pandas/core/indexing.py) !

 - There are no PEP8 issues in the file [`pandas/core/internals/blocks.py`](https://github.com/pambot/pandas/blob/a96b271a03b4dd58bf784f43252b6814daeb336c/pandas/core/internals/blocks.py) !

 - There are no PEP8 issues in the file [`pandas/core/nanops.py`](https://github.com/pambot/pandas/blob/a96b271a03b4dd58bf784f43252b6814daeb336c/pandas/core/nanops.py) !

 - There are no PEP8 issues in the file [`pandas/core/ops.py`](https://github.com/pambot/pandas/blob/a96b271a03b4dd58bf784f43252b6814daeb336c/pandas/core/ops.py) !

 - There are no PEP8 issues in the file [`pandas/core/sparse/array.py`](https://github.com/pambot/pandas/blob/a96b271a03b4dd58bf784f43252b6814daeb336c/pandas/core/sparse/array.py) !

 - There are no PEP8 issues in the file [`pandas/core/tools/datetimes.py`](https://github.com/pambot/pandas/blob/a96b271a03b4dd58bf784f43252b6814daeb336c/pandas/core/tools/datetimes.py) !

 - There are no PEP8 issues in the file [`pandas/core/window.py`](https://github.com/pambot/pandas/blob/a96b271a03b4dd58bf784f43252b6814daeb336c/pandas/core/window.py) !

2018-09-30 09:17 UTC, datapythonista reviewed
The PR looks just great. There are couple of cases that I'm unsure, and would like to know your reasons for a change. Other than that, looks really good. Thanks for the hard work on this!

2018-09-30 09:17 UTC, datapythonista commented on doc/source/whatsnew/v0.24.0.txt
> +- Added specific exception classes to fix bare except statements in `pandas/core` (:issue:``22873)
Thanks for adding this, but not sure if it's worth adding this change to the release note. It's more of a internal change that should not have any impact on users.

2018-09-30 09:17 UTC, datapythonista commented on pandas/core/indexes/multi.py
> +            except (KeyError, IndexError, ValueError):
Can you clarify this change? It feels like we just wanted to ignore `KeyError` exceptions, and I'm sure you have a reason to also ignore `IndexError` and `ValueError`, but it's not obvious to me.

2018-09-30 09:17 UTC, datapythonista commented on pandas/core/nanops.py
> +                                .format(value=x))
I don't understand this change either. Seems like the original behavior was to try to cast to float. Why to not try it anymore and raise directly?

2018-09-30 11:47 UTC, datapythonista commented
If I'm not wrong, those were problems with the build unrelated to your PR. I think the datetime one is now fix in master, and should be ok if you merge the last master. The parquet one I think it was because of an amazon url, not sure if that's fixed, or it happens just some times. We need to take a look at it, don't worry much about it, if your changes are all right, we'll fix it eventually and merge your PR.

2018-09-30 14:01 UTC, jreback requested changes

2018-09-30 14:01 UTC, jreback commented on pandas/core/frame.py
> +                    AssertionError, TypeError):
where is this assertion error coming from?

2018-09-30 14:01 UTC, jreback commented on pandas/core/indexes/multi.py
> +                except Exception:
can we be more specific here?

2018-09-30 14:01 UTC, jreback commented on pandas/core/indexes/multi.py
> +                except Exception:
same here

2018-09-30 14:01 UTC, jreback commented on pandas/core/indexes/multi.py
> +                except Exception:
can be more specific here

2018-09-30 14:01 UTC, jreback commented on pandas/core/internals/blocks.py
> +        except Exception:
can be more specific here

2018-10-01 11:56 UTC, jreback requested changes

2018-10-01 11:56 UTC, jreback commented on pandas/core/frame.py
> +                    AssertionError, TypeError):
hmm, does removing AssertionError cause any tests to fail?

2018-10-01 11:56 UTC, jreback commented on pandas/core/internals/blocks.py
> +        except Exception:
ok add a ``# noqa: E722``

2018-10-02 09:12 UTC, datapythonista approved these changes
lgtm, and the problems with the build are fixed.

Thanks for taking care of this @pambot

2018-10-02 21:16 UTC, jreback approved these changes

2018-10-02 21:16 UTC, jreback commented
thanks @pambot very nice!

2018-10-02 21:16 UTC, merged

2018-10-03 13:04 UTC, TomAugspurger commented
This seems to be the first commit with the failure on numpydev. https://travis-ci.org/pandas-dev/pandas/jobs/435916255#L2767

<details>

```
____________ TestSelection.test_groupby_duplicated_column_errormsg _____________
[gw0] linux -- Python 3.7.0 /home/travis/miniconda3/envs/pandas/bin/python
self = <pandas.tests.groupby.test_grouping.TestSelection object at 0x7f87673fb668>
    def test_groupby_duplicated_column_errormsg(self):
        # GH7511
        df = DataFrame(columns=['A', 'B', 'A', 'C'],
                       data=[range(4), range(2, 6), range(0, 8, 2)])
    
>       pytest.raises(ValueError, df.groupby, 'A')
pandas/tests/groupby/test_grouping.py:42: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pandas/core/generic.py:7136: in groupby
    observed=observed, **kwargs)
pandas/core/groupby/groupby.py:1966: in groupby
    return klass(obj, by, **kwds)
pandas/core/groupby/groupby.py:365: in __init__
    mutated=self.mutated)
pandas/core/groupby/grouper.py:588: in _get_grouper
    if is_categorical_dtype(gpr) and len(gpr) != obj.shape[axis]:
pandas/core/dtypes/common.py:574: in is_categorical_dtype
    return CategoricalDtype.is_dtype(arr_or_dtype)
pandas/core/dtypes/base.py:93: in is_dtype
    return cls.construct_from_string(dtype) is not None
pandas/core/dtypes/dtypes.py:359: in construct_from_string
    if string == 'category':
pandas/core/ops.py:1885: in f
    try_cast=False)
pandas/core/frame.py:4927: in _combine_const
    return ops.dispatch_to_series(self, other, func)
pandas/core/ops.py:1678: in dispatch_to_series
    new_data = expressions.evaluate(column_op, str_rep, left, right)
pandas/core/computation/expressions.py:205: in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
pandas/core/computation/expressions.py:65: in _evaluate_standard
    return op(a, b)
pandas/core/ops.py:1658: in column_op
    for i in range(len(a.columns))}
pandas/core/ops.py:1658: in <dictcomp>
    for i in range(len(a.columns))}
pandas/core/ops.py:1510: in wrapper
    res = na_op(values, other)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
x = array([0, 2, 0]), y = 'category'
    def na_op(x, y):
        # TODO:
        # should have guarantess on what x, y can be type-wise
        # Extension Dtypes are not called here
    
        # Checking that cases that were once handled here are no longer
        # reachable.
        assert not (is_categorical_dtype(y) and not is_scalar(y))
    
        if is_object_dtype(x.dtype):
            result = _comp_method_OBJECT_ARRAY(op, x, y)
    
        elif is_datetimelike_v_numeric(x, y):
            return invalid_comparison(x, y, op)
    
        else:
    
            # we want to compare like types
            # we only want to convert to integer like if
            # we are not NotImplemented, otherwise
            # we would allow datetime64 (but viewed as i8) against
            # integer comparisons
    
            # we have a datetime/timedelta and may need to convert
            assert not needs_i8_conversion(x)
            mask = None
            if not is_scalar(y) and needs_i8_conversion(y):
                mask = isna(x) | isna(y)
                y = y.view('i8')
                x = x.view('i8')
    
            method = getattr(x, op_name, None)
            if method is not None:
                with np.errstate(all='ignore'):
>                   result = method(y)
E                   FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
```

</details>

2018-10-03 13:14 UTC, TomAugspurger commented on pandas/core/dtypes/dtypes.py
> +            else:
I think this *may* have been it. For whatever reason, we're here with

```
ipdb> pp string
   A  A
0  0  2
1  2  4
2  0  4
```

We do

```
ipdb> string == 'category'
*** FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
```

That FutureWarning is elevated to an error. I didn't realize this, but you can catch warnings, so the very simple fix is to also catch `FutureWarning` here, but that feels fragile. I'll investigate a better fix...

2018-10-03 13:15 UTC, TomAugspurger commented
Moving further discussion to https://github.com/pandas-dev/pandas/issues/22960