git log | headCLN GH22874 replace bare excepts in pandas/io/pytables.py
pandas-dev/pandas pull request #22919
Opened 2018-10-01 01:57 UTC by pambot

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-10-01 01:57 UTC, pep8speaks commented
Hello @pambot! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/io/pytables.py`](https://github.com/pambot/pandas/blob/d8eb6b0bf52c4528fc74495e0d7e2d3ddfffe5e2/pandas/io/pytables.py) !

2018-10-01 10:49 UTC, jreback requested changes

2018-10-01 10:49 UTC, jreback commented on pandas/io/pytables.py
> +        import tables
this is already imported

2018-10-01 10:49 UTC, jreback commented on pandas/io/pytables.py
> +        except (AttributeError, OverflowError, KeyError, IndexError,
since this is so many things, ok here with just Exception (put a ``# noqa: E722`` to disable the warning)

2018-10-02 21:14 UTC, jreback approved these changes

2018-10-02 21:14 UTC, merged

2018-10-02 21:14 UTC, jreback commented
thanks @pambot very nice