API/DEPR: 'periods' argument instead of 'n' for PeriodIndex.shift()
pandas-dev/pandas pull request #22912
Opened 2018-09-30 18:54 UTC by arminv

- [x] closes #22458 
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

In order to be consistent with `Index.shift` & `Series.shift` & `DatetimeIndex.shift`, `n` argument was deprecated in favor of `periods`.

```
In [2]: idx = pd.PeriodIndex(freq='A', start='1/1/2001', end='12/1/2009')

In [3]: idx
Out[3]: 
PeriodIndex(['2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
             '2009'],
            dtype='period[A-DEC]', freq='A-DEC')

In [4]: idx.shift(1)
Out[4]: 
PeriodIndex(['2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
             '2010'],
            dtype='period[A-DEC]', freq='A-DEC')

In [5]: idx.shift(periods=1)
Out[5]: 
PeriodIndex(['2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
             '2010'],
            dtype='period[A-DEC]', freq='A-DEC')

In [6]: idx.shift(n=1)
//anaconda/envs/pandas_dev/bin/ipython:1: FutureWarning: the 'n' keyword is deprecated, use 'periods' instead
  #!//anaconda/envs/pandas_dev/bin/python
Out[6]: 
PeriodIndex(['2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
             '2010'],
            dtype='period[A-DEC]', freq='A-DEC')
```

2018-09-30 18:55 UTC, pep8speaks commented
Hello @arminv! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/arrays/datetimelike.py`](https://github.com/arminv/pandas/blob/022688f2c13181b22d70770adc4bee80f5aa9461/pandas/core/arrays/datetimelike.py) !

 - There are no PEP8 issues in the file [`pandas/core/arrays/period.py`](https://github.com/arminv/pandas/blob/022688f2c13181b22d70770adc4bee80f5aa9461/pandas/core/arrays/period.py) !

 - There are no PEP8 issues in the file [`pandas/core/generic.py`](https://github.com/arminv/pandas/blob/022688f2c13181b22d70770adc4bee80f5aa9461/pandas/core/generic.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexes/period/test_arithmetic.py`](https://github.com/arminv/pandas/blob/022688f2c13181b22d70770adc4bee80f5aa9461/pandas/tests/indexes/period/test_arithmetic.py) !

2018-10-01 11:24 UTC, TomAugspurger reviewed
LGTM.

I didn't closely follow the issue and other discussion, but I just want to double-check that we really *want* to do this. DatetimeIndex / PeriodIndex.shift are fundamentally different from Series.shift, (shifting values vs. position). Still, I think changing the argument name is still for the best.

cc @jorisvandenbossche

2018-10-01 11:46 UTC, jreback commented
this is ok, we have an inconsistency in named args now.

2018-10-07 23:19 UTC, jreback commented on pandas/core/arrays/period.py
> +        Index.shift : Shift values of Index.
can you update this @arminv

2018-10-07 23:19 UTC, jreback requested changes
ping on green.

2018-10-07 23:19 UTC, jreback commented on doc/source/whatsnew/v0.24.0.txt
> +- :func:`DatetimeIndex.shift` and :func:`PeriodIndex.shift` now accept ``periods`` argument instead of ``n`` for consistency with :func:`Index.shift` and :func:`Series.shift`. Using ``n`` throws a de
can you add this issue as well here (this PR number is fine)

2018-10-08 18:25 UTC, TomAugspurger approved these changes
Sorry about the merge conflict. This looks good.

2018-10-08 19:11 UTC, arminv commented
@jreback all green.
@TomAugspurger thanks for reviewing.

2018-10-08 19:13 UTC, merged

2018-10-08 19:13 UTC, TomAugspurger commented
Thanks!