DOC: fix DataFrame.sample doctests and reformat the docstring
pandas-dev/pandas pull request #22937
Opened 2018-10-02 02:29 UTC by Moisan

- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Based on #22459. Fix the docstring for DataFrame.sample. I also updated `ci/doctests.sh`.

I was on the fence if I should remove mentions of `Panels` since it is deprecated.

2018-10-02 02:29 UTC, pep8speaks commented
Hello @Moisan! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/generic.py`](https://github.com/Moisan/pandas/blob/252958076730c2c5c52c8d8234db8c593a81a309/pandas/core/generic.py) !

2018-10-02 02:49 UTC, TomAugspurger approved these changes

2018-10-02 02:49 UTC, TomAugspurger commented on pandas/core/generic.py
> +            `inf` and `-inf` values not allowed.
If this is code literals, then it should be double-backticks and quoted

    ``'inf'``

which is a bit noise. How about "infinite values are not allowed.?

2018-10-02 02:49 UTC, TomAugspurger commented on pandas/core/generic.py
> +        numpy.choice: Generates a random sample from a given 1-D numpy array.
`numpy.random.choice`?

2018-10-02 12:16 UTC, datapythonista requested changes

2018-10-02 12:16 UTC, datapythonista commented on pandas/core/generic.py
> +        Series or DataFrame:
The colon at the end is not needed in this case.

2018-10-02 12:16 UTC, datapythonista commented on pandas/core/generic.py
> +            A new object of same type as caller.
It'd be nice to briefly describe what is returned, not only the type.

2018-10-02 12:16 UTC, datapythonista commented on pandas/core/generic.py
> +        ...                    'C': range(0, 250, 5)})
I don't think we need so much data, and being arbitrary. Something like the animal datasets we've been using with 6 or 8 rows should be better to illustrate the resample method.

2018-10-07 23:10 UTC, jreback commented
@datapythonista

2018-10-08 04:30 UTC, datapythonista approved these changes
Looks great, and very good example.

2018-10-08 04:31 UTC, merged

2018-10-08 04:31 UTC, datapythonista commented
Thanks for another excellent PR @Moisan