Analytics.py fixtures added
pandas-dev/pandas pull request #22940
Opened 2018-10-02 04:55 UTC by akulagrawal

- [ ] Analytics.py tests passed
- Analytics.py fixtures added for issue #22471

2018-10-02 04:55 UTC, pep8speaks commented
Hello @akulagrawal! Thanks for submitting the PR.

 - In the file [`pandas/tests/frame/test_analytics.py`](https://github.com/akulagrawal/pandas/blob/287ec31ace3fbd6ec2e6bd7a6770effbf85f836a/pandas/tests/frame/test_analytics.py), following                are the PEP8 issues :
> [Line 791:80](https://github.com/akulagrawal/pandas/blob/287ec31ace3fbd6ec2e6bd7a6770effbf85f836a/pandas/tests/frame/test_analytics.py#L791): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (109 > 79 characters)
> [Line 1328:80](https://github.com/akulagrawal/pandas/blob/287ec31ace3fbd6ec2e6bd7a6770effbf85f836a/pandas/tests/frame/test_analytics.py#L1328): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (109 > 79 characters)
> [Line 1842:80](https://github.com/akulagrawal/pandas/blob/287ec31ace3fbd6ec2e6bd7a6770effbf85f836a/pandas/tests/frame/test_analytics.py#L1842): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)

2018-10-02 05:00 UTC, akulagrawal commented
Oh yes. Corrected! Should I open a new PR?

2018-10-02 06:12 UTC, akulagrawal commented
There's some issue with conftest.py which wasn't earlier.

2018-10-02 06:38 UTC, h-vetinari commented
@akulagrawal 
There's an open PR for the `test_analytics.py` module at #22733 - I've referenced PRs where they exist in #22471, please check before-hand. The reason this doesn't work is that there are class methods `_check_stat_op` and `_check_bool_op` which make fixturization harder.

Again, I would recommend to test locally before you push, and get rid of all errors.

2018-10-05 03:19 UTC, WillAyd requested changes

2018-11-05 18:31 UTC, closed without merging