Use ._tshift internally for datetimelike ops
pandas-dev/pandas pull request #22949
Opened 2018-10-02 18:26 UTC by TomAugspurger

In preperation for PeriodArray / DatetimeArray / TimedeltaArray.

Index.shift has a different meaning from ExtensionArray.shift.

- Index.shift pointwise shifts each element by some amount
- ExtensionArray.shift shits the *position* of each value in the array
  padding the end with NA

This is going to get confusing. This PR tries to avoid some of that by
internally using a new `_tshift` method (time-shift) when we want to do pointwise
shifting of each value. Places that know they want that behavior (like in the
datetimelike ops) should use that.

2018-10-03 11:13 UTC, jreback requested changes

2018-10-03 11:13 UTC, jreback commented on pandas/core/arrays/datetimelike.py
> +    def _tshift(self, periods, freq=None):
why don't we call this ._time_shift or ._period_shift

2018-10-03 11:13 UTC, jreback commented on pandas/core/arrays/datetimelike.py
> +        Note this is different from ExtensionArray.shift, which
how is this relevant here? this is simply a re-definition of what shift means. I understand the desire to make things clear, but this has *always* been the case, for example in comparing a DTI to an Index.

2018-10-03 11:14 UTC, jreback requested changes

2018-10-03 11:14 UTC, jreback commented on pandas/core/arrays/datetimelike.py
> +    def _tshift(self, periods, freq=None):
if you are actually going to change this, then this should be much more consistent across the code base, e.g. does internals need changing, what about the Index classes?

2018-10-03 11:54 UTC, jreback commented on pandas/core/arrays/datetimelike.py
> +    def _tshift(self, periods, freq=None):
we have a note to deprecate tshift entirely. I don't think this is a good name at all.

2018-10-03 19:20 UTC, TomAugspurger commented
Renamed to `_time_shift`.

> if you are actually going to change this, then this should be much more consistent across the code base, e.g. does internals need changing, what about the Index classes?

Do you have particular places in mind?

2018-10-04 15:28 UTC, TomAugspurger commented
All green.

2018-10-05 12:00 UTC, jreback approved these changes

2018-10-05 12:00 UTC, merged

2018-10-05 12:00 UTC, jreback commented
thanks