BUG GH22858 When creating empty dataframe, only cast int to float if index given
pandas-dev/pandas pull request #22963
Opened 2018-10-03 05:22 UTC by JustinZhengBC

- [X] closes #22858 
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Previously, when creating a dataframe with no data of dtype int, the dtype would be changed to float. This is necessary when a predefined number of rows is included as the index parameter, so that they can be filled with nan. However, when no index is passed, this cast is unexpected. This PR changes it so dtype is only altered when necessary.

2018-10-03 05:46 UTC, JustinZhengBC commented
I updated the whatsnew for v0.24. Also, after reverting to master, I found that while passing "int64" as the dtype caused the bug, merely passing int did not. I have updated the test to reflect this.

2018-10-03 05:51 UTC, WillAyd requested changes
FWIW the tests in this module could be improved with parametrization. On the fence but I'm generally OK with not requiring that for this PR (others may have a differing opinion), but would be a good follow up if you are interested.

2018-10-03 05:51 UTC, WillAyd commented on pandas/tests/frame/test_constructors.py
> +        df = DataFrame(columns=['a', 'b'], dtype="int64")
Can you add the GH issue number as a comment to reference?

2018-10-03 05:53 UTC, WillAyd commented on doc/source/whatsnew/v0.24.0.txt
> +- A newly constructed empty :class:`DataFrame` of integers will now only be cast to ``float64`` if an index is specified (:issue:`22858`)
Hmm I think the wording `DataFrame of integers` is somewhat misleading as there aren't actually any integers here; the type is just passed explicitly during construction and not subsequently coerced.

2018-10-04 03:33 UTC, jreback requested changes
minor comments lgtm
ping on green

2018-10-04 03:33 UTC, jreback commented on doc/source/whatsnew/v0.24.0.txt
> +- A newly constructed empty :class:`DataFrame` with integer as the ``dtype`` will now only be cast to ``float64`` if ``index`` is specified (:issue:`22858`)
move to api breaking changes

2018-10-04 03:33 UTC, jreback commented on pandas/core/dtypes/cast.py
> +        if is_integer_dtype(dtype) and isna(value) and length:
put the length check first

2018-10-04 03:33 UTC, jreback commented on pandas/tests/frame/test_constructors.py
> +        (None, lrange(10), ['a', 'b'], object, np.object_),
can u rename ans -> expected

2018-10-04 03:52 UTC, jreback approved these changes
doc comment, otherwise lgtm ping on green

2018-10-04 03:52 UTC, jreback commented on doc/source/whatsnew/v0.24.0.txt
> +- A newly constructed empty :class:`DataFrame` with integer as the ``dtype`` will now only be cast to ``float64`` if ``index`` is specified (:issue:`22858`)
put in the section itself, just below this (it’s a backward incompatible change)

2018-10-04 11:48 UTC, jreback commented
@WillAyd merge when satisfied

2018-10-04 23:13 UTC, WillAyd approved these changes

2018-10-04 23:13 UTC, merged

2018-10-04 23:14 UTC, WillAyd commented
Very nice change - thanks @JustinZhengBC !