DOC: Documentation for pandas.core.indexes.api
pandas-dev/pandas pull request #22980
Opened 2018-10-03 18:52 UTC by araraonline

The functions on pandas.core.indexes.api had almost no documentation. This is an attempt to explain them better and a progress towards #22915.

2018-10-03 18:52 UTC, pep8speaks commented
Hello @araraonline! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/indexes/api.py`](https://github.com/araraonline/pandas/blob/76c3e5dd035b8de33e606a73347aa5b1258c9d12/pandas/core/indexes/api.py) !

2018-10-04 03:27 UTC, jreback requested changes

2018-10-04 03:27 UTC, jreback commented on pandas/core/indexes/api.py
> +    lack indexes (e.g. they are numpy arrays)
can u add Parameters and Returns to each of these

2018-10-05 12:47 UTC, araraonline commented on pandas/core/indexes/api.py
> +    indexes: a list of Index or array-like objects
Actually, this should be 'a list of Index or *list*objects'

Will fix soon

2018-10-06 15:17 UTC, jreback approved these changes

2018-10-06 15:18 UTC, jreback commented
context looks ok, @datapythonista or @jorisvandenbossche if you want to glance at the doc-strings; these are internal only

2018-10-09 19:56 UTC, datapythonista requested changes
Looks good, it's nice to have docs in those functions.

Few comments about formatting that apply to all docstrings:
- Start he docstring in the next line of `"""`, not in the same
- Missing space before colon in Parameters `param_name : type`
- Missing period at the end of the parameter descriptions, and the returns description.
- Use Python types for parameter types (or returns), for example `bool` instead of `boolean`. And have just the type, for example `list of bool` instead of `a list of bool`

2018-10-10 00:57 UTC, araraonline commented on pandas/core/indexes/api.py
> +        Lists are sorted and converted to Index
Will add period to this too

2018-10-10 00:57 UTC, araraonline commented on pandas/core/indexes/api.py
> +    Give a consensus 'names' to indexes,
my bad

2018-11-04 09:55 UTC, datapythonista approved these changes
Thanks for adding these docs, and sorry for the delay in reviewing.

2018-11-04 09:56 UTC, merged