BUG-22984 Fix truncation of DataFrame representations
pandas-dev/pandas pull request #22987
Opened 2018-10-04 00:10 UTC by JustinZhengBC

- [X] closes #22984 
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

When printing a DataFrame to terminal, an extra column's worth of space is added to the calculated width of the DataFrame. This is presumably to help edge cases, but the calculated difference between the DataFrame width and the terminal window width is incremented by 1 a few lines later, seemingly to fix the same problem. Do any more experienced developers know of a reason to pad the DataFrame width even more?

2018-10-04 00:10 UTC, pep8speaks commented
Hello @JustinZhengBC! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/io/formats/format.py`](https://github.com/JustinZhengBC/pandas/blob/9526ec7a9667b259849e13979b01117370b53ddc/pandas/io/formats/format.py) !

2018-10-06 15:15 UTC, jreback requested changes

2018-10-06 15:15 UTC, jreback commented on doc/source/whatsnew/v0.24.0.txt
> +- Representation of :class:`DataFrame` fills up the terminal window better
can you add the issue number here, I would call this more of a bug fix, no?

2018-10-06 15:15 UTC, jreback commented on pandas/io/formats/format.py
> -                headers = [ele[0] for ele in strcols]
we have a number of tests for this, suprised this didn't break anything, can you make a test if we have no coverage for this case now? (e.g. you use option_context to set the width, then check the output string)

2018-10-06 15:15 UTC, jreback commented
cc @jorisvandenbossche

2018-11-14 14:33 UTC, jreback approved these changes

2018-11-14 14:33 UTC, jreback commented
lgtm. @TomAugspurger a glance if you can.

2018-11-14 14:53 UTC, TomAugspurger commented on doc/source/whatsnew/v0.24.0.txt
> +- Bug in :func:`to_string()` that caused representations of :class:`DataFrame` to not take up the whole window (:issue:`22984`)
This should be :class:\`DataFrame.to_string\` right? We don't have a top-level `pandas.to_string`.

2018-11-14 14:53 UTC, TomAugspurger commented on pandas/tests/io/formats/test_format.py
nitpick: we have a pytest fixture formock now, that does the try / except / skip done above.

I think it'd be cleanest to split this into a new test here, and accept the `mock` parameter.

```python
def test_repr_truncates_terminal_size_full(self, mock):
    ...
```

Any if you're feeling adventurous, you could change the try / except / skip mock import above to use the fixture as well. Not a big deal though.

2018-11-14 17:08 UTC, jreback commented
@JustinZhengBC need to merge master

2018-11-14 20:05 UTC, TomAugspurger commented
Another hypothesis failure on azure. OK to merge @jreback? I can investigate the failing test separately.

2018-11-14 21:18 UTC, jreback commented
yep

2018-11-14 21:20 UTC, TomAugspurger commented
Merged master to fix the confict. May as well let the CI run.

2018-11-14 23:42 UTC, JustinZhengBC commented
@TomAugspurger green. Also thanks for fixing the merge issue

2018-11-15 03:02 UTC, TomAugspurger commented
I caused it my merging my own PR, so it's the least I could do :)

2018-11-15 03:02 UTC, merged