BUG: millis res on parsed DatetimeIndex slice
pandas-dev/pandas pull request #23010
Opened 2018-10-05 21:11 UTC by tapiralec

Added support for millis resolution on a parsed DatetimeIndex slice.

There was no elif statement for when _parsed_string_to_bounds(self,
reso, parsed) was given reso == 'millisecond'

- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2018-10-05 21:11 UTC, pep8speaks commented
Hello @tapiralec! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/indexes/datetimes.py`](https://github.com/tapiralec/pandas/blob/810968273b108a559bb8dec359940fa076f26bfd/pandas/core/indexes/datetimes.py) !

2018-10-06 15:13 UTC, jreback commented
is this fixing an issue? this would need tests, I am not sure what doesn't work now.

2018-10-08 18:26 UTC, tapiralec commented
Sorry for the lack of good explanation earlier. I couldn't find any existing bug in the issues that listed this problem. Basically there exists support for slicing data with a DatetimeIndex using strings for the range in core/indexes/datetimes.py (line 1263):
```
_, parsed, reso = parsing.parse_time_string(label, freq)
lower, upper = self._parsed_string_to_bounds(reso, parsed)
```
_libs/tslibs/parsing.pyx returns a resolution of milliseconds when `microsecond % 1000 == 0` (line 334)
_parsed_string_to_bounds() has if/elif's on the resolution argument for year, month, ... second, microsecond, but doesn't have one for millisecond.

I found this when I was working with data that had a precision of tenths of milliseconds (hundreds of microseconds). If you pass in a string bound with, e.g. .9871 for the fraction of the second, it slices as expected since `987100 % 1000 = 100 != 0`, so resolution is "microseconds". But if you pass in a string bound with .9870, the parsed resolution is determined to be milliseconds and _parsed_string_to_bounds() will raise a KeyError.

With regards to the tests: I'm not familiar yet with pytest / numpy.testing, but I can take a crack at writing the tests to cover this case.

2018-10-09 12:36 UTC, jreback requested changes
needs tests and a whatsnew

2018-11-23 03:32 UTC, jreback commented
closing as stale. if you'd like to continue, pls ping.

2018-11-23 03:32 UTC, closed without merging