By convention, tuples indicate multi-level lookups.
pandas-dev/pandas pull request #23034
Opened 2018-10-08 00:45 UTC by KristianHolsheimer

This change fixes nlargest/smallest functionality for dataframes with MultiIndex columns.

- [ ] closes #23033

2018-10-08 00:45 UTC, pep8speaks commented
Hello @KristianHolsheimer! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/algorithms.py`](https://github.com/KristianHolsheimer/pandas/blob/f487c0992876055efe147bcca33894e02079a874/pandas/core/algorithms.py) !

2018-10-08 01:16 UTC, jreback commented
tests

2018-10-09 12:33 UTC, jreback requested changes
pls add a whatsnew note (bug fixes, reshaping)

2018-10-09 12:33 UTC, jreback commented on pandas/tests/frame/test_analytics.py
> +        df = pd.DataFrame(
add the issue number here

2018-10-09 12:33 UTC, jreback commented on pandas/tests/frame/test_analytics.py
> +        pd.util.testing.assert_frame_equal(
just use ``tm.assert_frame_equal`` its already imported.
use 

result = 
expected = 
tm.assert_frame_equal(result, expected)

put a comment for each case (if needed, may not be here)

2018-10-11 02:03 UTC, jreback approved these changes

2018-10-11 02:03 UTC, jreback commented
lgtm. ping on green.

2018-10-18 02:40 UTC, KristianHolsheimer commented
@jreback 
Hi Jeff,

I'd been away from my PRs for a few days. I fixed a merge conflict in the whatsnew doc, but didn't do anything else. This triggered the tests and some of them are failing now. They fail on stuff I never touched, though (`rolling` etc.).

Do you know what's going on?

Thanks,
Kris

2018-10-22 22:57 UTC, KristianHolsheimer commented
retest this please

2018-10-23 03:09 UTC, WillAyd commented
Can you try merging master?

2018-10-23 12:33 UTC, jreback requested changes
small change. ping when pushed.

2018-10-23 12:33 UTC, jreback commented on doc/source/whatsnew/v0.24.0.txt
> +- Bug in :meth:`DataFrame.nsmallest` and :meth:`DataFrame.nlargest` for dataframes that have :class:`MultiIndex`ed columns (:issue:`23033`).
this needs to go to reshaping section

2018-10-24 02:30 UTC, KristianHolsheimer commented
@jreback I pushed my changes a few hours ago. Tests are still pending.

2018-10-24 12:29 UTC, jreback approved these changes

2018-10-24 12:33 UTC, merged

2018-10-24 12:33 UTC, jreback commented
thanks

2018-10-24 22:09 UTC, KristianHolsheimer commented
Thanks for reviewing