BUG: Fix PeriodIndex +/- TimedeltaIndex
pandas-dev/pandas pull request #23031
Opened 2018-10-07 22:28 UTC by jbrockmendel

I think this may close #22998, need to check (and add tests if so)

- [ ] closes #xxxx
- [x] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-10-07 22:28 UTC, pep8speaks commented
Hello @jbrockmendel! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/arrays/datetimelike.py`](https://github.com/jbrockmendel/pandas/blob/341212f5be3993cea18fdfff55d0aea1bf05600a/pandas/core/arrays/datetimelike.py) !

 - In the file [`pandas/core/arrays/period.py`](https://github.com/jbrockmendel/pandas/blob/341212f5be3993cea18fdfff55d0aea1bf05600a/pandas/core/arrays/period.py), following                are the PEP8 issues :
> [Line 369:15](https://github.com/jbrockmendel/pandas/blob/341212f5be3993cea18fdfff55d0aea1bf05600a/pandas/core/arrays/period.py#L369): [W504](https://duckduckgo.com/?q=pep8%20W504) line break after binary operator


 - There are no PEP8 issues in the file [`pandas/tests/arithmetic/test_period.py`](https://github.com/jbrockmendel/pandas/blob/341212f5be3993cea18fdfff55d0aea1bf05600a/pandas/tests/arithmetic/test_period.py) !

 - There are no PEP8 issues in the file [`pandas/util/testing.py`](https://github.com/jbrockmendel/pandas/blob/341212f5be3993cea18fdfff55d0aea1bf05600a/pandas/util/testing.py) !

 - Complete extra results for this file :

> file_to_check.py:2456:-258: W605 invalid escape sequence '\('
file_to_check.py:2456:-255: W605 invalid escape sequence '\)'
---

2018-10-07 22:28 UTC, jbrockmendel commented on pandas/util/testing.py
> +    __tracebackhide__ = True
See #22643

2018-10-07 22:53 UTC, jreback commented on pandas/core/arrays/datetimelike.py
> +                # PeriodIndex + TimedeltaIndex _sometimes_ is valid
can you clarify?

2018-10-07 22:53 UTC, jreback requested changes
add a whatsnew note

2018-10-10 00:09 UTC, jbrockmendel commented
Updated with a whatsnew and more tests.  Doing this right required more a refactor than I expected, but in the end it touches only arithmetic code and doesn't fiddle with indexing code (like the previous attempt did)

2018-10-10 00:14 UTC, jbrockmendel commented on pandas/core/arrays/period.py
> -        ordinal_delta = self._maybe_convert_timedelta(other)
Getting the _maybe_convert_timedelta call out of the arithmetic ops makes everything simpler

2018-10-10 00:17 UTC, jbrockmendel commented on pandas/core/arrays/period.py
> +            raise TypeError(type(other).__name__)
Looking at this and some of the other methods in the datetime/timedelta/period array mixins, I think some de-duplication can be done on the next pass

2018-10-14 15:34 UTC, jbrockmendel commented
gentle ping

2018-10-14 16:53 UTC, jreback commented on pandas/core/arrays/period.py
> +        assert isinstance(self.freq, Tick)  # checked by calling function
can u add a doc string here

2018-10-14 16:54 UTC, jreback commented on pandas/core/arrays/period.py
> +        elif isinstance(other, np.ndarray):
can u comments these cases a bit

2018-10-14 16:55 UTC, jreback approved these changes

2018-10-14 16:56 UTC, jreback commented
lgtm. just add a couple of comments. merge when green

2018-10-14 20:52 UTC, jbrockmendel commented
Ping

2018-10-15 00:49 UTC, merged