CLN GH22985 Fixed interpolation with object error message
pandas-dev/pandas pull request #23044
Opened 2018-10-08 14:17 UTC by pambot

- [x] closes #22985
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

It looks like the problem with #22985 is mostly the mismatch between the input trigger and the error message, so this is just a tiny hotfix.

2018-10-08 14:17 UTC, pep8speaks commented
Hello @pambot! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/generic.py`](https://github.com/pambot/pandas/blob/92139d62494063de19a0b1a2fde8aaa113409d69/pandas/core/generic.py) !

2018-10-08 17:12 UTC, jschendel requested changes
Thanks! Can you add a test to `tests/frame/test_missing.py` that reproduces the error and verifies that the message is as expected with `tm.assert_raises_regex`?

2018-10-08 22:47 UTC, jschendel approved these changes
LGTM.  One small comment:

2018-10-08 22:47 UTC, jschendel commented on pandas/tests/frame/test_missing.py
> +        df = DataFrame({
Can you add the GitHub issue number as a comment?  See two tests below for an example.  It's useful if some makes changes that cause this test to break, as it allows them to quickly find the discussion and context for the test.

2018-10-10 12:04 UTC, merged

2018-10-10 12:05 UTC, jreback commented
thanks @pambot