REF: collect ops dispatch functions in one place, try to de-duplicate SparseDataFrame methods
pandas-dev/pandas pull request #23060
Opened 2018-10-09 15:27 UTC by jbrockmendel

2018-10-09 15:27 UTC, pep8speaks commented
Hello @jbrockmendel! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/frame.py`](https://github.com/jbrockmendel/pandas/blob/5f9d11127678466b8e9fbaf3f8ea191539535e39/pandas/core/frame.py) !

 - There are no PEP8 issues in the file [`pandas/core/ops.py`](https://github.com/jbrockmendel/pandas/blob/5f9d11127678466b8e9fbaf3f8ea191539535e39/pandas/core/ops.py) !

 - There are no PEP8 issues in the file [`pandas/core/sparse/frame.py`](https://github.com/jbrockmendel/pandas/blob/5f9d11127678466b8e9fbaf3f8ea191539535e39/pandas/core/sparse/frame.py) !

 - There are no PEP8 issues in the file [`pandas/tests/arithmetic/test_numeric.py`](https://github.com/jbrockmendel/pandas/blob/5f9d11127678466b8e9fbaf3f8ea191539535e39/pandas/tests/arithmetic/test_numeric.py) !

2018-10-10 13:48 UTC, jbrockmendel commented
Woops, accidentally pushed some unrelated commits collecting arithmetic tests.

2018-10-11 01:00 UTC, jreback requested changes
looks good. just a couple of questions / comments.

2018-10-11 01:00 UTC, jreback commented on pandas/tests/series/test_arithmetic.py
> +    @pytest.mark.parametrize('opname', ['add', 'sub', 'mul', 'floordiv',
ideally switch to our operators fixture

2018-10-11 01:33 UTC, jbrockmendel commented on pandas/core/ops.py
> +    import pandas.core.computation.expressions as expressions
I'm not 100% sure, but I think this is a run-time import to make `import pandas as pd` faster

2018-10-11 01:36 UTC, jbrockmendel commented on pandas/core/sparse/frame.py
> +            elif np.isnan(own_default) and not np.isnan(other_default):
At first I thought so, but the module-level docstring says only float64 is supported, so I kept the behavior as-is.  I think the overall takeaway is that this isn't especially well-maintained, and we should all look forward to Sparse EA.

2018-10-11 01:37 UTC, jbrockmendel commented on pandas/tests/frame/test_arithmetic.py
> +        ops = {'gt': 'lt', 'lt': 'gt', 'ge': 'le', 'le': 'ge', 'eq': 'eq',
Yah, the point of collecting these arithmetic tests is to parametrize/fixturize and especially de-duplicate them in an upcoming pass.

2018-10-23 03:14 UTC, jreback commented on pandas/tests/frame/test_arithmetic.py
> +                                         for col in x.columns},
can you parameterize this (next pass ok)

2018-10-25 04:33 UTC, jbrockmendel commented
If it will help, I can separate out the unrelated test parts of this.  There is a bunch of test cleanup to do, and already a healthy number of test-touching PRs in play.

2018-10-26 01:39 UTC, jreback approved these changes
comment, but can be a followup, ping on green.

2018-10-26 01:39 UTC, jreback commented on pandas/core/sparse/frame.py
> +            elif np.isnan(own_default) and not np.isnan(other_default):
can this be amendednow that that Sparse EA is here? (followup ok too)

2018-10-26 01:41 UTC, jbrockmendel commented
> can this be amendednow that that Sparse EA is here? (followup ok too)

@TomAugspurger any idea about this?  I have no clue

2018-10-26 01:57 UTC, jreback commented
also happy to merge this and followup later on sparse refactorings (prob better).

2018-10-26 04:32 UTC, jbrockmendel commented
Ping

2018-10-26 14:16 UTC, jbrockmendel commented on pandas/core/sparse/frame.py
> +            elif np.isnan(own_default) and not np.isnan(other_default):
Sounds good, thanks.

2018-10-28 03:18 UTC, jreback commented
can you rebase. the isort is playing havoc :>

2018-10-28 13:48 UTC, merged

2018-10-28 13:49 UTC, jreback commented
thanks @jbrockmendel nice as always!