Fixing memory leaks in read_csv
pandas-dev/pandas pull request #23072
Opened 2018-10-10 08:33 UTC by zhezherun

This PR fixes a memory leak in parsers.pyx detected by valgrind, and also adds some further cleanup that should avoid memory leaks on exceptions, as discussed in #21353:

- Moved the allocation of na_hashset further down, closer to where it is used. Otherwise it will not be freed if `continue` is executed,
- Delete `na_hashset` if there is an exception,
- Also clean up the allocation inside `kset_from_list` before raising an exception.

2018-10-10 11:40 UTC, jreback commented
can you run the asv's for csv to see if any effects & a whatsnew note

2018-10-10 11:42 UTC, jreback commented
can you run the code at the very top of the issue here and show the leak has disappeared.

2018-10-10 12:19 UTC, zhezherun commented
@kuraga, would you be able to test this change on your reproducer from #21353?

@jreback, not sure what asv's for CVS are.

This patch fixes a memory leak in some proprietary code I was working on so I can't post it here, and I don't have a standalone reproducer for my issue, sorry. The reason why I mentioned #21353 was that the leak I was seeing was also coming from read_csv.

2018-10-10 12:27 UTC, jreback commented
@zhezherun i understand, look at the top of the issue. there is a script at the top. pls run that with the new version.

2018-10-10 12:30 UTC, TomAugspurger commented
@zhezherun do you know, will this patch address https://github.com/pandas-dev/pandas/issues/19941 as well? Would this memory leak have been exacerbated by multiple threads, or do you think that's a different issue?

2018-10-10 13:43 UTC, TomAugspurger commented
I pulled down this branch and confirmed that it does not fix #19941 (but @zhezherun if you have any guesses on what may be going on there it'd be appreciated).

2018-10-11 00:50 UTC, jreback commented
@zhezherun can you add a whatsnew note in bug fixes / io section, mentioning the issue number. ping on green.

2018-10-18 16:15 UTC, jreback commented
@zhezherun can you update

2018-11-03 14:23 UTC, jreback requested changes
small comments, ping on green.

2018-11-18 18:36 UTC, jreback commented
@gfyoung can you rebase and fix up?

2018-11-19 02:34 UTC, gfyoung commented on doc/source/whatsnew/v0.24.0.txt
> +- Fixed memory leak in :func:`read_csv` (:issue:`21353`)
Done.

2018-11-19 02:40 UTC, gfyoung commented on pandas/_libs/parsers.pyx
> +            # XXX
Done.

2018-11-19 02:40 UTC, gfyoung commented on pandas/_libs/parsers.pyx
> +            try:
Done.

2018-11-19 02:43 UTC, jreback approved these changes

2018-11-19 02:43 UTC, jreback commented
lgtm. ping on green.

2018-11-19 05:43 UTC, gfyoung commented
@jreback : Comments addressed, and all is green.  PTAL.

2018-11-19 12:09 UTC, merged

2018-11-19 12:09 UTC, TomAugspurger commented
Thanks all.

2020-07-23 13:45 UTC, wasonkartik commented
Hi, I am facing this issue on google compute engine (Windows Server 2012 R2 Datacenter, 64 bit). How do I fix it? I have installed the latest version of Pandas.