add DataFrame.pearson_with, for calculate pearson matrix between two dataframes;
pandas-dev/pandas pull request #23175
Opened 2018-10-16 04:48 UTC by cahhbwy

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-10-16 04:48 UTC, pep8speaks commented
Hello @cahhbwy! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/frame.py`](https://github.com/cahhbwy/pandas/blob/bc9148bca9737065200bf3c27fad4395fe837428/pandas/core/frame.py) !

2018-10-17 05:37 UTC, mroeschke commented
Is there an outstanding issue that discusses adding this method?

2018-10-17 12:41 UTC, jreback requested changes

2018-10-17 12:41 UTC, jreback commented on pandas/core/frame.py
> +    def pearson_with(self, other, min_periods=1):
we won't accept another top level method, but would accept a cythonized dispatch, add a method keyword similar to https://github.com/pandas-dev/pandas/pull/22375

2018-11-24 02:21 UTC, closed without merging