BUG: sets in str.cat
pandas-dev/pandas pull request #23187
Opened 2018-10-16 19:15 UTC by h-vetinari

- [x] closes #23009
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

This is split off from #23065.

2018-10-16 19:15 UTC, pep8speaks commented
Hello @h-vetinari! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/strings.py`](https://github.com/h-vetinari/pandas/blob/6f32d435c3335aba360080f6adb19e2426eee435/pandas/core/strings.py) !

 - There are no PEP8 issues in the file [`pandas/tests/test_strings.py`](https://github.com/h-vetinari/pandas/blob/6f32d435c3335aba360080f6adb19e2426eee435/pandas/tests/test_strings.py) !

2018-10-18 20:47 UTC, h-vetinari commented
@jreback 
Tiny follow-up to / split-off from #23065, all green and ready for review

2018-10-19 13:08 UTC, jreback requested changes
minor comments, ping on green.

2018-10-19 13:08 UTC, jreback commented on doc/source/whatsnew/v0.24.0.txt
> +- Bug in :meth:`Series.str.cat` which falsely did not raise if `others` was a `set` (:issue:`23009`)
this is an api breaking change, so move it there. make this declerative as well, e.g. Series.str.cat will now raise if others is a set

2018-10-19 13:08 UTC, jreback commented on pandas/tests/test_strings.py
> +        # forbidden input type: set
add the issue number here

2018-10-23 03:10 UTC, merged

2018-10-23 03:10 UTC, jreback commented
thanks!