Duplicated keep all
pandas-dev/pandas pull request #23252
Opened 2018-10-20 16:56 UTC by svenharris

- [ ] closes #23251
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Unfortunately this didn't end up being as clean as I had hoped (due to preventing keep="all" being allowed when calling implicitly through drop_duplicates. So put in a bit of duplication of error handling. Happy to take suggestions if there's a better approach.

2018-10-20 16:56 UTC, pep8speaks commented
Hello @svenharris! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/algorithms.py`](https://github.com/svenharris/pandas/blob/ddfebd42eaf7d13e9e54566e4872a7851278ebe6/pandas/core/algorithms.py) !

 - There are no PEP8 issues in the file [`pandas/core/base.py`](https://github.com/svenharris/pandas/blob/ddfebd42eaf7d13e9e54566e4872a7851278ebe6/pandas/core/base.py) !

 - There are no PEP8 issues in the file [`pandas/core/frame.py`](https://github.com/svenharris/pandas/blob/ddfebd42eaf7d13e9e54566e4872a7851278ebe6/pandas/core/frame.py) !

 - There are no PEP8 issues in the file [`pandas/core/indexes/base.py`](https://github.com/svenharris/pandas/blob/ddfebd42eaf7d13e9e54566e4872a7851278ebe6/pandas/core/indexes/base.py) !

 - There are no PEP8 issues in the file [`pandas/core/series.py`](https://github.com/svenharris/pandas/blob/ddfebd42eaf7d13e9e54566e4872a7851278ebe6/pandas/core/series.py) !

 - There are no PEP8 issues in the file [`pandas/tests/frame/test_duplicates.py`](https://github.com/svenharris/pandas/blob/ddfebd42eaf7d13e9e54566e4872a7851278ebe6/pandas/tests/frame/test_duplicates.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexes/multi/test_duplicates.py`](https://github.com/svenharris/pandas/blob/ddfebd42eaf7d13e9e54566e4872a7851278ebe6/pandas/tests/indexes/multi/test_duplicates.py) !

 - There are no PEP8 issues in the file [`pandas/tests/series/test_duplicates.py`](https://github.com/svenharris/pandas/blob/ddfebd42eaf7d13e9e54566e4872a7851278ebe6/pandas/tests/series/test_duplicates.py) !

2018-10-23 05:25 UTC, WillAyd requested changes

2018-11-23 03:36 UTC, jreback commented
closing as stale. if you'd like to continue, pls ping.

2018-11-23 03:36 UTC, closed without merging

2018-11-23 07:59 UTC, svenharris commented
Will come back to this if I (or anyone else) thinks of a good idea for the design but there wasn't consensus in the discussion what the change should look like