CLN: isort imports
pandas-dev/pandas pull request #23331
Opened 2018-10-25 16:46 UTC by alimcmaster1

Signed-off-by: alimcmaster1 <alimcmaster1@gmail.com>

util directory/.py files in pandas directory.

- [x] follow up from #23096
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-10-25 16:47 UTC, pep8speaks commented
Hello @alimcmaster1! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/_version.py`](https://github.com/alimcmaster1/pandas/blob/9795a6cc11343b2beb2703bfab309e103d6ef1c8/pandas/_version.py) !

 - There are no PEP8 issues in the file [`pandas/conftest.py`](https://github.com/alimcmaster1/pandas/blob/9795a6cc11343b2beb2703bfab309e103d6ef1c8/pandas/conftest.py) !

 - There are no PEP8 issues in the file [`pandas/lib.py`](https://github.com/alimcmaster1/pandas/blob/9795a6cc11343b2beb2703bfab309e103d6ef1c8/pandas/lib.py) !

 - There are no PEP8 issues in the file [`pandas/parser.py`](https://github.com/alimcmaster1/pandas/blob/9795a6cc11343b2beb2703bfab309e103d6ef1c8/pandas/parser.py) !

 - There are no PEP8 issues in the file [`pandas/testing.py`](https://github.com/alimcmaster1/pandas/blob/9795a6cc11343b2beb2703bfab309e103d6ef1c8/pandas/testing.py) !

 - There are no PEP8 issues in the file [`pandas/tslib.py`](https://github.com/alimcmaster1/pandas/blob/9795a6cc11343b2beb2703bfab309e103d6ef1c8/pandas/tslib.py) !

 - There are no PEP8 issues in the file [`pandas/util/_decorators.py`](https://github.com/alimcmaster1/pandas/blob/9795a6cc11343b2beb2703bfab309e103d6ef1c8/pandas/util/_decorators.py) !

 - There are no PEP8 issues in the file [`pandas/util/_depr_module.py`](https://github.com/alimcmaster1/pandas/blob/9795a6cc11343b2beb2703bfab309e103d6ef1c8/pandas/util/_depr_module.py) !

 - There are no PEP8 issues in the file [`pandas/util/_doctools.py`](https://github.com/alimcmaster1/pandas/blob/9795a6cc11343b2beb2703bfab309e103d6ef1c8/pandas/util/_doctools.py) !

 - There are no PEP8 issues in the file [`pandas/util/_print_versions.py`](https://github.com/alimcmaster1/pandas/blob/9795a6cc11343b2beb2703bfab309e103d6ef1c8/pandas/util/_print_versions.py) !

 - There are no PEP8 issues in the file [`pandas/util/_test_decorators.py`](https://github.com/alimcmaster1/pandas/blob/9795a6cc11343b2beb2703bfab309e103d6ef1c8/pandas/util/_test_decorators.py) !

 - There are no PEP8 issues in the file [`pandas/util/decorators.py`](https://github.com/alimcmaster1/pandas/blob/9795a6cc11343b2beb2703bfab309e103d6ef1c8/pandas/util/decorators.py) !

 - There are no PEP8 issues in the file [`pandas/util/testing.py`](https://github.com/alimcmaster1/pandas/blob/9795a6cc11343b2beb2703bfab309e103d6ef1c8/pandas/util/testing.py) !

2018-10-25 16:57 UTC, WillAyd approved these changes
lgtm if green

2018-10-25 19:33 UTC, alimcmaster1 commented
Any chance a core dev - could restart the 3.6 build on Travis. ( Or grant me the relevant permission so I can do this myself going forward - happy to discuss this offline if appropriate )

I seem to be getting this:
`The job exceeded the maximum time limit for jobs, and has been terminated`

2018-10-25 20:22 UTC, TomAugspurger commented
Restarted. LMK if it times out again and I'll take a closer look.

2018-10-26 00:02 UTC, jreback commented
pls merge master. and ping on green.

2018-10-26 01:53 UTC, jreback commented
needs another merge of master

2018-10-28 02:29 UTC, jreback requested changes

2018-10-28 02:29 UTC, jreback commented on pandas/util/testing.py
> +# pylint: disable-msg=W0402
why is this here?

2018-10-28 02:29 UTC, jreback commented on pandas/lib.py
> +
can you remove the deprecated ones they are being removed elsewhere

2018-10-29 12:10 UTC, jreback commented
can you merge master, we just updated the isort cfg

2018-10-29 22:05 UTC, alimcmaster1 commented
ping - @jreback merged master and now green

2018-10-30 12:24 UTC, jreback approved these changes

2018-10-30 12:24 UTC, merged