unpin openpyxl
pandas-dev/pandas pull request #23361
Opened 2018-10-26 14:02 UTC by alimcmaster1

- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

- Follow up from #22601.

- Confirmed with openpyxl this bug was fixed in version 2.5.7 see [bitbucket issue here](https://bitbucket.org/openpyxl/openpyxl/issues/1093/newly-introduced-keyerror-problem-in)

This was release 13th Sept -> https://pypi.org/project/openpyxl/#history

2018-10-27 06:49 UTC, gfyoung approved these changes

2018-10-28 02:53 UTC, jreback requested changes
can you merge master. ping on green.

2018-10-28 02:53 UTC, jreback commented on ci/azure-27-compat.yaml
> -  - openpyxl=2.5.5
can you leave this pin here

2018-10-28 20:08 UTC, alimcmaster1 commented
ping - updated as per @jreback comments and now green - thanks @gfyoung too!

2018-10-28 20:14 UTC, jreback approved these changes

2018-10-28 20:14 UTC, merged

2018-10-28 20:14 UTC, jreback commented
thanks @alimcmaster1

2018-10-29 23:59 UTC, alimcmaster1 commented
@jreback this is strange -  this seems to have gone green on Azure despite the fact https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=2029&view=ms.vss-test-web.test-result-details tests seem to be failing on MacOS-35, or am I missing something?

2018-11-01 20:32 UTC, alimcmaster1 commented
@TomAugspurger thought I would also bring my above comment to your attention. Do you want me to create an issue? Pretty sure we want azure pipeline to fail if tests fail?

2018-11-01 21:59 UTC, TomAugspurger commented
Yeah, we want the CI status to be failed when the tests fails.

Skimming https://github.com/Microsoft/azure-pipelines-tasks/issues/1268 didn't make sense to me. I suppose we could only publish tests results if there's not a failure?