BUG-23428 Series.get fills in defaults correctly for multiple indices
pandas-dev/pandas pull request #23436
Opened 2018-10-31 23:53 UTC by JustinZhengBC

- [X] closes #23428
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

This PR makes the default parameter in `Series.get` behave as expected with multiple indices. Some of the testing classes had to be altered to make them work with receiving `None` (the default value for the `default` parameter in `Series.get`).

2018-10-31 23:53 UTC, pep8speaks commented
Hello @JustinZhengBC! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/generic.py`](https://github.com/JustinZhengBC/pandas/blob/6f29e8d4076413e83cb9cb7a3d09fd011c9a755d/pandas/core/generic.py) !

 - There are no PEP8 issues in the file [`pandas/tests/extension/decimal/array.py`](https://github.com/JustinZhengBC/pandas/blob/6f29e8d4076413e83cb9cb7a3d09fd011c9a755d/pandas/tests/extension/decimal/array.py) !

 - There are no PEP8 issues in the file [`pandas/tests/extension/json/array.py`](https://github.com/JustinZhengBC/pandas/blob/6f29e8d4076413e83cb9cb7a3d09fd011c9a755d/pandas/tests/extension/json/array.py) !

 - There are no PEP8 issues in the file [`pandas/tests/series/indexing/test_indexing.py`](https://github.com/JustinZhengBC/pandas/blob/6f29e8d4076413e83cb9cb7a3d09fd011c9a755d/pandas/tests/series/indexing/test_indexing.py) !

2018-11-01 00:21 UTC, jreback requested changes
I am not sure I buy this functionaily at all. This is a huge expansion. ``.get()`` accepts only a scalar; it would be suprising to actually accept a list. Why is this useful?

2018-11-01 00:21 UTC, jreback commented on pandas/tests/extension/decimal/array.py
> +        if value is None:
huh? this is simply an invalid input if None is passed here

2018-11-01 00:29 UTC, JustinZhengBC commented
Oh I was just looking at the issue this PR is meant to fix. In the example given in that thread, it looked like `.get()` was supposed to work with multiple indices. If that's not the case then this can be closed.

2018-11-01 00:34 UTC, jreback commented
thanks, closing.

2018-11-01 00:34 UTC, closed without merging