PERF: cython optimizations
pandas-dev/pandas pull request #23477
Opened 2018-11-03 23:23 UTC by jbrockmendel

cython was emitting some warnings about untyped array lookups in `tslibs.conversion`; added types to those

`arr.fill(val)` is a python call, while `arr[:]` is a C call, so replaced all of those

modernized an old non-python for-loop, some other small cleanups along the way.

We're running out of available optimizations/cleanups in these files.  One thing I'd be interested in changing (but I'm not confident enough to do) is removing uses of `double` and `double_t`, which I _think_ are equivalent to `float64_t`.  But I'm not sure if that is architecture or platform dependent or something.

2018-11-04 07:30 UTC, gfyoung commented on pandas/_libs/tslibs/timestamps.pyx
> +    raise ValueError("round_nsint64 called with an unrecognized rounding mode")
Given that this is a `def ` function, is this error tested in any way?

2018-11-04 07:31 UTC, gfyoung commented
> We're running out of available optimizations/cleanups in these files.

@jbrockmendel : Gosh, I wonder whose **"FAULT"** that is 😉

2018-11-04 15:21 UTC, jreback requested changes
minor comment.

2018-11-04 21:34 UTC, jbrockmendel commented
BTW any idea about the double_t thing?

2018-11-04 21:40 UTC, jreback commented
what is the problem with double_t ?
this is just float64

2018-11-04 21:43 UTC, jbrockmendel commented
> what is the problem with double_t ?  this is just float64

Yah that's the thing I want to double-check before changing all the places where we currently use `double` or `double_t` to `float64_t`

2018-11-06 03:23 UTC, jreback approved these changes

2018-11-06 03:23 UTC, merged