BUG: Fix of handle missing CSV MI column names
pandas-dev/pandas pull request #23484
Opened 2018-11-04 09:06 UTC by gfyoung

De-hackifies this hack:

https://github.com/pandas-dev/pandas/blob/d78bd7a65f87022bae5021d36c8656c0ea5a7b76/pandas/io/parsers.py#L3206-L3211

Setup:

~~~python
from pandas.compat import StringIO
from pandas import read_csv

data = ",,col\na,c,1\na,d,2\nb,c,3\nb,d,4"
print(read_csv(StringIO(data), index_col=[0, 1]))

data = "NotReallyUnnamed,Unnamed: 0,col\na,c,1\na,d,2\nb,c,3\nb,d,4"
print(read_csv(StringIO(data), index_col=[0, 1]))
~~~

Before:

~~~python
# Why only `index_names[0]` ?
              col
  Unnamed: 1
a c             1
  d             2
b c             3
  d             4

# Having "Unnamed" in the name doesn't make it replace-able ?
              col
  Unnamed: 0
a c             1
  d             2
b c             3
  d             4
~~~

After:

~~~python
# All placeholder names get dropped.
              col
a c             1
  d             2
b c             3
  d             4

# Non-placeholder names never get dropped.
                             col
NotReallyUnnamed Unnamed: 0
a                c             1
                 d             2
b                c             3
                 d             4
~~~

2018-11-04 09:06 UTC, pep8speaks commented
Hello @gfyoung! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/io/parsers.py`](https://github.com/gfyoung/pandas/blob/41ef255c8559febda7b815e37316dd7061dc550a/pandas/io/parsers.py) !

 - There are no PEP8 issues in the file [`pandas/tests/io/parser/index_col.py`](https://github.com/gfyoung/pandas/blob/41ef255c8559febda7b815e37316dd7061dc550a/pandas/tests/io/parser/index_col.py) !

2018-11-04 11:19 UTC, jreback requested changes

2018-11-04 11:19 UTC, jreback commented on pandas/io/parsers.py
> +                        this_columns.append(col_name)
so we still need unnamed_count ?
does unnamed_cols need to be a set or can it be a list? (you can always convert to a set later if needed)

2018-11-05 07:12 UTC, gfyoung commented
@jreback : I simplified the logic a little bit, but I still needed `unnamed_count` in some cases because it's computed on a per-iteration basis of a for-loop, whereas `unnamed_cols` is a global collection.  Everything is still green though.  PTAL.

2018-11-06 03:22 UTC, jreback requested changes

2018-11-06 04:16 UTC, gfyoung commented on pandas/_libs/parsers.pyx
> +                    if old_name == '':
Not quite.  You need to add the name that you get post-mangling (e.g. if there are dupes).  That's why you have to "keep track" after the logic ending at 794.

2018-11-06 13:08 UTC, jreback approved these changes

2018-11-06 13:08 UTC, merged

2018-11-06 13:08 UTC, jreback commented
thanks!