CI: Exclude asv benchmark envs from flake8 checks
pandas-dev/pandas pull request #23497
Opened 2018-11-04 20:35 UTC by qwhelan

When running `ci/code_checks.sh` on a local repository that has also been used to run `asv` benchmarks, `flake8` also lints the environments created. This massively increases the runtime and leads to linting errors on non-`pandas` packages, which is not informative.

This change simply adds `env` to the `flake8` default exclude list, which resolves the issue seen above.

### Before
```
~/projects/pandas$ LINT=true ./ci/code_checks.sh
inside ./ci/code_checks.sh

flake8 --version
3.6.0 (mccabe: 0.6.1, pycodestyle: 2.4.0, pyflakes: 2.0.0) CPython 3.6.5 on Linux
Linting .py code
./asv_bench/env/83b3be1235aa7b08e8a17448e2f70790/bin/runxlrd.py:18:80: E501 line too long (80 > 79 characters)
./asv_bench/env/83b3be1235aa7b08e8a17448e2f70790/bin/runxlrd.py:38:15: E401 multiple imports on one line
./asv_bench/env/83b3be1235aa7b08e8a17448e2f70790/bin/runxlrd.py:43:5: E303 too many blank lines (2)
./asv_bench/env/83b3be1235aa7b08e8a17448e2f70790/bin/runxlrd.py:65:24: E701 multiple statements on one line (colon)
./asv_bench/env/83b3be1235aa7b08e8a17448e2f70790/bin/runxlrd.py:66:19: E701 multiple statements on one line (colon)
./asv_bench/env/83b3be1235aa7b08e8a17448e2f70790/bin/runxlrd.py:71:25: E128 continuation line under-indented for visual indent
...
```

### After
```
~/projects/pandas$ LINT=true ./ci/code_checks.sh
inside ./ci/code_checks.sh
Could not find conda environment: pandas
You can list all discoverable environments with `conda info --envs`.

flake8 --version
3.6.0 (mccabe: 0.6.1, pycodestyle: 2.4.0, pyflakes: 2.0.0) CPython 3.6.5 on Linux
Linting .py code
./versioneer.py:423:1: E305 expected 2 blank lines after class or function definition, found 1
./versioneer.py:467:1: E305 expected 2 blank lines after class or function definition, found 0
./versioneer.py:927:-11937: W605 invalid escape sequence '\s'
```

### Output comparison
```
~/projects/pandas$ ls -altrh code_check*
-rw-rw-rw- 1 chris chris 32M Nov  4 12:31 code_check_old.log
-rw-rw-rw- 1 chris chris 14K Nov  4 12:33 code_check_new.log
```

2018-11-04 20:38 UTC, jreback requested changes
can u move these to the setup.cfg section instead

2018-11-04 20:40 UTC, qwhelan commented
@jreback Done

2018-11-05 00:22 UTC, datapythonista approved these changes
lgtm

You could add a comment too, something like `env  # directory created by asv after a run`. Not being in the repo, we may have the temptation to delete it later on

2018-11-05 20:21 UTC, qwhelan commented
@datapythonista Done

2018-11-06 01:49 UTC, jreback approved these changes

2018-11-06 01:49 UTC, merged

2018-11-06 01:49 UTC, jreback commented
thanks @qwhelan