BUG: pivot/unstack leading to too many items should raise exception
pandas-dev/pandas pull request #23512
Opened 2018-11-05 16:56 UTC by sweb

- [x] closes #20601
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

I did not provide a whatsnew entry for a new ValueError but I am happy to to so if required.

2018-11-05 16:56 UTC, pep8speaks commented
Hello @sweb! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/reshape/reshape.py`](https://github.com/sweb/pandas/blob/5f03406088a94f71f1602aaaeb2273a9b9a7b975/pandas/core/reshape/reshape.py) !

 - There are no PEP8 issues in the file [`pandas/tests/reshape/test_reshape.py`](https://github.com/sweb/pandas/blob/5f03406088a94f71f1602aaaeb2273a9b9a7b975/pandas/tests/reshape/test_reshape.py) !

2018-11-05 19:18 UTC, jreback commented
is this like #20784 ? (you can take that over if you wish)

2018-11-05 20:32 UTC, sweb commented
Yes, it is quite similar, however my changes are a bit more local. I do not attempt to compute how many rows/cols are allowed but just check whether the already computed value is negative due to an integer overflow.

However, it appears that this is OS dependent. On Unix `np.product` will not result in a negative value, but directly computes with `int64` or promotes it after reaching a limit.

In my current solution I explicitly set `dtype` of `np.product` to `int32` - this will mean a change in current behavior for Unix systems.

Do you think this is a valid approach or should we set it to `int64` as originally proposed?

2018-11-06 03:13 UTC, jreback commented
@sweb the approach in the other issue is good.

2018-11-06 15:21 UTC, jreback commented
you can simply cherry-pick that commit (ideally). or you can copy it whatever works.

2018-11-08 12:04 UTC, sweb commented
@jreback Thanks for the advice. I patched the commits of the other PR into this branch. Unfortunately, the proposed solution does not solve the problem - at least not on my environment.

Since this is most likely a Windows-specific error (I checked the example from #20601 on MacOs and everything works fine - I did not check it on Linux yet) the proposed solution would actually limit the capabilities of unstack().

In addition, on my Win10 machine, I still get an error, since `num_rows * num_columns` also overflows and the condition `if num_rows * num_columns > (2 ** 31 - 1)` is never met.

I modified the PR in that a numpy warning, indicating the overflow is caught instead of checking the upper bound of int32. The tests are only applied to Windows environments.

Can you replicate this? Maybe my Windows environment setup is screwed up.

2018-11-11 16:28 UTC, jreback requested changes

2018-11-12 13:48 UTC, sweb commented on pandas/tests/reshape/test_pivot.py
> +        if sys.platform == 'win32':
I don't know 100% percent, but numpy appears to treat int32 differently on Windows than on Unix:
https://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine/36279549

https://github.com/numpy/numpy/issues/8433

On my MacOs environment, the code from the issue works - takes some time but pandas (0.23.4) computes the expected result while my Windows environment encounters the described error. I therefore think, that this is a Windows only issue and we probably should not limit other OS versions by always checking against the int32 upper limit.

2018-11-12 13:49 UTC, sweb commented on pandas/core/reshape/pivot.py
> -    grouped = data.groupby(keys, observed=False)
Good question - this is from the original pull request and I did not know what it was for. I will change it back to the way it was.

2018-11-12 13:50 UTC, sweb commented on pandas/core/reshape/reshape.py
> +        num_rows = np.max([index_level.size for index_level
Good point - I will add the original comment from a later commit I did not cherry pick.

2018-11-12 14:12 UTC, sweb commented on pandas/tests/reshape/test_pivot.py
> +                            'ind2': np.arange(2 ** 16),
Can you explain this further? If I decrease the value to `2 ** 15` I do not get an overflow.

2018-12-03 02:01 UTC, jreback commented
can you merge master

2018-12-30 17:52 UTC, sweb commented
The ValueError now raises regardless of OS.

2018-12-30 19:51 UTC, jreback requested changes
lgtm. if you can add a whatsnew, put in reshaping bug fix section. saying that the error message is now improved, for pivoting with > int32.max uniques (obviously make a nice sentence about this).

2018-12-31 12:33 UTC, sweb commented
Whatsnew added, thank you for your help!

2018-12-31 13:16 UTC, jreback approved these changes

2018-12-31 13:16 UTC, merged

2018-12-31 13:16 UTC, jreback commented
thanks!