BUG: Don't over-optimize memory with jagged CSV
pandas-dev/pandas pull request #23527
Opened 2018-11-06 09:08 UTC by gfyoung

With jagged CSV's, we risk being too quick to dump memory that we need to allocate because previous chunks would have indicated much larger rows than we can anticipate in subsequent chunks.

Closes #23509.

2018-11-06 09:08 UTC, pep8speaks commented
Hello @gfyoung! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/tests/io/parser/common.py`](https://github.com/gfyoung/pandas/blob/feccd27b2725b71b6223f2a8fa4569d0b04e29da/pandas/tests/io/parser/common.py) !

2018-11-07 17:11 UTC, gfyoung commented
@jreback : Any thoughts on this one?

2018-11-08 13:34 UTC, jreback commented
can you run the current benchmarks on this. do we have any that specifically target this?

2018-11-08 16:59 UTC, gfyoung commented
@jreback : No specific benchmarks as far as know, though I did not observe any meaningful changes to the benchmarks after making this change.

2018-11-10 10:55 UTC, gfyoung commented
@jreback : Any other thoughts on this?

2018-11-11 16:16 UTC, jreback requested changes
@gfyoung ok I reviewed the original issue. so lgtm. if you would add some comments on the parts you added for future readers should be great. ping on green.

2018-11-11 16:16 UTC, jreback commented on pandas/_libs/src/parser/tokenizer.c
can you add a comment here

2018-11-11 16:16 UTC, jreback commented on pandas/_libs/src/parser/tokenizer.c
> +
can you add a comment here

2018-11-12 00:46 UTC, gfyoung commented on pandas/_libs/src/parser/tokenizer.c
Yep, done.

2018-11-12 00:47 UTC, gfyoung commented on pandas/_libs/src/parser/tokenizer.c
> +
Yep, done.

2018-11-12 07:19 UTC, gfyoung commented
@jreback : Addressed the doc comments, and all is still green.  PTAL.

2018-11-12 13:12 UTC, jreback approved these changes

2018-11-12 13:13 UTC, merged

2018-11-12 13:13 UTC, jreback commented
thanks @gfyoung