Ea public api
pandas-dev/pandas pull request #23532
Opened 2018-11-06 16:56 UTC by TomAugspurger

**API Changes**

Adds

* pandas.integer_array
* pandas.period_array
* pandas.IntervalArray
* pandas.CategoricalDtype
* pandas.api.extensions.IntergerArray
* pandas.api.extensions.PeriodDtype
* pandas.api.extensions.PeriodArray
* pandas.api.extensions.IntervalDtype
* pandas.api.extensions.DatetimeTZDtype

And adds documentation for those.

Closes https://github.com/pandas-dev/pandas/issues/22860

2018-11-06 16:56 UTC, pep8speaks commented
Hello @TomAugspurger! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/api/extensions/__init__.py`](https://github.com/TomAugspurger/pandas/blob/2e492bc8292bdd4105e72d757453210c7a499d69/pandas/api/extensions/__init__.py) !

 - There are no PEP8 issues in the file [`pandas/core/api.py`](https://github.com/TomAugspurger/pandas/blob/2e492bc8292bdd4105e72d757453210c7a499d69/pandas/core/api.py) !

 - There are no PEP8 issues in the file [`pandas/core/arrays/categorical.py`](https://github.com/TomAugspurger/pandas/blob/2e492bc8292bdd4105e72d757453210c7a499d69/pandas/core/arrays/categorical.py) !

 - There are no PEP8 issues in the file [`pandas/core/arrays/interval.py`](https://github.com/TomAugspurger/pandas/blob/2e492bc8292bdd4105e72d757453210c7a499d69/pandas/core/arrays/interval.py) !

 - There are no PEP8 issues in the file [`pandas/core/arrays/period.py`](https://github.com/TomAugspurger/pandas/blob/2e492bc8292bdd4105e72d757453210c7a499d69/pandas/core/arrays/period.py) !

 - There are no PEP8 issues in the file [`pandas/tests/api/test_api.py`](https://github.com/TomAugspurger/pandas/blob/2e492bc8292bdd4105e72d757453210c7a499d69/pandas/tests/api/test_api.py) !

2018-11-07 13:56 UTC, jreback requested changes

2018-11-07 13:56 UTC, jreback commented on doc/source/dsintro.rst
> +:class:`api.extensions.IntegerArray`  :ref:`integer_na`
I think we should be consistent here, moving IntegerArray & PeriodArray into pd namespace

2018-11-07 13:56 UTC, jreback commented on doc/source/integer_na.rst
> +
not really sure we need a whole section for this. Feels a bit odd actually.

2018-11-07 14:05 UTC, jreback commented on doc/source/integer_na.rst
> +
yeah sure

2018-11-09 15:42 UTC, TomAugspurger commented
This is being superseded by #23581.

2018-11-09 15:42 UTC, closed without merging