Fix Order of parameters in docstrings
pandas-dev/pandas pull request #23611
Opened 2018-11-10 04:46 UTC by thoo

- [ ] closes #23596 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Fix the following:

```
pandas.io.json.json_normalize: Wrong parameters order. Actual: ('data', 'record_path', 'meta', 'meta_prefix', 'record_prefix', 'errors', 'sep'). Documented: ('data', 'record_path', 'meta', 'record_prefix', 'meta_prefix', 'errors', 'sep')
pandas.crosstab: Wrong parameters order. Actual: ('index', 'columns', 'values', 'rownames', 'colnames', 'aggfunc', 'margins', 'margins_name', 'dropna', 'normalize'). Documented: ('index', 'columns', 'values', 'aggfunc', 'rownames', 'colnames', 'margins', 'margins_name', 'dropna', 'normalize')
pandas.Series.rolling: Wrong parameters order. Actual: ('window', 'min_periods', 'center', 'win_type', 'on', 'axis', 'closed'). Documented: ('window', 'min_periods', 'center', 'win_type', 'on', 'closed', 'axis')
pandas.DataFrame.rolling: Wrong parameters order. Actual: ('window', 'min_periods', 'center', 'win_type', 'on', 'axis', 'closed'). Documented: ('window', 'min_periods', 'center', 'win_type', 'on', 'closed', 'axis')
pandas.DataFrame.to_html: Wrong parameters order. Actual: ('buf', 'columns', 'col_space', 'header', 'index', 'na_rep', 'formatters', 'float_format', 'sparsify', 'index_names', 'justify', 'bold_rows', 'classes', 'escape', 'max_rows', 'max_cols', 'show_dimensions', 'notebook', 'decimal', 'border', 'table_id'). Documented: ('buf', 'columns', 'col_space', 'header', 'index', 'na_rep', 'formatters', 'float_format', 'sparsify', 'index_names', 'justify', 'max_rows', 'max_cols', 'show_dimensions', 'bold_rows', 'classes', 'escape', 'notebook', 'decimal', 'border', 'table_id')
pandas.DataFrame.to_string: Wrong parameters order. Actual: ('buf', 'columns', 'col_space', 'header', 'index', 'na_rep', 'formatters', 'float_format', 'sparsify', 'index_names', 'justify', 'line_width', 'max_rows', 'max_cols', 'show_dimensions'). Documented: ('buf', 'columns', 'col_space', 'header', 'index', 'na_rep', 'formatters', 'float_format', 'sparsify', 'index_names', 'justify', 'max_rows', 'max_cols', 'show_dimensions', 'line_width')
pandas.tseries.offsets.CustomBusinessDay: Wrong parameters order. Actual: ('n', 'normalize', 'weekmask', 'holidays', 'calendar', 'offset'). Documented: ('n', 'offset', 'normalize', 'weekmask', 'holidays', 'calendar')
pandas.tseries.offsets.CustomBusinessMonthEnd: Wrong parameters order. Actual: ('n', 'normalize', 'weekmask', 'holidays', 'calendar', 'offset'). Documented: ('n', 'offset', 'normalize', 'weekmask', 'holidays', 'calendar')
pandas.tseries.offsets.CustomBusinessMonthBegin: Wrong parameters order. Actual: ('n', 'normalize', 'weekmask', 'holidays', 'calendar', 'offset'). Documented: ('n', 'offset', 'normalize', 'weekmask', 'holidays', 'calendar')
pandas.tseries.offsets.CBMonthEnd: Wrong parameters order. Actual: ('n', 'normalize', 'weekmask', 'holidays', 'calendar', 'offset'). Documented: ('n', 'offset', 'normalize', 'weekmask', 'holidays', 'calendar')
pandas.tseries.offsets.CBMonthBegin: Wrong parameters order. Actual: ('n', 'normalize', 'weekmask', 'holidays', 'calendar', 'offset'). Documented: ('n', 'offset', 'normalize', 'weekmask', 'holidays', 'calendar')
pandas.tseries.offsets.CDay: Wrong parameters order. Actual: ('n', 'normalize', 'weekmask', 'holidays', 'calendar', 'offset'). Documented: ('n', 'offset', 'normalize', 'weekmask', 'holidays', 'calendar')
pandas.testing.assert_series_equal: Wrong parameters order. Actual: ('left', 'right', 'check_dtype', 'check_index_type', 'check_series_type', 'check_less_precise', 'check_names', 'check_exact', 'check_datetimelike_compat', 'check_categorical', 'obj'). Documented: ('left', 'right', 'check_dtype', 'check_index_type', 'check_series_type', 'check_less_precise', 'check_exact', 'check_names', 'check_datetimelike_compat', 'check_categorical', 'obj')```

2018-11-10 04:46 UTC, pep8speaks commented
Hello @thoo! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/frame.py`](https://github.com/thoo/pandas/blob/681d9191d09843ffa248fe27dfb677e9683e3f82/pandas/core/frame.py) !

 - There are no PEP8 issues in the file [`pandas/core/generic.py`](https://github.com/thoo/pandas/blob/681d9191d09843ffa248fe27dfb677e9683e3f82/pandas/core/generic.py) !

 - There are no PEP8 issues in the file [`pandas/core/reshape/pivot.py`](https://github.com/thoo/pandas/blob/681d9191d09843ffa248fe27dfb677e9683e3f82/pandas/core/reshape/pivot.py) !

 - There are no PEP8 issues in the file [`pandas/io/json/normalize.py`](https://github.com/thoo/pandas/blob/681d9191d09843ffa248fe27dfb677e9683e3f82/pandas/io/json/normalize.py) !

 - There are no PEP8 issues in the file [`pandas/io/parsers.py`](https://github.com/thoo/pandas/blob/681d9191d09843ffa248fe27dfb677e9683e3f82/pandas/io/parsers.py) !

 - There are no PEP8 issues in the file [`pandas/tseries/offsets.py`](https://github.com/thoo/pandas/blob/681d9191d09843ffa248fe27dfb677e9683e3f82/pandas/tseries/offsets.py) !

 - There are no PEP8 issues in the file [`pandas/util/testing.py`](https://github.com/thoo/pandas/blob/681d9191d09843ffa248fe27dfb677e9683e3f82/pandas/util/testing.py) !

2018-11-10 04:53 UTC, jreback requested changes
generally you cannot change the order of the kwargs themselves 
just fix the doc strings. if it makes more sense and it has a lot of args then we need a note in the whatsnew

2018-11-10 10:31 UTC, datapythonista commented
@thoo I think in this case it makes more sense to change the order of the parameters, as you did initially. But let's do that in a separate PR, just leave the other changes here.

2018-11-10 10:43 UTC, datapythonista commented
I created #23612 to address the changes in `to_string` and `to_html`.

2018-11-10 16:38 UTC, jschendel commented on pandas/core/window.py
> +    axis : int or string, default 0
when specifying parameter types: string --> str  (a couple other instances of this elsewhere too)

2018-11-10 16:39 UTC, jschendel commented on pandas/tseries/offsets.py
> +    calendar : pd.HolidayCalendar or np.
looks like `np.busdaycalendar` accidentally got truncated?

2018-11-10 16:45 UTC, thoo commented on pandas/tseries/offsets.py
> +    calendar : pd.HolidayCalendar or np.
Sorry !

2018-11-10 21:50 UTC, datapythonista approved these changes
lgtm, thanks @thoo for the work on this

2018-11-11 14:50 UTC, jreback approved these changes

2018-11-11 14:50 UTC, merged

2018-11-11 14:51 UTC, jreback commented
thanks @thoo nice work!

@datapythonista is this check now automatic in code_checks? (if not, pls create an issue for this, if you don't already).

2018-11-11 17:49 UTC, datapythonista commented
@jreback I'm adding the docstring checks that are ready to #23614 which still requires some work.

I'll add the validation of the order the parameters, but there too it'll still fail, until #23614 is merged.