Add Documentation for accessing files from S3.
pandas-dev/pandas pull request #23639
Opened 2018-11-12 16:43 UTC by myles

Add some documentation about accessing files from a remote S3 bucket in pandas.

- [x] closes #12206
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-11-12 22:18 UTC, alimcmaster1 requested changes

2018-11-12 22:18 UTC, alimcmaster1 commented on doc/source/cookbook.rst
> +Pandas support loading files from a S3 bucket for remote file interactivity.
NIT: But I think this should read 'Pandas supports loading files'

2018-11-12 22:51 UTC, datapythonista commented
We already have this: https://pandas.pydata.org/pandas-docs/stable/io.html#reading-remote-files

I'd expand that section if there is anything missing, I wouldn't expect many people to look in the cookbook for S3 options having a page specific for IO operations.

Does it make sense?

2018-11-13 14:59 UTC, myles commented
@datapythonista I've expanded the the section in io and remove it from cookbook.

2018-11-13 22:03 UTC, datapythonista approved these changes
Thanks for updating @myles. That looks good to me, but I don't know much about S3, so will let other people review.

2018-11-14 13:58 UTC, merged

2018-11-14 13:58 UTC, jreback commented
thanks!