API/DEPR: replace "raise_conflict" with "errors" for df.update
pandas-dev/pandas pull request #23657
Opened 2018-11-12 23:24 UTC by h-vetinari

- [x] closes #23585 
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

This is split off from #23192, as requested per review (because the PR was getting larger and larger).

2018-11-13 05:28 UTC, gfyoung approved these changes
cc @jreback 
cc @datapythonista (b/c of the doc changes)

2018-11-14 13:36 UTC, jreback requested changes

2018-11-14 13:36 UTC, jreback commented on pandas/core/frame.py
> +            If 'raise', will raise a ValueError if the DataFrame and `other`
versionchanged tag

2018-11-14 13:36 UTC, jreback commented on pandas/core/frame.py
>          ------
can you add an if for valid errors values (e.g. raise/error), and test for passing bad values in the tests themselves

2018-11-14 13:36 UTC, jreback commented on pandas/core/panel.py
> +        May also use object coercible to Panel. Will align on items.
this is fine

2018-11-14 13:36 UTC, jreback commented on pandas/tests/frame/test_combine_concat.py
> +            df.update(other, errors='raise')
can you move this to another test, e.g. test_update_deprecation

2018-11-15 13:30 UTC, jreback approved these changes

2018-11-15 13:30 UTC, merged

2018-11-15 13:30 UTC, jreback commented
thanks