BUG: Preserve categorical dtypes when melting (#15853)
pandas-dev/pandas pull request #23671
Opened 2018-11-13 17:37 UTC by dsm054

This addresses loss of Categorical status for columns used as id_vars by following Jeff's suggestion to introduce tiling, so Index, Series, and Categorical all grew a `.tile` method.

- [X] closes #15853
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

2018-11-13 17:37 UTC, pep8speaks commented
Hello @dsm054! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/compat/numpy/function.py`](https://github.com/dsm054/pandas/blob/2f2eba0b5faa473aa781b55fed6b2a19c8a5e045/pandas/compat/numpy/function.py) !

 - There are no PEP8 issues in the file [`pandas/core/arrays/categorical.py`](https://github.com/dsm054/pandas/blob/2f2eba0b5faa473aa781b55fed6b2a19c8a5e045/pandas/core/arrays/categorical.py) !

 - There are no PEP8 issues in the file [`pandas/core/indexes/base.py`](https://github.com/dsm054/pandas/blob/2f2eba0b5faa473aa781b55fed6b2a19c8a5e045/pandas/core/indexes/base.py) !

 - There are no PEP8 issues in the file [`pandas/core/indexes/datetimelike.py`](https://github.com/dsm054/pandas/blob/2f2eba0b5faa473aa781b55fed6b2a19c8a5e045/pandas/core/indexes/datetimelike.py) !

 - There are no PEP8 issues in the file [`pandas/core/series.py`](https://github.com/dsm054/pandas/blob/2f2eba0b5faa473aa781b55fed6b2a19c8a5e045/pandas/core/series.py) !

 - There are no PEP8 issues in the file [`pandas/tests/arrays/categorical/test_analytics.py`](https://github.com/dsm054/pandas/blob/2f2eba0b5faa473aa781b55fed6b2a19c8a5e045/pandas/tests/arrays/categorical/test_analytics.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexes/test_base.py`](https://github.com/dsm054/pandas/blob/2f2eba0b5faa473aa781b55fed6b2a19c8a5e045/pandas/tests/indexes/test_base.py) !

 - There are no PEP8 issues in the file [`pandas/tests/reshape/test_melt.py`](https://github.com/dsm054/pandas/blob/2f2eba0b5faa473aa781b55fed6b2a19c8a5e045/pandas/tests/reshape/test_melt.py) !

 - There are no PEP8 issues in the file [`pandas/tests/series/test_analytics.py`](https://github.com/dsm054/pandas/blob/2f2eba0b5faa473aa781b55fed6b2a19c8a5e045/pandas/tests/series/test_analytics.py) !

2018-11-13 19:17 UTC, TomAugspurger commented
I'm always hesitant to add new methods to Series / DataFrame. Do we think `.tile` is broadly useful enough to be included? `Series.tile` seems especially problematic, since you'll by definition end up with duplicate indices.

For fixing the original issue of preserving categorical in melt, I'd rather we define in internal helper function that knows how to tile extension arrays.

For Categorical we can tile the codes, datetimelike the `.asi8`, and for other EAs, we can convert to object, tile that, then use `_construct_from_sequence` to reconstruct the original dtype.

2018-11-13 19:32 UTC, dsm054 commented
I don't understand your objection about the duplicate indices: while they're always awkward, that's exactly how pd.Series.repeat works already, and whose pattern I followed.

The objection to adding new methods is reasonable enough.

2018-11-14 13:08 UTC, jreback requested changes
allowing this method is ok, its basically another version of repeat.

2018-11-14 13:08 UTC, jreback commented on pandas/core/series.py
> +            new_values = Categorical.from_codes(np.tile(self.cat.codes, reps),
do this more like ``repeats``, you just directly access the underlying function; then you don't need to type check

2018-11-14 13:08 UTC, jreback commented on pandas/tests/indexes/test_base.py
> +    def test_tile(self):
ideally you can use the indices fixture here and test all Index

2018-11-14 13:08 UTC, jreback commented on pandas/tests/reshape/test_melt.py
> +            tm.assert_series_equal(result[column], expected)
can you also test result itself

2018-11-14 13:31 UTC, TomAugspurger commented
I'm willing to take on some of that pain, if it means a cleaner API for EA authors.

We could write a repeat for EAs that operates uses either `ExtensionArray.take(np.repeat(np.arange(len(self))`, or a similar thing with factorized values.

I really don't think `.tile` makes sense for EAs, which are currently 1-D by definition.

2018-11-14 13:33 UTC, jreback commented
> We could write a repeat for EAs that operates uses either ExtensionArray.take(np.repeat(np.arange(len(self)), or a similar thing with factorized values.

yes these could be implemented in terms of repeat, i agree.

2018-11-19 02:09 UTC, jreback commented
can you rebase

2018-12-03 02:17 UTC, jreback commented
@dsm054 can you merge master and update

2018-12-23 23:11 UTC, jreback commented
can you merge master and update

2019-01-05 15:40 UTC, jreback commented
closing as stale. pls ping if you want to continue working.

2019-01-05 15:40 UTC, closed without merging