Add _expand_user to _stringify_path as we need to allow tilde - ~, to expand to full path
pandas-dev/pandas pull request #23769
Opened 2018-11-18 18:03 UTC by srinivasreddy

- [ ] closes #23473 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-11-18 18:03 UTC, pep8speaks commented
Hello @srinivasreddy! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/io/common.py`](https://github.com/srinivasreddy/pandas/blob/159f1958aa71203ba1f31b982b140322c78a6941/pandas/io/common.py) !

2018-11-18 18:11 UTC, jreback commented
we have some tests in io/test_common.py ; do these need to be expanded?

2018-11-18 18:42 UTC, jreback commented
ok, can you add a whatsnew note

2018-11-19 03:18 UTC, WillAyd requested changes
I actually would prefer adding a test case here which could be parametrized like say `test_read_non_existant` within the same module.

2018-11-22 13:59 UTC, WillAyd requested changes

2018-11-22 13:59 UTC, WillAyd commented on pandas/tests/io/test_common.py
> +        with pytest.raises(error_class):
I don't think this test actually does anything within the context of this change. Is there a way to make a stronger assertion about this actually working?

Another option may be to patch a call to `_expand_user` and assert it gets called via these functions

2018-12-09 19:13 UTC, jreback commented
can you merge master and address comments

2018-12-23 23:36 UTC, jreback commented
can you merge master

2019-01-05 15:40 UTC, jreback commented
@pandas-dev/pandas-core if someone can merge master and update the test

2019-01-05 16:08 UTC, WillAyd commented
Sure I'll take a look

2019-01-05 18:37 UTC, WillAyd commented on pandas/tests/io/test_common.py
> +        monkeypatch.setattr(icom, '_expand_user',
Could alternately use `mock.assert_called` for this test but didn't see that library used anywhere else and I know we've been removing it from other instances, so this is an alternate way of using monkey patch to get to the same place

2019-01-05 19:27 UTC, merged