API/DEPR: replace kwarg "pat" with "sep" in str.[r]partition
pandas-dev/pandas pull request #23767
Opened 2018-11-18 15:31 UTC by h-vetinari

- [x] closes #22676
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-11-18 15:31 UTC, pep8speaks commented
Hello @h-vetinari! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/strings.py`](https://github.com/h-vetinari/pandas/blob/8cbf9eac7e3d20357e720ea9817a42e2fa72db3b/pandas/core/strings.py) !

 - There are no PEP8 issues in the file [`pandas/tests/test_strings.py`](https://github.com/h-vetinari/pandas/blob/8cbf9eac7e3d20357e720ea9817a42e2fa72db3b/pandas/tests/test_strings.py) !

2018-11-18 15:52 UTC, WillAyd requested changes
Minor comment otherwise lgtm

2018-11-18 15:52 UTC, WillAyd commented on pandas/core/strings.py
> +    sep : str, default whitespace
Let's still keep `pat` documented but with a `deprecated` directive

2018-11-18 16:18 UTC, WillAyd commented on pandas/core/strings.py
> +           Use ``sep`` instead
Thanks! Do we need a newline after this or does it render OK?

2018-11-18 16:35 UTC, WillAyd approved these changes

2018-11-19 07:29 UTC, h-vetinari commented
Failure is a flaky hypothesis test.

2018-11-19 14:14 UTC, jreback commented
looks fine, ex @WillAyd comments. @WillAyd pls add this to the list in #6581 as well. merge when ready.

2018-11-19 17:23 UTC, h-vetinari commented
@jreback @WillAyd 
The feedback of @WillAyd is already incorporated.

2018-11-20 01:07 UTC, merged

2018-11-20 01:07 UTC, jreback commented
thanks @h-vetinari