DOC: Fix format of basics.rst, following PEP-8 standard
pandas-dev/pandas pull request #23802
Opened 2018-11-20 01:02 UTC by ywpark1

- [ ] closes #23792 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

I updated the format of `doc/source/basics.rst` file. 
I do not see any errors when I run `flake8-rst doc/source/basics.rst`.

Please let me know if there are some changes.

2018-11-20 12:34 UTC, datapythonista requested changes
Will review in detail after the spaces are removed, as they are wrong and they are making the review much more difficult.

2018-11-20 12:34 UTC, datapythonista commented on doc/source/basics.rst
> +.. ipython:: python
I don't understand why we're adding a white space after all directives. Is there a reason, or is it your editor that did those automatically?

Afaik this space is wrong, and they should be removed again.

2018-11-20 13:16 UTC, ywpark1 commented
I removed the spaces, and it shows these errors :
```
doc/source/basics.rst:310:10: E225 missing whitespace around operator
doc/source/basics.rst:6:4: E902 TokenError: EOF in multi-line statement
doc/source/basics.rst:754:4: E402 module level import not at top of file
doc/source/basics.rst:984:4: E402 module level import not at top of file
doc/source/basics.rst:1120:4: E402 module level import not at top of file
doc/source/basics.rst:1992:5: E999 SyntaxError: invalid syntax
```

Did I fix something wrong?

2018-11-20 14:27 UTC, datapythonista reviewed
Looks great. I commented on couple of extra things that I'd fix, but it's a nice improvement.

2018-11-20 14:29 UTC, datapythonista commented
I can't see why you get these errors, but don't worry about them, we can merge all the fixes you made, and check later whether they are caused by a bug in flake-rst or what's wrong.

2018-11-20 15:37 UTC, ywpark1 commented
I fixed the missing spaces, adjusted indentation, and removed 'In [0]' from ipython.

I also fixed other errors occurred after changes. When I run `flake8-rst doc/source/basics.rst`, I see only these errors :
```
doc/source/basics.rst:753:4: E402 module level import not at top of file
doc/source/basics.rst:983:4: E402 module level import not at top of file
doc/source/basics.rst:1119:4: E402 module level import not at top of file
doc/source/basics.rst:2128:6: E402 module level import not at top of file
doc/source/basics.rst:2158:6: E402 module level import not at top of file
doc/source/basics.rst:2178:5: E402 module level import not at top of file
doc/source/basics.rst:2193:5: E402 module level import not at top of file
doc/source/basics.rst:2219:5: E402 module level import not at top of file
```

2018-11-20 15:40 UTC, datapythonista reviewed
Nice changes. Added few suggestions on things that I think can be presented more clearly, but looks good.

2018-11-20 15:40 UTC, datapythonista commented on doc/source/basics.rst
> +       print('%s\n%s' % (row_index, row))
Do you mind changing this by `print(row_index, row, sep='\n')`

2018-11-20 15:40 UTC, datapythonista commented on doc/source/basics.rst
> +                           F=False, G=pd.Series([1] * 3, dtype='int8')))
could you move `G` to thenext line for consistency and clairity?

2018-11-20 15:40 UTC, datapythonista commented on doc/source/basics.rst
> +      >>> if df:                         # noqa: E999
If the `...` is giving problems with the validation I'd replace it by a `pass`, and we can also remove the `noqa` comment then.

2018-11-20 15:40 UTC, datapythonista commented on doc/source/basics.rst
> +       {'col1': np.random.randn(3), 'col2': np.random.randn(3)},
just a personal opinion here, but I think this style is easier to read:
```
df = pd.DataFrame({'col1': np.random.randn(3),
                   'col2': np.random.randn(3)},
```

2018-11-20 15:40 UTC, datapythonista commented on doc/source/basics.rst
> +                               np.random.randn(8), dtype='uint8'))))
I think this is clearer here, and should fit in 79 characters:
```
C=pd.Series(np.array(np.random.randn(8),
                     dtype='uint8'))))
```

2018-11-20 15:44 UTC, datapythonista commented
That's cool, thanks @ywpark1. I think the `E402 module level import not at top of file` shouldn't be reported by `flake8-rst`.

I'd add it to the list of flake8-rst errors to ignore in `setup.cfg`.

@FHaase what do you think?

2018-11-20 15:54 UTC, datapythonista approved these changes
Looks great, thanks @ywpark1

2018-11-21 06:36 UTC, ywpark1 commented
Hi @datapythonista ,
If you do not mind, can I try to re-open this Pull Request with the same changes? I touched something wrong in the local git and now it shows bunch of weird commits showing on this Pull Request.

2018-11-21 09:41 UTC, jorisvandenbossche requested changes

2018-11-21 09:41 UTC, jorisvandenbossche commented on doc/source/basics.rst
> +   result.loc[:, :, 'ItemA']
I don't directly see how the above changes cause this, but, this example is now failing in the doc build with:

```
>>>-------------------------------------------------------------------------
Exception in /home/travis/build/pandas-dev/pandas/doc/source/basics.rst at block ending on line 1183
Specify :okexcept: as an option in the ipython:: block to suppress this message

KeyErrorTraceback (most recent call last)

~/build/pandas-dev/pandas/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3146             try:
-> 3147                 return self._engine.get_loc(key)
   3148             except KeyError:
~/build/pandas-dev/pandas/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()
~/build/pandas-dev/pandas/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()
~/build/pandas-dev/pandas/pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()
~/build/pandas-dev/pandas/pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()
KeyError: 'ItemA'

During handling of the above exception, another exception occurred:

KeyErrorTraceback (most recent call last)
<ipython-input-209-ce1c0f9e4a44> in <module>
----> 1 result.loc[:, :, 'ItemA']
~/build/pandas-dev/pandas/pandas/core/indexing.py in __getitem__(self, key)
   1495             except (KeyError, IndexError, AttributeError):
   1496                 pass
-> 1497             return self._getitem_tuple(key)
   1498         else:
   1499             # we by definition only have the 0th axis
~/build/pandas-dev/pandas/pandas/core/indexing.py in _getitem_tuple(self, tup)
    868     def _getitem_tuple(self, tup):
    869         try:
--> 870             return self._getitem_lowerdim(tup)
    871         except IndexingError:
    872             pass
~/build/pandas-dev/pandas/pandas/core/indexing.py in _getitem_lowerdim(self, tup)
    988         for i, key in enumerate(tup):
    989             if is_label_like(key) or isinstance(key, tuple):
--> 990                 section = self._getitem_axis(key, axis=i)
    991 
    992                 # we have yielded a scalar ?
~/build/pandas-dev/pandas/pandas/core/indexing.py in _getitem_axis(self, key, axis)
   1914         # fall thru to straight lookup
   1915         self._validate_key(key, axis)
-> 1916         return self._get_label(key, axis=axis)
   1917 
   1918 
~/build/pandas-dev/pandas/pandas/core/indexing.py in _get_label(self, label, axis)
    146             raise IndexingError('no slices here, handle elsewhere')
    147 
--> 148         return self.obj._xs(label, axis=axis)
    149 
    150     def _get_loc(self, key, axis=None):
~/build/pandas-dev/pandas/pandas/core/panel.py in xs(self, key, axis)
    864         self._consolidate_inplace()
    865         axis_number = self._get_axis_number(axis)
--> 866         new_data = self._data.xs(key, axis=axis_number, copy=False)
    867         result = self._construct_return_type(new_data)
    868         copy = new_data.is_mixed_type
~/build/pandas-dev/pandas/pandas/core/internals/managers.py in xs(self, key, axis, copy, takeable)
    835             loc = key
    836         else:
--> 837             loc = self.axes[axis].get_loc(key)
    838 
    839         slicer = [slice(None, None) for _ in range(self.ndim)]
~/build/pandas-dev/pandas/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3147                 return self._engine.get_loc(key)
   3148             except KeyError:
-> 3149                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   3150         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   3151         if indexer.ndim > 1 or indexer.size > 1:
~/build/pandas-dev/pandas/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()
~/build/pandas-dev/pandas/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()
~/build/pandas-dev/pandas/pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()
~/build/pandas-dev/pandas/pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()
KeyError: 'ItemA'
```

2018-11-21 09:42 UTC, jorisvandenbossche commented
> If you do not mind, can I try to re-open this Pull Request with the same changes? I touched something wrong in the local git and now it shows bunch of weird commits showing on this Pull Request.

@ywpark1 The diff looks fine now? Or is there still something wrong with it? (and don't worry if there are more commits, they will get squashed when merging, so it is the diff that is important)

2018-11-21 12:33 UTC, datapythonista commented
@ywpark1 not sure what happened exactly, but in general you don't want to modify anything in a PR once it's been approved (unless you get further feedback).

There is something that will cause some trouble in this case. When working in an issue, you should create a new local git branch. Because you worked directly in master, now you can't work in any other issue until this PR is merged. If you work in something else, you'll have to do it in master and you'll mix things, or you'll have to create a new branch from a modified master, which will contain changes unrelated to the new feature.

We could fix that with a reset, and opening a new PR, but I think it's better to try to merge this, and then you can start again.

@jorisvandenbossche as `Panel` is deprecated and soon removed, wouldn't make sense to remove that whole block about it from the pandas basics documentation? Besides giving the error, I don't think anyone reading that page should find anything about `Panel`, they'll learn things that will be removed very soon.

2018-11-21 12:46 UTC, jreback commented
> @jorisvandenbossche as Panel is deprecated and soon removed, wouldn't make sense to remove that whole block about it from the pandas basics documentation? Besides giving the error, I don't think anyone reading that page should find anything about Panel, they'll learn things that will be removed very soon.

yes could remove that whole block is ok.

2018-11-21 12:51 UTC, datapythonista commented
@ywpark1 can you remove the whole `Applying with a Panel` section please.

You can check it here if that makes things easier: http://pandas.pydata.org/pandas-docs/stable/basics.html#applying-with-a-panel

2018-11-21 13:20 UTC, ywpark1 commented
Thanks for your advice @datapythonista . I was working with local master branch by mistake.
I will try to work on other issues once this is merged.

2018-11-21 14:54 UTC, jorisvandenbossche approved these changes

2018-11-21 14:55 UTC, jorisvandenbossche commented
Yes, good idea to just remove that section.

There is still another problem caused by removing this section (an import is missing in another file), but I will merge this and fix that in a separate PR.

2018-11-21 14:55 UTC, merged

2018-11-21 14:55 UTC, jorisvandenbossche commented
@ywpark1 Thanks a lot!

2018-11-21 15:00 UTC, jorisvandenbossche commented
> There is still another problem caused by removing this section (an import is missing in another file), but I will merge this and fix that in a separate PR.

https://github.com/pandas-dev/pandas/pull/23841