CLN: io/formats/html.py: refactor
pandas-dev/pandas pull request #23818
Opened 2018-11-20 14:55 UTC by simonjayhawkins

- [ n/a] follow-on from #22726
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [n/a ] whatsnew entry

remove `max_rows` and `max_cols` from `HTMLFormatter` as truncation is now handled by `DataFrameFormatter`

note: this PR should be orthogonal to #22655

2018-11-20 14:55 UTC, pep8speaks commented
Hello @simonjayhawkins! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/io/formats/format.py`](https://github.com/simonjayhawkins/pandas/blob/5644532ad9a7419af0037f435356c1e545701ee6/pandas/io/formats/format.py) !

 - There are no PEP8 issues in the file [`pandas/io/formats/html.py`](https://github.com/simonjayhawkins/pandas/blob/5644532ad9a7419af0037f435356c1e545701ee6/pandas/io/formats/html.py) !

2018-11-21 08:55 UTC, gfyoung requested changes
Are these classes in anyway considered user-facing?  If not, LGTM.

cc @jreback @WillAyd

2018-11-21 13:04 UTC, jreback requested changes

2018-11-21 13:04 UTC, jreback commented on pandas/io/formats/html.py
> +        self.is_truncated = self.fmt.is_truncated
this could be a property?

2018-11-21 13:04 UTC, jreback commented on pandas/io/formats/html.py
> +        ncols = len(self.fmt.tr_frame.columns)
these could also be properties fro clarify

2018-11-21 13:04 UTC, jreback commented
these changes are ok, though @simonjayhawkins pls add a note anyhow in api breaking changes (they are private but just a notice)

2018-11-26 18:16 UTC, simonjayhawkins commented
@gfyoung @jreback note about api breaking change has been added to whatsnew

2018-11-26 20:49 UTC, gfyoung approved these changes
cc @jreback

2018-11-27 02:37 UTC, jreback approved these changes

2018-11-27 02:37 UTC, merged

2018-11-27 02:37 UTC, jreback commented
thanks @simonjayhawkins