ISSUE NO. #19602
pandas-dev/pandas pull request #23856
Opened 2018-11-22 09:12 UTC by vaibhawc

-  closes #19602

2018-11-22 09:12 UTC, pep8speaks commented
Hello @vaibhawc! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/frame.py`](https://github.com/vaibhawc/pandas/blob/98629b2f342713b205fedd651299f5338b424f07/pandas/core/frame.py) !

2018-11-22 10:32 UTC, datapythonista commented
Thanks for the contribution @vaibhawc can you add unit tests and a whatsnew note on what is being fixed?

2018-12-09 20:14 UTC, jreback requested changes
needs tests

2018-12-09 20:19 UTC, datapythonista commented
Closing as stale, @vaibhawc if you want to continue working on it, please address comments and reopen the PR.

2018-12-09 20:19 UTC, closed without merging