CLN: Fixes to conda environment names
pandas-dev/pandas pull request #23860
Opened 2018-11-22 15:41 UTC by charlesdong1991

- [ ] closes #23851 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-11-22 19:11 UTC, datapythonista commented
@charlesdong1991 are you still working on it? The rest of the changes in the scripts and the travis and azure config described in the issue are missing.

2018-11-22 19:13 UTC, charlesdong1991 commented
Hi, so sorry that I am having dinner out, but I will carry on working after
back home.
On Thu, 22 Nov 2018 at 20:12, Marc Garcia <notifications@github.com> wrote:

> @charlesdong1991 <https://github.com/charlesdong1991> are you still
> working on it? The rest of the changes in the scripts and the travis and
> azure config described in the issue are missing.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/23860#issuecomment-441106095>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AI1yODPwZQTsFVvOoFA6pY7DtOzcyRdnks5uxvcGgaJpZM4YvksU>
> .
>

2018-11-22 19:38 UTC, datapythonista commented
Not a problem at all, just said, as it make things more efficient. Enjoy your dinner, and thanks for working on this.

2018-11-23 00:14 UTC, datapythonista requested changes
Looks good, thanks for working on this @charlesdong1991. Couple of comments, and they should fix the CI which is in red. If after changing them, you see the CI still red, you may want to check what else is needed.

2018-11-23 00:14 UTC, datapythonista commented on ci/incremental/setup_conda_environment.cmd
> +
we may need this, but you can replace the `%CONDA_ENV%` by `pandas-dev`

2018-11-23 00:14 UTC, datapythonista commented on ci/incremental/setup_conda_environment.sh
> +conda remove --all -q -y
can you leave the `-n pandas-dev`

2018-11-23 00:14 UTC, datapythonista commented on ci/incremental/setup_conda_environment.sh
> +source activate pandas-dev
this one can be removed, also the `set +/- v` around it

2018-11-23 08:15 UTC, charlesdong1991 commented
@datapythonista sorry, this is very wrong... i think i did something very bad when catching up with the latest change, i think i need to re-create a pr... sorry

2018-11-23 09:22 UTC, closed without merging