TST: split up pandas/tests/indexing/test_multiindex.py
pandas-dev/pandas pull request #23912
Opened 2018-11-25 21:25 UTC by simonjayhawkins

- [n/a ] follow on from  #23797
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ n/a] whatsnew entry

only whole tests moved, tests have not been split up. this and the removal of classes is left for a follow-on PR.

2018-11-27 02:46 UTC, jreback requested changes
looks good, some small splitting. ping on green.

2018-11-27 02:46 UTC, jreback commented on pandas/tests/indexing/multiindex/test_multiindex.py
> +    def test_multiindex_label_slicing_with_negative_step(self):
move to slicing

2018-11-27 02:46 UTC, jreback commented on pandas/tests/indexing/multiindex/test_multiindex.py
> +    def test_multiindex_symmetric_difference(self):
can you move to (new file set_ops)

2018-11-27 02:46 UTC, jreback commented on pandas/tests/indexing/multiindex/test_multiindex.py
> +    def test_get_loc_single_level(self, single_level_multiindex):
there are some loc tests in here

2018-11-27 02:46 UTC, jreback commented on pandas/tests/indexing/multiindex/test_multiindex.py
> +    def test_getitem_setitem_slice_integers(self):
can you move pure getitem tests to a new file, and pure setitem to a newfile as well, if they are both getitem & setitem, put in the setitem one

2018-11-27 02:46 UTC, jreback commented on pandas/tests/indexing/multiindex/test_multiindex.py
> +    def test_int_series_slicing(
to slicing

2018-11-27 02:46 UTC, jreback commented on pandas/tests/indexing/multiindex/test_multiindex.py
> +    def test_mixed_depth_insert(self):
insert, difference to set_ops

2018-11-29 11:48 UTC, simonjayhawkins commented
@jreback green!

2018-11-29 13:50 UTC, jreback approved these changes

2018-11-29 13:51 UTC, merged

2018-11-29 13:51 UTC, jreback commented
thanks!