Disallow intervalindex bins backup
pandas-dev/pandas pull request #23999
Opened 2018-11-29 18:41 UTC by charlesdong1991

- [ ] closes #23980 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-11-29 18:41 UTC, pep8speaks commented
Hello @charlesdong1991! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/reshape/tile.py`](https://github.com/charlesdong1991/pandas/blob/2e27412d2d3731f5fff76bd723d4d22981f39688/pandas/core/reshape/tile.py) !

 - There are no PEP8 issues in the file [`pandas/tests/reshape/test_tile.py`](https://github.com/charlesdong1991/pandas/blob/2e27412d2d3731f5fff76bd723d4d22981f39688/pandas/tests/reshape/test_tile.py) !

2018-11-29 21:28 UTC, jschendel requested changes
Thanks!  Looks good overall. A couple comments:
- Can you add a whatsnew note to 0.24.0 under the Reshaping subsection of the Bug Fixes section?
- Can you add "Must be non-overlapping." to `cut` docstring, at the end of the `IntervalIndex` portion of the `bins` parameter description?

2018-11-29 21:54 UTC, charlesdong1991 commented
Hi, @jschendel , thanks for the review and advices!! As for `Can you add a whatsnew note to 0.24.0 under the Reshaping subsection of the Bug Fixes section?`, I am not sure if I did it correctly (what i did was just tick the `whatsnew entry` above). Please give me more hints if it's not what you meant, sorry, not familiar with this part. And thanks again!

2018-11-29 22:18 UTC, jschendel commented
For the whatsnew entry, you'll need to edit the `/doc/source/whatsnew/v0.24.0.rst` file at around line 1485 to add an entry along the lines of:
```rst
- Bug in :func:`cut` with ``bins`` as an overlapping ``IntervalIndex`` where multiple bins were returned per item instead of raising a ``ValueError`` (:issue:`23980`)
```

2018-11-29 22:23 UTC, charlesdong1991 commented
@jschendel , ahh, I see!! Thank you very much, added!

2018-11-29 22:31 UTC, jschendel approved these changes

2018-11-30 00:08 UTC, jschendel commented on pandas/core/reshape/tile.py
> +        * IntervalIndex : Defines the exact bins to be used. Note that IntervalIndex
looks like linting failed since this line is a little too long

2018-12-01 00:17 UTC, merged

2018-12-01 00:18 UTC, jschendel commented
thanks @charlesdong1991!