Add test for rdivmod on EA array (GH23287)
pandas-dev/pandas pull request #24047
Opened 2018-12-02 13:34 UTC by makbigc

-  closes #23287 
-  test added
-  passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2018-12-02 13:34 UTC, pep8speaks commented
Hello @makbigc! Thanks for submitting the PR.

 - In the file [`pandas/tests/extension/base/ops.py`](https://github.com/makbigc/pandas/blob/a2dbea81276725d8496094204ecb27166ba9eb7d/pandas/tests/extension/base/ops.py), following                are the PEP8 issues :
> [Line 97:9](https://github.com/makbigc/pandas/blob/a2dbea81276725d8496094204ecb27166ba9eb7d/pandas/tests/extension/base/ops.py#L97): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 101:9](https://github.com/makbigc/pandas/blob/a2dbea81276725d8496094204ecb27166ba9eb7d/pandas/tests/extension/base/ops.py#L101): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '


 - There are no PEP8 issues in the file [`pandas/tests/extension/decimal/test_decimal.py`](https://github.com/makbigc/pandas/blob/a2dbea81276725d8496094204ecb27166ba9eb7d/pandas/tests/extension/decimal/test_decimal.py) !

 - There are no PEP8 issues in the file [`pandas/tests/extension/json/test_json.py`](https://github.com/makbigc/pandas/blob/a2dbea81276725d8496094204ecb27166ba9eb7d/pandas/tests/extension/json/test_json.py) !

 - There are no PEP8 issues in the file [`pandas/tests/extension/test_categorical.py`](https://github.com/makbigc/pandas/blob/a2dbea81276725d8496094204ecb27166ba9eb7d/pandas/tests/extension/test_categorical.py) !

 - There are no PEP8 issues in the file [`pandas/tests/extension/test_integer.py`](https://github.com/makbigc/pandas/blob/a2dbea81276725d8496094204ecb27166ba9eb7d/pandas/tests/extension/test_integer.py) !

 - There are no PEP8 issues in the file [`pandas/tests/extension/test_period.py`](https://github.com/makbigc/pandas/blob/a2dbea81276725d8496094204ecb27166ba9eb7d/pandas/tests/extension/test_period.py) !

 - There are no PEP8 issues in the file [`pandas/tests/extension/test_sparse.py`](https://github.com/makbigc/pandas/blob/a2dbea81276725d8496094204ecb27166ba9eb7d/pandas/tests/extension/test_sparse.py) !

2018-12-02 18:00 UTC, jreback requested changes

2018-12-05 14:31 UTC, TomAugspurger commented on pandas/tests/extension/decimal/test_decimal.py
> +@pytest.fixture
I think either of those makes sense.

Would the default be to `raise NotImpelmentedError` like the other `data` fixtures?

2018-12-06 13:55 UTC, makbigc commented on pandas/tests/extension/decimal/test_decimal.py
> +@pytest.fixture
Then I don't fixturize and move each array of ones inside every test functions?

2018-12-11 19:46 UTC, jreback commented on pandas/tests/extension/decimal/test_decimal.py
> +@pytest.fixture
@makbigc no, fixturize, but just rename it, alternatively have a fixture for each EA that returns a scalar, then inside the test functions you can create a list of those.

2018-12-25 18:15 UTC, jreback commented
can you merge master and rebase

2018-12-25 23:59 UTC, jreback requested changes

2018-12-25 23:59 UTC, jreback commented on pandas/tests/extension/decimal/test_decimal.py
> +@pytest.fixture
can you rename

2018-12-25 23:59 UTC, jreback commented on pandas/tests/extension/test_period.py
> +    def test_divmod_series_array(self):
this should work, no?

2019-02-27 23:53 UTC, WillAyd commented
@makbigc can you merge master on this one?

2019-03-03 03:16 UTC, jreback requested changes

2019-03-03 03:16 UTC, jreback commented on pandas/tests/extension/test_categorical.py
> +        pass
can you add a comment (skipping because its NotImplemented)

2019-03-03 03:16 UTC, jreback commented
@jbrockmendel can you have a look

2019-03-03 17:04 UTC, jbrockmendel commented
Looks fine to me.  I'm not particularly well-versed in this directory of the tests.

2019-03-05 03:56 UTC, TomAugspurger reviewed
I think you should add a fixture to `pandas/tests/extensions/conftest.py`. The docstring should describe the expected semantics of the `data_for_twos` fixture.

2019-03-10 16:10 UTC, jreback commented
this looks fine, can you merge master and get tests to pass.

2019-03-20 00:05 UTC, jreback approved these changes

2019-03-20 00:05 UTC, merged

2019-03-20 00:05 UTC, jreback commented
thanks @makbigc