Deprecate series.nonzero (GH18262)
pandas-dev/pandas pull request #24048
Opened 2018-12-02 15:01 UTC by makbigc

xref #18262

-  passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
-  whatsnew entry

2018-12-02 15:01 UTC, pep8speaks commented
Hello @makbigc! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/series.py`](https://github.com/makbigc/pandas/blob/ec4a003be18780d7d7f8be6a9e0c7809bc6d9716/pandas/core/series.py) !

2018-12-02 17:56 UTC, jreback commented
this would need a test. Also you would need to remove any uses of this from the test code itself (otherwise it would show a warning)

2018-12-02 17:56 UTC, jreback requested changes

2018-12-02 17:56 UTC, jreback commented on pandas/core/series.py
> +        msg = ("Series.nonzero() is deprecated "
can you show what it is replaced by here

2018-12-14 15:55 UTC, jreback commented
can you merge master and update

2018-12-30 19:59 UTC, jreback requested changes
are there any warnings issued by the test suite? need to change any internal uses of this

2018-12-30 19:59 UTC, jreback commented on pandas/core/frame.py
> +            if axis == 0:
you can do
``result = self.loc(axis=axis)[mask]``

2018-12-30 19:59 UTC, jreback commented on pandas/core/frame.py
> +            inds, = (-duplicated).values.nonzero()
change this like
``(~duplicated)._values.nonzero()``

2018-12-30 20:01 UTC, jreback commented
also remove this from api.rst if it exists

2019-01-01 16:26 UTC, jreback requested changes
there are NO warnings from the test suite?

2019-01-05 10:38 UTC, makbigc commented on pandas/io/stata.py
> +                missing_loc = np.argwhere(missing.values)
when nonzero is implemented in Series, np.argwhere will call it

2019-01-05 10:40 UTC, makbigc commented
No warning is raised due to deprecation of Series.nonzero, running the test suite in my own machine.

2019-01-05 15:14 UTC, jreback requested changes
looks fine, but need to remove doc/source/api.rst which you seem to have added back

2019-01-05 15:14 UTC, jreback commented on pandas/core/series.py
> +        .. deprecated:: 0.24.0
can you add what this is replaced here as well

2019-01-05 21:23 UTC, jreback approved these changes

2019-01-05 22:47 UTC, merged

2019-01-05 22:47 UTC, jreback commented
thank @makbigc