REF/TST: Add more pytest idiom to mi indexing tests
pandas-dev/pandas pull request #24040
Opened 2018-12-01 23:54 UTC by simonjayhawkins

- [n/a ] follow on from #23912
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [n/a ] whatsnew entry

for this pass:

- the Test classes have been removed.

- `catch_warnings`  used for the `.ix` deprecation replaced with `@pytest.mark.filterwarnings("ignore:\\n.ix:DeprecationWarning")` at test level.

2018-12-01 23:54 UTC, pep8speaks commented
Hello @simonjayhawkins! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/tests/indexing/multiindex/test_getitem.py`](https://github.com/simonjayhawkins/pandas/blob/c97de72fecb37c1e0648377d054a346a912dd00e/pandas/tests/indexing/multiindex/test_getitem.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexing/multiindex/test_iloc.py`](https://github.com/simonjayhawkins/pandas/blob/c97de72fecb37c1e0648377d054a346a912dd00e/pandas/tests/indexing/multiindex/test_iloc.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexing/multiindex/test_ix.py`](https://github.com/simonjayhawkins/pandas/blob/c97de72fecb37c1e0648377d054a346a912dd00e/pandas/tests/indexing/multiindex/test_ix.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexing/multiindex/test_loc.py`](https://github.com/simonjayhawkins/pandas/blob/c97de72fecb37c1e0648377d054a346a912dd00e/pandas/tests/indexing/multiindex/test_loc.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexing/multiindex/test_multiindex.py`](https://github.com/simonjayhawkins/pandas/blob/c97de72fecb37c1e0648377d054a346a912dd00e/pandas/tests/indexing/multiindex/test_multiindex.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexing/multiindex/test_panel.py`](https://github.com/simonjayhawkins/pandas/blob/c97de72fecb37c1e0648377d054a346a912dd00e/pandas/tests/indexing/multiindex/test_panel.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexing/multiindex/test_partial.py`](https://github.com/simonjayhawkins/pandas/blob/c97de72fecb37c1e0648377d054a346a912dd00e/pandas/tests/indexing/multiindex/test_partial.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexing/multiindex/test_set_ops.py`](https://github.com/simonjayhawkins/pandas/blob/c97de72fecb37c1e0648377d054a346a912dd00e/pandas/tests/indexing/multiindex/test_set_ops.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexing/multiindex/test_setitem.py`](https://github.com/simonjayhawkins/pandas/blob/c97de72fecb37c1e0648377d054a346a912dd00e/pandas/tests/indexing/multiindex/test_setitem.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexing/multiindex/test_slice.py`](https://github.com/simonjayhawkins/pandas/blob/c97de72fecb37c1e0648377d054a346a912dd00e/pandas/tests/indexing/multiindex/test_slice.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexing/multiindex/test_sorted.py`](https://github.com/simonjayhawkins/pandas/blob/c97de72fecb37c1e0648377d054a346a912dd00e/pandas/tests/indexing/multiindex/test_sorted.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexing/multiindex/test_xs.py`](https://github.com/simonjayhawkins/pandas/blob/c97de72fecb37c1e0648377d054a346a912dd00e/pandas/tests/indexing/multiindex/test_xs.py) !

2018-12-02 10:05 UTC, gfyoung requested changes
This is awesome work!  However, I have to ask:

Would it be possible to split this PR into multiple PR's?  This would make things easier to review.

Also, if you spot opportunities to improve the tests when refactoring, those would be great as well!  Improvements include:

* Breaking up big tests into smaller ones
* Checking error messages in `pytest.raises` if meaningful

2018-12-02 11:40 UTC, simonjayhawkins commented
@gfyoung  thanks for the review. breaking down the PR is not a problem. would your preference be to split by activity, by file or perhaps limit the number of files in the PR?

2018-12-02 17:53 UTC, jreback commented on pandas/tests/indexing/multiindex/test_iloc.py
> +def test_iloc_getitem_multiindex2():
we should fix this :>

2018-12-02 17:55 UTC, jreback commented
@simonjayhawkins here i think you can split by files. e.g. try to limit the amount that requires review in any 1 PR. Also if you have a PR which simply moves things, those should be independent to making actual changes.

2018-12-02 19:05 UTC, gfyoung commented
> here i think you can split by files.

I second @jreback on this.

2018-12-02 20:07 UTC, closed without merging

2018-12-13 16:16 UTC, simonjayhawkins commented on pandas/tests/indexing/multiindex/test_iloc.py
> +def test_iloc_getitem_multiindex2():
xref #24272