REF/TST: Add more pytest idiom to indexing/multiindex/test_getitem.py
pandas-dev/pandas pull request #24053
Opened 2018-12-02 20:26 UTC by simonjayhawkins

xref #24040

for this pass:

- the Test classes have been removed.

- `catch_warnings`  used for the `.ix` deprecation replaced with `@pytest.mark.filterwarnings("ignore:\\n.ix:DeprecationWarning")` at test level.

cc @jreback @gfyoung

2018-12-02 20:41 UTC, gfyoung commented on pandas/tests/indexing/multiindex/test_getitem.py
> +    tm.assert_series_equal(result, expected)
Can we break this massive test up into smaller ones?

2018-12-02 20:41 UTC, jreback requested changes

2018-12-02 20:41 UTC, jreback commented on pandas/tests/indexing/multiindex/test_getitem.py
> +def test_getitem_duplicates_multiindex():
can you try to parameteize this on the input frame / expected output.

2018-12-02 20:41 UTC, jreback commented on pandas/tests/indexing/multiindex/test_getitem.py
> +def test_getitem_duplicates_multiindex():
might make sense to split out the empty case to a new test

2018-12-02 20:41 UTC, gfyoung commented on pandas/tests/indexing/multiindex/test_getitem.py
> +    pytest.raises(com.SettingWithCopyError, f)
Any error message worth checking?

2018-12-02 22:42 UTC, simonjayhawkins commented on pandas/tests/indexing/multiindex/test_getitem.py
> +    result = s.xs(0, level=0)
we could then paramatrize..

```
@pytest.mark.parametrize('access_method', [lambda s, x: s[:, x],
                                           lambda s, x: s.loc[:, x],
                                           lambda s, x: s.xs(x, level=1)])
@pytest.mark.parametrize('level1_value, expected', [
    (0, Series([1], index=[0])),
    (1, Series([2, 3], index=[1, 2]))
])
def test_series_getitem_multiindex(access_method, level1_value, expected):

    # GH 6018
    # series regression getitem with a multi-index

    s = Series([1, 2, 3])
    s.index = MultiIndex.from_tuples([(0, 0), (1, 1), (2, 1)])
    result = access_method(s, level1_value)
    tm.assert_series_equal(result, expected)
```

or is this OTT.

2018-12-03 00:17 UTC, jreback commented on pandas/tests/indexing/multiindex/test_getitem.py
> +    result = s.xs(0, level=0)
no, you certainly parameterize this

2018-12-11 11:00 UTC, simonjayhawkins commented
@jreback @gfyoung 

`test_series_getitem_multiindex` and `test_getitem_duplicates_multiindex` split and parametrized. error messages checked.

carry on and split and parametrize the remaining tests in this file within this PR or limit the diff?

2018-12-11 13:53 UTC, jreback approved these changes

2018-12-11 13:54 UTC, merged

2018-12-11 13:54 UTC, jreback commented
thanks @simonjayhawkins keep em coming! I don't mind bigger ones, main issue is there are some other parts moving so easiest to get them in in self-contained units.