API/ENH/DEPR: Series.unique returns Series
pandas-dev/pandas pull request #24108
Opened 2018-12-05 07:38 UTC by h-vetinari

I know this PR is too big, but I need it to initiate discussion before `v.0.24` cutoff.

I've been working on adding a `return_inverse` to `unique` since mid June (as fast as possible). I know that changing the return type of `Series.unique` is potentially a controversial issue, but I truly believe that this should be done for v.0.24 (as otherwise the behavior is locked in past 1.0 and who knows if it ever changes then).

IMO, it's even a necessity if pandas ever wants to support `return_inverse` for `unique`. Here's a few arguments from working on this for a while:

* This is both a long-standing issue (#4087 milestoned since 0.14) and *very* hard for a user to do any other way.
* `.unique` is the obvious place for an inverse (as opposed to `.duplicated`, which I was directed to work on first, #21645)
* An inverse for `Series` only works well if the return type of `Series.unique` is a `Series`, see https://github.com/pandas-dev/pandas/issues/22824#issuecomment-432841642. This is not even the strongest reason IMO to change the type, as `.unique` is a patchwork currently (see rest OP of #22824):
  * `Index.unique` is already an `Index` (and changing that back to `ndarray` would be equally disruptive, and wouldn't lead anyhwere re:reconstruction)
  * The current `Series.unique` already special-cases `Categorical` and (effectively) `DatetimeArray`.

The reason I'm pushing this WIP for discussion is that this is obviously needs a deprecation cycle, and I *really* think this should be part of `v.0.24`. I'm sorry for the late timing, but I've been working as fast as feedback speed allowed (as often as politeness allowed me to ping) - #21645 was lying around mostly finished for 2 month, the cython backend (#22986 / #23400) took about 2 months, and I haven't been able to get an answer at #22824 for about 5 weeks (e.g. @jorisvandenbossche seems to be very busy or simply not available)

As for the PR itself, I *only* wanted to change the return-type in this PR, but `Series.unique` touches several important paths:
1. `Series.unique`
1. `IndexOpsMixin.unique` and hence `Index.unique`
1. `Categorical.unique`
1. `EA.unique`

So, as a demo here, I've adapted the first three, and it's a separate issue that **the EA contract should support the possibility for `return_inverse`**. This is also something that should IMO needs to make it to `v.0.24`.

- [x] actually closes #4087 (milestoned since 0.14), makes several big steps towards #21357 / #22824
- [x] tests modified / pass
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-12-05 07:38 UTC, pep8speaks commented
Hello @h-vetinari! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/algorithms.py`](https://github.com/h-vetinari/pandas/blob/6fd279a6b8d562bca9f4ddb6a44bd02c15320b27/pandas/core/algorithms.py) !

 - There are no PEP8 issues in the file [`pandas/core/arrays/categorical.py`](https://github.com/h-vetinari/pandas/blob/6fd279a6b8d562bca9f4ddb6a44bd02c15320b27/pandas/core/arrays/categorical.py) !

 - There are no PEP8 issues in the file [`pandas/core/base.py`](https://github.com/h-vetinari/pandas/blob/6fd279a6b8d562bca9f4ddb6a44bd02c15320b27/pandas/core/base.py) !

 - There are no PEP8 issues in the file [`pandas/core/indexes/base.py`](https://github.com/h-vetinari/pandas/blob/6fd279a6b8d562bca9f4ddb6a44bd02c15320b27/pandas/core/indexes/base.py) !

 - There are no PEP8 issues in the file [`pandas/core/series.py`](https://github.com/h-vetinari/pandas/blob/6fd279a6b8d562bca9f4ddb6a44bd02c15320b27/pandas/core/series.py) !

 - There are no PEP8 issues in the file [`pandas/tests/arrays/categorical/test_analytics.py`](https://github.com/h-vetinari/pandas/blob/6fd279a6b8d562bca9f4ddb6a44bd02c15320b27/pandas/tests/arrays/categorical/test_analytics.py) !

 - There are no PEP8 issues in the file [`pandas/tests/arrays/sparse/test_array.py`](https://github.com/h-vetinari/pandas/blob/6fd279a6b8d562bca9f4ddb6a44bd02c15320b27/pandas/tests/arrays/sparse/test_array.py) !

 - There are no PEP8 issues in the file [`pandas/tests/extension/base/methods.py`](https://github.com/h-vetinari/pandas/blob/6fd279a6b8d562bca9f4ddb6a44bd02c15320b27/pandas/tests/extension/base/methods.py) !

 - There are no PEP8 issues in the file [`pandas/tests/frame/test_indexing.py`](https://github.com/h-vetinari/pandas/blob/6fd279a6b8d562bca9f4ddb6a44bd02c15320b27/pandas/tests/frame/test_indexing.py) !

 - There are no PEP8 issues in the file [`pandas/tests/plotting/common.py`](https://github.com/h-vetinari/pandas/blob/6fd279a6b8d562bca9f4ddb6a44bd02c15320b27/pandas/tests/plotting/common.py) !

 - There are no PEP8 issues in the file [`pandas/tests/reshape/merge/test_merge.py`](https://github.com/h-vetinari/pandas/blob/6fd279a6b8d562bca9f4ddb6a44bd02c15320b27/pandas/tests/reshape/merge/test_merge.py) !

 - There are no PEP8 issues in the file [`pandas/tests/series/test_duplicates.py`](https://github.com/h-vetinari/pandas/blob/6fd279a6b8d562bca9f4ddb6a44bd02c15320b27/pandas/tests/series/test_duplicates.py) !

 - There are no PEP8 issues in the file [`pandas/tests/test_algos.py`](https://github.com/h-vetinari/pandas/blob/6fd279a6b8d562bca9f4ddb6a44bd02c15320b27/pandas/tests/test_algos.py) !

 - There are no PEP8 issues in the file [`pandas/tests/test_base.py`](https://github.com/h-vetinari/pandas/blob/6fd279a6b8d562bca9f4ddb6a44bd02c15320b27/pandas/tests/test_base.py) !

2018-12-05 07:51 UTC, h-vetinari reviewed
Some inline notes

2018-12-05 07:51 UTC, h-vetinari commented on pandas/core/base.py
> +            uniqs = self.unique()
Here, `raw=True` is unfortunately not compatible with the Index case

2018-12-05 07:51 UTC, h-vetinari commented on pandas/core/series.py
> +        dtype: datetime64[ns]
I think this is clearly superior output...

2018-12-05 07:51 UTC, h-vetinari commented on pandas/core/series.py
> -        result = super(Series, self).unique()
The branch for `raw=True` is exactly the same as before, but the diff is messed up because of the changed indentation.

2018-12-05 07:51 UTC, h-vetinari commented on pandas/tests/extension/base/methods.py
> +            result = method(duplicated)
This is a bit awkward, I'll admit, but the only way to avoid raising the `FutureWarning`.

2018-12-05 07:59 UTC, h-vetinari commented on pandas/core/series.py
> +        correctly set the index.
At this point, it's be really neat to have #22225 available to use `.set_index`...

2018-12-05 11:38 UTC, jreback requested changes
you are right this is way too big.

the question about the return value of .unique needs to be answered first; return an .array of the result (for Index and Series) is probably the most reasonable change and is mostly backward compatible

however better to bring this up on the issue (for unique return value)

2019-05-12 21:24 UTC, jreback commented
good idea, but closing as stale

2019-05-12 21:24 UTC, closed without merging

2019-05-13 05:36 UTC, h-vetinari commented
> @jreback: good idea, but closing as stale

Not stale, but will need precursors, like #24119.

2019-10-07 06:18 UTC, h-vetinari commented
@jreback @gfyoung @simonjayhawkins 
Can we please reopen this PR, or at least the precursor #24119?

2019-10-07 07:23 UTC, jreback commented
i am not averse to changing the return type of .unique but cannot be linked to return_inverse which likely has less support

PRs need to do exactly 1 thing as have been stated many times
this ape e too complex

2019-10-07 07:57 UTC, h-vetinari commented
@jreback 
Thanks for the response. I know this PR is too big (see OP), but it is the goal towards which I'd chip off smaller PRs (e.g. #24119).

Unfortunately, the `return_inverse` parts will have to come first, because it is not possible to return a Series with the correct index without tracking the inverse internally. In fact, I would argue that this is the *main* reason that `Series.unique` historically returned an array, because the cython-backend did not support calculating the inverse (luckily that's already been added in #22986 / #23400; the rest is a relatively easy change - see #24119).

2019-10-07 08:11 UTC, jreback commented
@h-vetinari maybe i still don’t see it

why is returning a Series from .unique() actually useful?
why not an .array? then doesn’t .factorize() exactly provide the ability to reconstruct (iirc your main goal); speaking of reconstruction; how is this useful to a user? what is the use case?

2019-10-07 08:24 UTC, jorisvandenbossche commented
@jreback many of those questions have already seen some discussion in https://github.com/pandas-dev/pandas/issues/22824 (including example use cases), so I would suggest we keep the general discussion on overhauling unique there. Can you repeat your comment there?