Added log10 to the list of unary functions df.eval can handle
pandas-dev/pandas pull request #24140
Opened 2018-12-07 07:57 UTC by euri10

- [x] closes https://github.com/pandas-dev/pandas/issues/24139 
- [x] tests ~~added~~ / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

`(pandas) ➜  pandas git:(binary_math_log) git diff upstream/master -u -- "*.py" | flake8 --diff
`
- [ ] whatsnew entry

2018-12-07 07:57 UTC, pep8speaks commented
Hello @euri10! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/computation/ops.py`](https://github.com/euri10/pandas/blob/5f46a28f918422b3199626becbaee561d22921c6/pandas/core/computation/ops.py) !

2018-12-07 12:50 UTC, jreback commented
can you add a test for this, in pandas/tests/computation/test_eval.py & a whatsnew note (bug fixes for numeric is ok)

2018-12-07 12:50 UTC, jreback requested changes
comments

2018-12-07 14:24 UTC, euri10 commented
Added the whatsnew part as requested @jreback 
For the tests, it seems unecessary to me to add something new, the existing one are already handle the case in [here](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/computation/test_eval.py#L1625-L1633)

2018-12-09 14:05 UTC, jreback requested changes

2018-12-09 14:05 UTC, jreback commented on doc/source/whatsnew/v0.23.5.txt
> +
can you move this to 0.24.0

2018-12-09 15:52 UTC, euri10 commented on doc/source/whatsnew/v0.23.5.txt
> +
oups, done, sorry for that

2018-12-09 15:53 UTC, jreback requested changes

2018-12-09 15:53 UTC, jreback commented on doc/source/whatsnew/v0.23.5.txt
> +- Bug in :func:`read_csv` that caused it to raise ``OverflowError`` when trying to use 'inf' as ``na_value`` with integer index column (:issue:`17128`)
you need to checkout this file from master as it should be unchanged.

2018-12-09 15:53 UTC, jreback commented on doc/source/whatsnew/v0.24.0.rst
> +- Added log10 to the list of supported functions in ``df.eval`` (:issue:`24139`)
use double back-ticks on ``log10``, use a ``:meth:`` reference for eval

2018-12-09 16:09 UTC, jreback approved these changes

2018-12-09 16:09 UTC, jreback commented
lgtm ping on green.

2018-12-09 18:52 UTC, merged