BUG: Throw ValueError when the format kwarg is passed to the HDFStore…
pandas-dev/pandas pull request #24155
Opened 2018-12-07 22:49 UTC by CianciuStyles

… constructor

- [x] closes #13291
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-12-07 22:49 UTC, pep8speaks commented
Hello @CianciuStyles! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/io/pytables.py`](https://github.com/CianciuStyles/pandas/blob/3359cfdd09c21d6a17e59403103a8f89dd336a0a/pandas/io/pytables.py) !

 - There are no PEP8 issues in the file [`pandas/tests/io/test_pytables.py`](https://github.com/CianciuStyles/pandas/blob/3359cfdd09c21d6a17e59403103a8f89dd336a0a/pandas/tests/io/test_pytables.py) !

2018-12-09 14:32 UTC, jreback requested changes

2018-12-09 14:32 UTC, jreback commented on doc/source/whatsnew/v0.24.0.rst
> +- :func:`HDFStore` will throw ``ValueError`` when the ``format`` kwarg is passed to the constructor (:issue:`13291`)
throw -> raise

2018-12-09 14:32 UTC, jreback commented
looks ok, ping when pushed / green.

2018-12-09 15:54 UTC, jreback approved these changes

2018-12-09 15:54 UTC, jreback commented
lgtm. ping on green.

2018-12-09 16:10 UTC, CianciuStyles commented
Hello Jeff, it looks like everything is green now.

2018-12-09 16:10 UTC, merged

2018-12-09 16:11 UTC, jreback commented
thans @CianciuStyles