DOC: Fix quotes position in Timestamp and Timedelta
pandas-dev/pandas pull request #24243
Opened 2018-12-11 21:58 UTC by diogo-bastos

The validate_docstrings.py validator was returning errors for methods with no comments. I only worked on the methods that already had comments in this PR.

- works on #24070

2018-12-11 21:58 UTC, pep8speaks commented
Hello @diogo-bastos! Thanks for submitting the PR.

 - In the file [`pandas/core/indexes/datetimes.py`](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py), following                are the PEP8 issues :
> [Line 46:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py#L46): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 46:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py#L46): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 47:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py#L47): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 48:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py#L48): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 48:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py#L48): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 403:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py#L403): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 403:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py#L403): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 404:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py#L404): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 419:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py#L419): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 419:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py#L419): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 420:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py#L420): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 449:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py#L449): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 449:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py#L449): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 450:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py#L450): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 457:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py#L457): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 457:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py#L457): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 458:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/datetimes.py#L458): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs


 - In the file [`pandas/core/indexes/interval.py`](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py), following                are the PEP8 issues :
> [Line 231:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py#L231): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 231:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py#L231): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 232:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py#L232): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 389:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py#L389): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 389:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py#L389): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 390:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py#L390): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 423:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py#L423): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 423:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py#L423): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 424:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py#L424): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 430:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py#L430): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 430:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py#L430): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 431:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py#L431): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 732:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py#L732): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 732:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py#L732): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 1029:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py#L1029): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 1029:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py#L1029): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 1030:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/pandas/core/indexes/interval.py#L1030): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 1157:1](https://github.com/diogo-bastos/pandas/blob/83b5fa46579f950d85a3890d31eb474b555c804b/p [...]

2018-12-12 13:24 UTC, jreback requested changes
lots of alignment issues with quotes

2018-12-12 13:24 UTC, jreback commented on pandas/_libs/tslibs/timedeltas.pyx
> +	"""
this is not aligned here

2018-12-12 13:24 UTC, jreback commented on pandas/_libs/tslibs/timedeltas.pyx
> +        int64_t value
huh? this is so much harder to read, just revert this

2018-12-13 14:44 UTC, datapythonista commented
@diogo-bastos some extra information that it was probably not clear in the issue description.

The goal of the issue is to fix the format of the docstrings, and leave them consistent everywhere. For a specific subset of docstrings.

So, regarding the issue, the only change needed is to make sure the The opening and closing quotes are correctly aligned.

So, as the issue says, this is correct:
```
def foo():
    """
    Summary of the docstring.

    Returns
    -------
    str
        Explaining what is being returned.
    """
```

and any other variation is not:
```
def foo():
    """    Summary of the docstring.

    Returns
    -------
    str
        Explaining what is being returned.
    """
```
or
```
def foo():
    """
       Summary of the docstring.

    Returns
    -------
    str
        Explaining what is being returned.
                """
```
etc.

And only for the docstrings reported by the script. So, the call to the script in the issue doesn't report any case once this is finished.

For this PR we don't expect any change to the code, change to other docstrings, change to the content of the docstrings or any unrelated change. If you think something else needs to be changed, open an issue, wait for the discussion on whether it's a good idea, and then open a separate PR specific to that issue. We need to do this to keep pandas development under control, be able to easily revert changes, and not have a chaos where we can't react to something breaking.

The only other thing that would be acceptable as part of this PR, would be to capitalize the summary and add a period at the end.

So, for example:
```
def foo():
    """ summary of the docstring """
```
could become
```
def foo():
    """
    Summary of the docstring.
    """
```

I'm going to close this for now, as I'm not sure if it'll be easier for you to start again in a new PR, or fix this. Feel free to reopen when you have the correct changes, or open a new PR.

Thanks a lot for working on this.

2018-12-13 14:44 UTC, closed without merging

2018-12-14 14:08 UTC, diogo-bastos commented
Hello @datapythonista , thank you for your feedback and patience. I will open a new PR with the correct changes soon.