API: Always return DataFrame from get_dummies
pandas-dev/pandas pull request #24284
Opened 2018-12-14 20:10 UTC by TomAugspurger

xref https://github.com/pandas-dev/pandas/issues/19239

In preparation for hopefully deprecating SparseDataFrame / SparseSeries. Right now, I've just made this an API breaking change.

If we want to do this via deprecation, we'd need a new keyword argument to control the result type. I opted against that, because to get a warning-free `get_dummies` people would need

```python
pd.get_dummies(..., sparse=True, result_type=None/'sparse_dataframe'/'dataframe'):
    ...
```

IMO, that's too big a burden for the common case, but would be curious to hear others' thoughts here.

2018-12-14 20:11 UTC, pep8speaks commented
Hello @TomAugspurger! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/reshape/reshape.py`](https://github.com/TomAugspurger/pandas/blob/bfb3dfb038b75370160cf51b7cab13bdc4adcbd1/pandas/core/reshape/reshape.py) !

 - There are no PEP8 issues in the file [`pandas/tests/reshape/test_reshape.py`](https://github.com/TomAugspurger/pandas/blob/bfb3dfb038b75370160cf51b7cab13bdc4adcbd1/pandas/tests/reshape/test_reshape.py) !

2018-12-14 23:22 UTC, jreback requested changes
minor comments

2018-12-15 19:21 UTC, jreback requested changes

2018-12-15 20:17 UTC, TomAugspurger commented
No specific issue.

2018-12-15 21:13 UTC, jreback approved these changes

2018-12-15 21:13 UTC, merged

2018-12-15 21:13 UTC, jreback commented
thanks !