BUG: Fix index bug due to parse_time_string GH24091
pandas-dev/pandas pull request #24294
Opened 2018-12-15 08:38 UTC by SimonAlecks

- [x] closes #24091
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

In Issue #24091 I detailed the root cause of the bug, and implemented the @toobaz suggestion.

I added a single line to test this case in the existing test, ran the full UT suite, checked the linting, and added a whatsnew (I added the whatsnew in the other category, as It wasn't clear where it belonged).

2018-12-15 08:38 UTC, pep8speaks commented
Hello @SimonAlecks! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/tests/tslibs/test_parsing.py`](https://github.com/SimonAlecks/pandas/blob/518545d06f5f2c7fccadea4ebf218b5a904bcd31/pandas/tests/tslibs/test_parsing.py) !

2018-12-15 19:18 UTC, jreback requested changes
add a test for the OP

2018-12-15 19:18 UTC, jreback commented on doc/source/whatsnew/v0.24.0.rst
> +- :meth:`~pandas._libs.tslibs.parsing.parse_time_string` now raises a type error if the passed argument is not a string, (:issue:`24091`)
use ``TypeError``. this is an internal method and doesn't need a note for this, rather the use facing case does.

2018-12-15 19:18 UTC, jreback commented on pandas/tests/tslibs/test_parsing.py
> +        pytest.raises(TypeError, parse_time_string, Period('2018-11-01', 'B'))
use a context manger here,  make this a separate test, and add the issue as a comment

2019-01-05 15:38 UTC, jreback commented
can you merge master and update

2019-02-27 23:55 UTC, WillAyd commented
Closing as stale. Ping if you'd like to continue

2019-02-27 23:55 UTC, closed without merging