STY: use pytest.raises context syntax
pandas-dev/pandas pull request #24297
Opened 2018-12-15 18:37 UTC by jbrockmendel

There are still about a thousand non-context usages of pytest.raises.

@gfyoung if there is a subset of these that especially merit match kwargs, let me know.  I'm not eager to manually go through all of them, but doing something systematic or manually doing a few I'd be up for.

2018-12-15 18:37 UTC, pep8speaks commented
Hello @jbrockmendel! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/tests/api/test_types.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/api/test_types.py) !

 - There are no PEP8 issues in the file [`pandas/tests/arrays/categorical/test_api.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/arrays/categorical/test_api.py) !

 - There are no PEP8 issues in the file [`pandas/tests/arrays/categorical/test_constructors.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/arrays/categorical/test_constructors.py) !

 - There are no PEP8 issues in the file [`pandas/tests/arrays/categorical/test_indexing.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/arrays/categorical/test_indexing.py) !

 - There are no PEP8 issues in the file [`pandas/tests/arrays/categorical/test_operators.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/arrays/categorical/test_operators.py) !

 - There are no PEP8 issues in the file [`pandas/tests/frame/test_apply.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/frame/test_apply.py) !

 - There are no PEP8 issues in the file [`pandas/tests/frame/test_indexing.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/frame/test_indexing.py) !

 - There are no PEP8 issues in the file [`pandas/tests/frame/test_quantile.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/frame/test_quantile.py) !

 - There are no PEP8 issues in the file [`pandas/tests/generic/test_frame.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/generic/test_frame.py) !

 - There are no PEP8 issues in the file [`pandas/tests/groupby/test_categorical.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/groupby/test_categorical.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexes/datetimes/test_astype.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/indexes/datetimes/test_astype.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexes/multi/test_analytics.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/indexes/multi/test_analytics.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexes/multi/test_sorting.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/indexes/multi/test_sorting.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexing/multiindex/test_setitem.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/indexing/multiindex/test_setitem.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexing/multiindex/test_slice.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/indexing/multiindex/test_slice.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexing/test_indexing.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/indexing/test_indexing.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexing/test_panel.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/indexing/test_panel.py) !

 - There are no PEP8 issues in the file [`pandas/tests/indexing/test_partial.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/indexing/test_partial.py) !

 - There are no PEP8 issues in the file [`pandas/tests/resample/test_resample_api.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/resample/test_resample_api.py) !

 - There are no PEP8 issues in the file [`pandas/tests/reshape/merge/test_multi.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/reshape/merge/test_multi.py) !

 - There are no PEP8 issues in the file [`pandas/tests/series/indexing/test_boolean.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/series/indexing/test_boolean.py) !

 - There are no PEP8 issues in the file [`pandas/tests/series/indexing/test_numeric.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/series/indexing/test_numeric.py) !

 - There are no PEP8 issues in the file [`pandas/tests/series/test_apply.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/series/test_apply.py) !

 - There are no PEP8 issues in the file [`pandas/tests/test_base.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/test_base.py) !

 - There are no PEP8 issues in the file [`pandas/tests/test_lib.py`](https://github.com/jbrockmendel/pandas/blob/c8fa1bc8606e3ec43e46fac82e5e451c46ee3f59/pandas/tests/test_lib.py) !

2018-12-15 19:16 UTC, jreback requested changes
can you create a lint rule to check for non-context manager usage of ``pytest.raises``?

2018-12-15 19:16 UTC, jreback commented on pandas/tests/frame/test_indexing.py
> +            np.log(s)
what's this

2018-12-15 19:41 UTC, jbrockmendel commented on pandas/tests/frame/test_indexing.py
> +            np.log(s)
must be a copy/paste mixup, will fix

2018-12-16 01:05 UTC, gfyoung commented
@jbrockmendel : Thanks for the ping.  Given how massive this is, I think we can just focus on the conversion to context manager first.  Which ones should use a match parameter can be determined after (i.e. subsequent PR’s)

2018-12-16 20:53 UTC, jreback approved these changes

2018-12-16 20:54 UTC, merged

2018-12-16 20:54 UTC, jreback commented
thanks. @gfyoung we should prob have a lint rule to detect this, but leave commented for now

2018-12-17 01:10 UTC, gfyoung commented
@jreback: I actually was discussing the checking if error messages, not the usage of the context manager versus not.  That being said, I do agree we should lint for what was addressed here.