BUG: Ensure incomplete stata files are deleted
pandas-dev/pandas pull request #24319
Opened 2018-12-17 14:39 UTC by bashtage

Attempt to delete failed writes and warn if not able to delete

- [x] closes N/A
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-12-17 14:39 UTC, pep8speaks commented
Hello @bashtage! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/io/stata.py`](https://github.com/bashtage/pandas/blob/00ab182bd9e606c5e93372a4abca3b81f2daaf6f/pandas/io/stata.py) !

 - There are no PEP8 issues in the file [`pandas/tests/io/test_stata.py`](https://github.com/bashtage/pandas/blob/00ab182bd9e606c5e93372a4abca3b81f2daaf6f/pandas/tests/io/test_stata.py) !

2018-12-17 14:42 UTC, bashtage commented
xref #23573

2018-12-18 14:26 UTC, jreback requested changes

2018-12-18 14:30 UTC, bashtage commented on pandas/io/stata.py
> +class IOWarning(Warning):
Fixed.  I wanted ResourceWarning but not available in 2.7.  Ready for 2.7 to be retired.

2018-12-18 14:32 UTC, jreback commented on pandas/io/stata.py
> +class IOWarning(Warning):
actually, use ``pandas.compat.ResourceWarning`` it is defined

2018-12-18 22:16 UTC, bashtage commented
@jreback This is ready now.

2018-12-18 22:35 UTC, jreback approved these changes

2018-12-18 22:35 UTC, merged

2018-12-18 22:35 UTC, jreback commented
thanks @bashtage