DOC: Update compiler guidance for Windows
pandas-dev/pandas pull request #24331
Opened 2018-12-18 11:08 UTC by jamesmyatt

... to make it a bit more encouraging.

2018-12-18 11:56 UTC, jamesmyatt commented on doc/source/contributing.rst
> +  the **Python development workload** and the **Python native development tools** option
Yeah, I wondered about that. But is it OK in principle?

2018-12-18 17:28 UTC, chris-b1 approved these changes

2018-12-18 18:29 UTC, WillAyd requested changes

2018-12-18 18:59 UTC, jreback commented on doc/source/contributing.rst
> +For Windows developers, when using Python 3.5 and later, it is sufficient to
this should be >= 3.5 i think

2018-12-19 13:01 UTC, jamesmyatt commented on doc/source/contributing.rst
> +For Windows developers, when using Python 3.5 and later, it is sufficient to
The current version of the Python dev guide says 3.6+, but the MS Python engineering blog posts say 3.5+.

https://blogs.msdn.microsoft.com/pythonengineering/2017/03/07/python-support-in-vs2017/

2018-12-19 13:05 UTC, datapythonista commented on doc/source/contributing.rst
> +For Windows developers, when using Python 3.5 and later, it is sufficient to
may be @zooba can help?

2018-12-19 14:16 UTC, chris-b1 commented on doc/source/contributing.rst
> +For Windows developers, when using Python 3.5 and later, it is sufficient to
So my understanding is that the VS 2015 _toolchain_ is required for python 3.5 extensions, but VS 2017 supports multiple toolchains, and the "Python native development tools" installs both the 2015/2017 c++ toolchains, so works for python 3.5+

2018-12-19 18:03 UTC, zooba commented on doc/source/contributing.rst
> +For Windows developers, when using Python 3.5 and later, it is sufficient to
That's correct, though IIRC Python 3.5 was never updated to automatically detect VS 2017, which is why the devguide refers to the newer version.

2018-12-19 19:46 UTC, WillAyd approved these changes
Fine with me @jreback

2018-12-19 22:53 UTC, jreback commented
thanks @jamesmyatt

2018-12-19 22:53 UTC, merged