add to_frame method to DataFrame
pandas-dev/pandas pull request #24336
Opened 2018-12-18 13:03 UTC by letalvoj

Add convenience method which makes sure that we can safely call `to_frame` on any method returning both `Series` and `DataFrame` instances, such as `groupby` etc.

- [ ] ~~closes #11292 xxx~~ (no issue)
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2018-12-18 13:03 UTC, pep8speaks commented
Hello @letalvoj! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/core/frame.py`](https://github.com/letalvoj/pandas/blob/7038a7931784bc9a3607b2a0adbd6f0908509aa7/pandas/core/frame.py) !

 - There are no PEP8 issues in the file [`pandas/tests/sparse/frame/test_frame.py`](https://github.com/letalvoj/pandas/blob/7038a7931784bc9a3607b2a0adbd6f0908509aa7/pandas/tests/sparse/frame/test_frame.py) !

2018-12-18 13:38 UTC, jreback commented
-0 on this. just cluttering the API.

2018-12-18 13:51 UTC, letalvoj commented
Sometimes I find people struggling to use `groupby` + `apply` / `loc`. As these methods can easily return both `DataFrame` / `Series` given not only the params but the instance on which you call it as well. IMO this is more elegant then `isinstance`ing.

_ad. api_
I get the argument regarding the API. yet in a sense all the other classes have the method
 * Series.to_frame
 * Panel.to_frame
 * Index.to_frame
even some indices
 * MultiIndex.to_frame
 * DatetimeIndex.to_frame
 * TimedeltaIndex.to_frame
Therefore I feel like it's not _just some other random method_. Or is it?

_ad. copying_
Oh, right. The implementation is copy-on-write, right? Is it going to be a great overhead then?

2018-12-18 14:11 UTC, jreback requested changes
needs some discussion

2018-12-19 00:30 UTC, datapythonista commented
@letalvoj do you mind writing a real case example on when this would be useful. I understand your point, but would be useful for the discussion to see how a real example would look with and without `DataFrame.to_frame()`

2019-01-14 00:13 UTC, jreback commented
@letalvoj I think this needs an issue for discussion. If you'd like to open one with a realistic usecase we can see if there is appetite. closing this for now.

2019-01-14 00:13 UTC, closed without merging