REF/TST: Add more pytest idiom to resample/test_base.py
pandas-dev/pandas pull request #24377
Opened 2018-12-20 19:33 UTC by simonjayhawkins

- [ n/a] xref #17806
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ n/a] whatsnew entry

in this pass:

- alternative approach to #24324
- parametrize base class tests individually to avoid changing fixtures

cc @jreback

2018-12-20 19:33 UTC, pep8speaks commented
Hello @simonjayhawkins! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`pandas/tests/resample/test_base.py`](https://github.com/simonjayhawkins/pandas/blob/dceb8bc314f568cdb491db4e39dc328877c917ce/pandas/tests/resample/test_base.py) !

2018-12-21 16:33 UTC, jreback requested changes
need to look some more

2018-12-21 16:33 UTC, jreback commented on pandas/tests/resample/test_base.py
> +    '_index_factory,_series_name,_index_start,_index_end',
this is slightly magical

2018-12-23 15:42 UTC, jreback requested changes
looks good. on master we have 499 tests and 139 skipped, here 497 ad 9 skipped. so I think a couple got removed?

2018-12-23 15:42 UTC, jreback commented on pandas/tests/resample/test_base.py
> +# tuples of '_index_factory,_series_name,_index_start,_index_end'
can you give a little more expl here on what this actuall does

2018-12-23 17:52 UTC, simonjayhawkins commented
@jreback 

> on master we have 499 tests and 139 skipped, here 497 ad 9 skipped. so I think a couple got removed?

for `TestDatetimeIndex::test_resample_empty_dtypes`

```
$ pytest pandas/tests/resample/test_base.py::TestDatetimeIndex::test_resample_empty_dtypes
============================= test session starts =============================
platform win32 -- Python 3.6.6, pytest-3.7.3, py-1.5.4, pluggy-0.7.1
rootdir: C:\Users\simon\OneDrive\code\pandas-simonjayhawkins, inifile: setup.cfg
plugins: xdist-1.23.0, forked-0.2, cov-2.5.1, hypothesis-3.59.1
collected 192 items

pandas\tests\resample\test_base.py ..................................... [ 19%]
........................................................................ [ 56%]
........................................................................ [ 94%]
...........                                                              [100%]

========================= 192 passed in 1.55 seconds ==========================
```

similarly for `TestPeriodIndex`

```
$ pytest pandas/tests/resample/test_base.py::TestPeriodIndex::test_resample_empty_dtypes
============================= test session starts =============================
platform win32 -- Python 3.6.6, pytest-3.7.3, py-1.5.4, pluggy-0.7.1
rootdir: C:\Users\simon\OneDrive\code\pandas-simonjayhawkins, inifile: setup.cfg
plugins: xdist-1.23.0, forked-0.2, cov-2.5.1, hypothesis-3.59.1
collected 192 items

pandas\tests\resample\test_base.py ..................................... [ 19%]
........................................................................ [ 56%]
........................................................................ [ 94%]
...........                                                              [100%]

========================= 192 passed in 1.10 seconds ==========================
```

and the same for `TestTimedeltaIndex`

but because `test_resample_empty_dtypes` is paramatrized using a generator it was misbehaving..

```
$ pytest pandas/tests/resample/test_base.py -k test_resample_empty_dtypes
============================= test session starts =============================
platform win32 -- Python 3.6.6, pytest-3.7.3, py-1.5.4, pluggy-0.7.1
rootdir: C:\Users\simon\OneDrive\code\pandas-simonjayhawkins, inifile: setup.cfg
plugins: xdist-1.23.0, forked-0.2, cov-2.5.1, hypothesis-3.59.1
collected 638 items / 318 deselected

pandas\tests\resample\test_base.py ..................................... [ 11%]
........................................................................ [ 34%]
........................................................................ [ 56%]
...........sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 79%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss      [100%]

=========== 192 passed, 128 skipped, 318 deselected in 1.43 seconds ===========

```

so that account for 128 of the 130 reduction in skipped tests. the other two are from the overridden tests...

https://github.com/pandas-dev/pandas/blob/1cd077a3077352d63c1226d554db1e46cb9d2c1a/pandas/tests/resample/test_base.py#L231-L237

the number of passed tests is reduced by two since `test_raises_on_non_datetimelike_index` is not dependent on index type so is now only run once instead of 3 times.

https://github.com/pandas-dev/pandas/blob/1cd077a3077352d63c1226d554db1e46cb9d2c1a/pandas/tests/resample/test_base.py#L71-L74

2018-12-23 19:08 UTC, jreback commented
```
_____________ ERROR collecting pandas/tests/resample/test_base.py _____________
2018-12-23T18:59:10.6286537Z C:\Miniconda\envs\pandas-dev\lib\site-packages\_pytest\python.py:450: in _importtestmodule
2018-12-23T18:59:10.6287402Z     mod = self.fspath.pyimport(ensuresyspath=importmode)
2018-12-23T18:59:10.6287666Z C:\Miniconda\envs\pandas-dev\lib\site-packages\py\_path\local.py:668: in pyimport
2018-12-23T18:59:10.6287846Z     __import__(modname)
2018-12-23T18:59:10.6288006Z E     File "D:\a\1\s\pandas\tests\resample\test_base.py", line 21
2018-12-23T18:59:10.6288224Z E   SyntaxError: Non-ASCII character '\xe2' in file D:\a\1\s\pandas\tests\resample\test_base.py on line 21, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
2018-12-23T18:59:10.629434
```

2018-12-23 23:05 UTC, jreback approved these changes

2018-12-23 23:06 UTC, merged

2018-12-23 23:06 UTC, jreback commented
thanks @simonjayhawkins