BUG/PERF: Sparse get_dummies uses concat
pandas-dev/pandas pull request #24372
Opened 2018-12-20 12:43 UTC by TomAugspurger

Working around the DataFrame constructor perf issue in https://github.com/pandas-dev/pandas/issues/24368

Fixes deprecation warnings in the ASV files so there's something to run.

Closes https://github.com/pandas-dev/pandas/issues/24371

2018-12-20 12:43 UTC, pep8speaks commented
Hello @TomAugspurger! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`asv_bench/benchmarks/join_merge.py`](https://github.com/TomAugspurger/pandas/blob/b253674bbdf2771221af82b5637fee63efa7f8d0/asv_bench/benchmarks/join_merge.py) !

 - There are no PEP8 issues in the file [`asv_bench/benchmarks/panel_ctor.py`](https://github.com/TomAugspurger/pandas/blob/b253674bbdf2771221af82b5637fee63efa7f8d0/asv_bench/benchmarks/panel_ctor.py) !

 - There are no PEP8 issues in the file [`asv_bench/benchmarks/reindex.py`](https://github.com/TomAugspurger/pandas/blob/b253674bbdf2771221af82b5637fee63efa7f8d0/asv_bench/benchmarks/reindex.py) !

 - There are no PEP8 issues in the file [`asv_bench/benchmarks/timedelta.py`](https://github.com/TomAugspurger/pandas/blob/b253674bbdf2771221af82b5637fee63efa7f8d0/asv_bench/benchmarks/timedelta.py) !

 - There are no PEP8 issues in the file [`asv_bench/benchmarks/timestamp.py`](https://github.com/TomAugspurger/pandas/blob/b253674bbdf2771221af82b5637fee63efa7f8d0/asv_bench/benchmarks/timestamp.py) !

 - There are no PEP8 issues in the file [`pandas/core/dtypes/concat.py`](https://github.com/TomAugspurger/pandas/blob/b253674bbdf2771221af82b5637fee63efa7f8d0/pandas/core/dtypes/concat.py) !

 - There are no PEP8 issues in the file [`pandas/core/reshape/reshape.py`](https://github.com/TomAugspurger/pandas/blob/b253674bbdf2771221af82b5637fee63efa7f8d0/pandas/core/reshape/reshape.py) !

2018-12-20 12:45 UTC, TomAugspurger commented on doc/source/whatsnew/v0.24.0.rst
> +- Bug in :func:`concat` when concatenating a list of :class:`Series` with all-sparse values changing the ``fill_value`` and converting to a dense Series (:issue:`24371`)
When the input to `concat` is a `List[Series[Sparse]]`, we now return a DataFrame with sparse values. Previously this was a dense DataFrame (probably a bug), so it isn't API breaking.

2018-12-20 13:23 UTC, jreback requested changes

2018-12-20 13:30 UTC, jreback commented on pandas/core/reshape/reshape.py
> +        if is_integer_dtype(dtype):
we have that too let’s try to not reinvent the wheel

2018-12-20 13:34 UTC, TomAugspurger commented
Do you know the method name? I don't see one that does it.

On Thu, Dec 20, 2018 at 7:30 AM Jeff Reback <notifications@github.com>
wrote:

> *@jreback* commented on this pull request.
> ------------------------------
>
> In pandas/core/reshape/reshape.py
> <https://github.com/pandas-dev/pandas/pull/24372#discussion_r243271163>:
>
> > @@ -909,7 +910,15 @@ def _make_col_name(prefix, prefix_sep, level):
>
>          index = None
>
>
>
>      if sparse:
>
> -        sparse_series = {}
>
> +
>
> +        if is_integer_dtype(dtype):
>
>
> we have that too let’s try to not reinvent the wheel
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/24372#discussion_r243271163>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABQHIsVh9gjb1l4vfllL5IRhx3YlAv9Mks5u65D5gaJpZM4ZcH5c>
> .
>

2018-12-20 14:08 UTC, TomAugspurger commented on pandas/core/reshape/reshape.py
> +        if is_integer_dtype(dtype):
I didn't a function like this in any of the dtypes modules.

2018-12-21 15:05 UTC, TomAugspurger commented
I think this should be merged soon if possible. The CI failures are blocking https://github.com/pandas-dev/pandas/pull/20796 and the explode PR.

I haven't made too much progress on fixing https://github.com/pandas-dev/pandas/issues/24368 properly. Too many edge cases in our constructors.

2018-12-21 17:11 UTC, jreback approved these changes

2018-12-21 17:11 UTC, merged