BUG: DataFrame.loc/iloc fails to update object with new dtype GH24269
pandas-dev/pandas pull request #24383
Opened 2018-12-21 16:15 UTC by slnguyen

- [ ] closes #24269 
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2018-12-21 16:15 UTC, pep8speaks commented
Hello @slnguyen! Thanks for submitting the PR.

 - In the file [`pandas/core/indexing.py`](https://github.com/slnguyen/pandas/blob/49df8968dd42d5aa7011997fe23a3451abc0f392/pandas/core/indexing.py), following                are the PEP8 issues :
> [Line 635:80](https://github.com/slnguyen/pandas/blob/49df8968dd42d5aa7011997fe23a3451abc0f392/pandas/core/indexing.py#L635): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 79 characters)
> [Line 639:5](https://github.com/slnguyen/pandas/blob/49df8968dd42d5aa7011997fe23a3451abc0f392/pandas/core/indexing.py#L639): [E129](https://duckduckgo.com/?q=pep8%20E129) visually indented line with same indent as next logical line

2018-12-23 00:36 UTC, gfyoung commented
@slnguyen : Good start!  Going to need to add a new test + `whatsnew` entry as well.

2018-12-23 15:54 UTC, jreback requested changes
the first thing you need is a test, before any code changes. the indexing code is quite complicated.

2018-12-23 15:54 UTC, jreback commented on pandas/core/indexing.py
> +                if isinstance(value, ABCDataFrame):
this is very complicated and likely does not belong here. you would need to heavily comment this and explain line by line.

2019-01-14 00:12 UTC, jreback commented
closing as stale if you want to continue working, please ping.

2019-01-14 00:12 UTC, closed without merging