CLN: minor cleaning of Categorical.__init__
pandas-dev/pandas pull request #24402
Opened 2018-12-23 09:31 UTC by topper-123

At a certain point in the Categorical init, we should for clarity only use ``dtype`` and not intermix ``categories`` or ``ordered``.

This small PR does that.

2018-12-23 20:44 UTC, jschendel requested changes

2018-12-23 20:44 UTC, jschendel commented on pandas/core/arrays/categorical.py
> +        if is_categorical_dtype(values) and dtype.categories is None:
I think this should remain nested for perf reasons so the `elif` is not hit unnecessarily when the `is_categorical_dtype(values)` condition is met, but `dtype.categories is None` is not met.  I pulled your changes and did some quick timings with/without this being nested, and the difference does look to be significant.

Nested `if` statements (old version):
```python
In [2]: cat_old = pd.Categorical(list('abca')*10**4)

In [3]: cdt_new = pd.api.types.CategoricalDtype(list('bdac'), True)

In [4]: %timeit  pd.Categorical(cat_old, dtype=cdt_new)
799 µs ± 6.92 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

Single flat `if` statement (new version):
```python
In [2]: cat_old = pd.Categorical(list('abca')*10**4)

In [3]: cdt_new = pd.api.types.CategoricalDtype(list('bdac'), True)

In [4]: %timeit  pd.Categorical(cat_old, dtype=cdt_new)
2.26 ms ± 12.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

2018-12-23 21:42 UTC, jschendel approved these changes
lgtm pending @jreback's asv comment

2018-12-24 11:40 UTC, topper-123 commented
I have some problem getting asv working. I don’t think this can have a performance effect now, after the change after @jschendel comments...

2018-12-24 18:52 UTC, merged

2018-12-24 18:52 UTC, jreback commented
thanks @topper-123