Potential bug fixes on shell scripts
pandas-dev/pandas pull request #24424
Opened 2018-12-25 06:27 UTC by mmphego

- Use $(..) instead of legacy `..`.
- Double quote to prevent globbing and word splitting.
- Redirecting `echo` output to `stderr`.
- Checking if `flake8`, `cpplint` and `isort` Python modules are installed.
- Using 'cd ... || exit' or 'cd ... || return' in case cd fails.
- Double quote to prevent globbing and word splitting.
- The use of > is for string comparisons. Using `-gt` instead.
- [Useless Use Of Cat](https://en.wikipedia.org/wiki/Cat_(Unix)#Useless_use_of_cat)
- Using echo -e "\n", instead of echo ""
- Using `find` instead of `ls` to better handle non-alphanumeric filenames

Signed-off-by: Mpho Mphego <mpho112@gmail.com>

2018-12-25 16:55 UTC, jreback requested changes

2018-12-25 16:55 UTC, jreback commented on ci/check_cache.sh
> +    rm -rf "${CACHE_DIR}" || exit 1
remove these

2018-12-25 16:55 UTC, jreback commented on ci/circle/install_circle.sh
> +    rm -f pandas/__init__.pyc || true;
you don't need the error conditions here

2018-12-25 16:55 UTC, jreback commented on ci/code_checks.sh
> +    # Check if flake8 is installed.
you can do the check on flake8 w/o moving the code itself, eg. revert lines 62 and on.
if the command doesn't exist then need to print a message and immediately exit

2018-12-25 16:55 UTC, jreback commented on ci/code_checks.sh
> +        echo '  To install: $ pip install flake8'
we don't use pip to install things, rather its conda install

2018-12-25 16:55 UTC, jreback commented on ci/code_checks.sh
> +        MSG='Linting .c and .h' ; echo "${MSG}"
same comment as above

2018-12-25 16:55 UTC, jreback commented on ci/code_checks.sh
> +    if command -v pytest >/dev/null; then
same comment as above

2018-12-25 22:27 UTC, datapythonista requested changes
-1 on merging this in a single PR

I don't see the value of some of these changes, they seem somehow arbitrary. And we're likely to introduce bugs here.

I think it makes more sense to have each change in a separate PR, so we can discuss them properly.

-1 on checking if `flake8`, `cpplint`... the errors we have now are good enough, and I don't think the extra complexity is justified.

2019-01-06 11:30 UTC, datapythonista commented
@mmphego can you split this PR as requested, and fix the conflicts please?

2019-01-09 10:09 UTC, mmphego commented
> @mmphego can you split this PR as requested, and fix the conflicts please?

I will be on it, asap - have been on away from my computer. Thanks.

2019-01-11 13:24 UTC, closed without merging