BUG-24408 Series.dt does not maintain own copy of index
pandas-dev/pandas pull request #24426
Opened 2018-12-25 20:31 UTC by JustinZhengBC

- [X] closes #24408
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

Previously, the `dt` accessor maintains its own copy of the index, so in-place operations would cause the indexes to be out of sync. This PR changes the accessor so it just gets the index from its parent.

2018-12-25 23:25 UTC, jreback requested changes

2018-12-25 23:58 UTC, mroeschke commented
Could you double check that the other accessors, `str` and `cat`, uses the current index (and add a test as well)?

2018-12-26 01:28 UTC, jreback approved these changes

2018-12-26 02:09 UTC, JustinZhengBC commented
@jreback green

2018-12-26 02:14 UTC, merged

2018-12-26 02:14 UTC, jreback commented
thanks!