BUG: Pandas any() returning false with true values present (GH #23070)
pandas-dev/pandas pull request #24434
Opened 2018-12-26 15:01 UTC by makbigc

-  closes #23070
-  1 test added
-  passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
-  whatsnew entry

2018-12-27 00:23 UTC, jreback requested changes

2018-12-27 16:59 UTC, jreback requested changes

2018-12-27 16:59 UTC, jreback commented on doc/source/whatsnew/v0.24.0.rst
> +- Bug in :meth:`DataFrame.any` returns wrong value when the axis is one and the data is of datetime type (:issue:`23070`)
in double-backticks say ``axis=1`` and data type is datetimelike

2018-12-29 17:19 UTC, makbigc commented
The test_any_all is failed in python2. An error is raised in line 239.

https://github.com/pandas-dev/pandas/blob/70bc919316db6be6be8cce1a53dd54d34f25ff98/pandas/tests/frame/test_analytics.py#L231-L240
1. Reason why test_any_all is passed in python3, but failed in python2
The class NonzeroFail implements the `__nonzero__` method. In python2, `bool()` calls `__nonzero__` method which raises the error. In python3, bool calls `__bool__` and then `__len__`. If none of the above methods were implemented, `True` is returned. [https://docs.python.org/3/reference/datamodel.html](url)

2. Reason why test_any_all is failed in this PR 
`self` is given to data, instead of `self._get_bool_data`. `_get_bool_data` gets rid of the object block of `NonzeroFail`.

https://github.com/pandas-dev/pandas/blob/70bc919316db6be6be8cce1a53dd54d34f25ff98/pandas/core/frame.py#L7293-L7294

The test with `DataFrame` containing `NonzeroFail` was passed due to the bug we are fixing. So the `NonzeroFail` is removed from the test.

2018-12-30 18:41 UTC, jreback approved these changes

2018-12-30 18:43 UTC, merged

2018-12-30 18:43 UTC, jreback commented
thanks @makbigc