DOC: Adding offsets to API ref
pandas-dev/pandas pull request #24446
Opened 2018-12-26 22:51 UTC by datapythonista

Adding Date Offsets API documentation. Added in the same format as other sections. Detected what are properties and what are methods with the `callable` function. The order of the classes is the one already used. The order inside properties and methods is alphabetical.

@jreback In `timeseries.rst` we already have a table with the different offsets: https://pandas-docs.github.io/pandas-docs-travis/timeseries.html#dateoffset-objects Not sure what would you like to add more.

CC: @mroeschke @jbrockmendel

2018-12-26 22:56 UTC, mroeschke commented
Is it possible to give `Properties` and `Methods` a different (smaller) heading style than the offset class? It's a bit difficult to pick out the offset from those two headings.

2018-12-26 23:05 UTC, datapythonista commented
Totally agree, but I think the short answer is no.

I copied the format of: https://pandas-docs.github.io/pandas-docs-travis/api.html#scalars

IMO, what we should do is split the API page in several sections (see the sections in the "API Reference" block in https://pandas-dev.github.io/pandas-sphinx-theme/pr-datapythonista_base/, but possibly with all Index classes in the same section). Then we should have at least one extra level of title/subtitle..., and we'll be able to do it.

Will open an issue soon, and see if there is agreement.

2018-12-26 23:11 UTC, jreback commented
> @jreback In timeseries.rst we already have a table with the different offsets: https://pandas-docs.github.io/pandas-docs-travis/timeseries.html#dateoffset-objects Not sure what would you like to add more.

it didn’t have clickable links before

2018-12-26 23:15 UTC, datapythonista commented
ah, I see, thanks for clarifying. But that's somehow unrelated, the class pages already existed, it's just that they are not links.

I'll add those in a separate PR.

2018-12-26 23:56 UTC, datapythonista commented
Created #24448 for the links.

2018-12-27 00:05 UTC, jreback requested changes
can you auto-generate these?

2018-12-27 00:05 UTC, jreback commented on doc/source/api.rst
> +    DateOffset.isAnchored
I think we are removing / not-advertising ``isAnchored``

2018-12-27 00:05 UTC, jreback commented on doc/source/api.rst
> +    DateOffset.nanos
I think we consider .nanos private @jbrockmendel ?

2018-12-27 14:43 UTC, datapythonista commented
I "autogenerated" them, would you prefer to generate the content of `api.rst` dynamically? If we do it for date offsets, it probably makes sense to do it for everything.

Regarding the private methods, sphinx will warn (and eventually we'll make it fail for warnings). So it'd probably be a better option to just rename them to `_isAnchored` (or `_is_anchored`) and `_nanos`. Is there any reason to not do that?

Related to this PR, I created #24451 to split `api.rst` in multiple files.

2018-12-27 16:46 UTC, jreback approved these changes

2018-12-27 16:46 UTC, jreback commented
this is fine for now (and ok on the splitting).

2018-12-27 16:46 UTC, merged