BUG-19214 int categoricals are formatted as ints
pandas-dev/pandas pull request #24494
Opened 2018-12-30 08:21 UTC by JustinZhengBC

- [X] closes #19214
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

This PR alters the `ExtensionArrayFormatter` such that if it receives a categorical series with only integers and `NaN`, it will print the integers as integers instead of converting to floats.

```
>>> # previous behaviour
>>> pd.Series([1,2, np.nan], dtype="object").astype("category")
0    1.0
1    2.0
2    NaN
dtype: category
Categories (2, int64): [1, 2]
>>> # new behaviour
>>> pd.Series([1,2, np.nan], dtype="object").astype("category")
0      1
1      2
2    NaN
dtype: category
Categories (2, int64): [1, 2]
```

2018-12-30 19:36 UTC, jreback requested changes

2018-12-30 19:36 UTC, jreback commented on pandas/io/formats/format.py
> +
we have a CategoricalFormatter already, mod should be made there. Should be caught when formatting, not as a post-action.

2018-12-30 19:36 UTC, jreback commented on pandas/tests/arrays/categorical/test_repr.py
> +        assert ".0" not in repr(s)
assert the exact repr (similar to other tests)

2018-12-30 21:34 UTC, JustinZhengBC commented
@jreback I looked into it and the `CategoricalFormatter` is used for printing categoricals like this:
```
[1.0, 2.0, NaN]
Categories (2, int64): [1, 2]
```
instead of like a series. The PR now modifies the `CategoricalFormatter` in addition to the `ExtensionArrayFormatter`.

2018-12-30 21:46 UTC, jreback requested changes
So the fix is in ``.get_values()`` do this

```
n [28]: c.categories.astype(object).take(c.codes, fill_value=np.nan)
Out[28]: Index([1, 2, nan], dtype='object')
```

if -1 in c.codes and  is_integer_dtype(c.categories)

2018-12-30 21:46 UTC, jreback commented on pandas/io/formats/format.py
> +        if is_integer_dtype(self.categorical.dtype.categories):
ok again the issue is that this is not how we need to do this.

2018-12-30 23:08 UTC, jreback commented
@TomAugspurger any objections here?

2018-12-30 23:09 UTC, jreback requested changes

2018-12-30 23:09 UTC, jreback commented on doc/source/whatsnew/v0.24.0.rst
> +- Bug in :meth:`Categorical.get_values` where integers would be coerced to floats if ``NaN`` values were present (:issue:`19214`)
can you make this a user facing message; mention both the formatting fix & the concat changes

2018-12-30 23:09 UTC, jreback commented on pandas/core/arrays/categorical.py
> +        elif -1 in self._codes and is_integer_dtype(self.categories):
reverse this check (check for integer first)

2018-12-31 23:28 UTC, jreback requested changes
the warnings are not needed

2018-12-31 23:52 UTC, JustinZhengBC commented on doc/source/whatsnew/v0.24.0.rst
> +- Bug in :meth:`Categorical.get_values` where integers would be formatted as floats if ``NaN`` values were present (:issue:`19214`)
@jreback I'm a bit confused as to what a user-facing note is. Is it a specific section somewhere? Or does it mean to phrase the note differently, like "bug in the Categorical repr"?

2018-12-31 23:54 UTC, jreback commented on doc/source/whatsnew/v0.24.0.rst
> +- Bug in :meth:`Categorical.get_values` where integers would be formatted as floats if ``NaN`` values were present (:issue:`19214`)
sorry. what I mean is a user would want to know that the string repr of Series (or categorical dtype) and Categoricals for integer categories will now not be coerced to float. Its maybe worth making this a sub-section (e.g. show previous / new behavior). you can just in-line it here.

2019-01-01 14:17 UTC, TomAugspurger commented on doc/source/whatsnew/v0.24.0.rst
> +- Calling :func:`pandas.concat` on a ``Categorical`` of ints with NA values now causes them to be processed as objects (formerly coerced to floats) (:issue:`19214`)
This only applies when concating a categorical with a different dtype, right? If I concat two integer cats with the same dtype, it’s still categoricalmright?

2019-01-01 14:18 UTC, TomAugspurger commented on pandas/tests/arrays/categorical/test_repr.py
> +        s_exp = """0      1\n1      2\n2    NaN\ndtype: category\nCategories (2, int64): [1, 2]"""  # noqa
You can use parenthesis to wrap this line.

2019-01-01 14:20 UTC, TomAugspurger reviewed
To me, the change in dtype for concat is the larger change. Just from the release notes it looks like the formatting change is larger.

2019-01-01 16:18 UTC, jreback commented
> To me, the change in dtype for concat is the larger change. Just from the release notes it looks like the formatting change is larger.

I don't think this is that big of a deal, do you want a sub-section for this?

2019-01-03 00:57 UTC, jreback commented
@TomAugspurger you think need to highlite the change more?

2019-01-03 12:20 UTC, TomAugspurger commented
The formatting change seems fine. I'm more concerned about the breaking
change to get_values
with no deprecation warning. Is there any way to deprecate the behavior, or
would that require to
many internal changes so that the warning doesn't show up when printing the
categorical?

On Wed, Jan 2, 2019 at 6:57 PM Jeff Reback <notifications@github.com> wrote:

> @TomAugspurger <https://github.com/TomAugspurger> you think need to
> highlite the change more?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/24494#issuecomment-451031339>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABQHIvMndIhl1YZHo1Iye0ANfYxd0P88ks5u_VV8gaJpZM4Zk2sS>
> .
>

2019-01-04 12:20 UTC, jreback commented
> I'm more concerned about the breaking
change to get_values
with no deprecation warning. Is there any way to deprecate the behavior, or
would that require to

This is a very small case to be honest (and our current behavior for concatting any non-same types, so this is a bug IMHO). 

@JustinZhengBC can you make a small sub-section about the changes in Categorical int-like concat, showing previous and current behavior. I think that is fine.

2019-01-05 15:12 UTC, jreback approved these changes

2019-01-05 15:12 UTC, jreback commented
@TomAugspurger better?

2019-01-05 20:01 UTC, TomAugspurger reviewed
Just doc comments.

2019-01-05 20:01 UTC, TomAugspurger commented on doc/source/whatsnew/v0.24.0.rst
> +Calling :func:`pandas.concat` on a ``Categorical`` of ints with NA values now
Specific that this only applies when concatenating a Categorical with something of a different dtype.

2019-01-05 20:01 UTC, TomAugspurger commented on doc/source/whatsnew/v0.24.0.rst
> +    In [3]: c = pd.Series([0, 1, np.nan], dtype="object").astype("category")
Why not `c = pd.Series([0, 1, np.nan], dtype="category")`?

2019-01-05 21:21 UTC, jreback commented
@TomAugspurger ?

2019-01-05 21:36 UTC, TomAugspurger approved these changes

2019-01-05 22:15 UTC, merged

2019-01-05 22:15 UTC, jreback commented
thanks @JustinZhengBC keep em coming!