exclude autogenerated c/cpp files from 'trailing whitespace' checks
pandas-dev/pandas pull request #24549
Opened 2019-01-02 13:39 UTC by saurav2608

- [x] closes #24526 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-01-02 14:42 UTC, jreback commented
@saurav2608 no, just leave this for @datapythonista to look. The CI failure is unrelated.

2019-01-12 19:07 UTC, datapythonista commented
There are C and C++ files in the pandas codebase, and I'd like to avoid tailing spaces on them too. Only the generated ones could be excluded.
```
./pandas/io/msgpack/_unpacker.cpp
./pandas/io/msgpack/_packer.cpp
./pandas/_libs/window.cpp
./pandas/util/move.c
./pandas/_libs/src/parser/io.c
./pandas/_libs/src/parser/tokenizer.c
./pandas/_libs/src/ujson/python/ujson.c
./pandas/_libs/src/ujson/python/objToJSON.c
./pandas/_libs/src/ujson/python/JSONtoObj.c
./pandas/_libs/src/ujson/lib/ultrajsondec.c
./pandas/_libs/src/ujson/lib/ultrajsonenc.c
./pandas/_libs/tslibs/src/datetime/np_datetime.c
./pandas/_libs/tslibs/src/datetime/np_datetime_strings.c
```

2019-02-05 05:00 UTC, WillAyd commented
@saurav2608 can you address comments and merge master?

2019-02-05 10:56 UTC, datapythonista approved these changes
This makes sense to me, not ideal to exclude all the C/C++ from the tailing spaces check (may confuse a human reader), but I think we should validate everything we want this way, and it's probably the simplest approach.

I'd just do couple of things before merging:
- Adding a comment in the tailing spaces check (where the `--exclude` is) explaining that C/C++ files will be checked with the linting
- Add in you local environment (i.e. don't commit) tailing whitespaces to some file in `/pandas/io/msgpack` and see if the script (so the CI) fails in that case. I think so, but just to double check

Thanks for the fixes @saurav2608

2019-02-05 13:04 UTC, saurav2608 commented
> * Add in you local environment (i.e. don't commit) tailing whitespaces to some file in `/pandas/io/msgpack` and see if the script (so the CI) fails in that case. I think so, but just to double check
> 
@datapythonista 
The cpp files are autogenerated - `./pandas/io/msgpack/_unpacker.cpp` Can you confirm that? The linter checks only .c and .h files. I can add cpp too if cpp files here are not autogenerated.

2019-02-05 14:41 UTC, datapythonista commented
You're right. I fail to see what we are doing here then. This PR is to exclude the autogenerated .cpp files from the tailing whitespace check, and we're then fully linting them?

2019-02-05 17:00 UTC, saurav2608 commented
> You're right. I fail to see what we are doing here then. This PR is to exclude the autogenerated .cpp files from the tailing whitespace check, and we're then fully linting them?

I have pushed the changes. The .c and .h files are fully Linted. I check and trailing whitespace does show up as an error.

2019-02-06 03:29 UTC, jreback requested changes

2019-02-06 03:36 UTC, saurav2608 commented on ci/code_checks.sh
> +    cpplint --quiet --extensions=c,h --headers=h --recursive --filter=-readability/casting,-runtime/int,-build/include_subdir pandas/_libs/src/*.h pandas/_libs/src/parser pandas/_libs/ujson pandas/_l
my bad.

2019-02-07 17:41 UTC, saurav2608 commented
@jreback can you please merge this?

2019-02-07 18:32 UTC, jreback commented
i will look next day or 2

2019-02-08 02:51 UTC, jreback approved these changes

2019-02-08 02:51 UTC, merged

2019-02-08 02:51 UTC, jreback commented
thanks @saurav2608