Support hard-masked numpy arrays
pandas-dev/pandas pull request #24581
Opened 2019-01-03 02:42 UTC by karldw

- [x] closes #24574
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

For the whatsnew entry, is this reasonable?
```rst
- :func:`DataFrame` and :func:`Series` now properly handle 
numpy masked arrays with hardened masks. Previously, constructing 
a DataFrame or Series from a masked array with a hard mask would 
create a pandas object containing the underlying value, rather than the
expected NaN. (:issue:`24574`)
```

2019-01-03 02:42 UTC, pep8speaks commented
Hello @karldw! Thanks for submitting the PR.

 - In the file [`pandas/core/frame.py`](https://github.com/pandas-dev/pandas/blob/b20389d19a0461d1fdf006204f0b869ada617e3b/pandas/core/frame.py), following are the PEP8 issues :

> [Line 403:39](https://github.com/pandas-dev/pandas/blob/b20389d19a0461d1fdf006204f0b869ada617e3b/pandas/core/frame.py#L403): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment

 - In the file [`pandas/core/internals/construction.py`](https://github.com/pandas-dev/pandas/blob/b20389d19a0461d1fdf006204f0b869ada617e3b/pandas/core/internals/construction.py), following are the PEP8 issues :

> [Line 550:31](https://github.com/pandas-dev/pandas/blob/b20389d19a0461d1fdf006204f0b869ada617e3b/pandas/core/internals/construction.py#L550): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment

 - In the file [`pandas/tests/frame/test_constructors.py`](https://github.com/pandas-dev/pandas/blob/b20389d19a0461d1fdf006204f0b869ada617e3b/pandas/tests/frame/test_constructors.py), following are the PEP8 issues :

> [Line 767:30](https://github.com/pandas-dev/pandas/blob/b20389d19a0461d1fdf006204f0b869ada617e3b/pandas/tests/frame/test_constructors.py#L767): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2019-01-03 03:01 UTC, jreback requested changes
whatsnew looks fine

2019-01-03 03:01 UTC, jreback commented on pandas/tests/frame/test_constructors.py
> +        frame = DataFrame(mat_hard, columns=['A', 'B', 'C'], index=[1, 2])
use the format
```
result = 
expected = pd.DataFrame(....)
tm.assert_frame_equal(result, expected)
```
construct the expected exactly

2019-01-03 03:01 UTC, jreback commented on pandas/tests/series/test_constructors.py
> +        data_hard = ma.copy(data).harden_mask()
add a separate test

2019-01-03 03:57 UTC, jreback commented
https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=6404 some lint issues as well

2019-01-03 16:06 UTC, jreback approved these changes

2019-01-03 16:06 UTC, jreback commented
lgtm. ping nogreen.

2019-01-03 16:32 UTC, jreback commented
some lint issues

2019-01-04 00:24 UTC, merged

2019-01-04 00:39 UTC, karldw commented
Thank you!