DOC: Bump fastparquet version
pandas-dev/pandas pull request #24590
Opened 2019-01-03 13:17 UTC by TomAugspurger

Should we just bump the min version to 0.2.1? It's quite new, but I think reading datetime data is somewhat common :) It'll save us bug reports.

2019-01-03 13:18 UTC, TomAugspurger commented
cc @jorisvandenbossche this fixes the doc error you were seeing.

2019-01-03 13:27 UTC, jorisvandenbossche approved these changes
Looks good, let's wait on the doc build to check if it actually worked

2019-01-03 13:52 UTC, jreback requested changes
is this *only* for docs? may have to update the parquet doc section as well.

2019-01-03 13:57 UTC, jorisvandenbossche commented
> is this only for docs? may have to update the parquet doc section as well.

For now, this PR is only about the doc build. But if the suggestion of Tom is followed to bump the fastparquet version, we should also update the docs (although, if we decide to not nump the minimum version, we should maybe still mention that for datetime data, the latest version is required)

2019-01-03 17:16 UTC, TomAugspurger commented
I've made the changes to bump the min version to 0.2.1 locally, but I think there's an issue with the conda-forge package. Going to fix that before pushing again.

2019-01-03 17:22 UTC, jreback commented
why are you bumping for parquet reading? (we had already bumped for this release I think).

2019-01-03 17:42 UTC, jreback commented
its fine. we don't usually bump up this fast, but ok.

2019-01-03 17:42 UTC, jreback commented
but would need to change the tests & docs

2019-01-03 17:43 UTC, TomAugspurger commented
https://github.com/pandas-dev/pandas/pull/24590#issuecomment-451216152

but fixing the CF package first.

2019-01-03 17:44 UTC, jreback commented
> but fixing the CF package first.

what is this?

2019-01-03 17:47 UTC, TomAugspurger commented
CF=conda-forge. There was an issue with the 0.2.1 build:
https://github.com/conda-forge/fastparquet-feedstock/pull/21

On Thu, Jan 3, 2019 at 11:45 AM Jeff Reback <notifications@github.com>
wrote:

> but fixing the CF package first.
>
> what is this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/24590#issuecomment-451221152>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABQHInnlsa-_-fi0B86YQOiGGd-c3vAQks5u_kGhgaJpZM4ZoEzZ>
> .
>

2019-01-03 17:49 UTC, jreback commented
ahh ok

2019-01-03 17:49 UTC, jreback approved these changes

2019-01-03 17:49 UTC, jreback commented
ok merge ok then

2019-01-03 22:09 UTC, jreback commented
merge?

2019-01-03 22:21 UTC, jorisvandenbossche commented
No , the problem is not yet fixed (see the doc build log on travis)

Possibly due the conda-forge package problem? (@TomAugspurger the conda list output indicates it installed fastparquet 0.2.1 from conda-forge, but then the error is still there and the `pd.sho_versions()` gives fastparquet 0.1.6 ...)

2019-01-03 22:23 UTC, jreback commented
ok cool.

2019-01-04 13:11 UTC, TomAugspurger commented
The fastparquet 0.2.1 conda-forge package was accidentally packaging 0.1.6 (but labeling it as 0.2.1), so the error persisted.

The linux builds for a corrected fastparquet are just finishing now. I'll clean up my version bump and push.

2019-01-04 13:58 UTC, jreback requested changes

2019-01-04 13:58 UTC, jreback commented on ci/deps/azure-macos-35.yaml
> -  - fastparquet
can you update environment.yaml as well

2019-01-04 14:04 UTC, jorisvandenbossche commented
Some travis builds are failing (didn't check why), but just checked that the doc build is now working (the error is gone)

2019-01-04 14:05 UTC, TomAugspurger commented
The travis build is failing because not all the conda packages are done building. Some are still pulling in the (bad) 0.2.1 fastparquet.

I'll let those finish up before pushing again (with the dev env update).

2019-01-04 20:33 UTC, TomAugspurger commented
FYI, conda-forge stopped building packages for Python 3.5 on MacOS, so I've removed fastparquet from that env.

2019-01-05 14:16 UTC, jreback approved these changes

2019-01-05 14:50 UTC, merged

2019-01-05 14:50 UTC, jreback commented
thanks!