DOC: Removed duplicate doc line
pandas-dev/pandas pull request #24668
Opened 2019-01-08 01:01 UTC by palewire

This line of documentation is already included in the parent shared docs. So the line appears twice. See the screenshot below from [the Dataframe.aggregate page](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.aggregate.html)

![screenshot from 2019-01-07 17-00-12](https://user-images.githubusercontent.com/9993/50803035-ca04fa00-129d-11e9-8078-a0a3d9a55400.png)

2019-01-08 16:40 UTC, WillAyd requested changes
See comment above

2019-01-08 18:57 UTC, datapythonista commented
@palewire do you mind running `./scripts/validate_docstrings.py pandas.DataFrame.aggregate` and copy the full output here in a comment? That will make it easier to review.

I'm not sure your fix is correct, as the latest version is different from your screenshot and the link you referred to. Seems like there is a problem with the sections, and those notes are now rendered in the returns section.

You may also want to run `./doc/make.py html --single=pandas.DataFrame.aggregate` to see how your changes will look like.

2019-01-26 13:32 UTC, rotuna commented
@WillAyd @palewire @datapythonista  

I've tried to fix the issues. The PR is here #24948. Please let me know if anything is amiss.

2019-01-26 15:14 UTC, jreback commented
close this in favor of #24948, a more comprehensive fix.

2019-01-26 15:14 UTC, closed without merging