[WIP]: API ExtensionDtype for DTA & TDA
pandas-dev/pandas pull request #24674
Opened 2019-01-08 15:49 UTC by TomAugspurger

Closes https://github.com/pandas-dev/pandas/issues/24662

TODO:

- [ ] Dedicated tests for new is_<foo> types
- [ ] Run the extension dtype tests for new dtypes
- [ ] (maybe?) see if the new EA tests pass for the new arrays. Tricky, since they aren't allowed internally. g
- [ ] failing dtype validation tests

This is going to fail. Going offline for a bit, but putting this up right now.

I'm going to clean up the changes in `internals` and the series constructor.

2019-01-08 19:43 UTC, TomAugspurger commented
Still a WIP, but probably not going to have time to update this any further through the end of the week.

2019-01-08 19:49 UTC, jreback requested changes

2019-01-08 19:49 UTC, jreback commented on pandas/core/dtypes/dtypes.py
> +    def construct_from_string(cls, string):
I think you need to move this to the sub-class as DatetimeDtype would actually accept this but raise on a construction error (as you can't pass a tz). I would maybe instead just have a unified constructor that accepts ``tz=None`` for naive.

2019-01-09 13:18 UTC, jorisvandenbossche commented
> I would maybe instead just have a unified constructor that accepts tz=None for naive.

@jreback do you also mean just having a single class internally? `DatetimeDtype(tz=None)` is the naive one and `DatetimeDtype(tz=tz)` is the aware one (and `DatetimeTzDtype` can be kept as an alias for now for backwards compatibility) 

I didn't really think about any possible technical implications of that, but it seems logical to me to do that, since we also have a single DatetimeArray.

2019-01-09 13:22 UTC, TomAugspurger commented
Sorry I put this up in haste and didn't explain things well. Initially, I tried that, but ran into some difficulties. It turns out that having `pandas_dtype("M8[ns]")` return a non NumPy dtype breaks a lot of stuff. So I split them apart, and don't register the `DatetimeDtype`.

I'm not sure if it's possible to both

1. Have a DatetimeDtype that registers datetime64[ns, tz], but not datetime64[ns]
2. Have construct_from_string always work correctly

but I can try (later, not today).

2019-01-09 13:57 UTC, jreback commented
yeah I think this is a great idea @TomAugspurger but also possibly to involve changing some tricky code; would prefer to push this to 0.25

2019-01-14 17:21 UTC, TomAugspurger commented
The main downside with pushing to 0.25 is it'll be an API breaking change for `DatetimeArray.dtype`, and `TimedeltaArray.dtype` with no path for deprecation.

---

just pushed an update, but still a WIP.

2019-01-16 15:17 UTC, TomAugspurger commented
Somewhat awkward API corner: what's the expected types for

1. `DatetimeArray.astype("M8[ns]")`
2. `DatetimeArray.astype(np.dtype("M8[ns]"))`
3. `DatetimeArray.astype(pd.DatetimeDtype())`

Previously, we'd use `.astype('M8[ns]')` to convert to an ndarray. But now that we have a dtype roughly equivalent to `M8[ns]`, should we keep doing that?

Another one, what should we do about `pd.DatetimeDtype() == "M8[ns]"` or `== np.dtpye("M8[ns]")`.

NumPy doesn't make this easy, since they would raise if the operands were flipped, rather than returning NotImplemented.

2019-01-17 15:47 UTC, jorisvandenbossche commented
For the expected types, I also have been wondering about this in general. So eg also for `DTA.astype("int64")`. 
Because we now have `PandasArray` and `PandasDtype`, so we could also return those? Similarly as `pd.array(DTA, dtype='int64')` does.

2019-01-17 16:12 UTC, TomAugspurger commented
Yeah, it's not obvious to me what's best here.

On the one hand, you could say that `.astype(np.dtype(.))` should always return an ndarray.

On the other hand, is it weird for `.astype(np.dtype("int64"))` to not match `.astype("int64")`? I suppose we'll need to sort all this out.

I'm really not sure what to do here :/

2019-01-20 23:05 UTC, h-vetinari commented
> @TomAugspurger: Yeah, it's not obvious to me what's best here.
On the one hand, you could say that `.astype(np.dtype(.))` should always return an ndarray.
On the other hand, is it weird for `.astype(np.dtype("int64"))` to not match `.astype("int64")`? I suppose we'll need to sort all this out.
I'm really not sure what to do here :/

How about `.astype` and `pd.array` always returning `PandasDType` (yes, even for an `np.dtype`)? If the user really wants an `ndarray`, they can then call `to_numpy`. That would in many ways be more consistent - and could later be extended to the point that the *only* way to get an `ndarray` from pandas is to call `to_numpy`.

2019-07-28 04:35 UTC, jbrockmendel commented
This has been inactive for a while.  Still a goal?

2019-07-29 15:21 UTC, TomAugspurger commented
I'm not sure. The API changes are tricky to get right.

Regardless, I don't think things will be done on this branch. I'll post an update on the issue.

2019-07-29 15:21 UTC, closed without merging