ModuleNotFoundError in  in_interactive_session
pandas-dev/pandas pull request #24714
Opened 2019-01-10 21:26 UTC by dickreuter

- [x] closes #24690
- [na] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2019-01-10 22:25 UTC, TomAugspurger reviewed
I'm still iffy on this. It's not clear to me what pylint is doing, and I'd prefer not to add workarounds if it's something that should be fixed upstream.

2019-01-11 12:54 UTC, jreback requested changes
just remove the note

2019-01-11 12:54 UTC, jreback commented on doc/source/whatsnew/v0.24.0.rst
> +- Bug in :func:`in_interactive_session` that caused it to raise ``ModuleNotFoundError`` (:issue:`24690`)
yeah I don't think we even need this note

2019-01-12 19:58 UTC, dickreuter commented
@rejack, remove the note

2019-01-13 19:17 UTC, jreback approved these changes

2019-01-13 19:17 UTC, merged

2019-01-13 19:17 UTC, jreback commented
thanks!

2019-01-13 19:30 UTC, dickreuter commented
Not sure I understand. The pylint issue is affecting both py2 and py3 I think. Or why do you think there’s a difference?

> On 13 Jan 2019, at 19:23, Tom Augspurger <notifications@github.com> wrote:
> 
> Hmm I still wasn't sure we should merge this. Can we check with upstream to
> see if their workaround can be applied for py2 only?
> 
> Or can we add a TODO to remove this when we drop Python2?
> 
> On Sun, Jan 13, 2019 at 1:17 PM Jeff Reback <notifications@github.com>
> wrote:
> 
> > thanks!
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/pandas-dev/pandas/pull/24714#issuecomment-453857330>,
> > or mute the thread
> > <https://github.com/notifications/unsubscribe-auth/ABQHItXs_RGnK_SmfJFGyA1DImwWHaWrks5vC4ZWgaJpZM4Z6WTF>
> > .
> >
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-01-13 19:43 UTC, TomAugspurger commented
From the linked bug report in
https://github.com/PyCQA/pylint/blob/master/pylint/lint.py#L153 to
https://bugs.python.org/issue10845,
it seems to be fixed in python 3.2. So it's possible that pylint could
apply that mock only for Python <=2.7

On Sun, Jan 13, 2019 at 1:30 PM Nicolas Dickreuter <notifications@github.com>
wrote:

> Not sure I understand. The pylint issue is affecting both py2 and py3 I
> think. Or why do you think there’s a difference?
>
> > On 13 Jan 2019, at 19:23, Tom Augspurger <notifications@github.com>
> wrote:
> >
> > Hmm I still wasn't sure we should merge this. Can we check with upstream
> to
> > see if their workaround can be applied for py2 only?
> >
> > Or can we add a TODO to remove this when we drop Python2?
> >
> > On Sun, Jan 13, 2019 at 1:17 PM Jeff Reback <notifications@github.com>
> > wrote:
> >
> > > thanks!
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly, view it on GitHub
> > > <
> https://github.com/pandas-dev/pandas/pull/24714#issuecomment-453857330>,
> > > or mute the thread
> > > <
> https://github.com/notifications/unsubscribe-auth/ABQHItXs_RGnK_SmfJFGyA1DImwWHaWrks5vC4ZWgaJpZM4Z6WTF
> >
> > > .
> > >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/24714#issuecomment-453858244>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABQHIg2btBiGKv--kIUFnYfsh6Uie6Hxks5vC4lJgaJpZM4Z6WTF>
> .
>

2019-01-13 20:59 UTC, dickreuter commented
I see. I have submitted a PR for Pylint as well to remove the mock, but
their release cycle is very slow.

On Sun, 13 Jan 2019 at 19:44, Tom Augspurger <notifications@github.com>
wrote:

> From the linked bug report in
> https://github.com/PyCQA/pylint/blob/master/pylint/lint.py#L153 to
> https://bugs.python.org/issue10845,
> it seems to be fixed in python 3.2. So it's possible that pylint could
> apply that mock only for Python <=2.7
>
> On Sun, Jan 13, 2019 at 1:30 PM Nicolas Dickreuter <
> notifications@github.com>
> wrote:
>
> > Not sure I understand. The pylint issue is affecting both py2 and py3 I
> > think. Or why do you think there’s a difference?
> >
> > > On 13 Jan 2019, at 19:23, Tom Augspurger <notifications@github.com>
> > wrote:
> > >
> > > Hmm I still wasn't sure we should merge this. Can we check with
> upstream
> > to
> > > see if their workaround can be applied for py2 only?
> > >
> > > Or can we add a TODO to remove this when we drop Python2?
> > >
> > > On Sun, Jan 13, 2019 at 1:17 PM Jeff Reback <notifications@github.com>
> > > wrote:
> > >
> > > > thanks!
> > > >
> > > > —
> > > > You are receiving this because you commented.
> > > > Reply to this email directly, view it on GitHub
> > > > <
> > https://github.com/pandas-dev/pandas/pull/24714#issuecomment-453857330>,
> > > > or mute the thread
> > > > <
> >
> https://github.com/notifications/unsubscribe-auth/ABQHItXs_RGnK_SmfJFGyA1DImwWHaWrks5vC4ZWgaJpZM4Z6WTF
> > >
> > > > .
> > > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub, or mute the thread.
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/pandas-dev/pandas/pull/24714#issuecomment-453858244
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe-auth/ABQHIg2btBiGKv--kIUFnYfsh6Uie6Hxks5vC4lJgaJpZM4Z6WTF
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/24714#issuecomment-453859294>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABMrfjPrSFnwBJeIfI03VsFGSQp-tno4ks5vC4yOgaJpZM4Z6WTF>
> .
>