PERF: 3x speedup in Series of dicts with datetime keys by not having error message scale with input
pandas-dev/pandas pull request #24743
Opened 2019-01-12 18:19 UTC by qwhelan

Surprisingly, the majority of the time spent in constructing a `Series` from a dict with `datetime`-like keys is spent formatting the keys into strings for an error message that gets suppressed.

As there's a test ensuring the string case makes it into the error message, we preserve the behavior there. In non-string cases, we mirror how the other `Dtypes` handle this case and do not include the input.
```
$ asv compare v0.24.0rc1 HEAD -s
       before           after         ratio
     [fdc4db25]       [5c82eab5]
     <v0.24.0rc1^0>       <series_dict_speedup>
-      1.14±0.02s          303±4ms     0.27  series_methods.SeriesConstructor.time_constructor('dict') 
```

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-01-12 18:25 UTC, jreback requested changes

2019-01-12 18:36 UTC, qwhelan commented on pandas/core/dtypes/dtypes.py
> +        else:
It's primarily caught by `pandas.core.dtypes.base._DtypeOpsMixin.is_dtype()`, which doesn't care about error message at all:
```
        try:
            return cls.construct_from_string(dtype) is not None
        except TypeError:
            return False
```
I'll check for direct calls that might be sensitive to the error message contents.

2019-01-13 00:21 UTC, qwhelan commented on pandas/core/dtypes/dtypes.py
> +        else:
I'm not seeing any calls reliant on the specific error message, so should be safe to change.

2019-01-13 00:35 UTC, jreback requested changes
can u add some tests that hit this (and the original)

2019-01-13 00:55 UTC, pep8speaks commented
Hello @qwhelan! Thanks for updating the PR.



 - In the file [`pandas/tests/dtypes/test_dtypes.py`](https://github.com/pandas-dev/pandas/blob/b0b50069c8bdf560757080bea5593f4c35305a05/pandas/tests/dtypes/test_dtypes.py), following are the PEP8 issues :

> [Line 235:80](https://github.com/pandas-dev/pandas/blob/b0b50069c8bdf560757080bea5593f4c35305a05/pandas/tests/dtypes/test_dtypes.py#L235): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)

2019-01-13 00:58 UTC, qwhelan commented
@jreback Done - original already had a test.

2019-01-13 18:54 UTC, jreback approved these changes

2019-01-13 18:54 UTC, merged

2019-01-13 18:54 UTC, jreback commented
thanks @qwhelan