Split test_excel.py (#24472)
pandas-dev/pandas pull request #24749
Opened 2019-01-13 11:25 UTC by stevenbw

Split tests/io/test_excel.py into two files, base.py and xlrd.py located in tests/io/excel/. The previous file was very large and a logical split has been applied to separate the `xlrd` tests.

- [ ] closes #24472 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-01-13 14:47 UTC, simonjayhawkins commented
@stevenbw The files will need to be named test_base.py and test_xlrd.py

2019-01-13 17:33 UTC, simonjayhawkins commented on pandas/tests/io/excel/test_base.py
> -    def test_usecols_int(self, ext):
you'll probably just want to split by complete classes in this PR and leave refactoring the classes to a follow-on PR.

2019-01-13 17:33 UTC, simonjayhawkins commented on pandas/tests/io/excel/test_xlrd.py
> +def ignore_xlrd_time_clock_warning():
any code required by both `test_base.py` and `test_xlrd.py` should probably be in `test_base.py`

2019-01-13 18:19 UTC, simonjayhawkins commented on pandas/tests/io/excel/test_xlrd.py
> +    @pytest.fixture(autouse=True, params=['xlrd'])
code duplicated from test_base

2019-01-13 18:20 UTC, simonjayhawkins commented on pandas/tests/io/excel/test_base.py
> +    @pytest.fixture(autouse=True, params=[None])
maybe a better name for `test_base` would be `test_common` or `test_all_engines`. this split is creating too much code duplication. maybe a split on reader/writer tests first before splitting out xlrd

2019-01-13 20:43 UTC, WillAyd commented
Agreed high level with @simonjayhawkins think there are just too many things moved to `test_xlrd`. If anything the entire `SharedItems` class you have can remain in the base file.

Did this yield the same number of tests before and after?

2019-01-13 21:19 UTC, jreback requested changes
so before this is actually split; it needs to be fixturized a bit more I think. not really sure the best way of doing this, but if you are just moving files, then that can be in a single PR. We don't want to mix moving things with changing things as its very hard to tell what is going on. So first move w/o any changes, then new PR' to change.

2019-01-14 20:32 UTC, stevenbw commented
Thanks for the support @simonjayhawkins, @WillAyd, @jreback :). I have taken on board your comments and attempted to simply split the file without separating classes or duplicating code. However, due to classes relying on previous classes, for example `TestXlrdReader`, which could belong to `test_xlrd.py` requires `ReadingTestsBase`,  which belongs to `test_all_engines.py`, there is only a small amount of code which can be moved. Other than `TestXlrdReader` there is only `ignore_xlrd_time_clock_warning` which could be in a separate file but it is used several times in `ReadingTestsBase`, it could be imported but doesn't seem to be of much benefit.

Unless I am missing something, it seems the ideal solution would be to rewrite the classes so they can be decoupled. I appreciate this would be a big change though.

2019-01-14 21:45 UTC, simonjayhawkins commented
@stevenbw the biggest classes by far are `ReadingTestsBase` and `TestExcelWriter`. i think these would need to be in separate files in order to make an impact on reducing the test file size. could the classes be grouped for this to work?

2019-01-15 17:16 UTC, stevenbw commented
@simonjayhawkins Yes they could. They both have a fundamental dependency on `SharedItems` but one option could be to import this class, then have one file `test_reader.py` for `ReadingTestsBase` and `TestXlrdReder`. The other file could contain all other classes and be called `test_writer.py`.

2019-02-12 05:35 UTC, WillAyd commented
Can you merge master here? Also we just refactored the excel code in #25153 so you may be able to mimic that set up on the test side

2019-02-13 20:39 UTC, stevenbw commented
Yes I will take a look, should be able to mimic what you have done.

2019-03-09 20:09 UTC, WillAyd commented
@stevenbw I think this is a duplicate of #25334 but if that's not the case let me know.

Generally should just keep pushing updates to the same PR rather than opening a new one

2019-03-09 20:09 UTC, closed without merging