BUG-16807-1 SparseFrame fills with default_fill_value if data is None
pandas-dev/pandas pull request #24842
Opened 2019-01-19 22:30 UTC by JustinZhengBC

- [ ] closes #16807
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

Previously, the constructor for SparseFrame would default to `np.nan` if the data parameter was `None`, even if a `default_fill_value` is specified. This PR fixes this.

2019-01-20 02:53 UTC, gfyoung approved these changes
cc @jreback

2019-01-20 16:09 UTC, jreback commented
there are a number of issues in the OP, are these all tested?

2019-01-22 06:30 UTC, JustinZhengBC commented
@jreback I added tests for issues 2-3. The last one I think isn't a storage issue, but a formatting one. Sometimes, integers in sparse data structures can be printed as floats if there are `NaN` values involved. Can it be fixed in this PR or should it be considered a separate issue?
```
>>> a=pd.SparseDataFrame(coo_matrix(np.arange(2).reshape(2,1),dtype=np.int64))
>>> a
     0
0  NaN
1  1.0
>>> a[0][1]
1
```

2019-02-28 00:19 UTC, WillAyd approved these changes
lgtm - can you merge master and ping on green?

2019-02-28 00:19 UTC, WillAyd requested changes
Whoops sorry one comment on whatsnew

2019-02-28 00:19 UTC, WillAyd commented on doc/source/whatsnew/v0.24.0.rst
> +- Bug in :class:`SparseFrame` constructor where passing ``None`` as the data would cause ``default_fill_value`` to be ignored (:issue:`16807`)
Move to 0.25

2019-03-03 02:48 UTC, jreback requested changes
looks good. merge master; ping on green.

2019-03-03 02:48 UTC, jreback commented on doc/source/whatsnew/v0.24.2.rst
> +- Bug in :class:`SparseFrame` constructor where passing ``None`` as the data would cause ``default_fill_value`` to be ignored (:issue:`16807`)
can you move to 0.25

2019-03-03 03:12 UTC, jreback approved these changes

2019-03-03 03:12 UTC, jreback commented
lgtm. ping on green.

2019-03-03 04:34 UTC, JustinZhengBC commented
@jreback green

2019-03-03 04:46 UTC, merged

2019-03-03 04:46 UTC, gfyoung commented
Thanks @JustinZhengBC !