BUG : ValueError in case on NaN value in groupby columns
pandas-dev/pandas pull request #24850
Opened 2019-01-20 21:14 UTC by cgangwar11

Fixes GH24740

- [x] closes #24740 
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

**Before**
```python
In [5]: ds.groupby("b").groups                                                                                   
Out[5]: {'b': Int64Index([1], dtype='int64'), 'c': Int64Index([2], dtype='int64')}
In [6]: ds.groupby("b", observed=True).groups                                                                    
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-d76af2ea5948> in <module>
----> 1 ds.groupby("b", observed=True).groups

~/Softwares/pandas/pandas/core/groupby/groupby.py in groups(self)
    388         """
    389         self._assure_grouper()
--> 390         return self.grouper.groups
    391 

```
**After**
```python
In [5]: ds.groupby('b',observed=True).groups                                                                     
Out[5]: {'b': Int64Index([1], dtype='int64'), 'c': Int64Index([2], dtype='int64')}

```

**Better Example**
```python
In [6]:  df = pd.DataFrame({'cat': pd.Categorical(['a', 'c', 'a'], 
   ...:                        categories=['a', 'b', 'd', 'e', 'f']), 
   ...:                        'vals': [1, 2, 3]})                                                               

In [7]: df                                                                                                       
Out[7]: 
   cat  vals
0    a     1
1  NaN     2
2    a     3

In [8]: df.groupby('cat').groups                                                                                 
Out[8]: 
{'a': Int64Index([0, 2], dtype='int64'),
 'b': Int64Index([], dtype='int64'),
 'd': Int64Index([], dtype='int64'),
 'e': Int64Index([], dtype='int64'),
 'f': Int64Index([], dtype='int64')}

In [9]: df.groupby('cat',observed=True).groups                                                                   
Out[9]: {'a': Int64Index([0, 2], dtype='int64')}

```

2019-01-21 03:40 UTC, WillAyd requested changes

2019-01-21 03:40 UTC, WillAyd commented on pandas/tests/groupby/test_categorical.py
> +def test_observed_groups_with_nan(observed=True):
You don't need `observed` as a keyword argument here; can just pass the literal value in the `groupby` call

2019-01-21 17:45 UTC, cgangwar11 commented
Also Fixes #21151

2019-01-21 21:18 UTC, TomAugspurger commented on doc/source/whatsnew/v0.24.0.rst
> +- Bug in :meth: `pandas.core.groupby.groups` which casues ``ValueError`` if ``observed=True`` and ``nan`` is present in group column (:issue:`22805`).
`pandas.core.groupby.groups` isn't a method. How about just "Bug in groupby causing a `ValueError` if ..."

2019-01-21 21:18 UTC, TomAugspurger commented on pandas/tests/groupby/test_categorical.py
> +    df = pd.DataFrame({'cat': pd.Categorical(['a', 'c', 'a'],
Could you make this `pd.Categorical(['a', np.nan, 'a'], categories=['a', 'b, 'd', 'e', 'f'])`? It wasn't immediately obvious that ''c'` would end up as NA.

2019-01-21 21:26 UTC, jreback requested changes
will look in a bit

2019-01-21 21:28 UTC, jreback requested changes

2019-01-21 21:33 UTC, jreback commented
if u claim this fixes other issues then pls explicitly test them and list in the whatsnew; these must be tested with the observed fixture

2019-01-21 21:36 UTC, TomAugspurger commented
This does test https://github.com/pandas-dev/pandas/issues/21151.

2019-01-21 21:45 UTC, jreback commented
there is no indication it tests any other issue

2019-01-21 22:01 UTC, TomAugspurger commented
@cgangwar11 can you add `GH-21151` as a comment in your regression test and add it to the `closes` in the original post on the PR?

@jreback what's the motivation for using the `observed` keyword? This is a regression test specifically for `observed=True`. I feel like parametrizing it makes the test more complicated that necessary.

2019-01-21 22:03 UTC, jreback commented
well these are very tricky tests and both cases must be tested

2019-01-21 22:06 UTC, TomAugspurger commented
Fair enough. I would assume that `observed=False` is already tested, but
probably best to have them both in one place.

On Mon, Jan 21, 2019 at 4:03 PM Jeff Reback <notifications@github.com>
wrote:

> well these are very tricky tests and both cases must be tested
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/24850#issuecomment-456210295>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABQHIgJFGjg8tVvZfmy8cfrVBoO71oFZks5vFjlJgaJpZM4aJ2jU>
> .
>

2019-01-22 12:08 UTC, jreback commented
@cgangwar11 pls update

2019-01-22 14:49 UTC, jreback requested changes
small whatsnew comment

2019-01-22 14:49 UTC, jreback commented on doc/source/whatsnew/v0.24.0.rst
> +- Bug in groupby which casues ``ValueError`` if ``observed=True`` and ``nan`` is present in group column (:issue:`22805`).
you can make these the same whatsnew entry. also this is specifically if grouping on a Categorical, pls say that.

2019-01-22 18:49 UTC, cgangwar11 commented
@jreback Changes done as requested !!!

2019-01-22 23:29 UTC, jreback approved these changes

2019-01-22 23:29 UTC, merged