ENH: Expose symlog scaling in plotting API
pandas-dev/pandas pull request #24871
Opened 2019-01-21 23:24 UTC by charlesdong1991

- [ ] closes #24867 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-01-21 23:39 UTC, WillAyd commented
Not terribly familiar with this code but looks OK to me at a glance. 

cc @TomAugspurger - too late to get this in for v0.24 at this point right?

2019-01-22 03:08 UTC, TomAugspurger reviewed
It's not clear to be that this is working correctly. You should add a test that includes an assertion that `ax.get_yscale() == 'symlog'`.

What's the user-facing API? I was thinking something like

```
df.plot(logy="sym")
```

so that a user can get regular log with `log=True`, symlog with `log="symlog"` or "sym", not sure which. And maybe accept "logit" too.

2019-01-22 03:08 UTC, TomAugspurger commented on pandas/plotting/_core.py
> -            [a.set_xscale('log') for a in axes]
Probably slightly cleaner to set

```python
scale = 'symlog if self.sym else 'log'
[a.set_xscale(scale) for a in axes]
```

2019-01-22 17:50 UTC, charlesdong1991 commented
Thanks @TomAugspurger for your review, appreciate a lot!
how about this, default value for `self.log` is `False`, which refers to linear. And user can specify any kind of log they want, e.g. `df.plot(log='logy')` or `df.plot(log='symloglog')`, i think this could be quite straightforward to users.
```python
        if self.log:
            scale_log = ["logx", "logy", "loglog"]
            scale_symlog = ["symlogx", "symlogy", "symloglog"]

            if self.log in scale_log:
                [a.set_xscale(scale_log) for a in axes]
            elif self.log in scale_symlog:
                [a.set_xscale(scale_symlog) for a in axes]
            else:
                raise ValueError("Invalid input for log.")
```
Will be very happy to hear your opinions!

2019-01-22 20:52 UTC, mdekstrand commented
I like @TomAugspurger's proposed UI - it's exactly what I had in mind. Since the documented API is already `logx=True`, allowing `logx='sym'` to turn on symlog makes a lot of sense to me as an API user.

2019-01-22 21:13 UTC, charlesdong1991 commented
Thank you very much @mdekstrand , it's good to know! since my proposal will be quite significant API change, so i would like to hear all of yours opinions first before submitting the pr... i will then keep Tom's proposal first in it!

2019-01-26 15:29 UTC, jreback requested changes
pls add a whatsnew note in 0.25.0 other enhancements

2019-01-27 21:54 UTC, charlesdong1991 commented
sorry, since i have several branches working on the same time... there are some git issues that i didn't notice so i messed it up... i will close this PR, and reopen another one... sorry...

2019-01-27 22:04 UTC, closed without merging