[DOC] Fix issues with DataFrame.aggregate page
pandas-dev/pandas pull request #24948
Opened 2019-01-26 13:24 UTC by rotuna

Fixed some formatting issues. Description was gettign rendered in the
wrong location.

Moved a line from generic.py to frame.py to help with the rendering.
Moved the description being clubbed with see also to doc string with the
function declaration in frame.py

- closes #24668

-  passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2019-01-27 03:22 UTC, WillAyd requested changes

2019-01-27 05:13 UTC, rotuna commented on pandas/core/generic.py
> +    The aggregation operations are always performed over an axis, either
Yes, my bad. 

Changed accoringly. Added summary as a variable so that it can be changed by df.agg. Everywhere else it is an empty string.

2019-01-29 02:22 UTC, WillAyd commented
@rotuna any chance you could post the output of `scripts/validate_docstrings.py` for the items you are changing? Would be helpful to see how these ultimately render

2019-01-30 12:07 UTC, rotuna commented
Hi, 

I've attached the output for all the aggregate pages. I can attach the rendered HTML too if you want.

The zip of the output files is here: 
[Archive.zip](https://github.com/pandas-dev/pandas/files/2812118/Archive.zip)

Rendered HTML files are here: 
[html.zip](https://github.com/pandas-dev/pandas/files/2812428/html.zip)

2019-02-08 11:37 UTC, rotuna commented
@WillAyd Do I need to make any further changes?

2019-02-08 20:46 UTC, WillAyd commented
Sorry missed previous ping - can you merge master and resolve conflicts? Will take a look after that

2019-02-19 04:17 UTC, WillAyd commented
@rotuna can you merge master?

2019-02-28 00:54 UTC, WillAyd requested changes
Some comments. Can merge master again to resolve CI issues.

As far as output can you just post the results of the validation of each of these directly in comment rather than zip archive? Will make review easier

2019-02-28 00:54 UTC, WillAyd commented on pandas/core/generic.py
> +       - If DataFrame.agg is called with a single function, returns a Series
Can you use asterisks here instead?

2019-02-28 00:54 UTC, WillAyd commented on pandas/core/generic.py
> +       - If DataFrame.agg is called with a single function, returns a Series
Also I think this will fail once #25132 gets merged. Give that a look to see how to handle

2019-03-05 15:47 UTC, TomAugspurger commented
@rotuna looks like there's a merge conflict. Can you merge master & push the update?

2019-03-19 03:39 UTC, WillAyd commented
@rotuna can you merge master and resolve the conflict here?

2019-03-28 05:33 UTC, WillAyd commented
Closing as stale. Ping if you'd like to pick this back up

2019-03-28 05:33 UTC, closed without merging