DEPR: Fixed warning for implicit registration
pandas-dev/pandas pull request #24964
Opened 2019-01-27 21:31 UTC by TomAugspurger

Reminder: We want people to explicitly call `pandas.plotting.register_matplotlib_converters()` when using a matplotlib plotting method with a pandas object. We implicitly call it as part of Series/Frame.plot.

```python
In [1]: import pandas as pd
In [2]: import matplotlib.pyplot as plt
In [3]: fig, ax = plt.subplots()
In [4]: s = pd.Series(range(12), index=pd.date_range('2017', periods=12))
In [5]: ax.plot(s)
## -- End pasted text --
Using matplotlib backend: TkAgg
/Users/taugspurger/sandbox/pandas/pandas/plotting/_converter.py:129: FutureWarning: Using an implicitly registered datetime converter for a matplotlib plotting method. The converter was registered by pandas on import. Future versions of pandas will require you to explicitly register matplotlib converters.

To register the converters:
        >>> from pandas.plotting import register_matplotlib_converters
        >>> register_matplotlib_converters()
  warnings.warn(msg, FutureWarning)
Out[1]: [<matplotlib.lines.Line2D at 0x1077d7b38>]
```

I'm not quite sure what happened in 
https://github.com/pandas-dev/pandas/pull/18307, but the warning wasn't showing up by default.

Closes https://github.com/pandas-dev/pandas/issues/24963

2019-01-28 12:13 UTC, jreback requested changes

2019-01-28 12:13 UTC, jreback commented on pandas/tests/plotting/test_converter_warning.py
> +# We isolate it completely, because its behavior depends on some global state
is there any easier way to do this? this is introducing massive technical debt.

2019-01-28 13:35 UTC, jreback commented
> I'm open to suggestions. But what about this is technical debt to you, that will slow down future development?

 you are adding a completely different framework in a special place. This is not great. I am most concerned about the separate call in the CI files.

2019-01-28 14:01 UTC, TomAugspurger commented
K. Let me know if you have suggestions for how to avoid that.

On Mon, Jan 28, 2019 at 7:35 AM Jeff Reback <notifications@github.com>
wrote:

> I'm open to suggestions. But what about this is technical debt to you,
> that will slow down future development?
>
> you are adding a completely different framework in a special place. This
> is not great. I am most concerned about the separate call in the CI files.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/24964#issuecomment-458134303>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABQHIlNLvwE7nuL7_KB-_K-d04JdaANtks5vHvyygaJpZM4aU805>
> .
>

2019-01-28 14:17 UTC, jreback commented
> K. Let me know if you have suggestions for how to avoid that

If you can't find a way with pytest, then I would simply remove the entire test.

2019-01-28 14:18 UTC, TomAugspurger commented
The only other thing I can think of is passing running the test in a subprocess, but trying to capture the stderr from that seems worse than using a test framework.

2019-01-28 14:43 UTC, TomAugspurger commented
> If you can't find a way with pytest, then I would simply remove the entire test.

I have a slight preference to testing this.

2019-01-28 18:01 UTC, jreback commented
> I have a slight preference to testing this.

I agree. But the way it is tested now is not great.

2019-01-29 02:52 UTC, TomAugspurger commented
Removed the tests.

2019-01-29 12:23 UTC, jreback approved these changes

2019-01-29 12:23 UTC, merged

2019-01-29 12:23 UTC, jreback commented
thanks @TomAugspurger

2019-01-29 13:47 UTC, jorisvandenbossche commented
I can confirm it is now warning on master!

2019-05-11 11:48 UTC, cfjhallgren commented
Hi everyone. Thanks for the amazing pandas package.

I get this warning even when I'm not plotting any pandas objects. When I remove the pandas import the warning disappears and the plotting works as expected. Is this expected behaviour?

2019-05-11 12:00 UTC, jorisvandenbossche commented
It *sounds* like that is indeed the expected warning, but it will be easier to judge if you can show a reproducible code example.

Pandas currently automatically registers some custom unit converters with matplotlib, which are used even when you don't use pandas' plotting methods. So that's what the warning is for, if something is not clear from the warning message, feedback very welcome!

2019-05-11 12:17 UTC, cfjhallgren commented
OK great! I explicitly registered the converters now.

Code example:

```python
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

plt.plot([datetime(2012,1,1), datetime(2012,1,2)], [1,2])
plt.show()
```

2019-05-30 22:22 UTC, TomAugspurger commented
@cfjhallgren pandas overwrites some of Matplotlib's units

```python
In [3]: matplotlib.units.registry
Out[3]:
{str: <matplotlib.category.StrCategoryConverter at 0x10e931358>,
 numpy.str_: <matplotlib.category.StrCategoryConverter at 0x10e931390>,
 bytes: <matplotlib.category.StrCategoryConverter at 0x10e9313c8>,
 numpy.bytes_: <matplotlib.category.StrCategoryConverter at 0x10e931400>,
 numpy.datetime64: <matplotlib.dates.DateConverter at 0x10e9711d0>,
 datetime.date: <matplotlib.dates.DateConverter at 0x10e971208>,
 datetime.datetime: <matplotlib.dates.DateConverter at 0x10e971240>}

In [4]: import pandas

In [5]: matplotlib.units.registry
Out[5]:
{str: <matplotlib.category.StrCategoryConverter at 0x10e931358>,
 numpy.str_: <matplotlib.category.StrCategoryConverter at 0x10e931390>,
 bytes: <matplotlib.category.StrCategoryConverter at 0x10e9313c8>,
 numpy.bytes_: <matplotlib.category.StrCategoryConverter at 0x10e931400>,
 numpy.datetime64: <pandas.plotting._converter.DatetimeConverter at 0x1119400b8>,
 datetime.date: <pandas.plotting._converter.DatetimeConverter at 0x111925dd8>,
 datetime.datetime: <pandas.plotting._converter.DatetimeConverter at 0x1119255c0>,
 pandas._libs.tslibs.timestamps.Timestamp: <pandas.plotting._converter.DatetimeConverter at 0x1119252e8>,
 pandas._libs.tslibs.period.Period: <pandas.plotting._converter.PeriodConverter at 0x111925550>,
 datetime.time: <pandas.plotting._converter.TimeConverter at 0x111940080>}
````

so you were getting pandas' formatting of those datetime objects.

2019-05-31 11:11 UTC, cfjhallgren commented
Interesting, thanks!