Fixed tuple to List Conversion in Dataframe class
pandas-dev/pandas pull request #25089
Opened 2019-02-02 10:05 UTC by Vibhu-Agarwal

- [X] closes #25075 
- [ ] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-02-02 18:45 UTC, alimcmaster1 commented
Hey thanks for the PR - mind writing a simple test to check this raises a Type Error?

2019-02-02 22:34 UTC, jreback requested changes
-  needs a test (put in tests/frame/test_constructor.py)
- whatsnew for 0.24.2
- pls do an asv check

2019-02-03 17:54 UTC, Vibhu-Agarwal commented
>     * needs a test (put in tests/frame/test_constructor.py)
> 
>     * whatsnew for 0.24.2
> 
>     * pls do an asv check

@jreback Will be adding the tests soon.
I'm not exactly aware about the **asv check** though.
Can you please explain me what it is or just point me to a good link.

2019-02-03 18:00 UTC, jreback commented
http://pandas.pydata.org/pandas-docs/stable/development/contributing.html#running-the-performance-test-suite

2019-02-04 13:06 UTC, jreback approved these changes

2019-02-04 13:06 UTC, jreback requested changes
waiting on tests / whatsnew / asv check

2019-02-04 18:13 UTC, Vibhu-Agarwal commented
- [X] added tests
- [X] modified whatsnew
- [X] performed asv check

@jreback Made all the requested changes.

2019-02-04 21:03 UTC, jreback requested changes

2019-02-04 21:03 UTC, jreback commented on doc/source/whatsnew/v0.24.2.rst
> +- Fixed regression in :meth:`DataFrame.__init__`  where mixed type of rows generated `Segmentation fault` (:issue:`25075`)
Fixed issue in ``DataFrame`` construction with passing a mixed list of mixed types could segfault.

2019-02-04 21:03 UTC, jreback commented on pandas/tests/frame/test_constructors.py
> +        data = [[1, 2], (3, 4)]
add the issue number as a comment

2019-02-04 21:03 UTC, jreback commented on pandas/tests/frame/test_constructors.py
> +        data2 = [[1, 2], [3, 4]]
you can inline data2 to the constructor

2019-02-05 04:58 UTC, pep8speaks commented
Hello @Vibhu-Agarwal! Thanks for updating the PR.

 - In the file [`pandas/tests/frame/test_constructors.py`](https://github.com/pandas-dev/pandas/blob/26cb100a38d8a8332f593aae007a3e1544ae92de/pandas/tests/frame/test_constructors.py), following are the PEP8 issues :

> [Line 1187:5](https://github.com/pandas-dev/pandas/blob/26cb100a38d8a8332f593aae007a3e1544ae92de/pandas/tests/frame/test_constructors.py#L1187): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 1187:5](https://github.com/pandas-dev/pandas/blob/26cb100a38d8a8332f593aae007a3e1544ae92de/pandas/tests/frame/test_constructors.py#L1187): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs

2019-02-05 07:57 UTC, Vibhu-Agarwal commented
@jreback Made all the requested changes and removed all unnecessary lines in whatsnew.

2019-02-05 12:45 UTC, jreback commented
can you run the appropriate asvs for this

2019-02-05 13:18 UTC, Vibhu-Agarwal commented
@jreback performed asv check with frame constructors (frame_ctor)
The report says `BENCHMARKS NOT SIGNIFICANTLY CHANGED.`

2019-02-06 02:16 UTC, jreback approved these changes

2019-02-06 02:17 UTC, merged

2019-02-06 02:17 UTC, jreback commented
thanks @Vibhu-Agarwal