Add tests for categorical apply
pandas-dev/pandas pull request #25095
Opened 2019-02-02 18:31 UTC by alimcmaster1

- [x] closes #20714
- [x] tests added / passed

[This issue](https://github.com/pandas-dev/pandas/pull/24275/files) fixed the underlying problem highlighted in #20714 . Added the appropriate test cases so we can close this.

2019-02-02 22:21 UTC, jreback requested changes

2019-02-02 23:17 UTC, jreback approved these changes

2019-02-02 23:17 UTC, jreback commented
lgtm ping on green.

2019-02-03 09:56 UTC, alimcmaster1 commented
Green and thanks for the review @jreback

2019-02-03 17:44 UTC, merged

2019-02-03 17:44 UTC, jreback commented
thanks @alimcmaster1