API: harmonize Index.to_flat_index to MultiIndex.to_flat_index
pandas-dev/pandas pull request #25094
Opened 2019-02-02 16:16 UTC by toobaz

- [x] closes #23670
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

After "implementing" it (that is, just unifying the method), I'm even more convinced about my [idea](https://github.com/pandas-dev/pandas/issues/23670#issue-380340023)... but @WillAyd and @h-vetinari feel free to consider this just a stimulus to resurrect (and conclude) the discussion ;-)

2019-02-02 22:26 UTC, jreback requested changes

2019-02-02 23:47 UTC, toobaz commented on doc/source/whatsnew/v0.24.1.rst
> +- :meth:`Index.to_flat_index` now always returns an :class:`Index` containing tuples, even in the case the original object was already a flat :class:`Index` (:issue:`23670`).
This should have been part of #22866, or at least of 0.24.0, when the method was introduced from scratch. Too late for that, but let's at least not expose for long a behavior which is inconsistent. Sure, [this needs discussion](https://github.com/pandas-dev/pandas/issues/23670) ;-)

2019-02-03 18:05 UTC, jreback commented on doc/source/whatsnew/v0.24.1.rst
> +- :meth:`Index.to_flat_index` now always returns an :class:`Index` containing tuples, even in the case the original object was already a flat :class:`Index` (:issue:`23670`).
So you mean to say ``Index.to_flat_index`` is not idempotent?

2019-02-03 19:31 UTC, jreback commented on doc/source/whatsnew/v0.24.1.rst
> +- :meth:`Index.to_flat_index` now always returns an :class:`Index` containing tuples, even in the case the original object was already a flat :class:`Index` (:issue:`23670`).
why is this a good thing though?

2019-02-04 00:33 UTC, toobaz commented on doc/source/whatsnew/v0.24.1.rst
> +- :meth:`Index.to_flat_index` now always returns an :class:`Index` containing tuples, even in the case the original object was already a flat :class:`Index` (:issue:`23670`).
For all the reasons in the [discussion](https://github.com/pandas-dev/pandas/issues/23670), plus one: ``one_level_multi_index.to_flat_index()`` is not idempotent, either.

2019-02-04 07:20 UTC, h-vetinari commented
> @toobaz: [...] but @WillAyd and @h-vetinari feel free to consider this just a stimulus to resurrect (and conclude) the discussion ;-)

A bit late to the party here, but I still don't understand the need for flattening MIs. I looked at [the original issue](https://github.com/pandas-dev/pandas/issues/19950) and the usecase there (squashing MI-columns for csv output) could IMO more idiomatically be solved by something like `MI.str.cat(', ')`

Of course, the latter current does not work yet (see also #23679), but I continue to think that tuples should not be usable in indexes. They are already necessary to "talk" to MIs, which makes their use ambiguous, plus it's incredibly hard to get right (and we don't, for large parts of the code base, including basic indexing), not least because it needs so much special casing for interacting with numpy (which treats tuples as arrays by default). See #24688

2019-02-04 08:38 UTC, toobaz commented
>  I continue to think that tuples should not be usable in indexes

Will comment on #24688 in few seconds. But this PR assumes that ``to_flat_index`` exists, and tries to fix it. This is a simple PR, worth doing even if ``to_flat_index`` disappears in a couple of releases. Doesn't need all that discussion.

2019-02-04 13:33 UTC, jreback requested changes
@toobaz pls in this issue lay out why you think this is a good think. len 1 MultiIndexes, while supported are not very useful. This elevates them to a first class citizen, not a good thing.

2019-02-04 14:18 UTC, toobaz commented
> len 1 MultiIndexes, while supported are not very useful. This elevates them to a first class citizen, not a good thing.

No, this PR doesn't change 1 level ``MultiIndex``es in any way.

> @toobaz pls in this issue lay out why you think this is a good think

This is quite clear in the issue: #23670

Anyway, in short, it's really simple:
1) ``Index.to_flat_index()`` doesn't make much sense per se - the index _is_ already flat
2) we support it only for compatibility with ``MultiIndex``
3) ... but in the current form, it is _not_ compatible. The output for ``MultiIndex`` with ``n`` levels is an ``Index`` with tuples of length ``n``
5) So the output for a flat ``Index``, which has 1 level, should be an ``Index`` with tuples of length 1
6) .. which is incidentally the output on a ``MultiIndex`` with 1 level. Which is good, because 1-level ``MultiIndexes`` should behave like flat ``Index``es (I couldn't care less about whether they are popular, encouraged or blamed: as long as they are allowed, we want them to behave consistently)

This is really a simple think, even @WillAyd is [now neutral](https://github.com/pandas-dev/pandas/issues/23670#issuecomment-460010083). Please provide any reason not to merge this, or let's proceed.

2019-04-10 05:01 UTC, WillAyd commented
Closing for now - I think it's worth continuing conversation in issue before updating any PRs on this

2019-04-10 05:01 UTC, closed without merging