Doc vic
pandas-dev/pandas pull request #25109
Opened 2019-02-03 12:35 UTC by victormoron

DOC 25104
- added type set_option docstring in config.py
-added type to boxplot_frame_groupby docstring in plotting/_core.py
-indented versionadded in ExcelWriter docstring io/excel.py
-updated code_check.sh to take into account PR10 type errors

2019-02-03 17:48 UTC, jreback requested changes

2019-02-03 17:48 UTC, jreback commented on pandas/plotting/_core.py
> +    subplots : bol
typo here, is this checked?

2019-02-04 12:03 UTC, datapythonista reviewed
Sorry, had this review unsent from yesterday.

@jreback I think we're far from being able to validate typos in types. We validate that bool is used intead of boolean, but at the moment we have all kinds of text in the types. Hopefully at some point we can parse them and have a list of allowed types/words. But that's very far in the future.

2019-02-04 12:06 UTC, datapythonista commented
@victormoron are the fixes to the docstrings failing because of the PR10 error? The fixes are correct, but seem unrelated. In general try to keep one PR per concept, if PR10 can already be validated, would be better to have it in a separate PR. If they are related, I think the validation is not working as expected.

2019-02-04 12:44 UTC, victormoron commented
@datapythonista. Basically the problem was not related with the fact of the space after the variable name, was related with the type not being defined. I firstly tried to delete the colon as suggested in the documentation, but then error was raised as type was required. I finally added the type of variable to get rid of the colon space problem. Hope that answers the question.

Should I update your suggestion and do another PR?

2019-02-04 15:10 UTC, datapythonista commented
Looks like the validation script reported PR10 for some false positives then, I wasn't aware. That would belong to another PR, if you can address the comments, happy to get this merged.

2019-02-07 20:16 UTC, victormoron commented
@datapythonista  should be ok now. let me know

2019-02-08 02:49 UTC, jreback approved these changes

2019-02-08 02:49 UTC, merged

2019-02-08 02:49 UTC, jreback commented
thanks @victormoron