BUG: Rewrite _make_concat_multiindex
pandas-dev/pandas pull request #25117
Opened 2019-02-03 15:50 UTC by toobaz

- [x] closes #20565
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2019-02-03 15:50 UTC, pep8speaks commented
Hello @toobaz! Thanks for submitting the PR.

 - In the file [`pandas/core/reshape/concat.py`](https://github.com/pandas-dev/pandas/blob/7d6d8f91f5eb529b7833e1cbfdede5111284ef6b/pandas/core/reshape/concat.py), following are the PEP8 issues :

> [Line 561:24](https://github.com/pandas-dev/pandas/blob/7d6d8f91f5eb529b7833e1cbfdede5111284ef6b/pandas/core/reshape/concat.py#L561): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 588:29](https://github.com/pandas-dev/pandas/blob/7d6d8f91f5eb529b7833e1cbfdede5111284ef6b/pandas/core/reshape/concat.py#L588): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

 - In the file [`pandas/tests/reshape/test_concat.py`](https://github.com/pandas-dev/pandas/blob/7d6d8f91f5eb529b7833e1cbfdede5111284ef6b/pandas/tests/reshape/test_concat.py), following are the PEP8 issues :

> [Line 2438:59](https://github.com/pandas-dev/pandas/blob/7d6d8f91f5eb529b7833e1cbfdede5111284ef6b/pandas/tests/reshape/test_concat.py#L2438): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator

2019-02-03 18:10 UTC, jreback requested changes
small comments. otherwise nice cleaning.

2019-02-03 18:10 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- Bug in :func:`concat` creating a malformed :class:`MultiIndex` when passed multiple frames indexed by identical :class:`MultiIndex`es (:issue:`20565`)
you need a space before the es I think

2019-02-03 18:10 UTC, jreback commented on pandas/core/reshape/concat.py
> +    temp_names = [None] * keys_levs.nlevels + list(orig.names)
name this empty_ames

2019-02-03 18:10 UTC, jreback commented on pandas/core/reshape/concat.py
> +    if levels is not None:
can you add some commentary what you are doing here

2019-02-04 01:02 UTC, mroeschke commented on pandas/core/reshape/concat.py
> +    keys_chunks = [([key] * len(idx)) for (key, idx) in zip(keys, indexes)]
Maybe make this a generator comprehension instead

2019-03-20 02:08 UTC, jreback commented
closing as stale

2019-03-20 02:08 UTC, closed without merging