BUG Solving issue #25011
pandas-dev/pandas pull request #25114
Opened 2019-02-03 15:38 UTC by HubertKl

- [ ] closes #xxxx
- [ ] tests added / passed
- [ x ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

This is supposed to solve issue #25011

2019-02-03 17:50 UTC, jreback requested changes
needs test & a whatnew entry

2019-02-09 23:13 UTC, pep8speaks commented
Hello @HubertKl! Thanks for updating the PR.



 - In the file [`pandas/tests/groupby/aggregate/test_aggregate.py`](https://github.com/pandas-dev/pandas/blob/19a041c9a0068d8a47cb895f936ab2bd15d2299e/pandas/tests/groupby/aggregate/test_aggregate.py), following are the PEP8 issues :

> [Line 290:1](https://github.com/pandas-dev/pandas/blob/19a041c9a0068d8a47cb895f936ab2bd15d2299e/pandas/tests/groupby/aggregate/test_aggregate.py#L290): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 301:5](https://github.com/pandas-dev/pandas/blob/19a041c9a0068d8a47cb895f936ab2bd15d2299e/pandas/tests/groupby/aggregate/test_aggregate.py#L301): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

2019-02-10 11:02 UTC, HubertKl commented
Test and whatsnew entry added

2019-02-11 13:35 UTC, jreback requested changes

2019-02-11 13:35 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- Bug in :method:'agg' when pqssing a list in the method agg on a Groupby with attibute as_index set as False, returned a DataFrame with the Groupby key as an index, now return the Groupby key as a c
can you make this much simpler, I am not sure what you are fixing here. add the issue number

2019-02-11 13:35 UTC, jreback commented on pandas/tests/groupby/aggregate/test_aggregate.py
> +
add the issue number. parameterize on as_index=[True,False]

2019-02-16 15:45 UTC, HubertKl commented
Thanks for the feedback and comments, I updated the PR accordingly.

2019-02-16 17:43 UTC, jreback requested changes
pls search for similar issues in the tracker. I am pretty sure this is actually a duplicate of 1 or more issues. We would also want to replicate those test cases here.

2019-02-16 17:43 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- Fixed bug in GroupBy when using as_index=False (issue:`25011`)
Bug in ::meth:`pandas.core.groupby.GroupBy.agg`` when passing ``as_index=False``, returning an additional column.

2019-02-16 17:43 UTC, jreback commented on pandas/tests/groupby/aggregate/test_aggregate.py
> +
like
```
@pytest.mark.parametize('as_index', [True, False]);
def test_agg_with_as_index(as_index):

....
```

2019-03-20 02:02 UTC, jreback commented
can you merge master

2019-04-10 05:18 UTC, WillAyd commented
@HubertKl can you merge master and fix up conflicts?

2019-05-03 05:43 UTC, WillAyd commented
Closing as stale but would certainly like this. Let us know if you'd like to pick it back up @HubertKl !

2019-05-03 05:43 UTC, closed without merging