ENH: Add in sort keyword to DatetimeIndex.union
pandas-dev/pandas pull request #25110
Opened 2019-02-03 13:00 UTC by reidy-p

- [ ] closes #24994, xref #24471
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

As discussed in #25063 for ``Index.union``, I have made the default ``sort=None`` which should sort except in the three cases outlined in the doc-string. When passing ``sort=False`` it should never sort.

There is a fastpath in the ``DatetimeIndex.union`` that at present automatically sorts the two ``DatetimeIndexes`` if they are both monotonic by simply putting the two indexes in the correct order and then removing any overlaps. I have tried to adjust this fastpath to control this sorting behaviour.

I have tried to adjust the tests to properly test the sorting behaviour but I think the set operations tests need more work in general.

@jorisvandenbossche and @TomAugspurger it would be great if you could have a look at this too.

2019-02-03 18:03 UTC, jreback requested changes

2019-02-03 18:03 UTC, jreback commented on pandas/core/indexes/datetimes.py
> +            * False : do not sort the result
add a versionaded tag

2019-02-16 17:54 UTC, jreback approved these changes

2019-02-16 17:55 UTC, jreback commented
lgtm. @jorisvandenbossche if you have a quick look.

2019-02-23 19:17 UTC, jreback requested changes
lgtm. very minor comment in whatsnew. ping on green.

2019-02-23 19:17 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- :meth:`DatetimeIndex.union` now supports the ``sort`` argument. The behaviour of the sort parameter matches that of ``Index.union`` (:issue:`24994`)
can you add a meth reference here

2019-02-23 21:22 UTC, reidy-p commented
@jreback it's green now. Thanks!

2019-02-23 21:43 UTC, jorisvandenbossche approved these changes

2019-02-23 21:43 UTC, merged

2019-02-23 21:43 UTC, jorisvandenbossche commented
@reidy-p thanks a lot!

2019-02-23 21:45 UTC, jorisvandenbossche commented
@reidy-p also, feel free to update https://github.com/pandas-dev/pandas/issues/24471 with the current status (do now all index classes have a sort keyword for intersection?)