TST: follow-up to Test nested pandas array #24993
pandas-dev/pandas pull request #25155
Opened 2019-02-05 10:06 UTC by simonjayhawkins

follow-up to #24993

@jreback : following discussion with @jorisvandenbossche at europandas it was deemed undesirable to apply markers directly to tests in the base class since these tests can be used by downstream projects.

The main goal of this PR is to remove the duplication added in #24993. With the constraint noted above this poses a slight problem regarding parameterised base tests. The parameterisation needs to be duplicated! To reduce this slightly some parameterisation has been replaced with fixtures.

@TomAugspurger : the additions to `test_numpy.py` are moreless copied from `numpy_/test_numpy_nested.py` with a few additional comments on the failure cases and the numpy version skip scoped to only the tests using the `data_missing` fixture.

2019-02-05 11:04 UTC, simonjayhawkins commented on pandas/tests/extension/test_numpy.py
> +NP_VERSION_INFO = tuple(int(x) for x in np.__version__.split('.'))
i see that LooseVersion is used throughout the codebase. I'll change to use that instead.

2019-02-06 02:21 UTC, jreback requested changes
@simonjayhawkins looks good. some very minor comments. ping on green.

2019-02-06 02:39 UTC, jreback commented
also pls merge master

2019-02-06 12:27 UTC, jreback approved these changes

2019-02-07 01:23 UTC, merged

2019-02-07 01:23 UTC, gfyoung commented
Thanks @simonjayhawkins !