BUG: fix sorting with observed=True in groupby
pandas-dev/pandas pull request #25173
Opened 2019-02-05 23:27 UTC by topper-123

- [x] closes #25167
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Fix bug in #25167.

2019-02-06 02:33 UTC, jreback requested changes
I am not sure I buy your test example. there are actually 4 cases here observed / sort both True/False. Please enumerate what the expected results are.

2019-02-06 02:33 UTC, jreback commented on pandas/tests/groupby/test_categorical.py
> +    # GH 25167
make this a separate test, parameterize by sort as well

2019-03-03 03:29 UTC, jreback requested changes
can you merge master and update to comments

2019-03-03 03:29 UTC, jreback commented on doc/source/whatsnew/v0.24.2.rst
> +- Fixed bug in :meth:`DataFrame.groupby` where using ``observed=True`` didn't sort properly (:issue:`25167`)
move to 0.25.0

2019-03-19 03:51 UTC, WillAyd commented
Closing as stale ping if you'd like to continue

2019-03-19 03:51 UTC, closed without merging