DOC: Clarify supported formats behavior in DatelikeOps.strftime GH24788
pandas-dev/pandas pull request #25188
Opened 2019-02-06 14:51 UTC by DeanLa

clarifies that the python string format is the only one supported

- [ ] closes #24788 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-02-06 16:31 UTC, mroeschke commented
The main issue was to clarify this for `Timestamp.strftime`. `DatetimeIndex.strftime` here has that already documented.

2019-02-07 09:41 UTC, DeanLa commented
Sorry for the mixup. Trying to change `Timestamp` now, but it seems that docs that are in pyx extension are not changed when I run `make.py`.
Is there a guide for a better understanding of how this works?

2019-03-10 22:51 UTC, mroeschke commented
Do you mind updating @DeanLa?

2019-03-10 22:54 UTC, jreback commented
looks fine just needs a rebase

2019-03-12 08:34 UTC, DeanLa commented
> Do you mind updating @DeanLa?

Yes, sorry.
The `Timestamp.strftime`is inherited directly from `datetime`. I couldn't find an easy way to write only docs without changing code.
Do you have any reference for a previous use case that does that?

2019-03-12 20:57 UTC, mroeschke commented
You can probably just override the `__doc__` for `strftime` to just append the information.

2019-03-20 01:36 UTC, jreback requested changes
can you merge master as well

2019-03-20 01:36 UTC, jreback commented on pandas/core/arrays/datetimelike.py
> +            key,  # type: Union[int, Sequence[int], Sequence[bool], slice]
this has been changed in master can you revert

2019-04-05 00:55 UTC, jreback commented
ca n you merge master and update

2019-04-20 16:56 UTC, jreback commented
can you merge master

2019-04-26 20:58 UTC, DeanLa commented
> You can probably just override the `__doc__` for `strftime` to just append the information.

Sorry, I'm not sure how. Because it only inherits without a python class, I need to change this in the cpython `pyx` files. But I also need to use `@Substitution` decorator which I see is not being used in cpython files.
I'd love it if you can reference to some doc because I couldn't find any example for such case, but I'll accept if this is too much to ask and pass this to someone else.

2019-04-27 02:35 UTC, mroeschke commented
Hmm this may be more trouble than it's worth. Additionally, we do say in the `timeseries.rst` docs that only python directive are supported https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#providing-a-format-argument

2019-04-28 17:32 UTC, jreback commented
closing as already documented in a reasonable way.

2019-04-28 17:32 UTC, closed without merging