BUG-25061 fix printing indices with NaNs
pandas-dev/pandas pull request #25202
Opened 2019-02-07 00:37 UTC by JustinZhengBC

- [X] closes #25061- [ ] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

The `FloatArrayFormatter` leaves a space in front of the floats it formats (expected behaviour as demonstrated by [this test](https://github.com/pandas-dev/pandas/blob/638ddebaa7da1e569836a5b89593b120dbbf491c/pandas/tests/io/formats/test_format.py#L2395)). To avoid misaligned values when printing indices, `NaN` values must be treated similarly.

2019-02-07 01:18 UTC, gfyoung commented on pandas/tests/series/test_repr.py
> +        i = Index([1, np.nan])
Reference issue above this line as a comment.

2019-02-07 05:13 UTC, gfyoung commented on pandas/tests/series/test_repr.py
> +        i = Index([1, np.nan])
I meant above the line `i = Index(...)` (hence why I put the comment where I did).  I corrected it myself.

2019-02-07 05:14 UTC, gfyoung approved these changes
cc @jreback

2019-02-08 02:38 UTC, jreback requested changes

2019-02-08 02:38 UTC, jreback commented on pandas/io/formats/format.py
can you do
``na_rep = self.na_rep`` here, then update (and use that value); so the value attached to self is not changed.

2019-02-09 16:52 UTC, jreback approved these changes

2019-02-09 16:52 UTC, merged

2019-02-09 16:52 UTC, jreback commented
thanks @JustinZhengBC