BUG: Duplicated returns boolean dataframe
pandas-dev/pandas pull request #25234
Opened 2019-02-09 01:44 UTC by gnilrets

- [x] closes #25184
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2019-02-09 17:14 UTC, jreback requested changes

2019-02-09 17:14 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- Bug in using duplicated with empty dataframes (:issue:`25184`)
say more like

``:meth:DataFrame.duplicate()`` on empty dataframe was not return a boolean dtyped Series

2019-02-09 17:14 UTC, jreback commented on pandas/tests/frame/test_duplicates.py
> +def test_duplicated_on_empty_frame_gives_back_frame():
can you add the issue number as a comment here, rename the test to

test_duplicated_on_empty_frame

2019-02-09 17:14 UTC, jreback commented on pandas/tests/frame/test_duplicates.py
> +    dupes = df.duplicated('a')
result = 
expected = 
tm.assert_frame_equal(result, expected)

2019-02-09 17:15 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- Bug in using duplicated with empty dataframes (:issue:`25184`)
this can go in 0.24.2

2019-02-09 21:47 UTC, gnilrets commented
@jreback - Requested changes addressed.

I wasn't sure if this PR should go against master or the v0.24.x branch?

2019-02-11 12:52 UTC, jreback approved these changes

2019-02-11 12:52 UTC, merged

2019-02-11 12:52 UTC, jreback commented
thanks @gnilrets all PRs go against master; *some* are backported.