PERF: avoid copy of dataframe while writing to SQL DBs
pandas-dev/pandas pull request #25255
Opened 2019-02-10 00:58 UTC by sridhu88

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] This change avoids making an entire copy of the dataframe while writing to SQL DBs with a chunksize. Instead we convert slices of the dataframe into a data list and write to the DB. Saves significant memory when writing large dataframes to SQL DBs.

2019-02-10 00:58 UTC, pep8speaks commented
Hello @sridhu88! Thanks for submitting the PR.

 - In the file [`pandas/io/sql.py`](https://github.com/pandas-dev/pandas/blob/c7bc9a25559e0235017d025664f794ec3096dce4/pandas/io/sql.py), following are the PEP8 issues :

> [Line 626:17](https://github.com/pandas-dev/pandas/blob/c7bc9a25559e0235017d025664f794ec3096dce4/pandas/io/sql.py#L626): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

2019-02-11 13:07 UTC, jreback requested changes
you would need to test this

2019-02-11 13:07 UTC, jreback commented on pandas/io/sql.py
> +            temp = self.frame[start_index:end_index].copy()
these should all be .iloc

2019-02-11 13:07 UTC, jreback commented on pandas/io/sql.py
> +            if start_index == 0 and end_index == len(self.frame.index):
this shouldn't be necessary

2019-02-13 08:19 UTC, sridhu88 commented
> you would need to test this

Sorry I'm new to Pandas development. Are you suggesting adding a test to demonstrate performance or just the correctness? If correctness, I thought there are already quite a few tests for the to_sql function which this change affects.

2019-02-13 13:06 UTC, jreback commented
@sridhu88 a performance test that this actually improves things, see the asv_bench dir

2019-02-13 13:40 UTC, jorisvandenbossche commented
Jeff, I am not sure it is easy to test this.  There are already sql tests in ASV, so we can run them and see if we see a difference, but I am not sure we will (copying is relatively cheap compared to the writing to sql). And we don't test memory in ASV.

2019-02-13 13:47 UTC, jreback commented
@jorisvandenbossche  https://github.com/pandas-dev/pandas/pull/25255#issuecomment-463202722

I agree, which is why I don't think this PR actually helps any, but I could be wrong.

2019-02-13 13:52 UTC, jorisvandenbossche commented
Actually, a specific benchmark that uses `chunksize` might be good to add (just checked and that is something we don't yet have) *in general*.

I quickly did a test with/without chunksize on master and this PR, and this PR is actually slower. Which is somewhat to be expected. We now chunk the dataframe before converting to arrays, while before it was slicing the arrays (and slicing arrays is faster than slicing dataframes). I still think this PR can be worth it, as it is a trade-off between memory and performance.

Howeve

2019-02-13 13:57 UTC, jorisvandenbossche commented
(Jeff, didn't see your comment before posting the last one, github is sometimes annoying :-))

@sridhu88 do you have a benchmark that measures memory that shows the impact of this PR? 
Without necessarily including that as a test, being able to show that is probably essential for deciding whether we want to merge this or not.

2019-02-14 06:09 UTC, sridhu88 commented
Thanks Jeff, Joris. Just to clarify, I labeled this PR as "PERF" purely for memory reasons. I was seeing that to insert a dataframe of ~2G, the peak memory during to_sql is approximately 2-3 times the dataframe size. With this change, the peak memory will remain very close to the actual size of the dataframe. As you mentioned, there may be a small hit to runtime. But in my tests, I didn't see a significant slowdown. Let me set up some benchmarking tests and get back to you soon.

2019-02-14 06:12 UTC, WillAyd commented
Is this not something we can measure with ASV?

https://asv.readthedocs.io/en/stable/writing_benchmarks.html#memory

2019-02-27 17:30 UTC, WillAyd commented
@sridhu88 can you see if we can get the ASV running and merge master?

2019-03-19 04:07 UTC, WillAyd commented
Closing as stale. Ping if you'd like to continue

2019-03-19 04:07 UTC, closed without merging