[BUG] exception handling of MultiIndex.__contains__ too narrow
pandas-dev/pandas pull request #25268
Opened 2019-02-11 14:31 UTC by makbigc

- closes #24570
- 1 test added
-  passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
-  whatsnew entry

2019-02-11 19:11 UTC, jreback requested changes

2019-02-11 19:11 UTC, jreback commented on pandas/tests/test_multilevel.py
> +    def test_in(self):
can you call this test_contains and move next to pandas/tests/indexing/test_multiindex.py

2019-02-11 19:11 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- Bug in which the error raised by Timedelta is not handled in the exception of :meth:`__contains__` (:issue:`24570`)
you need to say `MultiIndex.__contains__`. though you can just say something like: Incorrect exception raises when testing membership, e.g. ``pd.Timesdelta(...) in MultiIndex``

2019-02-11 19:41 UTC, jreback commented
this also can close #25087 ?

2019-02-12 14:26 UTC, makbigc commented
It seems no. Because no `MultiIndex` is involved in `DataFrame.dropna`.

2019-02-16 20:08 UTC, jreback commented
this is fine, pls merge master; ping on green.

2019-02-19 13:24 UTC, makbigc commented
@jreback Done. Thanks a lot.

2019-02-19 13:45 UTC, jreback approved these changes

2019-02-19 13:46 UTC, merged

2019-02-19 13:46 UTC, jreback commented
thanks @makbigc keep em coming!