BUG: Series.__setitem__ with datetimetz data
pandas-dev/pandas pull request #25331
Opened 2019-02-15 04:53 UTC by mroeschke

- [x] closes #12862
- [x] closes #20441
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2019-02-15 08:58 UTC, gfyoung commented on pandas/tests/series/indexing/test_indexing.py
> +    result = pd.Series()
nit: use `Series` directly instead of `pd.Series` (you do so in your first test)

2019-02-16 18:05 UTC, jreback requested changes
pls rebase as well

2019-02-16 18:05 UTC, jreback commented on pandas/core/series.py
> +            # GH 20441: set_value expects and ndarray, not ExtensionArray
and -> an, but can't we just do: ``.to_numpy()`` ?

2019-02-19 06:29 UTC, mroeschke commented
Going to postpone this. The fix is more complicated than I originally thought.

2019-02-19 06:29 UTC, closed without merging