Fixed regression of Multi index with NaN
pandas-dev/pandas pull request #25424
Opened 2019-02-24 02:16 UTC by hksonngan

- [x] closes #22247
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry
As pull #19074 changed compute of hashtable from `self.values` to `self.codes` and `self.levels`, NaN values doesn't cover.
I just simply fixed this regression the special case, by check return value from the hashtable.

2019-02-24 02:53 UTC, jreback requested changes
you are adding a significant amount of non trivial code here - which likely duplicates a fair amount of existing

likely this is change needs some work

2019-02-25 04:22 UTC, hksonngan commented
@jreback 
I want to check `NaN` in MultiIndex, but function `isna()` isn't implemented in MultiIndex.
How can I change?
and I change from `np.where()` to use `pd.core.algorithms.isin()` but can not pass the test cases.
Should I use directly `np.isin()` or modify `algorithms.isin()`?

2019-03-03 01:51 UTC, jreback commented
@hksonngan you are adding an amazing amount of complexity here. Please step thru the setting code; This is likely a very small change.

2019-03-05 23:57 UTC, hksonngan commented
@jreback I think one problem remains when set value multi-index with NaN, get_loc, will crash. I will investigate this.

2019-03-12 23:47 UTC, hksonngan commented
@jreback I add code to pass of the case when setting value with NaN index, but I don't know why I get a lot of linting errors when I rebase. I don't change these files. Do you know why?

2019-03-14 01:48 UTC, hksonngan commented
@jreback ping

2019-03-14 22:26 UTC, jreback commented
@hksonngan this is a massive amount of code.

2019-03-15 00:53 UTC, hksonngan commented
> @hksonngan this is a massive amount of code. I am not even sure what you are trying to do your fix is VERY complicated. Please point out exactly where the issue is.

@jreback if we have NaN in MultiIndex as:
```python
df = pd.DataFrame(
    [
        ['A', np.nan, 1.23, 4.56],
        ['A', 'G', 1.32, 4.65],
        ['A', 'D', 9.87, 10.54],
    ],
    columns=['pivot_0', 'pivot_1', 'col_1', 'col_2'],
)
df.set_index(['pivot_0', 'pivot_1'], inplace=True)
```
```
                                 col_1   col_2
pivot_0  pivot_1
A            NaN           1.23     4.56
              G                1.32     4.65
              D                9.87    10.54
```
Now I set new `df.at[('A', 'F'), 'col_2'] = 0.0` I get wrong result in `col_1` as:
```
                                 col_1   col_2
pivot_0  pivot_1
A            NaN           1.23      4.56
              G                1.32      4.65
              D                9.87    10.54
              F                 1.24      0.0
```
The right result is must `              F                 NaN      0.0`

2019-03-15 00:55 UTC, hksonngan commented
Or I add new MultiIndex with NaN, I get exception like this code:
```python



df = pd.DataFrame(
    [
        ['A', 'G', 1.32, 4.65],
        ['A', 'D', 9.87, 10.54],
    ],
    columns=['pivot_0', 'pivot_1', 'col_1', 'col_2'],
)
df.set_index(['pivot_0', 'pivot_1'], inplace=True)
df.at[('A', np.nan), 'col_2'] = 0.0 # Get exception in here
```

2019-03-15 01:12 UTC, hksonngan commented
* So I fixed simple by check 'NaN' exist or not in MultiIndex with function  [`_hasnans`](https://github.com/hksonngan/pandas/blob/7f7a12a0fe18c89a22b6f4bf3f9055e5d00b1b6e/pandas/core/indexes/multi.py#L754), because when add new value to DataFrame, the [get_indexer](https://github.com/hksonngan/pandas/blob/7f7a12a0fe18c89a22b6f4bf3f9055e5d00b1b6e/pandas/_libs/index.pyx#L660) return from hash with dulicate value -1, as NaN value and new value is same result from hashtable.
* Adding new value when have NaN in index will get the exception at [line 684 index.pyx `lab_int`](https://github.com/hksonngan/pandas/blob/7f7a12a0fe18c89a22b6f4bf3f9055e5d00b1b6e/pandas/_libs/index.pyx#L684) was not calculated for NaN value at class MultiIndex with function [`_engine()` line 1234 ](https://github.com/hksonngan/pandas/blob/7f7a12a0fe18c89a22b6f4bf3f9055e5d00b1b6e/pandas/core/indexes/multi.py#L1234). So I compensate with position of NaN in `levels` from line [688 index.pyx](https://github.com/hksonngan/pandas/blob/7f7a12a0fe18c89a22b6f4bf3f9055e5d00b1b6e/pandas/_libs/index.pyx#L688), I raise exception to call function `_hasnans`, and recalculate position of NaN in function [`_engine()` line 1234 ](https://github.com/hksonngan/pandas/blob/7f7a12a0fe18c89a22b6f4bf3f9055e5d00b1b6e/pandas/core/indexes/multi.py#L1234)

2019-04-16 20:10 UTC, hksonngan commented
close as I will investigate another way to solve this

2019-04-16 20:10 UTC, closed without merging