[BUG] maybe_upcast_putmast also handle ndarray
pandas-dev/pandas pull request #25431
Opened 2019-02-24 15:04 UTC by makbigc

-  closes #23823
-  2 tests added
-  passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
-  whatsnew entry

Follow h-vetinari's footstep. `maybe_upcast_putmask` was left untouched in #25425. Try to fix the bug so that `maybe_upcast_putmask` can also handle `ndarray` as well as `Series`.

2019-02-25 10:24 UTC, gfyoung commented on pandas/tests/dtypes/cast/test_upcast.py
> +    tm.assert_numpy_array_equal(result, expected)
I suspect these tests already have a home in another, existing test file.

2019-02-25 10:24 UTC, gfyoung commented on pandas/tests/dtypes/cast/test_upcast.py
> +    tm.assert_numpy_array_equal(result, expected)
Also, reference the issue number as a comment under each test definition.

2019-02-27 13:27 UTC, jreback requested changes
what problem is this solving?

2019-02-27 13:27 UTC, jreback commented on pandas/tests/dtypes/cast/test_upcast.py
> +def test_upcast_series():
can you parameterize these (both tests) as I suspect a myriad of cases (just a couple for now, e.g. int -> float you can start with)

2019-02-27 13:27 UTC, jreback commented on pandas/core/dtypes/cast.py
> +                    else:
what other types are here? a Series?

this should be converted at a higher level (at the beginning of the function)

2019-02-27 13:27 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- :func:`maybe_upcast_putmask` does not replace the element of the ``ndarray`` correctly (:issue:`23823`)
this doesn't warrant a whatsnew as its an internal impl detail

2019-03-09 13:22 UTC, makbigc commented
I investigated further and found that I misunderstood the usage of `maybe_upcast_putmask`. 

The result array should be replaced with the element of other array starting from the beginning, not in the position of mask. This behavior is due to np.place

 `changeit` isn't called.
```
In [4]: arr1 = np.array([1,2,3])                                                

In [5]: other = np.array([61,62,63])                                            

In [6]: mask = np.array([False, True, False])                                   

In [7]: result, _ = maybe_upcast_putmask(arr1, mask, other)                     

In [8]: result                                                                  
Out[8]: array([ 1, 61,  3])
```

`changeit` is called.
```
In [24]: arr2 = np.array([1,2,3])                                                                                                           

In [25]: other2 = np.array([61.1, 62.2, 63.3])                                                                                              

In [26]: mask = np.array([False, True, False])                                                                                              

In [27]: result, _ = maybe_upcast_putmask(arr2, mask, other2)                                                                               

In [28]: result                                                                                                                             
Out[28]: array([ 1. , 61.1,  3. ])
```

`changeit` isn't called.
```
In [15]: arr2 = np.arange('2019-01-01', '2019-01-04', dtype='datetime64[D]')    

In [16]: other2 = np.arange('2018-01-01', '2018-01-04', dtype='datetime64[D]')  

In [17]: mask = np.array([False, True, False])                                  

In [18]: result, _ = maybe_upcast_putmask(arr2, mask, other2)                   

In [19]: result                                                                 
Out[19]: array(['2019-01-01', '2018-01-01', '2019-01-03'], dtype='datetime64[D]')
```
So the behavior for Series as an input is not correct. And `maybe_upcast_putmask` does not expect a series input.

`changeit` is called.
```
>>> s = pd.Series([10, 11, 12])
>>> t = pd.Series([np.nan, 61, np.nan])
>>> from pandas.core.dtypes.cast import maybe_upcast_putmask
>>> result, _ = maybe_upcast_putmask(s, np.array([False, True, False]), t)
>>> result  # correct
0    10
1    61
2    12
dtype: int64
```
Examples can be added into the function docstring to elucidate the usage. Should I do it in this PR?

2019-03-10 23:23 UTC, jreback requested changes
can you update with your new tests. also you can do an assert on the input of the function itself (e.g. assert its an ndarray)

2019-03-10 23:23 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- :func:`maybe_upcast_putmask` does not replace the element of the ``ndarray`` correctly (:issue:`23823`)
can you remove

2019-03-17 07:07 UTC, makbigc commented
When adding the tests, the following bug is found and fixed. 

```
In [4]: arr = np.arange(10, 15)                                                 

In [5]: other = np.array([61, 62])                                              

In [6]: mask = np.array([False, True, False, True, True])                       

In [7]: result, changed = maybe_upcast_putmask(arr, mask, other)                
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-7-3ec9bc405a70> in <module>
----> 1 result, changed = maybe_upcast_putmask(arr, mask, other)

~/Code/pandas/pandas/core/dtypes/cast.py in maybe_upcast_putmask(result, mask, other)
    242             else:
    243 
--> 244                 if isna(other[mask]).any():
    245                     return changeit()
    246 

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 5
```

2019-03-19 23:56 UTC, jreback requested changes
minor comments, merge master, ping on green.

2019-03-19 23:56 UTC, jreback commented on pandas/tests/dtypes/cast/test_upcast.py
> +def test_upcast_error():
are there more cases to consider? e.g. non-ndarray

2019-03-22 11:50 UTC, jreback approved these changes

2019-03-22 11:51 UTC, merged

2019-03-22 11:51 UTC, jreback commented
thanks @makbigc keep em coming!