Add one line on the contribution guide
pandas-dev/pandas pull request #25490
Opened 2019-02-28 23:58 UTC by yehia67

issue https://github.com/pandas-dev/pandas/issues/25487 
add command 
`conda uninstall --force pandas`

2019-03-01 00:04 UTC, WillAyd approved these changes
lgtm @TomAugspurger

2019-03-01 02:28 UTC, TomAugspurger commented on doc/source/development/contributing.rst
> +   conda uninstall --force pandas
You should activate before uninstalling. So swap this line and the next.

2019-03-03 01:43 UTC, jreback requested changes
per @TomAugspurger comment

2019-03-03 20:30 UTC, TomAugspurger commented
Thanks @yehia67!

2019-03-03 20:30 UTC, merged