BUG-24971 copying blocks also considers ndim
pandas-dev/pandas pull request #25521
Opened 2019-03-03 03:00 UTC by JustinZhengBC

- [X] closes #24971 
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

The following gives a series containing [1] instead of 1
```
>>> pd.Series(pd.Categorical('A', categories=['A', 'B'])).replace({'A': 1, 'B': 2})
0    [1]
dtype: object
```
This bug occurs because in the process of copying the original categorical block (which is needed as the operation is not inplace), the constructor class for the new object defaults to `ObjectBlock`, whose constructor has a default `ndim` of 2. This PR alters the block `copy` function to specify that the newly constructed block should have the same `ndim` as the block being copied.

2019-03-03 03:10 UTC, jreback requested changes

2019-03-03 03:10 UTC, jreback commented on pandas/tests/series/test_constructors.py
> +        assert not is_list_like(s.replace({'A': 1})[0])
use assert_series_equal

2019-03-03 03:10 UTC, jreback commented on doc/source/whatsnew/v0.24.2.rst
> +- Bug where a copy of a categorical could have the wrong dimensions (:issue:`24971`)
can you reword to make this more clear. mentione this is on a Series of categorical dtype. The dimenension issue is an internal one. You want to emphasize the user visible effects.

2019-03-03 03:10 UTC, jreback commented on doc/source/whatsnew/v0.24.2.rst
> +- Bug where a copy of a categorical could have the wrong dimensions (:issue:`24971`)
this is visible when you call ``.replace()``

2019-03-03 03:10 UTC, jreback commented on pandas/tests/series/test_constructors.py
> +        # GH 24971
can you put all 3 tests from the OP here.

2019-03-03 03:10 UTC, jreback commented on pandas/tests/series/test_constructors.py
> +
this should go with the replace tests

2019-03-04 21:15 UTC, jreback requested changes

2019-03-04 23:13 UTC, JustinZhengBC commented
@jreback I've made the requested changes

2019-03-05 03:00 UTC, TomAugspurger commented on pandas/tests/series/test_replace.py
> +        tm.assert_series_equal(expected, result, check_dtype=False)
Looks like L292 has the reference now (https://github.com/pandas-dev/pandas/issues/23305)

2019-03-20 02:01 UTC, jreback commented
can you merge master

2019-03-20 12:26 UTC, jreback approved these changes

2019-03-20 12:26 UTC, merged

2019-03-20 12:27 UTC, jreback commented
thanks @JustinZhengBC nice patch, keep em coming!