BUG: in error message raised when invalid axis parameter
pandas-dev/pandas pull request #25553
Opened 2019-03-05 18:30 UTC by simonjayhawkins

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

I don't think there is currently an issue for this. will open new and then add whatsnew.

2019-03-05 18:49 UTC, WillAyd commented
Generally looks good to me. Is this a follow up to another PR?

2019-03-05 18:54 UTC, simonjayhawkins commented
> Generally looks good to me. Is this a follow up to another PR?

@WillAyd : just raised new issue #25555

2019-03-05 21:01 UTC, jreback requested changes
for 0.25 is ok

2019-03-05 21:01 UTC, jreback commented on pandas/core/generic.py
> -                         .format(axis, type(cls)))
I think this should just be ``cls`` as it gives the fully qualified path

2019-03-06 13:20 UTC, jreback requested changes

2019-03-06 13:20 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- Bug in error message raised when invalid ``axis`` parameter passed (:issue:`25555`)
can you reword a bit, I am not sure what this means here.

2019-03-06 22:35 UTC, jreback approved these changes

2019-03-06 22:35 UTC, merged

2019-03-06 22:36 UTC, jreback commented
thanks @simonjayhawkins