Multiloc
pandas-dev/pandas pull request #25607
Opened 2019-03-08 13:15 UTC by impact27

- [x] closes #25594
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Starting in 0.21.0, using .loc or [] with a list with one or more missing labels, is deprecated. In the doc, only getting is shown:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#indexing-with-list-with-missing-labels-is-deprecated

As argued in #25594, this should not be the case for setting. This PR is therefore adding the possibility of adding index and columns when setting with array-like index.

If the axis is a MultiIndex, the expected result is not trivial, and is therefore not covered in this PR.

2019-03-08 14:04 UTC, pep8speaks commented
Hello @impact27! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/frame/test_indexing.py`](https://github.com/pandas-dev/pandas/blob/0bbfa41bd6de39b3ffce06a598f31efb5b1d54ce/pandas/tests/frame/test_indexing.py):

> [Line 1095:80](https://github.com/pandas-dev/pandas/blob/0bbfa41bd6de39b3ffce06a598f31efb5b1d54ce/pandas/tests/frame/test_indexing.py#L1095): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)

2019-03-09 16:27 UTC, jreback requested changes
I am not sure we actually want to support this at all. allowing expansions is somewhat bug prone now, and introduces enormous complexity in the code. This PR seems to increase complexity. If you are actually going to move things around, please do a pre-cursor PR to do that w/o any other changes. Then can evaluate the merits of this change.

2019-03-12 16:03 UTC, impact27 commented
The complex part is guessing what the data type is from the value. This is only a problem when adding a column in the info axis. This PR simply creates float columns and then the dtype is changed when the data is set. This is not ideal but this is what the codes already does for most of the data types. (using loc, you can't create a 'int' column).

2019-04-20 17:43 UTC, jreback commented
closing. happy to take a reorg on the code (the pre-cursor). but need consensus on the issue you are trying to close first.

2019-04-20 17:43 UTC, closed without merging