BUG: Fix to_string output when using header keyword arg (#16718)
pandas-dev/pandas pull request #25602
Opened 2019-03-08 09:19 UTC by tomneep

Also affects to_latex midrule position

- [x] closes #16718
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Fixes the 4th example in the above issue. Should the whatsnew entry go in 24.2 or 25.0 (or both)?

2019-03-09 16:31 UTC, jreback requested changes
you mentioned this affects the latex output, can you add a test case for the same. pls add a note in 0.25.0 as well.

2019-03-12 14:05 UTC, tomneep commented
I've added a test for `to_latex` and a whatsnew entry. Let me know if you want me to change anything else.

2019-03-12 17:02 UTC, TomAugspurger approved these changes

2019-03-12 17:03 UTC, merged

2019-03-12 17:03 UTC, TomAugspurger commented
Thanks @tomneep!