BUG: to_csv line endings with compression
pandas-dev/pandas pull request #25625
Opened 2019-03-10 02:24 UTC by chris-b1

- [x] closes #25311
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-03-10 15:43 UTC, jreback requested changes

2019-03-10 15:43 UTC, jreback commented on pandas/tests/frame/test_to_csv.py
> +            result = gzip.open(path, mode='rt', newline='').read()
this needs a with to close it

2019-03-10 15:43 UTC, jreback commented on pandas/tests/frame/test_to_csv.py
> +            result = gzip.open(path, mode='rt', newline='').read()
but better to use pandas.util.testing.decompress_file anyhow

2019-03-11 10:12 UTC, jorisvandenbossche commented
Failure is unrelated, see https://github.com/pandas-dev/pandas/issues/25652

2019-03-11 14:51 UTC, jreback approved these changes

2019-03-11 14:51 UTC, jreback commented
lgtm. ping on green.

2019-03-11 15:26 UTC, merged

2019-03-11 15:27 UTC, jorisvandenbossche commented
Thanks @chris-b1 !