BUG: Fix user-facing AssertionError with to_html (#25608)
pandas-dev/pandas pull request #25620
Opened 2019-03-09 16:58 UTC by ArtificialQualia

- [x] closes #25608
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

I did not use an oxford comma in the error description, which is how it was written in the issue's expected result.

2019-03-09 18:05 UTC, gfyoung commented on pandas/io/formats/html.py
> +                                'not {typ}'.format(typ=type(self.classes)))
In general, we do use the Oxford comma in this codebase. 😉

2019-03-09 18:05 UTC, gfyoung commented on doc/source/whatsnew/v0.24.2.rst
> --
Move to 0.25.0.

2019-03-09 18:34 UTC, gfyoung approved these changes
Nice!

cc @jreback

2019-03-10 15:46 UTC, jreback requested changes

2019-03-10 15:46 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- Bug in converting to HTML when using an invalid type for ``classes`` parameter raised ``AsseertionError`` instead of ``TypeError`` (:issue:`25608`)
an you reference ``:meth:DataFrame.to_html``; this is not a bug, rather a change.

2019-03-10 21:36 UTC, jreback approved these changes

2019-03-10 21:36 UTC, merged

2019-03-10 21:36 UTC, jreback commented
thanks @ArtificialQualia