CLN: handle EAs and fast path (no bounds checking) in safe_sort
pandas-dev/pandas pull request #25696
Opened 2019-03-12 20:33 UTC by jorisvandenbossche

This is a possible alternative solution to what we have been discussing in https://github.com/pandas-dev/pandas/pull/25592.

This moves the logic into `safe_sort`, with:

- adding a `check_outofbounds` keyword to disable extra checks (otherwise the performance benefit of `take_1d` is lost)
- fixing `safe_sort` to work for EAs

The `check_outofbounds` make it a bit more complicated, but without it, we can't benefit of the performance improvement for which `take_1d` was used originally in `factorize`.

(another solution is to simply decide that this performance improvement is not worth this extra code, and we simply use the current `safe_sort` (but fixed to work for EAs) in `factorize`)

Need to add some more tests for the combination of EAs with a custom na_sentinel (a case that is currently broken)

2019-03-12 20:34 UTC, pep8speaks commented
Hello @jorisvandenbossche! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/core/sorting.py`](https://github.com/pandas-dev/pandas/blob/c6203cbe29ff8eeb31f9394b92d901651624f63d/pandas/core/sorting.py):

> [Line 408:72](https://github.com/pandas-dev/pandas/blob/c6203cbe29ff8eeb31f9394b92d901651624f63d/pandas/core/sorting.py#L408): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2019-03-12 20:53 UTC, jreback requested changes

2019-03-12 20:53 UTC, jreback commented on pandas/core/sorting.py
> +    check_outofbounds : bool, default True
this is not a bad name but not consistent across pandas, we use verify elsewhere.

2019-03-12 20:53 UTC, jreback commented on pandas/core/sorting.py
> +    if na_sentinel == -1:
would rather just fix take_1d

2019-03-20 01:34 UTC, jreback requested changes

2019-03-20 01:34 UTC, jreback commented on pandas/core/sorting.py
> +    check_outofbounds : bool, default True
can you update & add a versionadded tag

2019-03-20 01:34 UTC, jreback commented on pandas/core/sorting.py
> +    if (PY3 and not isinstance(values, ABCExtensionArray)
hah no more PY3 needed!

2019-03-20 01:34 UTC, jreback commented on pandas/core/sorting.py
> +    if (PY3 and not isinstance(values, ABCExtensionArray)
use is_extension_array

2019-04-05 07:10 UTC, jorisvandenbossche commented
Coming back to this

> would rather just fix take_1d

For `take_1d` itself, I am not sure it makes a lot of sense to support this. Currently, it is by definition that -1 values in the `indexer` passed to take signal missing values. The only use case for having this configurable would be this one, while it complicates the interface throughout pandas (eg also EAs would need to support this, as `take_1d` dispatch to them)

2019-04-20 16:59 UTC, jreback commented
can you merge master

2019-05-06 18:14 UTC, jorisvandenbossche commented
@jreback conflicts resolved, if you can take another look

2019-05-07 01:01 UTC, jreback approved these changes

2019-05-07 01:01 UTC, merged

2019-05-07 01:01 UTC, jreback commented
thanks @jorisvandenbossche nice cleanup & tests.