[BUG] Construction of Interval restricted to numeric/ Timestamp/ Timedelta (#23013)
pandas-dev/pandas pull request #25768
Opened 2019-03-18 14:57 UTC by makbigc

-  closes #23013
-  1 test replaced
-  passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
-  whatsnew entry

2019-03-18 23:00 UTC, jschendel requested changes
Thanks!  The issue itself didn't get much discussion, and I'm not sure if everyone will agree on this behavior, so will be interesting to see what comments arise here.  I support this change, as it's consistent with what we allow for arrays, and as a result eliminates some weird `Interval` specific corner cases.

2019-03-19 18:20 UTC, jreback commented
pls merge master

2019-03-21 07:02 UTC, makbigc commented on pandas/tests/scalar/interval/test_interval.py
> -        msg = 'cannot compute length between .* and .*'
Let's do it in a new PR.

2019-03-22 11:52 UTC, jreback commented
lgtm. @jschendel

2019-03-23 02:08 UTC, jschendel approved these changes

2019-03-23 02:08 UTC, merged

2019-03-23 02:09 UTC, jschendel commented
thanks @makbigc