Add regression test for #23986
pandas-dev/pandas pull request #25931
Opened 2019-03-30 22:57 UTC by alexcwatt

- [x] closes #23986 by adding regression test
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-03-30 23:49 UTC, WillAyd requested changes
Minor nit but otherwise lgtm. @mroeschke

2019-03-30 23:49 UTC, WillAyd commented on pandas/tests/indexes/datetimes/test_construction.py
> +    def test_constructor_invalid_dtype(self, dtype):
Can you just append `_raises` to the end of this? Convention we have for tests

2019-03-31 03:13 UTC, WillAyd approved these changes

2019-03-31 18:00 UTC, merged

2019-03-31 18:01 UTC, mroeschke commented
Thanks @alexcwatt!

If you're up for it, we have more issues that could be closed by adding regression tests. https://github.com/pandas-dev/pandas/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+label%3A%22Needs+Tests%22