to_html formatter not called for float values in a mixed-type column
pandas-dev/pandas pull request #25983
Opened 2019-04-03 23:12 UTC by simonjayhawkins

- [ ] closes #13021
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

can't shortcut completely without changing existing tested behaviour in a couple of tests.

for instance, the expected output for `test_to_string_with_formatters` in `pandas\tests\io\formats\test_format.py` has two spaces between float and object column, whereas shortcuting would only have one (the same as between the int and float columns)

```
  int  float    object
0 0x1 [ 1.0]  -(1, 2)-
1 0x2 [ 2.0]    -True-
2 0x3 [ 3.0]   -False-
```
if it's OK to change a couple of tests, we can remove this subtle leading_space bug in this PR.

2019-04-04 01:31 UTC, WillAyd requested changes

2019-04-04 01:31 UTC, WillAyd commented on pandas/tests/io/formats/test_to_html.py
> +        return x if type(x) is str else '${:,.0f}'.format(x)
Use isinstance instead of type

2019-04-04 01:31 UTC, WillAyd commented on pandas/tests/io/formats/test_to_html.py
> +    assert '$10' in result
Can we make a better assertion here? I understand the original issue pertained to floats only but probably doesn't hurt to make an assertion around the other values here as well

2019-04-04 12:30 UTC, jreback requested changes
looks fine, ex @WillAyd comments, this fully replicates the original issue?

2019-04-04 19:34 UTC, simonjayhawkins commented
>  this fully replicates the original issue?

yes.

2019-04-04 20:27 UTC, jreback approved these changes

2019-04-04 20:27 UTC, jreback commented
lgtm. ping on green.

2019-04-04 21:55 UTC, simonjayhawkins commented
green. but not all checks ran. needs a restart?

2019-04-05 00:11 UTC, jreback commented
hmm yeah, merge master and push again.

2019-04-05 01:03 UTC, simonjayhawkins commented
gbq failure, otherwise good.

2019-04-05 01:08 UTC, jreback commented
yeah working on fixing gbq now

2019-04-05 02:26 UTC, merged

2019-04-05 02:27 UTC, jreback commented
thanks @simonjayhawkins

2019-04-05 10:52 UTC, jreback commented
I reverted this: https://github.com/pandas-dev/pandas/commit/fc5f292377412fa7bc824d2c2cc69f2ae45bd7f9 as CI is failing