DEPR: Deprecate sort=None for union and implement sort=True
pandas-dev/pandas pull request #25980
Opened 2019-04-03 21:39 UTC by reidy-p

- [ ] progress towards #24471 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

This is a WIP pull request because I wanted to make sure I'm going in the right direction before continuing.

In #24959 it was agreed that the default for some of the set operations should be ``sort=None`` for backwards compatibility in 0.24.1. ``sort=None`` generally tries to sort in all cases _except_ when the two indices are equal or one of the indices is empty. This meant that in a future release we could introduce a proper ``sort=True`` which would try to sort in all cases and change the default to ``sort=False`` in cases.

Are there any potential problems with this plan? 

In this PR I have started to deprecate ``sort=None`` for ``Index.union`` and to introduce ``sort=True``. ``sort=None`` is currently the default for this set operation so a ``FutureWarning`` will be given by default. I will make similar changes to the ``union`` method in all the index classes if this is the approach we want to take.

2019-04-04 02:06 UTC, WillAyd requested changes

2019-04-04 02:06 UTC, WillAyd commented on pandas/tests/indexes/test_base.py
> +        with tm.assert_produces_warning(warning):
I think it would just be easier to move the warnings to a separate test since this will eventually be ripped out anyway

2019-06-27 22:13 UTC, jreback requested changes
can you merge master when you have a chance

2019-06-27 22:13 UTC, jreback commented on pandas/bin/activate
> +/Users/paul/anaconda/bin/activate
looks like some extra files got included

2019-08-28 16:17 UTC, closed without merging