GH26013 Fix type annotations in pandas/tseries/*
pandas-dev/pandas pull request #26014
Opened 2019-04-06 16:05 UTC by gwrome

- [X] closes #26013
- [X] tests passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [  ] whatsnew entry

Part of #25882

2019-04-06 16:23 UTC, WillAyd requested changes

2019-04-06 16:23 UTC, WillAyd commented on pandas/tseries/frequencies.py
> +_offset_map = {}  # type: Dict
Can you be more explicit about the elements contained within the Dict?

2019-04-06 16:23 UTC, WillAyd commented on pandas/tseries/holiday.py
> +    rules = []  # type: List
More explicit here as well

2019-04-07 21:35 UTC, jreback commented
lgtm. @WillAyd

2019-04-07 23:19 UTC, WillAyd approved these changes

2019-04-07 23:19 UTC, merged

2019-04-07 23:19 UTC, WillAyd commented
Thanks @gwrome !