Replace wildcardimports in toplevelinit as precursor for reshape,stata,io p rs #25936 #25940 #25939
pandas-dev/pandas pull request #26019
Opened 2019-04-07 15:03 UTC by ryankarlos

- [x] closes ##25932, #25933, #25934
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-04-07 15:07 UTC, ryankarlos commented
@WillAyd Since im working on PRs #25936 #25940 #25939  which all depend on this top level import - thought it would make sense to replace wildcard imports for stata, reshape and io modules at the same time.

2019-04-07 15:25 UTC, WillAyd commented
I think you can still import from the apis exposed by each package but just need to list out the object that you are pulling in. Does that no work with Mypy?

2019-04-07 16:11 UTC, ryankarlos commented
So the only error that mypy throws is this - 
`pandas/__init__.py:70: error: Module 'pandas._libs' has no attribute 'join'`

Theres a lot of other modules in those apis which do not particularly affect the reshape, stata PRs that i am working on but Ive I've included them in in case they need to be imported via top level from other modules in the future.

2019-04-07 21:34 UTC, jreback requested changes
this must be *very* precisely done, IOW importing names explicity as we have tests which exactly guaranteee these imports are no more and no less what is actually imported

2019-04-07 21:34 UTC, jreback commented on pandas/__init__.py
> +from pandas.core.internals import BlockManager, _safe_reshape, make_block
these are internal and should not be imported

2019-04-07 21:34 UTC, jreback commented on pandas/__init__.py
> +from pandas._libs import join
this is internal

2019-04-07 21:34 UTC, jreback commented on pandas/__init__.py
> -from pandas.io.api import *
you need to do this one as well

2019-04-07 23:23 UTC, ryankarlos commented
@jreback Thanks for the review, i've pushed latest changes - hopefully they pass now as I think i have the exact number of imports in.

2019-04-08 16:05 UTC, WillAyd requested changes
Looks like there is still one wildcard import for NumPy compat - can you take a look at that here?

2019-04-09 11:23 UTC, jreback requested changes

2019-04-09 11:23 UTC, jreback commented on pandas/__init__.py
> +from pandas.core.api import (
can you organize these by section, e.g. something like

```
from pandas.core.api import (
    # dtype
    Int8Dtype.........

   # indexes
    Int64Index.....

  # tseries
   NaT, Period.....

  # conversion
   to_numeric, to_datetime...

  # missing
   isna, isnul.....

  # misc
  np, TimeGrouper....

2019-04-09 11:23 UTC, jreback commented on pandas/__init__.py
> +    read_clipboard, ExcelFile, ExcelWriter, read_excel,
can you sort these

2019-04-09 22:48 UTC, pep8speaks commented
Hello @ryankarlos! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/__init__.py`](https://github.com/pandas-dev/pandas/blob/2b3afa5598decc3df72fa5ee0a2bd892c8fb35b5/pandas/__init__.py):

> [Line 48:5](https://github.com/pandas-dev/pandas/blob/2b3afa5598decc3df72fa5ee0a2bd892c8fb35b5/pandas/__init__.py#L48): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 53:5](https://github.com/pandas-dev/pandas/blob/2b3afa5598decc3df72fa5ee0a2bd892c8fb35b5/pandas/__init__.py#L53): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 56:5](https://github.com/pandas-dev/pandas/blob/2b3afa5598decc3df72fa5ee0a2bd892c8fb35b5/pandas/__init__.py#L56): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 61:5](https://github.com/pandas-dev/pandas/blob/2b3afa5598decc3df72fa5ee0a2bd892c8fb35b5/pandas/__init__.py#L61): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 66:5](https://github.com/pandas-dev/pandas/blob/2b3afa5598decc3df72fa5ee0a2bd892c8fb35b5/pandas/__init__.py#L66): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 69:5](https://github.com/pandas-dev/pandas/blob/2b3afa5598decc3df72fa5ee0a2bd892c8fb35b5/pandas/__init__.py#L69): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 71:46](https://github.com/pandas-dev/pandas/blob/2b3afa5598decc3df72fa5ee0a2bd892c8fb35b5/pandas/__init__.py#L71): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 90:5](https://github.com/pandas-dev/pandas/blob/2b3afa5598decc3df72fa5ee0a2bd892c8fb35b5/pandas/__init__.py#L90): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 93:5](https://github.com/pandas-dev/pandas/blob/2b3afa5598decc3df72fa5ee0a2bd892c8fb35b5/pandas/__init__.py#L93): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 96:5](https://github.com/pandas-dev/pandas/blob/2b3afa5598decc3df72fa5ee0a2bd892c8fb35b5/pandas/__init__.py#L96): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 99:5](https://github.com/pandas-dev/pandas/blob/2b3afa5598decc3df72fa5ee0a2bd892c8fb35b5/pandas/__init__.py#L99): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 102:5](https://github.com/pandas-dev/pandas/blob/2b3afa5598decc3df72fa5ee0a2bd892c8fb35b5/pandas/__init__.py#L102): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 105:5](https://github.com/pandas-dev/pandas/blob/2b3afa5598decc3df72fa5ee0a2bd892c8fb35b5/pandas/__init__.py#L105): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 109:5](https://github.com/pandas-dev/pandas/blob/2b3afa5598decc3df72fa5ee0a2bd892c8fb35b5/pandas/__init__.py#L109): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

2019-04-10 01:09 UTC, ryankarlos commented
@jreback @WillAyd pushed latest changes through

2019-04-10 01:18 UTC, jreback approved these changes

2019-04-10 01:18 UTC, merged

2019-04-10 01:18 UTC, jreback commented
thanks @ryankarlos

2019-04-10 01:19 UTC, jreback commented
if you’d merge master and update any typing PRs can get them in

2019-04-10 02:23 UTC, ryankarlos commented
Thanks @jreback , pushed latest updates for dependant PRs #25936 #25940 #25939