BUG: Replace internal use of loc with reindex in DataFrame append
pandas-dev/pandas pull request #26022
Opened 2019-04-07 17:40 UTC by cbertinato

The issue here was that the DataFrame append method was using .loc, which only throws a warning now, but would eventually throw a KeyError whenever that went into effect. Just swapped out that use of .loc for .reindex.

- [x] closes #22252
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2019-04-07 18:23 UTC, jreback requested changes
always write tests first; how else would know if this works?

2019-04-07 23:10 UTC, cbertinato commented
Sorry about that. In progress.

2019-04-08 03:38 UTC, gfyoung commented on pandas/tests/frame/test_combine_concat.py
> +
Separate out test and reference issue number as a comment under test function `def`.

2019-04-08 12:49 UTC, cbertinato commented
Prior to this fix, the test still would have passed, but a FutureWarning would have been thrown, and eventually a KeyError. Should I also throw in a check that a FutureWarning and/or KeyError is not thrown?

2019-04-08 15:32 UTC, gfyoung commented
> Should I also throw in a check that a FutureWarning and/or KeyError is not thrown?

The way that the test is written is fine.

2019-04-09 11:46 UTC, jreback requested changes

2019-04-09 11:46 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- Bug in which :meth:`DataFrame.append` produced a warning indicating that a KeyError will be thrown in the future when the data to be appended contains new columns (:issue:`22252`).
double backticks on KeyError. make this clear that this warning should not have been shown.

2019-04-09 11:46 UTC, jreback commented on pandas/tests/frame/test_combine_concat.py
> +        # GH22252
make this a new test

2019-04-19 18:07 UTC, cbertinato commented
Anything else to do here?

2019-04-19 20:28 UTC, jreback requested changes
test comment, ping on green.

2019-04-19 20:28 UTC, jreback commented on pandas/tests/frame/test_combine_concat.py
> +        dicts = [{'foo': 9}, {'bar': 10}]
can you put an assert_produces_warning(None) around this

2019-04-20 16:47 UTC, jreback approved these changes

2019-04-20 16:47 UTC, jreback commented
lgtm. can you merge master; ping on green.

2019-04-21 07:29 UTC, cbertinato commented
All green!

2019-04-21 16:21 UTC, merged

2019-04-21 16:21 UTC, jreback commented
thanks @cbertinato