Fixed issue #13503
pandas-dev/pandas pull request #26055
Opened 2019-04-11 20:37 UTC by yhaque1213

- [ ] closes #13503 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry
Added axis parameter to the constructor call in the count function, fixing the original issue in #13503. This fix works for the example given in the issue. This does not fix the problem addressed by jorisvandenbossche, as that seems to be a type issue.

2019-04-11 20:52 UTC, jreback commented
tests pls

2019-04-12 02:49 UTC, pep8speaks commented
Hello @yhaque1213! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/test_window.py`](https://github.com/pandas-dev/pandas/blob/c64c76a30d1bd32b415010a297b5af6e15332445/pandas/tests/test_window.py):

> [Line 672:31](https://github.com/pandas-dev/pandas/blob/c64c76a30d1bd32b415010a297b5af6e15332445/pandas/tests/test_window.py#L672): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 672:45](https://github.com/pandas-dev/pandas/blob/c64c76a30d1bd32b415010a297b5af6e15332445/pandas/tests/test_window.py#L672): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 674:49](https://github.com/pandas-dev/pandas/blob/c64c76a30d1bd32b415010a297b5af6e15332445/pandas/tests/test_window.py#L674): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 674:80](https://github.com/pandas-dev/pandas/blob/c64c76a30d1bd32b415010a297b5af6e15332445/pandas/tests/test_window.py#L674): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (108 > 79 characters)
> [Line 679:52](https://github.com/pandas-dev/pandas/blob/c64c76a30d1bd32b415010a297b5af6e15332445/pandas/tests/test_window.py#L679): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 679:80](https://github.com/pandas-dev/pandas/blob/c64c76a30d1bd32b415010a297b5af6e15332445/pandas/tests/test_window.py#L679): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 79 characters)
> [Line 680:80](https://github.com/pandas-dev/pandas/blob/c64c76a30d1bd32b415010a297b5af6e15332445/pandas/tests/test_window.py#L680): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)

2019-04-12 06:01 UTC, gfyoung commented on pandas/tests/test_window.py
> +        assert_equal(df.rolling(2, axis='columns').count(), df_correct_column_count)
Use `tm.assert_frame_equal` instead of `assert_equal`.

2019-04-12 23:17 UTC, yhaque1213 commented
@gfyoung 
I updated the tests to replace my calls to `assert_equal` with `tm.assert_frame_equal`, and I also modified it to pass pep8 checks. My initial changes to fix the issue, without any tests, was passing all of the builds.

Once I added my tests, however, I started failing pandas-dev.pandas and pandas-dev.pandas (Linux py35_compat), and I'm having some trouble figuring out what's causing this to happen.

More specifically, it seems to be an error with the `test_drop_duplicates_categorical_non_bool` in `pandas/tests/series/test_analytics.py`, but I have no idea why this specific test would be failing because of adding my test, `test_count_axis`. 

Do you have any advice?

2019-04-13 01:05 UTC, gfyoung commented
@yhaque1213 : Have you rebased onto the most recent `master`?  Try that and see if it goes away.  Otherwise, we'll look into seeing if we can remove (or weaken) the `xfail` on those tests.

2019-04-15 22:24 UTC, yhaque1213 commented
@gfyoung : that seemed to do the trick - my latest update is passing all of the checks. Thank you, and please let me know if there's anything else you'd like me to add!

2019-04-16 04:17 UTC, gfyoung commented
@yhaque1213 : Don't forget the `whatsnew` entry

2019-04-16 13:07 UTC, jreback requested changes
pls add a whatsnew note as well; bug fixes groupby/rolling section

2019-04-16 13:07 UTC, jreback commented on pandas/tests/test_window.py
> +        tm.assert_frame_equal(df.rolling(2).count(), df_row)
use 

result=
expected=
tm.assert_frame_equal

so df_row looks like your expected

2019-04-16 13:07 UTC, jreback commented on pandas/tests/test_window.py
> +        df_col = DataFrame({'x': [1.0, 1.0, 1.0], 'y': [2.0, 2.0, 2.0]})
same here

2019-04-16 13:07 UTC, jreback commented on pandas/tests/test_window.py
> +    def test_count_axis(self):
rename this to test_rolling_axis_count, rename the test right above to test_rolling_axis_sum

2019-04-19 20:24 UTC, jreback requested changes

2019-04-19 20:24 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- Bug in :meth:`pandas.core.window._Rolling_and_Expanding.count` that did not include axis parameter in constructor call (:issue:`13503`)
this is not a public method, use ``:meth:`pandas.core.window.Rolling.count`` and another for Expanding

2019-04-19 20:24 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- Bug in :meth:`pandas.core.window._Rolling_and_Expanding.count` that did not include axis parameter in constructor call (:issue:`13503`)
this is also confusing over what you are saying, can you reword, something like '....was previously ignoring the ``axis`` keyword'

2019-04-19 20:24 UTC, jreback commented on pandas/tests/test_window.py
> +    def test_rolling_axis_count(self):
use the axis_frame fixture which resoles to rows/columns/0/1

2019-04-19 21:33 UTC, yhaque1213 commented
I made the changes to the test and to the docs, but it seems like these Azure pipelines checks are passing arbitrarily. For instance, after fixing a typo in a comment (commit #12065b6) we passed 10/10 tests, while the previous commit only passed 8 (commit #41ae7fe). This happened even with rebasing before each push, therefore, we aren't sure what to change for this last commit to get it to pass all 10.

2019-04-20 16:00 UTC, jreback commented
> I made the changes to the test and to the docs, but it seems like these Azure pipelines checks are passing arbitrarily. For instance, after fixing a typo in a comment (commit #12065b6) we passed 10/10 tests, while the previous commit only passed 8 (commit #41ae7fe). This happened even with rebasing before each push, therefore, we aren't sure what to change for this last commit to get it to pass all 10.

CI is not 'arbitrary', rather there was an upstream change that broke things.

2019-04-20 17:09 UTC, jreback commented
pls merge master and ping on green.

2019-04-20 17:10 UTC, jreback requested changes

2019-04-20 17:10 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- Bug in :meth:`pandas.core.window.Expanding.count` was previously ignoring the axis keyword (:issue:`13503`)
make a single entry here (just combine the lines)

2019-04-20 17:10 UTC, jreback commented on pandas/tests/test_window.py
> +        if axis == 0:
this is not correct (should your test have broken?)

``if axis in [0, 'index']`` is what you need

2019-04-21 00:32 UTC, yhaque1213 commented
@jreback : Just made the changes requested, and I'm passing all the checks now!

2019-04-21 16:29 UTC, jreback requested changes
looks good; edit the whatsnew; ping on green.

2019-04-21 16:29 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- Bug in :func:`idxmax` and :func:`idxmin` on :meth:`DataFrame.groupby` with datetime column would return incorrect dtype (:issue:`25444`, :issue:`15306`)
looks like this was picked up somehow, pls remove

2019-04-22 21:57 UTC, yhaque1213 commented
I've made all of the changes that were requested, but I'm still having trouble getting all of the checks to pass. I've tried rebasing and merging multiple times, but nothing has been working

2019-04-22 22:06 UTC, jreback commented
try

git merge upstream/master

2019-04-22 22:20 UTC, WillAyd commented
There's a failure in the doc checks that should be unrelated. Not sure if its a versioning thing or a commit to master. Taking a look now

2019-04-22 22:27 UTC, jreback commented
this was cleared yesterday

2019-04-22 23:17 UTC, yhaque1213 commented
Latest push was with merging with upstream/master, but it looks like the checks are still failing in the same ways as before. Sorry I'm not sure if I'm doing something wrong, but I've tried everything I could think of

2019-04-23 13:05 UTC, jreback approved these changes

2019-04-23 13:06 UTC, jreback requested changes
lgtm. tiny typo. pls rebase on master which is green now.

2019-04-23 13:06 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- Bug in :meth:`pandas.core.window.Rolling.count` and `pandas.core. window.Expanding.count` was previously ignoring the axis keyword (:issue:`13503`)
can you remove the space here pandas.core.window....

2019-04-26 01:18 UTC, jreback commented
small typo plus can i merge master ; ping on green

2019-04-26 19:27 UTC, yhaque1213 commented
@jrebeck: I removed the typo - I'm passing all the checks now!

2019-04-28 16:45 UTC, jreback approved these changes

2019-04-28 16:45 UTC, merged

2019-04-28 16:45 UTC, jreback commented
thanks @yhaque1213