day_of_week
pandas-dev/pandas pull request #26094
Opened 2019-04-15 03:17 UTC by Violet-XiaoWeiHuang

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-04-15 03:17 UTC, pep8speaks commented
Hello @Violet-XiaoWeiHuang! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`asv_bench/benchmarks/timestamp.py`](https://github.com/pandas-dev/pandas/blob/e8bf846edb7be90f2dbaa1da7a806b1f9d6e0f82/asv_bench/benchmarks/timestamp.py):

> [Line 50:13](https://github.com/pandas-dev/pandas/blob/e8bf846edb7be90f2dbaa1da7a806b1f9d6e0f82/asv_bench/benchmarks/timestamp.py#L50): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented

2019-04-15 03:32 UTC, mroeschke commented
As mentioned https://github.com/pandas-dev/pandas/pull/25924#issuecomment-478132760, `dayofweek` needs to be deprecated first. This can't just be replaced.

2019-04-20 18:26 UTC, jreback requested changes

2019-04-20 18:26 UTC, jreback commented on asv_bench/benchmarks/timestamp.py
> +    def time_day_of_week(self, tz, freq):
indent error here

2019-04-20 18:26 UTC, jreback commented on asv_bench/benchmarks/timestamp.py
>      def time_dayofweek(self, tz, freq):
you can remove the original one

2019-04-20 18:26 UTC, jreback commented on doc/redirects.csv
> +generated/pandas.DatetimeIndex.day_of_week,../reference/api/pandas.DatetimeIndex.day_of_week
i don't think you need to add the new one, we don't have original pages for it

2019-04-20 18:26 UTC, jreback commented on doc/source/reference/arrays.rst
>     Timestamp.dayofweek
you can remove the original from the docs

2019-04-20 18:26 UTC, jreback commented on doc/source/whatsnew/v0.16.2.rst
> +- Bug in ``NaT`` raises ``AttributeError`` when accessing to ``daysinmonth``, ``dayofweek``, ``day_of_week`` properties. (:issue:`10096`)
don't change the original what's new notes

2019-04-20 18:26 UTC, jreback commented on pandas/_libs/tslibs/period.pyx
>      def dayofweek(self):
just do

dayofweek = day_of_week

2019-05-12 21:15 UTC, jreback commented
can you merge master and update per comments

2019-06-08 20:38 UTC, jreback commented
closing as stale. this is pretty close, so ping if you'd like to continue.

2019-06-08 20:38 UTC, closed without merging