Improve documentation for assert_frame|series_equal #26101
pandas-dev/pandas pull request #26106
Opened 2019-04-16 10:58 UTC by sandepp123

- [ ] closes #26101 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-04-17 15:56 UTC, WillAyd requested changes

2019-04-17 15:56 UTC, WillAyd commented on pandas/util/testing.py
> +        When comparing two numbers, if the first number has magnitude less
These belong as part of the description of `check_less_precise`

2019-04-21 16:00 UTC, jreback commented
lgtm. @WillAyd

2019-04-22 15:31 UTC, WillAyd approved these changes

2019-04-22 15:31 UTC, merged

2019-04-22 15:31 UTC, WillAyd commented
Thanks @sandepp123