Include missing data count in pd.DataFrame.describe()
pandas-dev/pandas pull request #26102
Opened 2019-04-15 16:31 UTC by alexander-ponomaroff

- [x] closes #21689
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2019-04-15 16:37 UTC, alexander-ponomaroff commented
I would like to receive some feedback on the added summary statistic to `describe()`. It's between having `missing`, which counts the number of missing values, and having `length`, which will include missing values and if the user wants to get the missing summary, they will have to subtract `count` from `length`. I bring this up because @jreback asked for `length` in the issue, but the creator of the issue asked for `missing`. In my opinion, I think that the way I currently did it with `missing` is better.

Please let me know what everyone thinks, and once that's out of the way, I will proceed to change the documentation in the function to reflect the new enhancement.

2019-04-15 18:47 UTC, WillAyd commented
Missing is not a method that exists in our API so I don't think it should be added here. Size seems more appropriate to me

2019-04-26 18:31 UTC, WillAyd requested changes
Can you merge master and address comment?

2019-04-27 17:21 UTC, alexander-ponomaroff commented
@WillAyd Thanks for the feedback, let me know if you agree with the change now that I changed 'missing' to 'size'. If all good, I will go ahead and fix other tests that are failing due to the added functionality.

2019-04-28 16:43 UTC, jreback requested changes
I am only +0 on adding this.

2019-04-28 16:43 UTC, jreback commented on pandas/core/generic.py
>              d = ([series.count(), series.mean(), series.std(), series.min()] +
should be the first arg

2019-04-28 16:43 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- Added enhancement to :func:`pd.DataFrame.describe` to include size as one of the summary statistics (:issue:`21689`)
this needs a separate subsection, its actually a fairly large API change.

2019-05-12 21:13 UTC, jreback commented
can you update per comments

2019-05-19 22:10 UTC, alexander-ponomaroff commented
Sorry for the long delay, I was away on vacation. I will be making the updates within the next couple of days.

2019-06-27 03:35 UTC, jreback commented
closing as stale, ping if you'd like to continue.

2019-06-27 03:35 UTC, closed without merging

2022-10-19 22:33 UTC, drkarthi commented
@jreback @WillAyd I am interested in having the number of rows in the dataframe as an output in describe(). I assume that is what is being called `size` here. Is there still interest to have this added? I am happy to pick up from where @alexander-ponomaroff left off

2022-10-26 19:02 UTC, drkarthi commented
@jbrockmendel @mroeschke I see you are active contributors right now. do you you have any objections to adding the number of rows in the dataframe as an output of describe()

2022-10-29 17:55 UTC, jbrockmendel commented
i have no opinion on describe.  if mroeschke expresses an opinion ill agree with that, otherwise ill agree with jreback at +0.