CLN: Remove unnecessary io function returns
pandas-dev/pandas pull request #26238
Opened 2019-04-29 17:12 UTC by ihsansecer

These functions return a function either with empty return statement or doesn’t return. It causes docstring validation error with type RT01 (See #26234).

- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2019-04-29 18:42 UTC, WillAyd requested changes
Minor comment but otherwise lgtm

2019-04-29 18:42 UTC, WillAyd commented on pandas/core/frame.py
> +        gbq.to_gbq(self, destination_table, project_id=project_id,
Would be good to take this all the way through. `pandas.io.gbq.to_gbq` also has a return statement, but if that actually doesn't return anything should be removed there as well

2019-04-30 01:43 UTC, WillAyd approved these changes
lgtm @jreback

2019-04-30 13:02 UTC, merged

2019-04-30 13:02 UTC, jreback commented
thanks @ihsansecer