Remove register
pandas-dev/pandas pull request #26264
Opened 2019-05-02 04:00 UTC by WillAyd

- [X] closes #26263
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

ASV results show no difference:

```sh
BENCHMARKS NOT SIGNIFICANTLY CHANGED.``
```

As I am fairly certain this keyword was being entirely ignored by the compilers anyway (see issue for reasoning)

2019-05-02 04:01 UTC, gfyoung approved these changes

2019-05-02 04:25 UTC, jbrockmendel commented on doc/source/whatsnew/v0.25.0.rst
> +- Removed usage of register keyword in C extension modules (:issue:`26263`)
Quoted around register?

2019-05-02 11:47 UTC, jreback commented
these were all just added here: https://github.com/pandas-dev/pandas/pull/25784/files

cc @vnlitvin @anmyachev

2019-05-02 11:47 UTC, jreback requested changes
see comments; this needs benchmarking

2019-05-02 14:25 UTC, anmyachev commented
@WillAyd try running: `asv continuous -f 1.05 origin/master remove-register -b io.csv -a sample_time=2 -a warmup_time=2`

2019-05-02 17:11 UTC, WillAyd commented
Ran that and benchmarks still showed no change:

<details>

```sh
$ asv continuous -f 1.05 7fafb356549f1c52a9896429ce0241487f42bea9 a491c2b217b69208e810c23ce6db7a21d033fd06 -b io.csv -a sample_time=2 -a warmup_time=2
· Creating environments
· Discovering benchmarks.
·· Uninstalling from conda-py3.6-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-pytest-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt.
·· Installing a491c2b2 <remove-register~2> into conda-py3.6-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-pytest-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt..
· Running 36 total benchmarks (2 commits * 1 environments * 18 benchmarks)
[  0.00%] · For pandas commit 7fafb356 <master~2> (round 1/2):
[  0.00%] ·· Building for conda-py3.6-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-pytest-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt...
[  0.00%] ·· Benchmarking conda-py3.6-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-pytest-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt
[  1.39%] ··· Running (io.csv.ReadCSVCategorical.time_convert_direct--)...
[  5.56%] ··· Running (io.csv.ReadCSVDInferDatetimeFormat.time_read_csv--).
[  6.94%] ··· Running (io.csv.ReadCSVFloatPrecision.time_read_csv--).
[  8.33%] ··· Running (io.csv.ReadCSVFloatPrecision.time_read_csv_python_engine--).
[ 11.11%] ··· Running (io.csv.ReadCSVParseDates.time_baseline--)...
[ 15.28%] ··· Running (io.csv.ReadCSVSkipRows.time_skipprows--)..
[ 18.06%] ··· Running (io.csv.ReadUint64Integers.time_read_uint64--)...
[ 22.22%] ··· Running (io.csv.ToCSV.time_frame--).
[ 23.61%] ··· Running (io.csv.ToCSVDatetime.time_frame_date_formatting--)...
[ 25.00%] · For pandas commit a491c2b2 <remove-register~2> (round 1/2):
[ 25.00%] ·· Building for conda-py3.6-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-pytest-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt...
[ 25.00%] ·· Benchmarking conda-py3.6-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-pytest-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt
[ 26.39%] ··· Running (io.csv.ReadCSVCategorical.time_convert_direct--)...
[ 30.56%] ··· Running (io.csv.ReadCSVDInferDatetimeFormat.time_read_csv--).
[ 31.94%] ··· Running (io.csv.ReadCSVFloatPrecision.time_read_csv--).
[ 33.33%] ··· Running (io.csv.ReadCSVFloatPrecision.time_read_csv_python_engine--).
[ 36.11%] ··· Running (io.csv.ReadCSVParseDates.time_baseline--)...
[ 40.28%] ··· Running (io.csv.ReadCSVSkipRows.time_skipprows--)..
[ 43.06%] ··· Running (io.csv.ReadUint64Integers.time_read_uint64--)...
[ 47.22%] ··· Running (io.csv.ToCSV.time_frame--).
[ 48.61%] ··· Running (io.csv.ToCSVDatetime.time_frame_date_formatting--)...
[ 50.00%] · For pandas commit a491c2b2 <remove-register~2> (round 2/2):
[ 50.00%] ·· Benchmarking conda-py3.6-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-pytest-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt
[ 51.39%] ··· io.csv.ReadCSVCategorical.time_convert_direct                                                                 42.1±0.5ms
[ 52.78%] ··· io.csv.ReadCSVCategorical.time_convert_post                                                                     59.2±1ms
[ 54.17%] ··· io.csv.ReadCSVComment.time_comment                                                                            28.8±0.2ms
[ 55.56%] ··· io.csv.ReadCSVDInferDatetimeFormat.time_read_csv                                                                      ok
[ 55.56%] ··· ======================= ============ ============= =============
              --                                       format
              ----------------------- ----------------------------------------
               infer_datetime_format     custom       iso8601         ymd
              ======================= ============ ============= =============
                        True           6.38±0.1ms   2.71±0.07ms   2.69±0.06ms
                       False            108±2ms     2.17±0.09ms    2.12±0.1ms
              ======================= ============ ============= =============

[ 56.94%] ··· io.csv.ReadCSVFloatPrecision.time_read_csv                                                                            ok
[ 56.94%] ··· ===== ============= ============= ================ ============= ============= ================
              --                                    decimal / float_precision
              ----- -----------------------------------------------------------------------------------------
               sep     . / None      . / high    . / round_trip     _ / None      _ / high    _ / round_trip
              ===== ============= ============= ================ ============= ============= ================
                ,    2.01±0.07ms   1.89±0.08ms     2.92±0.1ms      2.32±0.1ms   2.35±0.06ms    2.34±0.06ms
                ;    2.22±0.04ms   2.07±0.04ms     2.94±0.1ms     2.29±0.05ms   2.28±0.07ms    2.20±0.03ms
              ===== ============= ============= ================ ============= ============= ================

[ 58.33%] ··· io.csv.ReadCSVFloatPrecision.time_read_csv_python_engine                                                              ok
[ 58.33%] ··· ===== ============= ============= ================ ============= ============= ================
              --                                    decimal / float_precision
              ----- -----------------------------------------------------------------------------------------
               sep     . / None      . / high    . / round_trip     _ / None      _ / high    _ / round_trip
              ===== ============= ============= ================ ============= ============= ================
                ,    4.51±0.07ms   4.61±0.08ms    4.57±0.05ms     3.99±0.03ms   4.08±0.07ms     4.02±0.1ms
                ;     4.56±0.1ms   4.70±0.06ms    4.62±0.04ms     4.12±0.05ms   4.07±0.02ms     4.01±0.1ms
              ===== ============= ============= ================ ============= ============= ================

[ 59.72%] ··· io.csv.ReadCSVMemoryGrowth.mem_parser_chunks                                                                           0
[ 61.11%] ··· io.csv.ReadCSVParseDates.time_baseline                                                                       2.40±0.03ms
[ 62.50%] ··· io.csv.ReadCSVParseDates.time_multiple_date                                                                  2.88±0.03ms
[ 63.89%] ··· io.csv.ReadCSVParseSpecialDate.time_read_special_date                                                                 ok
[ 63.89%] ··· ======== ============
               param1
              -------- ------------
                 mY     52.3±0.6ms
                mdY     21.8±0.4ms
                 hm      431±8ms
              ======== ============

[ 65.28%] ··· io.csv.ReadCSVSkipRows.time_skipprows                                                                                 ok
[ 65.28%] ··· ========== ============
               skiprows
              ---------- ------------
                 None     20.3±0.9ms
                10000     13.6±0.2ms
              ========== ============

[ 66.67%] ··· io.csv.ReadCSVThousands.time_thousands                                                                                ok
[ 66.67%] ··· ===== ============ ============
              --            thousands
              ----- -------------------------
               sep      None          ,
              ===== ============ ============
                ,    16.2±0.1ms   17.2±0.7ms
                |    16.1±0.2ms   17.7±0.5ms
              ===== ============ ============

[ 68.06%] ··· io.csv.ReadUint64Integers.time_read_uint64                                                                    3.83±0.1ms
[ 69.44%] ··· io.csv.ReadUint64Integers.time_read_uint64_na_values                                                          7.24±0.3ms
[ 70.83%] ··· io.csv.ReadUint64Integers.time_read_uint64_neg_values                                                         6.63±0.3ms
[ 72.22%] ··· io.csv.ToCSV.time_frame                                                              [...]

2019-05-02 21:18 UTC, anmyachev commented
I ran a test with `-f 1.01` and did not get any changes either. Apparently in the past something misled us, because now it looks completely unnecessary.

2019-05-03 11:11 UTC, jreback commented on doc/source/whatsnew/v0.25.0.rst
> +- Removed usage of ``register`` keyword in C extension modules (:issue:`26263`)
not necessary as the introduction was in 0.25 (u can add this issue number to the other note if u want)

2019-05-05 21:15 UTC, jreback approved these changes

2019-05-05 21:15 UTC, merged

2019-05-05 21:15 UTC, jreback commented
thanks @WillAyd

2019-05-06 09:40 UTC, vnlitvin commented
> Apparently in the past something misled us, because now it looks completely unnecessary.

My guess is it was relevant for Windows + Python 2 (this combo used VS2008 to build), more modern compilers might be caching stuff to registers more eagerly.

That said, @WillAyd did you run some benchmarks on Windows?