BUG: Fix RecursionError when using a scalar point to select IntervalIndex columns
pandas-dev/pandas pull request #26570
Opened 2019-05-30 07:01 UTC by jschendel

- [X] closes #26490
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

2019-05-30 12:21 UTC, jreback requested changes

2019-05-30 12:21 UTC, jreback commented on pandas/core/frame.py
> +            if isinstance(self.columns, ABCIntervalIndex):
rather would not inject specific index logic here

you can make this not a single key (so it takes a different branch)

or define one of the _convert_to_index routines which dispatch to the index type

2019-06-27 03:36 UTC, jreback commented
@jschendel can you merge master and had some comments

2019-07-17 22:41 UTC, jbrockmendel commented
@jschendel can you rebase

2019-07-19 05:24 UTC, jschendel commented
I don't have a cleaner implementation here, and will need to come back to this later.  Closing for now as I don't want this sitting around stale.

2019-07-19 05:24 UTC, closed without merging