remove outdated gtk package from code
pandas-dev/pandas pull request #26590
Opened 2019-05-31 12:11 UTC by xcz011

- [x] closes #26563
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2019-05-31 13:00 UTC, WillAyd requested changes
Generally looks good

2019-05-31 13:41 UTC, xcz011 commented on doc/source/whatsnew/v0.25.0.rst
> +- Removed outdated packge gtk import for clipboard related (:issue:`26563`)
Got it, I will remove it soon

2019-06-01 02:48 UTC, xcz011 commented on pandas/io/clipboard/__init__.py
> +PyQt4 modules are not available for Python 3,
By looking at PyQt4 document [https://www.riverbankcomputing.com/static/Docs/PyQt4/python_v3.html](url), they seems support python 3, so I am going remove this comment.

2019-06-01 12:59 UTC, WillAyd approved these changes

2019-06-01 12:59 UTC, WillAyd commented
Lgtm @jreback

2019-06-01 14:15 UTC, jreback requested changes
can you add a note in the whatsnew (api changes) that we removed support for gtk for clipboards. ping on green.

2019-06-02 20:45 UTC, xcz011 commented
> can you add a note in the whatsnew (api changes) that we removed support for gtk for clipboards. ping on green.

Hi @jreback just added 😄

2019-06-02 21:08 UTC, jreback approved these changes

2019-06-02 21:09 UTC, merged

2019-06-02 21:09 UTC, jreback commented
thanks @xcz011