Allow operator overloading for custom classes to return custom objects
pandas-dev/pandas pull request #26652
Opened 2019-06-05 02:50 UTC by mhsekhavat

Uses a similar convention as numpy's ufunc overriding mechanism (https://docs.scipy.org/doc/numpy-1.13.0/neps/ufunc-overrides.html) to fix #22255

- [ ] closes #22255
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-06-05 03:17 UTC, TomAugspurger commented
Sorry, I missed the issue when it was originally opened. My initial reaction is that a `__pandas_ufunc__` isn't appropriate; I don't think it's defined well enough.

@jbrockmendel do you have any thoughts?

2019-06-05 12:01 UTC, jreback requested changes
as @TomAugspurger indicated, this would need substantial discussion. I am -1 on this in any event as I don't see a real reason for this. The numpy duck-like-arrays are much more pervasive and can use an override to operators, but this doesn't exist in the pandas ecosystem. Even if we saw many other packages trying to do this, just overriding operators is not that useful.

2019-06-05 13:13 UTC, jbrockmendel commented
I would want to see some compelling use cases for this before going forward.

Something close that I _could_ get on board with is something like `__array_priority__` to define how `op(EA_foo, EA_bar)` behaves.

2019-06-05 15:07 UTC, mhsekhavat commented
Thank you for your feedbacks @jreback and @TomAugspurger. I think your concerns are valid. 

In order to resolve your concern, I think a better alternative is to return `NotImplemented` in those situations that pandas does not handle `other` object. For example, pandas is raising `TypeError` in some situations like line 2306 of:

https://github.com/pandas-dev/pandas/blob/e0c41f79104c5bc61952c9a14f1883cd5bda53f7/pandas/core/ops.py#L2292-L2307

If pandas does not raise and return NotImplemented instead, python itself with raise `TypeError` when the other object can't handle it. Take the following example:

```python
>>> class A:
...     def __add__(self, other):
...         if isinstance(other, A):
...             return A()
...         return NotImplemented
... 
>>> A() + A()
<__main__.A object at 0x7f803dfe5c18>
>>> A() + object()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'A' and 'object'
```

In this proposal, there is no longer need to define inappropriate hooks like `__pandas_ufunc__`, and at the same time, python defers implementation to third-party libraries if pandas returns `NotImplemented` in the "else" part of its type checks like line 2306.

Finally, I think there are some use cases like "lazy/distributed/GPU" evaluation that can take benefit from custom overloading of operators in interaction with pandas objects.

2019-06-05 15:25 UTC, mhsekhavat commented
@jbrockmendel The only concrete use case I know is my own library, https://github.com/sspipe/sspipe. However, not blocking third-party interaction with pandas objects makes ideas like lazy/distributed/remote computation libraries to interact with pandas objects too. If numpy had blocked its operators to its own objects, pandas could not become so convenient. 
On the other hand, in my last proposal at the comment above, the code change will be limited to returning `NotImplemented` instead of raising `TypeError`. This doesn't add any explicit logic like `__pandas_ufunc__` hook to the existing code.

2019-06-05 16:37 UTC, TomAugspurger commented
> if pandas returns NotImplemented in the "else" part of its type checks like line 2306.

I think that's a starting point. Would you be able to summarize the conditions under which you think we should return NotImplemented, but currently don't?

2019-06-06 20:53 UTC, mhsekhavat commented
@TomAugspurger In most of the cases, we can replace the `else: <ORIGINAL_ELSE>` part of type checkings in `ops.py` to something like this:

```python
builtin_types = (int, float, complex, list, tuple, range, str, datetime, timedelta)
pandas_operand_types = (np.generic, np.array, ABCGeneric) + builtin_types

...
elif isinstance(other, pandas_operand_types):
    <ORIGINAL_ELSE>
else:
    return NotImplemented
```

One case that I think this will break current behavior is for Series whose dtype is `object`. In this case, the current behavior is to iterate over its items and apply operation on them item-wise, independent of the operand's datatype. Although I believe this behavior is too magical, I think in order to maintain current behavior, we can use the following snippet for this case:

```python
reverse_operations = {
    f'__{op}__': f'__r{op}__' for op in ('add', 'sub', 'mul', 'mod', 'pow', 'truediv', 'floordiv', 'divmod'
}

...
else:
    try:
        other_handler = getattr(other, reverse_operations[op.__name__])
        return other_handler(self)
    except Exception:
         <ORIGINAL_ELSE>
```

2019-06-07 19:51 UTC, TomAugspurger commented
I'm not sure what is best here. The definition of the "right" thing to do
here is unclear to me.

On Thu, Jun 6, 2019 at 3:54 PM Mohammad Hossein Sekhavat <
notifications@github.com> wrote:

> @TomAugspurger <https://github.com/TomAugspurger> In most of the cases,
> we can replace the else: <ORIGINAL_ELSE> part of type checkings in ops.py
> to something like this:
>
> builtin_types = (int, float, complex, list, tuple, range, str, datetime, timedelta)
> pandas_operand_types = (np.generic, np.array, ABCGeneric) + builtin_types
> ...elif isinstance(other, pandas_operand_types):
>     <ORIGINAL_ELSE>else:
>     return NotImplemented
>
> One case that I think this will break current behavior is for Series whose
> dtype is object. In this case, the current behavior is to iterate over
> its items and apply operation on them item-wise, independent of the
> operand's datatype. Although I believe this behavior is too magical, I
> think in order to maintain current behavior, we can use the following
> snippet for this case:
>
> reverse_operations = {
>     f'__{op}__': f'__r{op}__' for op in ('add', 'sub', 'mul', 'mod', 'pow', 'truediv', 'floordiv', 'divmod'
> }
> ...else:
>     try:
>         other_handler = getattr(other, reverse_operations[op.__name__])
>         return other_handler(self)
>     except Exception:
>          <ORIGINAL_ELSE>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/26652?email_source=notifications&email_token=AAKAOIQYRHHVTU5ZETIR3S3PZF2ORA5CNFSM4HTMZ23KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXEEGKI#issuecomment-499663657>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKAOIWOM7PGS2ULGMIFUPLPZF2ORANCNFSM4HTMZ23A>
> .
>

2019-07-11 16:11 UTC, jreback commented
closing this for now in favor of potentially more discussion on issue #22255 not sure we want to go down this route at this point (adding api for __pandas_ufunc__, though its interesting.)

2019-07-11 16:11 UTC, closed without merging