Fixed warning in doc build
pandas-dev/pandas pull request #26679
Opened 2019-06-05 19:55 UTC by nadebu

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-06-05 20:55 UTC, WillAyd commented
Thanks for the PR! What warning were you getting? Any easy way to detect others?

2019-06-06 08:49 UTC, datapythonista commented
I think all the CI failures are unrelated, not sure what's broken there.

But looks like the warning is still in the docs. @nadebu can you see if you find what's wrong?

@WillAyd added more info to the description.

2019-06-06 08:52 UTC, datapythonista requested changes
@nadebu I see that one file (`doc/esample.feather` was added by mistake). Can you please remove it?

Also, I think your change is probably fixing one of the errors, but a similar error is happening in the example immediately after in the PR. Can you apply the same change there please?

Thanks!

2019-06-08 21:17 UTC, jreback requested changes

2019-06-08 21:17 UTC, jreback commented on doc/source/whatsnew/v0.11.0.rst
>  Mixed Conversion
can you remove the added doc/example.feather file?

2019-06-08 21:17 UTC, jreback commented on doc/source/whatsnew/v0.11.0.rst
> -   :okwarning:
rather than this can you change to a code-block (and just show what it was)

2019-06-14 13:58 UTC, jorisvandenbossche commented
@nadebu sorry, it have been working the last days on the documentation, and this has already been fixed in the meantime.

2019-06-14 13:58 UTC, closed without merging

2019-06-14 13:59 UTC, jorisvandenbossche commented
Hopefully you can find another issue to work on! (there are some labeled with good-first-issue)

2019-06-14 14:00 UTC, jorisvandenbossche commented
Also, specifically for https://github.com/pandas-dev/pandas/issues/24173 (flake8 in the docs), there are still files left to do, so very welcome to open PRs for those.

2019-07-31 11:49 UTC, nadebu commented
Sorry I missed all this conversation. My mail was being diverted and still familiarising myself with github's messaging.