Isort __init__ files
pandas-dev/pandas pull request #26749
Opened 2019-06-09 00:33 UTC by alimcmaster1

- [x] related to #23334
 - [x] passes git diff upstream/master -u -- "*.py" | flake8 --diff

2019-06-09 00:40 UTC, jreback requested changes

2019-06-09 00:40 UTC, jreback commented on pandas/core/internals/__init__.py
> +    concatenate_block_managers  # noqa:F401; reshape.concat, reshape.merge
why do you have these separated? don't use ``\`` for conuation, use parens

2019-06-09 00:40 UTC, jreback commented on pandas/core/internals/__init__.py
> +from .blocks import _block_shape  # noqa:F401; io.pytables
why would this be after the others? (and why don't you have .blocks all in one)

2019-06-09 00:40 UTC, jreback commented on setup.cfg
> +    pandas/io/msgpack/__init__.py
extra line needed

2019-06-27 23:28 UTC, jreback approved these changes

2019-06-28 12:27 UTC, pep8speaks commented
Hello @alimcmaster1! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/__init__.py`](https://github.com/pandas-dev/pandas/blob/3491280d275dbfde6fc4e8171fc6e4bbc348c1b1/pandas/__init__.py):

> [Line 49:80](https://github.com/pandas-dev/pandas/blob/3491280d275dbfde6fc4e8171fc6e4bbc348c1b1/pandas/__init__.py#L49): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 60:80](https://github.com/pandas-dev/pandas/blob/3491280d275dbfde6fc4e8171fc6e4bbc348c1b1/pandas/__init__.py#L60): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)

2019-06-28 15:37 UTC, merged

2019-06-28 15:38 UTC, jreback commented
there are still 3 non-trivial isorts that remain (aside from the asv ones); but these I think require updating the setup.cfg for isort itself to ensure our ordering to avoid circular imports; alternatively we can put some isort ignores in the file (specifically pandas/__init__.py)

2019-06-30 13:49 UTC, alimcmaster1 commented
Thanks for fixing this up @jreback it was on my to do list I promise!