BLD: fix build warnings
pandas-dev/pandas pull request #26757
Opened 2019-06-10 01:58 UTC by jbrockmendel

xref #25995, #17936

AFAICT these warnings are caused by cython casting `len(some_ndarray)` to `int` or `Py_ssize_t` but casting `len(some_memoryview)` to `size_t`.  Easiest fix is to declare the affected len variables as `size_t` since we know they'll never be negative.

2019-06-10 02:40 UTC, WillAyd commented
Hmm understood that these would never be negative but since Py_ssize_t is what Python would use for indexing that still seems like the more natural data type to use. Is there not a way to silence these warnings while still using that type for indexers?

2019-06-10 02:49 UTC, jbrockmendel commented
@scoder any thoughts on whether this is worthwhile and if not, how to silence the warnings?

2019-06-10 06:14 UTC, scoder commented
`size_t`, or, more generally, unsigned integer types in C, have their advantages and disadvantages. Special use cases like bit manipulation aside, it's nice that they explicitly state that their value cannot be lower than zero. On the downside, they mix badly with C's default (signed) integer behaviour and signed arithmetic in general, and fail to support Python's negative indexing.

I think `Py_ssize_t` is the most obvious return type for `len()`, and memory views shouldn't diverge from this. This is something we can change in Cython 3.0. If you have an opinion, please discuss it at
https://github.com/cython/cython/issues/2992

As for a work-around for now, it's probably best to explicitly cast the return values to `Py_ssize_t`, at least where it's not used in an unsigned context anyway.

2019-06-10 12:31 UTC, jreback requested changes
we are consistently using Py_ssize_t, adding in size_t is confusing.

2019-06-10 14:13 UTC, jbrockmendel commented
Updated to use Py_ssize_t consistently

2019-06-11 00:31 UTC, jreback commented on pandas/_libs/ops.pyx
> +        size_t i, n = len(left)
does this one need updating?

2019-06-11 13:53 UTC, jbrockmendel commented on pandas/_libs/ops.pyx
> +        size_t i, n = len(left)
Yes, fixed.

2019-06-12 14:40 UTC, jreback requested changes
import comment, otherwise lgtm. ping on green.

2019-06-12 14:40 UTC, jreback commented on pandas/_libs/tslibs/parsing.pyx
> +from cython import size_t, Py_ssize_t
does size_t still need to be imported?

2019-06-12 14:47 UTC, jbrockmendel commented on pandas/_libs/tslibs/parsing.pyx
> +from cython import size_t, Py_ssize_t
Nope,

2019-06-12 14:51 UTC, jreback approved these changes

2019-06-12 14:51 UTC, jreback commented
lgtm. merge on green (and close the issues above if this & others cover)

2019-06-12 14:53 UTC, jbrockmendel commented
> and close the issues above if this & others cover

There's still a bunch in interval.pyx that I'm not sure are purely cosmetic (cc @jschendel)

2019-06-12 15:44 UTC, merged

2019-06-12 15:45 UTC, jreback commented
thanks @jbrockmendel