fix a indices bug for categorical-datetime columns
pandas-dev/pandas pull request #26860
Opened 2019-06-14 20:17 UTC by alexifm

This is to fix a bug reported in #26859

- [ ] closes #26859
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-06-15 00:56 UTC, WillAyd commented
Can you add a test? That's typically the first thing we look for with PRs

2019-06-15 02:04 UTC, pep8speaks commented
Hello @alexifm! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/groupby/test_groupby.py`](https://github.com/pandas-dev/pandas/blob/cfa0fefafbed98174eeddf45a3e3a2cc4f74f611/pandas/tests/groupby/test_groupby.py):

> [Line 1756:1](https://github.com/pandas-dev/pandas/blob/cfa0fefafbed98174eeddf45a3e3a2cc4f74f611/pandas/tests/groupby/test_groupby.py#L1756): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1760:1](https://github.com/pandas-dev/pandas/blob/cfa0fefafbed98174eeddf45a3e3a2cc4f74f611/pandas/tests/groupby/test_groupby.py#L1760): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1809:13](https://github.com/pandas-dev/pandas/blob/cfa0fefafbed98174eeddf45a3e3a2cc4f74f611/pandas/tests/groupby/test_groupby.py#L1809): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 1813:80](https://github.com/pandas-dev/pandas/blob/cfa0fefafbed98174eeddf45a3e3a2cc4f74f611/pandas/tests/groupby/test_groupby.py#L1813): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 1815:1](https://github.com/pandas-dev/pandas/blob/cfa0fefafbed98174eeddf45a3e3a2cc4f74f611/pandas/tests/groupby/test_groupby.py#L1815): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1816:1](https://github.com/pandas-dev/pandas/blob/cfa0fefafbed98174eeddf45a3e3a2cc4f74f611/pandas/tests/groupby/test_groupby.py#L1816): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1817:1](https://github.com/pandas-dev/pandas/blob/cfa0fefafbed98174eeddf45a3e3a2cc4f74f611/pandas/tests/groupby/test_groupby.py#L1817): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1818:1](https://github.com/pandas-dev/pandas/blob/cfa0fefafbed98174eeddf45a3e3a2cc4f74f611/pandas/tests/groupby/test_groupby.py#L1818): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1819:1](https://github.com/pandas-dev/pandas/blob/cfa0fefafbed98174eeddf45a3e3a2cc4f74f611/pandas/tests/groupby/test_groupby.py#L1819): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1821:1](https://github.com/pandas-dev/pandas/blob/cfa0fefafbed98174eeddf45a3e3a2cc4f74f611/pandas/tests/groupby/test_groupby.py#L1821): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1822:1](https://github.com/pandas-dev/pandas/blob/cfa0fefafbed98174eeddf45a3e3a2cc4f74f611/pandas/tests/groupby/test_groupby.py#L1822): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1822:1](https://github.com/pandas-dev/pandas/blob/cfa0fefafbed98174eeddf45a3e3a2cc4f74f611/pandas/tests/groupby/test_groupby.py#L1822): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2019-06-15 02:36 UTC, alexifm commented
I need to find a better way to test to equality of the dictionaries in the output for 3.5.

2019-06-16 14:23 UTC, jreback requested changes

2019-06-16 14:23 UTC, jreback commented on pandas/core/groupby/ops.py
> +            keys = [np.array(key) for key in keys]
this needs to be in get_indexer_dict in pandas/core/sorting.py

also, use ``np.asarray`` (np.array like this copies)

2019-06-16 14:23 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +    df = pd.DataFrame({
just do this inline (no need to name the Series)

2019-06-16 14:23 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +def test_groupby_indices():
move this after the test:  test_indices_concatenation_order()

2019-06-16 14:23 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +    col_order = [
if you want to specify an ordering do it in the constructor itself

2019-06-16 14:23 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +    for n in range(1, n_choices + 1):
you can parameterize this function  rather than doing this as it makes the test very opaque

2019-06-16 21:08 UTC, topper-123 commented
This should also have a entry in the whatsnew.

2019-06-17 02:17 UTC, alexifm commented
Thanks for the feedback.  Will update.

2019-06-28 14:50 UTC, jreback commented
@alexifm can you merge master and update

2019-09-11 16:01 UTC, TomAugspurger reviewed
Sorry, there's a merge conflict in the whatsnew. Can you merge master and resolve that?

@jbrockmendel do you have thoughts here?

2019-09-11 16:01 UTC, TomAugspurger commented on doc/source/whatsnew/v1.0.0.rst
> +- Bug in :meth:`DataFrameGroupBy.indices` raises exception when grouping on multiple columns and one is a categorical with datetime values. (:issue:`26860`)
"raises" -> "raising an"

"and one" -> "when one"

2019-09-11 22:22 UTC, jbrockmendel commented
i think we need the test cases to include Categorical[datetimetz]

2019-10-06 23:41 UTC, jreback commented
can you merge master and update to comments

2019-10-18 21:34 UTC, jreback commented
can you merge master

2019-11-02 00:39 UTC, jbrockmendel commented
@alexifm can you rebase.  this would be nice to get in

2019-11-13 18:19 UTC, jreback commented
closing as stale, if you want to continue pls ping.

2019-11-13 18:19 UTC, closed without merging