Calculate normalized freqs in value_counts correctly when bins is not None
pandas-dev/pandas pull request #26923
Opened 2019-06-18 14:19 UTC by krsnik93

- [x] closes #25970
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-06-19 00:54 UTC, jreback requested changes
can you add a whatsnew note, reshape section of bug fixes

2019-06-19 00:54 UTC, jreback commented on pandas/tests/test_algos.py
>          dtypes = (np.float64, np.object, 'M8[ns]')
can you pull the dtypes into another level of parameterization

2019-06-19 18:51 UTC, pep8speaks commented
Hello @krsnik93! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/test_algos.py`](https://github.com/pandas-dev/pandas/blob/5d1e2f88a84841aceb803eb4d01611400c78b22d/pandas/tests/test_algos.py):

> [Line 971:5](https://github.com/pandas-dev/pandas/blob/5d1e2f88a84841aceb803eb4d01611400c78b22d/pandas/tests/test_algos.py#L971): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

2019-06-21 01:24 UTC, jreback commented
@krsnik93 can you merge master & add a whatsnew note (bug fix in reshaping is ok). ping on green.

2019-06-21 07:47 UTC, krsnik93 commented
I have a failing test in tests/groupby/test_value_counts.py. The test compares `Series.value_counts` against `SeriesGroupBy.value_counts`. For this issue, I modified Series.value_counts and I think the change is correct. However, I think `SeriesGroupBy.value_counts` should change as well. This is the troubling bit:

https://github.com/pandas-dev/pandas/blob/c275dbfcee0fa9644fa2718ad76fd91ca056069b/pandas/core/groupby/generic.py#L1261-L1275

For some reason, it takes by-group counts of unbinned data (either NaN values or outside of bin breaks) and resets those counts to 0 (last line). I do not understand why is this done, but the whole method is kind hard to read and I am not able to make the required changes.

2019-06-24 15:08 UTC, TomAugspurger commented
cc @jschendel if you have time to take a look.

2019-09-05 17:18 UTC, WillAyd commented
@krsnik93 can you merge master and fix up merge conflicts?

2019-09-20 14:53 UTC, WillAyd commented
Closing as this looks stale, but @krsnik93 please ping if you'd like to continue and can open back up

2019-09-20 14:53 UTC, closed without merging