DOC: Exception raised if columns do not match data GH27003
pandas-dev/pandas pull request #27067
Opened 2019-06-26 19:56 UTC by srf94

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-06-26 19:56 UTC, pep8speaks commented
Hello @srf94! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/frame.py`](https://github.com/pandas-dev/pandas/blob/c393e8ed9d250334e6150033650cc4d89751648e/pandas/core/frame.py):

> [Line 1433:69](https://github.com/pandas-dev/pandas/blob/c393e8ed9d250334e6150033650cc4d89751648e/pandas/core/frame.py#L1433): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2019-06-27 02:40 UTC, WillAyd requested changes
Can you check if we have test coverage for this scenario?

2019-06-27 23:12 UTC, jorisvandenbossche commented
I think that we indeed first need to pin down the behaviour in code and tests. As it does not seem to always give an error message. For example:

```
In [24]: data = {1: ["foo"], 2: ["bar"]} 

In [25]: pd.DataFrame.from_records(data, columns=['a', 'b']) 
Out[25]: 
Empty DataFrame
Columns: [a, b]
Index: []
```

2019-06-27 23:15 UTC, jorisvandenbossche commented
Also, the sentence you are changing is about the case that your data already have names. While the use case in the reported issue is when the data have no names.

2019-08-28 17:08 UTC, closed without merging