BUG: Fix indexing on DatetimeBlock
pandas-dev/pandas pull request #27110
Opened 2019-06-28 22:00 UTC by jbrockmendel

- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Addresses one of the problems behind #26864, but probably doesn't address the statefullness problem there.

2019-06-28 23:21 UTC, jreback requested changes

2019-06-28 23:21 UTC, jreback commented on pandas/core/internals/blocks.py
> +            if isinstance(col, slice):
could be elif

2019-06-28 23:21 UTC, jreback commented on pandas/tests/groupby/aggregate/test_other.py
> +    assert ts == grouped.apply(lambda x: x.iloc[0]).iloc[0, 0]
can you reference this issue and maybe put a comment here on whey this is like this

2019-06-28 23:21 UTC, jreback commented on pandas/tests/groupby/aggregate/test_other.py
> +    assert ts == grouped.apply(lambda x: x.iloc[0]).iloc[0, 0]
or this is actually returning a single column DataFrame right? can you assert that

2019-06-28 23:21 UTC, jreback commented on pandas/tests/groupby/aggregate/test_other.py
> +    # FIXME: the next assertion is wrong; GH#26864
same here

2019-06-28 23:21 UTC, jreback commented on pandas/tests/groupby/aggregate/test_other.py
> +    # FIXME: the next assertion is wrong; GH#26864
also ok with moving these to a new test if easier

2019-06-29 14:29 UTC, jbrockmendel commented
I'm pretty sure this problem also affects other EA blocks, will check and add tests if so

2019-07-01 00:44 UTC, jbrockmendel commented
@jreback any idea what’s up with the CI?

2019-07-01 11:45 UTC, jreback commented
```
/home/vsts/work/1/s/doc/source/whatsnew/v0.25.0.rst:786: WARNING: Unknown interpreted text role "method".
/home/vsts/work/1/s/doc/source/whatsnew/v0.25.0.rst:786: WARNING: Unknown interpreted text role "method".
```

2019-07-01 11:46 UTC, jreback commented
method -> meth in the whatnew

2019-07-01 21:40 UTC, jreback approved these changes

2019-07-01 21:40 UTC, merged

2019-07-01 21:41 UTC, jreback commented
thanks @jbrockmendel