CLN: separate raising from non-raising parts of method
pandas-dev/pandas pull request #27151
Opened 2019-06-30 20:23 UTC by jbrockmendel

There is lots of code in core.internals inside try/except blocks, in particular calls to _try_coerce_args.  It is tough to reason about these because it is often unclear what the raising cases are.  This simplifies that problem by separating `values, args = self._try_coerce_args(values, args)` into `values = self._coerce_values(values)` and `args = self._try_coerce_args(args)`  (Note the former doesnt have a "try" in the name because it never raises).

Also: removed a never-used `ndim` kwarg from `Block.make_block` and removed a now-redundant `DatetimeTZBlock.copy` method.

2019-07-01 01:26 UTC, jbrockmendel commented
@jorisvandenbossche CI fails look unrelated, ami missing something?

2019-07-01 02:50 UTC, jorisvandenbossche commented
@mroeschke mentioned those should be fixed by a commit in https://github.com/pandas-dev/pandas/pull/27144#issuecomment-507071945

2019-07-01 21:46 UTC, jbrockmendel commented
yep, that fixed it, thanks.

2019-07-01 22:11 UTC, jreback requested changes
lgtm. if you can fix the doc-strings (on the super class); ok to remove from the other _coerce_values.

2019-07-01 22:11 UTC, jreback commented on pandas/core/internals/blocks.py
> +    def _coerce_values(self, values):
if possible can you add types (ok for future PR) and full doc-strings

2019-07-01 22:11 UTC, jreback commented on pandas/core/internals/blocks.py
>          """
you can omit the doc-strings (as will inherit from super class)

2019-07-01 22:11 UTC, jreback commented on pandas/core/internals/blocks.py
> +        """
can omit doc-string

2019-07-02 00:01 UTC, jreback approved these changes

2019-07-02 00:01 UTC, jreback commented
lgtm. ping on green.

would really love a typing PR on blocks :->

2019-07-02 13:17 UTC, jbrockmendel commented
psuedo-ping.  CI has been in this state for 13 hours

2019-07-02 13:31 UTC, merged

2019-07-02 13:31 UTC, TomAugspurger commented
CI finished, seems like Github missed the notification.

FYI @jbrockmendel let me know if you want to be added to the azure team so you can restart builds. Just need an azure account name.