Raise with message for 3.5.2 and earlier
pandas-dev/pandas pull request #27288
Opened 2019-07-08 13:41 UTC by TomAugspurger

Closes https://github.com/pandas-dev/pandas/issues/27247

2019-07-08 15:41 UTC, WillAyd commented on pandas/tests/test_downstream.py
> +    out = subprocess.run(["python", "-c", code], check=False, capture_output=True)
capture_output I don't think is available until 3.7 so source of CI errors. Maybe not needed at all?

2019-07-09 21:12 UTC, jreback requested changes

2019-07-09 21:12 UTC, jreback commented on pandas/tests/test_downstream.py
> +def test_old_python_raises():
we *could* move the import of just ``pandas.compat`` at the beginning of init and define PY35 there (and import here); would put the code more logically together.

2019-07-13 15:21 UTC, shoyer commented
Would it work to put this error in setup.py instead? Install time errors seem better than import time errors. Or are there cases where that doesn’t get run?

2019-07-13 15:24 UTC, jreback commented
> Would it work to put this error in setup.py instead? Install time errors seem better than import time errors. Or are there cases where that doesn’t get run?

i think if you have a old pip and install from a wheel this wont be hit in setup.py
only at import time

2019-07-16 14:34 UTC, TomAugspurger commented
Agreed that this should be in `setup.py`, but after thinking about it more, I'm hesitant to duplicate things that pip is doing (when used correctly).

The reported fail case in https://github.com/pandas-dev/pandas/issues/27247 was from (incorrectly) using `python setup.py develop` directly. I'd rather educate users on how pip says it should be done, rather than add duplicative checks.

2019-07-16 14:34 UTC, closed without merging