CLN: Split test_window.py
pandas-dev/pandas pull request #27305
Opened 2019-07-09 07:26 UTC by mroeschke

- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

`test_window.py` was getting fairly unwieldily. There a couple test classes that use a non-pytest-idomatic `Base` class, so those test classes are kept together for now. I split out the rest of the test classes into separate files as they made sense.

I think the classes in `test_window.py` need further untangling before a `conftest.py` file can be made for the new directory.

Open to additional quick win optimizations.

cc @jreback

2019-07-09 15:15 UTC, WillAyd requested changes
Thanks - this module could definitely use a little refactor.

Not opposed to this move but thinking through if we should parametrize first instead

2019-07-09 15:15 UTC, WillAyd commented on pandas/tests/window/test_dtypes.py
> +    def test_dtypes(self):
Is this the only function being tested in this module? If so I think would make sense to try and parametrize this first before moving

2019-07-09 15:15 UTC, WillAyd commented on pandas/tests/window/test_timeseries_window.py
> +        df = self.ragged
Good case for parametrization here (and a few functions below)

2019-07-09 15:15 UTC, WillAyd commented on pandas/tests/window/test_window.py
> +from typing import Any
Not opposed to this but note that we haven't done annotations in any other test module nor do we check it (mypy.ini excludes these) so would be OK to leave out for now as well

2019-07-09 15:15 UTC, WillAyd commented on pandas/tests/window/test_window.py
> +def min_periods(request) -> Any:
`Optional[int]` would be preferable as the return value here

2019-07-09 20:40 UTC, jreback commented
@mroeschke @WillAyd let's do the straight split first, modifications later.

ping on green.

2019-07-10 16:24 UTC, jreback commented
I think we merged something, can you merge master and ping on green.

2019-07-10 17:33 UTC, mroeschke commented
All green @jreback

2019-07-10 18:36 UTC, merged

2019-07-10 18:36 UTC, jreback commented
thanks @mroeschke

2019-07-10 19:22 UTC, simonjayhawkins commented
it looks like this broke the ci.

2019-07-10 19:26 UTC, jreback commented
@simonjayhawkins can u put a link up

2019-07-10 19:38 UTC, simonjayhawkins commented
https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=14275

2019-07-10 20:24 UTC, pilkibun commented
Strange that my PRs based on earlier commit also fails. Does azure merge the PR into master before tesing?

2019-07-10 20:49 UTC, simonjayhawkins commented
> Does azure merge the PR into master before tesing?

it looks like it. good to know.