Resolve #27315 - prevent contextually useless kwargs from causing an index error
pandas-dev/pandas pull request #27326
Opened 2019-07-10 16:49 UTC by ajspera

…seless in that case anyway

- [x] closes #27315
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-07-10 16:54 UTC, jreback requested changes
pls always add tests

2019-07-10 16:57 UTC, jreback commented
find the reindex tests; we need to run all combinations of args for an empty

2019-07-10 17:05 UTC, ajspera commented
Will do when I find some more time... New to the python world and this project so I need a few more moments to get familiar with the testing.

2019-07-16 07:18 UTC, ajspera commented
@jreback, could the tests be a while loop on a dict list using **kwargs on the method or are you looking for explicit individual tests for each arg combination? The former makes sense to me for efficiency, but being relatively new to python projects I'm not sure whether that overly obfuscates failure messages. Also I noticed the entry point on reindex tests are not on the class where I discovered the issue or even in the stack trace of those errors, and the class that I changed is further down inheritance of the tested class in there. Should we write tests for higher level DataFrame.reindex or should we go for the lowest public granularity of where (assuming private methods are not test targets like other languages) the changes are at Index.reindex? I can see reasons for either decision based on skimming through the class inheritance patterns.

Sorry if these are remedial questions, just want to make my limited time focused and productive while reducing review cycle tedium for you where my knowledge gaps are. I'll make decisions once I get into it either way if there's no preference, but some foresight would save some time if there are preferences.

Also sorry for the delay, too many commitments on my plate at the moment. Next step for this is to get a list of args for the test which is simple but tedious enough to conflict my schedule. If anyone wants to assist I can probably fit resolving any test failures into my schedule easier. If nobody claims that testing task I will wrap this up as soon as I can.

2019-09-08 16:45 UTC, jreback requested changes
needs a test & a whatsnew note

2019-09-08 16:45 UTC, jreback commented on pandas/core/indexes/base.py
> +        if len(self) == 0:
use not len

2019-10-06 23:48 UTC, jreback commented
closing as stale; this does fix the issue but needs tests. if you want to continue, pls merge master and ping to re-open.

2019-10-06 23:48 UTC, closed without merging