BUG:remove rollback from generate_range
pandas-dev/pandas pull request #27337
Opened 2019-07-11 10:31 UTC by Alpima-Quant

'elif end and not offset.onOffset(end): end = offset.rollback(end)' gives
unwanted results for e.g. offset=MonthEnd when start.time() > end.time()

EXAMPLE:
In [1]: import pandas as pd

In [2]: from datetime import datetime

In [3]: pd.date_range(freq='M', start=datetime(2019, 4, 30, 0, 2), end=datetime(2019, 7, 1, 0, 1))
Out[3]: DatetimeIndex(['2019-04-30 00:02:00', '2019-05-31 00:02:00'], dtype='datetime64[ns]', freq='M')

In [4]: pd.date_range(freq='M', start=datetime(2019, 4, 30, 0, 1), end=datetime(2019, 7, 1, 0, 1))
Out[4]: DatetimeIndex(['2019-04-30 00:01:00', '2019-05-31 00:01:00', '2019-06-30 00:01:00'],
              dtype='datetime64[ns]', freq='M')

line 3 output expected to include 2019-06-30 as only 1 second difference between start dates in lines 3 and 4

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-07-11 14:15 UTC, jbrockmendel commented
can you add a unit test

2019-07-11 14:23 UTC, jreback requested changes
pls also add a whatsnew note in bug fixes datetimelike

2019-07-11 14:23 UTC, jreback commented
is there an open issue for this?

2019-07-15 18:15 UTC, Alpima-Quant commented
> can you add a unit test

2019-07-15 18:19 UTC, Alpima-Quant commented
> is there an open issue for this?

Not that we could find.

2019-07-15 18:20 UTC, Alpima-Quant commented
> pls also add a whatsnew note in bug fixes datetimelike

Done.

2019-07-15 18:20 UTC, Alpima-Quant commented
> can you add a unit test

Done.

2019-07-16 04:15 UTC, mroeschke commented on pandas/tests/tseries/offsets/test_offsets.py
> +            assert dates[-1].date() == expected_last_date
Can you construct an expected index and use `tm.assert_index_equal`?

2019-07-16 04:17 UTC, mroeschke requested changes
Can you also add test for the reverse case and with the `tz_aware_fixture` to test timezones?

`` pd.date_range(freq='-M', end=datetime(2019, 4, 30, 0, 2), start=datetime(2019, 7, 1, 0, 1))``

2019-07-16 15:11 UTC, Alpima-Quant commented
> Can you also add test for the reverse case and with the `tz_aware_fixture` to test timezones?
> 
> ` pd.date_range(freq='-M', end=datetime(2019, 4, 30, 0, 2), start=datetime(2019, 7, 1, 0, 1))`

exploring the negative offset case, we've noticed that e.g. pd.date_range(freq=pd.offsets.MonthEnd(-1), start=datetime(2019, 10, 1), end=datetime(2019, 9, 29))
returns
DatetimeIndex(['2019-10-31', '2019-09-30'], dtype='datetime64[ns]', freq='-1M')
which is unexpected as 2019-10-31 is well out of the range of start and end

we suspect that this is caused by the behaviour of offset.rollforward/offset.rollback, we feel that rollback with a negative offset should be equivalent to rollforward with a positive offset

would you be happy with us changing the behaviour of rollback/rollforward to reflect this?

2019-07-16 15:43 UTC, pep8speaks commented
Hello @Alpima-Quant! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tseries/offsets.py`](https://github.com/pandas-dev/pandas/blob/43750b3878423e30a5db8db1289997364cd7c0ae/pandas/tseries/offsets.py):

> [Line 395:72](https://github.com/pandas-dev/pandas/blob/43750b3878423e30a5db8db1289997364cd7c0ae/pandas/tseries/offsets.py#L395): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 400:1](https://github.com/pandas-dev/pandas/blob/43750b3878423e30a5db8db1289997364cd7c0ae/pandas/tseries/offsets.py#L400): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 404:63](https://github.com/pandas-dev/pandas/blob/43750b3878423e30a5db8db1289997364cd7c0ae/pandas/tseries/offsets.py#L404): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2019-07-16 17:00 UTC, mroeschke commented
Agreed that the current behavior of `pd.date_range(freq=pd.offsets.MonthEnd(-1), start=datetime(2019, 10, 1), end=datetime(2019, 9, 29))` doesn't look right. Happy to have the behavior fixed as well.

2019-09-08 15:58 UTC, jreback commented
can you merge master and update to comments

2019-10-06 22:47 UTC, jreback commented
@Alpima-Quant can you merge master and update to any open comments.

2019-10-11 22:36 UTC, WillAyd commented
Nice PR but I think this has gone stale and CI is all red. Closing for now but if you'd like to pick back up and get tests to pass please ping

2019-10-11 22:36 UTC, closed without merging