Correctly re-instate Matplotlib converters
pandas-dev/pandas pull request #27481
Opened 2019-07-19 18:06 UTC by dstansby

Fixes https://github.com/pandas-dev/pandas/issues/27479. Converters should only be cached to be re-instated if they are original, and not pandas converters.

I'm struggling to write a test for this; I think it requires a clean state with no pandas imports, so one can check what was in the units registry before pandas was imported. I think this means a new test file with no pandas imports at the top, but maybe someone has a better idea?

2019-07-19 18:12 UTC, TomAugspurger commented
Thanks for this!

> I'm struggling to write a test for this; 

Testing these is quite hard (we accidentally broke the warning for a release and didn't notice).

https://github.com/pandas-dev/pandas/blob/9bab81e013af33084c48b54dc2a6ef188acfd225/pandas/tests/plotting/test_converter.py#L31 works reasonably well I think. The idea is to run the check in a subprocess.

2019-07-19 18:12 UTC, TomAugspurger commented
A release note in whatsnew/0.25.1.rst would be nice to have. I think there's a "plotting" subsection.

2019-07-19 21:13 UTC, dstansby commented
Thanks for the test tip, the new test fails before the changes in this PR.

2019-07-20 16:42 UTC, jreback requested changes

2019-07-20 16:42 UTC, jreback commented on doc/source/whatsnew/v0.25.1.rst
> +- Fixed the re-instatement of Matplotlib datetime converters after calling
can you add the issue number

2019-07-20 16:42 UTC, jreback commented on pandas/plotting/_matplotlib/converter.py
> +        if type_ in units.registry and type(units.registry[type_]) is not cls:
can you use isinstance here

2019-07-20 16:42 UTC, jreback commented on pandas/tests/plotting/test_converter.py
> +    # Check that Matplotlib converters are properly reset
can you add the issue number as a comment here

2019-07-24 11:31 UTC, jreback requested changes
also pls merge master

2019-07-24 11:31 UTC, jreback commented on doc/source/whatsnew/v0.25.1.rst
> +  `pandas.plotting.deregister_matplotlib_converters()` (issue #27481).
sorry this needs to be like ``:issue:`27481` `` to render

2019-07-24 21:44 UTC, dstansby commented
I'm away for the next week or so without a computer, so if anyone wants this in quicker than that feel free to force push to my branch.

2019-08-05 14:23 UTC, dstansby commented
Is there anything else (apart from a rebase) I need to do on this?

2019-08-05 14:30 UTC, TomAugspurger approved these changes
Looks good. Ping on green.

2019-08-05 15:21 UTC, TomAugspurger commented
Did you merge master before pushing? We've seen similar CI failures, but I thought we fixed them all on master.

2019-08-06 08:42 UTC, dstansby commented
Yeah, I should have rebased on to master, I've done another rebase to see if that fixes the tests.

2019-08-08 19:32 UTC, TomAugspurger commented
Merged master again to see if we can get the CI passing.

2019-08-20 14:26 UTC, TomAugspurger approved these changes

2019-08-20 14:26 UTC, merged

2019-08-20 14:26 UTC, TomAugspurger commented
Thanks @dstansby. Sorry about the CI issues.