BUG: Fix interpolate ValueError for datetime64_tz index
pandas-dev/pandas pull request #27549
Opened 2019-07-23 21:33 UTC by alorenzo175

- [ x ] closes #27548 
- [ x ] tests added / passed
- [ x ] passes `black pandas`
- [ x ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ x ] whatsnew entry

2019-07-23 21:57 UTC, mroeschke commented on doc/source/whatsnew/v0.25.1.rst
> +- Bug in :meth:`interpolate` when using a timezone aware index (:issue:`27548`)
```... when using a timezone aware :class:`DatetimeIndex` ...```

2019-07-23 22:25 UTC, jreback commented on doc/source/whatsnew/v0.25.1.rst
> +- Bug in :meth:`interpolate` when using a timezone aware :class:`DatetimeIndex` (:issue:`27548`)
this won't render, you want ```:meth:`Series.interpolate` ```

2019-07-23 22:25 UTC, jreback commented
looks ok, ping when changed & green.

2019-07-23 22:30 UTC, jreback requested changes

2019-07-23 22:30 UTC, jreback commented on pandas/tests/series/test_missing.py
> +    @pytest.mark.parametrize("method", ["nearest", "pad"])
you can parametrize on tz_naive_fixture here (and just remove the bottom test); this includes None and a bunch of timezones.

2019-07-23 23:51 UTC, alorenzo175 commented
@jreback I've updated to use the tz_naive_fixture and checks are green

2019-07-23 23:53 UTC, mroeschke approved these changes

2019-07-24 11:26 UTC, jreback approved these changes

2019-07-24 11:42 UTC, merged

2019-07-24 11:42 UTC, jreback commented
thanks @alorenzo175