CLN: more assorted cleanups
pandas-dev/pandas pull request #27555
Opened 2019-07-24 03:40 UTC by jbrockmendel

Continuing with the theme of avoiding runtime imports

2019-07-24 03:47 UTC, jreback commented on pandas/core/groupby/generic.py
> +from .groupby import groupby
can u do absolute imports

2019-07-24 11:47 UTC, jreback requested changes

2019-07-24 11:47 UTC, jreback commented on pandas/core/generic.py
> +        if not is_list_like(lower) and np.any(pd.isna(lower)):
these are already imported at the top, can drop the pd.

2019-07-24 11:47 UTC, jreback commented on pandas/core/groupby/generic.py
> +from pandas.core.dtypes.missing import _isna_ndarraylike, isna, notna
future, can you de-privatize this

2019-07-24 13:27 UTC, jbrockmendel commented on pandas/core/groupby/generic.py
> +from .groupby import groupby
yep

2019-07-24 15:15 UTC, jbrockmendel commented
Comments addressed

2019-07-25 17:11 UTC, jreback approved these changes

2019-07-25 17:12 UTC, merged

2019-07-25 17:12 UTC, jreback commented
thanks @jbrockmendel