BUG: partial string indexing with scalar
pandas-dev/pandas pull request #27712
Opened 2019-08-02 14:22 UTC by TomAugspurger

Closes #27516

cc @jreback if you have thoughts on this approach.

2019-08-02 14:22 UTC, TomAugspurger commented on pandas/core/indexing.py
> +            if isinstance(k, str) and ax.is_all_dates:
Is `is_all_dates` the appropriate way to check whether partial string indexing is supported?

2019-08-02 14:23 UTC, TomAugspurger commented on pandas/core/indexing.py
> +            if isinstance(k, str) and ax.is_all_dates:
My concern is that it's potentially expensive. Why not just `isinstance(ax, DatetimeIndex)`?

2019-08-02 14:48 UTC, jbrockmendel commented on pandas/core/indexing.py
> +            if isinstance(k, str) and ax.is_all_dates:
could alias `is_all_dates` to `_partial_str_indexing_supported` (or something less verbose) to make this more obvious?

For non-object Index is_all_dates is pretty cheap

2019-08-02 16:02 UTC, jreback requested changes

2019-08-02 16:02 UTC, jreback commented on pandas/core/indexing.py
> +            if isinstance(k, str) and ax.is_all_dates:
this is not the right place for this, rather you just call: 

self._get_partial_string_timestamp_match_key(key, labels)

2019-08-02 16:24 UTC, TomAugspurger commented on pandas/core/indexing.py
> +            if isinstance(k, str) and ax.is_all_dates:
Where would you do that? The problem with the current structure is that `_LocIndexer.__getitem__` if `self._is_scalar_access(key)` returns True, we go straight to `return self._getitem_scalar(key)`, which is incorrect for partial string indexing.

It doesn't look like `_get_partial_string_timestamp_match_key` will work, at least not directly. That doesn't convert the partial string key to a slice or array indexer.

```python
(Pdb) pp key
('2000', 'A')
(Pdb) pp self._get_partial_string_timestamp_match_key(key[0], self.obj.axes[0])
'2000'
```

Stepping back, I think that `_is_scalar_access` *should* return False for partial string indexing, since it's not actually a scalar access.

2019-08-02 16:36 UTC, TomAugspurger commented on pandas/core/indexing.py
> +            if isinstance(k, str) and ax.is_all_dates:
> could alias is_all_dates to _partial_str_indexing_supported (or something less verbose) to make this more obvious?

> For non-object Index is_all_dates is pretty cheap
 
It's the object case that I'm worried about, as I think this always hit.

Rather than inferring, why don't we define whether an index type supports partial string indexing as a class attribute? That skips the (potentially) expensive inference step, which IIUC would only be useful if (object-type) `Index` objects supported partial string indexing, which I don't believe they do.

2019-08-02 16:42 UTC, TomAugspurger commented on pandas/core/indexing.py
> +            if isinstance(k, str) and ax.is_all_dates:
0fb9bbe6e6b95d7bd1e47233e7fa659a48141a4b has that, as a POC. All the indexing tests pass locally.

2019-08-04 21:54 UTC, jreback approved these changes

2019-08-04 21:54 UTC, merged

2019-08-04 21:55 UTC, jreback commented
thanks @TomAugspurger

2019-08-04 21:55 UTC, jreback commented
@jbrockmendel can you create an issue to see if we can remove .is_all_dates entirely?