Shiny new feature
pandas-dev/pandas pull request #27964
Opened 2019-08-17 16:56 UTC by rmunjal29

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-08-17 17:05 UTC, jbrockmendel commented
Can you use a more informative title?

Looks like a .ipynb file got included accidentally?

2019-08-17 17:14 UTC, rmunjal29 commented
Yes sure I will do that.

And could you please ignore .ipynb file. I accidently got uploaded.

Sent from my iPhone

> On Aug 17, 2019, at 12:06 PM, jbrockmendel <notifications@github.com> wrote:
> 
> Can you use a more informative title?
> 
> Looks like a .ipynb file got included accidentally?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-08-17 17:32 UTC, jbrockmendel commented
Thanks.  We can ignore the extra file for now, but you'll need to remove it before this can be merged.

Looks like the lint checker is unhappy about the removed newline.  Can you run `black pandas/core/series.py`

2019-08-17 17:44 UTC, pep8speaks commented
Hello @rmunjal29! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/series.py`](https://github.com/pandas-dev/pandas/blob/baab4cd0810d18cf619ec71bfaa08dc4e14b1453/pandas/core/series.py):

> [Line 180:1](https://github.com/pandas-dev/pandas/blob/baab4cd0810d18cf619ec71bfaa08dc4e14b1453/pandas/core/series.py#L180): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2019-08-26 23:51 UTC, WillAyd requested changes
Minor comments. If you can address and remove the ipynb file should be good to go

2019-10-06 23:42 UTC, jreback requested changes
also merge master

2019-10-06 23:42 UTC, jreback commented on Untitled.ipynb
> +   },
need to revert this file

2019-10-22 01:41 UTC, WillAyd commented
@rmunjal29 can you address comments?

2019-10-22 02:16 UTC, rmunjal29 commented
Already updated the changes

Regards,
Ritika

> On Oct 21, 2019, at 8:42 PM, William Ayd <notifications@github.com> wrote:
> 
> ﻿
> @rmunjal29 can you address comments?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2019-10-22 02:26 UTC, WillAyd commented
Looks like there is a notebook in the diff - can you remove that?

Sent from my iPhone

> On Oct 21, 2019, at 7:17 PM, rmunjal29 <notifications@github.com> wrote:
> 
> ﻿Already updated the changes
> 
> Regards,
> Ritika
> 
> > On Oct 21, 2019, at 8:42 PM, William Ayd <notifications@github.com> wrote:
> > 
> > ﻿
> > @rmunjal29 can you address comments?
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2019-11-08 16:42 UTC, WillAyd approved these changes

2019-11-08 16:42 UTC, merged

2019-11-08 16:42 UTC, WillAyd commented
Thanks @rmunjal29