Added try-except clause to catch numpy error.
pandas-dev/pandas pull request #27970
Opened 2019-08-17 18:38 UTC by dustanlevenstein

Fixes https://github.com/pandas-dev/pandas/issues/27953

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-08-17 18:40 UTC, jbrockmendel commented
needs a test

2019-08-17 18:45 UTC, jreback requested changes
always add tests first
we are also trying to remove try/excepts except in very limited circumstances as they hide errors

2019-08-17 19:20 UTC, dustanlevenstein commented
Modified as requested.

2019-08-18 02:16 UTC, jbrockmendel commented on pandas/core/internals/construction.py
> +            if isinstance(dtype, CategoricalDtype):
this check would use `is_categorical_dtype(dtype)`

2019-08-18 02:17 UTC, jbrockmendel commented
by "needs a test" I meant that this PR fixes some bug and we need a unit test (goes somewhere in pandas/tests/) to test that we get the correct behavior

2019-08-18 18:35 UTC, dustanlevenstein commented
I added a test in a place that seemed appropriate. It passed on my platform.

2019-08-18 20:12 UTC, dustanlevenstein commented
The last version didn't pass the checks. I'm confused because the error doesn't seem to be related to anything that I edited...

![Screenshot from 2019-08-18 15-06-44](https://user-images.githubusercontent.com/43019642/63229856-8aef3d80-c1ca-11e9-96e4-b9763bc641da.png)
![Screenshot from 2019-08-18 15-05-19](https://user-images.githubusercontent.com/43019642/63229857-8b87d400-c1ca-11e9-90f3-aa8da80a0907.png)

2019-08-18 22:25 UTC, mroeschke commented on pandas/tests/frame/test_dtypes.py
> +        cat = pd.CategoricalDtype()
Could you add tests for other extension dtypes (e.g. datetime with timezones and/or period)

2019-08-18 22:25 UTC, mroeschke commented on pandas/core/internals/construction.py
> +            if is_categorical_dtype(dtype):
Based on the original issue this needs to be `is_extension_dtype`.

2019-08-18 22:28 UTC, mroeschke requested changes
Also needs a whatsnew entry in 1.0.0

2019-09-08 16:04 UTC, jreback commented
can you merge master and add a test

2019-10-03 19:11 UTC, jreback commented
closing this as stale, though its a nice change, needs a rebase and comments addressed.

2019-10-03 19:11 UTC, closed without merging