test case for transform with fillna #27905
pandas-dev/pandas pull request #27974
Opened 2019-08-17 20:26 UTC by ukantesaria

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-08-17 20:26 UTC, pep8speaks commented
Hello @ukantesaria! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/groupby/test_transform.py`](https://github.com/pandas-dev/pandas/blob/599b84229740e8cc976eeb576316e0289895e6ca/pandas/tests/groupby/test_transform.py):

> [Line 1078:1](https://github.com/pandas-dev/pandas/blob/599b84229740e8cc976eeb576316e0289895e6ca/pandas/tests/groupby/test_transform.py#L1078): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 1079:4](https://github.com/pandas-dev/pandas/blob/599b84229740e8cc976eeb576316e0289895e6ca/pandas/tests/groupby/test_transform.py#L1079): [E121](https://duckduckgo.com/?q=pep8%20E121) continuation line under-indented for hanging indent
> [Line 1105:4](https://github.com/pandas-dev/pandas/blob/599b84229740e8cc976eeb576316e0289895e6ca/pandas/tests/groupby/test_transform.py#L1105): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 1105:48](https://github.com/pandas-dev/pandas/blob/599b84229740e8cc976eeb576316e0289895e6ca/pandas/tests/groupby/test_transform.py#L1105): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 1106:4](https://github.com/pandas-dev/pandas/blob/599b84229740e8cc976eeb576316e0289895e6ca/pandas/tests/groupby/test_transform.py#L1106): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 1106:31](https://github.com/pandas-dev/pandas/blob/599b84229740e8cc976eeb576316e0289895e6ca/pandas/tests/groupby/test_transform.py#L1106): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2019-08-18 02:14 UTC, jbrockmendel commented on pandas/tests/groupby/test_transform.py
> +    "inputDF, expectedDF",
inputDF -> input_df
expectedDF -> expected_df

are there other dtypes we should be testing?

2019-08-18 08:03 UTC, charlesdong1991 commented
thanks for creating the PR, i think it would be nice also to test `groupby(group_col).transform("fillna")` case

2019-09-08 16:03 UTC, jreback commented
can you merge master and update to comments

2019-10-03 19:10 UTC, jreback commented
can you merge master and update

2019-10-05 23:13 UTC, jreback requested changes
can you parameterize this over all of the functions in the OP

2019-10-05 23:13 UTC, jreback commented on pandas/tests/groupby/test_transform.py
> +    input1 = inputDF.groupby("A").transform(lambda x: x.fillna(x.mean()))
use the forms

result =
tm.assert_frame_equal(result, expected)

2019-10-18 21:32 UTC, jreback commented
can you merge master and update to the comments

2019-10-22 01:37 UTC, WillAyd commented
closing as stale

2019-10-22 01:37 UTC, closed without merging