Fixed docstrings text that aren’t on the next line after opening `"""` and followed immediately by the line with closing `"""`. Issue #27986
pandas-dev/pandas pull request #27988
Opened 2019-08-18 04:54 UTC by steveayers124

- [ ] closes #27986
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-08-18 04:54 UTC, pep8speaks commented
Hello @steveayers124! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:













* In the file [`pandas/util/testing.py`](https://github.com/pandas-dev/pandas/blob/318bd9a02fdbd359de787c5f0f1504e63c76a360/pandas/util/testing.py):

> [Line 934:1](https://github.com/pandas-dev/pandas/blob/318bd9a02fdbd359de787c5f0f1504e63c76a360/pandas/util/testing.py#L934): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2019-08-18 19:59 UTC, datapythonista reviewed
Good work, thanks for working on these @steveayers124.

I see that the CI is red, and that pep8speaks complaint about couple of lines being too long. Can you check the CI and fix any errors, so everything is green and we can merge please? Thanks!

2019-08-21 20:53 UTC, steveayers124 commented
I think I may have made a mistake. I'll need to figure out what I did and how to undo it.
I came back to this after a couple days to finish up, and at the command line intended to pull down  the latest. I typed in the command 
`git fetch upstream && git merge upstream/master`

No, actually everything may be okay.
It appears it did pull down the latest, and did not make my fork automatically merge into Pandas master.

2019-08-24 06:06 UTC, steveayers124 commented
I appreciate your review, and encouragement, @datapythonista. I'll try going in smaller increments to see maybe what's failing, when I try more pull requests on my remaining changes. Thanks for the feedback!

2019-08-24 08:03 UTC, datapythonista approved these changes
looks great, thanks @steveayers124 for the work on this.

2019-08-24 08:12 UTC, WillAyd requested changes
Minor comments otherwise lgtm

2019-08-24 08:12 UTC, WillAyd commented on pandas/conftest.py
> +    Pass in the observed keyword to groupby for [True, False]
I think need a blank line separating short description from long description here

2019-08-24 08:12 UTC, WillAyd commented on pandas/conftest.py
> +    Combine frame, functions from SelectionMixin._cython_table
Short description should be one line

2019-08-24 08:22 UTC, datapythonista commented
Agree on both @WillAyd. But I'm also happy to have them in a follow up. GL01 and GL02 are about the position of the quotes, and for formatting errors I'd say it may speed up things if we merge PRs fast and keep opening new tickets fast, than trying to address too many in the PRs.

I'm writing a blog post about what I think it makes sense, so we can discuss and find the way that we all find more efficient. But there is so much to say that it's taking forever. :)

2019-08-24 08:24 UTC, WillAyd commented
Sure - merge away

Sent from my iPhone

> On Aug 24, 2019, at 9:22 AM, Marc Garcia <notifications@github.com> wrote:
> 
> Agree on both @WillAyd. But I'm also happy to have them in a follow up. GL01 and GL02 are about the position of the quotes, and for formatting errors I'd say it may speed up things if we merge PRs fast and keep opening new tickets fast, than trying to address too many in the PRs.
> 
> I'm writing a blog post about what I think it makes sense, so we can discuss and find the way that we all find more efficient. But there is so much to say that it's taking forever. :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-08-24 09:32 UTC, merged

2019-08-24 09:34 UTC, datapythonista commented
Thanks @steveayers124, keep the good work.