GH27394
pandas-dev/pandas pull request #27998
Opened 2019-08-18 16:52 UTC by PraneethKhanna

Raised an error if argument prefix is set when there are headers present during pandas read_csv.

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-08-18 22:41 UTC, mroeschke requested changes
Needs test and whatsnew entry in 1.0.0

2019-08-19 13:51 UTC, datapythonista reviewed
This change can break code, not sure if we should start by a warning and break later.

2019-08-19 13:51 UTC, datapythonista commented on pandas/io/parsers.py
> +            if self.prefix:
probably worth using `elif`

2019-08-19 13:51 UTC, datapythonista commented on pandas/io/parsers.py
> +                raise ValueError("argument prefix must be None if header not None")
The error message is not 100% correct, since the header can be provided with `names`.

2019-08-19 19:08 UTC, PraneethKhanna commented on pandas/io/parsers.py
> +            if self.prefix:
yes, will change that

2019-08-29 15:10 UTC, datapythonista commented
@PraneethKhanna do you have time to add the requested test and the note in the release notes (aka whatsnew)?

2019-09-17 15:37 UTC, WillAyd commented
Looks like this is stale but @PraneethKhanna if you'd like to pick back up please ping!

2019-09-17 15:37 UTC, closed without merging