Docstrings
pandas-dev/pandas pull request #28001
Opened 2019-08-18 17:43 UTC by realjohnward

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Partially resolves issue 27979

2019-08-18 17:43 UTC, pep8speaks commented
Hello @realjohnward! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:











* In the file [`pandas/io/pytables.py`](https://github.com/pandas-dev/pandas/blob/d647f0931550efd88dfed63c2ebf57ad16815a81/pandas/io/pytables.py):

> [Line 567:89](https://github.com/pandas-dev/pandas/blob/d647f0931550efd88dfed63c2ebf57ad16815a81/pandas/io/pytables.py#L567): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 88 characters)
> [Line 1177:89](https://github.com/pandas-dev/pandas/blob/d647f0931550efd88dfed63c2ebf57ad16815a81/pandas/io/pytables.py#L1177): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 88 characters)

* In the file [`pandas/tseries/offsets.py`](https://github.com/pandas-dev/pandas/blob/d647f0931550efd88dfed63c2ebf57ad16815a81/pandas/tseries/offsets.py):

> [Line 237:89](https://github.com/pandas-dev/pandas/blob/d647f0931550efd88dfed63c2ebf57ad16815a81/pandas/tseries/offsets.py#L237): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (207 > 88 characters)

2019-08-18 19:51 UTC, datapythonista requested changes
Good stuff, thanks for working on this @realjohnward.

Added some comments, and when you address them, please make sure that the CI is green, otherwise we can't merge the changes.

Also, please try to provide a more descriptive title and reference the issue you're working on in the description (you can edit the description, I'm changing the title myself).

2019-08-18 19:51 UTC, datapythonista commented on asv_bench/benchmarks/io/json.py
> -
Can you undo this please, besides probably being the reason to have the CI in green, we are strict about not including unrelated changes to PR, to keep the maintenance of the project under control.

2019-08-18 19:51 UTC, datapythonista commented on pandas/io/parsers.py
> +        kwds["encoding"] = 'auto'
Can you have the code changes in a separate PR please?

2019-08-18 19:51 UTC, datapythonista commented on pandas/io/pytables.py
> +    Either Fixed or Table format.
Can you leave a blank line between the two paragraphs.

2019-08-18 19:51 UTC, datapythonista commented on pandas/io/pytables.py
> +        Return a (potentially unordered) list of the keys corresponding to the objects stored in the HDFStore.
Not sure if this is too long, can you check the CI please?

2019-08-18 19:51 UTC, datapythonista commented on pandas/io/pytables.py
> +        format   : 'Fixed(f)|Table(t)', default is 'fixed'
If you don't mind, can you leave just one space in each side of the colon? I know it's from the original code, not your changed, but would be good to have this fixed.

2019-08-18 19:51 UTC, datapythonista commented on pandas/io/pytables.py
> +            Table(t) : Table format
I think this is incorrect, I know you did it to make the validation of the docstring not fail, but we'll have to find another solution, you can just restore how it was for now.

2019-08-18 19:51 UTC, datapythonista commented on pandas/io/pytables.py
> +        where : str, optional, default "/"
you can remove the optional, we used it when the default is None

2019-08-18 19:51 UTC, datapythonista commented on pandas/tseries/offsets.py
> +    dateutil.relativedelta.relativedelta :     The relativedelta type is designed to be applied to an existing datetime an can replace specific components of that datetime, or represents an interval
You'll have to split the description in different lines, this is surely too long. Also, leave just one space after the colon.

2019-08-18 19:53 UTC, datapythonista commented
just saw you did reference the issue in the PR, you can check how we usually do (the hash makes github create a link to this PR in the issue)

2019-08-22 17:03 UTC, closed without merging

2019-08-22 17:05 UTC, realjohnward commented
Thank you @datapythonista for looking over this PR and requesting changes. I am creating another PR with the requested changes made.