Add support to names keyword in Index
pandas-dev/pandas pull request #28032
Opened 2019-08-20 11:19 UTC by pedrocunial

- [x] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-08-23 14:08 UTC, WillAyd requested changes

2019-08-23 14:08 UTC, WillAyd commented on pandas/core/indexes/base.py
> +        names=None,
Can you move this to the end (before kwargs)

2019-08-23 14:08 UTC, WillAyd commented on pandas/core/indexes/base.py
> +        if names is not None:
Not super familiar with this part of the code but is it possible to share the length of checking of `names` across the index types? This already fails for a MultiIndex:

```python
>>> pd.MultiIndex.from_tuples((('a', 'b'), ('c', 'd')), names=('a', 'b', 'c'))

ValueError: Length of names must match number of levels in MultiIndex.
```

So ideally could share that machinery here

2019-09-06 17:00 UTC, TomAugspurger commented
> With that said I'm a little hesitant on this change. I understand the goal but it feels weird to have both a name and names argument as part of the constructor.

I'd say that's an issue with the `Index` constructors API. They're both valid arguments, this just updating the signature / docs to reflect that :)

2019-09-06 17:10 UTC, WillAyd commented
> They're both valid arguments, this just updating the signature / docs to reflect that :)

I assume that's just because the Index constructor appears to accept anything though, right? Not necessarily that it's valid.

```python
>>> pd.Index([], names=["foo"])
Index([], dtype='object')
>>> pd.Index([], names=["foo"])
Index([], dtype='object')
>>> pd.Index([], something="foo")
Index([], dtype='object')
```

2019-09-06 17:15 UTC, TomAugspurger commented
It's used if you take the MultiIndex route

```python
In [5]: pd.Index([(1, 2), (3, 4)], names=['a', 'b'], tupleize_cols=True)
Out[5]:
MultiIndex([(1, 2),
            (3, 4)],
           names=['a', 'b'])
```

2019-09-06 20:53 UTC, WillAyd commented
Sorry I think I went in a circle but coming back to it...I don't see how having both `name` and `names` makes sense from an API perspective. I get we want to do that to achieve symmetry in our inheritance but from an end user perspective this feels like a step in the wrong direction

2019-10-03 19:09 UTC, jreback commented
closing; we want to deprecate names I think, this is going backwards.

2019-10-03 19:09 UTC, closed without merging