Fixes issue #27563
pandas-dev/pandas pull request #28091
Opened 2019-08-22 14:33 UTC by elisamalzoni

- [ ] closes #27563
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Adds a new option in `pd.set_option()` method.

Usage:
```python
# n is an int that represents the interval of rows which the headers are repeated (default = 0, no repetition)
pd.set_option("display.repeating_row_index", n)   
```
Before | After (n = 3)
----------- | -------------
![Imgur](https://i.imgur.com/jPjDAu0.png) | ![Imgur](https://i.imgur.com/uodLczI.png)

@leostayner

2019-08-22 14:33 UTC, pep8speaks commented
Hello @elisamalzoni! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/io/formats/html.py`](https://github.com/pandas-dev/pandas/blob/fa4a67a61a5967ba32e82de5541beb10dd8c7a56/pandas/io/formats/html.py):

> [Line 424:1](https://github.com/pandas-dev/pandas/blob/fa4a67a61a5967ba32e82de5541beb10dd8c7a56/pandas/io/formats/html.py#L424): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2019-08-23 18:02 UTC, TomAugspurger commented
Hmm, I'm not entirely sure about this. It doesn't mesh well with my idea of an HTML table.

If we proceed, we'd need tests, and we would need to handle it similar to the other options (a parameter that gets plumbed through from DataFrame.to_html down to the formatter, and looked up from the config if not specified)

2019-08-25 20:01 UTC, WillAyd commented
Yea I think this is a little arbitrary. From the linked issue I get the problem we are trying to solve is that the headers aren't visible while scrolling through. Wouldn't it be possible to just pin the headers then with appropriate CSS?

cc @simonjayhawkins for insights

2019-08-25 20:09 UTC, simonjayhawkins commented
I do think that this could be out-of-scope for pandas. presumably, it's an issue for any application/library display HTML in the notebook and the issue should be raised there?

2019-08-25 20:39 UTC, simonjayhawkins commented
@elisamalzoni will look in detail, but on initially glance suspect that this may have issues with a multiIndex because of rowspan. Changes to _write_hierarchical_rows would also be needed. Can you add a test for this?

2019-08-26 07:31 UTC, gfyoung requested changes
I agree that pinning is a preferable option to resolving this issue.

2019-08-26 14:39 UTC, closed without merging