BUG: fix+test Timestamp with int array
pandas-dev/pandas pull request #28161
Opened 2019-08-27 00:41 UTC by jbrockmendel

Preliminary 2/3 for fixing #28080.

2019-08-27 01:04 UTC, WillAyd requested changes

2019-08-27 03:40 UTC, f-vert commented
does data analyst need a bachelors ?

On Mon, Aug 26, 2019 at 5:41 PM jbrockmendel <notifications@github.com>
wrote:

> Preliminary 2/3 for fixing #28080
> <https://github.com/pandas-dev/pandas/issues/28080>.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/pandas-dev/pandas/pull/28161
> Commit Summary
>
>    - BUG: fix+test Timestamp with int array
>
> File Changes
>
>    - *M* pandas/_libs/tslibs/c_timestamp.pyx
>    <https://github.com/pandas-dev/pandas/pull/28161/files#diff-0> (16)
>    - *M* pandas/tests/scalar/timestamp/test_arithmetic.py
>    <https://github.com/pandas-dev/pandas/pull/28161/files#diff-1> (53)
>
> Patch Links:
>
>    - https://github.com/pandas-dev/pandas/pull/28161.patch
>    - https://github.com/pandas-dev/pandas/pull/28161.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/28161?email_source=notifications&email_token=AKHFDSHWXBJHHJSVM4EGX3DQGRZ4RA5CNFSM4IPZGG4KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HHQO2XQ>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKHFDSF5DFHESL7ZBMBT3STQGRZ4RANCNFSM4IPZGG4A>
> .
>

2019-09-02 21:01 UTC, jreback commented
lgtm. @WillAyd

2019-09-02 21:17 UTC, WillAyd approved these changes

2019-09-02 21:17 UTC, merged

2019-09-02 21:17 UTC, WillAyd commented
Thanks @jbrockmendel