Datetime mergeasof tolerance
pandas-dev/pandas pull request #28241
Opened 2019-08-31 13:51 UTC by ianzur

- [ ] closes #28098
- [ ] tests 1 / 1
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-08-31 14:04 UTC, jreback commented on pandas/core/reshape/merge.py
> +                try:
this is not a good way
rather just wrap it in Timedelta then leave the original

2019-08-31 14:04 UTC, jreback requested changes
comments

2019-09-01 00:35 UTC, mroeschke commented on doc/source/whatsnew/v0.25.1.rst
> +- Bug :meth:`merge_asof` could not use datetime.timedelta for `tolerance` kwarg (:issue:`28098`)
* ````Bug in :func:`merge_asof` ````
* ````:class:`datetime.timedelta` ````
* ```` ``tolerance`` ````

2019-09-01 00:37 UTC, mroeschke commented on pandas/core/reshape/merge.py
> +                if not isinstance(self.tolerance, Timedelta):
Don't think we need this `if` statement. (it's okay to pass a `Timedelta` into `Timedelta` I think).

2019-09-02 21:56 UTC, jreback requested changes

2019-09-02 21:56 UTC, jreback commented on doc/source/whatsnew/v0.25.1.rst
> +- Bug :meth:`merge_asof` could not use datetime.timedelta for `tolerance` kwarg (:issue:`28098`)
move this to 0.25.2

2019-09-10 12:27 UTC, jreback requested changes

2019-09-10 12:27 UTC, jreback commented on doc/source/whatsnew/v0.25.1.rst
> +- Bug :meth:`merge_asof` could not use datetime.timedelta for `tolerance` kwarg (:issue:`28098`)
sorry, move to 1.0

2019-09-23 15:40 UTC, alimcmaster1 commented
@ianzur - this is great! Mind updating as per @jreback comments looks like this is almost there

2019-09-23 19:52 UTC, ianzur commented
Thanks for the reminder! I got distracted with school.

On Mon, Sep 23, 2019 at 10:41 AM alimcmaster1 <notifications@github.com>
wrote:

> @ianzur <https://github.com/ianzur> - this is great! Mind updating as per
> @jreback <https://github.com/jreback> comments looks like this is almost
> there
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/28241?email_source=notifications&email_token=AICYMWMMTMSUQ24OPG4YNQDQLDPSNA5CNFSM4ISTXQ22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7LJPSQ#issuecomment-534157258>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AICYMWKARA6KQ5YMIA3HVCDQLDPSNANCNFSM4ISTXQ2Q>
> .
>

2019-09-25 00:17 UTC, alimcmaster1 commented
Does this need a test? Can we now get rid of the xfail for test_tolerance in test_merge_asof?

2019-09-25 01:46 UTC, ianzur commented
@alimcmaster1 There is already a test in place. The test is not set to xfail.

https://github.com/pandas-dev/pandas/blob/8de8b081a77a484cd0e4e73dd88abe9de99bfd75/pandas/tests/reshape/merge/test_merge_asof.py#L593-L605

2019-09-25 07:37 UTC, alimcmaster1 commented
@ianzur - LGTM now thanks! Yep see that now (wasn’t showing up earlier)

2019-09-25 14:18 UTC, WillAyd approved these changes
lgtm though @mroeschke or @jbrockmendel might have some thoughts

2019-09-25 15:50 UTC, merged

2019-09-25 15:50 UTC, mroeschke commented
Thanks @ianzur.