BUG: pivot_table not returning correct type when margin=True and aggfunc='mean'
pandas-dev/pandas pull request #28248
Opened 2019-09-01 17:11 UTC by mabelvj

- [ ] closes #24893
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

# What's new
Use of `maybe_downcast_to_dtype` in `_add_margins` so it can resolve the dtype conversion, avoiding floats being converted to integers when the result of the `aggfunc` is a float.

# Issues
There are test referencing that np.means of ints are casted back into ints. However, giving that for the aggregations in the rows, floats are kept when the np.mean of integers is a float, it does not make sense that this behavior does not hold for the margins.

2019-09-01 17:11 UTC, pep8speaks commented
Hello @mabelvj! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/reshape/pivot.py`](https://github.com/pandas-dev/pandas/blob/7f2c8df0f21a284c0123c152b501a5d3a76310eb/pandas/core/reshape/pivot.py):

> [Line 257:89](https://github.com/pandas-dev/pandas/blob/7f2c8df0f21a284c0123c152b501a5d3a76310eb/pandas/core/reshape/pivot.py#L257): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 88 characters)

2019-09-02 18:56 UTC, simonjayhawkins commented
@mabelvj Thanks for the PR.

to fix the ci failure you'll need to run `black pandas` https://dev.pandas.io/development/contributing.html#python-pep8-black 

also test to confirm the fix works.

2019-09-03 12:45 UTC, mabelvj commented
I see that there are tests referencing that np.means of ints are casted back into ints marked with `pytest.mark.xfail` that are related to this issue, should I update them?:
https://github.com/pandas-dev/pandas/blob/03b3c8fc82b3a18a3ddcad1b3b26d601467fc74c/pandas/tests/reshape/test_pivot.py#L1604
https://github.com/pandas-dev/pandas/blob/03b3c8fc82b3a18a3ddcad1b3b26d601467fc74c/pandas/tests/reshape/test_pivot.py#L1618

2019-09-03 15:27 UTC, TomAugspurger commented
> should I update them?

Has the output changed? I would have expected them to fail CI if they were changed to no longer cast from float to int.

2019-09-04 12:14 UTC, jreback requested changes
lgtm. can you add a release note in reshaping bug fix section for 1.0

2019-09-04 12:15 UTC, jreback commented on pandas/core/reshape/pivot.py
>      try:
can you add a comment here about what is going on

2019-09-05 20:08 UTC, mabelvj commented
@TomAugspurger the results do not change for those, the tests are skipped if failing since they are marked to do so. Still, checking them (since they are related to this issue, because they check the float casting on the margins),  the expected values do not match the output result (old and new pivot_table give the same output here).

2019-09-11 01:25 UTC, WillAyd requested changes

2019-09-11 01:25 UTC, WillAyd commented on pandas/tests/reshape/test_pivot.py
> +        table = result
This line is causing the CI failure - should be able to just remove

2019-09-11 20:09 UTC, TomAugspurger approved these changes

2019-10-06 23:49 UTC, jreback commented
this lgtm. @mabelvj can you merge master; ping on green.

2019-11-07 21:10 UTC, WillAyd commented
ping @mabelvj - if you can fix up merge conflicts can get this one in

2019-11-23 12:20 UTC, mabelvj commented
@jreback @WillAyd Fixed the conflicts, but Flake8 keeps giving a false positive F841 error on [L1670-1671](https://github.com/mabelvj/pandas/blob/dd121dac85bdbdf5d0552e3692f3f75c498e761c/pandas/tests/reshape/test_pivot.py#L1670-L1671) because of unused variables, but they are used at the last line of the function.

It's strange because other functions have the same structure and do not raise any error.

2019-11-23 17:16 UTC, WillAyd commented
I think you need to add `tm.assert_result_equal(result, expected)` to the end of the test

2019-11-23 22:20 UTC, mabelvj commented
@WillAyd Fixed now. It seems the line disappeared when fixing previous conflicts with master.

2019-11-23 22:43 UTC, WillAyd approved these changes

2019-11-23 22:43 UTC, merged

2019-11-23 22:44 UTC, WillAyd commented
Great - thanks @mabelvj for seeing this one through!