BUG: Timestamp+int should raise NullFrequencyError, not ValueError
pandas-dev/pandas pull request #28268
Opened 2019-09-03 17:53 UTC by jbrockmendel

Last prerequisite before we can fix #28080.

2019-09-03 18:13 UTC, TomAugspurger commented
What would a release note for this look like? IIUC, this is backwards compatible since catching a ValueError will still catch this NullFrequencyError? But we should still have a note describing the change so that users could tighten up the caught exception if they desire.

2019-09-03 19:09 UTC, jbrockmendel commented
> What would a release note for this look like?

This is a good question.  I'm hesitant to advertise the change because before long we'll be enforcing the deprecation, at which point this should raise TypeError.

2019-09-03 21:00 UTC, WillAyd commented
I think OK to just say something like `... now raises a NullFrequencyError` without worrying too much about the details of a future deprecation

2019-09-04 11:29 UTC, jreback requested changes

2019-09-04 11:29 UTC, jreback commented on doc/source/whatsnew/v0.25.2.rst
> +- Addition and subtraction of integer or integer-dtype arrays with :class:`Timestamp` will now raise ``NullFrequencyError`` instead of ``ValueError`` (:issue:`28268`)
move to 1.0

2019-09-04 17:30 UTC, jbrockmendel commented on doc/source/whatsnew/v0.25.2.rst
> +- Addition and subtraction of integer or integer-dtype arrays with :class:`Timestamp` will now raise ``NullFrequencyError`` instead of ``ValueError`` (:issue:`28268`)
changed+green

2019-09-07 17:45 UTC, jreback approved these changes

2019-09-07 17:45 UTC, jreback commented
lgtm. maybe rebase and push again (as the CI is hanging)

2019-09-07 18:55 UTC, jbrockmendel commented
rebased+green

2019-09-07 19:22 UTC, WillAyd approved these changes

2019-09-07 19:22 UTC, WillAyd commented
Looks like some merge conflicts - can you fix up and repush?

2019-09-07 21:36 UTC, jbrockmendel commented
rebased+green

2019-09-08 17:09 UTC, merged

2019-09-08 17:09 UTC, jreback commented
thanks @jbrockmendel