FIX: add additional condition to check invalid type(#28277)
pandas-dev/pandas pull request #28319
Opened 2019-09-06 16:07 UTC by boomsquared

- [ ] closes #28277
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-09-06 16:07 UTC, pep8speaks commented
Hello @boomsquared! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/strings.py`](https://github.com/pandas-dev/pandas/blob/0b801a91f0dc58f94323836ef7bf057799da2e4d/pandas/core/strings.py):

> [Line 2110:78](https://github.com/pandas-dev/pandas/blob/0b801a91f0dc58f94323836ef7bf057799da2e4d/pandas/core/strings.py#L2110): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 2110:89](https://github.com/pandas-dev/pandas/blob/0b801a91f0dc58f94323836ef7bf057799da2e4d/pandas/core/strings.py#L2110): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 88 characters)

2019-09-06 16:17 UTC, WillAyd commented
Thanks for the PR! Can you add a test for the behavior you are trying to solve? Tests are typically the most critical part of any PR

2019-09-06 16:40 UTC, bangsquared commented
@WillAyd Thanks for the advice, will certainly do.

2019-09-06 20:42 UTC, WillAyd requested changes
Thanks again for the PR! Great investigation into root cause. I'm not sure about the proposed fixed just yet but cc @TomAugspurger if he has thoughts as well

Can you also add a whatsnew note for v1.0.0?

2019-09-06 20:42 UTC, WillAyd commented on pandas/core/strings.py
> +        elif is_list_like(others, allow_sets=False) and not isinstance(
Not sure about this. I *think* the real issue is that `is_list_like` returns True for `s.str` when it shouldn't, though I do see that is also technically Iterable so maybe this should be allowed and just fixed

2019-09-06 20:56 UTC, TomAugspurger commented
I'm not sold on the value of `Series.str.__iter__`, but https://github.com/pandas-dev/pandas/issues/3638 and https://github.com/pandas-dev/pandas/pull/3645 are interesting history. I'm not sure about the value of `Series.str.__iter__`, especially when it causes surprising behavior like this.

2019-09-06 21:04 UTC, WillAyd commented
Hmm that's very surprising. Seems like it yields "columnar character by character" access across all elements?

Maybe we should just deprecate that behavior then? Having a hard time seeing where that is useful as an iterator

2019-09-07 03:37 UTC, boomsquared commented
@WillAyd  The StringMethods.get calls str_get which str_get "Extract element from lists, tuples, or strings in each element in the  Series/Index". Should I fix the StringMethods.get by not calling str_get?

2019-09-09 17:05 UTC, WillAyd commented
I think the best approach would be to deprecate the `__iter__` method of `Series.str` as noted above and remove in the future - is that something you'd be interested in trying?

2019-09-10 01:47 UTC, boomsquared commented
@WillAyd Is there something more to depreciating the function than just removing it from the code?

2019-09-10 01:53 UTC, WillAyd commented
Yea we would want to throw a warning for the time being and add some doc notes / sphinx directives for the deprecation. There's a Deprecate label where you can see past PRs, but citing a specific example I think #26744 is one PR that's relatively clean to emulate

2019-09-10 12:18 UTC, closed without merging