GH28337: Period index doesn't handle reindexing with a non-period index
pandas-dev/pandas pull request #28354
Opened 2019-09-09 03:29 UTC by christopherzimmerman

- [ ] closes #28323 and #28337 
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Adds a workaround to allow period indexes to be reindexed with non-period indexes.

2019-09-09 12:45 UTC, jreback requested changes
if you are closing https://github.com/pandas-dev/pandas/issues/28323, can you an a replicating test as well

2019-09-09 12:45 UTC, jreback commented on doc/source/whatsnew/v1.0.0.rst
> +- Reindexing a `PeriodIndex` with an index of dtype `Object` no longer uses the `PeriodIndex`'s `_int64index`
can you use ``:meth:`PeriodIndex` `` here, double back-ticks around ``object`` (and make it lowercase); also can you make this a bit more user friendly, no need to mention _int64index; these are user facing notes.

also add the issues that are closed.

move to the Indexing section.

2019-09-09 16:15 UTC, gfyoung approved these changes
@jreback : Over to you again

2019-09-10 00:00 UTC, WillAyd requested changes
minor nit but otherwise lgtm

2019-09-10 00:00 UTC, WillAyd commented on pandas/tests/reshape/test_pivot.py
> +        df = DataFrame(
Can you add the issue as comment here too?

2019-09-10 12:06 UTC, jreback approved these changes

2019-09-10 12:06 UTC, merged

2019-09-10 12:06 UTC, jreback commented
thanks @christopherzimmerman