Fix to_datetime(errors='coerce') not swallowing all parser exceptions...
pandas-dev/pandas pull request #28367
Opened 2019-09-10 09:44 UTC by squigmig

… (#28299)

- [x] closes #28299
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2019-09-10 12:00 UTC, jreback requested changes
cc @jbrockmendel

2019-09-10 12:00 UTC, jreback commented on doc/source/whatsnew/v0.25.2.rst
> +- Bug in :func:`to_datetime` where passing arrays of malformed ``str`` while attempting to coerce errors could incorrectly lead to raising errors instead (:issue:`28299`)
move to 1.0

2019-09-10 12:17 UTC, jreback commented
this *might* solve https://github.com/pandas-dev/pandas/issues/25143, https://github.com/pandas-dev/pandas/issues/23447, https://github.com/pandas-dev/pandas/issues/9107

if you'd have a look (if so pls add a test for whatever this solves)

2019-09-11 09:32 UTC, squigmig commented on doc/source/whatsnew/v0.25.2.rst
> +- Bug in :func:`to_datetime` where passing arrays of malformed ``str`` while attempting to coerce errors could incorrectly lead to raising errors instead (:issue:`28299`)
thanks, done

2019-09-11 09:57 UTC, squigmig commented
> this _might_ solve #25143, #23447, #9107
> 
> if you'd have a look (if so pls add a test for whatever this solves)

Looks like none of these is affected. At least one seems to be handled by a different change

2019-09-11 11:42 UTC, TomAugspurger approved these changes

2019-09-11 13:10 UTC, jreback commented
@squigmig 

> Looks like none of these is affected. At least one seems to be handled by a different change

care to do a PR with a test for (which?) one

2019-09-11 13:53 UTC, squigmig commented
> > Looks like none of these is affected. At least one seems to be handled by a different change
> 
> care to do a PR with a test for (which?) one

sure, have raised #28386

...

Failing checks on this PR seem to be intermittent. What is the preferred way to resolve or force a re-run?

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=17284
Checks: Setup environment and build pandas is probably the originator of the rest of the failures
```conda env create -q --file=environment.yml
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

CondaHTTPError: HTTP 404 NOT FOUND for url <https://repo.anaconda.com/pkgs/main/linux-64/widgetsnbextension-3.5.1-py37_0.conda>
Elapsed: 00:00.006773
CF-RAY: 5148a6736939e0b2-IAD

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

##[error]Bash exited with code '1'.
##[section]Finishing: Setup environment and build pandas```

2019-09-11 14:21 UTC, TomAugspurger commented
Pushing an empty commit, or asking a maintainer. I've restarted the build.

On Wed, Sep 11, 2019 at 8:53 AM Miguel <notifications@github.com> wrote:

> Looks like none of these is affected. At least one seems to be handled by
> a different change
>
> care to do a PR with a test for (which?) one
>
> sure, have raised #28386 <https://github.com/pandas-dev/pandas/pull/28386>
>
> ...
>
> Failing checks on this PR seem to be intermittent. What is the preferred
> way to resolve or force a re-run?
>
> https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=17284
> Checks: Setup environment and build pandas is probably the originator of
> the rest of the failures
>
> Collecting package metadata (repodata.json): ...working... done
> Solving environment: ...working... done
>
> CondaHTTPError: HTTP 404 NOT FOUND for url <https://repo.anaconda.com/pkgs/main/linux-64/widgetsnbextension-3.5.1-py37_0.conda>
> Elapsed: 00:00.006773
> CF-RAY: 5148a6736939e0b2-IAD
>
> An HTTP error occurred when trying to retrieve this URL.
> HTTP errors are often intermittent, and a simple retry will get you on your way.
>
> ##[error]Bash exited with code '1'.
> ##[section]Finishing: Setup environment and build pandas```
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/28367?email_source=notifications&email_token=AAKAOITUQ4YG3KAJNDXA5G3QJDZ7LA5CNFSM4IVFMYV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6OSAPY#issuecomment-530391103>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKAOIWV4WARTKQ7VVWZE3DQJDZ7LANCNFSM4IVFMYVQ>
> .
>

2019-09-11 15:12 UTC, jbrockmendel commented on doc/source/whatsnew/v1.0.0.rst
> +- Bug in :func:`to_datetime` where passing arrays of malformed ``str`` while attempting to coerce errors could incorrectly lead to raising errors instead (:issue:`28299`)
'while attempting to coerce errors' --> 'with `errors="coerce"`'

'could incorrectly lead to raising errors instead' --> 'could incorrectly raise [???]`

2019-09-11 15:16 UTC, jbrockmendel commented on pandas/_libs/tslib.pyx
> +                            tz = py_dt.utcoffset()
can the utcoffset() call raise?  if not, why move this up?

2019-09-12 12:42 UTC, jreback approved these changes

2019-09-12 12:45 UTC, merged