ENH: MultiIndex.from_product infers names from inputs if not explicitly provided
pandas-dev/pandas pull request #28417
Opened 2019-09-12 16:51 UTC by christopherzimmerman

- [x] closes #27292
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Infers names in `MultiIndex.from_product`  and normalizes handing of `names=None` between `from_arrays` and `from_product`

2019-09-12 18:20 UTC, TomAugspurger approved these changes
One tiny comment: https://github.com/pandas-dev/pandas/pull/28417/files#r323883775 LGTM otherwise.

2019-09-12 19:43 UTC, jreback requested changes
tiny comment, other lgtm.

2019-09-13 21:26 UTC, TomAugspurger approved these changes
Doc formatting. Looks good otherwise.

2019-09-13 21:26 UTC, TomAugspurger commented on pandas/core/indexes/multi.py
> +            ..versionchanged 1.0
```suggestion
            .. versionchanged:: 1.0.0
```

2019-09-13 21:26 UTC, TomAugspurger commented on pandas/core/indexes/multi.py
> +            If not explicitly provided, names will be inferred from the
```suggestion
               If not explicitly provided, names will be inferred from the
```

2019-09-13 21:26 UTC, TomAugspurger commented on pandas/core/indexes/multi.py
> +            elements of iterables if an element has a name attribute
```suggestion
               elements of iterables if an element has a name attribute
```

2019-09-18 13:42 UTC, TomAugspurger approved these changes
Verified that we do have other coverage for `from_arrays` and input arrays with names.

2019-09-18 13:42 UTC, merged

2019-09-18 13:42 UTC, TomAugspurger commented
Thanks!