Pick and choose numpy version based on Python 2 or 3.
pandas-dev/pandas pull request #28511
Opened 2019-09-18 21:06 UTC by didip

- [x] closes #27435
- [ ] tests added / passed
- [x] passes `black pandas` (on Python 3 only)
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-09-19 08:10 UTC, jorisvandenbossche commented
Thanks for the PR!

Hmm, there a couple of failures. Not directly related to your change, but related to the fact that we didn't run those tests (at the state of 0.24.2) for some time, and fixes have been made for changed dependencies. 
See eg https://github.com/pandas-dev/pandas/issues/26725, https://github.com/pandas-dev/pandas/pull/26726

There also seem to be some actual failures with numpy 1.17, so an option could be to restrict it to lower versions also for python 3 ?

2019-09-19 17:43 UTC, didip commented
Thanks for the quick response.

Do you have documented versions of what the maximum versions pandas should have on Python 3?

2019-09-19 18:37 UTC, TomAugspurger commented
I haven't looked at the failures, but are they actual, noticeable bugs, or
just failures in the test?

If they're real issues then we can just have pandas 0.24.x require NumPy
<1.17 across the board.

On Thu, Sep 19, 2019 at 12:44 PM Didip Kerabat <notifications@github.com>
wrote:

> Thanks for the quick response.
>
> Do you have documented versions of what the maximum versions pandas should
> have on Python 3?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/28511?email_source=notifications&email_token=AAKAOITOQJNDPWJTJBLZRO3QKO26PA5CNFSM4IYDXLM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7EIVHI#issuecomment-533236381>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKAOIUASZO5KC2EJDTIHATQKO26PANCNFSM4IYDXLMQ>
> .
>

2019-09-19 20:27 UTC, TomAugspurger commented
Yeah, numpydev can certainly be ignored.

For the rest, perhaps try adding back the `free` channel in each
environment that needs it?

On Thu, Sep 19, 2019 at 1:54 PM Joris Van den Bossche <
notifications@github.com> wrote:

> Actually, I was looking at the numpy dev build. Most of the other build
> failures seem to be problems getting the environment installed (missing
> packages etc), like the python 2.7 build on Azure:
>
> Solving environment: ...working... failed
>
> ResolvePackageNotFound:
>   - xlsxwriter=0.5.2
>   - pytz=2013b
>   - python-dateutil=2.5.0
>   - xlwt=0.7.5
>
> Note sure how much effort we should do to get those CIs running again ..
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/28511?email_source=notifications&email_token=AAKAOIRXC2E4C3BPFKJZM5TQKPDFZA5CNFSM4IYDXLM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7EPEMA#issuecomment-533262896>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKAOIV27MQSLBV63ZUB6JLQKPDFZANCNFSM4IYDXLMQ>
> .
>

2019-10-07 13:05 UTC, datapythonista reviewed
Thanks for the fixing this @didip. Can you remove the tailing whitespace that is breaking the CI, and check the styling comment?

2019-10-07 13:05 UTC, datapythonista commented on setup.py
> +    numpy_install_rule += ', < {numpy_ver}'.format(numpy_ver=max_numpy_ver)
Just a style preference, but what fo you think about the less verbose option:

```python
numpy_requires = 'numpy >= {min_numpy_ver}{max_numpy_rule}'.format(
    min_numpy_ver=min_numpy_ver,
    max_numpy_rule=', < {}'.format(max_numpy_ver_py2) if sys.version_info[0] < 3 else '')
```

2019-10-07 13:06 UTC, datapythonista commented
Also, if you can please merge master into this branch.

2019-10-07 16:38 UTC, TomAugspurger commented
I think this is targeting 0.24.x directly, since we don't want these changes on master.

2019-10-07 16:40 UTC, didip commented
Agree with @TomAugspurger

2019-10-07 16:42 UTC, TomAugspurger commented
We still need the linting issues fixed though.

On Mon, Oct 7, 2019 at 11:41 AM Didip Kerabat <notifications@github.com>
wrote:

> Agree with @TomAugspurger <https://github.com/TomAugspurger>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/28511?email_source=notifications&email_token=AAKAOIWZ32LSX4LVKAQ5IELQNNRCBA5CNFSM4IYDXLM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEARAMAA#issuecomment-539100672>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKAOIQRLK3TQUGZNE7KR2TQNNRCBANCNFSM4IYDXLMQ>
> .
>

2019-10-07 17:19 UTC, didip commented
Yes, I’ll try to find sometime today to address it.

2019-10-07 21:59 UTC, didip commented
Where is the CI/CD output that shows failed linting?

2019-10-07 22:04 UTC, datapythonista commented
yes, but the build is too old and is not available anymore. You can run `./ci/code_checks.sh` and should report where are the tailing spaces.

2019-10-08 06:19 UTC, didip commented
There are tons of lint problems when running `./ci/code_checks.sh` but I don't see one that pertains to `setup.py`.

2019-10-12 20:43 UTC, datapythonista commented
Not quite sure what's the problem with the docstrings, but you've also got this error in the CI `pytables needs a release beyong 3.4.4 to support numpy 1.16x`.

Do you mind having a look @didip. We can't merge this until the CI is green.

2019-10-22 01:23 UTC, WillAyd commented
At this point we don't have any further plans for a 24.x release, so unfortunately I don't think this is something we will address (if anyone disagrees feel free to reopen)

2019-10-22 06:23 UTC, jorisvandenbossche commented
As far as I recall, we said to give the opportunity to interested contributors, so let's wait a bit more to see if @didip has time to update this.

2019-10-28 19:06 UTC, jbrockmendel commented
@didip it looks like some xfailed pytables tests need to be updated for the changes in this PR to work.  can you take a look and update?

2019-10-29 15:28 UTC, didip commented
Upgraded `pytables` to 3.5.2. `sh test_fast.sh` now actually runs end-to-end with 20 failures.

2019-10-31 02:21 UTC, didip commented
`sh test.sh` ran until the end with 45 failures.

Anything else I need to do? Is this good enough to merge?

2019-10-31 03:23 UTC, jbrockmendel commented
> sh test.sh ran until the end with 45 failures.  Anything else I need to do? Is this good enough to merge?

You'll need to get the tests passing.  This can include xfailing if appropriate.

2019-10-31 04:21 UTC, didip commented
@jbrockmendel They look unrelated though. Example:

```
XFAIL pandas/tests/test_strings.py::TestStringMethods::test_api_per_method[empty0-rsplit-Index-category]
  reason: Raising too restrictively; solved by GH 23167
```

2019-11-03 14:21 UTC, didip commented
Ran `sh ci/code_checks.sh`. All of its failures are DocTest.

All of them failed because the expectation and results are in the wrong order. Examples:

```
4253 Examples
4254 --------
4255 >>> df = pd.DataFrame({'name': ['Raphael', 'Donatello'],
4256 ...                    'mask': ['red', 'purple'],
4257 ...                    'weapon': ['sai', 'bo staff']})
4258 >>> df.to_csv(index=False)
Expected:
    'name,mask,weapon\nRaphael,red,sai\nDonatello,purple,bo staff\n'
Got:
    'mask,name,weapon\nred,Raphael,sai\npurple,Donatello,bo staff\n'
```

or another one:

```
2665         >>> d2 = {'name': ['Alice', 'Bob'],
2666         ...       'score': [9.5, 8],
2667         ...       'employed': [False, True],
2668         ...       'kids': [0, 0]}
2669         >>> df2 = pd.DataFrame(data=d2)
2670         >>> df2
Differences (unified diff with -expected +actual):
    @@ -1,3 +1,3 @@
    -    name  score  employed  kids
    -0  Alice    9.5     False     0
    -1    Bob    8.0      True     0
    +   employed  kids   name  score
    +0     False     0  Alice    9.5
    +1      True     0    Bob    8.0
```

2019-12-02 01:01 UTC, jreback requested changes
@didip happy to take this, but needs to pass the CI (and I know you tried to fix)

ping if you can get this too work.

2019-12-02 01:01 UTC, jreback commented on requirements-dev.txt
> +tables>=3.5.2
i don't think this would work because it would require a newer numpy than is allowed in this version (1.13)

2019-12-23 04:15 UTC, alimcmaster1 commented
@didip - thanks for the effort so far - do you still want to work on this?

2019-12-23 18:23 UTC, didip commented
To be honest, I am running out of capacity to continue this work. I am completely unfamiliar with the build system to properly debug further problems.

2020-01-01 21:00 UTC, jreback commented
closing, but still happy for someone to push a PR to close this issue.

2020-01-01 21:00 UTC, closed without merging