REF: Parametrize value_counts tests
pandas-dev/pandas pull request #28537
Opened 2019-09-19 20:03 UTC by dsaxton

Parametrizes the for loop in `test_series_groupby_value_counts`.  As a side note, this test seems to run for a pretty long time (a minute and a half); should it operate on less data perhaps?

2019-09-19 20:12 UTC, TomAugspurger commented
Not sure about reducing the number of cases. Looking into the history of
the test may shed some light.

On Thu, Sep 19, 2019 at 3:03 PM Daniel Saxton <notifications@github.com>
wrote:

> Parametrizes the for loop in test_series_groupby_value_counts. As a side
> note, this test seems to run for a pretty long time (a minute and a half);
> should it operate on less data perhaps?
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/pandas-dev/pandas/pull/28537
> Commit Summary
>
>    - REF: Parametrize value_counts tests
>
> File Changes
>
>    - *M* pandas/tests/groupby/test_value_counts.py
>    <https://github.com/pandas-dev/pandas/pull/28537/files#diff-0> (35)
>
> Patch Links:
>
>    - https://github.com/pandas-dev/pandas/pull/28537.patch
>    - https://github.com/pandas-dev/pandas/pull/28537.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/28537?email_source=notifications&email_token=AAKAOIRYYZGEICZGM5XL6KTQKPLJDA5CNFSM4IYPPMYKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HMQLQSQ>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKAOIVFWNSFHKWE5653L4TQKPLJDANCNFSM4IYPPMYA>
> .
>

2019-09-20 02:39 UTC, WillAyd commented
Yea a minute and a half for one benchmark is too much. Is there a way to get it down to a few seconds and still get the same measurement?

2019-09-20 02:42 UTC, WillAyd requested changes

2019-09-20 02:42 UTC, WillAyd commented on pandas/tests/groupby/test_value_counts.py
> +    "isort, normalize, sort, ascending, dropna", list(product((False, True), repeat=5))
Not really a fan of using `itertools` to generate parametrization. Could you instead write this as:

```python
@pytest.mark.parametrize("isort", [True, False])
@pytest.mark.parametrize("normalize", [True, False])
...
```

Equivalent at the end of the day but I think clearer and match the rest of the codebase

2019-09-20 12:47 UTC, jreback commented
this is a comprehensive test and is marked as slow, so perf is ok, other than @WillAyd comment lgtm.

2019-09-20 14:27 UTC, WillAyd approved these changes

2019-09-20 14:27 UTC, merged

2019-09-20 14:28 UTC, WillAyd commented
Thanks @dsaxton