[DOC ] add warning about empty results in sample
pandas-dev/pandas pull request #28592
Opened 2019-09-24 06:29 UTC by roelhogervorst

As referred to in https://github.com/pandas-dev/pandas/issues/28495.

- [x] closes #28495
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-09-24 06:29 UTC, pep8speaks commented
Hello @roelhogervorst! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/generic.py`](https://github.com/pandas-dev/pandas/blob/a5f26671f05f1492be504da1766a4a2a0e71480a/pandas/core/generic.py):

> [Line 4864:71](https://github.com/pandas-dev/pandas/blob/a5f26671f05f1492be504da1766a4a2a0e71480a/pandas/core/generic.py#L4864): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 4865:89](https://github.com/pandas-dev/pandas/blob/a5f26671f05f1492be504da1766a4a2a0e71480a/pandas/core/generic.py#L4865): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 88 characters)

2019-10-11 22:14 UTC, WillAyd commented
Can you provide something more descriptive? This as is is rather ambiguous

2019-10-14 03:27 UTC, datapythonista commented on pandas/core/generic.py
> +            result can be empty.
Something like `If the computed number of samples is zero, the result will be empty.` would be better I think. It feels quite obvious to me, but if you find that surprising, happy to see it clarified.

2019-10-22 01:17 UTC, WillAyd requested changes
@roelhogervorst can you address comments?

2019-11-07 23:49 UTC, WillAyd commented
Closing as stale but @roelhogervorst ping if you'd like to pick back up

2019-11-07 23:49 UTC, closed without merging