DEPR: Deprecate Index.set_value
pandas-dev/pandas pull request #28621
Opened 2019-09-25 19:32 UTC by topper-123

- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Deprecates ``Index.set_value``. This is a very little used and confusing method IMO.

For a given index ``idx``, array ``arr``,  value ``idx_val`` in ``idx`` and a new value of ``val``, ``idx.set_value(arr, idx_val, val)``  is equivalent to ``arr[idx.get_loc(idx_val) = val``, which is more standard and should be used instead.

2019-09-26 07:05 UTC, jorisvandenbossche commented
There has been some discussion before about `Index.get_value`: https://github.com/pandas-dev/pandas/issues/19728, where the thought was that this might be relied upon.  
But in contrast to get_value, set_value is apparently something we don't use internally ourselves?

cc @shoyer

2019-09-26 16:29 UTC, topper-123 commented
Yeah that's right, ``Index.set_value`` is not used by pandas itself.

2019-10-02 04:09 UTC, WillAyd reviewed
I think this makes sense so OK by me

2019-10-02 04:09 UTC, WillAyd commented on doc/source/whatsnew/v1.0.0.rst
> +  is equivalent to ``arr[idx.get_loc(idx_val) = val``, which should be used instead (:issue:`28621`).
```suggestion
  is equivalent to ``arr[idx.get_loc(idx_val) = val]``, which should be used instead (:issue:`28621`).
```

missing end bracket

2019-10-02 12:07 UTC, jreback requested changes
lgtm ping on green

2019-10-02 12:07 UTC, jreback commented on doc/source/whatsnew/v1.0.0.rst
> +- :meth:`Index.set_values` has been deprecated. For a given index ``idx``, array ``arr``,
does this actually render? you should remove set_values from api.rst

2019-10-02 21:41 UTC, topper-123 commented
I've updated the PR according to comments.

In addition, I've added ``"set_value"`` to ``Index._deprecations``.

2019-10-03 02:39 UTC, WillAyd approved these changes
lgtm @jreback

2019-10-03 06:54 UTC, jorisvandenbossche approved these changes

2019-10-03 06:56 UTC, merged

2019-10-03 06:56 UTC, jorisvandenbossche commented
Thanks!