Fixes issue #8193
pandas-dev/pandas pull request #28659
Opened 2019-09-27 18:58 UTC by Leostayner

- [ ] closes #8193
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Line/bar plot accepts color by dictonary.

2019-09-28 07:45 UTC, gfyoung commented on pandas/tests/plotting/test_misc.py
> +        # Test plot color dictionary format
Reference issue number as a comment

2019-10-01 23:10 UTC, pep8speaks commented
Hello @Leostayner! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`pandas/tests/plotting/test_misc.py`](https://github.com/pandas-dev/pandas/blob/0e4b33eec93878f65f1f655e123cb7e7cc74fb54/pandas/tests/plotting/test_misc.py):

> [Line 423:9](https://github.com/pandas-dev/pandas/blob/0e4b33eec93878f65f1f655e123cb7e7cc74fb54/pandas/tests/plotting/test_misc.py#L423): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 424:9](https://github.com/pandas-dev/pandas/blob/0e4b33eec93878f65f1f655e123cb7e7cc74fb54/pandas/tests/plotting/test_misc.py#L424): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 432:9](https://github.com/pandas-dev/pandas/blob/0e4b33eec93878f65f1f655e123cb7e7cc74fb54/pandas/tests/plotting/test_misc.py#L432): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 437:9](https://github.com/pandas-dev/pandas/blob/0e4b33eec93878f65f1f655e123cb7e7cc74fb54/pandas/tests/plotting/test_misc.py#L437): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

2019-10-18 21:31 UTC, jreback commented
can you merge master

2019-10-24 13:26 UTC, Leostayner commented
@jreback, Merged!

2019-11-08 00:11 UTC, WillAyd requested changes
Can you add a whatsnew note for v1.0.0 and update the docstring for `.plot` to reflect this?

2019-11-21 13:58 UTC, Leostayner commented
Updated whatsnew. Now where should I update the `.plot` docstring? Here is where I think it should be, is it right?

https://github.com/pandas-dev/pandas/blob/c0050e071d0cc31501d4f730c27a81f3a126fc5c/pandas/plotting/_core.py#L855

https://github.com/pandas-dev/pandas/blob/c0050e071d0cc31501d4f730c27a81f3a126fc5c/pandas/plotting/_core.py#L924

2019-12-27 19:41 UTC, jreback commented
can you merge master

2020-01-16 09:41 UTC, MarcoGorelli commented
Hi @Leostayner - sorry to chase you up on this, just wanted to ask whether you're still working on it :)

2020-01-16 09:53 UTC, gfyoung commented
@MarcoGorelli - given the silence, I think you're okay to finish this up if you want.

2020-01-16 11:37 UTC, MarcoGorelli commented
Sure. Looks like it's gone stale, so I've taken it forward in #31071 (note to OP: you're welcome to reopen this if you want to keep working on it)

2020-01-19 08:16 UTC, closed without merging