TST: Add test for categorical with str and tuples
pandas-dev/pandas pull request #28693
Opened 2019-09-30 20:10 UTC by has2k1

The bug is not present any more.

- [ ] closes #21416
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-09-30 20:10 UTC, pep8speaks commented
Hello @has2k1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/arrays/categorical/test_constructors.py`](https://github.com/pandas-dev/pandas/blob/01c8f2d49e2a41ae4bd1a665f3aa31e160ba9d28/pandas/tests/arrays/categorical/test_constructors.py):

> [Line 606:9](https://github.com/pandas-dev/pandas/blob/01c8f2d49e2a41ae4bd1a665f3aa31e160ba9d28/pandas/tests/arrays/categorical/test_constructors.py#L606): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

2019-10-01 20:31 UTC, has2k1 commented
This bug affects  numpy versions *1.13.3* to *1.15.4*. Versions greater than *1.16.0* are fine. However, since it was a regression in numpy (e.g. *1.11.0* is okay), I do not know if it will not show up again.

The tests are failing for lower versions of numpy.

2019-10-03 20:46 UTC, topper-123 commented
To check for different versions of numpy, you need to skipif using the ``compat.numpy._np_version_under1p*` bools.

2019-10-05 13:37 UTC, topper-123 requested changes

2019-10-05 13:37 UTC, topper-123 commented on pandas/tests/arrays/categorical/test_constructors.py
> +            raise pytest.skip("Skipping for NumPy <1.16")
Better to decorate the test method with ``@pytest.mark.skipif( _np_version_under1p16, reason="Skipping for NumPy <1.16")``.

2019-10-06 21:59 UTC, topper-123 approved these changes

2019-10-06 22:02 UTC, merged

2019-10-06 22:04 UTC, topper-123 commented
Thanks,  @has2k1!