DOC: Reference level name as Term of HDFStore.select query (#28791)
pandas-dev/pandas pull request #28793
Opened 2019-10-04 16:14 UTC by nrebena

Add documentation for default level name with HDFStore MultiIndex.

- [x] closes #28791
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-10-06 22:22 UTC, jreback requested changes

2019-10-06 22:22 UTC, jreback commented on doc/source/user_guide/io.rst
> +Using level name when querying MultiIndex DataFrame.
can you make this a sub-section (like using timedelta64), name it Query MultiIndex (also rename Using timedelta64 Query timedelta64)

2019-10-06 22:22 UTC, jreback commented on doc/source/user_guide/io.rst
> +Using ``level_0`` and ``level_1`` for MultiIndex without name.
give a statement about how the level names of ``level_i`` for the index of the level are available automatically if the level name is None

2019-10-06 22:23 UTC, jreback commented
are there any other issues about this (can you do a search)

2019-10-07 17:54 UTC, nrebena commented
> are there any other issues about this (can you do a search)

I did not find any other issue specifically about this (I did not even find it on StackOverflow). I guess everybody name its index…

I did find the issue #6208 that speficy that you cant use "index" as an level name (still true on master). I guess it is worth a note in section Storing MultiIndex DataFrames.

2019-10-16 12:11 UTC, jreback approved these changes

2019-10-16 12:11 UTC, merged

2019-10-16 12:11 UTC, jreback commented
thanks @nrebena