TST: Dataframe KeyError when getting nonexistent category (#28799)
pandas-dev/pandas pull request #28809
Opened 2019-10-06 22:10 UTC by bravech

- [ ] closes #28799 
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry
Added test to check for correct exception when accessing a nonexistent category in a DataFrame.

2019-10-06 22:38 UTC, jreback requested changes

2019-10-06 22:38 UTC, jreback commented on pandas/tests/frame/test_indexing.py
> +    def test_get_nonexistant_category(self):
this needs to go in pandas/tests/groupby/test_categorical.py

2019-10-06 22:38 UTC, jreback commented on pandas/tests/frame/test_indexing.py
> +        with pytest.raises(KeyError) as col_error:
use the ```message=``` arg of ``pytest.raises`` rather than checking like this

2019-10-07 01:29 UTC, dsaxton commented on pandas/tests/frame/test_indexing.py
> +    def test_get_nonexistant_category(self):
Should be spelled `nonexistent`

2019-10-08 12:53 UTC, jreback approved these changes

2019-10-08 12:53 UTC, merged

2019-10-08 12:54 UTC, jreback commented
thanks @bravech