BUG: Patch for skipping seek() when loading Excel files from url
pandas-dev/pandas pull request #28826
Opened 2019-10-07 19:51 UTC by hellbe

- [ x] closes #28825
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Discovered that 0.25.x reintroduces #20437. Proposing the same fix here.

2019-10-07 20:54 UTC, WillAyd requested changes
Hmm OK thanks. I think this was intentionally removed here https://github.com/pandas-dev/pandas/pull/26233/files#r279220473 so @tdamsma might have thoughts as well.

In any case is there a way to add a test for this?

2019-10-07 21:31 UTC, tdamsma commented
I just tested with 25.1 (on osx), can't reproduce. I took this from #20437:
```python
import pandas

url = "https://raw.github.com/pandas-dev/pandas/master/pandas/tests/io/data/test1.xls"
df = pandas.read_excel(url)
print(df)
```

I believe there are tests for downloading from a url included in the test suite.

2019-10-07 21:42 UTC, WillAyd commented
Thanks @tdamsma ! I actually was not able to reproduce this on master either. @hellbe can you try there?

2019-10-08 13:22 UTC, hellbe commented
Oh, slight difference in use actually. The reason is that I downloaded first using `requests`. The following code reproduces:

```
import pandas
import requests
url = "https://raw.github.com/pandas-dev/pandas/master/pandas/tests/io/data/test1.xls"
r = requests.get(url, stream=True)
df = pandas.read_excel(r.raw)
print(df)
```

Throws `UnsupportedOperation: seek`

2019-10-08 13:31 UTC, hellbe commented
So in my case I can easily fix my code by passing the url directly instead. However, there might be other situations where extra functionality from `requests` is needed, e.g. for authentication.

https://requests.kennethreitz.org/en/master/user/quickstart/#raw-response-content

So `excel_read()` is fed an [urllib3.response.HTTPResponse](https://urllib3.readthedocs.io/en/latest/reference/#urllib3.response.HTTPResponse) object which doesn't have a `seek()` method.

2019-10-08 13:37 UTC, hellbe commented
Updated the issue with the above information.

2019-10-08 14:07 UTC, hellbe commented
Updated the PR commit to match above and refer to new issue

2019-10-08 14:13 UTC, hellbe commented
Rebased

2019-10-08 14:17 UTC, hellbe commented
Surely possible to create a test case specifically for reading urllib3's HTTPResponse objects but I'm not it's meaningful tbh

2019-10-08 15:04 UTC, WillAyd commented
@ocefpaf would this fall under the umbrella of what you were trying to accomplish in #21504? Wonder if it would be better to address comprehensively in a common func rather than one-off for excel files

2019-10-08 18:08 UTC, ocefpaf commented
> @ocefpaf would this fall under the umbrella of what you were trying to accomplish in #21504? Wonder if it would be better to address comprehensively in a common func rather than one-off for excel files

Probably. Let me check. I still have the old PR here waiting for me. (I'm at a code sprint at the moment, Might tackle it again this week.)

2019-10-09 18:07 UTC, ocefpaf commented
@WillAyd I can confirm that #21504 (or the new incarnation that I'll push in a few hours) will "fix this" b/c pandas will use `requests` and wrap it in a `BytesIO` object, with `seek`, if requests is installed.

2019-10-11 14:38 UTC, WillAyd commented
Thanks for the PR @hellbe but I think this is getting more comprehensively addressed in #28874 by @ocefpaf so let's track this there

2019-10-11 14:38 UTC, closed without merging