Allow all int types for merge
pandas-dev/pandas pull request #28875
Opened 2019-10-09 18:58 UTC by jjlkant

- [ ] closes #28870
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-10-09 19:52 UTC, mroeschke requested changes
* Needs a test to confirm the behavior has been fixed.
* Needs a new whatsnew entry (in 0.25.2)

2019-10-09 23:12 UTC, mroeschke commented on doc/source/whatsnew/v0.25.2.rst
> +- Fix to ensure all int dtypes can be used in :meth:`pandas.core.reshape.merge_asof` when using a tolerance value (:issue:`28870`).
`` :func:`merge_asof` `` and maybe clarify that any non-int64 integer previously raised an erroneous `MergeError`

2019-10-09 23:15 UTC, mroeschke commented on pandas/tests/reshape/merge/test_merge_asof.py
> +        left["a"] = left["a"].astype(np.int32)
Could you `pytest.mark.parameterize` over more int dtypes. e.g. `[int, "int64", "int32", "int16", "int8", "uint64", "uint32", "uint16", "uint8"]`

2019-10-10 05:23 UTC, mroeschke approved these changes

2019-10-10 12:54 UTC, jreback requested changes

2019-10-10 12:54 UTC, jreback commented on doc/source/whatsnew/v0.25.2.rst
> +- Fix to ensure all int dtypes can be used in :func:`merge_asof` when using a tolerance value. Before every non-int64 type would raise an erroneous ``MergeError`` (:issue:`28870`).
moved to 1.0

Before -> Previously

2019-10-10 12:54 UTC, jreback commented on pandas/tests/reshape/merge/test_merge_asof.py
> +        [int, "int64", "int32", "int16", "int8", "uint64", "uint32", "uint16", "uint8"],
use the any_int_dtype fixture instead

2019-10-11 12:09 UTC, jreback approved these changes

2019-10-11 12:09 UTC, merged

2019-10-11 12:09 UTC, jreback commented
thanks @jjlkant