TST: add test_series_any_timedelta for GH17667
pandas-dev/pandas pull request #28942
Opened 2019-10-12 17:51 UTC by rohitsanj

Test case example is the same as the one given in the issue #17667 

- [x] closes #17667 
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-10-12 20:15 UTC, simonjayhawkins commented on pandas/tests/test_multilevel.py
> +    def test_series_any_timedelta(self):
can you add the issue number

2019-10-12 20:15 UTC, simonjayhawkins commented on pandas/tests/test_multilevel.py
> +        ex = Series(data=[False, True], index=["a", "t"])
use expected

2019-10-12 20:15 UTC, simonjayhawkins commented on pandas/tests/test_multilevel.py
> +        ex = Series(data=[False, True])
same

2019-10-12 20:16 UTC, simonjayhawkins requested changes
@rohitsanj thanks for the PR. couple of suggestions.

2019-10-13 01:51 UTC, rohitsanj commented on pandas/tests/test_multilevel.py
> +    def test_series_any_timedelta(self):
added

2019-10-13 16:34 UTC, mroeschke approved these changes

2019-10-13 16:44 UTC, simonjayhawkins approved these changes

2019-10-13 16:44 UTC, merged

2019-10-13 16:44 UTC, simonjayhawkins commented
Thanks @rohitsanj

2019-10-13 17:24 UTC, mroeschke commented
@rohitsanj feel free to contribute more tests like this! https://github.com/pandas-dev/pandas/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+label%3A%22Needs+Tests%22