Fix mypy errors for pandas\tests\* #28926 (test_algos.py)
pandas-dev/pandas pull request #28960
Opened 2019-10-13 23:14 UTC by lrm25

- [x ] closes #28926 (partial)
- [x] tests added / passed (verified that tests still pass)
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [N/A] whatsnew entry

2019-10-13 23:20 UTC, simonjayhawkins commented on pandas/tests/test_algos.py
> +            def __eq__(self, other: object):
I _think_ we only need to correct the signature to resolve the error at this stage. @WillAyd 

```suggestion
            def __eq__(self, other):
```

2019-10-13 23:21 UTC, simonjayhawkins commented
Thanks @lrm25 for the PR.

2019-10-13 23:25 UTC, simonjayhawkins requested changes
@lrm25 can you remove the test_algos section from setup.cfg

2019-10-14 00:22 UTC, simonjayhawkins approved these changes
@lrm25 lgtm @WillAyd

2019-10-14 00:28 UTC, WillAyd commented
Nice find. Not sure this was even testing what was intended previously, so definitely speaks to annotations being useful for tests

2019-10-14 00:28 UTC, merged

2019-10-14 00:28 UTC, WillAyd commented
Thanks!