Test decimal typefix
pandas-dev/pandas pull request #28988
Opened 2019-10-15 06:01 UTC by yogendrasoni

- [ ] closes #28926
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-10-15 15:30 UTC, simonjayhawkins requested changes
@yogendrasoni Thanks for the PR. A couple of suggestions.

2019-10-15 15:30 UTC, simonjayhawkins commented on setup.cfg
can you remove this entire section from setup.cfg

2019-10-26 04:21 UTC, yogendrasoni commented on pandas/tests/extension/decimal/test_decimal.py
> +class TestDtype(BaseDecimal, base.BaseDtypeTests):  # type: ignore
tried putting staticmethod, BaseExtensionTests methods takes (left,right, some arguments) but BaseDecimal takes (left,right,*args,**kwargs) it is still showing incompatible by mypy, didn't find anything to solve this. I need to study more to solve this.

2019-11-08 01:00 UTC, WillAyd commented on pandas/tests/extension/decimal/test_decimal.py
> +class TestDtype(BaseDecimal, base.BaseDtypeTests):  # type: ignore
I think #28994 has the same issue. What error are you getting after trying what @simonjayhawkins suggested?

2019-11-12 16:43 UTC, jbrockmendel commented
@simonjayhawkins am i right in thinking that the `# type: ignore` this uses is something were trying pretty hard to avoid?

2019-11-13 15:05 UTC, simonjayhawkins commented on pandas/tests/extension/decimal/test_decimal.py
> +class TestDtype(BaseDecimal, base.BaseDtypeTests):  # type: ignore
yes we have two modules that are reporting mypy errors due to the same root issue.

2019-11-13 15:06 UTC, simonjayhawkins commented
> @simonjayhawkins am i right in thinking that the `# type: ignore` this uses is something were trying pretty hard to avoid?

correct.

2019-12-17 17:46 UTC, WillAyd commented
@yogendrasoni is this still active?

2019-12-27 19:51 UTC, jreback commented
closing as stale, if you'ld like to continue, pls ping.

2019-12-27 19:51 UTC, closed without merging