tests/indexing/test_coercion.py typefix
pandas-dev/pandas pull request #28990
Opened 2019-10-15 08:10 UTC by lukasbk

- [ ] xref #28926
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-10-15 18:18 UTC, simonjayhawkins approved these changes
@lukasbk lgtm @WillAyd

2019-10-16 03:46 UTC, WillAyd requested changes

2019-10-16 03:46 UTC, WillAyd commented on pandas/tests/indexing/test_coercion.py
> +    rep = {}  # type: Dict[str, List[Any]]
Minor nit but can you just do `List` instead of `List[Any]`? Equivalent but I think the former is used throughout code base

2019-10-16 23:52 UTC, WillAyd approved these changes

2019-10-16 23:52 UTC, merged

2019-10-16 23:52 UTC, WillAyd commented
Thanks @lukasbk