Fix mypy error in pandas\tests\indexes\interval\test_interval_tree.py
pandas-dev/pandas pull request #29021
Opened 2019-10-16 04:32 UTC by pqzx

- [ ] relates to #28926
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-10-16 10:05 UTC, simonjayhawkins requested changes
@pqzx Thanks for the PR.

2019-10-16 10:05 UTC, simonjayhawkins commented on pandas/tests/indexes/interval/test_interval_tree.py
> +    @pytest.mark.parametrize("order", map(lambda x: list(x), permutations(range(3))))
as this is a known issue with mypy, see https://github.com/python/mypy/issues/6697, i'd prefer not to change the code here.

add a `# type: ignore` and add the issue number as a comment i.e.

```python
    # https://github.com/python/mypy/issues/6697
    # error: Argument 1 to "map" has incompatible type "Type[List[Any]]";
    #  expected "Callable[[Tuple[int, ...]], List[_T]]"
    @pytest.mark.parametrize("order", map(list, permutations(range(3))))  # type: ignore
```

2019-10-16 10:05 UTC, simonjayhawkins commented on pandas/tests/indexes/interval/test_interval_tree.py
> +    @pytest.mark.parametrize("order", map(lambda x: list(x), permutations(range(3))))
same

2019-10-16 11:02 UTC, pep8speaks commented
Hello @pqzx! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/indexes/interval/test_interval_tree.py`](https://github.com/pandas-dev/pandas/blob/e09936b099e7e1e18ba9025e068e0e18f20b5df5/pandas/tests/indexes/interval/test_interval_tree.py):

> [Line 160:73](https://github.com/pandas-dev/pandas/blob/e09936b099e7e1e18ba9025e068e0e18f20b5df5/pandas/tests/indexes/interval/test_interval_tree.py#L160): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 170:73](https://github.com/pandas-dev/pandas/blob/e09936b099e7e1e18ba9025e068e0e18f20b5df5/pandas/tests/indexes/interval/test_interval_tree.py#L170): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment

2019-10-16 12:59 UTC, simonjayhawkins approved these changes
@pqzx lgtm @WillAyd

2019-10-16 18:53 UTC, WillAyd commented
Hmm just out of curiosity does this work if you did `(list(x) for x in permutations(range(3)))`. Assuming equivalent I think would be easier to track than the type ignore

2019-10-17 06:14 UTC, pqzx commented
> 
> 
> Hmm just out of curiosity does this work if you did `(list(x) for x in permutations(range(3)))`. Assuming equivalent I think would be easier to track than the type ignore

Yes, this works. Updated to use this instead.

2019-10-21 07:28 UTC, simonjayhawkins commented
@pqzx can you fix lint error and merge master

2019-10-22 23:25 UTC, pqzx commented
@simonjayhawkins sorry for the noob question, what's the lint error in this case? Is it the line length?

2019-10-23 00:55 UTC, WillAyd commented
Looks like the checks are fine. I think if you merge master and try again should work (have had intermittent failures recently)

2019-11-07 21:49 UTC, simonjayhawkins commented
@WillAyd OK to merge?

2019-11-07 23:07 UTC, WillAyd approved these changes

2019-11-07 23:08 UTC, merged

2019-11-07 23:08 UTC, WillAyd commented
Thanks @pqzx !