Remove TestData from series-tests test_repr.py
pandas-dev/pandas pull request #29148
Opened 2019-10-22 12:04 UTC by SaturnFromTitan

Part of #22550

* Replaced TestData usage in `pandas/tests/series/test_repr.py` with fixtures

- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2019-10-22 13:25 UTC, SaturnFromTitan commented
I added a new empty_series fixture as it is mentioned in the issue description. I've seen more places where this can be used, so I hope this is fine with you

2019-10-22 18:50 UTC, WillAyd approved these changes
lgtm

2019-10-23 12:43 UTC, jreback requested changes

2019-10-23 12:43 UTC, jreback commented on pandas/tests/series/conftest.py
> +
don't add these fixtures, just use Series()

2019-10-23 14:23 UTC, jreback approved these changes

2019-10-23 14:23 UTC, merged

2019-10-23 14:23 UTC, jreback commented
thanks