Fix SS06 errors
pandas-dev/pandas pull request #29255
Opened 2019-10-28 17:10 UTC by profwacko

SS06 (Summary should fit in a single line) errors fixed (#29254) for the following:

```
 pandas.DataFrame.slice_shift
 pandas.DataFrame.to_period
 pandas.DataFrame.plot
 pandas.DataFrame.sparse.density
 pandas.DataFrame.style
 pandas.Series.as_blocks
 pandas.Series.ix
 pandas.Series.ptp
 pandas.DataFrame.as_blocks
 pandas.DataFrame.ix
```
Validated with `python scripts/validate_docstrings.py`

Also referencing issue: #27977

2019-10-28 20:47 UTC, WillAyd requested changes
Looks good. Minor comments to improve styling / remove repetition

2019-10-28 20:47 UTC, WillAyd commented on pandas/core/arrays/sparse/accessor.py
> +        Ratio of non-sparse points to total (dense) data points represented
I think you can remove this extended summary; it says the same thing as the first line

2019-10-28 20:47 UTC, WillAyd commented on pandas/core/generic.py
> +        Convert the frame to a dict of dtype.
```suggestion
        Convert the frame to a dict of dtype -> Constructor Types.
```

2019-10-28 20:47 UTC, WillAyd commented on pandas/core/generic.py
> +        Convert the frame to a dict of dtype-> Constructor Types that each
Remove  this as well; just duplicative

2019-10-28 20:47 UTC, WillAyd commented on pandas/plotting/_core.py
>      Make plots of Series or DataFrame using the backend specified by the
```suggestion
    Uses the backend specified by the
```

2019-10-28 20:47 UTC, WillAyd commented on pandas/core/frame.py
> +        Property returning a Styler object containing methods for building
Looks like the word `of` is misspelled here

2019-10-28 20:47 UTC, WillAyd commented on pandas/core/frame.py
> +        Property returning a Styler object containing methods for building
```suggestion
        Contains methods for building a styled HTML representation of the DataFrame.
```

2019-10-29 00:44 UTC, profwacko commented
Hi @WillAyd, added the changes you suggested.

2019-10-29 03:14 UTC, WillAyd approved these changes

2019-10-29 03:14 UTC, merged

2019-10-29 03:14 UTC, WillAyd commented
Great thanks @profwacko !