Fix SS06 formatting errors
pandas-dev/pandas pull request #29283
Opened 2019-10-30 09:39 UTC by MomIsBestFriend

Errors fixed (from the list in #29254 ):
pandas.io.formats.style.Styler.from_custom_template
pandas.io.formats.style.Styler.apply
pandas.io.formats.style.Styler.applymap
pandas.io.formats.style.Styler.set_properties
pandas.io.formats.style.Styler.clear
pandas.io.formats.style.Styler.background_gradient
pandas.io.formats.style.Styler.use
pandas.io.formats.style.Styler.where

Validated the fixes with ```python scripts/validate_docstrings.py```
Refrencing issue: #29254

2019-10-30 16:18 UTC, WillAyd requested changes
Some minor grammatical things but otherwise lgtm

2019-10-31 06:43 UTC, MomIsBestFriend commented
@WillAyd Ty so much for the corrections. Not taken for granted the fact you literally marked the problems.

2019-10-31 07:38 UTC, gfyoung approved these changes

2019-10-31 08:03 UTC, jorisvandenbossche approved these changes

2019-10-31 08:03 UTC, merged