Pv feature2
pandas-dev/pandas pull request #29354
Opened 2019-11-02 14:50 UTC by pv8473h12

- [x] closes GH 9113
- [x] tests added / passed
- [x] passes `black pandas`
- [x] new test added: test_replace_no_cast()

2019-11-02 20:08 UTC, jreback requested changes

2019-11-02 20:08 UTC, jreback commented on pandas/tests/series/test_replace.py
> +        result = series.replace(to_replace, value)
to_replace and value are the same for the cases, so don't make these args, just put it in the code

2019-11-02 20:20 UTC, jreback approved these changes

2019-11-02 20:21 UTC, jreback commented
lgtm. ping on green.

2019-11-02 23:58 UTC, pv8473h12 commented
All green @jreback

2019-11-03 01:42 UTC, merged

2019-11-03 01:42 UTC, WillAyd commented
Thanks @pv8473h12