Fix pipe docs
pandas-dev/pandas pull request #29368
Opened 2019-11-02 17:30 UTC by alimcmaster1

- [x] closes #27054

See the image below which highlights what i've done here

![image](https://user-images.githubusercontent.com/16733618/68074732-4f5e1b80-fd96-11e9-96ea-d2f40e07ee3e.png)

cc. @datapythonista to review

2019-11-02 23:49 UTC, alimcmaster1 commented
Unsure why the code coverage has dramatically reduced..

2019-11-03 01:51 UTC, WillAyd requested changes
Want to avoid using lambdas where possible

2019-11-03 01:51 UTC, WillAyd commented on doc/source/getting_started/basics.rst
> +        df['city_name'] = df['city_and_code'].apply(lambda x: x.split(', ')[0])
```suggestion
        df['city_name'] = df['city_and_code'].str.split(",").str.get(0)
```

2019-11-03 01:51 UTC, WillAyd commented on doc/source/getting_started/basics.rst
> +        df['city_and_country'] = df[col].apply(lambda x: f'{x}-{country_name}')
```suggestion
        df['city_and_country'] = df[col] + "-USA"
```

2019-11-04 23:01 UTC, alimcmaster1 commented
Thanks for the comments @WillAyd totally agree - updated

2019-11-04 23:34 UTC, WillAyd approved these changes
lgtm @datapythonista care to take a look here?

2019-11-06 17:51 UTC, merged

2019-11-06 17:51 UTC, WillAyd commented
Thanks @alimcmaster1

2019-11-06 23:18 UTC, alimcmaster1 commented
Thanks @WillAyd

2019-11-07 01:48 UTC, datapythonista commented
Sorry I couldn't check this before. Looks great, good job @alimcmaster1. Happy to see this finally improved.