Add documentation linking to sqlalchemy
pandas-dev/pandas pull request #29373
Opened 2019-11-02 19:16 UTC by cruzzoe

- [x] closes #23086
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2019-11-02 23:55 UTC, alimcmaster1 commented
Hey - Can you submit updates on the same PR https://github.com/pandas-dev/pandas/pull/29363 in the future - means we don’t have to re-review..

2019-11-03 09:22 UTC, cruzzoe commented
Sure. Sorry, didn't know what the correct process was.

On Sat, 2 Nov 2019, 23:56 alimcmaster1, <notifications@github.com> wrote:

> Hey - Can you submit updates on the same PR #29363
> <https://github.com/pandas-dev/pandas/pull/29363> in the future - means
> we don’t have to re-review..
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/29373?email_source=notifications&email_token=ACXR24RLKYL6A6KCSZSNGPLQRYHRXA5CNFSM4JIHRNZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEC5HSCY#issuecomment-549091595>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACXR24S5DMZ4UE3DZFZDXE3QRYHRXANCNFSM4JIHRNZQ>
> .
>

2019-11-04 16:15 UTC, WillAyd commented on pandas/core/generic.py
> +            Closing the connection is handled by the SQLAlchemy Engine. See `here \
Is this continuation necessary? Don't think we have anywhere else?

2019-11-04 16:53 UTC, cruzzoe commented
Yes. Without the continuation it would not render correctly

On Mon, 4 Nov 2019, 16:16 William Ayd, <notifications@github.com> wrote:

> *@WillAyd* commented on this pull request.
> ------------------------------
>
> In pandas/core/generic.py
> <https://github.com/pandas-dev/pandas/pull/29373#discussion_r342136081>:
>
> > @@ -2646,6 +2646,10 @@ def to_sql(
>          con : sqlalchemy.engine.Engine or sqlite3.Connection
>              Using SQLAlchemy makes it possible to use any DB supported by that
>              library. Legacy support is provided for sqlite3.Connection objects.
> +
> +            Closing the connection is handled by the SQLAlchemy Engine. See `here \
>
> Is this continuation necessary? Don't think we have anywhere else?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/29373?email_source=notifications&email_token=ACXR24TV7YBIBMVJDKXW7EDQSBDEDA5CNFSM4JIHRNZ2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCKGET5A#pullrequestreview-311183860>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACXR24UPCPMYWUERVRTBILTQSBDEDANCNFSM4JIHRNZQ>
> .
>

2019-11-04 22:42 UTC, WillAyd requested changes
Might be a personal thing but I find the wording here rather confusing. By saying `Closing the connection is handled by the SQLAlchemy Engine` I got the impression it was done automatically, but that is not the case. Any chance you can clarify or reword that to make it clear that pandas does nothing special here, i.e. the user is responsible for management of the connection?

There was a previous PR #27972 that was pretty close to getting merged if you'd like to take a look

2019-11-04 22:56 UTC, alimcmaster1 commented
I'm thinking we do something like this - similar to the other PR:

![image](https://user-images.githubusercontent.com/16733618/68165015-34d2a080-ff56-11e9-8c02-a4ba902bb723.png)

@WillAyd do you agree? I also got confused by current wording.

2019-11-04 23:32 UTC, WillAyd commented
Yea that sounds like a great idea

2019-11-06 19:56 UTC, pep8speaks commented
Hello @cruzzoe! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/generic.py`](https://github.com/pandas-dev/pandas/blob/b8d420945d54e9e6ae6aa6f436a511e0721d3961/pandas/core/generic.py):

> [Line 2648:89](https://github.com/pandas-dev/pandas/blob/b8d420945d54e9e6ae6aa6f436a511e0721d3961/pandas/core/generic.py#L2648): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

* In the file [`pandas/io/sql.py`](https://github.com/pandas-dev/pandas/blob/b8d420945d54e9e6ae6aa6f436a511e0721d3961/pandas/io/sql.py):

> [Line 364:88](https://github.com/pandas-dev/pandas/blob/b8d420945d54e9e6ae6aa6f436a511e0721d3961/pandas/io/sql.py#L364): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 365:87](https://github.com/pandas-dev/pandas/blob/b8d420945d54e9e6ae6aa6f436a511e0721d3961/pandas/io/sql.py#L365): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 366:74](https://github.com/pandas-dev/pandas/blob/b8d420945d54e9e6ae6aa6f436a511e0721d3961/pandas/io/sql.py#L366): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2019-11-07 00:06 UTC, alimcmaster1 commented
LGTM (But I’m on mobile so can’t do a doc build to check how this renders).
CC @WillAyd

2019-11-07 00:07 UTC, alimcmaster1 commented on pandas/core/generic.py
> +                <https://docs.sqlalchemy.org/en/13/core/connections.html>`_
Not sure if the blank line is necessary

2019-11-07 20:46 UTC, WillAyd commented
Content looks good. Can you build locally and just post a screenshot of how it renders to be safe?

2019-11-22 08:45 UTC, cruzzoe commented
> Content looks good. Can you build locally and just post a screenshot of how it renders to be safe?

![pd1](https://user-images.githubusercontent.com/11476338/69411182-5f697b00-0d04-11ea-9172-476f4bec31c4.png)
![pd2](https://user-images.githubusercontent.com/11476338/69411183-5f697b00-0d04-11ea-99c1-53452ecbba22.png)

2019-11-22 16:19 UTC, WillAyd approved these changes

2019-11-22 16:19 UTC, merged

2019-11-22 16:19 UTC, WillAyd commented
Thanks @cruzzoe !