BUG: GH29310 HDF file compression not working
pandas-dev/pandas pull request #29404
Opened 2019-11-04 23:06 UTC by yp1996

- [x] closes #29310 
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Re #29310, the complib and complevel parameters were not being passed down all the way previously, hence HDF compression not working.  

I noticed that the implementation of to_hdf() specifies that compression is not allowed for fixed formats:  
` if not s.is_table and complib:
            raise ValueError("Compression not supported on Fixed format stores")`

I'm guessing that means the performance comparison section for https://github.com/pandas-dev/pandas/pull/28890/files will also need to be updated to remove the test_fixed_compress test @WuraolaOyewusi? 

Also, after the update, the following test is currently failing: 
![image](https://user-images.githubusercontent.com/13011161/68165200-a4736c00-ff13-11e9-964f-3ebc105e7e46.png)

due to a ValueError for using compression with a fixed format, and I'm not sure as to why the expected behaviour for this test is what it is? Why should setting complib disable compression? I would appreciate any further info on that.

2019-11-04 23:40 UTC, WillAyd requested changes
Does this only affect those two arguments? There are a few more documented on to_hdf:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_hdf.html

cc @TomAugspurger another one to maybe consider for io kwargs

2019-11-04 23:40 UTC, WillAyd commented on pandas/tests/io/pytables/test_store.py
> +                df.to_hdf(tmpfile, gname, complib=lib, complevel=lvl, format="table")
Can you add a dedicated test for the change you are making instead of just modifying this?

2019-11-04 23:40 UTC, WillAyd commented on pandas/io/pytables.py
> +        complevel : int, 0-9, default None
Can you align the docstring with the signature? Looks like `compilb` and `complevel` are swapped

2019-11-04 23:40 UTC, WillAyd commented on pandas/io/pytables.py
> +        complib=None,
Can you add annotations for new parameters?

2019-11-05 03:44 UTC, pep8speaks commented
Hello @yp1996! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/io/pytables.py`](https://github.com/pandas-dev/pandas/blob/2c3b9d422d1a53f608c22ff113efe0c06e6ae653/pandas/io/pytables.py):

> [Line 266:76](https://github.com/pandas-dev/pandas/blob/2c3b9d422d1a53f608c22ff113efe0c06e6ae653/pandas/io/pytables.py#L266): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 937:22](https://github.com/pandas-dev/pandas/blob/2c3b9d422d1a53f608c22ff113efe0c06e6ae653/pandas/io/pytables.py#L937): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 938:23](https://github.com/pandas-dev/pandas/blob/2c3b9d422d1a53f608c22ff113efe0c06e6ae653/pandas/io/pytables.py#L938): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 939:23](https://github.com/pandas-dev/pandas/blob/2c3b9d422d1a53f608c22ff113efe0c06e6ae653/pandas/io/pytables.py#L939): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 940:25](https://github.com/pandas-dev/pandas/blob/2c3b9d422d1a53f608c22ff113efe0c06e6ae653/pandas/io/pytables.py#L940): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 941:21](https://github.com/pandas-dev/pandas/blob/2c3b9d422d1a53f608c22ff113efe0c06e6ae653/pandas/io/pytables.py#L941): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 941:22](https://github.com/pandas-dev/pandas/blob/2c3b9d422d1a53f608c22ff113efe0c06e6ae653/pandas/io/pytables.py#L941): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 985:89](https://github.com/pandas-dev/pandas/blob/2c3b9d422d1a53f608c22ff113efe0c06e6ae653/pandas/io/pytables.py#L985): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 88 characters)
> [Line 1107:89](https://github.com/pandas-dev/pandas/blob/2c3b9d422d1a53f608c22ff113efe0c06e6ae653/pandas/io/pytables.py#L1107): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (118 > 88 characters)
> [Line 1580:89](https://github.com/pandas-dev/pandas/blob/2c3b9d422d1a53f608c22ff113efe0c06e6ae653/pandas/io/pytables.py#L1580): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 88 characters)

* In the file [`pandas/tests/io/pytables/test_store.py`](https://github.com/pandas-dev/pandas/blob/2c3b9d422d1a53f608c22ff113efe0c06e6ae653/pandas/tests/io/pytables/test_store.py):

> [Line 268:9](https://github.com/pandas-dev/pandas/blob/2c3b9d422d1a53f608c22ff113efe0c06e6ae653/pandas/tests/io/pytables/test_store.py#L268): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 268:16](https://github.com/pandas-dev/pandas/blob/2c3b9d422d1a53f608c22ff113efe0c06e6ae653/pandas/tests/io/pytables/test_store.py#L268): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 271:17](https://github.com/pandas-dev/pandas/blob/2c3b9d422d1a53f608c22ff113efe0c06e6ae653/pandas/tests/io/pytables/test_store.py#L271): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 273:13](https://github.com/pandas-dev/pandas/blob/2c3b9d422d1a53f608c22ff113efe0c06e6ae653/pandas/tests/io/pytables/test_store.py#L273): [E121](https://duckduckgo.com/?q=pep8%20E121) continuation line under-indented for hanging indent

2019-11-05 14:33 UTC, WuraolaOyewusi commented
> * [x]  closes #29310
> * [x]  passes `black pandas`
> * [x]  passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
> 
> Re #29310, the complib and complevel parameters were not being passed down all the way previously, hence HDF compression not working.
> 
> I noticed that the implementation of to_hdf() specifies that compression is not allowed for fixed formats:
> ` if not s.is_table and complib: raise ValueError("Compression not supported on Fixed format stores")`
> 
> I'm guessing that means the performance comparison section for https://github.com/pandas-dev/pandas/pull/28890/files will also need to be updated to remove the test_fixed_compress test @WuraolaOyewusi?
> 
> Also, after the update, the following test is currently failing:
> ![image](https://user-images.githubusercontent.com/13011161/68165200-a4736c00-ff13-11e9-964f-3ebc105e7e46.png)
> 
> due to a ValueError for using compression with a fixed format, and I'm not sure as to why the expected behaviour for this test is what it is? Why should setting complib disable compression? I would appreciate any further info on that.

I think rather than silently refuse compression of fixed format, It should raise an error instead.

2019-11-23 16:02 UTC, jbrockmendel commented
pls rebase

2019-12-01 01:08 UTC, jbrockmendel commented
rebased, fixing a couple of annotations `foo: str = None` --> `foo: Optional[str] = None`

2020-01-01 18:20 UTC, jreback commented
@yp1996 can you merge master

2020-01-21 13:04 UTC, MarcoGorelli commented
HI @yp1996  - sorry to chase you up, just wanted to ask whether you're still working on this :)
Seems that there's some test failures, but I can't check them as it says "build not found"

2020-01-22 06:52 UTC, yp1996 commented
Hey @jreback @MarcoGorell, sorry i'd gone mia - i've merged with master but the build is still failing, please feel free to look into it!

2020-01-27 11:57 UTC, MarcoGorelli commented
> the build is still failing, please feel free to look into it!

For a start, there's some linting issues - did you run `black` against the `.py` files you changed?

2020-02-07 07:55 UTC, MarcoGorelli commented
Closing as it looks like this has gone stale and @joybhallaa has expressed interest in working on it

2020-02-07 07:55 UTC, closed without merging