Add docstrings to arithmetic fixtures
pandas-dev/pandas pull request #29441
Opened 2019-11-06 20:27 UTC by dalgarno

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-11-06 20:47 UTC, datapythonista reviewed
Thanks for the contribution @dalgarno.

This looks like an improvement, but after reading the docstrings it's still not clear what those fixture do, or how they should be used. Do you mind trying to rephrase, and may be use examples?

2019-11-08 16:31 UTC, WillAyd requested changes

2019-11-08 16:31 UTC, WillAyd commented on pandas/tests/arithmetic/conftest.py
> +    Uses vector of length 5 for broadcasting with `numeric_idx` fixture,
Can you model the extended description here after what you have in the other method? I find that quite nice, but don't really understand this one

2019-11-12 21:40 UTC, pep8speaks commented
Hello @dalgarno! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/arithmetic/conftest.py`](https://github.com/pandas-dev/pandas/blob/6a6b93bea10d9d93857656c3901713d60686be33/pandas/tests/arithmetic/conftest.py):

> [Line 61:65](https://github.com/pandas-dev/pandas/blob/6a6b93bea10d9d93857656c3901713d60686be33/pandas/tests/arithmetic/conftest.py#L61): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 62:1](https://github.com/pandas-dev/pandas/blob/6a6b93bea10d9d93857656c3901713d60686be33/pandas/tests/arithmetic/conftest.py#L62): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 65:1](https://github.com/pandas-dev/pandas/blob/6a6b93bea10d9d93857656c3901713d60686be33/pandas/tests/arithmetic/conftest.py#L65): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2019-11-13 01:53 UTC, jreback commented
lgtm. side issue we should rename these to maybe ``one_value``and so on and move to pandas/conftest.py (but for another PR)

2019-11-17 15:39 UTC, dalgarno commented
@WillAyd can you approve if you're happy?

2019-11-17 16:05 UTC, datapythonista approved these changes
lgtm, thanks @dalgarno

2019-11-18 01:40 UTC, WillAyd approved these changes

2019-11-18 01:40 UTC, merged

2019-11-18 01:40 UTC, WillAyd commented
Thanks @dalgarno