[WIP] Validate dtype when Int64Index, UInt64Index, or Float64Index are cons…
pandas-dev/pandas pull request #29545
Opened 2019-11-11 14:44 UTC by MarcoGorelli

…tructed

- [ ] closes #29539 
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-11-11 16:19 UTC, jschendel reviewed
Thanks! Can you add an entry to the 1.0 whatsnew under the "Bug Fixes - Numeric" subsection?

2019-11-11 16:19 UTC, jschendel commented on pandas/core/indexes/numeric.py
> +        if not dtype:
Maybe make this `if dtype is None:` to be extra safe in case another falsey value is passed for `dtype`.

2019-11-11 16:19 UTC, jschendel commented on pandas/core/indexes/numeric.py
> +            if not is_signed_integer_dtype(dtype):
I think it'd be fine to combine these in a single condition:
```python
if cls._typ == "int64index" and not is_signed_integer_dtype(dtype):
```

2019-11-11 16:19 UTC, jschendel commented on pandas/tests/indexes/test_numeric.py
> +        with pytest.raises(ValueError):
Can you use the `match` kwarg to check the error message?  And add the GH issue as a comment?

2019-11-11 16:19 UTC, jschendel commented on pandas/core/indexes/numeric.py
> +                raise ValueError("Incorrect `dtype` passed")
Can you add a little more info to these messages, like what is expected and what was received?

2019-11-11 19:38 UTC, MarcoGorelli commented
Done, but I don't think it's right yet, need to understand what goes on in test_coercion (shouldn't be necessary to allow Float64 index with integer dtype?)

2019-11-12 11:22 UTC, MarcoGorelli commented
@jschendel thanks for your review :) I've updated my PR as per your suggestions

2019-11-12 23:28 UTC, jreback requested changes
can you conform RangeIndex._validate_dtype to the same signature here

2019-11-12 23:28 UTC, jreback commented on pandas/core/indexes/numeric.py
> +    def _validate_dtype(cls, dtype):
looks ok, can you type this

2019-11-12 23:28 UTC, jreback commented on pandas/core/indexes/numeric.py
> +        cls._validate_dtype(cls, dtype)
make this a ```@classmethod``` then you don't need to pass cls

2019-11-13 11:17 UTC, MarcoGorelli commented
Thanks for your reviews, @jreback and @jschendel , really appreciate it. Have updated the PR accordingly.

2019-11-16 00:34 UTC, jschendel reviewed
lgtm overall; one small comment

2019-11-16 00:34 UTC, jschendel commented on pandas/tests/indexes/test_range.py
> +        with pytest.raises(ValueError):
Can you check the error message via the `match` keyword here, and for the other instances where you updated this.  IIRC there's an open issue where we're trying to add this across the entire test suite.

2019-11-16 10:32 UTC, MarcoGorelli commented
@jschendel sure, done!

2019-11-18 00:53 UTC, jschendel approved these changes

2019-11-18 00:53 UTC, jschendel commented
Can you merge master to resolve the conflict in the whatsnew?

2019-11-18 11:20 UTC, MarcoGorelli commented
Done - thanks for the approval!

2019-11-18 13:43 UTC, jreback approved these changes

2019-11-18 13:44 UTC, merged

2019-11-18 13:44 UTC, jreback commented
thanks @MarcoGorelli