CLN: Make non-empty kwargs fail
pandas-dev/pandas pull request #29625
Opened 2019-11-14 22:56 UTC by topper-123

In #29624 I made change so random kwargs weren't passed to ``Index._simple_new``. I'v found out after merging that the selected solution dropped non-empty kwargs, which isn't great either.

This version ensures that passing non-accepted kwargs raises, so ``pd.Index(['a'], foo="foo")`` raises a TypeError. Instead of raising a TypeError, should we deprecate adding random attributes to Index?

2019-11-14 23:13 UTC, topper-123 commented on pandas/core/indexes/base.py
> +                   ABCIntervalIndex)
Without this, if the first element is a IntervalIndex, a"side" parameter is passed to ``_shallow_copy_with_infer`` ind the call will fail.

2019-11-14 23:16 UTC, topper-123 commented on pandas/tests/indexes/multi/test_constructor.py
> +    result = pd.Index(index, name="A")
Both result an dexpected are normal ``Index`` and instantiating with a ``names`` parameter should fail.

2019-11-16 21:21 UTC, jreback requested changes

2019-11-16 21:21 UTC, jreback commented on pandas/core/indexes/base.py
> +                    msg = f"Unexpected keyword arguments {set(kwargs)!r}"
I would just use this one (the set), no need to make a super-detailed error message

2019-11-16 22:01 UTC, jreback approved these changes

2019-11-16 22:01 UTC, jreback commented
lgtm. merge on green.

2019-11-17 10:23 UTC, merged