ENH: merge set validation (#29649)
pandas-dev/pandas pull request #29651
Opened 2019-11-15 22:33 UTC by robertdavidwest

Added new feature to pandas merge to validate "set-theory" relationship
between left and right dataframes. Updated docs and tests for new
feature.

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-11-15 22:34 UTC, pep8speaks commented
Hello @robertdavidwest! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/frame.py`](https://github.com/pandas-dev/pandas/blob/49e6058efd5bff0ab585c91046324ab041082449/pandas/core/frame.py):

> [Line 219:78](https://github.com/pandas-dev/pandas/blob/49e6058efd5bff0ab585c91046324ab041082449/pandas/core/frame.py#L219): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2019-11-15 23:12 UTC, robertdavidwest commented
I would have attempted the "whatsnew" entry but I didn't really understand what was being asked [here](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#documenting-your-code). If anyone is able to describe exactly what should be done here. I'd be happy to add it to the Pull Request.

2019-11-15 23:29 UTC, jreback requested changes
can you show the use for this?

2019-11-15 23:43 UTC, robertdavidwest commented
@jreback use case is. Suppose you have two dataframes:
```
df1 = pd.DataFrame({"key": [1,2,3]
df2 = pd.DataFrame({"key": [1,2,3]
```
Suppose that you want to perform an outer merge these dataframes on `key` and that you want to validate that there are no records in the second dataframe that do not have a match in the first. You could achieve this using existing features as follows:

```
result = pd.merge(df1, df2, on='key', how='outer', indicator=True)
assert(set(result._merge) == {'left_only', 'both'})
result = result.drop(axis=1, labels="_merge")
```
This is pretty clunky especially if you do it often in your merges. The intended new feature is allow this to be expressed within the call to the merge function as follows:

```
result = pd.merge(df1, df2, on='key', how='outer', indicator_assert_set={'left_only', 'both'})
```

2019-11-16 00:07 UTC, jreback commented
> This is pretty clunky especially if you do it often in your merges. The intended new feature is allow this to be expressed within the call to the merge function as follows:

so write a function and call it when you want

every added piece of api adds mental overhead to the user and of course requires upkeep on the project. simpler is always better.

2019-11-16 00:12 UTC, robertdavidwest commented
You could have said the exact same thing about the ‘validate’ parameter. I
use to use a wrapper function around ‘pd.merge’ until that feature was
added.

On Fri, Nov 15, 2019 at 7:07 PM Jeff Reback <notifications@github.com>
wrote:

> This is pretty clunky especially if you do it often in your merges. The
> intended new feature is allow this to be expressed within the call to the
> merge function as follows:
>
> so write a function and call it when you want
>
> every added piece of api adds mental overhead to the user and of course
> requires upkeep on the project. simpler is always better.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/29651?email_source=notifications&email_token=AAUD6LGCE2B2C34WFDZSUL3QT42VFA5CNFSM4JOBSBU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEHC4HY#issuecomment-554577439>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAUD6LEPFUKZ6B2UMTPY4KTQT42VFANCNFSM4JOBSBUQ>
> .
>

2019-11-16 00:14 UTC, jreback commented
indicator could not trivially be computed from the results
where this can

2019-11-16 00:32 UTC, robertdavidwest commented
Yes. I was referencing the ‘validate’ field. That’s pretty trivial right?
Just checking the indices. But that helpful little parameter goes a long
way I think. Especially in terms encouraging people to think more about the
importance of these kinds of things when merging, settings higher standard
for what should be considered when merging. Anyways, just my opinion I
guess. Appreciate your time.

On Fri, Nov 15, 2019 at 7:14 PM Jeff Reback <notifications@github.com>
wrote:

> indicator could not trivially be computed from the results
> where this can
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/29651?email_source=notifications&email_token=AAUD6LEDPYHADCLVZNSASJDQT43PRA5CNFSM4JOBSBU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEHDIJQ#issuecomment-554578982>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAUD6LDTS4DSCDMSGYVLHHLQT43PRANCNFSM4JOBSBUQ>
> .
>

2019-11-17 00:49 UTC, WillAyd commented
Hi @robertdavidwest and thanks for the PR. I'm also though -1 on this addition. Note that we have a very high bar for adding to the API at this point, so if you have other ideas in the future might be best to open an issue for discussion first, though hope at the very least you learnt more about the pandas internals through this.

2019-11-17 00:49 UTC, closed without merging