DEPR: remove itemsize, data, base, flags, strides
pandas-dev/pandas pull request #29918
Opened 2019-11-28 17:21 UTC by jbrockmendel

and un-deprecated `item`, though im not sure where that goes in the whatsnew

2019-11-28 17:35 UTC, jreback requested changes

2019-11-28 17:35 UTC, jreback commented on pandas/core/base.py
> +            return next(iter(self))
so we have sufficient tests that this preserves the correct type
eg  Timestamp with tz 

i think it does but should test

2019-11-28 19:13 UTC, jorisvandenbossche commented
You will need to remove some things from the API docs (that's what the doc failure is complaining about)

2019-11-28 20:25 UTC, jbrockmendel commented
Will update per comments.  Also need to change the implementation so item() raises for len!=1

2019-11-28 20:52 UTC, jorisvandenbossche commented
Can you leave the `item` change for a separate PR? 
That change deserves specific attention I think, not hidden in an "easy remove some stuff" PR

2019-11-28 20:58 UTC, jbrockmendel commented
> Can you leave the item change for a separate PR?

Sounds good

2019-11-29 20:39 UTC, jbrockmendel commented
updated+green, un-doing `item` changes

2019-11-29 22:34 UTC, jreback commented
lgtm, need a rebase

2019-11-29 23:24 UTC, jreback approved these changes

2019-11-30 00:31 UTC, jbrockmendel commented
rebased+green

2019-11-30 17:47 UTC, merged

2019-11-30 17:47 UTC, WillAyd commented
Thanks @jbrockmendel