DEPR: tz_convert in the Timestamp constructor raises
pandas-dev/pandas pull request #29929
Opened 2019-11-29 20:24 UTC by mroeschke

- [x] xref #23621
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2019-11-29 21:02 UTC, jbrockmendel commented on pandas/tests/scalar/timestamp/test_timestamp.py
>              Timestamp(box(**kwargs), tz="US/Pacific")
can we also have a case with the tzinfo kwarg

2019-11-29 21:03 UTC, jbrockmendel commented
one test request, otherwise LGTM

2019-11-29 21:08 UTC, WillAyd approved these changes
lgtm outside of @jbrockmendel request

2019-11-29 22:26 UTC, jreback requested changes

2019-11-29 22:26 UTC, jreback commented on doc/source/whatsnew/v1.0.0.rst
> +- Timezone converting a tz-aware ``datetime.datetime`` or :class:`Timestamp` with :class:`Timestamp` and the ``tz`` argument now raises a ``ValueError`` (:issue:`23621`)
can you re-word this a bit, hard to grok.

2019-11-30 17:31 UTC, jbrockmendel commented on pandas/tests/scalar/timestamp/test_timestamp.py
>              Timestamp(box(**kwargs), tz="US/Pacific")
i think we need separate `pytest.raises` contexts (and the tzinfo kwarg is supposed to be a tzinfo object)

2019-11-30 22:46 UTC, jbrockmendel commented
LGTM pending green

2019-12-01 02:51 UTC, mroeschke commented
All green.

2019-12-01 21:38 UTC, jreback approved these changes

2019-12-01 21:38 UTC, merged

2019-12-01 21:38 UTC, jreback commented
thanks @mroeschke