CLN: move odf import inline in excel benchmark
pandas-dev/pandas pull request #29924
Opened 2019-11-29 09:02 UTC by jorisvandenbossche

I know this is an optional dependency, but IMO it's still nice that running a different benchmark still works when you don't have odf installed (noticed this yesterday when running the isnull benchmarks). It's similar to pytest skipping if an optional dependency is not installed.

2019-11-29 17:30 UTC, WillAyd commented
Does the asv.conf not account for this when building the environment?

2019-11-29 22:27 UTC, jreback commented
> Does the asv.conf not account for this when building the environment?

is odf in the asv? (that's a separate issue)

2019-12-09 10:15 UTC, jorisvandenbossche commented
Sorry for the slow reply: you are right the env creation handles this fine, but if you use `asv dev` or `asv run ` with some config, you can use your existing environment. So therefore I just ran into this (my dev environment was created before odpy was added as optional dependency). So no big deal, I just find it a bit friendlier to not directly error when you are trying to run those benchmarks.

2019-12-09 11:23 UTC, jreback commented
we don’t do this for any other optional deps
this makes for a confusing style

i would say simply update the asv environment

2019-12-09 11:29 UTC, jorisvandenbossche commented
> i would say simply update the asv environment

It's *not* the asv environment

> we don’t do this for any other optional deps

We do this constantly in eg tests (you can run tests without having all optional dependencies installed)

2019-12-09 12:00 UTC, jreback requested changes
we do not do this for asv at all

-1 on this change

2019-12-09 16:39 UTC, WillAyd commented
Yea I agree with Jeff - I think confusing to special case just this one library

2019-12-09 19:20 UTC, jorisvandenbossche commented
>  I think confusing to special case just this one library

I am happy to do it for *all* libraries, which are those odfpy imports and a single sqlalchemy import

2019-12-10 16:16 UTC, WillAyd commented
I still would rather not change this; we only document using `asv continuous` in the contributing guide as of now

2019-12-20 19:28 UTC, jbrockmendel commented
1) Avoiding special casing is good (@jreback and @WillAyd's points)
2) The frictions in using asv in development are a PITA, things that mitigate that are good (@jorisvandenbossche's point)

I'm inclined to think the special casing here is pretty benign and 2 is more important.

2019-12-27 19:56 UTC, jreback commented
I would rather have asv hard fail than special case. special cases have a trend of making code harder to grok and splintering style. so closing this, but would take a PR to make *alls* optional deps not make it hard fail, or we do nothing.

2019-12-27 19:56 UTC, closed without merging