BUG: fix Series.interpolate(method='index') with unsorted index
pandas-dev/pandas pull request #29943
Opened 2019-12-01 15:18 UTC by immaxchen

`Series.interpolate(method='index')` use [numpy.interp](https://docs.scipy.org/doc/numpy/reference/generated/numpy.interp.html) under the hood, which cannot work with unsorted X values. Here we sort the known data for `numpy.interp`.

- [x] closes #21037
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2019-12-01 22:51 UTC, jreback requested changes

2019-12-01 22:51 UTC, jreback commented on pandas/tests/series/test_missing.py
> +    def test_interpolate_unsorted_index(self):
can you add all of the examples from the OP.

2019-12-01 22:51 UTC, jreback commented on pandas/tests/series/test_missing.py
> +        expected = ts.sort_index(ascending=True).interpolate(method="index")
can you hard-code the expected result (e.g. don't use interpolate)

2019-12-01 22:51 UTC, jreback commented on pandas/tests/series/test_missing.py
> +    def test_interpolate_unsorted_index(self):
you can likely parameterize this test

2019-12-01 22:51 UTC, jreback commented on pandas/core/missing.py
> +        seq = np.argsort(inds[valid])
can you add a comment here on what you are doing

2019-12-01 22:51 UTC, jreback commented on pandas/core/missing.py
> +        seq = np.argsort(inds[valid])
call this ``indexer``

2019-12-01 22:51 UTC, jreback commented on doc/source/whatsnew/v1.0.0.rst
> +- Bug in :meth:`Series.interpolate` when using method ``index`` with unsorted index. (:issue:`21037`)
``method=`index` `` with an unsorted index, would previously return incorrect results.

2019-12-03 15:32 UTC, immaxchen commented
Hi @jreback, all done, please have a look.

2019-12-03 16:18 UTC, jreback approved these changes

2019-12-03 16:18 UTC, jreback commented
lgtm. @TomAugspurger  if any comments

2019-12-03 22:36 UTC, TomAugspurger approved these changes

2019-12-03 22:36 UTC, TomAugspurger commented
Thanks!

2019-12-03 22:36 UTC, merged