BUG: merge_asof with tz_aware left index and right column
pandas-dev/pandas pull request #29940
Opened 2019-11-30 22:33 UTC by mroeschke

- [x] closes #29864
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2019-11-30 22:44 UTC, jreback requested changes

2019-11-30 22:44 UTC, jreback commented on pandas/tests/reshape/merge/test_merge_asof.py
> +        result = pd.merge_asof(
can u test the reverse case as well right_index=True with a left column

2019-12-01 02:50 UTC, mroeschke commented
Tested and green.

2019-12-01 21:32 UTC, jreback approved these changes

2019-12-01 21:32 UTC, merged

2019-12-01 21:33 UTC, jreback commented
thanks @mroeschke