add variable types
pandas-dev/pandas pull request #30024
Opened 2019-12-04 00:04 UTC by JojoYY

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-12-04 01:26 UTC, alimcmaster1 commented
Thanks for the PR: Could you please sort your imports using isort
```
4.3.21
Check import format using isort
ERROR: /home/runner/work/pandas/pandas/pandas/plotting/_core.py Imports are incorrectly sorted.
```

2019-12-04 01:27 UTC, alimcmaster1 requested changes

2019-12-04 01:27 UTC, alimcmaster1 commented on pandas/plotting/_core.py
>      by=None,
Could we type these too?

2019-12-04 04:50 UTC, WillAyd requested changes
Thanks for the PR. Looks good and I think CI failures are unrelated / have been fixed on master since this was created.

To be sure, can you locally on your `pydata_sprint` branch run:

```sh
git fetch upstream
git merge upstream/master
git push origin pydata_sprint
```

I think should get CI green for this. Flag me down at PyData if you have any questions

2019-12-04 10:44 UTC, simonjayhawkins commented on pandas/plotting/_core.py
> +    layout: Optional[Tuple[int]] = None,
```suggestion
    layout: Optional[Tuple[int, int]] = None,
```
`layout`is a 2-tuple of (row,columns)

2019-12-04 10:44 UTC, simonjayhawkins commented on pandas/plotting/_core.py
> +    rot: Optional[Union[float, int]] = 0,
```suggestion
    rot: Optional[float] = 0,
```
int is a subtype of float

2019-12-04 10:44 UTC, simonjayhawkins commented on pandas/plotting/_core.py
> +    figsize: Optional[Tuple[int, float]] = None,
```suggestion
    figsize: Optional[Tuple[float, float]] = None,
```
figsize is a 2-tuple (width, height). I assume that if height accepts a float, so does width?

2019-12-04 10:44 UTC, simonjayhawkins commented on pandas/plotting/_core.py
> +    column: Optional[Union[str, List[str]]] = None,
from the docstring...
```
column : str or list of str, optional
    Column name or list of names, or vector.
```
is vector any sequence of strings?

2020-01-01 17:22 UTC, jreback commented
closing as stale, if you'd like to continue, pls ping.

2020-01-01 17:22 UTC, closed without merging