f string in io.common
pandas-dev/pandas pull request #30022
Opened 2019-12-03 23:26 UTC by daniellebrown

- [ ] ref #29547
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-12-04 01:33 UTC, alimcmaster1 commented
Thanks for the PR. Please run black on your changes
```
Checking black formatting
would reformat /home/runner/work/pandas/pandas/pandas/io/common.py
Oh no! 💥 💔 💥
1 file would be reformatted, 875 files would be left unchanged.
```

2019-12-04 01:33 UTC, alimcmaster1 requested changes
Please run black

2019-12-04 04:46 UTC, WillAyd requested changes
Thanks for the PR. Looks good and I think CI failures are unrelated / have been fixed on master since this was created.

To be sure, can you locally on your shiny-new-feature branch run:

```sh
git fetch upstream
git merge upstream/master
git push origin shiny-new-feature
```

I think should get CI green for this. Flag me down at PyData if you have any questions

W.r.t black you will also want to run `black pandas/io/common.py`

2019-12-04 11:18 UTC, simonjayhawkins commented on pandas/io/common.py
> +                        " Only one file per ZIP: {zip_names}"
```suggestion
                        f" Only one file per ZIP: {zip_names}"
```
`f` needed on this line

2019-12-06 20:14 UTC, alimcmaster1 commented
If you merge master as @WillAyd suggested above test failures should be fixed

2019-12-08 00:27 UTC, WillAyd commented
I think CI failure is unrelated yet again - can you merge master one more time to be sure?

2019-12-08 04:39 UTC, daniellebrown commented
Hi,
I've attempted to merge to master, however, receive the following error messages. Any help much appreciated!

![errormsg](https://user-images.githubusercontent.com/21073989/70384297-94dfac80-1931-11ea-8f2d-313156fea5d0.JPG)

2019-12-08 17:46 UTC, jreback commented
@daniellebrown you need to ``git push origin shiny-new-feature -f``

2019-12-09 04:49 UTC, WillAyd commented
@daniellebrown might want to try one more of:

```
git fetch upstream
git merge upstream/master
git push origin shiny-new-feature
```

To resolve CI failures

2019-12-10 12:16 UTC, simonjayhawkins commented
@daniellebrown https://github.com/pandas-dev/pandas/pull/30022#issuecomment-561434493 see https://dev.pandas.io/docs/development/contributing.html#python-pep8-black

2019-12-10 12:24 UTC, simonjayhawkins requested changes
https://github.com/pandas-dev/pandas/pull/30022#discussion_r353685117

2019-12-11 08:03 UTC, daniellebrown commented
Any advice on how to fix this error: 

would reformat /home/runner/work/pandas/pandas/pandas/io/common.py
Oh no! 💥 💔 💥
1 file would be reformatted, 880 files would be left unchanged.

I've run black several times and it doesn't seem to do the trick.

2019-12-11 10:37 UTC, simonjayhawkins approved these changes
@daniellebrown lgtm @WillAyd

2019-12-11 13:16 UTC, merged

2019-12-11 13:17 UTC, jreback commented
thanks @daniellebrown  very nice

2019-12-11 19:02 UTC, daniellebrown commented
thanks @jreback @WillAyd @simonjayhawkins !