fstring in io.sql
pandas-dev/pandas pull request #30026
Opened 2019-12-04 00:36 UTC by lexy-lixinyu

- [ ] ref #29547
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-12-04 04:55 UTC, WillAyd requested changes
Thanks for the PR. Looks good and I think CI failures are unrelated / have been fixed on master since this was created.

To be sure, can you locally on your `shiny-new-feature` branch run:

```sh
git fetch upstream
git merge upstream/master
git push origin shiny-new-feature
```

I think should get CI green for this. Flag me down at PyData if you have any questions

2019-12-04 09:57 UTC, simonjayhawkins commented on pandas/io/sql.py
> +                        "levels, which is {nlevels}"
this line needs an `f`

2019-12-04 09:59 UTC, simonjayhawkins commented on pandas/io/sql.py
> +                    raise ValueError(f"The type of {col} is not a " "SQLAlchemy type ")
```suggestion
                    raise ValueError(f"The type of {col} is not a SQLAlchemy type ")
```

2019-12-04 10:06 UTC, simonjayhawkins commented on pandas/io/sql.py
> +                    f"Execution failed on sql: {args[0]}\n{exc}\nunable " "to rollback"
```suggestion
                    f"Execution failed on sql: {args[0]}\n{exc}\nunable to rollback"
```

2019-12-04 10:08 UTC, simonjayhawkins commented on pandas/io/sql.py
> +                    raise ValueError(f"{col} ({my_type!s}) not a string")
Is the `!s` required here?

2019-12-14 00:36 UTC, WillAyd commented
@lexy-lixinyu can you commit changes as suggested by @simonjayhawkins ?

2019-12-17 20:13 UTC, jbrockmendel commented on pandas/io/sql.py
> +                    raise ValueError(f"The type of {col} is not a " "SQLAlchemy type ")
remove trailing space?

2019-12-24 20:04 UTC, jbrockmendel commented
just pushed edits removing unintentional " " in two places.

2019-12-25 20:17 UTC, datapythonista commented
Thanks for the work on this @lexy-lixinyu, can you address the two last comments, and update your branch from master please? This is ready to be merged after it.

If you need help let us know.

2019-12-31 00:10 UTC, jbrockmendel commented
just pushed edits to address outstanding comments

2019-12-31 00:15 UTC, datapythonista approved these changes
lgtm

2019-12-31 09:02 UTC, merged

2019-12-31 09:02 UTC, simonjayhawkins commented
Thanks @lexy-lixinyu and @jbrockmendel