TST: DataFrameGroupBy.shift Loses TimeZone in datetime64 columns
pandas-dev/pandas pull request #30153
Opened 2019-12-09 10:23 UTC by tranctan

Adding test case for issue GH30134

- [x] closes #30134
- [x] tests added / passed

2019-12-09 16:55 UTC, WillAyd requested changes
Thanks for the PR! Looks good just a few edits

Can you also move this to pandas/tests/groupby/test_transform.py?

2019-12-09 16:55 UTC, WillAyd commented on pandas/tests/dtypes/test_dtypes.py
> +        df = pd.DataFrame({"a": [1, 1], "date": dt.datetime.now(tz=pytz.utc)})
```suggestion
        df = pd.DataFrame({"a": [1, 1], "date": pd.Timestamp.utcnow()})
```

Slightly more idiomatic

2019-12-09 16:55 UTC, WillAyd commented on pandas/tests/dtypes/test_dtypes.py
> +        assert expected == result
Can you build the actual expected series and use `tm.assert_series_equal(result, expected)`? Should see examples of this throughout tests

2019-12-10 12:43 UTC, jreback requested changes

2019-12-10 12:43 UTC, jreback commented on pandas/tests/groupby/test_transform.py
> +
can you move to pandas/tests/groupby/test_groupby.py, near the other _shift tests

2019-12-10 13:12 UTC, jreback approved these changes

2019-12-10 13:12 UTC, jreback commented
lgtm ping on green

2019-12-11 11:21 UTC, merged

2019-12-11 11:21 UTC, simonjayhawkins commented
Thanks @tranctan