CLN: no need for mixin, move non-index timedelta arithmetic test
pandas-dev/pandas pull request #30220
Opened 2019-12-11 23:29 UTC by jbrockmendel

2019-12-12 08:34 UTC, gfyoung approved these changes

2019-12-12 13:21 UTC, jreback requested changes

2019-12-12 13:21 UTC, jreback commented on pandas/tests/indexes/test_frozen.py
>      def setup_method(self, _):
can you move this setup_method to the top (and/or use fixtures)

2019-12-13 14:09 UTC, jreback approved these changes

2019-12-13 14:09 UTC, merged

2019-12-13 14:09 UTC, jreback commented
thanks