DOC: .get_slice_bound in MultiIndex needs documentation. (#29967)
pandas-dev/pandas pull request #30257
Opened 2019-12-13 13:56 UTC by proost

- [ ] closes #29967
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

I'm not good at English. So if there are wrong sentences or awkward sentences, please let me know.

2019-12-13 17:03 UTC, WillAyd requested changes

2019-12-13 17:03 UTC, WillAyd commented on pandas/core/indexes/multi.py
> +    def get_slice_bound(self, label, side, kind) -> int:
```suggestion
    def get_slice_bound(self, label, side: str, kind: str) -> int:
```

If you know how to annotate `label` would be great as well

2019-12-14 04:34 UTC, pep8speaks commented
Hello @proost! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/indexes/multi.py`](https://github.com/pandas-dev/pandas/blob/52c9ef96fcac872e45b091ceeb0596d3b65fb064/pandas/core/indexes/multi.py):

> [Line 2447:9](https://github.com/pandas-dev/pandas/blob/52c9ef96fcac872e45b091ceeb0596d3b65fb064/pandas/core/indexes/multi.py#L2447): [E121](https://duckduckgo.com/?q=pep8%20E121) continuation line under-indented for hanging indent
> [Line 2447:9](https://github.com/pandas-dev/pandas/blob/52c9ef96fcac872e45b091ceeb0596d3b65fb064/pandas/core/indexes/multi.py#L2447): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line

2019-12-16 20:23 UTC, WillAyd requested changes
minor comment otherwise lgtm

2019-12-16 20:23 UTC, WillAyd commented on pandas/core/indexes/multi.py
> +        self, label: Union[object, Tuple[object, ...]], side: str, kind: str
```suggestion
        self, label: Union[Hashable, Sequence[Hashable]], side: str, kind: str
```

I think our labels should be a little more generic. Maybe worth putting something like this into pandas._typing @simonjayhawkins for thoughts

2019-12-17 17:00 UTC, WillAyd requested changes
@simonjayhawkins care to take a look?

2019-12-17 17:00 UTC, WillAyd commented on pandas/core/indexes/multi.py
> +from pandas._typing import OneOrMoreObjects
I think OK to leave this out of `pandas._typing` for now - just a thought for the future

2019-12-18 18:50 UTC, WillAyd requested changes

2019-12-18 18:50 UTC, WillAyd commented on pandas/core/indexes/multi.py
> +        kind : {'ix', 'loc', 'getitem'}
Is this still correct? `ix` is removed for the 1.0 release

2019-12-23 09:25 UTC, WillAyd approved these changes
lgtm. if you can fix up merge conflict ping on green

2020-01-01 17:27 UTC, merged

2020-01-01 17:27 UTC, jreback commented
thanks @proost