STY: Replace .format() to fstrings
pandas-dev/pandas pull request #30278
Opened 2019-12-14 21:32 UTC by EydenVillanueva

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

#29547

2019-12-15 14:42 UTC, simonjayhawkins commented
@EydenVillanueva Thanks for the PR. can you merge master to resolve the merge conflicts.

2019-12-15 14:49 UTC, simonjayhawkins commented on pandas/core/missing.py
> +        raise ValueError(f"method must be one of {valid}. Got '{method}' " "instead.")
```suggestion
        raise ValueError(f"method must be one of {valid}. Got '{method}' instead.")
```

2019-12-15 14:49 UTC, simonjayhawkins commented on pandas/core/indexes/period.py
> +                        f"ufunc {func.__name__}" " not supported for the PeriodIndex"
```suggestion
                        f"ufunc {func.__name__} not supported for the PeriodIndex"
```

2019-12-15 14:49 UTC, simonjayhawkins commented on pandas/core/missing.py
> +                "order needs to be specified and greater than 0; " f"got order: {order}"
```suggestion
                f"order needs to be specified and greater than 0; got order: {order}"
```

2019-12-15 20:36 UTC, EydenVillanueva commented
> @EydenVillanueva Thanks for the PR. can you merge master to resolve the merge conflicts.

Done 👍

2019-12-15 20:42 UTC, simonjayhawkins commented on pandas/core/indexes/accessors.py
> +                "datetimelike index".format(type(data))
@EydenVillanueva It looks like the merge undid some changes on master. can you merge again, see https://dev.pandas.io/docs/development/contributing.html#updating-your-pull-request

2019-12-16 11:42 UTC, simonjayhawkins requested changes
@EydenVillanueva IIUC there should only be 3 or 4 files changed?

2019-12-16 21:09 UTC, EydenVillanueva commented
> @EydenVillanueva IIUC there should only be 3 or 4 files changed?

Yes, you're right. It should be fine now. 
I'll keep checking in case you find another problem

2019-12-17 21:45 UTC, WillAyd approved these changes
lgtm merge if happy @simonjayhawkins

2019-12-18 09:57 UTC, simonjayhawkins approved these changes

2019-12-18 09:57 UTC, merged

2019-12-18 09:57 UTC, simonjayhawkins commented
Thanks @EydenVillanueva