Parquet schema
pandas-dev/pandas pull request #30270
Opened 2019-12-13 23:47 UTC by ieaves

- [X] closes #30189 
- [ ] tests added / passed
- [X] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-12-14 00:30 UTC, WillAyd requested changes
Thanks for the PR! Could you add a test case for this feature?

@jorisvandenbossche

2019-12-15 01:39 UTC, ieaves commented
Added! I'm a first time contributor to pandas - let me know if that whatsnew entry was appropriate.

2019-12-15 08:12 UTC, jorisvandenbossche commented on doc/source/whatsnew/v1.0.0.rst
> +- :meth: `to_parquet` now appropriately handles the ``schema`` argument for user defined schemas in the pyarrow engine. (:issue: `30270`)
I think you can move this to the "Other enhancements" section.

Otherwise looks good!

2019-12-15 21:29 UTC, jreback requested changes
can you also merge master

2019-12-15 21:29 UTC, jreback commented on pandas/io/parquet.py
> +        if "schema" in kwargs:
you could make this section simplier, something like

```
from_pandas_kwargs: Dict[str, Any] = {schema: kwargs.pop('schema', None)}
if index is not None:
    from_pandas_kwargs['preserve_index'] = index
```

2019-12-17 20:22 UTC, ieaves commented
@jreback I merged master but it doesn't look like the build failures are a result of changes from this PR.

2019-12-17 20:55 UTC, TomAugspurger commented
Fixing that in another PR. You can ignore it for now.

2019-12-17 20:56 UTC, ieaves commented
Awesome, let me know if there's anything else we need in here.

2019-12-18 07:55 UTC, jorisvandenbossche approved these changes

2019-12-18 10:39 UTC, merged

2019-12-18 10:39 UTC, jorisvandenbossche commented
Thanks a lot @ieaves !