BUG: raise on non-hashable Index name, closes #29069
pandas-dev/pandas pull request #30335
Opened 2019-12-18 22:55 UTC by jbrockmendel

- [x] closes #29069
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-12-19 14:15 UTC, TomAugspurger commented
To close https://github.com/pandas-dev/pandas/issues/29069, Index.name should probably be a settable property, and the setter should validate that the name is hashable.

Any perf concerns here? Things should be OK right?

2019-12-19 15:58 UTC, jbrockmendel commented
huh, looks like i got confused by `names`, which is a property.  will update.

2019-12-20 15:45 UTC, jreback requested changes

2019-12-20 15:45 UTC, jreback commented on pandas/core/indexes/base.py
> +def maybe_extract_name(name, obj):
i think this shares with series yes?

2019-12-20 15:46 UTC, jreback reviewed
can you also add a whatsnew note

2019-12-20 18:30 UTC, jbrockmendel commented
Are we OK with being able to set MultiIndex.name?  When I tried disallowing it, some tests broke

2019-12-20 19:24 UTC, jbrockmendel commented
xref #11979 should we try to address that here while were at it?

2019-12-21 19:18 UTC, jbrockmendel commented on pandas/core/indexes/base.py
> +def maybe_extract_name(name, obj):
yep

2019-12-24 14:29 UTC, jreback requested changes
lgtm. some changes

2019-12-24 14:29 UTC, jreback commented on pandas/core/indexes/base.py
> +        raise TypeError(f"{cls_name}.name must be a hashable type")
can you use type(obj).__name__ here?

2019-12-24 14:29 UTC, jreback commented on pandas/core/indexes/base.py
> +def maybe_extract_name(name, obj, cls_name="Index"):
can you type and add a doc-string

2019-12-27 01:48 UTC, jbrockmendel commented
I think #19171 becomes easier after this.

2019-12-27 15:59 UTC, jreback commented on pandas/core/indexes/base.py
> +        maybe_extract_name(value, None, type(self))
in series.py you can change name.setter to use this I think (ok for followon)

2019-12-27 16:00 UTC, jreback approved these changes
comments for a followon

2019-12-27 16:00 UTC, jreback commented on pandas/core/indexes/base.py
> +def maybe_extract_name(name, obj, cls) -> Optional[Hashable]:
see my comment above, can be more general so need to relocate i think as this is common between series/index)

2019-12-27 16:00 UTC, merged

2019-12-27 16:00 UTC, jreback commented
thanks