Removed unsigned parametrization from Intervaltree
pandas-dev/pandas pull request #30366
Opened 2019-12-19 22:17 UTC by WillAyd

Unclear if we currently consider this a feature, but I couldn't find anything explicitly asking for it so trying the removal route first

Not sure what the other alternative would be for parametrization, but I think generally we need to be careful when doing comparisons between signed and unsigned in templating or fused types

Side benefit - this gets rid of 128 build warnings and a slight perf boost to compilation

2019-12-19 22:51 UTC, jbrockmendel commented
> this gets rid of 128 build warnings

That'd be really nice

2019-12-19 23:09 UTC, WillAyd commented
Hmm missed the parametrized tests that are causing failures. Suppose this won't be as easy as I'd hoped

2019-12-20 00:58 UTC, WillAyd commented
@jschendel just saw your comment here which I think is applicable:

https://github.com/pandas-dev/pandas/pull/20651#issuecomment-381046318

From quite a while ago but does this still ring a bell? Do you know what fix you had that raised an `OverflowError`? I actually think that would be preferable?

2019-12-20 15:18 UTC, jreback requested changes
you likely need to change the inner code to actually handle uint64 with different indexers

2019-12-24 09:39 UTC, jschendel commented
I don't remember exactly what I did to get the `OverflowError` but my vague recollection is that I had to create two additional fused types for signed vs unsigned and them add them as an additional parameter to `nodes` here:

https://github.com/pandas-dev/pandas/blob/5a7b5c958c6f004c395136f9438a1ed6c04861dd/pandas/_libs/intervaltree.pxi.in#L233-L235

And then appropriately use the signed/unsigned fused types within the node classes.

I recall trying a lot of different things, so the above might not actually be the appropriate thing to do, and is really just the thing I most distinctly recall trying.

2020-01-01 23:58 UTC, WillAyd commented
@jschendel already fixed this. closing

2020-01-01 23:58 UTC, closed without merging