BUG: Series.drop() with MultiIndex: inconsistent behaviour
pandas-dev/pandas pull request #30377
Opened 2019-12-20 14:02 UTC by proost

- [ ] closes #8594
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

description:
In core.base 
```
        indexer = self.get_indexer(labels)
        mask = indexer == -1
        if mask.any():
            if errors != "ignore":
                raise KeyError(f"{labels[mask]} not found in axis")
```
single index check and raise if there is no matching indexer. But 'MultiIndex' case,
In indexes.multi
```
        codes = com.index_labels_to_array(codes)
        i = self._get_level_number(level)
        index = self.levels[i]
        values = index.get_indexer(codes)

        mask = ~algos.isin(self.codes[i], values)

        return self[mask]
```
no check. So i add check logic and raise exception if there is no matching indexer.
This bug cause from 'MultiIndex', so do not distinguish between "Series" and "DataFrame"

2019-12-22 19:31 UTC, gfyoung commented on doc/source/whatsnew/v1.0.0.rst
> +- Series and MultiIndex `.drop` with `MultiIndex` raise exception if labels not in given level (:issue:`8594`)
```suggestion
- Series and MultiIndex `.drop` with `MultiIndex` raise exception if labels not in given in level (:issue:`8594`)
```

2019-12-22 19:32 UTC, gfyoung commented on pandas/tests/indexes/multi/test_drop.py
> +        df.drop(7, level="b")
We can probably parameterize this (via `pytest` idiom).  Not necessary to do now though.

2019-12-26 01:00 UTC, jreback requested changes
looks good. ping on green.

2019-12-26 01:00 UTC, jreback commented on pandas/tests/indexes/multi/test_drop.py
> +)
can you add some test cases for ``errors='ignore'``

2019-12-26 01:01 UTC, jreback commented
also needs a rebase

2019-12-26 13:35 UTC, jreback approved these changes

2019-12-26 13:35 UTC, merged

2019-12-26 13:35 UTC, jreback commented
thanks @proost