CLN: Old string formatting: .format() -> f
pandas-dev/pandas pull request #30408
Opened 2019-12-22 17:59 UTC by DorAmram

- [ ] ref #29547
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2019-12-22 17:59 UTC, pep8speaks commented
Hello @DorAmram! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/_version.py`](https://github.com/pandas-dev/pandas/blob/85dc33621f249d4ab44cca96fa4272e8556d696d/pandas/_version.py):

> [Line 104:89](https://github.com/pandas-dev/pandas/blob/85dc33621f249d4ab44cca96fa4272e8556d696d/pandas/_version.py#L104): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 88 characters)

2019-12-22 19:06 UTC, topper-123 requested changes
Looks good, a single issue.

2019-12-22 19:06 UTC, topper-123 commented on pandas/_version.py
> +                doesn't start with prefix '{parentdir_prefix}'"""
don't use triple-quoted strings, it's not the same as two single-quoted strings.

2019-12-23 17:45 UTC, alimcmaster1 commented
Hmm I think this file is autogenerated as per @jbrockmendel comments here https://github.com/pandas-dev/pandas/pull/29518#discussion_r344826266

2019-12-23 17:53 UTC, jreback commented
yeah we can leave this one alone, do we have a check for .format usage in checks? (prob not yet)

2019-12-23 18:32 UTC, alimcmaster1 commented
> yeah we can leave this one alone, do we have a check for .format usage in checks? (prob not yet)

Not yet there are still 200+ files to tackle. 
`grep -l -R -e '%s' -e '%d' -e '\.format(' --include=*.{py,pyx} pandas/`

If we want to add a check now we can do - and users remove the file from exclude list once done?
(Would help confirm all instances of .format have been removed in the PR for a file)

2019-12-24 00:23 UTC, jbrockmendel commented
grepping for `.format(` will be complicated by the fact that we have 6 places where we `def format\(`.  But we can worry about that later.  This PR is non-actionable, closing.

2019-12-24 00:23 UTC, closed without merging