WIP/ DOC: Move 'For Developers' content from wiki to contributing docs. (#30232)
pandas-dev/pandas pull request #30406
Opened 2019-12-22 16:46 UTC by souvik3333

2019-12-22 19:22 UTC, gfyoung requested changes
There is a noticeable amount of Python 2 discussion here, even though we don't support Python 2 anymore in the codebase.

Can you explain why you added so much content about Python 2 compatibility?

2019-12-22 19:33 UTC, datapythonista commented
Thanks @souvik3333, I think moving things from the wiki here is a good idea, but looks like the page you moved is not relevant anymore, now that we don't support Python 2.

Closing, but we should remove the page from the wiki (I don't have permissions, or may be it's just that it's not possible in the mobile version).

2019-12-22 20:26 UTC, souvik3333 commented
> Can you explain why you added so much content about Python 2 compatibility?

I was working on issue #30232 and this content was mentioned there. @gfyoung @datapythonista Can you verify about the other content in the list?

2019-12-23 13:32 UTC, alimcmaster1 commented
https://github.com/pandas-dev/pandas/issues/30410 @souvik3333 there is some discussion going on about it here

2019-12-23 13:39 UTC, souvik3333 commented
> #30410 @souvik3333 there is some discussion going on about it here

Yes, I just found it. Thank you.

2019-12-28 14:24 UTC, simonjayhawkins commented
> Thanks @souvik3333, I think moving things from the wiki here is a good idea, but looks like the page you moved is not relevant anymore, now that we don't support Python 2.

I think we want the `Imports (aim for absolute)` section and maybe more.

2019-12-29 17:10 UTC, simonjayhawkins commented on doc/source/development/contributing.rst
> +Python 2/3 Compatibility
only py3.6+ is supported, so I think we can remove this too

2019-12-29 18:21 UTC, simonjayhawkins commented
@souvik3333 I think the additions here should be added to doc/source/development/contributing_code_guide.rst once #30129 is merged

2020-01-03 13:11 UTC, datapythonista commented
Closing this, since all the Python 2/3 documentation is not useful anymore. @souvik3333 as said, once #30129 is merged, you can add a section about the imports there. Thanks!

2020-01-03 13:11 UTC, closed without merging