BUG: Disable parallel cythonize on Windows (GH 30214)
pandas-dev/pandas pull request #30585
Opened 2019-12-31 17:09 UTC by Dr-Irv

- [x ] closes #30214
- [ ] tests added / passed
  - N/A
- [ ] passes `black pandas`
  - Didn't run - changes too many files
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Added test in `setup.py` to check if nthreads is positive and on Windows.

2019-12-31 20:09 UTC, jbrockmendel commented on doc/source/whatsnew/v1.0.0.rst
> -- Bug in :class:`Index` where a non-hashable name could be set without raising ``TypeError`` (:issue:29069`)
good catch, thanks

2019-12-31 20:10 UTC, jbrockmendel commented on setup.py
> +        print("Parallel build for cythonize ignored on Windows")
comment with GH reference leading back here or to the relevant discussion?

2019-12-31 20:46 UTC, WillAyd requested changes
Can you also enable this for Windows CI? Would be curious to see how much time it saves there

2019-12-31 20:46 UTC, WillAyd commented on doc/source/whatsnew/v1.0.0.rst
> +- Disabled parallel cython builds on Windows (:issue:`30214`)
This was never explicitly added before 1.0 so shouldn’t need a whatsnew

2019-12-31 21:04 UTC, Dr-Irv commented
> Can you also enable this for Windows CI? Would be curious to see how much time it saves there

@WillAyd If I "enable" it for Windows CI, then all compiles would run sequentially.  So that wouldn't save time (assuming the parallel stuff is working now). What am I missing here?

2019-12-31 21:13 UTC, WillAyd commented
I meant should add the “-j N” flag to the build command for Windows in the CI folder. We currently don’t pass anything so Cythonization and compilation are sequential

Sent from my iPhone

> On Dec 31, 2019, at 4:04 PM, Irv Lustig <notifications@github.com> wrote:
> 
> ﻿
> Can you also enable this for Windows CI? Would be curious to see how much time it saves there
> 
> @WillAyd If I "enable" it for Windows CI, then all compiles would run sequentially. So that wouldn't save time (assuming the parallel stuff is working now). What am I missing here?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2019-12-31 21:23 UTC, Dr-Irv commented
> I meant should add the “-j N” flag to the build command for Windows in the CI folder. We currently don’t pass anything so Cythonization and compilation are sequential

OK, I put that in the last commit

2019-12-31 21:44 UTC, topper-123 approved these changes
I've tried this solution out, and compilation works fine for me.

Would be interesting to try parallizing on Windows when https://github.com/cython/cython/issues/3262 is solved in a new Cython release.

2020-01-01 01:34 UTC, merged

2020-01-01 01:34 UTC, jreback commented
thanks @Dr-Irv