DEPR/REGR: Fix pandas.util.testing deprecation
pandas-dev/pandas pull request #30745
Opened 2020-01-06 16:50 UTC by TomAugspurger

Closes https://github.com/pandas-dev/pandas/issues/30735

This avoids using _DeprecatedModule, which doesn't work for
direct imports from a module. Sorry for the importlib magic, but
I think this is the correct way to do things.

cc @jorisvandenbossche.

2020-01-06 17:35 UTC, jreback requested changes

2020-01-06 17:35 UTC, jreback commented on pandas/util/__init__.py
> +import importlib as _importlib
umm why don't you actually just leave pandas.util.testing as a module itself? (and just re-import what you need). This is how we did all of the original deprecations.

2020-01-06 19:20 UTC, jorisvandenbossche commented
I don't have a strong opinion on this approach vs just leaving the pandas.util.testing module and importing what is needed there (and add a deprecation warning in the module, which will only trigger a warning once?). But if we keep the approach in this PR, should this be factored out in a utility and just replace the current DeprecatedModule utility?

2020-01-06 19:22 UTC, TomAugspurger commented
Sorry, I think @jreback is right. We don't need the import hook stuff. Just

```python
# pandas/util/testing.py
warnings.warn("pandas.util.testing is deprecated. Use pandas.testing instead")
from pandas._testing import *
```

should accomplish the same thing with less hassle. Will update shortly (I do think I need to restructure a few things to avoid a circular import from core)

2020-01-06 19:27 UTC, TomAugspurger commented
Sorry about that. Just using standard stuff now.

2020-01-06 20:07 UTC, jorisvandenbossche approved these changes

2020-01-06 21:28 UTC, jbrockmendel commented
LGTM

2020-01-07 00:01 UTC, jreback approved these changes

2020-01-07 00:01 UTC, jreback commented on pandas/tests/api/test_api.py
> +        sys.modules.pop("pandas.util.testing", None)
in theory this should be in a context manager (but nbd)

2020-01-07 00:01 UTC, merged

2020-01-07 00:01 UTC, jreback commented
thanks @TomAugspurger