:pencil: set klass correctly for series and dataframe set_axis
pandas-dev/pandas pull request #30885
Opened 2020-01-10 14:28 UTC by MarcoGorelli

- [ ] closes #30881 
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-01-10 15:50 UTC, simonjayhawkins commented
Thanks @MarcoGorelli for the PR. will look soon.

2020-01-11 11:14 UTC, simonjayhawkins commented
sorry @MarcoGorelli struggling to get doc build locally and now AFK for the best part of the day.

2020-01-11 11:16 UTC, MarcoGorelli commented
@simonjayhawkins no hurry :)

2020-01-12 15:10 UTC, simonjayhawkins commented
@MarcoGorelli should probably also change `See Also` to have %(klass)s substitution and use substitution for `An object of same type as caller` otherwise lgtm.

2020-01-13 11:18 UTC, MarcoGorelli commented
@simonjayhawkins sure, done - thanks for your review!

2020-01-13 12:03 UTC, simonjayhawkins approved these changes
Thanks @MarcoGorelli for the updates.

I missed it the first time round, but now that the docstrings are independent, I think could also update axis to `axis : %(axes_single_arg)s, default 0` and re-work the docstrings a bit (separate PR OK)

2020-01-13 14:57 UTC, simonjayhawkins approved these changes

2020-01-16 19:59 UTC, WillAyd requested changes
Any chance you can post a screenshot of the built docs?

2020-01-16 19:59 UTC, WillAyd commented on pandas/core/generic.py
> +        axis : %(axes_single_arg)s, default 0
Is this actually being substituted?

2020-01-17 10:04 UTC, MarcoGorelli commented
Sure, here's the output of
`python make.py clean`
`python make.py --single pandas.DataFrame.set_axis`
`python make.py --single pandas.Series.set_axis`


![image](https://user-images.githubusercontent.com/33491632/72601530-81026f80-390d-11ea-9970-af5c62306bd7.png)
![image](https://user-images.githubusercontent.com/33491632/72603370-cb392000-3910-11ea-8f5a-c14f3bcd246a.png)

2020-01-17 10:34 UTC, MarcoGorelli commented on pandas/core/generic.py
> +        axis : %(axes_single_arg)s, default 0
Looks like it, see below

2020-01-18 19:10 UTC, jreback approved these changes
lgtm. @WillAyd

2020-01-20 18:03 UTC, WillAyd approved these changes

2020-01-20 18:04 UTC, merged

2020-01-20 18:04 UTC, WillAyd commented
Thanks @MarcoGorelli