Fix DataFrame.info() range summary for DatetimeIndex
pandas-dev/pandas pull request #31069
Opened 2020-01-16 08:20 UTC by Ircama

**Fix `DataFrame.info()` range summary for DatetimeIndex**

This PR fixes range display errors that might occur when [DataFrame.info](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html) describes a [DatetimeIndex](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.html) of big dataframes: depending on the dataframe structure, related *"min date" to "max date"* values can be wrong.

Example of output produced by `DataFrame.info()`:

```python
import pandas as pd
idx = pd.date_range('2020-01-15 01:03:05',
                    periods=1000004, freq='ms')
df = pd.DataFrame({'count': range(len(idx))}, index=idx)
df
df.info()
```

`df` output:
```
                           count
2020-01-15 01:03:05.000        0
2020-01-15 01:03:05.001        1
2020-01-15 01:03:05.002        2
2020-01-15 01:03:05.003        3
2020-01-15 01:03:05.004        4
...                          ...
2020-01-15 01:19:44.999   999999
2020-01-15 01:19:45.000  1000000
2020-01-15 01:19:45.001  1000001
2020-01-15 01:19:45.002  1000002
2020-01-15 01:19:45.003  1000003
```

`df.info()` output:
```
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1000004 entries, 2020-01-15 01:03:05 to 2020-01-15 01:19:45.003000
Freq: L
Data columns (total 1 columns):
count    1000004 non-null int64
dtypes: int64(1)
memory usage: 15.3 MB
```

This PR fixes possible errors within the description: `"DatetimeIndex: ... entries, `*date_a*` to `*date_b* output, where *date_a* and *date_b* should respectively show minimum and maximum date range values.

2020-01-16 09:32 UTC, MarcoGorelli commented
Thanks for your PR, and welcome :)

I'm not sure I see the issue in your example - `df.info()` shows 
```
2020-01-15 01:03:05 to 2020-01-15 01:19:45.003000
```
but isn't that what we were expecting to see?

Could you please raise an issue first, in which you show an example of where the output is wrong, along with your expected output?

2020-01-16 18:41 UTC, WillAyd commented
Please add test(s) for the issue you are trying to fix - we typically ask for these as the first part of any PR

2020-01-16 18:42 UTC, WillAyd requested changes
note above comment on tests

2020-01-18 02:33 UTC, Ircama commented
Ok, thanks. I'll first create an issue and relate it to this PR.

2020-01-18 10:04 UTC, MarcoGorelli commented
Thanks for opening the issue.

However, before this PR is accepted, you need to write a test / make sure you don't break existing ones - see [contributing to the code base](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#contributing-to-the-code-base)

2020-02-03 13:16 UTC, MarcoGorelli commented
@WillAyd just checking - is this something pandas would like to support?

If so, @Ircama , is this something you're still working on?

2020-02-04 10:36 UTC, MarcoGorelli commented
On a second thought, I think I might prefer the current behaviour. Otherwise, if I did `df.info()` and saw the min and max values instead of the first and last ones, I might get the (possibly false) impression that my index was already sorted

2020-02-05 08:02 UTC, Ircama commented
> On a second thought, I think I might prefer the current behaviour.

Yes, I did some further analysis and at the end I agree.

Even if the wording used with `df.info()` on *DatetimeIndex* entries might lead to believe that the two shown elements are the index range, actually these are the first and the last element of the DataFrame index.

Sorting the index is optional and the shown values could help the developer check whether sorting has been applied to the index.

I would then consequently close https://github.com/pandas-dev/pandas/pull/31069 and https://github.com/pandas-dev/pandas/issues/31116.

Thanks for the support so far.

2020-02-05 08:02 UTC, closed without merging