CLN: __all__ for core/index.py
pandas-dev/pandas pull request #31082
Opened 2020-01-16 19:03 UTC by MomIsBestFriend

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-01-16 19:33 UTC, WillAyd approved these changes
lgtm

2020-01-16 19:34 UTC, WillAyd requested changes

2020-01-16 19:34 UTC, WillAyd commented on pandas/core/index.py
> -from pandas.core.indexes.multi import _sparsify  # noqa:F401
Is this actually imported from anywhere else? If not I think could actually be removed

2020-01-16 19:36 UTC, datapythonista commented on pandas/core/index.py
> +    "_sparsify",
I don't think the private methods `_new_Index` and `_sparsify` should be in `__all__`. I guess they are being used by other modules, which shouldn't be the case.

I'm ok to merge it like this, if that's the case, but if you don't mind researching a bit, seeing where those are used, and adding at least a comment about this, that would be great.

I'd probably move these imports at the end, so they are separated from the rest.

2020-01-16 19:50 UTC, MomIsBestFriend commented
this file is not used __anywhere__ in the code base (AT ALL).
It was deprecated in #30193 (About a month ago).

Is it OK to removed it completely?

I don't know if a month is a lot of time or not when it comes to API changes, if it's not a lot of time, then what is a good time span to give users a warn about API change before actually changing it?

2020-01-16 20:06 UTC, datapythonista commented
The CI is red, I guess the objects you removed were being imported somewhere.

2020-01-16 21:51 UTC, MomIsBestFriend commented
Looks like it failed before it began the tests, closing and reopening

2020-01-16 23:34 UTC, datapythonista commented
Sorry, assumed there were genuine test fails. The failure is a correct error now, you need to either remove `_new_Index` if it's not used, or add it to the `__all__` (with a comment if possible).

2020-01-17 08:33 UTC, jorisvandenbossche commented
This is a deprecated module that is being changed, that should not be used in pandas. So what is the rationale for this change?

2020-01-17 08:38 UTC, MomIsBestFriend commented
> This is a deprecated module that is being changed, that should not be used in pandas. So what is the rationale for this change?

@jorisvandenbossche I just saw the ```# noqa:F401``` comments, and decided to cleaned it up, regardless if the module is deprecated or not.

2020-01-17 08:44 UTC, jorisvandenbossche commented
OK, I wouldn't put effort in a deprecated / unused file, but too late I guess :-)

Is there a general issue about such changes?

2020-01-17 08:48 UTC, MomIsBestFriend commented
> but too late I guess :-)

That's exactly what I said, when I saw the deprecation message, only after I have made the changes :)

> Is there a general issue about such changes?

There isn't a "master issue" for it, it's something I started to do here and there since https://github.com/pandas-dev/pandas/pull/30828#discussion_r364500688 was pointed out.

2020-01-17 17:40 UTC, WillAyd commented
Yea I think since deprecated maybe not even worth touching this module so just closing this one out. But thanks as always @MomIsBestFriend

2020-01-17 17:40 UTC, closed without merging

2020-01-17 17:58 UTC, MomIsBestFriend commented
Understandable :)