ENH: partial string indexing on non-monotonic PeriodIndex
pandas-dev/pandas pull request #31096
Opened 2020-01-17 02:40 UTC by jbrockmendel

Looks like the DatetimeIndex analogue of this was done in #2437 (https://github.com/pandas-dev/pandas/commit/3a173f19b308d2fb7d8e96dfc57f2e5ecd046138)

This does _not_ yet support two-sides slicing e.g. `ser["2015":"2016"]`, but im hoping to get that handled before long.

Partial overlap with #31058, nothing should actually conflict.

2020-01-17 17:50 UTC, WillAyd commented
Is this a bug fix or a new feature? Can you add a whatsnew?

2020-01-17 18:28 UTC, jbrockmendel commented
> Is this a bug fix or a new feature? Can you add a whatsnew?

I think it counts as a feature, but there are a lot of inconsistencies in the surrounding code, so I wouldn't argue the point.  Just added whatsnew.

2020-01-18 15:54 UTC, jreback requested changes

2020-01-18 15:54 UTC, jreback commented on doc/source/whatsnew/v1.1.0.rst
> +:class:`PeriodIndex` now supports partial string slicing for non-monotonic indexes, mirroring :class:`DatetimeIndex` behavior (:issue:`31096`)
can you update the docs: https://pandas.io/docs/user_guide/timeseries.html#partial-string-indexing

2020-01-18 15:54 UTC, jreback commented on doc/source/whatsnew/v1.1.0.rst
> +   pi = dti.to_period("D")
can you show ser, maybe break this into 2 to make it more readable

2020-01-20 17:21 UTC, jreback commented
can you rebase

2020-01-20 19:50 UTC, jreback commented on doc/source/user_guide/timeseries.rst
> +As of version 1.1.0, this works with non-monotonic ``PeriodIndex`` indexes.
ok, should be versionadded directive. (ad put at the beginning of the slicing with period strings section); thought we didn't have *any* docs on this (but seems we do)

2020-01-20 19:51 UTC, jreback commented on doc/source/whatsnew/v1.1.0.rst
> +   ser["2014"]
can you make a separate ipythonblock for these last 2

2020-01-20 19:51 UTC, jreback approved these changes
doc comments, otherwise lgtm.

2020-01-20 23:40 UTC, jreback commented
one more rebase

2020-01-21 16:24 UTC, jbrockmendel commented
rebased+green

2020-01-21 16:27 UTC, merged

2020-01-21 16:27 UTC, WillAyd commented
Thanks @jbrockmendel