DOC: Restore ExtensionIndex.dropna.__doc__
pandas-dev/pandas pull request #31095
Opened 2020-01-17 01:46 UTC by jbrockmendel

Per request from @jorisvandenbossche on #30717.

2020-01-17 08:08 UTC, jorisvandenbossche requested changes
The same is true for `take` (from https://github.com/pandas-dev/pandas/pull/30703/files#diff-fcbd0a5e2913f5949094b4eae4ef9edaL726), `astype` (from https://github.com/pandas-dev/pandas/commit/ac9901b8a27ff23f40e3a8e89f4414e7b605a0d0#diff-26a6d2ca7adfca586aabbb1c9dd8bf36L545) and maybe others

2020-01-18 15:54 UTC, jreback approved these changes
lgtm. @jorisvandenbossche

2020-01-20 13:34 UTC, jorisvandenbossche approved these changes

2020-01-20 13:35 UTC, merged

2020-01-20 13:35 UTC, jorisvandenbossche commented
Thanks @jbrockmendel !