REF: combine all alignment into _align_method_FRAME
pandas-dev/pandas pull request #31288
Opened 2020-01-24 17:22 UTC by jbrockmendel

This puts us within striking distance of de-duplicating _flex_comp_method_FRAME and _comp_method_FRAME, with _arith_method_FRAME not far behind

2020-01-24 17:40 UTC, WillAyd requested changes
looks good generally minor things

2020-01-24 17:40 UTC, WillAyd commented on pandas/core/ops/__init__.py
> +        None indices not to check for alignment.
```suggestion
        None indicates not to check for alignment.
```

I *think* this is a typo

2020-01-24 17:40 UTC, WillAyd commented on pandas/core/ops/__init__.py
> +def _align_method_FRAME(left, right, axis, flex=False, level=None):
```suggestion
def _align_method_FRAME(left, right, axis, flex: Optional[bool] = False, level: Optional[Label] = None):
```

I think should add types for the new arguments here

2020-01-24 17:41 UTC, pep8speaks commented
Hello @jbrockmendel! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`pandas/core/ops/__init__.py`](https://github.com/pandas-dev/pandas/blob/517b073a332e0c2e0af891e4c9b60894866319d0/pandas/core/ops/__init__.py):

> [Line 612:89](https://github.com/pandas-dev/pandas/blob/517b073a332e0c2e0af891e4c9b60894866319d0/pandas/core/ops/__init__.py#L612): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 88 characters)

2020-01-24 17:42 UTC, WillAyd requested changes

2020-01-24 17:42 UTC, WillAyd commented on pandas/core/ops/__init__.py
> +def _align_method_FRAME(left, right, axis, flex: Optional[bool] = False, level: Optional[Label] = None):
```suggestion
def _align_method_FRAME(left, right, axis, flex: Optional[bool] = False, level: Optional[Level] = None):
```

Sorry typo on previous; we actually have Level defined in pandas._typing already (probably need to import)

2020-01-31 03:36 UTC, merged

2020-01-31 03:36 UTC, jreback commented
thanks