BUG: groupby().agg fails on categorical column when func is first
pandas-dev/pandas pull request #31470
Opened 2020-01-30 19:20 UTC by charlesdong1991

- [ ] closes #31450 
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-01-30 19:20 UTC, pep8speaks commented
Hello @charlesdong1991! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/groupby/groupby.py`](https://github.com/pandas-dev/pandas/blob/93ebadb22de0bc66a94a500256b40ab781a69ff5/pandas/core/groupby/groupby.py):

> [Line 816:76](https://github.com/pandas-dev/pandas/blob/93ebadb22de0bc66a94a500256b40ab781a69ff5/pandas/core/groupby/groupby.py#L816): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

2020-01-30 19:29 UTC, jbrockmendel commented
is this limited to "first"?  i think the conclusion from previous thread is that we need to be more systematic about when we call _try_cast

2020-01-30 19:32 UTC, charlesdong1991 commented
@jbrockmendel yeah, very right, i was about to change something in `_try_cast`, but haven't seen the follow-up discussions, and due to the added change of `isinstance(result[0], dtype.type)` in `_try_cast`, the case of `first` won't be casted back which it should be. 
so I just added as an experiment to see if this could work, and prepare a more generic solution if so.

2020-01-31 12:07 UTC, WillAyd requested changes
Hmm not a fan of the approach here - I think should try and avoid special-casing / adding more groupings to base. 

This works for DataFrame selection but not Series right? If so I think should dive deeper into why the former can naturally support but the latter can't to find resolution

2020-01-31 12:10 UTC, TomAugspurger commented
Haven't had a chance to look closely yet, but I think my preferred approach is for the calling function to decide what the output dtype should be based on the input dtype. Not sure how best to put that to code either.

2020-01-31 13:37 UTC, charlesdong1991 commented
@WillAyd @TomAugspurger I agree, and i am not a big fan of this current approach, this is the reason i have [WIP] in the title. I tried to fix when to call this `_try_cast` depending on the situation and type, but not working, and causes a lot of errors locally, so i am still trying to find a better/more robust fix. 

Sorry about this noise in PRs, and i wish i could update this soon!

2020-01-31 14:13 UTC, TomAugspurger commented
Thanks for working on this. It's good that we're exploring possible
solutions. We should take a bit of time to try and get this right.

On Fri, Jan 31, 2020 at 7:37 AM Kaiqi Dong <notifications@github.com> wrote:

> @WillAyd <https://github.com/WillAyd> @TomAugspurger
> <https://github.com/TomAugspurger> I agree, and i am not a big fan of
> this current approach, this is the reason i have [WIP] in the title. I
> tried to fix when to call this _try_cast depending on the situation and
> type, but not working, and causes a lot of errors locally, so i am still
> trying to find a better/more robust fix.
>
> Sorry about this noise in PRs, and i wish i could update this soon!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/31470?email_source=notifications&email_token=AAKAOIQL5KBDBER4RG25CMDRAQSSLA5CNFSM4KN3O4JKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKOVKXI#issuecomment-580736349>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKAOISV7CVPVR2LFT33PPTRAQSSLANCNFSM4KN3O4JA>
> .
>

2020-02-01 15:53 UTC, charlesdong1991 commented
I still have some confusion on what should be the correct behaviour, based on the https://github.com/pandas-dev/pandas/pull/31359#issuecomment-579799671
it seems for `IntegerArray`, `mean` should return a float type result because `IntegerArray._reduce("mean")` returns float. However, in the case below, doing `agg.mean` on a normal array with integer returns `int64` output instead of `float`? is it correct? if so, could this be considered as inconsistency between extension array and normal array and then cause confusion to users? @TomAugspurger @jreback 

```
def test_groupby_extension_agg(self, as_index, data_for_grouping):
        df = pd.DataFrame({"A": [1, 1, 2, 2, 3, 3, 1, 4], "B": data_for_grouping})
        result = df.groupby("B", as_index=as_index).A.mean()
        _, index = pd.factorize(data_for_grouping, sort=True)
    
        index = pd.Index(index, name="B")
        expected = pd.Series([3, 1, 4], index=index, name="A")
        if as_index:
>           self.assert_series_equal(result, expected)
E           AssertionError: Attributes of Series are different
E           
E           Attribute "dtype" are different
E           [left]:  float64
E           [right]: int64
```

2020-02-01 16:47 UTC, TomAugspurger commented
IMO the result dtype should only depend on the dtype of the inputs, not the values. IIUC the result can only be int dtype in this case because the mean of the values happens to be equal to an integer? If so, I’d say that’s a bug. The result dtype should always be a float.

2020-02-01 17:25 UTC, charlesdong1991 commented
@TomAugspurger  thanks for your quick reply. Indeed, in these cases the output has int dtype because it happens to be equal to integer.

2020-02-01 17:31 UTC, jreback commented
the int return in mean is a bug it should be float
likely just happened to coerce it before

2020-02-03 23:00 UTC, charlesdong1991 reviewed
I think this should pass the CI now, before heading to bed, I would like to describe it a bit, feel free to take a look and your reviews are very welcomed:

1. now the `.agg("mean")` will return `float64`, the same for `var`, `median` etc, it is aligned with numpy behaviour also. And for the rest (defined in the base, they should NOT be casted) and keep the type
2. and `python_agg` will always return the same type as the original object, and it is not changing the current behaviour, since right now those results are coerced. And I think this is correct, because we might want to return different types for `python_agg` and `cython_agg` on cython funcs, and this design is especially good for self-defined function used in aggregate. Therefore, you could see that in test, `.agg("mean")` will have `float64` now while `.agg(lambda x: np.mean(x))` will still return `int64` as they are on master.

I believe this will have a lot of disputes, but all opinions are welcome, and having a consesus on the correct behaviour is important, afterwards I will focus on better coding later. Thanks all, I will do a follow-up code changes tomorrow, and hopefully get this done before 1.0.1 releases. @TomAugspurger @jreback @jbrockmendel @jorisvandenbossche @WillAyd

2020-02-04 21:59 UTC, TomAugspurger commented
Thanks for working on this @charlesdong1991. I hope to write up more later, but in general, I like the general idea of the calling function indicating the result dtype is a good idea.

For our immediate needs, I think we can use a more targeted fix to restore the 0.25.x behavior. I'll propose that as a separate PR.

2020-02-04 22:19 UTC, TomAugspurger commented
https://github.com/pandas-dev/pandas/pull/31668 for the alternative.

2020-02-05 00:25 UTC, jreback requested changes
thanks for working on this @charlesdong1991 but this is not very clean; i know this is a patch release. but this is making things worse.

2020-02-05 00:25 UTC, jreback commented on pandas/core/groupby/groupby.py
> +                from pandas import notna
you can import at the top

2020-02-05 00:32 UTC, jreback commented
merged in https://github.com/pandas-dev/pandas/pull/31668, which is a backportable patch. thanks @charlesdong1991

2020-02-05 00:32 UTC, closed without merging

2020-02-05 07:49 UTC, charlesdong1991 commented
> #31668 for the narrowly scoped alternative to just fix the regression, but not the general issue.

this is much cleaner!! awesome!! @TomAugspurger 👍