BUG: objToJson.c - remove generic pointer
pandas-dev/pandas pull request #31482
Opened 2020-01-31 08:08 UTC by alimcmaster1

- [x] xref #31463

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=27217&view=logs&j=3a03f79d-0b41-5610-1aa4-b4a014d0bc70&t=fe74a338-551b-5fbb-553d-25f48b1836e8&l=687

Seems like this warning is somehow causing an error in the users builds of pandas

2020-01-31 08:26 UTC, alimcmaster1 commented
Seems to not work on mac:

![image](https://user-images.githubusercontent.com/16733618/73523731-677c2000-4403-11ea-9c43-e51267cb36e1.png)

2020-01-31 10:44 UTC, WillAyd commented
Not at a computer to check but just might want to return NULL at the end of the function instead of changing it from a void pointer to void. I think original error is that the import_array() macro may only return that in some versions, so can force to work for all by returning NULL (though also a little strange)

2020-02-01 00:24 UTC, alimcmaster1 commented
Thanks Will - will update

2020-02-01 15:03 UTC, jreback requested changes
@alimcmaster1 can you add a note in the whatsnew (1.0.1), ping on green.

2020-02-02 16:44 UTC, jreback approved these changes

2020-02-02 16:44 UTC, jreback commented
thanks @alimcmaster1 ping on green (ex the 37 build which i just have to backport to CI).

2020-02-02 17:07 UTC, alimcmaster1 commented
@jreback - All green ex 37. I can merge https://github.com/pandas-dev/pandas/pull/31573 into this branch

2020-02-02 17:09 UTC, merged

2020-02-02 17:09 UTC, jreback commented
thanks @alimcmaster1