BUG: fix reindexing with a tz-aware index and method='nearest'
pandas-dev/pandas pull request #31511
Opened 2020-01-31 18:23 UTC by kanderso-nrel

- [x] closes #26683
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

First pandas PR, happy to make changes as needed.

2020-01-31 19:08 UTC, MarcoGorelli commented on pandas/tests/frame/indexing/test_indexing.py
> +    def test_reindex_nearest_tz(self):
Thanks!

Can you add the issue number number under the test? So
```
def test_reindex_nearest_tz(self):
    # GH26683
```

(many old tests didn't do this, but it seems to be preferred for new ones)

2020-01-31 19:10 UTC, MarcoGorelli commented on pandas/tests/frame/indexing/test_indexing.py
> +        idx = pd.date_range("2019-01-01", periods=5, tz="US/Eastern")
There are some fixtures defined in `conftest.py`, I think here you might want to add `tz_aware_fixture`:
```
def test_reindex_nearest_tz(self, tz_aware_fixture):
    tz = tz_aware_fixture
    idx = pd.date_range("2019-01-01", periods=5, tz=tz)
```

2020-01-31 19:56 UTC, kanderso-nrel commented
Thanks @MarcoGorelli for the guidance!  Is there anything else I can improve?

2020-01-31 20:27 UTC, kanderso-nrel commented
Docs build fail seems unrelated, transient network error?  https://github.com/pandas-dev/pandas/pull/31511/checks?check_run_id=419939179#step:6:37

2020-01-31 20:34 UTC, charlesdong1991 commented
@kanderso-nrel likely a network issue, you could add a whatsnew note in `1.1` and try it again

2020-02-02 22:39 UTC, jreback requested changes
looks good, some comments, pls merge master. ping on green.

2020-02-02 22:39 UTC, jreback commented on doc/source/whatsnew/v1.1.0.rst
> +- Bug in :meth:`DataFrame.reindex` and :meth:`Series.reindex` when reindexing with a tz-aware index and method='nearest' (:issue:`26683`)
can you move to Datetimelike

2020-02-02 22:39 UTC, jreback commented on pandas/core/indexes/base.py
> +        left_distances = abs(self[left_indexer] - target)
can we change to use np.abs

2020-02-03 03:39 UTC, kanderso-nrel commented
@jreback all green after #31594

2020-02-03 03:47 UTC, jreback approved these changes

2020-02-03 03:48 UTC, merged

2020-02-03 03:48 UTC, jreback commented
thanks!