REGR: Categorical with np.str_ categories
pandas-dev/pandas pull request #31528
Opened 2020-02-01 03:40 UTC by jbrockmendel

- [x] closes #31499
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2020-02-01 11:52 UTC, TomAugspurger approved these changes
LGTM. Is this something we want to support long-term?

2020-02-01 11:52 UTC, TomAugspurger commented on doc/source/whatsnew/v1.0.1.rst
> +- Bug in :class:`Categorical` construction with ``numpy.str_`` categories (:issue:`31499`)
```suggestion
- Fixed regression in :class:`Categorical` construction with ``numpy.str_`` categories (:issue:`31499`)
```

2020-02-01 15:05 UTC, jreback approved these changes

2020-02-01 15:06 UTC, jreback requested changes

2020-02-01 15:06 UTC, jreback commented on pandas/tests/arrays/categorical/test_constructors.py
> +        cat = pd.Categorical(["1", "0", "1"], [np.str_("0"), np.str_("1")])
actually, I think we should be santizing these inputs on Index construction; we already *do* this for Series IIRC (deep in block manager i think).  Can you see if that's better (as its a more maintainable long term soln). Not averse to your change, but that's *after* we already saved the inputs.

2020-02-01 22:21 UTC, jreback requested changes
i would prefer to actually fix this rather than work around np.str_ which is not used anywhere else.

2020-02-03 12:37 UTC, TomAugspurger commented
What's the proposed fix?

IMO, we should deprecate the old behavior first if it isn't too costly. This PR doesn't seem too bad, though I don't really understand all its implications.

2020-02-03 12:42 UTC, jorisvandenbossche commented
>  I think we should be santizing these inputs on Index construction; we already do this for Series IIRC 

I thought as well, but that doesn't seem to be the case:

```
In [1]: s = pd.Series([np.str_("0"), np.str_("1")])  

In [2]: s[0]        
Out[2]: '0'

In [3]: type(s[0])  
Out[3]: numpy.str_
```

I would keep a possible sanitation for a separate issue / discussion. This PRs seems an easy fix to address the regression.

2020-02-03 13:12 UTC, jreback commented
this is just an unsupportable bandaid. this is handling a leak of np.str_ into the internals, which is really bad. I don't think its worth trying to fix this for 1.0.1 like this, rather address a systematic real fix.

2020-02-03 13:46 UTC, jorisvandenbossche commented
> this is just an unsupportable bandaid. this is handling a leak of np.str_ into the internals, which is really bad. 

It is what we did before for years. So I don't think it is that unsupportable. 

Since we can still store numpy strings in a Series, and since we supported converting those to a Categorical before, I think this is a good fix. 

For 1.1, we can discuss further if we want to keep supporting this, or want to deprecate it, or want to sanitize on input (to avoid needing to support it).

2020-02-03 13:57 UTC, TomAugspurger commented
> For 1.1, we can discuss further if we want to keep supporting this, or want to deprecate it, or want to sanitize on input (to avoid needing to support it).

Agreed.

2020-02-03 15:12 UTC, jreback commented
these last minute patches are just causing more and more issues. do what you will this.

2020-02-03 18:41 UTC, TomAugspurger commented
@jbrockmendel are you aware of any maintenance burdens or ambiguities this might cause?

At least on 0.25.3, we seem to treat `str` and `np.str_` equivalently in methods like `get_loc` and `unique`

2020-02-03 20:15 UTC, jbrockmendel commented
> are you aware of any maintenance burdens or ambiguities this might cause?

Not especially.  If we want to root np.str_ out entirely, that would be a pretty big endeavor.

2020-02-04 07:54 UTC, jorisvandenbossche approved these changes

2020-02-04 16:23 UTC, TomAugspurger commented
OK. Naively, I agree that rooting out `np.str_` objects in our constructors sounds difficult. At the least, it would require a scan over the values and a couple isinstance checks on each value, which I'd like to avoid if it's not causing problems elsewhere. I'm sure we'll get reports if it is.

2020-02-04 16:23 UTC, merged

2020-02-04 16:24 UTC, TomAugspurger commented
Thanks @jbrockmendel.