[MRG] f-string updates for issue #29547
pandas-dev/pandas pull request #31556
Opened 2020-02-02 01:22 UTC by abbiepopa

Addresses, in part, https://github.com/pandas-dev/pandas/issues/29547 

…ape/pivot, reshape/reshape

- [ x] address #29547 
- [n/a ] tests added / passed
- [x ] passes `black pandas`
- [ x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [n/a ] whatsnew entry

2020-02-02 01:22 UTC, pep8speaks commented
Hello @abbiepopa! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`pandas/core/reshape/merge.py`](https://github.com/pandas-dev/pandas/blob/b934d2a8eef71269dca77d6517bf7a3c0cbfea4e/pandas/core/reshape/merge.py):

> [Line 614:89](https://github.com/pandas-dev/pandas/blob/b934d2a8eef71269dca77d6517bf7a3c0cbfea4e/pandas/core/reshape/merge.py#L614): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (107 > 88 characters)
> [Line 1188:89](https://github.com/pandas-dev/pandas/blob/b934d2a8eef71269dca77d6517bf7a3c0cbfea4e/pandas/core/reshape/merge.py#L1188): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 88 characters)
> [Line 1672:89](https://github.com/pandas-dev/pandas/blob/b934d2a8eef71269dca77d6517bf7a3c0cbfea4e/pandas/core/reshape/merge.py#L1672): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 88 characters)



* In the file [`pandas/core/reshape/reshape.py`](https://github.com/pandas-dev/pandas/blob/b934d2a8eef71269dca77d6517bf7a3c0cbfea4e/pandas/core/reshape/reshape.py):

> [Line 880:17](https://github.com/pandas-dev/pandas/blob/b934d2a8eef71269dca77d6517bf7a3c0cbfea4e/pandas/core/reshape/reshape.py#L880): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 881:17](https://github.com/pandas-dev/pandas/blob/b934d2a8eef71269dca77d6517bf7a3c0cbfea4e/pandas/core/reshape/reshape.py#L881): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 882:13](https://github.com/pandas-dev/pandas/blob/b934d2a8eef71269dca77d6517bf7a3c0cbfea4e/pandas/core/reshape/reshape.py#L882): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented

2020-02-02 01:40 UTC, WillAyd requested changes
Thanks for the PR! Mostly minor edits

2020-02-02 01:40 UTC, WillAyd commented on pandas/core/reshape/concat.py
> +                    f"only Series and DataFrame objs are valid"
```suggestion
                    "only Series and DataFrame objs are valid"
```

Don't need the f-prefix for lines with no replacement

2020-02-02 01:40 UTC, WillAyd commented on pandas/core/reshape/melt.py
> +        regex = r"^{re.escape(stub)}{re.escape(sep)}{suffix}$"
```suggestion
        regex = fr"^{re.escape(stub)}{re.escape(sep)}{suffix}$"
```

Missing the prefix here

2020-02-02 01:40 UTC, WillAyd commented on pandas/core/reshape/merge.py
> +                f"merging between different levels can give an unintended "
```suggestion
                "merging between different levels can give an unintended "
```

2020-02-02 01:40 UTC, WillAyd commented on pandas/core/reshape/merge.py
> +                    f"Cannot use `indicator=True` option when "
```suggestion
                    "Cannot use `indicator=True` option when "
```

2020-02-02 01:40 UTC, WillAyd commented on pandas/core/reshape/merge.py
> +                        f"No common columns to perform merge on. "
```suggestion
                        "No common columns to perform merge on. "
```

2020-02-02 01:40 UTC, WillAyd commented on pandas/core/reshape/merge.py
> +            msg = f"allow_exact_matches must be boolean, " \
We don't use explicit line continuation, so just use parentheses as needed

2020-02-02 01:40 UTC, WillAyd commented on pandas/core/reshape/reshape.py
> +                        f"length of the columns being encoded "
```suggestion
                        "length of the columns being encoded "
```

2020-02-02 05:41 UTC, abbiepopa commented
Thank you @WillAyd , I covered the changes you requested. I'm having some trouble figuring out why I'm failing the current tests. LMK if it's obvious to you, otherwise I will continue investigating.

2020-02-02 08:03 UTC, MarcoGorelli commented
Thanks, Abbie!

> I'm having some trouble figuring out why I'm failing the current tests

If you click on 'details' next to, say, "CI / Checks", you'll see an 'X' near 'linting'. If you expand it, you'll see
```
black --version
black, version 19.10b0
Checking black formatting
would reformat /home/runner/work/pandas/pandas/pandas/core/reshape/concat.py
would reformat /home/runner/work/pandas/pandas/pandas/core/reshape/melt.py
would reformat /home/runner/work/pandas/pandas/pandas/core/reshape/pivot.py
would reformat /home/runner/work/pandas/pandas/pandas/core/reshape/merge.py
Oh no! 💥 💔 💥
4 files would be reformatted, 923 files would be left unchanged.
```
So for a start, you need to run `black` again any file you've changed. For example,

```
black pandas/core/reshape/concat.py
```

The [contributing guide](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#contributing-to-the-code-base) has some more info about this.

2020-02-02 21:04 UTC, abbiepopa commented
Thank you, @MarcoGorelli ! Looks like the latest failure is a timeout. Is there a way to retrigger the test that timed out?

2020-02-02 21:38 UTC, abbiepopa commented
Yay! Thanks @WillAyd and @MarcoGorelli . LMK if you need additional changes etc.

2020-02-02 22:26 UTC, jreback reviewed
comment, pls ping on green.

2020-02-02 22:26 UTC, jreback commented on pandas/core/reshape/merge.py
> +        def _msg_sorted(side):
i would revert this section, it is more clear the existing way

2020-02-03 00:00 UTC, MomIsBestFriend commented on pandas/core/reshape/concat.py
> +                    raise ValueError(f"Key {key!s} not in level {level!s}")
I *think* you can get rid of the ```!s``` just have it as

```python
raise ValueError(f"Key {key} not in level {level}")
```

2020-02-03 00:02 UTC, MomIsBestFriend commented on pandas/core/reshape/merge.py
> +                f"allow_exact_matches must be boolean, "
Can you please remove the ```f``` here?

2020-02-03 00:03 UTC, MomIsBestFriend commented on pandas/tests/reshape/merge/test_merge.py
> +            f"No common columns to perform merge on. "
Can you remove the ```f```` here?

2020-02-03 04:43 UTC, abbiepopa commented
Thanks @jreback and @MomIsBestFriend ! I updated based on your reviews.

2020-02-04 00:40 UTC, WillAyd approved these changes

2020-02-04 00:41 UTC, merged

2020-02-04 00:41 UTC, WillAyd commented
Great thanks @abbiepopa