fixing the issue #31537
pandas-dev/pandas pull request #31624
Opened 2020-02-03 16:40 UTC by anant4299

DOC: Mention that boolean indexing is impossible for new nullable integer/boolean and string data types when they contain missing values

2020-02-04 18:45 UTC, jbrockmendel commented
looks like you've got trailing whitespace somewhere

2020-02-05 01:23 UTC, jreback requested changes

2020-02-05 01:23 UTC, jreback commented on doc/source/user_guide/indexing.rst
> +Note- pandas does not allow indexing with NA values. Attempting to do so
use a proper note construct (search for note and you'll see how).

add a ref to the correct location

2020-02-26 20:23 UTC, datapythonista commented
Closing as stale.

2020-02-26 20:23 UTC, closed without merging