REF: implement ExtensionIndex._concat_same_dtype, use for IntervalIndex
pandas-dev/pandas pull request #31635
Opened 2020-02-03 23:00 UTC by jbrockmendel

2020-02-03 23:00 UTC, pep8speaks commented
Hello @jbrockmendel! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`pandas/core/indexes/interval.py`](https://github.com/pandas-dev/pandas/blob/785b95706d4a47afc3b309a2594cb29103340d84/pandas/core/indexes/interval.py):

> [Line 186:68](https://github.com/pandas-dev/pandas/blob/785b95706d4a47afc3b309a2594cb29103340d84/pandas/core/indexes/interval.py#L186): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2020-02-04 07:43 UTC, jorisvandenbossche requested changes

2020-02-04 07:43 UTC, jorisvandenbossche commented on pandas/core/indexes/extension.py
> +        return self._data.dtype
This is already included in the base Index class (with docstring actually), so I think this is not needed here?

2020-02-04 07:43 UTC, jorisvandenbossche commented on pandas/core/indexes/extension.py
> +        return len(self._data)
Same comment as below for this one

2020-02-04 17:08 UTC, jorisvandenbossche reviewed
Can you maybe add a comment somewhere that those attributes (`__len__`, `dtype`) are already dispatched to `_data` in the base class?

2020-02-04 17:08 UTC, jorisvandenbossche commented on pandas/core/indexes/extension.py
> +        return len(self)
Actually, also size is already provided by the base class it seems?

2020-02-05 01:14 UTC, jreback commented on pandas/core/indexes/interval.py
> -        "__len__",
why don't we need the deleted ones?

2020-02-05 01:15 UTC, jreback commented on pandas/core/indexes/interval.py
> -        "__len__",
ahh i c, by reading comments.

2020-02-05 01:15 UTC, jreback approved these changes
lgtm.

2020-02-09 16:50 UTC, jreback commented on pandas/core/indexes/extension.py
> +    def _concat_same_dtype(self, to_concat, name):
if you can type at some point (doc-string inherited)?

2020-02-09 16:50 UTC, jreback commented
cc @jorisvandenbossche

2020-02-10 10:27 UTC, jorisvandenbossche approved these changes

2020-02-10 12:52 UTC, merged

2020-02-10 12:52 UTC, jreback commented
thanks @jbrockmendel