BUG: Too aggressive typing NDFrame.align
pandas-dev/pandas pull request #31788
Opened 2020-02-07 18:50 UTC by topper-123

- [x] closes #31785

The type checking was too aggressive. ``right`´ has type ``Any``, so the wrapping in ``_ensure_type`` should not be done.

2020-02-07 20:41 UTC, jbrockmendel commented
> The type checking was too aggressive

Is this in reference to annotations or to runtime type checking?

2020-02-07 20:50 UTC, topper-123 commented
> Is this in reference to annotations or to runtime type checking?

It's type checking, but can spill over to the run time because an ``assert`` is used to enforce the type, (that's what the call to ``._ensure_type`` does). Without ``._ensure_type`` the type of left would be ``Optional[DataFrame]`` and mypy would complain of operations on None.

2020-02-07 20:58 UTC, jorisvandenbossche commented
Do any of the other usage of `_ensure_types` introduced in the PR also need fixing?

2020-02-07 21:05 UTC, topper-123 commented
There should`t be more; here I assumed that left and right should be treated alike, which was a wrong idea.

2020-02-08 00:45 UTC, WillAyd approved these changes
lgtm

2020-02-08 00:45 UTC, WillAyd requested changes
too quick on approval...can you add test?

2020-02-08 10:10 UTC, topper-123 commented
Ok, I've added a test.

2020-02-09 17:12 UTC, merged

2020-02-09 17:13 UTC, jreback commented
thanks can we open an issue about how to improve / fix _ensure_type to make things like this work?