BUG: Pickle NA objects
pandas-dev/pandas pull request #32104
Opened 2020-02-19 13:46 UTC by TomAugspurger

According to
https://docs.python.org/3/library/pickle.html#object.__reduce__,

> If a string is returned, the string should be interpreted as the name
> of a global variable. It should be the object’s local name relative to
> its module; the pickle module searches the module namespace to determine
> the object’s module. This behaviour is typically useful for singletons.

Closes https://github.com/pandas-dev/pandas/issues/31847

2020-02-19 13:57 UTC, jreback commented on pandas/tests/scalar/test_na_scalar.py
> +def test_pickle_roundtrip():
also can u test with read/to_pickle

2020-02-19 22:26 UTC, jreback requested changes

2020-02-19 22:26 UTC, jreback commented on pandas/tests/scalar/test_na_scalar.py
> +    with tm.ensure_clean("data.pkl") as f:
there are test functions to do this in pandas._testing

2020-02-19 23:15 UTC, jorisvandenbossche approved these changes
Thanks!

2020-02-20 07:56 UTC, jorisvandenbossche commented on pandas/tests/scalar/test_na_scalar.py
> +    s = pd.Series(pd.array([1, 2, pd.NA]))
Can you also add a test with object array + one with string array? As the integer array doesn't actually store pd.NA, while those others do

2020-02-20 07:57 UTC, jorisvandenbossche commented on pandas/tests/scalar/test_na_scalar.py
> +    s = pd.Series(pd.array([1, 2, pd.NA]))
(to also cover https://github.com/pandas-dev/pandas/issues/32095, and https://github.com/pandas-dev/pandas/issues/31847#issuecomment-588500110)

2020-02-21 17:34 UTC, jbrockmendel commented
@TomAugspurger can you re-push?  looks like azure has stalled

2020-02-21 22:00 UTC, TomAugspurger commented
It'll be a week or so before I can look at this again.


On Fri, Feb 21, 2020 at 10:34 AM jbrockmendel <notifications@github.com>
wrote:

> @TomAugspurger <https://github.com/TomAugspurger> can you re-push? looks
> like azure has stalled
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/32104?email_source=notifications&email_token=AAKAOIQOCULSNCBWNQBS33TREAGCPA5CNFSM4KXZVAX2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMTPIWA#issuecomment-589755480>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKAOIXQS62R266VAIIDX7TREAGCPANCNFSM4KXZVAXQ>
> .
>

2020-02-22 15:28 UTC, jreback requested changes

2020-02-22 15:28 UTC, jreback commented on pandas/tests/scalar/test_na_scalar.py
> +def test_pickle_roundtrip_pandas():
ideally better to just parameterize this (@jorisvandenbossche comment below)

2020-02-26 12:37 UTC, jreback commented
@TomAugspurger can you rebase and update (small requests)

2020-03-02 18:18 UTC, TomAugspurger commented
I think everything has been addressed.

2020-03-02 23:13 UTC, jorisvandenbossche approved these changes

2020-03-02 23:13 UTC, merged

2020-03-02 23:13 UTC, jorisvandenbossche commented
Thanks @TomAugspurger !

2020-03-02 23:20 UTC, jorisvandenbossche commented
@MeeseeksDev backport to 1.0.x