DataFrame: Ctor from non Iterable 2-d array like
pandas-dev/pandas pull request #32109
Opened 2020-02-19 15:56 UTC by jschueller

In case we pass a 2d array like that do not use __iter__ but the
__getitem__ interface, it falls outside the collection.abc.Iterable case
and throw.

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-02-19 15:56 UTC, pep8speaks commented
Hello @jschueller! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/frame/test_constructors.py`](https://github.com/pandas-dev/pandas/blob/c0d40abdb48cb08ed6c67383bc452657fa2360cb/pandas/tests/frame/test_constructors.py):

> [Line 2599:36](https://github.com/pandas-dev/pandas/blob/c0d40abdb48cb08ed6c67383bc452657fa2360cb/pandas/tests/frame/test_constructors.py#L2599): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 2600:13](https://github.com/pandas-dev/pandas/blob/c0d40abdb48cb08ed6c67383bc452657fa2360cb/pandas/tests/frame/test_constructors.py#L2600): [E306](https://duckduckgo.com/?q=pep8%20E306) expected 1 blank line before a nested definition, found 0
> [Line 2605:26](https://github.com/pandas-dev/pandas/blob/c0d40abdb48cb08ed6c67383bc452657fa2360cb/pandas/tests/frame/test_constructors.py#L2605): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 2605:28](https://github.com/pandas-dev/pandas/blob/c0d40abdb48cb08ed6c67383bc452657fa2360cb/pandas/tests/frame/test_constructors.py#L2605): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 2606:13](https://github.com/pandas-dev/pandas/blob/c0d40abdb48cb08ed6c67383bc452657fa2360cb/pandas/tests/frame/test_constructors.py#L2606): [E306](https://duckduckgo.com/?q=pep8%20E306) expected 1 blank line before a nested definition, found 0
> [Line 2609:26](https://github.com/pandas-dev/pandas/blob/c0d40abdb48cb08ed6c67383bc452657fa2360cb/pandas/tests/frame/test_constructors.py#L2609): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 2611:30](https://github.com/pandas-dev/pandas/blob/c0d40abdb48cb08ed6c67383bc452657fa2360cb/pandas/tests/frame/test_constructors.py#L2611): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 2612:1](https://github.com/pandas-dev/pandas/blob/c0d40abdb48cb08ed6c67383bc452657fa2360cb/pandas/tests/frame/test_constructors.py#L2612): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2020-02-20 02:42 UTC, jbrockmendel commented
can you run `black pandas/tests/frame/test_constructors.py`

2020-02-20 02:43 UTC, jbrockmendel commented on pandas/tests/frame/test_constructors.py
> +            def __init__(self, size, dim):
size, dim -> length, width?

2020-02-20 02:44 UTC, jbrockmendel commented
what use case is likely to lead to this kind of input?

2020-02-20 04:07 UTC, WillAyd commented
Maybe a lack of understanding but not sure I see this as being useful and worth supporting. Does this reference an open issue?

2020-02-20 07:32 UTC, jschueller commented on pandas/tests/frame/test_constructors.py
> +            def __init__(self, size, dim):
yes

2020-02-20 07:37 UTC, jschueller commented
we have a container that behaves like this in openturns:
http://openturns.github.io/openturns/master/user_manual/_generated/openturns.Sample.html?highlight=sample#openturns.Sample

this change would allow to use the DataFrame ctor directly:
```
import openturns as ot
import pandas as pd
sample = ot.Normal(3).getSample(10)
df = pd.DataFrame(data=sample, columns=sample.getDescription())
```

for now we can only build a DataFrame using from_records:
```
df = pd.DataFrame.from_records(sample, columns=sample.getDescription())
```

One could consider inconsistent that it succeeds with from_records and not with the ctor

2020-02-20 10:00 UTC, jreback requested changes
i am not how this is useful in any way
a non iterable container is very strange 

if this succeeds in from_records then use that
that likely just happens to work

2020-02-20 10:03 UTC, jschueller commented
It's not that it is not iterable, it's just that it does not use the __iter__/__next__ interface for iteration but the __gettitem__ interface, and so it's not getting in the abc.Iterable case

2020-02-26 06:15 UTC, WillAyd commented
In a vacuum this is OK, but my main concern is that we don’t comprehensively support this type of “iterable” so somewhat weird to do one-off here. Not sure it would even be worth the effort for other pandas objects that we construct from iterables, so I think I would be -1 on moving forward with this

2020-02-26 07:34 UTC, closed without merging

2020-02-26 07:34 UTC, jschueller commented
[sadface]

2020-02-26 17:43 UTC, WillAyd commented
Thanks in any case @jschueller - we disagree on this one but attempt is in any case appreciated. Certainly would welcome more in the future