replaced string = "HolyMoly" instead of string = "HolyMoly'" as there is a typo in docs"
pandas-dev/pandas pull request #32133
Opened 2020-02-20 17:39 UTC by PSY27

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-02-20 17:50 UTC, rohitsanj requested changes
some comments for your consideration

2020-02-20 17:50 UTC, rohitsanj commented on doc/source/whatsnew/v0.10.0.rst
> +    In [41]: store = pd.HDFStore('store.h5')
undo this change, remove the whitespace

2020-02-20 17:50 UTC, rohitsanj commented on doc/source/user_guide/io.rst
>     instead of this
please remove this line

2020-02-20 17:55 UTC, PSY27 commented on doc/source/whatsnew/v0.10.0.rst
> +    In [41]: store = pd.HDFStore('store.h5')
ok
thanks for the input

2020-02-20 22:08 UTC, WillAyd commented
I think this is correct as is - isn't this supposed to show how the single quote doesn't get escaped? See text immediately following

2020-02-20 23:36 UTC, WillAyd requested changes
as mentioned let's revert the change to the string, but can use f-strings if you'd like to make a change

2020-02-20 23:36 UTC, WillAyd commented on doc/source/user_guide/io.rst
>        store.select('df', 'index == %s' % string)
You can update this to use an f-string if you'd like to change something

2020-02-21 13:55 UTC, MarcoGorelli commented
> I think this is correct as is - isn't this supposed to show how the single quote doesn't get escaped? See text immediately following

Yup, my bad - sorry @PSY27 . Though as Will said, if you change line 3818 to use an f-string, that would be good

2020-02-22 02:43 UTC, rohitsanj requested changes

2020-02-22 02:43 UTC, rohitsanj commented on doc/source/user_guide/io.rst
>        store.select('df', 'index == %s' % string)
Change this to 
```python
store.select('df', f'index == {string}')
```

2020-02-22 02:43 UTC, rohitsanj commented on doc/source/user_guide/io.rst
> +      string = "HolyMoly"
Revert this change

2020-02-22 02:43 UTC, rohitsanj commented on doc/source/user_guide/io.rst
> +      string = "HolyMoly"
Revert this change as well

2020-02-22 02:43 UTC, rohitsanj commented on doc/source/user_guide/io.rst
>        store.select('df', 'index == string')
@WillAyd shouldn't this be changed to use an f-string too?

2020-02-22 12:22 UTC, PSY27 commented
@WillAyd @MarcoGorelli  please review it now

2020-02-22 13:11 UTC, MarcoGorelli requested changes
Looks good, thanks @PSY27!

While we're here, there's some other `.format`s which could be changed within this file - for example, this one on line 3828:

```
store.select('df', f'index == {string!r}')
```

Else I think it's fine as is, I realise the requirement for this PR wasn't clear upfront :)

EDIT
----

Though if you do make this extra change (line 3828) please also change the line
```
If you *must* interpolate, use the ``'%r'`` format specifier
```
to
```
If you *must* interpolate, use the ``!r`` conversion flag
```

2020-02-22 16:33 UTC, merged

2020-02-22 16:33 UTC, jreback commented
thanks @PSY27