CLN/TST: parametrize some tests in tests.indexing.test_float
pandas-dev/pandas pull request #32187
Opened 2020-02-22 21:27 UTC by jbrockmendel

2020-02-23 15:59 UTC, jreback requested changes

2020-02-23 15:59 UTC, jreback commented on pandas/tests/indexing/test_floats.py
> +    @pytest.mark.parametrize("index_func", tm.all_index_generator(5))
can you use the indices fixture?

2020-02-23 20:30 UTC, jbrockmendel commented on pandas/tests/indexing/test_floats.py
> +    @pytest.mark.parametrize("index_func", tm.all_index_generator(5))
not without being pretty invasive

2020-02-24 16:33 UTC, jreback commented on pandas/tests/indexing/test_floats.py
> +    @pytest.mark.parametrize("index_func", tm.all_index_generator(5))
kk, on the list for the future

2020-02-24 16:33 UTC, jreback approved these changes

2020-02-24 16:34 UTC, jreback commented
lgtm merge on green.

2020-02-26 04:43 UTC, merged