PERF: pass through to numpy validation for iloc setitem
pandas-dev/pandas pull request #32257
Opened 2020-02-26 02:00 UTC by jbrockmendel

We lose a little bit of ground on the range and slice (not really sure why), pick up a bigger amount of ground on list or ndarray.

```
In [3]: ser = pd.Series(range(10**5))                                                                                      
In [4]: key = range(100, 200) 
In [5]: key2 = list(key)
In [6]: key3 = slice(100, 200)                                                                                             
In [7]: key4 = np.array(key2)                                                                                                 

In [16]: %timeit ser.iloc[key] = 1
56.3 µs ± 1.19 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)  # <-- master
62.9 µs ± 1.77 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)  # <-- PR

In [17]: %timeit ser.iloc[key2] = 1
95.6 µs ± 2.69 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)  # <-- master
55.6 µs ± 922 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)  # <-- PR

In [20]: %timeit ser.iloc[key3] = 1
49 µs ± 756 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)  # <-- master
50.6 µs ± 1.01 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)  # <-- PR

In [21]: %timeit ser.iloc[key4] = 1
71.6 µs ± 1.98 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)  # <-- master
45.7 µs ± 427 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)  # <-- PR
```

2020-02-26 12:43 UTC, jreback requested changes
lgtm. minor nit

2020-02-26 12:43 UTC, jreback commented on pandas/core/indexing.py
> +                #  with having numpy raise IndexError("too many indices for array")
would be ok i think

2020-02-26 12:43 UTC, jreback commented on pandas/tests/frame/indexing/test_indexing.py
> +# We pass through a TypeError raised by numpy
nit. you used iloc_msg in the other function (non-private); i would make these more verbose

slice_exception_msg

2020-02-26 19:35 UTC, jbrockmendel commented
Removed the tuple length validation, picked up on the order of a microsecond compared to the posts from the OP.

2020-02-27 12:52 UTC, jreback approved these changes

2020-02-27 12:52 UTC, merged

2020-02-27 12:52 UTC, jreback commented
thanks