DOC: Update pandas.core.groupby.GroupBy.pipe docstring
pandas-dev/pandas pull request #32352
Opened 2020-02-29 05:09 UTC by hsjsjsj009

- [x] closes https://github.com/pandanistas/pandanistas_sprint_ui2020/issues/2
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-02-29 17:29 UTC, WillAyd requested changes
looks good! a few edits

2020-02-29 17:29 UTC, WillAyd commented on pandas/core/groupby/groupby.py
> +Use `.pipe` when you want to improve readability.
Can you revert the changes to this paragraph?

2020-02-29 17:29 UTC, WillAyd commented on pandas/core/groupby/groupby.py
> +    Function to apply to this %(klass)s object or, alternatiy,
```suggestion
    Function to apply to this %(klass)s object or
```

2020-03-07 20:41 UTC, datapythonista commented
@hsjsjsj009 do you have time to address the comments? Would be great to get this merged.

2020-03-07 20:46 UTC, hsjsjsj009 commented
Sorry, I just saw this email, I will do it today.

On Sun, Mar 8, 2020, 3:41 AM Marc Garcia <notifications@github.com> wrote:

> @hsjsjsj009 <https://github.com/hsjsjsj009> do you have time to address
> the comments? Would be great to get this merged.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/32352?email_source=notifications&email_token=ALI76F275UEZU3S2A2VZVV3RGKWQLA5CNFSM4K6NGZHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOEE5QQ#issuecomment-596135618>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALI76FYV7KL5ZXIMV4E5EV3RGKWQLANCNFSM4K6NGZHA>
> .
>

2020-03-07 21:38 UTC, datapythonista reviewed
Looks good, just a small thing.

2020-03-07 21:38 UTC, datapythonista commented on pandas/core/groupby/groupby.py
> +functions expect Series, DataFrames, GroupBy or Resampler objects.
can you restore `that`

2020-03-07 21:43 UTC, closed without merging

2020-03-07 21:47 UTC, hsjsjsj009 commented on pandas/core/groupby/groupby.py
> +functions expect Series, DataFrames, GroupBy or Resampler objects.
okay