Fix PR08, RT02, RT03, and SA01 on pandas.Index.fillna
pandas-dev/pandas pull request #32355
Opened 2020-02-29 05:15 UTC by RafifEL

- [x] closes #https://github.com/pandanistas/pandanistas_sprint_ui2020/issues/5
- [ ] tests added / passed
- [x] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-02-29 08:59 UTC, MomIsBestFriend commented
Why was all of those files in c4099b5 was removed?

2020-02-29 17:32 UTC, WillAyd commented
@RafifEL looks like something went awry with the git workflow here. Can you `git checkout master FILENAME` for all the files you didn't update the docstring in and re-push?

2020-02-29 22:31 UTC, RafifEL commented
I'm sorry I'm new to this stuff. is there any way for me to go back to 1dbea46 commit?

2020-02-29 22:35 UTC, RafifEL commented
> @RafifEL looks like something went awry with the git workflow here. Can you `git checkout master FILENAME` for all the files you didn't update the docstring in and re-push?

I'm sorry, I'm new to this stuff, is there anyway for me to hard reset to 1dbea46 commit?

2020-03-01 02:23 UTC, WillAyd commented
Sure! From your branch try:

```sh
git reset --hard 1dbea46
git push -f origin rafif-feature
```

2020-03-01 09:10 UTC, RafifEL commented
> Why was all of those files in [c4099b5](https://github.com/pandas-dev/pandas/commit/c4099b526ec0e1add6577f5d07d753860fce9b38) was removed?

I'm Sorry, i was trying to see the HTML of the documentation by using "python doc/make.py html". It got an Error, so i delete the reference folder on this branch

2020-03-02 22:54 UTC, WillAyd requested changes
Nice job getting back to a clean state. Just some minor fixups otherwise should be good to go here

2020-03-02 22:54 UTC, WillAyd commented on pandas/core/indexes/base.py
> +        filled
```suggestion
        Index
```

Can just specify return type; don't need named variable in Returns section

2020-03-02 22:54 UTC, WillAyd commented on pandas/core/indexes/base.py
> +            Index.
Let's remove this line altogether

2020-03-04 15:41 UTC, WillAyd approved these changes

2020-03-04 15:41 UTC, merged

2020-03-04 15:41 UTC, WillAyd commented
Thanks @RafifEL