docs: fix SS06, PR08, RT02, RT03, SA04 in pandas.DatetimeIndex.indexe…
pandas-dev/pandas pull request #32353
Opened 2020-02-29 05:09 UTC by rahmadiantio

…r_at_time

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

 Fix : https://github.com/pandanistas/pandanistas_sprint_ui2020/issues/8

2020-02-29 05:09 UTC, pep8speaks commented
Hello @rahmadiantio! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/indexes/datetimes.py`](https://github.com/pandas-dev/pandas/blob/18743f33fcd52fbf57bd3e18374c9450985aae09/pandas/core/indexes/datetimes.py):

> [Line 706:1](https://github.com/pandas-dev/pandas/blob/18743f33fcd52fbf57bd3e18374c9450985aae09/pandas/core/indexes/datetimes.py#L706): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 707:13](https://github.com/pandas-dev/pandas/blob/18743f33fcd52fbf57bd3e18374c9450985aae09/pandas/core/indexes/datetimes.py#L707): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 720:72](https://github.com/pandas-dev/pandas/blob/18743f33fcd52fbf57bd3e18374c9450985aae09/pandas/core/indexes/datetimes.py#L720): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 725:72](https://github.com/pandas-dev/pandas/blob/18743f33fcd52fbf57bd3e18374c9450985aae09/pandas/core/indexes/datetimes.py#L725): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2020-02-29 06:41 UTC, Iqrar99 commented on pandas/core/indexes/datetimes.py
> +            An array is a container object that holds a fixed number of
This line has a trailing space. Should be removed.
```suggestion
            An array is a container object that holds a fixed number of
```

2020-02-29 06:42 UTC, Iqrar99 commented on pandas/core/indexes/datetimes.py
> +        indexer_between_time : Return index locations of values between
Also this line.
```suggestion
        indexer_between_time : Return index locations of values between
```

2020-02-29 06:43 UTC, Iqrar99 requested changes
Some trailing spaces should be removed.

2020-03-07 20:44 UTC, datapythonista reviewed
Thanks for the contribution @rahmadiantio, do you have time to address the comments?

2020-03-07 20:44 UTC, datapythonista commented on pandas/core/indexes/datetimes.py
> +        array of integers
Isn't this returning an Index?

2020-03-07 20:44 UTC, datapythonista commented on pandas/core/indexes/datetimes.py
> +        asof : bool
Do you mind adding a description here?

2020-03-10 14:37 UTC, datapythonista commented
Closing as stale. @rahmadiantio let us know if you finally want to address the review comments.

2020-03-10 14:37 UTC, closed without merging