BUG: Fix DataFrame.apply(..., raw=True) not calling with raw array
pandas-dev/pandas pull request #32425
Opened 2020-03-03 23:37 UTC by kernc

- [x] closes https://github.com/pandas-dev/pandas/issues/32423
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-03-04 00:24 UTC, kernc commented
Seems to pass. :tada: Where do I put the whatsnew?

2020-03-04 00:48 UTC, WillAyd requested changes
Thanks for the PR. Can you put the whatsnew note in for 1.1?

@jreback

2020-03-04 00:48 UTC, WillAyd commented on pandas/tests/frame/test_apply.py
> +    def test_apply_raw(self, float_frame, mixed_type_frame):
Can you just make a separate test for this and reference GH issue number?

2020-03-04 00:48 UTC, WillAyd commented on pandas/tests/frame/test_apply.py
> +    def test_apply_raw(self, float_frame, mixed_type_frame):
Also can you assert that this is getting passed a 1D array?

2020-03-04 13:47 UTC, jreback requested changes
looks good. can you add a whatsnew note for 1.1, in bug fixes, reshaping.

2020-03-04 13:48 UTC, jreback requested changes

2020-03-04 13:48 UTC, jreback commented on pandas/tests/frame/test_apply.py
> +        # Mixed dtype
can you move the _assert_raw to the top of this test & use it *also* on a single dtype frame (like you do below but on float_frame as well)

2020-03-06 15:55 UTC, WillAyd approved these changes
lgtm @jreback

2020-03-14 20:21 UTC, jreback approved these changes

2020-03-14 20:21 UTC, merged

2020-03-14 20:21 UTC, jreback commented
thanks @kernc