Disallow .__call__() as workaround for non-named functions
pandas-dev/pandas pull request #32460
Opened 2020-03-05 12:07 UTC by alexmojaki

Currently this script:
```python
import pandas as pd
funcs = [lambda: 1]
pd.eval("funcs[0]()")
```

Fails with:

    TypeError: Only named functions are supported

however this can easily be worked around by adding `.__call__`:

```python
pd.eval("funcs[0].__call__()")
```

I'm assuming we don't want to allow this workaround. This PR ensures that it will fail with the same error.

2020-03-15 00:53 UTC, jreback requested changes
I am not sure what you are suggesting here? in theory lambda functions could be supported, but to be honest i think the error is fine here. Always start with a test.

2020-03-15 08:12 UTC, alexmojaki commented
It's not about lambdas. In this context "named" means a variable name or an attribute - pandas doesn't allow calling arbitrary expressions. For example `funcs[0]` is a subscript expression so it can't be called.

2020-04-10 22:12 UTC, jreback requested changes
needs a whatsnew note, bug fixes for 1.1 under the reshaping section. pls merge master and ping on green.

2020-04-10 22:12 UTC, jreback commented on pandas/tests/frame/test_query_eval.py
> +        with pytest.raises(TypeError):
can you test the exception message as well, it is not clear what the user is going to see here

2020-05-10 12:37 UTC, alexmojaki commented
@jreback ping!

2020-05-10 15:43 UTC, jreback requested changes
looks ok, ping on green.

2020-05-10 15:43 UTC, jreback commented on pandas/tests/frame/test_query_eval.py
> +        def func(*_):
can you add the issue number here as a comment.

2020-05-10 17:51 UTC, pep8speaks commented
Hello @alexmojaki! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/frame/test_query_eval.py`](https://github.com/pandas-dev/pandas/blob/2f7c3a12aae2c722cf4485bde9675bee2b874905/pandas/tests/frame/test_query_eval.py):

> [Line 1188:89](https://github.com/pandas-dev/pandas/blob/2f7c3a12aae2c722cf4485bde9675bee2b874905/pandas/tests/frame/test_query_eval.py#L1188): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 88 characters)

2020-05-10 19:19 UTC, alexmojaki commented
@jreback pong!

2020-05-13 15:53 UTC, jreback approved these changes

2020-05-13 15:53 UTC, merged

2020-05-13 15:53 UTC, jreback commented
thanks @alexmojaki