CLN: Remove redundant index test from tests/base/test_ops.py
pandas-dev/pandas pull request #32484
Opened 2020-03-06 09:48 UTC by SaturnFromTitan

part of #23877
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Boolean indexing is already thoroughly tested in `test_series_mask_boolean` in `tests/indexes/test_na_indexing.py`

2020-03-06 15:45 UTC, WillAyd requested changes
On board with cleaning up, but are we not losing any coverage here? Maybe overlooking, but one that sticks out is indexing with an Index object which appears here but I think not in the test you linked to replace this?

2020-03-07 09:24 UTC, SaturnFromTitan commented
Good point @WillAyd, I'll check that later. I was assuming that if we lose coverage, then I'd get a codecov warning here in the PR. Isn't there a bot for these sort of things?

2020-03-07 21:14 UTC, WillAyd commented
We do have codecov but it’s not generally very insightful (at least for us)

Sent from my iPhone

> On Mar 7, 2020, at 1:24 AM, Martin Winkel <notifications@github.com> wrote:
> 
> ﻿
> Good point @WillAyd, I'll check that later. I was assuming that if we lose coverage, then I'd get a codecov warning here in the PR. Isn't there a bot for these sort of things?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-03-08 19:34 UTC, SaturnFromTitan commented on pandas/tests/indexing/test_na_indexing.py
> +        expectation = do_not_raise()
inspired by https://github.com/pytest-dev/pytest/issues/1830

2020-03-08 19:38 UTC, SaturnFromTitan commented
@WillAyd I think this is ready for another review now. I added an `indexer_class` parametrization to `test_series_mask_boolean` and refactored the test a little bit (which I mostly had to do to get it passing)

2020-03-08 21:37 UTC, SaturnFromTitan commented on pandas/tests/indexing/test_na_indexing.py
> +@pytest.mark.parametrize("indexer_class", [list, pd.array, pd.Index, pd.Series])
This test previously only covered `pd.array` and `pd.Series`

2020-03-08 21:38 UTC, SaturnFromTitan commented on pandas/tests/indexing/test_na_indexing.py
> +        ([], "object"),
The empty scenario was previously covered with some redundant code in the bottom of the test. I moved it to the parametrization instead and adjusted the generic test code to handle it properly

2020-03-11 03:51 UTC, jreback commented
looks ok, will have to look again after @WillAyd comments are addressed.

2020-03-11 07:25 UTC, SaturnFromTitan commented
@jreback I addressed all comments of @WillAyd (added the lost test cases to the parametrization of `test_series_mask_boolean`)

2020-03-14 20:12 UTC, merged

2020-03-14 20:12 UTC, jreback commented
thanks @SaturnFromTitan