TST: fix test creating invalid CategoricalBlock
pandas-dev/pandas pull request #32519
Opened 2020-03-07 16:24 UTC by jbrockmendel

The incorrect tests here turned up when trying to replace Block.get_values calls with simpler alternatives.

2020-03-09 02:05 UTC, jreback requested changes

2020-03-09 03:08 UTC, jbrockmendel commented on pandas/core/internals/blocks.py
> +        if self.ndim == 2 and len(self.mgr_locs) != 1:
either goes here or in NonconsolidateableMixin (which should be merged into ExtensionBlock anyway)

2020-03-11 02:38 UTC, jreback commented on pandas/core/internals/blocks.py
> +        if self.ndim == 2 and len(self.mgr_locs) != 1:
no this is not what i mean. how can we possibly get here when passing a Categorical? and if you can't except by directly constructing a manager, then this should be an assertion error.

2020-03-11 02:46 UTC, jbrockmendel commented on pandas/core/internals/blocks.py
> +        if self.ndim == 2 and len(self.mgr_locs) != 1:
> then this should be an assertion error.

sure, will update

2020-03-11 02:57 UTC, jreback approved these changes

2020-03-11 02:57 UTC, jreback commented
k merge on green

2020-03-14 15:50 UTC, merged