BUG: retain tz in to_records
pandas-dev/pandas pull request #32535
Opened 2020-03-08 02:13 UTC by jbrockmendel

plus the initial motivation: get rid of two of our `_internal_get_values` calls (of which i count 16 left in master)

2020-03-11 02:36 UTC, jreback requested changes
can you add a whatsnew

2020-03-12 02:48 UTC, jbrockmendel commented
whatsnew added + green

2020-03-14 03:39 UTC, jreback approved these changes
lgtm. merge on green after comment.

2020-03-14 03:39 UTC, jreback commented on pandas/tests/frame/methods/test_to_records.py
> +        df = DataFrame({"A": date_range("2012-01-01", "2012-01-02", tz="US/Eastern")})
if you can add the issue numbe here

2020-03-14 18:37 UTC, jbrockmendel commented on pandas/tests/frame/methods/test_to_records.py
> +        df = DataFrame({"A": date_range("2012-01-01", "2012-01-02", tz="US/Eastern")})
updated+green

2020-03-14 21:29 UTC, merged