DOC: Fix EX01 in pandas.DataFrame.idxmax
pandas-dev/pandas pull request #32551
Opened 2020-03-09 05:53 UTC by farhanreynaldo

- [ ] closes #xxxx
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Related to #27977. 

```
################################################################################
################################## Validation ##################################
################################################################################

2020-03-09 13:55 UTC, MarcoGorelli requested changes
Thanks @farhanreynaldo , just suggesting some very minor changes

2020-03-09 13:55 UTC, MarcoGorelli commented on pandas/core/frame.py
> +        By default, it returns index for the maximum value in each columns.
By default, it returns the index for the maximum value in each column.

2020-03-09 13:55 UTC, MarcoGorelli commented on pandas/core/frame.py
> +        To return index for the maximum value in each rows, use ``axis="columns"``.
To return the index for the maximum value in each row, use ``axis="columns"``.

2020-03-09 13:55 UTC, MarcoGorelli commented on pandas/core/frame.py
> +        Consider dataset containing food consumption in Argentina.
Consider a dataset containing food consumption in Argentina.

2020-03-09 13:55 UTC, MarcoGorelli commented on pandas/core/frame.py
> +        ...                    'co2_emission': [37.2, 19.66, 1712]},
...                    'co2_emissions': [37.2, 19.66, 1712]},

(this will have to change in the other parts too)

2020-03-10 04:01 UTC, farhanreynaldo commented
Thanks for the input, @MarcoGorelli!

2020-03-10 14:13 UTC, datapythonista approved these changes
Thanks @farhanreynaldo, nice example.

2020-03-11 01:35 UTC, WillAyd approved these changes

2020-03-11 01:35 UTC, merged

2020-03-11 01:35 UTC, WillAyd commented
Thanks @farhanreynaldo