FIX: series.fillna doesn't shallow copy if len(series) == 0
pandas-dev/pandas pull request #32733
Opened 2020-03-15 19:09 UTC by SaturnFromTitan

- [x] closes #32543
- [] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2020-03-15 22:04 UTC, SaturnFromTitan commented
/azp run

2020-03-16 01:18 UTC, jreback requested changes
looks ok, ping on green.

2020-03-16 01:18 UTC, jreback commented on doc/source/whatsnew/v1.1.0.rst
> +- Calling :meth:`fillna` on an empty Series now correctly returns a shallow copied object. The behaviour is now consistent with :class:`Index`, :class:`DataFrame` and a non-empty :class:`Series` (:is
move to missng section

2020-03-16 08:41 UTC, SaturnFromTitan commented
@jreback Adapted the isnew section and CI is green

2020-03-16 08:41 UTC, SaturnFromTitan commented
@jreback btw, is there any chance I could get priviledges to run `/azp run`?

2020-03-16 12:30 UTC, jreback commented
@SaturnFromTitan added you to pandas-triage

you can now label & close issues (i think u can prob trigger CI not sure about that)

2020-03-16 12:34 UTC, SaturnFromTitan commented
sweet, thanks a lot @jreback!

2020-03-16 22:34 UTC, WillAyd approved these changes

2020-03-16 22:34 UTC, merged

2020-03-16 22:34 UTC, WillAyd commented
Great thanks @SaturnFromTitan and congrats on the triage role - well deserved!

2020-03-16 22:41 UTC, SaturnFromTitan commented
Thanks for the kind words @WillAyd :)