CLN: remove _ndarray_values
pandas-dev/pandas pull request #32768
Opened 2020-03-17 02:47 UTC by jbrockmendel

- [x] closes #23565
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-03-18 00:11 UTC, WillAyd requested changes

2020-03-18 00:11 UTC, WillAyd commented on pandas/core/arrays/categorical.py
> +        pass
This is nice on a first pass at the diff, but probably better just to blow this branch away

2020-03-18 00:11 UTC, WillAyd commented on pandas/core/indexes/base.py
> +        if not isinstance(values, np.ndarray):
Is there not a more generic way to accomplish this?

2020-03-19 00:01 UTC, WillAyd approved these changes
lgtm

2020-03-19 00:24 UTC, merged

2020-03-19 00:24 UTC, jreback commented
boom!