ERR: Raise on invalid na_action in Series.map
pandas-dev/pandas pull request #32790
Opened 2020-03-17 21:56 UTC by dsaxton

- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

`Series.map` treats any `na_action` other than `"ignore"` like `None`, but it should probably raise if someone provides an invalid option:

```python
In [1]: import pandas as pd                                                                                                                                

In [2]: pd.Series([1, 2, 3]).map(lambda x: x, na_action="xxxxx")                                                                                           
Out[2]: 
0    1
1    2
2    3
dtype: int64
```

2020-03-17 23:02 UTC, jbrockmendel commented
Do any Index methods need the same fix?

2020-03-17 23:43 UTC, dsaxton commented
> Do any Index methods need the same fix?

Looks like they do. Actually it seems worse, e.g. `ExtensionArray` indexes just ignore `na_action`: https://github.com/pandas-dev/pandas/blob/master/pandas/core/indexes/extension.py#L291

2020-03-19 00:31 UTC, jreback requested changes

2020-03-19 00:31 UTC, jreback commented on pandas/core/base.py
> +                raise ValueError("na_action must either be 'ignore' or None")
add: ```f`{na_action}``` was passed

2020-03-19 00:31 UTC, jreback commented on pandas/tests/series/test_apply.py
> +        s = pd.Series([1, 2, 3])
add the issue umber as a comment

2020-03-21 21:06 UTC, jreback approved these changes
lgtm. merge master and ping on green.

2020-03-21 22:18 UTC, dsaxton commented
> lgtm. merge master and ping on green.

@jreback Merged master and green, thanks for reviewing

2020-03-22 00:13 UTC, merged

2020-03-22 00:13 UTC, jreback commented
thanks