Added `const` where avaible
pandas-dev/pandas pull request #32893
Opened 2020-03-21 19:10 UTC by MomIsBestFriend

- [ ] closes #xxxx
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-03-21 20:28 UTC, jreback commented
any perf change?

cc @WillAyd @jbrockmendel

2020-03-21 20:28 UTC, jreback approved these changes

2020-03-21 22:10 UTC, jbrockmendel commented on pandas/_libs/tslibs/conversion.pyx
> +    ndarray[int64_t] trans,
can we make this `const int64_t[:]`?

2020-03-21 22:12 UTC, jbrockmendel commented
LGTM

2020-03-21 22:33 UTC, MomIsBestFriend commented
> any perf change?
> 
> cc @WillAyd @jbrockmendel

Unsure which function to test, which one you would like to see?

2020-03-21 22:41 UTC, jreback requested changes
asv on time zone functions

2020-03-21 22:53 UTC, MomIsBestFriend commented
@jreback Actually I can't manage to run ```asv```, I hoped you can give me a specific function/method name to ```%timeit``` on

2020-03-22 00:44 UTC, MomIsBestFriend commented
```
[ 75.00%] ··· tslibs.timestamp.TimestampOps.time_tz_convert                                                 ok
[ 75.00%] ··· ============ =============
                   tz                   
              ------------ -------------
                  None        296±4ns   
               US/Eastern    17.8±0.2μs 
                 <UTC>      5.11±0.04μs 
                tzutc()      5.17±0.2μs 
              ============ =============

[ 75.00%] · For pandas commit 4195bfbe <master> (round 2/2):
[ 75.00%] ·· Building for conda-py3.6-Cython-matplotlib-numba-numexpr-numpy-odfpy-openpyxl-pytables-pytest-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt...
[ 75.00%] ·· Benchmarking conda-py3.6-Cython-matplotlib-numba-numexpr-numpy-odfpy-openpyxl-pytables-pytest-scipy-sqlalchemy-xlrd-xlsxwriter-xlwt
[100.00%] ··· tslibs.timestamp.TimestampOps.time_tz_convert                                                 ok
[100.00%] ··· ============ =============
                   tz                   
              ------------ -------------
                  None        309±3ns   
               US/Eastern    17.6±0.4μs 
                 <UTC>      4.90±0.03μs 
                tzutc()      5.11±0.1μs 
              ============ =============


BENCHMARKS NOT SIGNIFICANTLY CHANGED.
```

2020-03-22 00:54 UTC, jreback approved these changes

2020-03-23 21:08 UTC, merged

2020-03-23 21:08 UTC, jbrockmendel commented
Thanks @MomIsBestFriend