BUG: query uses numexpr even when 'compute.use_numexpr' is False
pandas-dev/pandas pull request #33006
Opened 2020-03-25 10:46 UTC by quangngd

- [ ] closes #32556
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Still thinking about how to write tests while not using the "bug" in the related issue

2020-03-26 02:00 UTC, jreback requested changes
I am not sure how this address the actual issue (which is that numexpr knows nothing about extension types; they shouldn't be passed to it at all).

but the title suggests you think there is an actual but in use_numexpr? can you explain.

2020-03-26 03:06 UTC, quangngd commented
If i understand correctly, the issue #32556 is about df.query does not care about the pd.set_option option, not about the extension dtype (which is still open at #25369)
@teto used ```pd.set_option('compute.use_numexpr', False)``` as a workaround for the original dtype issue but turned out it is also a bug on its own.

2020-03-26 12:16 UTC, teto commented
@quangngd  that's an accurate description of the issue. Thanks for taking care of this !

2020-03-29 15:49 UTC, jreback commented
@quangngd you need to have a test which fails on master but works here. can you construct one.

2020-03-29 20:23 UTC, teto commented
there is one in my issue (might not be usable out of the box though).

2020-03-30 04:46 UTC, quangngd commented
@teto I don't think it's a good idea using a bug as a test.

2020-03-30 05:17 UTC, quangngd commented
So to my understanding, the test must be able to differentiate the used engine during the ```df.query```/ ```df.eval``` call (yah, just found out the bug is in ```df.eval``` too, and is too fixed by this pr). The thing is we could't use any "non-parse-able"  behaviour since it could be a bug and could be fixed in the future.
The best I could come up with is the following based on [numexpr' note](https://numexpr.readthedocs.io/en/latest/user_guide.html#notes).
```py
import pandas as pd
df = pd.DataFrame(data=[4+1j,5,6], columns=["col_test"])
s = "abs(col_test)"
display(df.eval(s, engine='python').dtype)
display(df.eval(s, engine='numexpr').dtype)
```
output:
```py
dtype('float64')
dtype('complex128')
```
But so far I can't think of how to make a test for ```df.query```

2020-06-14 15:44 UTC, jreback commented
@quangngd I am not sure of the status here. please merge master and address comments.

2020-06-17 08:34 UTC, quangngd commented
@jreback the fix is already there but I cannot think of a sensible test

2020-07-06 19:31 UTC, rhshadrach commented
@quangngd: What about this?

    from pandas.core.computation.eval import _check_engine
    with pd.option_context('compute.use_numexpr', False):
        result = _check_engine(None)
        assert result == 'python'

2020-07-07 03:52 UTC, quangngd commented
@rhshadrach thankyou, the test indeed fails on master and pass on my branch. Where should be the proper place to place the test?

2020-07-07 12:59 UTC, rhshadrach commented
> Where should be the proper place to place the test?

`tests.computation.test_eval`

2020-11-02 22:57 UTC, jbrockmendel commented on pandas/core/computation/eval.py
> +        engine = "numexpr" if _USE_NUMEXPR else "python"
i think in this case we need to check `expr.USE_NUMEXPR`, _not_ `USE_NUMEXPR` since the former may change at runtime

2020-11-26 19:12 UTC, jreback commented
closing, this needs a reproducible tests that fails before any patch. (it can certainly be part of the patch, but demonstrate on the issue)

2020-11-26 19:12 UTC, closed without merging

2020-11-27 16:10 UTC, teto commented
wait what ? it's not easy to reproduce, you would need to disable one package or monkeypatch one package I suppose. The absence of a test should not prevent fixing an issue/document it/remove the feature.

2020-11-27 16:35 UTC, jreback commented
w/o a test how do you know it was fixed?

2020-11-27 16:53 UTC, rhshadrach commented
Is this test not sufficient?

https://github.com/pandas-dev/pandas/pull/33006#issuecomment-654424734

2020-11-27 17:06 UTC, jreback commented
sure if it fails on master

2021-07-22 02:32 UTC, saehuihwang commented
take