ERR: Raise a better error for numpy singletons in Index
pandas-dev/pandas pull request #33026
Opened 2020-03-25 23:32 UTC by dsaxton

- [ ] closes #33017
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-03-25 23:35 UTC, dsaxton commented on pandas/core/indexes/base.py
> +            return Index(np.asarray(data), dtype=dtype, copy=copy, name=name, **kwargs)
Just checking for scalars _before_ testing for an `__array__` attribute since things like `np.array([1, 2])[0]` pass both

2020-03-26 00:10 UTC, WillAyd commented
lgtm - can you add a whatsnew?

2020-03-26 03:16 UTC, WillAyd requested changes
sorry one more nit otherwise lgtm

2020-03-26 03:16 UTC, WillAyd commented on pandas/tests/indexes/base_class/test_constructors.py
> +    @pytest.mark.parametrize("value", [1, [1, 2][0], np.array([1, 2])[0]])
```suggestion
    @pytest.mark.parametrize("value", [1, np.int64(1)])
```

I think can simplify a bit further

2020-03-26 13:24 UTC, merged

2020-03-26 13:24 UTC, jreback commented
thanks @dsaxton

2020-03-27 16:33 UTC, JoElfner commented
Many thanks! That was a quick fix! :)