Fix 25648 improve read csv stacktrace on bad argument
pandas-dev/pandas pull request #33023
Opened 2020-03-25 21:55 UTC by roberthdevries

- [x] closes #25648
- [x] tests added / passed
- [x] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2020-03-25 22:03 UTC, roberthdevries commented
It works, but it may not be pretty

2020-03-26 00:00 UTC, WillAyd commented
Yea this is pretty hacky :-X is this really the only option?

2020-03-26 04:55 UTC, gfyoung requested changes
-1 on this change unfortunately.  `exec` is extremely hacky for something that is arguably minor.

While I don't have an immediate alternative off the top of my head, I think it's better to let this one percolate a little than to force a fix.

2020-03-26 04:55 UTC, gfyoung commented on doc/source/whatsnew/v1.1.0.rst
> +- `TypeError` exceptions raised by :meth:`read_csv` and :meth:`read_table` where showing as ``parser_f`` when an unexpected keyword argument was passed (:issue:`25648`)
```suggestion
- `TypeError` exceptions raised by :meth:`read_csv` and :meth:`read_table` were showing as ``parser_f`` when an unexpected keyword argument was passed (:issue:`25648`)
```

2020-03-28 11:54 UTC, roberthdevries commented
The options to fix this are limited by the fact that the exception raising mechanism uses a read-only variable of the code attribute of a function: `<func>.code.co_name`.
This variable is set by the python compiler/interpreter by taking the name of the function when it is defined: `def <func>`. Which means that we **have** to do `def read_csv()` and `def read_table()` to fix this issue.

I see 4 options in total:

1. Use `exec()` to dynamically create the functions with the appropriate names
2. Make two duplicates of `parser_f` with all of its arguments, factor out the body of the function
3. Make a template function e.g. `parser_f.py.in` and generate `read_csv.py` and `read_table.py` at build time
4. Don't fix this issue :smiley: 

May I have your suggestions/votes please

2020-03-28 19:36 UTC, gfyoung commented
1. -1: too hacky as already discussed
2. -1: maintenance burden > error correctness
3. -0.5: less maintenance burden, but I still feel creating a template just for this is too much

4. +0: It's worked us for awhile, but I don't want to give up on this just yet.

Middle ground option:

Rename `parser_f` to something like `read_document` ?   Then the function name isn't as foreign sounding and at least aligns with what `read_csv` and `read_table` do.

Another middle ground option:

Create a wrapper around `parser_f` than takes in `*args` and `**kwargs` and catch `TypeError` to replace instances of the string `parser_f` with the function name.

The disadvantage is we lose the signature when we do `help` on these functions.

2020-03-28 20:00 UTC, jreback commented
agree with comments here - we cannot use string execution like this 

you an try setting 

parser_f.__name__ = ...

2020-03-28 22:15 UTC, gfyoung commented
> parser_f.name = ...

As the OP

2020-04-04 19:29 UTC, jbrockmendel commented
@roberthdevries can you rebase

2020-04-04 19:43 UTC, gfyoung commented
> @roberthdevries can you rebase

Before rebasing, I think it's only fair that we get some consensus on how to address the underlying problem, given that we largely agree that the proposed fix is not something we would like to merge.

2020-04-05 10:04 UTC, roberthdevries commented
I am currently ill, and not able to work on this

2020-04-05 10:26 UTC, gfyoung commented
> I am currently ill, and not able to work on this

@roberthdevries : Oh no!  Very sorry to hear that.  Hope you get better soon.

We can take over this PR once we get some consensus.

2020-04-16 21:53 UTC, jbrockmendel commented
is it possible compat.set_function_name may work where just setting `func.__name__` doesnt?

2020-04-16 22:39 UTC, gfyoung commented
> is it possible compat.set_function_name may work where just setting `func.__name__` doesnt?

@jbrockmendel : Unfortunately not.  As mentioned in the OP, the function name in the error message is populated from a read-only attribute.

2020-04-16 22:47 UTC, jbrockmendel commented
OK, then im inclined towards the emerging consensus of "learn to live with it"

2020-04-16 23:24 UTC, gfyoung commented
> OK, then im inclined towards the emerging consensus of "learn to live with it"

Learn to live with it?  We've been living with this stacktrace issue for years 😄

2020-05-22 10:48 UTC, simonjayhawkins commented
@roberthdevries Thanks for looking into this. closing for now as stale. ping if you want to continue.

2020-05-22 10:48 UTC, closed without merging

2020-05-22 14:00 UTC, roberthdevries commented
Can you mark  #25648 as wontfix?

2020-05-22 14:24 UTC, simonjayhawkins commented
added a needs discussion label and removed the contributions welcome for now.