BUG: Add test to ensure, that bug will not occur again. #33058
pandas-dev/pandas pull request #33072
Opened 2020-03-27 17:04 UTC by phofl

- [x] closes #33058
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Should I add a whatsnew entry? It's not really new, if it is backported to 1.0.1.

2020-03-27 17:10 UTC, simonjayhawkins commented
Thanks @phofl for the PR. changing closes #33058 to xref until a decision re backport.

> Should I add a whatsnew entry?

not needed

2020-03-27 17:17 UTC, simonjayhawkins approved these changes
Thanks @phofl lgtm pending green

2020-03-27 17:17 UTC, simonjayhawkins commented on pandas/tests/groupby/test_apply.py
> +def test_apply_function_adds_a_row():
```suggestion
def test_apply_function_with_indexing():
```

2020-03-27 17:18 UTC, simonjayhawkins commented
marked as 1.1 but could backport if fixed on 1.0.x

2020-03-27 17:42 UTC, phofl commented on pandas/tests/groupby/test_apply.py
> +def test_apply_function_adds_a_row():
Changed the test name

2020-04-02 13:01 UTC, simonjayhawkins commented
@phofl can you merge upstream master

2020-04-02 19:11 UTC, pep8speaks commented
Hello @phofl! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/groupby/test_apply.py`](https://github.com/pandas-dev/pandas/blob/41e43744b8115e805fbd59270c406a40ec040217/pandas/tests/groupby/test_apply.py):

> [Line 903:45](https://github.com/pandas-dev/pandas/blob/41e43744b8115e805fbd59270c406a40ec040217/pandas/tests/groupby/test_apply.py#L903): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2020-04-02 19:12 UTC, phofl commented
@simonjayhawkins Done.

2020-04-03 08:19 UTC, simonjayhawkins approved these changes
@phofl lgtm @jorisvandenbossche

2020-04-07 23:11 UTC, WillAyd commented
/azp run

2020-04-10 19:24 UTC, WillAyd requested changes
So I'm not sure this is worth adding a test for - mutating the argument during a `.apply` seems fraught with peril and I'm a little hesitant to make guarantees about behavior

@jorisvandenbossche do you have a strong preference towards adding this?

2020-04-10 20:45 UTC, jreback commented
> So I'm not sure this is worth adding a test for - mutating the argument during a `.apply` seems fraught with peril and I'm a little hesitant to make guarantees about behavior
> 
> @jorisvandenbossche do you have a strong preference towards adding this?

this is fine, we currently support mutating inside an apply, though we have an issue to deprecate.

2020-04-10 20:47 UTC, WillAyd commented
sounds good

2020-04-10 20:47 UTC, jreback requested changes
see my comments & ping on green.

2020-04-10 20:47 UTC, jreback commented on pandas/tests/groupby/test_apply.py
> +
can you put this in a *new* file, call it ``test_apply_mutate.py``; there are 2 tests 

```
pandas/tests/groupby/test_groupby.py:def test_mutate_groups():
pandas/tests/groupby/test_groupby.py:def test_no_mutate_but_looks_like():
```

that should also be moved there.

2020-04-10 20:47 UTC, merged

2020-04-10 20:48 UTC, WillAyd commented
Thanks @phofl

2020-04-10 20:48 UTC, WillAyd commented
Sorry @jreback merged while you were commented; i can do in a follow up

2020-04-10 21:23 UTC, jreback commented
thanks @WillAyd