Bug 30999
pandas-dev/pandas pull request #33103
Opened 2020-03-28 18:01 UTC by sumanau7

- [ ] closes #30999
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-03-28 18:02 UTC, sumanau7 commented
@MomIsBestFriend Please review.

2020-03-28 21:06 UTC, MomIsBestFriend commented on pandas/tests/indexes/period/test_setops.py
> +        msg = fr".*Input has different freq=W-WED from PeriodIndex/(freq=D/)"
does the ```.*``` necessary here?

2020-03-28 21:07 UTC, MomIsBestFriend commented on pandas/tests/indexes/period/test_setops.py
> +        msg = fr".*Input has different freq=W-WED from PeriodIndex/(freq=D/)"
```suggestion
        msg = fr".*Input has different freq=W-WED from PeriodIndex\(freq=D\)"
```

2020-03-29 05:59 UTC, sumanau7 commented on pandas/tests/indexes/period/test_setops.py
> +        msg = fr".*Input has different freq=W-WED from PeriodIndex/(freq=D/)"
No, updated the PR.

2020-03-29 08:14 UTC, sumanau7 commented
@MomIsBestFriend Green.

2020-03-29 09:17 UTC, MomIsBestFriend commented
>     * [x]  closes #30999
> 
>     * [x]  tests added / passed
> 
>     * [x]  passes `black pandas`
> 
>     * [x]  passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
> 
>     * [ ]  whatsnew entry

@sumanau7 Can you please change the word "closes" to the word "xref"?

2020-03-29 09:21 UTC, ShaharNaveh requested changes
In a few spots you are using f-strings where there isn't a reason to do so.

otherwise this is LGTM :)

2020-03-29 09:21 UTC, MomIsBestFriend commented on pandas/core/arrays/period.py
> +        assertion_msg = f"Should be numpy array of type i8"
```suggestion
        assertion_msg = "Should be numpy array of type i8"
```

2020-03-29 09:21 UTC, MomIsBestFriend commented on pandas/tests/indexes/period/test_constructors.py
> +        msg = f"Should be numpy array of type i8"
```suggestion
        msg = "Should be numpy array of type i8"
```

2020-03-29 09:21 UTC, MomIsBestFriend commented on pandas/tests/indexes/period/test_join.py
> +        msg = fr".*Input has different freq=2D from PeriodIndex\(freq=D\)"
```suggestion
        msg = r"Input has different freq=2D from PeriodIndex\(freq=D\)"
```

2020-03-29 09:21 UTC, MomIsBestFriend commented on pandas/tests/indexes/period/test_partial_slicing.py
> +        msg = f"slice indices must be integers or None or have an __index__ method"
```suggestion
        msg = "slice indices must be integers or None or have an __index__ method"
```

2020-03-29 09:21 UTC, MomIsBestFriend commented on pandas/tests/indexes/period/test_partial_slicing.py
> +        msg = f"slice indices must be integers or None or have an __index__ method"
```suggestion
        msg = "slice indices must be integers or None or have an __index__ method"
```

2020-03-29 09:21 UTC, MomIsBestFriend commented on pandas/tests/indexes/period/test_setops.py
> +        msg = fr"Input has different freq=W-WED from PeriodIndex\(freq=D\)"
```suggestion
        msg = r"Input has different freq=W-WED from PeriodIndex\(freq=D\)"
```

2020-03-29 09:21 UTC, MomIsBestFriend commented on pandas/tests/indexes/period/test_setops.py
> +        msg = fr"Input has different freq=W-WED from PeriodIndex\(freq=D\)"
```suggestion
        msg = r"Input has different freq=W-WED from PeriodIndex\(freq=D\)"
```

2020-03-29 09:21 UTC, MomIsBestFriend commented on pandas/tests/indexes/period/test_setops.py
> +        msg = fr"Input has different freq=2D from PeriodIndex\(freq=D\)"
```suggestion
        msg = r"Input has different freq=2D from PeriodIndex\(freq=D\)"
```

2020-03-29 13:16 UTC, sumanau7 commented
@MomIsBestFriend Green.

2020-03-29 13:46 UTC, ShaharNaveh requested changes
Small nitpick

2020-03-29 13:46 UTC, MomIsBestFriend commented on pandas/tests/indexes/period/test_join.py
> +        msg = r".*Input has different freq=2D from PeriodIndex\(freq=D\)"
```suggestion
        msg = r"Input has different freq=2D from PeriodIndex\(freq=D\)"
```

2020-03-29 15:25 UTC, merged

2020-03-29 15:25 UTC, jreback commented
thanks @sumanau7