BUG: Fix bug when replacing categorical value with self
pandas-dev/pandas pull request #33292
Opened 2020-04-04 20:04 UTC by dsaxton

- [ ] closes #33288
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-04-04 20:13 UTC, jbrockmendel commented
LGTM pending green

2020-04-04 21:21 UTC, MomIsBestFriend commented
@dsaxton If you rebase it should fix the Travis issue

2020-04-05 11:04 UTC, simonjayhawkins commented
@dsaxton I've tagged this as 1.0.4 for now since #33288 is a regression.

I don't think need to move whatsnew yet, see https://github.com/pandas-dev/pandas/pull/33157#issuecomment-606742451

opened #33300 to help keep track and discuss

2020-04-05 19:45 UTC, jreback requested changes

2020-04-05 19:45 UTC, jreback commented on pandas/core/arrays/categorical.py
>                  if new_value in cat.categories:
you can move this check to line 2451, e.g.
```
elif replace_value == new_value:
    continue
```

2020-04-05 19:45 UTC, jreback commented on pandas/tests/arrays/categorical/test_algos.py
> +        ("a", "a", ["a", "b"], None),
can you annotate this case (add a comment on line before with this issue number)

2020-04-06 22:01 UTC, jreback approved these changes

2020-04-06 22:01 UTC, merged

2020-04-06 22:02 UTC, jreback commented
thanks @dsaxton