CLN: assorted cleanups
pandas-dev/pandas pull request #33297
Opened 2020-04-04 23:59 UTC by jbrockmendel

Mostly annotations

2020-04-05 19:20 UTC, jreback requested changes

2020-04-05 19:20 UTC, jreback commented on pandas/_libs/tslibs/timedeltas.pyx
> +    m, p = precision_from_unit(unit or "ns")
is this hit? (the ns)

2020-04-05 19:20 UTC, jreback commented on pandas/core/indexes/base.py
> +            from copy import copy as copy_func
this should be at the top of the file

2020-04-05 22:41 UTC, jbrockmendel commented on pandas/core/indexes/base.py
> +            from copy import copy as copy_func
updated

2020-04-06 21:47 UTC, jreback approved these changes

2020-04-07 23:08 UTC, WillAyd approved these changes

2020-04-07 23:08 UTC, merged

2020-04-07 23:08 UTC, WillAyd commented
Thanks @jbrockmendel