BLD: Increase minimum version of Cython to 0.29.16
pandas-dev/pandas pull request #33334
Opened 2020-04-06 18:26 UTC by mgmarino

- In particular, this fixes a bug in code returning ctuples
    - cython/cython#2745 
    - cython/cython#1427
- This is a prereq for #33220

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-04-06 18:37 UTC, TomAugspurger commented
I think you need to bump `min_cython_ver` in `setup.py` and the `pyproject.toml`

2020-04-06 18:42 UTC, jreback commented on doc/source/whatsnew/v1.1.0.rst
> +Build Changes
Can you rename this to Development Changes

2020-04-06 20:43 UTC, datapythonista approved these changes
lgtm

2020-04-06 21:10 UTC, jreback requested changes
very minor comment, ping on green.

2020-04-06 21:10 UTC, jreback commented on doc/source/whatsnew/v1.1.0.rst
> +- The minimum version of Cython is now the most recent bug-fix version (0.29.16).
can you add this PR number here

2020-04-06 21:12 UTC, jreback commented
also if you can PR to pandas-wheels repo:  https://github.com/MacPython/pandas-wheels/blob/master/azure/posix.yml and https://github.com/MacPython/pandas-wheels/blob/master/azure/windows.yml (these 2 files).

2020-04-07 06:18 UTC, mgmarino commented
@jreback Tests green, PR in wheels repo opened

2020-04-07 23:23 UTC, jreback approved these changes

2020-04-07 23:24 UTC, merged

2020-04-07 23:24 UTC, jreback commented
thanks @mgmarino (and for the pandas-wheels one)