BUG/PLT: Order of columns is sorted alphabetically in df.hist
pandas-dev/pandas pull request #33336
Opened 2020-04-06 19:00 UTC by charlesdong1991

- [x] closes #29235
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2020-04-29 19:52 UTC, charlesdong1991 commented
could you please take a look? ^^  @WillAyd @jreback 

thanks!

2020-04-29 21:44 UTC, WillAyd requested changes
Thanks for the ping. Minor nit on whatsnew but otherwise lgtm

I wasn't too familiar with `try_sort`. Looks like there's only one other use in pandas/core/indexes/api.py so separately might be worth cleaning up if not required

2020-04-29 21:44 UTC, WillAyd commented on doc/source/whatsnew/v1.1.0.rst
> +- Bug in :meth:`DataFrame.hist` where the column is sorted given the ``column`` is assigned or not. (:issue:`29235`)
```suggestion
- Bug in :meth:`DataFrame.hist` where the order of the ``column`` argument was ignored (:issue:`29235`)
```

2020-04-30 08:40 UTC, charlesdong1991 commented
thanks for your review! @WillAyd I rephrase the whatsnew note

the build failure is unrelated

I will take a look at the other use of `try_sort` and see if it is needed, if not needed, I plan to have two follow-ups: one is to replace the `try_sort` in the other use, and then another one to deprecate the `try_sort`. Does it sound good to you? @WillAyd

2020-04-30 20:36 UTC, WillAyd approved these changes
lgtm

2020-05-01 07:33 UTC, charlesdong1991 commented
ping

seems it is the azure machine issue @WillAyd @jreback

2020-05-01 13:43 UTC, charlesdong1991 commented
ping @WillAyd @jreback

2020-05-05 00:50 UTC, merged

2020-05-05 00:50 UTC, WillAyd commented
Great thanks @charlesdong1991