TST: Parameterize tests
pandas-dev/pandas pull request #33402
Opened 2020-04-08 18:05 UTC by MomIsBestFriend

- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-04-08 20:45 UTC, jreback approved these changes

2020-04-08 21:33 UTC, jbrockmendel commented on pandas/tests/indexes/numeric/test_indexing.py
> +        assert idx.get_loc(1, method=method) == 1
to match how this looks in other files, lets remove "method_" from the test name, and not pass method kwarg

2020-04-08 21:33 UTC, jbrockmendel commented on pandas/tests/indexes/numeric/test_indexing.py
> +        "method, loc", [("pad", 1), ("backfill", 2), ("nearest", 1)]
for reasons beyond my ken, the pattern is to not put a space after comma

2020-04-08 21:34 UTC, jbrockmendel commented on pandas/tests/indexes/numeric/test_indexing.py
> +    def test_get_loc_float64_method_loc(self, method, loc):
maybe combine this with test_get_loc_float64_method above?

2020-04-08 21:35 UTC, jbrockmendel commented on pandas/tests/indexes/numeric/test_indexing.py
> +    def test_get_indexer_float64(self, method, arr):
"arr" -> "expected"

2020-04-08 21:35 UTC, jbrockmendel commented on pandas/tests/indexes/numeric/test_indexing.py
> +            idx.get_indexer(target, method=method), np.array(arr, dtype=np.intp)
separate into three lines 

result = ...
expected = ...
tm.assert_ ...

2020-04-08 21:36 UTC, jbrockmendel commented on pandas/tests/indexes/numeric/test_indexing.py
> +        "obj",
obj -> value

2020-04-08 21:37 UTC, jbrockmendel commented
a bunch of nitpicks, but this is substantively excellent.  we have tons of legacy tests that need to be split up like this

2020-04-10 21:02 UTC, jreback requested changes

2020-04-10 21:02 UTC, jreback commented on pandas/tests/indexes/numeric/test_indexing.py
> +    @pytest.mark.parametrize("method", ["pad", "backfill", "nearest"])
can create a fixture for this (followon ok)

2020-04-10 21:02 UTC, jreback commented on pandas/tests/indexes/numeric/test_indexing.py
> +            idx.get_indexer(idx), np.array([0, 1, 2], dtype=np.intp)
same here, use result, expected

2020-04-15 18:16 UTC, jbrockmendel commented on pandas/tests/indexes/numeric/test_indexing.py
> +        assert idx.get_loc(1, method=method) == 1
@MomIsBestFriend can you address comments; this is generally a nice refactor

2020-05-21 18:37 UTC, WillAyd commented
@MomIsBestFriend can you merge master?

2020-06-14 15:30 UTC, jreback commented
@MomIsBestFriend this looks fine, can you merge master and a few comments

2020-07-17 11:18 UTC, jreback commented
closing as stale

2020-07-17 11:18 UTC, closed without merging