Added option to ignore file paths
pandas-dev/pandas pull request #33479
Opened 2020-04-11 13:47 UTC by MomIsBestFriend

This is needed both for #32942 and to #33394 to ignore the ```pandas/tests``` directory

2020-04-14 22:11 UTC, alimcmaster1 commented
If you merge master test failures will be resolved

2020-04-16 23:07 UTC, jbrockmendel commented on scripts/validate_unwanted_patterns.py
> +            with open(file_path, mode="r") as file_obj:
is making "mode" explicit necesary?  its not a pattern we used elsewhere

2020-04-16 23:08 UTC, jbrockmendel commented on scripts/validate_unwanted_patterns.py
> +        help="Coma seperated file extensions to check.",
Coma -> Comma (i hope) 
seperated -> separated

looks like both of these need fixing on L395 too

2020-04-22 04:25 UTC, WillAyd requested changes

2020-04-22 04:25 UTC, WillAyd commented on scripts/validate_unwanted_patterns.py
> +    FILE_EXTENSIONS_TO_CHECK: FrozenSet[str] = frozenset(
```suggestion
    FILE_EXTENSIONS_TO_CHECK = frozenset(
```

Mypy will infer this from the right hand side

2020-04-22 04:25 UTC, WillAyd commented on scripts/validate_unwanted_patterns.py
> +    PATHS_TO_IGNORE: FrozenSet[str] = frozenset(excluded_file_paths.split(","))
```suggestion
    PATHS_TO_IGNORE = frozenset(excluded_file_paths.split(","))
```

2020-04-24 09:56 UTC, MomIsBestFriend commented
Sorry, I got into other obligation in the past week and a half, I'll try to finish what I started as much as I can.

2020-06-14 15:50 UTC, jreback commented
can you merge master

2020-07-10 00:06 UTC, jreback commented
closing as stale, if you want to continue pls ping.

2020-07-10 00:06 UTC, closed without merging