Added two tests for issue #29697
pandas-dev/pandas pull request #33508
Opened 2020-04-13 00:28 UTC by devjeetr

I added two basic tests for `merge` as requested in #29697, one for `how="outer"` and one for  `how="right"`. 

I'm not sure if the way I'm creating duplicate columns for the `expected` dataframe is the recommended way but I could not find anything on this. Please let me know if there's a better way to do this.

- [ ] closes #29697
- [x] 2 tests added / 2 passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2020-04-14 22:00 UTC, alimcmaster1 requested changes

2020-04-14 22:02 UTC, alimcmaster1 commented
Think the best place in the file for this test method would be directly after `def test_merge_suffix`

2020-04-16 06:02 UTC, devjeetr commented on pandas/tests/reshape/merge/test_merge.py
> +    def test_merge_right_duplicate_suffix(self):
Added @pytest.mark.parameterize. I am not super familiar with pytest but I tried following other tests that used parameterize, but let me know about any changes I should make.

2020-04-16 06:04 UTC, devjeetr commented
> Think the best place in the file for this test method would be directly after `def test_merge_suffix`

I gave it a look and I agree. Moved it in the latest commit.

2020-04-16 06:39 UTC, pep8speaks commented
Hello @devjeetr! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/reshape/merge/test_merge.py`](https://github.com/pandas-dev/pandas/blob/522bf13e21b4ef7a671a02ad8208bf173963607c/pandas/tests/reshape/merge/test_merge.py):

> [Line 2033:85](https://github.com/pandas-dev/pandas/blob/522bf13e21b4ef7a671a02ad8208bf173963607c/pandas/tests/reshape/merge/test_merge.py#L2033): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2020-04-16 22:59 UTC, alimcmaster1 commented
LGTM please fix up the pep8 issues for CI to pass. @devjeetr

2020-04-23 18:36 UTC, jbrockmendel commented
force-pushed a lint fixup

2020-04-26 20:24 UTC, merged

2020-04-26 20:24 UTC, jreback commented
thanks @devjeetr