Partial fix for Issue #28792
pandas-dev/pandas pull request #33514
Opened 2020-04-13 03:41 UTC by devjeetr

Fixed SR04 for `pandas/core/window/rolling.py`
- [ ] 0 tests added / 0 passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2020-04-14 22:07 UTC, alimcmaster1 commented
Please ref the issue in the description?

2020-04-14 22:08 UTC, alimcmaster1 requested changes

2020-04-14 22:08 UTC, alimcmaster1 commented on pandas/tests/reshape/merge/test_merge.py
> +    def test_merge_right_duplicate_suffix(self):
Please remove these changes - believe you have a separate PR for these

2020-04-16 17:02 UTC, jbrockmendel commented
Is this PR about the tests or the docstrings?

@datapythonista are the docstring edits here desired?  I dont find the extra verbosity helpful, but not a strong opinion

2020-04-16 17:14 UTC, datapythonista commented
> @datapythonista are the docstring edits here desired? I dont find the extra verbosity helpful, but not a strong opinion

Adding descriptions to the see also items is desired. But I agree with your point. I think adding `DataFrame.aggregate: Alias of DataFrame.agg.` is useful for users. The description added here is probably not very useful, and even confusing, since users will wonder which one they should use.

@devjeetr can you have another look, remove the unrelated changes as requested, and provide a more useful description.

2020-05-22 10:29 UTC, simonjayhawkins commented
@devjeetr closing as stale. ping if you want to continue.

2020-05-22 10:29 UTC, closed without merging