BUG: Series[listlike_of_ints] incorrect on MultiIndex
pandas-dev/pandas pull request #33539
Opened 2020-04-14 02:51 UTC by jbrockmendel

- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

This is one of the cases that @jorisvandenbossche identified in #33355.

2020-04-17 21:06 UTC, jreback requested changes
this needs a section in api breaking changes with an example as its possible some people were actually relying on this. i don't think deprecation is warranted as this is a small edge case.

2020-04-17 23:00 UTC, jbrockmendel commented
whatsnew added + green

2020-04-22 21:59 UTC, jbrockmendel commented
rebased+green

2020-04-25 21:01 UTC, jreback approved these changes

2020-04-25 21:02 UTC, merged