[WIP] Add remote file io using fsspec.
pandas-dev/pandas pull request #33549
Opened 2020-04-14 20:42 UTC by jrderuiter

- [x] closes #33452
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-04-17 00:29 UTC, alimcmaster1 commented on pandas/io/common.py
> +        file_obj = filesystem.open(filepath_or_buffer, mode=mode or "rb")
Do we need to pass through the encoding? to .open() You will potentially also fix this if you do so: https://github.com/pandas-dev/pandas/issues/26124 :)

2020-04-21 15:25 UTC, TomAugspurger reviewed
Have you been able to test this out manually? Do things seem OK?

2020-04-28 15:48 UTC, martindurant commented
@jrderuiter , is there any way in which I can help here?

2020-05-04 15:21 UTC, martindurant commented
ping ?

2020-05-04 15:35 UTC, jreback requested changes
you need to add fsspec to several of the ci files but not all and environment.yaml

to have testing and proper skipping

2020-05-04 15:35 UTC, jreback commented on pandas/io/common.py
> +def is_fsspec_url(url) -> bool:
can u type url

2020-05-04 15:35 UTC, jreback commented on pandas/io/common.py
> +    if not isinstance(url, str):
you don’t need this

2020-05-19 20:10 UTC, TomAugspurger commented
Closing in favor of https://github.com/pandas-dev/pandas/pull/34266.

2020-05-19 20:10 UTC, closed without merging