Issue 33428 fix
pandas-dev/pandas pull request #33583
Opened 2020-04-16 06:34 UTC by Dxin-code

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-04-16 06:34 UTC, pep8speaks commented
Hello @Dxin-code! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/plotting/_misc.py`](https://github.com/pandas-dev/pandas/blob/9f88a29b51e044e8d75b0dfeccdbfca7efd433d4/pandas/plotting/_misc.py):

> [Line 362:89](https://github.com/pandas-dev/pandas/blob/9f88a29b51e044e8d75b0dfeccdbfca7efd433d4/pandas/plotting/_misc.py#L362): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 88 characters)

2020-04-16 14:00 UTC, simonjayhawkins commented
Thanks @Dxin-code for the PR. #33428 is already fixed? issue is closed.

2020-04-16 14:11 UTC, simonjayhawkins requested changes

2020-04-16 17:13 UTC, jbrockmendel commented on pandas/tests/util/test_assert_frame_equal.py
> +    msg = f"{obj_fixture}"
The other edit fails the linter because the line is too long.  i think close this and focus on the other PRs

2020-04-22 04:00 UTC, WillAyd commented
Thanks for the PR but looks like this was already solved in #33099

2020-04-22 04:00 UTC, closed without merging

2020-04-22 04:17 UTC, Dxin-code commented
> Thanks for the PR but looks like this was already solved in #33099

Got it! Thanks for the reminder!