Issue 30999 fix
pandas-dev/pandas pull request #33581
Opened 2020-04-16 06:34 UTC by Dxin-code

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-04-16 06:34 UTC, pep8speaks commented
Hello @Dxin-code! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/arrays/boolean/test_arithmetic.py`](https://github.com/pandas-dev/pandas/blob/27a882dd4bc55e2c86b6ffb298522f8e37478f2b/pandas/tests/arrays/boolean/test_arithmetic.py):

> [Line 26:10](https://github.com/pandas-dev/pandas/blob/27a882dd4bc55e2c86b6ffb298522f8e37478f2b/pandas/tests/arrays/boolean/test_arithmetic.py#L26): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 26:10](https://github.com/pandas-dev/pandas/blob/27a882dd4bc55e2c86b6ffb298522f8e37478f2b/pandas/tests/arrays/boolean/test_arithmetic.py#L26): [E113](https://duckduckgo.com/?q=pep8%20E113) unexpected indentation
> [Line 26:13](https://github.com/pandas-dev/pandas/blob/27a882dd4bc55e2c86b6ffb298522f8e37478f2b/pandas/tests/arrays/boolean/test_arithmetic.py#L26): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 34:8](https://github.com/pandas-dev/pandas/blob/27a882dd4bc55e2c86b6ffb298522f8e37478f2b/pandas/tests/arrays/boolean/test_arithmetic.py#L34): [E901](https://duckduckgo.com/?q=pep8%20E901) IndentationError: unindent does not match any outer indentation level

2020-04-16 06:48 UTC, alimcmaster1 commented
Please can you give all these descriptive titles + fix up pep8? Thanks

2020-04-16 14:33 UTC, simonjayhawkins requested changes
Thanks @Dxin-code for the PR. https://github.com/pandas-dev/pandas/pull/33581#issuecomment-614448854

2020-04-16 17:16 UTC, jbrockmendel commented on pandas/tests/arrays/boolean/test_arithmetic.py
> +         msg="invalid scalars"
you've got a SyntaxError here

2020-05-22 10:39 UTC, simonjayhawkins commented
@Dxin-code closing as stale.

2020-05-22 10:39 UTC, closed without merging