TST: Groupby first/last/nth nan column test
pandas-dev/pandas pull request #33627
Opened 2020-04-18 11:37 UTC by jamescobonkerr

- [X] closes #33591
- [X] tests added / passed
- [X] passes `black pandas`
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

The first two asserts (`first()`/`last()`) fail on `1.0.3`, as expected.

2020-04-18 18:09 UTC, WillAyd requested changes
Thanks - just a minor nit to make things more readable otherwise lgtm

2020-04-18 18:09 UTC, WillAyd commented on pandas/tests/groupby/test_nth.py
> +    df["nans"] = df["data"].where(df["data"] != "A")
You can just add this column to the constructor

2020-04-19 15:46 UTC, simonjayhawkins requested changes
Thanks @jamescobonkerr for the PR. does this test follow the same code path as the code sample in the issue OP?, see https://github.com/pandas-dev/pandas/issues/33591#issuecomment-616164785

2020-04-19 17:13 UTC, simonjayhawkins commented
> The first two asserts (`first()`/`last()`) fail on `1.0.3`, as expected

this was changed in #32949

be86b6583f97a49ded14bdd4290ccf721bf1f645 is the first new commit
commit be86b6583f97a49ded14bdd4290ccf721bf1f645
Author: jbrockmendel <jbrockmendel@gmail.com>
Date:   Fri Apr 10 09:18:06 2020 -0700

    CLN: remove unnecessary Series._convert calls (#32949)

2020-04-19 18:01 UTC, jamescobonkerr commented
> Thanks @jamescobonkerr for the PR. does this test follow the same code path as the code sample in the issue OP?, see [#33591 (comment)](https://github.com/pandas-dev/pandas/issues/33591#issuecomment-616164785)

Ah, you're right — pardon the oversight.



> > The first two asserts (`first()`/`last()`) fail on `1.0.3`, as expected
> 
> this was changed in #32949
> 
> [be86b65](https://github.com/pandas-dev/pandas/commit/be86b6583f97a49ded14bdd4290ccf721bf1f645) is the first new commit
> commit [be86b65](https://github.com/pandas-dev/pandas/commit/be86b6583f97a49ded14bdd4290ccf721bf1f645)
> Author: jbrockmendel [jbrockmendel@gmail.com](mailto:jbrockmendel@gmail.com)
> Date: Fri Apr 10 09:18:06 2020 -0700
> 
> ```
> CLN: remove unnecessary Series._convert calls (#32949)
> ```

Removing the `_convert` call from `core.groupby.generic.DataFrameGroupBy._wrap_aggregated_output` seems to fix the reported issue, however, breaks a range of other tests. I don't have a great understanding of how `GroupBy` works. I'll close this PR.

2020-04-20 08:44 UTC, simonjayhawkins commented
@jamescobonkerr Thanks for working on this.

The test you have added here does have value since it is testing a change in behaviour against regression.

As you pointed out this test fails on 1.0.3 and is fixed on master. AFAICT this is working since #32949

I'll reopen this PR, but once merged will not close #33591 (rather than open a new issue at this point, i'll reference you code sample in #33591)

2020-04-20 08:50 UTC, simonjayhawkins approved these changes
Thanks @jamescobonkerr lgtm pending green ci.

2020-04-21 12:55 UTC, jreback requested changes

2020-04-21 12:55 UTC, jreback commented on pandas/tests/groupby/test_nth.py
> +    assert grouped["nans"].first().dtype == object
construct an expected frame and use
tm.assert_frame_equal(result, expected)

2020-04-23 17:51 UTC, jreback commented on pandas/tests/groupby/test_nth.py
> +    tm.assert_series_equal(grouped.nans.nth(0), expected)
dont' we need to *also* tests `.nth(-1)`?

2020-04-23 21:30 UTC, jreback approved these changes

2020-04-23 21:30 UTC, merged

2020-04-23 21:31 UTC, jreback commented
thanks @jamescobonkerr always happy to take these