BUG, TST, DOC: fix core.missing._akima_interpolate will raise AttributeError
pandas-dev/pandas pull request #33784
Opened 2020-04-25 04:54 UTC by hkennyv

- [x] closes #33426 
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Wasn't sure if this warranted a whatsnew entry since its mostly code cleanup

2020-04-25 22:08 UTC, jreback requested changes
lgtm. can you add a whatsnew note. put in bug fixes in 1.1 missing section, just say that clarified documentation on interpolate with method =akima the der parmater must be a scalar or None

2020-04-26 00:52 UTC, hkennyv commented
thanks @jreback, how's that look?

2020-04-26 19:57 UTC, jreback approved these changes

2020-04-26 19:57 UTC, merged

2020-04-26 19:57 UTC, jreback commented
thanks @hkennyv