BUG: Ignoring columns from index_col in _is_potential_multi_index
pandas-dev/pandas pull request #33982
Opened 2020-05-04 22:51 UTC by mproszewska

- [x] closes #33476
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [] whatsnew entry

2020-05-05 16:44 UTC, jreback requested changes
can you also add a csv test that hits this

2020-05-05 16:44 UTC, jreback commented on pandas/io/parsers.py
> +def _is_potential_multi_index(columns, index_col=None):
when adding args, can you type them (also existing args if you can)

2020-05-10 16:41 UTC, pep8speaks commented
Hello @mproszewska! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`pandas/tests/io/parser/test_index_col.py`](https://github.com/pandas-dev/pandas/blob/02706f01d5289bdeb05139aedd4b7125b79b4be9/pandas/tests/io/parser/test_index_col.py):

> [Line 203:1](https://github.com/pandas-dev/pandas/blob/02706f01d5289bdeb05139aedd4b7125b79b4be9/pandas/tests/io/parser/test_index_col.py#L203): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2020-05-13 16:04 UTC, jreback commented on pandas/tests/io/parser/test_index_col.py
> +    result = parser.read_csv(StringIO(data), index_col="I11", header=0)
can you compare this last as well

2020-05-25 22:15 UTC, jreback requested changes

2020-05-25 22:15 UTC, jreback commented on pandas/tests/io/excel/test_readers.py
> +    def test_header_with_index_col(self, engine, filename):
what exactly is this testing? can you add the issue number as a comment. should we also assert the results?

2020-05-25 22:15 UTC, jreback commented on pandas/tests/io/parser/test_index_col.py
> +    parser = all_parsers
can you add the issue number as a comment

2020-05-31 14:47 UTC, mproszewska commented
I added requested changes.

2020-05-31 22:11 UTC, jreback requested changes

2020-05-31 22:11 UTC, jreback commented on pandas/tests/io/excel/test_readers.py
> +    def test_header_with_index_col(self, engine, filename):
can you assert the results. as a point of interaction, do not resolve conversions, let the questioner do it.

2020-06-03 00:04 UTC, mproszewska commented
Everything should be fine now

2020-06-04 21:56 UTC, jreback approved these changes

2020-06-04 21:56 UTC, merged

2020-06-04 21:56 UTC, jreback commented
thanks @mproszewska

2020-06-12 12:32 UTC, kuraga commented
@mproszewska , thanks very much!

But @mproszewska , @jreback , should we add an argument to [this line](https://github.com/pandas-dev/pandas/pull/33982/files#diff-777d7549579ddc0c6e67596ad87e0d27L1594), too, shouldn't we?

2020-06-19 14:26 UTC, kuraga commented
@mproszewska , @jreback , ping.

2026-09-03 17:45 UTC, kuraga commented
> should we add an argument to [this line](https://github.com/pandas-dev/pandas/blob/c71bfc36211b5e2d860a06d8fbef902b757bd6e4/pandas/io/parsers.py#L1601), too, shouldn't we?

We shouldn't: we're constructing (multi-)index ourselves there, so we don't have the index column(s)).