Revert "CLN: short-circuit case in Block.replace (#27768)"
pandas-dev/pandas pull request #34048
Opened 2020-05-07 13:55 UTC by simonjayhawkins

- [ ] xref #32988
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-05-07 16:05 UTC, jreback requested changes
why are you reverting things?

2020-05-07 16:05 UTC, jreback commented
I am ok with reverting things for the 1.0.4 branch but not for master.

2020-05-07 16:40 UTC, jbrockmendel commented on pandas/core/internals/blocks.py
> -            # FIXME: make sure we have compatible NA
pls leave this and other comments

2020-05-07 17:40 UTC, simonjayhawkins commented on pandas/core/internals/blocks.py
> -            # FIXME: make sure we have compatible NA
sure

2020-05-09 20:07 UTC, jreback approved these changes

2020-05-09 20:07 UTC, merged

2020-05-09 20:07 UTC, jreback commented
thanks @simonjayhawkins