doc: clarify boxplot whisker's extension
pandas-dev/pandas pull request #34070
Opened 2020-05-08 14:49 UTC by neutrinoceros

As I'm getting started with box plots, I found confusing that the `DataFrame.boxplot` docstring didn't mention that whiskers extend _at most_ to 1.5 * IQR away from the box's edges.

- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry -> is it required for such a minor change ?

2020-05-09 07:37 UTC, MarcoGorelli requested changes
Thanks @neutrinoceros , agreed that this clarifies things

2020-05-09 07:37 UTC, MarcoGorelli commented on pandas/plotting/_core.py
> +`1.5 * IQR (IQR = Q3 - Q1)` from the edges of the box, or to the farther
```suggestion
`1.5 * IQR (IQR = Q3 - Q1)` from the edges of the box, or to the farthest
```

2020-05-09 07:42 UTC, MarcoGorelli approved these changes

2020-05-11 19:28 UTC, joooeey commented
This doc change is sorely needed. Thanks for doing it! However, your explanation is wrong. The whiskers only ever extend to 1.5*IQR if there happens to be a data point exactly there. Here's how it actually works: https://stackoverflow.com/a/49781675/4691830 .

I suggest the following wording:

``By default, they extend no more than `1.5 * IQR (IQR = Q3 - Q1)` from the edges of the box, ending at the farthest data point within that interval. Outliers are plotted as separate dots.``

2020-05-11 20:09 UTC, neutrinoceros commented
Thanks @joooeey for clarifying this, I applied your suggestion !

2020-05-11 20:14 UTC, MarcoGorelli commented
>  However, your explanation is wrong

@joooeey are you sure it's wrong? When the OP wrote

> they extend up to `1.5 * IQR (IQR = Q3 - Q1)` from the edges of the box, or to the farthest
data point if it lies within this interval

I think they meant that the whiskers only extend there if there's a point there, which I think is what you're saying.

> I suggest the following wording:

Having said that, thanks for this, I do think your wording is very clear

2020-05-11 20:19 UTC, MarcoGorelli commented
@neutrinoceros did you push it? :) I don't (yet) see anything here

2020-05-11 20:20 UTC, neutrinoceros commented
> I think they meant that the whiskers only extend there if there's a point there, which I think is what you're saying.

I believe my own wording was correct if you read the "or" _and_ the "within that interval" as an _inclusive_, which showed my own misunderstanding.

> @neutrinoceros did you push it? :) I don't (yet) see anything here

Oops, you're right, the pushed failed for some reason.

2020-05-21 18:17 UTC, WillAyd approved these changes

2020-05-21 18:17 UTC, merged

2020-05-21 18:17 UTC, WillAyd commented
Great thanks @neutrinoceros