BUG: Fixed __join_multi always returning indexers (#34074)
pandas-dev/pandas pull request #34075
Opened 2020-05-08 17:25 UTC by CuylenE

- [x] closes #34074
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-05-08 17:25 UTC, pep8speaks commented
Hello @CuylenE! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/indexes/base.py`](https://github.com/pandas-dev/pandas/blob/a28d6f95c1118839e58be7754ece9a2b3eeecb62/pandas/core/indexes/base.py):

> [Line 3536:1](https://github.com/pandas-dev/pandas/blob/a28d6f95c1118839e58be7754ece9a2b3eeecb62/pandas/core/indexes/base.py#L3536): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2020-05-09 07:30 UTC, MarcoGorelli requested changes
Thanks @CuylenE 

Is there a test case for the `return_indexers=False` case? If not, can you add one?

2020-05-10 15:16 UTC, jreback requested changes
also pls add a whatsnew note, bug fixes 1.1., MultiIndex section

2020-05-10 15:16 UTC, jreback commented on pandas/tests/indexes/multi/test_join.py
> +    join_idx, lidx, ridx = midx1.join(midx2, return_indexers=True)
can you add a test that hits return=False

2020-05-11 12:56 UTC, MarcoGorelli requested changes
Thanks @CuylenE , just making a suggestion for the test

2020-05-11 12:56 UTC, MarcoGorelli commented on pandas/tests/indexes/multi/test_join.py
> +    assert type(midx1.join(midx2, return_indexers=False)) != tuple
Could this be made more explicit?

Just a suggestion:
```python
result = midx1.join(midx2, return_indexers=False)
expected = <construct expected result here>
tm.assert_index_equal(result, expected)
```

As an aside, see [PEP8](https://www.python.org/dev/peps/pep-0008/) for how it's advised to write object type comparisons

2020-05-11 18:56 UTC, jreback approved these changes

2020-05-11 18:57 UTC, merged

2020-05-11 18:57 UTC, jreback commented
thanks @CuylenE