TST: Shrink groupby.nunique test case
pandas-dev/pandas pull request #34096
Opened 2020-05-09 22:29 UTC by dsaxton

This test takes about 40 seconds to run for me while shrinking the size of the data brings the runtime down to 2 seconds, presumably without changing coverage (do we even need to parametrize over n and m here?).

2020-05-09 22:47 UTC, jreback requested changes
pls leave this as is - this is rating a regresssiom from a few years back

u can mark slow i suppose

2020-05-09 23:37 UTC, rhshadrach commented
I've also wondered why the parameters are so large. Maybe it'd be worth tracking down the original issue and adding a comment.

2020-05-09 23:51 UTC, dsaxton commented
> I've also wondered why the parameters are so large. Maybe it'd be worth tracking down the original issue and adding a comment.

Looks like it was added here: https://github.com/pandas-dev/pandas/pull/10894

2020-05-10 15:03 UTC, jreback approved these changes

2020-05-10 15:04 UTC, merged

2020-05-10 15:04 UTC, jreback commented
thanks @dsaxton