TST: Added test for json containing the key "last_status_change_at"
pandas-dev/pandas pull request #34169
Opened 2020-05-14 01:08 UTC by rivera-fernando

- [ ] closes #32409
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-05-14 03:28 UTC, mroeschke requested changes
Could you move this test to `pandas/tests/frame/methods/test_describe.py`?

And structure the test similar to what is describe in our guide?

https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#writing-tests

2020-05-15 18:48 UTC, mroeschke commented on pandas/tests/frame/methods/test_describe.py
> +    result = pd.DataFrame(
- Could you remove the extra `_` in `test__`
- Could you add the issue number as a comment?
- This test should test this behavior: https://github.com/pandas-dev/pandas/issues/32409#issuecomment-626423254

2020-06-14 15:30 UTC, jreback commented
@rivera-fernando can you merge master and respond to comments

2020-06-28 08:06 UTC, MarcoGorelli requested changes

2020-06-28 08:06 UTC, MarcoGorelli commented on pandas/tests/frame/methods/test_describe.py
> +    result = pd.DataFrame(
Thanks @rivera-fernando 

What's the difference between `result` and expected? Can you construct `result` using `.describe` (as in the original issue)?

2020-07-12 09:17 UTC, simonjayhawkins commented
closing as stale

2020-07-12 09:17 UTC, closed without merging