TST: add explicit csr explicit zero tests for GH28992
pandas-dev/pandas pull request #34182
Opened 2020-05-14 20:44 UTC by bakitybacon

simple test case to check that explicitly setting a value to zero in a matrix with csr representation does not cause other values to change, specifically to be set to zero erroneously

- [ ] closes #xxxx
- [*] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-05-15 08:48 UTC, MarcoGorelli requested changes
Thanks @bakitybacon 

Can you run `black` again your changed file, and also add the issue number to your post so it reads
> closes #28992 

?

2020-05-25 23:08 UTC, jreback commented
@bakitybacon if you can fix up the linting issues & merge master, pls ping on green.

2020-06-01 01:45 UTC, jreback commented
can u merge master and ping on green

2020-07-24 12:43 UTC, simonjayhawkins commented
Thanks @bakitybacon for the PR. closing as stale.

2020-07-24 12:43 UTC, closed without merging