Make option_context a ContextDecorator.
pandas-dev/pandas pull request #34253
Opened 2020-05-19 12:54 UTC by anntzer

This makes it possible to use option_context as a decorator over an
entire function, saving an indent level and making it easy to comment
out (or in) the context while keeping correct indentation.

- [ ] closes #xxxx (N/A)
- [X] tests added / passed
- [X] passes `black pandas`
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

2020-05-19 14:51 UTC, WillAyd approved these changes
Looks good - test failure should be unrelated

2020-05-20 03:56 UTC, WillAyd commented
Can you merge master and repush? Should get CI green

2020-05-20 08:25 UTC, anntzer commented
done

2020-05-20 15:13 UTC, jreback requested changes
lgtm. doc-comments, ping on green.

2020-05-20 15:50 UTC, anntzer commented on doc/source/whatsnew/v1.1.0.rst
> +- Make ``option_context`` a :class:`contextlib.ContextDecorator`, which allows it to be used as a decorator over an entire function.
done

2020-05-20 15:50 UTC, anntzer commented on pandas/tests/config/test_config.py
> +        @self.cf.option_context("a", 123)
done

2020-05-25 17:40 UTC, jreback approved these changes

2020-05-25 17:40 UTC, merged

2020-05-25 17:40 UTC, jreback commented
thanks @anntzer