CLN: Move rolling helper functions to where they are used
pandas-dev/pandas pull request #34269
Opened 2020-05-20 05:39 UTC by mroeschke

- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Added some docstrings as well

2020-05-20 10:42 UTC, MarcoGorelli commented on pandas/core/window/rolling.py
> +    Calculates an offset necessary to have the window label to be centered
Sorry to be pedantic :) But should this follow the docstring guide?

> The short summary must start with a capital letter, **end with a dot**, and fit in a single line. It needs to express what the object does without providing details. For functions and methods, the short summary must **start with an infinitive verb**.

same for the `calculate_min_periods` docstring

2020-05-20 14:08 UTC, jreback requested changes
lgtm. happy to have you de-privatize things if needed (e.g. get_center_of_mass) and/or improve doc-strings. just give a quick pass if you can. ping on green.

2020-05-21 16:08 UTC, WillAyd approved these changes

2020-05-21 16:09 UTC, merged

2020-05-21 16:09 UTC, WillAyd commented
Thanks @mroeschke