Added missing import in boxplot_frame_groupby example
pandas-dev/pandas pull request #34343
Opened 2020-05-23 16:05 UTC by gsyqax

- [X] closes #28903 
- [ ] tests added / passed
- [X] passes `black pandas`
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-05-23 16:15 UTC, MarcoGorelli commented
Thanks @gsyqax - did you build this page of the documentation locally to check it works?

2020-05-23 17:07 UTC, gsyqax commented
@MarcoGorelli yes, it is working.

I noticed the example also makes use of 'pd' and 'np' alias without importing and aliasing pandas and numpy. I don't think this can lead to confusing, but do you think I should also add those imports?

2020-05-23 17:12 UTC, MarcoGorelli commented
That's OK, it fits with the [docstring guide](https://pandas.pydata.org/docs/development/contributing_docstring.html)

> Import required libraries (except numpy and pandas)

2020-05-23 17:14 UTC, MarcoGorelli commented
> @MarcoGorelli yes, it is working.

I just tried building it with your changes and I don't see any plot though, do you?

2020-05-23 18:09 UTC, gsyqax commented
I'm not seeing any plots either. I thought a plot was not needed since the current version is not showing any either.

I will add the plots and commit again

2020-05-23 20:06 UTC, pep8speaks commented
Hello @gsyqax! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/plotting/_core.py`](https://github.com/pandas-dev/pandas/blob/855448d3ba4b45c64cb366a3a2c22de586d3e60e/pandas/plotting/_core.py):

> [Line 554:1](https://github.com/pandas-dev/pandas/blob/855448d3ba4b45c64cb366a3a2c22de586d3e60e/pandas/plotting/_core.py#L554): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2020-05-23 20:09 UTC, gsyqax commented
@MarcoGorelli I added some plots and made a few minor changes to make everything clearer, hope it's OK. Also removed whitespace as indicated by pep8speaks.

2020-05-24 09:49 UTC, MarcoGorelli requested changes
Nice! Thanks, just tried running it and it looks good. Can you just add a space between the two examples, as suggested below?

2020-05-24 09:49 UTC, MarcoGorelli commented on pandas/plotting/_core.py
> +        The ``subplots=False`` option shows the boxplots in a single figure.
```suggestion

    The ``subplots=False`` option shows the boxplots in a single figure.
```

2020-05-24 09:52 UTC, MarcoGorelli commented
Also, I don't think a whatsnew note is necessary for documentation improvements, could you please revert that change?

2020-05-24 12:30 UTC, MarcoGorelli approved these changes
LGTM

have opened #34353 as I'm not sure what to do about the subplots being too close (but it would warrant a separate PR anyway, I don't think there'd be any need to change that here)

2020-05-24 13:04 UTC, gsyqax commented
Great! Many thanks @MarcoGorelli for all the help, really appreciate it!

2020-05-25 16:17 UTC, jreback commented
cc @datapythonista @jorisvandenbossche @WillAyd

2020-05-25 16:49 UTC, charlesdong1991 commented
try `boxplot_frame_groupby(grouped, rot=45, fontsize=12, figsize=(8, 10))` for instance? @gsyqax 

it will avoid having overlapped subplots and make doc look better

2020-05-26 07:04 UTC, jorisvandenbossche reviewed
IMO we should not advertise `boxplot_frame_groupby` like that directly, but rather as `df.groupby(..).boxplot(..)`

2020-05-27 04:26 UTC, WillAyd commented
Slight preference for what @jorisvandenbossche has suggested above but not a blocker so OK either way

2020-05-30 11:07 UTC, gsyqax commented
I applied the change to the plot fig size and replace boxplot_frame_groupby by df.groupby.boxplot. I'm keeping the intermediate var 'grouped' to make things easier to read

2020-06-18 14:29 UTC, TomAugspurger commented on pandas/plotting/_core.py
> +        >>> from pandas.plotting import boxplot_frame_groupby
@gsyqax can you remove this import.

2020-07-06 14:53 UTC, TomAugspurger commented on pandas/plotting/_core.py
> +        >>> from pandas.plotting import boxplot_frame_groupby
```suggestion
```

2020-07-06 23:39 UTC, jreback commented
lgtm. @TomAugspurger

2020-07-07 11:09 UTC, merged

2020-07-07 11:09 UTC, TomAugspurger commented
Thanks @gsyqax!