BUG: new method for join with multiindex and single index (#34292)
pandas-dev/pandas pull request #34368
Opened 2020-05-25 19:19 UTC by CuylenE

- [x] closes #34292
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Tests still to be added.
I replaced the method to join a multiindex & a single index because outer joins didn't include data from the single index. The new method is similar to a join between 2 multiindexes.
I'm not sure what the keep_order parameter was, but it was never used and in other _join-methods it didn't exist either. So I suggest removing it all together.

2020-05-25 19:20 UTC, pep8speaks commented
Hello @CuylenE! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/indexes/base.py`](https://github.com/pandas-dev/pandas/blob/3e6592fcc509498dd92d86a85e323e8bbc605404/pandas/core/indexes/base.py):

> [Line 3645:13](https://github.com/pandas-dev/pandas/blob/3e6592fcc509498dd92d86a85e323e8bbc605404/pandas/core/indexes/base.py#L3645): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 3655:89](https://github.com/pandas-dev/pandas/blob/3e6592fcc509498dd92d86a85e323e8bbc605404/pandas/core/indexes/base.py#L3655): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 88 characters)
> [Line 3668:17](https://github.com/pandas-dev/pandas/blob/3e6592fcc509498dd92d86a85e323e8bbc605404/pandas/core/indexes/base.py#L3668): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 3668:89](https://github.com/pandas-dev/pandas/blob/3e6592fcc509498dd92d86a85e323e8bbc605404/pandas/core/indexes/base.py#L3668): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 88 characters)

2020-05-25 20:54 UTC, jreback requested changes
please always add test first

2020-05-25 22:58 UTC, CuylenE commented
> please always add test first
Test added. Though I'm not sure why non-related test are failing.

2020-10-31 21:41 UTC, arw2019 reviewed
@CuylenE are you interested in picking this back up? If yes merge master, resolve the conflicts  and we can take it from there

2020-11-29 04:47 UTC, arw2019 commented
Closing for now as stale. @CuylenE ping us if you'd like to pick this up and we'll reopen

2020-11-29 04:47 UTC, closed without merging