BUG: pd.DataFrame.transform recursively loops in some cases #34224
pandas-dev/pandas pull request #34377
Opened 2020-05-26 02:02 UTC by pedrooa

- [x] closes #xxxx
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Error handling within try/except in aggregate function of frame.py file

2020-05-26 13:24 UTC, jreback requested changes
can you add the test which hits this

2020-05-27 14:29 UTC, pedrooa commented
> can you add the test which hits this

Sure! Do You mean singling out a test that already exists and hits this, or creating a new test for this case?

2020-05-27 20:54 UTC, dsaxton commented
> Sure! Do You mean singling out a test that already exists and hits this, or creating a new test for this case?

You'll want to create a new test for a case that was raising the RecursionError before, but now raises a more appropriate error / message. You could use the example from the original issue.

2020-05-27 23:32 UTC, pep8speaks commented
Hello @pedrooa! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/series/test_apply.py`](https://github.com/pandas-dev/pandas/blob/89d7384df8440a0f628b1d04dc6b3c3e51416f34/pandas/tests/series/test_apply.py):

> [Line 45:9](https://github.com/pandas-dev/pandas/blob/89d7384df8440a0f628b1d04dc6b3c3e51416f34/pandas/tests/series/test_apply.py#L45): [E704](https://duckduckgo.com/?q=pep8%20E704) multiple statements on one line (def)
> [Line 59:9](https://github.com/pandas-dev/pandas/blob/89d7384df8440a0f628b1d04dc6b3c3e51416f34/pandas/tests/series/test_apply.py#L59): [E704](https://duckduckgo.com/?q=pep8%20E704) multiple statements on one line (def)

2020-05-28 00:05 UTC, dsaxton commented on pandas/tests/series/test_apply.py
> +            df.transform({"a": int})
Can you also include the issue number as a comment and test the new error message?

2020-06-01 01:34 UTC, jreback requested changes
looks good can u add a whats new note
reshaping bug fix for 1.1

2020-06-01 22:06 UTC, jreback approved these changes

2020-06-01 22:07 UTC, jreback commented
lgtm ping on green.

2020-06-02 22:56 UTC, jreback commented on doc/source/whatsnew/v1.1.0.rst
> +- Bug in :func:`aggregate` was causing recursive loop in some cases (:issue:`34224`)
actually this is not right, can you put `` :func:`DataFrame.aggregate` `` and `` :func:`Series.aggregate` ``.

pls ping on green.

2020-06-03 18:05 UTC, merged

2020-06-03 18:05 UTC, jreback commented
thanks @pedrooa