ENH: Set index of returned dataframe in DatetimeIndex.isocalendar
pandas-dev/pandas pull request #34392
Opened 2020-05-26 18:36 UTC by mgmarino

This is a followup on #33595, (specifically
[here](https://github.com/pandas-dev/pandas/pull/33595#issuecomment-614888200)
and
[here](https://github.com/pandas-dev/pandas/pull/33595#issuecomment-614897268)),
where it was noted that `DatetimeIndex.isocalendar` should set the index of the
returned dataframe.

2020-05-26 22:16 UTC, jreback requested changes
lgtm. can you add this PR number to the existing whatsnew note (for isocalendar change), and ping on green.

2020-05-27 05:22 UTC, mgmarino commented
@jreback, thanks, what's new entry updated.  Back to green.

2020-05-27 12:35 UTC, jreback approved these changes

2020-05-27 12:36 UTC, merged

2020-05-27 12:36 UTC, jreback commented
thanks @mgmarino

2020-05-27 12:37 UTC, jreback commented
btw I think we should a mention of using isocalendar in the docs proper, maybe around here: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#time-date-components

if you can do a PR would be great.

2020-05-27 12:47 UTC, mgmarino commented
I am very happy to expand the docs on this, but this is already a blurb on this right after this table:

https://github.com/pandas-dev/pandas/blame/master/doc/source/user_guide/timeseries.rst#L789

2020-05-27 20:42 UTC, jreback commented
ahh i c, yep forgot about that. lgtm.