BUG: Fix failing MacPython 32bit wheels for rolling groupby
pandas-dev/pandas pull request #34423
Opened 2020-05-28 04:26 UTC by mroeschke

- [x] closes #34410
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

What would be the best way to validate that this fixes the MacPython/pandas-wheels @TomAugspurger

2020-05-28 11:20 UTC, TomAugspurger commented
If you really wanted to, you could build a docker image with these changes.

```Dockerfile
FROM quay.io/pypa/manylinux1_i686:latest  # verify this is the right image.

RUN git clone --depth=1 https://github.com/mroeschke/pandas/mac32_rolling \
 && cd pandas \
 && /opt/python/cp37-cp37/bin/python -m pip install numpy cython python-dateutil pytz
WORKDIR pandas

RUN /opt/python/cp38-cp38/bin/python setup.py build_ext -i
```

We really need to get this hooked up to our CI here, but it isn't 100% straightforward.

2020-05-28 20:14 UTC, WillAyd commented
Wondering if something like this would work?

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops

2020-05-28 20:16 UTC, jreback requested changes

2020-05-28 20:16 UTC, jreback commented on pandas/core/window/indexers.py
> +            start = start.astype(np.int64)
should np.intp

2020-05-28 20:16 UTC, jreback commented on pandas/core/window/indexers.py
> +            start = start.astype(np.int64)
nvm this is ok

2020-05-28 20:16 UTC, jreback approved these changes

2020-05-28 20:24 UTC, TomAugspurger commented
> Wondering if something like this would work?

Yeah that's 100% what we need. Just integrating it into the current layout isn't straightforward.

There's also the fact that Anaconda stopped building 32-bit linux package, making this somewhat hard to test.

2020-05-28 20:54 UTC, WillAyd commented
Here's a correct Dockerfile if it helps. This is just Py37, could extend to others simply using something like this:

https://github.com/pypa/python-manylinux-demo/blob/84dc72039a0c85c1c960e024f024fd3d37387634/travis/build-wheels.sh#L18

```sh
FROM quay.io/pypa/manylinux1_i686:latest

RUN git clone -b mac32_rolling https://github.com/mroeschke/pandas.git \
 && cd pandas \
 && /opt/python/cp37-cp37m/bin/python -m pip install numpy cython python-dateutil pytz
WORKDIR pandas

RUN /opt/python/cp37-cp37m/bin/python setup.py build_ext -i -j4
```

FWIW still fails to build but I think errors are just what @TomAugspurger is fixing in #34416 

For this change in particular (being python-level only) we probably need an extra step to actually execute the tests if we wanted to verify quickly that way

2020-05-28 23:58 UTC, jreback commented
we should drop 32 bit support (for 1.1)

2020-05-29 15:51 UTC, WillAyd approved these changes

2020-05-29 15:51 UTC, WillAyd commented
I think this and the other 32 bit fixup are fine to merge if it gets the wheel building moving along @TomAugspurger

2020-05-29 19:05 UTC, merged