DOC: DataFrame.reindex improve summary and return type
pandas-dev/pandas pull request #34584
Opened 2020-06-04 22:38 UTC by gauravchandok

- [ ] closes #33888 
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-06-05 05:07 UTC, fujiaxiang requested changes

2020-06-05 05:07 UTC, fujiaxiang commented on pandas/core/generic.py
> +        DataFrame with an additional index is generated subject to customization
No `reindex` does not generate additional index for `DataFrame` or `Series`. "A new object" actually refers to a new `DataFrame` or `Series`, not a new index. Perhaps you can try the function to see it's behavior and then decide your wordings

2020-06-05 05:07 UTC, fujiaxiang commented on pandas/core/generic.py
> +        %(klass)s with 2 indices.
same as above, `reindex` does not give 2 indices

2020-06-06 20:05 UTC, pep8speaks commented
Hello @gauravchandok! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/generic.py`](https://github.com/pandas-dev/pandas/blob/b15b121163db71cbeaaabefa84557efe8eb6d54f/pandas/core/generic.py):

> [Line 4244:89](https://github.com/pandas-dev/pandas/blob/b15b121163db71cbeaaabefa84557efe8eb6d54f/pandas/core/generic.py#L4244): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (206 > 88 characters)

2020-06-09 10:49 UTC, fujiaxiang commented
While I'm reading your changes I realized there is more to this confusion than just the docstring. See #34663. The behavior of `copy` is confusing in my opinion. We probably need to address that first. 

At the moment, I don't think this PR explains its behavior accurately. Let's discuss in #34663 what the desired behavior should be first, which could be to deprecate `copy`. After that you can continue working on this PR or open a new PR to achieve that.

2020-09-16 00:59 UTC, dsaxton commented
@gauravchandok Can you merge master to fix conflicts?

2020-09-20 02:09 UTC, jreback requested changes

2020-09-20 02:09 UTC, jreback commented on pandas/core/generic.py
> +        Create an object with a new index and columns retained from %(klass)s.
this is not true, you can specify index and/or columns.

2020-09-20 02:09 UTC, jreback commented on pandas/core/generic.py
> +        The values are only retained for index that matches in %(klass)s else NA/Nan.
can you say what the intent is here?

2020-10-21 00:49 UTC, dsaxton commented
@gauravchandok Can you address comments and merge master?

2020-11-04 08:43 UTC, arw2019 commented
Closing for now. @gauravchandok ping us whenever you'd like to continue and we'll reopen!

2020-11-04 08:44 UTC, closed without merging