CLN: dont consolidate in NDFrame._is_numeric_mixed_type
pandas-dev/pandas pull request #34678
Opened 2020-06-09 21:09 UTC by jbrockmendel

2020-06-09 22:12 UTC, jreback commented
presume that these are either neutral or + on perf

2020-06-09 23:39 UTC, jbrockmendel commented
> presume that these are either neutral or + on perf

AFAICT.  The main upside is getting rid of a side-effect.

2020-06-10 07:37 UTC, jorisvandenbossche requested changes
This one will indeed not matter, as just before `_is_mixed_type` already consolidated

2020-06-10 07:37 UTC, jorisvandenbossche commented on pandas/core/generic.py
> +        return self._mgr.is_numeric_mixed_type
Since this property is only used in the function right below, I would just inline the `self._mgr.is_numeric_mixed_type` there

2020-06-10 20:38 UTC, jorisvandenbossche approved these changes

2020-06-15 16:55 UTC, jbrockmendel commented
rebased+green

2020-06-15 17:28 UTC, merged