CLN: dont consolidate in indexing
pandas-dev/pandas pull request #34679
Opened 2020-06-09 21:14 UTC by jbrockmendel

2020-06-10 07:44 UTC, jorisvandenbossche requested changes

2020-06-10 07:44 UTC, jorisvandenbossche commented on pandas/core/indexing.py
> -                    ser._consolidate_inplace()
this one is a no-op since `ser` is a series (I think?), so can easily be removed

2020-06-10 07:44 UTC, jorisvandenbossche commented on pandas/core/indexing.py
> -            self.obj._consolidate_inplace()
Removing this one will need a performance check, IMO, and also has potential API changes that might need investigation

2020-06-21 16:34 UTC, jbrockmendel commented
reverted the non-consensus edit

2020-06-26 20:34 UTC, jbrockmendel commented
gentle ping.  This is now just the 1-line edit

2020-06-26 23:59 UTC, merged

2020-06-26 23:59 UTC, jreback commented
lgtm