DOC: updated files for SS06 errors
pandas-dev/pandas pull request #34739
Opened 2020-06-13 02:46 UTC by willpeppo

2020-06-13 17:09 UTC, WillAyd requested changes

2020-06-13 17:09 UTC, WillAyd commented on pandas/core/indexes/multi.py
> -        Return vector of label values for requested level,
I think should keep the extra information here and in the other docstrings rather than just removing.

2020-06-29 21:43 UTC, WillAyd commented
@willpeppo can you fix merge conflict and address comments?

2020-07-08 16:13 UTC, WillAyd commented
@willpeppo still active?

2020-07-08 18:17 UTC, willpeppo commented
Yes sorry.  Will get back going on documentation shortly.   I’d like to be an ongoing contributor.  Sorry!

2020-07-24 12:38 UTC, simonjayhawkins commented
@willpeppo Thanks for the PR. closing as stale for now. LMK when you are ready to continue and i'll reopen.

2020-07-24 12:38 UTC, closed without merging