add test
pandas-dev/pandas pull request #34906
Opened 2020-06-20 15:40 UTC by vivikelapoutre

- [ ] closes #26321 
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-06-20 15:42 UTC, vivikelapoutre commented
Given that this is my first commit to pandas, I'm not quite sure whether what I'm doing is what is expected. I just added the example from the bugreport as a test, is that ok? Should additional things be tested? Tested differently? Please, let me know.

2020-06-20 20:02 UTC, jreback requested changes
this needs to go with other min tests, put in test_function.py but find a similar test.

2020-06-20 20:02 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +        df.groupby("b")["c"].min(),
pls use 

result=
expected=

2020-06-20 20:02 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +        check_index_type=False,
if you have to set check_index_type or check_names the something is wrong with the expected here.

2020-06-20 20:02 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +    df = pd.DataFrame(
pls simplify this construction, e.g. directly construct the nputs

2020-06-27 20:52 UTC, vivikelapoutre commented
I addressed the comments, could you please have a look again?

2020-06-30 19:45 UTC, vivikelapoutre commented
I don't know why there suddenly are test failures, the particular test that failed (pandas/tests/base/test_unique.py::test_unique_bad_unicode), passes on my setup and is nowhere near the test that I added.

2020-07-06 16:16 UTC, TomAugspurger commented
@vivikelapoutre can you try merging master & repushing to see if that fixes it?

2020-07-08 08:13 UTC, vivikelapoutre commented
> 
> 
> @vivikelapoutre can you try merging master & repushing to see if that fixes it?

Thank you, that worked indeed.

2020-07-16 16:08 UTC, merged

2020-07-16 16:09 UTC, TomAugspurger commented
Thanks @vivikelapoutre!