TST: regression tests for indexing sparse dataframe with iterable
pandas-dev/pandas pull request #34908
Opened 2020-06-20 16:04 UTC by suvayu

- [x] closes #34526
- [ ] 2 tests added / 1 passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

This PR adds regression tests for #34526 and #34540, the second set of tests will fail until the indexing with iterable issue is fixed.

2020-06-20 16:11 UTC, jreback requested changes
looks fine, can you create a test_sparse.py (in this directory) and move other sparse indexing tests as well (e.g. the one right above, maybe more)

2020-06-20 16:11 UTC, jreback commented on pandas/tests/frame/indexing/test_indexing.py
> +        result_t = df.loc[itr_idx].dtypes.values
can you can re-use result, expected

2020-06-20 17:07 UTC, suvayu commented
@jreback Thanks for the review!  I'll try fix the bug in the next few days.

2020-06-24 14:28 UTC, suvayu commented
For the type inference logic, I wasn't sure which to use, `SparseArray.dtype.subtype` or the sparse values themselves (`SparseArray.sp_values`).  I went with the former because it seemed conceptually cleaner.

2020-07-02 16:17 UTC, suvayu commented
Hi @jreback, just bringing this to your attention. I wasn't sure if you noticed it's ready for review (I used the "request review" option in the side panel).  Apologies if this is already on your list.

2020-07-07 19:59 UTC, TomAugspurger commented
@suvayu can you add a whatsnew to 1.1.0.rst in the bug fixes section?

2020-07-07 20:00 UTC, TomAugspurger approved these changes
The changes look good, just need a release note. Make sure to include references to both issues fixed.

2020-07-07 22:15 UTC, suvayu commented
Hi @TomAugspurger, I added the the whatsnew entry.  There was a merge conflict with master (another entry in the same section), so I had to force push after resolving it.

2020-07-08 11:46 UTC, TomAugspurger approved these changes

2020-07-08 11:47 UTC, merged

2020-07-08 11:47 UTC, TomAugspurger commented
Thanks @suvayu!