BUG: Avoids b' prefix for bytes in to_csv() (#9712)
pandas-dev/pandas pull request #35004
Opened 2020-06-26 04:33 UTC by sidhant007

Avoids b' prefix written for bytes in the `to_csv()` method (in accordance with this [proposal](https://github.com/pandas-dev/pandas/issues/9712#issuecomment-635803657))

Added a new optional parameter named `bytes_encoding` to allow a specific encoding scheme to be used to decode the bytes.

- [x] closes #9712
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2020-06-26 06:45 UTC, sidhant007 commented
The CI check complains on linting: 
`##[error]./pandas/core/apply.py:9:1:F401:'pandas._libs.reduction as libreduction' imported but unused`
I believe this error is not associated with this PR.

2020-06-26 15:31 UTC, WillAyd commented
We shouldn't need a new keyword for this - can you not just use the `encoding` parameter?

2020-06-26 16:27 UTC, sidhant007 commented
> We shouldn't need a new keyword for this - can you not just use the `encoding` parameter?

So, I had tried to get the csv writer behaviour changed in Python itself can see [this ](https://bugs.python.org/issue40762) discussion on the bpo issue tracker. Some of the maintainers there raised a very valid point ([here](https://bugs.python.org/issue40762#msg370043)) of how there can be potential data-loss((mojibake) in-cases when the bytes to be written have been collected from an unknown source that uses a different encoding scheme compared to the encoding scheme with which the csv file is opened. 

For most cases I do agree that `encoding` parameter will just work, that is why I proposed the `bytes_encoding` to be an optional additional parameter, which if not passed takes the value of what the `encoding` parameter is.

2020-06-26 16:32 UTC, WillAyd commented
I personally agree with what the Python devs said - the current behavior isn't all that terrible or may an error should be raised. If neither of those, then at the very least `encoding` could be used, but definitely a new keyword here is confusing

2020-06-29 14:21 UTC, pep8speaks commented
Hello @sidhant007! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`pandas/tests/frame/test_to_csv.py`](https://github.com/pandas-dev/pandas/blob/636a9158e4c8e256be2871b08a4b041443f34704/pandas/tests/frame/test_to_csv.py):

> [Line 772:89](https://github.com/pandas-dev/pandas/blob/636a9158e4c8e256be2871b08a4b041443f34704/pandas/tests/frame/test_to_csv.py#L772): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (118 > 88 characters)

2020-06-29 14:25 UTC, sidhant007 commented
> I personally agree with what the Python devs said - the current behavior isn't all that terrible or may an error should be raised. If neither of those, then at the very least `encoding` could be used, but definitely a new keyword here is confusing

If you look at the issue (#9712) there seems to be a consensus that the current behavior is indeed a bug ([here](https://github.com/pandas-dev/pandas/issues/9712#issuecomment-235591968)) and the participants on that discussion ( showed more interest in getting it fixed rather than raising an exception. 

I understand your point of view that the new keyword can cause confusion. Accordingly I have updated my PR removing the `bytes_encoding` additional parameter and using the `encoding` parameter provided instead.

2020-06-29 16:15 UTC, WillAyd commented
For some perspective that comment is 4 years old and came at at time when we still had Python2 compat, so probably needs to be reconsidered. I am -1 on doing this and think we should match the stdlib, but @TomAugspurger might have other thoughts

2020-06-29 16:20 UTC, TomAugspurger commented
I wasn't aware of the stdlib's behavior here, so feel free to ignore my opinion.

2020-07-02 05:57 UTC, jzwinck commented
@WillAyd @TomAugspurger 

The stdlib csv behavior is not useful for users.  It does satisfy some sort of conceptual purity, but as we know Pandas is not so constrained.  We should make `pd.to_csv()` useful for users, not beholden to an ideal of encodings that many real programs won't achieve (and sometimes can't, because they'd run out of memory due to the 4x overhead of unicode in Python on Linux).

If you look at comments from users about this topic, nobody says they prefer the `b'` prefix in their CSV output as a user.  The only people who prefer it are developers.

A lot of data comes into Pandas from outside of Python, and `to_csv()` is one of the most popular ways to get data out.  No other program understands the `b'` prefixes, so this breaks the main use case.  And a lot of data also arrives via NumPy, where `'S'` still means bytes, even in Python 3.

2020-07-02 10:20 UTC, jreback commented
i’m raising an error we if detect bytes 

transcoding bytes to text seems slightly suspect here; sure it’s convenient but this deliberately bypassing the clear difference between bytes and strings; we and python are very strict about this so relaxing it is -1

2020-07-02 10:21 UTC, jreback requested changes
needs discussion; impl is adding a lot of pure tech debt

2020-07-02 11:03 UTC, jzwinck commented
@jreback I don't think this would be "bypassing the clear difference between bytes and strings", rather the initial proposal was to have an explicit parameter to control the encoding of bytes into strings.  Would you like that version back again?  The one where `bytes_encoding` is a separate parameter?  It certainly doesn't let anyone bypass anything, it is just a more performant way of decoding all the bytes instead of doing it column-by-column and maybe running out of memory along the way.

2020-07-02 11:15 UTC, jreback commented
@jzwinck i appreciate your point but what is so hard about .decode()

that is the canonical way to do this (and is clear this is an exceptional case)

2020-07-02 14:04 UTC, jzwinck commented
@jreback Would you prefer a solution where `to_csv()` on `bytes` raises an error and tells the user to first invoke some helper function (which we could add if it doesn't already exist) to create a copy of their DataFrame with all bytes converted to unicode so they can call `to_csv()` on that?  This would consume >100% extra memory compared with the solution currently in this PR, but at least it could be convenient.

2020-07-02 14:31 UTC, jreback commented
i don’t think we need to provide a helper function at all

just raise an error

2020-07-06 18:03 UTC, WillAyd commented
@sidhant007 can you update this PR to raise instead?

2020-07-08 01:00 UTC, sidhant007 commented
@WillAyd I dont agree with the approach of raising an error and am thus closing this PR. I willl remain open to discuss other suggestions/ideas on how to tackle this issue.

2020-07-08 01:00 UTC, closed without merging