Issue34731 1
pandas-dev/pandas pull request #35003
Opened 2020-06-26 03:30 UTC by pizzathief

- [ x] closes #34731 
- [x ] tests added / passed
- [ X] passes `black pandas`
- [ x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ x] whatsnew entry

2020-06-26 05:25 UTC, pizzathief commented
> Linting .py code
> 16
> ##[error]./pandas/core/apply.py:9:1:F401:'pandas._libs.reduction as libreduction' imported but unused
> 

should I remove this line as part of this PR? "libreduction" isn't mentioned anywhere else in the file pandas/core/apply.py , but on the other hand, its out of scope

2020-06-26 15:35 UTC, WillAyd commented
Can you merge master to fix CI issue?

2020-06-27 00:23 UTC, dsaxton commented on pandas/tests/reshape/test_melt.py
> +        with warnings.catch_warnings(record=True) as w:
Can you use tm.assert_produces_warning here (e.g., as in L580 of this file)?

2020-06-29 21:23 UTC, WillAyd requested changes

2020-06-29 21:23 UTC, WillAyd commented on pandas/core/reshape/melt.py
> +            'The value column name "%s" conflicts with an existing '
Can you use f-string syntax? We don't use the Py2 syntax any more

2020-06-29 21:23 UTC, WillAyd commented on pandas/core/reshape/melt.py
> +            DeprecationWarning,
Can you change this to a FutureWarning?

2020-06-29 21:23 UTC, WillAyd commented on doc/source/whatsnew/v1.1.0.rst
> +- Issue warning if value column name already exists when using :meth:`DataFrame.melt` (:issue:`34731`)
Can you move this to the Deprecations section?

2020-06-29 21:23 UTC, WillAyd commented on pandas/core/reshape/melt.py
> +            "column in the dataframe." % (value_name),
Generally we want to give users insight as to what they need to do before the deprecated behavior gets changed - can you try to clarify the message a bit?

2020-06-30 12:58 UTC, jreback requested changes

2020-06-30 12:58 UTC, jreback commented on doc/source/whatsnew/v1.1.0.rst
> +- Issue warning if value column name already exists when using :meth:`DataFrame.melt` (:issue:`34731`)
can you start with `DataFrame.melt` (like the other notes above), and also say that this is deprecated and removed in future version.

2020-06-30 12:58 UTC, jreback commented on pandas/core/reshape/melt.py
> +            "This dataframe has a column name that matches the value column "
put `value` in single quotes as this is an argument that the user passed. (and this should be `value_name`)

2020-06-30 12:58 UTC, jreback commented on pandas/core/reshape/melt.py
> +            f'name of the resultant melted dataframe (That being "{value_name})". '
resultant -> resuling DataFrame. you don't need the parenthesized expression.

2020-06-30 12:58 UTC, jreback commented on pandas/core/reshape/melt.py
> +            "In the future this will raise an error, please set the value_name "
`value_name` in single quotes

2020-06-30 12:58 UTC, jreback commented on pandas/tests/reshape/test_melt.py
> +            dfm = df.melt(id_vars="value")  # noqa F841
can you create an expected value and use assert_frame_equal

also instead of dfm, call this result.

2020-07-02 15:26 UTC, jreback approved these changes

2020-07-02 15:26 UTC, merged

2020-07-02 15:26 UTC, jreback commented
thanks @pizzathief

2022-10-29 01:44 UTC, jbrockmendel commented
@pizzathief want to make a PR to enforce this deprecation?

2022-11-02 10:30 UTC, samukweku commented on pandas/core/reshape/melt.py
> +            "name of the resultiing Dataframe. "
the spelling here should be `resulting`, not `resultiing`