Fix Issue #34923: Inferred dtype at the end of df explode method
pandas-dev/pandas pull request #35011
Opened 2020-06-26 11:51 UTC by SanthoshBala18

- [ ] closes #34923 
- [ ] tests added / passed
          pandas/tests/series/methods/test_explode.py, method test_inferred_dtype
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-06-26 11:52 UTC, pep8speaks commented
Hello @SanthoshBala18! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/series/methods/test_explode.py`](https://github.com/pandas-dev/pandas/blob/0208993255b3fd61309457023254ad56352ddace/pandas/tests/series/methods/test_explode.py):

> [Line 124:21](https://github.com/pandas-dev/pandas/blob/0208993255b3fd61309457023254ad56352ddace/pandas/tests/series/methods/test_explode.py#L124): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 124:26](https://github.com/pandas-dev/pandas/blob/0208993255b3fd61309457023254ad56352ddace/pandas/tests/series/methods/test_explode.py#L124): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 125:27](https://github.com/pandas-dev/pandas/blob/0208993255b3fd61309457023254ad56352ddace/pandas/tests/series/methods/test_explode.py#L125): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 125:30](https://github.com/pandas-dev/pandas/blob/0208993255b3fd61309457023254ad56352ddace/pandas/tests/series/methods/test_explode.py#L125): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 125:32](https://github.com/pandas-dev/pandas/blob/0208993255b3fd61309457023254ad56352ddace/pandas/tests/series/methods/test_explode.py#L125): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 125:34](https://github.com/pandas-dev/pandas/blob/0208993255b3fd61309457023254ad56352ddace/pandas/tests/series/methods/test_explode.py#L125): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 125:42](https://github.com/pandas-dev/pandas/blob/0208993255b3fd61309457023254ad56352ddace/pandas/tests/series/methods/test_explode.py#L125): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 128:50](https://github.com/pandas-dev/pandas/blob/0208993255b3fd61309457023254ad56352ddace/pandas/tests/series/methods/test_explode.py#L128): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2020-06-26 12:31 UTC, jreback requested changes

2020-06-26 12:31 UTC, jreback commented on doc/source/whatsnew/v1.1.0.rst
> +- :meth:'DataFrame.explode' can now infer dtypes (:issue:`34923`)
this goes in api breaking changes, can you expand on this slightly.

2020-06-26 12:31 UTC, jreback commented on pandas/tests/series/methods/test_explode.py
> +    result = s. explode()
remove this space

2020-06-26 12:31 UTC, jreback commented on pandas/tests/series/methods/test_explode.py
> +    s = pd.Series([1, None, 3])
add the issue number here

2020-06-26 12:31 UTC, jreback commented on pandas/tests/series/methods/test_explode.py
> +    expected = np.array([np.dtype('float64'), np.dtype('int64')])
always use `assert_frame_equal`, numpy loses types

2020-06-26 12:31 UTC, jreback commented
you may need to update the example in the docs as well

2020-07-17 10:43 UTC, jreback requested changes
lgtm pls merge master and ping on green

2020-07-17 10:43 UTC, jreback commented on doc/source/whatsnew/v1.1.0.rst
> +
use an ipython block, so it runs the code for this part

2020-07-17 13:01 UTC, SanthoshBala18 commented
@jreback, merged the master branch..

2020-07-17 13:02 UTC, jreback commented on doc/source/whatsnew/v1.1.0.rst
> +
you also need to remove the i python prompts 

they are added automatically

2020-07-20 06:25 UTC, SanthoshBala18 commented
@jreback Can we restart the checks.?

2020-07-20 14:17 UTC, simonjayhawkins commented
I'm -1 on this. This is a breaking change and not a bug.

the change for lists of ints with some rows containing empty lists now being cast to float should wait till a major release and maybe use the nullable integer type instead.

current
```
>>> pd.__version__
'1.1.0rc0'
>>>
>>> s = pd.Series([[1, 2, 3, 4], [], [5, 6, 7]])
>>> s
0    [1, 2, 3, 4]
1              []
2       [5, 6, 7]
dtype: object
>>>
>>> res = s.explode()
>>> res
0      1
0      2
0      3
0      4
1    NaN
2      5
2      6
2      7
dtype: object
>>>
>>> type(res.iloc[1])
<class 'int'>
>>>
```

this PR
```
>>> pd.__version__
'1.1.0rc0+13.gf6144512d'
>>>
>>> s = pd.Series([[1, 2, 3, 4], [], [5, 6, 7]])
>>> s
0    [1, 2, 3, 4]
1              []
2       [5, 6, 7]
dtype: object
>>>
>>> res = s.explode()
>>> res
0    1.0
0    2.0
0    3.0
0    4.0
1    NaN
2    5.0
2    6.0
2    7.0
dtype: float64
>>>
>>> type(res.iloc[1])
<class 'numpy.float64'>
>>>

```

2020-11-26 18:58 UTC, jreback commented
closing this. see my comments on the issue (basically need to add an option `downcast=` instead here.

2020-11-26 18:58 UTC, closed without merging