BUG: fix read_excel error for header=None and index_col as list #31783
pandas-dev/pandas pull request #35035
Opened 2020-06-27 21:11 UTC by rjfs

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-06-29 16:09 UTC, WillAyd requested changes
Change looks good - minor issue on the test. Can you also add a whatsnew note for v1.1?

2020-06-29 16:09 UTC, WillAyd commented on pandas/tests/io/excel/test_readers.py
> +    def test_no_header_with_list_index_col(self, engine):
Can you parametrize this with the `read_ext` fixture and change the extension rather than only testing .xlsx?

2020-06-29 23:17 UTC, jreback requested changes
also can you add a note in bug fixes for 1.1 I/O section

2020-07-08 16:03 UTC, WillAyd reviewed
minor cleanup of unused parametrization otherwise lgtm

2020-07-08 16:03 UTC, WillAyd commented on pandas/tests/io/excel/test_readers.py
> +    def test_no_header_with_list_index_col(self, engine, read_ext):
```suggestion
    def test_no_header_with_list_index_col(self, read_ext):
```

2020-07-08 17:48 UTC, WillAyd commented
/azp run

2020-07-10 12:34 UTC, jreback requested changes
looks good. ping on green.

2020-07-10 12:34 UTC, jreback commented on doc/source/whatsnew/v1.1.0.rst
> +- Bug in :meth:`read_excel` that was raising a TypeError when header=None and index_col given as list (:issue:`31783`)
use double backticks on `TypeError`, also around `header=None` and `index_col`

2020-07-10 13:45 UTC, rjfs commented
Thanks for the review guys. Should be fine now @jreback

2020-07-10 13:53 UTC, jreback approved these changes

2020-07-10 13:53 UTC, merged

2020-07-10 13:54 UTC, jreback commented
thanks @rjfs