Sql get schema index
pandas-dev/pandas pull request #35063
Opened 2020-06-30 18:04 UTC by VirosaLi

- [ ] closes #9084
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-07-02 14:59 UTC, jreback requested changes
lgtm, can you add a whatsnew note in Other Enhancements for 1.1.

`get_schema` is meant to be user-facing?

2020-07-06 14:34 UTC, TomAugspurger commented on pandas/io/sql.py
> +         New in version 1.1.0.
```suggestion

        .. versionadded:: 1.1.0
```

2020-07-06 14:34 UTC, TomAugspurger commented on doc/source/whatsnew/v1.1.0.rst
> +- :meth:`~pandas.io.sql.get_schema` now accepts `index` parameter to include index of the DataFrame in the schema (:issue:`9084`).
This isn't in our API documentation. Can you add it to `doc/source/reference/io.rst` under the SQL section?

2020-07-06 15:56 UTC, TomAugspurger commented on doc/source/reference/io.rst
> +.. currentmodule:: pandas.io.sql
I think just do `sql.get_schema` in the block above. This shouldn't need its own section.

2020-07-06 15:57 UTC, TomAugspurger commented on doc/source/whatsnew/v1.1.0.rst
> -- :meth:`~pandas.io.sql.get_schema` now accepts `index` parameter to include index of the DataFrame in the schema (:issue:`9084`).
We still want the release note.

2020-07-06 16:46 UTC, TomAugspurger approved these changes

2020-07-06 17:47 UTC, TomAugspurger commented
Sorry, a couple issues with the docstring: https://github.com/pandas-dev/pandas/pull/35063/checks?check_run_id=842449220#step:10:9. Do you have time to fix those here? `python scripts/validate_docstring.py pandas.io.sql.get_schema` should print all the issues.

2020-07-06 17:57 UTC, jorisvandenbossche commented
> get_schema is meant to be user-facing?

That's not entirely clear, see https://github.com/pandas-dev/pandas/issues/9960

2020-07-07 14:36 UTC, TomAugspurger commented
I think we should just consider it public and document it as is.

2020-09-16 18:29 UTC, dsaxton commented
@VirosaLi From the above looks like this might be ready to go? Maybe merge master again?

2020-09-26 18:17 UTC, dsaxton commented on doc/source/whatsnew/v1.2.0.rst
> +- :meth:``~pandas.io.sql.get_schema`` now accepts ``index`` parameter to include index of the DataFrame in the schema (:issue:`9084`).
```suggestion
- :meth:`~pandas.io.sql.get_schema` now accepts ``index`` parameter to include index of the DataFrame in the schema (:issue:`9084`).
```

2020-12-08 03:12 UTC, pep8speaks commented
Hello @fangchenli! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/io/sql.py`](https://github.com/pandas-dev/pandas/blob/3a02222496f464ed42f2943eaa603402f1a2c4eb/pandas/io/sql.py):

> [Line 1865:89](https://github.com/pandas-dev/pandas/blob/3a02222496f464ed42f2943eaa603402f1a2c4eb/pandas/io/sql.py#L1865): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 88 characters)

2021-01-27 01:53 UTC, alimcmaster1 commented
@fangchenli - still interested in working on this or shall we close?

2021-02-11 01:33 UTC, jreback commented
closing as stale. if you want to continue, pls ping and can re-open.

2021-02-11 01:33 UTC, closed without merging