Fix regression on datetime in MultiIndex
pandas-dev/pandas pull request #35140
Opened 2020-07-06 14:27 UTC by Dr-Irv

- [x] closes #35015
- [x] tests added / passed
  - `tests.indexing.multiindex.test_datetime:test_multiindex_datetime_columns`
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry
   - Not needed - this was a regression

2020-07-06 19:07 UTC, WillAyd commented
/azp run

2020-07-06 21:15 UTC, WillAyd commented
@jbrockmendel this is what you had in mind right?

2020-07-06 21:31 UTC, jbrockmendel commented
Yes

2020-07-06 22:41 UTC, jreback requested changes
can you add a whatsnew, bug fixes 1.1 in conversion section, patch looks good, some comments

2020-07-06 22:41 UTC, jreback commented on pandas/tests/indexing/multiindex/test_datetime.py
> +    assert list(df.columns.names) == ["a", "b"]
can you construct the expected dataframe and use assert_frame_equal?

2020-07-06 22:41 UTC, jreback commented on pandas/core/indexing.py
> +            except InvalidIndexError:
can you add a comment here about why this is

2020-07-07 13:35 UTC, Dr-Irv commented
> can you add a whatsnew, bug fixes 1.1 in conversion section, patch looks good, some comments

@jreback I'm not going to add a whatsnew, as this was NOT a bug in 1.0.5, but was introduced during the development of 1.1 .  I will do the other things.

2020-07-07 14:52 UTC, TomAugspurger approved these changes

2020-07-08 12:43 UTC, jreback commented
> > can you add a whatsnew, bug fixes 1.1 in conversion section, patch looks good, some comments
> 
> @jreback I'm not going to add a whatsnew, as this was NOT a bug in 1.0.5, but was introduced during the development of 1.1 . I will do the other things.

thanks

2020-07-08 12:43 UTC, jreback approved these changes

2020-07-08 12:43 UTC, merged