PERF: Allow str.split callers to skip expensive post-processing
pandas-dev/pandas pull request #35223
Opened 2020-07-10 23:42 UTC by wbadart

Hey team-

I've got some string processing in my pipeline and have noticed that `Series.str.split` is a pretty significant bottleneck:

<img width="806" alt="Screen Shot 2020-07-09 at 18 03 09" src="https://user-images.githubusercontent.com/8717474/87210555-cd31d980-c2ca-11ea-8c79-e247b236cc0d.png">

(For reference, the rest of the function calls from this `pyinstrument` run take 5-10 seconds.)

It seemed odd to me that it was spending more time post-processing the result (`_wrap_result`) than actually doing the work of splitting strings, so I looked into it. It turns out that when you use `expand=True`, `_wrap_result` makes three full passes over the data (in Python iteration land!). From what I gather, the procedure is to make sure that each row of the resulting data frame ends up with the same number of columns. However, for my use case, I happen to know ahead of time that this will be true; my Series is full of well-formed IPv4 addresses (and from what I gather online, this is a pretty common use of `Series.str.split`), so I know each split string list will be 4 elements long (one for each octet).

This pull request offers an escape hatch for users like me who know that this expensive post-processing step is essentially a no-op, in the form of the `pad_sequences` argument. If `True`, the default, then the original procedure will be run. If `False`, it will be skipped in favor of simply casting the result from a numpy array of lists to a list of lists, to be crammed into a DataFrame a few lines down. It's up to the caller to determine ahead of time if the split will produce uniform-length sequences. (If `expand=False`, then `pad_sequences` has no effect.)

Looking forward to hearing your thoughts!

Many thanks

---

- Related to #10090

- ~[ ] closes #xxxx~
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-07-10 23:44 UTC, wbadart commented
Just need a minute to write up a whatsnew entry

2020-07-10 23:56 UTC, jreback requested changes
its going to be easier to get this accepted to simply optimize this.

2020-07-11 00:00 UTC, jreback commented on pandas/core/strings.py
> -            def cons_row(x):
you could just write a short cython routine which does all of this

2020-07-11 00:07 UTC, jreback commented
we already have some benchmarks for this, so should be easy to tell a good change.

2020-07-24 11:54 UTC, simonjayhawkins commented
@wbadart can you address comments?

2020-07-27 21:56 UTC, wbadart commented
Sure, I can take a whack at it. I'm a bit of a cython n00b, so I can't promise I'll be particularly speedy, but if you have any recommended docs or tutorials, that'd be a big help.

2020-09-30 15:45 UTC, WillAyd commented
@wbadart is this still active?

2020-09-30 21:13 UTC, wbadart commented
We can close this out; I haven't had the bandwidth to tackle it and probably won't soon :/

2020-09-30 21:13 UTC, closed without merging

2021-08-30 22:00 UTC, w-m commented
This [stackoverflow answer](https://stackoverflow.com/a/68990278/463796) highlights a performance issue that is likely related. In the example data, there are rows of strings separated by commas with a varying number of elements. str.split with `expand=True` is about 2x slower than str.split with `expand=False` followed by `to_list()` and creating a new DataFrame from the results:

```
df = pd.DataFrame(["a", "a,b", "a,b,c"] * 100000, columns=["steps"])

%timeit res = df.steps.str.split(",", expand=True)
249 ms ± 12.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%timeit res2 = pd.DataFrame(df.steps.str.split(",").to_list())
128 ms ± 1.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


```