BUG: Inconsistent behavior in Index.difference
pandas-dev/pandas pull request #35231
Opened 2020-07-11 13:23 UTC by simonjayhawkins

- [ ] closes #35217
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-07-13 11:08 UTC, jorisvandenbossche reviewed
Generally this looks good to me. 

But can you check how well Float64Index `equals` is covered in the tests? 
For example, you added an assert that floats and strings are not equal, but if we preserve behaviour, we should ensure that float / ints and float / object ints keep evaluating to True:

```
In [18]: pd.Index([1, 2]).equals(pd.Index([1., 2.])) 
Out[18]: True

In [20]: pd.Index([1, 2]).equals(pd.Index([1., 2.], dtype=object)) 
Out[20]: True
```

(both of those will work fine as well with the new implementaiton, I think (since array_equivalent right now doesn't check the exact dtype for those, only equality), but just want to ensure it is tested)

2020-07-13 11:51 UTC, simonjayhawkins commented
Thanks @jorisvandenbossche for reviewing this. have extended an existing test

2020-07-13 16:46 UTC, jreback requested changes

2020-07-13 16:46 UTC, jreback commented on pandas/tests/indexes/test_numeric.py
> +        i4 = Float64Index([1.0, np.nan])
possible to paramaterize?

2020-07-13 16:46 UTC, jreback commented on pandas/tests/indexes/test_numeric.py
> +    float_index = pd.Index([1.0, 2, 3])
ideally parameterize

2020-07-13 16:46 UTC, jreback commented on pandas/tests/indexes/test_numeric.py
> +    float_index = pd.Index([1.0, 2, 3])
same

2020-07-15 15:05 UTC, TomAugspurger commented
@simonjayhawkins are you able to update here?

2020-07-15 15:39 UTC, simonjayhawkins commented
> @simonjayhawkins are you able to update here?

i've parameterised the additional tests added in response to https://github.com/pandas-dev/pandas/pull/35231#pullrequestreview-447153446

not sure parameterise makes sense for the issue regression tests (parameterise on `order` i.e index.equals(other) and other.equals(index) or include the indexes in the parameterisation?) 

have pushed changes but not yet appearing here.

2020-07-15 16:11 UTC, simonjayhawkins commented
> have pushed changes but not yet appearing here.

The changes are now showing, but ci not running.

2020-07-15 16:40 UTC, simonjayhawkins commented
azure and travis triggered, but not github actions. will push another empty commit later if github actions doesn't run.

2020-07-15 19:06 UTC, TomAugspurger approved these changes
All green.

2020-07-15 22:23 UTC, jreback approved these changes

2020-07-15 22:23 UTC, jreback commented
lgtm. can merge on green.

2020-07-16 09:55 UTC, merged