TST: Verify filtering operations on DataFrames with categorical Series
pandas-dev/pandas pull request #35233
Opened 2020-07-11 16:20 UTC by avinashpancham

- [ x ] closes #22609
- [ x ] tests added / passed
- [ x ] passes `black pandas`
- [ x ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ x ] whatsnew entry

2020-07-13 17:26 UTC, jreback requested changes
ping on green.

2020-07-13 17:26 UTC, jreback commented on pandas/tests/dtypes/test_common.py
> +def test_categorical_filtering():
can you move this to pandas/tests/indexing/frame/test_categorcal.py

2020-07-15 19:06 UTC, TomAugspurger approved these changes
Moved.

2020-07-15 22:23 UTC, jreback approved these changes

2020-07-15 22:24 UTC, merged

2020-07-15 22:24 UTC, jreback commented
thanks @avinashpancham