PERF: array_equivalent
pandas-dev/pandas pull request #35256
Opened 2020-07-12 23:04 UTC by jbrockmendel

xref #35249, this gives about a 3x speedup in the asv reported there

cc @jorisvandenbossche EA.equals doesn't support a strict_nan arg, is there anything we need to do to account for that here?

2020-07-13 09:01 UTC, jorisvandenbossche reviewed
Thanks for looking into this!

2020-07-13 09:02 UTC, jorisvandenbossche commented
> EA.equals doesn't support a strict_nan arg, is there anything we need to do to account for that here?

Indeed, EA.equals doesn't support that (and not sure it should). But see also my inline comment: is it actually needed to handle EAs here?

2020-07-13 10:26 UTC, simonjayhawkins commented
maybe merge #35231 first since that PR adds additional tests?

2020-07-13 16:44 UTC, jreback requested changes

2020-07-13 16:44 UTC, jreback commented on pandas/core/dtypes/missing.py
> +            return (ileft == iright).all()
hmm yeah i agree here, nan's would compare not equal, this is eactly why we need the nan mask (you can use np.isnan here though)

2020-07-14 20:08 UTC, jbrockmendel commented
> maybe merge #35231 first since that PR adds additional tests?

good idea

2020-07-14 20:10 UTC, jbrockmendel commented on pandas/core/dtypes/missing.py
> +        return right.equals(left)
In the PR that removed Block.equals I thought you agreed that array_equivalent should dispatch for EAs.

I'm OK with removing this check for now; its orthogonal to the perf goal.

2020-07-14 20:12 UTC, jbrockmendel commented on pandas/core/dtypes/missing.py
>          return ((left == right) | (isna(left) & isna(right))).all()
This is a good point (two, really).  Because of the inf_as_na thing, we should probably consider it as a bugfix and address it separately

2020-07-14 20:15 UTC, jbrockmendel commented on pandas/core/dtypes/missing.py
> +            return (ileft == iright).all()
darn, fair point.  if we cant compare after int-casting, then i think we lose pretty much all of the perf gain.  closing.

2020-07-14 20:15 UTC, closed without merging