Update datetimes.py
pandas-dev/pandas pull request #35348
Opened 2020-07-20 07:18 UTC by zky001

change some issues be metioned at #35342

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-07-20 09:26 UTC, zky001 commented
![testresult_20200720172043.png](https://i.loli.net/2020/07/20/52RGWSEsKng9uav.png)
I test all the cases on my machine but there still have some errors like `pytz.exceptions.NonExistentTimeError: 1907-01-01 00:00:00`
I want to know whether should I change NonExistentTimeError detect ways.

2020-07-20 09:39 UTC, zky001 commented
I don't know weather should the time Zone of Indian/Chagos show time like `1907-01-01 00:00:00` should be droped？

2020-07-20 16:24 UTC, mroeschke requested changes
This would need a test.

Also I don't think this is an appropriate place for the fix. I imagine the bug is in `generate_range`

Could you give this PR a more informative title as well? Thanks.

2020-07-23 06:06 UTC, zky001 commented
> This would need a test.
> 
> Also I don't think this is an appropriate place for the fix. I imagine the bug is in `generate_range`
> 
> Could you give this PR a more informative title as well? Thanks.

I have make some tests and they all passed,I will let PR have  a more informative title。
![image](https://user-images.githubusercontent.com/9131265/88256275-6d392b00-cced-11ea-8d25-83f4f18b151a.png)

2020-07-24 04:29 UTC, mroeschke commented on pandas/core/arrays/datetimes.py
> +        end = Timestamp(str(end).split(' ')[0] + ' 23:59:59')
I think this fix is too specific. The bug probably lies in not checking the end bounds

2020-07-24 04:29 UTC, mroeschke commented
This PR still needs a test.

2020-09-15 08:18 UTC, simonjayhawkins commented
@zky001 can you address https://github.com/pandas-dev/pandas/pull/35348#issuecomment-663341641 and https://github.com/pandas-dev/pandas/pull/35348#pullrequestreview-454628733

2020-09-23 20:25 UTC, jbrockmendel commented
See my comment in #35342 on the appropriate fix

2020-09-26 15:45 UTC, dsaxton commented
Closing as stale, @zky001 let us know if you'd still like to work on this

2020-09-26 15:45 UTC, closed without merging