REF: implement _apply_blockwise
pandas-dev/pandas pull request #35359
Opened 2020-07-20 21:35 UTC by jbrockmendel

Preliminary pushing towards #34714

2020-08-05 02:37 UTC, jreback requested changes
I think ultimately you want to put this _apply_blockwise in a BlockwiseMixin, similar to SelectionMixin, so you can add it to groupby and so on, but suppose could be done later

2020-08-05 02:37 UTC, jreback commented on pandas/core/window/rolling.py
> +    def _apply_blockwise(self, homogeneous_func: Callable):
can you type the output

2020-08-05 02:37 UTC, jreback commented on pandas/core/window/rolling.py
> +        skipped = []
can you type these

2020-08-05 03:38 UTC, jbrockmendel commented
> I think ultimately you want to put this _apply_blockwise in a BlockwiseMixin, similar to SelectionMixin, so you can add it to groupby and so on, but suppose could be done later

I'm planning a BlockManager method that subsumes all of the apply-blockwise usages.

2020-08-05 20:23 UTC, jbrockmendel commented
@simonjayhawkins is this new/expected?

```
pandas/core/window/rolling.py:500: error: Type variable "pandas._typing.ArrayLike" is unbound
pandas/core/window/rolling.py:500: note: (Hint: Use "Generic[ArrayLike]" or "Protocol[ArrayLike]" base class to bind "ArrayLike" inside a class)
pandas/core/window/rolling.py:500: note: (Hint: Use "ArrayLike" in function signature to bind "ArrayLike" inside a function)
```

2020-08-06 13:54 UTC, simonjayhawkins commented on pandas/core/window/rolling.py
> +    def _apply_blockwise(self, homogeneous_func: Callable) -> FrameOrSeries:
```suggestion
    def _apply_blockwise(
        self, homogeneous_func: Callable[..., ArrayLike]
    ) -> FrameOrSeries:
```

will get mypy to green. (but not yet checked that the type is correct, just consistent with the variable annotation declaration in the method body)

2020-08-06 21:33 UTC, jbrockmendel commented
that worked, thanks @simonjayhawkins

2020-08-06 23:50 UTC, jreback approved these changes

2020-08-06 23:50 UTC, merged

2020-08-06 23:50 UTC, jreback commented
thanks