CLN: clarify TypeError for IndexSlice argument to pd.xs
pandas-dev/pandas pull request #35411
Opened 2020-07-25 14:20 UTC by arw2019

- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry (pending 1.2)

As per discussion in #35301 we do not support `IndexSlice` arguments to `xs`. This PR aims to clarify the `TypeError` thrown when that happens.

This doesn't close #35301: a remaining part there is new functionality for `loc`.

2020-08-03 23:34 UTC, jreback requested changes

2020-08-03 23:34 UTC, jreback commented on doc/source/whatsnew/v1.2.0.rst
> +- Bug in `DataFrame.xs` when used with `IndexSlice` raises ``TypeError`` with message `Expected label or tuple of labels` (:issue:`35301`)
can you use ``` :meth:`DataFrame.xs` ``` and same for ```IndexSlice```

2020-08-03 23:34 UTC, jreback commented on pandas/core/generic.py
> +                raise TypeError(f"Expected label or tuple of labels, got {key}")
can you add `from e` (need to add the the except as well)

2020-08-03 23:34 UTC, jreback commented on pandas/tests/test_multilevel.py
> +        # GH 35301
can you make this a new test

2020-08-06 23:34 UTC, jreback requested changes
if you can move the test; merge master and ping on green.

2020-08-06 23:34 UTC, jreback commented on pandas/tests/test_multilevel.py
> +        # GH 35301
can you move to: pandas/tests/indexing/multiindex/test_xs.py

2020-08-07 16:57 UTC, jreback approved these changes

2020-08-07 16:58 UTC, merged

2020-08-07 16:58 UTC, jreback commented
thanks @arw2019 very nice (failure is unrelated)

2020-08-07 17:16 UTC, arw2019 commented
great! thanks @jreback for reviewing