MAINT: Fix issue in StataReader due to upstream changes
pandas-dev/pandas pull request #35427
Opened 2020-07-27 10:57 UTC by bashtage

Avoid creating an array of dtypes to workaround NumPy future change

closes #35426

- [X] closes #35426
- [ ] tests added / passed
- [X] passes `black pandas`
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-07-27 11:37 UTC, simonjayhawkins approved these changes
Thanks @bashtage

2020-07-27 15:07 UTC, TomAugspurger commented
Probably no reason to do this for 1.1.0. Are you OK with waiting for 1.1.1 @simonjayhawkins?

2020-07-27 15:09 UTC, simonjayhawkins commented
> Probably no reason to do this for 1.1.0. Are you OK with waiting for 1.1.1 @simonjayhawkins?

no problem.

2020-07-29 10:02 UTC, simonjayhawkins requested changes

2020-07-29 10:02 UTC, simonjayhawkins commented on pandas/tests/window/test_ewm.py
> +    data = np.arange(10.)
IIUC you can revert this and just keep this PR scoped to the Stata change. see https://github.com/pandas-dev/pandas/issues/35426#issuecomment-665036331

2020-07-29 10:33 UTC, simonjayhawkins commented
moving milestone. The Stata tests are no longer failing with Linux py37_np_dev on master so this won't need backport.

2020-07-29 11:14 UTC, bashtage commented
Should we just close this as unneeded?  The second fix does appear to be
needed or at least a good idea since assigning Nan to an int array has a
funny smell.

On Wed, Jul 29, 2020, 11:33 Simon Hawkins <notifications@github.com> wrote:

> moving milestone. The Stata tests are no longer failing with Linux
> py37_np_dev on master so this won't need backport.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/35427#issuecomment-665585142>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABKTSRJF4NFNURKEPDR4JMDR573I7ANCNFSM4PIUO5VA>
> .
>

2020-07-29 11:21 UTC, simonjayhawkins commented
> The second fix does appear to be needed or at least a good idea since assigning Nan to an int array has a funny smell.

Thanks. I'm not sure where we are with numpy-dev. We still have 20 fails on master. not sure whether further changes in numpy will resolve these or we still have work to do.

> Should we just close this as unneeded? 

up to you.

2020-07-30 14:07 UTC, bashtage commented
@simonjayhawkins I reverted the second commit so this just a small, sensible always safe refactor.

2020-07-30 14:28 UTC, simonjayhawkins approved these changes
Thanks @bashtage

2020-08-05 20:21 UTC, jbrockmendel commented
Restarted the Travis build, LGTM pending green

2020-08-05 22:56 UTC, bashtage commented
@jbrockmendel green.

2020-08-06 12:42 UTC, merged

2020-08-06 12:43 UTC, simonjayhawkins commented
Thanks @bashtage