DOC: Document that read_hdf can use pickle
pandas-dev/pandas pull request #35554
Opened 2020-08-04 20:16 UTC by TomAugspurger

This documents that `read_hdf`, which uses PyTables, might invoke pickle to deserialize arrays that were serialize with pickle.

PyTables clearly documents this at http://www.pytables.org/usersguide/libref/declarative_classes.html#tables.ObjectAtom, but pandas users may not realize that if they aren't aware that pandas uses pytables under the hood.

I've tried to include the warning in all the methods that eventually read data, but it's a bit hard to say if I've gotten them all.

Ideally we would also like to provide an `allow_pickle=False` keyword, but that would be best implemented in PyTables, and used by us. I opened https://github.com/PyTables/PyTables/issues/813 for discussion.

2020-08-04 21:32 UTC, jreback requested changes

2020-08-04 21:32 UTC, jreback commented on doc/source/user_guide/io.rst
> +   Pandas uses PyTables for reading and writing HDF5 files, which allows
note that this only applies to fixed stores; tables do not use pickle

2020-08-04 23:11 UTC, WillAyd commented
lgtm ex Jeff's comments

2020-08-06 21:01 UTC, TomAugspurger commented
FYI, I tagged this for 1.1.1. Wouldn't normally backport doc-only changes but this is tangentially security related so I think it's better to backport.

2020-08-06 22:00 UTC, jreback approved these changes

2020-08-06 22:00 UTC, merged

2020-08-06 22:00 UTC, jreback commented
thanks @TomAugspurger