DEPR: Deprecate inplace param in MultiIndex.set_codes and MultiIndex.set_codes
pandas-dev/pandas pull request #35626
Opened 2020-08-08 12:13 UTC by topper-123

Deprecates ``inplace`` parameter in ``MultiIndex.set_codes`` and ``MultiIndex.set_levels``.

Allowing inplace ops in indexes makes them more complicated wtr. caching etc. After ``inplace`` is removed, ``MultiIndex`` will be immutable, except the ``names`` attribute, similarly to other index classes.

2020-08-08 14:55 UTC, jreback requested changes
small comment, can you add this to the deprecation issue: https://github.com/pandas-dev/pandas/issues/30228

2020-08-08 14:55 UTC, jreback commented on doc/source/user_guide/indexing.rst
> +directly. They default to returning a copy; however, you can specify ``inplace=True`` to
you can remove the inplace ref

2020-08-08 16:55 UTC, topper-123 commented
Updated.

2020-08-10 13:18 UTC, jreback commented on pandas/core/indexes/multi.py
> +    def set_codes(self, codes, level=None, inplace=None, verify_integrity=True):
typing these would be good at some point

2020-08-10 13:18 UTC, jreback approved these changes

2020-08-10 13:18 UTC, merged

2020-08-10 13:18 UTC, jreback commented
thanks @topper-123