add test for agg on ordered categorical cols
pandas-dev/pandas pull request #35630
Opened 2020-08-08 14:44 UTC by mathurk1

- [Y] closes #27800
- [Y] tests added / passed
- [Y] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-08-08 20:04 UTC, mroeschke commented on pandas/tests/groupby/aggregate/test_aggregate.py
> +    data = np.array([(1, 4, "a"), (5, 8, "c")])
I think if you just pass this in as a list, then you won't have to `astype()` later on

2020-08-08 23:12 UTC, mroeschke approved these changes

2020-08-10 13:26 UTC, jreback requested changes
can you make sure that we are covering all of the tests in the OP as there were a number of cases. happy to enumerate them here (even though we likely have tests for most of them).

2020-08-19 20:57 UTC, jreback requested changes
this is adding a lot of code, can you simplify / parameterize things.

2020-08-19 20:57 UTC, jreback commented on pandas/tests/groupby/aggregate/test_aggregate.py
> +    """
pls add the issue number as a comment.

you don't really need the doc-string; the test name should be descriptive enough

2020-08-19 22:23 UTC, mathurk1 commented
> this is adding a lot of code, can you simplify / parameterize things.

Sure. Planning to add a fixture for the input dataframe and use it across the six test cases.  I feel parameterizing the tests will have a big decorator function on top which might become hard to understand/maintain. Let me know your thoughts.

2020-08-21 22:34 UTC, jreback approved these changes

2020-08-21 22:34 UTC, merged