BUG: GH-35558 merge_asof tolerance error
pandas-dev/pandas pull request #35654
Opened 2020-08-10 15:07 UTC by ikedaosushi

- [x] closes #35558
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2020-08-11 09:17 UTC, simonjayhawkins requested changes
Thanks @ikedaosushi for the PR. AFAICT the added test passes without the code changes.

2020-08-12 16:38 UTC, ikedaosushi commented
@simonjayhawkins Sorry, I made a mistake for the test code. It was fixed.

2020-08-12 19:46 UTC, simonjayhawkins reviewed
Thanks @ikedaosushi lgtm ex missing comment

2020-08-12 19:46 UTC, simonjayhawkins commented on pandas/tests/reshape/merge/test_merge_asof.py
> +    def test_left_index_right_index_tolerance(self):
add the issue number as a comment here
```suggestion
    def test_left_index_right_index_tolerance(self):
        # https://github.com/pandas-dev/pandas/issues/35558
```

2020-08-12 21:46 UTC, jreback reviewed
lgtm ex- @simonjayhawkins  comment

2020-08-13 05:10 UTC, ikedaosushi commented on pandas/tests/reshape/merge/test_merge_asof.py
> +    def test_left_index_right_index_tolerance(self):
Thank you @simonjayhawkins

2020-08-13 06:19 UTC, simonjayhawkins approved these changes

2020-08-13 10:15 UTC, merged

2020-08-13 10:16 UTC, simonjayhawkins commented
Thanks @ikedaosushi

2020-08-13 10:17 UTC, simonjayhawkins commented
@meeseeksdev backport 1.1.x