ENH add na_action to DataFrame.applymap
pandas-dev/pandas pull request #35704
Opened 2020-08-13 11:11 UTC by jnothman

For symmetry with Series.map

- [x] closes #23803
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2020-08-14 21:39 UTC, jreback requested changes

2020-08-14 21:39 UTC, jreback commented on pandas/core/frame.py
> +    def applymap(self, func, na_action=None) -> "DataFrame":
can you type the new arg

2020-08-14 21:39 UTC, jreback commented on pandas/core/frame.py
> +            .. versionadded:: 1.1
1.2

2020-08-14 21:39 UTC, jreback commented on pandas/core/frame.py
> +            raise ValueError(
is this tested?

2020-08-14 21:39 UTC, jreback commented on pandas/tests/frame/apply/test_frame_apply.py
> +        print(strlen_frame_na_ignore)
no prints!

2020-08-15 10:52 UTC, jnothman commented
Apologies for my omissions! Thanks for the review.

2020-08-15 10:57 UTC, jnothman commented on doc/source/whatsnew/v1.2.0.rst
> +- :meth:`applymap` now supports ``na_action`` (:issue:`23803`)
I was surprised by similar usage elsewhere in this file, which I copied:
https://github.com/pandas-dev/pandas/blob/6325a33/doc/source/whatsnew/v1.2.0.rst#L35

2020-08-16 05:59 UTC, jnothman commented
Failure appears unrelated

2020-09-05 20:08 UTC, jreback commented
looks good, can you merge master and ping on green.

2020-09-08 01:45 UTC, jnothman commented
@jreback it's green :)

2020-09-11 17:40 UTC, jreback approved these changes

2020-09-11 17:40 UTC, merged

2020-09-11 17:40 UTC, jreback commented
thanks @jnothman very nice