update io documentation
pandas-dev/pandas pull request #35720
Opened 2020-08-14 14:34 UTC by grrlic

The HDFS dropna=True parameter does not drop the NaN values. Perhaps this is a bug to the core Pandas, or really a typo in the documentation

- [X] closes #35719
- [X] tests added / passed
- [X] passes `black pandas`
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2020-08-14 18:44 UTC, rhshadrach commented
The way you're changing the documentation, setting `dropna=True` keeps NA values. That isn't correct, I believe this is a bug, not an issue with the docs.

2020-08-14 19:18 UTC, simonjayhawkins requested changes
Thanks @grrlic for the PR. see @rhshadrach comment

2020-08-15 02:31 UTC, grrlic commented
Ah, glad this bug is found soon, 'cause I myself kinda doubt that the errata comes from the docs, but apparently it's not the case. Thanks to @XiaozhanYang observations.

2020-08-15 02:31 UTC, closed without merging

2020-08-15 02:39 UTC, grrlic commented
@simonjayhawkins Thanks for the quick updates with @rhshadrach. I am actually new to contributing to open source. I myself am quite familiar with Python. Perhaps with regards to this bug, you have any suggestion or tips that would allow helping contribute? thanks in advanced, really love pandas hahaha.

2020-08-15 11:13 UTC, simonjayhawkins commented
@grrlic in the first instance, if you are unfamiliar with the codebase, I would probably bisect the regression, see #35685 to get a idea of where a fix should be applied.

although for this case, it might be quite straightforward to follow the code from `to_hdf` (I notice from git blame that there we changes to the signature in #29957) It appears that dropna is not passed onto `store.put` in the if append else block