Pass check_dtype to assert_extension_array_equal
pandas-dev/pandas pull request #35750
Opened 2020-08-16 04:14 UTC by dsaxton

- [x] closes #35715
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2020-08-16 04:14 UTC, pep8speaks commented
Hello @dsaxton! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/_testing.py`](https://github.com/pandas-dev/pandas/blob/b47d9b3f13ac7aac1dd28a8d392cc0411772de55/pandas/_testing.py):

> [Line 1380:89](https://github.com/pandas-dev/pandas/blob/b47d9b3f13ac7aac1dd28a8d392cc0411772de55/pandas/_testing.py#L1380): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 88 characters)
> [Line 1385:89](https://github.com/pandas-dev/pandas/blob/b47d9b3f13ac7aac1dd28a8d392cc0411772de55/pandas/_testing.py#L1385): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 88 characters)

2020-08-16 14:50 UTC, simonjayhawkins commented
i've milestoned this 1.1.1. It does not appear to be a regression but no harm in backporting this. can put in bugfix section of whatsnew

2020-08-16 15:34 UTC, dsaxton commented on pandas/_testing.py
> +            check_dtype=check_dtype,
Included this also as it seems it can't be wrong to pass check_dtype here, but not certain of how best to test (if at all)

2020-08-17 14:40 UTC, jreback requested changes

2020-08-17 14:40 UTC, jreback commented on pandas/tests/util/test_assert_series_equal.py
> +def test_assert_series_equal_ignore_extension_dtype_mismatch():
same as above

2020-08-17 18:20 UTC, jreback approved these changes

2020-08-17 18:20 UTC, merged

2020-08-17 18:20 UTC, jreback commented
thanks @dsaxton very nice

2020-08-17 18:31 UTC, simonjayhawkins commented
@meeseeksdev backport 1.1.x