BUG: Index.get_slice_bounds does not accept datetime.date or tz naive datetime.datetimes
pandas-dev/pandas pull request #35848
Opened 2020-08-22 06:47 UTC by mroeschke

- [x] closes #35690
- [x] closes #34077
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

This method appeared under tested so added some additional tests for numeric and object `Index`

2020-08-23 00:39 UTC, jreback requested changes
will look soon

2020-08-24 22:16 UTC, jbrockmendel commented on pandas/core/indexes/datetimes.py
> +            key = datetime.combine(key, time(0, 0))
won't the `Timestamp(key)` below do this already?

2020-08-24 22:17 UTC, jbrockmendel commented on pandas/tests/indexes/test_slice_ops.py
> +from datetime import date, datetime
id put the object ones in `tests.indexes.base_class.test_indexing.TestGetSliceBounds` and the numeric ones in `tests.indexes.numeric.test_indexing.TestGetSliceBounds`

2020-08-24 22:26 UTC, jbrockmendel commented
Just commented on #35690, the upshot of which is that I think the current behavior is correct.

2020-08-25 00:18 UTC, jreback requested changes

2020-08-25 00:18 UTC, jreback commented on pandas/core/indexes/base.py
> +            raise ValueError(
this should be an AssertionError  as this is an internal method (yes I know @RhysU is actually calling it), but its officially public and merely an interface from `.loc`

2020-08-25 05:10 UTC, pep8speaks commented
Hello @mroeschke! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/indexes/base_class/test_indexing.py`](https://github.com/pandas-dev/pandas/blob/830df027f90901fe29a2be7a59f7f90588cdfde8/pandas/tests/indexes/base_class/test_indexing.py):

> [Line 17:85](https://github.com/pandas-dev/pandas/blob/830df027f90901fe29a2be7a59f7f90588cdfde8/pandas/tests/indexes/base_class/test_indexing.py#L17): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','



* In the file [`pandas/tests/indexes/test_numeric.py`](https://github.com/pandas-dev/pandas/blob/830df027f90901fe29a2be7a59f7f90588cdfde8/pandas/tests/indexes/test_numeric.py):

> [Line 695:45](https://github.com/pandas-dev/pandas/blob/830df027f90901fe29a2be7a59f7f90588cdfde8/pandas/tests/indexes/test_numeric.py#L695): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2020-09-02 21:35 UTC, jreback approved these changes

2020-09-02 21:36 UTC, jreback commented
lgtm @mroeschke 

ideally we *also* test via ```.loc[]``` for these behaviors (we likey have some already tested); but as a followup is fine.

2020-09-02 21:36 UTC, merged

2020-09-02 21:49 UTC, jbrockmendel commented
See comment [above](https://github.com/pandas-dev/pandas/pull/35848#issuecomment-679397568), this PR should not be merged.