CLN: resolve UserWarning #35945
pandas-dev/pandas pull request #35946
Opened 2020-08-28 05:40 UTC by VirosaLi

- [ ] closes #35945
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2020-08-28 08:04 UTC, charlesdong1991 requested changes
thanks for the PR, @VirosaLi 

just curious where is this warning getting caught or is the warning raised on a newer matplotlib version, do we have any tests right now to catch the warning?

2020-08-28 14:57 UTC, VirosaLi commented
> thanks for the PR, @VirosaLi
> 
> just curious where is this warning getting caught or is the warning raised on a newer matplotlib version, do we have any tests right now to catch the warning?

pandas/tests/plotting/test_frame.py: 10 warnings
pandas/tests/plotting/test_series.py: 5 warnings
  /home/fangchenli/Workspace/pandas-VirosaLi/pandas/plotting/_matplotlib/core.py:1235: UserWarning: FixedFormatter should only be used together with FixedLocator
    ax.set_xticklabels(xticklabels)

2020-08-28 14:57 UTC, VirosaLi commented on pandas/plotting/_matplotlib/core.py
> +            ax.set_xticks(xticks)
I agree with you. Let me take another look.

2020-09-03 03:09 UTC, jreback commented
@VirosaLi so the warning is now gone? I don't think we actually need a test for this, but if you can put an assert_produces_warning(None) around something and have it pass would be great.

2020-09-03 06:23 UTC, charlesdong1991 approved these changes
lgtm

if you could get the CI green (doesn't seem relevant to the PR though, maybe try to rebase one more time)

2020-09-03 10:20 UTC, charlesdong1991 commented
the first one will be resolved once https://github.com/pandas-dev/pandas/pull/36085 gets merged.

2020-09-05 03:33 UTC, merged

2020-09-05 03:33 UTC, jreback commented
thanks @VirosaLi

2020-10-02 11:55 UTC, simonjayhawkins commented
@meeseeksdev backport 1.1.x