Gh35889 groupby dropna apply
pandas-dev/pandas pull request #35951
Opened 2020-08-28 09:33 UTC by cwkwong

- [X] closes #35889 
- [X] tests added / passed
- [X] passes `black pandas`
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry in `v1.1.2.rst`

2020-08-28 19:36 UTC, arw2019 requested changes
thanks @cwkwong for a nice PR!

Some largely cosmetic comments, otherwise lgtm

2020-08-28 19:36 UTC, arw2019 commented on pandas/tests/groupby/test_groupby_dropna.py
> +    dfg = df.groupby("groups", dropna=dropna)
nitpick: call this `gb`

2020-08-28 19:36 UTC, arw2019 commented on pandas/tests/groupby/test_groupby_dropna.py
> +    rv = dfg.apply(lambda grp: pd.DataFrame({"values": list(range(len(grp)))}))
another nitpick: call this `result`

2020-08-28 19:36 UTC, arw2019 commented on pandas/tests/groupby/test_groupby_dropna.py
> +def test_groupby_dropna_multi_index_dataframe_apply(
I'd do `test_groupby_apply_with_dropna_for_multiindex`

2020-08-28 19:36 UTC, arw2019 commented on pandas/tests/groupby/test_groupby_dropna.py
> +    # `groupby` with `dropna=False` and `apply` returning DataFrame of different
nit-pick: probably don't need this, GH issue and test name are enough info

2020-08-28 19:36 UTC, arw2019 commented on pandas/tests/groupby/test_groupby_dropna.py
> +    rv = dfg.apply(lambda grp: pd.DataFrame({"values": list(range(len(grp)))}))
also you can feed `range` directly to the DataFrame constructor, no need to convert to list

2020-08-28 19:36 UTC, arw2019 commented on pandas/tests/groupby/test_groupby_dropna.py
> +    tuples = tuple(zip(df_cols_in["groups"], df_cols_out["values"]))
nitpick: I'd call this `mi_tuples`

2020-08-28 19:36 UTC, arw2019 commented on pandas/tests/groupby/test_groupby_dropna.py
> +    dropna, df_cols_in, df_cols_out, levels
I'd rename `df_cols_in` &#8594; `data`  and `df_cols_out` &#8594; `selected_data`

2020-08-28 19:36 UTC, arw2019 commented on doc/source/whatsnew/v1.1.2.rst
> +- Bug in :meth:`DataFrame.apply` on :meth:`DataFrame.groupby`, ``dropna=False`` and ``np.nan`` group(s) (:issue:`35889`)
Bug in :meth:`DataFrame.groupby(...).apply(...)` raising error with ``np.nan`` group(s) when `dropna=False`

2020-08-29 12:57 UTC, arw2019 approved these changes

2020-08-29 13:09 UTC, arw2019 commented
@cwkwong might want to have a more descriptive title `BUG: Fix DataFrame.groupby().apply() for NaN groups with dropna=False`

2020-09-01 01:22 UTC, cwkwong commented
Thanks @arw2019 for approving the changes. What's the next step to hopefully make this as part of the `1.1.2` release?

2020-09-01 20:06 UTC, charlesdong1991 requested changes
thanks for the PR @cwkwong 

This should be moved to whatsnew 1.2.0 note. 1.1.2 mainly focuses on regression issue.

2020-09-01 20:06 UTC, charlesdong1991 commented on doc/source/whatsnew/v1.1.2.rst
> +- Bug in :meth:`DataFrame.groupby(...).apply(...)` raising error with ``np.nan`` group(s) when ``dropna=False`` (:issue:`35889`)
```suggestion
- Bug in :meth:`DataFrameGroupBy.apply` raising error with ``np.nan`` group(s) when ``dropna=False`` (:issue:`35889`)
```

2020-09-01 20:06 UTC, charlesdong1991 commented on pandas/core/reshape/concat.py
> +        # for each level and pass those to MultiIndex.from_arrays.
could you please revert the change here? ideally only change the code where needs to be changed

2020-09-01 20:06 UTC, charlesdong1991 commented on pandas/core/reshape/concat.py
> +
same here?

2020-09-01 20:06 UTC, charlesdong1991 commented on pandas/core/reshape/concat.py
> +                mask = (isna(level) & isna(key)) | (level == key)
could you pls add a comment above this line to describe the `mask` behaviour?

2020-09-05 03:15 UTC, merged

2020-09-05 03:15 UTC, jreback commented
thanks @cwkwong very nice