DOC: Add Notes about difference to numpy behaviour for ddof in std() GH35985
pandas-dev/pandas pull request #35986
Opened 2020-08-30 11:51 UTC by timhunderwood

GH35985.

- [ ] closes #GH35985
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-08-30 13:16 UTC, dsaxton reviewed
Thanks @timhunderwood, small suggested wording edit

2020-08-30 13:16 UTC, dsaxton commented on pandas/core/generic.py
> +behaviour as numpy, use ddof=0.\n"""
```suggestion
The default divisor (normalization) is different from numpy, which
by default normalizes by N. To have the same behaviour as numpy,
use ddof=0.\n"""
```

2020-08-31 08:22 UTC, timhunderwood commented on pandas/core/generic.py
> +behaviour as numpy, use ddof=0.\n"""
Done @dsaxton , thanks!

2020-08-31 10:12 UTC, MarcoGorelli requested changes
Thanks @timhunderwood 

> normalizes by N

Are you sure this is correct? Does dividing by N actually normalise the quantity?

IMO it should be enough to write something like
```
Notes
-----
To have the same behaviour as `numpy.std`, use `ddof=0` (instead of the default `ddof=1`)
```

2020-08-31 10:22 UTC, timhunderwood commented
> Thanks @timhunderwood
> 
> > normalizes by N
> 
> Are you sure this is correct? Does dividing by N actually normalise the quantity?
> 
> IMO it should be enough to write something like
> 
> ```
> Notes
> -----
> To have the same behaviour as `numpy.std`, use `ddof=0` (instead of the default `ddof=1`)
> ```



> Thanks @timhunderwood
> 
> > normalizes by N
> 
> Are you sure this is correct? Does dividing by N actually normalise the quantity?
> 
> IMO it should be enough to write something like
> 
> ```
> Notes
> -----
> To have the same behaviour as `numpy.std`, use `ddof=0` (instead of the default `ddof=1`)
> ```

thanks @MarcoGorelli , I agree this could be confusing. I've changed to your simpler wording, thanks.

2020-08-31 21:45 UTC, dsaxton approved these changes
Seems like an improvement to me 👍

2020-09-01 16:25 UTC, MarcoGorelli approved these changes
Looks good to me, can you fetch and merge upstream/master and then push again to restart the CI process in order to get it green?

2020-09-02 20:31 UTC, timhunderwood commented
> Looks good to me, can you fetch and merge upstream/master and then push again to restart the CI process in order to get it green?

Done - CI process has started...

2020-09-03 16:58 UTC, merged

2020-09-03 16:58 UTC, MarcoGorelli commented
Thanks @timhunderwood !