Center window
pandas-dev/pandas pull request #36097
Opened 2020-09-03 17:06 UTC by adamamiller

- [x] closes #20012
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Added center functionality for `VariableWindowIndexer`. Note - I am unsure if the NotImplementedError in lines 1966-1969 in rolling.py still correctly raises an error for offset based windows.

2020-09-05 15:19 UTC, jreback requested changes
needs a fair amount of tests

2020-09-05 15:19 UTC, jreback commented on pandas/_libs/window/indexers.pyx
> +            if (index[j] == index[0] + index_growth_sign*window_size/2 and
this is likley failing linting (need spaces between operators)

2020-11-01 17:59 UTC, arw2019 reviewed
@adamamiller are you interested in continuing? If yes please address @jreback comment (he's requesting tests) and merge master/resolve conflicts

2020-11-04 08:26 UTC, arw2019 commented
Closing for now. @adamamiller ping whenever you'd like to continue and we'll reopen!

2020-11-04 08:26 UTC, closed without merging

2020-12-29 13:22 UTC, Zaubeerer commented
Would love to see this functionality and would like to pick up the pull request with @luholgit

What are the next required steps?

We already forked the pandas repo and checked out the branch from @adamamiller.

However, when trying to update the branch by pulling from origin/master into fork/center_window we encountered several merge conflicts which we are not sure how to solve.

Should we solve them based on our understanding and then discuss those changes in this PR?

2020-12-29 13:24 UTC, Zaubeerer commented
@jreback and @arw2019, mentioning you explicitly as we need this change urgently and would love to implement at the open source directly as opposed to our private repository! :)

2020-12-29 13:49 UTC, jreback commented
you see the comments above

this needs to have master merged and needs tests

2020-12-29 14:25 UTC, Zaubeerer commented
Thanks for your quick response, we are implementing the merge and tests right now.

(Un)Fortunately, we were not able to push to @adamamiller's fork. 

Could you change the pull request to come from https://github.com/luholgit/pandas/tree/center_window?

2020-12-29 14:30 UTC, Zaubeerer commented
Or shall we create a new issue such that the new source branch from our fork is selected automatically?

2020-12-29 14:36 UTC, MarcoGorelli commented
@Zaubeerer thanks for taking this forwards - you can open a new pull request

2020-12-29 14:56 UTC, jreback commented
@Zaubeerer you just create a new PR, no need to create a new issue