BUG: copying series into empty dataframe does not preserve dataframe index name
pandas-dev/pandas pull request #36141
Opened 2020-09-05 14:58 UTC by Dr-Irv

- [x] closes #31368
- [x] tests added / passed
   `indexing/test_partial.py:TestPartialSetting:test_index_name_empty`
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2020-09-05 19:44 UTC, jreback commented on pandas/core/frame.py
> +            index_copy = value.index.copy()
FYI `value.index.set_name(self.index.name)` should work as well

2020-09-05 19:45 UTC, jreback requested changes

2020-09-05 19:45 UTC, jreback commented on pandas/tests/indexing/test_partial.py
> +        tm.assert_equal(df.index.name, "df_index")
can you construct the expected frame and use tm.assert_frame_equal

2020-09-06 17:00 UTC, jreback commented
also pls merge master

2020-09-08 12:43 UTC, jreback approved these changes

2020-09-08 12:44 UTC, jreback commented
@simonjayhawkins ok for 1.1.2 (if you haven't tagged), otherwise let's push to 1.1.3

2020-09-08 12:49 UTC, simonjayhawkins commented
> @simonjayhawkins ok for 1.1.2 (if you haven't tagged), otherwise let's push to 1.1.3

ok for 1.1.2

2020-09-08 13:45 UTC, merged

2020-09-08 13:45 UTC, simonjayhawkins commented
Thanks @Dr-Irv

2020-09-08 13:46 UTC, simonjayhawkins commented
@meeseeksdev backport 1.1.x

2020-09-08 13:50 UTC, simonjayhawkins commented
@meeseeksdev backport 1.1.x

2020-09-08 13:56 UTC, simonjayhawkins commented
@meeseeksdev backport 1.1.x