TST GH 29699 multilevel column is called after multiple appends
pandas-dev/pandas pull request #36230
Opened 2020-09-08 21:25 UTC by TAJD

- [x] closes #29699
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Not sure where the best place to put the test is. 

Also, this code generates a warning which doesn't seem to disappear when following the guidance of the warning i.e: set `sort=False`. As the default behaviour is meant to return a warning this is tested for.

2020-09-08 22:21 UTC, jreback requested changes

2020-09-08 22:21 UTC, jreback commented on pandas/tests/test_multilevel.py
> +                a = pd.concat([a], keys=["multi"], names=["level1"], axis=1)
add `sort=False` here (and remove the assert_productions_warning

2020-09-08 22:23 UTC, jreback requested changes

2020-09-08 22:23 UTC, jreback commented on pandas/tests/test_multilevel.py
> +    def test_multilevel_multiple_append(self):
can you move the test to pandas/tests/reshape/test_concat.py

2020-10-11 00:31 UTC, jreback commented
@TAJD can you merge master and ping when green-ish

2020-11-04 09:13 UTC, arw2019 commented
@TAJD can you merge master again & resolve conflicts? Based on comments this looks good to go

2020-11-04 10:55 UTC, TAJD commented
For some reason it doesn't quite work out when I merge and then run tests. The warning still appears. I've not got much time at the moment to work this one out - I hope I've not missed anything obvious.

2020-11-17 17:07 UTC, arw2019 commented
> For some reason it doesn't quite work out when I merge and then run tests. The warning still appears. I've not got much time at the moment to work this one out - I hope I've not missed anything obvious.

No problem! Thanks for looking into this anyways. Closing the PR for now - let us know whenever you'd like to pick this back up and we'll reopen

2020-11-17 17:07 UTC, closed without merging