Fix #35484 - re-allow sqlalchemy declarative system to use `%` in read_sql.
pandas-dev/pandas pull request #36275
Opened 2020-09-10 20:33 UTC by machow

- [x] closes #35484
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

* Adds tests to cover sql cases combining parameters and `%`.
* Notably, these tests highlight two regressions in v1.1
  - `pd.read_sql("SELECT 1 %% 2", engine)` fails. See #35871.
  - `pd.read_sql(sqlalchemy.sql.text("SELECT 1 % 2"), engine)` fails. See #35484.
* Fixes the second regression by modifying SqlDatabase to not use `no_parameter`, and wrapping string queries in `sql.text()` when no parameters are passed.

I was going nuts trying to keep track of all the cases, so tossed them into a table! I didn't have time to explicitly check v1.05, so would be helpful if someone could verify that column (or I may be able to loop back to it)!

| query |   v1.05 | v.1.1 | PR | issue |
| --- | --- | --- | --- | --- |
| no params, `%` | ❌ | ✅ | ✅ | #34211 (merged) |
| no params, `%%` | ✅ | ❌ | ❌ | #35871 |
| params, `%` | ❌ | ❌ | ❌ |  https://github.com/psycopg/psycopg2/issues/827 |
| params, `%%` | ✅ | ✅ | ✅ | | 
| sqla declarative, `%` | ✅ | ❌ | ✅ | #35484 |

2020-09-23 20:03 UTC, jbrockmendel commented
@TomAugspurger any idea who to ping about sqlalchemy review?

2020-09-24 19:56 UTC, TomAugspurger commented
I'm not sure. Perhaps contributors on the issue that caused the regression.

On Wed, Sep 23, 2020 at 3:03 PM jbrockmendel <notifications@github.com>
wrote:

> @TomAugspurger <https://github.com/TomAugspurger> any idea who to ping
> about sqlalchemy review?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/36275#issuecomment-697942716>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKAOIV77NXROY6LJSU4PL3SHJICTANCNFSM4RF2DVNQ>
> .
>

2020-10-26 23:05 UTC, jbrockmendel commented
@john-bodley can you take a look at this

2020-10-27 05:27 UTC, john-bodley commented
I guess this is a known issue with SQLAlchemy (using 1.2.8 per the Pandas specs) using the default connection for certain dialects, i.e., 

```python
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:@localhost:5433/postgres', echo=False) 
engine.execute("SELECT 1 % 2")  # TypeError: 'dict' object does not support indexing
```

versus the raw-connection:

```python
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:@localhost:5433/postgres', echo=False) 
cursor = engine.raw_connection().cursor() 
cursor.execute("SELECT 1 % 2")
cursor.fetchone()  # (1,)
```

Googling the issue it seems taking the `sql.text(...)` approach as proposed by @machow seems to be a commonly recommended solution.

2020-11-26 19:08 UTC, jreback requested changes
can you write a whatsnew entry (1.2). i think this would make evaluating this easier.

2020-11-26 19:08 UTC, jreback commented on pandas/tests/io/test_sql.py
> +    @pytest.mark.xfail
can you add an explict xfail / message or reason

2020-11-26 19:08 UTC, jreback commented
can you also merge master

2020-11-27 18:02 UTC, machow commented
@john-bodley @jreback thanks for your feedback. I'll have some time after next week--will add a whatsnew entry and bring things up to date.

2020-12-28 00:38 UTC, jreback commented
closing this as stale, though maybe fixed by https://github.com/pandas-dev/pandas/pull/37534 (in 1.2) in any event.

if this is not the case @machow you can create a new PR.

2020-12-28 00:38 UTC, closed without merging