CLN: typo cleanups
pandas-dev/pandas pull request #36276
Opened 2020-09-10 20:50 UTC by jbrockmendel

2020-09-10 21:47 UTC, WillAyd approved these changes
lgtm

2020-09-11 10:57 UTC, ivanovmg requested changes

2020-09-11 10:57 UTC, ivanovmg commented on scripts/validate_unwanted_patterns.py
> +        Comma seperated values of what file extensions to check.
Should be "comma separated" (not seperated). Here and below.

2020-09-11 15:20 UTC, ivanovmg approved these changes

2020-09-12 01:00 UTC, merged