PERF: constructing string Series
pandas-dev/pandas pull request #36317
Opened 2020-09-12 23:02 UTC by topper-123

Example:

```python
>>> x = np.array([str(u) for u in range(1_000_000)], dtype=object)
>>> %timeit pd.Series(x, dtype=str)
344 ms ± 59.7 ms per loop  # v1.1.0
157 ms ± 7.04 ms per loop  # after #35519
22.6 ms ± 191 µs per loop  # after #36304
11.2 ms ± 48.6 µs per loop  # after this PR
```

Similar speed-up is possible for `pd.Series(x, dtype="string")`, but requires some refactorng of `Stringarray`, so I'll do that is a seperate PR.

xref #35519 & #36304.

2020-09-12 23:27 UTC, jreback requested changes
great (can u add all of these issues on the whats new, same entry just keep appending)

2020-09-13 08:20 UTC, topper-123 commented
Updated.

2020-09-13 12:39 UTC, jreback approved these changes

2020-09-13 12:39 UTC, merged

2020-09-13 12:40 UTC, jreback commented
thanks @topper-123