CLN: Clean series/test_arithmetic.py
pandas-dev/pandas pull request #36406
Opened 2020-09-16 20:01 UTC by dsaxton

2020-09-16 22:00 UTC, rhshadrach approved these changes
Nice cleanup, lgtm.

2020-09-16 23:20 UTC, jreback requested changes

2020-09-16 23:20 UTC, jreback commented on pandas/tests/series/test_arithmetic.py
> +    @pytest.mark.parametrize("op", ["eq", "ne", "le", "le", "gt", "ge"])
can you use the `all_compare_operators` fixture

2020-09-16 23:20 UTC, jreback commented on pandas/tests/series/test_arithmetic.py
> +    @pytest.mark.parametrize("axis", [0, None, "index"])
can you use the `all_compare_operators` fixture

2020-09-17 16:36 UTC, jreback approved these changes

2020-09-17 16:36 UTC, merged

2020-09-17 16:36 UTC, jreback commented
thanks @dsaxton