Call finalize in Series.__array_ufunc__
pandas-dev/pandas pull request #36553
Opened 2020-09-22 19:38 UTC by TomAugspurger

xref 28283

2020-09-27 18:31 UTC, jbrockmendel commented
makes sense, looks mypy complaints

2020-09-27 18:49 UTC, jreback requested changes

2020-09-27 18:49 UTC, jreback commented on pandas/core/series.py
> +            # TODO: When we support multiple values in __finalize__, this should
I think i understand what you mean, but can you expand on this for readers

2020-10-02 23:05 UTC, jreback commented
hmm can you merge master

2020-10-07 22:11 UTC, TomAugspurger commented
This is being subsumed by https://github.com/pandas-dev/pandas/pull/36955

2020-10-07 22:11 UTC, closed without merging