TST: 32bit dtype compat #36579
pandas-dev/pandas pull request #36584
Opened 2020-09-23 20:14 UTC by fangchenli

Part of #36579

2020-09-23 20:15 UTC, pep8speaks commented
Hello @fangchenli! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`pandas/tests/test_algos.py`](https://github.com/pandas-dev/pandas/blob/c6e64b115ea6188889724e0d5be070d7447f71b3/pandas/tests/test_algos.py):

> [Line 1549:89](https://github.com/pandas-dev/pandas/blob/c6e64b115ea6188889724e0d5be070d7447f71b3/pandas/tests/test_algos.py#L1549): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 88 characters)
> [Line 1583:89](https://github.com/pandas-dev/pandas/blob/c6e64b115ea6188889724e0d5be070d7447f71b3/pandas/tests/test_algos.py#L1583): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 88 characters)

2020-09-24 01:56 UTC, jreback requested changes

2020-09-24 01:56 UTC, jreback commented on pandas/tests/indexes/test_base.py
> +        tm.assert_numpy_array_equal(result[1], ex2.astype(expected_dtype))
same

2020-09-24 01:56 UTC, jreback commented on pandas/tests/indexes/test_base.py
> +        tm.assert_numpy_array_equal(result[1], ex2.astype(expected_dtype))
actually if you just remove the astype this should be correct

2020-09-24 01:56 UTC, jreback commented on pandas/tests/test_algos.py
> +        expected_dtype = np.int64 if IS64 else np.int32
same

2020-09-24 01:56 UTC, jreback commented on pandas/tests/test_algos.py
> +        expected_dtype = np.int64 if IS64 else np.int32
same

2020-09-24 22:22 UTC, jreback approved these changes

2020-09-24 22:22 UTC, merged

2020-09-24 22:23 UTC, jreback commented
thanks!

do we have a 32-bit build on CI? e.g. where were these failing

2020-09-24 23:00 UTC, fangchenli commented
> thanks!
> 
> do we have a 32-bit build on CI? e.g. where were these failing

The 32-bit build is still work in progress https://github.com/pandas-dev/pandas/pull/35898. It's working but not integrated with our existing setup yet. I also saw those failures on Raspberry Pi.