BUG: Categorical setitem, comparison with tuple category
pandas-dev/pandas pull request #36623
Opened 2020-09-25 02:39 UTC by jbrockmendel

- [x] closes #20439
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-09-25 15:50 UTC, WillAyd reviewed
lgtm - can you add a whatsnew?

2020-09-29 20:53 UTC, WillAyd approved these changes
lgtm @TomAugspurger

2020-09-30 00:09 UTC, jreback requested changes
can you also check getitem?

2020-09-30 00:09 UTC, jreback commented on pandas/core/arrays/categorical.py
> +        rvalue = value if not is_hashable(value) else [value]
can use `maybe_make_list` (but certainly can followup as may need to change that definition slightly)

2020-09-30 00:43 UTC, jbrockmendel commented
> can you also check getitem?

not sure i follow.  you mean check that `cat[i]` gives a tuple.  pretty sure we already have tests for that

2020-10-02 22:42 UTC, jreback commented
> > can you also check getitem?
> 
> not sure i follow. you mean check that `cat[i]` gives a tuple? pretty sure we already have tests for that

ok then.

2020-10-02 22:43 UTC, jreback approved these changes

2020-10-02 22:43 UTC, merged