bump pytables to 3.5.1 #24839
pandas-dev/pandas pull request #36683
Opened 2020-09-27 14:49 UTC by fangchenli

- [ ] closes #24839
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

PyTables 3.5.1 was released on March 14, 2019. And it offers better support for np16.

2020-09-27 19:37 UTC, jreback requested changes

2020-09-27 19:37 UTC, jreback commented on pandas/tests/io/pytables/test_store.py
> -    @td.xfail_non_writeable
can remove these version requirements as they are obsolete

2020-09-29 21:04 UTC, WillAyd approved these changes
lgtm

2020-09-30 00:05 UTC, jreback approved these changes

2020-09-30 00:06 UTC, jreback commented
can you add a whatsnew bug fix note (I/O) that the issue is fixed in the OP; can merge after that.

2020-09-30 02:23 UTC, merged

2020-09-30 02:23 UTC, jreback commented
thanks @fangchenli