BUG: df.diff axis=1 mixed dtypes
pandas-dev/pandas pull request #36710
Opened 2020-09-28 18:00 UTC by jbrockmendel

- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-09-30 02:01 UTC, jreback requested changes
this would need a note in whatsnew, maybe a sub-section as this is a non-trivial change (good change), but should be made aware.

2020-09-30 02:44 UTC, jbrockmendel commented on pandas/core/frame.py
> +        if not isinstance(periods, int):
will do

2020-09-30 02:45 UTC, jbrockmendel commented on pandas/core/frame.py
> +                    result.insert(0, col, filler, allow_duplicates=True)
it is inplace on `result` which we havent returned to the user yet

2020-10-07 03:28 UTC, jreback approved these changes

2020-10-07 03:29 UTC, merged