DEPR: automatic alignment on frame.__cmp__(series)
pandas-dev/pandas pull request #36795
Opened 2020-10-01 23:14 UTC by jbrockmendel

- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

xref #28759, may close it depending on if we want to do anything else on that front

2020-10-02 01:23 UTC, rhshadrach requested changes

2020-10-02 01:23 UTC, rhshadrach commented on pandas/core/ops/__init__.py
> +                    "is deprecated and will be raise ValueError in a future version.  "
Typo: "be"

2020-10-02 18:27 UTC, mroeschke approved these changes

2020-10-03 00:26 UTC, jbrockmendel commented
rebased+green

2020-10-03 00:55 UTC, merged