ran blacken docs tool and checked output to improve formatting #36777
pandas-dev/pandas pull request #36802
Opened 2020-10-02 06:09 UTC by maria-ilie

For task #36777
Ran blacken-tools on user_guide/10min.rst, user_guide/advanced.rst, basics.rst

2020-10-02 06:54 UTC, MarcoGorelli commented
Thanks @maria-ilie ! This looks correct, it's just that E203 needs to be added to the ignore list for [flake8-rst]

Could you make the following change to `setup.cfg` as well? I think it's fine if it's part of this same pull request

```diff
diff --git a/setup.cfg b/setup.cfg
index 73986f692..eb2efb937 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -40,7 +40,9 @@ bootstrap =
     np  # avoiding error when importing again numpy or pandas
     pd  # (in some cases we want to do it to show users)
 ignore = E402,  # module level import not at top of file
+         E203,  # space before : (needed for how black formats slicing)
          W503,  # line break before binary operator
+         W504,  # line break after binary operator
          # Classes/functions in different blocks can generate those errors
          E302,  # expected 2 blank lines, found 0
          E305,  # expected 2 blank lines after class or function definition, found 0
```

2020-10-02 10:48 UTC, erfannariman commented
Just to be sure we don't get any conflicts, I edited `10min.rst` on #36780

2020-10-02 14:36 UTC, dsaxton commented
Thanks @maria-ilie for the PR, can you merge master to fix the conflict?

2020-10-04 13:22 UTC, MarcoGorelli requested changes
Thanks for updating, there's just one small thing which is causing the automated checks to fail

2020-10-04 13:22 UTC, MarcoGorelli commented on doc/source/user_guide/10min.rst
> +    )
Looks like this block got extra-indented by one space, this is causing the CI error

2020-10-04 23:24 UTC, dsaxton approved these changes
Looks good, just one tiny nitpick. Also merging master should fix the CI.

2020-10-04 23:24 UTC, dsaxton commented on doc/source/user_guide/basics.rst
> +    (df_p.pipe(extract_city_name).pipe(add_country_name, country_name="US"))
```suggestion
    df_p.pipe(extract_city_name).pipe(add_country_name, country_name="US")
```

2020-10-05 02:07 UTC, merged

2020-10-05 02:07 UTC, dsaxton commented
Thanks @maria-ilie

2020-10-05 02:09 UTC, maria-ilie commented
Thanks so much for reviewing!

2020-10-06 08:15 UTC, MarcoGorelli commented
Happy to help, let us know if you'd like any help/mentoring with other issues