Fix test_unstack
pandas-dev/pandas pull request #36987
Opened 2020-10-08 18:58 UTC by jrm5100

The test was failing if the ExtensionDtype had an na_value that wasn't equivalent to nan

- [x] closes #36986 
- [x] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-10-08 18:58 UTC, pep8speaks commented
Hello @jrm5100! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/extension/base/reshaping.py`](https://github.com/pandas-dev/pandas/blob/88c70731327ad4b18c65e9288f5ecdb34a3eb315/pandas/tests/extension/base/reshaping.py):

> [Line 319:89](https://github.com/pandas-dev/pandas/blob/88c70731327ad4b18c65e9288f5ecdb34a3eb315/pandas/tests/extension/base/reshaping.py#L319): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 88 characters)

2020-10-08 19:22 UTC, arw2019 requested changes
thanks @jrm5100 for the PR!

There's still some linting issue (according to CI you need to run black)

2020-10-08 20:53 UTC, TomAugspurger approved these changes
Thanks, I guess it came down to this passing

```python
In [45]: a = pd.Series([1, np.nan], dtype=object)

In [46]: b = pd.Series([1, pd.NA], dtype=object)

In [47]: pd.testing.assert_series_equal(a, b)
```


FYI, we're making a list of 3rd-party extension types at https://pandas.pydata.org/pandas-docs/stable/ecosystem.html#extension-data-types, if you want to add pandas-genomics to ecosystem.rst

2020-10-08 20:53 UTC, TomAugspurger commented
I restarted the failed numpy dev build (timed out)

2020-10-08 22:01 UTC, merged

2020-10-08 22:01 UTC, jreback commented
thanks @jrm5100

2020-10-08 22:02 UTC, jreback commented
> Thanks, I guess it came down to this passing
> 
> ```python
> In [45]: a = pd.Series([1, np.nan], dtype=object)
> 
> In [46]: b = pd.Series([1, pd.NA], dtype=object)
> 
> In [47]: pd.testing.assert_series_equal(a, b)
> ```
> 
> FYI, we're making a list of 3rd-party extension types at https://pandas.pydata.org/pandas-docs/stable/ecosystem.html#extension-data-types, if you want to add pandas-genomics to ecosystem.rst

shouldn't this raise as these are *not* equal

2020-10-09 15:46 UTC, TomAugspurger commented
> shouldn't this raise as these are not equal

I think so. Looks like it's come up in https://github.com/pandas-dev/pandas/issues/18463 / https://github.com/pandas-dev/pandas/issues/27613