DOC: Clarify display.precision
pandas-dev/pandas pull request #37030
Opened 2020-10-10 14:36 UTC by hongshaoyang

- [x] closes #21004
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2020-10-10 15:52 UTC, rhshadrach requested changes
This change seems less precise than what is in Settings and Options. Can we just copy that? 

> Floating point output precision in terms of number of places after the decimal, for regular formatting as well as scientific notation. Similar to numpy’s precision print option

2020-10-10 16:19 UTC, jreback requested changes

2020-10-10 16:19 UTC, jreback commented on pandas/core/config_init.py
> +    numpy's ``precision`` print option.
you can directly reference the numpy function itself ```:meth:`np. ....` ```

2020-10-10 16:45 UTC, hongshaoyang commented
Thanks @jreback, @rhshadrach, updated.

2020-10-11 20:14 UTC, rhshadrach approved these changes

2020-10-12 11:34 UTC, hongshaoyang commented
all checks passing.

2020-10-12 15:08 UTC, jreback approved these changes

2020-10-12 15:09 UTC, merged

2020-10-12 15:09 UTC, jreback commented
thanks @hongshaoyang