CI: Check for inconsistent pandas namespace usage
pandas-dev/pandas pull request #37188
Opened 2020-10-17 03:51 UTC by dsaxton

Adding a CI check that we aren't (for instance) using `Series(...)` and `pd.Series(...)` in the same file. This is kept intentionally small in scope (checking only DataFrame and Series for one file name right now) since this is very common in the code base and I'm not sure if this is something we'd actually want to enforce.

2020-10-17 15:26 UTC, dsaxton commented on ci/code_checks.sh
> +    grep -R -l --include="test_missing.py" " DataFrame(" | xargs grep -n "pd\.DataFrame("; test $? -gt 0
Will put this in a function if we want to check for this. I didn't see an obvious way to use invgrep for this check so writing a custom command instead.

2020-10-17 16:36 UTC, jreback requested changes
yeah we had an issue where we talked about this a while back . There was an analysis and IIRC we were basically split between these usages. The discussion basically said that an individual file should be consistent (either pd.* or just Series/DataFrame), but we wouldn't do the effort to clean everything up.

@jorisvandenbossche was for not clean
me and @jbrockmendel though we should just standarize on Series/DataFrame

IIRC.

I am still in favor of using Series/DataFrame everywhere in tests (and not pd.*)

2020-10-17 16:36 UTC, jreback commented on ci/code_checks.sh
> +    grep -R -l --include="test_analytics.py" " ${1}(" | xargs grep -n "pd\.${1}("
make the includes another variable so it can be (slowly) expanded over time

2020-10-17 17:42 UTC, jbrockmendel commented
I agree with @jreback: small preference towards not `pd.`, preference for within-file consistency, not worth bikeshedding on this topic

2020-10-20 01:33 UTC, jreback requested changes

2020-10-20 01:33 UTC, jreback commented on ci/code_checks.sh
> +    grep -R -l --include="${2}" --exclude="${3}" " ${1}(" | xargs grep -n "pd\.${1}("
can you use named parameters here, e.g. something like

```
local -r INCLUDE="${1}"
```

2020-10-20 01:34 UTC, jreback commented
yeah it think this is ok to add. will have to figure out the best way to expand this coverage. maybe a file for includes with the test files to check? (or a config like file).

2020-10-20 22:15 UTC, dsaxton commented
> yeah it think this is ok to add. will have to figure out the best way to expand this coverage. maybe a file for includes with the test files to check? (or a config like file).

The diffs will be very large but it may be easier just to fix this globally for the different classes. I did this for Series just now (can revert if the PR is too large) and could do for DataFrame, etc. if worthwhile.

2020-10-20 22:40 UTC, jreback commented
> > yeah it think this is ok to add. will have to figure out the best way to expand this coverage. maybe a file for includes with the test files to check? (or a config like file).
> 
> The diffs will be very large but it may be easier just to fix this globally for the different classes. I did this for Series just now (can revert if the PR is too large) and could do for DataFrame, etc. if worthwhile.

oh i think this is fine (yeah do DataFrame separately); only issue is have to make sure all passing (in case we are missing imports). ci is a bit cranky now.

2020-10-20 23:21 UTC, jreback commented
and actually merge master once again (as just merged big PR). ping when you are ready.

2020-10-21 00:36 UTC, dsaxton commented
> and actually merge master once again (as just merged big PR). ping when you are ready.

Looks to be mostly green (only annoying thing that can happen are false positives due to Series(...) being used in comments but not code, so I changed those as well)

2020-10-21 00:51 UTC, jreback approved these changes

2020-10-21 00:52 UTC, merged

2020-10-21 00:52 UTC, jreback commented
thanks @dsaxton