BUG: Join behaved like an inner join when only one side had MultiIndex
pandas-dev/pandas pull request #37211
Opened 2020-10-17 23:28 UTC by phofl

- [x] closes #34292
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

We can use the regular path now, since ``droplevel`` can handle an ``Index``. Only difference is a resorted result, because ``Index.join()`` does not preserve the order of the leading input

```
left = pd.Index([0, 1, 2, 1], name="b")
right = pd.Index([1, 2, 5], name="b")
print(left.join(right, how="left"))
```

returns 

```
Int64Index([0, 1, 1, 2], dtype='int64', name='b')
```

2020-10-17 23:48 UTC, phofl commented
The change caused a few other tests to fail, which I have not run locally. All because the new result has a differently sorted index. Is this ok or do we have to figure a way out to get the old behavior?

2021-01-01 22:08 UTC, jreback requested changes
@phofl if you can merge master will have a look

2021-01-01 22:08 UTC, jreback commented on doc/source/whatsnew/v1.2.0.rst
> +- Bug in :func:`join` behaved like an inner join, when one side had a regular :class:`Index` while the other side had a :class:`MultiIndex` (:issue:`34292`)
move to 1.3

2021-01-01 23:58 UTC, phofl commented on doc/source/whatsnew/v1.2.0.rst
> +- Bug in :func:`join` behaved like an inner join, when one side had a regular :class:`Index` while the other side had a :class:`MultiIndex` (:issue:`34292`)
Done

2021-02-11 01:38 UTC, jreback commented
@phofl status here?

2021-06-16 13:49 UTC, simonjayhawkins commented
@phofl closing as stale. reopen when ready.

2021-06-16 13:49 UTC, closed without merging