TYP: DatetimeIndex, TimedeltaIndex
pandas-dev/pandas pull request #37365
Opened 2020-10-23 16:08 UTC by jbrockmendel

Better alternative to parts of #37224

2020-10-26 12:08 UTC, jreback requested changes

2020-10-26 12:08 UTC, jreback commented on pandas/core/indexes/datetimes.py
> +    def _maybe_utc_convert(self, other):
can you type this at all?

2020-10-26 21:03 UTC, jbrockmendel commented on pandas/core/indexes/datetimes.py
> +    def _maybe_utc_convert(self, other):
updated+greenish

2020-10-27 18:05 UTC, jbrockmendel commented on pandas/core/indexes/datetimes.py
> +    def _maybe_utc_convert(self, other):
all the way green

2020-10-29 00:57 UTC, jreback approved these changes

2020-10-29 00:57 UTC, merged