DEPR: Index.__and__, __or__, __xor__ behaving as set ops
pandas-dev/pandas pull request #37374
Opened 2020-10-23 23:25 UTC by jbrockmendel

- [x] closes #36758
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2020-10-24 03:06 UTC, jreback requested changes
can u link to the deprecation removal issue

also pls test the inplace ops produce a warning

eg

|= and so on

2020-10-24 22:36 UTC, jbrockmendel commented
> can u link to the deprecation removal issue

done

> also pls test the inplace ops produce a warning

we dont support inplace ops for these

2020-10-26 03:13 UTC, jreback requested changes

2020-10-26 03:13 UTC, jreback commented on pandas/core/series.py
> -                index |= s.index
we certainly are using this (or at least were), so need to make sure these inplace ops are deprecated as well.

2020-10-31 17:23 UTC, jreback commented on pandas/core/series.py
> -                index |= s.index
can you add some tests for the inplace to make sure they are warning as well

2020-10-31 20:09 UTC, jreback approved these changes

2020-10-31 20:09 UTC, jreback commented
lgtm merge on greenish

2020-11-02 01:02 UTC, merged

2020-11-02 01:02 UTC, jreback commented
thanks @jbrockmendel

2020-11-02 13:42 UTC, jreback commented
hmm this may have broken some tests: https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=46712&view=logs&j=eab14f69-13b6-5db7-daeb-7b778629410b&t=ce687173-08c6-5301-838d-71b2dda24510

2020-11-02 15:00 UTC, jbrockmendel commented
> hmm this may have broken some tests 

just opened #37587 for this