CLN: Deprecate dayofweek/hello day_of_week (#9606)
pandas-dev/pandas pull request #37390
Opened 2020-10-24 22:39 UTC by abhishekmangla

Rename dayofweek properties in Period, Datetime, and PeriodArray classes.
Add day_of_week property to respective tests for each class.

- [ ] closes #9606
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-10-24 23:30 UTC, arw2019 requested changes
Thanks @abhishekmangla for the PR!

Looks good, some comments.

You'll also need to add a whatsnew (v1.2) under enhancements

Let us know if you have any questions!

2020-10-24 23:30 UTC, arw2019 commented on pandas/_libs/tslibs/timestamps.pyx
> +    @property
You don't need to define a second property, set `dayofweek` to be an alias of `day_of_week`

2020-10-24 23:30 UTC, arw2019 commented on pandas/_libs/tslibs/period.pyx
> +    @property
I don't think you need this? Just set dayofweek` to be an alias of `day_of_week`

2020-10-24 23:30 UTC, arw2019 commented on pandas/tests/generic/test_finalize.py
> +        # Add better named field for GH-9606
nit-pick but we usually don't leave comments like this: git/blame keeps track of when changes occurred

2020-10-24 23:30 UTC, arw2019 commented on pandas/tests/indexes/datetimes/test_scalar_compat.py
> +            # Add better named field for GH-9606
same here

2020-10-24 23:30 UTC, arw2019 commented on pandas/tests/indexes/period/test_period.py
> +            # Add better named field for GH-9606
same here

2020-10-25 02:25 UTC, abhishekmangla commented
@arw2019 Thank you for the review. I addressed your comments and added an entry to whatsnew file.

2020-10-25 02:33 UTC, arw2019 requested changes
Thanks for following up on this!

Some more (minor) comments, otherwise good to go IMO

2020-10-25 02:33 UTC, arw2019 commented on doc/source/whatsnew/v1.2.0.rst
> +.. _whatsnew_120.improve_timeseries_accessor_naming:
sorry to be a pain but could you do something short here like the whatsnew in this PR:
 https://github.com/pandas-dev/pandas/pull/9605/files

2020-10-25 02:33 UTC, arw2019 commented on pandas/_libs/tslibs/period.pyx
> +    # Alias dayofweek function to day_of_week (GH-9606)
let's drop this comment

2020-10-25 02:33 UTC, arw2019 commented on pandas/_libs/tslibs/timestamps.pyx
> +    # Alias dayofweek function to day_of_week (GH-9606)
Same here, let's drop this comment

2020-10-25 15:24 UTC, abhishekmangla commented
@arw2019 Resolved minor issues. Do you know how to locally test .rst files, in the CI stage of the checks, I am failing things like
`/home/runner/work/pandas/pandas/pandas/core/indexes/period.py:docstring of pandas.PeriodIndex.rst:77: WARNING: autosummary: stub file not found 'pandas.PeriodIndex.day_of_year'. Check your autosummary_generate setting.
2391`
AND
`/home/runner/work/pandas/pandas/doc/source/whatsnew/v1.2.0.rst:31: WARNING: Explicit markup ends without a blank line; unexpected unindent.`

`./ci/code_checks.sh` shows no errors locally

2020-10-25 17:36 UTC, arw2019 commented
> @arw2019 Resolved minor issues. Do you know how to locally test .rst files? In the CI stage of the checks, I am failing things like
> `/home/runner/work/pandas/pandas/pandas/core/indexes/period.py:docstring of pandas.PeriodIndex.rst:77: WARNING: autosummary: stub file not found 'pandas.PeriodIndex.day_of_year'. Check your autosummary_generate setting. 2391`

I think you (maybe) need to add the new methods to the rst files manually - for example in doc/source/reference/series.rst both    daysinmonth and days_in_month are listed

> `/home/runner/work/pandas/pandas/doc/source/whatsnew/v1.2.0.rst:31: WARNING: Explicit markup ends without a blank line; unexpected unindent.`

This one is a linting issue

2020-10-26 13:39 UTC, abhishekmangla commented
@arw2019 The only unit test that is failing on Azure pipeline is `test_binary_arith_ops` which seems to be a known unreliable test (#37328). (The test suite passes on my macOS machine)

Is this good to merge now?

2020-10-26 13:45 UTC, jreback requested changes
this is fine. ping on green.

2020-10-26 13:45 UTC, jreback commented on doc/source/whatsnew/v1.2.0.rst
> +.. _whatsnew_120.improve_timeseries_accessor_naming:
you can just put these notes in Other Enhancements section

2020-10-26 13:45 UTC, jreback commented on doc/source/whatsnew/v1.2.0.rst
> +:class:`Series` and :class:`DataFrame` can now be created with ``allows_duplicate_labels=False`` flag to control whether the index or columns can contain duplicate labels (:issue:`28394`). This can b
pls don't adjust other notes

2020-10-26 13:45 UTC, jreback commented
@pandas-dev/pandas-core should we do a DeprecationWarning / FutureWarning on the original attributes? (would be a followon)

2020-10-26 16:58 UTC, abhishekmangla commented
@jreback All checks green except aforementioned `test_binary_arith_ops`

2020-10-29 01:18 UTC, merged

2020-10-29 01:19 UTC, jreback commented
thanks @abhishekmangla very nice