BUG: Metadata propagation for groupby iterator
pandas-dev/pandas pull request #37461
Opened 2020-10-28 07:30 UTC by Japanuspus

Addresses part of #28283

This PR ensures that `__finalize__` is called for objects returned by iterator over `.groupby`-results.
Based on the discussion and benchmarks in PR #35688 (see https://github.com/pandas-dev/pandas/pull/35688#issuecomment-675367517), `__finalize__` is _not_ called for intermediate objects used by `.apply` (and maybe other code paths).

The implemented solution is the safe choice with regard to performance: An alternative solution would be to call `__finalize__` immediately after initialization (in `DataSplitter._chop()`).
The downside to doing so would be the performance hit due to the overhead of finalizing intermediate objects in `.apply` (and maybe other code paths).  In the benchmarks referenced above, this amounted to around 4%.
The upside of finalizing immediately after initialization would be reduced complexity and that it would allow `.apply` (and any other code paths using the (`DataSplitter._chop`) to access metadata.

Have not opened a ticket for this specific sub-issue of #28283, nor included a whatsnew entry.

- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-10-28 08:26 UTC, Japanuspus commented
@jorisvandenbossche You asked about this PR. Do you have any position on the performance question? Would you be able to review?

I will have a look at the failing tests.

2020-10-29 16:24 UTC, simonjayhawkins commented
Thanks @Japanuspus for the PR.

> Addresses part of #28283

This PR may also fix #37343, see https://github.com/pandas-dev/pandas/issues/37343#issuecomment-718864907

If you could add a test for that issue, that'll be great. Also if you could keep the changes in this PR minimal as we would likely want to backport this.

2020-10-30 09:22 UTC, Japanuspus commented
Thanks @simonjayhawkins! 

> This PR may also fix #37343, see [#37343 (comment)](https://github.com/pandas-dev/pandas/issues/37343#issuecomment-718864907)
> 
> If you could add a test for that issue, that'll be great. Also if you could keep the changes in this PR minimal as we would likely want to backport this.

Yes, this was exactly the issue that I saw in my own code as well after the 1.1 update. I will add a test. It appears I need to merge 2414c75bfe06064a95d8da4db5c8248e5aa0cdbb to get passing tests: will rebase and force push to keep things clean for backport.

2020-10-30 10:25 UTC, Japanuspus commented
Still seeing unrelated test failures. Will try waiting for things to settle down once 1.1.4 is released.

2020-10-30 15:36 UTC, jreback requested changes
can you also update the metadata issue in the 1.2 whatsnew (just add the issue number on)

2020-10-30 15:36 UTC, jreback commented on pandas/tests/groupby/test_grouping.py
> +
hmm i think we have other metadata tests for groupby, so nothing broke?

2020-10-30 18:07 UTC, jbrockmendel commented
Does something similar need to be done for the cython path?

2020-11-02 08:54 UTC, Japanuspus commented
> Does something similar need to be done for the cython path?

I believe not: The functional change is in `BaseGrouper.get_iterator` which does not appear to have a cython alternative path.

2020-11-02 15:17 UTC, simonjayhawkins commented
@jreback are you OK with backporting this?

2020-11-02 21:23 UTC, jreback commented
> @jreback are you OK with backporting this?

actually this is fine to backport. 

@Japanuspus can you update the whatsnew note to put in 1.1.5

2020-11-02 21:24 UTC, jreback requested changes
lgtm if you can move the note and merge master. ping on green-ish.

2020-11-02 21:24 UTC, jreback commented on doc/source/whatsnew/v1.2.0.rst
> +- Bug in metadata propagation for ``groupby`` iterator (:issue:`37343`)
move to 1.1.5

2020-11-04 10:29 UTC, Japanuspus commented on doc/source/whatsnew/v1.2.0.rst
> +- Bug in metadata propagation for ``groupby`` iterator (:issue:`37343`)
Done. Force pushed to drop this commit.

2020-11-04 11:24 UTC, simonjayhawkins commented
> lgtm if you can move the note and merge master. ping on green-ish.

32 bit failure unrelated. (caused by recent merge to master of #36842)

2020-11-04 13:22 UTC, jreback approved these changes

2020-11-04 13:22 UTC, merged

2020-11-04 13:22 UTC, jreback commented
thanks @Japanuspus

2020-11-04 13:26 UTC, simonjayhawkins commented
@meeseeksdev backport 1.1.x