BUG: Series.replace does not preserve dtype of original Series
pandas-dev/pandas pull request #37512
Opened 2020-10-30 03:11 UTC by arw2019

- [x] closes #33484
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Reheating #33622 (stale)

2020-11-02 13:49 UTC, jreback requested changes

2020-11-02 13:49 UTC, jreback commented on pandas/core/internals/blocks.py
> +        if is_categorical_dtype(dtype) or self.is_datetime:
the is_datetime condition is already handled above, if for some reason you actually need to do this then do it above (and I am not really sure why you are trying to do this)

2020-11-02 13:49 UTC, jreback commented on pandas/core/internals/blocks.py
> +        if is_extension_array_dtype(self.dtype) and not is_categorical_dtype(dtype):
this if/then is already very complicated, what is the intent here?

2020-11-07 04:13 UTC, arw2019 commented
Coverting to draft while I debug

2020-11-11 01:36 UTC, jbrockmendel commented
@arw2019 the underlying problem (or one of them at least) is that ExtensionBlock._can_hold_element and ExtensionBlock.putmask are completely FUBAR.

I suggest you try adding the two following methods to CategoricalBlock (taken from a branch I have trying to get rid of CategoricalBlock.replace and _replace_list)

```
    def _can_hold_element(self, element: Any) -> bool:
        try:
            self.values._validate_setitem_value(element)
            return True
        except (TypeError, ValueError):
            return False

    def putmask(
        self, mask, new, inplace: bool = False, axis: int = 0, transpose: bool = False
    ) -> List["Block"]:
        if self._can_hold_element(new):
            return super().putmask(mask, new, inplace, axis, transpose)

        # TODO: should this be inplace?
        # TODO: use coerce_to_target_dtype?
        cat = self.values.add_categories(new)
        nb = self.make_block(cat)
        assert nb._can_hold_element(new)
        return nb.putmask(mask, new, inplace, axis, transpose)
```

and in coerce_to_target_dtype just after the is_dtype_equal(self.dtype, dtype) check:

```
        if self._can_hold_element(other):
            return self
        elif self.is_categorical:
            # Note: this will be wrong if we ever have a tuple category
            cat = self.values.add_categories(other)
            return self.make_block(cat)
```

This changes the behavior for a handful of tests causing Series/DataFrame.replace to return CategoricalDtype (with added categories) instead of object-dtype, so may not be _quite_ what we want.  But I'm pretty sure its in the right ballpark.

2020-11-11 19:32 UTC, arw2019 commented
> if self._can_hold_element(other):
>             return self
>         elif self.is_categorical:
>             # Note: this will be wrong if we ever have a tuple category
>             cat = self.values.add_categories(other)
>             return self.make_block(cat)

Thanks!!! Pushed this, will see what fails

2020-11-11 20:46 UTC, closed without merging

2020-11-11 21:06 UTC, jbrockmendel commented
cc @jorisvandenbossche the latest commit here is pretty much exactly the edits i was referring to re CategoricalBlock.replace.  Only difference is I would also remove CategoricalBlock.replace and _replace_list.