refactor core/arrays
pandas-dev/pandas pull request #37581
Opened 2020-11-02 11:36 UTC by MarcoGorelli

Some refactorings found by Sourcery https://sourcery.ai/

I've removed the ones of the kind
```diff
- if param:
-     var = a
- else:
-     var = b
+ var = a if param else b
```

2020-11-02 14:34 UTC, jreback requested changes

2020-11-02 14:34 UTC, jreback commented on pandas/core/arrays/boolean.py
> +        if inferred_dtype in integer_like and not np.all(
would use parens here to make this easier to read / line up

2020-11-02 14:34 UTC, jreback commented on pandas/core/arrays/sparse/array.py
> +        if fcounts > 0 and (not self._null_fill_value or not dropna):
this is nice but it may have changed the semantics

2020-11-02 22:43 UTC, jreback commented
this is failing checks

2020-11-04 07:58 UTC, MarcoGorelli commented
> this is failing checks

Yes, the change
```diff
-        for i in range(len(self)):
-            yield self[i]
+        yield from self
```
was throwing a RecursionError

2020-11-04 13:47 UTC, jreback approved these changes

2020-11-04 13:47 UTC, merged

2020-11-04 13:47 UTC, jreback commented
thanks @MarcoGorelli