BUG: nunique not ignoring both None and np.nan
pandas-dev/pandas pull request #37607
Opened 2020-11-03 16:52 UTC by GYHHAHA

- [ ] closes #37566
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-11-03 16:52 UTC, pep8speaks commented
Hello @GYHHAHA! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/base/test_unique.py`](https://github.com/pandas-dev/pandas/blob/7f91c9009cc29a6b497a458b5487d1c0819287ed/pandas/tests/base/test_unique.py):

> [Line 125:1](https://github.com/pandas-dev/pandas/blob/7f91c9009cc29a6b497a458b5487d1c0819287ed/pandas/tests/base/test_unique.py#L125): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 127:25](https://github.com/pandas-dev/pandas/blob/7f91c9009cc29a6b497a458b5487d1c0819287ed/pandas/tests/base/test_unique.py#L127): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 128:27](https://github.com/pandas-dev/pandas/blob/7f91c9009cc29a6b497a458b5487d1c0819287ed/pandas/tests/base/test_unique.py#L128): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 128:29](https://github.com/pandas-dev/pandas/blob/7f91c9009cc29a6b497a458b5487d1c0819287ed/pandas/tests/base/test_unique.py#L128): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 131:1](https://github.com/pandas-dev/pandas/blob/7f91c9009cc29a6b497a458b5487d1c0819287ed/pandas/tests/base/test_unique.py#L131): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 131:1](https://github.com/pandas-dev/pandas/blob/7f91c9009cc29a6b497a458b5487d1c0819287ed/pandas/tests/base/test_unique.py#L131): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2020-11-03 22:09 UTC, arw2019 requested changes
Thanks @GYHHAHA for the PR!

Some comments

2020-11-03 22:09 UTC, arw2019 commented on pandas/core/base.py
> +        if dropna:
I'd do
``` python
obj = self.dropna() if dropna else self
return len(obj.unique())
```

2020-11-03 22:09 UTC, arw2019 commented on pandas/tests/base/test_unique.py
> +    # test for #37566
Do `# GH37566`

2020-11-03 22:09 UTC, arw2019 commented on pandas/tests/base/test_unique.py
> +def test_nunique_dropna():
Parametrize on `dropna` (True/False)

2020-11-03 22:09 UTC, arw2019 commented on pandas/tests/base/test_unique.py
> +    res = s.nunique(dropna=True)
just do `assert res == 1`

2020-11-03 22:09 UTC, arw2019 commented on doc/source/whatsnew/v1.2.0.rst
> +- Bug in :meth:`nunique` with ``dropna = True`` returns wrong result when different kinds of NA-like values exist (:issue:`37566`)
```
Bug in :meth:`Series.nunique` with ``dropna = True`` was returning incorrect results when both ``NA`` and ``None`` missing values were present (:issue:`37566`)
```

2020-11-04 01:53 UTC, GYHHAHA commented
This fails. So we can't use `dropna` in `IndexOpsMixin` even if this is inherited by both index and series which have `dropna` method? @arw2019 
```
Performing static analysis using mypy
pandas/core/base.py:1035: error: "IndexOpsMixin" has no attribute "dropna"  [attr-defined]
```

2020-11-04 06:48 UTC, arw2019 commented on pandas/tests/base/test_unique.py
> +    res = s.nunique(dropna=True)
`res = s.nunique(dropna)` here, no?

2020-11-04 06:49 UTC, arw2019 requested changes
One more comment, o/w lgtm

2020-11-04 07:54 UTC, arw2019 approved these changes

2020-11-10 01:02 UTC, phofl commented on doc/source/whatsnew/v1.2.0.rst
> +- Bug in :meth:`Series.nunique` with ``dropna = True`` was returning incorrect results when both ``NA`` and ``None`` missing values were present (:issue:`37566`)
Could you delete spaces around ``=``?

2020-11-10 01:20 UTC, GYHHAHA commented on doc/source/whatsnew/v1.2.0.rst
> +- Bug in :meth:`Series.nunique` with ``dropna = True`` was returning incorrect results when both ``NA`` and ``None`` missing values were present (:issue:`37566`)
done

2020-11-10 03:28 UTC, jreback commented
looks good, just @phofl comment i think is left, ping on green.

2020-11-10 06:07 UTC, GYHHAHA commented
cc @jreback

2020-11-10 23:41 UTC, merged

2020-11-10 23:41 UTC, jreback commented
thanks @GYHHAHA very nice

2020-11-11 17:03 UTC, jorisvandenbossche commented on pandas/core/base.py
> +        obj = remove_na_arraylike(self) if dropna else self
Late comment, but would it be more performant if we removed the NAs *after* calculating the uniques? (assume the uniques is typically a much smaller array, and not this does an extra scan and creates a copy of the full array)