DOC: test organization
pandas-dev/pandas pull request #37637
Opened 2020-11-04 23:49 UTC by jbrockmendel

Documenting the MO behind the test organization we've been doing.

1) I expect this is not valid rst ATM
2) The style does not match the rest of the docs, so probably needs a re-write.

2020-11-08 02:25 UTC, jreback requested changes
lgtm small comments.

2020-11-08 02:25 UTC, jreback commented on doc/source/development/test_writing.rst
> +        This test likely belongs in one of:
can you be a little more precise here (e.g. do we have criteria for putting in pandas/tests/indexing over the frame/series ones? (can be a TODO of course)

2020-11-08 02:25 UTC, jreback commented on doc/source/development/index.rst
> +    test_writing
maybe put after internals

2020-11-11 00:19 UTC, merged

2020-11-11 00:19 UTC, jreback commented
thanks @jbrockmendel very nice

2020-11-11 04:32 UTC, jbrockmendel commented
i think this might have been merged prematurely, the docbuild is complaining about rst stuff i need to figure out

2020-11-11 09:22 UTC, jorisvandenbossche commented
@jbrockmendel if you push your branch again, I *think* you should be able to reopen the PR (unless you also already deleted the branch locally), and then we can work out the failures here