REF: implement Categorical.encode_with_my_categories
pandas-dev/pandas pull request #37650
Opened 2020-11-05 15:18 UTC by jbrockmendel

Categorical._validate_listlike is misleading, since it treats not-in-categories entries as NAs, whereas we usually want to raise when we see those.  This implements the more obviously-named encode_with_my_categories

2020-11-08 02:16 UTC, jreback requested changes

2020-11-08 02:16 UTC, jreback commented on pandas/core/arrays/categorical.py
> +    def encode_with_my_categories(self, other: "Categorical") -> "Categorical":
should be a private method

2020-11-08 02:37 UTC, jbrockmendel commented on pandas/core/arrays/categorical.py
> +    def encode_with_my_categories(self, other: "Categorical") -> "Categorical":
sure, will update

2020-11-08 15:22 UTC, jbrockmendel commented on pandas/core/arrays/categorical.py
> +    def encode_with_my_categories(self, other: "Categorical") -> "Categorical":
privatized + green

2020-11-09 00:37 UTC, jreback approved these changes

2020-11-09 00:37 UTC, merged