BUG: unpickling modifies Block.ndim
pandas-dev/pandas pull request #37657
Opened 2020-11-06 00:38 UTC by jbrockmendel

- [x] closes #37631
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2020-11-08 02:21 UTC, jreback requested changes

2020-11-08 02:21 UTC, jreback commented on doc/source/whatsnew/v1.2.0.rst
> +- Bug in indexing on a :class:`Series` with ``CategoricalDtype`` after unpickling (:issue:`37631`)
i think let's move this to 1.1.5

2020-11-08 15:22 UTC, jbrockmendel commented on doc/source/whatsnew/v1.2.0.rst
> +- Bug in indexing on a :class:`Series` with ``CategoricalDtype`` after unpickling (:issue:`37631`)
note moved + green

2020-11-09 00:37 UTC, jreback approved these changes

2020-11-09 00:38 UTC, merged

2020-11-09 11:10 UTC, simonjayhawkins commented
@meeseeksdev backport 1.1.x