REF: dont support dt64tz in nanmean
pandas-dev/pandas pull request #37658
Opened 2020-11-06 01:36 UTC by jbrockmendel

nanmean is annotated as taking a ndarray, no reason for it to support dt64tz

2020-11-08 02:15 UTC, jreback requested changes
rebase as well

2020-11-08 02:15 UTC, jreback commented on pandas/core/nanops.py
>      if result is NaT:
can you add an assert here as well

2020-11-08 02:43 UTC, jbrockmendel commented on pandas/core/nanops.py
>      if result is NaT:
what do you want to assert?

2020-11-08 15:21 UTC, jbrockmendel commented
rebased+green

2020-11-09 00:38 UTC, jreback approved these changes

2020-11-09 00:38 UTC, merged