DOC: Highlight pre-commit section
pandas-dev/pandas pull request #37701
Opened 2020-11-08 12:36 UTC by hongshaoyang

- [x] closes #37358 
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2020-11-08 12:41 UTC, hongshaoyang commented
I noticed that https://dev.pandas.io/ is not up to date, is this intended?

2020-11-08 12:47 UTC, hongshaoyang commented
~~I noticed that https://dev.pandas.io/ is not up to date, is this intended?~~

it seems like this is intentional and that latest docs from `master` are at https://pandas.pydata.org/docs/dev/, see #37248.

2020-11-09 00:44 UTC, jreback commented
looks fine to me. @MarcoGorelli if you can have a look see

2020-11-09 15:31 UTC, MarcoGorelli requested changes
Looks good, thanks, just suggesting some minor changes

2020-11-09 15:31 UTC, MarcoGorelli commented on doc/source/development/contributing.rst
> +format throughout the project. We encourage you to use :ref:`pre-commits <contributing.pre-commit>`.
```suggestion
format throughout the project. We encourage you to use :ref:`pre-commit <contributing.pre-commit>`.
```

2020-11-09 15:31 UTC, MarcoGorelli commented on doc/source/development/code_style.rst
> +:ref:`pre-commits <contributing.pre-commit>` to automatically run ``black``,
```suggestion
:ref:`pre-commit <contributing.pre-commit>` to automatically run ``black``,
```

2020-11-09 15:31 UTC, MarcoGorelli commented on doc/source/development/contributing.rst
> +In addition, using this pre-commit hook will also allow you to more easily
```suggestion
In addition, using ``pre-commit`` will also allow you to more easily
```

2020-11-09 15:31 UTC, MarcoGorelli commented on doc/source/development/contributing.rst
> +to run its checks by running::
```suggestion
If you don't want to use ``pre-commit`` as part of your workflow, you can still use it
to run its checks with::
```

2020-11-09 15:31 UTC, MarcoGorelli commented on doc/source/development/contributing.rst
> +without having to have done ``pre-commit install`` beforehand.
```suggestion
without needing to have done ``pre-commit install`` beforehand.
```

2020-11-10 02:20 UTC, hongshaoyang commented
Thanks @MarcoGorelli , applied your suggestions.

2020-11-10 03:27 UTC, jreback commented
lgtm. cc @MarcoGorelli merge when ready

2020-11-10 09:42 UTC, merged

2020-11-10 09:42 UTC, MarcoGorelli commented
Thanks @hongshaoyang