DOC: add unqiue value counts example to groupyby guide
pandas-dev/pandas pull request #37847
Opened 2020-11-14 19:28 UTC by Abo7atm

Co-authored-by: Abdulelah Almesfer <28743265+abdulelahsm@users.noreply.github.com>
Co-authoerd-by: Abdulellah Alnumay <33042538+Abo7atm@users.noreply.github.com>

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Adding an example to the groupby user guide. The example showcases the usage of ```nunique``` aggregate function. This is from the PyData Global sprint, from [this issue](https://github.com/MarcoGorelli/PyDataGlobal2020-sprint/issues/5). The example is taken from [StackOverflow](https://stackoverflow.com/questions/15411158/pandas-countdistinct-equivalent).

2020-11-15 11:57 UTC, MarcoGorelli requested changes
Thanks @Abo7atm

For context, this is a common duplicate on StackOverflow, so I think it's good to include it in the docs.

Did you try building this page of the docs locally? If so, can you post a screenshot of this new section?

2020-11-15 11:57 UTC, MarcoGorelli commented on doc/source/user_guide/groupby.rst
> +Another aggregation example is to compute the number of unique values of a group. This is similar to the ``value_counts`` function, execpt that ``value_counts`` return the number of all values instea
```suggestion
Another aggregation example is to compute the number of unique values of each group. This is similar to the ``value_counts`` function, except that it only counts unique values.
```

2020-11-15 11:57 UTC, MarcoGorelli commented on doc/source/user_guide/groupby.rst
> +   pd.DataFrame(ll, columns=['A', 'B']).groupby('A').nunique()
```suggestion
   pd.DataFrame(ll, columns=["A", "B"]).groupby("A")["B"].nunique()
```

2020-11-15 15:42 UTC, Abo7atm commented
![Screen Shot 2020-11-15 at 18 40 51](https://user-images.githubusercontent.com/33042538/99189442-38585480-2772-11eb-9ad1-505dd028addc.png)

2020-11-18 13:49 UTC, jreback requested changes

2020-11-18 13:49 UTC, jreback commented on doc/source/user_guide/groupby.rst
> +   pd.DataFrame(ll, columns=["A", "B"]).groupby("A")["B"].nunique()
can you first show the input df, then do the groupby.nunique on the next line

2020-11-18 14:41 UTC, Abo7atm commented
@jreback done 👍

2020-11-24 13:51 UTC, jreback commented
can you merge master @Abo7atm the precommit checks are failing

2020-11-24 15:48 UTC, Abo7atm commented
@jreback merged master and ran precommit locally with `pre-commit run --files doc/source/user_guide/groupby.rst` and everything passed.

2020-11-25 13:30 UTC, jreback approved these changes

2020-11-25 13:30 UTC, merged

2020-11-25 13:30 UTC, jreback commented
thanks @Abo7atm