Added examples
pandas-dev/pandas pull request #37844
Opened 2020-11-14 19:05 UTC by nguevara

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-11-14 19:32 UTC, MarcoGorelli requested changes
Thanks @nguevara

2020-11-14 19:32 UTC, MarcoGorelli commented on pandas/_testing.py
> +    Examples
can you add a new line before `Examples`?

2020-11-14 19:32 UTC, MarcoGorelli commented on pandas/_testing.py
> +    >>> a=pd.Index([1,2,3])
can you add spaces around the `=`? so `a = pd.Index`...

2020-11-14 20:11 UTC, jorisvandenbossche commented on pandas/_testing.py
> +    >>> from pandas._testing import assert_index_equal
The public import is `pandas.testing`, can you use that?

2020-11-15 09:18 UTC, MarcoGorelli requested changes
Thanks @nguevara ! Just making a nitpick comment to make the style more consistent with the rest of the codebase

2020-11-15 09:18 UTC, MarcoGorelli commented on pandas/_testing.py
> +    >>> assert_series_equal(a,b)
```suggestion
    >>> a = pd.Series([1, 2, 3, 4])
    >>> b = pd.Series([1, 2, 3, 4])
    >>> assert_series_equal(a, b)
```

2020-11-15 09:18 UTC, MarcoGorelli commented on pandas/_testing.py
> +    >>> assert_extension_array_equal(b,c)
```suggestion
    >>> a = pd.Series([1, 2, 3, 4])
    >>> b, c = a.array, a.array
    >>> assert_extension_array_equal(b, c)
```

2020-11-15 09:18 UTC, MarcoGorelli commented on pandas/_testing.py
> +    >>> assert_index_equal(a,b)
```suggestion
    >>> a = pd.Index([1, 2, 3])
    >>> b = pd.Index([1, 2, 3])
    >>> assert_index_equal(a, b)
```

2020-11-16 20:38 UTC, jorisvandenbossche approved these changes

2020-11-16 20:39 UTC, merged

2020-11-16 20:39 UTC, jorisvandenbossche commented
Thanks a lot @nguevara !