Feature/docstrings errors
pandas-dev/pandas pull request #37904
Opened 2020-11-16 23:58 UTC by lucasrodes

Example section added for several methods in class [pd.Timestamp](https://github.com/pandas-dev/pandas/blob/1f89b82cc65f512e78b0038975425cc3d0772a05/pandas/_libs/tslibs/timestamps.pyx#L768)

- [X] xref #37875
- [X] tests added / passed
- [X] passes `black pandas`
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-11-17 11:43 UTC, lucasrodes commented
From the checks, I believe that there are some docstrings that were not supposed to be changed? 

I am starting to contribute and trying to follow up on this #17327

2020-11-19 02:46 UTC, jreback requested changes
looks good a couple of comments. pls merge master and ping on green.

2020-11-19 02:46 UTC, jreback commented on pandas/_libs/tslibs/timestamps.pyx
> +        numpy.datetime64('2020-03-14T15:32:52.192548651')
can you put a blank line between cases

2020-11-19 02:46 UTC, jreback commented on pandas/_libs/tslibs/timestamps.pyx
> +        Timestamp('2020-03-14 15:33:00')
can you put a blank line between cases

2020-11-19 02:46 UTC, jreback commented on pandas/_libs/tslibs/timestamps.pyx
> +        >>> ts.floor(freq='T') # minute
same

2020-11-19 02:46 UTC, jreback commented on pandas/_libs/tslibs/timestamps.pyx
> +        >>> ts.floor(freq='L') # miliseconds
prob can show just a few rather than all

2020-11-19 02:46 UTC, jreback commented on pandas/_libs/tslibs/timestamps.pyx
> +        >>> ts.ceil(freq='S') # seconds
same comment

2020-11-20 03:14 UTC, jreback commented
can you merge master and ping on green (to make sure no failures are real).

2020-11-20 16:07 UTC, lucasrodes commented
Added few changes to [pandas/_libs/tslibs/nattype.pyx](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslibs/nattype.pyx) so the docstrings match. Should pass the tests now, I'll ping you again. specially this one below:

https://github.com/pandas-dev/pandas/blob/456fcb9829f4e8fba200658efff6ba26152009cd/pandas/tests/scalar/test_nat.py#L326

2020-11-20 17:06 UTC, lucasrodes commented
@jreback passing all tests

2020-11-20 17:07 UTC, lucasrodes commented on pandas/_libs/tslibs/timestamps.pyx
> +        Timestamp('2020-03-14 15:33:00')
Done

2020-11-20 17:08 UTC, lucasrodes commented on pandas/_libs/tslibs/timestamps.pyx
> +        numpy.datetime64('2020-03-14T15:32:52.192548651')
Done

2020-11-20 17:08 UTC, lucasrodes commented on pandas/_libs/tslibs/timestamps.pyx
> +        >>> ts.floor(freq='T') # minute
Done

2020-11-20 17:08 UTC, lucasrodes commented on pandas/_libs/tslibs/timestamps.pyx
> +        >>> ts.ceil(freq='S') # seconds
Done

2020-11-21 22:33 UTC, jreback requested changes
ok happy for you to revert the nattype updates and we can address in another PR. ping on green.

2020-11-21 22:33 UTC, jreback commented on pandas/_libs/tslibs/nattype.pyx
> +        Examples
these need to be NaT examples (same for anything in nattype)

2020-11-23 17:04 UTC, lucasrodes commented
Sure @jreback, can do that. However, this pull request won't go through the tests as I mentioned before (won't be green). Should we merge it regardless?

2020-11-24 16:16 UTC, lucasrodes commented
@jreback changes reverted

2020-11-25 23:42 UTC, jreback commented
> Sure @jreback, can do that. However, this pull request won't go through the tests as I mentioned before (won't be green). Should we merge it regardless?

oh how is master passing now then?

yeah this needs to be green. ok i guess re-revert. the only thing with the NaT tests is that they should be showing NaT int he examples

2020-11-26 11:33 UTC, lucasrodes commented
Hi @jreback ,
The test I attach below is checking if the docstrings between methods in  [pandas/_libs/tslibs/nattype.pyx](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslibs/nattype.pyx) and  [pandas/_libs/tslibs/timestamps.pyx](pandas/_libs/tslibs/timestamps.pyx) match. That's why I also used pd.Timestamp instead of pd.NaT.

https://github.com/pandas-dev/pandas/blob/456fcb9829f4e8fba200658efff6ba26152009cd/pandas/tests/scalar/test_nat.py#L326


 Should we maybe change the test [pandas/pandas/tests/scalar/test_nat.py](pandas/pandas/tests/scalar/test_nat.py) in onther PR?

2020-11-26 16:49 UTC, jreback commented
> Hi @jreback ,
> The test I attach below is checking if the docstrings between methods in [pandas/_libs/tslibs/nattype.pyx](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslibs/nattype.pyx) and [pandas/_libs/tslibs/timestamps.pyx](pandas/_libs/tslibs/timestamps.pyx) match. That's why I also used pd.Timestamp instead of pd.NaT.
> 
> https://github.com/pandas-dev/pandas/blob/456fcb9829f4e8fba200658efff6ba26152009cd/pandas/tests/scalar/test_nat.py#L326
> 
> Should we maybe change the test [pandas/pandas/tests/scalar/test_nat.py](pandas/pandas/tests/scalar/test_nat.py) in onther PR?

ok instead let's use the same doc-string, BUT add a NaT example to it, this should make tests pass and make the examples useful.

ping on green.

2020-11-27 10:31 UTC, lucasrodes commented
test

2020-11-27 15:05 UTC, lucasrodes commented
Error in the following test from [pandas/tests/io/test_gcs.py](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/io/test_gcs.py) in Windows. Not sure what is causing it.


https://github.com/pandas-dev/pandas/blob/5abc06fbb9b9f7cf63059695bf7fa87d9b57df5c/pandas/tests/io/test_gcs.py#L83-L119

2020-11-27 15:07 UTC, lucasrodes commented
On another note:

Hi @jreback, thanks for your feedback.

Let me summarize last commits below.

### 1) `NaT` examples added
I have added examples with NaT in the docstrings of the following functions in [nattype.pyx](
https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslibs/nattype.pyx) and [timestamps.pyx](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslibs/timestamps.pyx):

- tz_convert
- tz_localize
- today
- to_pydatetime
- to_numpy
- round
- replace
- now
- month_name
- floor
- day_name
- ceil

Hence, **these methods now have the same docstring in both modules and should pass the tests** :heavy_check_mark:.

### 2) `NaT` examples not added
Next, I have not added `NaT` examples in the following examples as **these methods basically raise a `ValueError` if called from a `NaT` object**. However I have copied the docstrings from [timestamps.pyx](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslibs/timestamps.pyx) (otherwise tests are not passed).

- utcnow
- utcfromtimestamp
- timestamp
- strftime
- fromtimestamp
- fromordinal
- combine
- astimezone

Note that these methods were created using method [`_make_error_func`](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslibs/nattype.pyx#L67) instead of [`_make_nat_func`](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslibs/nattype.pyx#L59) or [`_make_nan_func`](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslibs/nattype.pyx#L51).

As **these methods now have the same docstring in both modules and should pass the tests** :heavy_check_mark:.

---

### 3) Way forward

From here I see three ways out:

A) Review of this PR, iterate and merge.
B) Remove the Example section from all methods listed in 2) in both modules (so docstrings still match), commit, review and merge PR.
C) Review the tests in [test_nat.pyx](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/scalar/test_nat.py). In particular the parametrization of `compare`. Probably another PR is required.

https://github.com/pandas-dev/pandas/blob/11a5a4b1b11ad68999b6d153cca99907db43affe/pandas/tests/scalar/test_nat.py#L319-L334

2020-12-28 00:40 UTC, jreback commented
@lucasrodes i am ok prob merging this as is, if you can merge master and ping

2021-02-11 01:37 UTC, jreback commented
@lucasrodes this was close. if you can merge master and see if can get all passing.

2021-02-13 14:49 UTC, lucasrodes commented
Sorry for the late reply @jreback. Will do asap

2021-02-17 20:07 UTC, lucasrodes commented
@jreback merged with master

2021-03-21 00:40 UTC, mroeschke commented on pandas/_libs/tslibs/nattype.pyx
> +        Timestamp('2020-03-14 15:32:52.192548651+0100', tz='Europe/Stockholm'
Missing an ending `)`

2021-03-21 00:42 UTC, mroeschke commented
Sorry for the long delay @lucasrodes . Looks mostly good. One comment otherwise LGTM

2021-03-21 15:08 UTC, lucasrodes commented
@mroeschke Merged with upstream & fixed typos (missing '(' in docstring examples)

2021-03-21 17:22 UTC, mroeschke approved these changes

2021-04-30 00:47 UTC, merged

2021-04-30 00:47 UTC, mroeschke commented
Thanks @lucasrodes! Apologies for the long wait getting this one in.