BUG: fix sharey overwrite on area plots
pandas-dev/pandas pull request #37943
Opened 2020-11-18 18:00 UTC by lrusnac

- [x] closes #37942
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2020-11-18 18:00 UTC, pep8speaks commented
Hello @lrusnac! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/plotting/_matplotlib/core.py`](https://github.com/pandas-dev/pandas/blob/32ef66317dfc06ba76993b5d5a97bdb1206e5144/pandas/plotting/_matplotlib/core.py):

> [Line 1343:50](https://github.com/pandas-dev/pandas/blob/32ef66317dfc06ba76993b5d5a97bdb1206e5144/pandas/plotting/_matplotlib/core.py#L1343): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2020-11-19 02:43 UTC, jreback requested changes
can you add a test which replicates the original behavior and resolves with the patch.

2020-11-19 09:14 UTC, lrusnac commented
Hey @jreback, I was looking into that but could not locate any area plots tests, could you suggest a suitable location such a test? is it worth starting a similar file like https://github.com/pandas-dev/pandas/blob/master/pandas/tests/plotting/test_hist_method.py for area_method? if so perhaps that should be bigger task at testing the area plots in general?

2020-11-19 09:42 UTC, charlesdong1991 commented
could put the tests to `pandas/tests/plotting/frame/test_frame.py` (and `pandas/tests/plotting/test_series.py` if you want to have it tested for `Series`)

2020-11-19 15:49 UTC, lrusnac commented
@charlesdong1991 thanks for the pointers, should have looked closer there indeed 😅 
@jreback some tests added now

2020-11-19 18:38 UTC, jreback approved these changes
lgtm @charlesdong1991

2020-11-19 19:18 UTC, charlesdong1991 requested changes
Thanks for the PR!

I just have one minor comment on whatsnew, plus a general question: what if users explicitly specify `sharey=False` in `df.plot`? Will `sharey` previously defined by matplotlib be overridden by pandas (I know such a setting is very silly)?

something like below using example from your test:
```python
df = DataFrame(np.random.rand(4, 2), columns=["x", "y"])
fig, (ax1, ax2) = plt.subplots(1, 2, sharey=True)

df.plot(ax=ax1, kind="area", sharey=False)
df.plot(ax=ax2, kind="area", sharey=False)
```

2020-11-19 19:46 UTC, lrusnac commented on doc/source/whatsnew/v1.2.0.rst
> +- Bug in :meth:`DataFrame.plot` was overwriting matplotlib's shared y axes behaviour when no sharey parameter was passed (:issue:`37942`)
yeah, they both share the same method in the end

2020-11-19 19:51 UTC, lrusnac commented
> Thanks for the PR!
> 
> I just have one minor comment on whatsnew, plus a general question: what if users explicitly specify `sharey=False` in `df.plot`? Will `sharey` previously defined by matplotlib be overridden by pandas (I know such a setting is very silly)?
> 
> something like below using example from your test:
> 
> ```python
> df = DataFrame(np.random.rand(4, 2), columns=["x", "y"])
> fig, (ax1, ax2) = plt.subplots(1, 2, sharey=True)
> 
> df.plot(ax=ax1, kind="area", sharey=False)
> df.plot(ax=ax2, kind="area", sharey=False)
> ```

that's a fair question, to me that doesn't make much sense, I see the use of sharey in the plot only when it's pandas to make multiple plots, if you specify an ax then it's a bit weird option in my interpretation. 

that said, the line plots for instance are not overwriting the behaviour, it's specific to area plots where in the end it sets the min or max limit to 0, and in the process resets the other extreme too.

that's all to say that if you pass a specific False, then pandas should maybe overwrite the default with False (to be tested how the line plots handle that actually).

2020-11-19 19:56 UTC, lrusnac commented
I checked, apparently `sharey=False` is ignored for other plot types
<img width="1014" alt="Screenshot 2020-11-19 at 20 55 04" src="https://user-images.githubusercontent.com/1005173/99717335-92765400-2aa9-11eb-9b1a-84ea2200d5bb.png">

2020-11-19 20:02 UTC, lrusnac commented
to be honest I don't know why this snippet 

```python
if self.ylim is None:
    if (data >= 0).all().all():
        ax.set_ylim(0, None)
    elif (data <= 0).all().all():
```

would be needed at all. if it's area chart, it does use line plots for 0 and the other extreme and the fill between, so it should be already set as min or max limit at 0. but maybe I don't have a good understanding of the system

2020-11-20 09:37 UTC, charlesdong1991 commented
> to me that doesn't make much sense, I see the use of sharey in the plot only when it's pandas to make multiple plots

As I said, I also don't think this makes much sense, and totally agree with you on the assessment since `sharex or y` should only apply when `subplots=true`. I was just curious what the result would be if doing so. 

> would be needed at all. if it's area chart, it does use line plots for 0 and the other extreme and the fill between, so it should be already set as min or max limit at 0.

unfortunately, I am not very familiar with this snippet either, cannot answer you right now, need a look. but if you could find a way of cleaning this up, feel free to come up with a new PR to do so!

2020-11-20 09:38 UTC, merged

2020-11-20 09:38 UTC, charlesdong1991 commented
very nice @lrusnac and any clean-up PR is very welcome!