BUG: crosstab with duplicate column or index labels
pandas-dev/pandas pull request #37997
Opened 2020-11-22 05:12 UTC by arw2019

- [x] closes #22529
- [x] tests added / passed
- [x] passes black pandas
- [x] passes git diff upstream/master -u -- "*.py" | flake8 --diff
- [x] whatsnew entry

Picking up from #28474 

cc @jreback in case this can go in in time for 1.2

2020-11-22 05:24 UTC, arw2019 commented on pandas/tests/reshape/test_crosstab.py
> +        assert result.index.names == ["foo"]
getting rid of these asserts since `assert_frame_equal` already does this

2020-11-22 06:27 UTC, arw2019 commented
I tried consolidating the tests using `eval` but for a reason I can't atm figure out this doesn't work:
``` python
    @pytest.mark.parametrize("args_res, args_exp, axis", (
        ["s3, [s1, s2_foo]", "s3, [s1, s2_bar]", 1],
        ["[s1, s2_foo], s3", "[s1, s2_bar], s3", 0],
    ))
    def test_crosstab_duplicate_labels(self, args_res, args_exp, axis):
        # GH 22529

        s1 = Series(range(3), name="foo")
        s2_foo = Series(range(1, 4), name="foo")
        s2_bar = Series(range(1, 4), name="bar")
        s3 = Series(range(3), name="waldo")

        result = crosstab(*eval(args_res))

        expected = crosstab(*eval(args_exp))
        expected = expected.rename_axis(columns={"bar": "foo"}, axis=axis)

        tm.assert_frame_equal(result, expected)

```

2020-11-22 06:57 UTC, arw2019 commented on pandas/tests/reshape/test_crosstab.py
> +    def test_crosstab_duplicate_names(self):
addressed https://github.com/pandas-dev/pandas/pull/28474/files#r432993578

2020-11-22 07:07 UTC, arw2019 commented on pandas/core/reshape/pivot.py
> +    Parameters
working on https://github.com/pandas-dev/pandas/pull/28474/files#r432993840

2020-11-22 07:08 UTC, arw2019 commented on pandas/core/reshape/pivot.py
> +    shared_col_row_names = set(rownames).intersection(set(colnames))
working on https://github.com/pandas-dev/pandas/pull/28474/files#r491538724

2020-11-22 18:01 UTC, arw2019 commented on pandas/core/reshape/pivot.py
> +    shared_col_row_names = set(rownames).intersection(set(colnames))
addressed

2020-11-22 18:01 UTC, arw2019 commented on pandas/core/reshape/pivot.py
> +    Parameters
addressed

2020-11-26 16:43 UTC, jreback requested changes
looks good thanks for picking this up. comments & ping on green.

2020-11-26 16:43 UTC, jreback commented on pandas/core/reshape/pivot.py
> +    def get_duplicates(names):
can you add a doc-string here

2020-11-27 04:03 UTC, arw2019 commented on pandas/core/reshape/pivot.py
> +    def get_duplicates(names):
Done

2020-11-27 05:10 UTC, arw2019 commented
Green + addressed comments

2020-11-28 17:28 UTC, jreback approved these changes

2020-11-28 17:29 UTC, merged

2020-11-28 17:29 UTC, jreback commented
thanks @arw2019 and @cuchoi