ENH: support 2D in DatetimeArray._from_sequence
pandas-dev/pandas pull request #38021
Opened 2020-11-23 18:01 UTC by jbrockmendel

Broken off from a branch that fixes #37682, the constraint on which is that _validate_setitem_value needs to handle 2D.

2020-11-23 21:24 UTC, jorisvandenbossche requested changes
Same comment as in https://github.com/pandas-dev/pandas/pull/37950, I am personally not convinced we should expand the 2D capabilities.

2020-11-23 21:46 UTC, jbrockmendel commented
Thank you for weighing in Joris.  As I said in the OP, this is part of fixing #37682.

2020-11-26 17:15 UTC, jreback commented
hmm, yeah i think i agree with @jorisvandenbossche here, we should either go all in on 2D or not. can we just process column by column instead?

2020-11-26 19:07 UTC, jbrockmendel commented
> can we just process column by column instead?

we _can_, but it means putting more logic in Blocks which is the opposite of what im trying to do

2020-12-13 17:16 UTC, jreback commented
looking at this again it is fine. we do this in all kinds of places where we can potentially have 1d or 2d inputs.

unless objecting by @jorisvandenbossche and i think would need a concrete proposal that acheives the same aim, will merge tomorrow.

2020-12-17 13:52 UTC, merged

2020-12-17 13:52 UTC, jreback commented
this is fine