merge_ordered fails with list-like left_by
pandas-dev/pandas pull request #38089
Opened 2020-11-26 15:05 UTC by GYHHAHA

- [ ] closes #35269
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-11-26 18:10 UTC, jreback requested changes

2020-11-26 18:10 UTC, jreback commented on pandas/tests/reshape/merge/test_merge_ordered.py
> +        result = merge_ordered(left, right, on=["T"], left_by=["G", "H"])
can you test the same with `on='T'`
also can you test with right_by

2020-11-27 02:31 UTC, pep8speaks commented
Hello @GYHHAHA! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/reshape/merge/test_merge_ordered.py`](https://github.com/pandas-dev/pandas/blob/7fabf459cbb6491e63fd82ed5327d12109c18045/pandas/tests/reshape/merge/test_merge_ordered.py):

> [Line 127:21](https://github.com/pandas-dev/pandas/blob/7fabf459cbb6491e63fd82ed5327d12109c18045/pandas/tests/reshape/merge/test_merge_ordered.py#L127): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 133:17](https://github.com/pandas-dev/pandas/blob/7fabf459cbb6491e63fd82ed5327d12109c18045/pandas/tests/reshape/merge/test_merge_ordered.py#L133): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 141:21](https://github.com/pandas-dev/pandas/blob/7fabf459cbb6491e63fd82ed5327d12109c18045/pandas/tests/reshape/merge/test_merge_ordered.py#L141): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 147:17](https://github.com/pandas-dev/pandas/blob/7fabf459cbb6491e63fd82ed5327d12109c18045/pandas/tests/reshape/merge/test_merge_ordered.py#L147): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent

2020-11-27 04:17 UTC, GYHHAHA commented
There also exists two parts should be fixed.
```python
>>>l = pd.DataFrame([['g', 'h', 1], ['g', 'h', 3]], columns=list('GHT'))
>>>l
   G  H  T
0  g  h  1
1  g  h  3
>>>r = pd.DataFrame([[2, 1]], columns=list('TE'))
>>>r
   T  E
0  2  1
```
First, the following unexpected left join is related to wrongly `groupby` .
```python
>>>pd.merge_ordered(l, r, on='T', left_by=['G'])
```
  | G | H | T | E
-- | -- | -- | -- | --
g | h | 1 | NaN
g | h | 3 | NaN
Second, unexpected result appears when unseen label exists in `left_by` . (also caused by `try ... groupby` part)
```python
>>>pd.merge_ordered(l, r, on='T', left_by=['G', 'h'])
```
  | G | H | T | E | h
-- | -- | -- | -- | -- | --
G | h | 1 | NaN | G
G | NaN | 2 | 1.0 | G
h | NaN | 2 | 1.0 | h
h | h | 3 | NaN | h


Since they are different bugs from the current list-like issue, thus I will make another PR for the above-mentioned two after this merged.

2020-11-28 17:49 UTC, jreback requested changes

2020-11-28 17:49 UTC, jreback commented on pandas/tests/reshape/merge/test_merge_ordered.py
> +        result1 = merge_ordered(left, right, on=["T"], left_by=["G", "H"])
can you parameterize this test with the cases

2020-11-29 12:21 UTC, GYHHAHA commented
failures from `test_arithmetic`, unrelated? @jreback

2020-11-29 17:45 UTC, merged

2020-11-29 17:45 UTC, jreback commented
thanks @GYHHAHA very nice!