Only enable -Werror in the CI jobs
pandas-dev/pandas pull request #38087
Opened 2020-11-26 13:34 UTC by xhochy

- [x] closes #33315
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-11-26 13:35 UTC, xhochy commented
In which `whatsnew` section should this go? Bug fixes - other?

2020-11-26 14:19 UTC, jorisvandenbossche commented
Thanks! "Bug fixes - other" is fine for me 
(in pandas 1.0.0, we had a "build changes" section (https://pandas.pydata.org/docs/whatsnew/v1.0.0.html#build-changes), but that was a more relevant change, related to pyproject.toml)

2020-11-26 15:33 UTC, jreback requested changes
very minor comment, lgtm

2020-11-26 15:33 UTC, jreback commented on setup.py
> +    if os.environ.get("PANDAS_CI", "0") == "1":
can you add a comment that this is set explicity in ci/setup_env.sh

2020-11-26 15:33 UTC, jreback commented
also not averse to do this for 1.1.5 as well.

2020-11-26 15:40 UTC, simonjayhawkins commented
> also not averse to do this for 1.1.5 as well.

sure. however not an issue on MacPython for 1.1.5. Is causing issues with 1.2 though. see https://github.com/pandas-dev/pandas/issues/37784#issuecomment-732911912

https://github.com/MacPython/pandas-wheels/pull/112 my not be needed with this change.

2020-11-26 15:50 UTC, jreback commented
> > also not averse to do this for 1.1.5 as well.
> 
> sure. however not an issue on MacPython for 1.1.5. Is causing issues with 1.2 though. see [#37784 (comment)](https://github.com/pandas-dev/pandas/issues/37784#issuecomment-732911912)
> 
> [MacPython/pandas-wheels#112](https://github.com/MacPython/pandas-wheels/pull/112) my not be needed with this change.

interesting ok, then fine not to backport.

2020-11-26 15:53 UTC, simonjayhawkins commented
> interesting ok, then fine not to backport.

it's not causing us issues, but i'm ok with backporting if it could be beneficial to others

2020-11-26 15:55 UTC, xhochy commented
> > interesting ok, then fine not to backport.
> 
> it's not causing us issues, but i'm ok with backporting if it could be beneficial to others

It would be helpful for the conda packages on macOS

2020-11-26 17:02 UTC, jreback commented on doc/source/whatsnew/v1.2.0.rst
> +- Only set ``-Werror`` as a compiler flag in the CI jobs (:issue:`33315`, :issue:`33314`)
ok happy to backport, can you move to 1.1.5 whatnew

2020-11-26 18:11 UTC, jreback approved these changes

2020-11-26 18:12 UTC, jreback commented on doc/source/whatsnew/v1.2.0.rst
> +- Only set ``-Werror`` as a compiler flag in the CI jobs (:issue:`33315`, :issue:`33314`)
if you'd move the note, pls ping on green (might be a while, merged a lot of things today :->)

2020-11-26 20:38 UTC, simonjayhawkins commented
all green

2020-11-26 20:41 UTC, jreback commented
this needs the note moved to 1.1.5

2020-11-27 16:48 UTC, simonjayhawkins commented
test failure unrelated

```
=========================== short test summary info ============================
FAILED pandas/tests/plotting/test_misc.py::TestDataFramePlots::test_scatter_matrix_axis
= 1 failed, 143660 passed, 3518 skipped, 1408 xfailed, 14 warnings in 1846.77s (0:30:46) =
```

2020-11-27 20:03 UTC, merged

2020-11-27 20:04 UTC, jorisvandenbossche commented
Thanks @xhochy !

2020-11-27 20:49 UTC, simonjayhawkins commented
@meeseeksdev backport 1.1.x