API: CategoricalIndex.append fallback to concat_compat
pandas-dev/pandas pull request #38098
Opened 2020-11-26 21:26 UTC by jbrockmendel

- [x] closes #14586
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

The main thing being changed here is `CategoricalIndex._concat` to better match the behavior of all the other `FooIndex._concat` methods.  Everything else being changed here is just cleanup that this makes possible.

cc @jorisvandenbossche

2020-11-26 22:42 UTC, jreback approved these changes
lgtm

2020-11-28 17:31 UTC, jreback requested changes
need a whatsnew note as this is a behavior change (now a non-matching category is coerced  to object)

2020-11-28 22:29 UTC, jbrockmendel commented
whatsnew added + greenish (test_area_lim)

2020-11-29 15:59 UTC, jreback approved these changes

2020-11-29 15:59 UTC, merged