BUG: Index.intersection casting to object instead of numeric
pandas-dev/pandas pull request #38122
Opened 2020-11-27 20:39 UTC by jbrockmendel

- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

2020-11-29 18:07 UTC, jreback requested changes
lgtm pls add a whatsnew note (1.2 fine)

2020-11-29 18:07 UTC, jreback commented on pandas/core/indexes/base.py
> +            this = self.astype(dtype)
prob nbd but can do copy=False

2020-11-29 18:11 UTC, jbrockmendel commented
already has whatsnew.  mind if i add the copy=False in the next pass?  lots in the pipeline

2020-11-29 18:15 UTC, jreback commented
> already has whatsnew. mind if i add the copy=False in the next pass? lots in the pipeline

sure

2020-11-29 18:15 UTC, jreback approved these changes

2020-11-29 18:15 UTC, merged

2020-12-04 13:37 UTC, jorisvandenbossche commented
I don't know if it was this PR (from this range https://github.com/pandas-dev/pandas/compare/65319af6...f04ec866), but the `intersection` method got a bit slowdown in case of numeric indexes: https://pandas.pydata.org/speed/pandas/#index_object.SetOperations.time_operation?p-dtype='int'&p-method='intersection'

2020-12-04 13:40 UTC, jorisvandenbossche commented
Ah, might also be https://github.com/pandas-dev/pandas/pull/36927