REF: de-duplicate Block.__init__
pandas-dev/pandas pull request #38134
Opened 2020-11-28 16:10 UTC by jbrockmendel

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-11-29 18:17 UTC, jreback requested changes

2020-11-29 18:17 UTC, jreback commented on pandas/core/internals/blocks.py
> +            raise AssertionError("block.size != values.size")
test hit this?

2020-11-29 18:17 UTC, jreback commented on pandas/core/internals/blocks.py
> +                "Accepting ndim=None in the Block constructor is deprecated, "
ahh i c, can you open an issue on arrow jira tracker and link to this PR for updating this

2020-11-29 18:18 UTC, jreback requested changes

2020-11-29 18:18 UTC, jreback commented on pandas/core/internals/blocks.py
> +                FutureWarning,
normally i want FutureWarning, but in this case this is only an internal library use. ok to use DeprecationWarning here

2020-11-29 18:19 UTC, jreback commented
ok for 1.2

2020-11-29 19:13 UTC, jreback commented
@jbrockmendel if you can address these comments can get this in

2020-11-29 20:17 UTC, jbrockmendel commented
xref https://issues.apache.org/jira/browse/ARROW-10768

2020-11-29 21:00 UTC, jorisvandenbossche requested changes
What's the rationale for this change? Why is it needed to deprecate it? (pyarrow code currently works fine? Or is there a problem with it)

2020-11-29 21:10 UTC, jbrockmendel commented
> What's the rationale for this change? Why is it needed to deprecate it? (pyarrow code currently works fine? Or is there a problem with it)

We recently made it so that all our internal calls explicitly pass ndim.  Now we're telling other packages (that ideally wouldnt be accessing internals in the first place) they need to do the same.

2020-11-30 06:57 UTC, jorisvandenbossche commented
> they need to do the same.

But so is there an actual reason to require this, apart from "we are not using the keyword anymore internally" ? 
(I didn't closely follow your prior work related to `ndim`, so I am honestly asking. Does it give risks on bugs for the external users, or is it slower, or ... when they don't explicitly pass the `ndim`?)

If we do the change, we could also keep this for after the 1.2 RC, so the deprecation is only for 1.3, which gives pyarrow time to fix the code and have a release before this is released by pandas.

2020-11-30 15:02 UTC, jbrockmendel commented
> But so is there an actual reason to require this, apart from "we are not using the keyword anymore internally" ?
(I didn't closely follow your prior work related to ndim, so I am honestly asking. Does it give risks on bugs for the external users, or is it slower, or is it hard to maintain that functionality for us, or ... when they don't explicitly pass the ndim?)

The motivation that led me to update all of our internal usages to always pass ndim explicitly was that on other branches I was getting errors related to incorrect ndim inference.  (Keep in mind I have active branches for both ArrayManager and EA2D among others and I don't recall off the top of my head which one(s) were producing these errors)

> or is it slower

ndim inference isn't going to be particularly slow, but we do call the Block constructors a lot, so it _could_ add up.

> or is it hard to maintain that functionality for us

In general I think being more explicit and more strict in internals code makes maintenance easier, yes.

2020-12-01 17:59 UTC, simonjayhawkins commented
> If we do the change, we could also keep this for after the 1.2 RC, so the deprecation is only for 1.3, which gives pyarrow time to fix the code and have a release before this is released by pandas.

@jbrockmendel can we remove the blocker tag? and do this for 1.3?

2020-12-01 18:07 UTC, jbrockmendel commented
> and do this for 1.3?

sounds good

2020-12-20 04:42 UTC, jbrockmendel commented
Mothballing pending https://github.com/apache/arrow/pull/8957

2021-03-07 19:32 UTC, jbrockmendel commented
re-opening; now that make_block is exposed specifically for downstream, we can do the validation there and be stricter in private-internals

2021-03-07 22:24 UTC, jbrockmendel commented on pandas/core/internals/blocks.py
> +            raise AssertionError("block.size != values.size")
yes, test_invalid_ea_block gets here

2021-03-08 13:02 UTC, jreback approved these changes

2021-03-08 13:03 UTC, jreback commented
lgtm @jorisvandenbossche if any issues.

2021-03-08 19:38 UTC, jorisvandenbossche commented
To make it explicit: the PR now no longer includes a deprecation warning. But you still changed the behaviour of `Block.__init__`, or not?

2021-03-08 20:24 UTC, jbrockmendel commented
> To make it explicit: the PR now no longer includes a deprecation warning. But you still changed the behaviour of Block.__init__, or not?

`Block.__init__` is changed, but the relevant validation is now done in `api.make_block`, so downstream libraries using that will be unaffected.

2021-03-09 22:07 UTC, jreback commented
> Yep, but thus downstream libraries using `Block` can be affected. But since we are not aware of such libraries, and the known ones use `make_block` / `make_block_same_class`, that's probably OK

great

2021-03-09 22:07 UTC, merged

2021-03-09 22:07 UTC, jreback commented
thanks @jbrockmendel

2021-03-09 22:16 UTC, jbrockmendel commented
alright! between this, #40262, and a couple follow-ups to this, im hopeful to take another big chunk out of the difference between libreduction-vs-purepython paths (xref #40263)