BUG: combine_first does not retain dtypes with Timestamp DataFrames
pandas-dev/pandas pull request #38145
Opened 2020-11-29 04:31 UTC by arw2019

- [x] closes #28481
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Picking up #35514

2020-11-29 05:31 UTC, jbrockmendel commented
Why does combin_first use expressions.where instead of mgr.where? Casting should be handled correctly there

2020-11-29 07:43 UTC, arw2019 commented
> Why does combin_first use expressions.where instead of mgr.where? Casting should be handled correctly there

That line hasn't been touched since #17744, will look

2020-11-29 15:51 UTC, jbrockmendel commented
Now that i have an actual keyboard: this would likely also require fixing Block.where #38073

2020-11-29 17:38 UTC, arw2019 commented
> Now that i have an actual keyboard: this would likely also require fixing Block.where #38073 

Ok - in this case this would sit on top of that

I'm struggling a little with the pattern. Atm I have:
``` python
    def combine_first(self, other: DataFrame) -> DataFrame:
        def combiner(x, y):
            mask = extract_array(isna(x))

            x_values = extract_array(x, extract_numpy=True)
            y_values = extract_array(y, extract_numpy=True)

            # If the column y in other DataFrame is not in first DataFrame,
            # just return y_values.
            if y.name not in self.columns:
                return y_values

            _where = self._mgr.where(y_values, mask, align=True, errors="raise", try_cast=True, axis=1)
            # extract array from _where

        return self.combine(other, combiner, overwrite=False)
```
Is this in the right ballpark?

2020-11-29 19:32 UTC, jreback requested changes
> Now that i have an actual keyboard: this would likely also require fixing Block.where #38073

@jbrockmendel is the current patch not good for 1.2? (agreed could use some refactoring).

2020-11-29 19:32 UTC, jreback commented on pandas/tests/frame/methods/test_combine_first.py
> +        (pd.Period("2020-01-01", "D"), pd.Period("2020-01-02", "D")),
can add an Interval example here as well

2020-11-29 19:36 UTC, jbrockmendel commented
> is the current patch not good for 1.2? (agreed could use some refactoring).

This looks good for now

2020-11-29 19:43 UTC, jreback commented
@arw2019 ok small test comment. ping on green.

2020-11-30 05:24 UTC, arw2019 commented on pandas/tests/frame/methods/test_combine_first.py
> +        (pd.Period("2020-01-01", "D"), pd.Period("2020-01-02", "D")),
Done

2020-11-30 13:21 UTC, merged

2020-11-30 13:21 UTC, jreback commented
thanks @arw2019

2020-12-01 03:54 UTC, jbrockmendel commented
@arw2019 do you have time to try to make this go through `self._mgr.where`?  (no hurry)

2020-12-01 06:04 UTC, arw2019 commented
> @arw2019 do you have time to try to make this go through `self._mgr.where`? (no hurry)

yes, in the works