Gh28486 add schema kwarg
pandas-dev/pandas pull request #38146
Opened 2020-11-29 04:41 UTC by arw2019

- [x] closes  #28486
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Picking up #33278

2020-11-29 19:34 UTC, jreback commented
lgtm. @jorisvandenbossche if you can give a once over

2020-12-03 14:22 UTC, jreback commented
cc @jorisvandenbossche

2020-12-06 23:37 UTC, mroeschke commented on doc/source/whatsnew/v1.2.0.rst
> +- :meth:`get_schema` now allows a schema kwarg that will add a schema into the create table statement (:issue:`28486`)
Mind specifying `io.sql.get_schema` directly?

2020-12-06 23:37 UTC, mroeschke reviewed
One minor comment otherwise LGTM

2020-12-07 08:50 UTC, arw2019 commented on doc/source/whatsnew/v1.2.0.rst
> +- :meth:`get_schema` now allows a schema kwarg that will add a schema into the create table statement (:issue:`28486`)
Sure! Done

2020-12-07 19:25 UTC, mroeschke approved these changes

2020-12-07 19:30 UTC, jreback requested changes
ping on green

2020-12-07 19:30 UTC, jreback commented on pandas/io/sql.py
> +    return pandas_sql._create_sql_schema(
oh you need to update doc-string and add versionadded 1.2

2020-12-07 21:41 UTC, jreback approved these changes

2020-12-07 21:41 UTC, jreback commented
lgtm ping on green

2020-12-07 23:02 UTC, arw2019 commented
Green

2020-12-08 02:44 UTC, merged

2020-12-08 02:45 UTC, mroeschke commented
Thanks @arw2019