DOC: Add examples for filling missing data
pandas-dev/pandas pull request #38163
Opened 2020-11-29 23:59 UTC by chrystalchan-academic

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-11-30 14:33 UTC, jreback requested changes

2020-11-30 14:33 UTC, jreback commented on doc/source/user_guide/missing_data.rst
> +nonDateDf = df.select_dtypes(exclude=['datetime'])
need to be indented. don't use camelCase, pref `non_date_df`

2020-11-30 14:33 UTC, jreback commented on doc/source/user_guide/missing_data.rst
> +nonDateDf = df.select_dtypes(exclude=['datetime'])
its not clear what you are trying to do here, can you add a comment & show the resulting frame (and the before one if needed); you are assigning in place so it won't show currently.

2020-12-20 10:57 UTC, MarcoGorelli commented
Hi @chrystalchan-academic - is this still active?

2021-01-24 11:36 UTC, MarcoGorelli commented
closing for now, let us know if you'd like to continue working on this and we'll reopen

2021-01-24 11:36 UTC, closed without merging