The error message for unsupported index on shift() could be more explicit
pandas-dev/pandas pull request #38176
Opened 2020-11-30 06:54 UTC by ZhihuiChen0903

When the type of data index is not datetime-like, the following error message will raise:
`NotImplementedError: Not supported for type Index`
 
The error message could be more useful by explicitly stating which types of data that `shift` supports.
 
Expected error message:
` f"This method is only implemented for DatetimeIndex, PeriodIndex and TimedeltaIndex; Got type {type(self).__name__}."`

2020-11-30 06:54 UTC, pep8speaks commented
Hello @ZhihuiChen0903! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/indexes/base.py`](https://github.com/pandas-dev/pandas/blob/c0b2b53d3b74150289a0f04b6f15292dd84111fc/pandas/core/indexes/base.py):

> [Line 4738:89](https://github.com/pandas-dev/pandas/blob/c0b2b53d3b74150289a0f04b6f15292dd84111fc/pandas/core/indexes/base.py#L4738): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (151 > 88 characters)

2020-12-02 02:32 UTC, jreback requested changes
happy to have, we have tests that check the error message and need to be adjusted (have a look at CI logs for which ones).

2020-12-03 21:41 UTC, jreback commented
lgtm @ZhihuiChen0903 if you turnt his off draft can merge.

2020-12-04 01:45 UTC, ZhihuiChen0903 commented
@jreback I have turned off draft.

2020-12-04 01:59 UTC, jreback approved these changes

2020-12-04 02:00 UTC, merged

2020-12-04 02:00 UTC, jreback commented
thanks @ZhihuiChen0903