ENH: context-manager for TextFileReader
pandas-dev/pandas pull request #38225
Opened 2020-12-02 02:54 UTC by twoertwein

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Allows (and encourages) the following use:
```py
import pandas as pd

filename = "pandas/tests/io/data/csv/iris.csv"
chunksize = 2
with pd.read_csv(filename, chunksize=chunksize) as reader:
    for chunk in reader:
        # risky code that might raise
```
Same can be done for `read_json/sas` (I think these are all methods that support `chunksize`). If this PR should make it into 1.2, I can quickly add the changes for json/sas as well.

Are there more places to promote this new context manager?

2020-12-02 03:09 UTC, jreback commented
this looks pretty neat. can you add a small note section in io.rst which shows this off. i think this is ok for 1.2, can add json/sas as followsup.

2020-12-02 15:11 UTC, twoertwein commented
I don't understand why the documentation example is failing:

Exception in /home/runner/work/pandas/pandas/doc/source/user_guide/io.rst at block ending on line 1586
ParserError: Error tokenizing data. C error: out of memory

2020-12-03 23:17 UTC, jreback requested changes

2020-12-03 23:47 UTC, twoertwein commented on doc/source/user_guide/io.rst
> +   with pd.read_csv("tmp.sv", sep="|", chunksize=4) as reader:
I assume this is only needed here and not at the other places in `io.rst` where I changed the examples?

Do you have opinions about `versionchanged` vs `versionadded`? I used `versionchanged` when documenting the arguments for `read_*` and used it here again for consistency.

I will try to re-produced the doc issue over the weekend.

2020-12-04 16:53 UTC, jreback requested changes
great. just some minor doc omments. ping on green.

2020-12-04 16:53 UTC, jreback commented on doc/source/user_guide/io.rst
> +   with pd.read_csv("tmp.sv", sep="|", chunksize=4) as reader:
yeah versionchanged here is fine. its just a cue in the docs that these are not the same.

2020-12-04 16:53 UTC, jreback commented on doc/source/user_guide/io.rst
> +  ``read_csv/json/sas`` return a context-manager when iterating through a file.
I *think* you need a blank after the versionadded to make this render correctly, though never remember

2020-12-04 16:53 UTC, jreback commented on doc/source/whatsnew/v1.2.0.rst
> +- :func:`read_csv/sas/json` return a context manager when called with ``chuncksize``/``iterator`` (:issue:`38225`)
can you change this slightly, that with turn a reader which can be used in a context manager

2020-12-04 16:53 UTC, jreback commented on pandas/io/parsers.py
> +        ``TextFileReader`` is a context manager.
same comments generally these might need a blank line.

2020-12-04 16:53 UTC, jreback commented on pandas/io/sas/sasreader.py
> +
perfect

2020-12-04 18:28 UTC, twoertwein commented
@jreback green. I hope the whatsnew entry is good now

2020-12-04 18:58 UTC, jreback approved these changes

2020-12-04 18:58 UTC, merged

2020-12-04 18:58 UTC, jreback commented
thanks @twoertwein very nice