TYP/BUG: fix passing incorrect type to interpolate_1d
pandas-dev/pandas pull request #38306
Opened 2020-12-05 03:31 UTC by jbrockmendel

2020-12-05 03:42 UTC, jreback requested changes
any additional tests?

2020-12-05 03:44 UTC, jbrockmendel commented
> any additional tests?

i dont think so.  i checked that we get here with dt64tz but thats about it.

2020-12-07 15:06 UTC, jreback approved these changes

2020-12-07 15:06 UTC, merged

2020-12-07 15:06 UTC, jreback commented
wow typing actually is helping