BUG: Groupby first/last/nth treats None as an observation
pandas-dev/pandas pull request #38330
Opened 2020-12-06 16:13 UTC by rhshadrach

- [x] closes #38286
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

This is a regression from 1.0.x to 1.1.x, introduced by #32800. Assuming it doesn't get into the 1.2 rc, not sure if it should go into 1.2 during the rc phase or wait until 1.3.

Had to decide on some edge-case behaviors in odd situations with missing values, see https://github.com/pandas-dev/pandas/issues/38286#issuecomment-739521117

2020-12-06 16:17 UTC, jreback requested changes
pls find out when this was originally changed 

this was on purpose

2020-12-06 16:21 UTC, rhshadrach commented
@jreback This was originally changed in #32800 so that 

    pd.DataFrame({"id": ["a"], "value": [None]}, dtype=object).groupby("a").first()

returns `None` rather than `np.nan`. That behavior is retained here.

2020-12-06 16:25 UTC, jreback commented
so you think that the original issues are wrong? this is deleting that test case and reverting

2020-12-06 16:25 UTC, simonjayhawkins commented
> This is a regression from 1.0.x to 1.1.x

if this is the case, should go in 1.1.5.

2020-12-06 16:29 UTC, rhshadrach commented
@jreback I believe this is reverting the fix in #33462 and solving the issue there in the proper manner, along with the regression it caused. The original test case still exists, is the first parameter to `test_first_last_with_none`

2020-12-06 16:29 UTC, rhshadrach commented
I can restore the original test and add the new one for the regression if that's preferable.

2020-12-06 16:47 UTC, jreback commented
yes if this also doesn't change the original issue then leave the tests

ok for 1.1.5

2020-12-06 17:08 UTC, rhshadrach commented
@jreback test restored, added to whatsnew 1.5

2020-12-06 17:11 UTC, jreback commented on doc/source/whatsnew/v1.1.5.rst
> +- Fixed regression in :meth:`.GroupBy.first`, :meth:`.GroupBy.last`, and :meth:`.GroupBy.nth` where ``None`` was considered a non-NA value (:issue:`38286`)
this doesn't affect nth right?

2020-12-06 17:33 UTC, rhshadrach commented on doc/source/whatsnew/v1.1.5.rst
> +- Fixed regression in :meth:`.GroupBy.first`, :meth:`.GroupBy.last`, and :meth:`.GroupBy.nth` where ``None`` was considered a non-NA value (:issue:`38286`)
Indeed, thanks. Fixed.

2020-12-06 17:46 UTC, jreback reviewed
can u run some  asvs / perf for this
i am worried we are converting to object type

2020-12-06 18:34 UTC, rhshadrach commented
@jreback asv run with `asv continuous -f 1.1 upstream/master HEAD -b ^groupby` resulted in `BENCHMARKS NOT SIGNIFICANTLY CHANGED`.

Linux py39 failure is unrelated:

    FAILED pandas/tests/io/pytables/test_store.py::TestHDFStore::test_append_with_data_columns
    = 1 failed, 143282 passed, 5482 skipped, 1091 xfailed, 4 warnings in 1132.31s (0:18:52) =

2020-12-06 18:46 UTC, jreback approved these changes

2020-12-06 18:46 UTC, merged

2020-12-06 18:46 UTC, jreback commented
thanks for the quick patch @rhshadrach

2020-12-06 18:49 UTC, simonjayhawkins commented
@meeseeksdev backport 1.1.x

2020-12-07 17:56 UTC, AMALCGCG commented
We just upgraded to 1.1.5 this morning, and it works great! Thank you for the blazing fast discussion, decision, fix, merge, and backport!