BUG: add sorting_reamaining=True to avoid IndexError GH25831
pandas-dev/pandas pull request #38438
Opened 2020-12-13 02:10 UTC by YuRenee

- [ ] closes #25831
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-12-13 03:44 UTC, arw2019 reviewed
Can you add test(s)? It's the first thing we look for when reviewing

2020-12-13 08:24 UTC, YuRenee commented
Sure!

2020-12-13 08:59 UTC, YuRenee commented
Just added!

2020-12-13 09:06 UTC, pep8speaks commented
Hello @YuRenee! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/frame/methods/test_sort_index.py`](https://github.com/pandas-dev/pandas/blob/8dca32952cce8bec7cec92193be744de04bf7909/pandas/tests/frame/methods/test_sort_index.py):

> [Line 866:13](https://github.com/pandas-dev/pandas/blob/8dca32952cce8bec7cec92193be744de04bf7909/pandas/tests/frame/methods/test_sort_index.py#L866): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line

2020-12-13 17:35 UTC, jreback requested changes

2020-12-13 17:35 UTC, jreback commented on pandas/core/sorting.py
> +    if isinstance(level, (str, int)) and level is not None:
you don't need the not None conditions

2020-12-13 17:35 UTC, jreback commented on pandas/core/sorting.py
> +    elif isinstance(level, list) and len(level) != 0:
don't use list testing directly rather is_list_like

2020-12-13 17:35 UTC, jreback commented on pandas/core/sorting.py
> +    if isinstance(level, (str, int)) and level is not None:
use is_scalar(level) instead

2020-12-13 17:35 UTC, jreback commented on pandas/core/sorting.py
> +    elif isinstance(level, list) and len(level) != 0:
rather just make this robust to an empty level

2020-12-13 17:35 UTC, jreback commented on pandas/core/sorting.py
> +    if isinstance(level, (str, int)) and level is not None:
same comments as above

2020-12-13 17:35 UTC, jreback commented on pandas/tests/frame/methods/test_sort_index.py
> +        expected = df.sort_index(level=[], sort_remaining=True)
an you hard-code the expected result frame.

can you parameterize this test for sort_remaining =True/False

2020-12-22 00:48 UTC, jreback commented
can you merge master

2020-12-22 00:50 UTC, jreback requested changes

2020-12-22 00:50 UTC, jreback commented on pandas/core/indexes/category.py
> +            # pandas\core\indexes\category.py:315: error: "CategoricalIndex"
hmm CI shouldn't have an attribute ordered, rather the CDT does

2020-12-22 00:50 UTC, jreback commented on pandas/core/indexes/category.py
> +            if not to_concat[0].ordered:
can you do a list comprehension instead,using counters like this is not pythonic

2020-12-22 00:50 UTC, jreback commented on pandas/core/reshape/concat.py
> +
ideally if you dont' touch whitespace would be good

2020-12-29 17:22 UTC, jreback commented
can you merge master and update

2021-02-11 01:39 UTC, jreback commented
closing as stale. if you want to continue, pls ping and can re-open.

2021-02-11 01:39 UTC, closed without merging