Tests .loc on sparse DataFrame #34687
pandas-dev/pandas pull request #38540
Opened 2020-12-17 13:49 UTC by weikhor

- [ ✔️] closes #34687
- [ ✔️] tests added / passed

Created test case for ttps://github.com/pandas-dev/pandas/issues/34687

2020-12-17 13:49 UTC, pep8speaks commented
Hello @weikhor! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/arrays/sparse/test_array.py`](https://github.com/pandas-dev/pandas/blob/ac1d4f1b94304ead6599ea74233e99a4371f0a86/pandas/tests/arrays/sparse/test_array.py):

> [Line 16:29](https://github.com/pandas-dev/pandas/blob/ac1d4f1b94304ead6599ea74233e99a4371f0a86/pandas/tests/arrays/sparse/test_array.py#L16): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 862:1](https://github.com/pandas-dev/pandas/blob/ac1d4f1b94304ead6599ea74233e99a4371f0a86/pandas/tests/arrays/sparse/test_array.py#L862): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 866:1](https://github.com/pandas-dev/pandas/blob/ac1d4f1b94304ead6599ea74233e99a4371f0a86/pandas/tests/arrays/sparse/test_array.py#L866): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2020-12-17 17:18 UTC, arw2019 requested changes
Thanks @weikhor for the PR!

The new test is failing - PTAL. I left some pointers below.

Also I think the test should include something to the effect of
``` python
tm.assert_frame_equal(df.loc[range(5)].loc[range(3)], df.loc[range(3)])
```
as IMO that was the point of the ticket

2020-12-17 17:18 UTC, arw2019 commented on pandas/tests/arrays/sparse/test_array.py
> +        res1 = s.loc[range(2)]
This produces a DataFrame so you need to construct a DataFrame and compare that

2020-12-17 17:18 UTC, arw2019 commented on pandas/tests/arrays/sparse/test_array.py
> +        s = pd.DataFrame.sparse.from_spmatrix(eye(5))
Call this `df`

2020-12-17 17:18 UTC, arw2019 commented on pandas/tests/arrays/sparse/test_array.py
> +        tm.assert_sp_array_equal(res1, exp1)
you will want to use `tm.assert_frame_equal` here

2020-12-18 15:59 UTC, weikhor commented
@arw2019 

I have tried my test cases on my side. It work perfectly. I not sure why automatic test case still failed.

2020-12-18 16:04 UTC, arw2019 commented
> @arw2019
> 
> I have tried my test cases on my side. It work perfectly. I not sure why automatic test case still failed.

If you look at the output it's because scipy is not being imported correctly. Take a look at what we do in other similar tests to get this to green (we won't merge if the checks don't pass)

2020-12-18 16:05 UTC, arw2019 requested changes

2020-12-18 16:05 UTC, arw2019 commented on pandas/tests/arrays/sparse/test_array.py
> +        exp1 = pd.DataFrame(
pls don't use `to_numpy` here. Compare the dataframes using `tm.assert_frame_equal`

2020-12-18 16:06 UTC, arw2019 commented
you also need to format the code (look at output from pre-commit hook)

2020-12-19 06:55 UTC, arw2019 requested changes
Some comments (but getting close 👍)

2020-12-19 06:55 UTC, arw2019 commented on pandas/tests/arrays/sparse/test_array.py
> +        ).astype(dtype)
instead of astyping pass `dtype` into the constructor

2020-12-19 06:55 UTC, arw2019 commented on pandas/tests/arrays/sparse/test_array.py
> +        # Tests .loc on sparse DataFrame #34687
Change this comment to simply `# GH34687`

2020-12-19 06:55 UTC, arw2019 commented on pandas/tests/arrays/sparse/test_array.py
> +        ).astype(dtype)
same here

2020-12-19 06:58 UTC, arw2019 commented on pandas/tests/arrays/sparse/test_array.py
> +from scipy.sparse import eye
you need to get rid of this to get CI to pass

2020-12-19 13:57 UTC, weikhor commented
Hi @arw2019, I failed on AssertionError: ExtensionArray NA mask are different https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=50437&view=logs&j=2d7fb38a-2053-50f3-a67c-09f6e91d3121&t=449937cc-3d50-56b5-5662-e489f41f1268&l=125  and pre-commit / pre-commit (pull_request). Please assist.

2020-12-19 16:33 UTC, arw2019 commented
> Hi @arw2019, I failed on AssertionError: ExtensionArray NA mask are different https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=50437&view=logs&j=2d7fb38a-2053-50f3-a67c-09f6e91d3121&t=449937cc-3d50-56b5-5662-e489f41f1268&l=125 and pre-commit / pre-commit (pull_request). Please assist.

Well they *are* different:
``` python
In [18]: res2 = df.loc[range(2)].loc[range(1)]
    ...: exp2 = pd.DataFrame(
    ...:             [[1.0, 0.0, np.nan, np.nan, np.nan]], dtype=pd.SparseDtype("float64", 0.0)
    ...:         )

In [19]: res2
Out[19]: 
     0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0

In [20]: exp2
Out[20]: 
     0    1   2   3   4
0  1.0  0.0 NaN NaN NaN
```
so you need to change the output.

Re: pre-commit, the easiest thing is to run pre-commit locally and let the hooks do the modifications

2020-12-20 07:41 UTC, arw2019 requested changes
CI passing now (the outstanding failures are unrelated) 👍 

I think we should move this to `pandas/tests/indexing/test_loc.py` - that's where these kinds of tests sit

2020-12-20 15:34 UTC, weikhor commented
@arw2019 

All checks have passed. Thank

2020-12-21 13:03 UTC, weikhor commented
@arw2019 @jreback 
Please review and approve the pull request. Thank

2020-12-21 18:10 UTC, jreback requested changes
ideally you can parameterize this test?

2020-12-21 18:10 UTC, jreback commented on pandas/tests/indexing/test_loc.py
> +        res1 = df.loc[range(2)]
can you call this result, and use the word expected instead of exp1

2020-12-21 18:10 UTC, jreback commented on pandas/tests/indexing/test_loc.py
> +        res2 = df.loc[range(2)].loc[range(1)]
blank line & use result / expected

2020-12-21 18:10 UTC, jreback commented on pandas/tests/indexing/test_loc.py
> +    def testss_loc_filling_DataFrame(self):
can you rename to

test_loc_sparse_frame

2020-12-29 17:21 UTC, jreback commented
can you merge master and update

2021-02-11 01:31 UTC, jreback commented
closing as stale. if you want to continue, pls ping and can re-open.

2021-02-11 01:31 UTC, closed without merging

2021-03-22 22:17 UTC, EricLeer commented
> closing as stale. if you want to continue, pls ping and can re-open.

I was thinking of taking over this pull request, since it looks like it is almost finished. What would be the best way of doing that, with this living on the fork of weikhor? Just copy the changes over to a new pr?

2021-03-23 01:55 UTC, jreback commented
sure you can cherry pick off of the other branch is prob best