testing case sort_index with pd.set_option('use_inf_as_na', True)
pandas-dev/pandas pull request #38542
Opened 2020-12-17 15:06 UTC by weikhor

- [ ] closes #29687
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Create test cases for sort_index works with 'pd.set_option('mode.use_inf_as_na',True)

2020-12-17 15:06 UTC, pep8speaks commented
Hello @weikhor! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/frame/methods/test_sort_index.py`](https://github.com/pandas-dev/pandas/blob/e1c5a881d12275ea55c90a46a6d2a4328de9bf0d/pandas/tests/frame/methods/test_sort_index.py):

> [Line 860:1](https://github.com/pandas-dev/pandas/blob/e1c5a881d12275ea55c90a46a6d2a4328de9bf0d/pandas/tests/frame/methods/test_sort_index.py#L860): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 866:1](https://github.com/pandas-dev/pandas/blob/e1c5a881d12275ea55c90a46a6d2a4328de9bf0d/pandas/tests/frame/methods/test_sort_index.py#L866): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 879:1](https://github.com/pandas-dev/pandas/blob/e1c5a881d12275ea55c90a46a6d2a4328de9bf0d/pandas/tests/frame/methods/test_sort_index.py#L879): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2020-12-17 17:24 UTC, arw2019 requested changes
The snippet in the original ticket works on master. To close the ticket you'll need to figure out which commit fixed the issue (likely by running git bisect) and only add new tests if there aren't any already

2020-12-17 17:24 UTC, arw2019 commented on pandas/tests/frame/methods/test_sort_index.py
> +        try:
please use `pytest.raises` here

2020-12-17 17:25 UTC, arw2019 commented on pandas/tests/frame/methods/test_sort_index.py
> +        try:
(this specific bit doesn't raise so this is a general pointer)

2021-01-01 21:49 UTC, jreback commented
@weikhor can you merge master and update to comments

2021-02-11 01:42 UTC, jreback commented
closing as stale. if you want to continue, pls ping and can re-open.

2021-02-11 01:42 UTC, closed without merging