pandas-dev issue #38267
pandas-dev/pandas pull request #38693
Opened 2020-12-25 08:47 UTC by ftrihardjo

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-12-25 18:08 UTC, MarcoGorelli requested changes
Thanks @ftrihardjo

2020-12-25 18:08 UTC, MarcoGorelli commented on pandas/tests/series/methods/test_replace.py
> +        result = pd.Series([0, None]).astype(dtype)
can you put the issue number as a comment here? see some other tests for an example

2020-12-25 18:08 UTC, MarcoGorelli commented on pandas/tests/series/methods/test_replace.py
> +        result.replace(0, pd.NA)
I think you'll want
```
result = result.replace(0, pd.NA)
```

2020-12-25 18:08 UTC, MarcoGorelli commented on pandas/tests/series/methods/test_replace.py
> +        expected.fillna(0).replace(0, pd.NA)
why is this line needed? Just construct `expected` directly

2020-12-26 02:09 UTC, ftrihardjo commented
thank you for your review

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Sat, Dec 26, 2020 at 1:09 AM Marco Gorelli <notifications@github.com>
wrote:

> *@MarcoGorelli* requested changes on this pull request.
>
> Thanks @ftrihardjo <https://github.com/ftrihardjo>
> ------------------------------
>
> In pandas/tests/series/methods/test_replace.py
> <https://github.com/pandas-dev/pandas/pull/38693#discussion_r548898329>:
>
> > +    def test_replace_int_with_na(self, dtype):
> +        result = pd.Series([0, None]).astype(dtype)
>
> can you put the issue number as a comment here? see some other tests for
> an example
> ------------------------------
>
> In pandas/tests/series/methods/test_replace.py
> <https://github.com/pandas-dev/pandas/pull/38693#discussion_r548898449>:
>
> > @@ -208,6 +208,14 @@ def test_replace_with_dict_with_bool_keys(self):
>          expected = pd.Series(["yes", False, "yes"])
>          tm.assert_series_equal(result, expected)
>
> +    @pytest.mark.parametrize('dtype', ['int8', 'int16', 'int32', 'int64'])
> +    def test_replace_int_with_na(self, dtype):
> +        result = pd.Series([0, None]).astype(dtype)
> +        result.replace(0, pd.NA)
>
> I think you'll want
>
> result = result.replace(0, pd.NA)
>
> ------------------------------
>
> In pandas/tests/series/methods/test_replace.py
> <https://github.com/pandas-dev/pandas/pull/38693#discussion_r548898461>:
>
> > @@ -208,6 +208,14 @@ def test_replace_with_dict_with_bool_keys(self):
>          expected = pd.Series(["yes", False, "yes"])
>          tm.assert_series_equal(result, expected)
>
> +    @pytest.mark.parametrize('dtype', ['int8', 'int16', 'int32', 'int64'])
> +    def test_replace_int_with_na(self, dtype):
> +        result = pd.Series([0, None]).astype(dtype)
> +        result.replace(0, pd.NA)
> +        expected = pd.Series([0, None]).astype(dtype)
> +        expected.fillna(0).replace(0, pd.NA)
>
> why is this line needed? Just construct expected directly
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/38693#pullrequestreview-558831366>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF2RQQOYKEZAMDBFVPBC7UDSWTILXANCNFSM4VI6XQWA>
> .
>

2020-12-26 08:38 UTC, MarcoGorelli requested changes

2020-12-26 08:38 UTC, MarcoGorelli commented on pandas/tests/series/methods/test_replace.py
> +        expected = pd.Series([0, None]).astype(dtype).fillna(0).replace(0, pd.NA)
Is it possible to construct `expected` directly (e.g. `expected = pd.Series([pd.NA, pd.NA])`)?

2020-12-26 13:16 UTC, MarcoGorelli requested changes

2020-12-26 13:16 UTC, MarcoGorelli commented on pandas/tests/series/methods/test_replace.py
> +    @pytest.mark.parametrize("dtype", ["int8", "int16", "int32", "int64"])
the types need to be capitalised, as in the issue, e.g. `Int64` not `int64`

2020-12-27 07:00 UTC, arw2019 commented on pandas/tests/series/methods/test_replace.py
> +    def test_replace_int_with_na(self, dtype):
I'd call it `test_replace_nullable_int_with_na` or `test_replace_Int_with_na`

2020-12-27 07:03 UTC, arw2019 commented on pandas/tests/series/methods/test_replace.py
> +        expected = pd.Series([pd.NA, pd.NA])
you also need to pass dtype here else (looking at CI output) this casts to object. That's why currently this test doesn't actually pass

2020-12-27 12:52 UTC, MarcoGorelli commented
Thanks @ftrihardjo , looks like just https://github.com/pandas-dev/pandas/pull/38693#discussion_r549074576 still needs to be addressed

2020-12-27 22:25 UTC, jreback requested changes

2020-12-27 22:25 UTC, jreback commented on pandas/tests/series/methods/test_replace.py
> +        result = pd.Series([0, None], dtype=dtype).replace(0, pd.NA)
can you add the working example as well e.g. 0,1 as another case.

2020-12-27 22:25 UTC, jreback commented on pandas/tests/series/methods/test_replace.py
> +    @pytest.mark.parametrize("dtype", ["Int8", "Int16", "Int32", "Int64"])
can you use the fixture: any_nullable_int_dtype instead here.

2020-12-27 22:31 UTC, pep8speaks commented
Hello @ftrihardjo! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/series/methods/test_replace.py`](https://github.com/pandas-dev/pandas/blob/a5dc3c4c691fed17e961218811529cb65b1139f0/pandas/tests/series/methods/test_replace.py):

> [Line 217:1](https://github.com/pandas-dev/pandas/blob/a5dc3c4c691fed17e961218811529cb65b1139f0/pandas/tests/series/methods/test_replace.py#L217): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2020-12-28 14:54 UTC, jreback approved these changes

2020-12-28 14:55 UTC, merged

2020-12-28 14:55 UTC, jreback commented
thanks @ftrihardjo