Iloc truncates single-column dataframe with extension arrays
pandas-dev/pandas pull request #38750
Opened 2020-12-28 13:42 UTC by luijkr

Added a test to ensure .iloc does not truncate data for a single-column dataframe with an extension array, as discussed in GH30263.

- [ ] closes #30263
- [x ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2020-12-28 13:42 UTC, pep8speaks commented
Hello @luijkr! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/indexing/test_iloc.py`](https://github.com/pandas-dev/pandas/blob/386f391683fdc09b8d5c0e4f8b36f2d46fe6ea64/pandas/tests/indexing/test_iloc.py):

> [Line 877:1](https://github.com/pandas-dev/pandas/blob/386f391683fdc09b8d5c0e4f8b36f2d46fe6ea64/pandas/tests/indexing/test_iloc.py#L877): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2020-12-28 16:23 UTC, rhshadrach commented on pandas/tests/indexing/test_iloc.py
> +        tm.assert_equal(np.array(df.shape), expected)
I think the issue only appears for ExtensionArray. I'd guess that the behavior you're testing for here is, in some shape or form tested for already, just not for ExtensionArray. Can you check?

Also, as reported in the original issue, `df.shape` returns the expected result but `df.values.shape` does not. Both should be tested (again, for EAs).

2020-12-28 16:51 UTC, jreback requested changes

2020-12-28 16:51 UTC, jreback commented on pandas/tests/indexing/test_iloc.py
> +        # GH30263
also can you add the example from the OP exactly

2021-02-11 01:42 UTC, jreback commented
closing as stale. if you want to continue, pls ping and can re-open.

2021-02-11 01:42 UTC, closed without merging