Update conf.py to execute imports during pdf building
pandas-dev/pandas pull request #38841
Opened 2020-12-31 02:32 UTC by gepcel

According [https://ipython.readthedocs.io/en/stable/sphinxext.html](), it should be `ipython_execlines` not `ipython_exec_lines`. Should close issue #38451

2020-12-31 02:38 UTC, jreback commented
hmm so it is.

2020-12-31 02:39 UTC, jreback commented
cc @simonjayhawkins

2020-12-31 13:09 UTC, simonjayhawkins requested changes
Thanks @gepcel for the PR. will check pdf doc build shortly on my release environment for 1.2 with this change 

changed milestone as we will want to backport this, if merged.

2021-01-03 16:27 UTC, jreback commented
@simonjayhawkins how's this looking

2021-01-05 12:55 UTC, simonjayhawkins commented
will merge this to close #38451 as it does prevent the NameError.

However, something else is awry since `{{ header }}` still appears in the pdf docs.

During the first run of `./make.py latex_forced` it appears in 10 minutes to pandas and no contents are created. we run a second time (I assume to get the contents to build) and on the second run the visualisaztion section is recreated (why this happens is they key to solving this properly) but without the header code being run but the change here means that we don't get the NameErrors

2021-01-05 12:57 UTC, merged

2021-01-05 12:57 UTC, simonjayhawkins commented
Thanks @gepcel

2021-01-06 04:38 UTC, gepcel commented
> However, something else is awry since {{ header }} still appears in the pdf docs.

That might because the section (reference) name is "visualization" and the section title is also "visualization", therefore the `Duplicate implicit target name: "visualization"`.