REF: Move aggregation into apply
pandas-dev/pandas pull request #38867
Opened 2020-12-31 21:51 UTC by rhshadrach

- [ ] closes #xxxx
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

This is a step toward #35725. We can't simply ban agg from not aggregating because it's used by apply for series, dataframe, groupby, resampler, and rolling. There are two other related issues. First, apply, agg, and transform are all doing similar things but with different implementations leading to unintended inconsistencies. Second, we would also like to ban mutation in apply (and presumably agg and transform for the same reasons).

It seems best to me to handle all of these by first combining the implementation into apply, cleaning up and sharing code between the implementations, and then we would be in a good place to ban agg from not aggregating.

This starts the process by moving aggregation.aggregate into apply, but it is only utilized for frames. Once this is done for the remaining objects (series, groupby, resampler, rolling), the rest of the functions in aggregation can be moved into apply as well.

2021-01-01 21:31 UTC, jreback requested changes
cc @jbrockmendel

2021-01-01 21:31 UTC, jreback commented on pandas/core/apply.py
> +    assert how in ("apply", "agg")
prob dont' need this as have in the constructor

2021-01-01 21:31 UTC, jreback commented on pandas/core/apply.py
> +        self.f: Any = f
AggFuncTypeBase?

2021-01-01 21:31 UTC, jreback commented on pandas/core/apply.py
> +    def agg(self):
can you type the return

2021-01-02 17:38 UTC, rhshadrach commented
Thanks @jreback, changes made and green.

2021-01-03 16:55 UTC, jreback approved these changes

2021-01-03 16:55 UTC, jreback commented on pandas/core/frame.py
> +        op = frame_apply(
let's consider having this *inside* the `frame_apply` in the future and just passing the obj (e.g. the transpose / reverse is internal to `frame_apply`)

2021-01-03 16:56 UTC, merged