Contribution
pandas-dev/pandas pull request #38873
Opened 2021-01-01 08:35 UTC by ftrihardjo

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2021-01-01 08:35 UTC, pep8speaks commented
Hello @ftrihardjo! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/series/methods/test_update.py`](https://github.com/pandas-dev/pandas/blob/0d2df961e7af27751daabd81c462b56bd36a391b/pandas/tests/series/methods/test_update.py):

> [Line 111:5](https://github.com/pandas-dev/pandas/blob/0d2df961e7af27751daabd81c462b56bd36a391b/pandas/tests/series/methods/test_update.py#L111): [E301](https://duckduckgo.com/?q=pep8%20E301) expected 1 blank line, found 0

2021-01-01 09:25 UTC, MarcoGorelli commented
Hi @ftrihardjo - could you please put a meaningful title and link to the issue you're closing in the pull request body?

2021-01-01 20:37 UTC, jreback requested changes
looks good, ping on green,

2021-01-01 20:37 UTC, jreback commented on pandas/tests/series/methods/test_update.py
> +    def test_update_with_categorical_type(self):
can you add a blank line before the test.

2021-01-01 20:37 UTC, jreback commented on pandas/tests/series/methods/test_update.py
> +        t = CategoricalDtype(['a', 'b', 'c', 'd'])
call this dtype

2021-01-01 22:36 UTC, jreback commented
see here: https://github.com/pandas-dev/pandas/pull/38873/checks?check_run_id=1634842619

make sure you have `precommit` installed it will fix anything when you commit

2021-01-03 08:43 UTC, MarcoGorelli approved these changes
Thanks @ftrihardjo !

2021-01-03 17:10 UTC, jreback approved these changes

2021-01-03 17:10 UTC, merged

2021-01-03 17:10 UTC, jreback commented
thanks @ftrihardjo