ENH: Use Kahan summation to calculate groupby.sum()
pandas-dev/pandas pull request #38903
Opened 2021-01-02 15:58 UTC by phofl

- [x] closes #38778 
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

This simplifies the op example.

I think 
```
series = Series([1e16, 99, -5e15, -5e15])
series.sum()
```
is dispatched to numpy? Because the result here is wrong too. ``100.0``

2021-01-02 22:01 UTC, phofl commented
We dispatch to numpy in case of 32bit systems, which returns the wrong result

2021-01-02 23:41 UTC, arw2019 commented on doc/source/whatsnew/v1.3.0.rst
> +- Improve numerical stability for :meth:`DataFrameGroupBy.sum()` and :meth:`SeriesGroupBy.sum()` through using Kahan summation (:issue:`38778`)
no brackets after `...GroupBy.sum`?

2021-01-02 23:44 UTC, phofl commented on doc/source/whatsnew/v1.3.0.rst
> +- Improve numerical stability for :meth:`DataFrameGroupBy.sum()` and :meth:`SeriesGroupBy.sum()` through using Kahan summation (:issue:`38778`)
thx

2021-01-03 17:00 UTC, jreback requested changes
comments, ping on green.

note that we have been seeing some recent work on *combing* the aggregation functions for 1d and groupby, this  would be a great case here. (slightly complicated because for 1d we actually dispatch to bottleneck if installed), otherwise we use the `np.nan*` functions so have to see if this is worth it).

2021-01-03 18:00 UTC, phofl commented on doc/source/whatsnew/v1.3.0.rst
> +- Improve numerical stability for :meth:`DataFrameGroupBy.sum` and :meth:`SeriesGroupBy.sum` through using Kahan summation (:issue:`38778`)
Moved

2021-01-03 21:11 UTC, jreback approved these changes

2021-01-03 21:33 UTC, phofl commented
@jreback green

2021-01-03 23:25 UTC, merged

2021-01-03 23:25 UTC, jreback commented
thanks @phofl