REF: de-duplicate code in libparsing/libperiod
pandas-dev/pandas pull request #38915
Opened 2021-01-03 05:19 UTC by jbrockmendel

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

2021-01-03 17:05 UTC, jreback requested changes
lgtm. small comments

2021-01-03 17:05 UTC, jreback commented on pandas/_libs/tslibs/parsing.pyx
> +                # TODO: hack attack, GH#1228
prob can remove the comment now :->

2021-01-03 17:05 UTC, jreback commented on pandas/_libs/tslibs/period.pyx
> +from pandas._libs.tslibs.parsing cimport quarter_to_myear
prob can cimport parse_time_string too

2021-01-03 18:11 UTC, jbrockmendel commented on pandas/_libs/tslibs/parsing.pyx
> +                # TODO: hack attack, GH#1228
updated

2021-01-03 18:11 UTC, jbrockmendel commented on pandas/_libs/tslibs/period.pyx
> +from pandas._libs.tslibs.parsing cimport quarter_to_myear
its not cpdef

2021-01-04 00:10 UTC, jreback approved these changes

2021-01-04 00:10 UTC, merged