BUG: MultiIndex.union dropping duplicates from result
pandas-dev/pandas pull request #38977
Opened 2021-01-05 19:42 UTC by phofl

- [x] xref #38745
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

This more or less sits on top of #36299. The current base-_union implementation works only for sorted indexes correctly if indexes containing duplicates. Hence I've only added tests for sorted indexes,

2021-04-11 00:16 UTC, mroeschke approved these changes
LGTM. Any performance implications?

2021-04-11 00:43 UTC, phofl commented
Thx, code itself is good, but this depends on #40862, after this is merged we can remove the sort_values in the tests. Will run asvs afterwards to check for performance implications

2021-04-13 14:58 UTC, jreback commented
wait for #40862 right?

2021-04-13 14:58 UTC, phofl commented
Yes

2021-04-13 15:23 UTC, jreback requested changes

2021-04-13 16:10 UTC, phofl commented on doc/source/whatsnew/v1.3.0.rst
> +- Bug in :meth:`MultiIndex.union` dropping duplicates from result (:issue:`38977`)
Done, will adjust here after the other is merged and ping then

2021-04-14 14:12 UTC, jreback approved these changes

2021-04-14 16:24 UTC, mroeschke approved these changes
LGTM pending merge conflicts

2021-04-14 20:13 UTC, phofl commented
Unfortunately this looks like a pretty high performance penalty

```
       before           after         ratio
     [84d9c5ed]       [f77120cc]
     <multiindex_union~1^2>       <multiindex_union>
+        77.4±2ms          159±4ms     2.05  multiindex_object.SetOperations.time_operation('non_monotonic', 'int', 'union')
+      33.4±0.5ms         57.9±1ms     1.73  multiindex_object.GetLoc.time_large_get_loc_warm
+         102±1ms          152±2ms     1.49  multiindex_object.SetOperations.time_operation('non_monotonic', 'string', 'union')
+      99.4±0.9ms          144±1ms     1.45  multiindex_object.SetOperations.time_operation('monotonic', 'string', 'union')
+         520±4ms         640±20ms     1.23  multiindex_object.SetOperations.time_operation('non_monotonic', 'datetime', 'union')

```

2021-04-28 00:54 UTC, mroeschke reviewed
IMO I think this is okay given that it fixes a bug. cc @jreback if this is okay despite the performance penalty.

2021-04-30 21:07 UTC, jreback commented
where is the perf diff coming from now?

2021-04-30 22:30 UTC, phofl commented
The Index union for duplicates is not that fast

2021-04-30 22:36 UTC, jreback commented
ok this is fine if this slowdown only occurs when we have duplicates (which i think is the case)

2021-04-30 22:39 UTC, phofl commented
I'll check the benchmarks

2021-05-01 18:08 UTC, phofl commented
Unfortunately the slowdown is for also for non monotonic indexes. We could do it with only dispatching to Index.union in case of duplicates or nans, but this is makes it more complicated unfortunately.

```
       before           after         ratio
     [0158382a]       [692272cb]
                      <multiindex_union>
+         685±5ms         887±20ms     1.30  multiindex_object.SetOperations.time_operation('non_monotonic', 'datetime', 'intersection')
```

2021-05-25 09:28 UTC, simonjayhawkins commented
@phofl can you merge master

2021-05-25 09:34 UTC, phofl commented
Done

2021-05-26 02:02 UTC, merged

2021-05-26 02:02 UTC, jreback commented
thanks @phofl