pandas-dev issue #30699
pandas-dev/pandas pull request #38986
Opened 2021-01-06 01:37 UTC by ftrihardjo

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-01-06 14:20 UTC, jreback requested changes

2021-01-06 14:20 UTC, jreback commented on pandas/tests/extension/test_datetime.py
> +    def test_compare_with_Categorical(self):
can you parameterize this over the  types (date_range and such),

also pls add a case for !=

2021-01-06 15:51 UTC, jorisvandenbossche commented on pandas/tests/extension/test_datetime.py
> +    def test_compare_with_Categorical(self):
We shouldn't add additional tests to this file (some other files in this directory have a note about that, just opened a PR to add that to this file as well -> https://github.com/pandas-dev/pandas/pull/39003)

@ftrihardjo can you move the test to eg `/tests/arrays/test_datetimelike.py` ? (not fully sure what is the best place to put those nowadays) There also already seems to be a `test_compare_categorical_dtype` test in that file, so you can put it close to that one (or see to what extent it overlaps)

2021-01-07 13:56 UTC, jreback requested changes

2021-01-07 13:56 UTC, jreback commented on pandas/tests/arrays/test_datetimelike.py
> +    def test_compare_with_Categorical(self):
can you parameterize  over pd.date_range,timedetla_range and period_range

2021-01-08 00:30 UTC, pep8speaks commented
Hello @ftrihardjo! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/arrays/test_datetimelike.py`](https://github.com/pandas-dev/pandas/blob/949cbd75400dd59bf2c14c14377cb0be47bb2115/pandas/tests/arrays/test_datetimelike.py):

> [Line 88:38](https://github.com/pandas-dev/pandas/blob/949cbd75400dd59bf2c14c14377cb0be47bb2115/pandas/tests/arrays/test_datetimelike.py#L88): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 88:89](https://github.com/pandas-dev/pandas/blob/949cbd75400dd59bf2c14c14377cb0be47bb2115/pandas/tests/arrays/test_datetimelike.py#L88): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (206 > 88 characters)

2021-01-08 14:09 UTC, jreback approved these changes

2021-01-08 14:10 UTC, merged

2021-01-08 14:10 UTC, jreback commented
thanks @ftrihardjo