REGR: errors='replace' when encoding/errors are not specified
pandas-dev/pandas pull request #38997
Opened 2021-01-06 06:02 UTC by twoertwein

- [ ] closes #38989
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

Should 1.3 use `errors='replace'` when no `encoding/errors` are specified or use `errors=None` (strict)?

2021-01-06 12:34 UTC, phofl commented
I would say replace only when encoding is Not set. This should go back to 1.2.1

2021-01-06 13:50 UTC, phofl commented on pandas/io/common.py
> +            if errors is None and ioargs.encoding == "utf-8":
Doesn't this also set ``errors="replace"`` if encoding was given as utf-8?

2021-01-06 14:24 UTC, jreback requested changes
tests!

2021-01-07 02:33 UTC, twoertwein commented
Should a follow-up PR intentionally revert this PR for 1.3? Personally, I would want to know when `read_csv` fails to read certain characters (`errors = None` by default).

2021-01-07 09:06 UTC, phofl commented
I don't think that content from skipped rows should matter and it should raise no error if the rest of the file is ok. Maybe you could add a test withouth skiprows, this raises on 1.1.5 which is good and should keep raising

2021-01-07 13:55 UTC, jreback requested changes

2021-01-07 13:55 UTC, jreback commented on pandas/io/common.py
> +    encoding_not_specified = False
instead why don't you
```
encoding_passed, encoding = encoding, encoding or 'utf-i'
```

and then you can test `encoding_passed is not None` its the same as you have but i think a bit more natural

2021-01-07 17:33 UTC, twoertwein commented
I thought `errors` is exposed in `read_csv`. It isn't. In that case it makes sense to keep `'replace'` as the default.

I don't think it is feasible to ignore encoding errors only for skipped rows. (We could read everything in binary mode but we would need to decode it to determine line endings.)

2021-01-07 17:34 UTC, phofl commented
This errors parameter is Not exposed

2021-01-07 17:36 UTC, twoertwein commented
yes, it isn't exposed. Sorry, that is what I meant to say :)

2021-01-07 18:48 UTC, jreback approved these changes

2021-01-07 18:48 UTC, merged

2021-01-07 18:48 UTC, jreback commented
thanks @twoertwein

2021-01-07 18:48 UTC, jreback commented
@meeseeksdev backport 1.2.x

2021-01-07 19:07 UTC, phofl commented
Thanks