CLN: inspect_excel_format
pandas-dev/pandas pull request #39008
Opened 2021-01-06 21:05 UTC by lithomas1

- [x] closes #38823 
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-01-06 21:45 UTC, rhshadrach requested changes
Thanks for taking this up!

2021-01-06 21:45 UTC, rhshadrach commented on pandas/io/excel/_base.py
> +    content_or_path: Union[None, str, BufferedIOBase, RawIOBase, IO[bytes]] = None,
I don't think the default value or type None is necessary here, is that right?

2021-01-06 21:45 UTC, rhshadrach commented on pandas/io/excel/_base.py
>      assert content_or_path is not None
With the above, would be okay to remove this line.

2021-01-06 23:42 UTC, jreback requested changes

2021-01-06 23:42 UTC, jreback commented on pandas/io/excel/_base.py
> +    content_or_path: Union[None, str, BufferedIOBase, RawIOBase, IO[bytes]] = None,
could just be Buffer? (and I would call the arg buffer)

2021-01-08 16:07 UTC, jreback approved these changes
lgtm. cc @rhshadrach

2021-01-08 21:04 UTC, rhshadrach approved these changes
lgtm

2021-01-08 21:39 UTC, merged

2021-01-08 21:39 UTC, rhshadrach commented
Thanks @lithomas1!