Disallow DataFrame indexer for iloc setitem and getitem
pandas-dev/pandas pull request #39022
Opened 2021-01-07 19:05 UTC by phofl

- [x] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

2021-01-07 19:52 UTC, jorisvandenbossche requested changes
See my note on the PR: https://github.com/pandas-dev/pandas/issues/39004#issuecomment-756344692

In addition, if we disallow this, I think it should be deprecated first for assignment (since that case was working right now)

2021-01-08 14:49 UTC, jreback commented
> See my note on the PR: [#39004 (comment)](https://github.com/pandas-dev/pandas/issues/39004#issuecomment-756344692)
> 
> In addition, if we disallow this, I think it should be deprecated first for assignment (since that case was working right now)

this is reasonable to deprecate for setitem and simply raise for getitem. @phofl if you can amend.

2021-01-08 14:54 UTC, phofl commented
Don't know if I would call this wrong. It is counterintuitive for sure. 

If you *know* that iloc does not align, you may expect the result, Additionally it only works if indexer has the same dimension as the object to index.

Will add a DeprecationWarning

2021-01-08 15:58 UTC, jreback commented
> Will add a DeprecationWarning 

FutureWarning but thanks

2021-01-08 17:36 UTC, phofl commented
Added the Warning

2021-01-08 17:40 UTC, jreback commented on pandas/core/indexing.py
> +                "DataFrame indexer for iloc is deprecated and will be removed in "
```suggestion
                "DataFrame indexer for .iloc is deprecated and will be removed in
                
                 consider using .loc with a DataFrame indexer for automatic alignment.
                   "
```

2021-01-08 17:41 UTC, phofl commented on pandas/core/indexing.py
> +                "DataFrame indexer for iloc is deprecated and will be removed in "
Thx

2021-01-08 17:41 UTC, pep8speaks commented
Hello @phofl! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/indexing.py`](https://github.com/pandas-dev/pandas/blob/82446b5b292382ee90f0cdf2a127f5ddc5f5c5e2/pandas/core/indexing.py):

> [Line 1396:18](https://github.com/pandas-dev/pandas/blob/82446b5b292382ee90f0cdf2a127f5ddc5f5c5e2/pandas/core/indexing.py#L1396): [E131](https://duckduckgo.com/?q=pep8%20E131) continuation line unaligned for hanging indent

2021-01-08 17:41 UTC, jreback commented on pandas/core/indexing.py
> +            raise IndexError("DataFrame indexer is not allowed for iloc")
```suggestion
            raise IndexError("DataFrame indexer is not allowed for .iloc\nConsider using .loc for automatic alignment.")
```

2021-01-08 17:45 UTC, phofl commented
Added a deprecation whatsnew

2021-01-08 19:58 UTC, jreback requested changes
lgtm tiny comment

2021-01-08 19:58 UTC, jreback commented on pandas/core/indexing.py
> +                "a future version",
repeated 'a future version'

2021-01-08 20:34 UTC, phofl commented on pandas/core/indexing.py
> +                "a future version",
Thx, changed

2021-01-08 21:03 UTC, jreback approved these changes

2021-01-08 21:18 UTC, phofl commented
@jreback green

2021-01-08 21:24 UTC, jorisvandenbossche commented
Let's give this a bit more time, since the discussion in https://github.com/pandas-dev/pandas/issues/39004 is still ongoing

2021-01-20 01:01 UTC, jreback commented
@phofl conflict and if you can rebase. i think this is fine to merge.

2021-01-20 09:40 UTC, phofl commented
Done, failure unrelated

2021-01-21 18:05 UTC, jreback commented
this looks fine to me. @jorisvandenbossche are you still objecting?

2021-02-11 00:34 UTC, jreback commented
@phofl can you merge master and update

2021-02-13 20:34 UTC, phofl commented
@jreback merged master, failure unrelated

2021-02-15 23:56 UTC, jreback commented
everyone ok here

@jorisvandenbossche @phofl @jbrockmendel @gooney47

2021-02-17 17:53 UTC, jbrockmendel commented
LGTM

2021-03-02 19:53 UTC, phofl commented
Are we good here?

2021-03-02 21:11 UTC, jreback approved these changes
lgtm. ping on greenish

2021-03-02 22:44 UTC, phofl commented
@jreback greenish

2021-03-02 23:21 UTC, merged

2021-03-02 23:22 UTC, jreback commented
thanks @phofl