Pin xlrd to 1.2.0 temporarily
pandas-dev/pandas pull request #39077
Opened 2021-01-09 22:19 UTC by phofl

- [x] closes #39076
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

Is pinning here the right thing to do in environment.yml?

cc @jreback

2021-01-09 22:30 UTC, phofl commented
Alternatively we could remove this benchmark

2021-01-09 22:41 UTC, jreback requested changes
NO, do not pin this. just remove the benchmark

2021-01-09 22:47 UTC, phofl commented
Done

2021-01-09 22:52 UTC, phofl commented
Have to backport this too.

2021-01-09 23:05 UTC, jreback approved these changes

2021-01-09 23:06 UTC, jreback commented
great, backporting as well to avoid 1.2.x CI failures

2021-01-09 23:33 UTC, phofl commented
@jreback greenish based on the changes here. Azure will take a while because of the new master commits

2021-01-10 00:41 UTC, merged

2021-01-10 00:41 UTC, jreback commented
thanks @phofl

2021-01-10 00:42 UTC, jreback commented
@meeseeksdev backport 1.2.x

2021-01-10 20:27 UTC, jorisvandenbossche commented on asv_bench/benchmarks/io/excel.py
> +    params = ["openpyxl", "odf"]
We could also rather keep this, but with writing an xls file (in addition to the xlsx file) to read with xlrd?