BUG: to_stata tried to remove file before closing it
pandas-dev/pandas pull request #39202
Opened 2021-01-16 01:24 UTC by twoertwein

Spin-off from #39047:

If an error occurred during `to_stata`, the code tried to first remove the file and then close the file handle:

1. removing the file failed on Windows (it is still opened)
2. It created an empty file when closing the handle

2021-01-16 01:31 UTC, jreback commented
this is a regression (i think so?). put a note on 1.2.1

2021-01-16 02:09 UTC, twoertwein commented
yes, you are right! I extended a test to make sure that the file doesn't exists and added a whatsnew entry.

2021-01-16 02:13 UTC, jreback approved these changes
excellent ping on greenish

2021-01-16 04:47 UTC, twoertwein commented
The failing test will not fail in 'real life': the test uses `tm.ensure_clean()` to ensure that the file will not exist. Unfortunately, this means that we have an open file handle that `to_stata` cannot close. I will look into re-writing `ensure_clean()`.

2021-01-16 14:24 UTC, jreback requested changes

2021-01-16 14:24 UTC, jreback commented on doc/source/whatsnew/v1.2.1.rst
> +- :meth:`to_state` did not remove written file when an error occured (:issue:`39202`)
sorry can you fix typo : to_stata also this should be DataFrame.to_stata

2021-01-16 14:26 UTC, jreback commented
also some failures

2021-01-16 16:27 UTC, twoertwein commented
I think `to_stata` is the only `to_*` method that tries to remove created files in case of an error. Is that something other methods should also try to do?

I'm not sure but I could imagine that `__exit__` in `IOHandles` might be able to determine whether an exception from within pandas's io part was raised: if yes, try to delete the files. This would probably only cover local files (no fsspec strings) and only work for `to_*` methods that use `with get_handles(...)` (some methods have to use it without the context manager and explicitly call `close` - `IOHandles` wouldn't know whether an exception occurred.

2021-01-16 16:49 UTC, jreback commented
we should remove it if it's corrupt - however this might be hard to tell

so ok leaving it

2021-01-16 19:23 UTC, twoertwein commented
@jreback green'ish

The new `ensure_clean` has the drawback (I see it as an advantage) that the code using it needs to make sure that no file handle references the temporary file. If an open file handle exists, the test on windows will fail. That's why I had to fix a few tests in this PR.

2021-01-17 00:06 UTC, mroeschke commented on doc/source/whatsnew/v1.2.1.rst
> +- :meth:`DataFrame.to_state` did not remove created file when an error occured (:issue:`39202`)
Nit: `DataFrame.to_state` -> `DataFrame.to_stata`

2021-01-17 15:38 UTC, jreback reviewed
lgtm comment, ping on green

2021-01-17 15:38 UTC, jreback commented on pandas/_testing/contexts.py
> +def ensure_clean(filename="", return_filelike: bool = False, **kwargs: Any):
should revert to `None` right?

2021-01-17 17:12 UTC, twoertwein commented
@jreback  green'ish, failed test seem to be unrelated

2021-01-17 17:27 UTC, simonjayhawkins commented
> failed test seem to be unrelated

yep, known flaky test and pre-commit issue

2021-01-17 19:22 UTC, simonjayhawkins commented
one question before this is merged. How public-ish is tm.ensure_clean?

2021-01-17 19:59 UTC, jreback commented
> one question before this is merged. How public-ish is tm.ensure_clean?

its not

2021-01-18 15:22 UTC, jreback approved these changes

2021-01-18 15:22 UTC, merged

2021-01-18 15:22 UTC, jreback commented
thanks @twoertwein

2021-01-18 15:22 UTC, jreback commented
@meeseeksdev backport 1.2.x

2021-01-18 15:23 UTC, jreback commented
@twoertwein would you mind putting up the backport PR