REF: Split up parsers into smaller files
pandas-dev/pandas pull request #39217
Opened 2021-01-17 00:38 UTC by phofl

- [x] closes #38930
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

Refactored them into 4 files, similar to described in the issue. If this is accepted I will try to clean this up a bit more through unifying the calls a bit

2021-01-19 21:15 UTC, jreback requested changes
i would update `pandas/io/parsers/__init__.py` to import `read_csv, read_fwf, read_table`, and other public functions here (if any others).

you can leave `.readers` just import them to ```__init__.py``` (then you don't need to change the other modules that import).

otherwise this is a straight move?

2021-01-19 21:17 UTC, phofl commented
Thanks, will do that. 

Yes, just moved them around. Will go to refactoring after this

2021-01-19 21:32 UTC, phofl commented
I moved the relevant functions up, I changed the import paths for the helper functions in the test functions

2021-01-19 22:12 UTC, jreback approved these changes
lgtm ping on green

2021-01-19 22:27 UTC, jreback commented
https://github.com/pandas-dev/pandas/pull/39217/checks?check_run_id=1730796224 looks like a real fail

2021-01-19 22:29 UTC, phofl commented
Have to check, this one worked 3 days ago in the pipelines

2021-01-19 22:37 UTC, phofl commented
Hm merged master, let's check if this persists. Can not reproduce this locally

2021-01-19 22:45 UTC, phofl commented
Additionally this worked the commit before when I forgot a few imports. At least a place to start pinning if it persists

2021-01-19 23:15 UTC, phofl commented
Green now

@twoertwein I think you worked with unclosed handles the last few days/weeks? Could you maybe have a look and see if this is familiar?

2021-01-19 23:24 UTC, phofl commented
Failing https://github.com/pandas-dev/pandas/runs/1731152527?check_suite_focus=true too, unrelated here then

2021-01-19 23:32 UTC, twoertwein commented
> @twoertwein I think you worked with unclosed handles the last few days/weeks? Could you maybe have a look and see if this is familiar?

I assume that most of the ssl warnings come from boto3 (I honestly gave up on them for now in #39047). Wasn't a test like that recently xfailed  (reason s3/boto3 being updated)?

2021-01-20 00:07 UTC, phofl commented
Yes, but this test really failed not only raised a warning,

2021-01-20 00:35 UTC, twoertwein commented
do you mean the  `OSError: [Errno 98] Address already in use` in `test_server_and_default_headers test`? Is it possible that multiple instances of pytest run on the same machine but they like to use the same port?

or `test_warn_if_chunks_have_mismatched_type`. I think I have looked at this (or a similar) test when working on #39047. As far as I remember, there shouldn't be a need for any "ssl-stuff" in this test. The only resource that might not be closed is `StringIO`. Locally (on linux) I can not re-create most of the ResourceWanrings.

2021-01-20 08:44 UTC, phofl commented
Sorry this was not clear enough by myself. I was talking about ``test_warn_if_chunks_have_mismatched_type``. Have the same issue, can not reproduce locally.

2021-01-21 23:48 UTC, jreback commented on pandas/io/parsers/readers.py
> +def _clean_na_values(na_values, keep_default_na=True):
might be worth moving from here down to another module (validation.py?) in a followup, e.g. keep readers.py for the actual readers

2021-01-21 23:48 UTC, jreback approved these changes

2021-01-21 23:48 UTC, merged

2021-01-21 23:48 UTC, jreback commented
thanks @phofl