BUG: SeriesGroupBy.value_counts() raising error on an empty Series
pandas-dev/pandas pull request #39326
Opened 2021-01-21 19:09 UTC by AnnaDaglis

- [x] closes #39172
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

2021-01-21 20:52 UTC, jreback requested changes
lgtm @AnnaDaglis minor comment, pls ping on green

2021-01-21 20:52 UTC, jreback commented on pandas/core/groupby/generic.py
> +        if len(ids) == 0:
can you do `not len(ids)` (and same below)

2021-01-22 20:24 UTC, AnnaDaglis commented
@jreback Green and ready to go!

2021-01-22 21:43 UTC, jreback commented
looks good. can you merge master and ping on green (the reason is just merged a PR that changes the hashing of .value_counts()); it should be fine, just making sure.

2021-01-22 23:23 UTC, AnnaDaglis commented
@jreback I've merged the master, and it's green

2021-01-22 23:26 UTC, jreback approved these changes

2021-01-22 23:26 UTC, merged

2021-01-22 23:26 UTC, jreback commented
thanks @AnnaDaglis keep em coming!