BUG: read_excel failing to check older xlrd versions properly
pandas-dev/pandas pull request #39355
Opened 2021-01-23 20:43 UTC by lithomas1

- [ ] closes #38955
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

Probably should be in 1.2.1 given that this occurred after the deprecation of the xlrd engine in 1.2. 
cc @rhshadrach

2021-01-24 02:05 UTC, rhshadrach requested changes
Thanks @lithomas1! Seems to me we should be using `_optional._get_version`. Also I think there  is one in the tests - can you change that too.

2021-01-25 21:42 UTC, pep8speaks commented
Hello @lithomas1! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/io/excel/_base.py`](https://github.com/pandas-dev/pandas/blob/7bd431d2b01e7a83fcbef10c2af084d922ee98e2/pandas/io/excel/_base.py):

> [Line 1057:1](https://github.com/pandas-dev/pandas/blob/7bd431d2b01e7a83fcbef10c2af084d922ee98e2/pandas/io/excel/_base.py#L1057): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2021-01-25 22:21 UTC, rhshadrach commented
@lithomas1 I think we still want to use LooseVersion, can apply it to the result of `_get_version`.

2021-01-26 13:48 UTC, simonjayhawkins commented on doc/source/whatsnew/v1.2.2.rst
> +- Fixed bug in :meth:``read_excel`` that caused it to fail when checking version of older xlrd versions(:issue:`38955`)
can you move to regression section above

2021-01-26 13:49 UTC, simonjayhawkins commented
pre-commit failing

```
pandas/io/excel/_base.py:5:1: F401 'distutils.version.LooseVersion' imported but unused
pandas/tests/io/excel/__init__.py:1:1: F401 'distutils.version.LooseVersion' imported but unused
```

2021-01-28 14:58 UTC, jreback commented
@lithomas1 can you merge master and update

2021-01-28 19:57 UTC, jreback commented on pandas/io/excel/_base.py
> +from pandas.compat._optional import _get_version, import_optional_dependency
we should make this `get_version` and not a private function that is imported across modules. can you make this change as well?

2021-01-29 10:21 UTC, simonjayhawkins commented on doc/source/whatsnew/v1.2.2.rst
> +- Fixed bug in :meth:``read_excel`` that caused it to fail when checking version of older xlrd versions(:issue:`38955`)
```suggestion
- Fixed regression in :func:`read_excel` that caused it to raise ``AttributeError`` when checking version of older xlrd versions (:issue:`38955`)
```

2021-01-30 21:18 UTC, rhshadrach commented
@lithomas1 Can also remove `"_get_version"` from scripts/validate_unwatned_patterns.py

2021-01-31 13:52 UTC, rhshadrach approved these changes
lgtm - thanks @lithomas1!

2021-02-01 13:45 UTC, merged

2021-02-01 13:45 UTC, jreback commented
thanks @lithomas1

2021-02-01 13:46 UTC, jreback commented
@meeseeksdev backport 1.2.x

2021-02-01 13:48 UTC, jreback commented
hmm this is not backporting cleanly, @lithomas1 can you follow the instructions above and put up a PR

2023-12-31 14:12 UTC, rhshadrach commented
@brobr - can you raise this as a new issue