BUG: #35830 Restore index by Date to DatetimeIndex
pandas-dev/pandas pull request #39380
Opened 2021-01-24 20:35 UTC by davidia

DatetimeIndex has supported indexing by date for many many years. This was broken
after 1.0.5. This attempts to restore support by promoting date a non--tz aware
datetime at midnight.

- [x] closes #35830
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-01-24 20:38 UTC, davidia commented
I an add more testes for slicing and asof if this will be considered for merging

2021-01-24 22:43 UTC, jreback requested changes
i would be ok with a warning but we deliberately change this as it's incorrect

2021-01-25 04:16 UTC, seth-p requested changes

2021-04-02 06:14 UTC, mroeschke commented
Closing as it appears this PR has gotten stale. Let us know if you'd like to continue adding a deprecation warning for this behavior and we'd be happy to reopen.

2021-04-02 06:14 UTC, closed without merging