ENH: Styler css Str optional input arguments as well as List[Tuple]
pandas-dev/pandas pull request #39564
Opened 2021-02-02 20:13 UTC by attack68

- [x] closes #39563 
- [x] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-02-04 14:15 UTC, attack68 commented
this is ready for review..

2021-02-04 15:16 UTC, jreback requested changes
looks fine. couple of comments.

2021-02-04 15:16 UTC, jreback commented on pandas/io/formats/style.py
> +):
can you add an output type (maybe define this at the top as CSSProperties or similar)

2021-02-04 15:16 UTC, jreback commented on doc/source/whatsnew/v1.3.0.rst
> +- :meth:`.Styler.set_tooltips_class` and :meth:`.Styler.set_table_styles` amended to optionally allow certain css-string input arguments.
locate after the other note, L56 (which is missing an issue number; use the PR number for it)

2021-02-04 21:46 UTC, attack68 commented
@jreback changes made, with some better typing throughout the module.

one failed test is unrelated.

2021-02-05 14:57 UTC, jreback approved these changes

2021-02-05 14:57 UTC, merged

2021-02-05 14:57 UTC, jreback commented
thanks @attack68 keep em coming!