pandas-dev issue #24211
pandas-dev/pandas pull request #39638
Opened 2021-02-07 12:46 UTC by ftrihardjo

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-02-07 13:22 UTC, MarcoGorelli commented
Thanks @ftrihardjo - could you make the title the same as the issue please, and put the issue number in the pull request body (near `closes #`) ?

2021-02-07 16:33 UTC, jreback requested changes

2021-02-07 16:33 UTC, jreback commented on pandas/tests/groupby/transform/test_transform.py
> +        df.groupby("key").transform("ffill")["values"],
can you use
result=
expected=

2021-02-07 16:33 UTC, jreback commented on pandas/tests/groupby/transform/test_transform.py
> +
test both for seriesgropuby & dataframegroupby

2021-02-07 16:33 UTC, jreback commented on pandas/tests/groupby/transform/test_transform.py
> +    data = [["a", 0.0], ["a", float("nan")], ["b", 1.0], ["b", float("nan")]]
can you co-locate with other ffill/filling tests (in this file)

2021-02-14 11:20 UTC, MarcoGorelli approved these changes

2021-02-15 22:34 UTC, jreback approved these changes

2021-02-15 22:34 UTC, merged

2021-02-15 22:34 UTC, jreback commented
thanks @ftrihardjo