DEP: bump min version of openpyxl to 3.0.0 #39603
pandas-dev/pandas pull request #39702
Opened 2021-02-09 17:23 UTC by fangchenli

- [ ] closes #39603

2021-02-09 22:04 UTC, jreback commented
cc @rhshadrach

2021-02-09 23:18 UTC, rhshadrach requested changes
There are also some version checks in the openpyxl tests that can be removed/simplified.

2021-02-11 23:32 UTC, rhshadrach requested changes
Small request, rest look great!

2021-02-11 23:32 UTC, rhshadrach commented on pandas/io/excel/_openpyxl.py
> -        # writers sometimes omit or get it wrong
Can you move this comment down to the `if is_readonly` below, add that it only impacts read-only worksheets

2021-02-13 23:03 UTC, rhshadrach approved these changes
lgtm, thanks @fangchenli

2021-02-15 22:14 UTC, merged

2021-02-15 22:14 UTC, jreback commented
thanks @fangchenli