Fix series pad
pandas-dev/pandas pull request #39978
Opened 2021-02-22 21:23 UTC by dylanp-git

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

#39640 Added doc tag above ffill() to substitute klass

2021-02-22 23:19 UTC, jreback commented
cc @simonjayhawkins @jorisvandenbossche 

lgtm.

2021-02-23 11:05 UTC, simonjayhawkins requested changes
can we also fix bfill/backfill while doing this. basically same issue, needs same change applied to L6516

2021-02-23 20:28 UTC, dylanp-git commented
yeah I can do that. I'm not sure what "Igtm" or "L6516" mean/referring to, if I need to know then could someone let me know please.

2021-02-23 20:34 UTC, MarcoGorelli commented
@dylanp-git lgtm means 'looks good to me'; L6516 is line number 6516

2021-02-23 20:38 UTC, dylanp-git commented
> @dylanp-git lgtm means 'looks good to me'; L6516 is line number 6516

aha thankyou, I'm slowly learning the lingo!!

2021-02-24 13:35 UTC, jorisvandenbossche approved these changes

2021-02-24 13:36 UTC, merged

2021-02-24 13:36 UTC, jorisvandenbossche commented
Thanks a lot @dylanp-git !

2021-02-24 14:55 UTC, dylanp-git commented
> Thanks a lot @dylanp-git !

No worries! I was going to look into it again later as only 20/22 checks passed?

On another note, how many "good first issue" issues do you think I should do before trying something a bit more in-depth?

2021-02-24 15:08 UTC, MarcoGorelli commented
> only 20/22 checks passed?

the failures were unrelated (sometimes that happens)

> how many "good first issue" issues do you think I should do before trying something a bit more in-depth?

IMO if you've got familiar with the contribution workflow then you could start immediately