pandas-dev issue #24271
pandas-dev/pandas pull request #39986
Opened 2021-02-23 06:45 UTC by ftrihardjo

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-02-23 06:45 UTC, pep8speaks commented
Hello @ftrihardjo! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/groupby/test_groupby.py`](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py):

> [Line 151:28](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L151): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 151:34](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L151): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 151:44](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L151): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 152:26](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L152): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 152:49](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L152): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 153:20](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L153): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 153:30](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L153): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 160:56](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L160): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 161:18](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L161): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 162:18](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L162): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 163:18](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L163): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 164:18](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L164): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 165:18](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L165): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 166:18](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L166): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 167:41](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L167): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 167:56](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L167): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 168:26](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L168): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 168:28](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L168): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 169:34](https://github.com/pandas-dev/pandas/blob/bce5e0ac67636b35dd7d51f68290db21aa3121fb/pandas/tests/groupby/test_groupby.py#L169): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2021-02-23 08:11 UTC, MarcoGorelli commented
Hi @ftrihardjo - could you put "closes #24271" in the pull request description and put a descriptive title (e.g. the name of the issue) please?

2021-02-25 00:57 UTC, jreback requested changes
pls also merge master

2021-02-25 00:57 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +def test_multi_index_sort():
can you rename to 

test_sorting_with_different_categoricals

2021-02-25 00:57 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +def test_multi_index_sort():
move to test_categorical.py (same directory)

2021-03-15 00:32 UTC, jreback approved these changes

2021-03-15 00:32 UTC, merged

2021-03-15 00:32 UTC, jreback commented
thanks @ftrihardjo