REF: Consolidate validation of dictionary argument in agg/transform
pandas-dev/pandas pull request #40004
Opened 2021-02-23 21:58 UTC by rhshadrach

- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

Currently there are no tests for dict-like argument with agg when a DataFrame is missing a column. This PR changes the error slightly from

> f"Column '{k}' does not exist!"

to

> f"Column(s) {cols} do not exist"

in order to make it consistent (and I think more helpful, in the case of multiple columns) with the error message from transform.

2021-02-23 22:37 UTC, rhshadrach commented
@jreback - added test_invalid_arg to start reorganizing the apply tests to something with a better layout. If this seems like a good idea, will move other relevant tests here in a followup.

2021-02-24 16:34 UTC, jreback commented
great, this is a very small api change (e.g. now get SpecificationError rather than KeyError in some cases), can you add a whatsnew note. ping on green.

2021-02-24 17:45 UTC, rhshadrach commented
@jreback Ah - thanks for catching this. Before adding the note - is it clear that we want a SpecificationError here and not KeyError? Looking throughout pandas.core, I only see SpecificationError used in three places:

 - groupby.generic._aggregate_multiple_funcs
 - aggregation.reconstruct_func  - only used by DataFrame.agg and DataFrameGroupBy.agg
 - apply for transform (and with this PR, agg too)

In each case, I believe either KeyError or ValueError is also appropriate. It seems to me maybe changing to KeyError for transform here would be better, and removing SpecificationError altogether in the future. This would also having the benefit of a smaller API change (transform is only used by Series/DataFrame here, whereas agg is used by GroupBy/Resampler/Rolling).

2021-02-24 18:11 UTC, jreback requested changes

2021-02-24 18:11 UTC, jreback commented on pandas/tests/apply/test_invalid_arg.py
> +    with pytest.raises(SpecificationError, match=match):
this error is good

2021-02-24 18:11 UTC, jreback commented on pandas/tests/apply/test_invalid_arg.py
> +    with pytest.raises(SpecificationError, match=match):
would be ok here with a KeyError (which i think is the same as now)

2021-02-25 00:42 UTC, jreback approved these changes

2021-02-25 00:42 UTC, merged

2021-02-25 00:42 UTC, jreback commented
very nice!