TYP: incorrect annotations in internals.construction
pandas-dev/pandas pull request #40061
Opened 2021-02-25 20:14 UTC by jbrockmendel

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-02-26 00:26 UTC, jreback requested changes
any perf difference? (e.g. wrapping with Index / ensure_index) a few times

2021-02-26 00:26 UTC, jreback commented
cc @simonjayhawkins if you have a chance to look

2021-02-27 16:21 UTC, jbrockmendel commented
> any perf difference? (e.g. wrapping with Index / ensure_index) a few times

i dont think so; the Index wrapping would have to happen eventually anyway.  if anything, early consistent wrapping should make it easier to avoid re-checking later

2021-02-27 18:13 UTC, jreback approved these changes

2021-02-27 18:13 UTC, merged