Make Index.all compatible with numpy.all
pandas-dev/pandas pull request #40180
Opened 2021-03-02 20:15 UTC by pauldmccarthy

- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

Due to a bug in my own code, I discovered that `pandas.Index` objects cannot be passed to the `numpy.all` function:

```python
In [1]: import numpy as np

In [2]: import pandas as pd

In [3]: idx = pd.Int64Index([1,2,3,4,5])

In [4]: np.all(idx)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-597ac8c43e48> in <module>
----> 1 np.all(idx)

<__array_function__ internals> in all(*args, **kwargs)

~/venvs/funpack.venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py in all(a, axis, out, keepdims, where)
   2437     """
   2438     return _wrapreduction(a, np.logical_and, 'all', axis, None, out,
-> 2439                           keepdims=keepdims, where=where)
   2440
   2441

~/venvs/funpack.venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     83                 return reduction(axis=axis, dtype=dtype, out=out, **passkwargs)
     84             else:
---> 85                 return reduction(axis=axis, out=out, **passkwargs)
     86
     87     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

TypeError: all() got an unexpected keyword argument 'axis'
```

Using [this PR](https://github.com/pandas-dev/pandas/pull/26324/) as precedent, the fix is quite straightforward.

2021-03-04 01:55 UTC, jreback requested changes

2021-03-04 01:55 UTC, jreback commented on doc/source/whatsnew/v1.2.4.rst
> +- Allow :class:`Index` to be passed to the numpy ``all`` function.
move to 1.3 Bug Fixes in reshaping section, add the PR number as the issue number, can you reference np.all here I think `:func:numpy.all` works or similar

2021-03-04 01:55 UTC, jreback commented on pandas/tests/reductions/test_reductions.py
> +        idx = Index([0, 1, 2])
can you add the issue number as a comment

2021-03-04 01:55 UTC, jreback commented on pandas/tests/reductions/test_reductions.py
> +        idx = Index([0, 1, 2])
can you move this near other tests similar to `def test_any_all`

2021-03-04 01:57 UTC, jreback requested changes

2021-03-04 01:57 UTC, jreback commented on pandas/tests/reductions/test_reductions.py
> +        idx = Index([0, 1, 2])
can you parameterize over Index & Series

2021-03-04 15:56 UTC, pauldmccarthy commented
@jreback Requested changes made - thanks!

2021-03-05 01:28 UTC, jreback approved these changes

2021-03-05 01:28 UTC, merged

2021-03-05 01:28 UTC, jreback commented
thanks @pauldmccarthy very nice!