Add examples to documentation for DataFrame.swaplevel
pandas-dev/pandas pull request #40269
Opened 2021-03-06 12:42 UTC by thordisstella

- [x ] closes https://github.com/MarcoGorelli/pyladies-sprint-March-2021/issues/13
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-03-06 12:42 UTC, pep8speaks commented
Hello @thordisstella! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/frame.py`](https://github.com/pandas-dev/pandas/blob/7daa05c368dc6b20f12bfeeab5fea519e014e195/pandas/core/frame.py):

> [Line 6285:89](https://github.com/pandas-dev/pandas/blob/7daa05c368dc6b20f12bfeeab5fea519e014e195/pandas/core/frame.py#L6285): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 88 characters)
> [Line 6296:89](https://github.com/pandas-dev/pandas/blob/7daa05c368dc6b20f12bfeeab5fea519e014e195/pandas/core/frame.py#L6296): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (106 > 88 characters)
> [Line 6298:89](https://github.com/pandas-dev/pandas/blob/7daa05c368dc6b20f12bfeeab5fea519e014e195/pandas/core/frame.py#L6298): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (96 > 88 characters)
> [Line 6306:89](https://github.com/pandas-dev/pandas/blob/7daa05c368dc6b20f12bfeeab5fea519e014e195/pandas/core/frame.py#L6306): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 88 characters)

2021-03-06 17:25 UTC, MarcoGorelli requested changes
Really nice example @thordisstella , thanks, have just left some minor comments

2021-03-06 17:25 UTC, MarcoGorelli commented on pandas/core/frame.py
> +        ...                         ['January','February','March','April']])
Could you reformat this according to the `black` formatter (to be consistent with most of the rest of the docs...we should probably run `blackdoc`, but that's for a separate issue/PR)

2021-03-06 17:25 UTC, MarcoGorelli commented on pandas/core/frame.py
> +        >>> df.swaplevel(0,1)
can you add a space between the arguments? (`swaplevel(0, 1)`)

2021-03-08 18:08 UTC, thordisstella commented
> Really nice example @thordisstella , thanks, have just left some minor comments

Thanks for the review @MarcoGorelli! I addressed the comments, but when I ran `black` on the changes I'd made, nothing further was updated (after I'd addressed your other two comments). Please let me know if I've missed something here

2021-03-08 20:57 UTC, MarcoGorelli commented
Hey @thordisstella , thanks for updating! Sorry, I was unclear - `black` indeed won't modify what you've written, because it doesn't format code inside docstrings (barring some very minor things). I was suggesting to reformat the docstring the way that `black` would - one way to do this would be to paste the docstring into a temporary file (say, `t.py`):
```python
# t.py

"""
        >>> df = pd.DataFrame({'Grade':['A','B','A','C']},
        ...                   index=[['Final exam', 'Final exam', 'Coursework',
        ...                              'Coursework'],
        ...                         ['History','Geography','History','Geography'],
        ...                         ['January','February','March','April']])
"""
```
, running
```python
pip install blackdoc
blackdoc t.py --line-length 80
```
and then pasting the reformatted version back into this docstring of `swaplevel`

Finally, you should run
```console
$ python scripts/validate_docstrings.py pandas.DataFrame.swaplevel
```
and check it doesn't throw any extra errors compared to when run on `master` (in this case you prob. just need to reformat the code in the example and remove the extra blankline at the end of the docstring)

2021-03-09 09:51 UTC, thordisstella commented
Thanks, and belated happy IWD to you too! 😊 

Thanks for the clarification - I've updated the PR as you suggested so hopefully we should be good now 🤞

2021-03-09 10:19 UTC, MarcoGorelli requested changes
Thanks - there's just a blank line which needs removing (else it'll fail `scripts/validate_docstrings.py`), rest looks good

2021-03-09 10:19 UTC, MarcoGorelli commented on pandas/core/frame.py
>          """
```suggestion
        Geography   Coursework  April           C
        """
```

2021-03-10 09:02 UTC, MarcoGorelli commented
Hi @thordisstella - looks good, CI failures should be unrelated, could you fetch and merge upstream/master please?

2021-03-11 21:00 UTC, MarcoGorelli approved these changes
Pending green, looks good to me!

(a follow-up PR to add a similar example to `Series.swaplevel` and/or make a shared docstring would be welcome if you want)

2021-03-12 14:10 UTC, merged

2021-03-15 13:58 UTC, thordisstella commented
Thanks for the review, all the advice and for merging this @MarcoGorelli ! And apologies for the delay in reacting to your last comment. I'll take a look at the follow up PR you suggested either later this week or next week :)