STYLE: Resolved Inconsistent namespace
pandas-dev/pandas pull request #40286
Opened 2021-03-07 14:00 UTC by deepang17

- [ ] closes #39992 
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-03-07 14:17 UTC, MarcoGorelli commented
Hi @deepang17 - instead of excluding a file, can we change `test_unique_tuples` so the last argument of the function is `uniques` instead of `unique`?

2021-03-07 14:19 UTC, deepang17 commented
Sure, will do that.

2021-03-07 15:15 UTC, MarcoGorelli commented
Thanks, looks good - I'll just mark this as draft pending on https://github.com/pandas-dev/pandas/issues/39992#issuecomment-792294708 , will then reopen and rebase (depending on what we hear back)

2021-03-08 17:13 UTC, MarcoGorelli commented
Hi @deepang17 - #40310 is in, do you want to rebase and fix up any remaining errors so we can get this in?

2021-03-08 17:23 UTC, deepang17 commented
Hello, @MarcoGorelli I have completed work from my side. If you think that changing from `unique` to `uniques` is not a breaking change then this works fine.

2021-03-08 17:26 UTC, MarcoGorelli commented
You'll also need to change it to `uniques` in
```
    @pytest.mark.parametrize(
        "arr, unique",
```

It's just a variable in a test, so it's not a breaking change

If you could fetch and merge upstream/master and fixup "unique" in `pytest.mark.parametrize` then this should be good to go

2021-03-08 17:28 UTC, deepang17 commented
Ok, will do that.

2021-03-08 17:56 UTC, MarcoGorelli requested changes
Thanks for updating - there's still some files to be fixed up though, which are failing the pre-commit check

2021-03-08 17:56 UTC, deepang17 commented
![image](https://user-images.githubusercontent.com/47976918/110361148-a0a2ad00-8065-11eb-89e1-e5996f7fbbb3.png)

@MarcoGorelli these new files are producing the error.

![image](https://user-images.githubusercontent.com/47976918/110361228-bdd77b80-8065-11eb-84c6-0d5da79597e6.png)

2021-03-08 18:03 UTC, deepang17 commented
Shall I convert them to arrays?

2021-03-08 20:46 UTC, MarcoGorelli commented
I'd suggest renaming to `arr` rather than `arrays`, as here there's only one of them (`uniques` in `test_algos.py` is fine as there's many objects there anyway many objects and arguably might have been better named `uniques` from the start)

2021-03-08 20:55 UTC, deepang17 commented
`arr` is used at quite a few places, so it will again create conflicts. Please suggest something else. Thank you.

2021-03-08 21:08 UTC, MarcoGorelli requested changes
I've made some suggestions for some files, for the others I think `arr` might work (if not, please let me know for which ones it doesn't)

2021-03-08 21:08 UTC, MarcoGorelli commented on pandas/tests/arithmetic/test_interval.py
> +def arrays(left_right_dtypes):
can we rename to `interval_array`?

2021-03-08 21:08 UTC, MarcoGorelli commented on pandas/tests/arrays/sparse/test_array.py
> +        "arrays, dtype, expected",
how about `sparse_array`?

2021-03-08 21:08 UTC, MarcoGorelli commented on pandas/tests/arrays/string_/test_string.py
> +    arrs = pd.array(["a", "b", "c", "d"], dtype=dtype)
I think `arr` will work in this file? Else `pd_array`?

2021-03-08 21:08 UTC, MarcoGorelli commented on pandas/tests/arrays/test_datetimelike.py
> +    "arrays,casting_nats",
how about `ts_array` (for time series array)?

2021-03-08 21:08 UTC, MarcoGorelli commented on pandas/tests/dtypes/test_inference.py
> -        array = np.array([datetime(2015, 1, 1, tzinfo=pytz.utc), 1], dtype=object)
np_array ?

2021-03-08 21:08 UTC, MarcoGorelli commented on pandas/tests/extension/base/getitem.py
> +        arrays = data_missing._from_sequence(
I think `arr` will work in this file?

2021-03-08 21:08 UTC, MarcoGorelli commented on pandas/tests/indexing/test_check_indexer.py
> +    arrays = np.array([1, 2, 3])
I think `arr` will work in this file too

2021-03-08 23:46 UTC, deepang17 commented
@MarcoGorelli it's ready to be merged. Thank you for your guidance.

2021-03-09 10:15 UTC, MarcoGorelli requested changes
Hi @deepang17 

>  it's ready to be merged

I admire your confidence :) Still have some comments though, I think some of these names are unclear and that `arr` should work in those files

2021-03-09 10:15 UTC, MarcoGorelli commented on pandas/tests/series/test_ufunc.py
> +    u_arr = np.random.randint(0, 10, 10, dtype="int64")
can't this be `arr`? I just tried it and it was fine - besides, what does `u_arr` stand for? Unary array? If so, what is that?

2021-03-09 10:15 UTC, MarcoGorelli commented on pandas/tests/indexing/test_check_indexer.py
> +    n_arr = np.array([1, 2, 3])
this looks like it could mean `number of arrays`. `arr` will work here, I just tried it

2021-03-09 10:55 UTC, MarcoGorelli approved these changes
Looks good to me pending green, cc @jbrockmendel / @jorisvandenbossche for any further comments

2021-03-09 16:48 UTC, jbrockmendel commented on pandas/tests/arrays/string_/test_string.py
> +    pd_array = pd.array(["a", "b", "c", "d"], dtype=dtype)
pd_array -> arr

2021-03-10 09:47 UTC, MarcoGorelli requested changes

2021-03-10 09:47 UTC, MarcoGorelli commented on pandas/tests/extension/base/getitem.py
> +        d_arr = data_missing._from_sequence(
as suggested in https://github.com/pandas-dev/pandas/pull/40286#discussion_r589747955 , can't this just be `arr`? It's not clear to me what `d_arr` is mean to stand for

2021-03-10 11:01 UTC, MarcoGorelli approved these changes

2021-03-11 10:56 UTC, MarcoGorelli approved these changes
I went ahead and renamed the rest of these `*_array` to `arr` and they seem to be fine, not sure why you said there'd be conflicts - perhaps it was just the fixture?

2021-03-11 13:12 UTC, deepang17 commented
Great, at that time some other variables were also used with the name `arr` and one of them produced an error for me hence I thought it will produce an error for all. But now as you have done it, it seems fine.

2021-03-11 13:47 UTC, MarcoGorelli commented
Thanks @deepang17 !

2021-03-11 13:47 UTC, merged