docs: changes to documentation
pandas-dev/pandas pull request #40305
Opened 2021-03-08 13:05 UTC by mohamed-khoualed

docs: changes to documentation
small grammatical update to the documentation

2021-03-08 14:13 UTC, jreback requested changes

2021-03-08 14:13 UTC, jreback commented on doc/source/reference/index.rst
> +methods. All classes and functions are exposed in ``pandas.*`` namespace are public.
revert this as, or add 'the' later in the sentence

2021-03-08 14:13 UTC, jreback commented on doc/source/development/contributing.rst
> +operations. To install pandas from the source, you need to compile these C
revert this, its a common saying

2021-03-08 14:13 UTC, jreback commented on doc/source/development/contributing.rst
> +To test out code changes, you'll need to build pandas from the source, which
revert this

2021-03-09 14:17 UTC, Bhard27 commented on doc/source/development/contributing.rst
> +you need to learn how to work with GitHub and the pandas codebase.
In computer science programming, we usually write Codebase and not Code base/ Code-Base. So I think this is not that necessary.

2021-05-25 11:59 UTC, simonjayhawkins commented
@mohamed-khoualed closing as stale. ping when ready to continue

2021-05-25 11:59 UTC, closed without merging