DEPS: sync fastparquet version
pandas-dev/pandas pull request #40424
Opened 2021-03-14 05:19 UTC by fangchenli

follow up #38344

2021-03-14 16:05 UTC, rhshadrach requested changes
Looks like the version in TestParquetFastParquet needs updated too.

2021-03-14 18:24 UTC, rhshadrach approved these changes
lgtm

2021-03-14 23:32 UTC, jreback requested changes

2021-03-14 23:32 UTC, jreback commented on pandas/tests/io/test_parquet.py
> +    from pandas.compat._optional import VERSIONS
I don't think you need this at all, just remove the min version, no?

2021-03-15 16:59 UTC, jreback approved these changes

2021-03-15 16:59 UTC, merged