ENH: `escape` html argument in Styler.format
pandas-dev/pandas pull request #40437
Opened 2021-03-14 22:42 UTC by attack68

- [x] closes #40388 

Adds an HTML `escape` parameter to `Styler.format`, which acts to escape the data value **before** it is passed to a formatter.

For example, `Styler.format('<a href="a.com/{0}">{0}</a>', escape=True)` will not escape the HTML as part of the formatting function, it will only escape the value `{0}` going into the formatter.

2021-03-15 00:07 UTC, jreback requested changes
sure, minor comment. ping on green.

2021-03-15 00:07 UTC, jreback commented on pandas/io/formats/style.py
> +
versionadded 1.3

2021-03-15 00:07 UTC, jreback commented
cc @jnothman if comments.

2021-03-15 00:08 UTC, jreback commented
also checks are failing

2021-03-15 02:28 UTC, jnothman approved these changes
LGTM

2021-03-15 07:30 UTC, attack68 commented
> also checks are failing

when fixing these I noticed that the `na_rep` was not working with `escape` since missing values were escaped before being replaced.

so I refactored to fix this and added a test for it.

@jreback ping is green.

2021-03-15 10:31 UTC, attack68 commented on pandas/io/formats/style.py
> +            return lambda x: na_rep if pd.isna(x) else formatter_func(escape_func(x))
This might be a bug escaping floats, since escaping converts to string. Will review and come back

2021-03-15 16:07 UTC, attack68 commented on pandas/io/formats/style.py
> +            return lambda x: na_rep if pd.isna(x) else formatter_func(escape_func(x))
OK this is fixed now too. 3rd test added.

2021-03-15 16:12 UTC, jreback requested changes

2021-03-15 16:43 UTC, attack68 commented on pandas/io/formats/style.py
>      if na_rep is None:
hows this?

2021-03-15 17:06 UTC, jreback commented on pandas/io/formats/style.py
>      if na_rep is None:
good

2021-03-22 18:46 UTC, attack68 commented
this should be good to go in now, I believe.

2021-03-23 17:03 UTC, jreback approved these changes

2021-03-23 17:03 UTC, merged

2021-03-23 17:03 UTC, jreback commented
thanks @attack68