DOC: release notes for 1.3.0 Styler
pandas-dev/pandas pull request #40637
Opened 2021-03-25 16:53 UTC by attack68

Added a note to the enhancements section detailing some different upgrades to `Styler` for 1.3.0

If this is not standard or unnecessary just close this PR - I'm only including it in case it is helpful (it is not for self-publication), so I am completely indifferent!

Hopefully there will be one or two more items to add before the end of May.

2021-03-29 13:44 UTC, jreback requested changes

2021-03-29 13:44 UTC, jreback commented on doc/source/whatsnew/v1.3.0.rst
> +The :meth:`.Styler.format` has also had upgrades to easily format missing data,
sure this is fine. pls indicate the releavant issues / PR number as appropriate

2021-04-02 17:35 UTC, jreback approved these changes

2021-04-02 17:36 UTC, jreback commented
can you merge master and ping on green

2021-04-02 20:30 UTC, attack68 commented
@jreback pinging green now

2021-04-02 21:37 UTC, merged