CLN: move pytest config to pyproject.toml
pandas-dev/pandas pull request #40656
Opened 2021-03-27 14:23 UTC by fangchenli

According to https://docs.pytest.org/en/stable/customize.html, using `setup.cfg`as pytest config file is not recommended. So moved everything to `pyproject.toml`

2021-03-28 16:42 UTC, jbrockmendel commented
I'm reticent to do this.  The everything-in-one-file nature of setup.cfg is really nice improvement over the older proliferation of config files

2021-03-31 02:20 UTC, twoertwein commented
> I'm reticent to do this. The everything-in-one-file nature of setup.cfg is really nice improvement over the older proliferation of config files

Isn't pyproject.toml the "new" everything-in-one file? I would love to be able to use `poetry update` in the source tree to get all dependencies installed/updated (would need to move all the depdencies to pyproject.toml).

2021-04-01 23:03 UTC, jreback commented
can we move *everything* to pyproject.toml? (or is this not supported for some things yet)?

2021-04-01 23:32 UTC, fangchenli commented
> can we move _everything_ to pyproject.toml? (or is this not supported for some things yet)?

We can also move `isort` to pyproject.toml. But other tools don't support it yet.

2021-04-02 02:43 UTC, fangchenli commented
And seems like mypy is going to support pyproject.toml soon https://github.com/python/mypy/pull/10219.

2021-04-19 20:56 UTC, MarcoGorelli commented
Black doesn't support setup.cfg, flake8 doesn't support pyproject.toml, and the xkcd comic about standards is as relevant as ever 😆 

Anyway if the pytest docs advise against setup.cfg for pytest, then this PR seems like a good idea, thanks for doing it

2021-04-19 21:08 UTC, fangchenli commented
LOL... Let me put it here.

![](https://imgs.xkcd.com/comics/standards.png)

2021-04-21 17:34 UTC, MarcoGorelli approved these changes
Looks good to me.

For anyone wondering where `-s` has gone, the [pytest docs](https://docs.pytest.org/en/6.2.x/reference.html#command-line-flags) say:

> -s                    shortcut for --capture=no.

2021-04-21 18:54 UTC, jreback commented
this looks like a net improvement to me, sure we can't move everything yet, but newer versions you can (e.g. isort)

cc @jorisvandenbossche @jbrockmendel

2021-04-21 18:57 UTC, jbrockmendel commented
as long as we have someone who is competent with toml to maintain this file, no objection here

2021-04-21 18:59 UTC, jreback requested changes

2021-04-21 18:59 UTC, jreback commented on ci/deps/actions-37-minimum_versions.yaml
> +  - pytest=6.0
can we do >=

2021-04-22 22:23 UTC, jreback commented
hmm somehow a conflict, can you merge master

2021-04-25 11:57 UTC, MarcoGorelli commented
Thanks @fangchenli !

2021-04-25 11:57 UTC, merged

2021-04-25 16:26 UTC, simonjayhawkins commented
@fangchenli running the tests locally, test-data.xml is generated and is an untracked file. probably need to add to git ignore to clean up.