Fix libpthread not found during local installation
pandas-dev/pandas pull request #40706
Opened 2021-03-31 15:39 UTC by cgarciae

Hey! This is my first PR, I am getting to know the code base and found this as I was doing the local setup.

- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

I was installing the development environment and it was failing due to:
> /home/cristian/miniforge3/envs/pandas-dev/compiler_compat/ld: cannot find /lib64/libpthread.so.0
/home/cristian/miniforge3/envs/pandas-dev/compiler_compat/ld: cannot find /usr/lib64/libpthread_nonshared.a

This also happens in the Docker container under some conditions (creating a new env).

Steps followed:
```bash
mamba env create -f environment.yml  
conda activate pandas-dev

python setup.py build_ext -j 4 # <-- ERROR HERE
python -m pip install -e . --no-build-isolation --no-use-pep517
```

Adding a `extra_link_args.append("-L/usr/lib/x86_64-linux-gnu/")` fixed the issue on Ubuntu 20.04.

2021-03-31 15:51 UTC, jreback requested changes
are you sure? this will likely break other linux arches 

and not even clear why this is actually needed

2021-03-31 16:04 UTC, cgarciae commented
Hey @jreback, to be honest I don't in general, I had to do this to get my development environment working.
It might affect other Ubuntu contributors. An alternate solution would be to add it to the documentation at [creating-a-python-environment](https://pandas.pydata.org/docs/dev/development/contributing.html#creating-a-python-environment).

2021-03-31 16:48 UTC, jreback commented
sure would take that as a note (eg you may have to do this in some platforms)

2021-03-31 20:59 UTC, jorisvandenbossche commented
@cgarciae Thanks for checking out pandas and your first PR!

Now, I agree we shouldn't just add this. And even instead of adding a note about it, I would first try to understand why this is needed or what's going wrong (eg I am also on Ubuntu 20.04, and using conda environments, but didn't need this). It could also point to something wrong with your conda env (does your conda env have `gxx_linux-64` included?)

2021-04-01 15:59 UTC, cgarciae commented
Hey @jorisvandenbossche! 

I do have `gxx_linux-64` on my env, I manually added it after searching a bit, but that didn't work either. Initially I was trying to modify the `.devcontainer.json` a bit to improve the development experience with Docker (installing the conda env inside the workspace so it was stateful) but I was getting the same error there. I can try to reproduce the Docker setup if its of interest.

2021-04-06 09:31 UTC, rgommers commented
This is an odd problem indeed. The conda gcc compiler itself will add `-pthread`, and it should find `libpthread` in its `sysroot` (something like `../envs/pandas-dev/x86_64-conda-linux-gnu/sysroot/usr/lib64/libpthread.so`). If you look at a build log, you'll see all extensions are compiled with
```
x86_64-conda_cos6-linux-gnu-gcc -pthread -shared ....
```
even though Pandas doesn't use any multi-threading explicitly (I believe).

Can you add a full build log that shows the error in the PR description @cgarciae?

2021-04-07 17:31 UTC, jbrockmendel commented on doc/source/development/contributing.rst
> +    If the ``python setup.py build_ext -j 4`` command fails on a linux distribution you might
can we be more specific than "you might be able to"?  is there reason to believe this is a common failure mode?

2021-04-07 17:31 UTC, jbrockmendel commented on setup.py
> +
can you revert these

2021-04-08 22:24 UTC, Davidnet commented
Can you echo your LD_CONFIG variables before you build?

2021-04-08 23:54 UTC, cgarciae commented
Hey @rgommers! I added the logs to the description.
I could not reproduce it in docker as I originally posted so I believe it has to do with my system config.

2021-04-09 07:29 UTC, jorisvandenbossche commented
One part of the output:

```
gcc -pthread -shared -B /home/cristian/miniforge3/envs/pandas-dev/compiler_compat -L/home/cristian/
miniforge3/envs/pandas-dev/lib -Wl,-rpath=/home/cristian/miniforge3/envs/pandas-dev/lib -Wl,--no-as-n
eeded -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/pandas/_libs/hashing.o -o build/lib.linux-x86_64-3.8/
pandas/_libs/hashing.cpython-38-x86_64-linux-gnu.so
/home/cristian/miniforge3/envs/pandas-dev/compiler_compat/ld: cannot find /lib64/libpthread.so.0
/home/cristian/miniforge3/envs/pandas-dev/compiler_compat/ld: cannot find /usr/lib64/libpthread_nonshared.a
```

So as @rgommers said above, for some reason it is not looking for / not finding libpthread in the conda environment's sysroot.

Googling a bit, it seems to come up regularly a while ago (https://github.com/ContinuumIO/anaconda-issues/issues/7363, https://github.com/cocodataset/cocoapi/issues/94), but that was end of 2017 with the migration to new compilers which could give problems. 

@cgarciae could you also show the output of `conda info` and ``conda list`` (in the pandas-dev environment).  

You could maybe also try to explicitly deactive and reactive the environment, to be sure the env variables are properly set. 

One of the things mentioned in https://github.com/ContinuumIO/anaconda-issues/issues/7363 is to check `python -c "import sysconfig; print(sysconfig.get_config_var('LDFLAGS'))"`

2021-04-09 07:38 UTC, jorisvandenbossche commented
Another observation (from https://github.com/ContinuumIO/anaconda-issues/issues/7363#issuecomment-346191151) that I am seeing here as well: you have `-Wl,--sysroot=/` in your gcc invocation, which I don't have when building pandas in my conda env.

So I suppose that's indicating that not all compiler flags are properly set up for the conda env (not fully/correctly activated for some reason?)

2021-04-09 08:32 UTC, rgommers commented
> you have -Wl,--sysroot=/ in your gcc invocation, which I don't have when building pandas in my conda env.

then you are probably building with your system compiler rather than the conda compilers.

> You could maybe also try to explicitly deactive and reactive the environment, 

I've found that in some cases that's not enough, and you really need a completely fresh terminal.

2021-04-09 15:33 UTC, cgarciae commented
Thanks a lot @jorisvandenbossche and @rgommers! Thanks to your pointers I found the culprit: vscode's terminal seems to do something that makes this happen. I manually activated the conda env from the gnome terminal then ran the previous code and it worked just fine.

I'll be closing the issue since it must be something specific to my setup.

2021-04-09 15:51 UTC, cgarciae commented
My previous comment was wrong, I forgot to remove the patch to the `setup.py`, however I found the problem is conda is not behaving properly in the `fish` shell which I am using, running the previous from `bash` works just fine.

2021-04-09 15:51 UTC, closed without merging

2021-04-09 16:01 UTC, rgommers commented
Ah that makes sense, environment activation (which sets the sysroot, compilers, etc.) does shell-specific things.

2021-04-09 18:13 UTC, jorisvandenbossche commented
@cgarciae you might want to raise an issue at https://github.com/conda/conda to report about the `fish` activation going wrong. Because they have special code for a variety of shells. 
B

2021-04-09 18:16 UTC, jorisvandenbossche commented
Doing a quick look for their fish support, I actually see https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html#using-with-fish-shell. Did you do `conda init fish` ?

2021-04-09 19:29 UTC, cgarciae commented
@jorisvandenbossche yeah, `conda init fish` adds this to my config:
```fish
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
eval /home/cristian/miniforge3/bin/conda "shell.fish" "hook" $argv | source
# <<< conda initialize <<<
```
and it works for most stuff but it seems to be failing for this specific use case. I'll post an issue there, thanks for all the help!