Enable server side cursors
pandas-dev/pandas pull request #40796
Opened 2021-04-06 04:27 UTC by J0

This pull request attempts to fix #35689. I read an article by @itamarst and decided to look further into the codebase. After noticing that the fix semed to be simple I decided file a PR. The fix is naive and I'm not sure the true solution is as simple as I imagine it to be. There are probably many things I'm missing as I've not read the codebase in detail so do let me know what else needs to be addressed.

- [ ] closes #35689
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-04-07 09:27 UTC, auvipy approved these changes

2021-04-07 21:20 UTC, itamarst commented
Thanks for doing this! You could perhaps only do the stream_results=True conditionally, if chunksize is set.

2021-04-09 00:03 UTC, jreback requested changes
this doesnt' seems to break anything, but its certainly possible we are not exerciing things. can you a) comment on what that parameter is doing (e.g. put an reference in the code to the article), and b) if you can come up with a test that fails current and passes with this and c) would need a whatsnew note (perf section)? for 1.3.

would we ever need to turn this off?

2021-04-09 12:20 UTC, itamarst commented
As context, this is a memory usage performance improvement (in some cases). You can see the article here (https://pythonspeed.com/articles/pandas-sql-chunking/) with some memory-usage graphs.

With streaming mode, rows are only fetched on demand. If you're using chunking, this is what you want, because otherwise you might try to load gigabytes of rows into memory and then dole them out in chunks, potentially running out of memory.

If you're _not_ using chunking, though, streaming is probably a runtime performance hint, because there's a bunch more network latency involved, and you already know you want all the data so why not just get it all in one go? (See #40847 for follow-up work that would use streaming cursors everywhere, but I don't think it should always be on).

2021-04-09 12:36 UTC, J0 commented
Hey @itamarst  and @jreback,

Thanks for the input! Will do, will address the comments and revert shortly.

2021-04-11 15:42 UTC, pep8speaks commented
Hello @J0! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/io/sql.py`](https://github.com/pandas-dev/pandas/blob/e1f51dc792c75564e3bd2fe325fbed56de3f8edf/pandas/io/sql.py):

> [Line 1328:89](https://github.com/pandas-dev/pandas/blob/e1f51dc792c75564e3bd2fe325fbed56de3f8edf/pandas/io/sql.py#L1328): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 88 characters)

2021-05-19 00:05 UTC, J0 commented
Yes, I am still interested in working on this and will take a look at this on the weekend

2021-06-08 18:22 UTC, simonjayhawkins commented
> Yes, I am still interested in working on this and will take a look at this on the weekend

Thanks @J0 . closing as stale. ping when ready

2021-06-09 04:38 UTC, J0 commented
Okay, will do. Sorry -- work got a bit busy. Will try to make time for it in this weekend or over an evening.

2021-06-12 12:35 UTC, J0 commented
Hey! @simonjayhawkins,

I'm working on this right now -- any chance I could get this re-opened?

2021-06-12 12:57 UTC, J0 commented
Thanks!

2021-06-12 14:07 UTC, J0 commented
Not too sure what's the best way to go about writing a failing this for this since the main change is in the option passed in

Will think about this but just wanted to check if  @itamarst and @jreback had any suggestions

2021-06-13 19:08 UTC, itamarst commented
My guess is the failure is unrelated: it timed out after 60 minutes. I would just push a meaningless change and see if it passes this time.

2021-06-14 16:05 UTC, J0 commented
Looks like I need approval to run the workflows D: @simonjayhawkins could I trouble you again for help with requesting for approval to run the branch? 

Thank you so much for  -- am aware you probably are quite busy.

2021-06-22 03:04 UTC, J0 commented
Hey, does anyone have suggestions on how I might get the tests to pass? a little clueless at this point.

2021-06-23 12:28 UTC, itamarst commented
In a large project like this, it's possible (a) to have intermittent failures (b) for things to break in ways that are unrelated to your code. So general procedure is:

1. Try rerunning with meaningless commit.
2. If you get the exact same failure, and it's clear that it's not related to your code, merge forward or rebase, depending on how the project does it.

2021-07-02 02:15 UTC, J0 commented
Workflows :( any chance for help with this again? @simonjayhawkins

2021-07-12 13:15 UTC, jreback requested changes

2021-07-12 13:15 UTC, jreback commented on pandas/io/sql.py
> +        if "chunksize" in kwargs:
if you are going to do this, then chunksize should be an actual keyword with a default, and a doc-string.

are there *any* tests which actually evaluate this path?

2021-09-08 02:18 UTC, closed without merging

2022-01-13 06:37 UTC, J0 commented
@mroeschke apologies for the delay. I now have time to patch this again -- by any chance could we reopen this? Or would it be better if I opened a new PR? 

Lmk!

2022-01-13 22:22 UTC, mroeschke commented
@J0 appears I cannot reopen this pull request as our master branch was renamed to main recently. I would recommend to open a new PR with the change.

2022-01-14 04:33 UTC, J0 commented
@mroeschke sure, sounds good, will open a new PR! :)

2022-02-27 07:23 UTC, J0 commented
Re-opened at https://github.com/pandas-dev/pandas/pull/46166