BUG-7023 allow error bars to use style
pandas-dev/pandas pull request #40816
Opened 2021-04-06 22:11 UTC by GLeurquin

- [x] closes #7023
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

2021-04-06 23:48 UTC, mzeitlin11 reviewed
Thanks for the pr @GLeurquin. One comment on whatsnew, plus needs tests!

2021-04-06 23:48 UTC, mzeitlin11 commented on doc/source/whatsnew/v1.3.0.rst
> +- Bug in :meth:`MPLPlot._plot` ignoring ``style`` when using error bars (:issue:`7023`)
Can you describe this in a user-facing way (what changes about publicly exposed pandas api?)

2021-04-09 00:01 UTC, jreback requested changes
pls also adds a test that exercises this code path

2021-05-11 19:57 UTC, datapythonista commented
Closing as stale. @GLeurquin if you want to add tests and address the comment, just ping me, and more than happy to reopen.

2021-05-11 19:57 UTC, closed without merging