ENH: Make maybe_convert_object respect dtype itemsize
pandas-dev/pandas pull request #40908
Opened 2021-04-12 22:18 UTC by rhshadrach

- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

Precursor to #40790

This adds support for e.g. `float32` NumPy dtypes to maybe_convert_object. If any non-NumPy scalar is hit, the behavior is the same as master. This is my first foray into the NumPy C-API, so any tips are appreciated. In particular, I couldn't figure out how to use the C API to do the cast:

    result = result.astype(result.dtype.kind + str(itemsize))

Not sure if there should also be specific logic for EAs/nullable types.

2021-04-12 22:25 UTC, jbrockmendel commented on pandas/_libs/tslibs/util.pxd
> +cdef inline int64_t get_itemsize(object val):
if this is only used in lib.pyx, i think better to put it there

2021-04-12 22:26 UTC, jbrockmendel commented on pandas/_libs/lib.pyx
> +        if result is not None:
should this be tightened to something like ` result is floats or result is uints or result is ints`? i.e. exclude datetimes/timedeltas/bools

2021-04-12 22:28 UTC, jbrockmendel commented on pandas/_libs/lib.pyx
> +                curr_itemsize = cnp.PyArray_ITEMSIZE(result)
id just use `result.dtype.itemsize` and not bother with the C API.

2021-04-13 13:25 UTC, jreback commented
can you add some explict tests for this, maybe around

```
pandas/tests/dtypes/test_inference.py:        result = lib.maybe_convert_objects(arr)
pandas/tests/dtypes/test_inference.py:    def test_maybe_convert_objects_uint64(self):
pandas/tests/dtypes/test_inference.py:        tm.assert_numpy_array_equal(lib.maybe_convert_objects(arr), exp)
pandas/tests/dtypes/test_inference.py:        tm.assert_numpy_array_equal(lib.maybe_convert_objects(arr), exp)
pandas/tests/dtypes/test_inference.py:        tm.assert_numpy_array_equal(lib.maybe_convert_objects(arr), exp)
pandas/tests/dtypes/test_inference.py:        tm.assert_numpy_array_equal(lib.maybe_convert_objects(arr), exp)
pandas/tests/dtypes/test_inference.py:    def test_maybe_convert_objects_datetime(self):
pandas/tests/dtypes/test_inference.py:        out = lib.maybe_convert_objects(
pandas/tests/dtypes/test_inference.py:        out = lib.maybe_convert_objects(
pandas/tests/dtypes/test_inference.py:        out = lib.maybe_convert_objects(
pandas/tests/dtypes/test_inference.py:    def test_maybe_convert_objects_timedelta64_nat(self):
pandas/tests/dtypes/test_inference.py:        result = lib.maybe_convert_objects(arr, convert_timedelta=True)
pandas/tests/dtypes/test_inference.py:    def test_maybe_convert_objects_nullable_integer(self, exp):
pandas/tests/dtypes/test_inference.py:        result = lib.maybe_convert_objects(arr, convert_to_nullable_integer=True)
pandas/tests/dtypes/test_inference.py:    def test_maybe_convert_objects_bool_nan(self):
pandas/tests/dtypes/test_inference.py:        out = lib.maybe_convert_objects(ind.values, safe=1)
pandas/tests/dtypes/test_inference.py:        result = lib.maybe_convert_objects(arr, convert_datetime=True)
```

2021-04-13 20:46 UTC, rhshadrach commented
Thanks @jbrockmendel and @jreback - will make changes and tests. But I want to figure out what the right output here is:

```
        df = DataFrame(
            {"A": [None, 2, 3], "B": [1.0, np.nan, 3.0], "C": ["foo", None, "bar"]}
        )
    
        # Function aggregate
        result = getattr(df, how)({"A": "count"})
        expected = Series({"A": 2})
    
>       tm.assert_series_equal(result, expected)
E       AssertionError: Attributes of Series are different
E       
E       Attribute "dtype" are different
E       [left]:  int32
E       [right]: int64
```

The count is computed by summing an ndarray of Booleans, which NumPy gives back on a 32-bit machine as an int32. This PR is making it stay an int32 (master would convert to int64).

Do we want `Series({"A": 2})` to come back on a 32-bit machine as being an int32 as well? If the answer is no, then I'm thinking this PR should be scrapped. If we do, I think we can implement that here as well:

```
    if result is uints or result is ints or result is floats:
        if itemsize_max > 0 and itemsize_max != result.dtype.itemsize:
            result = result.astype(result.dtype.kind + str(itemsize_max))
        else:
            result = result.astype(result.dtype.kind + str(np.intp().dtype.itemsize))
        return result
```

(with perhaps a better way to get at the 4 vs 8 bytes)

2021-04-14 02:39 UTC, jreback commented
we diverge with numpy by always casting a list of python into to int64 (numpy would do int32)

2021-04-14 02:41 UTC, rhshadrach commented
Thanks @jreback - this was actually an issue with Series.count. All paths of DataFrame.count cast to int64, and when level is not None, Series would do this as well. But when using Series.count with level=None, no cast was done. I'm hopeful adding this in (along with some other test fixes) will fix CI.

2021-04-15 04:05 UTC, rhshadrach commented
The xfailed test on `DataFrame.replace` is due to a change in NumPy behavior:

```
values = np.array(['a'], dtype='object')
mask = np.array([True])
value = np.int8(1)
np.putmask(values, mask, value)
print(type(values[0]))
```

results in `<class 'int'>` with NumPy 1.18.1 but `<class 'numpy.int8'>` with NumPy >= 1.19.

2021-04-15 04:30 UTC, rhshadrach commented on pandas/core/series.py
> +            return notna(self._values).sum().astype("int64")
All paths for Series.count and DataFrame.count result in int64 except for this one.

2021-04-15 20:10 UTC, rhshadrach commented
@jbrockmendel - changes made, @jreback - test added. 

This still needs a whatsnew note, I think at least the impact on Series/DataFrame construction with numpy types should perhaps be in a section of its own. But maybe_convert_objects is used in many places, not sure if there should be more mentioned. When I follow this up with #40790 I'll add on the impact to UDF methods.

2021-04-15 20:15 UTC, rhshadrach commented
Now I'm second guessing making its own section - I'd guess that construction via a list of NumPy scalars is not so common. Maybe just a single line in other enhancements?

2021-04-16 00:43 UTC, jreback requested changes
minor comment. any perf issues?

2021-04-16 00:43 UTC, jreback commented on pandas/_libs/lib.pyx
> +        if result is uints or result is ints or result is floats or result is complexes:
can you put a blank line & comment here (e.g. casting to itemsize)

2021-04-19 20:40 UTC, rhshadrach commented
@jreback - changes made

> any perf issues?

I updated the ASV in the OP, and included some timeit using maybe_convert_objects directly.

2021-04-20 23:33 UTC, jreback approved these changes
lgtm merge on greenish

2021-04-21 04:24 UTC, rhshadrach commented
@jreback - greenish. Failure is:

>           raise AssertionError(f"Caused unexpected warning(s): {repr(extra_warnings)}")
> E           AssertionError: Caused unexpected warning(s): [('ResourceWarning', ResourceWarning('unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x000001FA4204DFC8>'), 'C:\\Miniconda\\envs\\pandas-dev\\lib\\asyncio\\sslproto.py', 322)]

2021-04-21 12:53 UTC, merged

2021-04-21 12:53 UTC, jreback commented
thanks @rhshadrach