BUG: Fix Dataframe constructor missing sql column names (#40682)
pandas-dev/pandas pull request #41005
Opened 2021-04-17 21:22 UTC by jnchngc

…ames

- [x] closes #40682  
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-04-17 21:22 UTC, pep8speaks commented
Hello @jnchngc! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/core/frame.py`](https://github.com/pandas-dev/pandas/blob/466cbe98d2b49bbe2beaa14b1f8adce92824cf63/pandas/core/frame.py):

> [Line 681:73](https://github.com/pandas-dev/pandas/blob/466cbe98d2b49bbe2beaa14b1f8adce92824cf63/pandas/core/frame.py#L681): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator

2021-04-26 22:55 UTC, jreback requested changes
you would *always* need to start with a test

2021-04-26 22:55 UTC, jreback commented on pandas/core/frame.py
> +                # For data is a sqlalchemy query, extract column names
umm what exactly are you trying to do here?

2021-06-25 16:13 UTC, mzeitlin11 commented
Thanks for contributing @jnchngc, closing as stale for now, but please ping to reopen if you'd like to continue and address comments (would also be good to avoid the added dependency here as well).

2021-06-25 16:13 UTC, closed without merging