add type hint for 'data' argument in DataFrame's from_dict method: Un…
pandas-dev/pandas pull request #41136
Opened 2021-04-24 13:55 UTC by GrossBetruger

…ion[dict, list]

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-04-24 14:52 UTC, attack68 commented on pandas/core/frame.py
> +        data: Union[dist, list],
```suggestion
        data: dict | list,
```

2021-04-24 15:18 UTC, GrossBetruger commented on pandas/core/frame.py
> +        data: Union[dist, list],
done

2021-05-22 16:24 UTC, simonjayhawkins requested changes
Thanks @GrossBetruger for the PR. this is failing type validation and is inconsistent with the docstring. can you fixup to get mypy passing.

2021-06-22 08:21 UTC, simonjayhawkins commented
@GrossBetruger Thanks for the PR. closing as stale. ping if you want to continue.

2021-06-22 08:21 UTC, closed without merging