REF: tests.indexes.numeric.py
pandas-dev/pandas pull request #41192
Opened 2021-04-28 08:59 UTC by topper-123

This PR ensures that all index instantiation calls in `tests.indexes.numeric.py` use the `_holder` class variable instead of the actual index class. This will make it easier to extend the existing tests to tests for the new `NumIndex` in #41153.

Also renames `_holder` to `_index_cls` for all of `tests.indexes`. I think this is a more descriptive name.

2021-04-28 15:07 UTC, jreback requested changes
ideally if you can remove all explict construction and use fixtures (can be in the class itself is fine) instead.

2021-04-28 15:07 UTC, jreback commented on pandas/tests/indexes/test_numeric.py
> +    def create_index(self) -> Float64Index:
could make these into fixtures instead

2021-04-28 23:34 UTC, topper-123 commented
Ok, I have changed those to fixtures.

2021-04-30 18:52 UTC, jreback approved these changes

2021-04-30 18:52 UTC, merged