BUG : Min/max markers on box plot are not visible with 'dark_background' (#40769)
pandas-dev/pandas pull request #41349
Opened 2021-05-06 09:55 UTC by yeshsurya

[*] closes #40769
[*] tests added / passed
[*] Ensure all linting tests pass, see here for how to run them
[*] Color in boxplot.py should be a hex value. Letter based color will be at matplotlib level. Using same color as that of boxes for the caps as well. The color will be fetched based on the selected theme. We are over riding color with "k" , rather need to use the one set at matplotlib level.
Before Fix :

Caps for the box plot is not visible :
![![image](https://user-images.githubusercontent.com/9417467/117279259-2634b480-ae7f-11eb-933c-350cff0133de.png)](https://user-images.githubusercontent.com/9417467/117279207-1a48f280-ae7f-11eb-9f0f-fe477d80dc77.png)

After Fix :

Caps for the box plow will be visible in dark background mode :
![image](https://user-images.githubusercontent.com/9417467/117279282-2df45900-ae7f-11eb-8107-9fe3ae2fe15f.png)

Whats New : Box Plot's Caps will have same color as boxes unless color is explicitly specified by user arguments. Hence theme changes will not adversly effect caps color.

2021-05-06 19:08 UTC, attack68 approved these changes
this seems to align with the approval I submitted for the previous PR which got corrupted.

2021-05-07 08:32 UTC, charlesdong1991 commented
sorry, @yeshsurya a bit unlucky, I _think_ this failure isn't related to your change, probably you will need another rebase

2021-05-07 13:00 UTC, jreback requested changes

2021-05-07 13:00 UTC, jreback commented on doc/source/whatsnew/v1.3.0.rst
> +- Bug in :meth:`BoxPlot._validate_color_args` in box plot when 'dark_background' theme was selected, caps or min/max markers for the plot was not visible (:issue:`40769`)
pls change this to be a user friendly note, eg. DataFrame.plot.boxplot(....) or similar

2021-05-09 17:24 UTC, charlesdong1991 approved these changes
thanks! very nice! @yeshsurya 

just a minor tip: use ``` ``dark_background`` ``` instead of ``` 'dark_background' ``` would be more aligned with the syntax usually done in whatsnew notes ^^

2021-05-10 09:34 UTC, merged

2021-05-10 09:34 UTC, charlesdong1991 commented
thanks very much, very nice!