REF: add internal mechanics to separate index/columns sparsification in Styler
pandas-dev/pandas pull request #41391
Opened 2021-05-09 07:51 UTC by attack68

This is not a user facing change.

It adds only the necessary code to permit separate control of index/column MultIndex sparsification. Essentially it removes the `get_option("display.multi_sparse")` from a low level method to a higher level method where it can be overwritten by user-args later.

2021-05-10 23:27 UTC, jreback requested changes
lgtm doc comments.

2021-05-10 23:27 UTC, jreback commented on pandas/io/formats/style_render.py
> +        index : Index
is this indented?

2021-05-10 23:27 UTC, jreback commented on pandas/io/formats/style_render.py
> +    Returns
blank line before this

2021-05-11 05:03 UTC, attack68 commented on pandas/io/formats/style_render.py
> +        index : Index
fixed

2021-05-11 05:03 UTC, attack68 commented on pandas/io/formats/style_render.py
> +    Returns
fixed

2021-05-12 01:14 UTC, jreback approved these changes
looks fine. happy to merge and do typing on followups or here.

2021-05-12 01:14 UTC, jreback commented on pandas/io/formats/style_render.py
> +    def _translate(self, sparsify_index=None, sparsify_cols=None):
can you type input & output here

2021-05-12 01:14 UTC, jreback commented on pandas/io/formats/style_render.py
> +    def _translate(self, sparsify_index=None, sparsify_cols=None):
docs-strings as well

2021-05-12 01:14 UTC, jreback commented on pandas/io/formats/style_render.py
> +def _get_level_lengths(index, sparsify, hidden_elements=None):
can you type

2021-05-12 09:40 UTC, attack68 commented on pandas/io/formats/style_render.py
> +def _get_level_lengths(index, sparsify, hidden_elements=None):
typed.

2021-05-12 10:22 UTC, attack68 commented on pandas/io/formats/style_render.py
> +    def _translate(self, sparsify_index=None, sparsify_cols=None):
typed and added all doc strings

2021-05-12 14:37 UTC, attack68 commented
@jreback ping this is green and your requested changes made.

2021-05-12 15:03 UTC, merged

2021-05-12 15:03 UTC, jreback commented
thanks @attack68