DOC: Adding Cylon under ecosystem/out of core
pandas-dev/pandas pull request #41402
Opened 2021-05-09 16:57 UTC by chathurawidanage

- [x]  Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

This PR adds a link and a description about Cylon to the ecosystem page.

2021-05-10 23:18 UTC, jreback requested changes

2021-05-12 00:06 UTC, chathurawidanage commented on doc/source/ecosystem.rst
> +Cylon is a fast, scalable, distributed memory parallel runtime with a Pandas like Python DataFrame API. ”Core Cylon” is implemented with C++ using Apache Arrow format to represent the data in-memory.
Added an example.

2021-05-12 00:18 UTC, datapythonista approved these changes
lgtm, thanks for the update @chathurawidanage

2021-05-12 00:29 UTC, datapythonista commented on doc/source/ecosystem.rst
> +
I think you've got spaces in this blank line, you'll need to remove them to get the CI green.

2021-05-12 02:03 UTC, datapythonista commented
CI still red for trailing spaces, `git diff upstream/master` should highlight them if your editor doesn't.

2021-05-12 02:54 UTC, chathurawidanage commented
Thanks, @datapythonista that did the trick!

2021-05-12 14:07 UTC, jreback approved these changes

2021-05-12 14:07 UTC, merged

2021-05-12 14:07 UTC, jreback commented
thanks @chathurawidanage