Issue41072 timestamp
pandas-dev/pandas pull request #41413
Opened 2021-05-11 01:28 UTC by rauniyars

- [*] closes 41072
- [*] tests added / passed
- [*] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

2021-05-11 04:47 UTC, hewittk commented
Upon seeing Github Actions CI, we seem to have a couple of issues with other test cases that invoke methods that eventually invoke the creation of a new timestamp in which one of their timestamps is nonexistent. For one of these, a `nonexistent = 'shift_forward'` parameter in `tz_localize` isn't accounted for in `__new__` and in another, nonexistent isn't directly accounted for in any parameters. A possible way to resolve this would be adding a `nonexistent` parameter to `Timestamp` or potentially to `__new__` that defaults at "raise", but I haven't had a lot of time to think through the feasibility of that. Let me know what you think!

2021-05-11 20:17 UTC, jbrockmendel commented on pandas/tests/scalar/timestamp/test_timestamp.py
> +    def test_new_nonexistent_error(self):
can you add a comment like `# GH#41413` to point back here

2021-05-11 20:19 UTC, jbrockmendel commented on doc/source/whatsnew/v1.3.0.rst
> +- Invocation of methods to check whether objects created through ```Timestamp`` are nonexistent times and raising ``NonExistentTimeError`` (:issue:`41072`)
i think this can go in the Timezones bugfix section something like 'Bug in :class:`Timestamp` constructor failing to raise [...]'

2021-05-12 01:19 UTC, jreback requested changes

2021-05-12 01:19 UTC, jreback commented on pandas/_libs/tslibs/timestamps.pyx
> +        tz_localize_to_utc_single(naive_ts.value, ts.tzinfo, False, "raise")
this is a super hotspot, if we *really* need to do this then need to confirm performance.

2021-08-17 00:52 UTC, mroeschke commented
Thanks for the PR, but it appears that it has gone stale and needs to address the reviews. Going to close due to inactivity but let us know if you'd like to continue and we can reopen.

2021-08-17 00:52 UTC, closed without merging