DOC: freeze old whatsnew #6856
pandas-dev/pandas pull request #41442
Opened 2021-05-12 18:53 UTC by fangchenli

xref #6856

2021-05-12 21:55 UTC, jreback requested changes

2021-05-12 21:55 UTC, jreback commented on doc/source/whatsnew/v0.10.0.rst
> +.. code-block:: python
i think we need to actually paste in the ipython prompts of the execution (e.g. execute the block and paste in the docs)

2021-05-13 18:35 UTC, datapythonista commented
As Jeff says, this is unfortunately more complex than simply replacing the directives. See those:
```
.. ipython:: python
   print('hello world')

.. code-block:: python
   >>> print('hello world')
   hello world
```

The reason we use the ipython directive is that we don't need to write the `>>>` or the output, just the code. So, to do this, we need to add those two to every example. :\

If we want to do this, what I'd recommend is to use the master issue to keep track of all the files to edit. And then increasingly create issues for each individual file, and label them as "good first issue". Maybe you can work on the first file yourself, so there is a reference PR for the other issues. But this is a lot of work, and too much for a single person in my opinion. And we surely don't want to review PRs with more than one file updated IMHO.

2021-05-14 17:19 UTC, jreback commented
closing this as being done in pieces

2021-05-14 17:19 UTC, closed without merging