DOC: unpin numpydoc, fix validation script #39688
pandas-dev/pandas pull request #41456
Opened 2021-05-13 19:16 UTC by fangchenli

- [ ] closes #39688
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-05-13 19:24 UTC, fangchenli commented
The breaking change was from https://github.com/numpy/numpydoc/pull/302. 

After modifying our script according to the new API. There is an AttributeError error:

```
pandas.Series.array <property object at 0x1199e99f0>
Traceback (most recent call last):
  File "scripts/validate_docstrings.py", line 438, in <module>
    main(
  File "scripts/validate_docstrings.py", line 384, in main
    return print_validate_all_results(
  File "scripts/validate_docstrings.py", line 328, in print_validate_all_results
    result = validate_all(prefix, ignore_deprecated)
  File "scripts/validate_docstrings.py", line 298, in validate_all
    doc_info = pandas_validate(func_name)
  File "scripts/validate_docstrings.py", line 241, in pandas_validate
    result["examples_errs"] = doc.examples_errors
  File "scripts/validate_docstrings.py", line 161, in examples_errors
    for test in finder.find(self.raw_doc, self.name, globs=context):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pandas-dev/lib/python3.8/site-packages/numpydoc/validate.py", line 135, in name
    return '.'.join([self.obj.__module__, self.obj.__name__])
AttributeError: 'property' object has no attribute '__module__'
```

2021-06-22 16:24 UTC, jbrockmendel commented
@fangchenli is this actionable?

2021-06-25 14:58 UTC, jreback commented
cc @MarcoGorelli @simonjayhawkins

2021-07-11 09:28 UTC, MarcoGorelli requested changes

2021-07-11 09:28 UTC, MarcoGorelli commented on scripts/validate_docstrings.py
> +                name = type(self.obj).__name__
this isn't covered by any of the tests in `scripts/validate_docstrings.py` - when could it happen?

2021-07-11 09:28 UTC, MarcoGorelli commented on scripts/validate_docstrings.py
> +        if name is not None:
likewise, none of the tests cover when `name` is `None` - when could that happen?

2021-09-08 02:11 UTC, mroeschke commented
This PR has appeared to have gone stale. Feel free to reopen if you're still interested in working on this.

2021-09-08 02:11 UTC, closed without merging