REF: collect methods in NumericIndex
pandas-dev/pandas pull request #41472
Opened 2021-05-14 14:58 UTC by topper-123

Seperates the refactoring of existing methods out of #41153. Will make it easier to see what #41153 actually brings in.

This Pr changes no functionality, but only makes the exisiting numeric indexes into thin subclasses of `NumericIndex`.

2021-05-14 15:11 UTC, topper-123 commented on pandas/core/indexes/numeric.py
> +        return cls._default_dtype
This is just a shrim for now. Will get more content in later PR.

2021-05-17 15:35 UTC, jreback requested changes
looks good a couple of comments

2021-05-17 15:35 UTC, jreback commented on pandas/core/indexes/numeric.py
> +    @property
cached_property?

2021-05-17 15:35 UTC, jreback commented on pandas/core/indexes/numeric.py
> +    @property
cached_property

2021-05-17 15:35 UTC, jreback commented on pandas/core/indexes/numeric.py
> +        """Ensure int64 dtype for Int64Index, etc. Assumed dtype is validated."""
can add a doc-string (followon ok)

2021-05-17 15:35 UTC, jreback commented on pandas/core/indexes/numeric.py
> +_int64_descr_args = {
can you put these *in* the class?

2021-05-17 19:07 UTC, topper-123 commented
Updated.

2021-05-17 19:19 UTC, jreback approved these changes
lgtm. @jbrockmendel if any comments

2021-05-17 19:40 UTC, jbrockmendel commented on pandas/core/indexes/numeric.py
> +    def _assert_safe_casting(cls, data, subarr) -> None:
subarr is ndarray?

2021-05-17 19:41 UTC, jbrockmendel commented
LGTM; if you find anywhere where `@final` can be correctly added, pls do

2021-05-17 19:44 UTC, topper-123 commented on pandas/core/indexes/numeric.py
> +    def _assert_safe_casting(cls, data, subarr) -> None:
Yes, and data too, I can add those.

2021-05-17 19:47 UTC, topper-123 commented
Wrt. @final, I’m not sure I like it in library code.

Couldn’t a third party subclass an index and change one of methods in an unanticipated way, but the @final be in the way of that?

2021-05-18 06:36 UTC, topper-123 commented
Updated type hints.

2021-05-18 13:05 UTC, merged

2021-05-18 13:05 UTC, jreback commented
thanks @topper-123