DEPR: dropping nuisance columns in DataFrame reductions
pandas-dev/pandas pull request #41480
Opened 2021-05-15 01:37 UTC by jbrockmendel

- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

Discussed on this week's call

2021-05-17 14:22 UTC, jreback requested changes
looks good. can you add a sub-section in deprecations as this is fairly user visible. ping on green.

2021-05-17 14:22 UTC, jreback commented on pandas/core/frame.py
> +                # columns have been dropped
can you add the issue number here and below (this PR number is fine),

2021-05-17 18:49 UTC, jbrockmendel commented
added a whatsnew subsection.  this is actually just the first half of the note im about to push for #41475.  

the smart money says ive made a mess of the rst conventions regarding `code-block:: ipython` vs `ipython:: python` vs [...]

2021-05-17 21:07 UTC, jreback commented on doc/source/whatsnew/v1.3.0.rst
> +When calling a reduction (.min, .max, .sum, ...) on a :class:`DataFrame` with
```suggestion
The default of calling a reduction (.min, .max, .sum, ...) on a :class:`DataFrame` with
``numeric_only=None`` will silently ignore and drop from the result nuiscance columns, e.g. a string column in a .mean() reduction.
```

2021-05-17 21:08 UTC, jreback commented on doc/source/whatsnew/v1.3.0.rst
> +are silently ignored and dropped from the result.  This behavior is deprecated.
Start a new paragraph with 'This behavior is deprecated'

2021-05-17 21:08 UTC, jreback commented on doc/source/whatsnew/v1.3.0.rst
> +
show df here

2021-05-21 17:04 UTC, jreback approved these changes

2021-05-21 17:05 UTC, jreback approved these changes
lgtm. can you rebase once more and ping on green.

2021-05-21 20:58 UTC, jbrockmendel commented
ping

2021-05-21 20:59 UTC, merged