REF: make array_to_datetime single-pass
pandas-dev/pandas pull request #41525
Opened 2021-05-17 20:09 UTC by jbrockmendel

Or more specifically, remove the need for falling back to datetime_to_datetime64 which does a second pass.

2021-05-17 20:09 UTC, jbrockmendel commented
cc @mroeschke

2021-05-17 21:17 UTC, jreback requested changes
how do asv's look here?

2021-05-17 21:17 UTC, jreback commented on pandas/_libs/tslib.pyx
> +                        elif not utc_convert and not tz_compare(seen_tz, val.tzinfo):
is this comparison expenseive?

2021-05-18 00:04 UTC, mroeschke commented on pandas/_libs/tslib.pyx
> +                        if seen_tz is None:
What happens when we get a timezone offset from a string and a tzinfo object from a `datetime.datetime`?

2021-07-01 23:07 UTC, jreback commented
can you rebase

2021-07-02 14:51 UTC, jbrockmendel commented
> can you rebase

yah will circle back before too long, need to address some other comments above.  pretty focused on MultiIndex bugs ATM.

2021-07-11 17:54 UTC, jbrockmendel commented
mothballing to clear the queue, will revisit

2021-07-11 17:54 UTC, closed without merging