API: EA._can_hold_na -> EDtype.can_hold_na
pandas-dev/pandas pull request #41654
Opened 2021-05-24 23:34 UTC by jbrockmendel

- [x] closes #40574
- [ ] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

2021-05-27 02:45 UTC, jreback requested changes

2021-05-27 02:45 UTC, jreback commented on pandas/core/arrays/datetimelike.py
> +    _can_hold_na = True  # type: ignore[assignment]
if u make this a property (like u do below) then can avoid the typing issue

2021-05-27 02:45 UTC, jreback commented on pandas/tests/extension/test_external_block.py
> +    # "Block" defined the type as "Callable[[Block], bool]")
same comment here

2021-05-27 18:42 UTC, jreback approved these changes
lgtm. @jorisvandenbossche if any comments

2021-05-27 18:42 UTC, jreback commented
> pandas/tests/extension/test_external_block.py:18: error: Cannot override final attribute "_can_hold_na" (previously declared in base class "Block")  [misc]

actually this is failing precommit

2021-05-28 15:12 UTC, jbrockmendel commented
pre-commit fixed

2021-06-01 21:09 UTC, jorisvandenbossche commented on pandas/core/dtypes/base.py
> +    def can_hold_na(self) -> bool:
This doesn't need to be public?

2021-06-01 21:11 UTC, jorisvandenbossche commented
I know this is an existing property on the ExtensionArray, but do we actually support (or want to support) an extension array that cannot hold missing values? (I don't think we currently have one, so this is also not really tested?)

2021-06-01 21:12 UTC, jorisvandenbossche commented
> I don't think we currently have one

Except for PandasArray, I assume (but since that's not actually stored in practice, that's a bit a special case anyhow)

2021-06-01 22:33 UTC, jbrockmendel commented
I think `Sparse[inty]`?

2021-06-02 09:56 UTC, simonjayhawkins commented
i've added blocker since I don't think we should change this during the rc. so we either get it in for 1.3.0rc or move to 1.4/2.0

2021-06-02 14:35 UTC, jbrockmendel commented
is the public/private question (and a rebase) the only outstanding issue?  im happy to make this private

2021-06-02 19:21 UTC, jorisvandenbossche commented
Also the question whether we should have this at all, IMO. And if we have that property, what does it mean? (what's the behaviour for operations like setitem or reindexing that can introduce missing values?)

2021-06-02 19:33 UTC, jbrockmendel commented
> Also the question whether we should have this at all, IMO. And if we have that property, what does it mean? (what's the behaviour for operations like setitem or reindexing that can introduce missing values?)

I'm open to having this discussion, but I think it can be done separately from the "where should this attribute live" discussion given that it already exists on EA.

2021-06-02 19:37 UTC, jorisvandenbossche commented
But if we are not yet sure if and how such property would be used, we can also leave it where it is for now? (or what problem is this PR fixing?)

If moving it, let's at least make it private and document it that way (as an internal property that no EA author should change, as that is undefined behaviour)

2021-06-02 19:43 UTC, jbrockmendel commented
> (or what problem is this PR fixing?)

The corner cases I want to rule out are where can_hold_na is values-dependent and potentially non-constant, e.g. (xref #40574)

```
class WeirdEA(ExtensionArray):
      @property
      def _can_hold_na(self) -> bool:
           return some_func(self[0])
```

2021-06-03 00:15 UTC, jreback commented
this lgtm, i agree this should be on the dtype.

2021-06-07 16:49 UTC, jreback commented
@jorisvandenbossche ok here?

2021-06-07 18:55 UTC, jorisvandenbossche commented on doc/source/whatsnew/v1.3.0.rst
> +- :attr:`ExtensionArray._can_hold_na` should now be implemented on the :class:`ExtensionDtype` subclass as ``_can_hold_na`` (:issue:`40574`)
I would remove this mention, if we are not yet clear on the intended semantics of it.

2021-06-07 19:03 UTC, jorisvandenbossche commented
Yeah, I won't object moving it. Just a tiny comment on the whatsnew.

2021-06-07 21:24 UTC, jbrockmendel commented
whatsnew removed + greenish

2021-06-08 12:55 UTC, merged

2021-06-08 12:55 UTC, simonjayhawkins commented
Thanks @jbrockmendel