add abiility for json.dumps to parse and add timezones
pandas-dev/pandas pull request #41667
Opened 2021-05-25 21:42 UTC by jeliashi

- [ ] closes #12997
- [ ] tests modofied
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

Ok, so this is a doozy AND it's not done, but it can be merged as is.
What do we do:
We add timezones to json output!
Before:
```
ts = pd.Timestamp('2020-10-5 4:00:05', tz='US/Pacific')
print(pd.io.json.dumps(ts, iso_dates=True))
print(ts.isoformat())
```
would provide
`"2020-10-05T11:00:05.000Z"`
and
`"2020-10-05T04:00:05.000-07:00"`
respectively.

Now they both produce
``"2020-10-05T04:00:05.000-07:00"``

So what do I mean by not complete?
This still doesn't work for arrays that have datetime values. This only works for single datetime values.
So:
`pd.DataFrame({'foo': range(5)}, index=pd.date_range('2020-10-12', freq='H', periods=5, tz='US/Eastern')).to_json(date_format='iso')`

will still produce:
`'{"foo":{"2020-10-12T04:00:00.000Z":0,"2020-10-12T05:00:00.000Z":1,"2020-10-12T06:00:00.000Z":2,"2020-10-12T07:00:00.000Z":3,"2020-10-12T08:00:00.000Z":4}}'`

and not 
`'{"foo":{"2020-10-12T00:00:00.000-04:00":0,"2020-10-12T01:00:00.000-04:00":1,"2020-10-12T02:00:00.000-04:00":2,"2020-10-12T03:00:00.000-04:00":3,"2020-10-12T04:00:00.000-04:00":4}}'`

Working on it currently. Open to recommendations!

2021-05-25 22:15 UTC, pep8speaks commented
Hello @jeliashi! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/io/json/test_ujson.py`](https://github.com/pandas-dev/pandas/blob/1461da08b5be71b33a69928aabc7930b7429d290/pandas/tests/io/json/test_ujson.py):

> [Line 394:89](https://github.com/pandas-dev/pandas/blob/1461da08b5be71b33a69928aabc7930b7429d290/pandas/tests/io/json/test_ujson.py#L394): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 88 characters)

2021-05-26 09:24 UTC, simonjayhawkins requested changes
@jeliashi can you close this one and carry on with #41573 if possible, much easier to track.

2021-05-26 15:36 UTC, jeliashi commented
> @jeliashi can you close this one and carry on with #41573 if possible, much easier to track.

sure thing

2021-05-26 15:38 UTC, jeliashi commented
> > @jeliashi can you close this one and carry on with #41573 if possible, much easier to track.
> 
> sure thing

Oh wow, sorry, I didn't see these were on the same branch on my fork. I thought I had separated them, my bad.

2021-05-26 15:42 UTC, closed without merging