Npdev
pandas-dev/pandas pull request #41665
Opened 2021-05-25 18:21 UTC by jbrockmendel

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

hopefully numpy will provide an alternative that makes this unnecessary

2021-05-26 09:37 UTC, simonjayhawkins commented
@jbrockmendel you are changing the code here for unreleased compat issues. IIUC numpy may make some further changes. would it be better to add something to the 54 failing tests for now?

2021-05-26 17:11 UTC, jbrockmendel commented
I'm holding out hope that numpy will handle this upstream, xref https://github.com/numpy/numpy/issues/19078

2021-05-26 21:43 UTC, jreback requested changes

2021-05-26 21:43 UTC, jreback commented on pandas/core/algorithms.py
> +        filterwarnings("ignore", category=FutureWarning)
why don't u use create_ndarray here?

2021-05-27 16:40 UTC, jbrockmendel commented on pandas/core/algorithms.py
> +        filterwarnings("ignore", category=FutureWarning)
bc `value` can be a scalar here

2021-05-28 19:26 UTC, jbrockmendel commented
@seberg should we just suppress these warnings for the time being in expectation of a fix/change upstream?

2021-05-31 16:23 UTC, closed without merging

2021-06-02 15:46 UTC, seberg commented
Sorry about being away for the long weekend.  I will look into this again, but I got the feeling that you will likely need some type of helper like `create_ndarray` in any case.  Hopefully, we can avoid the warning context at least, though.

2021-06-02 18:36 UTC, seberg commented
We just discussed this in the numpy call, and I think the most likely solution will be to (unfortunately) delay the deprecation, to give you more time and hopefully a better solution to this.

That would mean you don't have to worry about string promotion changes for this release.

2021-06-04 19:31 UTC, jbrockmendel commented
OK.  Is there anything I/we can do short(ish)-term to make the process easier on your end?

2021-06-04 20:07 UTC, seberg commented
@jorisvandenbossche not sure.  Maybe we can meet up briefly and discuss how well `np.discover_array_params` would help you (I am very flexible)?  And also what pandas needs right now in terms of dtype/descriptor discovery from NumPy?
(Plus, I guess what pandas actually does itself, since you currently need those multiple passes before and after the NumPy pass.)

I have some hopes that we could both clean up pandas and make NumPy and pandas work better together in one go with just small modifications to NumPy (and exposure of the new API).  And that would just solve this issue incidentally.

2021-06-04 20:11 UTC, jbrockmendel commented
> Maybe we can meet up briefly and discuss

Sure.  I'm in UTC-7, can do any AM between now and Tuesday, inclusive.

2021-06-04 20:37 UTC, seberg commented
Great! Send you an invite, in case anyone is curious, put the details here also: https://hackmd.io/fe_VHCBjSwutSwhpPP8KSg