Add test for fixed regression in concat with empty DataFrames
pandas-dev/pandas pull request #41677
Opened 2021-05-26 10:03 UTC by weikhor

- [ ✓ ] closes #39037 
- [ ✓ ] tests added / passed
- [ ✓ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

2021-05-26 10:03 UTC, pep8speaks commented
Hello @weikhor! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/reshape/concat/test_empty.py`](https://github.com/pandas-dev/pandas/blob/c729840cb44d0e5adb42623289c4611607dabe3a/pandas/tests/reshape/concat/test_empty.py):

> [Line 258:89](https://github.com/pandas-dev/pandas/blob/c729840cb44d0e5adb42623289c4611607dabe3a/pandas/tests/reshape/concat/test_empty.py#L258): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 88 characters)
> [Line 260:1](https://github.com/pandas-dev/pandas/blob/c729840cb44d0e5adb42623289c4611607dabe3a/pandas/tests/reshape/concat/test_empty.py#L260): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2021-05-26 10:07 UTC, simonjayhawkins commented
@weikhor thanks for the PR. lint issue to resolve.

2021-05-26 15:32 UTC, charlesdong1991 requested changes
I think it would be nice to create empty dataframes directly instead of using [0:0] or [:0] ?

2021-05-26 15:32 UTC, charlesdong1991 commented on pandas/tests/reshape/concat/test_empty.py
> +        df1 = DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
```suggestion
        df1 = DataFrame(columns=["a", "b"])
```

2021-05-26 15:32 UTC, charlesdong1991 commented on pandas/tests/reshape/concat/test_empty.py
> +        result = concat([df1[0:0], df2[0:0], df1[0:0]]).astype('int32')
could you please create empty dataframes instead?

2021-05-26 15:32 UTC, charlesdong1991 commented on pandas/tests/reshape/concat/test_empty.py
> +    def test_concat_empty_dataframe_different_dtypes(self):
same for this test

2021-05-27 01:49 UTC, jreback requested changes

2021-05-27 01:49 UTC, jreback commented on pandas/tests/reshape/concat/test_empty.py
> +        assert result["a"].dtype == np.int64
construct and expected frame and use assert_frame_equal

2021-05-27 16:25 UTC, weikhor commented
Hi I have make change to code. Please review pull request. Thank

2021-05-27 17:39 UTC, charlesdong1991 requested changes
thank you, i triggered the complete tests for you and probably one job will fail (on the double quote).

2021-05-27 17:39 UTC, charlesdong1991 commented on pandas/tests/reshape/concat/test_empty.py
> +        expected = DataFrame(columns=['a', 'b', 'c'])
to standardise, we all use double quote, and I think pre-commit job will fail on this

2021-05-27 17:39 UTC, charlesdong1991 commented on pandas/tests/reshape/concat/test_empty.py
> +        expected = DataFrame(columns=['a', 'b'])
also double quotes

2021-05-27 17:39 UTC, charlesdong1991 commented on pandas/tests/reshape/concat/test_empty.py
> +        tm.assert_frame_equal(result, expected)
Look at comments in the issue, seems it is also nice to have type of value checked? https://github.com/pandas-dev/pandas/issues/39037#issuecomment-756748197

2021-05-28 16:31 UTC, weikhor commented
Hi Thank for review. Have making changes to codes.

2021-05-28 17:08 UTC, jreback approved these changes

2021-05-28 19:05 UTC, merged

2021-05-28 19:05 UTC, jreback commented
thanks @weikhor