Resolve about inconsistent results for empty datasets describe
pandas-dev/pandas pull request #41716
Opened 2021-05-29 09:55 UTC by weikhor

- [✔ ]  closes https://github.com/pandas-dev/pandas/issues/41575
- [ ✔]  tests added / passed
- [✔ ]  Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

2021-05-29 17:06 UTC, weikhor commented
Hi @jreback This PR is about fixing https://github.com/pandas-dev/pandas/issues/41575. Thank

2021-05-31 21:57 UTC, jreback requested changes

2021-05-31 21:57 UTC, jreback commented on pandas/core/groupby/generic.py
> +        if self.axis == 1 or (not isinstance(result.index, MultiIndex)):
can you simply check `not self.empty` ?

2021-05-31 21:57 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +    # 41575
put with smilar tests in pandas/tests/groupby/test_function.py

2021-05-31 21:57 UTC, jreback commented
this currently fails on master right?

2021-06-01 15:56 UTC, pep8speaks commented
Hello @weikhor! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/frame.py`](https://github.com/pandas-dev/pandas/blob/6dd99648551787a772b45e7a77310cf9a0d9234b/pandas/core/frame.py):

> [Line 8549:1](https://github.com/pandas-dev/pandas/blob/6dd99648551787a772b45e7a77310cf9a0d9234b/pandas/core/frame.py#L8549): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace





* In the file [`pandas/tests/groupby/test_function.py`](https://github.com/pandas-dev/pandas/blob/6dd99648551787a772b45e7a77310cf9a0d9234b/pandas/tests/groupby/test_function.py):

> [Line 1210:1](https://github.com/pandas-dev/pandas/blob/6dd99648551787a772b45e7a77310cf9a0d9234b/pandas/tests/groupby/test_function.py#L1210): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2021-06-01 16:03 UTC, weikhor commented on pandas/core/groupby/generic.py
> +        if self.axis == 1 or (not isinstance(result.index, MultiIndex)):
Yes

2021-06-01 16:30 UTC, weikhor commented
> this currently fails on master right?
Yes

2021-07-15 21:45 UTC, rhshadrach requested changes
Thanks for the PR! I don't understand why the changing of errors being raised in `_cython_transform` and `_cython_agg_general`, can you explain why that's needed?

2021-07-15 21:45 UTC, rhshadrach commented on pandas/core/groupby/generic.py
> +        if self.axis == 1 or not isinstance(result.index, MultiIndex):
As @jreback commented, can check that it's not empty. I think the code would be more readable if we added it as a separate check without the transpose - I couldn't figure out why you'd want to take the transpose before realizing the frame is empty.

```
if result.empty:
    return result
elif self.axis == 1:
    return result.T
```

2021-07-15 21:45 UTC, rhshadrach commented on pandas/core/groupby/generic.py
> +    boxplot = boxplot_frame_groupby
Add a newline here

2021-07-15 21:45 UTC, rhshadrach commented on pandas/tests/groupby/test_function.py
> +    # 41575
Can you prefix with `GH` or `GH #` or `GH#`? We're not consistent, but I believe there is usually _some_ prefix.

2021-07-15 21:45 UTC, rhshadrach commented on pandas/tests/groupby/test_function.py
> +    result = df.groupby("A").B.describe().reset_index(drop=True)
Can you remove the reset index? The test should just test the behavior of describe.

2021-08-17 02:03 UTC, mroeschke commented
Thanks for the PR, but it appears that this has gone stale and needs to address the reviews. Closing due to inactivity but happy to reopen if you're interested in continuing.

2021-08-17 02:03 UTC, closed without merging