Frame aggregate
pandas-dev/pandas pull request #41722
Opened 2021-05-29 17:44 UTC by weikhor

- [ ✔] closes https://github.com/pandas-dev/pandas/issues/41672
- [ ✔] tests added / passed
- [ ✔] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

2021-05-29 17:44 UTC, pep8speaks commented
Hello @weikhor! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/frame.py`](https://github.com/pandas-dev/pandas/blob/878c33bce257f73cd7771f19ec78e3330355b7a2/pandas/core/frame.py):

> [Line 8539:1](https://github.com/pandas-dev/pandas/blob/878c33bce257f73cd7771f19ec78e3330355b7a2/pandas/core/frame.py#L8539): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2021-05-29 20:47 UTC, jbrockmendel commented on pandas/tests/frame/test_aggregate.py
> +def _check_mixed_int(df, dtype=None):
is this supposed to be a test?

2021-05-30 00:50 UTC, weikhor commented on pandas/tests/frame/test_aggregate.py
> +def _check_mixed_int(df, dtype=None):
My mistake. Have updated the code

2021-05-31 21:47 UTC, jreback requested changes

2021-05-31 21:47 UTC, jreback commented on pandas/tests/frame/test_aggregate.py
> +
these go in pandas/tests/apply/test_frame_apply.py

there are already extensive tests, so find a good place to exercise the empty case

we have these, so model after

```
(pandas) jreback@lhs2:~/pandas-dev$ grep -r empty pandas/tests/apply/|grep def
pandas/tests/apply/test_frame_transform.py:def test_transform_empty_listlike(float_frame, ops, frame_or_series):
pandas/tests/apply/test_frame_transform.py:def test_transform_empty_dictlike(float_frame, ops, frame_or_series):
pandas/tests/apply/test_frame_transform.py:def test_transform_empty_dataframe():
pandas/tests/apply/test_series_apply.py:def test_apply_empty_integer_series_with_datetime_index():
pandas/tests/apply/test_series_apply.py:def test_map_empty(index):
pandas/tests/apply/test_frame_apply.py:def test_apply_empty(float_frame):
pandas/tests/apply/test_frame_apply.py:def test_apply_with_reduce_empty():
pandas/tests/apply/test_frame_apply.py:def test_apply_funcs_over_empty(func):
pandas/tests/apply/test_frame_apply.py:def test_nunique_empty():
pandas/tests/apply/test_frame_apply.py:def test_apply_empty_infer_type():
pandas/tests/apply/test_frame_apply.py:def test_apply_empty_list_reduce():
```

2021-07-03 09:07 UTC, simonjayhawkins commented
Thanks @weikhor for the PR. can you add a release note to doc/source/whatsnew/v1.3.1.rst, Bug fixes section and address https://github.com/pandas-dev/pandas/pull/41722#discussion_r642685684

2021-08-17 02:07 UTC, mroeschke commented
Thanks for the PR, but it appears this has gone stale and needs addressing of the reviews. Closing, but happy to reopen if still interested.

2021-08-17 02:07 UTC, closed without merging