DOC: update README.md, list setuptools as dependency
pandas-dev/pandas pull request #41818
Opened 2021-06-04 21:54 UTC by fangchenli

xref #41815

2021-06-05 01:24 UTC, jreback commented
https://github.com/pandas-dev/pandas/blob/master/setup.cfg#L33 update as well i think

2021-06-07 10:22 UTC, jorisvandenbossche requested changes
I wouldn't add it to `install_requires`, see https://github.com/pandas-dev/pandas/issues/41815

2021-06-07 10:22 UTC, jorisvandenbossche commented on README.md
> +- [Setuptools - A fully-featured, actively-maintained, and stable library designed to facilitate packaging Python projects](https://setuptools.readthedocs.io/en/latest/)
Can you move this to the optional dependencies section?

2021-06-07 17:57 UTC, jorisvandenbossche commented on doc/source/getting_started/install.rst
> -`setuptools <https://setuptools.readthedocs.io/en/latest/>`__    38.6.0
Can you add it to the optional dependencies below?

2021-06-08 12:49 UTC, simonjayhawkins approved these changes

2021-06-08 12:59 UTC, merged

2021-06-08 12:59 UTC, jreback commented
thanks @fangchenli