DOC: Add .to_xyz to io docs
pandas-dev/pandas pull request #41844
Opened 2021-06-06 23:03 UTC by gansel51

- [ x] closes #41839
- [ ] tests added / passed
- [ x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

Screenshot below for updated docs

<img width="558" alt="Screen Shot 2021-06-06 at 7 03 23 PM" src="https://user-images.githubusercontent.com/59709552/120942916-e53bf400-c6f9-11eb-96bc-d16dc852f45c.png">

2021-06-07 05:51 UTC, attack68 requested changes
Thanks v m @gansel51. 

Few comments in line and also:

Can you add a section on `LaTeX` and add:
`DataFrame.to_latex` and `Styler.to_latex`

2021-06-07 05:51 UTC, attack68 commented on doc/source/reference/io.rst
> +   DataFrame.to_excel
can you also add `Styler.to_excel`

2021-06-07 05:51 UTC, attack68 commented on doc/source/reference/io.rst
> +   DataFrame.to_html
Can you also add as a separate line `Styler.to_html`

2021-06-07 15:46 UTC, gansel51 commented
@attack68 For sure. I added the `DataFrame.to_latex` method on a feature branch I'll merge when complete. Looking into the Styler methods now because an import error blocked my original request.

2021-06-07 16:00 UTC, gansel51 commented
@attack68 Added those methods, ready for re-review!

2021-06-07 17:16 UTC, gansel51 commented
<img width="614" alt="Screen Shot 2021-06-07 at 1 15 28 PM" src="https://user-images.githubusercontent.com/59709552/121061897-7199f580-c792-11eb-91b2-3001965eecda.png">

@attack68 yeah, here's a screenshot of the LaTeX section which shows a cross section of the three types of changes:
1. Add new section
2. Add DataFrame.to_xyz
3. Add Syle.to_xyz

2021-06-07 21:52 UTC, attack68 approved these changes
LGTM.

This is better with the increased info and links. Would be nice if as a follow on we could get the columns aligning, i.e. by merging the Styler and DataFrame tocs so they dont have different alignment.

2021-06-08 05:40 UTC, WillAyd reviewed
Thanks for the PR. Just out of curiosity why are some but not all of these namespaced with `DataFrame...`

2021-06-08 13:07 UTC, gansel51 commented
@WillAyd The `DataFrame.to_xyz` methods have the DataFrame modifier because they are DataFrame methods and must be done on one. The remaining IO methods aren't done on DataFrames (just `pandas` or `Styler`) so didn't have that prefix. It both lets Sphynx pick up the methods (otherwise they won't be found by the autosummary) and gives users more accurate usage information.

2021-06-08 14:57 UTC, attack68 requested changes
There seems to be some CI errors. The docs don't build without errors, I think because the current module is changed in one part of `pandas.io.formats.style` and then `ExcelWriter` is referenced.

2021-06-08 15:15 UTC, gansel51 commented
> There seems to be some CI errors. The docs don't build without errors, I think because the current module is changed in one part of `pandas.io.formats.style` and then `ExcelWriter` is referenced.

The docs didn't build without errors when I first tried pre-PR either, but I switched the current module back for ExcelWriter and it is generating properly. See screenshot below for ExcelWriter

<img width="534" alt="Screen Shot 2021-06-08 at 11 14 55 AM" src="https://user-images.githubusercontent.com/59709552/121211781-c39e5200-c84a-11eb-93be-95ce0d85bf6c.png">

2021-06-08 15:26 UTC, gansel51 commented
@attack68 I went ahead and resolved the warnings on the page as well. The page is rendering properly for me with no errors.

2021-06-08 20:52 UTC, jreback commented
lgtm. can merge on green.

2021-06-08 20:53 UTC, gansel51 commented
> lgtm. can merge on green.

Thanks @jreback will keep an eye on the checks

2021-06-08 21:43 UTC, gansel51 commented
> https://github.com/pandas-dev/pandas/pull/41844/checks?check_run_id=2777904153

I can switch that, but `LaTeX` is the proper capitalization for the project (see [LaTeX Website](https://www.latex-project.org/)). Please advise if I should switch it or if there is a way to override that check @jreback

2021-06-09 00:37 UTC, jreback commented
actually this is coming from our validate_rst_ checker cc @MarcoGorelli i think there is a way to ignore it

2021-06-10 03:10 UTC, gansel51 commented
@jreback cc @MarcoGorelli Any update here?

2021-06-10 11:23 UTC, simonjayhawkins commented
moving off 1.3 milestone for now.

2021-06-10 12:31 UTC, MarcoGorelli commented
Looks like the error is
```
/home/runner/work/pandas/pandas/pandas/io/json/_normalize.py:240:SS04:pandas.io.json.json_normalize:Summary contains heading whitespaces
```

2021-06-11 03:13 UTC, gansel51 commented
@jreback @MarcoGorelli @attack68 I removed the deprecated method from the documentation, kicking off a new build could (should?) solve the issue so this PR can merge. I can definitely look into putting LaTeX in the allowlisted next!

2021-06-14 14:17 UTC, gansel51 commented
@attack68 I'm not seeing where the checks are failing and not just failing because of a cancellation, can you point me in the right direction?

2021-06-14 15:48 UTC, simonjayhawkins commented
```
/home/runner/work/pandas/pandas/doc/source/reference/api/pandas.to_pickle.rst:40: WARNING: Citation [Recbd1b9f7896-1] is not referenced.
```
in https://github.com/pandas-dev/pandas/pull/41844/checks?check_run_id=2800940727

2021-06-16 00:18 UTC, jreback commented
@gansel51 this is ok for 1.3 after its passing.

2021-06-16 14:55 UTC, attack68 commented
> @attack68 I'm not seeing where the checks are failing and not just failing because of a cancellation, can you point me in the right direction?

isnt this because it should be `DataFrame.to_pickle`. if `pandas.to_pickle` isnt there that will produce the error simonjayhawkins highlighted

2021-06-16 20:26 UTC, gansel51 commented
@attack68 @simonjayhawkins Thanks for pointing it out, I was having trouble isolating the error from the logs. Made that change, will keep an eye on the workflow status.

2021-06-16 22:17 UTC, jreback approved these changes

2021-06-16 23:07 UTC, merged

2021-06-16 23:07 UTC, jreback commented
thanks @gansel51

2021-06-16 23:07 UTC, jreback commented
@meeseeksdev backport 1.3.x