ENH: `Styler` `apply` and `applymap` over the index instead of the data
pandas-dev/pandas pull request #41893
Opened 2021-06-09 13:04 UTC by attack68

Checks an item on #41648 and #41693 (if follow-ons completed)

Currently Styler has the `apply` and `applymap` methods to **perform conditional styling on the data elements**.

Recent additions to `Styler.set_table_styles` allows styling of index and column headers if the key-labels are directly specified. But this solution cannot work with LaTeX, nor excel output, and is obviously not conditionally applied.

This PR adds the mechanics to **perform conditional styling on per level index labels**

Feedback on the API is appreciated. Instead of new methods `apply_index` and `applymap_index`, these could be incorporated into the `apply` and `applymap` methods with a new kwarg identifying the target for application.

![Screen Shot 2021-06-09 at 15 02 58](https://user-images.githubusercontent.com/24256554/121359514-d9d40d00-c933-11eb-8e9e-0083913c1473.png)

The follow-ons to this include:

- [ ] doing same over column headers.
- [ ] updating LaTeX templates to incorporate the styles.
- [ ] updatin Excel output to incorporate the styles.

2021-07-28 01:17 UTC, jreback requested changes
wouldn't apply_axis be more appropriate? e.g. don't see _header anywhere else in the codebase

do we need both (i get that we have symmetry, but is this overkill)?

2021-07-29 14:52 UTC, attack68 commented
> wouldn't apply_axis be more appropriate? e.g. don't see _header anywhere else in the codebase
> 
> do we need both (i get that we have symmetry, but is this overkill)?

i came up with 'header' becuase in the HTML that styler renders the index and column header cells are `<th>` (table header) elements, and these are the ones targeted by this method.

I'm not tied to the name but `apply_axis` feels a bit odd, since `axis` is already used by pandas for a common meaning and not really to do with impacting the values of the index or column headers. 

`apply_index(axis="columns")` might be an alternative to make it clear that the function is being applied to either the index values or the column header values??

2021-08-11 19:56 UTC, jreback commented on doc/source/whatsnew/v1.4.0.rst
> +- :meth:`.Styler.apply_index` and :meth:`.Styler.applymap_index` added to allow conditional styling of index and column header values (:issue:`41893`)
might be worth creating a styler sub-section in other enhancements (followon)

2021-08-11 19:56 UTC, jreback approved these changes

2021-08-11 19:56 UTC, merged