BUG: Scalar assignment to empty dataframe with loc. Closes GH41891
pandas-dev/pandas pull request #41921
Opened 2021-06-10 09:49 UTC by klieret

This weakens a check introduced in 7bbeb79297532d209d67f7bdc61394ddee3acbb1
which caused ValueErrors for df[:, 1] = 1 if df is an empty DataFrame.
With this commit no error is thrown and the column is added to the
dataframe (which remains empty).

- [x] closes #41891
- [x] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-06-10 10:37 UTC, jreback requested changes
what is the actual problem you are trying to solve?

adding a column with a value which disappears (not to mention not setting a dtype) is nonsensical and harmful not helpful

the issue you pointed is completely unrelated as there IS a non empty index

2021-06-10 12:49 UTC, klieret commented
Thanks for taking a look at this so quickly @jreback . 

> adding a column with a value which disappears (not to mention not setting a dtype) is nonsensical and harmful not helpful

My expectations for `df.loc[:, 'a'] = 1` are that the following statements are true

1. If it doesn't already exist, a column `a` is added to the frame
2. column `a` has the value `1` for all rows

Thus, if `df` is empty, 2 simply becomes trivial and 1 should still be true. Maybe I'm missing something, but this feels perfectly natural to me.

This is also the behaviour of `df['a'] = 1` (this syntax however will show the `SettingWithCopyWarning` if `df` is a copy/view). 

> not to mention not setting a dtype

In my branch, the `dtype` is set properly to `int64`:

```
In [1]: import pandas as pd
In [2]: df = pd.DataFrame()
In [3]: df.loc[:, "a"] = 1
In [4]: df["a"]
Out[6]: Series([], Name: a, dtype: int64)
```

> what is the actual problem you are trying to solve?

Given a copy, I want to be able to set a scalar value without explicitly having to check for emptiness every time. So basically I'm looking for something that replicates the behavior of `df['a'] = 1` without complaining about copies (also see #41891).

As written above, from my perspective it also feels very unnatural and unnecessary to have a `ValueError` raised here. But perhaps I lack some context or there is a different way to look at this?

2021-06-12 17:27 UTC, phofl commented
I think this is quite confusing. 

```
import pandas as pd

df = pd.DataFrame()

df.loc[:, 'b'] = [1]
```

results in

```
   b
0  1
```

Assigning values to empty DataFrames itself is not ideal imo

2021-06-14 14:16 UTC, klieret commented
Your example is using the enlargement syntax, which is triggered whenever there's something list like on the right hand side (which I agree isn't entirely intuitive, especially because there's no index given for the new entry in your example). 

But I think it's even more confusing that `df[:, 'a'] = 1` is different from `df['a'] = 1`. And as argued above, it can be viewed as perfectly logical to have the outcome of this be a dataframe without rows (and what's more, this perspective on the logic of it is much more practical than raising a `ValueError`).

The new behavior proposed here would be fairly backwards compatible and I'm still convinced that it would be an improvement. Sorry for being stubborn.

2021-08-17 02:21 UTC, mroeschke commented
Thanks for the PR, but appears from the review that this current approach does not have much support from other members of the core team. I think it's probably best if this is further discussed in the original issue first before proceeding with a PR. Closing.

2021-08-17 02:21 UTC, closed without merging