Regression raising Error when having dup cols with single dtype for read csv
pandas-dev/pandas pull request #42030
Opened 2021-06-15 21:26 UTC by phofl

- [x] closes #42022
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

regression on master, so no whatsnew

2021-06-15 22:28 UTC, jreback requested changes
is this for 1.3?

2021-06-15 22:28 UTC, jreback commented on pandas/_libs/parsers.pyx
> +                                and isinstance(self.dtype, dict)
can we use is_dict_like?

2021-06-15 22:29 UTC, jreback commented
> is this for 1.3?

looks like it

2021-06-15 22:32 UTC, phofl commented on pandas/_libs/parsers.pyx
> +                                and isinstance(self.dtype, dict)
Yes, thx

2021-06-15 22:32 UTC, phofl commented
Yes this is a regression on the rc

2021-06-15 22:33 UTC, jreback approved these changes

2021-06-16 01:46 UTC, merged

2021-06-16 01:46 UTC, jreback commented
thanks @phofl

2021-06-16 01:46 UTC, jreback commented
@meeseeksdev backport 1.3.x