Allow passing custom sentinel into MultiIndex.format
pandas-dev/pandas pull request #42061
Opened 2021-06-16 23:13 UTC by eltoder

Commit b0468aa45f3 seems to have unintentionally removed functionality
to pass custom sentinel values for sparsifying in MultiIndex.format().
Previously, any "Truthy" value other than 1 and True was used as the
sentinel, which is useful particularly with adjoin=False. The current
logic does not make sense: it checks sparsify for "Falsey" values under
"if sparsify:" condition. Under this if sparsify cannot be Falsey.

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-06-16 23:13 UTC, pep8speaks commented
Hello @eltoder! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/io/formats/test_format.py`](https://github.com/pandas-dev/pandas/blob/f6042e50b3d07c2ab580eb77876466af34692281/pandas/tests/io/formats/test_format.py):

> [Line 3203:89](https://github.com/pandas-dev/pandas/blob/f6042e50b3d07c2ab580eb77876466af34692281/pandas/tests/io/formats/test_format.py#L3203): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 88 characters)
> [Line 3210:89](https://github.com/pandas-dev/pandas/blob/f6042e50b3d07c2ab580eb77876466af34692281/pandas/tests/io/formats/test_format.py#L3210): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 88 characters)
> [Line 3211:89](https://github.com/pandas-dev/pandas/blob/f6042e50b3d07c2ab580eb77876466af34692281/pandas/tests/io/formats/test_format.py#L3211): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 88 characters)
> [Line 3212:89](https://github.com/pandas-dev/pandas/blob/f6042e50b3d07c2ab580eb77876466af34692281/pandas/tests/io/formats/test_format.py#L3212): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (107 > 88 characters)
> [Line 3214:89](https://github.com/pandas-dev/pandas/blob/f6042e50b3d07c2ab580eb77876466af34692281/pandas/tests/io/formats/test_format.py#L3214): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (116 > 88 characters)

2021-06-17 13:30 UTC, jreback requested changes
not sure i love this double argument here. would be ok with deprecating this behavior entirely and add ing a *new* keyword to do this `sentinel` to `.format()`

2021-06-17 13:32 UTC, eltoder commented
@jreback I agree. Ok to keep this change though? The current code doesn't make sense and changed the API

2021-06-17 14:36 UTC, eltoder commented
@jreback How about this?

2021-10-04 00:23 UTC, jreback commented
closing as stale, if you want to continue working, please ping.

2021-10-04 00:23 UTC, closed without merging