BUG: excelwriter engine_kwargs fix
pandas-dev/pandas pull request #42214
Opened 2021-06-24 22:02 UTC by Joeperdefloep

- [x] closes #xxxx
- [x] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them - *I cannot find the linked page*
- [ ] whatsnew entry
- closes #29095

The `engine_kwargs` argument was not passed properly and this was not tested. Also added some documentation.

2021-06-24 22:02 UTC, pep8speaks commented
Hello @Joeperdefloep! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/io/excel/_base.py`](https://github.com/pandas-dev/pandas/blob/18d9eab603e723cc532251013d47f9ec49fca927/pandas/io/excel/_base.py):

> [Line 760:89](https://github.com/pandas-dev/pandas/blob/18d9eab603e723cc532251013d47f9ec49fca927/pandas/io/excel/_base.py#L760): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (112 > 88 characters)
> [Line 767:89](https://github.com/pandas-dev/pandas/blob/18d9eab603e723cc532251013d47f9ec49fca927/pandas/io/excel/_base.py#L767): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 88 characters)



* In the file [`pandas/tests/io/excel/test_xlsxwriter.py`](https://github.com/pandas-dev/pandas/blob/18d9eab603e723cc532251013d47f9ec49fca927/pandas/tests/io/excel/test_xlsxwriter.py):

> [Line 65:1](https://github.com/pandas-dev/pandas/blob/18d9eab603e723cc532251013d47f9ec49fca927/pandas/tests/io/excel/test_xlsxwriter.py#L65): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 67:22](https://github.com/pandas-dev/pandas/blob/18d9eab603e723cc532251013d47f9ec49fca927/pandas/tests/io/excel/test_xlsxwriter.py#L67): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 67:42](https://github.com/pandas-dev/pandas/blob/18d9eab603e723cc532251013d47f9ec49fca927/pandas/tests/io/excel/test_xlsxwriter.py#L67): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 67:79](https://github.com/pandas-dev/pandas/blob/18d9eab603e723cc532251013d47f9ec49fca927/pandas/tests/io/excel/test_xlsxwriter.py#L67): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 67:87](https://github.com/pandas-dev/pandas/blob/18d9eab603e723cc532251013d47f9ec49fca927/pandas/tests/io/excel/test_xlsxwriter.py#L67): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-07-05 15:19 UTC, mattelacchiato commented
We would really love to have this fix in the next version of pandas, since we have to mitigate XLSX injections. Is there something I could help here to achieve this?

2021-07-06 13:01 UTC, jreback commented
> We would really love to have this fix in the next version of pandas, since we have to mitigate XLSX injections. Is there something I could help here to achieve this?

this is just docs, you can already do this

2021-07-06 13:01 UTC, jreback commented
@Joeperdefloep can you merge master

2021-07-10 14:46 UTC, Joeperdefloep commented
Ehm, sorry if Don;t understand, but I am mergin master here I think?
it says:
Joeperdefloep wants to merge 3 commits into `pandas-dev:master` from `Joeperdefloep:master`

2021-07-15 21:13 UTC, rhshadrach requested changes
Thanks for the PR!

2021-07-15 21:13 UTC, rhshadrach commented on pandas/io/excel/_xlsxwriter.py
> +        self.book = Workbook(self.handles.handle, engine_kwargs)
Can you add a test for this.

2021-07-15 21:13 UTC, rhshadrach commented on pandas/io/excel/_base.py
> +    ... ) as writer:
I think this will only be valid with xlsxwriter, is that right? Can you specify the engine here to make it clear that's what is being used.

2021-07-15 21:13 UTC, rhshadrach commented on pandas/tests/io/excel/test_xlsxwriter.py
> +
Remove this blank line, it will not pass code checks (two blank lines between functions)

2021-09-02 00:59 UTC, mroeschke commented
Thanks for the PR, but it appears to have gone stale. Let us know if you're still interested in working on this and we can reopen. Closing.

2021-09-02 00:59 UTC, closed without merging

2021-09-02 01:04 UTC, rhshadrach commented
@mattelacchiato - any interest in picking this up?

2021-09-05 20:47 UTC, Joeperdefloep commented
Heyy, sorry I was on holidays a bit so that's why it stopped and went stale...

Also there was a weird thing that there was a merge conflict, where my test was changed to another one. That's why this PR doesn't mention it.