ENH: Create directories when missing in to_* methods
pandas-dev/pandas pull request #42255
Opened 2021-06-26 16:27 UTC by rgkimball

This is the most fundamental approach to creating new folders when a user specifies a path that is missing in file creation methods like `to_csv`, `to_excel`, `to_feather` etc. We can do this in [io/common.py:`get_handle()`](https://github.com/pandas-dev/pandas/blob/50a59bac1f2bcbf9ac87c7a4160d4355be512294/pandas/io/common.py#L521) conditionally when the file buffer provided is in a writable mode.

- [x] closes #24306
   - Can use the existing #42250 to extend documentation for each of the `to_*` methods (@Joeperdefloep)
- [x] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-06-26 18:44 UTC, Joeperdefloep commented
So do we want default behaviour to be that directories are always created or an extra argument like `mkdirs=True` that needs to be passed?

I can add that to the documentation. Then that would be in all `to_something` that can be a file?

2021-06-26 18:52 UTC, rgkimball commented
Exposing an argument to control this might be helpful and shouldn't be too much work (and would allow us to reinstate the two tests I removed). I'll defer to the maintainers as to whether this should be on or off by default, but I agree that changing these to create missing directories by default is much more intuitive for novice users.

2021-06-26 19:06 UTC, Joeperdefloep commented
Then I'll also wait with the documentation until this is resolved :)

2021-07-01 23:51 UTC, jreback requested changes
so I would start with a note in the docs about this

would also accept a *better* error message for cases like this (not sure how hard this is to detect that if you create the parent folders). (separate PR)

I don't think automatic creation of directories is a great idea to do so *automatically*, so after the 2 above could consider via a keyword (yes some work for this). but please propose before you do the PR.

2021-08-17 02:45 UTC, mroeschke commented
Thanks for the PR, but as mentioned, the team isn't keen on supporting an API that creates directories and instead would prefer a documentation approach like in https://github.com/pandas-dev/pandas/pull/42250/files. Closing.

2021-08-17 02:45 UTC, closed without merging