[WIP] ENH: `Styler.bar` extended to allow centering about the mean, value or callable
pandas-dev/pandas pull request #42301
Opened 2021-06-29 13:14 UTC by attack68

This refactors `Styler.bar` to allow more flexible arguments to align bars, and an additional keyword `props` akin to other builtin methods that allow some customisation, demonstrated in the new user guide (image below)

- [x] closes (#26070)
- [x] tests added / passed
- [ ] whats new

All previous tests pass with minor formatting alterations.

![Screen Shot 2021-06-29 at 14 53 56](https://user-images.githubusercontent.com/24256554/123800804-f2f42c00-d8e9-11eb-970a-31468d7a29fa.png)

2021-07-04 18:25 UTC, jreback requested changes
looks fine. anything need updating in the doc-string?

2021-07-04 18:25 UTC, jreback commented on pandas/io/formats/style.py
> +def _bar(
could consider moving style* things to a separate dir e.g. pandas/io/formats/style/* and then have flexibility to for example move some utilities to own modules. (obviously for future)

2021-07-05 07:19 UTC, attack68 commented
> looks fine. anything need updating in the doc-string?

have also done the changes to the doc string and added a `versionadded` or `versionchanged` tag for 1.4.0

2021-07-09 13:14 UTC, jreback approved these changes

2021-07-09 13:15 UTC, merged

2021-07-09 13:15 UTC, jreback commented
thanks @attack68