WEB: Added theme dependent favicon
pandas-dev/pandas pull request #42325
Opened 2021-06-30 13:11 UTC by DeviousLab

- [x] closes #42314
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

Added a light mode version of the favicon based upon the .svgs in the static folder as well as added a small js scipt to the template page to detect the theme change.

![mgCmqcreiy](https://user-images.githubusercontent.com/53790060/123965934-fe1c8a00-d9c5-11eb-8838-ce72ee988a3c.gif)

2021-06-30 20:01 UTC, attack68 commented on web/pandas/_templates/layout.html
> +            setupIcons();
```suggestion
        }

        setupIcons();
```

2021-06-30 20:08 UTC, attack68 commented on web/pandas/_templates/layout.html
> +            const lightSchemeIcon = document.querySelector('link#light-scheme-icon');
```suggestion
            // change the favicon based on browser detected color scheme on refresh
            const lightSchemeIcon = document.querySelector('link#light-scheme-icon');
```

2021-07-01 05:43 UTC, attack68 approved these changes
lgtm.

2021-07-01 23:35 UTC, jreback commented
cc @datapythonista if any comment

2021-07-01 23:45 UTC, datapythonista requested changes
Thanks for the contribution @DeviousLab. Looks fine, but I think we can get a way simpler implementation. Your code is only executed at load time, so why not leave the html as is (just adding an id), and the javascript simply have an if to check if the theme is dark, and if it change the href value?

2021-07-02 08:47 UTC, DeviousLab commented
@datapythonista I probably have done it this way in the first place, but I've made the changes you've requested, now updates the favicon without requiring refresh through use of a event listener. And now just updates the href of the current favicon. Definitely a lot simpler. 
![363GRl3Xq6](https://user-images.githubusercontent.com/53790060/124248105-91270280-db33-11eb-804c-2aa41866ed93.gif)

2021-07-02 16:31 UTC, datapythonista approved these changes
I don't think a theme update is something we need to worry about, but in any case, this is much clearer, looks good to me.

Thanks for working on it @DeviousLab

2021-07-05 11:14 UTC, DeviousLab commented
Are there any more changes that need to be made? Or can it be safely merged without conflicts?

2021-07-05 16:35 UTC, datapythonista commented
Sorry for the delay @DeviousLab. We usually require two core devs to review a PR before merging, let's wait a bit more and see if someone else can have a look. Thanks for your patience.

2021-07-05 18:32 UTC, DeviousLab commented
> Sorry for the delay @DeviousLab. We usually require two core devs to review a PR before merging, let's wait a bit more and see if someone else can have a look. Thanks for your patience.

No worries! just thought I might have been missing something

2021-07-08 13:08 UTC, DeviousLab commented
@jreback Does this look good to you?

2021-07-09 13:16 UTC, merged

2021-07-09 13:16 UTC, jreback commented
thanks @DeviousLab