BUG: pd.cut with duplicate index Series lowest included
pandas-dev/pandas pull request #42425
Opened 2021-07-07 12:48 UTC by debnathshoham

- [x] closes #42185
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-07-07 14:27 UTC, jreback requested changes
pls always add tests for any change

2021-07-07 15:26 UTC, debnathshoham commented
Hi @jreback , apologies, I am new to open source contributions.
I have run the tests. Below is a screenshot. I am not very if (and how) my change caused these failures.

![Screenshot 2021-07-07 at 8 50 43 PM](https://user-images.githubusercontent.com/6472290/124786611-7c989f00-df65-11eb-9291-e4973866c0ff.png)

2021-07-07 15:38 UTC, jreback commented
we have extensive docummentation on how to do changes: https://pandas.pydata.org/pandas-docs/dev/development/index.html

you need to add tests for your scenario and not break anything else.

2021-07-08 12:49 UTC, jreback requested changes

2021-07-08 12:49 UTC, jreback commented on pandas/tests/reshape/test_cut.py
> +def df_from_series_with_nonexact_categoricalindices_frompdcut():
this won't execute as its not named correctly e.g. name similar to the above

2021-07-08 12:49 UTC, jreback commented on doc/source/whatsnew/v1.3.1.rst
> +- Fixed bugs pertaining to :meth:`pandas.cut` operations on :class:`Series` with duplicate indices(:issue:`42185`) and non-exact :meth:`pandas.CategoricalIndex` (:issue:`42425`)
```suggestion
-Bug in :meth:`pandas.cut` on :class:`Series` with duplicate indices (:issue:`42185`) and non-exact :meth:`pandas.CategoricalIndex` (:issue:`42425`)
```

2021-07-08 12:49 UTC, jreback commented on pandas/core/reshape/tile.py
> +        if isinstance(x, ABCSeries):
try using
`ids[np.asarray(x) == bins[0]] = 1` instead of the if/else

2021-07-08 14:35 UTC, closed without merging