BUG: Fix multi-index colname references in read_csv c engine.
pandas-dev/pandas pull request #42519
Opened 2021-07-13 17:38 UTC by jmcomie

This fixes an issue with the read_csv c engine when the input has more than one header row and arguments to dtype, na_values, or converters reference multi-index column names as tuples.

- [x] closes #42446
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

I added a whatsnew entry for v1.4.0 since that's what other recent bug fixes have done, but I'm not yet sure of the criteria for that. Is it appropriate to add it for whichever release "owns" master?

2021-07-13 23:00 UTC, jreback requested changes
looks fine, some comments

2021-07-13 23:00 UTC, jreback commented
cc @gfyoung if you'd have a look

2021-07-14 00:50 UTC, jmcomie commented on pandas/tests/io/parser/dtypes/test_dtypes_basic.py
> +    parser = all_parsers
> can you add the issue number as a comment

done

2021-07-14 00:51 UTC, jmcomie commented on pandas/_libs/parsers.pyx
> +                    if self.has_mi_columns:
done

2021-07-14 01:19 UTC, gfyoung approved these changes

2021-07-14 23:15 UTC, jreback approved these changes

2021-07-15 01:46 UTC, jmcomie commented
Regarding the failed check -- I've run the test _tests/scalar/timedelta/test_arithmetic.py_ and it's passing locally.  If it's an issue in my branch I will work to fix it but it seems this might be an environmental error ?

2021-07-15 04:20 UTC, merged

2021-07-15 04:20 UTC, jreback commented
thanks @jmcomie 

failed check is not related