DOC: Add user_guide examples and docstring example for df.plot.box and df.plot.hist
pandas-dev/pandas pull request #42520
Opened 2021-07-13 18:34 UTC by charlesdong1991

- [ ] closes #42492
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-07-13 22:55 UTC, jreback requested changes
lgtm minor comments

2021-07-13 22:55 UTC, jreback commented on doc/source/user_guide/visualization.rst
> +You could also create groupings with :meth:`DataFrame.plot.box`, for instance,
can you add a versionchanged 1.4

2021-07-13 22:55 UTC, jreback commented on doc/source/user_guide/visualization.rst
> +.. ipython:: python
can you add a versionchanged 1.4

2021-07-13 22:55 UTC, jreback commented on pandas/plotting/_core.py
> +
can you add a versionchanged

2021-07-15 19:40 UTC, charlesdong1991 commented on doc/source/user_guide/visualization.rst
> +You could also create groupings with :meth:`DataFrame.plot.box`, for instance,
yep! add for all 3 places!

2021-07-28 01:06 UTC, jreback approved these changes

2021-07-28 01:06 UTC, merged

2021-07-28 01:06 UTC, jreback commented
thanks @charlesdong1991