ENH: Add support for nullable boolean and integers in Stata writers
pandas-dev/pandas pull request #42565
Opened 2021-07-16 13:47 UTC by bashtage

Add code that allows nullable arrays to be written

closes #40855

- [X] closes #40855
- [X] tests added / passed
- [X] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ X] whatsnew entry

2021-07-19 08:26 UTC, bashtage commented
Seeing a lot of random failures unrelated to this.

2021-09-01 14:57 UTC, bashtage commented
@jreback I think this is ready, and all green now.

2021-09-14 12:37 UTC, jreback requested changes
lgtm, doc typo. ping on green.

2021-09-14 12:37 UTC, jreback commented on doc/source/whatsnew/v1.4.0.rst
> +- Additional options added to :meth:`.Styler.bar` to control alignment and display, with keyword only arguments (:issue:`26070`, :issue:`36419`)
extra?

2021-09-14 12:37 UTC, jreback commented on doc/source/whatsnew/v1.4.0.rst
> +-
extra line here

2021-09-14 12:38 UTC, jreback commented
pls merge master as well

2021-09-14 14:11 UTC, bashtage commented on doc/source/whatsnew/v1.4.0.rst
> +- Additional options added to :meth:`.Styler.bar` to control alignment and display, with keyword only arguments (:issue:`26070`, :issue:`36419`)
Must have been a rebase error. Thanks.

2021-09-14 16:35 UTC, merged

2021-09-14 16:35 UTC, jreback commented
thanks @bashtage