Pin fastparquet
pandas-dev/pandas pull request #42612
Opened 2021-07-19 16:53 UTC by lithomas1

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

Get CI to green.

2021-07-19 17:18 UTC, bashtage commented
Should probably pin in requirements-dev.txt as well until it is ready to move to 0.7.0.

2021-07-19 21:39 UTC, simonjayhawkins commented
The fastparquet tests also fail on 1.3.x, so milestone 1.3.1 to trigger backport

2021-07-19 21:40 UTC, simonjayhawkins commented
@lithomas1 can you open an issue to unpin this.

2021-07-19 21:43 UTC, simonjayhawkins requested changes
pre-commit failure.

2021-07-20 09:28 UTC, simonjayhawkins commented
> @lithomas1 can you open an issue to unpin this.

added xref to the issue to the op, so no need to open a separate issue.

2021-07-20 12:18 UTC, jreback commented on ci/deps/actions-38-db.yaml
> +  - fastparquet>=0.4.0, < 0.7.0
this causes a pre-commit failure (remove the space before the 0.7.0)

2021-07-20 14:16 UTC, lithomas1 commented
@github-actions pre-commit

2021-07-20 16:53 UTC, lithomas1 commented
Green, can someone from @pandas-dev/pandas-core merge?

Sorry about the noise in this PR, was using the Github Web UI, which pre-commit apparently doesn't like.

2021-07-20 16:56 UTC, phofl approved these changes

2021-07-20 16:57 UTC, merged

2021-07-20 17:00 UTC, phofl commented
thx @lithomas1

2021-07-20 17:11 UTC, phofl commented
backported manually

2021-07-20 17:12 UTC, lithomas1 commented
thx @phofl.