Update frame.py
pandas-dev/pandas pull request #42667
Opened 2021-07-22 16:26 UTC by trevorkask

Added an example to the reorder_levels function

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-07-22 16:26 UTC, pep8speaks commented
Hello @trevorkask! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/frame.py`](https://github.com/pandas-dev/pandas/blob/34a53d1b9bdbfdf5098704d10c566cad6612208b/pandas/core/frame.py):

> [Line 6791:1](https://github.com/pandas-dev/pandas/blob/34a53d1b9bdbfdf5098704d10c566cad6612208b/pandas/core/frame.py#L6791): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 6794:89](https://github.com/pandas-dev/pandas/blob/34a53d1b9bdbfdf5098704d10c566cad6612208b/pandas/core/frame.py#L6794): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (96 > 88 characters)
> [Line 6821:1](https://github.com/pandas-dev/pandas/blob/34a53d1b9bdbfdf5098704d10c566cad6612208b/pandas/core/frame.py#L6821): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2021-07-24 22:28 UTC, jbrockmendel commented
the linter has a few complaints

2021-07-28 01:51 UTC, jreback requested changes
ping when green

2021-07-28 01:51 UTC, jreback commented on pandas/core/frame.py
> +        >>> df=pd.DataFrame(data,columns=['class','diet','species'])
space around the equals

2021-07-28 01:51 UTC, jreback commented on pandas/core/frame.py
> +        >>> data={'class':['Mammals','Mammals','Reptiles','Reptiles','Amphibians','Amphibians'],
i don't think this is pep8 formatted, can you add spaces where needed

2021-07-28 01:51 UTC, jreback commented on pandas/core/frame.py
> +        >>> df.reorder_levels(["diet", "class"])
is this how it actually renders?

2021-08-13 22:52 UTC, jreback commented
closing in favor of #42935

2021-08-13 22:52 UTC, closed without merging