TST: test_column_types_consistent
pandas-dev/pandas pull request #42725
Opened 2021-07-26 14:26 UTC by shiv-io

- [x] closes #26779
- [x] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

This PR adds a test for the following issue: #26779

2021-07-26 22:37 UTC, jreback requested changes
precommit is failing: https://github.com/pandas-dev/pandas/pull/42725/checks?check_run_id=3162612999

make sure you do these locally before commit

2021-07-26 22:37 UTC, jreback commented on pandas/tests/generic/test_frame.py
> +    def test_column_types_consistent(self):
can you move to tests/frame/indexing/test_loc.py

2021-07-26 22:57 UTC, phofl commented on pandas/tests/generic/test_frame.py
> +                    np.NaN,
Coud you use pd.NaT for clairty?

2021-07-27 12:55 UTC, phofl approved these changes

2021-07-28 01:02 UTC, jreback approved these changes

2021-07-28 01:02 UTC, merged

2021-07-28 01:02 UTC, jreback commented
thanks @shiv-io