ENH: Provide a method to convert DataFrames to structured arrays.
pandas-dev/pandas pull request #42854
Opened 2021-08-02 14:39 UTC by anntzer

Structured arrays can be significantly faster than record arrays:
```
In [1]: s = np.random.rand(1000, 2).astype([("a", float), ("b", float)]); r = s.view(np.recarray)

In [2]: %timeit s["a"]
69.4 ns ± 0.0733 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [3]: %timeit r["a"]
1.2 µs ± 10 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [4]: %timeit r.a
1.86 µs ± 7.42 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```
Therefore it can be desirable to convert DataFrames to
structured arrays rather than record arrays (the recipe
for the conversion directly comes from the numpy docs at
https://numpy.org/doc/stable/user/basics.rec.html#record-arrays,
ignoring the handling of non-record inputs).

Currently the implementation simply reuses the to_record implementation.

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-08-02 16:58 UTC, jreback requested changes
-1 on adding api like this. using structured / recarrays not have dubious use cases to be honest

would take a doc note

2021-08-02 17:12 UTC, anntzer commented
Feel free to close if you're not going to accept this, I don't mind keeping this as a helper in my own utils.py...

2021-08-02 22:17 UTC, jbrockmendel commented
Agreed with Jeff.  A note in the docstring would be OK

2021-08-03 18:21 UTC, closed without merging

2021-08-03 18:22 UTC, anntzer commented
I'm not sure what specifically you suggest adding to the docstring?