TST: add test for getting array from series
pandas-dev/pandas pull request #42939
Opened 2021-08-08 21:00 UTC by horaceklai

- [x ] closes #38543 
- [ x] tests added / passed
- [x ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-08-08 23:21 UTC, jreback requested changes

2021-08-08 23:21 UTC, jreback commented on pandas/tests/arrays/test_array.py
> +def test_array_from_series():
can you instead put in pandas/tests/test_constructors.py

and can you assert the results of each of these with `tm.assert_numpy_array_equal`.

2021-08-08 23:21 UTC, mroeschke commented on pandas/tests/arrays/test_array.py
> +    np.array([pd.Series({0: 0})])
Could you use `pytest.mark.parameterize` to test each case?

Additionally, these tests should follow the format

```
result = np.array(np.array([pd.Series({0: 0})]))
expected = np.array(...) # another way to construct the result
tm.assert_numpy_array_equal(result, expected)
```

2021-08-17 00:22 UTC, mroeschke commented
Mind investigating the failures @horaceklai?

2021-08-17 21:28 UTC, horaceklai commented
> Mind investigating the failures @horaceklai?

Do you mean investigating the bug that the issue initially described?

The failure has to do with the bug reoccurring. I thought it was fixed from the comments written before I took this issue, but it is here now.

2021-08-19 01:41 UTC, jreback requested changes

2021-08-19 01:41 UTC, jreback commented on pandas/tests/test_constructors.py
> +import numpy as np
sorry menat pandas/tests/series/test_constructors.py

2021-08-31 23:44 UTC, jreback commented
can you merge master and ping on green.

2021-09-05 00:05 UTC, lithomas1 requested changes
You need to skip this test on old numpy. I believe 1.19 is the first version it works on but haven't checked.

2021-09-05 12:48 UTC, horaceklai commented
> You need to skip this test on old numpy. I believe 1.19 is the first version it works on but haven't checked.

Hi Thomas,

I am not sure how to skip certain tests for old numpy. Mind giving me a tip?

Thanks,
Horace

2021-09-05 14:55 UTC, lithomas1 commented
Have a look at the ``pytest.mark.skipif`` decorator(https://docs.pytest.org/en/latest/reference/reference.html#pytest-mark-skipif-ref). 

You'll also need https://github.com/pandas-dev/pandas/blob/35d52ff2d50ebbf24514407d5986ccf89f56b296/pandas/compat/numpy/__init__.py#L12 from ``pandas.compat.numpy``.
This variable is a boolean that tells you if the numpy version is under 1.19

So you'll have something like 
```
from pandas.compat.numpy import np_version_under1p19
...
...
...
@pytest.mark.skipif(np_version_under1p19, reason="fails on numpy below 1.19")
[your test code]
```

Let me know if you have more questions.

2021-09-06 12:34 UTC, horaceklai commented
> Have a look at the `pytest.mark.skipif` decorator(https://docs.pytest.org/en/latest/reference/reference.html#pytest-mark-skipif-ref).
> 
> You'll also need
> 
> https://github.com/pandas-dev/pandas/blob/35d52ff2d50ebbf24514407d5986ccf89f56b296/pandas/compat/numpy/__init__.py#L12
> 
> from `pandas.compat.numpy`.
> This variable is a boolean that tells you if the numpy version is under 1.19
> So you'll have something like
> 
> ```
> from pandas.compat.numpy import np_version_under1p19
> ...
> ...
> ...
> @pytest.mark.skipif(np_version_under1p19, reason="fails on numpy below 1.19")
> [your test code]
> ```
> 
> Let me know if you have more questions.

Thanks! You pretty much did all the work for me and I learned something new!

2021-09-06 15:25 UTC, jreback commented on pandas/tests/series/test_constructors.py
> +@pytest.mark.skipif(np_version_under1p19, reason="fails on numpy below 1.19")
can you write a tests that specifically tests < numpy 1.19. e.g. an asserts the error that happens (OT I wonder if this is fixable on the pandas side).

2021-09-06 15:32 UTC, horaceklai commented
Yes, good idea.

On Mon, Sep 6, 2021, 5:25 PM Jeff Reback ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In pandas/tests/series/test_constructors.py
> <https://github.com/pandas-dev/pandas/pull/42939#discussion_r702974630>:
>
> > @@ -1840,3 +1841,17 @@ def test_constructor(rand_series_with_duplicate_datetimeindex):
>      dups = rand_series_with_duplicate_datetimeindex
>      assert isinstance(dups, Series)
>      assert isinstance(dups.index, DatetimeIndex)
> +
> +
> ***@***.***(
> +    "input_dict,expected",
> +    [
> +        ({0: 0}, np.array([[0]], dtype=np.int64)),
> +        ({"a": "a"}, np.array([["a"]], dtype=object)),
> +        ({1: 1}, np.array([[1]], dtype=np.int64)),
> +    ],
> +)
> ***@***.***(np_version_under1p19, reason="fails on numpy below 1.19")
>
> can you write a tests that specifically tests < numpy 1.19. e.g. an
> asserts the error that happens (OT I wonder if this is fixable on the
> pandas side).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/42939#pullrequestreview-747317050>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKTQNIYUAY6N3G6P42VDOQTUATMQHANCNFSM5BY3FVMA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-12 18:14 UTC, lithomas1 commented
@horaceklai Can you fix the test failures?

2021-09-12 21:07 UTC, horaceklai commented
> @horaceklai Can you fix the test failures?

I think I fixed it now with the error message not matching, but now I'm having another error that I don't know if it is related. The test is taking too much time (> 1hr)

2021-09-13 00:20 UTC, lithomas1 approved these changes
Lgtm. Thanks for the PR. Don't worry about the timeouts.

2021-09-13 02:18 UTC, mroeschke approved these changes

2021-09-13 02:18 UTC, merged

2021-09-13 02:18 UTC, mroeschke commented
Thanks @horaceklai