Update frame.py
pandas-dev/pandas pull request #42935
Opened 2021-08-08 16:47 UTC by trevorkask

Response to changes suggested on my previous pull request

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-08-08 16:47 UTC, pep8speaks commented
Hello @trevorkask! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/frame.py`](https://github.com/pandas-dev/pandas/blob/61bd74917f46b5d83d2f53286a1748429a83d1ac/pandas/core/frame.py):

> [Line 6793:8](https://github.com/pandas-dev/pandas/blob/61bd74917f46b5d83d2f53286a1748429a83d1ac/pandas/core/frame.py#L6793): [E901](https://duckduckgo.com/?q=pep8%20E901) IndentationError: unindent does not match any outer indentation level

2021-08-08 16:56 UTC, MarcoGorelli requested changes
Have you tried building the docs to check this looks right? 

https://pandas.pydata.org/pandas-docs/stable/development/contributing_documentation.html

2021-08-08 17:02 UTC, attack68 commented
Are you going to close #42667 or this? You should really continue that PR and close this one.

2021-08-15 15:47 UTC, MarcoGorelli requested changes
Can you try building the docs for this function locally to check it renders fine? (hint: at the moment it won't, this'll help you tell whether the PR is ready)

2021-08-15 15:47 UTC, MarcoGorelli commented on pandas/core/frame.py
> +        --------
This won't render, it needs to be inside the docstring

2021-08-15 15:47 UTC, MarcoGorelli commented on pandas/core/frame.py
> +        >>> df.set_index(['class','diet'],drop=True,inplace=True)
can you write this without using `inplace=True` please?

2021-08-16 01:29 UTC, jreback commented
use this one

2021-08-22 14:26 UTC, MarcoGorelli requested changes
Hi @trevorkask - the example looks good, there's just some stylistic errors

Can you fix them up? See https://pandas.pydata.org/pandas-docs/stable/development/contributing_codebase.html?highlight=pre%20commit#pre-commit

2021-08-23 16:54 UTC, MarcoGorelli approved these changes
![](https://i.fluffy.cc/Xr1jnB3r6dWrfwqPwNdrpnF9zW1lVp0F.gif)

2021-08-23 16:54 UTC, merged

2021-08-23 16:54 UTC, MarcoGorelli commented
Thanks @trevorkask