ENH: add kwarg `max_rows` `max_cols` to `Styler.to_html`
pandas-dev/pandas pull request #42972
Opened 2021-08-10 17:45 UTC by attack68

one more item towards deprecating `DataFrame.to_html` for #41693

2021-08-31 23:01 UTC, jreback commented on pandas/io/formats/style_render.py
> +    if max_rows:
this exercised enough in tests?

2021-08-31 23:01 UTC, jreback requested changes
can you rebase

2021-09-06 21:48 UTC, jreback commented
can you merge master

2021-09-07 16:14 UTC, attack68 commented on pandas/io/formats/style_render.py
> +    if max_rows:
added specific cases

2021-09-08 21:53 UTC, jreback approved these changes

2021-09-09 06:04 UTC, merged