Bug in Series constructor returning wrong missing values
pandas-dev/pandas pull request #43026
Opened 2021-08-13 20:29 UTC by phofl

- [x] closes #43017
- [x] xref #43018 (if the reindex case is ok, then this is done too)
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

This ensures consistency with the DataFrame constructor

2021-08-13 21:43 UTC, jreback commented on doc/source/whatsnew/v1.4.0.rst
> +- Bug in :class:`Series` constructor returning 0 for missing values with dtype ``int64`` and ``False`` for dtype ``boo`` (:issue:`43017`, :issue:`43018`)
```suggestion
- Bug in :class:`Series` constructor returning 0 for missing values with dtype ``int64`` and ``False`` for dtype ``bool`` (:issue:`43017`, :issue:`43018`)
```

2021-08-13 21:44 UTC, jreback requested changes

2021-08-13 21:44 UTC, jreback commented on pandas/tests/series/methods/test_astype.py
> +        expected = Series(True, dtype="bool")
this is True?

2021-08-13 21:44 UTC, jreback commented on pandas/tests/series/test_constructors.py
> +        expected = Series(True, index=[0], dtype="bool")
this is True?

2021-08-13 22:57 UTC, jbrockmendel commented on pandas/tests/series/methods/test_astype.py
> +        expected = Series(True, dtype="bool")
`bool(np.nan)` returns True

2021-08-14 18:45 UTC, phofl commented on pandas/tests/series/methods/test_astype.py
> +        expected = Series(True, dtype="bool")
Yes exactly.

2021-08-19 02:01 UTC, jreback approved these changes

2021-08-19 02:01 UTC, merged

2021-08-19 02:01 UTC, jreback commented
thanks @phofl

2022-03-25 17:20 UTC, simonjayhawkins commented
@phofl we have had reports regarding both these cases. Is the new behavior now consistent?

```python
import pandas as pd

print(pd.__version__)
s = pd.Series(dtype="int", index=[0])
print(s)
s2 = pd.Series(dtype="bool", index=[0])
print(s2)
```
```
1.3.5
0    0
dtype: int64
0    False
dtype: bool
```
```
1.4.1
0   NaN
dtype: float64
0    True
dtype: bool
```

It appears to me (and maybe others from the issues) that the changes are confusing.

We have changed the `int` case and and instead create a `float` array saying that the missing value cannot be held in a integer array and yet for the bool case we continue to keep the bool dtype even though we cannot represent a missing value in a boolean array?

I appreciate that `int(np.nan)` raises `ValueError: cannot convert float NaN to integer` and `bool(np.nan)` is `True` but the users are not specifying `np.nan`, they are not supplying data. I wonder whether we ought to revert this until we change the constructors to use nullable dtypes?

2022-04-01 20:45 UTC, jbrockmendel commented
>  I wonder whether we ought to revert this until we change the constructors to use nullable dtypes?

no opinion on the reversion, but i advise against the implicit assumption that constructors are going to default to nullable dtypes.  support has improved, but its still a mess.