REGR: window ewm slowdown
pandas-dev/pandas pull request #43052
Opened 2021-08-15 14:34 UTC by mzeitlin11

- [x] closes #42333
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry (will move once 1.3.3 notes merged)

```
-     3.22±0.09ms       1.29±0.3ms     0.40  rolling.EWMMethods.time_ewm('DataFrame', 10, 'int', 'mean')
-      2.92±0.1ms       1.08±0.1ms     0.37  rolling.EWMMethods.time_ewm('DataFrame', 1000, 'int', 'mean')
-      2.68±0.1ms        959±100μs     0.36  rolling.EWMMethods.time_ewm('DataFrame', 1000, 'float', 'mean')
-      3.00±0.2ms      1.02±0.03ms     0.34  rolling.EWMMethods.time_ewm('DataFrame', 10, 'float', 'mean')
-      2.78±0.1ms        850±100μs     0.31  rolling.EWMMethods.time_ewm('Series', 10, 'int', 'mean')
-      2.34±0.2ms         683±30μs     0.29  rolling.EWMMethods.time_ewm('Series', 10, 'float', 'mean')
-     2.74±0.06ms         739±60μs     0.27  rolling.EWMMethods.time_ewm('Series', 1000, 'float', 'mean')
-      2.55±0.3ms         681±40μs     0.27  rolling.EWMMethods.time_ewm('Series', 1000, 'int', 'mean')
```

2021-08-15 17:54 UTC, jbrockmendel commented
nice speedup, cc @mroeschke

2021-08-15 17:57 UTC, mroeschke approved these changes
Thanks! LGTM

2021-08-15 17:58 UTC, jreback requested changes
yep lgtm

2021-08-15 17:58 UTC, jreback commented on doc/source/whatsnew/v1.3.2.rst
> +- Performance regression in :meth:`core.window.ewm.ExponentialMovingWindow.mean` (:issue:`42333`)
move to 1.3.3

2021-08-15 17:58 UTC, jreback commented on pandas/_libs/window/aggregations.pyx
> +         const float64_t[:] deltas=None) -> np.ndarray:
can u update the doc string

2021-08-15 19:09 UTC, mzeitlin11 commented on pandas/_libs/window/aggregations.pyx
> +         const float64_t[:] deltas=None) -> np.ndarray:
done

2021-08-15 19:09 UTC, mzeitlin11 commented on doc/source/whatsnew/v1.3.2.rst
> +- Performance regression in :meth:`core.window.ewm.ExponentialMovingWindow.mean` (:issue:`42333`)
done

2021-08-16 20:26 UTC, jreback approved these changes

2021-08-16 20:26 UTC, merged

2021-08-16 20:27 UTC, jreback commented
thanks @mzeitlin11

2021-08-16 20:27 UTC, jreback commented
@meeseeksdev backport 1.3.x