TST: groupby.first/last retains categorical dtype
pandas-dev/pandas pull request #43153
Opened 2021-08-21 11:57 UTC by debnathshoham

- [x] closes #33090
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

2021-08-21 14:21 UTC, jreback requested changes

2021-08-21 14:21 UTC, jreback commented on pandas/tests/groupby/test_categorical.py
> +def test_groupby_last_first_preserve_categoricaldtype():
can you parameterize over first/last

2021-08-24 19:11 UTC, debnathshoham commented on pandas/tests/groupby/test_categorical.py
> +def test_groupby_last_first_preserve_categoricaldtype():
Done

2021-08-25 19:56 UTC, phofl requested changes

2021-08-26 09:14 UTC, phofl approved these changes
Lgtm

2021-08-31 23:57 UTC, jreback approved these changes

2021-08-31 23:58 UTC, merged

2021-08-31 23:58 UTC, jreback commented
thanks @debnathshoham 

since we get a lot of PRs, periodically rebasing yours is a good idea as it moves them to the front of the queue (assuming they are ready to go)