TST: added test for to_string when max_rows is zero (GH35394)
pandas-dev/pandas pull request #43300
Opened 2021-08-30 10:20 UTC by lorenzophys

- [x] closes #35394
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

Provided tests for `to_string` when `max_rows=0`.

Tests and linter pass locally.

2021-08-31 22:15 UTC, alimcmaster1 commented on pandas/tests/io/formats/test_to_string.py
> +
Can remove this blank line

2021-08-31 22:17 UTC, alimcmaster1 requested changes
Thanks for the PR. Minor comments

2021-08-31 22:17 UTC, alimcmaster1 commented on pandas/tests/io/formats/test_to_string.py
> +            {"col1": [0, 2, 4], "col2": [3, 4, 5]},
This test case seems pretty similar to the first is it really needed?

2021-09-01 16:18 UTC, alimcmaster1 commented
/azp run

2021-09-01 16:19 UTC, alimcmaster1 approved these changes
Looks okay to me.

2021-09-01 18:08 UTC, merged

2021-09-01 18:08 UTC, jreback commented
thanks @lorenzophys