Refactor/validate utils
pandas-dev/pandas pull request #43551
Opened 2021-09-13 15:42 UTC by zyc09

- [x] refactoring for #40245
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

2021-09-13 19:06 UTC, jreback requested changes
looks really code, some comments. ping on green.

2021-09-13 19:06 UTC, jreback commented on pandas/util/_validators.py
> +def validate_endpoints(closed):
can you type this (input & output)

2021-09-13 19:06 UTC, jreback commented on pandas/util/_validators.py
> +def validate_inclusive(inclusive):
can you type

2021-09-14 12:13 UTC, jreback approved these changes

2021-09-14 12:14 UTC, jreback requested changes

2021-09-14 12:14 UTC, jreback commented on pandas/util/_validators.py
> +def validate_endpoints(closed: Any) -> tuple[bool, bool]:
hmm this should be Optional[str]

2021-09-14 12:14 UTC, jreback commented on pandas/util/_validators.py
> +def validate_inclusive(inclusive: Any) -> tuple[bool, bool]:
same here Optional[str]

2021-09-14 12:19 UTC, zyc09 commented on pandas/util/_validators.py
> +def validate_inclusive(inclusive: Any) -> tuple[bool, bool]:
oof, let me amend that

2021-09-14 12:38 UTC, jreback approved these changes

2021-09-14 14:09 UTC, merged

2021-09-14 14:09 UTC, jreback commented
thanks @zyc09 very nice!