TST: Adding unit tests for named indexes resulting from empty datafra…
pandas-dev/pandas pull request #43593
Opened 2021-09-16 01:46 UTC by IamJasonBian

…me shifts

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

Tests added for issue: https://github.com/pandas-dev/pandas/issues/41264

2021-09-16 01:46 UTC, pep8speaks commented
Hello @IamJasonBian! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/groupby/test_groupby_shift_emptydf.py`](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py):

> [Line 5:14](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L5): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 10:1](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L10): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 11:5](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L11): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 11:89](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L11): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (112 > 88 characters)
> [Line 12:1](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L12): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 14:1](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L14): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 17:1](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L17): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 20:1](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L20): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 21:1](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L21): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 22:5](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L22): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 22:89](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L22): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 88 characters)
> [Line 23:1](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L23): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 25:1](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L25): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 26:36](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L26): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 27:46](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L27): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 28:1](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L28): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 31:1](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L31): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 32:1](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L32): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 33:5](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L33): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 33:74](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L33): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 34:5](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L34): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 35:1](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L35): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 36:31](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L36): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 36:34](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L36): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 36:36](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L36): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 36:44](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L36): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 36:47](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L36): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 36:49](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L36): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 36:57](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L36): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 36:60](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L36): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 36:62](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L36): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 38:1](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L38): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 39:36](https://github.com/pandas-dev/pandas/blob/1c8debe3299a19ff2f1eb7bdd6a13ffe597282bb/pandas/tests/groupby/test_groupby_shift_emptydf.py#L39): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line [...]

2021-09-16 21:23 UTC, jreback requested changes

2021-09-16 21:23 UTC, jreback commented on pandas/tests/groupby/test_groupby_shift_emptydf.py
> +from pandas import (
pls don't make a new file, look for a similar test in this directory and put it near.

2021-09-16 21:23 UTC, jreback commented on pandas/tests/groupby/test_groupby_shift_emptydf.py
> +def test_empty_shift_with_fill():
referencde the original issue in a comment

2021-09-16 21:23 UTC, jreback commented on pandas/tests/groupby/test_groupby_shift_emptydf.py
> +
looks like you can parameterize some of these

2021-09-22 06:56 UTC, IamJasonBian commented
@jreback 
* merged with test_groupby_shift_diff
* removed third test as issue did not exist in 1.3.0.dev0+1510.gfea6799dba

2021-10-03 22:53 UTC, jreback requested changes
pls merge master and ping on green

2021-10-03 22:53 UTC, jreback commented on pandas/tests/groupby/test_groupby_shift_diff.py
> +@pytest.mark.parametrize(
since this is just a single test no need to parameterize (e.g. just create it inside the test)

2021-10-04 16:59 UTC, IamJasonBian commented
@jreback, ok to push? Not sure why pre-commit black is failing and PEP8 linter passed locally.

2021-10-05 00:16 UTC, jreback commented
no if precommit is failing then there is a problem

2021-10-05 07:26 UTC, IamJasonBian commented
@jreback pinging on green

2021-10-31 01:01 UTC, mroeschke commented
@IamJasonBian could you merge master one more time? Will merge after all green again

2021-10-31 01:01 UTC, mroeschke approved these changes

2021-10-31 14:57 UTC, jreback approved these changes

2021-10-31 14:58 UTC, merged

2021-10-31 14:58 UTC, jreback commented
thanks @IamJasonBian