GH36236
pandas-dev/pandas pull request #43700
Opened 2021-09-22 17:31 UTC by kasmith11

TST

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

2021-09-22 17:31 UTC, pep8speaks commented
Hello @kasmith11! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/frame/methods/test_join.py`](https://github.com/pandas-dev/pandas/blob/76e03c8501f8d270a35b4a785559b8a54ce2816e/pandas/tests/frame/methods/test_join.py):

> [Line 377:1](https://github.com/pandas-dev/pandas/blob/76e03c8501f8d270a35b4a785559b8a54ce2816e/pandas/tests/frame/methods/test_join.py#L377): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 378:52](https://github.com/pandas-dev/pandas/blob/76e03c8501f8d270a35b4a785559b8a54ce2816e/pandas/tests/frame/methods/test_join.py#L378): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 378:54](https://github.com/pandas-dev/pandas/blob/76e03c8501f8d270a35b4a785559b8a54ce2816e/pandas/tests/frame/methods/test_join.py#L378): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 378:56](https://github.com/pandas-dev/pandas/blob/76e03c8501f8d270a35b4a785559b8a54ce2816e/pandas/tests/frame/methods/test_join.py#L378): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 378:58](https://github.com/pandas-dev/pandas/blob/76e03c8501f8d270a35b4a785559b8a54ce2816e/pandas/tests/frame/methods/test_join.py#L378): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 379:52](https://github.com/pandas-dev/pandas/blob/76e03c8501f8d270a35b4a785559b8a54ce2816e/pandas/tests/frame/methods/test_join.py#L379): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 379:54](https://github.com/pandas-dev/pandas/blob/76e03c8501f8d270a35b4a785559b8a54ce2816e/pandas/tests/frame/methods/test_join.py#L379): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 379:56](https://github.com/pandas-dev/pandas/blob/76e03c8501f8d270a35b4a785559b8a54ce2816e/pandas/tests/frame/methods/test_join.py#L379): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 379:58](https://github.com/pandas-dev/pandas/blob/76e03c8501f8d270a35b4a785559b8a54ce2816e/pandas/tests/frame/methods/test_join.py#L379): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2021-09-22 18:28 UTC, kasmith11 commented
@github-actions pre-commit

2021-09-22 18:37 UTC, debnathshoham commented
Hi @kasmith11. Thanks for the PR!
Is there a particular issue you're trying to address?

2021-09-22 18:39 UTC, kasmith11 commented
Hello @debnathshoham I wanted to contribute a test for the [following issue](https://github.com/pandas-dev/pandas/issues/36263).

2021-09-22 18:45 UTC, debnathshoham commented
Awesome! Could you please make the title to more informative.
And mark closes #36263 in the OP.

2021-09-22 18:50 UTC, kasmith11 commented
@debnathshoham done!

2021-09-23 04:48 UTC, attack68 requested changes

2021-09-23 04:48 UTC, attack68 commented on pandas/tests/frame/methods/test_join.py
> +    df1 = pd.DataFrame(np.random.randn(5), index=[0, 1, 2, 3, 3], columns=["a"])
add `# GH xxxxx`, with the relevant issue your solving with the test above this line.

2021-09-27 14:20 UTC, kasmith11 commented
@github-actions pre-commit

2021-11-07 02:38 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale and the added test is still not passing the CI. If you'd like to continue, please merge master and we can reopen.

2021-11-07 02:38 UTC, closed without merging