ENH: Add equivalence test for float in to_numeric() GH43693
pandas-dev/pandas pull request #43710
Opened 2021-09-23 03:49 UTC by jbencina

- [x] closes #43693 
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

This PR prevents issues where float64 arrays would be downcast to float32 arrays even if the values were out of range for float32. An equivalence check is performed to ensure all values are equal to 7 significant digits. If this fails, the original float64 is retained. This behavior is consistent with int where downcasting is not performed if the integer is out of bounds.

Pre Change:
```python
>>> pd.to_numeric(pd.Series([608202549.0]), downcast='float')
0    608202560.0
```
Post Change:
```python
>>> pd.to_numeric(pd.Series([608202549.0]), downcast='float')
0    608202549.0
```

2022-01-16 18:04 UTC, jreback commented
@jbencina can you move the note, this looks good

2022-01-16 18:04 UTC, jreback requested changes
pls move the note and merge master

2022-01-16 18:04 UTC, jreback commented on doc/source/whatsnew/v1.4.0.rst
> +- :meth:`to_numeric` now preserves float64 arrays when downcasting would generate values not representable in float32 (:issue:`43693`)
can you move to 1.5

2022-01-16 21:28 UTC, jbencina commented on doc/source/whatsnew/v1.4.0.rst
> +- :meth:`to_numeric` now preserves float64 arrays when downcasting would generate values not representable in float32 (:issue:`43693`)
Moved this note to v1.5.0.rst

2022-01-16 23:58 UTC, jbencina commented
@jreback Moved the change to V1.5.0. Not sure why this PR has trouble with the CI checks, but I don't think it's related to my code (eg. Azure timing out)

2022-01-17 01:06 UTC, jreback approved these changes

2022-01-17 13:48 UTC, merged

2022-01-17 13:48 UTC, jreback commented
thanks @jbencina