GH38482: Added sentence to show that unmatched values return -1.
pandas-dev/pandas pull request #43738
Opened 2021-09-25 11:22 UTC by DhruvBShetty

- [ ] closes #38482
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew: Added sentence to show that unmatched values return -1 in get_indexer method

In [1]: python make.py --single pandas.Index.get_indexer
Out [1]:![image](https://user-images.githubusercontent.com/50010452/134762263-3be88054-ddfa-4fee-889c-112c00cf780e.png)

In [2]: pre-commit run --files pandas/core/indexes/base.py
Out [2] : ![image](https://user-images.githubusercontent.com/50010452/134768894-a75b8ade-175e-477d-94ff-fefa224f98f9.png)

2021-09-25 11:22 UTC, pep8speaks commented
Hello @DhruvBShetty! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/indexes/base.py`](https://github.com/pandas-dev/pandas/blob/27033142f8470b9bcf067a8702cc7916771698fe/pandas/core/indexes/base.py):

> [Line 3486:1](https://github.com/pandas-dev/pandas/blob/27033142f8470b9bcf067a8702cc7916771698fe/pandas/core/indexes/base.py#L3486): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2021-09-25 17:25 UTC, MarcoGorelli approved these changes
![](https://i.fluffy.cc/XLT38p3r6PgBxFpMgcp72Cl2bvLRMrlt.gif)

2021-09-29 13:22 UTC, jreback requested changes

2021-09-29 13:22 UTC, jreback commented on pandas/core/indexes/base.py
> +        Returns -1 for unmatched values, for further explanation see the example
move to the Notes section

2021-10-30 07:57 UTC, MarcoGorelli commented
Hi @DhruvBShetty can you address the comment please

2021-10-31 18:13 UTC, DhruvBShetty commented
> This pull request is stale because it has been open for thirty days with no activity. Please update or respond to this comment if you're still interested in working on this.
Interested

2021-10-31 18:14 UTC, DhruvBShetty commented
> This pull request is stale because it has been open for thirty days with no activity. Please update or respond to this comment if you're still interested in working on this.

Interested in finishing this.

2021-10-31 22:37 UTC, MarcoGorelli requested changes
please check the [pandas docstring guide](https://pandas.pydata.org/pandas-docs/stable/development/contributing_docstring.html) for how to write the "notes" section

2021-11-01 09:00 UTC, MarcoGorelli requested changes
Can you run the [validating docstrings](https://pandas.pydata.org/docs/development/contributing_documentation.html#updating-a-pandas-docstring) script for this function?

2021-11-01 11:14 UTC, DhruvBShetty commented
> Can you run the [validating docstrings](https://pandas.pydata.org/docs/development/contributing_documentation.html#updating-a-pandas-docstring) script for this function?

Done, It's the first error
![image](https://user-images.githubusercontent.com/50010452/139662439-9a7d1f8c-5d3e-4e0d-8657-1ad0e45eaae5.png)

After which it's this
![image](https://user-images.githubusercontent.com/50010452/139662605-d267c753-630b-426d-b46d-5e7ea5a9ff39.png)

Left a line between %(raises_section)s and notes accidentally.
![image](https://user-images.githubusercontent.com/50010452/139662878-b94ea7d9-aefc-4e61-8362-3045f8c18d81.png)

2021-11-01 11:29 UTC, MarcoGorelli approved these changes
Nice, thanks!

![](https://i.fluffy.cc/2VN5sRNLH0hds4wglBHfnstJlJXC4mgJ.gif)

2021-11-06 02:45 UTC, mroeschke approved these changes

2021-11-06 02:45 UTC, merged

2021-11-06 02:45 UTC, mroeschke commented
Thanks @DhruvBShetty