update fix ignored sort in api.py and add test
pandas-dev/pandas pull request #43833
Opened 2021-10-01 14:23 UTC by CloseChoice

- [ ] closes #43375 
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

2021-10-01 14:23 UTC, pep8speaks commented
Hello @CloseChoice! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/arrays/integer/test_concat.py`](https://github.com/pandas-dev/pandas/blob/b50dcb507bb1c635aff302d700b18f35daefbee9/pandas/tests/arrays/integer/test_concat.py):

> [Line 67:1](https://github.com/pandas-dev/pandas/blob/b50dcb507bb1c635aff302d700b18f35daefbee9/pandas/tests/arrays/integer/test_concat.py#L67): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 68:89](https://github.com/pandas-dev/pandas/blob/b50dcb507bb1c635aff302d700b18f35daefbee9/pandas/tests/arrays/integer/test_concat.py#L68): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 88 characters)
> [Line 69:65](https://github.com/pandas-dev/pandas/blob/b50dcb507bb1c635aff302d700b18f35daefbee9/pandas/tests/arrays/integer/test_concat.py#L69): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 69:80](https://github.com/pandas-dev/pandas/blob/b50dcb507bb1c635aff302d700b18f35daefbee9/pandas/tests/arrays/integer/test_concat.py#L69): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 70:16](https://github.com/pandas-dev/pandas/blob/b50dcb507bb1c635aff302d700b18f35daefbee9/pandas/tests/arrays/integer/test_concat.py#L70): [E702](https://duckduckgo.com/?q=pep8%20E702) multiple statements on one line (semicolon)
> [Line 73:1](https://github.com/pandas-dev/pandas/blob/b50dcb507bb1c635aff302d700b18f35daefbee9/pandas/tests/arrays/integer/test_concat.py#L73): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2021-10-01 19:18 UTC, jreback commented on pandas/tests/arrays/integer/test_concat.py
> +def test_concat_frame_with_sort_false():
can you move to pandas/tests/reshape/concat/test_sort.py

put near simliar tests

2021-10-01 19:18 UTC, jreback requested changes
might have to adjust some other tests

2021-10-03 07:30 UTC, CloseChoice commented
> might have to adjust some other tests

Can we just adjust other test results? That would be technically be a breaking change, wouldn't it?

2021-10-03 12:03 UTC, jreback commented
my point about adjusting test is that this case might be only internal or not - will have to see

2021-10-08 12:30 UTC, jreback requested changes
looks good, can you add a whatsnew note for 1.4, reshaping and ping on green

2021-10-08 14:33 UTC, CloseChoice commented
@github-actions pre-commit

2021-10-08 16:33 UTC, CloseChoice commented
@jreback all lights on green.

2021-10-10 17:28 UTC, jreback approved these changes

2021-10-10 17:28 UTC, merged