CLN: assorted
pandas-dev/pandas pull request #43845
Opened 2021-10-01 21:57 UTC by jbrockmendel

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

2021-10-01 23:58 UTC, jreback requested changes

2021-10-01 23:58 UTC, jreback commented on pandas/core/series.py
> +            result = np.empty(len(self), dtype=np.intp)
np.full?

2021-10-02 01:50 UTC, jbrockmendel commented on pandas/core/series.py
> +            result = np.empty(len(self), dtype=np.intp)
sure, updated

2021-10-03 13:54 UTC, jreback approved these changes

2021-10-03 13:54 UTC, merged