added test case for issue #43599
pandas-dev/pandas pull request #43879
Opened 2021-10-04 14:49 UTC by gamenerd457

-added unittest  for issue #43599 
-error occurs due to different versions of pandas

2021-10-04 14:49 UTC, pep8speaks commented
Hello @gamenerd457! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/indexing/test_loc.py`](https://github.com/pandas-dev/pandas/blob/ea55a095b50e34822d2860816c9d98ca184995f7/pandas/tests/indexing/test_loc.py):

> [Line 2863:35](https://github.com/pandas-dev/pandas/blob/ea55a095b50e34822d2860816c9d98ca184995f7/pandas/tests/indexing/test_loc.py#L2863): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 2863:36](https://github.com/pandas-dev/pandas/blob/ea55a095b50e34822d2860816c9d98ca184995f7/pandas/tests/indexing/test_loc.py#L2863): [E262](https://duckduckgo.com/?q=pep8%20E262) inline comment should start with '# '
> [Line 2865:89](https://github.com/pandas-dev/pandas/blob/ea55a095b50e34822d2860816c9d98ca184995f7/pandas/tests/indexing/test_loc.py#L2865): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (114 > 88 characters)
> [Line 2866:12](https://github.com/pandas-dev/pandas/blob/ea55a095b50e34822d2860816c9d98ca184995f7/pandas/tests/indexing/test_loc.py#L2866): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 2866:27](https://github.com/pandas-dev/pandas/blob/ea55a095b50e34822d2860816c9d98ca184995f7/pandas/tests/indexing/test_loc.py#L2866): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 2866:31](https://github.com/pandas-dev/pandas/blob/ea55a095b50e34822d2860816c9d98ca184995f7/pandas/tests/indexing/test_loc.py#L2866): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 2867:12](https://github.com/pandas-dev/pandas/blob/ea55a095b50e34822d2860816c9d98ca184995f7/pandas/tests/indexing/test_loc.py#L2867): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 2867:89](https://github.com/pandas-dev/pandas/blob/ea55a095b50e34822d2860816c9d98ca184995f7/pandas/tests/indexing/test_loc.py#L2867): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (112 > 88 characters)
> [Line 2869:1](https://github.com/pandas-dev/pandas/blob/ea55a095b50e34822d2860816c9d98ca184995f7/pandas/tests/indexing/test_loc.py#L2869): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 2870:9](https://github.com/pandas-dev/pandas/blob/ea55a095b50e34822d2860816c9d98ca184995f7/pandas/tests/indexing/test_loc.py#L2870): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 2870:34](https://github.com/pandas-dev/pandas/blob/ea55a095b50e34822d2860816c9d98ca184995f7/pandas/tests/indexing/test_loc.py#L2870): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 2872:1](https://github.com/pandas-dev/pandas/blob/ea55a095b50e34822d2860816c9d98ca184995f7/pandas/tests/indexing/test_loc.py#L2872): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2021-10-04 16:08 UTC, mzeitlin11 requested changes
Thanks for the pr @gamenerd457.  Please look at the contributing guide (https://pandas.pydata.org/docs/development/index.html#development), especially the portions about testing (we don't use `unittest`) and style (this is currently failing checks)

2021-10-04 21:14 UTC, phofl requested changes
Please use pre-commit

2021-10-04 21:14 UTC, phofl commented on pandas/tests/indexing/test_loc.py
> +import unittest
We use pytest

2021-10-09 15:50 UTC, gamenerd457 commented
> Thanks for the pr @gamenerd457. Please look at the contributing guide (https://pandas.pydata.org/docs/development/index.html#development), especially the portions about testing (we don't use `unittest`) and style (this is currently failing checks)

I have made the changes

2021-10-10 22:01 UTC, jreback requested changes

2021-10-21 02:09 UTC, jreback requested changes

2021-11-14 03:19 UTC, jreback commented
ca you merge master and update to comments

2022-01-25 01:30 UTC, mroeschke commented
Thanks for the PR but appears to have gone stale. If interested in continuing please merge the main branch, address the review, and we can reopen.

2022-01-25 01:30 UTC, closed without merging