BUG: Fix groupby nth with axis=1
pandas-dev/pandas pull request #43926
Opened 2021-10-08 13:50 UTC by johnzangwill

Fixes a bug that no one has reported and probably no one cares about. But overlaps slightly with #42947, so I thought that I would make it a separate PR.

Current behaviour: `df.groupby(df.iloc[1], axis=1).nth(0)` crashes ungracefully.

2021-10-09 00:15 UTC, jreback requested changes
also pls add a whatsnew note for 1.4, groupby bug fix section

2021-10-09 15:43 UTC, johnzangwill commented
> also pls add a whatsnew note for 1.4, groupby bug fix section

Done

2021-10-10 21:59 UTC, jreback requested changes
small nit, pls merge master and ping on green

2021-10-12 22:18 UTC, jreback requested changes

2021-10-13 15:31 UTC, jreback approved these changes

2021-10-13 15:31 UTC, merged