added test to indexing on groupby, #32464
pandas-dev/pandas pull request #44046
Opened 2021-10-16 03:06 UTC by gabrieldi95

- [x] closes #32464
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them

This makes sure an index of a groupby with more then one column is always a MultiIndex.

2021-10-17 13:43 UTC, gabrieldi95 commented
I tried using `tm.assert_frame_equal` to test if a.groupby(["a", "b", "c"]).sum() has a MultiIndex like this:

```python
    a = DataFrame({"a": [], "b": [], "c": []})
    result = a.groupby(["a", "b", "c"]).sum()

    expected_index = MultiIndex.from_arrays([[], [], []], names=("a", "b", "c"))
    expected = DataFrame(
        np.ndarray((0, 0)), dtype="float64", index=expected_index, columns=Index([])
    )

    # Tests if groupby with all columns has a multiindex
    tm.assert_frame_equal(result, expected)
```

But it didn't work, so I'm keeping just the other assertion, that tests if both groupby's are equel.

2021-11-14 03:05 UTC, jreback commented
can you merge master and update to comments

2021-11-16 23:33 UTC, gabrieldi95 commented
Yes, I was working on other stuff, will work on it now!

2021-11-19 00:06 UTC, gabrieldi95 commented
Hm I don't really know why the check fail, can someone help me?

2021-11-28 20:48 UTC, jreback commented
can you merge master again and ping on green

2021-11-29 01:33 UTC, gabrieldi95 commented
@jreback can you help me with the error?

2021-12-23 22:53 UTC, jreback commented
is worthwhile but needs to be passing (and pls merge master)

2022-01-23 02:45 UTC, rhshadrach commented
@gabrieldi95 - The CI failure appears unrelated to me; can you try merging master again

2022-01-31 00:06 UTC, jreback commented
@gabrieldi95 can you merge master and address comments

2022-02-15 21:28 UTC, rhshadrach commented
Closing to take this off the queue. @gabrieldi95 please let me know if you'd like to continue this!

2022-02-15 23:30 UTC, gabrieldi95 commented
@rhshadrach sorry for taking so long! Yes, I would like to continue

2022-02-19 19:21 UTC, rhshadrach commented on pandas/tests/groupby/test_function.py
> +    agg_1 = a.groupby(["a", "b"]).sum()
Can you just test in the case of an empty frame here - nonempty is covered elsewhere. Indeed it is tricky to construct an empty MultiIndex of the expected type; this works:

```
df = DataFrame({"a": [1], "b": [2], "c": [3]}).set_index(['a', 'b', 'c'])
result = df.groupby(["a", "b", "c"]).sum().index[:0]
expected = df.index[:0]
tm.assert_index_equal(result, expected)
```

2022-02-19 19:25 UTC, rhshadrach requested changes

2022-02-19 19:25 UTC, rhshadrach commented on pandas/tests/groupby/test_function.py
> +def test_if_is_multiindex():
Can you rename to something like test_empty_multiindex

2022-02-27 00:23 UTC, jreback commented
can you merge master

2022-03-06 23:29 UTC, jreback commented
can you merge master and update to comments

2022-04-06 13:11 UTC, jreback commented on pandas/tests/groupby/test_function.py
> +    agg_1 = a.groupby(["a", "b"]).sum()
@gabrieldi95 can you replace the test with basically this example

2022-05-07 02:42 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in main and address the review and we can reopen.

2022-05-07 02:42 UTC, closed without merging