BUG: Change of behavior in casting of datetime-like types in MultiIndex
pandas-dev/pandas pull request #44081
Opened 2021-10-18 12:58 UTC by shubham11941140

- [x] closes #43091
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

Added try-except block in multi.py to reset the behaviour back to 1.2.5

2021-10-18 12:58 UTC, pep8speaks commented
Hello @shubham11941140! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/indexes/multi.py`](https://github.com/pandas-dev/pandas/blob/642392040a53f30fc1882d6f13643e4603380ce1/pandas/core/indexes/multi.py):

> [Line 1679:9](https://github.com/pandas-dev/pandas/blob/642392040a53f30fc1882d6f13643e4603380ce1/pandas/core/indexes/multi.py#L1679): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'

* In the file [`pandas/tests/series/methods/test_reset_index.py`](https://github.com/pandas-dev/pandas/blob/642392040a53f30fc1882d6f13643e4603380ce1/pandas/tests/series/methods/test_reset_index.py):

> [Line 183:1](https://github.com/pandas-dev/pandas/blob/642392040a53f30fc1882d6f13643e4603380ce1/pandas/tests/series/methods/test_reset_index.py#L183): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 186:33](https://github.com/pandas-dev/pandas/blob/642392040a53f30fc1882d6f13643e4603380ce1/pandas/tests/series/methods/test_reset_index.py#L186): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 187:33](https://github.com/pandas-dev/pandas/blob/642392040a53f30fc1882d6f13643e4603380ce1/pandas/tests/series/methods/test_reset_index.py#L187): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 193:89](https://github.com/pandas-dev/pandas/blob/642392040a53f30fc1882d6f13643e4603380ce1/pandas/tests/series/methods/test_reset_index.py#L193): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (117 > 88 characters)

2021-10-18 15:01 UTC, alimcmaster1 requested changes
Thanks for the PR - some comments above

2021-10-28 02:12 UTC, jreback requested changes
pls look at the 1.3 release. I am pretty sure we change this on purpose. `datetime.date` is retained which is the point here.

2021-11-04 11:24 UTC, simonjayhawkins commented
Thanks @shubham11941140 for the PR. These changes do not appear to correspond with the changes in the PR that was identified in the issue as causing the reported change in behavior.

We also need to decide if we are reverting to 1.2.5 behavior.

I am closing for now but feel free to contribute to the discussion in #43091

2021-11-04 11:24 UTC, closed without merging