PERF: improve efficiency of `BaseMaskedArray.__setitem__`
pandas-dev/pandas pull request #44186
Opened 2021-10-26 03:15 UTC by alexreg

This somewhat deals with #44172, though that won't be fully resolved until 2D `ExtensionArray`s are supported (per the comments there).

CC @jbrockmendel

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

2021-10-28 12:38 UTC, jreback requested changes
we also need an asv for this

2021-11-01 16:19 UTC, jbrockmendel commented on pandas/core/arrays/boolean.py
> +            key = check_array_indexer(self, key)
Take a look at the test_setitem_foo tests in tests.arrays.test_datetimelike.  Something similar in either tests.arrays.masked_shared or tests.arrays.(integer|boolean|floating).test_indexing

2021-11-28 21:02 UTC, jreback commented
@alexreg status here? pls merge master as well

2021-11-28 21:57 UTC, alexreg commented
@jreback Sorry, haven't had much time lately. It would probably take me a while to properly wrap my head around the testing framework and write good tests. Ideally someone else could step in with that, but if not, maybe I'll get to it in a month or two.

I rebased on current master, however, and pushed that. (Nice and easy.0

2021-12-16 23:32 UTC, jbrockmendel commented
> Ideally someone else could step in with that

None of us are going to write tests for you, but we will [help](https://github.com/pandas-dev/pandas/pull/44186#discussion_r740343732) you through getting the hang of writing them.

```
def test_descriptive_name():
    obj = pd.whatever()
    with pytest.raises(something, match=expected_exception_message):
         obj[0] = some_invalid_value_that_doesnt_raise_now_but_does_with_your_bugfix
```

2022-01-17 13:45 UTC, closed without merging