BUG: setitem into td64/dt64 series/frame with Categorical[strings]
pandas-dev/pandas pull request #44236
Opened 2021-10-30 02:05 UTC by jbrockmendel

- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

2021-10-30 14:12 UTC, jreback requested changes

2021-10-30 14:12 UTC, jreback commented on pandas/core/arrays/datetimelike.py
> +    return dtype == "string"
what hits here, other EAs? but not numpy types e.g. `np.str` would be above, right?

maybe a comment to this effect

2021-10-30 14:12 UTC, jreback commented on pandas/core/arrays/datetimelike.py
> +        return (
shoudn't this be in core.dtypes.common?

2021-10-30 14:12 UTC, jreback commented
this a user facing bug?

2021-10-31 16:22 UTC, jbrockmendel commented
> this a user facing bug?

yes, updated with whatsnew

2021-11-01 13:55 UTC, jreback commented on pandas/core/dtypes/common.py
> +def is_all_strings(value: ArrayLike) -> bool:
wouldn't hurt to add some unit tests for this when you have a chance :->

2021-11-01 13:55 UTC, jreback approved these changes

2021-11-01 13:55 UTC, merged