TST: Old issues
pandas-dev/pandas pull request #44245
Opened 2021-10-31 03:29 UTC by mroeschke

- [x] closes #16380
- [x] closes #14135
- [x] closes #16577
- [x] closes #16925
- [x] closes #17093
- [x] closes #17382
- [x] closes #18050
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them

2021-10-31 14:49 UTC, jreback requested changes

2021-10-31 14:49 UTC, jreback commented on pandas/tests/groupby/test_groupby.py
> +def test_mean_on_timedelta():
put this in a different file, maybe test_function.py

2021-10-31 20:59 UTC, jbrockmendel commented
CI failure looks unrelated

2021-11-01 13:14 UTC, jreback approved these changes

2021-11-01 13:14 UTC, merged

2021-11-01 13:14 UTC, jreback commented
thanks @mroeschke