BUG: Period.__eq__ numpy scalar (#44182 (comment))
pandas-dev/pandas pull request #44285
Opened 2021-11-02 07:47 UTC by mathause

- [x] fixes https://github.com/pandas-dev/pandas/pull/44182#issuecomment-956851322
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

2021-11-02 07:53 UTC, mathause commented
I added three tests but only one of them fails without the code change.

Fixed by the code update:
```python
Period("2000-01", "M") == np.array(0)
```

Additional tests not affected by the code update:
```python
idx = period_range("2007-01", periods=20, freq="M")
idx == np.array(idx[10])

Period("2000-01", "M") == np.int_(0)
```

2021-11-02 10:14 UTC, jreback requested changes

2021-11-02 10:14 UTC, jreback commented on pandas/_libs/tslibs/period.pyx
> +        elif util.is_array(other) and not np.ndim(other) == 0:
np.ndim(..) > 0

2021-11-02 11:27 UTC, mathause commented
This used to return `True`, so I think we are not yet entirely there:

```python
p = pd.Period("2000-01", "M")
p == np.array(p)
```

2021-11-02 18:19 UTC, jbrockmendel commented on pandas/_libs/tslibs/period.pyx
> +            if np.ndim(other) > 0:
cnp.PyArray_IsZeroDim(other)

2021-11-02 18:19 UTC, jbrockmendel commented on pandas/_libs/tslibs/period.pyx
> +            if np.ndim(other) > 0:
`# GH#44285`

2021-11-02 18:21 UTC, jbrockmendel commented on pandas/tests/scalar/period/test_period.py
> +        for left, right in ((p, scalar), (scalar, p)):
the loop here is unnecessary; its two lines either way and clearer without

2021-11-02 18:22 UTC, jbrockmendel commented on pandas/tests/scalar/period/test_period.py
> +    def test_comparison_numpy_scalar(self, scalar, expected):
scalars are already tested; its zerodim we need to catch.  in particular a zero-dim ndarray containing a Period object

2021-11-03 23:55 UTC, jbrockmendel approved these changes
LGTM cc @jreback

2021-11-04 00:43 UTC, jreback approved these changes

2021-11-04 00:43 UTC, merged

2021-11-04 00:43 UTC, jreback commented
thanks @mathause