ENH: add suffixes argument to compare
pandas-dev/pandas pull request #44365
Opened 2021-11-09 07:06 UTC by erfannariman

- [x] closes #44354 
- [ ] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

2021-11-14 02:30 UTC, jreback requested changes

2021-11-14 02:30 UTC, jreback commented on pandas/tests/frame/methods/test_compare.py
> +    result_suffixes = comp.columns.get_level_values(1).unique()
can you use tm.assert_frame_equal here to assert the results

2021-11-14 02:30 UTC, jreback commented on pandas/core/generic.py
> +        diff = concat([self, other], axis=axis, keys=suffixes)
these must be a tuple and non-None right? can you add a check and tests the cases (e.g. this is similar to what we checkin merge for example)

2021-11-14 02:30 UTC, jreback commented on pandas/core/frame.py
> +        suffixes: Suffixes = ("self", "other"),
pls update doc string & add a versionadded.

if we have this in the docs anywhere else (i don't think so but pls check), maybe needs updating

2021-11-14 02:30 UTC, jreback requested changes
also add a note in other enhancements section for 1.4

2021-11-25 15:10 UTC, jreback requested changes

2021-11-25 15:10 UTC, jreback commented on pandas/core/frame.py
> +        suffixes: Suffixes = ("self", "other"),
can you update the doc-string, needs a versionadded 1.4. tag

2022-02-06 22:51 UTC, mroeschke commented
Thanks for the pull request, but this pull request appears to have gone stale. If interested in continuing, please merge in main and address the comments and this PR can be reopened. Closing in the meantime

2022-02-06 22:51 UTC, closed without merging