WARN: Add FutureWarning for `DataFrame.to_latex`
pandas-dev/pandas pull request #44411
Opened 2021-11-12 17:25 UTC by attack68

Instead of xxx, which performs a refactor and adds the warning in the same PR, I am proposing adding the warning only for 1.4.0 and then in 2.0 there will be scope to make breaking changes and refactor the arguments signature.

2021-11-13 17:11 UTC, jreback requested changes

2021-11-13 17:11 UTC, jreback commented on pandas/core/generic.py
> +        warnings.warn(msg, FutureWarning, stacklevel=2)
use `find_stack_level` here

2021-11-20 21:16 UTC, jreback approved these changes

2021-11-20 21:17 UTC, jreback commented
looks fine can you add a whatsnew note in the deprecation section to message this. ping on green.

2021-11-21 23:37 UTC, jreback commented on doc/source/whatsnew/v1.4.0.rst
> +- A deprecation warning is now shown for :meth:`DataFrame.to_html` indicating the arguments signature may change and emulate more the arguments to :meth:`.Styler.to_html` in future versions (:issue:`
hmm this should be for to_latex :->

2021-11-24 06:19 UTC, merged

2022-11-18 20:04 UTC, mroeschke commented
@attack68 do you have bandwidth/appetite to align DataFrame.to_latex and Styler.to_latex since 2.0 will be the next version?

2022-11-18 22:08 UTC, attack68 commented
see https://github.com/pandas-dev/pandas/pull/47970#issuecomment-1320579957