Assign err2
pandas-dev/pandas pull request #44664
Opened 2021-11-29 03:50 UTC by nickleus27

xref #37715

My apologies, I pushed hastily on my previous branch assign_err and did not check the diff of the files i was pushing. I accidentally pulled when i should have merged and I pushed a bunch of other peoples commits.  These are my previous changes.

2021-11-29 05:00 UTC, jreback commented
umm what are these in reference to?

2021-11-29 05:04 UTC, nickleus27 commented
@jreback #44373

2021-12-01 01:01 UTC, jreback requested changes

2021-12-01 01:01 UTC, jreback commented on pandas/core/dtypes/dtypes.py
> +            combined_hashed = combine_hash_arrays(
umm can you avoid repeating the code here on L 469

2021-12-03 00:14 UTC, jreback approved these changes

2021-12-03 00:15 UTC, merged

2021-12-03 00:15 UTC, jreback commented
thanks @nickleus27