BUG: Raise TypeError for scalar indexer in take
pandas-dev/pandas pull request #44763
Opened 2021-12-05 01:27 UTC by gfkang

- [x] closes #42875
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

2021-12-05 11:11 UTC, phofl requested changes
Couple of comments. Also please add whatsnew

2021-12-05 11:11 UTC, phofl commented on pandas/core/indexes/base.py
> +            raise TypeError("Expected indices to be array-like")
Please use is_scalar from pandas.

2021-12-05 11:11 UTC, phofl commented on pandas/tests/indexes/test_indexing.py
> +        integer_index = Int64Index([0, 1, 2, 3])
I think this index constructor is deprecated, please use Index(

2021-12-05 11:11 UTC, phofl commented on pandas/tests/indexes/test_indexing.py
> +    def test_take_indexer_type(self):
Please add issue number

2021-12-10 15:59 UTC, phofl approved these changes

2021-12-10 15:59 UTC, phofl commented
Could you rebase master? We had a few ci failures

2021-12-10 21:07 UTC, mroeschke approved these changes

2021-12-10 21:08 UTC, merged

2021-12-10 21:08 UTC, mroeschke commented
Thanks @gfkang