BUG: IntervalArray.__cmp__(pd.NA)
pandas-dev/pandas pull request #44830
Opened 2021-12-09 21:17 UTC by jbrockmendel

- [x] closes #31882
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

Could repurpose #31882 to be about the more general case and not just IntervalArray?

DataFrame cases fail in a way that would be avoided with 2D EAs.

2021-12-09 23:52 UTC, jreback requested changes

2021-12-09 23:52 UTC, jreback commented on pandas/_testing/__init__.py
> +        return pd.core.arrays.IntervalArray(obj)
can you use is_interval_dtype to be consistent

2021-12-09 23:54 UTC, jbrockmendel commented
Perf! Have another branch that will move them all to the faster version

On Thu, Dec 9, 2021 at 3:52 PM Jeff Reback ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In pandas/_testing/__init__.py
> <https://github.com/pandas-dev/pandas/pull/44830#discussion_r766237941>:
>
> > @@ -282,6 +283,10 @@ def to_array(obj):
>          return DatetimeArray._from_sequence(obj)
>      elif is_timedelta64_dtype(dtype):
>          return TimedeltaArray._from_sequence(obj)
> +    elif isinstance(obj, pd.core.arrays.BooleanArray):
> +        return obj
> +    elif isinstance(dtype, IntervalDtype):
> +        return pd.core.arrays.IntervalArray(obj)
>
> can you use is_interval_dtype to be consistent
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/44830#pullrequestreview-828309450>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB5UM6HGLKEGVOJT24XOAJTUQE6LRANCNFSM5JXPZ4BA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-11 01:22 UTC, jreback approved these changes

2021-12-11 01:22 UTC, merged

2021-12-11 01:22 UTC, jreback commented
if you can add a whatsnew in followon