Added example for num and bool to pandas.Series.str.strip
pandas-dev/pandas pull request #44885
Opened 2021-12-14 20:43 UTC by R3dIO

- [x] closes #44867
- [ ] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

2021-12-15 11:00 UTC, phofl requested changes
The doctests are failing. Could you have a look which one of your changes is causing this?

2021-12-15 11:00 UTC, phofl commented on pandas/core/strings/accessor.py
> +    s = pd.Series(['hello ', ' goodbye', 1.0, 0.0, 1, 0, True, False, np.nan])
Could you use other numbers int(True) is 1 and int(False) is 0

2021-12-16 22:48 UTC, R3dIO commented
Sure I'll have a look

2021-12-17 22:42 UTC, jreback requested changes

2021-12-17 22:42 UTC, jreback commented on pandas/core/strings/accessor.py
> +    Series.str.strip : Remove leading and trailing characters in Series/Index,
i wouldn't add any of this, instead you can add in a Notes section a line.

2022-01-04 03:47 UTC, Anunaya07 commented
Hello I am first time contributor. Is this issue still open can I work on it?

2022-01-04 11:28 UTC, phofl commented
@R3dIO  are you interested in continuing?

2022-01-04 11:36 UTC, R3dIO commented
Sure, let me know how can I help?

2022-01-04 11:37 UTC, R3dIO commented
I'll review my PR and fix the changed soon

2022-01-04 11:41 UTC, Anunaya07 commented
Can I also try too?

2022-01-04 11:44 UTC, phofl commented
Please search for another issue labeled as good first issue. We try to keep ownership, so please don’t Open another pr if someone has already started working on it

2022-01-04 11:45 UTC, Anunaya07 commented
OK. Thank you.

2022-02-06 22:53 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. Please merge in main and address the above comments and we can reopen this PR. Closing.

2022-02-06 22:53 UTC, closed without merging