DOC: update documentation of type annotation (PEP 585)
pandas-dev/pandas pull request #44948
Opened 2021-12-17 20:12 UTC by twoertwein

2021-12-17 22:17 UTC, jreback requested changes
small comment

2021-12-17 22:17 UTC, jreback commented on doc/source/development/contributing_codebase.rst
> +   maybe_primes: list[Union[int, None]] = []
can use `|` ?

2021-12-17 22:18 UTC, jreback commented
pre commit failing

2021-12-17 22:54 UTC, twoertwein commented on doc/source/development/contributing_codebase.rst
> +   maybe_primes: list[Union[int, None]] = []
These are two negative examples followed by one positive example.

2021-12-17 22:54 UTC, twoertwein commented
Without the CSS:
![image](https://user-images.githubusercontent.com/6618166/146617012-a67d98de-2419-4608-ba7c-e36d608e5ebb.png)

2021-12-19 22:38 UTC, jreback approved these changes

2021-12-19 22:38 UTC, merged