CI: Avoid flaky hypothesis test with deadline=None
pandas-dev/pandas pull request #44969
Opened 2021-12-19 02:15 UTC by mroeschke

xref https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=70928&view=logs&jobId=9dd5e044-6afa-5be6-cb56-860f1ee82b31&j=9dd5e044-6afa-5be6-cb56-860f1ee82b31&t=d3ae057b-d0af-59ce-6e4c-b69ef3739701

2021-12-19 22:54 UTC, jreback requested changes

2021-12-19 22:54 UTC, jreback commented on pandas/tests/frame/indexing/test_where.py
> +@settings(deadline=None)  # GH 44969
can you move the hypothesis setup to the  pandas/_testing/_hypothesis.py instead (and make this change)

2021-12-19 23:08 UTC, jreback approved these changes

2021-12-19 23:08 UTC, jreback commented
great, merge on green

2021-12-20 01:44 UTC, merged

2021-12-20 01:44 UTC, mroeschke commented
Failure due to stalled build