DOC: to_hdf() method docstring updated with dropna and index
pandas-dev/pandas pull request #45039
Opened 2021-12-24 02:25 UTC by fanoway

Resolves GitHub Issue #45030

- [x] closes #45030 
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

2021-12-24 03:04 UTC, fanoway commented
@github-actions pre-commit

2021-12-24 04:05 UTC, fanoway commented
@github-actions pre-commit

2021-12-24 11:17 UTC, phofl commented
Hey, thx for tackling this. I think there are a few places where this might be missing too. Should have mentioned in the issue

HDFStore.append and HDFStore.put are candidates.

2021-12-24 23:25 UTC, fanoway commented
> Hey, thx for tackling this. I think there are a few places where this might be missing too. Should have mentioned in the issue
> 
> HDFStore.append and HDFStore.put are candidates.

Cheers, I'm getting a couple of failing checks in the github actions, not entirely sure hwat is going on as I only updated docstrings. Can you lend me some adivce cheers?

2021-12-24 23:54 UTC, phofl commented
They are unrelated

2021-12-26 04:45 UTC, pep8speaks commented
Hello @fanoway! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/io/pytables.py`](https://github.com/pandas-dev/pandas/blob/78b6e06de4a80747712bc44338f9e98d9507d634/pandas/io/pytables.py):

> [Line 1110:89](https://github.com/pandas-dev/pandas/blob/78b6e06de4a80747712bc44338f9e98d9507d634/pandas/io/pytables.py#L1110): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 88 characters)
> [Line 1258:89](https://github.com/pandas-dev/pandas/blob/78b6e06de4a80747712bc44338f9e98d9507d634/pandas/io/pytables.py#L1258): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 88 characters)

2021-12-26 04:45 UTC, fanoway commented
> 

Ok cheers. I fixed all the doc strings for the HDFStoe.put() and HDFStore.append() as they were missing quite a few parameters

2021-12-26 14:28 UTC, fanoway commented
@github-actions pre-commit

2021-12-27 14:47 UTC, jreback requested changes
precommit is failing

2021-12-27 14:47 UTC, jreback commented on pandas/io/pytables.py
> +        axes         : Optional, specify rows or columns
don't add extra whitespace here (before the :)

2021-12-29 11:59 UTC, phofl commented
@fanoway you can install pre-commit locally which will check a few styling things

2022-01-31 20:10 UTC, stdcout42 commented on pandas/io/pytables.py
> +            pecifies the compression library to be used.
Typo 'specifies'

2022-02-14 15:44 UTC, phofl commented
@fanoway Are you interested in continuing?

2022-02-22 05:23 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing please merge in main, address the comments and we can reopen

2022-02-22 05:23 UTC, closed without merging