Adding a test case for the issue 28570
pandas-dev/pandas pull request #45075
Opened 2021-12-26 23:56 UTC by aliraeisdanaei

- [x] closes #28570
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry
a unit test was added in accordance with issue [28570] (https://github.com/pandas-dev/pandas/issues/28570). It asserts the equality of the expected output with the tested df.

2021-12-26 23:57 UTC, pep8speaks commented
Hello @aliraeisdanaei! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/groupby/aggregate/test_aggregate.py`](https://github.com/pandas-dev/pandas/blob/67dd1fa05601f01522757d9a132a8810e76f992d/pandas/tests/groupby/aggregate/test_aggregate.py):

> [Line 78:71](https://github.com/pandas-dev/pandas/blob/67dd1fa05601f01522757d9a132a8810e76f992d/pandas/tests/groupby/aggregate/test_aggregate.py#L78): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 78:73](https://github.com/pandas-dev/pandas/blob/67dd1fa05601f01522757d9a132a8810e76f992d/pandas/tests/groupby/aggregate/test_aggregate.py#L78): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 78:75](https://github.com/pandas-dev/pandas/blob/67dd1fa05601f01522757d9a132a8810e76f992d/pandas/tests/groupby/aggregate/test_aggregate.py#L78): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 78:77](https://github.com/pandas-dev/pandas/blob/67dd1fa05601f01522757d9a132a8810e76f992d/pandas/tests/groupby/aggregate/test_aggregate.py#L78): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2021-12-26 23:58 UTC, aliraeisdanaei commented
Hey, this is my first pull request to pandas, so please do tell me if I have made any mistakes. 

Thank you & God bless,
Ali Raeisdanaei

2021-12-27 00:04 UTC, jbrockmendel commented on pandas/tests/groupby/aggregate/test_aggregate.py
> +    test = pd.DataFrame({'col1': ['a', 'a', 'b', 'b', 'b'], 'col2': [1,2,3,4,5]})
see the doc on code_style; running `black` should take care of this

2021-12-27 00:04 UTC, jbrockmendel commented on pandas/tests/groupby/aggregate/test_aggregate.py
> +    # print(test)
please remove commented-out

2021-12-27 00:05 UTC, jbrockmendel commented on pandas/tests/groupby/aggregate/test_aggregate.py
> +    assert(test.equals(expected_df))
use tm.assert_frame_equal(test, expected_df)

2021-12-27 00:11 UTC, aliraeisdanaei commented
@jbrockmendel Thanks for the feedback.

2021-12-27 01:06 UTC, mroeschke commented on pandas/tests/groupby/aggregate/test_aggregate.py
> +    def add_top_column(df, top_col, inplace=False):
Looks like this function is only used once. Could you in-line the logic directly in the test?

2021-12-27 03:55 UTC, mroeschke commented on pandas/tests/groupby/aggregate/test_aggregate.py
> +    def add_top_column(df, top_col, inplace=False):
Rather, this _entire function_ is only used once so all the logic can be in-lined.

2021-12-27 14:11 UTC, jreback requested changes

2021-12-27 14:11 UTC, jreback commented on pandas/tests/groupby/aggregate/test_aggregate.py
> +    expected_df = add_top_column(expected_df, "col2")
can you just inline the add_top_column, as a function just obfuscates the purpose

2021-12-27 14:11 UTC, jreback commented on pandas/tests/groupby/aggregate/test_aggregate.py
> +    test = pd.DataFrame({"col1": ["a", "a", "b", "b", "b"], "col2": [1, 2, 3, 4, 5]})
call this df

2021-12-27 14:11 UTC, jreback commented on pandas/tests/groupby/aggregate/test_aggregate.py
> +    test = test.groupby("col1").agg({"col2": [quant50, quant70]})
call this result

2021-12-27 14:11 UTC, jreback commented on pandas/tests/groupby/aggregate/test_aggregate.py
> +    expected_df = pd.DataFrame(
just call this expected

2022-01-09 17:55 UTC, jbrockmendel commented on pandas/tests/groupby/aggregate/test_aggregate.py
> +    # for issue 28570
nitpick: can you write this `GH#28570`?  makes it easier to grep for issue numbers

2022-02-05 21:00 UTC, rhshadrach requested changes
I don't think this closes the issue, see https://github.com/pandas-dev/pandas/issues/28570#issuecomment-1030697905 for details.

2022-03-06 01:33 UTC, mroeschke commented
Thanks for the PR, but it appears to have gone stale. If you'd like to continue and investigate the bug fix, please ping and we can reopen.

2022-03-06 01:33 UTC, closed without merging