BUG: head and tail not dropping groups with nan
pandas-dev/pandas pull request #45102
Opened 2021-12-28 23:55 UTC by phofl

- [x] closes #45089
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

We could also create a specific function for this.

Also that nth respects ``as_index`` while it is ignored by ``head`` and ``tail`` looks inconsistent

2021-12-29 18:24 UTC, jreback requested changes

2021-12-29 18:24 UTC, jreback commented on doc/source/whatsnew/v1.4.0.rst
> +- Bug in :meth:`GroupBy.head` and :meth:`GroupBy.tail` no dropping groups with ``NaN`` when ``dropna=True`` (:issue:`45089`)
no -> not

2021-12-29 18:24 UTC, jreback commented on pandas/tests/groupby/test_nth.py
> +
can you test nth here as well

2021-12-29 18:24 UTC, jreback commented
> We could also create a specific function for this.

what does this mean

2021-12-29 18:26 UTC, phofl commented
Adjusting the mask for the dropna flag in a dedicated function, because the place I put this is a bit awkward

2021-12-29 21:02 UTC, phofl commented on doc/source/whatsnew/v1.4.0.rst
> +- Bug in :meth:`GroupBy.head` and :meth:`GroupBy.tail` no dropping groups with ``NaN`` when ``dropna=True`` (:issue:`45089`)
Thx

2021-12-29 21:02 UTC, phofl commented on pandas/tests/groupby/test_nth.py
> +
Done

2021-12-30 00:01 UTC, jreback approved these changes

2021-12-30 00:01 UTC, merged