BUG: allow use of both default+input resolvers in df.eval, GH34966
pandas-dev/pandas pull request #45134
Opened 2021-12-30 22:06 UTC by bubblingoak

- [ ] closes #34966
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

Allows default resolvers to be used with input resolvers in `pandas.dataframe.eval`. Previously cases such as this would break:
```python
import pandas as pd

df = pd.DataFrame({'a':[0,1,2], 'b':[7,8,9]}) 
d = {'c': 5}
df.eval('a+b*c', resolvers=[d])
```
with `pandas.core.computation.ops.UndefinedVariableError: name 'a' is not defined` as explained in #34966. Following this update, the above works as expected.

2021-12-30 22:09 UTC, jreback requested changes
umm can you add a test which fails w/o this change

2021-12-30 22:46 UTC, pep8speaks commented
Hello @bubblingoak! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/frame/test_query_eval.py`](https://github.com/pandas-dev/pandas/blob/d8d1496c6a9266e909e3d50a4b98a9924a72da18/pandas/tests/frame/test_query_eval.py):

> [Line 167:1](https://github.com/pandas-dev/pandas/blob/d8d1496c6a9266e909e3d50a4b98a9924a72da18/pandas/tests/frame/test_query_eval.py#L167): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 170:42](https://github.com/pandas-dev/pandas/blob/d8d1496c6a9266e909e3d50a4b98a9924a72da18/pandas/tests/frame/test_query_eval.py#L170): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 172:1](https://github.com/pandas-dev/pandas/blob/d8d1496c6a9266e909e3d50a4b98a9924a72da18/pandas/tests/frame/test_query_eval.py#L172): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 174:48](https://github.com/pandas-dev/pandas/blob/d8d1496c6a9266e909e3d50a4b98a9924a72da18/pandas/tests/frame/test_query_eval.py#L174): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 174:50](https://github.com/pandas-dev/pandas/blob/d8d1496c6a9266e909e3d50a4b98a9924a72da18/pandas/tests/frame/test_query_eval.py#L174): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 175:1](https://github.com/pandas-dev/pandas/blob/d8d1496c6a9266e909e3d50a4b98a9924a72da18/pandas/tests/frame/test_query_eval.py#L175): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2021-12-30 23:03 UTC, bubblingoak commented
> umm can you add a test which fails w/o this change

Added the test `tests.frame.test_query_eval.TestDataFrameEval.test_eval_resolvers_combined`. The updated code passes, but current master fails on [line 174](https://github.com/bubblingoak/pandas/blob/fix-df-eval-resolvers/pandas/tests/frame/test_query_eval.py#L174): 
```python
result = df.eval("a + b * c", resolvers=[dict1])
```
with `pandas.core.computation.ops.UndefinedVariableError: name 'a' is not defined`

2021-12-31 15:53 UTC, jreback requested changes
small commment, ping on green

2021-12-31 15:53 UTC, jreback commented on doc/source/whatsnew/v1.4.0.rst
> +- Bug in :meth:`DataFrame.eval` where ``resolvers`` argument was overriding the default resolvers
can you add the issue number here

2022-01-03 23:31 UTC, bubblingoak commented on doc/source/whatsnew/v1.4.0.rst
> +- Bug in :meth:`DataFrame.eval` where ``resolvers`` argument was overriding the default resolvers
Updated now to add the issue number

2022-01-03 23:34 UTC, jreback approved these changes

2022-01-04 14:15 UTC, merged

2022-01-04 14:15 UTC, jreback commented
thanks @bubblingoak