REF: separate numpy-specific part of can_hold_element
pandas-dev/pandas pull request #45166
Opened 2022-01-02 22:36 UTC by jbrockmendel

By returning the value instead of just a bool, we open the option to return the _casted_ value, which is what we'll do in the follow-up, which will let us de-duplicate NumericIndex._validate_fill_value.  By separating out the np-specific parts, we'll be able to improve perf in a couple of places.

2022-01-03 21:36 UTC, jreback requested changes
would it be better to use `None` as the return value rathe than using exceptions as control flow ? (e.g. performance)

2022-01-03 21:36 UTC, jreback commented on pandas/core/dtypes/cast.py
> +def np_can_hold_element(dtype: np.dtype, element: Any):
can you add a return Any

2022-01-03 21:36 UTC, jreback commented on pandas/core/dtypes/cast.py
> +
add a Returns section

2022-01-03 22:13 UTC, jbrockmendel commented
> would it be better to use None as the return value rathe than using exceptions as control flow ? (e.g. performance)

That becomes ambiguous with if the actual element is None.

There _are_ some performance concerns i have with this function, but try/except overhead is not among them.

2022-01-03 22:49 UTC, jreback commented
> There are some performance concerns i have with this function, but try/except overhead is not among them.

oh ok.

2022-01-04 14:16 UTC, jreback approved these changes

2022-01-04 14:16 UTC, merged