allow multiple series argument calling in ufunc
pandas-dev/pandas pull request #45171
Opened 2022-01-03 07:04 UTC by miettal

- [ ] closes #39853
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

2022-01-03 07:04 UTC, pep8speaks commented
Hello @miettal! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/arraylike.py`](https://github.com/pandas-dev/pandas/blob/bedb58a11636dc08a2d122583d16f244477f52fd/pandas/core/arraylike.py):

> [Line 300:89](https://github.com/pandas-dev/pandas/blob/bedb58a11636dc08a2d122583d16f244477f52fd/pandas/core/arraylike.py#L300): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (106 > 88 characters)

2022-01-03 16:55 UTC, jbrockmendel commented
can you add a test for the bug(s) this fixes

2022-01-03 22:41 UTC, jreback requested changes
yep pls always add a test. also if this does fix things pls add a whatsnew note in bug fixes 1.4, reshape section is fine

2022-02-13 00:44 UTC, mroeschke commented
Thanks for the pull request, but appears this PR is stale and broke some tests. If you'd like to continue please merge master, include a unit test, and verify the fix locally with the entire test suite, and we can reopen.

2022-02-13 00:44 UTC, closed without merging