TST: Create test for #30122 about display.precision
pandas-dev/pandas pull request #45185
Opened 2022-01-04 01:55 UTC by dhruvsamdani

- [x] closes #30122 
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

2022-01-04 14:56 UTC, jreback requested changes

2022-01-04 14:56 UTC, jreback commented on pandas/tests/io/formats/test_format.py
> +            assert str(df) == str(DataFrame(value).round(1))
instead of this can you hard code the expected result (in the parameterization) and check it

2022-01-04 21:51 UTC, mroeschke commented on pandas/tests/io/formats/test_format.py
> +            ([9.5444, 9.6], [10, 10]),
The str result of `DataFrame(value)` should be hardcoded here as `expected` instead

2022-01-06 19:40 UTC, mroeschke reviewed
Could you merge master another time? Otherwise LGTM

2022-01-07 03:23 UTC, dhruvsamdani commented
I have merged master and pushed the code again.

2022-01-07 03:26 UTC, mroeschke approved these changes

2022-01-08 15:32 UTC, jreback approved these changes

2022-01-08 15:32 UTC, merged

2022-01-08 15:32 UTC, jreback commented
thanks @dhruvsamdani