BUG: Fix lost precision when reading from Oracle Number column GH34988
pandas-dev/pandas pull request #45221
Opened 2022-01-06 13:38 UTC by andrewkisel

Fixes: https://github.com/pandas-dev/pandas/issues/34988

- [x] closes #34988
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

2022-01-07 10:57 UTC, phofl reviewed
Can we create a test for this?

2022-01-07 10:57 UTC, phofl commented on pandas/io/sql.py
>          if isinstance(sqltype, Float):
You could potentially move that into this isinstance check

2022-01-08 15:31 UTC, jreback requested changes
pls add a test which covers this

2022-02-13 00:46 UTC, mroeschke commented
Thanks for the pull request, but appears it has gone stale. If you'd like to continue, please address the review, move the whatsnew note to v.1.5 and we can reopen

2022-02-13 00:46 UTC, closed without merging