DOC: improving example
pandas-dev/pandas pull request #45262
Opened 2022-01-08 14:34 UTC by realead

- [x] closes #45222

This is a minimal fix: the example with strange output is replaced (even if the underlying problem is not fixed/should be fixed)

Now the output in the current version is:

```
Index([None, NaT, True], dtype='object')
```

2022-01-08 15:54 UTC, jreback requested changes
I think we actually need to fix this for 1.4 (the actual issue which i think is just the repr), e.g. these are *already* separate things IIUC

2022-01-09 07:05 UTC, realead commented
@jreback I've proposed a fix for repr-issue in #45283. Not sure it is good to make such a change  shortly before release (and thus this much more minimal PR) also probably some discussion needed  what is actually the desired and consistent behavior (probably not only series are affected).

2022-01-10 13:32 UTC, jreback commented
closing in favor of #45283

2022-01-10 13:32 UTC, closed without merging

2022-01-10 13:32 UTC, jreback commented
> @jreback I've proposed a fix for repr-issue in #45283. Not sure it is good to make such a change shortly before release (and thus this much more minimal PR) also probably some discussion needed what is actually the desired and consistent behavior (probably not only series are affected).

yeah i think your change is fine