BUG: BooleanArray+pd.NA altering array inplace
pandas-dev/pandas pull request #45421
Opened 2022-01-17 17:34 UTC by jbrockmendel

- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

2022-01-18 15:58 UTC, jorisvandenbossche requested changes

2022-01-18 17:46 UTC, jbrockmendel commented on pandas/tests/arrays/boolean/test_arithmetic.py
> +def test_boolean_array_add_pdna():
good idea, updated

2022-01-19 07:49 UTC, jorisvandenbossche approved these changes

2022-01-19 07:49 UTC, merged

2022-01-19 07:49 UTC, jorisvandenbossche commented
Thanks!