Regression: Loc raising when indexing mi with one level
pandas-dev/pandas pull request #45785
Opened 2022-02-02 21:51 UTC by phofl

- [x] closes #45779 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

@jbrockmendel You moved the error catching logic out of maybe_mi_droplevels. Is this necessary for one of the other code paths?

2022-02-03 02:01 UTC, jreback requested changes

2022-02-03 02:01 UTC, jreback commented on pandas/core/indexes/multi.py
> +                result_index = maybe_mi_droplevels(indexer, [level])
oh i c @jbrockmendel moved this. can you document this in the doc-string of maybe_mi_droplevels? (and prob should just move maybe_mi_droplevels) top a non-nested function (ok with these being a followup on main as well).

2022-02-06 20:20 UTC, phofl commented on pandas/core/indexes/multi.py
> +                result_index = maybe_mi_droplevels(indexer, [level])
Added a note. Would like to move in a separate pr to not backport this

2022-02-09 00:25 UTC, jreback commented on pandas/core/indexes/multi.py
> +                result_index = maybe_mi_droplevels(indexer, [level])
great, yeah ideally clean in 1.5

2022-02-09 00:25 UTC, jreback approved these changes

2022-02-09 00:25 UTC, merged

2022-02-09 00:25 UTC, jreback commented
@meeseeksdev backport 1.4.x

2022-02-09 01:28 UTC, jreback commented
@phofl if you wouldn't mind push a backport PR

2022-02-14 10:22 UTC, phofl commented
Thx for the backport @simonjayhawkins