Enable server side cursors
pandas-dev/pandas pull request #46166
Opened 2022-02-27 06:48 UTC by J0

The old PR went stale and I ended up busy for a year so had to re-open in a new branch. Hoping to finally push this through

This pull request attempts to fix #35689.  I read an article by @itamarst and decided to look further into the codebase. After noticing that the fix semed to be simple I decided file a PR. The fix is naive and I'm not sure the true solution is as simple as I imagine it to be. There are probably many things I'm missing as I've not read the codebase in detail so do let me know what else needs to be addressed.

- [x] closes #35689
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry(N.A.)

2022-02-27 20:15 UTC, jreback requested changes
is this exercised in *any* current tests? 

does the doc-string need updating here?

2022-02-27 20:15 UTC, jreback commented on pandas/io/sql.py
> +    def execute(self, chunksize: int = 0, *args, **kwargs):
can you add a return type

2022-03-01 02:36 UTC, J0 commented on pandas/io/sql.py
> +    def execute(self, chunksize: int = 0, *args, **kwargs):
Will do!

2022-04-01 12:53 UTC, pep8speaks commented
Hello @J0! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/io/sql.py`](https://github.com/pandas-dev/pandas/blob/1d0a412049ba3b3f944b5f1f1cfc4610b7924186/pandas/io/sql.py):

> [Line 1394:1](https://github.com/pandas-dev/pandas/blob/1d0a412049ba3b3f944b5f1f1cfc4610b7924186/pandas/io/sql.py#L1394): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2022-04-24 02:56 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge the main branch, address the review comments, and we can reopen.

2022-04-24 02:56 UTC, closed without merging

2023-08-03 17:11 UTC, gregorywaynepower commented
@J0 Is this still being worked on?