DOC: Clarify groupby.first does not use nulls
pandas-dev/pandas pull request #46195
Opened 2022-03-01 22:08 UTC by NumberPiOso

- [X] closes  #8427
- [X] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

2022-03-02 01:19 UTC, jreback commented
great. can you also update `.last()`?

2022-03-04 22:26 UTC, NumberPiOso commented
Nowadays, when I run the same .first() example I get the following error. Do you know the reason? I will still commit what I would think would be the change for .last()

```python
In [4]: df = pd.DataFrame(dict(A=[1, 1, 3], B=[None, 5, 6], C=[1, 2, 3]))

In [5]: df.groupby("A").first()
<ipython-input-5-b69697f6536c>:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.first is deprecated. In a future version, a TypeError will be raised. Before calling .first, select only columns which should be valid for the function.
  df.groupby("A").first()
Out[5]: 
Empty DataFrame
Columns: []
Index: [1, 3]
```

2022-03-05 15:14 UTC, rhshadrach requested changes
Small request, otherwise looks great.

2022-03-05 15:14 UTC, rhshadrach commented on pandas/core/groupby/groupby.py
> +            First not non-null of values within each group.
Just "First non-null"

2022-03-05 15:14 UTC, rhshadrach commented on pandas/core/groupby/groupby.py
> +            Last not non-null of values within each group.
Ditto.

2022-03-06 20:20 UTC, rhshadrach requested changes

2022-03-06 20:20 UTC, rhshadrach commented on pandas/core/groupby/groupby.py
> +
Need to remove this blank line - causes docstring validation to fail.

2022-03-10 21:52 UTC, rhshadrach approved these changes
lgtm

2022-03-10 21:54 UTC, merged

2022-03-10 21:55 UTC, rhshadrach commented
Thanks @NumberPiOso!