Adding overwrite or ignore behavior for row conflicts.
pandas-dev/pandas pull request #46232
Opened 2022-03-04 21:26 UTC by LSturtew

@cvonsteg started the effort to implement this. Since they are unable to continue and this is a highly desired feature, I made an attempt to clean up the code and fix merge conflicts. I would like to share the credit for this PR (I do not know how this works).

A new parameter is added to `to_sql`: `on_row_conflct`

    on_row_conflict : {'fail', 'overwrite', 'append'},
        default: 'fail'
        Determine insertion behavior in case of a primary key clash.
        - 'fail': Do nothing to handle primary key clashes, will raise an Error.
        - 'overwrite': Update existing rows in database with primary key clashes,
          and append the remaining rows with non-conflicting primary keys
        - 'append': Ignore incoming rows with primary key clashes, and
          insert only the incoming rows with non-conflicting primary keys

- [x] closes #14553, continuation of #29636
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2022-03-05 17:17 UTC, jreback requested changes
i started reviewing, but this again is adding an enormous amount of complexity. can you get sqlalchemy to do this type of operation directly?

2022-03-05 17:17 UTC, jreback commented on pandas/core/generic.py
> +        default 'fail'
why are you u using row-continuation here? just leave it

can consider deprecating this and change the name to `if_table_exists` to be more obvious (but orthogonal)

2022-03-05 17:17 UTC, jreback commented on pandas/core/generic.py
> +            * overwrite: Overwrite the row with the incoming data.
use 'replace' not overwrite

2022-03-05 17:17 UTC, jreback commented on pandas/io/sql.py
> +        default 'fail'.
try not to change things not-related it makes the diff that much bigger

2022-03-05 17:17 UTC, jreback commented on pandas/core/generic.py
> +        default 'fail'
needs a versionadded 1.5.0

2022-03-05 17:17 UTC, jreback commented on pandas/io/sql.py
> +        raise ValueError(f"'{on_row_conflict}' is not valid for on_row_conflict'")
is there a test for this?

2022-03-05 17:17 UTC, jreback commented on pandas/io/sql.py
> +    # on_row_conflict only used with append
blank line before, comments can be *inside* the clause

2022-03-05 17:17 UTC, jreback commented on pandas/io/sql.py
> +    def _load_existing_pkeys(self, primary_keys, primary_key_values):
type inputs & outputs

2022-03-06 08:46 UTC, LSturtew commented on pandas/io/sql.py
> +        raise ValueError(f"'{on_row_conflict}' is not valid for on_row_conflict'")
yes:
```
    def test_to_sql_invalid_on_row_conflict(self, pkey_frame):
        msg = "'notvalidvalue' is not valid for on_row_conflict"
        with pytest.raises(ValueError, match=msg):
            sql.to_sql(
                pkey_frame,
                "pkey_frame1",
                self.conn,
                if_exists="append",
                on_row_conflict="notvalidvalue",
            )
```

2022-03-06 08:55 UTC, LSturtew commented
Sqlalchemy handles row conflicts differently depending on the database dialect. E.g: for postgress and sqlite the implementation is similar to what was originally proposed in the original PR: `on_conflict_do_nothing` or `on_conflict_do_update`, for mysql on the other hand this is handled with `on_duplicate_key_update`.

2022-04-27 12:20 UTC, maveec commented
@LSturtew seems little is missing to finalize this. Thank you for your effort and keep up the great work, lots of people are - and will be - grateful for this =)

2022-08-21 14:27 UTC, hichameyessou commented
@LSturtew few months passed, do you still have the capacity to complete this PR?

2022-08-29 11:28 UTC, JustinGuese commented
can we run this again? the logs for the tests are gone... Or what seems to be missing? I guess it is only a problem with the Docstrings and types, right?

2022-08-29 16:30 UTC, JustinGuese commented
I have added a pr for some small docstring changes to the repo of @LSturtew, because if I create a new PR to the pandas main branch all the colab would be lost I guess?
Otherwise, if you (LSturtew) give editing rights to maintainers I can do it directly (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

2022-08-29 16:51 UTC, LSturtew commented
> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

The box `Allow edits and access to secrets by maintainers` is checked

2022-08-30 10:45 UTC, JustinGuese commented
okay, i can't get it to work... maybe I'm just stuck in my thoughts
```
ERROR: Permission to LSturtew/pandas.git denied to JustinGuese.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I'm:
1. `gh pr checkout -R pandas-dev/pandas 46232`
2. adding my changes, git add & git commit
3. `git push git@github.com:LSturtew/pandas.git sql-upsert:sql-upsert`

what am I doing wrong?

2023-01-16 19:42 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2023-01-16 19:42 UTC, closed without merging