Bug fix -  groupby sum removed columns
pandas-dev/pandas pull request #46342
Opened 2022-03-12 16:20 UTC by weikhor

- [ ] closes #44132 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2022-03-14 13:49 UTC, pep8speaks commented
Hello @weikhor! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/groupby/groupby.py`](https://github.com/pandas-dev/pandas/blob/9066ffbf7e63e897975153679ecf93ac96518ca4/pandas/core/groupby/groupby.py):

> [Line 2186:21](https://github.com/pandas-dev/pandas/blob/9066ffbf7e63e897975153679ecf93ac96518ca4/pandas/core/groupby/groupby.py#L2186): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'

2022-03-16 01:02 UTC, jreback requested changes

2022-03-16 01:02 UTC, jreback commented on pandas/core/groupby/groupby.py
> +            if isinstance(result, DataFrame):
umm why would this be fix?

2022-03-19 10:13 UTC, weikhor commented
I close this since I stuck this for long time. I get simpler task. Thank for review.

2022-03-19 10:13 UTC, closed without merging