Added the round( ) function to avoid error while multiplication of float numbers issue: #46362
pandas-dev/pandas pull request #46388
Opened 2022-03-16 07:36 UTC by ShamithaReddy

- Added round( ) function to round the values and then convert it to int type while they are passed into the list-out, so that we can avoid conversations of int(28.999999999999996) to 28.
- if we round the value first it will be converted into 29 and then formating them to int type.
- ✅ closes #46362 
- ✅ [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- ✅ All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- ✅ Added an entry in the latest `doc/source/whatsnew/v1.4.2.rst`

2022-03-16 07:36 UTC, pep8speaks commented
Hello @ShamithaReddy! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/io/formats/test_format.py`](https://github.com/pandas-dev/pandas/blob/6e0693ee61c70cf037d49aba8de2bed9e0f7b1c7/pandas/tests/io/formats/test_format.py):

> [Line 3266:43](https://github.com/pandas-dev/pandas/blob/6e0693ee61c70cf037d49aba8de2bed9e0f7b1c7/pandas/tests/io/formats/test_format.py#L3266): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 3266:48](https://github.com/pandas-dev/pandas/blob/6e0693ee61c70cf037d49aba8de2bed9e0f7b1c7/pandas/tests/io/formats/test_format.py#L3266): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 3266:53](https://github.com/pandas-dev/pandas/blob/6e0693ee61c70cf037d49aba8de2bed9e0f7b1c7/pandas/tests/io/formats/test_format.py#L3266): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2022-03-16 11:05 UTC, jreback requested changes
needs a test to replicate the original issue (the describe case)

2022-03-16 11:05 UTC, jreback commented on doc/source/whatsnew/v1.4.2.rst
> +- Fixed a case where the format of printing percentiles in not correct for the describe function in ``format.py`` (:issue:`46362`)
move to 1.5

2022-03-19 07:21 UTC, ShamithaReddy commented
> needs a test to replicate the original issue (the describe case)
@jreback 
I did already include the original test case in https://github.com/pandas-dev/pandas/pull/46388/commits/998f9174c27d3cee9eddc90428e0e0765ee5979a

2022-04-05 00:48 UTC, datapythonista reviewed
Thanks for the contribution @ShamithaReddy. Implementation looks good. Added some comments. I think they should also leave the CI green, but would be great if you can check it yourself, and fix any other problem that make it red.

You've also got a conflict that you need to fix.

2022-04-05 00:48 UTC, datapythonista commented on doc/source/whatsnew/v1.4.2.rst
> +
Can you revert this please?

2022-04-05 00:48 UTC, datapythonista commented on pandas/tests/io/formats/test_format.py
> +    result = fmt.format_percentiles([0.281,0.57,0.58,0.29])
You need spaces after the commas. Also, those are supposed to be percentiles, so they should be sorted.

2022-04-05 00:48 UTC, datapythonista commented on doc/source/whatsnew/v1.5.0.rst
> +- Bug in :meth:`format.py` the percentiles values are converted to integer dtype, which ignores the floating point error while multiplying. (:issue:`46362`)
This seems a bit confusing. What about something more like "Bug when formatting percentiles, more decimals than needed shown" or something similar.

2022-05-24 21:01 UTC, mroeschke commented
Thanks for the pull request, but it appears to be stale. If interested in continuing, please merge in the main branch, address the review, and we can reopen.

2022-05-24 21:01 UTC, closed without merging