Test for gh46313
pandas-dev/pandas pull request #46422
Opened 2022-03-18 19:55 UTC by rxd330

- [x] closes #46313  (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

This patch adds a test for checking regression behavior as described in #46313. The bug was reported to be fixed and I could not reproduce the bug in the latest version as Mar.18, 2022. So, only a test was added.

This is my first contribution to the open-source project. Please let me know if something needs to be fixed. Thanks!

2022-03-19 17:54 UTC, jreback requested changes

2022-03-19 17:54 UTC, jreback commented on pandas/tests/dtypes/test_dtypes.py
> +    not_expected = np.dtype(np.object_)
you don't need the not expected case

2022-03-19 17:54 UTC, jreback commented on pandas/tests/dtypes/test_dtypes.py
> +        {"int_cat": [1, 2, 3], "bool_cat": [True, False, False]}, dtype="category"
move to pandas/tests/series/accessors/test_cat_accessor.py

2022-03-20 15:13 UTC, rxd330 commented
Hi there, I moved the code to the specified location and removed the unnecessary line. 

Thanks for giving feedback!

2022-03-20 16:18 UTC, jreback approved these changes

2022-03-20 18:01 UTC, mroeschke approved these changes

2022-03-20 18:01 UTC, merged

2022-03-20 18:01 UTC, mroeschke commented
Thanks @rxd330