TYP: Index.join
pandas-dev/pandas pull request #46518
Opened 2022-03-26 01:48 UTC by twoertwein

Overloads for Index.join

2022-03-26 01:48 UTC, twoertwein commented on pandas/core/indexes/base.py
> +    @deprecate_nonkeyword_arguments(version=None, allowed_args=["self", "other"])
Does this need a whatsnew+test?

2022-04-03 03:14 UTC, jreback requested changes

2022-04-03 03:14 UTC, jreback commented on pandas/core/indexes/base.py
> +    @deprecate_nonkeyword_arguments(version=None, allowed_args=["self", "other"])
yes this would need a note.

2022-05-06 21:26 UTC, jreback approved these changes

2022-05-06 21:26 UTC, merged

2022-05-06 21:26 UTC, jreback commented
thanks @twoertwein