TST: Regression test added for Timedelta
pandas-dev/pandas pull request #46645
Opened 2022-04-05 19:34 UTC by rxd330

- [x] closes #35665 
- [x] [Tests added and passed]
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

The commit on Mar 18 is approved. Not sure why it is showing up here... You can see it here:
https://github.com/pandas-dev/pandas/pull/46422

This PR adds a regression test for #35665 , which was caused by #38965. Please let me know if there's more I need to do! Thanks!

2022-04-10 00:46 UTC, jreback requested changes

2022-04-10 00:46 UTC, jreback commented on pandas/tests/dtypes/test_dtypes.py
> +def test_categorical_of_booleans_is_boolean():
this is unrelated, please merge master

2022-04-10 00:46 UTC, jreback commented on pandas/tests/frame/test_constructors.py
> +                row
don't put a try/except in a test.

also compare row here

2022-05-24 21:03 UTC, mroeschke commented
Thanks for the pull request, but it appears to be stale. If interested in continuing, please merge in the main branch, address the review, and we can reopen.

2022-05-24 21:03 UTC, closed without merging