Fix __instancecheck__ and __subclasscheck__ of metaclass in pandas.core.dtypes.generic
pandas-dev/pandas pull request #46719
Opened 2022-04-09 09:36 UTC by leonarduschen

- [ ] closes #46684 (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2022-04-09 20:22 UTC, rhshadrach requested changes
Thanks for the PR! Looks really good, but I suppose a test should also be added for apply as well.

2022-04-10 10:04 UTC, leonarduschen commented
Alright done!

2022-04-10 16:57 UTC, jreback approved these changes
lgtm over to you @rhshadrach

2022-04-10 22:27 UTC, rhshadrach approved these changes
lgtm

2022-04-10 22:28 UTC, merged

2022-04-10 22:28 UTC, rhshadrach commented
Thanks @leonarduschen!