Change `mylen` function to account for empty lists
pandas-dev/pandas pull request #46791
Opened 2022-04-16 17:13 UTC by ehariri

- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2022-04-16 17:36 UTC, mroeschke commented
Thanks for the pull request. Doesn't this fix relate to an existing issue? Can you demonstrate the behavior before/after fix?

2022-04-18 01:41 UTC, njriasan commented on pandas/tests/frame/methods/test_explode.py
> +            {
I think you should include the github issue on both of your test changes to make sure its clear why you added these tests.

2022-04-19 03:06 UTC, rhshadrach requested changes
Thanks for the PR!

2022-04-19 03:06 UTC, rhshadrach commented on pandas/core/frame.py
> +            mylen = lambda x: len(x) if is_list_like(x) and len(x) else 1
nit: for readability, can you make `and len(x) > 0`.

2022-04-19 03:06 UTC, rhshadrach commented on pandas/tests/frame/methods/test_explode.py
>      # GH 39240
In regards to https://github.com/pandas-dev/pandas/pull/46791/files#r851832909, add the issue number here; i.e. `# GH 39240, 46084`

2022-04-22 13:42 UTC, phofl reviewed
Could you please add a whatsnew note?

2022-04-22 13:42 UTC, phofl commented on pandas/tests/frame/methods/test_explode.py
> +    "input_dict, input_index, input_subset, expected_dict, expected_index",
Could you make new tests? This is really hard to review

2022-04-30 00:49 UTC, jreback requested changes
great, can you add a whatsnew note. bug fixes for 1.5, in the reshaping section.

2022-10-24 21:24 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2022-10-24 21:24 UTC, closed without merging