stopped numeric_only=True from dropping columns
pandas-dev/pandas pull request #46830
Opened 2022-04-22 03:38 UTC by hhheidi

- [ ] [Tests added and passed] Issue #46375

2022-04-22 03:38 UTC, pep8speaks commented
Hello @hhheidi! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pandas/tests/groupby/test_groupby.py`](https://github.com/pandas-dev/pandas/blob/2fa264bac0cc2c80d6f85c08953f0a4458817586/pandas/tests/groupby/test_groupby.py):

> [Line 2701:89](https://github.com/pandas-dev/pandas/blob/2fa264bac0cc2c80d6f85c08953f0a4458817586/pandas/tests/groupby/test_groupby.py#L2701): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 88 characters)
> [Line 2729:89](https://github.com/pandas-dev/pandas/blob/2fa264bac0cc2c80d6f85c08953f0a4458817586/pandas/tests/groupby/test_groupby.py#L2729): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 88 characters)
> [Line 2731:14](https://github.com/pandas-dev/pandas/blob/2fa264bac0cc2c80d6f85c08953f0a4458817586/pandas/tests/groupby/test_groupby.py#L2731): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '{'
> [Line 2731:74](https://github.com/pandas-dev/pandas/blob/2fa264bac0cc2c80d6f85c08953f0a4458817586/pandas/tests/groupby/test_groupby.py#L2731): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 2734:51](https://github.com/pandas-dev/pandas/blob/2fa264bac0cc2c80d6f85c08953f0a4458817586/pandas/tests/groupby/test_groupby.py#L2734): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 2737:14](https://github.com/pandas-dev/pandas/blob/2fa264bac0cc2c80d6f85c08953f0a4458817586/pandas/tests/groupby/test_groupby.py#L2737): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '{'
> [Line 2737:74](https://github.com/pandas-dev/pandas/blob/2fa264bac0cc2c80d6f85c08953f0a4458817586/pandas/tests/groupby/test_groupby.py#L2737): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 2740:51](https://github.com/pandas-dev/pandas/blob/2fa264bac0cc2c80d6f85c08953f0a4458817586/pandas/tests/groupby/test_groupby.py#L2740): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 2743:14](https://github.com/pandas-dev/pandas/blob/2fa264bac0cc2c80d6f85c08953f0a4458817586/pandas/tests/groupby/test_groupby.py#L2743): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '{'
> [Line 2743:74](https://github.com/pandas-dev/pandas/blob/2fa264bac0cc2c80d6f85c08953f0a4458817586/pandas/tests/groupby/test_groupby.py#L2743): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 2746:51](https://github.com/pandas-dev/pandas/blob/2fa264bac0cc2c80d6f85c08953f0a4458817586/pandas/tests/groupby/test_groupby.py#L2746): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 2750:89](https://github.com/pandas-dev/pandas/blob/2fa264bac0cc2c80d6f85c08953f0a4458817586/pandas/tests/groupby/test_groupby.py#L2750): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 88 characters)
> [Line 2755:44](https://github.com/pandas-dev/pandas/blob/2fa264bac0cc2c80d6f85c08953f0a4458817586/pandas/tests/groupby/test_groupby.py#L2755): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2022-04-22 13:33 UTC, phofl requested changes
This broke lots of tests. I think you have to fix this somewhere else

2022-04-22 23:12 UTC, hhheidi commented
Ouch, I just reran all the tests. Not sure if I have the expertise to fix the issue as-is, so could I update the PR with just the tests? Is that a thing?

2022-05-24 20:52 UTC, mroeschke commented
Thanks for the pull request, but it appears to be stale and is failing a lot of the CI checks. If interested in continuing, please fix the formatting and tests failures locally and we can reopen.

2022-05-24 20:52 UTC, closed without merging