REF: implement utc_val_to_local_val
pandas-dev/pandas pull request #46847
Opened 2022-04-23 01:34 UTC by jbrockmendel

I'm pretty happy with the perf impact, as the cases that are slowed down are the ones that are currently the fastest.

```
asv continuous -E virtualenv -f 1.01 a8968bfa 874d1ed4 --record-samples --append-samples -b tslibs.normalize -b tslibs.tslib.TimeIntsToPydatetime -b tslibs.period.TimeDT64ArrToPeriodArr -b tslibs.resolution
[...]
       before           after         ratio
     [a8968bfa]       [874d1ed4]
     <enh-nano-tzconversion>                 
+        89.6±3μs          122±2μs     1.36  tslibs.normalize.Normalize.time_is_date_array_normalized(10000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+      8.93±0.5ms       12.1±0.6ms     1.35  tslibs.normalize.Normalize.time_is_date_array_normalized(1000000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+        85.0±4μs          109±4μs     1.28  tslibs.normalize.Normalize.time_is_date_array_normalized(10000, datetime.timezone(datetime.timedelta(seconds=3600)))
+      8.40±0.5ms       10.5±0.7ms     1.25  tslibs.normalize.Normalize.time_is_date_array_normalized(1000000, datetime.timezone(datetime.timedelta(seconds=3600)))
+        74.1±4μs         85.5±3μs     1.15  tslibs.normalize.Normalize.time_is_date_array_normalized(10000, None)
+     2.07±0.09μs      2.35±0.06μs     1.14  tslibs.normalize.Normalize.time_is_date_array_normalized(100, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+     1.24±0.06μs      1.41±0.03μs     1.14  tslibs.normalize.Normalize.time_is_date_array_normalized(100, datetime.timezone.utc)
+        75.4±5μs         85.1±1μs     1.13  tslibs.normalize.Normalize.time_is_date_array_normalized(10000, datetime.timezone.utc)
+      7.74±0.7ms       8.69±0.6ms     1.12  tslibs.normalize.Normalize.time_is_date_array_normalized(1000000, None)
+      7.65±0.3ms       8.57±0.2ms     1.12  tslibs.normalize.Normalize.time_is_date_array_normalized(1000000, datetime.timezone.utc)
+     1.32±0.08μs      1.46±0.05μs     1.11  tslibs.normalize.Normalize.time_is_date_array_normalized(100, None)
+         104±5μs          115±5μs     1.11  tslibs.normalize.Normalize.time_normalize_i8_timestamps(10000, datetime.timezone(datetime.timedelta(seconds=3600)))
+        244±10μs          270±3μs     1.10  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 3000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         116±4μs          128±2μs     1.10  tslibs.normalize.Normalize.time_normalize_i8_timestamps(10000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+        23.9±1ms       26.3±0.3ms     1.10  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 3000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+      11.3±0.6ms       12.4±0.3ms     1.10  tslibs.normalize.Normalize.time_normalize_i8_timestamps(1000000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+      9.66±0.7ms       10.6±0.3ms     1.10  tslibs.normalize.Normalize.time_normalize_i8_timestamps(1000000, datetime.timezone(datetime.timedelta(seconds=3600)))
+      8.11±0.6ms       8.90±0.3ms     1.10  tslibs.normalize.Normalize.time_normalize_i8_timestamps(1000000, None)
+        85.7±2μs        93.9±10μs     1.10  tslibs.normalize.Normalize.time_normalize_i8_timestamps(10000, datetime.timezone.utc)
+         203±4μs          222±2μs     1.09  tslibs.resolution.TimeResolution.time_get_resolution('m', 10000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+      8.20±0.5ms       8.96±0.3ms     1.09  tslibs.normalize.Normalize.time_normalize_i8_timestamps(1000000, datetime.timezone.utc)
+      5.11±0.1μs       5.49±0.1μs     1.08  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(100, 12000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         279±8μs          300±3μs     1.07  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 12000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+        26.1±2ms       28.0±0.5ms     1.07  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 8000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         267±9μs         287±10μs     1.07  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 8000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+      23.8±0.7ms       25.5±0.8ms     1.07  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 2000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         270±8μs          288±3μs     1.07  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 9000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+        27.7±1ms       29.5±0.4ms     1.07  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 4006, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         284±8μs          302±6μs     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 4006, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+        26.2±2ms         27.9±1ms     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 9000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         250±8μs          265±3μs     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 2011, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+        27.4±1ms       29.1±0.8ms     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 12000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         246±9μs          261±3μs     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 1000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+      23.7±0.7ms         25.1±1ms     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 1000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+      22.4±0.8ms       23.7±0.3ms     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 2000, None)
+      26.2±0.8ms         27.7±1ms     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 7000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+        25.9±1ms       27.3±0.3ms     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 6000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         249±9μs         263±20μs     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 6000, None)
+        87.8±4μs         92.6±1μs     1.06  tslibs.normalize.Normalize.time_normalize_i8_timestamps(10000, None)
+        246±10μs          259±3μs     1.05  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 1011, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+        246±10μs          259±5μs     1.05  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 2000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         236±8μs          247±3μs     1.05  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 2011, None)
+      24.0±0.7ms       25.2±0.3ms     1.05  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 1011, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         250±3μs          262±3μs     1.05  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 6000, datetime.timezone.utc)
+         230±6μs          241±7μs     1.05  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 2000, datetime.timezone.utc)
+         231±7μs          242±4μs     1.05  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 2000, None)
+      22.6±0.9ms       23.6±0.2ms     1.05  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 2000, datetime.timezone.utc)
+     4.80±0.08μs       5.01±0.3μs     1.04  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(100, 1000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         262±4μs          274±3μs     1.04  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 11000, None)
+        262±10μs          273±4μs     1.04  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 8000, datetime.timezone(datetime.timedelta(seconds=3600)))
+      23.2±0.8ms       24.2±0.5ms     1.04  tslibs.period.Ti [...]

2022-04-23 22:28 UTC, mroeschke approved these changes
Nice LGTM. I think the slight performance hit is worth the consolidation of logic

2022-04-26 00:26 UTC, jreback requested changes
.html file included

2022-04-26 00:26 UTC, jreback commented on pandas/_libs/tslibs/vectorized.html
> +<!-- Generated by Cython 0.29.24 -->
umm is this meant to be included?

2022-04-26 03:23 UTC, jbrockmendel commented on pandas/_libs/tslibs/vectorized.html
> +<!-- Generated by Cython 0.29.24 -->
nope, removed

2022-04-26 20:05 UTC, mroeschke approved these changes

2022-04-27 12:26 UTC, jreback approved these changes

2022-04-27 12:26 UTC, merged

2022-04-27 12:26 UTC, jreback commented
thanks @jbrockmendel I believe have merged all of the non-nano stuff....