BUG: DatetimeIndex.resolution with nanosecond reso
pandas-dev/pandas pull request #46903
Opened 2022-04-30 02:14 UTC by jbrockmendel

- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2022-05-04 23:33 UTC, jreback requested changes

2022-05-04 23:33 UTC, jreback commented on pandas/tests/series/methods/test_asof.py
> +        # GH#46903 previously incorrectly was "day"
can you put this in a dedicated method (the deprecation check)

2022-05-05 22:10 UTC, mroeschke approved these changes

2022-05-09 18:49 UTC, mroeschke approved these changes
Not sure if @jreback's comment was completely addressed but LGTM

2022-05-17 23:48 UTC, jbrockmendel commented
Rebased + green

2022-05-19 13:11 UTC, jreback approved these changes

2022-05-19 13:12 UTC, merged