TYP: fix a few annotations in offsets.pyi
pandas-dev/pandas pull request #46920
Opened 2022-05-01 18:18 UTC by twoertwein

- [ ] closes #46908
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

Some doc-strings refer to `pd.HolidayCalendar` but that doesn't seem to exist?!

There are a few more un-annotated variables and a few containers (list and dict) without types but I'm not familair enough with them to annotate them.

2022-05-01 18:28 UTC, Dr-Irv requested changes
I checked your changes against current API.  Did not check if there are others that need fixing - assume you did that.  Small changes to make

2022-05-01 18:28 UTC, Dr-Irv commented on pandas/_libs/tslibs/offsets.pyi
> +        variation: str = ...,
`variation` should be `Literal["nearest", "last"]` according to the docs.

2022-05-01 18:28 UTC, Dr-Irv commented on pandas/_libs/tslibs/offsets.pyi
> +        calendar: np.busdaycalendar = ...,
Looking at the `__init__()` in the `pyx` file, I think `calendar` should be `None | np.busdaycalendar`

2022-05-01 18:28 UTC, Dr-Irv commented on pandas/_libs/tslibs/offsets.pyi
> +        calendar: np.busdaycalendar = ...,
Allow `None` for `calendar`

2022-05-01 18:28 UTC, Dr-Irv commented on pandas/_libs/tslibs/offsets.pyi
> +        calendar: np.busdaycalendar = ...,
allow `None` for calendar

2022-05-01 18:44 UTC, Dr-Irv reviewed
This is a minor thing, but you have this:
```python
        holidays: None | list = ...,
        calendar: np.busdaycalendar | None = ...,
```

Have we standardized on whether we put `None` last or first?  If not, we should be consistent within this file.

2022-05-01 18:51 UTC, twoertwein commented
> Have we standardized on whether we put `None` last or first?

Not that I'm aware of. The only example I found is here: https://pandas.pydata.org/docs/development/contributing_codebase.html#style-guidelines (None at the end).

2022-05-01 18:56 UTC, Dr-Irv commented
> > Have we standardized on whether we put `None` last or first?
> 
> Not that I'm aware of. The only example I found is here: https://pandas.pydata.org/docs/development/contributing_codebase.html#style-guidelines (None at the end).

I think we use the style of `str | None` more than `None | str`, so can you use the former throughout in this file for this PR?

2022-05-01 19:37 UTC, Dr-Irv approved these changes

2022-05-03 11:58 UTC, merged

2022-05-03 11:58 UTC, Dr-Irv commented
Thanks @twoertwein