DEPR: groupby numeric_only default
pandas-dev/pandas pull request #47025
Opened 2022-05-14 16:04 UTC by rhshadrach

- [x] closes #46072 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

There are two cases we want to emit a deprecation warning for DataFrameGroupBy:
 - numeric_only is not specified and columns get dropped. In this case emit a warning that the default of numeric_only will change to False in the future.
 - numeric_only is specified to False and columns still get dropped. In this case emit a warning that the op will raise in the future.

2022-05-15 02:09 UTC, jreback requested changes
not a fan of filterwarnings, i know its a bit annoying but can you either explicity test or just pass `numeric_only=False`?

2022-05-15 02:09 UTC, jreback commented on pandas/core/groupby/groupby.py
> +                self.axis != 1
can you make a helper for this rather than repeating?

2022-05-15 02:09 UTC, jreback commented on pandas/tests/groupby/test_categorical.py
> +@pytest.mark.filterwarnings("ignore:.*value of numeric_only.*:FutureWarning")
can you explictily test these rather than filtering (alt pass `numeric_only=False`) as needed

2022-05-18 02:39 UTC, rhshadrach commented
Thanks @jreback; filterwarnings has been removed and the helper had been added.

2022-05-18 12:54 UTC, jreback approved these changes

2022-05-18 12:54 UTC, merged

2022-05-18 12:54 UTC, jreback commented
very nice @rhshadrach

2022-05-18 17:04 UTC, twoertwein commented
I think this causes the doc build to fail with multiple of these warnings:

> <ipython-input-97-5805a339bf74>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
>   (bb.groupby(['year', 'team']).sum()

Would probably need to update the documentation to avoid these FutureWarnings.