BUG: `DataFrame.shift` shows different behavior for `axis=1` when `freq` is specified
pandas-dev/pandas pull request #47051
Opened 2022-05-18 03:05 UTC by wjsi

- [x] closes #47039 
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2022-05-21 20:02 UTC, jreback requested changes

2022-05-21 20:02 UTC, jreback commented on doc/source/whatsnew/v1.5.0.rst
> +- Bug in :meth:`DataFrame.shift` when ``axis`` is ``columns`` and ``fill_value`` is absent, ``freq`` is ignored (:issue:`47039`)
will take this for 1.4.3, can you move the note (can put under regression section)

2022-05-26 17:54 UTC, mroeschke approved these changes
LGTM, failure unrelated. Needs approval from @jreback to merge.

2022-05-27 13:23 UTC, simonjayhawkins commented
> LGTM, failure unrelated

merge conflict needed resolving. so shouldn't fail this time with main merged.

2022-05-28 01:39 UTC, jreback approved these changes

2022-05-28 10:10 UTC, merged

2022-05-28 10:11 UTC, simonjayhawkins commented
@meeseeksdev backport 1.4.x