Fix set_sticky background
pandas-dev/pandas pull request #47082
Opened 2022-05-21 08:35 UTC by ShawnZhong

- [x] closes #46984 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Inherit the `background-color` of the sticky elements from its parents instead of hard-coding it to white. 

Example: 

```py
import pandas as pd
import numpy as np

pd.DataFrame(np.random.randn(16, 100)).style.set_sticky()
```

<img width="465" alt="image" src="https://user-images.githubusercontent.com/6421097/169643245-68b071c4-bdff-4813-9537-8eba341570f3.png">

For reference, https://github.com/pandas-dev/pandas/issues/42799 introduced the `set_sticky` feature.

2022-05-21 19:34 UTC, jreback requested changes
can you add a note for this, 1.5, styler section

2022-05-21 19:35 UTC, jreback commented
cc @attack68

2022-05-21 20:13 UTC, attack68 commented
This is the best solution. LGTM

2022-05-26 17:48 UTC, mroeschke approved these changes

2022-05-26 17:49 UTC, mroeschke commented
LGTM. Needs approval from @jreback to merge.

2022-05-26 17:54 UTC, jreback approved these changes

2022-05-26 17:59 UTC, merged

2022-05-26 17:59 UTC, mroeschke commented
Thanks @ShawnZhong

2023-04-22 00:49 UTC, byrdie commented
I think this PR introduced a bit of a regression since it makes the background of the sticky row/column transparent, which makes it harder to read once you scroll to right/down.

You can see the behaviour in the current docuemntation
https://pandas.pydata.org/docs/user_guide/style.html#Sticky-Headers

2023-04-22 05:59 UTC, attack68 commented
I think regression is too strong a word for this item, but generally I agree. The underlying issue was reopened and remains outstanding.