Fix SAS7BDAT run-length encoding formula
pandas-dev/pandas pull request #47099
Opened 2022-05-23 21:56 UTC by jonashaag

Run across an error/simplification? of a RLE formula in the SAS7BDAT parser. The original code https://bitbucket.org/jaredhobbs/sas7bdat/src/18cbd14407918c1aa90f136c1d6c5d83f307dba0/sas7bdat.py#lines-110:114 has the correct formula. I am not sure why we have another version.

Unfortunately I do not know how to add a regression test. The SAS file that reproduces the issue is proprietary, as is the SAS7BDAT file format, and I'm not aware of any means of creating a SAS file.

- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2022-05-23 22:02 UTC, jonashaag commented
Similar case here https://github.com/pandas-dev/pandas/issues/31243#issuecomment-686386759

2022-05-23 22:04 UTC, jonashaag commented
pyreadstat has the same logic https://github.com/Roche/pyreadstat/blob/master/src/sas/readstat_sas_rle.c#L62-L63

2022-05-23 22:19 UTC, jonashaag commented on pandas/io/sas/sas.pyx
> +        if control_byte == 0x00 and ipos < length:
```suggestion
        if control_byte == 0x00:
```

2022-05-23 22:21 UTC, jonashaag commented on pandas/io/sas/sas.pyx
> +            nbytes = <int>(inbuff[ipos] & 0xFF) + 64 + end_of_first_byte * 256
```suggestion
            nbytes = <int>inbuff[ipos] + 64 + end_of_first_byte * 256
```

2022-05-23 22:21 UTC, jonashaag commented on pandas/io/sas/sas.pyx
> +            nbytes = <int>inbuff[ipos] + 64 + end_of_first_byte * 256
```suggestion
            nbytes = <int>(inbuff[ipos]) + 64 + end_of_first_byte * 256
```

2022-05-24 00:00 UTC, jreback requested changes
can you add a test case / sample file that replicates the bug & a whatsnew note (I/O bug fixes for 1.5)

2022-05-24 06:16 UTC, jonashaag commented
See my note above about a test case. Can add a what’s new

2022-05-24 08:29 UTC, jonashaag commented
Unfortunately all test files I've seen so far (including the ones in pyreadstat) don't  reproduce the bug.

2022-05-24 15:54 UTC, jonashaag commented
Unfortunately both of the files do not reproduce the bug

2022-06-05 23:45 UTC, jreback commented
cc @bashtage WDYT?

2022-06-06 17:40 UTC, bashtage commented
Would be good to have a file that requires this offset Is it possible to create one?

2022-06-09 09:49 UTC, jonashaag commented
@bashtage Unfortunately I don't have a file that I can share and pyreadstat can't write SAS7BDAT files. Do you have any ideas where to get such a file?

2022-06-12 20:40 UTC, jonashaag commented
@bashtage came up with a test file by zeroing almost all of the bytes of a real world file. PR now depends on https://github.com/pandas-dev/pandas/pull/47154

2022-06-12 22:06 UTC, bashtage commented
> @bashtage came up with a test file by zeroing almost all of the bytes of a real world file. PR now depends on #47154

Once that is in rebase and then should be good.

2022-06-21 07:18 UTC, bashtage commented
LGTM.

2022-06-21 07:19 UTC, bashtage approved these changes
LGTM.

2022-06-21 07:19 UTC, bashtage commented on pandas/tests/io/sas/test_sas7bdat.py
> +    assert df.shape == (11_000, 20)
Adding a review comment so I can approve.

2022-06-26 14:06 UTC, pep8speaks commented
Hello @jonashaag! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/tests/io/sas/test_sas7bdat.py`](https://github.com/pandas-dev/pandas/blob/76e5b557e94959fd246936eb806ee53bdc10a6b4/pandas/tests/io/sas/test_sas7bdat.py):

> [Line 399:36](https://github.com/pandas-dev/pandas/blob/76e5b557e94959fd246936eb806ee53bdc10a6b4/pandas/tests/io/sas/test_sas7bdat.py#L399): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2022-07-03 15:53 UTC, jonashaag commented
@jreback @mroeschke mind reviewing this?

2022-07-05 17:04 UTC, jonashaag commented on doc/source/whatsnew/v1.5.0.rst
> +- Bug in :func:`read_sas` with RLE-compressed SAS7BDAT files that contain 0x00 control bytes (:issue:`47099`)
No it’s a different control byte

2022-07-05 17:15 UTC, mroeschke commented on doc/source/whatsnew/v1.5.0.rst
> +- Bug in :func:`read_sas` with RLE-compressed SAS7BDAT files that contain 0x00 control bytes (:issue:`47099`)
Ah thanks missed that 😅

2022-07-05 17:15 UTC, mroeschke approved these changes

2022-07-05 17:15 UTC, merged

2022-07-05 17:15 UTC, mroeschke commented
Thanks @jonashaag

2022-07-05 17:21 UTC, jonashaag commented
Thanks :)