Unit Test: Construction of DataFrame works with empty list but not empty array
pandas-dev/pandas pull request #47192
Opened 2022-06-01 15:38 UTC by weikhor

- [ ] closes #46822 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2022-06-03 13:22 UTC, phofl reviewed
Do we really want that?

2022-06-05 22:51 UTC, jreback requested changes
this is as intended, so i don't think we want to change.

2022-06-05 23:03 UTC, mroeschke reviewed
@weikhor instead could you just write a unit test `pandas.DataFrame(data=numpy.array([]), columns=['a','b'])` raises an exception cementing this behavior?

2022-06-06 19:26 UTC, mroeschke commented on pandas/tests/frame/test_constructors.py
> +    def test_construction_empty_dataframe(self):
Could you make this test name a bit more specific like `test_construction_empty_array_multi_column_raises`

2022-06-11 17:47 UTC, mroeschke approved these changes
Thanks LGTM. Needs @jreback approval to merge

2022-06-11 18:05 UTC, jreback approved these changes

2022-06-11 18:05 UTC, merged

2022-06-11 18:05 UTC, jreback commented
thanks @weikhor