DEPR: groupby.transform not aligning with input index
pandas-dev/pandas pull request #47244
Opened 2022-06-05 17:08 UTC by rhshadrach

- [x] closes #45648 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

cc @jbrockmendel

2022-06-05 22:23 UTC, jreback requested changes
minor comments

2022-06-05 22:23 UTC, jreback commented on pandas/core/groupby/groupby.py
> +    When using ``.transform`` on a grouped DataFrame and the transformation function
nit, don't you need a blank line here?

2022-06-05 22:23 UTC, jreback commented on pandas/core/groupby/generic.py
> +        if emit_alignment_warning:
can you add this PR / issue number here as a comment

2022-06-05 22:23 UTC, jreback commented on doc/source/user_guide/groupby.rst
> +    When using ``.transform`` on a grouped DataFrame and the transformation function
blank line here?

2022-06-06 21:14 UTC, rhshadrach commented
Thanks @jreback - changes made

2022-06-10 23:43 UTC, jreback approved these changes

2022-06-10 23:44 UTC, jreback commented
lgtm merge on green

2022-06-11 15:20 UTC, merged

2022-06-11 15:21 UTC, jreback commented
thanks @rhshadrach