Update ecosystem.rst
pandas-dev/pandas pull request #47464
Opened 2022-06-22 14:40 UTC by kswarj

Fix capitalization for some headings

- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2022-06-23 20:30 UTC, mroeschke requested changes

2022-06-23 20:30 UTC, mroeschke commented on doc/source/ecosystem.rst
> +IdE
I don't think a lowercase d here makes sense

2022-06-24 10:20 UTC, phofl requested changes
Please don't rename them. The current capitalization corresponds with the library names itself

2022-06-24 17:36 UTC, mroeschke commented
Thanks for the PR, but as mentioned these titles are as intended. If interested in contributing feel free to tackle any issue labeled `good first issue`. Closing.

2022-06-24 17:36 UTC, closed without merging