ENH: Make categories setitem error more readable
pandas-dev/pandas pull request #47624
Opened 2022-07-07 12:23 UTC by siddartha-10

Closes #46646

2022-07-07 12:23 UTC, pep8speaks commented
Hello @siddartha-10! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/core/arrays/categorical.py`](https://github.com/pandas-dev/pandas/blob/6dc64dd0316126ca119e00c7605722805c709325/pandas/core/arrays/categorical.py):

> [Line 1477:29](https://github.com/pandas-dev/pandas/blob/6dc64dd0316126ca119e00c7605722805c709325/pandas/core/arrays/categorical.py#L1477): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1478:62](https://github.com/pandas-dev/pandas/blob/6dc64dd0316126ca119e00c7605722805c709325/pandas/core/arrays/categorical.py#L1478): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1479:69](https://github.com/pandas-dev/pandas/blob/6dc64dd0316126ca119e00c7605722805c709325/pandas/core/arrays/categorical.py#L1479): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2022-07-07 18:52 UTC, mzeitlin11 requested changes
Thanks for the pr @siddartha-10. Can you please explain the rationale behind this change? Is there a related issue?

2022-07-07 19:01 UTC, siddartha-10 commented
> Thanks for the pr @siddartha-10. Can you please explain the rationale behind this change? Is there a related issue?

Yes @mzeitlin11 There is a issue #46646. Before this it was showing lot of error statements after this it just shows a few of them I believe

2022-07-07 19:38 UTC, mzeitlin11 commented
> Yes @mzeitlin11 There is a issue #46646. Before this it was showing lot of error statements after this it just shows a few of them I believe

Thanks. Can you please add a test showing how this fixes the issue in #46646. See https://pandas.pydata.org/docs/development/contributing.html for some guidance on how to add a test. Looks like there is also a linting error, please see https://pandas.pydata.org/docs/development/contributing_codebase.html#pre-commit for how to fix that

2022-07-09 02:14 UTC, phofl commented on pandas/core/arrays/categorical.py
> +            "Cannot setitem on a Categorical with a new "
An intendation is missing here

2022-08-15 16:22 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. We have another active contribution in https://github.com/pandas-dev/pandas/pull/48087, so closing in favor.

2022-08-15 16:22 UTC, closed without merging