BUG in read_pickle
pandas-dev/pandas pull request #48007
Opened 2022-08-08 15:54 UTC by Kinza-Raza

- [ ] closes #47895
- [ ] Fixed note in the latest `pandas/io/pickle.py`

2022-08-08 19:09 UTC, MarcoGorelli requested changes
Thanks, wording looks good!

I was surprised that `flake8` wasn't throwing an error because of the long line, then I noticed `noqa: E501` on L185

While we're here, could you please rewrite L167 so it spans multiple lines, like
```
    >>> original_df = pd.DataFrame(
    ...     {{"foo": range(5), "bar": range(5, 10)}}
    ...    )  # doctest: +SKIP
```
and then split the line you added into 2 lines, and also remove the `noqa: E501` on line 185?

2022-08-08 20:41 UTC, pep8speaks commented
Hello @Kinza-Raza! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandas/io/pickle.py`](https://github.com/pandas-dev/pandas/blob/b4fc94158c929d5eeb1ba7cca46f699f3cc77ded/pandas/io/pickle.py):

> [Line 170:31](https://github.com/pandas-dev/pandas/blob/b4fc94158c929d5eeb1ba7cca46f699f3cc77ded/pandas/io/pickle.py#L170): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 188:8](https://github.com/pandas-dev/pandas/blob/b4fc94158c929d5eeb1ba7cca46f699f3cc77ded/pandas/io/pickle.py#L188): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2022-08-08 20:49 UTC, Kinza-Raza commented
@MarcoGorelli I was trying to build the documentation as explained [here](https://pandas.pydata.org/docs/dev/development/contributing_documentation.html#how-to-build-the-pandas-documentation) but got some import errors (modules not found) even though I built the dev environment with docker.

It says in **make.py**

> To build the docs you must have all optional dependencies for pandas
installed. See the installation instructions for a list of these.

Could you redirect me to the installation instructions for future reference so I can view the changes I'm making? Many thanks!

2022-08-08 23:30 UTC, twoertwein commented on pandas/io/pickle.py
> +    """
I think the only thing left to approve the CI is to remove the trailing white space after `"""`

2022-08-09 19:10 UTC, MarcoGorelli approved these changes
Thanks @Kinza-Raza 

![](https://i.fluffy.cc/4HrdmGw7MHL3rcH3J0lCBBG7xhlxnWs7.gif)

2022-08-09 19:10 UTC, merged

2022-08-09 19:11 UTC, MarcoGorelli commented
> Could you redirect me to the installation instructions for future reference so I can view the changes I'm making? Many thanks!

The instructions should all be in https://pandas.pydata.org/docs/development/contributing.html - if anything's not clear / doesn't work, please do feel free to ask for help