CLN: Use cython algo for groupby var with ddof != 1
pandas-dev/pandas pull request #48152
Opened 2022-08-19 12:03 UTC by phofl

- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

cc @rhshadrach 

I think you've implemented ddof on the cython level a while back. Any reasons why var is taking a different path? Results look sensible and no failing tests

Also, gives a nice speedup

2022-08-19 16:49 UTC, mroeschke reviewed
From a quick look, I didn't see a test in `pandas/tests/groupby` with `ddof !=1`. Could you confirm and add that test if there isn't one?

2022-08-19 16:59 UTC, phofl commented
We've got the number tests that are testing consistency between numba and cython, so I think we are good. They are testing ddof 0

2022-08-19 17:04 UTC, mroeschke approved these changes
Ah yes, forgot there were cython comparison tests for `numba_supported_reductions`.

2022-08-19 20:28 UTC, rhshadrach requested changes
Nice! From what I can tell I added it to cython but ran into issues with var, reworked the implementation and forgot to add it back in.

Could use a line in the performance section of the whatsnew

2022-08-19 20:28 UTC, rhshadrach commented on pandas/core/groupby/groupby.py
> +                **{"ddof": ddof},
Just do `ddof=ddof`?

2022-08-19 20:51 UTC, phofl commented on pandas/core/groupby/groupby.py
> +                **{"ddof": ddof},
Good point, also added whatsnew

2022-08-19 21:40 UTC, rhshadrach approved these changes
lgtm

2022-08-20 00:08 UTC, merged

2022-08-20 00:08 UTC, mroeschke commented
Thanks @phofl