Get rid of question marks in getting started tutorials
pandas-dev/pandas pull request #48233
Opened 2022-08-24 19:10 UTC by samrao1997

- [x] closes #48227 (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2022-08-24 19:26 UTC, mroeschke commented on doc/source/getting_started/intro_tutorials/04_plotting.rst
>  ----------------------------------
All the `-` will need to match the length of these altered titles.

2022-08-25 17:43 UTC, MarcoGorelli requested changes
The issue is about removing question marks when the heading isn't a question (e.g. "How to calculate summary statistics?"), heading that are already questions (e.g. "How do I create plots in pandas?") can stay as they are

2022-08-25 17:53 UTC, samrao1997 commented
@MarcoGorelli I adjusted that to remain as is [aka `How do I create plots?`]. 

However, I noticed that in the docs for some reason the [plots](https://pandas.pydata.org/docs/getting_started/intro_tutorials/04_plotting.html#) heading shows `How to` with a question mark and when I added the previous change with `How to` without question mark building the docs got rid of the question mark on that page.

Not sure how the code show `How do I` when the docs show the heading `How to`....

2022-08-25 17:55 UTC, MarcoGorelli requested changes

2022-08-25 17:55 UTC, MarcoGorelli commented on doc/source/getting_started/intro_tutorials/06_calculate_statistics.rst
>  ------------------------------------
you need to align the underscores (remove the last one)

2022-08-25 17:56 UTC, MarcoGorelli commented
> Not sure how the code show `How do I` when the docs show the heading `How to`....

you probably just need to do `python make.py clean` first

2022-08-25 18:11 UTC, samrao1997 commented
@MarcoGorelli I have updated the dashes to be the length of the alter titles. Sorry about that.

2022-08-25 18:33 UTC, MarcoGorelli approved these changes
Thanks @samrao1997 

![](https://i.fluffy.cc/qHzfcB6BZ9ZD7K3wFknqLsrHqsq56bPM.gif)

2022-08-25 22:05 UTC, mroeschke approved these changes

2022-08-25 22:05 UTC, merged

2022-08-25 22:05 UTC, mroeschke commented
Thanks @samrao1997