CI: Catch importwarning _SixMetaPathImporter.find_spec
pandas-dev/pandas pull request #48278
Opened 2022-08-26 20:14 UTC by phofl

Lets see if this helps somehow

I can't see how this could be related to our s3fs and aiobotocore pins. The following is the version diff from before and after the pin:

```
                 Name_old     Name_new Version_old Version_new
3             aiobotocore  aiobotocore       2.4.0       1.4.2
26                  boto3        boto3     1.24.59    1.17.106
27               botocore     botocore     1.27.59    1.20.106
76                 fsspec       fsspec    2022.7.1    2021.7.0
77                  gcsfs        gcsfs    2022.7.1    2021.7.0
98   google-cloud-storage          NaN       2.5.0         NaN
119              jmespath     jmespath       1.0.1      0.10.0
286                  s3fs         s3fs       0.6.0    2021.7.0
287            s3transfer   s3transfer       0.6.0       0.4.2
```

2022-08-26 20:59 UTC, mroeschke reviewed
I wouldn't be opposed to just adding this to `filterwarnings` in pyproject.toml since pandas doesn't explicitly use `six` so it should be from one of the dependencies: https://github.com/benjaminp/six/issues/341

2022-08-26 21:01 UTC, phofl commented
Yes, definitely. Its a bit hard to find out from which one though. 

Just want to see if this helps. Can add to pyproject.toml afterwards

2022-08-26 21:17 UTC, phofl commented
Added to pyproject.toml, lets see if it works. Can not reproduce the warning locally

2022-08-27 08:35 UTC, phofl commented
It looks like filterwarnings does not work well together with assert_produces_warning. Could not get tests to pass locally when filtering the warning with pytest and checking for no warning

2022-08-27 19:55 UTC, phofl commented
cc @mroeschke 

This is greenish now. Check is ugly though

2022-08-27 22:49 UTC, lithomas1 commented
So I did a little debugging, and the warning is coming from botocore(they vendor six), and it looks like the pinning downgraded botocore, cuasing this warning to come back.

2022-08-27 22:56 UTC, lithomas1 requested changes
This is a symptom of pinning aiobotocore(see comments in #48272)

2022-08-28 04:32 UTC, phofl commented
Yeah but this is necessary, see https://github.com/pandas-dev/pandas/pull/48272#issue-1352193730

2022-08-29 18:10 UTC, lithomas1 commented
The thing is, this does have to do with it. The way I understand it is s3fs pins aiobotocore which pins down botocore. As I mentioned, pinning aiobotocore in the other PR is pinning down botocore to an old version that vendors an old six doesn't address the warning.

So I would be -1 on this, since this ImportWarning is telling us that pinning aiobotocore was not the right move.

2022-08-29 18:33 UTC, phofl commented
S3fs is not pinning aiobotocore, but we have to pin since the old s3fs is not compatible with aiobotocore > 2.0. pinning botocore will most likely cause non solvable environments

i think pinning aiobotocore is the right move here in a sense, not having a higher s3fs minimum requirement is the actual issue. The old s3fs is not compatible with 3.10

can we bump this in the rc? Or do we have to follow a certain version Schema there?

2022-08-29 18:39 UTC, mroeschke commented
> can we bump this in the rc? Or do we have to follow a certain version Schema there?

As mentioned in https://github.com/pandas-dev/pandas/pull/48291, I would be +1 to simply bumping `s3fs` in the 1.5.0rc. I have been following a "min version that has been released one year prior" rule of thumb for most optional dependencies.

2022-08-29 19:09 UTC, phofl commented
Thx, closing in favour of #48299

2022-08-29 19:09 UTC, closed without merging