Backport PR #48272 on branch 1.5.x (CI: Require s3fs greater than minumum version in builds)
pandas-dev/pandas pull request #48276
Opened 2022-08-26 17:42 UTC by meeseeksmachine

Backport PR #48272: CI: Require s3fs greater than minumum version in builds

2022-08-27 22:54 UTC, lithomas1 requested changes
Blocking pending discussion in #48272

2022-08-28 09:42 UTC, phofl commented
#48272 is unavoidable, but we should at least get #48276 in before merging here

2022-08-29 00:57 UTC, lithomas1 approved these changes
Unblocking this, provided #48291 is merged.

2022-08-29 19:56 UTC, phofl commented
Waiting for #48299

2022-08-29 22:45 UTC, merged