Unexpected keyword argument
pandas-dev/pandas pull request #48914
Opened 2022-10-02 17:54 UTC by shalearkane

This fixed unexpected-keyword-argument warnings from pylint.
The other warnings produced were already expected to be caught in tests.

- [x] closes #48855

2022-10-02 19:57 UTC, shalearkane commented
`pre-commit` is failing because I am using Optional type annotation with the older syntax `Optional[type]` as the newer syntax `type | None` is only supported on Python 3.10+

2022-10-02 20:02 UTC, MarcoGorelli commented
> `pre-commit` is failing because I am using [Optional type annotation](https://docs.python.org/3/library/typing.html#typing.Optional) with the older syntax `Optional[type]` as the newer syntax `type | None` is only supported on Python 3.10+

it's supported with `from __future__ import annotations`, which is at the top of the file

2022-10-03 15:18 UTC, MarcoGorelli requested changes

2022-10-03 20:35 UTC, shalearkane commented on pandas/core/indexes/base.py
> +        dtype=None,
Yes, I looked into the code, it seems like _constructor is being overridden by the classes `ExtensionIndex`, `MultiIndex` and `NumericIndex` which inherit form the base class `Index`.

2022-10-04 05:54 UTC, shalearkane commented on pandas/core/indexes/base.py
> +        dtype=None,
![classes](https://user-images.githubusercontent.com/78898665/193744862-c37f778f-adfd-45a2-adcb-fe4a2c354b72.png)

2022-10-05 07:00 UTC, MarcoGorelli requested changes

2022-10-05 07:00 UTC, MarcoGorelli commented on pandas/core/indexes/base.py
> +        dtype=None,
wait, this isn't resolved - I think the issue is that pylint can't tell that `@cache_readonly` makes `_constructor` act like a property and that it doesn't take arguments

I'll have another look later

2022-11-03 17:50 UTC, MarcoGorelli requested changes
Thanks @shalearkane for your PR

I've had a closer look, and I don't think we should enable this check

`cache_readonly` acts like a property, but `pylint` isn't aware of this and so it thinks that the arguments that are passed to whetever function the property returns are being passed to the property itself

`mypy` already checks this, and the way pandas gets mypy to recognise that `cache_readonly` is a property is

https://github.com/pandas-dev/pandas/blob/7440fe27eef0aab0f217ca9fb434f1e3ac74836e/pandas/_libs/properties.pyi#L16

So, I'll add this to the list of checks we probably can't turn off

Closing for now then

2022-11-03 17:50 UTC, closed without merging