enhancement: Added 'errors=coerce' option in astype()
pandas-dev/pandas pull request #49042
Opened 2022-10-11 08:12 UTC by subbusainath

- [ ] closes #48781  
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [errors=coerce in astype()](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/v1.6.1.rst` file if fixing a bug or adding a new feature.

2022-10-11 11:12 UTC, jreback requested changes
tests always

2022-10-11 16:56 UTC, mroeschke requested changes
Thanks for the pull request. The original issue hasn't had much discussion or agreement from the core team, so I would recommend waiting until there's more consensus

2022-10-12 17:38 UTC, mroeschke commented
Going to close for now pending the discussion in the original issue. Happy to have your thoughts in that issue if you are in support of this feature.

2022-10-12 17:43 UTC, subbusainath commented
Why didn't we moved this PR ? Since it does not have a huge enhancement in the astype method. I would like to add this enhancement feature into astype (). Which help us to solve the issue. I hope!

2022-10-12 17:52 UTC, mroeschke commented
We would still be open to this enhancement given more support and discussion in #48781 first.

2022-10-12 17:53 UTC, mroeschke commented
Actually to stimulate discussion, I'll reopen this PR, sorry.

2022-10-12 21:03 UTC, jbrockmendel commented on doc/source/whatsnew/v1.6.1.rst
> +.. _whatsnew_161:
if accepted, this would go in the 1.6.0 file

2022-10-12 21:03 UTC, jbrockmendel commented on pandas/core/dtypes/astype.py
> +            new_values = values
how is this different from `errors="ignore"`?

2022-11-17 01:11 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. Additionally this issue could use more discussion on the original issue before moving forward to closing to await resolution on the main issue

2022-11-17 01:11 UTC, closed without merging