WIP: perf/cache typing
pandas-dev/pandas pull request #49112
Opened 2022-10-15 10:15 UTC by Code0x58

- [ ] closes #48212
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
- [ ] Check coverage

2022-10-23 16:13 UTC, Code0x58 commented
> Could you split this in 2 PR, 1 for typing and 1 for caching?
> 
> Also the whatsnew note should go in `v2.0.0.rst`.

I've stripped out caching as it generally wasn't beneficial, but left a note on https://github.com/pandas-dev/pandas/issues/48212#issuecomment-1288145916 about what where might be good to pursue for further gains without losses.

2022-10-24 17:58 UTC, mroeschke requested changes
So generally this PR should be typing only? If so, could you undo all the refactoring?

2022-10-25 06:23 UTC, Code0x58 commented
> So generally this PR should be typing only? If so, could you undo all the refactoring?

Oh right, I thought you meant separating some bits in different modules. Is there some policy around type annotation additions? I originally added some after the pre-commit hook/CI complained about typing,

If not, the get

2022-10-25 10:43 UTC, Code0x58 commented
Accidentally closed and bodged editing of previous message while trying to walk and type at the same time

2022-11-22 00:52 UTC, jbrockmendel commented
@Code0x58 can you merge main and address comments

2022-12-17 19:34 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2022-12-17 19:34 UTC, closed without merging