ENH/CoW: use lazy copy in set_axis method
pandas-dev/pandas pull request #49600
Opened 2022-11-09 18:18 UTC by Th3nn3ss

Copy-on-Write in `set_axis`
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
This PR is part of an effort to implement the Copy-on-Write implementation mentioned in #49473. More detail in this proposal https://docs.google.com/document/d/1ZCQ9mx3LBMy-nhwRl33_jgcvWo9IWdEfxDNQ2thyTb0/edit / with discussions in https://github.com/pandas-dev/pandas/issues/36195

2022-11-12 12:40 UTC, MarcoGorelli requested changes

2022-11-12 12:40 UTC, MarcoGorelli commented on pandas/core/frame.py
> +        copy: bool | None = None,
you'll need to update the annotation and default value for `Series.set_axis` as well

2022-11-12 12:40 UTC, MarcoGorelli commented on pandas/tests/frame/methods/test_set_axis.py
> +                )
why do we need the `if` block here? If `copy=True` was explicitly passed, then wouldn't we expect that memory not be shared regardless of `copy_on_write`?

2022-11-12 12:40 UTC, MarcoGorelli commented on pandas/tests/frame/methods/test_set_axis.py
> +        if not using_copy_on_write:
here, seeing as the default is being used, then can't we have
```python
else:
    <assert they do share memory>
```

2022-11-12 13:28 UTC, MarcoGorelli requested changes

2022-11-12 13:28 UTC, MarcoGorelli commented on pandas/tests/frame/methods/test_set_axis.py
> +                )
here you've explicitly set `copy=True`, so I don't think you need `if-else`, just do the `# check we DID make a copy` check in both cases

2022-11-12 17:00 UTC, MarcoGorelli commented on pandas/tests/frame/methods/test_set_axis.py
>          # check we DID make a copy
this comment feels a bit out of place now, perhaps move it after the `if` statement (and then an opposite one in the `else`)?

2022-11-12 18:48 UTC, MarcoGorelli approved these changes
no objections, over to @jorisvandenbossche 

![](https://i.fluffy.cc/Xr1jnB3r6dWrfwqPwNdrpnF9zW1lVp0F.gif)

2022-11-15 18:27 UTC, jorisvandenbossche reviewed
Looks good! Just the comment to add a variant of the test for Series as well

2022-11-15 18:27 UTC, jorisvandenbossche commented on pandas/tests/copy_view/test_methods.py
> +    df2.iloc[0, 1] = 0
```suggestion
    df2.iloc[0, 0] = 0
```

(just to keep it as simple as possible, for this test there is no reason to not take the first value/column)

2022-11-15 18:27 UTC, jorisvandenbossche commented on pandas/tests/copy_view/test_methods.py
> +    tm.assert_frame_equal(df, df_orig)
Could you also add a variant for Series.set_axis? (since the main signature is defined separately, it's good to cover that in this case)

2022-11-15 18:28 UTC, jorisvandenbossche commented
And you will also have to merge the main branch, to resolve the conflict from merging your other PR

2022-11-28 13:30 UTC, jorisvandenbossche commented
@Th3nn3ss small reminder in case you have time to update for the minor comments above

2022-11-30 05:25 UTC, Th3nn3ss commented
sorry about the delay @jorisvandenbossche I was preoccupied with my research project. I have made some changes. Thanks for taking a look at my PR.

2022-12-24 10:45 UTC, phofl commented on pandas/tests/copy_view/test_methods.py
> +def test_set_frame_axis(using_copy_on_write):
This confuses me a bit, why are we deleting the set_index test?

2022-12-28 17:12 UTC, phofl approved these changes

2022-12-28 17:13 UTC, merged

2022-12-28 17:13 UTC, phofl commented
Thx @Th3nn3ss