STYLE: fix pylint redefined-oute-name warnings (pandas-dev#49656)
pandas-dev/pandas pull request #49668
Opened 2022-11-12 16:58 UTC by giridhrubajyoti2002

Fixed warnings for the following files :-
- pandas/core/internals/concat.py
- pandas/core/reshape/merge.py
- pandas/io/json/_json.py

2022-11-12 17:29 UTC, MarcoGorelli requested changes
thanks for working on this!

2022-11-12 17:29 UTC, MarcoGorelli commented on pandas/core/internals/concat.py
> +import copy as _copy_
how about `import copy as stdlib_copy`?

2022-11-12 17:29 UTC, MarcoGorelli commented on pandas/core/reshape/merge.py
> +import copy as _copy_
same comment as above

2022-11-12 17:29 UTC, MarcoGorelli commented on pandas/io/json/_json.py
> +    def _get_object_parser(self, json_object) -> DataFrame | Series:
if you're no longer import `json`, then can this argument stay the same?

2022-11-12 17:29 UTC, MarcoGorelli commented on pandas/io/json/_json.py
> +        json_object,
same as above

2022-11-12 17:36 UTC, giridhrubajyoti2002 commented on pandas/core/internals/concat.py
> +import copy as _copy_
right, i am working on that.

2022-11-12 18:15 UTC, MarcoGorelli commented
will need to fixup the pre-commit checks, but apart from that looks good

2022-11-17 18:41 UTC, MarcoGorelli requested changes
@giridhrubajyoti2002 can you run
```
pre-commit run --files pandas/core/internals/concat.py
```
(and similarly for the other files you've modified) please?

2022-11-23 08:54 UTC, MarcoGorelli commented
closing as stale, thanks anyway for your PR!

2022-11-23 08:54 UTC, closed without merging