ENH: DatetimeProperties results seem to be inconsistent since missing milliseconds #49073
pandas-dev/pandas pull request #49719
Opened 2022-11-16 00:27 UTC by PedroPUCRIO

- [ X] closes #49073 (Replace xxxx with the GitHub issue number)
- [ X] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ X] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

I have added the millisecond feature to the Datetime function on Pandas. As it was discussed in the issue, it seemed inconsistent. However, I didn't change how the microseconds were being exhibited (with 6 digits instead of 3), not to break the code.

2022-11-16 17:34 UTC, mroeschke commented on pandas/core/arrays/datetimes.py
> +                + self.millisecond / 3600 / 10**3
Why was this added? I think `self.microsecond` should already include the milliseconds

2022-11-16 17:34 UTC, mroeschke requested changes
Thanks for the start:

1. Could you add tests for this functionality?
2. Could you also add this for `Timestamp` for symmetry?

2022-11-21 15:14 UTC, MarcoGorelli requested changes
thanks for working on this, but as mentioned in 

https://github.com/pandas-dev/pandas/issues/49073#issuecomment-1322213775

 I think I'd be -1 on this

2022-11-22 16:47 UTC, MarcoGorelli commented
closing as per https://github.com/pandas-dev/pandas/issues/49073#issuecomment-1323967551 , but thanks for your PR!

2022-11-22 16:47 UTC, closed without merging