STYLE: Enable unnecessary list index lookup
pandas-dev/pandas pull request #49911
Opened 2022-11-25 17:10 UTC by uzzell

- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

Associated with #48855.  Enables the Pylint type "R" warning `unnecessary-list-index-lookup`.  Also updates the list of intentionally disabled checks.

2022-11-25 17:41 UTC, MarcoGorelli requested changes
thanks for working on this

could you please:
- run the pre-commit checks (see contributing guide for how)
- fetch upstream, and rebase onto it, looks like you have some irrelevant changes in here

2022-11-25 17:41 UTC, MarcoGorelli commented on pandas/io/pytables.py
> +            bvalues.append(v.reshape(new_shape))
nice!

2022-11-28 16:47 UTC, uzzell commented
@MarcoGorelli , are you talking about the changes to `pyproject.toml`?  I took the liberty of updating the list of intentionally disabled warnings: `wrong-import-order` appeared twice in the list, while `broad-except` and `overridden-final-method` were in the list at the top of #48855 but not in the section for intentionally disabled warnings in `pyproject.toml`.

If you'd like, I can change them back.

2022-11-28 16:57 UTC, MarcoGorelli commented
ah, that's fine then, thanks for explaining!

2022-11-28 16:58 UTC, MarcoGorelli approved these changes
thanks @uzzell 

![](https://i.fluffy.cc/Xr1jnB3r6dWrfwqPwNdrpnF9zW1lVp0F.gif)

2022-11-28 16:58 UTC, merged