DEPR: enforce not-automatically aligning in DataFrame comparisons
pandas-dev/pandas pull request #49946
Opened 2022-11-28 22:52 UTC by jbrockmendel

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2022-11-28 23:08 UTC, MarcoGorelli reviewed
Changes look good to me - just got a comment, and wanted to double-check about the issue number in the whatsnew

2022-11-28 23:08 UTC, MarcoGorelli commented on doc/source/whatsnew/v2.0.0.rst
> +- Comparisons between a :class:`DataFrame` and a :class:`Series` where the frame's columns do not match the series's index raise ``ValueError`` instead of automatically aligning, do ``left, right = l
is this the right issue number?

2022-11-29 00:26 UTC, jbrockmendel commented on pandas/tests/arithmetic/test_datetime64.py
> +        ser = tm.box_expected(ser, box)
Yes, it’s a pattern we use elsewhere

2022-11-29 00:26 UTC, jbrockmendel commented on doc/source/whatsnew/v2.0.0.rst
> +- Comparisons between a :class:`DataFrame` and a :class:`Series` where the frame's columns do not match the series's index raise ``ValueError`` instead of automatically aligning, do ``left, right = l
Nope, will update. Thanks

2022-11-29 08:14 UTC, MarcoGorelli approved these changes

2022-11-29 08:17 UTC, MarcoGorelli requested changes
Ah wait, the related ASV checks are failing
```
2022-11-29T00:54:09.9434614Z [  1.81%] ··· ...thSeriesAxis.time_frame_op_with_series_axis1        6/12 failed
2022-11-29T00:54:09.9435374Z [  1.81%] ··· ========== ==========
2022-11-29T00:54:09.9435738Z                 opname             
2022-11-29T00:54:09.9436168Z               ---------- ----------
2022-11-29T00:54:09.9436526Z                   eq       failed  
2022-11-29T00:54:09.9437238Z                   ne       failed  
2022-11-29T00:54:09.9437518Z                   lt       failed  
2022-11-29T00:54:09.9437736Z                   le       failed  
2022-11-29T00:54:09.9437960Z                   ge       failed  
2022-11-29T00:54:09.9438183Z                   gt       failed  
2022-11-29T00:54:09.9438611Z                  add      12.0±0ms 
2022-11-29T00:54:09.9438899Z                  sub      11.8±0ms 
2022-11-29T00:54:09.9439204Z                truediv    11.8±0ms 
2022-11-29T00:54:09.9439479Z                floordiv   42.0±0ms 
2022-11-29T00:54:09.9439765Z                  mul      11.6±0ms 
2022-11-29T00:54:09.9440049Z                  pow      31.0±0ms 
2022-11-29T00:54:09.9440264Z               ========== ==========
```

Good to have fixed the flakiness, I'd got so used to seeing that check fail I was going to just restart it, but this time it's not a false positive

2022-11-30 08:12 UTC, MarcoGorelli approved these changes
Looks good to me!

2022-12-01 22:06 UTC, mroeschke approved these changes

2022-12-01 22:06 UTC, merged

2022-12-01 22:06 UTC, mroeschke commented
Thanks @jbrockmendel