BUG: fix  AttributeError: CompileError object has no attribute orig
pandas-dev/pandas pull request #50053
Opened 2022-12-04 13:24 UTC by thanhbui221

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2022-12-04 13:29 UTC, thanhbui221 commented
Pandas version: 1.5.2.
AttributeError: CompileError object has no attribute orig

2022-12-05 04:10 UTC, nguyenmphu commented on pandas/io/sql.py
> +            if hasattr(err, 'orig'):
```suggestion
            if hasattr(err, "orig"):
```

2022-12-05 09:53 UTC, thanhbui221 commented
Function pandas.DataFrame.to_sql() writes records stored in a DataFrame to a SQL database. Databases supported by SQLAlchemy are supported. This function will call 'sql.py' in 'pandas/pandas/io/sql.py'.

When applied to a database supported by SQLAlchemy, 'sql.py' will use the class 'SQLAlchemyEngine(BaseEngine)', which has this line causing the reported bug: https://github.com/pandas-dev/pandas/blob/main/pandas/io/sql.py#L1392.

Basically, method 'insert_records' handles 'SQLAlchemyError' exceptions. But not all child class of base class 'SQLAlchemyError' has the attribute 'orig'. Doc: https://docs.sqlalchemy.org/en/14/core/exceptions.html

Therefore, adding a checking attribute step will fix this bug.

2022-12-05 13:55 UTC, phofl requested changes
Hi, 1.5.2 is already out, so this has to go to 1.5.3.

Also, please add tests

2023-01-18 20:27 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2023-01-18 20:27 UTC, closed without merging