Improve to_datetime bounds checking
pandas-dev/pandas pull request #50183
Opened 2022-12-11 15:50 UTC by rebecca-palmer

to_datetime(errors='raise') is supposed to raise an exception on out-of-bounds input.  However, it uses rounding to integer for this bounds checking but not the actual conversion, and hence, for input just outside the bounds it may instead return NaT ([on x86](https://buildd.debian.org/status/fetch.php?pkg=pandas&arch=all&ver=1.5.2%2Bdfsg-1&stamp=1669856039&raw=0)) or output clipped to the bounds ([on arm](https://buildd.debian.org/status/fetch.php?pkg=pandas&arch=arm64&ver=1.5.2%2Bdfsg-1&stamp=1669872650&raw=0)).

It also assumes that converting NaN to int gives NaT, which [may not be true on unusual hardware](https://buildd.debian.org/status/fetch.php?pkg=pandas&arch=riscv64&ver=1.4.3%2Bdfsg-1&stamp=1659694881&raw=0).  (This was how I originally noticed the problem, as Debian tries to build packages on a wide range of hardware.)

This patch fixes both issues.  (In the Debian logs linked here, search for 'near-limits test', the first run is unpatched 1.3.5, the second run is patched 1.5.x.)

Its effect on speed is unclear: it is [sometimes faster](https://buildd.debian.org/status/fetch.php?pkg=pandas&arch=amd64&ver=1.5.1%2Bdfsg-1&stamp=1667870121&raw=0) and [sometimes slower](https://buildd.debian.org/status/fetch.php?pkg=pandas&arch=amd64&ver=1.5.2%2Bdfsg-1&stamp=1669859491&raw=0), possibly because other load on the build machines varies.

- [this bug does not appear to be previously reported ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [X] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [X] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [N/A ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2022-12-12 12:51 UTC, MarcoGorelli commented on pandas/_libs/tslib.pyx
>              fvalues = iresult.astype("f8") * mult
First, thanks for doing this

Second, I haven't looked closely at this yet (but will do!), just wanted to ask - would this overlap with, or supersede, https://github.com/pandas-dev/pandas/pull/48705 ?

2022-12-13 11:04 UTC, MarcoGorelli reviewed
If I've understood correctly:

Before:
- `values` would get cast to `i8` (thus losing some precision, e.g. `292.32702463` -> `292`)
- the `i8` cast would then get cast back to `f8`, but once this has been done, the result could be smaller than what you started with, because of the loss of precision
- the bounds check might (erroneously) not pass

Whereas now:
- `values` are multiplied directly with `mult`
- as there's no loss of precision, the out-of-bounds check no longer erroneously passes

That's one change. The other change is to use `values != values` in the mask, as was done in #48705. Perhaps let's merge that one first, then rebase this one?

I've just left a question, as one change looks good but orthogonal (it's fine, just checking)

2022-12-13 11:04 UTC, MarcoGorelli commented on pandas/_libs/tslib.pyx
> -                fresult[mask] = 0
Just for my understanding, is this just a refactor (reuse `fvalues`, as it was already calculated above)?

2022-12-13 13:24 UTC, MarcoGorelli requested changes
https://github.com/pandas-dev/pandas/pull/48705 is in - could you rebase please and we can get this in too?

2023-01-18 20:25 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2023-01-18 20:56 UTC, MarcoGorelli commented
I'll add a commit here when I get a chance (hopefully early next week), I think we should ship this, and @rebecca-palmer did some seriously good work here

2023-01-19 00:01 UTC, jbrockmendel commented
> Unrelated to my changes, but it looks like https://github.com/pandas-dev/pandas/pull/50263 may have accidentally undone the effect of https://github.com/pandas-dev/pandas/pull/50301 for some input types - @jbrockmendel ?

That's entirely plausible.  Would be happy to see a PR fixing that.

2023-01-19 07:51 UTC, rebecca-palmer commented on pandas/_libs/tslib.pyx
>              fvalues = iresult.astype("f8") * mult
and fvalues is now float-input-only, so this possible waste of time no longer exists

2023-01-19 07:54 UTC, rebecca-palmer commented
That CI fail looks like the same one main then had - retrying.

2023-01-19 19:08 UTC, MarcoGorelli reviewed
Looks good to me - only minor comments would be to add a whatsnew note in the 2.0.0 bug fixes section, and ideally to have a link to the github issue (or to the pull request if there's no issue) in the test (check some other tests for examples)

2023-01-19 21:26 UTC, rebecca-palmer commented on pandas/_libs/tslib.pyx
> +            fvalues = (values * mult).astype("f8")
Now uses copy=False

2023-01-19 21:29 UTC, rebecca-palmer commented
Fixed, but also removed the unnecessary copy, so wait for the CI to check that it really is unnecessary.

2023-01-19 21:32 UTC, MarcoGorelli approved these changes
Looks good to me pending green, thanks @rebecca-palmer !

2023-01-20 07:36 UTC, rebecca-palmer commented
Does the Windows CI timing out suggest there's a hang bug in this, or does that just happen sometimes?

(Numpy Dev also fails on main, for reasons that are nothing to do with pandas: numpy/numpy#23033)

2023-01-20 17:25 UTC, mroeschke approved these changes

2023-01-20 17:25 UTC, merged