Index order fix
pandas-dev/pandas pull request #50193
Opened 2022-12-11 22:45 UTC by codestorm177

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2022-12-11 23:10 UTC, phofl commented on pandas/core/indexes/api.py
> +            result = Index(result)
Pretty sure that this will break tests. If sort=True we should still sort.

Please link the issue in your pr

2022-12-12 00:01 UTC, jreback requested changes

2022-12-12 00:01 UTC, jreback commented on pandas/tests/frame/test_api.py
> +        assert df1.iloc[0]["a"] == 1 and df1.iloc[1]["a"] == 2 and df1.iloc[2]["a"] == 3
construct the expected
frame and use assert_frame_equal

2022-12-13 13:28 UTC, phofl commented on pandas/tests/frame/test_api.py
> +        df1_correct = DataFrame()
Please construct this in one call, not multiple

Tests are failing

2023-01-18 20:22 UTC, closed without merging