avoid some upcasting when its not the purpose of the test
pandas-dev/pandas pull request #50493
Opened 2022-12-29 21:12 UTC by MarcoGorelli

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2022-12-29 21:26 UTC, MarcoGorelli commented on pandas/tests/frame/test_query_eval.py
>          df.iloc[0, 0] = pd.NaT
here, `df[0]` is first created of `int` dtype, and then `df.iloc[0, 0] = pd.NaT` upcasts it to `object`. Might as well create it of dtype `object` in the first place, as the purpose of this test comes in the lines below (`df.query(...`)

2022-12-29 21:26 UTC, MarcoGorelli commented on pandas/tests/frame/test_query_eval.py
>          df.iloc[0, 0] = pd.NaT
same as above

2022-12-29 21:26 UTC, MarcoGorelli commented on pandas/tests/frame/test_reductions.py
>          df2.loc[0, "foo"] = "a"
in both `df1` and `df2`, column `'foo'` is initially created to be of dtype `'int'`, and then by setting an element to a string it is upcasting to `object`. This is done on purpose to check the `numeric_only` flag below

Might as well declare column `'foo'` to be of dtype `object` from the start then

2022-12-29 21:26 UTC, MarcoGorelli commented on pandas/tests/groupby/test_timegrouper.py
> +            ).astype({"Buyer": object})
column `'Buyer'` is originally set to `0`, and then some strings are set (thus upcasting to `object`). Might as well construct it as `object` from the start - furthermore, this is the `expected` dataframe, so it doesn't change what's being tested

2022-12-29 21:26 UTC, MarcoGorelli commented on pandas/tests/series/methods/test_replace.py
>          df.iloc[2, 2] = ""
the third column `df[2]` is initially made up of ints, and then an element is set to  `' '` (thus upcasting to object)

might as well set to `object` from the start, as the purpose of the test is on the line below `df.replace(...`

2022-12-29 22:02 UTC, rhshadrach requested changes
Looks good - I would recommend adding comments as otherwise it seems easy for a contributor to see thiese tests and think the `astype` is unnecessary.

2022-12-30 09:02 UTC, MarcoGorelli commented
good call, thanks

2022-12-30 15:12 UTC, rhshadrach approved these changes
lgtm

2023-01-02 09:02 UTC, merged