ENH: DTI/TDI as_unit
pandas-dev/pandas pull request #50616
Opened 2023-01-07 04:41 UTC by jbrockmendel

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2023-01-08 03:01 UTC, gfyoung commented on doc/source/whatsnew/v2.0.0.rst
> +- Added :meth:`DatetimeIndex.as_unit` and :meth:`TimedeltaIndex.as_unit` to convert to different resolutions; supported resolutions are "s", "ms", "us", and "ns" (:issue:`??`)
```suggestion
- Added :meth:`DatetimeIndex.as_unit` and :meth:`TimedeltaIndex.as_unit` to convert to different resolutions; supported resolutions are "s", "ms", "us", and "ns" (:issue:`50616`)
```

2023-01-08 10:09 UTC, phofl commented on pandas/core/indexes/datetimelike.py
> +    def as_unit(self: _TDT, unit: str) -> _TDT:
Can we somehow add a public docstring?

2023-01-08 21:22 UTC, phofl approved these changes

2023-01-09 20:07 UTC, MarcoGorelli requested changes
Nice!

I just don't really follow the note on supported resolutions - should non-supported ones raise?

2023-01-09 20:07 UTC, MarcoGorelli commented on doc/source/whatsnew/v2.0.0.rst
> +- Added :meth:`DatetimeIndex.as_unit` and :meth:`TimedeltaIndex.as_unit` to convert to different resolutions; supported resolutions are "s", "ms", "us", and "ns" (:issue:`50616`)
looks like other units work

e.g.
```python
In [24]: dti = date_range('2000', periods=10)

In [25]: dti.as_unit('D').unit
Out[25]: 'D'
```

should this raise?

2023-01-09 21:04 UTC, jbrockmendel commented
> I just don't really follow the note on supported resolutions - should non-supported ones raise?

good catch, will fix.

2023-01-09 21:13 UTC, MarcoGorelli approved these changes
Looks good to me pending green, thanks @jbrockmendel !

2023-01-09 22:35 UTC, mroeschke approved these changes

2023-01-10 11:48 UTC, merged