DOC Fix EX01 errors - added example
pandas-dev/pandas pull request #51288
Opened 2023-02-10 10:23 UTC by DeaMariaLeon

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Towards #37875

2023-02-10 15:01 UTC, MarcoGorelli requested changes

2023-02-10 15:01 UTC, MarcoGorelli commented on pandas/core/base.py
> +        (3,)
thanks for your PR! I think just the first one should be fine, no need to repeat the example

2023-02-10 22:32 UTC, phofl approved these changes

2023-02-11 17:51 UTC, MarcoGorelli approved these changes
thanks @DeaMariaLeon !

![](https://i.fluffy.cc/txmjpfs0Svcz29tn0vtDVvLR0KhWh82h.gif)

2023-02-11 17:51 UTC, merged

2023-02-11 18:13 UTC, DeaMariaLeon commented
Thanks again :)