CI pre-commit autoupdate
pandas-dev/pandas pull request #51290
Opened 2023-02-10 10:50 UTC by MarcoGorelli

the automated one didn't run, maybe because the diff is too large?

this touches a lot of files, but it's mostly just `black` removing newlines

2023-02-10 22:43 UTC, topper-123 commented
> but it's mostly just `black` removing newlines

Is there anything else? I cab only see reoval of newlines, but there are a lot, so may I'm missing something?

2023-02-11 11:50 UTC, rhshadrach requested changes

2023-02-11 11:50 UTC, rhshadrach commented on .pre-commit-config.yaml
> -        additional_dependencies: [black==22.10.0]
Update environment.yml too?

2023-02-11 16:11 UTC, MarcoGorelli commented
> Could also upgrade autotyping to 23.2.0 (pyright as well but that will probably require some code changes).

I tried this but got
```
IndexError: string index out of range

Failed to codemod /home/marcogorelli/pandas-dev/pandas/core/arrays/categorical.py
```
I'll see if this needs reporting to them

> Is there anything else? I cab only see removal of newlines, but there are a lot, so may I'm missing something?

I don't think so, but perhaps let's keep that to a separate PR

2023-02-11 19:09 UTC, rhshadrach approved these changes
lgtm

2023-02-11 19:15 UTC, MarcoGorelli commented
thanks for reviewing!

2023-02-11 19:15 UTC, merged