DOC: fix EX02 docstring errors for three plotting docstrings
pandas-dev/pandas pull request #51596
Opened 2023-02-23 20:19 UTC by phershbe

Some work towards issue https://github.com/pandas-dev/pandas/issues/51236
The issue is being worked on by several people and has more docstrings remaining to do.

Makes docstrings pass for:
`pandas.plotting.andrews_curves`
`pandas.plotting.autocorrelation_plot`
`pandas.plotting.lag_plot`

2023-02-23 20:33 UTC, phershbe commented
@MarcoGorelli This is currently a draft because I'm unsure about something.

I got these docstrings to pass by changing instances of `AxesSubplot` in the `Expected` outputs to what the `Got` outputs said in a few places, I don't know if this is correct though. The other options would be that there are mistakes in the docstrings in the ways the methods are called or in the parameters passed in or something, or that there are mistakes in the methods themselves. 

I don't know what I would be searching for in the alternative possibilities that I mentioned and maybe what I did was correct anyway and nothing else is necessary, so I thought I would make a draft and ask.

2023-02-23 20:57 UTC, MarcoGorelli commented
Hey - looks like these are failing in CI when run as doctests
```
https://github.com/pandas-dev/pandas/actions/runs/4256504265/jobs/7405473685
```
But then they do pass when run as part of the docstring validation job...I don't know why that might be, I'll take a look

2023-02-23 23:58 UTC, phershbe commented
@MarcoGorelli Oh, maybe it's because `infer_dtype`  is not passing `./ci/code_checks.sh docstrings`. I think it was accidentally broken in another pull request on this issue, or maybe broken for some other reason, or maybe it was broken by this pull request. I was pretty sure before that that mistake wasn't from this pull request, but I'll check soon here. I figured that we would clean it up later but didn't think about that it would be necessary for the validation job to clear.

2023-02-27 11:39 UTC, MarcoGorelli requested changes
I think we should just doctest+SKIP these plotting ones, see

https://github.com/pandas-dev/pandas/pull/51614#pullrequestreview-1315410861

2023-02-28 05:02 UTC, closed without merging

2023-02-28 05:07 UTC, phershbe commented
@MarcoGorelli uh oh, I'm not very good at Git yet and was having a lot of trouble fetching from the main upstream repository and then pushing my changes without conflicts. I'm working on opening a new pull request now, sorry for making a mess of this.