API/BUG: infer_dtype_from_scalar with non-nano
pandas-dev/pandas pull request #52212
Opened 2023-03-26 00:41 UTC by jbrockmendel

- [x] closes #51196 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Needs whatsnew and targeted tests, opening to see if there are opinions about doing this as a bugfix or waiting to do it as an API change in 3.0

2023-05-04 00:32 UTC, jbrockmendel commented
@MarcoGorelli thoughts on if/how this is worth pursuing?

2023-05-05 11:32 UTC, MarcoGorelli commented
sorry, missed this. I'd have thought this was fine as a bug fix - I'm at jupytercon next week though so may be a bit slow to review, but will take a look when I get a chance

2023-05-15 15:03 UTC, MarcoGorelli requested changes
nice! just got some minor comments

2023-05-15 21:01 UTC, jbrockmendel commented on pandas/tests/series/test_constructors.py
> +            )
is strict=True no longer the default?  if so, will update.  (also if so: yikes)

2023-05-15 21:04 UTC, jbrockmendel commented on pandas/tests/frame/test_constructors.py
> +        np.dtype("M8[ns]").name
nope, will remove

2023-05-16 13:06 UTC, MarcoGorelli commented on pandas/tests/series/test_constructors.py
> +            )
nvm, ignore me, it's configured to be the default

https://github.com/pandas-dev/pandas/blob/730439603919b9a38a54477f768b775f1aaf6412/pyproject.toml#L441

2023-05-16 13:13 UTC, MarcoGorelli approved these changes
Changes look good to me, I think it'd be OK to get this into 2.1 as it'd be a bug fix

do you want to add a whatsnew note?

2023-05-17 17:44 UTC, MarcoGorelli commented
🤔 not sure if this might be related
```
FAILED pandas/tests/frame/methods/test_reindex.py::TestDataFrameSelectReindex::test_reindex_tzaware_fill_value - ValueError: Unexpected value for 'dtype': 'int32'. Must be 'datetime64[s]', 'datetime64[ms]', 'datetime64[us]', 'datetime64[ns]' or DatetimeTZDtype'.
```

2023-05-18 12:56 UTC, MarcoGorelli approved these changes
Looks good to me

@mroeschke any comments, or good to go?

2023-05-18 16:11 UTC, mroeschke approved these changes

2023-05-18 16:11 UTC, merged

2023-05-18 16:11 UTC, mroeschke commented
Thanks @jbrockmendel