BUG: Index with duplicate labels raises ValueError in Dataframe.query #51815
pandas-dev/pandas pull request #52224
Opened 2023-03-26 16:14 UTC by steliospetrakis02

- [x] closes #51815 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2023-03-27 18:12 UTC, mroeschke requested changes
The fix should not require a new method on the DataFrame

2023-03-28 15:56 UTC, steliospetrakis02 commented
Hey @mroeschke , just wanted to give you a quick update on my progress. I've integrated the latest version of my code into the 'query()' function, which should help streamline the overall process. Let me know if you have any questions or concerns.

2023-03-28 18:03 UTC, mroeschke commented on pandas/core/frame.py
> +    def query(self,expr: str, engine='numexpr', *, inplace: bool = False, **kwargs) -> DataFrame | None:
This signature should no change

2023-03-28 18:04 UTC, mroeschke requested changes

2023-03-28 18:04 UTC, mroeschke commented on pandas/core/frame.py
> +            res = self.eval(expr, **kwargs)
The bug in `eval` should be addressed directly instead of falling back like this

2023-03-30 12:18 UTC, steliospetrakis02 commented
Hello @mroeschke, I have made modifications to the query() function to check for duplicate index labels, but some tests have failed. As a new contributor to this open-source project, I would appreciate your expert opinion on whether I should make further changes to the code or focus on fixing the failing tests.

2023-03-30 16:01 UTC, mroeschke commented
> As a new contributor to this open-source project

Honestly, I would suggest tackling an issue label `good first issue` first rather than this bug. A fix should ideally not fail existing tests and the solution should not involve falling back to a try/except

2023-04-02 15:47 UTC, steliospetrakis02 commented
Hello @mroeschke , I'm not sure if you saw, but I have made changes to the implementation. It no longer requires falling back to a try/except. Instead, I added an if statement to check for duplicate indexes.It covers all the constraints that you have informed me of, and it is currently working.

   
 if self.index.duplicated().any():
            engine='numexpr'
            # Create a copy of the dataframe with a unique index to avoid reindexing errors
            unique_index = RangeIndex(len(self.index))
            df_copy = self.copy()
            df_copy.index = unique_index

            # Filter the copied dataframe
            filtered_df = df_copy.query(expr, engine=engine)

            # Map the filtered index back to the original index labels
            index_mapping = dict(zip(unique_index, self.index))
            filtered_df.index = filtered_df.index.map(index_mapping)
            
            return filtered_df

 I apologize for the frequent comments, I don't mean to be a bother.

2023-04-02 18:16 UTC, mroeschke requested changes

2023-04-02 18:16 UTC, mroeschke commented on pandas/core/frame.py
> +        if self.index.duplicated().any():
This is a similar workaround like the previous try/except solution. Ideally `self.eval(expr, **kwargs)` should be fixed directly, not working around it

2023-05-03 00:16 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2023-05-03 00:16 UTC, closed without merging