BUG: args offset in Timestamp.__new__ causes bugs
pandas-dev/pandas pull request #52344
Opened 2023-04-01 06:53 UTC by AlexKirko

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2023-04-01 06:54 UTC, AlexKirko commented
WIP. The same tests as in #52221, different solution.

2023-04-05 07:15 UTC, AlexKirko commented on asv_bench/benchmarks/tslibs/timestamp.py
> +        Timestamp(2020, 1, 1, 0, 0, 0)
An additional benchmark for future regressions might be helpful.

2023-04-05 08:00 UTC, AlexKirko commented
@mroeschke @jbrockmendel @jreback 
Hello, everyone. Here is the Timestamp refactor to using `*args, **kwargs` that I promised. This version fixes both the fold and the positional vs keyword inconsistency bugs. There is some performance gain when building from a Timestamp. There is a performance loss when building from positional arguments (added a check to the asv benchmark suite).

Had to rewrite most of the constructor, because naively switching to `*args, **kwargs` without changing the rest of the code had resulted in a 50-60% hit for most of the use cases.

Please review. Any suggestions on improving the performance of the positional arguments case would be appreciated.

2023-04-07 18:10 UTC, mroeschke commented on pandas/_libs/tslibs/timestamps.pyx
> +            return args[0]
What if a user passes `Timestamp(Timestamp(...), tz="UTC")`? I _think_ that should localize the timestamp?

2023-04-07 18:15 UTC, mroeschke commented on pandas/_libs/tslibs/timestamps.pyx
> +            if kwargs:
Should we raise if a user passes `Timestamp("2020-01-01" , foo="bar")`?

2023-04-07 18:21 UTC, mroeschke commented on pandas/_libs/tslibs/timestamps.pyx
> +                hour = kwargs.get("hour", hour)
Shouldn't we raise if a user passes the same argument by position and keyword e.g.

```
In [4]: datetime.datetime(2020, 1, 1, day=1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[4], line 1
----> 1 datetime.datetime(2020, 1, 1, day=1)

TypeError: argument for function given by name ('day') and position (3)
```

2023-04-08 17:52 UTC, AlexKirko commented
Doesn't look like the Parquet arrows in CircleCI have anything to do with this PR.

2023-04-08 17:57 UTC, jreback requested changes

2023-04-08 17:57 UTC, jreback commented on pandas/_libs/tslibs/timestamps.pyx
> +            day = kwargs.get("day")
is there anyway to simply translate the args to kwargs near the top

this looks so fragile and error prone

2023-04-08 18:44 UTC, jbrockmendel commented
i know i suggested the args/kwargs pattern, but... is there an alternative way out of the current problem by being stricter in disallowing mixed positional/keyword?

2023-04-08 19:24 UTC, jreback commented
> i know i suggested the args/kwargs pattern, but... is there an alternative way out of the current problem by being stricter in disallowing mixed positional/keyword?

+1 in this (or allow only fully qualified positionals - eg ymdhms required plus kwarg for example)

2023-04-09 06:59 UTC, AlexKirko commented
@jbrockmendel @jreback  Another option is to just use the Python>3.8 [args-only syntax](https://peps.python.org/pep-0570/) to make everything up to tzinfo positional-only. A couple of issues I see:

* this breaks the behavior compatibility with datetime. Users will construct the way they do with `datetime` and get errors. WIll need to make those clear enough that they don't think this is unexpected behavior.
* this breaks old code. I personally built Timestamps like `Timestamp(2020, 1, 1, hour=20, minute=30, second=0)` in my applications, adding kwargs only where I needed to make it clear what the Timestamp would contain. This is a pretty standard practice in finance where I come from.
* going through a deprecation cycle would keep the bug unfixed (unless we temporarily go with decoration or the current approach and add deprecation warnings, which is what we should do in that case)
* The arg offset bug is present in version 1.5.x too. A fix that breaks old code would not be possible/available there.
* tzinfo would become positional-only, I assume. tz will remain kwarg-only. This would look weird to users and probably be reported as an issue.

Because of these points, I didn't think this option was on the table.

Let's come up with an approach that you will be able to accept if it's decently done, and I will implement it. But please be aware that I won't be redoing this from scratch a fourth time, so let's get it right (I'll be happy to go back to one of the previous options though if we don't like the third solution).

I believe that the current arg offset in Timestamp is a buggy PITA that we took advantage of to maintain performance and keep code readable. The fix will either be a kludge, be harder to maintain, or break a bunch of code. I don't see a solution that does neither of those but would be happy to be wrong.

2023-04-09 07:12 UTC, AlexKirko commented
Unfortunately, I don't think there is a way of fixing this outside of using `*args, **kwargs` or enforcing the positional/kwargs division.

2023-04-21 15:57 UTC, jbrockmendel commented
@AlexKirko you make goods points, thanks for thinking through the idea that i clearly didn't.  I'll give this a close look.  Thanks for being patient.

2023-04-21 18:34 UTC, jbrockmendel commented on pandas/_libs/tslibs/timestamps.pyx
> +    def __new__(cls, *args, **kwargs):
does this get rendered in the docs somewhere?

2023-06-14 11:26 UTC, AlexKirko commented
A bit sick at the moment, will come back to it in a couple days once I'm better.

2023-06-25 13:34 UTC, AlexKirko commented
Back among the living. The illness and the job change have cost me some time.

2023-07-02 20:13 UTC, jbrockmendel commented on doc/source/whatsnew/v2.1.0.rst
> +- Bug in :class:`Timestamp` raising an error when passing fold when constructing from positional arguments.
can you put "fold" in quotes/ticks

2023-07-02 20:14 UTC, jbrockmendel commented on pandas/_libs/tslibs/timestamps.pyx
> +    def __new__(cls, *args, **kwargs):
@AlexKirko any idea about this?

2023-07-02 20:19 UTC, jbrockmendel commented
Is there any viable path to splitting this into smaller pieces?  This seems like a very difficult problem and is easy for me and other reviewers to be lazy about reviewing

2023-07-03 15:58 UTC, AlexKirko commented
> Is there any viable path to splitting this into smaller pieces? This seems like a very difficult problem and is easy for me and other reviewers to be lazy about reviewing

The bigger problem, to be honest, is me having been either swamped with work or sick this past month.

In my opinion, splitting this into multiple PRs that make sense is possible, only if we stop caring about the performance of the initial implementation, and put the necessary performance improvements into separate PRs. It would make this easier to review but lead to an initial PR that is very slow in some use cases.

2023-08-11 01:01 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2023-08-11 07:00 UTC, AlexKirko commented
I have merged in main, and I will try another approach next week, so I would like to reopen the request for now.

The problem here is that it's a "I will hate it when I see it" situation. There are three solutions that come to mind, and I've tried and submitted for review two. The third is terrible, in my opinion.
1. decorate the constructor. Very slow, very easy to read and support.
2. fix the kwargs/args order inside the constructor. Minimal performance impact, but is ugly and makes the code harder to support. This is the current approach in the branch that everyone seems to also reject.
3. Use the positional-only syntax. Breaks compatibility with datetime, breaks user code. I think it's much worse than the previous two approaches, but I can try it next week for illustrative purposes if nothing else.

No one has suggested another solution, and I'm out of ideas. I personally think that option 2 (the current one) is fine. Yes, it's ugly, but it doesn't slow things down too much or break old code and datetime compatibilty.

I'm well aware that all the approaches have significant downsides, but either someone needs to suggest an idea I haven't considered, or we need to choose. I'll try out the positional-only solution next week for illustration purposes, but I think it's the worst. Breaking API compatibility with current code to fix a bug is just wrong.

We can also leave the bug in if fixing it is worse than the current state of things, but that's also not great, to put it in mildly.

If I had the authority to take the responsibility for this decision, I'd just pick the current solution and move on.

I'd be happy to hear your thoughts, @mroeschke . You have more experience, so maybe you see a way out here.

2023-08-11 08:54 UTC, jreback reviewed
option 2 (current approach) looks like a good soln

the code complexity is not too bad - commented pretty well already

2023-08-11 09:33 UTC, AlexKirko commented
Okay, then I'll focus on cleaning up the current solution instead. Will try to make the changes as painless as possible to support.

2023-09-12 10:17 UTC, AlexKirko commented
I apologize for being glacially slow on this. Finally had an opportunity to review.

The MR is in decent shape except for the docs issue. We change the signature to `*args, **kwargs` and this gets reflected in the auto-generated docs. I suppose there is nothing to do here except implement an ad-hoc override for the docs.

2024-01-31 18:53 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2024-01-31 18:53 UTC, closed without merging