ENH: Infer best datetime format from a random sample
pandas-dev/pandas pull request #52626
Opened 2023-04-12 13:52 UTC by LeoGrin

- [x] closes #52508 
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/v2.1.0.rst` file if fixing a bug or adding a new feature.

2023-04-12 14:45 UTC, MarcoGorelli requested changes
thanks for working on this

couple of initial comments:
- this looks very complicated, is a simpler solution possible?
- this should be deterministic, and shouldn't depend on the result of `np.random` - can we use, say, the first 10 non-null elements? Or 10 equally spaced elements?

2023-04-12 15:01 UTC, LeoGrin commented
Thanks for the quick reply!
> * this looks very complicated, is a simpler solution possible?
Probably, I'll try to make it simpler.
> * this should be deterministic, and shouldn't depend on the result of `np.random` - can we use, say, the first 10 non-null elements? Or 10 equally spaced elements?
Will fix

2023-04-24 13:08 UTC, LeoGrin commented
@MarcoGorelli this is ready for review (don't know if I should tag or just wait)
The failing build seems to be related to #52853, not related to the PR.

2023-04-24 13:40 UTC, MarcoGorelli requested changes
thanks for updating!

this still look quite complicated - this is going to have be maintained long-term by multiple people and so I'm a bit hesitant to add a lot of code. Is there a simpler solution which would still improve datetime format inference?

2023-04-24 13:40 UTC, MarcoGorelli commented on doc/source/whatsnew/v0.19.0.rst
>     pd.to_datetime([1, "foo"], errors="coerce")
why is this needed?

2023-05-02 13:19 UTC, MarcoGorelli commented
> maybe for now we could directly fall back to dateutil when format="mixed" is provided?

yeah `format='mixed'` means that no format inference should take place

2023-06-02 12:24 UTC, MarcoGorelli commented
Thanks for your PR

I'm afraid this introduces too much complexity, sorry, it's going to be too hard to maintain, there's already very few people comfortable with this part of the codebase 

If you can find a simpler solution which improves format inference without greatly increasing the maintenance burden, then we can take. For example, just trying 5 elements and taking a majority vote would probably be an improvement and still be quite simple

2023-06-02 12:24 UTC, closed without merging