Typing: Narrow down types of arguments (NDFrame) #10
pandas-dev/pandas pull request #52754
Opened 2023-04-18 15:11 UTC by mKlepsch

[Typing: Narrow down types of arguments (NDFrame) #10](https://github.com/noatamir/pydata-workshop/issues/10)
Made these specifications to Literals:
- [ X] Specify date_unit in to_json more precisely
- [ X] Specify mode in to_hdf more precisely
- [ X] Specify complib in to_hdf more precisely
- [ X] Specify format in to_hdf more precisely

@phofl @jorisvandenbossche @noatamir @MarcoGorelli

2023-04-18 15:17 UTC, MarcoGorelli requested changes
thanks for your pr

2023-04-18 15:17 UTC, MarcoGorelli commented on pandas/core/generic.py
> +        date_unit: Literal["s", "ms", "us", "ns"] = "ms",
this one seems broadly useful - perhaps let's define it as `TimeUnit` in `_typing.py` and import it here?

2023-04-18 15:17 UTC, MarcoGorelli commented on pandas/core/generic.py
> +        complib: ["zlib", "lzo", "bzip2", "blosc"] | None = None,
missing literal

2023-04-20 14:56 UTC, mKlepsch commented
Hi, I can't figure out why it is still failing the CI. Could you give me some pointers?

2023-04-20 15:25 UTC, MarcoGorelli commented
you'll need to run the pre-commit hooks, please check the contributing guide for how to do that

2023-04-22 09:57 UTC, phofl commented
You can do:

```
pre-commit install
pre-commit run --all-files
```

(It's probably a space at the end of the line, which is disallowed

2023-04-22 09:58 UTC, phofl reviewed
Looks good after fixing pre-commit

2023-04-24 18:38 UTC, mroeschke approved these changes

2023-04-24 18:44 UTC, phofl approved these changes

2023-04-25 00:52 UTC, merged

2023-04-25 00:52 UTC, mroeschke commented
Thanks @mKlepsch