Metadata in DataFrame.mean
pandas-dev/pandas pull request #52925
Opened 2023-04-26 05:31 UTC by jiawei-zhang-a

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
The goal here is to make progress on https://github.com/pandas-dev/pandas/issues/28283.

2023-04-26 16:16 UTC, mroeschke requested changes

2023-04-26 16:16 UTC, mroeschke commented on pandas/core/frame.py
> +            if hasattr(result, "__finalize__")
This should be addressed more specifically then checking this way

2023-04-26 23:31 UTC, jiawei-zhang-a commented
[only propogate when it is Dataframe of Series](https://github.com/pandas-dev/pandas/pull/52925/commits/e842f9a8442d0eb954e5d395771d5d5f3570131f)

2023-04-27 20:57 UTC, jiawei-zhang-a commented
Mr. Roeschke, I am sorry to trouble you again, would you mind telling me something about Minimum Versions Unit Test?,please I look through all the test failures, but I did not find anything directly related to metadata propagation, do you know what should I do if I want to solve this problem

2023-05-30 17:51 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2023-05-30 17:51 UTC, closed without merging