DOC: Remove 1.2 versionadded and changed
pandas-dev/pandas pull request #52940
Opened 2023-04-26 18:38 UTC by phofl

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2023-04-26 20:15 UTC, mroeschke commented
```
023-04-26T18:50:42.6547459Z /home/runner/work/pandas/pandas/pandas/io/excel/_base.py:docstring of pandas.io.excel._base.read_excel:89: WARNING: Bullet list ends without a blank line; unexpected unindent.
2023-04-26T18:50:42.6548203Z /home/runner/work/pandas/pandas/pandas/io/excel/_base.py:docstring of pandas.io.excel._base.read_excel:90: WARNING: Block quote ends without a blank line; unexpected unindent.
```

2023-04-27 15:58 UTC, mroeschke commented
The same errors in my last comment are appearing

2023-04-27 22:36 UTC, datapythonista approved these changes
Looks good other than the CI problems.

I don't fully understand why we want to remove the indentation of the versionchanged in the Excel bullet points, but I trust you've checked the render and looks fine.

Out of curiosity, do we have a written policy for when those versionchanged/versionadded are removed?

2023-04-28 02:08 UTC, rhshadrach requested changes

2023-04-28 02:08 UTC, rhshadrach commented on pandas/io/excel/_base.py
> +      ``pyxlsb`` will be used.
These first two lines are a lead in to the bullet points that follow.

2023-04-28 02:08 UTC, rhshadrach commented on pandas/io/excel/_base.py
> +          `pyxlsb <https://pypi.org/project/pyxlsb/>`_ will be used.
Same as above

2023-05-04 20:59 UTC, rhshadrach requested changes
Looks like the change to indent is causing warnings in the docs build for io.excel.

2023-05-04 20:59 UTC, rhshadrach commented on pandas/io/excel/_base.py
> -        used to determine the engine:
I think these two lines should be left in.

2023-05-04 20:59 UTC, rhshadrach commented on pandas/io/excel/_base.py
> -           used to determine the engine:
Same here.

2023-06-12 18:21 UTC, mroeschke commented
Feel free to reopen when you have time to circle back here

2023-06-12 18:21 UTC, closed without merging