Type errors
pandas-dev/pandas pull request #52950
Opened 2023-04-26 21:47 UTC by rsurpur20

After running grep -Ern "type: ?ignore" pandas/ in the terminal, there's a list of type errors. I fixed type errors in three files:
- plotting/_matplotlib/timeseries.py
- core/methods/to_dict.py
- plotting/_matplotlib/converter.py

2023-04-27 16:08 UTC, mroeschke requested changes
Looks like a lot of these changes are failing the test suite and typing checks. Please validate these changes locally first with precommit

2023-04-29 15:36 UTC, jbrockmendel commented on pandas/plotting/_matplotlib/converter.py
> +    freq = pandas.offsets.BusinessDay()  # Example of creating a BusinessDay frequency
thats ignoring the input..

2023-04-29 15:36 UTC, jbrockmendel commented on pandas/core/methods/to_dict.py
> +    orient = 'dict'
thats ignoring the input

2023-04-29 15:37 UTC, jbrockmendel commented on pandas/plotting/_matplotlib/timeseries.py
> +# import pandas as pd
remove commented-out code

2023-04-29 15:37 UTC, jbrockmendel commented on pandas/plotting/_matplotlib/timeseries.py
> +import pandas
if you must, do `import pandas as pd`.  but we try to avoid that in favor or more specific imports where possible

2023-06-01 17:29 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2023-06-01 17:29 UTC, closed without merging