if branch may not be visited, so head and tail may not be correctly set
pandas-dev/pandas pull request #53044
Opened 2023-05-02 20:31 UTC by Charlie-XIAO

- [x] Closes #52960
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests)
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit)
- [x] Added an entry in the latest `doc/source/whatsnew/v2.1.0.rst` file

https://github.com/pandas-dev/pandas/blob/721bd7a22efbd1c57f86fd61d6f0e668b79942ae/pandas/io/formats/printing.py#L417-L420
The `if` branch as shown above may never be visited, so `head` and `tail` may not be correctly set. This pull request fixes this problem.

2023-05-04 17:37 UTC, mroeschke commented on doc/source/whatsnew/v2.1.0.rst
> +- Bug in :func:`format_object_summary`, head and tail were not correctly set (:issue:`52960`)
```suggestion
- Bug in displaying a :class:`MultiIndex` with a long element (:issue:`52960`)
```

2023-05-04 17:37 UTC, mroeschke requested changes
Could you also add a unit test

2023-05-04 17:38 UTC, Charlie-XIAO commented
Sure, thanks for your review! I'll make the changes ASAP.

2023-05-04 18:25 UTC, Charlie-XIAO commented
@mroeschke Hi, I've made the unit test. However, I'm not sure if this is the correct way to do, so would you mind giving some instructions if I'm not doing correctly? Thank you very much.

2023-05-05 18:05 UTC, mroeschke approved these changes

2023-05-05 18:05 UTC, merged

2023-05-05 18:05 UTC, mroeschke commented
Thanks @Charlie-XIAO