ENH:filters parameters in pd.read_parqeut
pandas-dev/pandas pull request #53212
Opened 2023-05-13 14:14 UTC by mrastgoo

- [x] Towards #52238 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

added filters as a new parameter in pd.read_parquet

2023-05-15 19:59 UTC, mroeschke requested changes
Instead since we still support both engines, I think linking to the docs for both fastparquet and pyarrow in `**kwargs` is sufficient https://github.com/pandas-dev/pandas/issues/52238#issuecomment-1485571801

2023-05-16 06:39 UTC, jorisvandenbossche commented
Given that the `filters` keyword is supported by both engines and works the same, I think it would certainly be useful to explicitly document this keyword, and not hide it in the description of the kwargs. We actually already do the same for the `columns` keyword.

2023-05-29 14:29 UTC, jorisvandenbossche commented
@mroeschke OK with adding this?

2023-05-30 17:05 UTC, mroeschke commented
Okay yeah that makes sense to add this then

2023-05-30 17:06 UTC, mroeschke reviewed
Could you add a test for `filters` for both engines?

2023-07-04 10:43 UTC, jorisvandenbossche commented
@mrastgoo would you have time to add a test?

We have an existing test for the columns keyword (`test_read_columns`), so could add an equivalent `test_read_filters` test case next to it. Something like:

```
    def test_read_filters(self, engine, tmp_path):
        df = pd.DataFrame({"int": list(range(4)), "part": list("aabb"),})

        expected = pd.DataFrame({"int": [0, 1]})
        check_round_trip(
            df,
            engine,
            path=tmp_path,
            expected=expected,
            write_kwargs={"partition_cols": ["part"]},
            read_kwargs={"filters": [("string", "==", "a")], "columns":["int"]},
            repeat=1,
        )
```

I used partition cols to actually see the effect of the filter also for fastparquet (to ensure it is correctly passed through). And with that, the `repeat=1` is needed to not add additional files to the directory when writing a second time (with partition_cols, it does not just overwrite the single file).

2023-07-04 11:09 UTC, mrastgoo commented
@jorisvandenbossche , yes I would do it asap, sorry for the delay in this issue and thanks for the info I will take that into account.

2023-07-05 19:59 UTC, mrastgoo commented
I just pushed for the test. 
I changed the following line for the test
```
read_kwargs={"filters": [("part", "==", "a")], "columns":["int"]},
```
the error which was raised was not very clear for missing columns, which is not a pandas issue, but thought to mention it. 
```
pyarrow.lib.ArrowInvalid: No match for FieldRef.Name(string) in int: int64
part: dictionary<values=string, indices=int32, ordered=0>
```

2023-08-01 17:29 UTC, mroeschke commented
Could you merge in main once more?

2023-08-01 20:09 UTC, mroeschke commented on pandas/io/parquet.py
> +    filters: list[tuple] | list[list[tuple]] | None = None,
Could you put this as the last argument? (before `**kwargs`)?

2023-08-01 20:10 UTC, mroeschke commented on pandas/io/parquet.py
> +        to prevent the loading of some row-groups and/or files.
Could you add a `.. versionadded:: 2.1.0` at the end?

2023-08-01 20:10 UTC, mroeschke reviewed
Also needs a whatsnew entry in `2.1.0.rst` in the IO section

2023-08-02 15:39 UTC, mroeschke approved these changes

2023-08-02 15:39 UTC, merged

2023-08-02 15:39 UTC, mroeschke commented
Thanks @mrastgoo