closes the issue #49046
pandas-dev/pandas pull request #53415
Opened 2023-05-27 16:26 UTC by flotaro

- [ ] closes #49046  (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2023-05-28 17:01 UTC, MarcoGorelli requested changes

2023-05-28 17:01 UTC, MarcoGorelli commented on web/pandas/community/ecosystem.md
> +### [Physipy]
the other bullet points have a link

2023-05-28 17:01 UTC, MarcoGorelli commented on web/pandas/community/ecosystem.md
> +  | [physipy]                    | `slice`    | `Series`, `DataFrame` |  | 'df.physipy'| 'Series'             |
does this render correctly?

2023-05-28 17:01 UTC, MarcoGorelli commented on web/pandas/pdeps/0006-ban-upcasting.md
> +   - ``numpy``: option 2;
unrelated?

2023-06-26 18:15 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2023-06-26 18:15 UTC, closed without merging