DEPR: Deprecate DataFrame.last and Series.last
pandas-dev/pandas pull request #53710
Opened 2023-06-17 16:40 UTC by rmhowe425

- [X] closes #53692 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [X] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2023-06-18 00:55 UTC, rmhowe425 commented
@MarcoGorelli Is something going on with the CI environment? The tests that are failing for this PR are not failing locally for me when I run pytest. 

The same tests also started failing in #53439 this morning after I updated my entry in whatsnew v2.1.0

2023-06-19 08:42 UTC, MarcoGorelli requested changes
thanks for your pr, generally looks good

failures might be unrelated - just got a minor comment, if you address that and then fetch and merge upstream/main then hopefully it'll be resolved

2023-06-19 08:42 UTC, MarcoGorelli commented on pandas/core/generic.py
>      Parameters
no need to duplicate this

2023-06-19 14:25 UTC, rmhowe425 commented
@MarcoGorelli The Doc bulid test failure seems to be unrelated

The docstring test is failing because the warning message that I imeplemented is executing. Since this method is being deprecated what would be the recommended solution in this instance? 

Should I add an additional note in the docstring to  create a mask and filter using `.loc` instead of `last` and then add code that shows how to do that? I don't believe this was handled in the PR for deprecating [series.first and DataFrame.first](https://github.com/pandas-dev/pandas/pull/53419/files#diff-1a2e3df0db7dd8bddc2ec4bff9de8a7a55e328e6c32e2cecde761dc9549fcd46)

2023-06-21 09:53 UTC, MarcoGorelli commented
thanks @rmhowe425 - does it work to `doctest: skip` the failing doctest?

2023-06-21 14:26 UTC, MarcoGorelli approved these changes
nice one @rmhowe425 !

![](https://i.fluffy.cc/g6TR0RVJMJ4f5nWrDR39tNrddc3gNSdm.gif)

2023-06-21 14:27 UTC, merged