DOC: Fixing EX01 - Added examples
pandas-dev/pandas pull request #53725
Opened 2023-06-19 14:34 UTC by DeaMariaLeon

- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

Towards https://github.com/pandas-dev/pandas/issues/37875

Partially fixing https://github.com/pandas-dev/pandas/issues/53668

2023-06-19 14:58 UTC, MarcoGorelli requested changes

2023-06-20 09:04 UTC, DeaMariaLeon commented on pandas/_libs/tslibs/timestamps.pyx
> +                           self.microsecond, self.tzinfo, fold=self.fold)
I must be missing something but I get: `AttributeError: 'datetime.time' object has no attribute 'timetz'`
I checked the docs too. So, isn't timetz a datetime method?

2023-06-20 15:04 UTC, MarcoGorelli commented on pandas/_libs/tslibs/timestamps.pyx
> +
I don't think there is a `super().timetz` method

2023-06-20 15:06 UTC, MarcoGorelli commented on pandas/_libs/tslibs/timestamps.pyx
> +
oh wait, sorry, there is, that's why there was no definition previously

in which case, yeah, if it doesn't give incorrect results for negative dates or anything, then that looks fine

2023-06-21 13:49 UTC, MarcoGorelli approved these changes
thanks @DeaMariaLeon !

![](https://i.fluffy.cc/4HrdmGw7MHL3rcH3J0lCBBG7xhlxnWs7.gif)

2023-06-21 13:49 UTC, merged