DOC: Update merge copy parameter documentation.
pandas-dev/pandas pull request #54077
Opened 2023-07-11 08:13 UTC by liang3zy22

- [ ] closes #4599 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2023-07-11 16:44 UTC, mroeschke requested changes

2023-07-11 16:44 UTC, mroeschke commented on pandas/core/frame.py
> +    If False, avoid copy if copy requirements are fulfilled. If copy operation
Not sure if this description clarifies when a copy is needed

2023-07-18 05:56 UTC, liang3zy22 commented
I have checked merge copy related codes, found that following codes will decide if copy:
```
pandas/pandas/core/internals/concat.py:229
        if needs_copy and not indexers:
            mgr = mgr.copy()
```
The needs_copy parameter is defined by user input, CoW status and concat axis.The indexers parameter is defined by following codes:
```
pandas/pandas/core/reshape/concat.py:666
            for obj in self.objs:
                indexers = {}
                for ax, new_labels in enumerate(self.new_axes):
                    # ::-1 to convert BlockManager ax to DataFrame ax
                    if ax == self.bm_axis:
                        # Suppress reindexing on concat axis
                        continue

                    # 1-ax to convert BlockManager axis to DataFrame axis
                    obj_labels = obj.axes[1 - ax]
                    if not new_labels.equals(obj_labels):
                        indexers[ax] = obj_labels.get_indexer(new_labels)

                mgrs_indexers.append((obj._mgr, indexers))
```
I don't know why new_labels can be not equal to obj_labels. They are both from objs, although there are some operations in self.new_axes function. I have tried several examples, but can't get an indexers value which is not None.

2023-08-21 19:32 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2023-08-21 19:32 UTC, closed without merging