Fixed groupby error with nullable types
pandas-dev/pandas pull request #54230
Opened 2023-07-22 19:27 UTC by KladeRe

- [x] closes #54206 
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2023-07-22 20:05 UTC, el33tneel commented on pandas/tests/groupby/test_rank.py
> +def test_groupy_op_with_nullables():
Minor: typo in method name: `test_groupy_op_with_nullables`-> `test_groupby_op_with_nullables`

2023-08-05 16:39 UTC, rhshadrach requested changes

2023-08-05 16:39 UTC, rhshadrach commented on doc/source/whatsnew/v2.1.0.rst
> +groupby_nullable_types_error
I don't think this qualifies for a notable bug fix. Instead, could you add to the GroupBy subsection of the bugfixes down below this.

2023-08-05 16:39 UTC, rhshadrach commented on pandas/core/arrays/masked.py
> +        result_mask = np.zeros(ngroups, dtype=bool)
This does not implement the change I suggested in the linked issue, and I believe is causing tests to fail.

2023-09-01 00:24 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2023-09-01 00:24 UTC, closed without merging