Replace cpplint with clang-format
pandas-dev/pandas pull request #55150
Opened 2023-09-15 19:15 UTC by WillAyd

cpplint isn't seemingly well maintained and focuses on C++, which we aren't using. I think clang-format is a much better tool for our formatting

2023-09-15 19:52 UTC, WillAyd commented
Since we are adding a hook to pre-commit I'm guessing pre-commit.ci will have to be updated somehow to account for it. Does @MarcoGorelli or @lithomas1 know how that works?

2023-09-15 22:06 UTC, lithomas1 commented
> Since we are adding a hook to pre-commit I'm guessing pre-commit.ci will have to be updated somehow to account for it. Does @MarcoGorelli or @lithomas1 know how that works?

I think Marco's out on vacation right now, so I'll do my best to help.

Can we try not using pocc's wrapper around clang-format? I think that one doesn't install clang-format for you, so it won't work on pre-commit CI. 

You can try adding something manual like 
https://github.com/pandas-dev/pandas/blob/cc58350c92a9e24bef586cd1b898c01640b33abc/.pre-commit-config.yaml#L131-L388

(see the pyright one. 
We can try adding a new entry something like
```
id: clang-format
name: clang-format
entry: << clang-format command goes here >>
language: conda
additional_dependencies:
- clang-format
```
(I'm just typing this off of my head. Idea is to get pre-commit to pull clang-format off of conda. Don't expect it to work out of the box, though)

2023-09-15 22:08 UTC, WillAyd commented
Ah OK thanks. I'll give that a shot - didn't realize pocc was missing something compared to the other repo to auto install

2023-10-03 18:17 UTC, WillAyd commented
Any concerns on this one?

2023-10-04 20:04 UTC, lithomas1 approved these changes
Thanks Will,

This LGTM.

@MarcoGorelli any thoughts on this one?

2023-10-20 15:49 UTC, MarcoGorelli approved these changes
sorry for the delay, looks really good, nice one!

2023-10-20 16:50 UTC, mroeschke requested changes

2023-10-20 16:50 UTC, mroeschke commented on .pre-commit-config.yaml
> +    -   id: clang-format
Could you use https://github.com/pre-commit/mirrors-clang-format instead?

2023-10-22 19:35 UTC, mroeschke approved these changes

2023-10-22 19:35 UTC, merged

2023-10-22 19:35 UTC, mroeschke commented
Thanks @WillAyd