Support e.g. modern MacBooks running Linux containers
pandas-dev/pandas pull request #56258
Opened 2023-11-30 13:15 UTC by sanmai-NL

Modern MacBooks have aarch64 CPUs. They now have to build Pandas from source if installing from the PyPI index. This costs a lot of time and complexity that is better dealt with in the Pandas product build environment.

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2023-11-30 22:21 UTC, lithomas1 requested changes
Can you elaborate more on why this is necessary?

We already build manylinux wheels on CircleCI here.
https://github.com/pandas-dev/pandas/blob/4f080b8f2e5c93d1b0dd1ceb5487fba67feb02ab/.circleci/config.yml#L100

Do you need musllinux arch ones?

2023-12-01 05:48 UTC, sanmai-NL commented
Yes, many container images including ours are based om Alpine Linux, which is the main 'container distro'. It is based on musl libc.

2023-12-01 18:45 UTC, mroeschke commented
Generally we generate wheels for platforms we have CI testing for, and currently we don't test on musl aarch. Once testing is added, we'd probably be more comfortable releasing wheels for it since there would be "support"

2023-12-01 19:37 UTC, mroeschke commented
> I'll gladly implement testing. Any pointers?

I would suggest trying to modify `unit-tests.yml` and copy the job contents of the `Linux-Musl` job except to use this image: https://quay.io/repository/pypa/manylinux2014_aarch64

2024-01-01 00:39 UTC, lithomas1 commented
I'm going to close this PR, but I merged in another PR a while back adding arm64 musllinux wheels (which you can expect to see in the next release).

2024-01-01 00:39 UTC, closed without merging