Add test groupby transform no column
pandas-dev/pandas pull request #56935
Opened 2024-01-17 22:22 UTC by DevpriyaDave

- [X] closes #37093 
- [X] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2024-01-18 00:51 UTC, rhshadrach requested changes
Thanks for the PR!

2024-01-18 00:51 UTC, rhshadrach commented on pandas/tests/groupby/transform/test_transform.py
> +        result = gb.sum()
For the linked issue, you want to be using `.transform("sum")` here.

2024-01-18 01:33 UTC, DevpriyaDave commented
> Thanks for the PR!

Thanks for your review and appreciate you updating the PR title, I will make a note of the format for next time.

2024-02-28 17:49 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2024-02-28 17:49 UTC, closed without merging