BUG: DateTimeIndex.is_year_start unexpected behavior when constructed with freq 'MS' date_range (#57377)
pandas-dev/pandas pull request #57494
Opened 2024-02-19 00:01 UTC by mattheeter

- [ ] closes #57377
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

- When a DateTimeIndex was created via date_range with the freq parameter as 'MS' would yield the wrong is_year_start (and later it was discovered is_quarter_start) attribute. In `pandas/_libs/tslibs/fields.pyx`, the way in which the start and end months were set was one way for freq 'MS', 'QS', and 'YS' than other offsets. However, only the latter two had the necessary properties to set start and end this way. As such, removing 'MS' from the list fixed the issue.

2024-03-25 18:18 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2024-03-25 18:39 UTC, MarcoGorelli commented
wait sorry, I think this is my fault for not having got round to reviewing it

reopening for now, hoping to get to it at some point before 3.0

@natmokval fancy taking a look too?

2024-03-25 20:40 UTC, natmokval commented
I think the suggested changes will fix the bug in `is_year_start` for `MonthBegin`. We will get the correct result for `freq="MS"`:
```
dr = pd.date_range("2017-12-01", periods=2, freq="MS")
print(dr) # DatetimeIndex(['2017-12-01', '2018-01-01'], dtype='datetime64[ns]', freq='MS')
dr_attr = dr.is_year_start
print(dr_attr) # [False  True]
```

These changes won't fix a problem with some other frequencies such as: `freq="QS-NOV"`:
```
dr = pd.date_range("2017-07-01", periods=2, freq="QS-NOV")
print(dr) # DatetimeIndex(['2017-08-01', '2017-11-01'], dtype='datetime64[ns]', freq='QS-NOV')
dr_comp = [dt.is_year_start for dt in dr]
dr_attr = dr.is_year_start
print(dr_attr) # [False  True]
print(dr_comp) # [False, False]
```

2024-03-26 22:50 UTC, natmokval commented
I think it's okay to leave the fix for `"MS"` in this PR and open a new PR to work on the problem for frequencies such as `"QS-NOV"`.

This PR is still `Stale`. It can take a couple of days to change its status to active.

2024-05-02 10:08 UTC, MarcoGorelli requested changes
thanks for your PR - I think a more general fix is needed here, rather than papering over already-broken logic

2024-05-02 10:11 UTC, MarcoGorelli commented on pandas/_libs/tslibs/fields.pyx
> +                freqstr[1:3] in ["QS", "YS"]):
wow, looks like this broken logic was introduced 13 years ago... 😭 

https://github.com/pandas-dev/pandas/pull/4823/files

2024-06-06 09:39 UTC, MarcoGorelli approved these changes
Thanks @mattheeter for your PR, thanks for your patience here, and sorry that this took a while

Looks good to me. I've added a hypothesis test too to make sure

2024-06-08 14:33 UTC, merged