Doc: resolve GL08 for pandas.core.groupby.SeriesGroupBy.value_counts
pandas-dev/pandas pull request #57609
Opened 2024-02-25 06:31 UTC by jordan-d-murphy

All GL08 Errors resolved in the following cases:

1. scripts/validate_docstrings.py --format=actions --errors=GL08 pandas.core.groupby.SeriesGroupBy.value_counts

- [x] xref https://github.com/pandas-dev/pandas/issues/57443
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2024-02-25 06:32 UTC, jordan-d-murphy commented
pre-commit.ci autofix

2024-02-25 13:47 UTC, rhshadrach requested changes

2024-02-25 13:47 UTC, rhshadrach commented on pandas/core/groupby/generic.py
> +            Series if the groupby as_index is True, otherwise DataFrame.
` ``as_index`` `

2024-02-25 13:47 UTC, rhshadrach commented on pandas/core/groupby/generic.py
> +          'proportion', depending on the ``normalize`` parameter.
` ``as_index`` ` here as well.

2024-02-25 21:37 UTC, jordan-d-murphy reviewed
updated as_index to ` ``as_index`` `

2024-02-25 21:37 UTC, jordan-d-murphy commented on pandas/core/groupby/generic.py
> +            Series if the groupby as_index is True, otherwise DataFrame.
thanks! pushed a fix

2024-02-25 21:37 UTC, jordan-d-murphy commented on pandas/core/groupby/generic.py
> +          'proportion', depending on the ``normalize`` parameter.
thanks! pushed a fix

2024-02-25 21:39 UTC, jordan-d-murphy commented
updated this PR based on your feedback, @rhshadrach can you take another look?

2024-02-26 22:34 UTC, rhshadrach approved these changes
lgtm

2024-02-26 22:34 UTC, merged

2024-02-26 22:34 UTC, rhshadrach commented
Thanks @jordan-d-murphy