Nanosecond fixed precision of DatetimeIndex with time zone information, Fix #53473
pandas-dev/pandas pull request #57703
Opened 2024-03-02 16:45 UTC by MarcusJak

The expected behaviour is now correct from issue #53473 The out->picoseond value wasn't set which ended with a Json error regarding the ns calculations.

- [x] closes #53473
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2024-03-02 16:53 UTC, WillAyd requested changes
Thanks for the PR. Can you also add a test for this in pandas/tests/io/json/test_pandas.py?

2024-03-02 16:53 UTC, WillAyd commented on pandas/_libs/src/datetime/pd_datetime.c
> +  out->ps = 1000 * PyLong_AsLong(PyObject_GetAttrString(obj, "nanosecond"));
Does this overflow need the bounds limits?

2024-03-07 19:02 UTC, robinho46 commented
Hi @WillAyd could you please check the new fixes, we would appreciate that :)

2024-04-15 17:25 UTC, closed without merging

2024-04-15 17:25 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.