DOC: Add examples for creating an index accessor
pandas-dev/pandas pull request #57867
Opened 2024-03-16 16:39 UTC by sjalkote

Picked up issue #49202. This adds examples for creating index, dataframe, and series accessors.
- [X] closes #49202 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2024-03-16 16:42 UTC, sjalkote commented
pre-commit.ci autofix

2024-03-16 16:53 UTC, sjalkote commented
pre-commit.ci autofix

2024-03-16 21:35 UTC, s1099 requested changes
remove double newline

2024-03-16 21:35 UTC, s1099 commented on pandas/core/accessor.py
> +
```suggestion

```

2024-03-16 21:35 UTC, s1099 commented on pandas/core/accessor.py
> +
```suggestion

```

2024-03-17 20:59 UTC, datapythonista reviewed
`Appender` is something that we used before `doc` existed, but I think it'd be better to not use, as makes things more difficult to understand. I think you're adding the examples to all register accessor functions, so you can add the `Examples` header to the main docstring, and then add a variable for the content of the section as it's done with `{klass}`.

Unrelated, in the examples section is not needed to create a `code-block`. You can just start the code with `>>>` and the docstring parser should understand it's code. Also, it's not needed to import pandas, `pd` should already be available without importing.

2024-03-17 21:48 UTC, sjalkote commented
pre-commit.ci autofix

2024-03-18 00:46 UTC, datapythonista commented
Can you have a look at the CI errors please?

2024-03-19 09:43 UTC, s1099 requested changes

2024-03-19 09:43 UTC, s1099 commented on pandas/core/accessor.py
> +        }, index=[1, 2, 5, 8])
```suggestion
>>> df = pd.DataFrame(
...     {"col1": [1, 2, 3, 4], "col2": ["a", "b", "c", "d"]}, index=[1, 2, 5, 8]
... )
```

2024-03-19 09:43 UTC, s1099 commented on pandas/core/accessor.py
> +        },orient='index')
```suggestion
>>> df = pd.DataFrame.from_dict(
...     {"row1": {"1": 1, "2": "a"}, "row2": {"1": 2, "2": "b"}}, orient="index"
... )
```

2024-03-26 20:03 UTC, Aloqeely commented
The checks are still failing, could you please fix them?

2024-04-02 00:39 UTC, sjalkote commented
Hi @datapythonista I believe we have fixed all the CI errors. Could you please re-review?

2024-04-03 00:03 UTC, sjalkote commented on ci/code_checks.sh
> +        -i "pandas.api.extensions.register_index_accessor" \
Yep, I removed it. The builds are still passing.

2024-04-03 18:09 UTC, mroeschke commented
/preview

2024-04-03 18:12 UTC, mroeschke approved these changes

2024-04-03 18:12 UTC, merged

2024-04-03 18:12 UTC, mroeschke commented
Thanks @sjalkote