ENH: Add leftsemi merge
pandas-dev/pandas pull request #57979
Opened 2024-03-24 02:14 UTC by phofl

- [ ] closes #42784 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

I want to add anti joins as a follow up, which can be incorporated into the new class

2024-03-25 13:11 UTC, WillAyd requested changes

2024-03-25 13:11 UTC, WillAyd commented on pandas/_libs/hashtable_class_helper.pxi.in
> +            Int64VectorData *l
Stylistic nit but would be better to not use single character variable names, especially those that conflict with debugger aliases. The cython debugger is hard enough to use as is :-)

2024-03-25 13:11 UTC, WillAyd commented on pandas/_libs/hashtable_class_helper.pxi.in
> +        # mask not implemented
Can we raise NotImplementedError here for now?

2024-03-25 13:11 UTC, WillAyd commented on pandas/_libs/hashtable_class_helper.pxi.in
> +            hash(val)
Is the point of this just to raise an error if an object is not hashable?

2024-03-25 13:11 UTC, WillAyd commented on pandas/_libs/hashtable_class_helper.pxi.in
> +            k = kh_get_pymap(self.table, <PyObject*>val)
Is the cast required here? I assume it would know we are already working with PyObjects given the declaration of values

2024-03-25 13:11 UTC, WillAyd commented on pandas/core/reshape/merge.py
> +    how: JoinHow + Literal["leftsemi"] = "inner",
Is there any reason why we don't just add `leftsemi` to the `JoinHow` definition?

2024-03-25 13:11 UTC, WillAyd commented on pandas/tests/reshape/merge/test_semi.py
> +def test_leftsemi_invalid():
Can we add a test for raising NotImplementederror when passing a mask?

2024-03-26 13:48 UTC, Dr-Irv requested changes
Concerned about whether this argument will apply to `DataFrame.join()`.

2024-03-26 13:48 UTC, Dr-Irv commented on pandas/core/frame.py
> +      preserve the order of the left keys. Doesn't support `left_index`, `right_index`,
```suggestion
      preserve the order of the left keys. Does not support `left_index`, `right_index`,
```

2024-03-26 13:48 UTC, Dr-Irv commented on pandas/_typing.py
> +MergeHow = Literal["left", "right", "inner", "outer", "cross", "leftsemi"]
`MergeHow` is also used as the type for `how` in `DataFrame.join()`.  

So if `DataFrame.join()` will not support the `"leftsemi"` operation, then you'll need to split this type into a `JoinHow` and `MergeHow`, with the latter dependent on the former.

If `DataFrame.join()` will support that operation, then you'll have to update the docs for `join` and add a test for it.

2024-09-25 19:01 UTC, mroeschke commented
Closing to clear the queue, but feel free to update and reopen anytime

2024-09-25 19:01 UTC, closed without merging