DOC: replace deprecated frequency alias
pandas-dev/pandas pull request #58256
Opened 2024-04-14 14:11 UTC by abonte

replace 'S' with 's'

- ~~[ ] closes #xxxx (Replace xxxx with the GitHub issue number)~~
- ~~[ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature~~
- ~~[ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).~~
- ~~[ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.~~
- ~~[ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.~~

2024-04-15 16:49 UTC, mroeschke requested changes
Is this in reference to an issue? Could you provide more context?

2024-04-16 08:36 UTC, abonte commented
Dreprecated since version 2.2.0 https://pandas.pydata.org/docs/whatsnew/v2.2.0.html#other-deprecations. 

Reference issue https://github.com/pandas-dev/pandas/issues/52536

2024-04-16 17:12 UTC, mroeschke approved these changes

2024-04-16 17:12 UTC, merged

2024-04-16 17:12 UTC, mroeschke commented
Thanks @abonte