BUG: Unable to open Stata 118 or 119 format files saved in big-endian…
pandas-dev/pandas pull request #58640
Opened 2024-05-08 15:40 UTC by cmjcharlton

… format that contain strL data

- [x] closes #58638
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2024-05-08 17:51 UTC, bashtage commented
Just to check - are the stata files produced by Stata?

2024-05-08 17:59 UTC, bashtage requested changes
Small changes to clarify changed test. Otherwise LGTM.  Only other question is to verify dta files are created by Stata.

2024-05-08 17:59 UTC, bashtage commented on pandas/tests/io/test_stata.py
> +    def test_unicode_dta_118(self, file, datapath):
Maybe rename 118 -> 118_119

2024-05-08 17:59 UTC, bashtage commented on pandas/tests/io/test_stata.py
> +    def test_read_dta18(self, file, datapath):
Similar rename here would be clearer.

2024-05-08 19:03 UTC, cmjcharlton commented
These files were not created with Stata but were made using the published specification. I have however checked that they all load correctly into Stata and have used it to verify that they are constructed correctly:

```
. use stata12_118.dta

. list

     +------------------------------+
     |  x     y                   z |
     |------------------------------|
  1. |  1   abc           abcdefghi |
  2. |  3   cba   qwertywertyqwerty |
  3. | 93                      strl |
     +------------------------------+

. dtaverify stata12_118.dta
  (file "stata12_118.dta" is .dta-format 118 from Stata 14, 15, 16, 17, or 18)

 1. reading and verifying header
    release is 118
    byteorder LSF
    K (# of vars) is 3
    N (# of obs) is 3                    
    label length 0 ||
    date length 17 |19 Feb 2015 09:20|

 2. reading and verifying map
    map[ 1] =                    0
    map[ 2] =                  158
    map[ 3] =                  281
    map[ 4] =                  320
    map[ 5] =                  728
    map[ 6] =                  757
    map[ 7] =                  947
    map[ 8] =                 1373
    map[ 9] =                 2371
    map[10] =                 2406
    map[11] =                 2473
    map[12] =                 2581
    map[13] =                 2610
    map[14] =                 2622
    verifying map
    1 2 3 4 5 6 7 8 9 10 11 12 13 14

 3. reading and verifying vartypes

 4. reading and verifying varnames
    verifying varnames unique

 5. reading and verifying sort order
    verifying contents

 6. reading and verifying display formats
    verifying formats
    verifying formats correspond to variable type

 7. reading and verifying value-label assignment
    verifying value-label construction
    verifying value label and corresponding variable types

 8. reading and verifying variable-label assignment
    verifying variable labels construction

 9. reading and verifying characteristics
    (0 characteristics in file)

10. reading and verifying data
    (dtaverify_118 cannot verify that values are correct)
    verifying construction
    (1 strL variables)
    verifying strL construction

11. reading and verifying strLs
    verifying construction
    (3 strLs expected)

12. reading and verifying value label definitions
    verifying construction
    (0 labels in file)

no errors or warnings above; .dta file valid

. use stata12_119.dta

. list

     +------------------------------+
     |  x     y                   z |
     |------------------------------|
  1. |  1   abc           abcdefghi |
  2. |  3   cba   qwertywertyqwerty |
  3. | 93                      strl |
     +------------------------------+

. dtaverify stata12_119.dta
  (file "stata12_119.dta" is .dta-format 119 from Stata 15, 16, 17, or 18)

 1. reading and verifying header
    release is 119
    byteorder LSF
    K (# of vars) is 3
    N (# of obs) is 3                    
    label length 0 ||
    date length 17 |19 Feb 2015 09:20|

 2. reading and verifying map
    map[ 1] =                    0
    map[ 2] =                  160
    map[ 3] =                  283
    map[ 4] =                  322
    map[ 5] =                  730
    map[ 6] =                  767
    map[ 7] =                  957
    map[ 8] =                 1383
    map[ 9] =                 2381
    map[10] =                 2416
    map[11] =                 2483
    map[12] =                 2591
    map[13] =                 2620
    map[14] =                 2632
    verifying map
    1 2 3 4 5 6 7 8 9 10 11 12 13 14

 3. reading and verifying vartypes

 4. reading and verifying varnames
    verifying varnames unique

 5. reading and verifying sort order
    verifying contents

 6. reading and verifying display formats
    verifying formats
    verifying formats correspond to variable type

 7. reading and verifying value-label assignment
    verifying value-label construction
    verifying value label and corresponding variable types

 8. reading and verifying variable-label assignment
    verifying variable labels construction

 9. reading and verifying characteristics
    (0 characteristics in file)

10. reading and verifying data
    (dtaverify_119 cannot verify that values are correct)
    verifying construction
    (1 strL variables)
    verifying strL construction

11. reading and verifying strLs
    verifying construction
    (3 strLs expected)

12. reading and verifying value label definitions
    verifying construction
    (0 labels in file)

no errors or warnings above; .dta file valid

. use stata12_be_117.dta

. list

     +------------------------------+
     |  x     y                   z |
     |------------------------------|
  1. |  1   abc           abcdefghi |
  2. |  3   cba   qwertywertyqwerty |
  3. | 93                      strl |
     +------------------------------+

. dtaverify stata12_be_117.dta
  (file "stata12_be_117.dta" is .dta-format 117 from Stata 13)

 1. reading and verifying header
    release is 117
    byteorder MSF
    K (# of vars) is 3
    N (# of obs) is 3
    label length 0 ||
    date length 17 |19 Feb 2015 09:20|

 2. reading and verifying map
    map[ 1] =                    0
    map[ 2] =                  153
    map[ 3] =                  276
    map[ 4] =                  315
    map[ 5] =                  435
    map[ 6] =                  464
    map[ 7] =                  630
    map[ 8] =                  768
    map[ 9] =                 1046
    map[10] =                 1081
    map[11] =                 1148
    map[12] =                 1244
    map[13] =                 1273
    map[14] =                 1285
    verifying map
    1 2 3 4 5 6 7 8 9 10 11 12 13 14

 3. reading and verifying vartypes

 4. reading and verifying varnames
    verifying varnames unique

 5. reading and verifying sort order
    verifying contents

 6. reading and verifying display formats
    verifying formats
    verifying formats correspond to variable type

 7. reading and verifying value-label assignment
    verifying value-label construction
    verifying value label and corresponding variable types

 8. reading and verifying variable-label assignment
    verifying variable labels construction

 9. reading and verifying characteristics
    (0 characteristics in file)

10. reading and verifying data
    (dtaverify_117 cannot verify that values are correct)
    verifying construction
    (1 strL variables)
    verifying strL construction

11. reading and verifying strLs
    verifying construction
    (3 strLs expected)

12. reading and verifying value label definitions
    verifying construction
    (0 labels in file)

no errors or warnings above; .dta file valid

. use stata12_be_118.dta

. list

     +------------------------------+
     |  x     y                   z |
     |------------------------------|
  1. |  1   abc           abcdefghi |
  2. |  3   cba   qwertywertyqwerty |
  3. | 93                      strl |
     +------------------------------+

. dtaverify stata12_be_118.dta
  (file "stata12_be_118.dta" is .dta-format 118 from Stata 14, 15, 16, 17, or 18)

 1. reading and verifying header
    release is 118
    byteorder MSF
    K (# of vars) is 3
    N (# of obs) is 3                    
    label length 0 ||
    date length 17 |19 Feb 2015 09:20|

 2. reading and verifying map
    map[ 1] =                    0
    map[ 2] =                  158
    map[ 3] =                  281
    map[ 4] =                  320
    map[ 5] =                  728
    map[ 6] =                  757
    map[ 7] =                  947
    map[ 8] =                 1373
    map[ 9] =                 2371
    map[10] =                 2406
    map[11] =                 2473
    map[12] =                 2581
    map[13] =                 2610
    map[14] =                 2622
    verifying map
    1 2 3 4 5 6 7 8 9 10 11 12 13 14

 3. reading and verifying vartypes

 4. reading and verifying varnames
    verifying varnam [...]

2024-05-08 20:00 UTC, cmjcharlton commented on pandas/tests/io/test_stata.py
> +    def test_unicode_dta_118(self, file, datapath):
Good idea - I have now renamed these functions.

2024-05-08 20:00 UTC, cmjcharlton commented on pandas/tests/io/test_stata.py
> +    def test_read_dta18(self, file, datapath):
I have now renamed this as suggested.

2024-06-10 10:52 UTC, bashtage commented
Can you ping on green and I'll merge this in.

2024-06-10 10:53 UTC, bashtage approved these changes

2024-06-10 11:42 UTC, cmjcharlton commented
Thanks @bashtage . All checks how how completed.

2024-06-10 11:44 UTC, merged

2024-06-10 11:44 UTC, bashtage commented
Thanks for the fix.