DOC: Document Remote Code Execution risk for Dataframe.query and computation.eval
pandas-dev/pandas pull request #58697
Opened 2024-05-13 11:09 UTC by r0rshark

## TLDR
This diff adds documentation to the Remote Code Execution risk for `Dataframe.query` and `computation.eval` with the same wording used in [Dataframe.eval](https://github.com/pandas-dev/pandas/blob/v2.2.2/pandas/core/frame.py#L4850-L4852)

## Details
The Dataframe.query function is internally calling Dataframe.eval [here](https://github.com/pandas-dev/pandas/blob/b552dc95c9fa50e9ca2a0c9f9cdb8757f794fedb/pandas/core/frame.py#L4547) passing the `expr` parameter. 
Dataframe.eval is correctly warning in the [documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.eval.html#pandas.DataFrame.eval) that this could lead to Code execution risk.
This is possible because using the `@` syntax we can access local variables and by referencing the imported pandas library we can get the `os.system` function thanks to `os` being imported inside [compat/__init__.py](https://github.com/pandas-dev/pandas/blob/main/pandas/compat/__init__.py#L13). In this way passing something like `@pd.compat.os.system('whoami')` to the `expr` parameter of `Dataframe.query` we can achieve code execution.

However in Dataframe.query [documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html) we do not surface this risk we only point out that pandas.eval is called but also [there](https://pandas.pydata.org/docs/reference/api/pandas.eval.html#pandas.eval) we do not warn about any code execution risks. 

The vulnerable code I found and that also surprised the developer who wrote it of the code execution risk can be summarized in UserControlled input flowing into the DataFrame.query expr value similarly to
```
import pandas as pd

def api_whatever(request: HTTPRequest):
  filter = request.GET["filter"]
  data = {
    "test": [125, 230, 412],
  }
  df = pd.DataFrame(data)
  df.query(filter)
   ... 

```
Calling this api with data:
https://www.example.com?filter=@pd.compat.os.system('whoami')
will allow code execution.

2024-05-16 16:49 UTC, WillAyd approved these changes
lgtm @jorisvandenbossche

2024-05-21 03:15 UTC, rhshadrach requested changes
Thanks for the PR!

2024-05-21 03:15 UTC, rhshadrach commented on pandas/core/frame.py
> +        injection if you pass user input to this function.
```suggestion
        This method can run arbitrary code, which can make you vulnerable to code
        injection if you pass user input to this function.
```

I don't think we need to mention the implementation details; it's sufficient to warn that query can run arbitrary code.

2024-05-21 03:15 UTC, rhshadrach commented on pandas/core/computation/eval.py
> +    injection if you pass user input to this function.
This is an internal method, right? In such case, I don't think this is necessary.

2024-05-21 03:17 UTC, rhshadrach commented on pandas/core/computation/eval.py
> +    injection if you pass user input to this function.
Ah - this is exposed at the top level. Agree with including it, but I don't think starting with `This` is accurate - it 
 reads to me like that refers to the previous sentence. Can just say

> `eval` can run arbitrary code, ...

2024-05-22 20:59 UTC, rhshadrach approved these changes
lgtm

2024-05-22 21:00 UTC, merged

2024-05-22 21:00 UTC, rhshadrach commented
Thanks @r0rshark!