Dep groupby corrwith
pandas-dev/pandas pull request #58732
Opened 2024-05-15 16:23 UTC by pedrocariellof

- [x] closes #57158 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2024-05-15 20:17 UTC, rhshadrach requested changes
Thanks for the PR! Looks pretty good, a few requests below.

2024-05-16 15:44 UTC, pedrocariellof commented on pandas/tests/groupby/test_all_methods.py
> +        warn_msg = "DataFrameGroupBy.fillna is deprecated"
Lines 28-30 repeat in other parts of the code. Should I remove all the instances or just the ones you pointed out?

2024-05-21 01:27 UTC, rhshadrach commented on pandas/tests/groupby/test_all_methods.py
> +        warn_msg = "DataFrameGroupBy.fillna is deprecated"
Either is fine.

2024-05-29 00:10 UTC, pedrocariellof commented
@rhshadrach

2024-05-29 22:25 UTC, rhshadrach requested changes
Looking good, a few minor requests.

2024-05-29 22:25 UTC, rhshadrach commented on doc/source/getting_started/install.rst
> -.. _install:
This is still changing

2024-05-29 22:25 UTC, rhshadrach commented on doc/source/whatsnew/v3.0.0.rst
> +
Can you remove the newline here.

2024-05-29 22:25 UTC, rhshadrach commented on doc/source/whatsnew/v3.0.0.rst
> +- Deprecated :meth:`Groupby.corrwith` (:issue:`57158`)
```suggestion
- Deprecated :meth:`.DataFrameGroupby.corrwith` (:issue:`57158`)
```

2024-06-03 21:25 UTC, rhshadrach requested changes
lgtm

2024-06-03 21:26 UTC, rhshadrach approved these changes

2024-06-03 21:27 UTC, merged

2024-06-03 21:27 UTC, rhshadrach commented
Thanks @pedrocariellof - and for the additional cleanups too!