BUG: Fix issue with negative labels in `group_cumsum`
pandas-dev/pandas pull request #58984
Opened 2024-06-12 07:06 UTC by luke396

- [x] closes #58811  (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2024-06-12 16:52 UTC, mroeschke requested changes
Looks good could you add a whatsnew entry in `v3.0.0.rst` under the groupby section?

2024-06-13 01:40 UTC, luke396 commented
Sorry for careless, and `whatsnew` is added now.

2024-06-14 16:54 UTC, mroeschke approved these changes

2024-06-14 16:55 UTC, merged

2024-06-14 16:55 UTC, mroeschke commented
Thanks @luke396