ENH: Allow to plot weighted KDEs.
pandas-dev/pandas pull request #59337
Opened 2024-07-27 19:33 UTC by fbourgey

- [ ] closes #59087 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2024-07-28 11:00 UTC, yuanx749 commented on pandas/plotting/_core.py
> +            Weights of datapoints. This must be the same shape as dataset.
`dataset` is a parameter of `scipy.stats.gaussian_kde`, but it is not explicitly used here. Perhaps `datapoints` is more clear.
```suggestion
            Weights of datapoints. This must be the same shape as datapoints.
```

2024-07-29 17:41 UTC, mroeschke requested changes
Could you add a test an whatsnew entry in `v3.0.0.rst`?

2024-07-29 17:41 UTC, mroeschke commented on pandas/plotting/_core.py
> +        weights: np.ndarray | None = None,
This needs to be placed after `ind`

2024-07-31 01:48 UTC, mroeschke commented on doc/source/whatsnew/v3.0.0.rst
> +- Added missing parameter ``weights`` in :meth:`DataFrame.plot.kde` for the estimation of the PDF (:issue:`59337`)
Can you add this under `Other Enhancements`?

2024-07-31 17:25 UTC, mroeschke approved these changes

2024-07-31 17:25 UTC, merged

2024-07-31 17:25 UTC, mroeschke commented
Thanks @fbourgey