BUG: Handle nonexistent end dates when resampling
pandas-dev/pandas pull request #59471
Opened 2024-08-10 14:09 UTC by rob-sil

- [x] closes #58380
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/v3.0.0.rst` file if fixing a bug or adding a new feature.

2024-08-11 16:31 UTC, rhshadrach requested changes
Thanks for the PR!

2024-08-11 16:31 UTC, rhshadrach commented on pandas/tests/resample/test_datetime_index.py
> +    print(f"{result=}")
Can you remove the print.

2024-08-11 16:31 UTC, rhshadrach commented on doc/source/whatsnew/v3.0.0.rst
> +- Bug in :meth:`Series.resample` could raise when the the date range ended shortly before DST. (:issue:`58380`)
Not just before DST, but more generally before a non-existent time, right?

2024-08-11 19:44 UTC, rob-sil commented on pandas/tests/resample/test_datetime_index.py
> +    print(f"{result=}")
Oops, sorry about that!

2024-08-13 02:25 UTC, rob-sil commented on pandas/core/resample.py
> +            last = last.tz_localize(index_tz, nonexistent="shift_forward")
I don't think `last` here is used as the last element in the series. Instead, `last` needs to be strictly after all the data points:
https://github.com/pandas-dev/pandas/blob/0fadaa9c9da39760e29e05012b14c8ce0782b5fe/pandas/_libs/lib.pyx#L893-L894

Shifting backwards should raise when running near a nonexistent hour, in the rare case where the nanosecond before is in the index:
```python
import pandas as pd

almost_a_day = pd.Timedelta(days=1) - pd.Timedelta(nanoseconds=1)
timestamp = pd.to_datetime("2024-04-25").tz_localize("Africa/Cairo")
ts = pd.Series(
    1,
    [timestamp, timestamp + almost_a_day],
)
ts.resample("1D", closed="right").sum()
```

However, shifting forward runs with the following output:
```
2024-04-24 00:00:00+02:00    1
2024-04-25 00:00:00+02:00    1
Freq: D, dtype: int64
```

(I'm not sure why it gives a bin on 2024-04-24.)

2024-08-19 17:05 UTC, mroeschke approved these changes
LGTM merge when ready @rhshadrach

2024-08-21 21:06 UTC, rhshadrach approved these changes
lgtm

2024-08-21 21:06 UTC, merged

2024-08-21 21:07 UTC, rhshadrach commented
Thanks @rob-sil!