Patch - updates maybe_indices_to_slice to use uint64
pandas-dev/pandas pull request #59537
Opened 2024-08-17 13:14 UTC by benjamindonnachie

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2024-08-17 14:26 UTC, WillAyd requested changes
inp_t is the proper size for an indexer - does it fix things if you try using that consistently?

2024-08-17 14:40 UTC, benjamindonnachie commented
Happy to give it a try.  I'll let you know.

2024-08-17 14:59 UTC, benjamindonnachie commented
Do you mean intp_t ?  If so, changing max_len to intp_t and np.intp respectively in lib.pyx and lib.pyi (to match the array definitions) also produces expected results:

```
>>> import pandas as pd
>>> print (pd.__version__)
3.0.0.dev0+1351.g523afa840a.dirty
>>> test = pd.read_pickle("summary.pkl")
>>> summary = test[test['count'] > 0]
>>> print (len(test))
4261028590
>>> print (len(summary))
1621743
```

Very minor changes but happy to submit another PR if that works for you.

2024-08-17 15:09 UTC, benjamindonnachie commented
Here - try this one https://github.com/pandas-dev/pandas/pull/59538

2024-08-17 15:09 UTC, WillAyd commented
Yes that's correct. You can just update this PR - no need to create another

2024-08-17 15:37 UTC, benjamindonnachie commented
Got there.... Many thanks for your help! :)

2024-08-17 15:50 UTC, WillAyd commented
@benjamindonnachie great I think this change looks pretty good! Let's see if CI is green.

You will also want to add a whatsnew entry, which can be added to pandas/doc/source/whatsnew/v3.0.0.rst`  You can add it to the section on Bug Fixes > Indexing (just follow the same pattern you see for other notes already there)

2024-08-17 16:09 UTC, benjamindonnachie commented
Whatsnew/v3.0.0.rst updated.  Fingers crossed! :)

2024-08-19 20:12 UTC, mroeschke commented on doc/source/whatsnew/v3.0.0.rst
> +- Bug in :meth:`maybe_indices_to_slice` max_len was set to an int causing ``OverflowError``: value too large to convert to int when manipulating very large dataframes (:issue:`59531`)
```suggestion
- Bug in :meth:`DataFrame.__getitem__` when slicing a :class:`DataFrame` many rows raised an ``OverflowError`` (:issue:`59531`)
```

2024-10-10 18:07 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2024-10-10 18:07 UTC, closed without merging

2024-10-10 22:28 UTC, benjamindonnachie commented
@mroeschke  I'm not sure what else you need given the minor nature of this patch.

2024-10-11 00:22 UTC, mroeschke commented
It appeared the code checks were not all passing https://github.com/pandas-dev/pandas/actions/runs/10938423968/job/30366432851

2025-03-07 15:35 UTC, swt2c commented
@benjamindonnachie any plans to revive this PR?  Otherwise, I will - I'm affected by this bug as well.