BUG: allow None as name in multi-index
pandas-dev/pandas pull request #59546
Opened 2024-08-18 10:45 UTC by matiaslindgren

- [x] closes #58721
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Another possible fix is to throw if `MultiIndex.names` contains `None`.
The exception message could say something like "empty index names must be empty strings, not None".

2024-08-25 14:16 UTC, rhshadrach requested changes
This is looking good to me, but we were explicit about not allowing `None` in the past and I'm not sure why. Traced it back to:

- issue: https://github.com/pandas-dev/pandas/issues/3662
- commit: https://github.com/pandas-dev/pandas/commit/dd79e5510368723e17955a339a089727af3f4ea6

Don't see any discussion about `None`. Can you take a look @mroeschke

2024-08-25 14:16 UTC, rhshadrach commented on doc/source/whatsnew/v3.0.0.rst
> +- :attr:`MultiIndex.names` containing ``None`` no longer throws ``AssertionError`` during join (:issue:`58721`)
Can you move the note to the `Reshaping` section of bugfixes.

2024-08-25 19:06 UTC, matiaslindgren commented
Automatic codeowner review requests were unintended, sorry. I accidentally pushed commits from my fork to this branch and that touched files unrelated to this PR. Force-pushed them away.

2024-08-26 17:21 UTC, mroeschke commented on doc/source/whatsnew/v3.0.0.rst
> +- :attr:`MultiIndex.names` containing ``None`` no longer throws ``AssertionError`` during join (:issue:`58721`)
```suggestion
- Bug in :meth:`DataFrame.join` when a :class:`DataFrame` with a :class:`MultiIndex` would raise an ``AssertionError`` when :attr:`MultiIndex.names` contained ``None``. (:issue:`58721`)
```

2024-08-26 20:50 UTC, rhshadrach approved these changes
lgtm

2024-08-26 20:55 UTC, mroeschke commented
pre-commit.ci autofix

2024-08-26 21:58 UTC, mroeschke approved these changes

2024-08-26 21:58 UTC, merged

2024-08-26 21:58 UTC, mroeschke commented
Thanks @matiaslindgren