DOC: add See Also section to groupby.DataFrameGroupBy.prod
pandas-dev/pandas pull request #59599
Opened 2024-08-25 01:32 UTC by ktseng4096

This PR fixes a numpy docstring validation error described in https://github.com/pandas-dev/pandas/issues/58063 for pandas.Series.to_dict

```
################################################################################
################################## Validation ##################################
################################################################################

1 Errors found for `pandas.core.groupby.DataFrameGroupBy.prod`:
	ES01	No extended summary found
```

2024-08-25 11:48 UTC, rhshadrach requested changes
Looks good - but pre-commit is failing.

2024-08-26 18:33 UTC, mroeschke approved these changes

2024-08-26 18:33 UTC, merged

2024-08-26 18:33 UTC, mroeschke commented
Thanks @ktseng4096

2024-08-26 18:40 UTC, ktseng4096 commented
@rhshadrach thanks for looking, fixed the ruff formatting