DOCS: fix docstring validation error for pandas.Series
pandas-dev/pandas pull request #59655
Opened 2024-08-30 00:33 UTC by githubalexliu

Partially addresses https://github.com/pandas-dev/pandas/issues/59592

Fixes
```
-i "pandas.Series.dt.normalize PR01" \
-i "pandas.Series.dt.qyear GL08" \
```

2024-09-06 20:19 UTC, mroeschke requested changes

2024-09-06 20:19 UTC, mroeschke commented on pandas/core/arrays/datetimes.py
> +    def normalize(self, *args, **kwargs) -> Self:
There is no `normalize` numpy function as far as I know so this should not be included

2024-09-18 08:59 UTC, yuanx749 requested changes

2024-09-18 08:59 UTC, yuanx749 commented on pandas/core/arrays/datetimes.py
> +        "qy",
```suggestion
        "qyear",
```
"qy" is not a valid field.

2024-10-10 18:06 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2024-10-10 18:06 UTC, closed without merging