Fix docstring
pandas-dev/pandas pull request #59719
Opened 2024-09-05 12:40 UTC by fbourgey

Issue #59698

Solved the following 
```python
"pandas.Timedelta.to_timedelta64 SA01"
"pandas.Timedelta.total_seconds SA01"
"pandas.Timedelta.view SA01"
```

2024-09-11 17:02 UTC, mroeschke commented
I think this PR can continue. I think the methods you're addressing are not resolved on main

2024-09-11 20:27 UTC, fbourgey commented
is there anything else I should do?

2024-09-12 21:10 UTC, mroeschke commented
Please view the failing CI checks. The logs should provide details of the error

2024-09-13 18:59 UTC, MarcoGorelli commented
yup - this is the test failure you should focus on:
```python

14m 4s
Prepare all required actions
Getting action download info
Download action repository 'actions/upload-artifact@v4' (SHA:50769540e7f4bd5e21e526ee35c689e35e0d6874)
Download action repository 'codecov/codecov-action@v4' (SHA:e28ff129e5465c2c0dcc6f003fc735cb6ae0c673)
Run ./.github/actions/run-tests
Run ci/run_tests.sh
PYTHONHASHSEED=2464250916
MESONPY_EDITABLE_VERBOSE=1 PYTHONDEVMODE=1 PYTHONWARNDEFAULTENCODING=1 pytest -r fE -n auto --dist=worksteal -s --cov=pandas --cov-report=xml --cov-append --cov-config=pyproject.toml pandas -m "not slow and not network and not clipboard and not single_cpu"
[1/1] Generating write_version_file with a custom command
+ /Users/runner/hostedtoolcache/Python/3.13.0-rc.2/arm64/bin/ninja
============================= test session starts ==============================
platform darwin -- Python 3.13.0rc2, pytest-8.3.3, pluggy-1.5.0
rootdir: /Users/runner/work/pandas/pandas
configfile: pyproject.toml
plugins: cov-5.0.0, hypothesis-6.112.1, xdist-3.6.1
created: 3/3 workers
3 workers [189517 items]

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/coverage/parser.py:409: DeprecationWarning: Bitwise inversion '~' on bool is deprecated and will be removed in Python 3.16. This returns the bitwise inversion of the underlying int object and is usually not what you expect from negating a bool. Use the 'not' operator for boolean negation or ~int(x) if you really want the bitwise inversion of the underlying int.
  self.code = compile(text, filename, "exec", dont_inherit=True)
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s..s.s...s.s.s.s..s..s..s..s............................................................................................................................s..........................................................................................................................x.....s.s.s.....x..............sssssssssss.sssss.ssssssss.sssssss.sssss.sssssssssssssssss.sssssssssssssssssssss.ssssssssssss.sssssssssssssssssssss.s.ssss...ssssss..sss.ss.s.sss.ss.sss.ss.sss.ssss.ssssss...s.s.s.s.s.ss.ss.ss.ss.sss.s.ss.s.sssss.sss.sssssssss.ss.sssssssssss.ss.sssssssss.sss.ss.s.ss.ssssssssssssssssssssssssssss.ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssxss.ss.sss.sss.s.sss..s.ss.ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.ssssssssxs.sss.sss.s..............................................................x..........x.................................................................................................................x.....................................................................................................................................................................................................................................x...................x............x.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................x...................................................................................................................................................................................x........................................................................................s................................................................................................................................................................................................................................................................................................................................................................................................s........................x.........x........x.....x...x...x.........x....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................x........x.........................................................................................x...........................................................x..................................................................x..............................................................................x.....x....x...x........x........................................................................................................................................................s.s...............................s.s.....................x........x.....x.....x......x................................................................x.............................x..x..xx..x......x...................................x...x...x...........x.........................x.........xx.x.....x...x............................x.........x..............................................................................................................................x......................x.......................................................ss.s.s..s.ss.s.ss.s.s..ss.s.s.ss..s.s.ss.s.ss..s..s..s.s..s.s.s..s.s..s..ss.s.s..s.ss..s.s.s.s..s..s.......................................................................x................................................x................x...........x................ss................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................x......................x.......................................................................s......s....s.....s.....s.....s...s....s...s...s....s.....s.....s....s.....................x..................x................x......................................x..................................x..............................................x............. [...]

2024-09-14 07:30 UTC, MarcoGorelli requested changes

2024-09-14 07:30 UTC, MarcoGorelli commented on pandas/tests/scalar/test_nat.py
>      if method == "to_numpy":
you should be modifying `total_seconds = ` in `nattype.pyx`, not skipping it 😉

2024-09-18 16:49 UTC, mroeschke approved these changes

2024-09-24 14:22 UTC, WillAyd commented
@MarcoGorelli need anything else on this PR?

2024-09-29 13:20 UTC, MarcoGorelli approved these changes
thanks @fbourgey - i think if you fetch and merge upstream/main then it should be good

2024-09-30 16:01 UTC, mroeschke approved these changes

2024-09-30 16:02 UTC, merged

2024-09-30 16:02 UTC, mroeschke commented
Thanks @fbourgey