BUG: read_json silently ignores the dtype when engine=pyarrow
pandas-dev/pandas pull request #59815
Opened 2024-09-16 05:57 UTC by jahn96

- [x] closes #59516  (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2024-09-17 03:45 UTC, yuanx749 requested changes

2024-09-17 03:45 UTC, yuanx749 commented on pandas/tests/io/json/test_pandas.py
> +
```suggestion

@td.skip_if_no("pyarrow")
```

2024-09-17 03:46 UTC, yuanx749 requested changes

2024-09-17 03:46 UTC, yuanx749 commented on pandas/tests/io/json/test_pandas.py
> +def test_read_json_pyarrow_dtype(datapath):
```suggestion
@td.skip_if_no("pyarrow")
def test_read_json_pyarrow_dtype(datapath):
```

2024-09-20 20:48 UTC, jahn96 commented on pandas/tests/io/json/test_pandas.py
> +def test_read_json_pyarrow_dtype(datapath):
Addressed [here](https://github.com/pandas-dev/pandas/pull/59815/commits/f78c8115b29b2213b48f220777db31c80c2a2ec0)

2024-10-29 20:40 UTC, closed without merging

2024-10-29 20:41 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.