DOC: Fix inconsistent and incomplete documentation of `pandas.eval`
pandas-dev/pandas pull request #59855
Opened 2024-09-21 00:07 UTC by JonathanMarriott

- [x] closes #58338
- [ ] ~~[Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature~~
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] ~~Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.~~
- [ ] ~~Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.~~

This PR implements the suggested documentation improvements outlined in #58338:
- Covering the supported operators and functions to `pandas.eval`
- Reorganising and adding links to  `pandas.DataFrame.eval` and  `pandas.DataFrame.query` to have a consistent explanation of the `expr` parameters

2024-09-23 05:42 UTC, yuanx749 requested changes

2024-09-23 05:42 UTC, yuanx749 commented on pandas/core/computation/eval.py
> +            and ``arctanh``
```suggestion
            ``arctan``, ``arctan2``, ``sinh``, ``cosh``, ``tanh``, ``arcsinh``, \
            ``arccosh`` and ``arctanh``
```
Nitpick: arctan2 is also supported.

2024-09-25 19:14 UTC, mroeschke approved these changes

2024-09-25 19:14 UTC, merged

2024-09-25 19:14 UTC, mroeschke commented
Thanks @JonathanMarriott