Improve error mesage verbosity
pandas-dev/pandas pull request #59900
Opened 2024-09-26 11:25 UTC by KevsterAmp

- [x] closes #59659  (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Continued stale PR: #59649

2024-10-18 08:23 UTC, KevsterAmp commented
@rhshadrach - could you take a look at this? thanks

2024-10-21 20:00 UTC, rhshadrach requested changes
Looking good - if this isn't currently hit by tests, they should be added.

2024-10-21 20:00 UTC, rhshadrach commented on pandas/core/strings/accessor.py
> +                f"Can only use .str accessor with string values!, not {inferred_dtype}"
Can you remove the `!`, I believe it is not grammatically correct.

2024-10-22 22:22 UTC, rhshadrach requested changes
Looks good! Can you update the test `test_str_attribute` in `tests/series/accessors/test_str_accessor.py`. Right now it is checking this case, but only checks part of the message. I think we can just update that to test the full message for this.

2024-10-24 21:02 UTC, rhshadrach commented
I think this looks good, but the CI has many unrelated failures. I'd like to get those resolved before merging PRs.

2024-10-27 13:34 UTC, rhshadrach commented
CI is fixed, can you merge main.

2024-10-28 05:42 UTC, KevsterAmp commented
@rhshadrach - CI looks good. Thanks

2024-10-28 21:04 UTC, rhshadrach approved these changes
lgtm

2024-10-28 21:05 UTC, merged