Bugfix : Added `mathjax_ignore` to HTMLFormatter._write_table and changed tests to assert `mathjax_ignore`
pandas-dev/pandas pull request #60043
Opened 2024-10-14 22:19 UTC by Maru5er

- [x] closes #59884 
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Feedback would be appreciated.

2024-10-15 06:09 UTC, attack68 approved these changes
LGTM - test cases covered

2024-10-22 21:50 UTC, rhshadrach commented
/preview

2024-10-22 21:52 UTC, rhshadrach commented
@datapythonista - the `/preview` feature seems broken, I get a 500 response from the server.

https://github.com/pandas-dev/pandas/actions/runs/11469095078/job/31915606006

Should I open an issue?

2024-10-22 21:56 UTC, rhshadrach requested changes

2024-10-22 21:56 UTC, rhshadrach commented on pandas/io/formats/style_render.py
> +                    'class="', 'class="tex2jax_ignore mathjax_ignore"'
This should be

    'class="', 'class="tex2jax_ignore mathjax_ignore '

as we are prepending to an already existing class.

2024-10-22 21:56 UTC, rhshadrach commented on pandas/io/formats/style_render.py
> +                table_attr += ' class="tex2jax_ignore mathjax_ignore"'
Similar here.

2024-10-22 21:56 UTC, rhshadrach commented on doc/source/whatsnew/v3.0.0.rst
> +- Bug in :meth:`set_option` where disabling pandas option display.html.use_mathjax has no effect (:issue:`59884`)
```suggestion
- Bug in :meth:`set_option` where setting the pandas option ``display.html.use_mathjax`` to ``False`` has no effect (:issue:`59884`)
```

2024-10-24 12:06 UTC, attack68 commented on pandas/io/formats/style_render.py
> +                table_attr += 'class="tex2jax_ignore mathjax_ignore"'
There is a reason for this space at the start.

2024-10-24 12:06 UTC, attack68 commented on pandas/io/formats/style_render.py
> +                table_attr += 'class="tex2jax_ignore mathjax_ignore"'
```suggestion
                table_attr += ' class="tex2jax_ignore mathjax_ignore"'
```

2024-11-06 21:47 UTC, KevsterAmp commented
This PR seems to have gone stale, can I take over this issue? Thanks

@rhshadrach @attack68

2024-11-07 21:36 UTC, rhshadrach commented
@KevsterAmp - sounds good.

2024-11-09 12:17 UTC, rhshadrach requested changes

2024-11-09 12:17 UTC, rhshadrach commented on pandas/io/formats/style_render.py
> +                    'class="', ' class="tex2jax_ignore mathjax_ignore '
```suggestion
                    'class="', 'class="tex2jax_ignore mathjax_ignore '
```

2024-11-11 12:01 UTC, KevsterAmp commented
@rhshadrach - Do I commit on this branch or I re-open a new PR? Thanks

2024-11-14 17:16 UTC, mroeschke commented
Thanks for this PR, but the issue was closed by https://github.com/pandas-dev/pandas/pull/60311

2024-11-14 17:16 UTC, closed without merging