Fix #59429 stacked bar label position
pandas-dev/pandas pull request #60211
Opened 2024-11-06 06:03 UTC by tev-dixon

- [x] closes #59429
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2024-11-06 14:01 UTC, rhshadrach requested changes
Thanks for the PR!

2024-11-06 14:01 UTC, rhshadrach commented on pandas/tests/plotting/frame/test_frame.py
> +        df = DataFrame({"A": [3, 0, 1], "B": [0, 2, 4], "C": [5, 0, 2]})
Can you start this test with a comment referencing the GH issue. E.g. see the test immediately below for an example.

2024-11-06 14:01 UTC, rhshadrach commented on doc/source/whatsnew/v2.3.0.rst
> +- Bug in :meth:`DataFrame.plot.bar` with ``stacked=True`` where labels on stacked bars with zero-height segments were incorrectly positioned at the base instead of the label position of the previous
This note should be move to v3.0.0.rst.

2024-11-06 14:02 UTC, rhshadrach commented on doc/source/whatsnew/v2.3.0.rst
> +- Bug in :meth:`DataFrame.plot.bar` with ``stacked=True`` where labels on stacked bars with zero-height segments were incorrectly positioned at the base instead of the label position of the previous
2.3.0 is a "special" release in that we are not doing it from the main branch. We are only backporting certain PRs to the 2.3.0 branch.

2024-11-06 23:34 UTC, tev-dixon commented
Thank you! I made the requested changes.
[x] removed the errant documentation from `doc/source/whatsnew/v2.3.0.rst`
[x] added documentation to `doc/source/whatsnew/v3.0.0.rst`
[x] added the github issue tracking number to the test in `pandas/tests/plotting/frame/test_frame.py`

2024-11-07 12:15 UTC, tev-dixon commented
I just want to add that my comment on the issue still stands: [comment](https://github.com/pandas-dev/pandas/issues/59429#issuecomment-2458796268)

By making this change, there is a side effect that will effectively bold some of the slice labels where multiple labels now overlap. I'm not sure if this is an intended behavior, and have assumed that it is. More details in my comment.

2024-11-07 21:32 UTC, rhshadrach approved these changes
lgtm

2024-11-07 21:32 UTC, merged

2024-11-07 21:33 UTC, rhshadrach commented
Thanks @tev-dixon!