DOC: Additions/updates documentation for df.interpolate() methods #60227
pandas-dev/pandas pull request #60247
Opened 2024-11-08 16:15 UTC by anishkarki

- [ ] closes #60227 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2024-11-09 13:47 UTC, anishkarki commented
@rhshadrach  Could you review this PR to improve documentation for df.interpolate() methods as part of issue #60227?”

2024-11-10 14:01 UTC, rhshadrach requested changes
Thanks for the PR! I see no difference between "actual numeric values" and "numeric values", so I think "actual" can be removed.

2024-11-10 14:01 UTC, rhshadrach commented on pandas/core/generic.py
> +              of the df's index to linearly calculate missing value.
```suggestion
            * 'index': The interpolation uses the numerical values
              of the DataFrame's index to linearly calculate missing values.
```

2024-11-10 14:01 UTC, rhshadrach commented on pandas/core/generic.py
> +              in the DataFrame, treating them as equally spaced along the index.
```suggestion
            * 'values': Interpolation based on the numerical values
              in the DataFrame, treating them as equally spaced along the index.
```

2024-11-11 13:19 UTC, anishkarki commented
@rhshadrach  I've made the requested changes to the documentation. Could you please review it again? Thanks!

2024-11-12 21:38 UTC, rhshadrach approved these changes
lgtm

2024-11-12 21:46 UTC, mroeschke approved these changes

2024-11-12 21:46 UTC, merged

2024-11-12 21:46 UTC, mroeschke commented
Thanks @anishkarki