ENH: Add table prefixes
pandas-dev/pandas pull request #60409
Opened 2024-11-24 20:45 UTC by Diadochokinetic

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2024-11-27 06:33 UTC, Diadochokinetic commented
I took a look into the ADBC implementation. `to_sql` uses `adbc_ingest`, which supports an (experimental) parameter `temporary`. I'll give it a shot. Although, this would only support the use case of temporary tables and not table prefixes in general. A more general solution could be to insert the prefixes into `table_name`. I will report, when I did some experimenting with it.

2024-11-27 15:19 UTC, Diadochokinetic commented
I did some testing and was able to implement the feature partially for `adbc` drivers. I used the `temporary` parameter of the `adbc_ingest` method. On the one hand, I don't like that it doesn't implement the full feature capacity of the paramater `prefixes` as its done in `sqlalchemy`, on the other hand it enables creating and appending temporary tables with the `to_sql` method for `sqlachemy` and `adbc` drivers, which is the main reason why I started working on this feature in the first place. Furthermore, I assume temporary tables will be like >99% of the use cases for `prefixes` anyway.

Now the question is:

- Should the paramater `prefixes` stay as proposed? Then the documentation needs to be expanded and explicitly state only `["TEMPORARY"]` will have an effect for `adbc` drivers. Maybe even throw a `NotImplementedError` for other values.
- Or reduce the parameter to a boolean `temporary` so it works exactly the same for both drivers, but loses functionality for `sqlalchemy`.

I personally prefer the first option, because I connect to `db2` databases via `sqlalchemy` and sometimes need to pass `prefixes=["GLOBAL", "TEMPORARY"]`.

2024-12-02 19:05 UTC, WillAyd commented
Can you check if there is an open issue for this upstream in the arrow-adbc repository? I think it may be of interest to them to handle more than just the temporary case.

ADBC releases are pretty quick, so if that is fixed upstream it benefits the entire ecosystem, and likely wouldn't be a long turnaround to get into pandas

2024-12-02 20:07 UTC, Diadochokinetic commented
That is a very good point. It wold be very beneficial, if both `sqlalchemy` and `adbc` support `prefixes`. So far, there is no open issue for that, so I opened one: https://github.com/sqlalchemy/sqlalchemy/issues/12149. Let's see what the `adbc` team thinks about this.

2024-12-14 10:55 UTC, Diadochokinetic commented
It looks like the `adbc` team is hesitant to implement an abstract parameter `prefixes` as it is available in `sqlalchemy`. So the option to wait for feature parity in both back ends seems to be unavailable. I prefer to implement `prefixes` in `to_sql()` to:

- have the full feature for `sqlalchemy` back-ends
- only use the `TEMPORARY` keyword for `adbc` back-ends and throw a `NotImplentedError` for other keywords

@WillAyd What are your thoughts on this?

2024-12-16 17:15 UTC, Diadochokinetic commented
And what about a reduced parameter `temporary`, that is supported by both back ends? That wouldn't solve all my use cases, but at least ~ 90% of it.

2025-01-22 04:37 UTC, Diadochokinetic commented
I'm still interested in working on this.

2025-01-27 16:55 UTC, Diadochokinetic commented
> And what about a reduced parameter `temporary`, that is supported by both back ends? That wouldn't solve all my use cases, but at least ~ 90% of it.

@WillAyd, what's your thought on this? Having a parameter `temporary`, that's supported by both back ends, would be a solution that solves 90% of prefix usage and does satisfy feature parity.

2025-01-28 19:21 UTC, WillAyd commented
I think that would be a reasonable solution across the implementations

2025-02-10 14:34 UTC, WillAyd requested changes

2025-02-10 14:34 UTC, WillAyd commented on pandas/io/sql.py
> +        except ProgrammingError:
Does sqlalchemy not provide a higher level abstraction than ProgrammingError or OperationalError? I'm not sure I understand the distinction between those, and I am not sure if they would catch all possible errors thrown by sqlalchemy either

2025-02-10 14:34 UTC, WillAyd commented on pandas/io/sql.py
> +        # sqlite doesn't allow a rollback at this point
Similar comment as before - we really want to avoid putting DBMS-specific logic into our implementation

2025-02-15 19:51 UTC, Diadochokinetic commented on pandas/io/sql.py
> +        except ProgrammingError:
The is a higher abstraction possible with `DatabaseError`.

2025-04-02 16:20 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2025-04-02 16:20 UTC, closed without merging