Fix KeyError by adding check for _convert_dates
pandas-dev/pandas pull request #60539
Opened 2024-12-11 13:33 UTC by Uvi-12

Closes #60536

This PR adds a check to prevent a KeyError when renaming columns by ensuring the original column name exists in the _convert_dates dictionary before updating it.

2024-12-18 20:32 UTC, Uvi-12 commented
@mroeschke Please review the PR, and let me know if everything looks good.

2024-12-27 14:47 UTC, rhshadrach requested changes
Thanks for the PR! Whenever changing behavior, please add tests.

2025-01-02 05:41 UTC, Uvi-12 commented
> Thanks for the PR! Whenever changing behavior, please add tests.

Thank you for the review. Please guide me on which test file would be the most appropriate for adding tests for this change.

2025-01-02 21:47 UTC, rhshadrach commented
`pandas/tests/io/test_stata.py`

2025-01-03 10:12 UTC, Uvi-12 commented
I have added the tests, please check if they are correct.

2025-01-09 20:40 UTC, rhshadrach requested changes
Thanks for the PR!

2025-01-09 20:40 UTC, rhshadrach commented on pandas/tests/io/test_stata.py
> +    assert writer._convert_dates == {"new_name": "converted_date"}
Can you instead test using the public API - provide a DataFrame with an name that will be changed, and a `convert_dates`, then call `read_stata` to check the result.

2025-01-09 20:40 UTC, rhshadrach commented on pandas/tests/io/test_stata.py
> +    temp_file = tmp_path / "test.dta"
Can you make the first line of test references the GitHub issue (or PR):

```python
def test_convert_dates_key_handling(tmp_path, version):
    # GH#60536
    temp_file = tmp_path / "test.dta"
```

2025-02-12 00:09 UTC, rhshadrach commented
Closing as stale. If you're interested in continuing, merge main and address the comments above and we'd be more than happy to reopen!

2025-02-12 00:09 UTC, closed without merging