DOC (string dtype): updated 'Working with text data' for str dtype in pandas 3.0
pandas-dev/pandas pull request #60535
Opened 2024-12-10 18:22 UTC by Uvi-12

Closes #60348 

This PR updates the "Working with Text Data" page in the pandas documentation to reflect the change in pandas 3.0 where "str" dtype is now the default.

2024-12-17 07:57 UTC, Uvi-12 commented
Hi @mroeschke, Please review the PR. I've made some updates to the 'text.rst' file which updated 'Working with text data' for str dtype in pandas 3.0

I noticed that after updating the branch, a commit for expressions.py was added, although I have made no commits in the file. Could you please help me understand the changes and guide me through?

2024-12-30 16:10 UTC, rhshadrach requested changes
Thanks for the PR! I think it'd be good to also link to the PDEP for history - perhaps at the top?

https://pandas.pydata.org/pdeps/0014-string-dtype.html

2024-12-30 16:10 UTC, rhshadrach commented on doc/source/user_guide/text.rst
> +3. ``str`` -dtype (default from pandas 3.0).
L14 needs to be updated. Also, should mention `string` here too I think.

2024-12-30 16:10 UTC, rhshadrach commented on doc/source/user_guide/text.rst
> +We recommend using the ``str`` dtype or :class:`StringDtype` to store text data.
Or `string`. Maybe reword to something like

    We recommend __not__ using ``object`` dtype to store text data.

2024-12-30 16:10 UTC, rhshadrach commented on doc/source/user_guide/text.rst
> +additional flexibility for missing values while maintaining compatibility with pandas' nullable types.
``str`` also handles NA values, the difference between `np.NaN` vs `pd.NA`. I think it'd be good to clarify that here.

2024-12-30 16:10 UTC, rhshadrach commented on doc/source/user_guide/text.rst
> +These are places where the behavior of ``StringDtype`` or ``str`` objects differ from
Needs a mention of `string` too.

2024-12-30 16:10 UTC, rhshadrach commented on doc/source/user_guide/text.rst
> +   in comparison operations, rather than always comparing unequal like :attr:`numpy.nan`.
I don't think this is true for `str`.

2024-12-30 16:10 UTC, rhshadrach commented on doc/source/user_guide/text.rst
> +    The type of the Series is inferred as ``str`` or ``string`` depending on the context.
In what context do we infer ``string``?

2024-12-30 16:10 UTC, rhshadrach commented on doc/source/user_guide/text.rst
> +The parameter ``others`` can also be two-dimensional. In this case, the number or rows must match the length of the calling ``Series`` (or ``Index``).
`the number or rows` should be `of` instead

2024-12-30 16:10 UTC, rhshadrach commented on pandas/core/computation/expressions.py
> +    )
This unintentional change was due to merging main, can you revert.

2025-01-01 08:00 UTC, Uvi-12 commented on doc/source/user_guide/text.rst
> +    The type of the Series is inferred as ``str`` or ``string`` depending on the context.
The `string` dtype is inferred when the data includes `pd.NA` or other nullable types, ensuring compatibility with pandas' nullable ecosystem. It is also inferred when explicitly specified by the user with `dtype="string"`. Otherwise, `str` is typically inferred for text data. Please correct me if I am wrong.

2025-01-01 08:10 UTC, Uvi-12 commented
I have made changes according to the review, but somehow I can't revert the changes in expressions.py. Can you please help me with it?

2025-01-01 13:05 UTC, rhshadrach commented
> I have made changes according to the review, but somehow I can't revert the changes in expressions.py. Can you please help me with it?

You can open the file with an editor and manually modify the file undoing the changes. Locally, you can run

    git diff upstream/main pandas/core/computation/expressions.py

and keep making modifications until that reports no differences.

2025-01-01 13:15 UTC, Uvi-12 commented
> If you'd like, I can push a commit undoing the changes there.

It would be very helpful, Thank you.

I have made the changes as per the review, please let me know if there are any other modifications required in the documentation.

2025-01-01 16:59 UTC, rhshadrach commented on doc/source/user_guide/text.rst
> +    The type of the Series is inferred as ``str`` or ``string`` depending on the context.
> The `string` dtype is inferred when the data includes `pd.NA` or other nullable types, ensuring compatibility with pandas' nullable ecosystem.

pandas will not infer `string` here. This is consistent with other nullable dtypes.

```python
pd.set_option("future.infer_string", True)

ser = pd.Series(["a", pd.NA, "c"])
print(ser.dtype)
# str

ser = pd.Series([1, pd.NA, 3])
print(ser.dtype)
# object
```

> It is also inferred when explicitly specified by the user with `dtype="string"`.

This is not inference - inference, by definition, is the behavior when it is not explicitly specified.

2025-01-01 17:09 UTC, Uvi-12 commented on doc/source/user_guide/text.rst
> +    The type of the Series is inferred as ``str`` or ``string`` depending on the context.
Thank you for the clarification, I will change it back to the original. Are there any other modifications required?

2025-01-09 13:00 UTC, Uvi-12 commented
@rhshadrach, is everything alright, or are modifications needed?

2025-01-09 20:59 UTC, rhshadrach requested changes
There are several mentions of `` `pd.StringDtype` or `str` `` as if these are distinct entities. As mentioned below, they are not. I think we should make it clear that `str` is an alias, and just mention `pd.StringDtype` from there on. But open to other approaches too.

2025-01-09 20:59 UTC, rhshadrach commented on doc/source/user_guide/text.rst
> +3. ``str`` -dtype (default from pandas 3.0).
The way this is written, it sounds like `str` is entirely separate from `StringDtype`, but that isn't the case.

```python
pd.set_option("future.infer_string", True)
ser1 = pd.Series(list("xyz"), dtype="str")
ser2 = pd.Series(list("xyz"), dtype=pd.StringDtype("pyarrow", np.nan))
print(ser1.dtype == ser2.dtype)
# True
```

Maybe just mention that `"str"`, when `future.infer_string` is set to True, is an alias for `pd.StringDtype("pyarrow", np.nan))` or `pd.StringDtype("python", np.nan))` depending on whether `pyarrow` is installed.

2025-01-09 20:59 UTC, rhshadrach commented on doc/source/user_guide/text.rst
> +Note that ``StringDtype`` uses ``pd.NA`` for missing values, whereas ``str`` dtype uses ``np.NaN``. ``StringDtype``
This is incorrect, since `StringDtype` accepts an `na_value` argument to choose between `pd.NA` and `np.nan`. `np.NaN` has been removed as of NumPy 2.0, so shouldn't be used.

2025-01-09 20:59 UTC, rhshadrach commented on doc/source/user_guide/text.rst
>     pd.Series(["a", "b", "c"], dtype=pd.StringDtype())
I think this should also show passing arguments to StringDtype.

2025-01-09 20:59 UTC, rhshadrach commented on doc/source/user_guide/text.rst
> +These are places where the behavior of ``StringDtype`` or ``str`` objects differ from
Actually - can just leave this as ``StringDtype`` - no need to mention the aliases.

2025-01-09 20:59 UTC, rhshadrach commented on doc/source/user_guide/text.rst
> +    The type of the Series is inferred as ``str`` or ``string`` depending on the context.
I think:

> When the option ``future.infer_string`` is set to True, the type of the Series is inferred as ``str``.

2025-03-24 16:47 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2025-03-24 16:47 UTC, closed without merging