ENH: removed median percentile to be always included in describe GH #60550
pandas-dev/pandas pull request #60557
Opened 2024-12-13 06:51 UTC by ZenithClown

- [ ] closes #60550 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

2024-12-13 19:05 UTC, mroeschke commented on pandas/core/methods/describe.py
> +        percentiles.append(0.5)
Could you skip the validation below if we hit this branch?

2024-12-13 19:05 UTC, mroeschke reviewed
Thanks could you add a test for this?

2024-12-14 10:34 UTC, ZenithClown commented
@mroeschke I don't think a separate test is needed as the core functionality remains the same.

2024-12-15 21:07 UTC, rhshadrach commented
> @mroeschke I don't think a separate test is needed as the core functionality remains the same.

We should have had a test that when you specify `[0.3, 0.6]` you get `0.3`, `0.5`, and `0.6`. This was missing in our test coverage. If it was there, then you would have had to modify such a test to just `0.3` and `0.6`. 

Since we're changing the behavior, I think a test needs to be added.

2024-12-18 05:36 UTC, ZenithClown commented
@mroeschke @rhshadrach thank you for your suggestions, this is now implemented.

2024-12-18 09:52 UTC, ZenithClown commented
@mroeschke @rhshadrach thanks for the feedback, the tests are now added.

2024-12-23 19:26 UTC, ZenithClown commented
@mroeschke, I hope you were able to look into this and merge the PR?

2024-12-23 23:11 UTC, asishm commented on pandas/core/methods/describe.py
> +        75th percentiles.If a blank list is passed, then returns only the
```suggestion
        75th percentiles. If a blank list is passed, then returns only the
```

2025-01-03 08:49 UTC, ZenithClown commented
@mroeschke please do the needful.

2025-01-03 18:49 UTC, mroeschke commented on pandas/tests/reductions/test_describe_ndframe.py
> +def test_refine_percentiles(percentiles_, expected):
Could you add a test in `pandas/tests/frame/methods/test_describe.py` instead? It should also test the `describe` method directly as mentioned in the original issue

2025-01-11 11:45 UTC, rhshadrach requested changes

2025-01-11 11:45 UTC, rhshadrach commented on doc/source/whatsnew/v2.3.0.rst
> +  list is passed (:issue:`60550`).
Can you move this to `v3.0.0.rst`. We should not do this breaking change in 2.3.

2025-01-11 11:45 UTC, rhshadrach commented on pandas/core/generic.py
> +            only the 50th percentile value.
I do not think this should be the behavior. If I pass an empty list, I should not get any percentiles.

2025-01-11 19:02 UTC, asishm commented on pandas/core/generic.py
> +            only the 50th percentile value.
I don't think we should remove the 50th percentile without at least a deprecation warning. Reporting the median by default is incredibly helpful.

2025-01-12 14:00 UTC, rhshadrach commented on pandas/core/generic.py
> +            only the 50th percentile value.
Agreed we should not be changing the default behavior. Recommend setting `no_default` as the default value and maintaining the default behavior when it is not changed.

2025-01-13 17:24 UTC, ZenithClown commented on pandas/core/generic.py
> +            only the 50th percentile value.
Okay, so we will add an argument `no_default : bool = False` as the argument and preserve the behavior with control.

2025-01-13 17:58 UTC, asishm commented on pandas/core/generic.py
> +            only the 50th percentile value.
@rhshadrach I got confused. the default for percentiles is already `None`. not sure if it's worth changing to `lib.no_default`.

@ZenithClown I believe what @rhshadrach means is to change the behavior so that the 50th percentile is removed if a user explicitly passes in `percentiles=[]` instead of the default `None` (or the suggestion to change to `no_default`)

2025-01-13 20:57 UTC, rhshadrach commented on pandas/core/generic.py
> +            only the 50th percentile value.
@asishm - me too! Agreed leaving the default as `None` is fine.

2025-02-19 21:27 UTC, rhshadrach commented
Closing as stale. If you're interesting in continuing, merge main and fix up the failing tests on the CI and we'd be more than happy to reopen!

2025-02-19 21:27 UTC, closed without merging