BUG: value_counts() check Index with PyArrow categorical columns
pandas-dev/pandas pull request #60569
Opened 2024-12-14 23:05 UTC by NOBODIDI

- [x] closes #60563
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests)
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

This is my first issue, thank you in advance for your patience and feedback!

2024-12-27 14:27 UTC, rhshadrach requested changes
Thanks for the PR! Will need to add tests using the `value_counts` method too. The CI appears to be failing, I'd recommend merging main and see if it's still failing.

2024-12-27 14:27 UTC, rhshadrach commented on pandas/core/arrays/categorical.py
> +                if values.__class__.__name__ == 'Index':
Use `isinstance` instead of checking the name.

2024-12-27 14:27 UTC, rhshadrach commented on pandas/tests/arrays/categorical/test_dtypes.py
> +        assert arr.equals(values._data._pa_array.combine_chunks())
What is this testing?

2025-01-27 18:20 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2025-01-27 18:20 UTC, closed without merging