TST: Make test_sql.py parallelizable
pandas-dev/pandas pull request #60595
Opened 2024-12-20 19:51 UTC by UmbertoFasci

- [x] closes #60378 
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

Description:

Generated individual uuids for individual hardcoded table name instances throughout the test cases as per the original feature description. Handling the test cases for connections with a shared database state as those which leverage the iris, or type table defined and created in fixtures requires more refactoring if needed to make parallelizable.

On that same note, the parallel safety of these particular connections should be further tested to see if they do require unique table names.

2024-12-20 19:54 UTC, AdLThinhRose reviewed
???

2024-12-20 20:16 UTC, WillAyd requested changes

2024-12-20 20:16 UTC, WillAyd commented on pandas/tests/io/test_sql.py
>  ]
Can you remove the pytest marker on L63 that makes this run on a single CPU? That will be the true test if this is working or not

2024-12-20 20:16 UTC, WillAyd commented on pandas/tests/io/test_sql.py
> +def table_uuid_gen(prefix: str) -> str:
```suggestion
def create_unique_table_name(prefix: str) -> str:
```

2024-12-20 20:16 UTC, WillAyd commented on pandas/tests/io/test_sql.py
> +    """Generate a unique table name with context prefix."""
You can remove this docstring - it doesn't add much value and we don't use docstrings in the test suite

2024-12-21 00:02 UTC, UmbertoFasci commented
@WillAyd There seems to be a race condition due to the way the drop_table function is currently set up. In other words, when running the tests in parallel, the cleanup operations can fail because one test process might try to check a table's structure right after another process has already deleted that table.

I am thinking this can be handled by simply catching the error that is raised if the table has already been dropped.

2024-12-21 18:49 UTC, mroeschke commented
With this change, each test should truly create and drop a unique table. There may be some routines that need to adapt to this (either drop being called more consistently or tables names being pass through from the create to the drop process)

2024-12-21 18:54 UTC, AdLThinhRose commented
Vậy nếu như ví dụ thì nhất quán theo 1 các thức thế nào. Khi không thể đưa
ra dẫn chứng cụ thể hơn. ( đây xem như góp ý đi). Có lẽ sau 2 h nó lại xãy
ra 1 lỗi x2. Hoạc giờ này tôi đang ghim map ngoài thái bình dương thêm 1
lần nữa

Vào CN, 22 thg 12, 2024 lúc 01:50 Matthew Roeschke ***@***.***>
đã viết:

> With this change, each test should truly create and drop a unique table.
> There may be some routines that need to adapt to this (either drop being
> called more consistently or tables names being pass through from the create
> to the drop process)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pandas-dev/pandas/pull/60595#issuecomment-2558202740>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKUN6KFCCON3ISH4EME37TT2GWZ55AVCNFSM6AAAAABT7XW7QKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNJYGIYDENZUGA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-12-27 15:59 UTC, WillAyd commented
Yea sorry @UmbertoFasci I suppose this is a little more complicated than I originally envisioned. You might be able to have the individual fixtures generate both a connection and a table name instead of just a connection. That way the filter can just drop the table name at the end of the fixture, if it exists.

There might be some nuance with views but I'd start with tables first and see how far you get

2025-04-02 16:20 UTC, mroeschke commented
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

2025-04-02 16:20 UTC, closed without merging