DOC: Adding a Persian version of Pandas Cheat Sheet
pandas-dev/pandas pull request #60612
Opened 2024-12-27 22:11 UTC by HasssanRad

I have translated the Pandas cheat sheet for the Persian-speaking community around the world, and it is ready to be added to the Pandas project documentation.

2024-12-30 16:08 UTC, Dr-Irv approved these changes
I'm going to trust here that what you wrote is correct.  Thanks @HasssanRad for the contribution.

2024-12-30 16:10 UTC, Dr-Irv requested changes
Actually, I just realized that you should update https://github.com/pandas-dev/pandas/blob/main/doc/cheatsheet/README.md as well.   Can you include that?

2024-12-31 06:00 UTC, HasssanRad commented
> Actually, I just realized that you should update https://github.com/pandas-dev/pandas/blob/main/doc/cheatsheet/README.md as well. Can you include that?

No problem, I'll do it.

2025-01-01 11:58 UTC, HasssanRad commented
@Dr-Irv I added the Pandas_Cheat_Sheet_FA to the README.md as per your request.

2025-01-02 14:42 UTC, Dr-Irv requested changes

2025-01-02 14:42 UTC, Dr-Irv commented on doc/cheatsheet/README.md
> +| Pandas_Cheat_Sheet_FA  | <a href="https://github.com/pandas-dev/pandas/blob/main/doc/cheatsheet/Pandas_Cheat_Sheet_FA.pdf" target="_parent"><img src="https://img.shields.io/badge/Open in PDF-%23FF0
Now that I see this, I'm not sure how many people will know that "FA" means "Persian", so can you add another column to this table (make it the second column after the file name) that indicates "Language" with values "English', "Japanese" and "Persian" ?

2025-01-02 16:53 UTC, HasssanRad commented on doc/cheatsheet/README.md
> +| Pandas_Cheat_Sheet_FA  | <a href="https://github.com/pandas-dev/pandas/blob/main/doc/cheatsheet/Pandas_Cheat_Sheet_FA.pdf" target="_parent"><img src="https://img.shields.io/badge/Open in PDF-%23FF0
I will add it.

2025-01-02 17:39 UTC, Dr-Irv approved these changes
Thanks @HasssanRad

2025-01-02 17:40 UTC, merged